WIP Add French configure-pod-configmap
kubernetes/website pull request #18962
Opened 2020-02-03 15:28 UTC by remyleone

2020-09-28 11:34 UTC, remyleone commented
/remove-lifecycle stale

2021-01-06 13:48 UTC, remyleone commented
/remove-lifecycle stale

2021-04-10 15:24 UTC, remyleone commented
/remove-lifecycle stale

2021-04-10 18:31 UTC, rekcah78 requested changes

2021-04-10 18:31 UTC, rekcah78 commented on content/fr/docs/tasks/configure-pod-container/configure-pod-configmap.md
> +   {{< codenew file="pods/pod-single-configmap-env-variable.yaml" >}}
the path is specific to the localization, you must copy the file to the fr branch,
/opt/build/repo/content/fr/examples/pods/pod-single-configmap-env-variable.yaml: no such file or directory

2021-04-10 18:31 UTC, rekcah78 commented on content/fr/docs/tasks/configure-pod-container/configure-pod-configmap.md
> +You can project keys to specific paths and specific permissions on a per-file basis.
not translated

2021-04-11 09:15 UTC, rekcah78 commented
@remyleone https://deploy-preview-18962--kubernetes-io-master-staging.netlify.app/fr/docs/tasks/configure-pod-container/configure-pod-configmap/
seems to have a rendering problem

2021-04-11 10:32 UTC, remyleone commented
@rekcah78 capture are not used anymore, therefore I needed to remove them :)

2021-04-11 11:07 UTC, rekcah78 requested changes

2021-04-11 11:07 UTC, rekcah78 commented on content/fr/docs/tasks/configure-pod-container/configure-pod-configmap.md
> +title: Configure a Pod to Use a ConfigMap
not translated

2021-04-13 09:26 UTC, AWKIF requested changes

2021-04-13 09:26 UTC, AWKIF commented on content/fr/docs/tasks/configure-pod-container/configure-pod-configmap.md
> +Par exemple, si vous créez un [volume Kubernetes] (/docs/concepts/storage/volumes/) à partir d'une ConfigMap, chaque élément de données de la ConfigMap est représenté par un fichier individuel dans l
remove space
[volume Kubernetes] (/docs/concepts/storage/volumes/)

2021-04-23 13:31 UTC, remyleone commented on content/fr/docs/tasks/configure-pod-container/configure-pod-configmap.md
> +title: Configure a Pod to Use a ConfigMap
Fixed :)

2021-04-26 07:38 UTC, AWKIF commented
/lgtm

2021-04-29 14:51 UTC, AWKIF commented
/approve

2021-04-29 14:52 UTC, merged