Translate docs/concepts/containers/images into Japanese
kubernetes/website pull request #23088
Opened 2020-08-12 03:01 UTC by takaf04

Closes #22905

2020-08-12 03:05 UTC, takaf04 commented
/assign @inductor

2020-08-12 03:37 UTC, inductor commented on content/ja/docs/concepts/containers/images.md
> +このページではコンテナイメージのコンセプト概要を説明します。
コンセプト概要、腹痛が痛いみたな感じに聞こえますね

2020-08-12 03:39 UTC, inductor commented
1. `<li>`などの箇条書き（markdownだと`-`や`1.`など）の場合は不要であれば文末の。は付けない（原文でも.がないです）
2. 通例だと箇条書きの中は「だ・である調」になってるかと思いますので、合わせていただけますと！

2020-08-12 08:13 UTC, takaf04 commented
@inductor 
リストの表現も箇条書きにし、文末の「。」を削除しました。

リスト表現部分でも２つの文章で構成されている部分については、最初の文の。は残してました。
文章の区切れがわかるように残してます。以下が例です。

`1. クラスターに独自仕様でない(例えば、オープンソース)イメージだけを実行する。イメージを非公開にする必要がない`

2020-08-23 17:56 UTC, kakts commented
L37までみました

2020-08-24 11:24 UTC, takaf04 commented on content/ja/docs/concepts/containers/images.md
> +プライベートリポジトリではイメージを読み込む為にキーが必要になる場合があります。
凡ミスでした。直します。

2020-08-24 11:26 UTC, takaf04 commented on content/ja/docs/concepts/containers/images.md
> +   - [AlwaysPullImagesアドミッションコントローラー](/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages)が有効化かを確認する必要あり。さもないと、全部のPodがすべてのイメージへのアクセスができてしまう可能性がある
直します。

2020-08-24 11:27 UTC, takaf04 commented on content/ja/docs/concepts/containers/images.md
> +   - 機密のデータはイメージに含めてしまうのではなく、"Secret"リソースに移行する
「の」不要ですね。

2020-08-24 13:33 UTC, takaf04 commented
レジストリの訳ミスが他にもあったので全部修正し、
もう一度全体をみて、言葉のおかしい部分を再チェックしました。

箇条書きの「です・ます調」、「である調」の件は、どうしましょうか？
個人的には「である調のほう」がスッキリ見えるとは思います。

2020-08-24 13:34 UTC, inductor commented
箇条書きはだ・である調派です。

2020-08-24 15:04 UTC, kakts requested changes

2020-08-24 15:04 UTC, kakts commented on content/ja/docs/concepts/containers/images.md
> +## マニュフェストを使ったマルチアーキテクチャイメージ
```suggestion
## マニフェストを使ったマルチアーキテクチャイメージ
```

2020-08-24 15:04 UTC, kakts commented on content/ja/docs/concepts/containers/images.md
> +コンテナレジストリはバイナリイメージの提供だけでなく、[コンテナイメージマニュフェスト](https://github.com/opencontainers/image-spec/blob/master/manifest.md)も提供する事ができます。
```suggestion
コンテナレジストリはバイナリイメージの提供だけでなく、[コンテナイメージマニフェスト](https://github.com/opencontainers/image-spec/blob/master/manifest.md)も提供する事ができます。
```

2020-08-24 15:04 UTC, kakts commented on content/ja/docs/concepts/containers/images.md
> +マニュフェストはコンテナのアーキテクチャ固有バージョンに関するイメージマニュフェストを参照できます。マニュフェストの目的はイメージの名前(例:`pause`、`example/mycontainer`、`kube-apiserver`)をもたせ、様々なシステムが使用しているマシンアーキテクチャにあう適切なバイナリイメージを取得できることです。
```suggestion
マニフェストはコンテナのアーキテクチャ固有バージョンに関するイメージマニフェストを参照できます。マニフェストの目的はイメージの名前(例:`pause`、`example/mycontainer`、`kube-apiserver`)をもたせ、様々なシステムが使用しているマシンアーキテクチャにあう適切なバイナリイメージを取得できることです。
```

2020-08-24 15:04 UTC, kakts commented on content/ja/docs/concepts/containers/images.md
> +Kubernetes自身は、通常コンテナイメージに`-$(ARCH)`のサフィックスを持つを名前をつけます。下位互換の為にサフィックス付きの古い仕様のイメージを生成してください。その目的は、`pause`のようなすべてのアーキテクチャのマニュフェストを持つイメージと、サフィックスのあるイメージをハードコードしていた可能性のある古い仕様の設定やYAMLファイルと下位互換がある`pause-amd6
```suggestion
Kubernetes自身は、通常コンテナイメージに`-$(ARCH)`のサフィックスを持つを名前をつけます。下位互換の為にサフィックス付きの古い仕様のイメージを生成してください。その目的は、`pause`のようなすべてのアーキテクチャのマニフェストを持つイメージと、サフィックスのあるイメージをハードコードしていた可能性のある古い仕様の設定やYAMLファイルと下位互換がある`pause-amd64`のようなイメージを生成することです。
```

翻訳ありがとうございます！

manifest
マニュフェスト　➡️　マニフェスト　が良いかと思います！

他の翻訳でもマニフェスト表記になっております。
https://github.com/kubernetes/website/pull/21455/files

2020-08-24 15:10 UTC, kakts requested changes

2020-08-24 15:10 UTC, kakts commented on content/ja/docs/concepts/containers/images.md
> +Kubernetes自身は、通常コンテナイメージに`-$(ARCH)`のサフィックスを持つを名前をつけます。下位互換の為にサフィックス付きの古い仕様のイメージを生成してください。その目的は、`pause`のようなすべてのアーキテクチャのマニュフェストを持つイメージと、サフィックスのあるイメージをハードコードしていた可能性のある古い仕様の設定やYAMLファイルと下位互換がある`pause-amd6
```suggestion
Kubernetes自身は、通常コンテナイメージに`-$(ARCH)`のサフィックスを持つ名前をつけます。下位互換の為にサフィックス付きの古い仕様のイメージを生成してください。その目的は、`pause`のようなすべてのアーキテクチャのマニフェストを持つイメージと、サフィックスのあるイメージをハードコードしていた可能性のある古い仕様の設定やYAMLファイルと下位互換がある`pause-amd64`のようなイメージを生成することです。
```

2020-08-24 15:10 UTC, kakts commented on content/ja/docs/concepts/containers/images.md
> +Kubernetes自身は、通常コンテナイメージに`-$(ARCH)`のサフィックスを持つを名前をつけます。下位互換の為にサフィックス付きの古い仕様のイメージを生成してください。その目的は、`pause`のようなすべてのアーキテクチャのマニュフェストを持つイメージと、サフィックスのあるイメージをハードコードしていた可能性のある古い仕様の設定やYAMLファイルと下位互換がある`pause-amd6
manifest
マニュフェスト　➡️　マニフェスト　が良いかと思います！

他の翻訳でもマニフェスト表記になっております。
https://github.com/kubernetes/website/pull/21455/files

2020-08-24 15:53 UTC, kakts commented
一通り見てコメント書きました！

2020-08-25 12:20 UTC, takaf04 commented on content/ja/docs/concepts/containers/images.md
> +Kubernetes自身は、通常コンテナイメージに`-$(ARCH)`のサフィックスを持つを名前をつけます。下位互換の為にサフィックス付きの古い仕様のイメージを生成してください。その目的は、`pause`のようなすべてのアーキテクチャのマニュフェストを持つイメージと、サフィックスのあるイメージをハードコードしていた可能性のある古い仕様の設定やYAMLファイルと下位互換がある`pause-amd6
レビューありがとうございます。
マニフェストに統一しました。

2020-08-25 12:22 UTC, takaf04 commented
レビューの結果を反映し、マニフェストに統一しました。

2020-08-25 17:16 UTC, kakts commented
修正ありがとうございます。

/lgtm

2020-09-17 19:23 UTC, inductor commented
/approve

2020-09-17 19:24 UTC, merged