Translate contribute/style/content-guide into Japanese
kubernetes/website pull request #23215
Opened 2020-08-17 22:24 UTC by shuuji3

Closes #23214.

2020-08-17 22:53 UTC, shuuji3 commented
/assign @inductor

Page preview: https://deploy-preview-23215--kubernetes-io-master-staging.netlify.app/ja/docs/contribute/style/content-guide/

2020-08-17 23:23 UTC, bells17 commented
/lgtm

2020-08-19 12:55 UTC, oke-py requested changes

2020-08-19 12:55 UTC, oke-py commented on content/ja/docs/contribute/style/content-guide.md
> +-  コンテンツがkubernetes.ioの正規のコンテンツであるか、他の場所の正規のコンテンツへのリンクである場合
```suggestion
- コンテンツがkubernetes.ioの正規のコンテンツであるか、他の場所の正規のコンテンツへのリンクである場合
```

2020-08-19 12:55 UTC, oke-py commented on content/ja/docs/contribute/style/content-guide.md
> +Kubernetesのドキュメントには、Kubernetesプロジェクト（[kubernetes](https://github.com/kubernetes)および[kubernetes-sigs](https://github.com/kubernetes-sigs) GitHub organizationsに存在するプロジェクト）の適用例が含まれています。
```suggestion
Kubernetesのドキュメントには、Kubernetesプロジェクト([kubernetes](https://github.com/kubernetes)および[kubernetes-sigs](https://github.com/kubernetes-sigs) GitHub organizationsに存在するプロジェクト)の適用例が含まれています。
```
括弧は半角にするルールですが、入れ子になっても大丈夫ですかね？

2020-08-19 13:42 UTC, shuuji3 commented on content/ja/docs/contribute/style/content-guide.md
> +Kubernetesのドキュメントには、Kubernetesプロジェクト（[kubernetes](https://github.com/kubernetes)および[kubernetes-sigs](https://github.com/kubernetes-sigs) GitHub organizationsに存在するプロジェクト）の適用例が含まれています。
おそらくこれは私の変換ミスですね。

半角に直してからプレビューで確認しましたが、問題なく表示されていました。

2020-09-17 17:15 UTC, bells17 commented
修正していただいたのであらためて
/lgtm

2020-09-17 19:18 UTC, inductor commented
/approve

2020-09-17 19:22 UTC, merged