Translate concepts/services-networking/network-policies into Japanese
kubernetes/website pull request #23235
Opened 2020-08-19 05:16 UTC by shuuji3

Closes #22988.

2020-08-19 05:16 UTC, shuuji3 commented
/assign @inductor

2020-08-19 05:31 UTC, shuuji3 commented
Page preview: https://deploy-preview-23235--kubernetes-io-master-staging.netlify.app/ja/docs/concepts/services-networking/network-policies/

2020-08-19 11:59 UTC, bells17 reviewed
すごい細かいですが1点だけコメントしました

2020-08-19 11:59 UTC, bells17 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +1. "default"名前空間内にある"role=db"のPodを、内向きと外向きのトラフィックに対して分離する(すでに分離されていなければ)
`すでに~` だとその後に文章が続く感じがするので(個人的な印象)、表現変えてみてもいいかもです

```suggestion
1. "default"名前空間内にある"role=db"のPodを、内向きと外向きのトラフィックに対して分離する(まだ分離されていなければ)
```

2020-08-19 13:29 UTC, shuuji3 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +1. "default"名前空間内にある"role=db"のPodを、内向きと外向きのトラフィックに対して分離する(すでに分離されていなければ)
@bells17 ありがとうございます。自分ではうまく説明できませんが、「まだ」の方がしっくり来る気がしますね。

さらに「(まだ分離されていない場合)」とするのはどうでしょうか？

2020-08-19 13:30 UTC, bells17 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +1. "default"名前空間内にある"role=db"のPodを、内向きと外向きのトラフィックに対して分離する(すでに分離されていなければ)
はい、良い気がします

2020-08-19 13:37 UTC, shuuji3 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +1. "default"名前空間内にある"role=db"のPodを、内向きと外向きのトラフィックに対して分離する(すでに分離されていなければ)
こちら、修正しました。

2020-09-06 08:07 UTC, oke-py requested changes

2020-09-10 14:07 UTC, shuuji3 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +Podを選択するNetworkPolicyが存在すると、Podは分離されるようになります。名前空間内に特定のPodを選択するNetworkPolicyが1つでも存在すると、そのPodはいずれかのNetworkPolicyで許可されていないすべての接続を拒否するようになります。
すみません、PRの段階でコミットに含まれているので、おそらく漏れだと思います。追加で翻訳しました。

2020-09-10 14:07 UTC, shuuji3 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +ネットワークポリシーは追加式であるため、競合することはありません。複数のポリシーがPodを選択する場合、そのPodに許可されるトラフィックは、それらのポリシーのingress/egressルールの和集合で制限されます。
こちらも同様に翻訳忘れのようです。

2020-09-10 14:08 UTC, shuuji3 commented
ご指摘いただいた点を反映しました。

2020-09-10 14:55 UTC, inductor commented on content/ja/docs/concepts/services-networking/network-policies.md
> +Podを選択するNetworkPolicyが存在すると、Podは分離されるようになります。名前空間内に特定のPodを選択するNetworkPolicyが1つでも存在すると、そのPodはいずれかのNetworkPolicyで許可されていないすべての接続を拒否するようになります。(名前空間内でもどのNetworkPolicyにも選択されなかった他のPodは、引き続きすべてのトラフィックを許可します。
>名前空間内でもどのNetworkPolicyにも

日本語が読みにくい感じになってしまっているのでいい感じにしたい

2020-09-10 15:21 UTC, shuuji3 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +Podを選択するNetworkPolicyが存在すると、Podは分離されるようになります。名前空間内に特定のPodを選択するNetworkPolicyが1つでも存在すると、そのPodはいずれかのNetworkPolicyで許可されていないすべての接続を拒否するようになります。(名前空間内でもどのNetworkPolicyにも選択されなかった他のPodは、引き続きすべてのトラフィックを許可します。
たしかに読みにくいですね…。

少し変更して「同じ名前空間内のPodでも、どのNetworkPolicyにも選択されなかった他のPodは、引き続きすべてのトラフィックを許可します。」というのはいかがでしょうか？

2020-09-17 19:40 UTC, inductor commented on content/ja/docs/concepts/services-networking/network-policies.md
> +Podを選択するNetworkPolicyが存在すると、Podは分離されるようになります。名前空間内に特定のPodを選択するNetworkPolicyが1つでも存在すると、そのPodはいずれかのNetworkPolicyで許可されていないすべての接続を拒否するようになります。(名前空間内でもどのNetworkPolicyにも選択されなかった他のPodは、引き続きすべてのトラフィックを許可します。
@shuuji3  よさそうです！

2020-09-17 22:27 UTC, shuuji3 commented on content/ja/docs/concepts/services-networking/network-policies.md
> +Podを選択するNetworkPolicyが存在すると、Podは分離されるようになります。名前空間内に特定のPodを選択するNetworkPolicyが1つでも存在すると、そのPodはいずれかのNetworkPolicyで許可されていないすべての接続を拒否するようになります。(名前空間内でもどのNetworkPolicyにも選択されなかった他のPodは、引き続きすべてのトラフィックを許可します。
こちらの翻訳でアップデートしました！

2020-09-24 10:17 UTC, bells17 commented
こちら僕はLGTMです
(翻訳漏れに気づいておらずすみません)

2020-11-05 14:31 UTC, bells17 commented
/lgtm

2020-11-05 14:43 UTC, inductor commented
/approve

2020-11-05 14:45 UTC, merged