Update Japanese localization on concepts/containers/container-lifecyc…
kubernetes/website pull request #23284
Opened 2020-08-21 02:51 UTC by hase1128

**What this PR does / why we need it:**
content/ja/docs/concepts/containers/container-lifecycle-hooks.md is outdated.

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/containers/container-lifecycle-hooks.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/containers/container-lifecycle-hooks.md

diff between translated and v1.18
https://gist.github.com/cb8130f11db134d87d4cbd82164582c5

**Which issue(s) this PR fixes:**
#23243 

**Special notes for your reviewer:**
It is better to merge this PR after the following documents are updated.
 - https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/pods/pod.md
 - https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/pods/pod-lifecycle.md

I changed the link of pod termination in this PR.
Original English doc moved the document about pod termination, so link URL was changed in original document.
In this case, Japanese doc also should move the document about pod termination, and then we change link URL in this PR.

I will create issues for updating the above two document, and inform these issues here. Please wait.

2020-08-21 02:52 UTC, hase1128 commented
/assign @inductor

2020-08-21 03:29 UTC, oke-py commented
/hold

2020-08-21 04:06 UTC, oke-py commented
ご提案いただいたように他ページを修正してからマージするため、holdしてマージされないようにしておきます。

2020-08-28 14:53 UTC, inductor commented
@oke-py これのゴールってなんでしたっけ

2020-08-31 00:41 UTC, oke-py commented
@inductor  リンク切れしないように #23450 が終わってからマージするのがよいです。
このPRで一緒に修正しておいて、と言うにはけっこう差分があって厳しいです。
ま、全部同じPRでmasterやrelease-1.18にマージするなら待たなくてもよいです。

@hase1128 こちらのページは完了していなくてもよさそうですが、挙げられているのはどういう意図でしょう？
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/pods/pod.md

2020-08-31 00:47 UTC, hase1128 commented
@oke-py 
pods/pod.mdの内容の一部がpods/pod-lifecycle.mdに移動したことでリンク切れを起こしたので、pod.mdの方も挙げました。
ただ、今考えてみると、pod-lifecycle.mdが更新されれば、とりあえず本PRのリンク切れは起きないので、本PRに関してはpod-life-cycle.mdのみ更新されればマージ可能と思いました。

2020-08-31 00:48 UTC, oke-py commented
承知しました。

2020-09-07 06:48 UTC, oke-py requested changes

2020-09-07 06:48 UTC, oke-py commented on content/ja/docs/concepts/containers/container-lifecycle-hooks.md
> +終了動作の詳細な説明は、[Termination of Pods](/ja/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)にあります。
```suggestion
終了動作の詳細な説明は、[Termination of Pods](/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination)にあります。
```
暫定的に原文にリンクを向け、一通りそろったあとでリンクを書き換えることにしようと思います。

2020-09-08 01:32 UTC, hase1128 commented
@oke-py 

> 暫定的に原文にリンクを向け、一通りそろったあとでリンクを書き換えることにしようと思います。

suggested changeをapplyしました。

2020-09-08 01:34 UTC, oke-py approved these changes
/unhold
/lgtm

2020-09-14 08:35 UTC, nasa9084 commented
/approve

2020-09-14 08:36 UTC, merged