Update docs/concepts/architecture/cloud-controller.md
kubernetes/website pull request #23291
Opened 2020-08-21 06:38 UTC by yu-kasuya

Closes: #23253

2020-08-21 06:50 UTC, inductor commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドインフラストラクチャ技術により、パブリック、プライベート、ハイブリッドクラウド上でKubernetesを動かすことができます。Kubernetesは、コンポーネント間の密なつながりが不要な自動化されたAPI駆動インフラストラクチャーであると考えられています。
```suggestion
クラウドインフラストラクチャー技術により、パブリック、プライベート、ハイブリッドクラウド上でKubernetesを動かすことができます。Kubernetesは、コンポーネント間の密なつながりが不要な自動化されたAPI駆動インフラストラクチャーであると考えられています。
```

2020-08-21 06:50 UTC, inductor commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドインフラストラクチャ技術により、パブリック、プライベート、ハイブリッドクラウド上でKubernetesを動かすことができます。Kubernetesは、コンポーネント間の密なつながりが不要な自動化されたAPI駆動インフラストラクチャーであると考えられています。
Ref. https://kubernetes.io/ja/docs/contribute/localization/

2020-08-24 03:01 UTC, yu-kasuya commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドインフラストラクチャ技術により、パブリック、プライベート、ハイブリッドクラウド上でKubernetesを動かすことができます。Kubernetesは、コンポーネント間の密なつながりが不要な自動化されたAPI駆動インフラストラクチャーであると考えられています。
レビューありがとうございます、修正しました

2020-08-24 03:01 UTC, yu-kasuya commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +![Kubernetes components](/images/docs/components-of-kubernetes.png)
Thanks!

2020-08-24 03:18 UTC, inductor commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +{{< glossary_definition term_id="cloud-controller-manager" length="all" prepend="cloud-controller-managerは">}}
ここって手元で動作確認するとどういう表示になりますか？

@yu-kasuya

2020-08-24 04:18 UTC, yu-kasuya commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +{{< glossary_definition term_id="cloud-controller-manager" length="all" prepend="cloud-controller-managerは">}}
こんな感じで内容が展開されてます。

![Screen Shot 2020-08-24 at 13 16 47](https://user-images.githubusercontent.com/15024080/91003373-13899080-e60c-11ea-98f6-2379e6fb776c.png)

2020-08-24 07:13 UTC, inductor commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +{{< glossary_definition term_id="cloud-controller-manager" length="all" prepend="cloud-controller-managerは">}}
おーなるほど、prepandの中身が中途半端な感じなのが気になりましたが、このままじゃないと動かない感じなんでしたっけ

2020-08-24 08:45 UTC, yu-kasuya commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +{{< glossary_definition term_id="cloud-controller-manager" length="all" prepend="cloud-controller-managerは">}}
たしかに中途半端な記載ですが、原文に合わせてみました。
原文も、prepandに"The cloud-controller-manager is"
glossaryは"a Kubernetes control plane component..."から記載されており、
glossaryに主語がないのでprepandでわりとむりやり付け足して書いている形式になっています。

2020-08-24 08:59 UTC, inductor commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +{{< glossary_definition term_id="cloud-controller-manager" length="all" prepend="cloud-controller-managerは">}}
なるほど！ありがとうございます :)

2020-08-25 02:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +cloud-controller-managerは、プラグインメカニズムを用い、異なるクラウドプロバイダーに対してそれぞれのプラットフォームとKubernetesの結合を可能にする構成になっています。
```suggestion
cloud-controller-managerは、プラグイン機構を用い、異なるクラウドプロバイダーに対してそれぞれのプラットフォームとKubernetesの結合を可能にする構成になっています。
```

技術ドキュメントはどうしても全体的にカタカナ語が多くなりがちなので、訳せる物は訳しちゃった方がよさそうです

2020-08-25 02:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドコントローラーマネージャーは、複製されたプロセスのセットとしてコントロールプレーンで実行されます。（通常、Pod内のコンテナとなります）各cloud-controller-managerは、シングルプロセスで複数の{{< glossary_tooltip text="controllers" term_id="controller" >}}を実装します。
```suggestion
クラウドコントローラーマネージャーは、複製されたプロセスの集合としてコントロールプレーンで実行されます。（通常、Pod内のコンテナとなります）各cloud-controller-managerは、シングルプロセスで複数の{{< glossary_tooltip text="controllers" term_id="controller" >}}を実装します。
```

2020-08-25 02:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドコントローラーマネージェーは、いかなるクラウドからもプラグインとしての実装を許可するためにGoインターフェースを使います。具体的には、 [kubernetes/cloud-provider](https://github.com/kubernetes/cloud-provider)の [`cloud.go`](https://github.com/kubernetes/cloud-pro
```suggestion
クラウドコントローラーマネージャーは、いかなるクラウドからもプラグインとしての実装を許可するためにGoインターフェースを使います。具体的には、 [kubernetes/cloud-provider](https://github.com/kubernetes/cloud-provider)の [`cloud.go`](https://github.com/kubernetes/cloud-provider/blob/release-1.17/cloud.go#L42-L62)で定義されている`CloudProvider`を使います。
```

2020-08-25 08:08 UTC, yu-kasuya commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +cloud-controller-managerは、プラグインメカニズムを用い、異なるクラウドプロバイダーに対してそれぞれのプラットフォームとKubernetesの結合を可能にする構成になっています。
なるほど！ありがとうございます修正しました。

2020-09-16 13:34 UTC, kakts requested changes
ご対応ありがとうございます。

2点コメントしました。ご確認お願いいたします。

2020-09-16 13:34 UTC, kakts commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドインフラストラクチャー技術により、パブリック、プライベート、ハイブリッドクラウド上でKubernetesを動かすことができます。Kubernetesは、コンポーネント間の密なつながりが不要な自動化されたAPI駆動インフラストラクチャーであると考えられています。
```suggestion
クラウドインフラストラクチャー技術により、パブリック、プライベート、ハイブリッドクラウド上でKubernetesを動かすことができます。Kubernetesは、コンポーネント間の密なつながりが不要な自動化されたAPI駆動インフラストラクチャーを信条としています。
```

>Kubernetes believes in ...
Kubernetesは... を信条とする　みたいなニュアンスが良いかと思いました!

2020-09-16 13:34 UTC, kakts commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +いくつかのクラウドプロバイダーは、これをノードコントローラーと分離ノードライフサイクルコントローラーに分けて実装しています。
```suggestion
いくつかのクラウドプロバイダーは、これをノードコントローラーと個別のノードライフサイクルコントローラーに分けて実装しています。
```
>separate node lifecycle controller 
separate 「個別の」 というニュアンスでも良いかと思いました。

https://ejje.weblio.jp/content/separate
>b限定用法の形容詞 別々の，個々の.

2020-09-17 03:54 UTC, yu-kasuya commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドインフラストラクチャー技術により、パブリック、プライベート、ハイブリッドクラウド上でKubernetesを動かすことができます。Kubernetesは、コンポーネント間の密なつながりが不要な自動化されたAPI駆動インフラストラクチャーであると考えられています。
なるほど！ありがとうございます

2020-09-17 03:55 UTC, yu-kasuya commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +いくつかのクラウドプロバイダーは、これをノードコントローラーと分離ノードライフサイクルコントローラーに分けて実装しています。
こちらもありがとうございます

2020-09-17 06:11 UTC, inductor requested changes

2020-09-17 06:11 UTC, inductor commented on content/ja/docs/concepts/architecture/cloud-controller.md
> +クラウドコントローラーマネージャーは、いかなるクラウドからもプラグインとしての実装を許可するためにGoインターフェースを使います。具体的には、 [kubernetes/cloud-provider](https://github.com/kubernetes/cloud-provider)の [`cloud.go`](https://github.com/kubernetes/cloud-pro
```suggestion
クラウドコントローラーマネージャーは、いかなるクラウドからもプラグインとしての実装を許可するためにGoインターフェースを使います。具体的には、[kubernetes/cloud-provider](https://github.com/kubernetes/cloud-provider)の [`cloud.go`](https://github.com/kubernetes/cloud-provider/blob/release-1.17/cloud.go#L42-L62)で定義されている`CloudProvider`を使います。
```

2020-09-17 14:08 UTC, kakts commented
ご対応ありがとうございます
/lgtm

2020-09-17 19:15 UTC, inductor commented
/approve

2020-09-17 19:16 UTC, merged