ja: Make docs/tasks/debug-application-cluster/get-shell-running-container.md follow v1.18 of the original text
kubernetes/website pull request #23388
Opened 2020-08-24 04:46 UTC by h1de27

Update docs/tasks/debug-application-cluster/get-shell-running-container.md to follow v1.18. https://github.com/kubernetes/website/issues/23387

2020-08-24 04:52 UTC, oke-py requested changes

2020-08-24 04:52 UTC, oke-py commented on content/ja/docs/tasks/debug-application-cluster/get-shell-running-container.md
> +ショートオプションの `-i` と `-t` は、ロングオプションの `--stdin` と `--tty` と同様です。
```suggestion
ショートオプションの`-i`と`-t`は、ロングオプションの`--stdin`と`--tty`と同様です。
```

2020-08-24 04:56 UTC, oke-py approved these changes
/lgtm

2020-08-24 04:57 UTC, h1de27 commented on content/ja/docs/tasks/debug-application-cluster/get-shell-running-container.md
> +ショートオプションの `-i` と `-t` は、ロングオプションの `--stdin` と `--tty` と同様です。
レビューありがとうございます。

2020-08-24 23:18 UTC, h1de27 commented
/assign @inductor

2020-08-28 14:44 UTC, inductor reviewed
箇条書きの場合「。」は不要かと

2020-08-28 14:44 UTC, inductor commented on content/ja/docs/tasks/debug-application-cluster/get-shell-running-container.md
> +* [kubectl exec](/docs/reference/generated/kubectl/kubectl-commands/#exec)について読む。
```suggestion
* [kubectl exec](/docs/reference/generated/kubectl/kubectl-commands/#exec)について読む
```

2020-08-30 20:44 UTC, h1de27 commented on content/ja/docs/tasks/debug-application-cluster/get-shell-running-container.md
> +* [kubectl exec](/docs/reference/generated/kubectl/kubectl-commands/#exec)について読む。
承知しました。ご指摘ありがとうございます。

2020-08-31 03:38 UTC, inductor commented
/lgtm
/approve

2020-08-31 03:40 UTC, merged