ja: Make docs/tasks/debug-application-cluster/debug-stateful-set.md follow v1.18 of the original text
kubernetes/website pull request #23401
Opened 2020-08-24 15:07 UTC by shuzokato

Updated docs/tasks/debug-application-cluster/debug-stateful-set.md to follow v1.18 of the original text. #23385

2020-08-24 15:17 UTC, shuzokato commented
/assign @nasa9084

2020-08-25 00:15 UTC, oke-py approved these changes
/lgtm

2020-08-28 14:46 UTC, inductor requested changes

2020-08-28 14:46 UTC, inductor commented on content/ja/docs/tasks/debug-application-cluster/debug-stateful-set.md
> +Podが長期間`Unknown`または`Terminating`の状態になっていることがわかった場合は、それらを処理する方法について[StatefulSet Podsの削除](/docs/tasks/run-application/delete-stateful-set/)タスクを参照してください。
```suggestion
Podが長期間`Unknown`または`Terminating`の状態になっていることがわかった場合は、それらを処理する方法について[StatefulSet Podの強制削除](/ja/docs/tasks/run-application/delete-stateful-set/)タスクを参照してください。
```

ref. https://kubernetes.io/ja/docs/tasks/run-application/force-delete-stateful-set-pod/

2020-08-30 03:45 UTC, inductor commented
/lgtm
/approve

2020-08-30 03:46 UTC, merged