Update ja/docs/concepts/architecture/controller.md
kubernetes/website pull request #23410
Opened 2020-08-25 03:15 UTC by yu-kasuya

Closes: #23252

2020-08-25 03:21 UTC, inductor requested changes

2020-08-25 03:21 UTC, inductor commented on content/ja/docs/concepts/architecture/controller.md
> +設計理念として、Kubernetesは多数のコントローラーを使用しており、各コントローラーはクラスターの状態の特定の側面をそれぞれ管理しています。最もよくあるパターンは、特定の制御ループ(コントローラー)が目的の状態として1種類のリソースを使用し、目的の状態を実現することを管理するために別の種類のリソースを用意するというものです。 たとえば、Jobのコントローラーは、Jobオブジェクト(新しい処
```suggestion
設計理念として、Kubernetesは多数のコントローラーを使用しており、各コントローラーはクラスターの状態の特定の側面をそれぞれ管理しています。最もよくあるパターンは、特定の制御ループ(コントローラー)が目的の状態として1種類のリソースを使用し、目的の状態を実現することを管理するために別の種類のリソースを用意するというものです。たとえば、Jobのコントローラーは、Jobオブジェクト(新しい処理を見つけるため)およびPodオブジェクト(Jobを実行し、処理が完了したか確認するため)を監視します。この場合、なにか別のものがJobを作成し、JobコントローラーはPodを作成します。
```

2020-08-25 09:44 UTC, inductor commented
commit suggestion機能もあるので使っていただいて大丈夫です :)

2020-08-26 03:31 UTC, yu-kasuya commented
ありがとうございます、今度使ってみます！

2020-08-28 15:03 UTC, inductor commented
/approve

2020-08-29 09:27 UTC, merged