Update ja/docs/concepts/cluster-administration/networking.md
kubernetes/website pull request #23439
Opened 2020-08-26 03:29 UTC by yu-kasuya

Closes:#23250

2020-08-27 04:10 UTC, yu-kasuya commented on content/ja/docs/concepts/cluster-administration/networking.md
> +[ネットワーク設計ドキュメント](https://git.k8s.io/community/contributors/design-proposals/network/networking.md)で詳細に説明されています。
原文ではリンク部分から改行されていたので同様にしましたが、リンク前にスペースが入ってしまっていました。
日本語の方はリンクあっても改行しないほうがいいでしょうか？

2020-08-27 04:28 UTC, oke-py commented on content/ja/docs/concepts/cluster-administration/networking.md
> +[ネットワーク設計ドキュメント](https://git.k8s.io/community/contributors/design-proposals/network/networking.md)で詳細に説明されています。
改行なしでお願いいたします。

2020-08-27 08:18 UTC, yu-kasuya commented on content/ja/docs/concepts/cluster-administration/networking.md
> +[ネットワーク設計ドキュメント](https://git.k8s.io/community/contributors/design-proposals/network/networking.md)で詳細に説明されています。
ありがとうございます！

2020-08-28 10:12 UTC, oke-py requested changes

2020-08-28 10:12 UTC, oke-py commented on content/ja/docs/concepts/cluster-administration/networking.md
> +1. 高度に結合されたコンテナ間の通信: これは、{{< glossary_tooltip text="Pods" term_id="pod" >}}および`localhost`通信によって解決されます。
```suggestion
1. 高度に結合されたコンテナ間の通信: これは、{{< glossary_tooltip text="Pod" term_id="pod" >}}および`localhost`通信によって解決されます。
```
翻訳時は単数形とします。
ref https://kubernetes.io/ja/docs/contribute/localization/#%E5%82%99%E8%80%83

2020-08-28 10:12 UTC, oke-py commented on content/ja/docs/concepts/cluster-administration/networking.md
> +[CNI-Genie](https://github.com/Huawei-PaaS/CNI-Genie) is a CNI plugin that enables Kubernetes to [simultaneously have access to different implementations](https://github.com/Huawei-PaaS/CNI-Genie/blo
```suggestion
[CNI-Genie](https://github.com/Huawei-PaaS/CNI-Genie) is a CNI plugin that enables Kubernetes to [simultaneously have access to different implementations](https://github.com/Huawei-PaaS/CNI-Genie/blob/master/docs/multiple-cni-plugins/README.md#what-cni-genie-feature-1-multiple-cni-plugins-enables) of the [Kubernetes network model](/ja/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model) in runtime. This includes any implementation that runs as a [CNI plugin](https://github.com/containernetworking/cni#3rd-party-plugins), such as [Flannel](https://github.com/coreos/flannel#flannel), [Calico](http://docs.projectcalico.org/), [Romana](http://romana.io), [Weave-net](https://www.weave.works/products/weave-net/).
```
まだドキュメント化できておらず恐縮ですが、リンクの`#`の値は、URLエンコードを避けるために英語表記する方針です。リンク先ファイルもあわせて修正できますでしょうか。以下のようにします。
```
# Kubernetesのネットワークモデル {#the-kubernetes-network-model}
```

2020-08-31 03:15 UTC, yu-kasuya commented on content/ja/docs/concepts/cluster-administration/networking.md
> +1. 高度に結合されたコンテナ間の通信: これは、{{< glossary_tooltip text="Pods" term_id="pod" >}}および`localhost`通信によって解決されます。
修正しました

2020-08-31 03:16 UTC, yu-kasuya commented on content/ja/docs/concepts/cluster-administration/networking.md
> +[CNI-Genie](https://github.com/Huawei-PaaS/CNI-Genie) is a CNI plugin that enables Kubernetes to [simultaneously have access to different implementations](https://github.com/Huawei-PaaS/CNI-Genie/blo
ありがとうございます、記述方法承知しました。
リンク先も修正しました。

2020-08-31 03:34 UTC, oke-py commented on content/ja/docs/concepts/cluster-administration/networking.md
> +[CNI-Genie](https://github.com/Huawei-PaaS/CNI-Genie) is a CNI plugin that enables Kubernetes to [simultaneously have access to different implementations](https://github.com/Huawei-PaaS/CNI-Genie/blo
あ、これはページ内リンクなんですね。これだけでよさそうな。
```
[Kubernetes network model](#the-kubernetes-network-model)
```
原文がこうなっているので、日本語版もこれでよいですが。

2020-08-31 03:35 UTC, oke-py approved these changes
/lgtm
/assign @inductor

2020-08-31 03:42 UTC, inductor commented
/approve

2020-08-31 03:44 UTC, merged