Translate docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ into Japanese. #23442
kubernetes/website pull request #23495
Opened 2020-08-27 15:33 UTC by cyberblack28

Translate docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/ into Japanese.

2020-08-27 15:45 UTC, cyberblack28 commented
/assign @nasa9084

2020-09-02 06:54 UTC, nasa9084 requested changes

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +reviewers:
これはenのレビュワーなので消してしまってください

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +* WindowsコンテナをホストするWindowsノードを構成するには、[Windows Server 2019ライセンス](https://www.microsoft.com/en-us/cloud-platform/windows-server-pricing)（またはそれ以上）を取得します。
```suggestion
* WindowsコンテナをホストするWindowsノードを構成するには、[Windows Server 2019ライセンス](https://www.microsoft.com/en-us/cloud-platform/windows-server-pricing)(またはそれ以上)を取得します。
```

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +* コントロールプレーンにアクセスできるLinuxベースのKubernetes kubeadmクラスター（[kubeadmを使用した単一のコントロールプレーンクラスターの作成](/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)を参照）
```suggestion
* コントロールプレーンにアクセスできるLinuxベースのKubernetes kubeadmクラスター([kubeadmを使用した単一のコントロールプレーンクラスターの作成](/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)を参照)
```

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +* WindowsコンテナをホストするWindowsノードを構成するには、[Windows Server 2019ライセンス](https://www.microsoft.com/en-us/cloud-platform/windows-server-pricing)（またはそれ以上）を取得します。
ref: style guide https://kubernetes.io/ja/docs/contribute/localization

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +## はじめに：クラスタへのWindowsノードの追加
```suggestion
## はじめに: クラスタへのWindowsノードの追加
```

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +    {{< note >}}Linux上のFlannelがWindows上のFlannelと相互運用するには、VNIを4096およびポート4789に設定する必要があります。これらのフィールドの説明については、[VXLANドキュメント](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#vxlan)を
```suggestion
    {{< note >}}Linux上のFlannelがWindows上のFlannelと相互運用するには、VNIを4096およびポート4789に設定する必要があります。これらのフィールドの説明については、[VXLANドキュメント](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#vxlan)を参照してください。{{< /note >}}
```

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +1. Windows Flannelとkube-proxy DaemonSetsを追加する
```suggestion
1. Windows Flannelとkube-proxy DaemonSetを追加する
```

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +1. wins、kubelet、kubeadmのインストールします。
```suggestion
1. wins、kubelet、kubeadmをインストールします。
```

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +    （コントロールプレーンホスト上で）を実行して新しいトークンを生成します。
```suggestion
    (コントロールプレーンホスト上で)を実行して新しいトークンを生成します。
```

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +`kube-system`名前空間のフランネルポッドを確認することで、以前と同様に進行状況を確認できます:
```suggestion
`kube-system`名前空間のflannel Podを確認することで、以前と同様に進行状況を確認できます:
```

flannelは固有のソフトウェア名称、podはリソース名なのでそれぞれママ表記でいいかと思います

2020-09-02 06:54 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +新しいノードが`NotReady`状態の場合は、flannelイメージがまだダウンロードされている可能性があります。
```suggestion
新しいノードが`NotReady`状態の場合は、flannelイメージがまだダウンロード中の可能性があります。
```

2020-09-02 06:55 UTC, nasa9084 commented
/cc @oke-py

2020-09-02 07:16 UTC, cyberblack28 commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +reviewers:
対応しました。

2020-09-03 10:31 UTC, nasa9084 commented
/approve

2020-09-05 01:25 UTC, oke-py requested changes

2020-09-05 01:25 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +* コントロールプレーンにアクセスできるLinuxベースのKubernetes kubeadmクラスター([kubeadmを使用した単一のコントロールプレーンクラスターの作成](/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)を参照)
```suggestion
* コントロールプレーンにアクセスできるLinuxベースのKubernetes kubeadmクラスター([kubeadmを使用したシングルコントロールプレーンクラスターの作成](/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/)を参照)
```
翻訳済みのためリンクを修正し、タイトルをリンク先に合わせておきます。

2020-09-05 01:25 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +## はじめに: クラスタへのWindowsノードの追加
```suggestion
## はじめに: クラスターへのWindowsノードの追加
```

2020-09-05 01:25 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +    VNIを4096、ポートを4789に設定するために、flannelマニフェストの`net-conf.json`セクションを変更します。次のようになります。:
```suggestion
    VNIを4096、ポートを4789に設定するために、flannelマニフェストの`net-conf.json`セクションを変更します。次のようになります:
```

2020-09-05 01:25 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +    順番に互換性のあるバージョンのkube-proxyを確実に入手するには、イメージのタグを代用する必要があります。
```suggestion
    互換性のあるバージョンのkube-proxyを確実に入手するには、イメージのタグを置換する必要があります。
```
In order to の In order をわけて訳してしまっているのでしょうか？

2020-09-05 01:25 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +    独自のdeploymentに合わせてバージョンを調整する必要があります。
```suggestion
    独自のデプロイに合わせてバージョンを調整する必要があります。
```

2020-09-05 01:25 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +    ホストゲートウェイを使用している場合は、代わりにhttps://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-host-gw.ymlを使用してください。
```suggestion
    ホストゲートウェイを使用している場合は、代わりに https://github.com/kubernetes-sigs/sig-windows-tools/releases/latest/download/flannel-host-gw.yml を使用してください。
```
前後に半角スペースを入れるとリンクになりそうです。

2020-09-05 01:25 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes.md
> +Windowsノードでイーサネット(「Ethernet0 2」など)ではなく別のインターフェースを使用している場合は、次の行を変更する必要があります。:
```suggestion
Windowsノードでイーサネット(「Ethernet0 2」など)ではなく別のインターフェースを使用している場合は、次の行を変更する必要があります:
```

2020-09-05 09:59 UTC, oke-py approved these changes
`/lgtm`してマージしてしまってもよさそうですが、一応変更分の再レビューしてもらいますかね。
@nasa9084 approve後の変更をさくっと見てもらって、よければlgtmもしてしまってください。

2020-09-07 02:51 UTC, inductor commented
/lgtm
/approve

2020-09-07 02:53 UTC, merged