Updata ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
kubernetes/website pull request #23511
Opened 2020-08-28 03:56 UTC by yu-kasuya

Closes: #23299

2020-08-28 14:58 UTC, inductor commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスタのAPIサーバの[1つ以内のバージョン](/ja/docs/setup/release/version-skew-policy/#ku
`APIサーバの1つ以内のバージョンである必要があります。`

ってなんか日本語的に伝わりづらい感じがします

2020-08-29 04:51 UTC, kakts commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスタのAPIサーバの[1つ以内のバージョン](/ja/docs/setup/release/version-skew-policy/#ku
```suggestion
{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスタのAPIサーバの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy/#kubectl)にある必要があります。
```

The kubectl version should be [within one minor version](/docs/setup/release/version-skew-policy/#kubectl) of your cluster's API server.

訳すの難しくて私も怪しいですが、こんな感じでしょうか...

2020-08-31 03:20 UTC, yu-kasuya commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスタのAPIサーバの[1つ以内のバージョン](/ja/docs/setup/release/version-skew-policy/#ku
ありがとうざいます、いただいた内容を反映しました。

2020-09-03 10:49 UTC, nasa9084 commented
/assign
/approve

2020-09-03 10:58 UTC, oke-py requested changes

2020-09-03 10:58 UTC, oke-py commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスタのAPIサーバの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy/
```suggestion
{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスターのAPIサーバーの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy/#kubectl)にある必要があります。
```

2020-09-03 11:19 UTC, inductor commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスタのAPIサーバの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy/
にある、よりもであるのほうが日本語的にはよさそう

2020-09-04 02:57 UTC, yu-kasuya commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスタのAPIサーバの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy/
ありがとうございます、修正しました

2020-09-04 10:11 UTC, oke-py requested changes

2020-09-04 10:11 UTC, oke-py commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスターのAPIサーバの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy
```suggestion
{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスターのAPIサーバーの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy/#kubectl)である必要があります。
```
サーバも長音つけておいてください。

2020-09-04 10:28 UTC, yu-kasuya commented on content/ja/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md
> +{{< glossary_tooltip text="kubectl" term_id="kubectl" >}}がインストールされているか確認するため、`kubectl version --client`を実行してください。kubectlのバージョンは、クラスターのAPIサーバの[1つのマイナーバージョン内](/ja/docs/setup/release/version-skew-policy
見落としてました、ありがとうございます！

2020-09-04 10:29 UTC, oke-py approved these changes
/lgtm

2020-09-04 10:29 UTC, merged