ja: Make docs/concepts/workloads/controllers/ttlafterfinished.md follow v1.18 of the original text
kubernetes/website pull request #23519
Opened 2020-08-28 12:28 UTC by shuzokato

Updated docs/concepts/workloads/controllers/ttlafterfinished.md to follow v1.18 of the original text. #23452

2020-08-28 14:57 UTC, inductor requested changes
https://kubernetes.io/ja/docs/concepts/workloads/controllers/job/

既に日本語版があるので、リンクごと修正お願いできますと幸いです！

2020-08-28 15:30 UTC, shuzokato commented
/assign @inductor
修正しました。

2020-08-28 16:17 UTC, inductor commented on content/ja/docs/concepts/workloads/controllers/ttlafterfinished.md
> +[Jobの自動クリーンアップ](/ja/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically)
`/#clean-up-finished-jobs-automatically` 手元でこれのハッシュのリンクが動くことを確認してみてもらえると！

2020-08-29 01:28 UTC, shuzokato commented
ハッシュのリンクを修正しました！
https://github.com/kubernetes/website/pull/23519/commits/7ed9664a45e643df54c3a9a328fe21f881131b64

2020-08-29 02:14 UTC, inductor commented
指摘の仕方がちょっと曖昧で申し訳ない。
どちらかというとリンク先の方を変えてほしいかもです。

```markdown
## 日本語タイトル {#english-title}
```

みたいにすれば動くと思います！

2020-08-29 15:33 UTC, shuzokato commented
リンクを修正しました。こちらで動くと思うのですがいかがでしょうか？

2020-08-30 03:48 UTC, inductor commented
これでは動かないですね。一旦英語のときのハッシュに戻してください。

そうではなくて、**対象のページの**ヘッダー部分を

```
# ただの日本語タイトル
```

から

```
# ただの日本語タイトル {origina-english-title}
```

みたいな感じにする必要がある、ということです。なのでこのページに加え、対象リンクの中身も変えてくださいというのが指示です。

2020-08-30 04:22 UTC, shuzokato commented
すみません、リクエストの趣旨を理解しました。
訂正しました。dev-1.18-ja.1ブランチにリンク先のページ(/ja/docs/concepts/workloads/controllers/job)が存在しなかったため、masterブランチのものをpullして修正しました。

2020-08-30 04:39 UTC, inductor commented
おや、1.18ブランチにはなかったですか・・・！
それはこちらの確認不足でした、すみません :bow:

そしたら、リンクだけ指定したようにしてもらって、ファイルの追加はしない状態にしていただいてもよろしいでしょうか

2020-08-30 04:51 UTC, shuzokato commented
了解です。これでどうでしょうか？

2020-08-30 16:39 UTC, kakts commented
翻訳ありがとうございます
/lgtm

2020-08-31 00:29 UTC, oke-py requested changes

2020-08-31 00:29 UTC, oke-py commented on content/ja/docs/concepts/workloads/controllers/ttlafterfinished.md
> +TTLコントローラーは現在{{< glossary_tooltip text="Jobs" term_id="job" >}}のみ扱っていて、将来的にPodやカスタムリソースなど、他のリソースの実行終了を扱えるように拡張される予定です。
```suggestion
TTLコントローラーは現在{{< glossary_tooltip text="Job" term_id="job" >}}のみ扱っていて、将来的にPodやカスタムリソースなど、他のリソースの実行終了を扱えるように拡張される予定です。
```
リソース名は単数形で表現します。
https://kubernetes.io/ja/docs/contribute/localization/

2020-08-31 00:29 UTC, oke-py commented on content/ja/docs/concepts/workloads/controllers/ttlafterfinished.md
> +[Jobの自動クリーンアップ](/ja/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically)
```suggestion
* [Jobの自動クリーンアップ](/ja/docs/concepts/workloads/controllers/job/#clean-up-finished-jobs-automatically)
```

2020-08-31 00:29 UTC, oke-py commented on content/ja/docs/concepts/workloads/controllers/ttlafterfinished.md
>  [設計ドキュメント](https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/0026-ttl-after-finish.md)
```suggestion
* [設計ドキュメント](https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/0026-ttl-after-finish.md)
```

2020-09-14 10:37 UTC, inductor commented on content/ja/docs/concepts/workloads/controllers/ttlafterfinished.md
>  [設計ドキュメント](https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/0026-ttl-after-finish.md)
@shuzokato こちらいかがでしょう？

2020-09-14 10:54 UTC, shuzokato commented
@inductor すみません，反映しましたのでよろしくお願いします！

2020-09-14 10:57 UTC, inductor commented
/lgtm
/approve

2020-09-14 10:59 UTC, merged