Update ja/docs/tasks/access-application-cluster/connecting-frontend-backend.md
kubernetes/website pull request #23578
Opened 2020-08-31 03:56 UTC by yu-kasuya

Closes: #23300

2020-08-31 14:28 UTC, kakts commented
/lgtm

2020-09-02 09:07 UTC, inductor requested changes

2020-09-02 09:07 UTC, inductor commented on content/ja/docs/tasks/access-application-cluster/connecting-frontend-backend.md
> +Serviceを削除するために、このコマンドを入力してください：
```suggestion
Serviceを削除するには、このコマンドを入力してください：
```

ために、はなんかちょっと直訳感が強すぎるので

2020-09-02 09:49 UTC, yu-kasuya commented on content/ja/docs/tasks/access-application-cluster/connecting-frontend-backend.md
> +Serviceを削除するために、このコマンドを入力してください：
たしかに。ありがとうございます

2020-09-02 10:09 UTC, inductor reviewed
/lgtm
/approve

2020-09-02 10:11 UTC, merged