Update Japanese localization on concepts/workloads/controllers/daemon…
kubernetes/website pull request #23581
Opened 2020-08-31 06:58 UTC by hase1128

**What this PR does / why we need it:**
content/ja/docs/concepts/workloads/pods/podpreset.md is outdated.

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/controllers/daemonset.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/concepts/workloads/controllers/daemonset.md

diff between translated and v1.18
https://gist.github.com/b09723b2d38ab847cfc0a22748a823cb

**Which issue(s) this PR fixes:**
#23457 

**Special notes for your reviewer:**
It is better to merge this PR after [concepts/workloads/pods/_index.md](https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/concepts/workloads/pods/_index.md) is updated.

2020-08-31 07:00 UTC, hase1128 commented
/assign @inductor

2020-08-31 07:04 UTC, hase1128 commented on content/ja/docs/concepts/workloads/controllers/daemonset.md
ここの変更でリンク切れが起きるように思います。
元の英語記事では`/docs/concepts/workloads/pods/pod-overview/#pod-templates`を
`/docs/concepts/workloads/pods/#pod-templates`に変更してます。(pod-templetesの記事が移動したため。)

しかし日本語ドキュメントでは、pod-templetesの記事の移動ができていないので、リンク先だけを変更した場合、リンク切れが起きます。

2020-09-01 13:52 UTC, kakts commented
対応ありがとうございます。
/lgtm

2020-09-06 16:12 UTC, kakts commented on content/ja/docs/concepts/workloads/controllers/daemonset.md
ありがとうございます。
このPRでは英語の元記事の`/docs/concepts/workloads/pods/#pod-templates`で進め、別途リンクを書き換えるissueを作って対応します。

2020-09-08 02:02 UTC, oke-py requested changes

2020-09-08 02:02 UTC, oke-py commented on content/ja/docs/concepts/workloads/controllers/daemonset.md
> +`.spec.template`は[Podテンプレート](/ja/docs/concepts/workloads/pods/#podテンプレート)となります。これはフィールドがネストされていて、`apiVersion`や`kind`をもたないことを除いては、{{< glossary_tooltip text="Pod" term_id="pod" >}}のテンプレートと同じスキーマとなります。
```suggestion
`.spec.template`は[Podテンプレート](/docs/concepts/workloads/pods/#pod-templates)となります。これはフィールドがネストされていて、`apiVersion`や`kind`をもたないことを除いては、{{< glossary_tooltip text="Pod" term_id="pod" >}}のテンプレートと同じスキーマとなります。
```
別PRでお伝えしたとおり、いったん英語版に向けてあとでまとめてjaに修正します。

2020-09-08 03:51 UTC, hase1128 commented
@oke-py 

> 別PRでお伝えしたとおり、いったん英語版に向けてあとでまとめてjaに修正します。

承知しました。suggestion appliedにしました。

2020-09-08 10:11 UTC, kakts commented
/lgtm

リンク書き換えるissueはこの後作成
https://github.com/kubernetes/website/pull/23581#discussion_r484087717

2020-09-08 11:53 UTC, kakts commented
@hase1128 @oke-py @inductor 

pod-templatesのページを書き換えるissue作りました。　
https://github.com/kubernetes/website/issues/23748

2020-09-09 01:46 UTC, inductor commented
/approve

2020-09-09 01:47 UTC, merged