Update Japanese localization on tasks/administer-cluster/running-clou…
kubernetes/website pull request #23593
Opened 2020-08-31 13:47 UTC by hase1128

**What this PR does / why we need it:**
content/ja/docs/tasks/administer-cluster/running-cloud-controller.md is outdated.

File to update
https://github.com/kubernetes/website/blob/dev-1.18-ja.1/content/ja/docs/tasks/administer-cluster/running-cloud-controller.md

Original
https://github.com/kubernetes/website/blob/fb6364d/content/en/docs/tasks/administer-cluster/running-cloud-controller.md

diff between translated and v1.18
https://gist.github.com/17cbe15c010350fe6ccd82c943a43116

**Which issue(s) this PR fixes:**
#23371 

**Special notes for your reviewer:**
None.

2020-08-31 13:48 UTC, hase1128 commented
/assign @nasa9084

2020-09-01 13:38 UTC, kakts commented
翻訳ありがとうございます。
/lgtm

2020-09-02 09:05 UTC, inductor requested changes

2020-09-02 09:05 UTC, inductor commented on content/ja/docs/tasks/administer-cluster/running-cloud-controller.md
> +title: クラウドコントローラーマネージャー運用
```suggestion
title: クラウドコントローラーマネージャーの運用管理
```
Administrationなので、単に運用、よりは、管理の色が強そうだなって感じがします。

2020-09-03 10:34 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/running-cloud-controller.md
> +cloud-controller-managerは、クラウドプロバイダーのAPIにクエリを送信して、すべてのノードの情報を取得します。非常に大きなクラスターの場合、リソース要件やAPIレートリミットなどのボトルネックの可能性を考慮する必要があります。
```suggestion
cloud-controller-managerは、クラウドプロバイダーのAPIにクエリーを送信して、すべてのノードの情報を取得します。非常に大きなクラスターの場合、リソース要件やAPIレートリミットなどのボトルネックの可能性を考慮する必要があります。
```

2020-09-08 01:53 UTC, inductor commented
@hase1128 こちら修正提案の内容はいかがでしょうか～

2020-09-08 03:47 UTC, hase1128 commented
@inductor @nasa9084 

昨日まで夏休みを取っていたので反応遅れました。
提案内容問題ありません。suggested changeをapplyしました。

2020-09-09 08:31 UTC, bells17 commented
/lgtm

2020-09-09 09:47 UTC, inductor commented
/approve

2020-09-09 09:47 UTC, merged