ja: Make docs/concepts/policy/resource-quotas.md follow v1.18 of the original text
kubernetes/website pull request #23621
Opened 2020-08-31 15:47 UTC by shuzokato

Updated docs/concepts/policy/resource-quotas.md tofollow v1.18 of the original text. #23604

2020-09-03 10:41 UTC, oke-py requested changes
1行だけの箇条書きはどうかと思うのですが、こちらもお願いいたします。行頭に`- `が追加されています。
https://gist.github.com/kakts/6f2ca7d74e52f532f32e65fd410a57b4#file-en-diff-L117-L118

2020-09-03 10:47 UTC, nasa9084 commented
/assign

2020-09-03 11:24 UTC, shuzokato commented
@oke-py  修正しました。確認お願いします

2020-09-03 16:29 UTC, nasa9084 commented
/approve

2020-09-04 10:07 UTC, oke-py approved these changes
/lgtm

2020-09-04 10:09 UTC, merged