Update ja/docs/tasks/access-application-cluster/service-access-application-cluster.md
kubernetes/website pull request #23630
Opened 2020-09-01 03:34 UTC by yu-kasuya

Closes: #23302

原文および元文のようにリンク・glossaryで改行するとglossary前後にスペースが入るため、本PRでは一文/一行表記としています。

2020-09-01 13:31 UTC, kakts commented
ありがとうございます
/lgtm

2020-09-02 09:03 UTC, inductor requested changes

2020-09-02 09:03 UTC, inductor commented on content/ja/docs/tasks/access-application-cluster/service-access-application-cluster.md
> +    このコマンドは{{< glossary_tooltip text="Deployment" term_id="deployment" >}}オブジェクトとそれに紐付く{{< glossary_tooltip term_id="replica-set" text="ReplicaSet" >}}オブジェクトを作成します。
ここの改行も同じ理由で消せる気がします

2020-09-02 10:02 UTC, yu-kasuya commented on content/ja/docs/tasks/access-application-cluster/service-access-application-cluster.md
> +    このコマンドは{{< glossary_tooltip text="Deployment" term_id="deployment" >}}オブジェクトとそれに紐付く{{< glossary_tooltip term_id="replica-set" text="ReplicaSet" >}}オブジェクトを作成します。
glossaryだけじゃなく、文中で改行するとスペース入るんですね。
修正しました。

2020-09-02 10:10 UTC, inductor commented
/approve

2020-09-02 10:16 UTC, inductor commented
/lgtm

2020-09-02 10:17 UTC, merged