Update ja/docs/tutorials/hello-minikube.md
kubernetes/website pull request #23682
Opened 2020-09-04 03:40 UTC by yu-kasuya

Closes: #23310

2020-09-05 03:12 UTC, oke-py requested changes
これらの行の削除もお願いいたします。
https://gist.github.com/kakts/fb38d017899c4d1dd69b5bb844f10e94#file-en-diff-L54
https://gist.github.com/kakts/fb38d017899c4d1dd69b5bb844f10e94#file-en-diff-L56
https://gist.github.com/kakts/fb38d017899c4d1dd69b5bb844f10e94#file-en-diff-L59

2020-09-05 03:12 UTC, oke-py commented on content/ja/docs/tutorials/hello-minikube.md
> +      <p>手を動かす準備はできていますか？本チュートリアルでは、サンプルアプリケーションを実行するKubernetesクラスタをビルドします。</p>
```suggestion
      <p>手を動かす準備はできていますか？本チュートリアルでは、サンプルアプリケーションを実行するKubernetesクラスターをビルドします。</p>
```
元々ある部分の修正ではありますが、お願いいたします。

2020-09-05 03:12 UTC, oke-py commented on content/ja/docs/tutorials/hello-minikube.md
> +`kubectl`コマンドの詳細な情報は[kubectl overview](/docs/user-guide/kubectl-overview/)を参照してください。
```suggestion
`kubectl`コマンドの詳細な情報は[kubectl overview](/ja/docs/reference/kubectl/overview/)を参照してください。
```

2020-09-07 03:24 UTC, yu-kasuya commented on content/ja/docs/tutorials/hello-minikube.md
> +      <p>手を動かす準備はできていますか？本チュートリアルでは、サンプルアプリケーションを実行するKubernetesクラスタをビルドします。</p>
ありがとうございます。
別issueたてるべきだったかもしれませんが、本ドキュメントにおいてクラスタ -> クラスターへ置換しました。

2020-09-07 04:14 UTC, oke-py requested changes

2020-09-07 04:14 UTC, oke-py commented on content/ja/docs/tutorials/hello-minikube.md
> +このチュートリアルはNGINXを利用してすべての要求をエコーバックするコンテナーイメージを提供します。
```suggestion
このチュートリアルはNGINXを利用してすべての要求をエコーバックするコンテナイメージを提供します。
```

2020-09-14 08:33 UTC, nasa9084 commented on content/ja/docs/tutorials/hello-minikube.md
> +    アプリケーションとその応答が表示されるブラウザウィンドウが開きます。
```suggestion
    アプリケーションとその応答が表示されるブラウザーウィンドウが開きます。
```

2020-09-23 03:56 UTC, nasa9084 commented
/lgtm

2020-09-23 11:38 UTC, inductor commented
/approve

2020-09-23 11:40 UTC, merged