ja: Make docs/reference/glossary/volume.md follow v1.18 of the original text
kubernetes/website pull request #23706
Opened 2020-09-06 06:39 UTC by takaf04

closes #23338

2020-09-06 06:41 UTC, takaf04 commented
/assign @inductor

2020-09-06 07:58 UTC, inductor commented on content/ja/docs/reference/glossary/volume.md
> +  データを格納するディレクトリで、Pod内のコンテナが利用可能です。
>Pod内のコンテナが利用可能です

ここの日本語が曖昧で、いろんな解釈に取れてしまいそうなのが気になります。

2020-09-06 09:23 UTC, takaf04 commented on content/ja/docs/reference/glossary/volume.md
> +  データを格納するディレクトリで、Pod内のコンテナが利用可能です。
コメントありがとうございます。
以前のバージョンを参考にして具体的な表現へ修正してみました。
どうでしょうか？

> データを格納するディレクトリで、Pod内のコンテナからアクセス可能です。

2020-09-06 09:56 UTC, oke-py requested changes
原文のdiffは最終行しかありませんので訳はそのままでもよいかと思いましたが、「Pod内のコンテナからアクセス可能」がデータにかかるのかディレクトリにかかるのかわかりにくいと考えて修正していただいていると思ってよいですか？

2020-09-06 09:56 UTC, oke-py commented on content/ja/docs/reference/glossary/volume.md
> + データを格納するディレクトリで、{{< glossary_tooltip term_id="pod" >}}内の{{< glossary_tooltip text="コンテナ" term_id="container" >}}からアクセス可能です。
```suggestion
 データを格納するディレクトリで、{{< glossary_tooltip text="Pod" term_id="pod" >}}内の{{< glossary_tooltip text="コンテナ" term_id="container" >}}からアクセス可能です。
```

2020-09-06 11:16 UTC, takaf04 commented on content/ja/docs/reference/glossary/volume.md
> + データを格納するディレクトリで、{{< glossary_tooltip term_id="pod" >}}内の{{< glossary_tooltip text="コンテナ" term_id="container" >}}からアクセス可能です。
ありがとうございます。
text="Pod"をつけておいたほうがいいですね。

2020-09-06 11:25 UTC, takaf04 commented
@oke-py 
おっしゃるとおりです。
当初はリンク部分だけの修正だけやろうと思ったのですが、若干文章がわかりにくいかなと私は感じたので直してみました。
もし前のバージョンのままでよいという話であれば、元に戻しますので言ってください。

2020-09-14 10:44 UTC, inductor commented
/approve

2020-09-14 12:34 UTC, oke-py approved these changes
/lgtm

2020-09-14 12:36 UTC, merged