Update ja/docs/reference/glossary/control-plane.md
kubernetes/website pull request #23717
Opened 2020-09-07 04:05 UTC by yu-kasuya

Closes: #23343

2020-09-07 04:09 UTC, yu-kasuya commented
/assign @bells17

2020-09-07 04:17 UTC, oke-py commented
@yu-kasuya 説明不足だったかもしれませんが、アサインは https://github.com/kubernetes/website/pull/23717#issuecomment-688018147 を参照してください。このPRでは以下のとおりです。

/assign @inductor

2020-09-07 04:27 UTC, yu-kasuya commented
勘違いしてました、ありがとうございます！

2020-09-08 12:22 UTC, kakts commented
対応ありがとうございます。
/lgtm

2020-09-08 12:26 UTC, oke-py requested changes

2020-09-08 12:26 UTC, oke-py commented on content/ja/docs/reference/glossary/control-plane.md
> + このレイヤーは、次のような多くの異なるコンポーネントから構成されます。（しかし、これらに限定はされません）
```suggestion
 このレイヤーは、次のような多くの異なるコンポーネントから構成されます(しかし、これらに限定はされません)。
```
括弧は半角にします。
https://kubernetes.io/ja/docs/contribute/localization/

2020-09-08 12:26 UTC, oke-py commented on content/ja/docs/reference/glossary/control-plane.md
> + * {{< glossary_tooltip text="API Server" term_id="kube-apiserver" >}}
```suggestion
 * {{< glossary_tooltip text="APIサーバー" term_id="kube-apiserver" >}}
```

2020-09-08 12:26 UTC, oke-py commented on content/ja/docs/reference/glossary/control-plane.md
> + * {{< glossary_tooltip text="Scheduler" term_id="kube-scheduler" >}}
```suggestion
 * {{< glossary_tooltip text="スケジューラー" term_id="kube-scheduler" >}}
```

2020-09-08 12:26 UTC, oke-py commented on content/ja/docs/reference/glossary/control-plane.md
> + * {{< glossary_tooltip text="Controller Manager" term_id="kube-controller-manager" >}}
```suggestion
 * {{< glossary_tooltip text="コントローラーマネージャー" term_id="kube-controller-manager" >}}
```

2020-09-08 12:26 UTC, oke-py commented on content/ja/docs/reference/glossary/control-plane.md
> + * {{< glossary_tooltip text="Cloud Controller Manager" term_id="cloud-controller-manager" >}}
```suggestion
 * {{< glossary_tooltip text="クラウドコントローラーマネージャー" term_id="cloud-controller-manager" >}}
```

2020-09-08 12:26 UTC, oke-py commented on content/ja/docs/reference/glossary/control-plane.md
> + これらのコンポーネントは従来のオペレーティングシステムサービス（デーモン）もしくはコンテナとして実行できます。これらのコンポーネントを実行するホストは歴史的に{{< glossary_tooltip text="マスター" term_id="master" >}}と呼ばれていました。
```suggestion
 これらのコンポーネントは従来のオペレーティングシステムサービス(デーモン)もしくはコンテナとして実行できます。これらのコンポーネントを実行するホストは歴史的に{{< glossary_tooltip text="マスター" term_id="master" >}}と呼ばれていました。
```

2020-09-09 03:03 UTC, yu-kasuya commented on content/ja/docs/reference/glossary/control-plane.md
> + このレイヤーは、次のような多くの異なるコンポーネントから構成されます。（しかし、これらに限定はされません）
ありがとうございます！半角見落としてました

2020-09-09 03:04 UTC, yu-kasuya commented on content/ja/docs/reference/glossary/control-plane.md
> + * {{< glossary_tooltip text="API Server" term_id="kube-apiserver" >}}
ここ迷ったのですが、K8sコンポーネントの説明でしたので英語表記そのままにしていました。日本語表記のほうがいいですかね？

2020-09-09 03:12 UTC, oke-py commented on content/ja/docs/reference/glossary/control-plane.md
> + * {{< glossary_tooltip text="API Server" term_id="kube-apiserver" >}}
仮にtextが`kube-apiserver`であればそのままですが、この場合は翻訳してよいと考えます。

2020-09-09 03:50 UTC, yu-kasuya commented on content/ja/docs/reference/glossary/control-plane.md
> + * {{< glossary_tooltip text="API Server" term_id="kube-apiserver" >}}
なるほど、修正ありがとうございます。

2020-09-09 08:22 UTC, inductor commented
/approve

2020-09-09 08:29 UTC, bells17 commented
/lgtm

2020-09-09 08:31 UTC, merged