Update ja/docs/reference/glossary/deployment.md
kubernetes/website pull request #23741
Opened 2020-09-08 03:32 UTC by yu-kasuya

Closes: #23342

2020-09-08 03:32 UTC, yu-kasuya commented
/assign @nasa9084

2020-09-08 12:25 UTC, kakts commented
対応ありがとうございます。
/lgtm

2020-09-09 01:46 UTC, inductor commented on content/ja/docs/reference/glossary/deployment.md
> + 複製されたアプリケーションを管理するAPIオブジェクトです、通常はローカル状態を持たないPodを実行します。
ローカル状態ってなんのことですかね？

2020-09-09 03:10 UTC, yu-kasuya commented on content/ja/docs/reference/glossary/deployment.md
> + 複製されたアプリケーションを管理するAPIオブジェクトです、通常はローカル状態を持たないPodを実行します。
違和感を覚えつつも、他の文でlocal stateをローカル状態と訳していたので揃えた、というところです。https://kubernetes.io/search/?q=%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E7%8A%B6%E6%85%8B
ステートレスとか意訳のほうがいいでしょうか

2020-09-09 08:15 UTC, inductor commented on content/ja/docs/reference/glossary/deployment.md
> + 複製されたアプリケーションを管理するAPIオブジェクトです、通常はローカル状態を持たないPodを実行します。
これは本家に物申しても良さそうな感じですねえ。

2020-09-13 10:17 UTC, inductor commented on content/ja/docs/reference/glossary/deployment.md
> + 複製されたアプリケーションを管理するAPIオブジェクトです、通常はローカル状態を持たないPodを実行します。
@yu-kasuya https://kubernetes.slack.com/archives/C1J0BPD2M/p1599694753085700?thread_ts=1599639480.081500&cid=C1J0BPD2M こちらご覧ください！

2020-09-15 03:09 UTC, yu-kasuya commented on content/ja/docs/reference/glossary/deployment.md
> + 複製されたアプリケーションを管理するAPIオブジェクトです、通常はローカル状態を持たないPodを実行します。
確認ありがとうございます、一旦ステートレス訳にしました。

2020-09-15 04:27 UTC, inductor commented
/approve

2020-09-16 04:35 UTC, oke-py requested changes

2020-09-16 04:35 UTC, oke-py commented on content/ja/docs/reference/glossary/deployment.md
> +各レプリカは{{< glossary_tooltip term_id="pod" >}}で表され、ポッドはクラスターの{{< glossary_tooltip text="ノード" term_id="node" >}}間で分散されます。
```suggestion
各レプリカは{{< glossary_tooltip text="Pod" term_id="pod" >}}で表され、Podはクラスターの{{< glossary_tooltip text="ノード" term_id="node" >}}間で分散されます。
```

2020-09-16 04:37 UTC, oke-py commented on content/ja/docs/reference/glossary/deployment.md
> + 複製されたアプリケーションを管理するAPIオブジェクトです、通常はステートレスなPodを実行します。
```suggestion
 複製されたアプリケーションを管理するAPIオブジェクトで、通常はステートレスなPodを実行します。
```
"で" or "であり"がよいかと思います。

2020-09-16 06:04 UTC, yu-kasuya commented on content/ja/docs/reference/glossary/deployment.md
> + 複製されたアプリケーションを管理するAPIオブジェクトです、通常はステートレスなPodを実行します。
切らないほうがいいですね、ありがとうございます

2020-09-17 18:24 UTC, bells17 commented
/lgtm

2020-09-17 18:26 UTC, merged