translate components.md
kubernetes/website pull request #23788
Opened 2020-09-10 10:18 UTC by shuzokato

updated japanese docs/concepts/overview/components.md to follow v1.18 of the original text.
this closes #23615 .

2020-09-10 10:24 UTC, shuzokato commented
/assign @inductor

2020-09-13 13:33 UTC, kakts requested changes
ご対応ありがとうございます。
2点コメントさせていただきました。

ご確認お願いいたします。

2020-09-13 13:33 UTC, kakts commented on content/ja/docs/concepts/overview/components.md
> +kube-controller-managerを使用すると、cloud-controller-managerは複数の論理的に独立したコントロールループをシングルバイナリにまとめ、これが一つのプロセスとして動作します。
https://github.com/kubernetes/website/blob/94b2f857bbef31cbfd3c8a433d8bb9aa572a4843/content/en/docs/concepts/overview/components.md
https://gist.github.com/kakts/4bbf133bc6397202519d1b64c9864d29#file-en-diff-L72-L73

原文を確認したところ、下記の文の訳が抜け落ちてそうです。こちらお手すきの際にご確認お願いいたします。

You can
+scale horizontally (run more than one copy) to improve performance or to help tolerate failures.

2020-09-13 13:33 UTC, kakts commented on content/ja/docs/concepts/overview/components.md
>    * ボリュームコントローラー：ボリュームを作成、アタッチ、マウントしたり、クラウドプロバイダーとやり取りしてボリュームを調整したりします。
https://github.com/kubernetes/website/blob/94b2f857bbef31cbfd3c8a433d8bb9aa572a4843/content/en/docs/concepts/overview/components.md
https://gist.github.com/kakts/4bbf133bc6397202519d1b64c9864d29#file-en-diff-L78-L84

こちら削除するのはボリュームコントローラーの方で、サービスコントローラーはそのまま残すのが正しいようです。

2020-09-17 11:28 UTC, shuzokato commented
@kakts 修正しました。確認よろしくお願いします。

2020-09-17 14:11 UTC, kakts commented
ご対応ありがとうございます!
/lgtm

2020-09-17 19:16 UTC, inductor commented
/approve

2020-09-17 19:17 UTC, inductor commented
/approve

2020-09-17 19:18 UTC, merged