Update ja/docs/reference/glossary/statefulset.md
kubernetes/website pull request #23780
Opened 2020-09-10 03:43 UTC by yu-kasuya

Closes: #23339

2020-09-10 03:43 UTC, yu-kasuya commented
/assign @nasa9084

2020-09-14 10:46 UTC, inductor requested changes

2020-09-14 10:46 UTC, inductor commented on content/ja/docs/reference/glossary/statefulset.md
> +  StatefulSetはDeploymentとPodのセットのスケーリングを管理します、永続化ストレージと各Podの永続的な識別子を備えています。
、の前後で主語が一緒には読めない感じになってるので、しますじゃなくてしのままでよさそうです。他にいい表現があれば、変えてもらってもいいです。

2020-09-15 03:13 UTC, yu-kasuya commented on content/ja/docs/reference/glossary/statefulset.md
> +  StatefulSetはDeploymentとPodのセットのスケーリングを管理します、永続化ストレージと各Podの永続的な識別子を備えています。
たしかに、そのままに修正しました

2020-09-17 18:21 UTC, bells17 commented
/lgtm

2020-09-17 19:20 UTC, inductor commented
/approve

2020-09-17 19:24 UTC, merged