ja: Make docs/concepts/overview/kubernetes-api.md follow v1.18 of the original text
kubernetes/website pull request #23784
Opened 2020-09-10 07:47 UTC by yoichiro0217

Updated docs/concepts/overview/kubernetes-api.md to follow v1.18 of the original text #23614

2020-09-10 07:52 UTC, yoichiro0217 commented
I signed it

2020-09-10 09:12 UTC, yoichiro0217 commented
I signed it

2020-09-10 09:16 UTC, yoichiro0217 commented
/assign @inductor

2020-09-10 15:01 UTC, inductor reviewed
念の為手元でも動作確認をお願いします～！

もし既にやっていて問題ないのであれば、その旨も合わせてご記載いただけますと！

2020-09-10 15:01 UTC, inductor commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +Kubernetesの中核である' {{< glossary_tooltip text="control plane" term_id="control-plane" >}}は{{< glossary_tooltip text="API server" term_id="kube-apiserver" >}} です。
ここの ' って必要なやつでしたっけ？

2020-09-12 01:04 UTC, yoichiro0217 commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +Kubernetesの中核である' {{< glossary_tooltip text="control plane" term_id="control-plane" >}}は{{< glossary_tooltip text="API server" term_id="kube-apiserver" >}} です。
失礼しました、英文のアポストロフィーが残ってました。除去しました。

2020-09-12 01:04 UTC, yoichiro0217 commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +**OpenAPI 仕様 {#api-specification}
こちらスペース必要ですね、あとシャープでした。修正しました。

2020-09-16 14:13 UTC, kakts requested changes
ご対応ありがとうございます。

1点コメントしました。ご確認お願いいたします。

2020-09-16 14:13 UTC, kakts commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +
https://gist.github.com/kakts/1882249d15967974d281d8abf7090562#file-en-diff-L79-L80

>Complete API details are documented using [OpenAPI](https://www.openapis.org/).

こちらの文の訳が抜けているようです。ご確認お願いいたします。

2020-09-18 08:57 UTC, yoichiro0217 commented on content/ja/docs/concepts/overview/kubernetes-api.md
> +
失礼しました、修正いたしました。

2020-09-18 09:05 UTC, yoichiro0217 commented
コメントありがとうございます、手元でも確認しました。
お手数ですが、ご確認をお願いします。

2020-09-19 01:33 UTC, kakts commented
ご対応ありがとうございます
/lgtm

2020-09-19 03:22 UTC, inductor commented
/approve

2020-09-19 03:24 UTC, merged