Make docs/tasks/_index.md follow v1.18 of the original text
kubernetes/website pull request #23789
Opened 2020-09-10 13:29 UTC by shuuji3

Closes #23296

2020-09-10 13:46 UTC, shuuji3 commented
/assign @inductor

2020-09-10 14:58 UTC, inductor commented
@shuuji3 
ローカルで確認したとき、 https://kubernetes.io/docs/tasks/ と同じ挙動になってますか？

結構差分がデカイので一応確認。

2020-09-10 15:18 UTC, shuuji3 commented
日本語ページが存在する項目はちゃんと表示されているので、問題なさそうです。

![localhost_1313_ja_docs_tasks_](https://user-images.githubusercontent.com/1425259/92752435-e5ee6680-f3c3-11ea-83af-ffad0f3a3de7.png)

(説明が空欄になっている項目は、少し前のPRがマージされれば表示されるようになるはずです)

2020-09-13 10:12 UTC, oke-py requested changes

2020-09-13 10:12 UTC, oke-py commented on content/ja/docs/tasks/_index.md
> +タスクページを作成したい場合は、[ドキュメントのPull Requestの作成](/docs/home/contribute/create-pull-request/)を参照してください。
```suggestion
タスクページを作成したい場合は、[ドキュメントのPull Requestの作成](/docs/contribute/new-content/open-a-pr/)を参照してください。
```
https://gist.github.com/oke-py/d782f14f5dcb26b31e7c920755870f31#file-en-diff-L90

2020-09-13 10:17 UTC, shuuji3 commented on content/ja/docs/tasks/_index.md
> +タスクページを作成したい場合は、[ドキュメントのPull Requestの作成](/docs/home/contribute/create-pull-request/)を参照してください。
すみません、見逃していました。ありがとうございます。

2020-09-13 10:18 UTC, oke-py approved these changes
/lgtm

2020-09-13 10:27 UTC, inductor commented
/close

2020-09-13 10:29 UTC, shuuji3 commented
@inductor あれ、コマンドが間違っていませんか？

2020-09-13 10:51 UTC, inductor commented
あ、まちがえた

2020-09-13 10:51 UTC, inductor commented
/approve

2020-09-13 10:52 UTC, merged