Update ja/docs/tasks/administer-cluster/enabling-endpointslices.md
kubernetes/website pull request #23805
Opened 2020-09-11 03:57 UTC by yu-kasuya

Closes: #23370

2020-09-11 03:57 UTC, yu-kasuya commented
/assign @inductor

2020-09-14 10:53 UTC, inductor commented on content/ja/docs/tasks/administer-cluster/enabling-endpointslices.md
> +EndpoitSliceはベータ版の機能です。APIとEndpointSlice{{< glossary_tooltip text="コントローラー" term_id="controller" >}}はデフォルトで有効です。{{<  glossary_tooltip text="kube-proxy" term_id="kube-proxy" >}}はデフォルトでEndpointを使用します、E
```suggestion
EndpoitSliceはベータ版の機能です。APIとEndpointSlice{{< glossary_tooltip text="コントローラー" term_id="controller" >}}はデフォルトで有効です。{{<  glossary_tooltip text="kube-proxy" term_id="kube-proxy" >}}はデフォルトでEndpointSliceではなくEndpointを使用します。
```

2020-09-14 12:47 UTC, oke-py requested changes

2020-09-14 12:47 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/enabling-endpointslices.md
> +スケーラビリティと性能向上のため、kube-proxy上で`EndpointSliceProxying`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)を有効にできます。この変更はデータソースをEndpointSliceに移します、これはkube-proxyとKubernetesAPI間のトラフ
```suggestion
スケーラビリティと性能向上のため、kube-proxy上で`EndpointSliceProxying`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)を有効にできます。この変更はデータソースをEndpointSliceに移します、これはkube-proxyとKubernetes API間のトラフィックの量を削減します。
```

2020-09-14 12:47 UTC, oke-py commented on content/ja/docs/tasks/administer-cluster/enabling-endpointslices.md
> +EndpoitSliceはベータ版の機能です。APIとEndpointSlice{{< glossary_tooltip text="コントローラー" term_id="controller" >}}はデフォルトで有効です。{{<  glossary_tooltip text="kube-proxy" term_id="kube-proxy" >}}はデフォルトでEndpointを使用します、E
```suggestion
EndpoitSliceはベータ版の機能です。APIとEndpointSlice{{< glossary_tooltip text="コントローラー" term_id="controller" >}}はデフォルトで有効です。{{<  glossary_tooltip text="kube-proxy" term_id="kube-proxy" >}}はデフォルトでEndpointSliceではなくEndpointsを使用します。
```
ちょっと厄介ですが、Endpointsリソースは"s"が必要です。

2020-09-15 03:15 UTC, yu-kasuya commented on content/ja/docs/tasks/administer-cluster/enabling-endpointslices.md
> +EndpoitSliceはベータ版の機能です。APIとEndpointSlice{{< glossary_tooltip text="コントローラー" term_id="controller" >}}はデフォルトで有効です。{{<  glossary_tooltip text="kube-proxy" term_id="kube-proxy" >}}はデフォルトでEndpointを使用します、E
修正ありがとうございます。

2020-09-15 03:34 UTC, inductor commented
/approve

2020-09-15 03:42 UTC, oke-py approved these changes
/lgtm

2020-09-15 03:44 UTC, merged