Update ja/docs/tasks/administer-cluster/coredns.md
kubernetes/website pull request #23803
Opened 2020-09-11 03:23 UTC by yu-kasuya

Closes: #23368

2020-09-11 03:24 UTC, yu-kasuya commented
/assign @nasa9084

2020-09-13 04:54 UTC, kakts requested changes
ご対応ありがとうございます。

こちらご確認お願いいたします。

2020-09-13 04:54 UTC, kakts commented on content/ja/docs/tasks/administer-cluster/coredns.md
> +Kubernetes 1.18では、kubeadmでのkube-dns使用は非推奨となり、将来のバージョンではは削除されます。
```suggestion
Kubernetes 1.18では、kubeadmでのkube-dns使用は非推奨となり、将来のバージョンでは削除されます。
```

2020-09-15 02:58 UTC, yu-kasuya commented on content/ja/docs/tasks/administer-cluster/coredns.md
> +Kubernetes 1.18では、kubeadmでのkube-dns使用は非推奨となり、将来のバージョンではは削除されます。
ありがとうございます

2020-09-16 15:13 UTC, kakts commented
ご対応ありがとうございます
/lgtm

2020-09-17 10:16 UTC, inductor approved these changes
/approve

2020-09-17 10:16 UTC, merged