ja: Make docs/setup/best-practices/multiple-zones.md follow v1.18 of the original text
kubernetes/website pull request #23848
Opened 2020-09-13 13:02 UTC by shuzokato

translated japanese docs/setup/best-practices/multiple-zones.md to follow v1.18 of the original text.
This closes #23640 .

2020-09-13 16:07 UTC, kakts requested changes
ご対応ありがとうございます。
コメントしました、ご確認お願いいたします。

2020-09-13 16:07 UTC, kakts commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +それでは、現存のマスターを再利用して現存のクラスターにもう１つのノードのセットを追加しましょう。
```suggestion
それでは、現存のマスターを再利用し、現存のクラスターの異なるゾーン(us-central1-bかus-west-2b)にもう１つのノードのセットを追加しましょう。
```

>Let's add another set of nodes to the existing cluster, reusing the
existing master, running in a different zone (us-central1-b or us-west-2b).

running in a different zone (us-central1-b or us-west-2b)
この文の意味が抜けておりました。ご確認お願いします。

2020-09-14 00:23 UTC, joey95033 approved these changes

2020-09-14 05:15 UTC, shuzokato commented
レビューありがとうございます。反映しました。

2020-09-14 05:49 UTC, shuzokato commented
/assign @nasa9084

2020-09-14 16:31 UTC, kakts commented
ありがとうございます! 修正内容確認しました
/lgtm

2020-09-15 01:32 UTC, inductor requested changes

2020-09-15 01:32 UTC, inductor commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +Kubernetes 1.2は複数のゾーンにおいて単一のクラスターを運用するサポートを追加しました(GCEでは単純に"ゾーン"，AWSは"アベイラビリティゾーン"と呼びますが、ここでは"ゾーン"とします)。
翻訳としては正しいんですが、日本語として正しいのかが気になる文でした（指摘というよりは感想ですが）

2020-09-15 01:32 UTC, inductor commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +これは、より範囲の広いCluster Federationの軽量バージョンです(以前は["Ubernetes"](https://github.com/kubernetes/community/blob/{{< param "githubbranch" >}}/contributors/design-proposals/multicluster/federation.md)の愛称で言及されていま
（この箇所単体ではなく全体ですが）Markdownの仕様で、改行を１行だけ挟むと半角スペースが入ってしまうというのは一応ご留意ください。

許容するかしないかみたいな話はレビュアーの中でも意見が別れている部分なので、ご自身が気になるようであれば直していただければ大丈夫ですし、やらなくても大丈夫です。

2020-09-15 01:32 UTC, inductor commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +マルチゾーンサポートは故意に限定されています: １つのKubernetesクラスターは複数のゾーンで運用することができますが、同じリージョン(あるいはクラウドプロバイダー)のみです。現在はGCEとAWSのみが自動的にサポートされています(他のクラウドプロバイダーやベアメタル環境においても、単にノードやボリュームに追加する適切なラベルを用意して同様のサポートを追加することは容易ではありますが)。
https://kubernetes.io/ja/docs/contribute/localization/#翻訳スタイルガイド に `数字とアルファベットは半角で表記` とあります。ご確認ください！（ここ以外にも全角数字ありそうでした～）

2020-09-17 11:49 UTC, shuzokato commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +Kubernetes 1.2は複数のゾーンにおいて単一のクラスターを運用するサポートを追加しました(GCEでは単純に"ゾーン"，AWSは"アベイラビリティゾーン"と呼びますが、ここでは"ゾーン"とします)。
直すとしたら，サポートが追加されました。のように受け身にするとかですか？

2020-09-17 11:49 UTC, shuzokato commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +マルチゾーンサポートは故意に限定されています: １つのKubernetesクラスターは複数のゾーンで運用することができますが、同じリージョン(あるいはクラウドプロバイダー)のみです。現在はGCEとAWSのみが自動的にサポートされています(他のクラウドプロバイダーやベアメタル環境においても、単にノードやボリュームに追加する適切なラベルを用意して同様のサポートを追加することは容易ではありますが)。
こちらは修正しました。

2020-09-17 11:52 UTC, shuzokato commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +これは、より範囲の広いCluster Federationの軽量バージョンです(以前は["Ubernetes"](https://github.com/kubernetes/community/blob/{{< param "githubbranch" >}}/contributors/design-proposals/multicluster/federation.md)の愛称で言及されていま
了解しました。現状，そのままにしております。

2020-09-17 13:15 UTC, inductor commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +Kubernetes 1.2は複数のゾーンにおいて単一のクラスターを運用するサポートを追加しました(GCEでは単純に"ゾーン"，AWSは"アベイラビリティゾーン"と呼びますが、ここでは"ゾーン"とします)。
主語がKubernetes 1.2はだとすると追加されましただと主述関係が食い違ってしまう感じがすると思うので、やるならKubernetes 1,2から追加されました、とか、Kubernetes 1,2からサポートされました、のようにすると良さそうな気がします。

2020-09-19 03:33 UTC, inductor commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +Kubernetes 1.2は複数のゾーンにおいて単一のクラスターを運用するサポートを追加しました(GCEでは単純に"ゾーン"，AWSは"アベイラビリティゾーン"と呼びますが、ここでは"ゾーン"とします)。
@shuzokato こちらいかがでしょ

2020-09-19 11:53 UTC, shuzokato commented on content/ja/docs/setup/best-practices/multiple-zones.md
> +Kubernetes 1.2は複数のゾーンにおいて単一のクラスターを運用するサポートを追加しました(GCEでは単純に"ゾーン"，AWSは"アベイラビリティゾーン"と呼びますが、ここでは"ゾーン"とします)。
@inductor 反映しました。確認お願いします！

2020-09-19 14:44 UTC, inductor commented
/lgtm
/approve

2020-09-19 14:46 UTC, merged