Update ja/docs/tasks/configure-pod-container/assign-cpu-resource.md
kubernetes/website pull request #23894
Opened 2020-09-15 03:55 UTC by yu-kasuya

Closes: #23373

2020-09-15 03:55 UTC, yu-kasuya commented
/assign @nasa9084

2020-09-16 04:10 UTC, oke-py requested changes
こちらの削除が漏れているようですのでご対応ください。
https://gist.github.com/oke-py/22a86d59137fa23e82d6ffed4a7e6ef7#file-en-diff-L64-L66

2020-09-16 06:03 UTC, yu-kasuya commented
確認ありがとうございます、該当行削除しました

2020-09-17 17:11 UTC, bells17 commented
/lgtm

2020-09-17 19:23 UTC, inductor commented
/approve

2020-09-17 19:26 UTC, merged