fixing FR language issues in page EndpointSlices
kubernetes/website pull request #23901
Opened 2020-09-15 11:05 UTC by didier-durand

Hello,

fixing FR language issues in page EndpointSlices

Best,

Didier
Signed-off-by: didier <durand.didier@gmail.com>

2020-09-15 11:06 UTC, didier-durand commented
/assign @anthonydahanne

2020-09-15 11:42 UTC, AWKIF requested changes

2020-09-15 11:42 UTC, AWKIF commented on content/fr/docs/concepts/services-networking/endpoint-slices.md
> +En dessous de cette échelle, EndpointSlices devraientt mapper 1:1 les Endpoints et les Services et devraientt avoir une performance similaire.
devraient**t**

2020-09-15 12:04 UTC, didier-durand commented on content/fr/docs/concepts/services-networking/endpoint-slices.md
> +En dessous de cette échelle, EndpointSlices devraientt mapper 1:1 les Endpoints et les Services et devraientt avoir une performance similaire.
Merci d'avoir trouvé cette erreur! Didier

2020-09-15 12:12 UTC, didier-durand commented
Bad commit message fixed

2020-09-16 08:50 UTC, remyleone commented
/lgtm
/approve

2020-09-16 09:01 UTC, merged

2020-09-16 09:20 UTC, didier-durand commented
@remyleone : merci! 
Didier