Translate concepts/storage/storage-capacity into Japanese
kubernetes/website pull request #23931
Opened 2020-09-17 01:37 UTC by shuuji3

Closes #23893.

2020-09-17 01:47 UTC, shuuji3 commented
/assign @inductor

Page preview: https://deploy-preview-23931--kubernetes-io-master-staging.netlify.app/concepts/storage/storage-capacity/

2020-09-17 18:10 UTC, bells17 reviewed
コメントしましたのでご確認お願いします。

2020-09-17 18:10 UTC, bells17 commented on content/ja/docs/concepts/storage/storage-capacity.md
> +volume binding modeが`Immediate`のボリュームの場合、ボリュームを使用するPodとは独立に、ストレージドライバーがボリュームの作成場所を決定します。次に、スケジューラーはボリュームが作成された後、Podをボリュームが利用できるノードにスケジューリングします。
```suggestion
volume binding modeが`Immediate`のボリュームの場合、ストレージドライバーはボリュームを使用するPodとは関係なく、ボリュームを作成する場所を決定します。次に、スケジューラーはボリュームが作成された後、Podをボリュームが利用できるノードにスケジューリングします。
```

2020-09-17 18:10 UTC, bells17 commented on content/ja/docs/concepts/storage/storage-capacity.md
> +`WaitForFirstConsumer`ボリュームがあるPodに対してノードが選択された場合は、その決定はまだ一時的なものです。次のステップで、CSIストレージドライバーに対して、選択されたノード上でボリュームが利用可能になることが予定されているというヒントを付きでボリュームの作成を要求します。
```suggestion
`WaitForFirstConsumer`ボリュームがあるPodに対してノードが選択された場合は、その決定はまだ一時的なものです。次のステップで、CSIストレージドライバーに対して、選択されたノード上でボリュームが利用可能になることが予定されているというヒントを使用してボリュームの作成を要求します。
```

2020-09-17 18:10 UTC, bells17 commented on content/ja/docs/concepts/storage/storage-capacity.md
> +スケジューリングが永続的に失敗する状況の1つは、Podが複数のボリュームを使用する場合で、あるトポロジーのセグメントで1つのボリュームがすでに作成された後、もう1つのボリュームのために十分な容量が残っていないような場合です。この状況から回復するには、たとえば、容量を増加させたり、すでに作成されたボリュームを削除するなどの手動の仲介が必要です。この問題に自動的に対処するためには、まだ[追加の作業]
"仲介"だとちょっとわかりずらい気がしました

```suggestion
スケジューリングが永続的に失敗する状況の1つは、Podが複数のボリュームを使用する場合で、あるトポロジーのセグメントで1つのボリュームがすでに作成された後、もう1つのボリュームのために十分な容量が残っていないような場合です。この状況から回復するには、たとえば、容量を増加させたり、すでに作成されたボリュームを削除するなどの手動での対応が必要です。この問題に自動的に対処するためには、まだ[追加の作業](https://github.com/kubernetes/enhancements/pull/1703)が必要となっています。
```

2020-09-24 08:48 UTC, nasa9084 commented
bells17さんの指摘以外LGTMです

2020-10-06 15:54 UTC, kakts requested changes

2020-10-06 15:54 UTC, kakts commented on content/ja/docs/concepts/storage/storage-capacity.md
> +
翻訳ありがとうございます!

> the CSIDriver object for the driver has StorageCapacity set to true.

ここの4つめの項目の訳が抜け落ちていましたので、こちらもご対応いただけますでしょうか。
https://github.com/kubernetes/website/blob/6d84df458ee50d01e0bcec19526689c424d0ba5b/content/en/docs/concepts/storage/storage-capacity.md

2020-11-02 11:42 UTC, shuuji3 commented on content/ja/docs/concepts/storage/storage-capacity.md
> +ストレージ容量は、Podが実行されるノードごとに制限があったり、大きさが異なる可能性があります。たとえば、NASがすべてのノードからはアクセスできなかったり、初めはストレージがノードローカルでしか利用できない可能性があります。
topolvmについて確認してからお返事しようと後回しにしていたら、だいぶ期間が空いてしまいまってすみません。

\[KubeConのtopolvmの発表スライド\](https://kccnceu20.sched.com/event/ZerD/capacity-aware-dynamic-volume-provisioning-for-lvm-local-storage-kazuhito-matsuda-satoru-takeuchi-cybozu)を読んでみたのですが、ここでもまさにこのKEPへの言及があったので、その想定は正しい気がします。topolvmを考えると、ご指摘の通り「初めから」というのが適切ですね。ありがとうございます。

2020-11-02 11:48 UTC, shuuji3 commented on content/ja/docs/concepts/storage/storage-capacity.md
> +
ご指摘ありがとうございます！ こちらの文も翻訳して追加しました。

2020-11-03 15:01 UTC, kakts commented
/lgtm

2020-11-03 15:03 UTC, inductor commented
/approve

2020-11-03 15:04 UTC, merged