Update japanese services-networking/service.md to follow v1.18 of the original (English) text
kubernetes/website pull request #24002
Opened 2020-09-19 09:53 UTC by tkms0106

#23596

2020-09-19 09:56 UTC, tkms0106 commented
/assign @nasa9084

2020-09-23 01:26 UTC, makocchi-git commented on content/ja/docs/concepts/services-networking/service.md
> +アルファ機能のため、このフィールドはデフォルトで有効化されていません。このフィールドを使用するには、 `ServiceAppProtocol` という[Feature gate](/docs/reference/command-line-tools-reference/feature-gates/)を有効化してください。
Feature gate は日本語にしてしまいましょうか
ついでにリンク先の日本語の方へ

```suggestion
アルファ機能のため、このフィールドはデフォルトで有効化されていません。このフィールドを使用するには、 `ServiceAppProtocol` という[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)を有効化してください。
```

2020-09-24 08:57 UTC, nasa9084 requested changes

2020-09-24 08:57 UTC, nasa9084 commented on content/ja/docs/concepts/services-networking/service.md
> +      # デフォルトでは利便性のため、Kubernetesコントロールプレーンはある範囲から1つポートを割り当てます（デフォルトの範囲：30000-32767）
```suggestion
      # デフォルトでは利便性のため、Kubernetesコントロールプレーンはある範囲から1つポートを割り当てます(デフォルト値の範囲：30000-32767)
```

ちょっと違和感ある気がしたので、なおしてみました　

2020-09-24 08:57 UTC, nasa9084 commented on content/ja/docs/concepts/services-networking/service.md
> +また、Kubernetesは（例えば、管理者の介入によって）無効な割り当てがされているかをチェックすることと、現時点でどのServiceにも使用されていない割り当て済みIPアドレスのクリーンアップのためにコントローラーを使用します。
```suggestion
また、Kubernetesは(例えば、管理者の介入によって)無効な割り当てがされているかをチェックすることと、現時点でどのServiceにも使用されていない割り当て済みIPアドレスのクリーンアップのためにコントローラーを使用します。
```

2020-09-25 03:16 UTC, makocchi-git commented
/lgtm

2020-09-28 01:50 UTC, inductor commented on content/ja/docs/concepts/services-networking/service.md
> +均等なトラフィックの分配を実現するために、DaemonSetの使用や、同一のNodeに配備しないように[Podのanti-affinity](/ja/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)を設定します。
このリンクが機能するか、念の為動作確認手元でしてもらってますでしょうか？

@tkms0106

2020-09-28 08:42 UTC, tkms0106 commented on content/ja/docs/concepts/services-networking/service.md
> +均等なトラフィックの分配を実現するために、DaemonSetの使用や、同一のNodeに配備しないように[Podのanti-affinity](/ja/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)を設定します。
すみません、未確認でした。:bow:
確認したところ、未翻訳ページだったようで404になっていました。
![image](https://user-images.githubusercontent.com/23391543/94409956-cc199580-01b1-11eb-9a70-7a6938a02f6c.png)

`/ja`を削って英語ページへのリンクに修正しようかと思います。
@inductor

2020-09-28 15:30 UTC, nasa9084 commented
/approve

2020-09-29 01:21 UTC, inductor commented on content/ja/docs/concepts/services-networking/service.md
> +均等なトラフィックの分配を実現するために、DaemonSetの使用や、同一のNodeに配備しないように[Podのanti-affinity](/ja/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)を設定します。
@tkms0106 おそらく、 `/ja/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity` のMarkdownファイルを `scheduling-eviction` ディレクトリに移さないといけないんだと思います。ただ、それは別Issueで対応すれば良さそうな気もしますので一旦はこの対応で大丈夫そうです。

2020-09-30 05:05 UTC, makocchi-git commented
/lgtm

2020-09-30 05:07 UTC, merged

2020-09-30 12:47 UTC, kakts commented
/lgtm 

ページ移行の件は別issueを立てます