ja: Make docs/reference/kubectl/overview.md follow v1.18 of the original text
kubernetes/website pull request #24000
Opened 2020-09-19 08:57 UTC by takaf04

Closes #23336

2020-09-19 08:57 UTC, takaf04 commented
/assign @nasa9084

2020-09-19 09:13 UTC, takaf04 commented
一点補足です。
68行目の`&nbsp;`は意図的に空白として入れてあります。
通常通り記述するとOperationのテーブルのOperation列が異様に狭くなり１文字分の幅に調整されてしまうため、コマンドが”縦書き”状態になってしまいます。
それだと見づらいので、英語版と同じ幅を確保させるよう意図的に空白を入れました。

**以下にわかりやすいようにイメージでまとめてみました**

- このように表示されてほしい

| 操作 |
| ---- |
| apply |

- 実際にはこうなってしまう

| 操作 |
| ---- |
| a<br>p<br>p<br>l<br>y|


他に代替案がありますでしょうか？
別案がありましたら対応しますのでいってください。

2020-09-24 08:51 UTC, nasa9084 requested changes

2020-09-24 08:51 UTC, nasa9084 commented on content/ja/docs/reference/kubectl/overview.md
> +reviewers:
reviewersブロックは完全に消してしまってください

2020-09-25 15:13 UTC, takaf04 commented on content/ja/docs/reference/kubectl/overview.md
> +reviewers:
reviewersブロック削除しました。
よろしくおねがいします。

2020-09-28 04:02 UTC, nasa9084 commented
テーブル幅はちょっとどうしたらいいのかわからないので
/approve

@inductor もし何かいい方法知ってたら教えて下さい...

2020-10-07 03:00 UTC, inductor commented
/lgtm

2020-10-07 03:02 UTC, merged