kubeadm: improve links and information around using the config file
kubernetes/website pull request #24076
Opened 2020-09-23 18:35 UTC by neolit123

- Add link from the kubeadm-config page to the paragraphs on
using "--config" with "init" and "join".
- Improve text in the the paragraphs on using "--config" with
"init" and "join".
- Reword the link about the configuration file in the
create-cluster-kubeadm page.

2020-09-23 18:35 UTC, neolit123 commented
/sig cluster-lifecycle
/kind cleanup

2020-09-23 18:50 UTC, yagonobre commented on content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
> +It's possible to configure `kubeadm init` with a configuration file instead of command
is it `kubeadm join`?

2020-09-23 19:09 UTC, neolit123 commented on content/en/docs/reference/setup-tools/kubeadm/kubeadm-join.md
> +It's possible to configure `kubeadm init` with a configuration file instead of command
yep, fixed.

2020-09-23 19:11 UTC, yagonobre commented
/lgtm

2020-09-23 19:15 UTC, neolit123 commented
thanks @yagonobre 

/assign @jimangel
PTAL for approval, thanks. (the bot suggested @kbarnard10 but not sure if she is still active).

2020-10-01 08:50 UTC, sftim commented
The branch name in @neolit123's fork implies the change might be for v1.20
/hold

@neolit123 can you confirm the branch this PR should target? Feel free to unhold after clarifying.

2020-10-01 11:04 UTC, neolit123 commented
Hi. No, the branch name is for me to track when I made a change.

/hold cancel

2020-10-01 11:34 UTC, sftim requested changes
One more thing to fix, sorry.

/lgtm cancel

2020-10-01 11:34 UTC, sftim commented on content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
> +or [Using kubeadm join with a configuration file](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/#config-file).
```suggestion
[Using kubeadm init with a configuration file](/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file)
or [Using kubeadm join with a configuration file](/docs/reference/setup-tools/kubeadm/kubeadm-join/#config-file).
```

2020-10-01 12:32 UTC, neolit123 commented
@sftim updated :+1:

2020-10-13 01:09 UTC, zparnold commented
/approve 
/lgtm

2020-10-13 01:11 UTC, merged