Jump to bottom ja: Make docs/concepts/extend-kubernetes/extend-cluster.md follow v1.18 of the original text
kubernetes/website pull request #24073
Opened 2020-09-23 15:12 UTC by shuzokato

translated docs/concepts/extend-kubernetes/extend-cluster.md to follow v1.18 of the original text.
This resolves #23617 .

2020-09-23 15:14 UTC, shuzokato commented
/assign @inductor

2020-09-24 15:28 UTC, kakts commented
私がissue作成した時に確認が漏れていたのですが、/docs/concepts/extend-kubernetes/_index.mdの方に今回のextend-cluster.mdとほぼ同じ内容のものが書かれており、対応どうするか検討中です

https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/extend-kubernetes/_index.md

https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/extend-kubernetes/extend-cluster.md

2020-09-24 15:34 UTC, kakts commented
@shuzokato 
対応ありがとうございます。
こちらの件で、英語原文では、下記の extend-kubernetes/_index.mdの方にもほぼ同じ内容（先頭のdescriptionの項目などが違うのみ)のものがあり、お手数ですが、_index.mdの方の日本語訳も対応お願いできますでしょうか。

https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/concepts/extend-kubernetes/_index.md

https://raw.githubusercontent.com/kubernetes/website/master/content/en/docs/concepts/extend-kubernetes/extend-cluster.md

2020-09-25 00:17 UTC, shuzokato commented
@kakts  上記の件了解しました。

2020-09-25 11:01 UTC, shuzokato commented
https://github.com/kubernetes/website/pull/24128
@kakts こちらで対応しました。

2020-09-27 02:53 UTC, kakts commented
ありがとうございます！

2020-09-27 02:55 UTC, kakts commented
/lgtm

2020-09-27 06:09 UTC, inductor requested changes

2020-09-27 06:09 UTC, inductor commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +2.   APIサーバーは全てのリクエストを処理します。APIサーバーのいくつかの拡張ポイントは、リクエストを認可する、コンテキストに基づいてブロックする、リクエストを編集する、そして削除を処理することを可能にします。これらは[APIアクセスエクステンション](/docs/concepts/extend-kubernetes/#api-access-extensions)セクションに記載されてい
このへんってもう１つのIssueが解消されたら日本語ページにできますよね。

2020-09-27 06:09 UTC, inductor commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +2.   APIサーバーは全てのリクエストを処理します。APIサーバーのいくつかの拡張ポイントは、リクエストを認可する、コンテキストに基づいてブロックする、リクエストを編集する、そして削除を処理することを可能にします。これらは[APIアクセスエクステンション](/docs/concepts/extend-kubernetes/#api-access-extensions)セクションに記載されてい
@kakts

2020-10-06 15:00 UTC, kakts commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +2.   APIサーバーは全てのリクエストを処理します。APIサーバーのいくつかの拡張ポイントは、リクエストを認可する、コンテキストに基づいてブロックする、リクエストを編集する、そして削除を処理することを可能にします。これらは[APIアクセスエクステンション](/docs/concepts/extend-kubernetes/#api-access-extensions)セクションに記載されてい
@inductor 
すいませんここのコメント見落としていました。

こちらのPRがマージされれば、日本語ページへのリンクにできます!
https://github.com/kubernetes/website/pull/24128/files#diff-2a3088323619c6cbc7f0c4251b616968R107

原文
https://github.com/kubernetes/website/blob/master/content/en/docs/concepts/extend-kubernetes/_index.md#api-access-extensions

2020-10-10 11:24 UTC, nasa9084 commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +[ResourceQuota](/ja/docs/concepts/policy/resource-quotas/)、[PodSecurityPolicy](/docs/concepts/policy/pod-security-policy/)、[NetworkPolicy](/docs/concepts/services-networking/network-policies/)、そしてロール
```suggestion
[ResourceQuota](/ja/docs/concepts/policy/resource-quotas/)、[PodSecurityPolicy](/docs/concepts/policy/pod-security-policy/)、[NetworkPolicy](/docs/concepts/services-networking/network-policies/)、そしてロールベースアクセス制御([RBAC](/docs/reference/access-authn-authz/rbac/))といった *ビルトインポリシーAPI* は、ビルトインのKubernetes APIです。APIは通常、ホスティングされたKubernetesサービスやマネージドなKubernetesで利用されます。これらは宣言的で、Podのような他のKubernetesリソースと同じ慣例に従っています。そのため、新しいクラスターの設定は繰り返し再利用することができ、アプリケーションと同じように管理することが可能です。さらに、安定版(stable)を利用している場合、他のKubernetes APIのような[定義済みのサポートポリシー](/docs/reference/using-api/deprecation-policy/)を利用することができます。これらの理由により、この方法は、適切な用途の場合、 *設定ファイル* や *フラグ* よりも好まれます。
```

2020-10-17 15:10 UTC, nasa9084 commented
#24128 待ち
/hold

2020-10-17 17:35 UTC, inductor requested changes

2020-10-17 17:35 UTC, inductor commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +2.   APIサーバーは全てのリクエストを処理します。APIサーバーのいくつかの拡張ポイントは、リクエストを認可する、コンテキストに基づいてブロックする、リクエストを編集する、そして削除を処理することを可能にします。これらは[APIアクセスエクステンション](/docs/concepts/extend-kubernetes/#api-access-extensions)セクションに記載されてい
```suggestion
2.   APIサーバーは全てのリクエストを処理します。APIサーバーのいくつかの拡張ポイントは、リクエストを認可する、コンテキストに基づいてブロックする、リクエストを編集する、そして削除を処理することを可能にします。これらは[APIアクセスエクステンション](/ja/docs/concepts/extend-kubernetes/#api-access-extensions)セクションに記載されています。
```

2020-10-17 17:35 UTC, inductor commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +3.   APIサーバーは様々な種類の *リソース* を扱います。`Pod`のような *ビルトインリソース* はKubernetesプロジェクトにより定義され、変更できません。ユーザーも、自身もしくは、他のプロジェクトで定義されたリソースを追加することができます。それは *カスタムリソース* と呼ばれ、[カスタムリソース](/docs/concepts/extend-kubernetes/#us
```suggestion
3.   APIサーバーは様々な種類の *リソース* を扱います。`Pod`のような *ビルトインリソース* はKubernetesプロジェクトにより定義され、変更できません。ユーザーも、自身もしくは、他のプロジェクトで定義されたリソースを追加することができます。それは *カスタムリソース* と呼ばれ、[カスタムリソース](/ja/docs/concepts/extend-kubernetes/#user-defined-types)セクションに記載されています。カスタムリソースは度々、APIアクセスエクステンションと一緒に使われます。
```

2020-10-17 17:35 UTC, inductor commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +4.   KubernetesのスケジューラーはPodをどのノードに配置するかを決定します。スケジューリングを拡張するには、いくつかの方法があります。それらは[スケジューラーエクステンション](/docs/concepts/extend-kubernetes/#scheduler-extensions)セクションに記載されています。
```suggestion
4.   KubernetesのスケジューラーはPodをどのノードに配置するかを決定します。スケジューリングを拡張するには、いくつかの方法があります。それらは[スケジューラーエクステンション](/ja/docs/concepts/extend-kubernetes/#scheduler-extensions)セクションに記載されています。
```

2020-10-17 17:35 UTC, inductor commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +6.   kubeletはサーバー上で実行され、Podが仮想サーバーのようにクラスターネットワーク上にIPを持った状態で起動することをサポートします。[ネットワークプラグイン](/docs/concepts/extend-kubernetes/#network-plugins)がPodのネットワーキングにおける異なる実装を適用することを可能にします。
```suggestion
6.   kubeletはサーバー上で実行され、Podが仮想サーバーのようにクラスターネットワーク上にIPを持った状態で起動することをサポートします。[ネットワークプラグイン](/ja/docs/concepts/extend-kubernetes/#network-plugins)がPodのネットワーキングにおける異なる実装を適用することを可能にします。
```

2020-10-17 17:35 UTC, inductor commented on content/ja/docs/concepts/extend-kubernetes/extend-cluster.md
> +7.   kubeletはまた、コンテナのためにボリュームをマウント、アンマウントします。新しい種類のストレージは[ストレージプラグイン](/docs/concepts/extend-kubernetes/#storage-plugins)を通じてサポートされます。
```suggestion
7.   kubeletはまた、コンテナのためにボリュームをマウント、アンマウントします。新しい種類のストレージは[ストレージプラグイン](/ja/docs/concepts/extend-kubernetes/#storage-plugins)を通じてサポートされます。
```

2020-10-23 02:48 UTC, nasa9084 commented
/unhold

2020-10-23 08:08 UTC, inductor commented
/approve

2020-10-30 15:03 UTC, nasa9084 commented
/lgtm

2020-10-30 15:04 UTC, merged