ja: Make docs/concepts/extend-kubernetes/_index.md follow v1.18 of the original text
kubernetes/website pull request #24128
Opened 2020-09-25 11:00 UTC by shuzokato

updated docs/concepts/extend-kubernetes/_index.md tp follow v1.18 of the original text.
This closes #23620 .

2020-09-25 11:03 UTC, shuzokato commented
/assign @nasa9084

2020-09-27 02:54 UTC, kakts commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +- chenopis
こちらのreviewersの項目は削除して大丈夫ですー

2020-09-27 03:43 UTC, shuzokato commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +- chenopis
修正しました！

2020-09-28 04:09 UTC, nasa9084 requested changes
行がダブってたり、diffの行表示みたいな物が残っちゃったりしてるので、全体的に修正が必要だと思いますので、一旦レビュー止めときます

2020-09-28 04:09 UTC, nasa9084 commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +## 概要
configuration / extension は 設定 / 拡張 でどうでしょうか (技術文書はカタカナ語が増えがちなので、できるだけ訳せる物は訳したい、という意図があります)

2020-09-28 04:09 UTC, nasa9084 commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +[ResourceQuota](/docs/concepts/policy/resource-quotas/)、[PodSecurityPolicy](/docs/concepts/policy/pod-security-policy/)、[NetworkPolicy](/docs/concepts/services-networking/network-policies/)、そしてロールベース
下の行とダブってますね
他にもいくつかあるようなので、修正お願いします

2020-09-28 04:09 UTC, nasa9084 commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +@@ -58,7 +58,7 @@ Kubernetes上でうまく動くクライアントプログラムを書くため
diffのコピペっぽい物が残っちゃってます
以下同様

2020-09-30 12:35 UTC, shuzokato commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +[ResourceQuota](/docs/concepts/policy/resource-quotas/)、[PodSecurityPolicy](/docs/concepts/policy/pod-security-policy/)、[NetworkPolicy](/docs/concepts/services-networking/network-policies/)、そしてロールベース
レビューありがとうございます！すみません，修正します！

2020-10-02 22:19 UTC, shuzokato commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +## 概要
修正しました。

2020-10-07 03:07 UTC, nasa9084 commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +[ResourceQuota](/docs/concepts/policy/resource-quotas/)、[PodSecurityPolicy](/docs/concepts/policy/pod-security-policy/)、[NetworkPolicy](/docs/concepts/services-networking/network-policies/)、そしてロールベース
ここ、ダブってるの残ってます〜

2020-10-07 03:13 UTC, kakts commented
/lgtm

2020-10-08 03:13 UTC, inductor commented
まだこれがあるのでhold

/hold

![image](https://user-images.githubusercontent.com/20236173/95410724-b0578180-095f-11eb-87d9-140932a7d4e5.png)

2020-10-10 05:10 UTC, shuzokato commented on content/ja/docs/concepts/extend-kubernetes/_index.md
> +[ResourceQuota](/docs/concepts/policy/resource-quotas/)、[PodSecurityPolicy](/docs/concepts/policy/pod-security-policy/)、[NetworkPolicy](/docs/concepts/services-networking/network-policies/)、そしてロールベース
遅くなりすみません，こちら修正しました！

2020-10-17 15:08 UTC, nasa9084 commented
/unhold
/approve

2020-10-17 17:19 UTC, inductor commented
/lgtm

2020-10-17 17:22 UTC, merged