ID localization for administrator cluster - cluster management
kubernetes/website pull request #24356
Opened 2020-10-03 12:46 UTC by ariscahyadi

This PR is addressing `/docs/tasks/administer-cluster/cluster-management` as mentioned in #22296.

Previously, it was claimed by @phanama but it seems not completed yet.

2020-10-03 12:51 UTC, irvifa requested changes
There’s typo that I see and it’s minor. Thanks for the contribution 😀

2020-10-03 12:51 UTC, irvifa commented on content/id/docs/tasks/administer-cluster/cluster-management.md
> +## Membuat dan mengonfigurasi klasterter
```suggestion
## Membuat dan mengonfigurasi klaster
```

2020-10-07 14:55 UTC, ariscahyadi commented
@irvifa and @girikuncoro the issue has been addressed. Please approve!

2020-10-07 15:05 UTC, irvifa commented
Thank you!
/lgtm
/approve

2020-10-07 15:06 UTC, merged