ja: Make docs/reference/kubectl/cheatsheet.md follow v1.18 of the original text
kubernetes/website pull request #24384
Opened 2020-10-05 15:14 UTC by takaf04

Closes #23337

2020-10-05 15:15 UTC, takaf04 commented
/assign @nasa9084

2020-10-06 15:13 UTC, kakts requested changes

2020-10-06 15:13 UTC, kakts commented on content/ja/docs/reference/kubectl/cheatsheet.md
> +# 現在のネームスペースでrunning状態のPodのリストを表示します
```suggestion
# 現在の名前空間でrunning状態のPodのリストを表示します
```

すいません、このページでもともとNamespace➡️ネームスペース　となっていたのですが、
他のページの役では名前空間となっており、名前空間に変更いただけますでしょうか。
このページに他にいくつかネームスペースの記載があるので、それも合わせて修正していただけますと幸いです。

参考
https://github.com/kubernetes/website/search?q=%E5%90%8D%E5%89%8D%E7%A9%BA%E9%96%93

2020-10-07 11:54 UTC, takaf04 commented on content/ja/docs/reference/kubectl/cheatsheet.md
> +kkubectl run nginx --image=nginx                    # nginx Podを実行し、マニフェストファイルをpod.yamlという名前で書き込みます
レビューありがとうございます。
余計な文字が混ざっておりました。除去します。

2020-10-07 12:15 UTC, takaf04 commented on content/ja/docs/reference/kubectl/cheatsheet.md
> +# 現在のネームスペースでrunning状態のPodのリストを表示します
このページに含まれている全部の「ネームスペース」を「名前空間」に変更しました。
引き続き確認お願いいたします。

2020-10-17 15:12 UTC, nasa9084 commented
/approve

2020-10-17 15:14 UTC, merged