[zh] Translate configure-gmsa into Chinese
kubernetes/website pull request #24634
Opened 2020-10-19 06:09 UTC by tengqm

closes: #24503 
/language zh

2020-10-20 12:51 UTC, howieyuen requested changes

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +本节讨论需要为每个集群执行一次的初始操作。
本节讨论需要为每个集群执行一组的初始操作。

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +1. 一个修改模式（Mutating）的 Webhook，将对 GMSA 的引用（在 Pod 规约中提现为名字）
1. 一个修改模式（Mutating）的 Webhook，将对 GMSA 的引用（在 Pod 规约中体现为名称）

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +### 安装 GMSACredentialSpec CRD
### 安装 GMSACredentialSpec CRD  {#install-the-GMSACredentialSpec-CRD}

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +### 安装 Webhook 来验证 GMSA 用户
same as above, anchor is missing

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +## 在活动目录中配置 GMSA 和 Windows 节点
anchor

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +## 创建 GMSA 凭据规约资源
anchor

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +## 配置集群角色以启用对特定 GMSA 凭据规约的 RBAC
anchor

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +该集群角色授权某主体（通常是一个服务账号）对特定的 GMSA 资源执行 `use` 动词。
该集群角色授权某主体（通常是一个服务账号）对特定的 GMSA 资源执行 `use` 操作。

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +## 将角色指派给要使用特定 GMSA 凭据规约的服务账号
anchor

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +## 在 Pod 规约中配置 GMSA 凭据规约引用
anchor

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +   上使用 `use` 动词。
上使用 `use` 操作。

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +1. 容器运行时为每个 Windows 容器配置所给的 GMSA 凭据规约，这样容器就可以以
容器运行时为每个 Windows 容器配置指定的 GMSA 凭据规约，这样容器就可以以

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +## 故障排查
anchor

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +如果 DNS 和通信测试通过，接下来你需要检查是否 Pod 已经与域之间建立了
如果 DNS 和通信测试通过，接下来你需要检查 Pod 是否已经与域之间建立了

2020-10-20 12:51 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +## GMSA 的局限
anchor

2020-10-20 13:38 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +本节讨论需要为每个集群执行一次的初始操作。
这里强调的是一次，不是一组。

2020-10-20 13:40 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +1. 一个修改模式（Mutating）的 Webhook，将对 GMSA 的引用（在 Pod 规约中提现为名字）
done

2020-10-20 13:40 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +### 安装 GMSACredentialSpec CRD
doesn't matter, because no one would link to this subsection I assume.

2020-10-20 13:42 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +   上使用 `use` 动词。
如果译为操作，则需要改成”执行 use 操作“，这又与原文的含义有出入。
所以决定忠实原文语义，译为"使用 ... 动词"。

2020-10-20 13:43 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +该集群角色授权某主体（通常是一个服务账号）对特定的 GMSA 资源执行 `use` 动词。
同上。

2020-10-20 13:45 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/configure-gmsa.md
> +该集群角色授权某主体（通常是一个服务账号）对特定的 GMSA 资源执行 `use` 动词。
决定译为 ”执行 use 动作"。

2020-10-21 01:26 UTC, howieyuen commented
/lgtm
thanks

2020-10-21 01:28 UTC, merged