[zh] Translate docs/tasks/configure-pod-container/configure-gmsa.md
kubernetes/website pull request #24674
Opened 2020-10-22 03:28 UTC by tengqm

closes: #24507

2020-10-25 01:01 UTC, markthink reviewed
/lgtm
/approve

2020-11-12 02:52 UTC, tengqm commented
/assign @howieyuen

2020-11-12 08:15 UTC, howieyuen requested changes

2020-11-12 08:15 UTC, howieyuen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +对 Windows 而言，在 Kubernetes 中使用 IPv6 需要
add {{note}} short code

2020-11-12 08:15 UTC, howieyuen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +目前 Windows 上的覆盖网络（VXLAN）还不支持双协议栈联网。
add {{note}} short code

2020-11-12 11:46 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +关于不同的 Windows Server 版本的服务渠道，包括其支持模式等相关信息可以在
这些 note 短代码没有必要，而且在 markdown 中输入与维护都是额外的 effort。
在翻译的时候是有意去掉的。

2020-11-12 11:46 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +我们并不指望所有 Windows 客户都为其应用频繁地更新操作系统。
同上。

2020-11-12 11:46 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +Windows Server 主机操作系统会受 [Windows Server](https://www.microsoft.com/en-us/cloud-platform/windows-server-pricing)
同上。

2020-11-12 11:46 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +带进程隔离的 Windows 容器受一些严格的兼容性规则约束，
同上。

2020-11-12 11:46 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +授权策略控制。Windows 容器镜像则遵从
同上。

2020-11-12 11:47 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +[局限性节](#limitations)中。
OK

2020-11-12 11:47 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +  最小、最简单单元。你不可以在同一 Pod 中部署 Windows 和 Linux 容器。
OK

2020-11-12 11:49 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +对 Windows 而言，在 Kubernetes 中使用 IPv6 需要
同上。

2020-11-12 11:50 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +目前 Windows 上的覆盖网络（VXLAN）还不支持双协议栈联网。
同上。

2020-11-12 16:16 UTC, howieyuen commented
/lgtm

2020-12-04 16:33 UTC, tanjunchen reviewed
big thanks for your work. thank you.
/lgtm   except for some issues

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +| 透明网络（[ovn-kubernetes](https://github.com/openvswitch/ovn-kubernetes) 的特殊用例） | 需要一个外部 vSwitch。容器挂接到某外部 vSwitch 上，该 vSwitch 通过逻辑网络（逻辑交换机和路由器）允许 Pod 间通信。 | 报文或者通过 [GENEVE](https://datatracker.ietf.org
南-北向通信 通过 NAT 网络地址转译来实现

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* Pod -> 服务（集群IP）
```suggestion
* Pod -> 服务（集群 IP）
```

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* Pod -> 服务（部分限定域名，仅适用于名称中不包含“."的情形）
双引号不一致

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +来为 `l2bridge` 网络启用 IPv4/IPv6 双栈联网支持。
联网 -> 网络

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +目前 Windows 上的覆盖网络（VXLAN）还不支持双协议栈联网。
联网 -> 网络

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +与此相比，Windows 为每个容器创建一个带有系统名字空间过滤设置的 Job 对象，
名字空间？

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 并非支持共享名字空间的所有功能特性（参见 API 节以了解详细信息）
名字空间 以下同理

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 卷挂载无法将文件或目录投射回宿主文件系统
投射？

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +1. 我怎样知道 `start.ps1` 成功完成？
```suggestion
1. 我怎样知道 `start.ps1` 是否成功完成？
```

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +   作为联网方案）flanneld 宿主代理进程，它们的运行日志显示在不同的
FLannel  -> Flannel

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +   中的网络配置值得额外的注意。你总是可以编辑这一静态文件。
是值得额外的注意

2020-12-04 16:33 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +    请参照 Microsoft 的 [Docker 仓库](https://hub.docker.com/u/microsoft/)
1

2020-12-05 05:06 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +  Pod 是 Kubernetes 中最基本的构造模块，是 Kubernetes 对象模型中你可以创建或部署的
yes. Building blocks.

2020-12-05 05:06 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +  最小、最简单元。你不可以在同一 Pod 中部署 Windows 和 Linux 容器。
yes, simplest unit

2020-12-05 05:07 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +  * 就绪态（Readiness）和活跃性（Liveness）探针
yes, 行文使用全角字符。除非英文上下文中或者 markdown 语法要求。

2020-12-05 05:07 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 对水平 Pod 自动扩展的支持
Horizontal Pod Auto Scaling 的直译。问题不大。

2020-12-05 05:08 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +StatefulSet 这类标准的 Kubernetes 构造体来部署。
Constructs 的直译。

2020-12-05 05:28 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +#### 联网     {#networking}
network 是网络，networking 是指建立网络配置和连接的过程。

2020-12-05 05:30 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +| 透明网络（[ovn-kubernetes](https://github.com/openvswitch/ovn-kubernetes) 的特殊用例） | 需要一个外部 vSwitch。容器挂接到某外部 vSwitch 上，该 vSwitch 通过逻辑网络（逻辑交换机和路由器）允许 Pod 间通信。 | 报文或者通过 [GENEVE](https://datatracker.ietf.org
南北向通信从何而来？

2020-12-05 05:32 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 卷挂载无法将文件或目录投射回宿主文件系统
关于 project，你有什么建议？

2020-12-05 10:47 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +| 透明网络（[ovn-kubernetes](https://github.com/openvswitch/ovn-kubernetes) 的特殊用例） | 需要一个外部 vSwitch。容器挂接到某外部 vSwitch 上，该 vSwitch 通过逻辑网络（逻辑交换机和路由器）允许 Pod 间通信。 | 报文或者通过 [GENEVE](https://datatracker.ietf.org
我通常遇到的南北通向流量与东西流量说法，这样感觉很好

2020-12-05 10:52 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 对水平 Pod 自动扩展的支持
ok

2020-12-05 10:52 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 卷挂载无法将文件或目录投射回宿主文件系统
我想想，映射吗？

2020-12-05 11:41 UTC, tengqm commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 卷挂载无法将文件或目录投射回宿主文件系统
projection 带有单向关联的意味。map 往往是双向的。

2020-12-06 06:43 UTC, tanjunchen commented on content/zh/docs/setup/production-environment/windows/intro-windows-in-kubernetes.md
> +* 卷挂载无法将文件或目录投射回宿主文件系统
ok

2020-12-06 06:47 UTC, tanjunchen commented
/lgtm
/approve

2020-12-06 06:49 UTC, merged