ja: Make ja: Make docs/concepts/storage/persistent-volumes.md follow v1.18 of the original text
kubernetes/website pull request #24848
Opened 2020-11-02 14:02 UTC by shuzokato

updated ja docs/concepts/storage/persistent-volumes.md to follow v1.18 of the original text.
this fixes #23595 .
sorry fo delay.

2020-11-02 16:44 UTC, inductor requested changes

2020-11-02 16:44 UTC, inductor commented on content/ja/docs/concepts/storage/persistent-volumes.md
> +基盤ストレージの拡張に失敗した際には、クラスターの管理者はPersistent Volume Claim (PVC)の状態を手動で復旧し、リサイズ要求をキャンセルします。それをしない限り、リサイズ要求は管理者の介入なしにコントローラによって継続的に再試行されます。
```suggestion
基盤ストレージの拡張に失敗した際には、クラスターの管理者はPersistent Volume Claim (PVC)の状態を手動で復旧し、リサイズ要求をキャンセルします。それをしない限り、リサイズ要求は管理者の介入なしにコントローラーによって継続的に再試行されます。  
```

2020-11-02 16:44 UTC, inductor commented on content/ja/docs/concepts/storage/persistent-volumes.md
> +`volumeMode`は任意のAPIパラメータです。
```suggestion
`volumeMode`は任意のAPIパラメーターです。  
```

2020-11-02 16:44 UTC, inductor commented on content/ja/docs/concepts/storage/persistent-volumes.md
> +`Filesystem`は`volumeMode`パラメータが省略がされたときに使用されるデフォルトのモードです。
```suggestion
`Filesystem`は`volumeMode`パラメーターが省略がされたときに使用されるデフォルトのモードです。  
```

2020-11-03 15:19 UTC, kakts requested changes
対応ありがとうございます。

1点コメントいたしましたので、ご確認をお願いいたします。

2020-11-03 15:19 UTC, kakts commented on content/ja/docs/concepts/storage/persistent-volumes.md
> +1. PersistentVolumeClaim(PVC)にバウンドしていないPersistentVolume(PV)を`Retain`再クレームポリシーとしてマークします。
```suggestion
1. PersistentVolumeClaim(PVC)にバインドされているPersistentVolume(PV)を`Retain`再クレームポリシーとしてマークします。
```

>Mark the PersistentVolume(PV) that is bound to the PersistentVolumeClaim(PVC) with Retain reclaim policy.

is bound to A ➡️　Aにバインドされている　という意味かと思いました！

2020-11-04 01:32 UTC, makocchi-git commented
/lgtm

2020-11-04 02:24 UTC, inductor commented
/approve

2020-11-04 02:26 UTC, merged