[zh] Sync changes to docs/concepts/policy/resource-quotas.md
kubernetes/website pull request #24894
Opened 2020-11-05 04:14 UTC by tengqm

Also fixed a nit in English version.

2020-11-05 11:40 UTC, howieyuen requested changes

2020-11-05 11:40 UTC, howieyuen commented on content/zh/docs/concepts/policy/resource-quotas.md
> +| `<storage-class-name>.storageclass.storage.k8s.io/persistentvolumeclaims` |  在与 storage-class-name 相关的所有持久卷声明中，命名空间中可以存在的[持久卷申领](/zh/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
whatever "persistent volume claim" translated to 持久卷声明 or 持久卷申领， keep context consistent

2020-11-08 09:51 UTC, howieyuen commented
/lgtm

2020-11-08 20:04 UTC, irvifa reviewed
/approve

2020-11-08 20:05 UTC, merged