Document SizeMemoryBackedVolumes feature for 1.20
kubernetes/website pull request #24906
Opened 2020-11-05 16:32 UTC by derekwaynecarr

Related KEP: https://github.com/kubernetes/enhancements/pull/1968

2020-11-05 17:38 UTC, annajung commented
/milestone 1.20
/hold no k/k pr
/assign
/sig node

enhancement: https://github.com/kubernetes/enhancements/issues/1967

2020-11-05 18:11 UTC, sftim commented on content/en/docs/concepts/storage/volumes.md
> +If the `SizeMemoryBackedVolumes` feature gate is enabled in 1.20+, users may
I'd write this:
```suggestion
If the `SizeMemoryBackedVolumes` [feature gate](/docs/reference/command-line-tools-reference/feature-gates/) is enabled, you can
```

2020-11-05 18:11 UTC, sftim commented on content/en/docs/concepts/storage/volumes.md
> +If the `SizeMemoryBackedVolumes` feature gate is enabled in 1.20+, users may
Remember to update `/docs/reference/command-line-tools-reference/feature-gates/`

2020-11-12 00:14 UTC, annajung commented
/hold cancel
k/k pr merged

Hi @derekwaynecarr w/ k/k pr merged in, Sig Docs would appreciate it if you could fill the content of the docs early, ideally before kubecon to get it reviewed/merged on time. Thank you!

2020-11-19 12:51 UTC, sftim commented
Hi @derekwaynecarr 

Would you have time to make sure that `/docs/reference/command-line-tools-reference/feature-gates/` is up to date for the changes this PR is documenting?

2020-11-23 15:48 UTC, annajung commented
Hi @derekwaynecarr today is the deadline for docs to be in ready for review state. Please address Tim's comment above and let us know if this is ready to be reviewed.

2020-11-23 21:13 UTC, derekwaynecarr commented
I made the recommended update, and believe this is ready for review.

2020-11-23 21:17 UTC, annajung commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +| `SizeMemoryBackedVolumes` | `false` | Alpha | 1.20 | |
Just need a short description below describing this feature. Then, I think docs are good to merge

2020-11-24 09:05 UTC, sftim reviewed
I wonder if https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/ should also get a mention of the new feature gate. What do you think @derekwaynecarr ?

2020-11-29 18:55 UTC, sftim commented
Hi @derekwaynecarr 

Repeating https://github.com/kubernetes/website/pull/24906#discussion_r529001457 - we'd like a summary of the new feature gate, similar to the other ones already in the list.

2020-11-30 23:53 UTC, reylejano commented
Hi @derekwaynecarr, just a reminder that the docs merge deadline is in a few days on Dec 2. If you can address @sftim 's comment about adding a summary of the new feature gate then this PR can merge after a quick review. Thank you

2020-12-01 16:04 UTC, derekwaynecarr commented
@annajung addressed feedback

2020-12-01 16:23 UTC, sftim requested changes
One fix needed; otherwise LGTM.

2020-12-01 16:23 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +- `SizeMemoryBackedVolumes`: Enables kubelet support to size memory backed volumes.  See [volumes] (docs/concepts/storage/volumes) for more details.
CommonMark doesn't like the extra space
```suggestion
- `SizeMemoryBackedVolumes`: Enables kubelet support to size memory backed volumes.  See [volumes](docs/concepts/storage/volumes) for more details.
```

2020-12-01 18:22 UTC, derekwaynecarr commented
@sftim fixed typo.

2020-12-01 18:55 UTC, annajung commented
/lgtm
/approve

2020-12-01 18:56 UTC, merged