[zh] Sync changes from English site (5)
kubernetes/website pull request #25017
Opened 2020-11-13 08:26 UTC by tengqm

2020-11-18 04:57 UTC, tanjunchen commented
/assign @tanjunchen

2020-11-25 05:03 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/service.md
> +如果以后你决定将数据库移到群集中，则可以启动其 Pod，添加适当的选择器或端点以及更改服务的 `type`。
群集？

2020-11-25 05:03 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/service.md
>  同时，基于 IPVS 的 kube-proxy 具有更复杂的负载平衡算法（最小连接，局部性，加权，持久性）。
负载平衡

2020-11-25 05:03 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/service.md
> +Service 是 Kubernetes REST API 中的顶级资源。你可以在以下位置找到有关A PI 对象的更多详细信息：
有关A PI ？

2020-11-25 05:03 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/service.md
> +* 阅读了解[端点切片](/zh/docs/concepts/services-networking/endpoint-slices/)
端点切片？

2020-11-25 05:03 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/service.md
> +要了解如何定义服务末端，请参阅[不带选择算符的服务](#services-without-selectors)。
末端？

2020-11-25 06:19 UTC, tengqm commented on content/zh/docs/concepts/services-networking/service.md
> +支持群集的 DNS 服务器（例如 CoreDNS）监视 Kubernetes API 中的新服务，并为每个服务创建一组 DNS 记录。
Many occurrence in previous translation. Now all fixed.

2020-11-25 06:22 UTC, tengqm commented on content/zh/docs/concepts/services-networking/service.md
> +* 阅读了解[端点切片](/zh/docs/concepts/services-networking/endpoint-slices/)
英文写成了两个词： Endpoint Slices

2020-11-25 09:47 UTC, howieyuen requested changes

2020-11-25 09:47 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/service.md
>  该负载均衡器将转发前缀为 [PROXY协议](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt)
PROXY 协议

2020-11-25 10:08 UTC, tengqm commented on content/zh/docs/concepts/services-networking/dual-stack.md
>  公共路由和非公共路由的 IPv6 地址块的使用是可以的。提供底层
I didn't verify the existing translation.

2020-11-26 01:32 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/service.md
> +支持群集的 DNS 服务器（例如 CoreDNS）监视 Kubernetes API 中的新服务，并为每个服务创建一组 DNS 记录。
ok.thanks for your good job!

2020-11-27 01:19 UTC, howieyuen commented
/lgtm

2020-11-27 04:56 UTC, tanjunchen commented
/approve
/lgtm

2020-11-27 04:58 UTC, merged