[zh] Resync concepts/services-networking/network-policies.md
kubernetes/website pull request #25036
Opened 2020-11-14 10:52 UTC by tengqm

2020-11-16 15:11 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +到 Kubernetes v1.20 为之，NetworkPolicy API 还不支持以下功能，不过
typo

2020-11-16 15:11 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +或者第七层技术（Ingress 控制器、服务网格实现）或准入控制器来 实现一些
多余的空格

2020-11-16 15:11 UTC, tanjunchen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +- 基于名字来选择名字空间或者服务（不过，你可以使用 {{< glossary_tooltip text="标签" term_id="label" >}}
名字空间 上下文尽量保持一致  有的译作名字空间 有的是命名空间 (个人感觉中一篇文章中尽量保持一致)

2020-11-17 01:42 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +如果你希望控制 IP 地址或端口层面（OSI 第 3 或第 4 层）控制网络流量，
revised.

2020-11-17 01:42 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +入站（Ingress）/离站（Egress）规则的并集。因此评估的顺序并不会影响策略的结果。
done

2020-11-17 01:43 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +到 Kubernetes v1.20 为之，NetworkPolicy API 还不支持以下功能，不过
fixed.

2020-11-17 01:44 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +- 基于名字来选择名字空间或者服务（不过，你可以使用 {{< glossary_tooltip text="标签" term_id="label" >}}
resolved

2020-11-17 07:28 UTC, howieyuen requested changes

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +该规则将指定端口上的流量匹配到 `10.0.0.0/24` 中的任何目的地。
目的地址。

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +2. （Ingress 规则）允许以下 Pod 连接到 "default" 名字空间下的带有 “role=db”
中英文双引号混搭

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +了解更多示例。
删除“了解”，演练更多示例。

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +Pod，应将其允许作为入口源或出口目的地。
入站/出站，保持上下文一致性。
下文中翻译时加入了“流量”这个词，个人感觉更好。
考虑一下将 “ingress sources or egress destinations.” 翻译成“入栈流量源地址和出站流量目的地址”，如何？

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +输入源或输出目的地。
入站/出站，同上

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +Pod 的连接，*或* 来自任何名字空间中标有 `user = alice` 的任何 Pod 的连接。
user=alice，删除空格

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +__ipBlock__: 此选择器将选择特定的 IP CIDR 范围以用作入站流量源或出站流量目的地。
同上

2020-11-17 07:28 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +允许进入或流出流量。
入站或出站

2020-11-17 07:56 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +该规则将指定端口上的流量匹配到 `10.0.0.0/24` 中的任何目的地。
有意将 ”destination“ 译为”目的地“，因为这里的确不是 destination address 的意思。

2020-11-17 08:27 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +了解更多示例。
英文原文

> See the [Declare Network Policy](/docs/tasks/administer-cluster/declare-network-policy/) walkthrough for further examples.

这里的演练是名词。

2020-11-17 08:46 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +2. （Ingress 规则）允许以下 Pod 连接到 "default" 名字空间下的带有 “role=db”
fixed

2020-11-17 08:47 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +Pod，应将其允许作为入口源或出口目的地。
OK. Fixed.

2020-11-17 08:49 UTC, tengqm commented on content/zh/docs/concepts/services-networking/network-policies.md
> +允许进入或流出流量。
OK. I didn't fix all the original translations.

2020-11-17 11:27 UTC, howieyuen commented
/approve

2020-11-17 11:27 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/network-policies.md
> +了解更多示例。
确实是名词。

2020-11-17 11:31 UTC, howieyuen commented
/lgtm

2020-11-17 12:28 UTC, tanjunchen reviewed
/approve
/lgtm

2020-11-17 12:30 UTC, merged