[zh] sync tasks/run-application/horizontal-pod-autoscale-walkthrough.md
kubernetes/website pull request #25137
Opened 2020-11-20 07:24 UTC by tengqm

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
>  ## 创建 Horizontal Pod Autoscaler
## 创建 Horizontal Pod Autoscaler {#create-horizontal-pod-autoscaler}

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
>  ## 增加负载
## 增加负载 {#increase-load}

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
>  ## 基于多项度量指标和自定义度量指标自动扩缩
## 基于多项度量指标和自定义度量指标自动扩缩 {#autoscaling-on-multiple-metrics-and-custom-metrics}

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +你还可以指定资源度量指标使用绝对数值，而不是百分比，你需要将 `target.type` 从
>使用绝对数值,
可能会误以为是绝对数（正数），不如改为：使用原始值

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +第一种可选的度量指标类型是 pod 度量指标。这些指标从某一方面描述了 Pod，
pod -> Pod

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +### 基于更特别的度量值来扩缩
### 基于更特别的度量值来扩缩 {#autoscaling-on-more-specific-metrics}

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
>  ## 附录：量纲
## 附录：量纲  {#appendix-quantities}

2020-11-22 03:59 UTC, zhiguo-lu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +### 以声明式方式创建 Autoscaler
## 附录：其他可能的情况 {#appendix-other-possible-scenarios}

### 以声明式方式创建 Autoscaler {#creating-the-autoscaler-declaratively}

2020-11-23 01:25 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +你还可以指定资源度量指标使用绝对数值，而不是百分比，你需要将 `target.type` 从
绝对值和绝对数值还是容易分清的。

2020-11-23 04:00 UTC, howieyuen requested changes

2020-11-23 08:52 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +第二种可选的度量指标类型是对象（object）度量指标。这些度量指标用于描述
英文可用斜体表示强调，中文改成斜体太难看了。

2020-11-23 12:13 UTC, howieyuen commented
/lgtm

2020-11-23 15:40 UTC, tanjunchen reviewed
/approve
/lgtm
thanks

2020-11-23 15:41 UTC, merged