[zh]sync chinese trans for feature-gate
kubernetes/website pull request #25141
Opened 2020-11-20 09:59 UTC by zhaojizhuang

[zh]sync chinese trans for feature-gate

2020-11-20 10:00 UTC, zhaojizhuang commented
/language zh

2020-11-20 10:00 UTC, zhaojizhuang commented
/assign @tengqm

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ImmutableEphemeralVolumes`: 允许将单个 Secret 和 ConfigMap 标记为不可变的，以提高安全性和性能。
```suggestion
- `ImmutableEphemeralVolumes`: 允许将各个 Secret 和 ConfigMap 标记为不可变更的，以提高安全性和性能。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `LocalStorageCapacityIsolation`：启用[本地临时存储](/docs/concepts/configuration/manage-resources-containers/)的消耗，以及 [emptyDir 卷](/docs/concepts/storage/volumes/#emptydir) 的 `sizeLimit` 属性。
```suggestion
- `LocalStorageCapacityIsolation`：允许使用[本地临时存储](/zh/docs/concepts/configuration/manage-resources-containers/)以及 [emptyDir 卷](/zh/docs/concepts/storage/volumes/#emptydir) 的 `sizeLimit` 属性。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `LocalStorageCapacityIsolationFSQuotaMonitoring`：如果为[本地临时存储](/docs/concepts/configuration/manage-resources-containers/)启用了 `LocalStorageCapacityIsolation`，并且 [emptyDir 卷](/docs/concepts/storage/vol
use Chinese url with prefix '/zh'.

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `PodOverhead`：启用 [PodOverhead](/docs/concepts/scheduling-eviction/pod-overhead/) 特性以解决 Pod 开销。
```suggestion
- `PodOverhead`：启用 [PodOverhead](/zh/docs/concepts/scheduling-eviction/pod-overhead/) 特性以考虑 Pod 开销。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ResourceLimitsPriorityFunction` （ *已弃用* ）：启用 scheduler 优先级特性，该特性将最低可能得 1 分配给至少满足输入 Pod 的 cpu 和内存限制之一的节点，目的是打破得分相同的节点之间的联系。
```suggestion
- `ResourceLimitsPriorityFunction` （ *已弃用* ）：启用某调度器优先级函数，该函数将
  最低得分 1 指派给至少满足输入 Pod 的 cpu 和内存限制之一的节点，目的是打破得分相同的
  节点之间的关联。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
>  - `SCTPSupport`：在 “服务”、“端点”、“NetworkPolicy” 和 “Pod” 定义中，将 SCTP 用作 “协议” 值。
```suggestion
- `SCTPSupport`：在 Service、Endpoints、NetworkPolicy 和 Pod 定义中，允许将 _SCTP_ 用作 `protocol` 值。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
>  - `ServerSideApply`：在 API 服务器上启用[服务器端应用（SSA）](/docs/reference/using-api/api-concepts/#server-side-apply) 路径。
```suggestion
- `ServerSideApply`：在 API 服务器上启用[服务器端应用（SSA）](/zh/docs/reference/using-api/server-side-apply/) 路径。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ServiceAccountIssuerDiscovery`: 在 API 服务器中为服务帐户发行者启用 OIDC 发现端点（发行者和 JWKS URL）。 详情请参见 [为 Pod 配置服务账户](/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery)
```suggestion
- `ServiceAccountIssuerDiscovery`: 在 API 服务器中为服务帐户颁发者启用 OIDC 发现端点
  （颁发者和 JWKS URL）。 详情请参见 [为 Pod 配置服务账户](/zh/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) 。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ServiceAppProtocol`: 在 服务 和 端点 上启用 “ AppProtocol” 字段。
```suggestion
- `ServiceAppProtocol`：为 Service 和 Endpoints 启用 `AppProtocol` 字段。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `SetHostnameAsFQDN`: 启用将完全合格域名 （FQDN）设置为 Pod 主机名的功能。请参见 [给 Pod 设置 `setHostnameAsFQDN` 字段](/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field).
```suggestion
- `SetHostnameAsFQDN`: 启用将全限定域名 （FQDN）设置为 Pod 主机名的功能。请参见 [给 Pod 设置 `setHostnameAsFQDN` 字段](/zh/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field).
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `TaintNodesByCondition`：根据[节点条件](/docs/concepts/scheduling-eviction/taint-and-toleration/)启用自动在节点标记污点。
use '/zh'

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `WindowsRunAsUserName` : 提供在 Windows 容器中运行应用程序时对非默认用户的支持。
```suggestion
- `WindowsRunAsUserName` : 提供使用非默认用户在 Windows 容器中运行应用程序的支持。
```

2020-11-20 12:32 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +  See [Configuring RunAsUserName](/docs/tasks/configure-pod-container/configure-runasusername) for more details.
漏译

2020-11-20 12:32 UTC, tengqm commented
看起来此页面大多数 URL 都需要修改，请帮忙。

2020-11-20 13:06 UTC, howieyuen requested changes
I found a lot of EN links and some untranslated line in this page, please recheck the whole doc and make sure that is synced fully.

2020-11-20 13:06 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ResourceLimitsPriorityFunction` （ *已弃用* ）：启用 scheduler 优先级特性，该特性将最低可能得 1 分配给至少满足输入 Pod 的 cpu 和内存限制之一的节点，目的是打破得分相同的节点之间的联系。
`ResourceLimitsPriorityFunction` （ *已弃用* ）：启用调度器优先级函数，对于至少满足 CPU 和内存限制条件之一的节点，此函数至少分配1分。这么做的目的是打破得分相同的节点之间的联系。

2020-11-20 15:27 UTC, zhaojizhuang commented
> 看起来此页面大多数 URL 都需要修改，请帮忙。

@tengqm Done

2020-11-20 15:28 UTC, zhaojizhuang commented
> I found a lot of EN links and some untranslated line in this page, please recheck the whole doc and make sure that is synced fully.

@howieyuen Done it ,Thanks

2020-11-21 01:52 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `AdvancedAuditing`：启用[高级审查功能](/zh/docs/tasks/debug-application-cluster/audit/#advanced-audit)。
auditing -> 审计

2020-11-21 01:53 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `CPUManager`：启用容器级别的 CPU 亲和力支持，有关更多详细信息，请参见 [CPU 管理策略](/zh/docs/tasks/administer-cluster/cpu-management-policies/)。
```suggestion
- `CPUManager`：启用容器级别的 CPU 亲和性支持，有关更多详细信息，
  请参见 [CPU 管理策略](/zh/docs/tasks/administer-cluster/cpu-management-policies/)。
```

2020-11-21 02:03 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +   颁发者和 JWKS URL）。 详情请参见 [为 Pod 配置服务账户](/zh/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) 。
```suggestion
   颁发者和 JWKS URL）。 详情请参见[为 Pod 配置服务账户](/zh/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) 。
```

2020-11-21 02:03 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `SetHostnameAsFQDN`: 启用将全限定域名 （FQDN）设置为 Pod 主机名的功能。请参见 [给 Pod 设置 `setHostnameAsFQDN` 字段](/zh/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field)。
```suggestion
- `SetHostnameAsFQDN`: 启用将全限定域名 （FQDN）设置为 Pod 主机名的功能。请参见[给 Pod 设置 `setHostnameAsFQDN` 字段](/zh/docs/concepts/services-networking/dns-pod-service/#pod-sethostnameasfqdn-field)。
```

2020-11-21 02:03 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ServiceTopology`：启用服务拓扑可以让一个服务基于集群的节点拓扑进行流量路由。有关更多详细信息，请参见[Service 拓扑](https://kubernetes.io/zh/docs/concepts/services-networking/service-topology/)。
```suggestion
- `ServiceTopology`：启用服务拓扑可以让一个服务基于集群的节点拓扑进行流量路由。有关更多详细信息，请参见
  [Service 拓扑](/zh/docs/concepts/services-networking/service-topology/)。
```

2020-11-21 02:03 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +- `TopologyManager`：启用一种机制来协调 Kubernetes 不同组件的细粒度硬件资源分配。详见 [控制节点上的拓扑管理策略](/zh/docs/tasks/administer-cluster/topology-manager/)。
```suggestion
- `TopologyManager`：启用一种机制来协调 Kubernetes 不同组件的细粒度硬件资源分配。详见
  [控制节点上的拓扑管理策略](/zh/docs/tasks/administer-cluster/topology-manager/)。
```

2020-11-21 02:03 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +  详情请参见 [Configuring RunAsUserName](/zh/docs/tasks/configure-pod-container/configure-runasusername)。
```suggestion
  详情请参见[配置 RunAsUserName](/zh/docs/tasks/configure-pod-container/configure-runasusername)。
```

2020-11-21 02:03 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +* Kubernetes 的 [弃用策略](/zh/docs/reference/using-api/deprecation-policy/) 介绍了项目已移除的特性部件和组件的方法。
```suggestion
* Kubernetes 的[弃用策略](/zh/docs/reference/using-api/deprecation-policy/)介绍了项目处理
  已移除的特性和组件的方法。
```

2020-11-21 12:44 UTC, zhaojizhuang commented
@tengqm Done，thanks for review

2020-11-22 04:11 UTC, xichengliudui commented
/approve

2020-11-23 01:12 UTC, tengqm commented
/lgtm

2020-11-23 01:13 UTC, merged