Update docs/setup/release/version-skew-policy.md
kubernetes/website pull request #25268
Opened 2020-11-27 07:11 UTC by KobayashiD27

Fix #25218
Update docs/setup/release/version-skew-policy.md

2020-11-27 08:33 UTC, inductor commented on content/ja/docs/setup/release/version-skew-policy.md
> +* ほかの`kube-apiserver`インスタンスは**{{< skew latestVersion >}}**および**{{< skew prevMinorVersion >}}**がサポートされます
（念の為の確認です）この記法はローカルで動作確認されましたか？

2020-11-27 09:45 UTC, KobayashiD27 commented on content/ja/docs/setup/release/version-skew-policy.md
> +* ほかの`kube-apiserver`インスタンスは**{{< skew latestVersion >}}**および**{{< skew prevMinorVersion >}}**がサポートされます
確認済みです。対応したバージョン番号が出ていました。

2020-11-27 09:56 UTC, KobayashiD27 commented on content/ja/docs/setup/release/version-skew-policy.md
> +* ほかの`kube-apiserver`インスタンスは**{{< skew latestVersion >}}**および**{{< skew prevMinorVersion >}}**がサポートされます
すいません、正確にはlatestVersinには**1.19**が表示されていました。
確認の意図が、1.18のドキュメントで1.19や1.20が出てきてはまずい、という意味でしたら、問題があるかもしれません。
[英語のページ](https://v1-18.docs.kubernetes.io/docs/setup/release/version-skew-policy/)でもバージョンはこのままなので、大丈夫かとは思いますが。

2020-11-27 10:04 UTC, inductor commented on content/ja/docs/setup/release/version-skew-policy.md
> +* ほかの`kube-apiserver`インスタンスは**{{< skew latestVersion >}}**および**{{< skew prevMinorVersion >}}**がサポートされます
はい、こちらはmasterの本家に沿ってれば大丈夫だと思います。ご確認ありがとうございます！

2020-12-02 07:42 UTC, KobayashiD27 commented
/assign @nasa9084

2020-12-02 07:49 UTC, inductor commented
/approve

2020-12-04 05:36 UTC, kakts requested changes
対応ありがとうございます。

一点コメントしました。ご確認お願いします

2020-12-04 05:36 UTC, kakts commented on content/ja/docs/setup/release/version-skew-policy.md
> +* `kube-proxy`のマイナーバージョンはノード上のの`kubelet`と同じマイナーバージョンでなければなりません
```suggestion
* `kube-proxy`のマイナーバージョンはノード上の`kubelet`と同じマイナーバージョンでなければなりません
```

2020-12-04 06:07 UTC, KobayashiD27 commented on content/ja/docs/setup/release/version-skew-policy.md
> +* `kube-proxy`のマイナーバージョンはノード上のの`kubelet`と同じマイナーバージョンでなければなりません
レビューありがとうございます。修正しました。
自分のチェックミスですね、すいません。

2020-12-06 16:31 UTC, kakts commented on content/ja/docs/setup/release/version-skew-policy.md
> +Kubernetesプロジェクトでは、最新の3つのマイナーリリースについてリリースブランチを管理しています ({{< skew latestVersion >}}, {{< skew prevMinorVersion >}}, {{< skew oldestMinorVersion >}}).。
```suggestion
Kubernetesプロジェクトでは、最新の3つのマイナーリリースについてリリースブランチを管理しています ({{< skew latestVersion >}}, {{< skew prevMinorVersion >}}, {{< skew oldestMinorVersion >}})。
```
こちらピリオド不要でしょうか

2020-12-07 00:15 UTC, KobayashiD27 commented on content/ja/docs/setup/release/version-skew-policy.md
> +Kubernetesプロジェクトでは、最新の3つのマイナーリリースについてリリースブランチを管理しています ({{< skew latestVersion >}}, {{< skew prevMinorVersion >}}, {{< skew oldestMinorVersion >}}).。
ありがとうございます。修正しました。

2020-12-08 11:37 UTC, makocchi-git commented on content/ja/docs/setup/release/version-skew-policy.md
> +* `kube-proxy`は `kube-apiserver`よりも新しいものであってはなりません
```suggestion
* `kube-proxy`は`kube-apiserver`よりも新しいものであってはなりません
```

細かいですけど、スペース消しておきましょうか

2020-12-08 11:38 UTC, makocchi-git commented on content/ja/docs/setup/release/version-skew-policy.md
> +* `kube-proxy` のマイナーバージョンは`kube-apiserver`のマイナーバージョンよりも2つ以上古いものでなければなりません
```suggestion
* `kube-proxy`のマイナーバージョンは`kube-apiserver`のマイナーバージョンよりも2つ以上古いものでなければなりません
```

こちらも同様に

2020-12-09 00:43 UTC, KobayashiD27 commented on content/ja/docs/setup/release/version-skew-policy.md
> +* `kube-proxy`は `kube-apiserver`よりも新しいものであってはなりません
ありがとうございます。

2020-12-10 14:45 UTC, kakts commented
/lgtm

2020-12-10 14:46 UTC, merged