[zh] Sync English site changes for authentication ref
kubernetes/website pull request #25293
Opened 2020-11-28 15:00 UTC by tengqm

Some changes are large because ... the original translator failed to include the English source. I don't know why those PRs got merged in the first place.

2020-11-30 04:00 UTC, howieyuen requested changes

2020-11-30 07:03 UTC, tengqm commented on content/zh/docs/reference/access-authn-authz/service-accounts-admin.md
> +- 监测服务账号令牌 Secret 的删除，如有需要，从相应的 ServiceAccount 中移除引用。
加上前缀更明确一些。

2020-11-30 08:19 UTC, howieyuen commented
/lgtm

2020-12-02 05:35 UTC, tanjunchen commented
/assign @tanjunchen

2020-12-04 05:50 UTC, xichengliudui commented
/approve

2020-12-04 05:53 UTC, merged