Automatically initialize git submodules
kubernetes/website pull request #25326
Opened 2020-12-01 08:47 UTC by rayw000

Currently when running `make serve` or something similar, you get just a warning says 
```
WARNING: Submodule not initialized: <module path>
```
Better if we could automatically initialize these submodules before build and serve.

2020-12-03 08:46 UTC, sftim requested changes
@rayw000 my concern here is that `make module-check`, by its name, should *not* have side effects.

We might change the name of the target or improve the user experience if the submodules are missing. We shouldn't have a target named for a check make changes to the contributor's local clone - that's unexpected / surprising behaviour.

2020-12-03 08:54 UTC, rayw000 commented on Makefile
>  module-check:
Agree with you. Actually I'd like to add a new rule which named `module-init` at first. But I'd noticed that `module-check` is depended by some rules below. I'm not sure if I could replace these dependencies from `module-check` to `module-init`. How do you think about it?

2020-12-03 09:39 UTC, rayw000 commented
@sftim I've pushed a new commit, which
1. Add a new rule `module-init`
2. If uninitialized modules detected, print a message in `module-check` to tell users to run `make module-init`, and then break the build chain.

Would you think it is a better way?

2020-12-09 08:02 UTC, rayw000 commented
/assign @bradtopol

2020-12-16 21:49 UTC, sftim reviewed
LGTM. I haven't tested this.

2020-12-16 21:49 UTC, sftim commented on Makefile
> +	@echo "Initializing submodules..."
Tiny nit:
```suggestion
	@echo "Initializing submodules..." 1>&2
```

2021-01-11 18:06 UTC, bradtopol commented
Looks like @sftim is engaged here so making him the assignee.
/assign @sftim 
/unassign

2021-01-26 03:56 UTC, rayw000 commented
Hi @sftim 
Could you review this PR if you are free? Thank you! 😃

2021-02-08 13:49 UTC, irvifa reviewed
/lgtm
I tested this locally but need another 👀

2021-02-11 01:36 UTC, kbhawkey commented
@rayw000 , 
I suggest to rename this pull request to describe the new make target (module-init)?

2021-02-19 19:46 UTC, kbhawkey commented
Hi @rayw000 .
I ran the targets. My local website repository has the theme installed.
I ran the `module-init` target and the api-ref-generator sub-module installed successfully.
The `module-check` target did not return a message.

If I remove the theme submodule, the `module-check` target returns (as expected .git is not there):

```
fatal: not a git repository: '.git'
fatal: failed to recurse into submodule 'themes/docsy'
```
I am not sure the module-check (original or modified) is working as expected.
Are you able to rebase your changes into a single commit?
I think the `module-init` target is useful.

2021-02-22 08:30 UTC, rayw000 commented
Hi @kbhawkey 

1.
> The `module-check` target did not return a message.

The original `module-check` target works as its name suggests, it only checks and outputs submodules which are not initialized, otherwise, it outputs nothing. So if you have all your submodules initialized, empty output is just what it is expected.

The mainly difference between original and current `module-check` is on return code. The original `module-check` always returns zero even if there are uninitialized submodules. It doesn't stop `make serve` or similar targets from trying to build website (of course, failed). I make it return non-zero in this situation in order to break the rules chain.

2.
> If I remove the theme submodule, the `module-check` target returns (as expected .git is not there):
> 
> ```
> fatal: not a git repository: '.git'
> fatal: failed to recurse into submodule 'themes/docsy'
> ```

I have no idea how do you "remove" your theme submodule. Would you like to provide more details?

I ran the following command
```
git submodule deinit -f <submodule>
```
and then `make module-check`, I got the following output as expected.
```
WARNING Submodule not initialized: api-ref-generator
WARNING Submodule not initialized: themes/docsy
You need to run make module-init to initialize missing modules first
make: *** [module-check] Error 1
```
And then if we run command `make serve`, we'll get the same error message as `make module-check`, and stop the current make procedure. That's why I introduce this target.

3. 
> Are you able to rebase your changes into a single commit?

Rebased.

2021-02-22 21:30 UTC, kbhawkey commented
Hi @rayw000 .
I cloned a new `website` repo and ran `make module-check`. The output is:
```
You need to run make module-init to initialize missing modules first
Makefile:27: recipe for target 'module-check' failed
make: *** [module-check] Error 1
```

2021-02-22 22:59 UTC, rayw000 commented
Hi @kbhawkey 

This output means there're uninitialized submodules. But there should be lines saying something like "Warning: Submodule not initialized: <submodule name>". I have no idea why they're missing.

It's weird that variable `err` used in awk is non-zero in your environment but no uninitialized submodules detected. I'll try to reproduce when I at my laptop.

2021-02-23 05:20 UTC, rayw000 commented
Hi @kbhawkey 

I cloned  a new `website` (head on ebb3d6a14d106f0ba9cc6f0d4c1f4467e1bec932)
```
git clone --depth=1 https://github.com/kubernetes/website website.tmp
```
and applied changes of this PR.  `make module-check` and `make module-init` worked as expected. 

Would you please provide more details?

2021-06-09 01:21 UTC, kbhawkey commented
/remove-lifecycle stale

2021-06-09 01:52 UTC, kbhawkey commented
Hi @rayw000 .
Sorry for the delay in testing these changes.
I tested by removing the submodules from an existing website repository.
In addition, I created a new repository and ran `module-check`. I received the expected error message.
```
WARNING Submodule not initialized: api-ref-generator
WARNING Submodule not initialized: themes/docsy
You need to run make module-init to initialize missing modules first
Makefile:25: recipe for target 'module-check' failed
make: *** [module-check] Error 1
```

2021-06-09 02:00 UTC, kbhawkey commented
I also tested this on a local Ubuntu installation.
/approve

2021-06-09 02:01 UTC, merged