Make docs/reference/kubectl/cheatsheet.md follow v1.18 of the origina…
kubernetes/website pull request #25331
Opened 2020-12-01 13:57 UTC by akitok

Close #25216

2020-12-01 14:02 UTC, akitok commented
/assign @nasa9084

2020-12-02 15:40 UTC, kakts requested changes
翻訳ありがとうございます!
一点コメントいたしましたので、ご確認をお願いいたします。

2020-12-02 15:40 UTC, kakts commented on content/ja/docs/reference/kubectl/cheatsheet.md
> +kubectlに関するより多くのサンプルは[カスタムカラムのリファレンス](/docs/reference/kubectl/overview/#custom-columns)を参照してください。
```suggestion
kubectlに関するより多くのサンプルは[カスタムカラムのリファレンス](/ja/docs/reference/kubectl/overview/#custom-columns)を参照してください。
```
masterブランチの日本語訳に該当の項目ありましたので　日本語訳の方にリンクを向けて問題なさそうです!
https://github.com/kubernetes/website/blob/07ec30894b927cca7cb1e2e97569ecff1245a1a4/content/ja/docs/reference/kubectl/overview.md#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%82%AB%E3%83%A9%E3%83%A0-custom-columns
#### カスタムカラム {#custom-columns}

2020-12-03 09:33 UTC, akitok commented
> 翻訳ありがとうございます!
> 一点コメントいたしましたので、ご確認をお願いいたします。

@kakts
コメントありがとうございます！完全に見落としておりました...
修正反映いたしました。

2020-12-03 14:04 UTC, kakts commented
ご対応ありがとうございます!
/lgtm

2020-12-03 16:24 UTC, inductor commented
/approve

2020-12-03 16:27 UTC, merged