Translate version-skew-policy.md into Korean
kubernetes/website pull request #25345
Opened 2020-12-02 07:23 UTC by mylovepooh

from #24985

2020-12-02 07:33 UTC, pjhwa commented
/assign @yoonian

2020-12-02 07:34 UTC, pjhwa commented
Preview page: https://deploy-preview-25345--k8s-dev-ko.netlify.app/ko/docs/setup/release/version-skew-policy/

2020-12-02 16:07 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +이 문서는 다양한 쿠버네티스 구성 요소간에 지원되는 최대 버전 차이(skew)를 설명한다.
```suggestion
이 문서는 다양한 쿠버네티스 구성 요소 간에 지원되는 최대 버전 차이(skew)를 설명한다. 
```

2020-12-02 16:07 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +특정 클러스터 배포 도구는 버전 차이(skew)에 대한 추가적인 제한을 설정할 수 있다.
```suggestion
특정 클러스터 배포 도구는 버전 차이에 대한 추가적인 제한을 설정할 수 있다.
```
병행 표기는 문서 처음에 한 번만 해도 될 것 같습니다.

2020-12-02 16:07 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +자세한 내용은 [쿠버네티스 릴리즈 버전](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#kubernetes-release-versioning)을 참조 한다.
```suggestion
자세한 내용은 [쿠버네티스 릴리즈 버전](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#kubernetes-release-versioning)을 참조한다.
```

2020-12-02 16:07 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +[고가용성(HA) 클러스터](/docs/setup/production-environment/tools/kubeadm/high-availability/)에서 최신 및 가장 오래된 `kube-apiserver` 인스턴스가 각각 한단계 마이너 버전 내에 있어야 한다.
```suggestion
[고가용성(HA) 클러스터](/docs/setup/production-environment/tools/kubeadm/high-availability/)에서 최신 및 가장 오래된 `kube-apiserver` 인스턴스가 각각 한 단계 마이너 버전 내에 있어야 한다.
```

2020-12-02 16:07 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +HA 클러스터의 `kube-apiserver` 인스턴스 사이에 버전 차이(skew)가 존재하면 허용되는 `kubelet` 버전의 범위도 줄어든다.
```suggestion
HA 클러스터의 `kube-apiserver` 인스턴스 사이에 버전 차이가 있으면 허용되는 `kubelet` 버전의 범위도 줄어든다.
```

2020-12-02 16:07 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 그들과 통신하는 `kube-apiserver` 인스턴스보다 최신 버전이면 안된다. `kube-apiserver` 마이너 버전과 일치 할 것으로 예상하지만, 최대 한단계 낮은 마이너 버전 까지는 허용 합니다.(실시간 업
```suggestion
`kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 그들과 통신하는 `kube-apiserver` 인스턴스보다 최신 버전이면 안 된다. `kube-apiserver` 마이너 버전과 일치 할 것으로 예상하지만, 최대 한 단계 낮은 마이너 버전까지는 허용합니다(실시간 업그레이드를 지원하기 위해서).
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +HA 클러스터의 `kube-apiserver` 인스턴스간에 버전 차이(skew)가 존재하고 이러한 구성 요소가 클러스터의 모든 `kube-apiserver` 인스턴스와 통신 할 수 있는 경우(예 :로드 밸런서를 통해서)에는 구성 요소의 허용하는 버전의 범위도 줄어든다.
```suggestion
HA 클러스터의 `kube-apiserver` 인스턴스 간에 버전 차이가 존재하고 이러한 구성 요소가 클러스터의 모든 `kube-apiserver` 인스턴스와 통신 할 수 있는 경우(예를 들어, 로드 밸런서를 통해서)에는 구성 요소의 허용하는 버전의 범위도 줄어든다.
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 **{{< skew prevMinorVersion >}}** 에서 지원 한다.(**{{< skew latestVersion >}}** 는 `kube-apiserver` 인스턴스의 **{{< skew prevMino
```suggestion
* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 **{{< skew prevMinorVersion >}}** 에서 지원한다(**{{< skew latestVersion >}}** 는 `kube-apiserver` 인스턴스의 **{{< skew prevMinorVersion >}}** 버전보다 최신이기 때문에 지원하지 않는다).
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kubectl`은 `kube-apiserver`의 한단계 마이너 버전 (이전 또는 최신) 내에서 지원한다.
```suggestion
`kubectl`은 `kube-apiserver`의 한 단계 마이너 버전 (이전 또는 최신) 내에서 지원한다.
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +HA 클러스터의`kube-apiserver` 인스턴스간에 버전 차이(skew)가 존재하는 경우 지원되는`kubectl` 버전의 범위도 줄어든다.
```suggestion
HA 클러스터의 `kube-apiserver` 인스턴스 간에 버전 차이가 있으면 지원되는`kubectl` 버전의 범위도 줄어든다.
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubectl` 은 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 에서 지원한다. (다른 버전은 `kube-apiserver`인스턴스들 중에 한단계 이상의 마이너 버전 차이(skew)가 난다)
```suggestion
* `kubectl` 은 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 에서 지원한다(다른 버전은 `kube-apiserver`인스턴스들 중에 한 단계 이상의 마이너 버전 차이가 난다).
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +구성요소 간 지원되는 버전 차이(skew)는 구성요소를 업그레이드해야 하는 순서에 영향을 준다.
```suggestion
구성요소 간 지원되는 버전 차이는 구성요소를 업그레이드하는 순서에 영향을 준다.
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +이 섹션에서는 기존 클러스터를 버전 **{{< skew prevMinorVersion >}}** 에서 버전 **{{< skew latestVersion >}}** 로 전환하기 위해 구성 요소를 업그레이드해야하는 순서를 설명한다.
```suggestion
이 섹션에서는 기존 클러스터를 버전 **{{< skew prevMinorVersion >}}** 에서 버전 **{{< skew latestVersion >}}** 로 전환하기 위해 구성 요소를 업그레이드하는 순서를 설명한다.
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* HA 클러스터에서 모든 `kube-apiserver` 인스턴스는 **{{< skew prevMinorVersion >}}** 또는 **{{< skew latestVersion >}}** 이어야 한다. (이것은 `kube-apiserver` 인스턴스들 간의 가장 최신과 오래된 버전들의 차이를 최대 1개의 마이너 버전의 차이(skew)로 보장한다.)
```suggestion
* HA 클러스터에서 모든 `kube-apiserver` 인스턴스는 **{{< skew prevMinorVersion >}}** 또는 **{{< skew latestVersion >}}** 이어야 한다(이것은 `kube-apiserver` 인스턴스들 간의 가장 최신과 오래된 버전들의 차이를 최대 1개의 마이너 버전의 차이로 보장한다).
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 이 서버와 통신하는 `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 의 버전은 **{{< skew prevMinorVersion >}}** 이어야 한다. (이것은 기존 API서버 버전 보다 최신 버전이 아니고 새로운 API서버 버전의 마이너 1개의 버전 내에 있음을
```suggestion
* 이 서버와 통신하는 `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 의 버전은 **{{< skew prevMinorVersion >}}** 이어야 한다(이것은 기존 API서버 버전보다 최신 버전이 아니고 새로운 API서버 버전의 마이너 1개의 버전 내에 있음을 보장한다).
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 모든 `kubelet` 인스턴스는 버전  **{{< skew prevMinorVersion >}}** 또는 **{{< skew oldestMinorVersion >}}** 이어야 한다. (이것은 기존 API서버 버전보다 최신 버전이 아니며, 새로운 API서버 버전의 2개의 마이너 버전 내에 있음을 보장한다.)
```suggestion
* 모든 `kubelet` 인스턴스는 버전  **{{< skew prevMinorVersion >}}** 또는 **{{< skew oldestMinorVersion >}}** 이어야 한다(이것은 기존 API서버 버전보다 최신 버전이 아니며, 새로운 API서버 버전의 2개의 마이너 버전 내에 있음을 보장한다).
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +  * `ValidatingWebhookConfiguration` 그리고 `MutatingWebhookConfiguration` 객체는 **{{< skew latestVersion >}}** 에 추가된 REST 리소스의 새 버전을 포함하도록 업데이트 한다. (또는 v1.15이상에서 사용 가능한 [`matchPolicy: Equivalent` option]
```suggestion
  * `ValidatingWebhookConfiguration` 그리고 `MutatingWebhookConfiguration` 오브젝트는 **{{< skew latestVersion >}}** 에 추가된 REST 리소스의 새 버전을 포함하도록 업데이트 한다(또는 v1.15이상에서 사용 가능한 [`matchPolicy: Equivalent` option](/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchpolicy) 설정을 사용).
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +[API 사용중지](/docs/reference/using-api/deprecation-policy/) 및
```suggestion
[API 지원 중단](/docs/reference/using-api/deprecation-policy/) 및
```

2020-12-02 16:08 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +에 대한 프로젝트 정책은 단일 클러스터일지라도 업그레이드 할 때 `kube-apiserver`의 마이너 버전을 건너 뛰지 않도록 요구 한다.
```suggestion
에 대한 프로젝트 정책은 단일 클러스터일지라도 업그레이드할 때 `kube-apiserver`의 마이너 버전을 건너뛰지 않도록 요구한다.
```

2020-12-02 16:09 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 이여야 한다. (HA 클러스터에서 `kube-apiserver` 인스턴스와 통신 할 수있는 구성 요소를 업그레이드 전에 모든 `kube-apiserver` 인스턴스는 업그레이드 되어야 한다.)
```suggestion
* `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 이여야 한다(HA 클러스터에서 `kube-apiserver` 인스턴스와 통신 할 수있는 구성 요소를 업그레이드 전에 모든 `kube-apiserver` 인스턴스는 업그레이드 되어야 한다).
```

2020-12-02 16:09 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +필요에 따라서 `kubelet` 인스턴스를 **{{< skew latestVersion >}}** 으로 업그레이드할 수 있다. (또는 **{{< skew prevMinorVersion >}}** 아니면 **{{< skew oldestMinorVersion >}}** 으로 유지할 수 있음)
```suggestion
필요에 따라서 `kubelet` 인스턴스를 **{{< skew latestVersion >}}** 으로 업그레이드할 수 있다(또는 **{{< skew prevMinorVersion >}}** 아니면 **{{< skew oldestMinorVersion >}}** 으로 유지할 수 있음).
```

2020-12-02 16:09 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +클러스터안의 `kubelet` 인스턴스를 `kube-apiserver`의 버전보다 2단계 낮은 버전으로 실행하는 것을 권장하지 않는다:
```suggestion
클러스터 안의 `kubelet` 인스턴스를 `kube-apiserver`의 버전보다 2단계 낮은 버전으로 실행하는 것을 권장하지 않는다:
```

2020-12-02 16:09 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-apiserver`를 업그레이드 하려고 한다면 한단계 낮은 버전으로 업그레이드 해야 한다.
```suggestion
* `kube-apiserver`를 업그레이드한다면 한 단계 낮은 버전으로 업그레이드해야 한다.
```

2020-12-02 16:09 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 이것은 관리되고 있는 3단계의 마이너 버전 보다 낮은 `kubelet` 을 실행할 가능성을 높인다.
```suggestion
* 이것은 관리되고 있는 3단계의 마이너 버전보다 낮은 `kubelet` 을 실행할 가능성을 높인다.
```

2020-12-02 16:10 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubelet` 버전도 반드시 **{{< skew oldestMinorVersion >}}** 와 동일한 마이너 버전 이어야 한다.
```suggestion
* `kubelet` 버전도 반드시 **{{< skew oldestMinorVersion >}}** 와 동일한 마이너 버전이어야 한다.
```

2020-12-02 16:11 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-apiserver` 버전은 반드시 **{{< skew oldestMinorVersion >}}** 에서 **{{< skew latestVersion >}}**사이 여야한다.
```suggestion
* `kube-apiserver` 버전은 반드시 **{{< skew oldestMinorVersion >}}** 에서 **{{< skew latestVersion >}}**사이 이여야 한다.
```

2020-12-02 16:19 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 모든 `kube-apiserver` 인스턴스로 라우팅하는 로드 밸러서와 통신한다.
```suggestion
* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 모든 `kube-apiserver` 인스턴스로 라우팅하는 로드 밸런서와 통신한다.
```

2020-12-02 16:20 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager`는 **{{< skew latestVersion >}}** 과 **{{< skew prevMinorVersion >}}** 을 지원 한다.
```suggestion
* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager`는 **{{< skew latestVersion >}}** 과 **{{< skew prevMinorVersion >}}** 을 지원한다.
```

2020-12-02 16:21 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 다른 `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 을 지원 한다.
```suggestion
* 다른 `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 을 지원한다.
```

2020-12-02 16:21 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kubelet`은 `kube-apiserver`보다 최신일 수 없으며, 2단계의 낮은 마이너 버전까지 지원 한다.
```suggestion
`kubelet`은 `kube-apiserver`보다 최신일 수 없으며, 2단계의 낮은 마이너 버전까지 지원한다.
```

2020-12-02 16:21 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubelet`는 **{{< skew latestVersion >}}**, **{{< skew prevMinorVersion >}}**, 및 **{{< skew oldestMinorVersion >}}** 을 지원 한다.
```suggestion
* `kubelet`는 **{{< skew latestVersion >}}**, **{{< skew prevMinorVersion >}}**, 및 **{{< skew oldestMinorVersion >}}** 을 지원한다.
```

2020-12-02 16:22 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubelet` 은 **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원 한다. (**{{< skew latestVersion >}}** 는  `kube-apiserver`의 **{{< skew prevMinorVersion >}}** 인스턴스보다 최신 버전이기 때문
```suggestion
* `kubelet` 은 **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다. (**{{< skew latestVersion >}}** 는  `kube-apiserver`의 **{{< skew prevMinorVersion >}}** 인스턴스보다 최신 버전이기 때문에 지원하지 않는다.)
```

2020-12-02 16:22 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubectl` 은 **{{< skew nextMinorVersion >}}**, **{{< skew latestVersion >}}**, 및 **{{< skew prevMinorVersion >}}** 을 지원 한다.
```suggestion
* `kubectl` 은 **{{< skew nextMinorVersion >}}**, **{{< skew latestVersion >}}**, 및 **{{< skew prevMinorVersion >}}** 을 지원한다.
```

2020-12-02 16:28 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kube-controller-manager`, `kube-scheduler`, 및 `cloud-controller-manager` 을 **{{< skew latestVersion >}}** 으로 업그레이드
```suggestion
`kube-controller-manager`, `kube-scheduler` 및 `cloud-controller-manager` 을 **{{< skew latestVersion >}}** 으로 업그레이드
```

2020-12-03 02:19 UTC, mylovepooh commented
@yoonian 문서 리뷰해주신거 다시 반영했습니다. 처음 번역하다보니 잔실수가 많았네요.

2020-12-03 08:47 UTC, yoonian requested changes
@mylovepooh 추가 수정하였습니다.

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +이 문서는 다양한 쿠버네티스 구성 요소간에 지원되는 최대 버전 차이를 설명한다.
```suggestion
이 문서는 다양한 쿠버네티스 구성 요소 간에 지원되는 최대 버전 차이를 설명한다. 
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 그들과 통신하는 `kube-apiserver` 인스턴스보다 최신 버전이면 안 된다. `kube-apiserver` 마이너 버전과 일치 할 것으로 예상하지만, 최대 한 단계 낮은 마이너 버전까지는 허용 합니다.(실시간
```suggestion
`kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 그들과 통신하는 `kube-apiserver` 인스턴스보다 최신 버전이면 안 된다. `kube-apiserver` 마이너 버전과 일치할 것으로 예상하지만, 최대 한 단계 낮은 마이너 버전까지는 허용한다(실시간 업그레이드를 지원하기 위해서).
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubelet` 은 **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다. (**{{< skew latestVersion >}}** 는  `kube-apiserver`의 **{{< skew prevMinorVersion >}}** 인스턴스보다 최신 버전이기 때문에
```suggestion
* `kubelet` 은 **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다(**{{< skew latestVersion >}}** 는  `kube-apiserver`의 **{{< skew prevMinorVersion >}}** 인스턴스보다 최신 버전이기 때문에 지원하지 않는다).
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 **{{< skew prevMinorVersion >}}** 에서 지원한다.(**{{< skew latestVersion >}}** 는 `kube-apiserver` 인스턴스의 **{{< skew prevMinor
```suggestion
* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 **{{< skew prevMinorVersion >}}** 에서 지원한다(**{{< skew latestVersion >}}** 는 `kube-apiserver` 인스턴스의 **{{< skew prevMinorVersion >}}** 버전보다 최신이기 때문에 지원하지 않는다).
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 이 서버와 통신하는 `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 의 버전은 **{{< skew prevMinorVersion >}}** 이어야 한다(이것은 기존 API서버 버전 보다 최신 버전이 아니고 새로운 API서버 버전의 마이너 1개의 버전 내에 있음을 보
```suggestion
* 이 서버와 통신하는 `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 의 버전은 **{{< skew prevMinorVersion >}}** 이어야 한다(이것은 기존 API서버 버전보다 최신 버전이 아니고 새로운 API서버 버전의 마이너 1개의 버전 내에 있음을 보장한다).
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 이여야 한다(HA 클러스터에서 `kube-apiserver` 인스턴스와 통신 할 수있는 구성 요소를 업그레이드 전에 모든 `kube-apiserver` 인스턴스는 업그레이드 되어야 한다).
```suggestion
* `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 이여야 한다(HA 클러스터에서 `kube-apiserver` 인스턴스와 통신할 수 있는 구성 요소를 업그레이드 전에 모든 `kube-apiserver` 인스턴스는 업그레이드되어야 한다).
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubelet`는 **{{< skew latestVersion >}}**, **{{< skew prevMinorVersion >}}**, 및 **{{< skew oldestMinorVersion >}}** 을 지원한다.
```suggestion
* `kubelet`는 **{{< skew latestVersion >}}**, **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubectl` 은 **{{< skew nextMinorVersion >}}**, **{{< skew latestVersion >}}**, 및 **{{< skew prevMinorVersion >}}** 을 지원한다.
```suggestion
* `kubectl` 은 **{{< skew nextMinorVersion >}}**, **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 을 지원한다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-proxy` 은 반드시 `kube-apiserver` 보다 최신버전이면 안된다.
```suggestion
* `kube-proxy` 은 반드시 `kube-apiserver` 보다 최신 버전이면 안 된다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +에 대한 프로젝트 정책은 단일 클러스터일지라도 업그레이드할 때 `kube-apiserver`의 마이너 버전을 건너뛰지 않도록 요구한다.
```suggestion
에 대한 프로젝트 정책에서는 단일 클러스터일지라도 업그레이드할 때 `kube-apiserver`의 마이너 버전을 건너뛰지 않도록 요구한다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +  * `ValidatingWebhookConfiguration` 그리고 `MutatingWebhookConfiguration` 오브젝트는 **{{< skew latestVersion >}}** 에 추가된 REST 리소스의 새 버전을 포함하도록 업데이트 한다(또는 v1.15이상에서 사용 가능한 [`matchPolicy: Equivalent` option]
```suggestion
  * `ValidatingWebhookConfiguration` 그리고 `MutatingWebhookConfiguration` 오브젝트는 **{{< skew latestVersion >}}** 에 추가된 REST 리소스의 새 버전을 포함하도록 업데이트한다(또는 v1.15 이상에서 사용 가능한 [`matchPolicy: Equivalent` option](/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchpolicy) 설정을 사용).
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kubectl`은 `kube-apiserver`의 한 단계 마이너 버전 (이전 또는 최신) 내에서 지원한다.
```suggestion
`kubectl`은 `kube-apiserver`의 한 단계 마이너 버전(이전 또는 최신) 내에서 지원한다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +자세한 내용은 [쿠버네티스 릴리즈 버전](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#kubernetes-release-versioning)을 참조한다.
```suggestion
자세한 내용은 [쿠버네티스 릴리스 버전](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/release/versioning.md#kubernetes-release-versioning)을 참조한다.
```

[용어집](https://docs.google.com/spreadsheets/d/1BWKq_HYmt_p1RKzQJoPfCb4ZgBgxH_q3_mf9ujCmniw/edit#gid=0)에서 `릴리즈`가 아니라 `릴리스`입니다.

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +쿠버네티스 프로젝트는 최근 세 개의 마이너 릴리즈 ({{< skew latestVersion >}}, {{< skew prevMinorVersion >}}, {{< skew oldestMinorVersion >}}) 에 대한 릴리즈 분기를 유지한다. 쿠버네티스 1.19 이상은 약 1년간의 패치 지원을 받는다. 쿠버네티스 1.18 이상은 약 9개월의 패치
```suggestion
쿠버네티스 프로젝트는 최근 세 개의 마이너 릴리스 ({{< skew latestVersion >}}, {{< skew prevMinorVersion >}}, {{< skew oldestMinorVersion >}}) 에 대한 릴리스 분기를 유지한다. 쿠버네티스 1.19 이상은 약 1년간의 패치 지원을 받는다. 쿠버네티스 1.18 이상은 약 9개월의 패치 지원을 받는다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +보안 수정사항을 포함한 해당 수정사항은 심각도와 타당성에 따라 세 개의 릴리즈 브랜치들로 백포트(backport) 될 수 있다.
```suggestion
보안 수정사항을 포함한 해당 수정사항은 심각도와 타당성에 따라 세 개의 릴리스 브랜치로 백포트(backport) 될 수 있다. 
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +패치 릴리즈는 각 브랜치별로 [정기적인 주기](https://git.k8s.io/sig-release/releases/patch-releases.md#cadence)로 제공하며, 필요한 경우 추가 긴급 릴리즈도 추가한다.
```suggestion
패치 릴리스는 각 브랜치별로 [정기적인 주기](https://git.k8s.io/sig-release/releases/patch-releases.md#cadence)로 제공하며, 필요한 경우 추가 긴급 릴리스도 추가한다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +[릴리즈 관리자](https://git.k8s.io/sig-release/release-managers.md) 그룹이 이러한 결정 권한을 가진다.
```suggestion
[릴리스 관리자](https://git.k8s.io/sig-release/release-managers.md) 그룹이 이러한 결정 권한을 가진다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +자세한 내용은 쿠버네티스 [패치 릴리즈](https://git.k8s.io/sig-release/releases/patch-releases.md) 페이지를 참조한다.
```suggestion
자세한 내용은 쿠버네티스 [패치 릴리스](https://git.k8s.io/sig-release/releases/patch-releases.md) 페이지를 참조한다.
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubectl` 은 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 에서 지원한다(다른 버전은 `kube-apiserver`인스턴스들 중에 한 단계 이상의 마이너 버전 차이가 난다).
```suggestion
* `kubectl` 은 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 에서 지원한다(다른 버전은 `kube-apiserver`인스턴스 중에 한 단계 이상의 마이너 버전 차이가 난다).
```

2020-12-03 08:47 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* HA 클러스터에서 모든 `kube-apiserver` 인스턴스는 **{{< skew prevMinorVersion >}}** 또는 **{{< skew latestVersion >}}** 이어야 한다(이것은 `kube-apiserver` 인스턴스들 간의 가장 최신과 오래된 버전들의 차이를 최대 1개의 마이너 버전의 차이로 보장한다).
```suggestion
* HA 클러스터에서 모든 `kube-apiserver` 인스턴스는 **{{< skew prevMinorVersion >}}** 또는 **{{< skew latestVersion >}}** 이어야 한다(이것은 `kube-apiserver` 인스턴스 간의 가장 최신과 오래된 버전의 차이를 최대 1개의 마이너 버전의 차이로 보장한다).
```

2020-12-03 09:24 UTC, mylovepooh commented
@yoonian 넵 추가사항 반영했습니다. 꼼꼼하게 리뷰 잘해주시네요. 감사합니다.

2020-12-03 12:14 UTC, yoonian requested changes
@mylovepooh 요기까지 하면 다 된 것 같습니다! 😃

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 최신 `kube-apiserver` 는 **{{< skew latestVersion >}}** 이다.
```suggestion
* 최신 `kube-apiserver`는 **{{< skew latestVersion >}}** 이다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubelet`는 **{{< skew latestVersion >}}**, **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다.
```suggestion
* `kubelet`은 **{{< skew latestVersion >}}**, **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubelet` 은 **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다(**{{< skew latestVersion >}}** 는  `kube-apiserver`의 **{{< skew prevMinorVersion >}}** 인스턴스보다 최신 버전이기 때문에 지
```suggestion
* `kubelet`은 **{{< skew prevMinorVersion >}}** 및 **{{< skew oldestMinorVersion >}}** 을 지원한다(**{{< skew latestVersion >}}** 는  `kube-apiserver`의 **{{< skew prevMinorVersion >}}** 인스턴스보다 최신 버전이기 때문에 지원하지 않는다).
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 그들과 통신하는 `kube-apiserver` 인스턴스보다 최신 버전이면 안 된다. `kube-apiserver` 마이너 버전과 일치할 것으로 예상하지만, 최대 한 단계 낮은 마이너 버전까지는 허용한다(실시간 업그레이
```suggestion
`kube-controller-manager`, `kube-scheduler` 그리고 `cloud-controller-manager`는 그들과 통신하는 `kube-apiserver` 인스턴스보다 최신 버전이면 안 된다. `kube-apiserver` 마이너 버전과 일치할 것으로 예상하지만, 최대 한 단계 낮은 마이너 버전까지는 허용한다(실시간 업그레이드를 지원하기 위해서).
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-apiserver` 은 **{{< skew latestVersion >}}** 이다.
```suggestion
* `kube-apiserver`은 **{{< skew latestVersion >}}** 이다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager`는 **{{< skew latestVersion >}}** 과 **{{< skew prevMinorVersion >}}** 을 지원한다.
```suggestion
* `kube-controller-manager`, `kube-scheduler` 그리고 `cloud-controller-manager`는 **{{< skew latestVersion >}}** 과 **{{< skew prevMinorVersion >}}** 을 지원한다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 는 **{{< skew prevMinorVersion >}}** 에서 지원한다(**{{< skew latestVersion >}}** 는 `kube-apiserver` 인스턴스의 **{{< skew prevMinorV
```suggestion
* `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager`는 **{{< skew prevMinorVersion >}}** 에서 지원한다(**{{< skew latestVersion >}}** 는 `kube-apiserver` 인스턴스의 **{{< skew prevMinorVersion >}}** 버전보다 최신이기 때문에 지원하지 않는다).
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-apiserver` 은 **{{< skew latestVersion >}}** 이다.
```suggestion
* `kube-apiserver`은 **{{< skew latestVersion >}}** 이다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubectl` 은 **{{< skew nextMinorVersion >}}**, **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 을 지원한다.
```suggestion
* `kubectl`은 **{{< skew nextMinorVersion >}}**, **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 을 지원한다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +HA 클러스터의`kube-apiserver` 인스턴스 간에 버전 차이가 있으면 지원되는`kubectl` 버전의 범위도 줄어든다.
```suggestion
HA 클러스터의 `kube-apiserver` 인스턴스 간에 버전 차이가 있으면 지원되는`kubectl` 버전의 범위도 줄어든다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kubectl` 은 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 에서 지원한다(다른 버전은 `kube-apiserver`인스턴스 중에 한 단계 이상의 마이너 버전 차이가 난다).
```suggestion
* `kubectl` 은 **{{< skew latestVersion >}}** 및 **{{< skew prevMinorVersion >}}** 에서 지원한다(다른 버전은 `kube-apiserver` 인스턴스 중에 한 단계 이상의 마이너 버전 차이가 난다).
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 이 서버와 통신하는 `kube-controller-manager`, `kube-scheduler`, 그리고 `cloud-controller-manager` 의 버전은 **{{< skew prevMinorVersion >}}** 이어야 한다(이것은 기존 API서버 버전보다 최신 버전이 아니고 새로운 API서버 버전의 마이너 1개의 버전 내에 있음을 보장
```suggestion
* 이 서버와 통신하는 `kube-controller-manager`, `kube-scheduler` 그리고 `cloud-controller-manager`의 버전은 **{{< skew prevMinorVersion >}}** 이어야 한다(이것은 기존 API서버 버전보다 최신 버전이 아니고 새로운 API서버 버전의 마이너 1개의 버전 내에 있음을 보장한다).
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kube-apiserver` 를 **{{< skew latestVersion >}}** 으로 업그레이드
```suggestion
`kube-apiserver`를 **{{< skew latestVersion >}}** 으로 업그레이드
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +*  `kubelet` 과 통신하는 `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 이어야 한다.
```suggestion
*  `kubelet`과 통신하는 `kube-apiserver` 인스턴스는 **{{< skew latestVersion >}}** 이어야 한다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* 이것은 관리되고 있는 3단계의 마이너 버전보다 낮은 `kubelet` 을 실행할 가능성을 높인다.
```suggestion
* 이것은 관리되고 있는 3단계의 마이너 버전보다 낮은 `kubelet`을 실행할 가능성을 높인다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-proxy` 은 반드시 `kubelet` 와 동일한 마이너 버전이어야 한다.
```suggestion
* `kube-proxy`은 반드시 `kubelet`과 동일한 마이너 버전이어야 한다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-proxy` 은 반드시 `kube-apiserver` 보다 최신 버전이면 안 된다.
```suggestion
* `kube-proxy`은 반드시 `kube-apiserver` 보다 최신 버전이면 안 된다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-proxy` 은 `kube-apiserver.` 보다 2단계 낮은 마이너 버전 이내여야 한다.
```suggestion
* `kube-proxy`은 `kube-apiserver` 보다 2단계 낮은 마이너 버전 이내여야 한다.
```

2020-12-03 12:14 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +* `kube-apiserver` 버전은 반드시 **{{< skew oldestMinorVersion >}}** 에서 **{{< skew latestVersion >}}**사이 이어야 한다.
```suggestion
* `kube-apiserver` 버전은 반드시 **{{< skew oldestMinorVersion >}}** 에서 **{{< skew latestVersion >}}** 사이 이어야 한다.
```

2020-12-03 16:08 UTC, mylovepooh commented
@yoonian 수정해서 반영했습니다. 감사합니다~~

2020-12-04 00:41 UTC, yoonian requested changes
@mylovepooh 이번이 마지막일 듯요!

2020-12-04 00:41 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +HA 클러스터의 `kube-apiserver` 인스턴스 간에 버전 차이가 있으면 지원되는`kubectl` 버전의 범위도 줄어든다.
```suggestion
HA 클러스터의 `kube-apiserver` 인스턴스 간에 버전 차이가 있으면 지원되는 `kubectl` 버전의 범위도 줄어든다.
```

2020-12-04 00:41 UTC, yoonian commented on content/ko/docs/setup/release/version-skew-policy.md
> +`kube-controller-manager`, `kube-scheduler` 및 `cloud-controller-manager` 을 **{{< skew latestVersion >}}** 으로 업그레이드
```suggestion
`kube-controller-manager`, `kube-scheduler` 및 `cloud-controller-manager`를 **{{< skew latestVersion >}}** 으로 업그레이드한다.
```

2020-12-04 01:35 UTC, mylovepooh commented
@yoonian 넵~ 수정했습니다.

2020-12-04 02:13 UTC, yoonian commented
/lgtm

2020-12-06 07:04 UTC, seokho-son commented
감사합니다!!
/approve

2020-12-06 07:05 UTC, merged