ja: Translate reference/command-line-tools-reference/kubelet-authentication-authorization.md into Japanese
kubernetes/website pull request #25633
Opened 2020-12-15 10:21 UTC by kosehy

from #25192

2020-12-16 14:29 UTC, kakts requested changes
ご対応いただき、ありがとうございます!

コメントしましたので、ご確認をお願いいたします。

2020-12-16 14:29 UTC, kakts commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +* `--client-ca-file`フラグで kubletを起動し、クライアント証明書を確認するための CA バンドルを提供します。
```suggestion
* `--client-ca-file`フラグでkubeletを起動し、クライアント証明書を確認するためのCAバンドルを提供します。
```

2020-12-16 14:29 UTC, kakts commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +動詞は、着信要求のHTTP動詞から決定されます:
```suggestion
動詞は、着信リクエストのHTTP動詞から決定されます:
```
ここの要求　➡️　リクエストで良いかと思いました!

2020-12-17 14:09 UTC, kosehy commented
> ご対応いただき、ありがとうございます!
> 
> コメントしましたので、ご確認をお願いいたします。

@kaktsさん詳細レビューしてくださって本当にありがとうございます！@kaktsさんの意見を反映して、再コミットしました！

2020-12-18 02:09 UTC, kakts commented
@kosehy 
修正いただき、ありがとうございます！
/lgtm

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +reviewers:
reviewerブロックは削除しちゃって下さい

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +title: Kubelet 認証/承認
```suggestion
title: Kubelet 認証/認可
```

authorizationは一般に「認可」かと思います

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +ノードとコンテナ内のさまざまなレベルの権限でタスクを実行するようにする。
```suggestion
ノードとコンテナ内のさまざまなレベルの権限でタスクを実行できるようにします。
```

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +kubelet API へのアクセスを細分化するには、次のような多くの理由が考えられます:
```suggestion
kubelet API へのアクセスを細分化するのは、次のような多くの理由が考えられます:
```

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +リソースとサブリソースは、着信リクエストのパスから決定されます:
```suggestion
リソースとサブリソースは、受けとったリクエストのパスから決定されます:
```

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +動詞は、着信リクエストのHTTP動詞から決定されます:
```suggestion
動詞は、受けとったリクエストのHTTP動詞から決定されます:
```

`verb` は 「動詞」ですけど、「メソッド」と読み替えてもいいかもしれないですね

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +* kubeletは、構成されたAPIサーバーで`SubjectAccessReview`APIを呼び出して、各リクエストが承認されているかどうかを判断します。
```suggestion
* kubeletは、構成されたAPIサーバーで`SubjectAccessReview` APIを呼び出して、各リクエストが承認されているかどうかを判断します。
```

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +* ベアラートークン認証は有効になっていますが、kubeletのAPIを呼び出す任意のAPIユーザー（サービスアカウントなど）の機能を制限する必要があります。
```suggestion
* ベアラートークン認証は有効になっていますが、kubeletのAPIを呼び出す任意のAPIユーザー(サービスアカウントなど)の機能を制限する必要があります。
```

2020-12-28 03:39 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +認証に成功した要求（匿名要求を含む）はすべて許可されます。デフォルトの認可モードは、すべての要求を許可する`AlwaysAllow`です。
```suggestion
認証に成功した要求(匿名要求を含む)はすべて許可されます。デフォルトの認可モードは、すべての要求を許可する`AlwaysAllow`です。
```

2020-12-31 13:37 UTC, kosehy commented
@nasa9084さん詳細レビューしてくださって本当にありがとうございます！@nasa9084さんの意見を反映して、再コミットしました！

2021-01-10 14:37 UTC, nasa9084 reviewed
確認遅くなってスミマセン。もう一つコメントしました。

2021-01-10 14:37 UTC, nasa9084 commented on content/ja/docs/reference/command-line-tools-reference/kubelet-authentication-authorization.md
> +kubelet API へのアクセスを細分化するのは、次のような多くの理由が考えられます:
```suggestion
kubelet APIへのアクセスを細分化するのは、次のような多くの理由が考えられます:
```

2021-01-18 04:53 UTC, nasa9084 commented
/approve

2021-01-18 13:32 UTC, nasa9084 commented
/assign

2021-02-01 12:11 UTC, makocchi-git commented
/lgtm

2021-02-01 12:13 UTC, merged