[zh] 2020-05-06-third-party-dual-sourced-content.md
kubernetes/website pull request #25731
Opened 2020-12-20 12:20 UTC by lis102

translation

2020-12-20 12:49 UTC, tengqm commented on content/en/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +去年夏末， SIG Docs 就 Kubernetes 文档中的第三方内容展开了一次社区会谈。这次讨论构建了 [Kubernetes Enhancement Proposal](https://github.com/kubernetes/enhancements/pull/1327)(KEP)，经过五个月的审查和评议， SIG Architecture 批准了 KEP 作为 Kubernetes
构建不合适
内容指南前无需空格
链接应指向中文版本

2020-12-20 12:49 UTC, tengqm commented on content/en/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +>总是允许链接到 Kubernetes 项目（kubernetes 和 kubernetes-sigs GitHub orgs 中的项目）中的活动内容。
'>' 之后需要一个空格，这是 markdown 的语法

2020-12-20 12:49 UTC, tengqm commented on content/en/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +>Kubernetes 需要一些第三方内容发挥作用。包括容器运行（容器， CRI-O， Docker），网络策略（ CNI 插件），入口控制器和日志等示例。
有些空格莫名奇妙

2020-12-20 12:49 UTC, tengqm commented on content/en/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +当文档准确，有用，值得信赖且始终专注于功能时，它们才能发挥最佳性能。根据我们的经验，供应商的内容会削弱信任度和准确性。
```suggestion
当文档准确、有用、值得信赖且始终专注于功能时，它们才能发挥最好的作用。根据我们的经验，供应商的内容会削弱信任度和准确性。
```

2021-01-08 02:04 UTC, howieyuen requested changes

2021-01-08 02:04 UTC, howieyuen commented on content/zh/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +某些读者认为有帮助的内容将被删除。为了确保读者可以持续访问这些信息，我们将向相关者保持开放直至[1.19文档发布截止日期](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.19)。**2020年7月9日**会将原定要删除的所有内容重新存放。
1.19 文档发布截止日期
数字前后分别加一个空格

2021-01-08 02:04 UTC, howieyuen commented on content/zh/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +在接下来的几个月中，随着贡献者打开 PR 删除内容，您将在文档中看到更少的第三方内容。
您 -> 你

2021-01-08 02:04 UTC, howieyuen commented on content/zh/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +Kubernetes 文档如何处理_dual-sourced content_虽然影响较小但同样重要。双源内容是在多处或从非规范来源发布的内容。
_dual-sourced content_ 前后加个空格

2021-01-08 02:04 UTC, howieyuen commented on content/zh/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +我们正在 [issue in the Kubernetes website repository](https://github.com/kubernetes/website/issues/20232) 跟踪第三方内容。如果您看到第三方内容超出项目范围并且不是 Kubernetes 正常运行所必需的，请对跟踪问题发表评论。
Kubernetes website 仓库的 issue 中

2021-01-08 02:04 UTC, howieyuen commented on content/zh/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +识别出不合格内容后，即可随意打开PR！
空格
即可随意打开 PR！

2021-01-08 02:04 UTC, howieyuen commented on content/zh/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +更多信息，请阅读问题描述[tracking third party content](https://github.com/kubernetes/website/issues/20232)。
追踪第三方内容

2021-01-08 15:37 UTC, bradtopol commented
/assign @kbarnard10 
/assign @tengqm

2021-01-08 17:26 UTC, onlydole requested changes
LGTM with one nit

2021-01-08 17:26 UTC, onlydole commented on content/en/blog/_posts/2020-05-06-third-party-dual-sourced-content.md
> +For more information, read the issue description for [tracking third party content](https://github.com/kubernetes/website/issues/20232).
```suggestion
For more information, read the issue description for [tracking third party content](https://github.com/kubernetes/website/issues/20232).
```
It'd be helpful to remove these extra spaces

2021-01-09 02:59 UTC, tengqm commented
@lis102 are you still working on this?

2021-02-06 06:52 UTC, tengqm commented
@lis102 Please respond to the review comments when convenient. Thanks.

2021-02-28 02:29 UTC, kbhawkey commented
👋 @lis102 .
Are you working on this PR? Reach out if you need help.

2021-03-26 10:24 UTC, tengqm commented
Feel free to reopen this when you get cycle to continue.
/close

2021-03-26 10:25 UTC, closed without merging