[zh]Synchronize with "/zh/docs/reference/kubectl/conventions/" in English
kubernetes/website pull request #25796
Opened 2020-12-24 08:00 UTC by yuandongx

I read the doc in Chinese and found a file is outdate.

2020-12-24 08:03 UTC, yuandongx commented
/assign @tengqm

2020-12-24 08:06 UTC, yuandongx commented
/assign @howieyuen

2020-12-24 08:32 UTC, howieyuen requested changes

2020-12-24 08:32 UTC, howieyuen commented on content/zh/docs/reference/kubectl/conventions.md
> +  rolebinding         为特定角色或ClusterRole创建 RoleBinding。
为特定角色或 ClusterRole 创建 RoleBinding。

2020-12-24 08:32 UTC, howieyuen commented on content/zh/docs/reference/kubectl/conventions.md
> +  namespace           使用指定的名称创建命名空间。
使用指定的名称创建名称空间。
ps：很多开发者习惯使用”命名空间“来翻译 namespace，文档库中基本都是使用”名称空间“，保持一致。

2020-12-24 08:32 UTC, howieyuen commented on content/zh/docs/reference/kubectl/conventions.md
> +<!--All `kubectl run` generators are deprecated.See the Kubernetes v1.17 documentation for a [list](https://v1-17.docs.kubernetes.io/docs/reference/kubectl/conventions/#generators) of generators and
注释符号保持单独一行，方便review
```
<!--
xxxx
-->
```

2020-12-24 08:32 UTC, howieyuen commented on content/zh/docs/reference/kubectl/conventions.md
> +<!--You can generate the following resources with a kubectl command, `kubectl create --dry-run=client -o yaml`:-->
同上

2020-12-24 09:38 UTC, yuandongx commented on content/zh/docs/reference/kubectl/conventions.md
> +  rolebinding         为特定角色或ClusterRole创建 RoleBinding。
Thanks, done.

2020-12-24 09:38 UTC, yuandongx commented on content/zh/docs/reference/kubectl/conventions.md
> +  namespace           使用指定的名称创建命名空间。
Thanks, done.

2020-12-24 11:05 UTC, howieyuen commented
/lgtm

2020-12-25 12:55 UTC, tengqm commented on content/zh/docs/reference/kubectl/conventions.md
> +所以的 `kubectl run` 生成器已弃用。
所有的

2020-12-28 01:42 UTC, tengqm commented on content/zh/docs/reference/kubectl/conventions.md
> +  poddisruptionbudget 使用指定名称创建 Pod 中断预算。
Pod 干扰预算

2020-12-28 01:42 UTC, tengqm commented on content/zh/docs/reference/kubectl/conventions.md
> +  secret              使用指定的子命令创建密钥。
密钥 -> Secret

2020-12-28 01:43 UTC, tengqm commented on content/zh/docs/reference/kubectl/conventions.md
> +```
请以注释形式附上 91-107 的英文原文

2020-12-28 02:26 UTC, tengqm commented
/approve

2020-12-28 02:31 UTC, howieyuen commented
/lgtm

2020-12-28 02:32 UTC, merged