[zh] sync /reference/using-api/_index.md
kubernetes/website pull request #25809
Opened 2020-12-25 07:02 UTC by yuandongx

2020-12-25 08:41 UTC, yuandongx commented
/assign @tengqm 
/assign @howieyuen

2020-12-25 10:07 UTC, howieyuen requested changes

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +以下是 Kubernetes 中的几个成组：
以下是 Kubernetes 中的几个 API 组：

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +   核心成组不被指定为 `apiVersion` 字段的一部分，例如， `apiVersion: v1`。
未将核心组指定为 `apiVersion` 字段的一部分，例如， `apiVersion: v1`。

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +   查看全部的 API 成组。
查看全部的 API 组。

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +*  被命名的成组位于 REST 路径为 `/apis/$GROUP_NAME/$VERSION`，
命名组位于 REST 路径 `/apis/$GROUP_NAME/$VERSION`，

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +##　使用或禁用 API 成组   {#enabling-or-disabling}
启用或禁用 API 组

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +默认情况下资源和 API 成组是可使用的。
默认情况下，某些资源和 API 组已启用。

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +你可以通过设置 `--runtime-config` 参数为逗号分隔的 `<key>[=<value>]` 键值对
`--runtime-config` 标志接受逗号分隔的 `<key>[=<value>]` 对，描述 API 服务器的运行时配置。

2020-12-25 10:07 UTC, howieyuen commented on content/zh/docs/reference/using-api/_index.md
> +来设置置 API 服务器上运行配置。如果键值对省略了 `=<value>`，那么视该键值为 `=true`。
如果省略了 `=<value>` 部分，则将其视为指定了 `=true`。

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  - 软件可能会有 Bug。使能某个特性门控可能会暴露出 Bug。
```suggestion
  - 软件可能会有 Bug。启用某个特性门控可能会暴露出 Bug。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  - 对象的模式和（或）语义可能以不兼容的方式改变随后的 Beta 版或稳定版。
```suggestion
  - 在随后的 Beta 版或稳定版中，对象的模式和（或）语义可能以不兼容的方式改变。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +    架构更改可能需要删除、编辑和重建 API 对象。
```suggestion
    模式更改可能需要删除、编辑和重建 API 对象。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +    后续发布版本可能会有兼容性变动。
```suggestion
    后续发布版本可能会有不兼容的变动。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  请试用测试版特性门控时并提供反馈。特性门控完成 Beta 阶段测试后，
```suggestion
  请试用测试版特性并提供反馈。特性完成 Beta 阶段测试后，
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  它就可能不会有太多的变更了。
```suggestion
  就可能不会有太多的变更了。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  - 功能的稳定版本出现在后续子版本的发布软件中。
```suggestion
  - 功能的稳定版本会出现在后续很多版本的发布软件中。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +使扩展 Kubernetes API 变得更简单。
```suggestion
能够简化对 Kubernetes API 的扩展。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +REST 路径和序列化对象中的 `apiVersion` 字段指定了 API 组。
```suggestion
API 组信息出现在REST 路径中，也出现在序列化对象的 `apiVersion` 字段中。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +   未将核心组指定为 `apiVersion` 字段的一部分，例如， `apiVersion: v1`。
```suggestion
   核心组并不作为 `apiVersion` 字段的一部分，例如，`apiVersion: v1`。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +*  被命名的组位于 REST 路径为 `/apis/$GROUP_NAME/$VERSION`，
```suggestion
*  指定的组位于 REST 路径 `/apis/$GROUP_NAME/$VERSION`，
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +   查看全部的 API 组。
```suggestion
   中查看全部的 API 组。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +##　使用或禁用 API 组   {#enabling-or-disabling}
```suggestion
##　启用或禁用 API 组   {#enabling-or-disabling}

```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +默认情况下资源和 API 组是可使用的。
```suggestion
资源和 API 组是在默认情况下被启用的。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +你可以通过设置 `--runtime-config` 参数接受逗号分隔的 `<key>[=<value>]` 对，
```suggestion
`--runtime-config` 参数接受逗号分隔的 `<key>[=<value>]` 对，
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +Kubernetes 通过 API 资源来将可序列化的状态写到 {{< glossary_tooltip term_id="etcd" >}} 中以进行存储。
```suggestion
Kubernetes 通过 API 资源来将序列化的状态写到 {{< glossary_tooltip term_id="etcd" >}} 中存储。
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +- 了解更多关于 [API 惯例](https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#api-conventions)
```suggestion
- 进一步了解 [API 惯例](https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#api-conventions)
```

2020-12-28 01:55 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +- 查阅设计文档以了解 [聚合器](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/aggregated-api-servers.md)
```suggestion
- 阅读[聚合器](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/api-machinery/aggregated-api-servers.md)
  的设计文档
```

2020-12-28 02:38 UTC, tengqm reviewed
feature gate -> 特性门控
feature -> 特性

2020-12-28 02:38 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  - 尽管一些特性门控会发生细节上的变化，但它们将会被长期支持。
```suggestion
  - 尽管一些特性会发生细节上的变化，但它们将会被长期支持。
```

2020-12-28 02:38 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  - 软件可能会有 Bug。启用某个特性门控可能会暴露出 Bug。
```suggestion
  - 软件可能会有 Bug。启用某个特性可能会暴露出 Bug。
```

2020-12-28 02:38 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +    某些特性门控可能默认禁用。
```suggestion
    某些特性可能默认禁用。
```

2020-12-28 02:38 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  - 对某个特性门控的支持可能会随时被删除，恕不另行通知。
```suggestion
  - 对某个特性的支持可能会随时被删除，恕不另行通知。
```

2020-12-28 02:38 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +    特性门控默认开启。
```suggestion
    特性默认被启用。
```

2020-12-28 02:38 UTC, tengqm commented on content/zh/docs/reference/using-api/_index.md
> +  请试用测试版特性门控时并提供反馈。特性门控完成 Beta 阶段测试后，
```suggestion
  请试用 Beta 特性时并提供反馈。特性完成 Beta 阶段测试后，
```

2021-01-08 01:40 UTC, howieyuen commented
/lgtm

2021-01-08 02:23 UTC, tengqm commented
/approve

2021-01-08 02:24 UTC, merged