[zh] Resync kubelet configuration
kubernetes/website pull request #25812
Opened 2020-12-25 10:00 UTC by tengqm

The kubelet reference was out-of-sync, and there have been some new changes in 1.20. This PR does a fresh resync.

2020-12-25 10:11 UTC, howieyuen commented
Every time I see your PR, I have kind of foreboding... cause it is a huge one 😨

2020-12-25 10:28 UTC, tengqm commented
@howieyuen It was huge. It took me 4 hours to get it done. I had to run `kubelet --help` on 1.20, cross verify the English version (which is also outdated) and the Chinese version (much older).

2020-12-25 10:30 UTC, tengqm commented
preview: https://deploy-preview-25812--kubernetes-io-master-staging.netlify.app/zh/docs/reference/command-line-tools-reference/kubelet/

2020-12-29 03:33 UTC, howieyuen requested changes

2020-12-29 03:33 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +为 kubernetes 组件所预留的计算资源。例如：<code>"/kube-reserved</code>。
"/kube-reserved" or /kube-reserved ?

2020-12-29 03:33 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +<code>--skip-log-headers</code>, <code>--stderrthreshold</code>, <code>--log-flush-frequency</code>.。
extra English dot ('.')

2020-12-29 03:33 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +设置用于管理 kubelet 文件的根目录（例如挂载卷的相关文件）。
（例如挂载卷的相关文件等）

2020-12-29 03:33 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +设置长时间运行的请求（包括 <code>pull</code>、<code>logs</code>、<code>exec</code>
设置除了长时间运行的请求

2020-12-29 03:33 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +和 <code>attach</code> 等操作）之外的其他请求的超时时间。
其他运行时请求的超时时间。

2020-12-29 03:39 UTC, howieyuen commented
It takes me one hour and a half to finish reviewing~~~hope these are valuable suggestions

2020-12-29 06:27 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +云驱动配置文件的路径。空字符串表示没有配置文件。
opt to 云驱动，changed across the whole page.

2020-12-29 06:31 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +&lt;警告：beta 特性&gt; 设置容器日志文件在轮换生成新文件时之前的最大值。
no. 原文“Set the maximum size (e.g. 10Mi) of container log file before it is rotated.". 这里特意强调 before it is rotated. 日志何时转储（dump 或者 flush）与此无关。可能进程已经在向新的文件写入了，老的文件的数据还有部分位于内存中，尚未落盘。

2020-12-29 06:37 UTC, tengqm commented
> It takes me one hour and a half to finish reviewing~~~hope these are valuable suggestions

Thanks for the huge effort. I cannot figure out for how long this page has been outdated. It was a huge effort to sync and to review.

2020-12-29 06:39 UTC, howieyuen commented
/lgtm

2021-01-06 06:13 UTC, xichengliudui commented
/approve

2021-01-06 06:13 UTC, merged