content/es/docs/concepts/configuration/manage-resources-containers.md
kubernetes/website pull request #25920
Opened 2021-01-02 21:00 UTC by Anynou

Add content/es/docs/concepts/configuration/manage-resources-containers.md

2021-01-02 21:00 UTC, Anynou commented
I think I have solved the problem with CLA

2021-01-06 18:24 UTC, sftim reviewed
One question

2021-01-06 21:09 UTC, Anynou commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +  title: Automatic bin packing
The original page (english) has that title. I don't know if I have to change it.

2021-01-07 11:28 UTC, raelga commented
Thanks @Anynou for the PR, let me review it and get back to you asap.

:)

2021-01-11 19:18 UTC, electrocucaracha reviewed
Envio primeras observaciones

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Los límites y solicitudes de `memoria` son medidos en bytes. Puedes expresar la memoria como
```suggestion
Los límites y peticiones de `memoria` son medidos en bytes. Puedes expresar la memoria como
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +un integral como un número decimal usando alguno de estos sufijos:
```suggestion
un número entero o como un número decimal usando alguno de estos sufijos:
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +E, P, T, G, M, K. También puedes usar el poder de dos equivalentes: Ei, Pi, Ti, Gi,
```suggestion
E, P, T, G, M, K. También puedes usar los equivalentes en potencia de dos: Ei, Pi, Ti, Gi,
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +El siguiente Pod tiene dos Contenedores. Cada Contenedor tiene una solicitud de 0.25 cpu
```suggestion
El siguiente Pod tiene dos contenedores. Cada contenedor tiene una petición de 0.25 cpu
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +y 64MiB (2<sup>26</sup> bytes) de memoria. Cada Contenedor tiene un límite de 0.5 cpu
```suggestion
y 64MiB (2<sup>26</sup> bytes) de memoria. Cada contenedor tiene un límite de 0.5 cpu
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +## Cómo son colocados los Pods con solicitudes de recursos
```suggestion
## Cómo son programados los Pods con solicitudes de recursos
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Cuando creas un Pod, el scheduler de Kubernetes selecciona un nodo para correr el Pod.
```suggestion
Cuando creas un Pod, el Scheduler de Kubernetes determina el nodo para correr dicho Pod.
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +la cantidad de CPU y memoria que dispone para los Pods. El scheduler se asegura de que,
```suggestion
la cantidad de CPU y memoria que dispone para los Pods. El Scheduler se asegura de que,
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +colocados es menor que la capacidad del nodo. Aunque los recursos de memoria y CPU
```suggestion
 para cada tipo de recurso, la suma de los recursos solicitados de los contenedores programados sea menor a la capacidad del nodo. Cabe mencionar que aunque la memoria actual o CPU
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +en uso de los nodos es muy baja, el scheduler todavía rechaza colocar un Pod en un nodo si
```suggestion
en uso de los nodos sea muy baja, el Scheduler todavía rechaza programar un Pod en un nodo si
```

2021-01-11 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +solictudes de  recursos.
```suggestion
solicitud de  recursos.
```

2021-01-11 19:41 UTC, Anynou commented
He aceptado los cambios que has indicado.

2021-01-14 20:52 UTC, raelga commented
Genial @Anynou, puedes hacer un squash y dejarlo en un solo commit?

/label tide/merge-method-squash

2021-01-23 08:11 UTC, Anynou commented
No sé si tengo que hacerlo yo. No veo dónde hacerlo en github.

2021-01-25 00:02 UTC, electrocucaracha commented
> No sé si tengo que hacerlo yo. No veo dónde hacerlo en github.

Tienes que hacerlo tu, por lo general yo uso el rebase interactivo `git rebase -i <commit-id>`

2021-01-25 09:25 UTC, raelga commented
@Anynou si quieres, lo comentamos en slack y lo dejamos listo en un momento.

2021-01-31 09:02 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +  title: Automatic bin packing
Es complicada de traducir la verdad, la traducción literal es `Empaquetamiento en Contenedores` pero es un problema computación conocido por el nombre en inglés: https://developers.google.com/optimization/bin/bin_packing

```suggestion
  title: Bin packing automático
```

2021-02-08 15:57 UTC, electrocucaracha reviewed
Envio otras observaciones

2021-02-08 15:57 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +filesystem de los volúmenes `emptyDir` , en el nodo, provee soporte de
```suggestion
Sistema de archivos de los volúmenes `emptyDir` , en el nodo, provee soporte de
```

2021-02-08 15:57 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Por ejemplo, XFS y ext4fs ofrecen cuotas de proeycto.
```suggestion
Por ejemplo, XFS y ext4fs ofrecen cuotas de proyecto.
```

2021-02-08 15:57 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Las cuotas de proyecto te permiten monitorizar el uso del almacenamiento; no
```suggestion
Las cuotas de proyecto te permiten monitorear el uso del almacenamiento; no 
```

2021-02-08 15:57 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +ene ste rango son usados para otros propósitos en el sistema, esos IDs
```suggestion
en este rango son usados para otros propósitos en el sistema, esos IDs 
```

2021-02-08 15:57 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +que kubernetes no los use.
```suggestion
que Kubernetes no los use.
```

2021-02-12 15:00 UTC, Anynou commented
Aceptadas las sugerencias

2021-02-18 13:27 UTC, raelga commented
> Aceptadas las sugerencias

Gracias!

2021-03-04 09:53 UTC, raelga commented
/assign

2021-03-09 18:56 UTC, raelga requested changes
Muchísimas gracias de nuevo @Anynou, en la review principalmente he añadido unos cuantos tooltips y alguna que otro error tipográfico. 

Si puedes echarle un ojo a la review y la de @electrocucaracha, así acabamos de perfilar el documento para publicarlo 🎉

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Si configuras un límite de `memory` de 4GiB  para el contenedor, Kubelet (y
```suggestion
Si configuras un límite de `memory` de 4GiB  para el contenedor, {{< glossary_tooltip text="kubelet" term_id="kubelet" >}})
 (y
```

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +en un Pod colocado en un nodo con 8GiB de memoria y no hay otros Pods, entonces el contenedor puede intentar usar
```suggestion
en un {{< glossary_tooltip term_id="pod" >}} colocado en un nodo con 8GiB de memoria y no hay otros {{< glossary_tooltip term_id="pods" >}}, entonces el contenedor puede intentar usar
```

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Por ejemplo, si configuras una petición de `memory` de 256 MiB  para un contenedor, y ese contenedor está
```suggestion
Por ejemplo, si configuras una petición de `memory` de 256 MiB  para un {{< glossary_tooltip text="contenedor" term_id="container" >}}, y ese contenedor está
```

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Sin embargo, un contenedor no está autorizado a utilizar más de lo especificado en `limit`.
```suggestion
Sin embargo, un {{< glossary_tooltip text="contenedor" term_id="container" >}} no está autorizado a utilizar más de lo especificado en `limit`.
```

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +El Runtime evita que el contenedor use más recursos de los configurados en el límite. Por ejemplo:
```suggestion
El Runtime evita que el {{< glossary_tooltip text="contenedor" term_id="container" >}} use más recursos de los configurados en el límite. Por ejemplo: 
```

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +{{< glossary_tooltip text="container runtime" term_id="container-runtime" >}})  impone el límite.
```suggestion
{{< glossary_tooltip text="container runtime" term_id="container-runtime" >}}) impone el límite.
```

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +cuando un proceso en el contenedor intenta consumir más cantidad de memoria de la permitida,
```suggestion
cuando un proceso en el {{< glossary_tooltip text="contenedor" term_id="container" >}} intenta consumir más cantidad de memoria de la permitida,
```

2021-03-09 18:56 UTC, raelga commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +y consumidas. Son distintas a los [Recursos API](/docs/concepts/overview/kubernetes-api/). Los recursos API , como Pods y
```suggestion
y consumidas. Son distintas a los [Recursos API](/docs/concepts/overview/kubernetes-api/). Los recursos API , como {{< glossary_tooltip text="Pods" term_id="pod" >}} y 
```

2021-03-10 15:53 UTC, electrocucaracha reviewed
Agrego mas observaciones. Dado que @Karmavil esta traduciendo un tema relacionado seria bueno tener su revisión /cc @Karmavil

2021-03-10 15:53 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +    Coloca los contenedores automáticamente con base en los recursos solicitados y otras limitaciones, mientras no se afecte la
@raelga me parece que es correcta la expresion "con base en". https://www.diccionariodedudas.com/con-base-en-en-base-a-o-con-base-a/

2021-03-10 15:53 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +{{< glossary_tooltip text="container runtime" term_id="container-runtime" >}})  impone el límite.
Seria bueno traducir `container runtime`? 

```suggestion
{{< glossary_tooltip text="motor de ejecución del contenedor" term_id="container-runtime" >}})  impone el límite.
```

2021-03-10 15:53 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +sobre los recursos de peticiones y límites del Pod. Un *limite/peticion de recursos de un Pod* para un tipo de recurso particular es la suma de
```suggestion
sobre los recursos de peticiones y límites del Pod. Un *limite/petición
 de recursos de un Pod* para un tipo de recurso particular es la suma de
```

2021-03-10 15:53 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +0.1 es la misma contidad de cpu que un core-simple, dual-core, o máquina de 48-core.
```suggestion
0.1 es la misma cantidad de cpu que un core-simple, dual-core, o máquina de 48-core.
```

2021-03-10 15:53 UTC, electrocucaracha commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +Cundo el kubelet inicia un Contenedor de un Pod, este pasa los límites de CPU y
```suggestion
Cuando el {{< glossary_tooltip text="kubelet" term_id="kubelet" >}} inicia un {{< glossary_tooltip text="contenedor" term_id="container" >}} de un {{< glossary_tooltip text="Pod" term_id="pod" >}}, este pasa los límites de CPU y
```

2021-03-12 15:40 UTC, Karmavil approved these changes
Reviewing suggested changes. I don't know why I was assigned to this I don't see my name here and I'm just a contributor. But it looks OK, let's proceed

2021-03-12 15:43 UTC, Karmavil commented
NO! I just check 2 change suggestions, not the entire PR
Solo revisé 2 correcciones, de ninguna manera intento aprobar el PR en su totalidad

2021-03-13 01:53 UTC, Karmavil commented on content/es/docs/concepts/configuration/manage-resources-containers.md
> +en un Pod colocado en un nodo con 8GiB de memoria y no hay otros Pods, entonces el contenedor puede intentar usar
Remplaza `{{< glossary_tooltip term_id="pods" >}}` por `{{< glossary_tooltip text="Pods" term_id="pod" >}}`
para evitar errores con el build

2021-03-13 02:09 UTC, Karmavil requested changes
Los cambios ingresados en las líneas 36 y 75 te estan dando un error al momento de levantar el sitio. Como no sé si lo que veo en la página son los cambios más recientes voy a comentar solo eso:
Remplaza en las líneas 36 y 75 `{{< glossary_tooltip term_id="pods" >}}` por `{{< glossary_tooltip text="Pods" term_id="pod" >}}`

Intenté dejar esto en un comentario pero no persistió, no quedó como un comentario así que pongo un review del tipo request changes

2021-03-13 20:16 UTC, Karmavil commented
Quick question: Is **[/buildify](https://prow.k8s.io/command-help#buildify)** or **/buildifier** the right tag/label to trigger the build again?

2021-03-14 14:30 UTC, Karmavil commented
### Outdated deploy preview

@Anynou no puedo ver los cámbios más recientes en el `Deploy preview` de **Netlify** porque no está haciendo el build correcto.
* Tu último **commit** (en éste momento) es: `1f2ad80`
```php
 Anynou and others added 11 commits 6 hours ago # <- Fecha
... 
Update content/es/docs/concepts/configuration/manage-resources-contai… · 1f2ad80  # El último en la lista del commit
```

* **netlify** está haciendo un _build_ con el **commit** `cad470b` 
```php
Anynou and others added 55 commits 2 days ago   # <- Fecha
...
Update content/es/docs/concepts/configuration/manage-resources-contai…  · cad470b # Es el 1ro listado en el commit
```

> Causa: Posiblemente algún glossary_tooltip mal referenciado. 

___

#### TL;DR

Considero que **Netlify** no está **notificando claramente** que a razón de que el útlimo build falló se utiliza el último commit sin errores en la construcción . 

Para quien desea ver el preview tendría que revisar primero el historial del PR, entender el estado actual y verificar uno mismo si se están utilizando los últimos cambios o no.

Entiendo que podría sugerir cambios, pero creo que es mejor una explicación para otras personas que deseen contribuir en la documentación. Yo mismo no entendía el problema.

Y a su vez, me hago un "borrador" de lo que sería una la solicitud de cambio para el Netlify ya que en este momento no sé si le corresponde a **sig-docs** evaluarlo y transferirlo o es algo que se puede proponer directamente a otro sig como por ejempo **sig-contribex**

2021-03-14 21:54 UTC, Anynou commented
@Karmavil He revisado el fichero y había un error en la linea 36. Lo he corregido y he probado en local y sí que funciona el build, por lo que debería de funcionar el despliegue.
Si queréis revisar todo, por si hubiera más sugerencias y cuando esté listo hago el rebase de todos los commits.
/buildify

2021-03-14 23:06 UTC, Karmavil commented
> @Karmavil He revisado el fichero y había un error en la linea 36. Lo he corregido y he probado en local y sí que funciona el build, por lo que debería de funcionar el despliegue.
> Si queréis revisar todo, por si hubiera más sugerencias y cuando esté listo hago el rebase de todos los commits.

Fui lo mas descriptivo que pude porque entiendo que esto implica mucho trabajo.

Preferiría no discutir aqui lo que no está relacionado con el contenido por lo que te dejo un  mensaje por slack. Para cuando te puedas darte un tiempo para hablar de otra cosa. Saludos y gracias por contribuir 👍

2021-03-25 08:11 UTC, raelga approved these changes
Muchas gracias @Anynou y perdón por la demora. Enhorabuena por el documento!

Por mi parte,

/lgtm

@electrocucaracha y @Karmavil si podéis validar vuestras revisiones, lo publicamos!

2021-03-25 08:13 UTC, merged

2021-03-25 08:19 UTC, raelga commented
Lo siento @electrocucaracha y @Karmavil, al darle LGTM desde el comentario de aprobar la revisión, se ha ejecutado una _doble_ aprobación que ha provocado el merge.

Lo tendré en cuenta la próxima vez!

@Anynou la página está publicada! 🎉  https://kubernetes.io/es/docs/concepts/configuration/manage-resources-containers/

Bienvenido a kubernetes :)