Update kube-proxy.md
kubernetes/website pull request #26035
Opened 2021-01-10 14:30 UTC by distributethe6ix

Adding clarification for potential types of Kube-proxies, and clarification as to when to use which. This is going under the CLI reference page as there is no specific page for Kube-proxy.
Reference https://github.com/kubernetes/website/issues/24950

2021-01-10 14:45 UTC, jayunit100 commented
/assign @rikatz

2021-01-10 14:49 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +•	You can make your own proxy with custom behavior (antrea, cilliim, calico? and leverage from the ideas of the implementation of kube-proxy.
Change the first character to "*" please :)

Also, is this a question or a conclusion? I guess we can remove the examples of the CNIs implementations and leave something just like "You can make your own proxy [...] (without the thing between parenthesis)

2021-01-10 14:54 UTC, rikatz requested changes
Hey @distributethe6ix and welcome :)

I've made the first round of review here, will take a better look carefully later

2021-01-10 14:54 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +•	You can make your own proxy with custom behavior (antrea, cilliim, calico? and leverage from the ideas of the implementation of kube-proxy.
Change the first character to "*" please :)

Also, is this a question or a conclusion? I guess we can remove the examples of the CNIs implementations and leave something just like "You can make your own proxy [...] (without the thing between parenthesis)

2021-01-10 14:54 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +•	The users-space proxy creates a new go routine for every service, this is rarely used, as kernel proxies (which use HNS, IPTables, IPVS, and so on) are much faster and scalable
Replace all the first characters here with '*'

2021-01-10 14:54 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +
Replace '-' for '*' here, otherwise Markdown wont render the bullet item list

2021-01-10 14:54 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +-	Iptables Proxy – Kube-proxy observes the cluster for changes and will proceed to open up a TCP port on the Worker Node but traffic goes from the IPTables to the Kubernetes Service object mapped to
It's not only TCP here

2021-01-10 14:54 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +-	Iptables Proxy – Kube-proxy observes the cluster for changes and will proceed to open up a TCP port on the Worker Node but traffic goes from the IPTables to the Kubernetes Service object mapped to
Also, I would replace the 'Suggested to use' to 'You should use readiness probe to ensure Pods are up and responsive before traffic is sent to it'

2021-01-10 14:56 UTC, rikatz commented
You also can take a look into the generated page here: https://deploy-preview-26035--kubernetes-io-master-staging.netlify.app/docs/reference/command-line-tools-reference/kube-proxy/

2021-01-10 18:42 UTC, rikatz commented
/cc

2021-01-10 18:43 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +•	The users-space proxy creates a new go routine for every service, this is rarely used, as kernel proxies (which use HNS, IPTables, IPVS, and so on) are much faster and scalable
also, user space (in singular) here

2021-01-10 18:44 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +-	User-space proxy – a deprecated mode of operation in which the Kube-proxy watches for changes to a cluster and will open up a TCP-based port on a Worker Node in the cluster. Iptables is responsible
@jayunit100 by windows side, do you know if user space proxy deals only with TCP protocol? I have no idea in Linux, will have to test

2021-01-10 18:45 UTC, rikatz commented on content/en/docs/reference/command-line-tools-reference/kube-proxy.md
> +•	You can make your own proxy with custom behavior (antrea, cilliim, calico? and leverage from the ideas of the implementation of kube-proxy.
Is there in any other reference docs Use-cases? I'm trying to figure out what's the point of having this here :)

2021-01-12 19:01 UTC, sftim commented
/sig network

2021-01-12 19:04 UTC, sftim requested changes
Hi @distributethe6ix 

Would you be willing to reformat these changes as [Markdown](https://daringfireball.net/projects/markdown/syntax)? That's for format of the rest of the document. 

The headings, hyperlink, and some bullet points aren't right at the moment. If you can, follow the documentation [style guide](https://kubernetes.io/docs/contribute/style/style-guide/).

2021-01-13 03:39 UTC, tengqm commented
This file is auto-generated, please do not change it.
The text and options come from the upstream source code (https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-proxy/app/server.go#L467-L473).

There are two options as I see it.

- Convince the upstream project to add these texts to the command line message. I am not sure this long text is suitable for command line help message, though.
- Find another place in the docs website and put the text there.

/hold

2021-03-09 19:48 UTC, rikatz commented
/unassign

Maybe this should be closed

2021-03-11 02:15 UTC, tengqm commented
/close

2021-03-11 02:15 UTC, closed without merging