[WIP]Update outdated files in the dev-1.20-ko.3 branch (2)
kubernetes/website pull request #26122
Opened 2021-01-17 05:30 UTC by pjhwa

Update outdated files in the upstream/dev-1.20-ko.3 branch.

### 16 files are updated
- [x]  M24.  `content/en/docs/reference/command-line-tools-reference/feature-gates.md`  | 2(+XS) 1(-)
- [x]  M25.  `content/en/docs/reference/kubectl/cheatsheet.md`  | 5(+XS) 0(-)
- [x]  M26.  `content/en/docs/reference/kubectl/conventions.md`  | 16(+S) 17(-)
- [x]  M27.  `content/en/docs/reference/kubectl/docker-cli-to-kubectl.md`  | 1(+XS) 6(-)
- [x]  M29.  `content/en/docs/setup/production-environment/container-runtimes.md`  | 75(+M) 11(-)
- [x]  M31.  `content/en/docs/tasks/access-application-cluster/connecting-frontend-backend.md`  | 51(+M) 40(-)
- [x]  M32.  `content/en/docs/tasks/manage-kubernetes-objects/kustomization.md`  | 5(+XS) 4(-)
- [x]  M33.  `content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html`  | 1(+XS) 3(-)
- [ ]  M34.  `content/en/examples/application/deployment.yaml`  | 1(+XS) 1(-)
- [ ]  M35.  `content/en/examples/application/guestbook/frontend-deployment.yaml`  | 1(+XS) 1(-)
- [ ]  M36.  `content/en/examples/application/guestbook/redis-master-deployment.yaml`  | 1(+XS) 1(-)
- [ ]  M37.  `content/en/examples/application/guestbook/redis-slave-deployment.yaml`  | 1(+XS) 1(-)
- [ ]  M38.  `content/en/examples/application/mysql/mysql-deployment.yaml`  | 1(+XS) 1(-)
- [ ]  M39.  `content/en/examples/application/wordpress/mysql-deployment.yaml`  | 1(+XS) 1(-)
- [ ]  M40.  `content/en/examples/application/wordpress/wordpress-deployment.yaml`  | 1(+XS) 1(-)
- [ ]  M41.  `content/en/examples/service/access/Dockerfile`  | 1(+XS) 1(-)
 
### 2 files are renamed
- [x]  R1.  R091 `content/en/examples/service/access/hello.yaml` -> `content/en/examples/service/access/backend-deployment.yaml`
- [x]  R2.  R095 `content/en/examples/service/access/hello-service.yaml` -> `content/en/examples/service/access/backend-service.yaml`

### 2 files are deleted
- [x]  D1.  `content/en/examples/service/access/frontend.conf`
- [x]  D2.  `content/en/examples/service/access/frontend.yaml`

### 2 files not updated which were already applied for Korean
- [x]  M28.  `content/en/docs/reference/scheduling/config.md`  | 1(+XS) 1(-)
- [x]  M30.  `content/en/docs/tasks/access-application-cluster/configure-access-multiple-clusters.md`  | 1(+XS) 1(-)

2021-01-17 06:22 UTC, pjhwa commented
/assign @yoonian

2021-01-18 06:43 UTC, seokho-son commented
@pjhwa 
 D1. content/en/examples/service/access/frontend.conf
 D2. content/en/examples/service/access/frontend.yaml

관련된 내용은 connecting-frontend-backend.md 에 포함되어 있네요. 원문을 찾아보니, 원문이 이미 변경되어 있는 상태이군요.
현재 한글화 문서가 원문과 다소 차이가 나므로, D1-D2 도 connecting-frontend-backend.md 와 함께 따로 처리하는 것이 좋을 것 같습니다.

\content/ko/docs/tasks/access-application-cluster/connecting-frontend-backend.md
```
:{{< codenew file="service/access/frontend.conf" >}}
```

content/ko/docs/tasks/access-application-cluster/connecting-frontend-backend.md
```
:{{< codenew file="service/access/frontend.yaml" >}}
:kubectl apply -f https://k8s.io/examples/service/access/frontend.yaml
```

2021-01-19 00:54 UTC, seokho-son commented
@pjhwa connecting-frontend-backend 갱신,벌써 진행해주셨네요.. ^^ 감사합니다!!

2021-01-19 00:56 UTC, pjhwa commented
> @pjhwa connecting-frontend-backend 갱신,벌써 진행해주셨네요.. ^^ 감사합니다!!

다시 원문이랑 비교해보니 파일이 추가도 되고, 파일명이 변경도 되었더라고요. :-)

2021-01-19 05:18 UTC, yoonian requested changes
간단히 살펴보았습니다.

2021-01-20 06:39 UTC, seokho-son commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                  첫 번째 디플로이먼트로, NGINX를 사용해 모든 요청을 에코하는 도커 컨테이너에 패키지된 hello-node 애플리케이션을 사용해보자. (아직 hello-node 애플리케이션을 작성하고 컨테이너를 활용해서 배포해보지 않았다면, <a href="/docs/tutorials/hello-minikube/">Hello Minik
@yoonian 
에코 (echo) 가 살짝 기술적인 의미에 해당할 수 있을 것 같아서, `에코` 그대로 유지하거나 한영병기하는 정도로 조정하면 어떨까요? 오리혀 echo 를 잘 사용하는 개발자 및 사용자들에게는 `메아리친다` 라는 개념이 더 어려울 수 있을 것 같기도 하고요..^^
https://ko.dict.naver.com/#/entry/koko/35dd14494f9341ad826e83c90230c1a3

2021-01-24 23:56 UTC, pjhwa commented on content/ko/docs/tasks/access-application-cluster/connecting-frontend-backend.md
> +파드에 트래픽을 보내는는 것을 볼 수 있다.
반영하겠습니다.

2021-01-24 23:57 UTC, pjhwa commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                  첫 번째 디플로이먼트로, NGINX를 사용해 모든 요청을 에코하는 도커 컨테이너에 패키지된 hello-node 애플리케이션을 사용해보자. (아직 hello-node 애플리케이션을 작성하고 컨테이너를 활용해서 배포해보지 않았다면, <a href="/docs/tutorials/hello-minikube/">Hello Minik
저도 같은 생각입니다. echo 는 유지하며 한영병기를 추가하는 것이 좋을 것 같습니다.

2021-01-24 23:57 UTC, pjhwa commented on content/ko/docs/setup/production-environment/container-runtimes.md
> +변경된 `conmon_cgroup` 에 유의한다. 일반적으로 kubelet(일반적으로 kubeadm을 통해 수행됨) 과
반영하겠습니다.

2021-01-25 00:00 UTC, pjhwa reviewed
@yoonian 검토해주셔서 감사합니다.
의견주신 내용은 일부 반영하여 업데이트하였습니다. 확인 부탁드립니다.

2021-01-26 01:12 UTC, yoonian commented
@pjhwa 디플로이 문제가 있네요? 확인 좀 부탁드려요~

2021-01-26 01:29 UTC, pjhwa commented
/retest

2021-01-26 01:48 UTC, pjhwa commented
> @pjhwa @seokho-son 빌드 문제가 있네요? 확인 부탁드려요~

"fatal error: concurrent map read and map write" 에러와 관련한 이슈가 있나봐요. 몇 번 재빌드하면 성공할때가 있다고 하니 다시 해보겠습니다. 
https://github.com/gohugoio/hugo/issues/7293

2021-01-27 05:39 UTC, seokho-son commented
@yoonian 빌드 테스트는 완료된 것 같습니다 ^^ 리뷰 완료해주시면, 제가 승인 절차에 들어가겠습니다.. ^^

2021-01-27 07:14 UTC, yoonian commented
@seokho-son 좋습니다~ 아까 올린다는 것이 깜박했네요.
/lgtm

2021-01-27 07:48 UTC, seokho-son reviewed
@pjhwa 아주 사소한 오타가 있어서 알려드립니다. 나머지는 완벽해 보이네요 ! ^^
혹시 수정 가능하시면 반영 부탁드리며, 필요에 따라선 작업 브랜치 머지시 살짝 처리해도 좋을 것 같습니다.. ^^

2021-01-27 07:48 UTC, seokho-son commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                  첫 번째 디플로이먼트로, NGINX를 사용해 모든 요청을 에코(echo)하는 도커 컨테이너로 패키지한 hello-node 애플리케이션을 사용해보자. (아직 hello-node 애플리케이션을 작성하고 컨테이너를 활용해서 배포해보지 않았다면, <a href="/docs/tutorials/hello-minikube/">Hello
```suggestion
                  첫 번째 디플로이먼트로, NGINX를 사용해 모든 요청을 에코(echo)하는 도커 컨테이너로 패키지한 hello-node 애플리케이션을 사용해보자. (아직 hello-node 애플리케이션을 작성하고 컨테이너를 활용해서 배포해보지 않았다면, <a href="/docs/tutorials/hello-minikube/">Hello Minikube 튜토리얼</a>의 지시를 따른다.)
```

2021-01-27 08:44 UTC, pjhwa commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                  첫 번째 디플로이먼트로, NGINX를 사용해 모든 요청을 에코(echo)하는 도커 컨테이너로 패키지한 hello-node 애플리케이션을 사용해보자. (아직 hello-node 애플리케이션을 작성하고 컨테이너를 활용해서 배포해보지 않았다면, <a href="/docs/tutorials/hello-minikube/">Hello
넵. 반영하겠습니다!

2021-01-28 04:30 UTC, seokho-son commented
Thank you !
/lgtm
/approve

2021-01-28 04:33 UTC, merged