[zh] Translate kubelet-tls-bootstrapping
kubernetes/website pull request #26170
Opened 2021-01-20 14:17 UTC by tengqm

This page, to my surprise, was not localized.

2021-01-21 12:38 UTC, tanjunchen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +This document describes the process of node initialization, how to set up TLS client certificate bootstrapping for
comment en

2021-01-29 08:59 UTC, howieyuen requested changes
it feels like reading a new post when review your PR, because no gap here~
And I really want type lgtm without reviewing...

2021-01-29 08:59 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +14. 可选地，如果配置了，kubelet 在证书接近于过期时自动请求更新证书
14. 可选：如果配置了，kubelet 在证书快要过期时自动请求更新证书

2021-01-29 08:59 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +启动引导令牌从 Kubernetes 1.12 开始是一种 Beta 功能特性。
启动引导令牌从 Kubernetes 1.12 开始是一种 __Beta__ 功能特性。

2021-01-29 08:59 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +现在启动引导节点被身份认证为 `system:bootstrapping` 组的成员，它需要被授权
现在启动引导节点被身份认证为 `system:bootstrapping` 组的成员，它需要 _被授权_

2021-01-29 08:59 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +为了避免与其它批复组件发生冲突，内置的批复组件不会显式地决绝任何 CSRs。
为了避免与其它批复组件发生冲突，内置的批复组件不会显式地决绝任何 CSR。

2021-01-29 08:59 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +3. 仅包含隶属于请求节点的 IP 和 DNS 的 `subjectAltNames`，没有 URI 和 email
3. 仅包含隶属于请求节点的 IP 和 DNS 的 `subjectAltNames`，没有 URI 和 Email

2021-01-29 09:23 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +2. kubelet 看到自己没有对应的 `kubeconfig` 文件
用斜体加前后空格的方式表示这个强调很不舒服。
如果一定要跟英文的一模一样，好吧。

2021-01-29 09:24 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +14. 可选地，如果配置了，kubelet 在证书接近于过期时自动请求更新证书
这种不是正常的中文表达形式。现在的翻译表达是将 ”可选地，”作为条件状语从句，用冒号之后就说不清了。

2021-01-29 09:25 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +启动引导令牌从 Kubernetes 1.12 开始是一种 Beta 功能特性。
这种加粗的强调似乎也没什么太大必要。

2021-01-29 09:27 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +现在启动引导节点被身份认证为 `system:bootstrapping` 组的成员，它需要被授权
同前，受 markdown 解析器限制，加星号来渲染斜体的时候，必须前后加空格，因此译文中也会出现空格且斜体的情况。看起来太奇怪了。英文里面的这个斜体加的也是莫名其妙。

2021-01-29 09:28 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +为了避免与其它批复组件发生冲突，内置的批复组件不会显式地决绝任何 CSRs。
懂你意思，“拒绝”

2021-01-29 09:28 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +3. 仅包含隶属于请求节点的 IP 和 DNS 的 `subjectAltNames`，没有 URI 和 email
OK

2021-01-29 09:29 UTC, tengqm commented
> it feels like reading a new post when review your PR, because no gap here~

Yes. This page was NOT translated before.

2021-01-30 01:38 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +为了避免与其它批复组件发生冲突，内置的批复组件不会显式地决绝任何 CSRs。
oops,my typo~

2021-01-30 01:39 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +2. kubelet 看到自己没有对应的 `kubeconfig` 文件
之前我也有类似的疑惑，是不是英文得斜体应该对应中文的加粗，这样是不是更合适一点

2021-01-30 05:03 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet-tls-bootstrapping.md
> +2. kubelet 看到自己没有对应的 `kubeconfig` 文件
我甚至不觉得这里需要任何强调，斜体或者加粗都没有必要。

2021-02-01 03:33 UTC, howieyuen commented
/lgtm

2021-02-06 02:05 UTC, tanjunchen reviewed
/approve
thanks

2021-02-06 02:07 UTC, merged