[zh] Resync kubelet reference
kubernetes/website pull request #26179
Opened 2021-01-21 05:22 UTC by tengqm

2021-01-21 12:25 UTC, tanjunchen reviewed
/approve

2021-01-22 02:03 UTC, howieyuen requested changes

2021-01-22 02:03 UTC, howieyuen commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +<code>nodefs.inodesFree<5%`。
need \</code\>

2021-01-22 02:53 UTC, chenrui333 commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +<code>nodefs.inodesFree<5%`。
:+1:

2021-01-22 02:58 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/kubelet.md
> +<code>nodefs.inodesFree<5%`。
good spot.

2021-01-22 03:12 UTC, howieyuen commented
/lgtm

2021-01-22 03:13 UTC, merged