Update README.md
kubernetes/website pull request #26207
Opened 2021-01-23 02:19 UTC by jailton

Add instruction to access API reference pages URL locally

2021-01-23 08:09 UTC, Arhell reviewed
/language en

2021-01-25 21:30 UTC, bradtopol commented
This looks like one for @jimangel.
/assign @jimangel

2021-02-01 18:45 UTC, celestehorgan requested changes

2021-02-01 18:45 UTC, celestehorgan commented on README.md
> +Open up your browser to http://localhost:1313/docs/reference/kubernetes-api/ to view the API reference pages.
```suggestion
In a web browser, go to http://localhost:1313/docs/reference/kubernetes-api/ to view the API reference.
```

2021-02-04 19:27 UTC, celestehorgan commented
/lgtm

2021-02-06 14:45 UTC, irvifa reviewed
/approve

2021-02-06 14:47 UTC, merged