Update administer-cluster out-of-resource.md and namespaces.md
kubernetes/website pull request #26213
Opened 2021-01-23 14:48 UTC by ydFu

* sync with english version in administer-cluster out-of-resource.md and namespcaes.md

Signed-off-by: ydFu <ader.ydfu@gmail.com>

2021-01-25 02:02 UTC, howieyuen requested changes

2021-01-25 02:02 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/namespaces.md
> +本页展示如何查看、使用和删除 {{< glossary_tooltip text="名字空间" term_id="namespace" >}} 。
此处显示的是“名字空间”，都是中文，所以这里不需要额外添加空格

2021-01-25 02:02 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/namespaces.md
>  * 你已拥有一个[配置好的 Kubernetes 集群](/zh/docs/setup/).
把这里的英文句号改成中文

2021-01-25 03:04 UTC, ydFu reviewed
thank

2021-01-25 03:08 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/namespaces.md
> +本页展示如何查看、使用和删除 {{< glossary_tooltip text="名字空间" term_id="namespace" >}} 。
thank you for suggesting me.

2021-01-25 03:08 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/namespaces.md
>  * 你已拥有一个[配置好的 Kubernetes 集群](/zh/docs/setup/).
thank you for suggesting me.

2021-01-25 03:09 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/namespaces.md
> +本页展示如何查看、使用和删除 {{< glossary_tooltip text="名字空间" term_id="namespace" >}} 。
thank you for suggesting me.

2021-01-25 04:55 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/namespaces.md
> + {{< glossary_tooltip text="Deployments" term_id="deployment" >}} 有基本理解。
29 行应按 28 行缩进两个空格

2021-01-25 04:56 UTC, tengqm commented
Umbrella issue for tasks pages is #26178

2021-01-27 01:27 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/namespaces.md
> + {{< glossary_tooltip text="Deployments" term_id="deployment" >}} 有基本理解。
thank you for suggesting me.

2021-01-27 02:52 UTC, tengqm commented
/lgtm
/approve

2021-01-27 02:53 UTC, merged