[zh] Sync web page for HA
kubernetes/website pull request #26332
Opened 2021-02-01 03:07 UTC by chenxuc

This is part of work in umbrella issue:
Umbrella issue: pages out of sync in tasks section #26178

HA (L):
 content/zh/docs/tasks/administer-cluster/highly-available-master.md

2021-02-01 03:32 UTC, howieyuen requested changes

2021-02-01 03:32 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/highly-available-master.md
> +使用 API 服务器标识功能需要启用 [特性门控](/zh/docs/reference/command-line-tools-reference/feature-gates/)，
“启用”后面多个空格

2021-02-01 03:32 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/highly-available-master.md
> +你可以在启动 {{< glossary_tooltip text="API 服务器" term_id="kube-apiserver" >}} 的时候
“的时候”前面多个空格

2021-02-01 03:32 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/highly-available-master.md
> +每个 kube-apiserver 每过 `IdentityLeaseRenewIntervalSeconds` （默认是 10 秒）就会刷新它的 `Lease` 对象。
中文括号前面的英文可以不用添加空格
下同

2021-02-01 03:32 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/highly-available-master.md
> +启用该功能是使用 HA API 服务器协调相关功能 （例如，`StorageVersionAPI` 特性门控） 的前提条件。
中文括号前面空格多余

2021-02-01 04:36 UTC, chenxuc commented
@howieyuen Thanks for the review. I've updated the commit.

2021-02-01 05:11 UTC, tengqm commented
/approve

2021-02-01 09:27 UTC, howieyuen commented
/lgtm

2021-02-01 09:27 UTC, merged

2021-02-02 01:20 UTC, chenxuc commented
@howieyuen 袁昊你好，
感谢你最近review我的几个PR~目前我有十多个k8s PR已经merged了。我准备申请k8s的member，目前已经找到了一位owner来sponsor。想请问你是否可以作为我的另一位sponsor呢？如果可以的话，我就把你的名字放进申请报告的sponsor里面。非常感谢！