clean up use of word: easy
kubernetes/website pull request #26352
Opened 2021-02-01 20:23 UTC by kbhawkey

- Create replacement text to replace the word "easy" throughout content
- Other minor cleanup
- Related to https://github.com/kubernetes/website/issues/17070

2021-02-03 18:34 UTC, celestehorgan requested changes
A few very minor edits.

Thank you so much for taking on this work, @kbhawkey <3

2021-02-03 18:34 UTC, celestehorgan commented on content/en/docs/tutorials/stateless-application/guestbook.md
> +Scaling up or down is effortless because your servers are defined as a Service that uses a Deployment controller.
```suggestion
You can scale up or down as needed because your servers are defined as a Service that uses a Deployment controller.
```

2021-02-03 18:34 UTC, celestehorgan commented on content/en/docs/tutorials/kubernetes-basics/_index.html
> +        <p>With modern web services, users expect applications to be available 24/7, and developers expect to deploy new versions of those applications several times a day. Containerization helps pac
```suggestion
        <p>With modern web services, users expect applications to be available 24/7, and developers expect to deploy new versions of those applications several times a day. Containerization helps package software to serve these goals, enabling applications to be released and updated without downtime. Kubernetes helps you make sure those containerized applications run where and when you want, and helps them find the resources and tools they need to work. Kubernetes is a production-ready, open source platform designed with Google's accumulated experience in container orchestration, combined with best-of-breed ideas from the community.</p>
```

2021-02-03 18:34 UTC, celestehorgan commented on content/en/docs/tasks/administer-cluster/limit-storage-consumption.md
> +This example demonstrates an straightforward way to limit the amount of storage consumed in a namespace.
```suggestion
This example demonstrates how to limit the amount of storage consumed in a namespace.
```

2021-02-03 18:34 UTC, celestehorgan commented on content/en/docs/reference/tools.md
> +run a single-node Kubernetes cluster locally on your workstation for
```suggestion
[`minikube`](https://minikube.sigs.k8s.io/docs/) is a tool that
runs a single-node Kubernetes cluster locally on your workstation for
```

2021-02-03 18:34 UTC, celestehorgan commented on content/en/docs/reference/kubernetes-api/extend-resources/validating-webhook-configuration-v1.md
> +    Please note that using `localhost` or `127.0.0.1` as a `host` is risky unless you take great care to run this webhook on all hosts which run an apiserver which might need to make calls to this we
👍 Great rewording @kbhawkey

2021-02-04 18:18 UTC, celestehorgan commented
/lgtm

2021-02-04 18:46 UTC, sftim reviewed
This is a really valuable improvement IMO.
/approve

2021-02-04 18:47 UTC, sftim commented
/kind cleanup

2021-02-04 18:48 UTC, merged