[zh] translate Migrating from dockershim
kubernetes/website pull request #26369
Opened 2021-02-03 07:46 UTC by zhiguo-lu

translate docs/tasks/administer-cluster/migrating-from-dockershim/_index.md 

close #26364

2021-02-03 09:09 UTC, howieyuen requested changes

2021-02-03 09:09 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +[弃用 dockershim](/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
把英文链接改成中文链接：/zh/xxx
下同

2021-02-03 10:00 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +[弃用 dockershim](/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
```suggestion
[弃用 dockershim](/zh/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
```

2021-02-03 10:29 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +[弃用 dockershim](/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
You can refer to this [contribute localization](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E4%B8%AD%E6%96%87%E9%93%BE%E6%8E%A5%E7%9B%AE%E6%A0%87).

2021-02-04 02:08 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +各类疑问随之而来：这对各类工作负载和 Kubernetes 部署集群会产生什么影响。
呵呵，手误，多翻译了一个集群，谢谢

2021-02-04 02:19 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +[弃用 dockershim](/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
提问：两个 blog 还没翻译，要加/zh吗
改完之后的地址是：https://kubernetes.io/zh/blog/2020/12/02/dockershim-faq/
手工打出来这个地址，浏览器访问，报404.

2021-02-04 02:22 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +[弃用 dockershim](/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
两个blog没翻译。
给两个blog加issue；还是这篇暂时不加/zh，等往后blog有了之后再把/zh加上？

2021-02-04 07:46 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +[弃用 dockershim](/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
我记得是会自动跳转的，你可以在本地试一下 `make serve`，确认可自适应跳转

2021-02-04 09:07 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/_index.md
> +[弃用 dockershim](/blog/2020/12/08/kubernetes-1-20-release-announcement/#dockershim-deprecation)，
本地没跳转。
这样吧，我先加上/zh，如果有问题，我再加issue来改。

2021-02-05 02:51 UTC, howieyuen commented
/lgtm

2021-02-05 05:06 UTC, tengqm commented
/lgtm
/approve

2021-02-05 05:08 UTC, merged