[zh] translate "Migrating telemetry and security agents from dockershim"
kubernetes/website pull request #26409
Opened 2021-02-07 03:33 UTC by zhiguo-lu

translate /docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md

close #26366

2021-02-08 09:04 UTC, howieyuen requested changes
This is one of the best translations I have ever read. 
Thanks for the contribution, I'd like to see more masterpieces from you~

2021-02-08 09:04 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +### 识别依赖于 Docker 的 DaemonSets {#identify-docker-dependency}
DaemonSet
key words prefer singular format

2021-02-08 09:04 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +下面是一个示例 shell 脚本，用于查找包含直连到 Docker 套接字的挂载点的 Pod。
下面是一个 shell 脚本示例

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +从博文[弃用 Dockershim 常见问题](/zh/blog/2020/12/02/dockershim-faq/)，
```suggestion
在博文[弃用 Dockershim 常见问题](/zh/blog/2020/12/02/dockershim-faq/)中，
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +但是，仍然有大量的遥测和安全代理，依赖 docker 来收集容器元数据、日志和指标。
```suggestion
但是，仍然有大量的遥测和安全代理依赖 Docker 来收集容器元数据、日志和指标。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +本文汇总了：一些信息和链接，信息用于阐述如何探查这些依赖，链接用于解释如何迁移这些代理去使用通用的工具或其他容器运行。
```suggestion
本文汇总了一些信息和链接：信息用于阐述如何探查这些依赖，链接用于解释如何迁移这些代理去
使用通用的工具或其他容器运行时。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +时间流逝，更多的运行时被创建出来，管理容器。
```suggestion
后来，人们开发了更多的运行时来管理容器。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +一些代理固定的绑定到了 Docker 工具。此类代理可以这样运行命令，比如用
```suggestion
一些代理与 Docker 工具有着紧密的绑定。此类代理可以用
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +来列出容器和进程，用
```suggestion
这类命令来列出容器和进程，用
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +如果 Pod 想调用运行在节点上的 `dockerd`， Pod 必须具备以下两个条件之一：
```suggestion
如果某 Pod 想调用运行在节点上的 `dockerd`，该 Pod 必须满足以下两个条件之一：
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +- 直接挂载 Docker 守护进程特权套接字的特定路径，也可以作为一个卷挂载。
```suggestion
- 直接以卷的形式挂载 Docker 守护进程特权套接字的特定路径。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +这意味着 Pod 的规格中需要定义挂载了文件 `/var/run/docker.sock` 的 `hostPath` 卷。
```suggestion
这意味着 Pod 的规约中需要包含 `hostPath` 卷以挂载 `/var/run/docker.sock`。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +下面是一个示例 shell 脚本，用于查找包含直连到 Docker 套接字的挂载点的 Pod。
```suggestion
下面是一个示例 shell 脚本，用于查找包含直接映射 Docker 套接字的挂载点的 Pod。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +你也可以删掉代码片段：grep `/var/run/docker.sock`，查看其它挂载信息。
```suggestion
你也可以删掉 grep `/var/run/docker.sock` 这一代码以查看其它挂载信息。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +对于 Pod 来说，有替代的方式能访问宿主机上的 Docker。
```suggestion
对于 Pod 来说，访问宿主机上的 Docker 还有其他方式。
```

2021-02-08 10:54 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +例如，可以挂载 `/var/run` 的父目录，来代替完整的路径
```suggestion
例如，可以挂载 `/var/run` 的父目录而非其完整路径
```

2021-02-09 12:16 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
got it

2021-02-09 12:17 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +### 识别依赖于 Docker 的 DaemonSets {#identify-docker-dependency}
done

2021-02-09 12:22 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +下面是一个示例 shell 脚本，用于查找包含直连到 Docker 套接字的挂载点的 Pod。
你提的对，这样读着更顺了。
不过我又想了想，“脚本”应该是主语，你看这样该可否：下面是一个 shell 示例脚本。

2021-02-09 12:27 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +时间流逝，更多的运行时被创建出来，管理容器。
这个“人们”加的真好。

2021-02-09 12:31 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +一些代理固定的绑定到了 Docker 工具。此类代理可以这样运行命令，比如用
我又优化了一下，你看行不行：一些代理和 Docker 工具紧密绑定。

2021-02-09 12:43 UTC, zhiguo-lu commented on content/zh/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +对于 Pod 来说，有替代的方式能访问宿主机上的 Docker。
厉害，通顺多了

2021-02-09 12:56 UTC, zhiguo-lu commented
> This is one of the best translations I have ever read.
> Thanks for the contribution, I'd like to see more masterpieces from you~

不行不行，我还是个新手。
从去年9月份才开始试着翻译点文档，都是比着你们过去的翻译，一点一点学的。
往后只要有时间，我就翻译几篇，希望对大家有用。

2021-02-10 08:20 UTC, tengqm commented
/approve

2021-02-11 08:17 UTC, tengqm commented
/lgtm

2021-02-11 08:18 UTC, merged