translate troubleshooting-kubeadm-1.18-ja
kubernetes/website pull request #26558
Opened 2021-02-15 17:24 UTC by AnguillaJaponica

close https://github.com/kubernetes/website/issues/26515

2021-02-16 01:26 UTC, makocchi-git commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +どのプログラムでもそうですが、kubeadmのインストールや実行でエラーが発生することがあります。このページでは、一般的な失敗例をいくつか挙げ、問題を理解して解決するための手順を示しています。
nit
```suggestion
- どのプログラムでもそうですが、kubeadmのインストールや実行でエラーが発生することがあります。
- このページでは、一般的な失敗例をいくつか挙げ、問題を理解して解決するための手順を示しています。
```

2021-02-16 02:00 UTC, makocchi-git commented
/lgtm

2021-02-17 08:19 UTC, inductor requested changes
下記リンクに翻訳の方針があるので、一度目を通してみてください 🙏 

https://kubernetes.io/ja/docs/contribute/localization/#翻訳スタイルガイド

2021-02-17 08:19 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +dockerのログを調べるのも有効である場合があります:
```suggestion
dockerのログを調べるのも有効な場合があります:
```

2021-02-17 08:19 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +`kubeadm init` の直後には、これらの状態ではポッドは存在しないはずです。
```suggestion
`kubeadm init` の直後には、これらの状態ではPodは存在しないはずです。
```

2021-02-17 08:19 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにポッドがある場合は、kubeadmのリポジトリにイシューを立ててください。ネットワークソリューションをデプロイするまでは `coredns` (または `kube-dns`)は `Pending`状態でなければなりません。
```suggestion
- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにイシューを立ててください。ネットワークソリューションをデプロイするまでは `coredns` (または `kube-dns`)は `Pending`状態でなければなりません。
```

2021-02-17 08:19 UTC, inductor commented
/hold

2021-02-17 09:14 UTC, AnguillaJaponica commented
ありがとうございます！修正します。

2021-02-17 10:45 UTC, AnguillaJaponica commented
- 「ポッド」を'Pod'に直しました。
-  「〜になります」「〜となります」を「〜です」に直しました。
- 余分な半角スペースを整理しました。
- 「〜ので」「〜から」「〜だから」を「〜のため 」「〜ため」に直しました。

2021-02-17 11:41 UTC, inductor requested changes

2021-02-17 11:41 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +ネットワークプロバイダが portmap CNI プラグインをサポートしていない場合は、[services](/ja/docs/concepts/services-networking/service/#nodeport)を使用するか、`HostNetwork=true`を使用してください。
```suggestion
ネットワークプロバイダが portmap CNI プラグインをサポートしていない場合は、[NodePortサービス](/ja/docs/concepts/services-networking/service/#nodeport)を使用するか、`HostNetwork=true`を使用してください。
```

2021-02-17 11:41 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +  sed ‘s/allowPrivilegeEscalation: false/allowPrivilegeEscalation: true/g’ | \
ここは変える必要ないような？

2021-02-17 11:41 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +  sed ‘s/allowPrivilegeEscalation: false/allowPrivilegeEscalation: true/g’ | \
ほかにもいくつかありそうでした

2021-02-17 11:50 UTC, AnguillaJaponica commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +ネットワークプロバイダが portmap CNI プラグインをサポートしていない場合は、[services](/ja/docs/concepts/services-networking/service/#nodeport)を使用するか、`HostNetwork=true`を使用してください。
修正しました

2021-02-17 11:51 UTC, AnguillaJaponica commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +  sed ‘s/allowPrivilegeEscalation: false/allowPrivilegeEscalation: true/g’ | \
自分で翻訳チェックをかけていた時に入ったものでした、、他にもあったのでまとめて修正しました。

2021-02-17 12:41 UTC, inductor requested changes

2021-02-17 12:41 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +  `kubelet`をリスタートしてください:
ここだけ再起動じゃなくてリスタートになってる？

2021-02-17 12:41 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +  これは、ホストの最初のインターフェイスをデフォルトにしているフランネルの問題につながるかもしれません。これは、すべてのホストが同じパブリックIPアドレスを持っていると考えます。これを防ぐには、2番目のインターフェイスが選択されるように `--iface eth1`フラグをflannelに渡してください。
フランネル→Flannel?

2021-02-18 01:32 UTC, AnguillaJaponica commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +  `kubelet`をリスタートしてください:
再起動に直しました

2021-02-18 01:33 UTC, AnguillaJaponica commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +  これは、ホストの最初のインターフェイスをデフォルトにしているフランネルの問題につながるかもしれません。これは、すべてのホストが同じパブリックIPアドレスを持っていると考えます。これを防ぐには、2番目のインターフェイスが選択されるように `--iface eth1`フラグをflannelに渡してください。
カタカナで残っていたものを修正しました。

2021-02-25 14:53 UTC, inductor commented
/unhold

2021-02-25 15:12 UTC, makocchi-git commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにIssueを立ててください。network solutionをデプロイするまでは`coredns`(または`kube-dns`)は`Pending`状態でなければなりません。
network solution は訳すほうがいいのではないかと思います (おそらく CNI のことを指しているんだと思うんですけども)
何かいい日本語があればいいんですが・・・ネットワークの解決方法とか、ちょっと意訳ですがネットワーク設定とか、いっそカタカナでネットワークソリューションにしちゃうとか

2021-02-25 15:37 UTC, AnguillaJaponica commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにIssueを立ててください。network solutionをデプロイするまでは`coredns`(または`kube-dns`)は`Pending`状態でなければなりません。
> 何かいい日本語があればいいんですが・・・ネットワークの解決方法とか、ちょっと意訳ですがネットワーク設定とか、いっそカタカナでネットワークソリューションにしちゃうとか

ありがとうございます。今のところ「ネットワークの解決方法」か「ネットワークソリューション」のどちらかなと思ってます(朝起きたらどちらかに寄せて修正出します)

2021-02-25 17:08 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにIssueを立ててください。network solutionをデプロイするまでは`coredns`(または`kube-dns`)は`Pending`状態でなければなりません。
今のところはネットワークソリューションのほうがよさそうです。解決方法って訳すと文章に起こしたときに、意味がちょっとわからなくなりそうなので

2021-02-26 01:29 UTC, AnguillaJaponica commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにIssueを立ててください。network solutionをデプロイするまでは`coredns`(または`kube-dns`)は`Pending`状態でなければなりません。
ネットワークソリューションのほうで統一しました。

2021-02-26 02:41 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +v1.18では、同名のノードが既に存在する場合にクラスタ内のノードに参加しないようにする機能を追加しました。これには、ブートストラップトークンユーザがノードオブジェクトをGETできるようにRBACを追加する必要がありました。
オブジェクトの場合は英語っていうルールがあるので (ref. https://kubernetes.io/ja/docs/contribute/localization/ )
Nodeオブジェクト、になる気がしますが、どうすかね @makocchi-git

2021-02-26 08:23 UTC, shu-mutou commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにIssueを立ててください。network solutionをデプロイするまでは`coredns`(または`kube-dns`)は`Pending`状態でなければなりません。
実態は[「アドオン」](https://kubernetes.io/docs/concepts/cluster-administration/addons/)で、同じページに「ネットワークアドオン」という記述もあるので、そちらに寄せても良いかもしれません。
あるいは、「ネットワークアドオン」と記述されている部分も「ネットワークソリューション」に統一したいですね。（本当は英語の原文から統一したいところではあります）
@inductor さん、@makocchi-git さん、いかがでしょうか

2021-02-26 08:30 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにIssueを立ててください。network solutionをデプロイするまでは`coredns`(または`kube-dns`)は`Pending`状態でなければなりません。
@shu-mutou そういう意味だと、ここのIssueだけだとスコープが変わってきちゃうんで別Issueで管理したいやつですね

2021-02-26 08:56 UTC, shu-mutou commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +- `kubeadm init`の _直後_ にこれらの状態のいずれかにPodがある場合は、kubeadmのリポジトリにIssueを立ててください。network solutionをデプロイするまでは`coredns`(または`kube-dns`)は`Pending`状態でなければなりません。
Issue を作ってみました #26722

2021-03-01 11:59 UTC, makocchi-git commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +v1.18では、同名のノードが既に存在する場合にクラスタ内のノードに参加しないようにする機能を追加しました。これには、ブートストラップトークンユーザがノードオブジェクトをGETできるようにRBACを追加する必要がありました。
んー確かにここは `Nodeオブジェクト` にしておきましょうか

2021-03-01 13:14 UTC, AnguillaJaponica commented on content/ja/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm.md
> +v1.18では、同名のノードが既に存在する場合にクラスタ内のノードに参加しないようにする機能を追加しました。これには、ブートストラップトークンユーザがノードオブジェクトをGETできるようにRBACを追加する必要がありました。
ここをNodeオブジェクトに修正しました。

2021-03-02 04:18 UTC, makocchi-git commented
/lgtm

2021-03-02 04:35 UTC, inductor commented
/approve

2021-03-02 04:37 UTC, merged