ja: Make docs/setup/production-environment/turnkey/gce.md follow v1.18 of the original text
kubernetes/website pull request #26557
Opened 2021-02-15 16:58 UTC by butterv

I updated the `content/ja/docs/setup/production-environment/turnkey/gce.md` to follow v1.18 of the original (English) text.

The following link is the differences between v1.17 and v1.18:
https://gist.github.com/inductor/c5961124a77fff385810347dba45a651

This PR fixes this issue:
#26519

2021-02-15 17:15 UTC, butterv commented
I signed it

2021-02-17 08:16 UTC, nasa9084 requested changes

2021-02-17 08:16 UTC, nasa9084 commented on content/ja/docs/setup/production-environment/turnkey/gce.md
> +downloaded by the get.k8s.io install script. See [Installing kubectl](/docs/tasks/tools/install-kubectl/)
```suggestion
The [kubectl](/ja/docs/reference/kubectl/kubectl/) tool controls the Kubernetes cluster
```

翻訳済みページのようなので、ついでに修正お願いします！

2021-02-17 08:16 UTC, nasa9084 commented on content/ja/docs/setup/production-environment/turnkey/gce.md
> +Similarly, you can take a look at the set of [pods](/docs/concepts/workloads/pods/) that were created during cluster startup.
```suggestion
Similarly, you can take a look at the set of [pods](/ja/docs/concepts/workloads/pods/) that were created during cluster startup.
```

翻訳済みページのようなので、ついでに修正お願いします！

2021-02-17 08:16 UTC, nasa9084 commented on content/ja/docs/setup/production-environment/turnkey/gce.md
> +Then, see [a simple nginx example](/docs/tasks/run-application/run-stateless-application-deployment/) to try out your new cluster.
```suggestion
Then, see [a simple nginx example](/ja/docs/tasks/run-application/run-stateless-application-deployment/) to try out your new cluster.
```

翻訳済みページのようなので、ついでに修正お願いします！

2021-02-25 15:43 UTC, nasa9084 commented
/approve

2021-02-25 15:44 UTC, nasa9084 commented
/assign
/cc @kakts @makocchi-git @bells17

2021-02-25 16:55 UTC, inductor commented
/lgtm

2021-02-25 16:57 UTC, merged