Synchronize Polish localization with upstream
kubernetes/website pull request #26567
Opened 2021-02-16 08:00 UTC by mfilocha

Polish translation synchronized up to fa83273ca52656c3d6ad5acb67db05a82d2d3bbc (2020-12-13).

2021-02-16 12:17 UTC, kpucynski requested changes

2021-02-16 12:17 UTC, kpucynski commented on content/pl/docs/concepts/overview/kubernetes-api.md
> +API Kubernetes pozwala na sprawdzanie i zmianę stanu obiektów
```suggestion
API Kubernetesa pozwala na sprawdzanie i zmianę stanu obiektów
```

2021-02-16 12:17 UTC, kpucynski commented on content/pl/docs/concepts/overview/kubernetes-api.md
> +## Trwałość
```suggestion
## Utrzymanie stanu
```
Stałość? Niezmienność? Chodzi będzie bardziej jako utrzymanie stanu - `persistance` niż `durability`

2021-02-17 09:15 UTC, nvtkaszpir requested changes

2021-02-17 09:15 UTC, nvtkaszpir commented on content/pl/docs/concepts/overview/kubernetes-api.md
> +## Trwałość
czy `Zachowanie stanu`?

2021-02-17 09:15 UTC, nvtkaszpir commented on content/pl/docs/concepts/overview/kubernetes-api.md
> +o ile ma zastosowanie) oraz nazwę. Serwer API może przeprowadza konwersję między
```suggestion
o ile ma zastosowanie) oraz nazwę. Serwer API może przeprowadzać konwersję między
```

2021-02-17 09:15 UTC, nvtkaszpir commented on content/pl/docs/concepts/overview/kubernetes-api.md
> +reprezentują w rzeczywistości ten sam zasób. Serwer API może udostępniać ten same dane
```suggestion
reprezentują w rzeczywistości ten sam zasób. Serwer API może udostępniać te same dane
```

2021-02-17 09:15 UTC, nvtkaszpir commented on content/pl/docs/concepts/overview/kubernetes-api.md
> +i ich zachowania i pozwala na kontrolowany dostęp do tych API, które są w fazie wycofywania
```suggestion
i ich zachowania  oraz pozwala na kontrolowany dostęp do tych API, które są w fazie wycofywania
```

2021-02-19 16:39 UTC, kpucynski approved these changes
/lgtm

2021-02-19 21:56 UTC, nvtkaszpir approved these changes
/approve
/lgtm

nice

2021-02-19 21:57 UTC, merged