Update `ja/create-cluster-kubeadm.md`
kubernetes/website pull request #26571
Opened 2021-02-16 10:27 UTC by RyuSA

resolve this issue. https://github.com/kubernetes/website/issues/26508

2021-02-16 11:16 UTC, RyuSA commented
/assign @nasa9084

2021-02-16 14:11 UTC, kakts commented
ご対応ありがとうございます。
/lgtm

2021-02-17 00:56 UTC, inductor requested changes

2021-02-17 00:56 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
> +`--control-plane-endpoint`はIPアドレスとIPアドレスへマッピングできるDNS名を使用できます。利用可能なソリューションをそうしたマッピングの観点から評価するには、ネットワーク管理者に相談してください。
IPアドレス２回連続で登場するの気になるけどどうしようかな・・・

2021-02-17 00:56 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
> +[Kubernetesのネットワークモデル](/ja/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model)を実装したアドオンの一覧も確認してください。
このリンクがタグまで含めて正しく動作しているか、手元で動作チェックお願いします。

必要に応じて該当リンク先のページも変更をお願いします 🙏

2021-02-17 13:12 UTC, nasa9084 commented on content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
> +`--control-plane-endpoint`はIPアドレスとIPアドレスへマッピングできるDNS名を使用できます。利用可能なソリューションをそうしたマッピングの観点から評価するには、ネットワーク管理者に相談してください。
```suggestion
`--control-plane-endpoint`はIPアドレスと、IPアドレスへマッピングできるDNS名を使用できます。利用可能なソリューションをそうしたマッピングの観点から評価するには、ネットワーク管理者に相談してください。
```

2回連続は諦めて、読点でクッションを入れることで多少違和感が拭えるかな、どうですかね

2021-02-17 14:19 UTC, RyuSA commented on content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
> +[Kubernetesのネットワークモデル](/ja/docs/concepts/cluster-administration/networking/#how-to-implement-the-kubernetes-networking-model)を実装したアドオンの一覧も確認してください。
`ja/docs/concepts/cluster-administration/networking.md`のURLフラグメントを修正する対応をしました 🎉 5d5b49c8a8c7f478c6e9a5e29c61b42580164525

2021-02-18 13:25 UTC, RyuSA commented on content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
> +`--control-plane-endpoint`はIPアドレスとIPアドレスへマッピングできるDNS名を使用できます。利用可能なソリューションをそうしたマッピングの観点から評価するには、ネットワーク管理者に相談してください。
@nasa9084 わかりやすくなるので良いと思います。
@inductor どうでしょうか？

2021-02-18 13:56 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm.md
> +`--control-plane-endpoint`はIPアドレスとIPアドレスへマッピングできるDNS名を使用できます。利用可能なソリューションをそうしたマッピングの観点から評価するには、ネットワーク管理者に相談してください。
@RyuSA nasaさんもメンテナなので従ってもらって大丈夫です！

2021-02-23 02:43 UTC, kakts commented
再度確認しました
/lgtm

2021-02-23 13:46 UTC, inductor commented
/approve

2021-02-23 13:48 UTC, merged