ja: Make docs/setup/production-environment/turnkey/aws.md follow v1.18 of the original text
kubernetes/website pull request #26637
Opened 2021-02-20 09:16 UTC by tettsu

Close #26517

2021-02-25 14:09 UTC, kakts commented
/lgtm

2021-02-25 15:01 UTC, inductor requested changes

2021-02-25 15:01 UTC, inductor commented on content/ja/docs/setup/production-environment/turnkey/aws.md
> +* [conjure-up](https://docs.conjure-up.io/stable/en/cni/k8s-and-aws) - Ubuntu上でネイティブなAWSインテグレーションを用いてKubernetesクラスターを作成するオープンソースのインストーラーです。
ここって変える必要ありましたっけ？見た感じは不要な気が・・・

https://v1-18.docs.kubernetes.io/docs/setup/production-environment/turnkey/aws/

2021-02-25 15:01 UTC, inductor commented on content/ja/docs/setup/production-environment/turnkey/aws.md
> +* [kube-aws](https://github.com/kubernetes-incubator/kube-aws) - EC2、CloudFormation、Auto Scalingを使用して、[Flatcar Linux](https://www.flatcar-linux.org/)ノードでKubernetesクラスターを作成および管理します。
ここもハイフンいらない気がするんですけどどうでしょう？
https://v1-18.docs.kubernetes.io/docs/setup/production-environment/turnkey/aws/

2021-02-26 14:58 UTC, tettsu commented on content/ja/docs/setup/production-environment/turnkey/aws.md
> +* [conjure-up](https://docs.conjure-up.io/stable/en/cni/k8s-and-aws) - Ubuntu上でネイティブなAWSインテグレーションを用いてKubernetesクラスターを作成するオープンソースのインストーラーです。
@inductor 
Kubernetes Operations がハイフン使っていたので、勝手に合わせてしまっていました。オリジナルに合わせるなら確かに不要と思います。

2021-02-26 14:58 UTC, tettsu commented on content/ja/docs/setup/production-environment/turnkey/aws.md
> +* [kube-aws](https://github.com/kubernetes-incubator/kube-aws) - EC2、CloudFormation、Auto Scalingを使用して、[Flatcar Linux](https://www.flatcar-linux.org/)ノードでKubernetesクラスターを作成および管理します。
@inductor 
こちらも上と同様と思います！

2021-02-26 18:21 UTC, inductor commented on content/ja/docs/setup/production-environment/turnkey/aws.md
> +* [conjure-up](https://docs.conjure-up.io/stable/en/cni/k8s-and-aws) - Ubuntu上でネイティブなAWSインテグレーションを用いてKubernetesクラスターを作成するオープンソースのインストーラーです。
とりあえず今回はこちらの変更はしない方向でお願いします。

2021-02-27 07:48 UTC, tettsu commented on content/ja/docs/setup/production-environment/turnkey/aws.md
> +* [conjure-up](https://docs.conjure-up.io/stable/en/cni/k8s-and-aws) - Ubuntu上でネイティブなAWSインテグレーションを用いてKubernetesクラスターを作成するオープンソースのインストーラーです。
@inductor 
ご指摘に対応し、変更無いようにしました。

2021-02-27 08:00 UTC, inductor commented
/approve
/lgtm

2021-02-27 08:00 UTC, merged