ja: Make docs/setup/production-environment/tools/kubeadm/self-hosting.md follow v1.18 of the original text #26513
kubernetes/website pull request #26763
Opened 2021-02-28 05:15 UTC by yoichiro0217

2021-02-28 05:18 UTC, yoichiro0217 commented
/assign @inductor

2021-02-28 08:08 UTC, inductor commented
@yoichiro0217 ご対応ありがとうございます！
PR本番が空になってるため、これがどのissueに紐付くのか情報を追加してもらえますでしょうか？

他の日本語翻訳PRを参考にしてもらえると良いかなと思います。

2021-02-28 08:44 UTC, yoichiro0217 commented
@inductor 失礼しました。本文追加しましたので、宜しくお願いします。

2021-03-02 04:38 UTC, inductor requested changes
https://kubernetes.io/ja/docs/contribute/localization/#翻訳スタイルガイド に全体の方針がまとまっていますので、こちらも一通りご確認いただけますと 🙏

2021-03-02 04:38 UTC, inductor commented on content/ja/docs/setup/production-environment/tools/kubeadm/self-hosting.md
> +1. デフォルトでは、セルフホスト型のコントロールプレーンのポッドは、[`hostPath`](/docs/concepts/storage/volumes/#hostpath)ボリュームからロードされた資格情報に依存しています。最初の作成を除いて、これらの資格情報はkubeadmによって管理されません。
ポッドはPodで統一してください～

参考: https://kubernetes.io/ja/docs/contribute/localization/#翻訳スタイルガイド

2021-03-03 02:55 UTC, nasa9084 commented
inductorさんの指摘が修正されたらlgtmです

2021-03-03 03:24 UTC, inductor commented
@yoichiro0217 メンションつけ忘れてたのでping

2021-03-03 10:11 UTC, yoichiro0217 commented
@inductor ご確認ありがとうございます！一通り翻訳ガイド確認し修正しました。
お手数ですが、再度ご確認をお願いします。

2021-03-03 13:04 UTC, inductor commented
/lgtm
/approve

2021-03-03 13:04 UTC, inductor commented
/lgtm
/approve

2021-03-03 13:05 UTC, merged