Add "Concepts/container/images.md" in pt language
kubernetes/website pull request #26789
Opened 2021-03-01 23:43 UTC by HugoPfeffer

Add translation of "Imagens de Contêineres"(Container Images)

Add Concepts/containers/images.md

Changes to be committed:
new file: content/pt/docs/concepts/containers/images.md

Ref: https://docs.google.com/spreadsheets/d/1HiaVFJ7nRZo1MPNNYyq1u-L_N9xrJvzuUzkZ3GuJGNU/edit#gid=325775340

Preview: 

/language pt

2021-03-02 13:20 UTC, edsoncelio commented
Hey @HugoPfeffer, thanks for that translation!
Just a comment,  I think to match with the en version, the directory content/pt/docs/concepts/**container**/ need to be content/pt/docs/concepts/**containers**/

2021-03-02 15:58 UTC, HugoPfeffer commented
Hey @edsoncelio, thanks for pointing it out!
Do you know how can I fix this? This is my first PR on a big repo, I'm still getting used to all of the CI/CD stuff :)

2021-03-04 13:55 UTC, devlware commented
Hi @HugoPfeffer, thanks for helping the project. I'll take a look at your PR later today. :)

2021-03-05 03:55 UTC, devlware requested changes
Thanks for helping, I left some suggestions!

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +como `docker` e` podman`).
In this line I believe there is an extra 'como'.

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +pontos (`.`) e travessões (` -`).
Nitpick, there is an extra space inside the ` ` for -, it should be (`-`).

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +A política de pull padrão é `IfNotPresent` que faz com que o
Suggestion, there is another option for this.
```suggestion
A política padrão de pull é `IfNotPresent` a qual faz com que o
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +Além de fornecer o binário das imagens, um registro de contêiner também pode servir um [índice de imagem do contêiner](https://github.com/opencontainers/image-spec/blob/master/image-index.md). Um índ
```suggestion
Além de fornecer o binário das imagens, um registro de contêiner também pode servir um [índice de imagem do contêiner](https://github.com/opencontainers/image-spec/blob/master/image-index.md). Um índice de imagem pode apontar para múltiplos [manifestos da imagem](https://github.com/opencontainers/image-spec/blob/master/manifest.md) para versões específicas de arquitetura de um contêiner. A ideia é que você possa ter um nome para uma imagem (por exemplo: `pause`, `exemple/meuconteiner`, `kube-apiserver`) e permitir que diferentes sistemas busquem o binário da imagem correta para a arquitetura de máquina que estão usando.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +O próprio Kubernetes normalmente nomeia as imagens de contêiner com o sufixo `- $ (ARCH)`. Para retrocompatibilidade, gere as imagens mais antigas com sufixos. A ideia é gerar a imagem `pause` que te
```suggestion
O próprio Kubernetes normalmente nomeia as imagens de contêiner com o sufixo `-$(ARCH)`. Para retrocompatibilidade, gere as imagens mais antigas com sufixos. A ideia é gerar a imagem `pause` que tem o manifesto para todas as arquiteturas e `pause-amd64` que é retrocompatível com as configurações anteriores ou arquivos YAML que podem ter codificado as imagens com sufixos.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +Se você executar o Docker em seus nós, poderá configurar o contêiner do Docker
```suggestion
Se você executar o Docker em seus nós, poderá configurar o contêiner runtime do Docker
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +runtime para autenticação em um registro de contêiner privado.
```suggestion
para autenticação em um registro de contêiner privado.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +configuração para todos os nós onde você precisa.
```suggestion
configuração em todos os nós que você precisar.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +as chaves de registro são adicionadas ao `.docker/config.json`.
```suggestion
Todos os pods terão premissão de leitura às imagens em qualquer registro privado, uma que as chaves privadas do registro são adicionadas ao `.docker/config.json`.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +será mesclado.
```suggestion
serão mescladas.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +    - Certifique-se de [controlador de admissão AlwaysPullImages] (/ docs / reference / access-authn-authz / admission-controllers / # alwayspullimages) está ativo. Caso contrário, todos os pods têm
```suggestion
    - Certifique-se de que o [controlador de admissão AlwaysPullImages] (/ docs / reference / access-authn-authz / admission-controllers / # alwayspullimages) está ativo. Caso contrário, todos os pods têm potencialmente acesso a todas as imagens.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +    - Certifique-se de [controlador de admissão AlwaysPullImages](/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages) está ativo. Caso contrário, todos os Pods de todos os loc
```suggestion
    - Certifique-se de que o [controlador de admissão AlwaysPullImages](/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages) está ativo. Caso contrário, todos os Pods de todos os locatários terão potencialmente acesso a todas as imagens.
```

2021-03-05 03:55 UTC, devlware commented on content/pt/docs/concepts/containers/images.md
> +* Read the [OCI Image Manifest Specification](https://github.com/opencontainers/image-spec/blob/master/manifest.md)
```suggestion
* Leia a [OCI Image Manifest Specification](https://github.com/opencontainers/image-spec/blob/master/manifest.md)
```

2021-03-05 04:29 UTC, HugoPfeffer commented
Thanks for your suggestions @devlware! 

Since it's a lot of changes and I found another typo at line 277, I decided to make a new commit with all the changes. I don't know if that's recommended. If not, please tell me.

Sorry if it had too many errors. It's my first time doing a docs translations so I'm still getting the hang of it :)

2021-03-05 11:59 UTC, devlware commented
Hi @HugoPfeffer no problem with the "many" changes, it happens to me all the time. Thanks again for putting your time on this project. :)
Regarding commit, there is no problem in doing that.

2021-03-05 11:59 UTC, devlware commented
/lgtm
/assign @femrtnz

2021-03-07 14:28 UTC, femrtnz commented on content/pt/docs/concepts/containers/images.md
> +você pode fazer como exemplo:
```suggestion
você pode seguir uma da opções:
```

2021-03-07 21:46 UTC, femrtnz commented
Thanks for contributing @HugoPfeffer !!
/lgtm
/approve

2021-03-07 21:47 UTC, merged