Update Stackdriver Logging details
kubernetes/website pull request #26925
Opened 2021-03-06 23:50 UTC by charlesbaer

Updated the Stackdriver Logging section to include the Cloud Ops for GKE resource model and guidance on how to use.
Updated the options for exports.

2021-03-07 08:36 UTC, Arhell reviewed
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/community/blob/master/CLA.md

2021-03-08 05:39 UTC, RA489 commented
/check-cla

2021-03-08 15:14 UTC, charlesbaer commented
The CLA request has been completed

2021-03-09 17:36 UTC, charlesbaer commented
> I believe we are trying to exclude vendor-specific or dual-hosted contents in the website.

The page title is "Logging Using Stackdriver" which scopes the contents of the docs page to using Stackdriver for Kubernetes logs. In this PR, I updated the incomplete and out-dated references.  As they currently stand, users may be confused when they start using Stackdriver Logging based on the contents of this document. I did not add new content, but rather, corrected or expanded the existing content.

2021-03-15 19:41 UTC, celestehorgan commented
Preview link: https://deploy-preview-26925--kubernetes-io-master-staging.netlify.app/docs/tasks/debug-application-cluster/logging-stackdriver/#verifying-your-logging-agent-deployment

2021-03-15 19:48 UTC, celestehorgan requested changes
Per the third party content section of the content guide: https://kubernetes.io/docs/contribute/style/content-guide/#third-party-content:

- I agree with @charlesbaer, this is an update of existing documentation and it is necessary for Kubernetes to function.
- While this PR _does_ introduce mention (and link to) Cloud Ops for GKE that wasn't previously present, I think it's necessary, as logging behaviour differs because of it. 

No major changes to this PR, but one typo fix.

2021-03-15 19:48 UTC, celestehorgan commented on content/en/docs/tasks/debug-application-cluster/logging-stackdriver.md
> +types are used even if the Kubernetes cluster is not on Google Kubernetes Engine).
```suggestion
types are used even if the Kubernetes cluster is not on Google Kubernetes Engine.
```

2021-03-15 19:48 UTC, celestehorgan commented
I'd love if someone from @kubernetes/sig-instrumentation-approvers could take a look at this and give a technical LGTM. 

/sig instrumentation

2021-03-16 18:46 UTC, ehashman commented
@celestehorgan we removed support of stackdriver in our e2e tests, so we may want to remove this page entirely. I'll add to SIG Instrumentation agenda this week to either find a reviewer or make a decision.

2021-03-17 20:22 UTC, celestehorgan commented
Thanks @ehashman! Loop back round here or in slack and let me know how this goes.

2021-03-18 16:43 UTC, logicalhan commented
/sig cloud-provider
/cc @cheftako

2021-03-18 16:45 UTC, ehashman commented
> I believe we are trying to exclude vendor-specific or dual-hosted contents in the website.

SIG Instrumentation is fine with this (and removing this vendor-specific doc), but we think these docs don't belong to us. Pinging SIG Cloud Provider.

2021-03-27 08:50 UTC, tengqm commented
/hold
So the current consensus is that this page should be removed rather than fixed.

2021-05-29 21:40 UTC, kbhawkey commented
Related to PR https://github.com/kubernetes/website/pull/28166.

2021-09-26 22:08 UTC, kbhawkey commented
👋 @charlesbaer .
Since there has been no recent activity on this PR, I plan to close it.
Feel free to reopen this pull request.
/close

2021-09-26 22:08 UTC, closed without merging