ja: Make docs/concepts/architecture/controller.md follow v1.19 of the original text
kubernetes/website pull request #26948
Opened 2021-03-08 07:49 UTC by KobayashiD27

update ja/docs/concepts/architecture/controller.md
#26854

2021-03-08 07:49 UTC, KobayashiD27 commented
/assign @nasa9084

2021-03-08 11:15 UTC, inductor commented
@KobayashiD27 Base branch is incorrect. Please use `dev-1.19-ja.1` .

2021-03-09 01:15 UTC, KobayashiD27 commented
> @KobayashiD27 Base branch is incorrect. Please use `dev-1.19-ja.1` .

Thank you for pointing out.
Sorry, I took mistake. I changed the base branch.

2021-03-13 09:28 UTC, bells17 commented
/lgtm

2021-03-13 11:21 UTC, inductor requested changes
I don't think these blanks are necessary. Please check there's any other too.

2021-03-13 11:21 UTC, inductor commented on content/ja/docs/concepts/architecture/controller.md
> +ここで重要な点は、コントローラーが目的の状態を実現するために変更を加えてから、現在の状態をクラスターのAPIサーバーに報告することです。 他の制御ループは、その報告されたデータを監視し、独自のアクションを実行できます。
```suggestion
ここで重要な点は、コントローラーが目的の状態を実現するために変更を加えてから、現在の状態をクラスターのAPIサーバーに報告することです。他の制御ループは、その報告されたデータを監視し、独自のアクションを実行できます。
```

2021-03-13 11:21 UTC, inductor commented on content/ja/docs/concepts/architecture/controller.md
> +サーモスタットの例では、部屋が非常に寒い場合、別のコントローラーが霜防止ヒーターをオンにすることもあります。 Kubernetesクラスターを使用すると、コントロールプレーンは、[Kubernetesを拡張して](/ja/docs/concepts/extend-kubernetes/)実装することにより、IPアドレス管理ツールやストレージサービス、クラウドプロバイダーAPI、およびその他のサー
```suggestion
サーモスタットの例では、部屋が非常に寒い場合、別のコントローラーが霜防止ヒーターをオンにすることもあります。Kubernetesクラスターを使用すると、コントロールプレーンは、[Kubernetesを拡張して](/ja/docs/concepts/extend-kubernetes/)実装することにより、IPアドレス管理ツールやストレージサービス、クラウドプロバイダーAPI、およびその他のサービスと間接的に連携します。
```

2021-03-17 08:01 UTC, KobayashiD27 commented
> I don't think these blanks are necessary. Please check there's any other too.

Thanks. I checked for unnecessary blanks, but nothing else.

2021-03-17 09:07 UTC, inductor commented
/approve
/lgtm

2021-03-17 09:08 UTC, merged