Update the hyperlink address of High-Availability Clusters
kubernetes/website pull request #27139
Opened 2021-03-19 09:01 UTC by vaibhav2107

Ref #27094

2021-03-22 02:40 UTC, jihoon-seo requested changes
Thank for your contribution.
I suggested some changes, since there are some translated versions of the target page. :)

2021-03-22 02:40 UTC, jihoon-seo commented on content/zh/docs/concepts/overview/components.md
> +请参阅[构建高可用性集群](/docs/setup/production-environment/tools/kubeadm/high-availability/)
```suggestion
请参阅[构建高可用性集群](/zh/docs/setup/production-environment/tools/kubeadm/high-availability/)
```

2021-03-22 02:40 UTC, jihoon-seo commented on content/ja/docs/concepts/overview/components.md
> +マルチマスター VMセットアップの例については、[高可用性クラスターの構築](/docs/setup/production-environment/tools/kubeadm/high-availability/) を参照してください。
```suggestion
マルチマスター VMセットアップの例については、[高可用性クラスターの構築](/ja/docs/setup/production-environment/tools/kubeadm/high-availability/) を参照してください。
```

2021-03-22 02:40 UTC, jihoon-seo commented on content/fr/docs/concepts/overview/components.md
> +Voir [Construire des Clusters en Haute Disponibilité](/docs/setup/production-environment/tools/kubeadm/high-availability/) pour une configuration d'exemple en multi-master-VM.
```suggestion
Voir [Construire des Clusters en Haute Disponibilité](/fr/docs/setup/production-environment/tools/kubeadm/high-availability/) pour une configuration d'exemple en multi-master-VM.
```

2021-03-22 02:40 UTC, jihoon-seo commented on content/id/docs/concepts/overview/components.md
> +dapat dilihat di modul [Membangun Klaster HA] (/docs/setup/production-environment/tools/kubeadm/high-availability/).
```suggestion
dapat dilihat di modul [Membangun Klaster HA] (/id/docs/setup/production-environment/tools/kubeadm/high-availability/).
```

2021-03-22 02:40 UTC, jihoon-seo commented on content/id/docs/reference/glossary/kube-apiserver.md
> +Komponen ini didesain agar dapat diskalakan secara horizontal. Lihat [Membangun Klaster HA](/docs/setup/production-environment/tools/kubeadm/high-availability/).
```suggestion
Komponen ini didesain agar dapat diskalakan secara horizontal. Lihat [Membangun Klaster HA](/id/docs/setup/production-environment/tools/kubeadm/high-availability/).
```

2021-03-22 02:40 UTC, jihoon-seo commented on content/id/docs/setup/best-practices/multiple-zones.md
> +tinggi harus mengikuti instruksi [ketersediaan tinggi](/docs/setup/production-environment/tools/kubeadm/high-availability/).
```suggestion
tinggi harus mengikuti instruksi [ketersediaan tinggi](/id/docs/setup/production-environment/tools/kubeadm/high-availability/).
```

2021-03-22 02:40 UTC, jihoon-seo commented on content/fr/docs/reference/glossary/kube-apiserver.md
> +Il est conçu pour une mise à l'échelle horizontale, ce qui veut dire qu'il met à l'échelle en déployant des instances supplémentaires. Voir [Construire des Clusters en Haute Disponibilité](/docs/setu
```suggestion
Il est conçu pour une mise à l'échelle horizontale, ce qui veut dire qu'il met à l'échelle en déployant des instances supplémentaires. Voir [Construire des Clusters en Haute Disponibilité](/fr/docs/setup/production-environment/tools/kubeadm/high-availability/).
```

2021-03-22 02:44 UTC, jihoon-seo commented
- This PR resolves #27094

2021-03-23 22:42 UTC, sftim reviewed
@vaibhav2107 we try to limit fixes to a single language per PR - see https://kubernetes.io/docs/contribute/new-content/overview/#languages-per-pr

This change would be difficult to approve as it requires co-ordination with more than 10 localization teams. Could you update just the English version for now?

Once the English change merges, we'd be very happy to review follow-up PRs to update the relevant localized pages.

2021-03-23 22:43 UTC, sftim commented
This might be OK to merge but getting all the approvals will be tricky!

2021-03-27 07:32 UTC, seokho-son commented
As a Korean contents owner, LGTM :) 
But I would like to postpone giving approval to this PR until @vaibhav2107  's feedback on the comment from @sftim .

2021-03-27 09:20 UTC, tengqm commented
There is no change to zh localization although `language/zh` is added.
Good luck with this PR spanning so many teams.

2021-03-30 04:26 UTC, vaibhav2107 commented
> @vaibhav2107 we try to limit fixes to a single language per PR - see https://kubernetes.io/docs/contribute/new-content/overview/#languages-per-pr
> 
> This change would be difficult to approve as it requires co-ordination with more than 10 localization teams. Could you update just the English version for now?
> 
> Once the English change merges, we'd be very happy to review follow-up PRs to update the relevant localized pages.

Thank You @sftim for informing about this. Now on, I'll be careful not to fix more than one language in a PR.

2021-04-15 23:44 UTC, atoato88 commented
@vaibhav2107 
As @sftim says, could you update this PR to include changes for English contents only?
I think target files of this PR are following:
- content/en/docs/concepts/overview/components.md 
- content/en/docs/tasks/debug-application-cluster/debug-cluster.md

That's say remove other files (which include contents for other language localization) from this PR and those files will be updated in other PRs.

And also rebase is needed for current PR codeset.

2021-04-22 01:15 UTC, jihoon-seo commented
The link in the English version was updated in the PR #26725.
This PR seems good to close.

2021-04-22 06:21 UTC, atoato88 commented
@vaibhav2107 
This PR has `content/en/docs/tasks/debug-application-cluster/debug-cluster.md` also.
So it's good to update PR with including `content/en/docs/tasks/debug-application-cluster/debug-cluster.md` only, and update files on multi language next on other PR.
WDYT?

2021-04-22 11:44 UTC, atoato88 commented
I think update flow is following:
- At first, this PR needs rebase with latest `kubernetes:master`.
- Next, update PR by excluding files except for `en` contents.
- Third, exclude `content/en/docs/concepts/overview/components.md` because #26725 fixed this file already.

2021-04-22 23:49 UTC, atoato88 commented
Thank you for updating. :smile: 
PR includes [`content/en/docs/concepts/overview/components.md` yet](https://github.com/kubernetes/website/pull/27139/files#diff-5aa7dbbe8bb73f90af59eb44d3118360ebe22fede8a50d99fedb3d9c197ef0f2R36-R41), so you need to exclude this file from PR.

2021-04-22 23:55 UTC, atoato88 commented
And I remove tags which doesn't related to current codeset.

/remove-language fr 
/remove-language id 
/remove-language it 
/remove-language ja 
/remove-language ko 
/remove-language pl 
/remove-language pt
/remove-language ru
/remove-language zh
/remove-language de
/remove-language es

2021-04-23 08:24 UTC, merged