Add/pt/glossary/authn
kubernetes/website pull request #27163
Opened 2021-03-22 07:22 UTC by jralmaraz

Add content/pt/docs/reference/glossary/alternate-x509-schemes.md
Add content/pt/docs/reference/glossary/kerberos.md
Add content/pt/docs/reference/glossary/keystone.md
Add content/pt/docs/reference/glossary/ldap.md
Add content/pt/docs/reference/glossary/saml.md
Add content/pt/docs/reference/glossary/tls-common-name.md
Add content/pt/docs/reference/glossary/username.md

2021-03-22 11:33 UTC, rikatz commented
/assign
/cc

2021-03-22 13:27 UTC, rikatz requested changes

2021-03-22 13:27 UTC, rikatz commented on content/pt/docs/reference/glossary/alternate-x509-schemes.md
> +title: Alternate x509 schemes
Shouldn't this title need to be renamed? Not the id, but the title

2021-03-22 13:27 UTC, rikatz commented on content/pt/docs/reference/glossary/alternate-x509-schemes.md
> +Introduzido pela primeira vez em 1988 junto com os padrões X.500 para serviços de diretório eletrônico, o X.509 foi adaptado para uso na Internet pelo grupo de trabalho Public-Key Infrastructure (X.5
Here wouldn't be "O RFV 5280 define o perfil do certificado" ?

2021-03-22 13:27 UTC, rikatz commented on content/pt/docs/reference/access-authn-authz/bootstrap-tokens.md
> +Os tokens de inicialização são definidos com um tipo especifico de segredos (`bootstrap.kubernetes.io/token`) que existem no namespace `kube-system`. Estes segredos são então lidos pelo autenticador
here it would be good to reference the 'segredos' also as _secrets_ (make the association of the secret object)

2021-03-22 13:27 UTC, rikatz commented on content/pt/docs/reference/access-authn-authz/bootstrap-tokens.md
> +do gerenciador de controle.
here, please make a reference to kube-controller-manager (I don't know if there's a conscensus about translating the words, so we can at least say "gerenciador de controle - _kube-controller-manager_"

2021-03-22 13:28 UTC, rikatz commented
Left some reviews here.

BTW, where's the glossary used? I didn't saw this on the original content/en repo, so I'm curious :D

2021-03-22 13:29 UTC, rikatz commented on content/pt/docs/reference/access-authn-authz/bootstrap-tokens.md
> +{{< aviso >}}
here, please keep the original 'warning' shortcode, it's used to generate the warning box :)

2021-03-22 23:14 UTC, jralmaraz commented
Thanks @rikatz. Glossary terms links were added in the authentication page, sorry for the confusion. https://github.com/kubernetes/website/pull/26928/commits/a35e7690178b993f97d469ef1091d7de8c6bc41a, I need to remove "Extra fields from it" as it's not needed.

2021-03-23 00:29 UTC, jralmaraz commented
So sorry @rikatz , I made a mess with branches again, so I've cleared up and kept this PR just for the bootstrap token page translation.

2021-03-23 01:13 UTC, rikatz commented
/label tide/merge-method-squash

2021-03-23 01:44 UTC, rikatz commented
/approve
/lgtm

Thanks!

2021-03-23 01:45 UTC, merged