[ko] Translate tasks/tls/managing-tls-in-a-cluster.md in Korean
kubernetes/website pull request #27219
Opened 2021-03-25 15:44 UTC by jmyung

/closes #27067

2021-03-25 16:08 UTC, jmyung commented
link : https://deploy-preview-27219--k8s-dev-ko.netlify.app/ko/docs/tasks/tls/managing-tls-in-a-cluster/

2021-03-26 00:59 UTC, seokho-son commented
@yoonian 리뷰 가능하실까요 ~ ? ^^
/assign @yoonian

2021-03-28 14:36 UTC, seokho-son commented
안녕하세요! 손석호입니다. 즐거운 주말 보내셨는지요~? ^^
dev-1.20-ko.7 마감 일정 공유드립니다.

- PR 프리즈: 03/28 - 일 (작업 브랜치에 포함되는 PR을 확정, 이후의 PR은 차기 작업 브랜치로 리베이스 필요)
- 브랜치 머지: **03/31** - 수 (master 브랜치에 머지되며, k8s.io에 반영)

이번 dev-1.20-ko.7는 쿠버네티스 1.21 릴리스 일정에 따라, 수요일 내에 master에 merge 하려고 합니다. 도움을 부탁드립니다.. ^^
리뷰어께서는 컨트리뷰터와 협업하여 가능한 수요일까지 처리 부탁드립니다. 혹시 리뷰가 어려운 분은 다른 분들이 함께 도울 수 있도록 연락 부탁드립니다.. ^^
승인자께서는 직접 할당된 PR이 아니더라도, lgtm이 있는 PR의 경우, (프리뷰 등) 최종 확인 후에 approve 부탁드립니다!

2021-03-30 06:33 UTC, yoonian requested changes
@jmyung 간단히 리뷰해보았습니다. 확인 부탁드릴께요.

2021-03-30 06:40 UTC, jmyung commented
squash는 금일 밤에 진행하겠습니다.

2021-03-30 11:36 UTC, yoonian commented
/lgtm

2021-03-30 17:35 UTC, seokho-son commented
@jmyung PR은 확인 완료하였습니다 ^^ 스쿼싱 진행해주시면 승인 처리하도록 하겠습니다~~! 감사합니다.

2021-04-01 13:59 UTC, seokho-son commented
감사합니다!
/approve

2021-04-01 14:01 UTC, merged