Fix a typo in README-pl
kubernetes/website pull request #27549
Opened 2021-04-14 08:10 UTC by mfilocha

Remove an extra parenthesis.

2021-04-14 08:13 UTC, kpucynski requested changes

2021-04-14 08:13 UTC, kpucynski commented on README-pl.md
> +Udział w działaniach społeczności Kubernetes jest regulowany przez [Kodeks postępowania CNCF](https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/pl.md).
```suggestion
Udział w działaniach społeczności Kubernetesa jest regulowany przez [Kodeks postępowania CNCF](https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/pl.md).
```

2021-04-14 08:17 UTC, kpucynski approved these changes
/lgtm

2021-04-15 12:37 UTC, mfilocha commented
/approve

2021-04-15 12:38 UTC, mfilocha commented
/assign @onlydole

2021-04-15 12:47 UTC, sftim reviewed
/approve

2021-04-15 12:47 UTC, merged