Translate content/ru/docs/concepts/architecture/controller.md to russian
kubernetes/website pull request #27564
Opened 2021-04-15 05:06 UTC by mshalmanov

Hello

Translate 
content/ru/docs/concepts/architecture/cloud-controller.md
content/ru/docs/concepts/architecture/controller.md
to russian

2021-04-19 10:44 UTC, mshalmanov commented
/assign @msheldyakov

2021-04-23 11:14 UTC, jihoon-seo requested changes

2021-04-23 11:14 UTC, jihoon-seo commented on content/ru/docs/concepts/architecture/cloud-controller.md
> +{{< Примечание: >}}
CI tests fail.

https://app.netlify.com/sites/kubernetes-io-master-staging/deploys/6077c9e13e5b640007c61fac

```
2:07:24 PM: Error: Error building site: "/opt/build/repo/content/ru/docs/concepts/architecture/cloud-controller.md:31:1": failed to extract shortcode: template for shortcode "Примечание" not found
2:07:24 PM: Makefile:27: recipe for target 'build' failed
2:07:24 PM: make: *** [build] Error 255
```

```suggestion
{{< note >}}
```

2021-04-23 11:14 UTC, jihoon-seo commented on content/ru/docs/concepts/architecture/controller.md
> +{{< Примечание >}}
```suggestion
{{< note >}}
```

2021-05-12 11:54 UTC, mshalmanov commented
/retest

2021-05-12 12:05 UTC, mshalmanov commented
/retest
/lgtm
/approve

2021-05-13 04:36 UTC, mshalmanov commented
/lgtm

2021-05-18 09:23 UTC, mshalmanov commented
Hello. After edit my translate files, run checks  and show error in the cloud-controller.md file. How i can fix my error ? 

`2:53:43 PM: Error: Error building site: "/opt/build/repo/content/ru/docs/concepts/architecture/cloud-controller.md:13:1": failed to render shortcode "glossary_definition": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/glossary_definition.html:18:19": execute of template failed: template: shortcodes/glossary_definition.html:18:19: executing "shortcodes/glossary_definition.html" at <$term_info.Content>: nil pointer evaluating resource.Resource.Content
2:53:43 PM: Makefile:27: recipe for target 'build' failed`

2021-05-27 17:08 UTC, karuppiah7890 commented
@mshalmanov There are two errors

```
5:06:09 PM: ERROR 2021/05/25 11:36:09 [ru] "docs/concepts/architecture/cloud-controller.md": "cloud-controller-manager" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
ERROR 2021/05/25 11:36:09 [ru] no Resource or Page matching "/static/community-values.md*".
```

The first -

```
5:06:09 PM: ERROR 2021/05/25 11:36:09 [ru] "docs/concepts/architecture/cloud-controller.md": "cloud-controller-manager" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
```

This is related to this failure -

```
5:06:09 PM: Error: Error building site: "/opt/build/repo/content/ru/docs/concepts/architecture/cloud-controller.md:13:1": failed to render shortcode "glossary_definition": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/glossary_definition.html:18:19": execute of template failed: template: shortcodes/glossary_definition.html:18:19: executing "shortcodes/glossary_definition.html" at <$term_info.Content>: nil pointer evaluating resource.Resource.Content
```

This is because you are trying to refer to a glossary definition for the term `cloud-controller-manager` but there's no definition for that.

Example - https://kubernetes.io/docs/reference/glossary/?fundamental=true - look for Controller definition in English. This definition is located at `content/en/docs/reference/glossary/controller.md`

For `cloud-controller-manager` glossary definition, you need to define `content/ru/docs/reference/glossary/cloud-controller-manager.md` and for an example you can look at `content/en/docs/reference/glossary/cloud-controller-manager.md`

The second error -

```
ERROR 2021/05/25 11:36:09 [ru] no Resource or Page matching "/static/community-values.md*".
```

This is related to the community values page as the error says. In `content/ru/community/values.md`, you refer to `/static/community-values.md` but there's no such page for Russian language. Example for English language is - `content/en/community/values.md` and the `/static/community-values.md` page is -> `content/en/community/static/community-values.md`. So, for Russian language, you have to create something at `content/ru/community/static/community-values.md`

With that, all the errors should be gone :)

So, in short, you basically need to define these two markdown files -

`content/ru/community/static/community-values.md`

`content/ru/docs/reference/glossary/cloud-controller-manager.md`

Start by creating the above two files as simply empty files and see if `git submodule update --init --recursive --depth 1 && make production-build` works with no errors and then start writing content :)

2021-05-28 06:31 UTC, mshalmanov commented
/lgtm
/approve

2021-05-28 20:54 UTC, jihoon-seo commented
/label tide/merge-method-squash

2021-05-28 21:00 UTC, jihoon-seo requested changes
PTAL @mshalmanov !

2021-05-28 21:05 UTC, jihoon-seo commented
According to @karuppiah7890 's comment,
@mshalmanov you added `content/ru/docs/reference/glossary/cloud-controller-manager.md` file in the commit e37b083,
but the file `content/ru/community/static/community-values.md` is not added yet.
@mshalmanov Could you PTAL again?
Thanks!

2021-05-31 11:11 UTC, mshalmanov commented
/assign @msheldyakov

2021-06-03 08:22 UTC, Arhell reviewed
/lgtm
/assign @Potapy4

2021-06-03 10:05 UTC, Potapy4 commented
спасибо!

/approve

2021-06-03 10:07 UTC, merged