Update ja/docs/concepts/workloads/pods/_index.md
kubernetes/website pull request #27582
Opened 2021-04-16 14:37 UTC by shuuji3

✅  Resolves #26900.

2021-04-16 14:42 UTC, shuuji3 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +*Pod*は、Kubernetes内で作成・管理できるコンピューティングの最小のデプロイ可能なユニットです。
https://github.com/kubernetes/website/blob/release-1.19/content/en/docs/concepts/workloads/pods/_index.md#L17

原文には "(as in a pod of whales or pea pod)" という表現([クラゲの群れ](https://images.app.goo.gl/N77PGvzZuT8GxpSS9)や[えんどう豆のさや](https://www.google.com/search?q=pea+pod)という意味らしいです)があって面白いと思ったのですが、日本語にすると分かりづらいと思ったので省略してしまいました。

2021-04-16 14:43 UTC, shuuji3 commented
/assign @nasa9084

2021-04-21 02:28 UTC, inductor requested changes

2021-04-21 02:28 UTC, inductor commented on content/ja/docs/concepts/workloads/pods/_index.md
> +title: Pod
ここ変えなくてよいかと

2021-04-21 03:22 UTC, shuuji3 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +title: Pod
たしかにそうですね。#27626 もそのままにするべきでした。こちらは修正します。

2021-04-26 01:49 UTC, atoato88 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +*Pod*は、Kubernetes内で作成・管理できるコンピューティングの最小のデプロイ可能なユニットです。
As refer other localization(ex: [zh](https://v1-19.docs.kubernetes.io/zh/docs/concepts/workloads/pods/), [ko](https://v1-19.docs.kubernetes.io/ko/docs/concepts/workloads/pods/)), zh translate the sentence by localized sentence only.
ko writes both of localized sentence and original words.
IMHO, I would like to select ko style.

2021-04-26 10:08 UTC, shuuji3 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +*Pod*は、Kubernetes内で作成・管理できるコンピューティングの最小のデプロイ可能なユニットです。
I checked Korean localization, and I agree with you to follow that style as you suggest. I'll update the translation to include "(as in a pod of whales or pea pod)".

2021-04-26 12:58 UTC, shuuji3 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +*Pod*は、Kubernetes内で作成・管理できるコンピューティングの最小のデプロイ可能なユニットです。
I added a missing translation of "(as in a pod of whales or pea pod)". I added it to the end to make Japanese text more readable.

2021-04-26 13:05 UTC, shuuji3 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +*Pod*は、Kubernetes内で作成・管理できるコンピューティングの最小のデプロイ可能なユニットです。
FYI: I found an [interesting conversion](https://twitter.com/thockin/status/1060301866070814720) related to "pod of whales".

2021-04-27 00:44 UTC, atoato88 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +*Pod*は、Kubernetes内で作成・管理できるコンピューティングの最小のデプロイ可能なユニットです。
Wow!
Thank you to let me know that! :whale: :whale: :whale:

2021-04-27 02:01 UTC, atoato88 reviewed
Here are some nits.

2021-04-27 11:26 UTC, shuuji3 commented on content/ja/docs/concepts/workloads/pods/_index.md
> +*Pod*は、Kubernetes内で作成・管理できるコンピューティングの最小のデプロイ可能なユニットです。
Welcome! I'd like to know about other conversations like this.😃 Maybe someone has already created a tweet collection about Kubernetes.

2021-04-27 22:52 UTC, atoato88 commented
/lgtm

2021-04-28 07:09 UTC, inductor commented
/approve

2021-04-28 07:10 UTC, merged