Update: ja/docs/concepts/services-networking/network-policies.md
kubernetes/website pull request #27588
Opened 2021-04-17 05:52 UTC by JIIOryo

Update: ja/docs/concepts/services-networking/network-policies.md

https://github.com/kubernetes/website/issues/26891

2021-04-21 05:48 UTC, makocchi-git commented on content/ja/docs/concepts/services-networking/network-policies.md
> +IPアドレスまたはポートのレベル(OSI参照モデルのレイヤ3または4)でトラフィックフローを制御したい場合、クラスター内の特定のアプリケーションにKubernetesのネットワークポリシーを使用することを検討してください。ネットワークポリシーはアプリケーション中心の構造であり、{{<glossary_tooltip text="Pod" term_id="pod">}}がネットワークを介して多様
Endpoint(s) も Service と同じく Kubernetes のリソースではあるので "Endpoint" とするほうが統一されていいかなと思いましたが、どうでしょうか？
```suggestion
IPアドレスまたはポートのレベル(OSI参照モデルのレイヤ3または4)でトラフィックフローを制御したい場合、クラスター内の特定のアプリケーションにKubernetesのネットワークポリシーを使用することを検討してください。ネットワークポリシーはアプリケーション中心の構造であり、{{<glossary_tooltip text="Pod" term_id="pod">}}がネットワークを介して多様な「エンティティ」(「Endpoint」や「Service」のようなKubernetesに含まれる特定の意味を持つ共通の用語との重複を避けるため、ここではエンティティという単語を使用します。)と通信する方法を指定できます。
```

2021-04-23 00:15 UTC, JIIOryo commented on content/ja/docs/concepts/services-networking/network-policies.md
> +IPアドレスまたはポートのレベル(OSI参照モデルのレイヤ3または4)でトラフィックフローを制御したい場合、クラスター内の特定のアプリケーションにKubernetesのネットワークポリシーを使用することを検討してください。ネットワークポリシーはアプリケーション中心の構造であり、{{<glossary_tooltip text="Pod" term_id="pod">}}がネットワークを介して多様
おっしゃる通りですね、ありがとうございます。
修正いたしました。

977e8fe

2021-04-23 03:15 UTC, makocchi-git commented
/lgtm

2021-04-23 05:52 UTC, inductor requested changes

2021-04-23 05:52 UTC, inductor commented on content/ja/docs/concepts/services-networking/network-policies.md
> +- クラスター内トラフィックを強制的に共通ゲートウェイを通過させる (これは、サービスメッシュもしくは他のプロキシで提供するのが最適な場合があります。)
```suggestion
- クラスター内トラフィックを強制的に共通ゲートウェイを通過させる(これは、サービスメッシュもしくは他のプロキシで提供するのが最適な場合があります)。
```

2021-04-23 05:52 UTC, inductor commented on content/ja/docs/concepts/services-networking/network-policies.md
> +- クラスター内トラフィックを強制的に共通ゲートウェイを通過させる (これは、サービスメッシュもしくは他のプロキシで提供するのが最適な場合があります。)
括弧の箇所には半角スペース不要なのと、「。」を括弧の外に出しました。

他にもあるので直してもらえると！

2021-04-24 03:56 UTC, JIIOryo commented on content/ja/docs/concepts/services-networking/network-policies.md
> +- クラスター内トラフィックを強制的に共通ゲートウェイを通過させる (これは、サービスメッシュもしくは他のプロキシで提供するのが最適な場合があります。)
ご指摘ありがとうございます。
修正しました。

f302697

2021-04-25 11:03 UTC, inductor commented
/lgtm
/approve

2021-04-25 11:05 UTC, merged