Glossary PL - all on letter 'a'
kubernetes/website pull request #27600
Opened 2021-04-18 08:53 UTC by nvtkaszpir

Signed-off-by: Michał Sochoń <kaszpir@gmail.com>

2021-04-18 08:57 UTC, kpucynski requested changes

2021-04-18 08:57 UTC, kpucynski commented on content/pl/docs/reference/glossary/admission-controller.md
> +  Kawałek kodu który przejmuje przychodzące zapytania do API Kubernetesa
```suggestion
  Fragment kodu który przejmuje przychodzące zapytania do API Kubernetesa
```

2021-04-18 08:57 UTC, kpucynski commented on content/pl/docs/reference/glossary/admission-controller.md
> +  Kawałek kodu który przejmuje przychodzące zapytania do API Kubernetesa
```suggestion
  Fragment kodu który przejmuje przychodzące zapytania do API Kubernetesa
```

2021-04-18 08:57 UTC, kpucynski commented on content/pl/docs/reference/glossary/admission-controller.md
> +Kontrolery wejściowe są konfigurowane w otoczeniu API Kubernetesa i ich celeme jest sprawdzanie lub modyfikacja (albo jedno i drugie) obiektów przychodzących w rządaniach.
```suggestion
Kontrolery wejściowe są konfigurowane w otoczeniu API Kubernetesa i ich celem jest sprawdzanie lub modyfikacja (albo jedno i drugie) obiektów przychodzących w żądaniach.
```

2021-04-18 08:57 UTC, kpucynski commented on content/pl/docs/reference/glossary/admission-controller.md
> +Dowolny kontroler może także odrzucić obiekt dostarczony w rządaniu, przez co nie zostanie on przekazany dalej, a tym bardziej stworzony.
```suggestion
Dowolny kontroler może także odrzucić obiekt dostarczony w żądaniu, przez co nie zostanie on przekazany dalej, a tym bardziej stworzony.
```

2021-04-19 18:02 UTC, mfilocha commented on content/pl/docs/reference/glossary/application-developer.md
> +to może mieć różny zakres - zależy od kierunku spojrzenia i perspektywy.
```suggestion
Zakres jego prac może być bardzo różny.
```

2021-04-19 18:54 UTC, nvtkaszpir commented on content/pl/docs/reference/glossary/admission-controller.md
> +zanim zostaną one na stałe zachowane.
'trwale' to tez bym troche krecil nosem, bo bardziej chodzi o to ze za zachowane w api, i potem moga ulegac modyfikacjom.

2021-04-19 18:58 UTC, nvtkaszpir commented on content/pl/docs/reference/glossary/application-developer.md
> +to może mieć różny zakres - zależy od kierunku spojrzenia i perspektywy.
Oryginal jest rownie lakoniczny ;)

2021-04-19 19:00 UTC, nvtkaszpir commented on content/pl/docs/reference/glossary/app-container.md
> +W Kuberetesie {{< glossary_tooltip text="zadania" term_id="workload" >}} w podzie mogą mieć różny cykl życia i fazę w której są wykonywane.
Moze zrobic PR do wersji angielskiej?

2021-04-20 19:17 UTC, mfilocha commented on content/pl/docs/reference/glossary/admission-controller.md
> +  Część kodu który przejmuje przychodzące zapytania do API Kubernetesa
```suggestion
  Część kodu, która przejmuje przychodzące zapytania do API Kubernetesa
```

2021-04-20 19:17 UTC, mfilocha commented on content/pl/docs/reference/glossary/admission-controller.md
> +Część kodu który przejmuje przychodzące zapytania do API Kubernetesa
```suggestion
Część kodu, która przejmuje przychodzące zapytania do API Kubernetesa
```

2021-04-24 21:01 UTC, nvtkaszpir commented on content/pl/docs/reference/glossary/admission-controller.md
> +Dowolny kontroler może także odrzucić obiekt dostarczony w żądaniu, przez co nie zostanie on przekazany dalej, a tym bardziej stworzony.
ping

2021-04-24 21:01 UTC, nvtkaszpir commented on content/pl/docs/reference/glossary/admission-controller.md
> +Kontrolery mutujące ("mutating") mogą dodatkowo zmieniać obiekty (np. dodawać dodatkowe adnotacje.)
'modyfikujące' brzmi lepiej.

2021-04-24 21:02 UTC, nvtkaszpir commented on content/pl/docs/reference/glossary/admission-controller.md
> +zanim zostaną one na stałe zachowane.
a moze porzucic slowo 'stałe' ?

2021-04-25 17:29 UTC, mfilocha commented on content/pl/docs/reference/glossary/admission-controller.md
> +zanim zostaną one na stałe zachowane.
+1

2021-04-25 18:38 UTC, mfilocha commented on content/pl/docs/reference/glossary/admission-controller.md
> +Dowolny kontroler może także odrzucić obiekt dostarczony w żądaniu, przez co nie zostanie on przekazany dalej, a tym bardziej stworzony.
Zamiast "mutujące" niech będzie "zmieniające".

2021-09-14 05:31 UTC, reylejano commented
/retitle [pl] Glossary PL - all on letter 'a'

2021-11-13 21:17 UTC, mfilocha commented on content/pl/docs/reference/glossary/admission-controller.md
> +zanim zostaną one zachowane.
```suggestion
przed ich zapisaniem.
```

2021-11-13 21:17 UTC, mfilocha commented on content/pl/docs/reference/glossary/admission-controller.md
> +  zanim zostaną one zachowane.
```suggestion
  przed ich zapisaniem.
```

2021-11-13 21:17 UTC, mfilocha commented on content/pl/docs/reference/glossary/admission-controller.md
> +  Część kodu który przejmuje przychodzące zapytania do API Kubernetesa
```suggestion
  Część kodu, który przejmuje przychodzące zapytania do API Kubernetesa
```

2021-12-06 04:40 UTC, jimangel commented
@nvtkaszpir are you still working on this? If so, please address the feedback and [squash your commits](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits). Thanks!

2022-04-20 06:59 UTC, mfilocha commented
/remove-lifecycle rotten

2022-07-26 15:08 UTC, mfilocha commented
/remove-lifecycle stale

2022-07-28 11:05 UTC, divya-mohan0209 commented
@nvtkaszpir Please reopen the PR whenever you're ready to address the comments. It has been ~7 months since there was any activity on this PR.
/close

2022-07-28 11:05 UTC, closed without merging