Update Japanese localization on concepts/configuration/configmap.md
kubernetes/website pull request #27659
Opened 2021-04-22 06:29 UTC by hase1128

**What this PR does / why we need it:**
concepts/configuration/configmap.md is outdated.

File to update
https://github.com/kubernetes/website/tree/dev-1.19-ja.1/content/ja/docs/concepts/configuration/configmap.md

Original
https://github.com/kubernetes/website/tree/release-1.19/content/en/docs/concepts/configuration/configmap.md

diff between translated and v1.19
https://gist.github.com/e92f6d3b819b60295505744afabab6f9

**Which issue(s) this PR fixes:**
#26859

2021-04-22 06:30 UTC, hase1128 commented
/assign @nasa9084

2021-04-22 13:58 UTC, makocchi-git commented on content/ja/docs/concepts/configuration/configmap.md
> +一度ConfigMapがイミュータブルに設定されると、この変更を元に戻したり、`data`または`binaryData`フィールドのコンテンツを変更することは*できません*。Configmapの削除と再作成のみ可能です。既存のPodは削除されたConfigMapのマウントポイントを保持するため、こうしたPodは再作成することをおすすめします。
他は lgtm です
```suggestion
一度ConfigMapがイミュータブルに設定されると、この変更を元に戻したり、`data`または`binaryData`フィールドのコンテンツを変更することは*できません*。ConfigMapの削除と再作成のみ可能です。既存のPodは削除されたConfigMapのマウントポイントを保持するため、こうしたPodは再作成することをおすすめします。
```

2021-04-23 00:37 UTC, hase1128 commented
@makocchi-git 
ご指摘ありがとうございます。suggestionをaccepctしました。

2021-04-23 03:14 UTC, makocchi-git commented
/lgtm

2021-04-23 05:50 UTC, inductor requested changes

2021-04-23 05:50 UTC, inductor commented on content/ja/docs/concepts/configuration/configmap.md
> +ConfigMapは、他のオブジェクトが使うための設定を保存できるAPI[オブジェクト](/ja/docs/concepts/overview/working-with-objects/kubernetes-objects/)です。ほとんどのKubernetesオブジェクトに`spec`セクションがあるのとは違い、ConfigMapには`data`および`binaryData`フィールドがありま
```suggestion
ConfigMapは、他のオブジェクトが使うための設定を保存できるAPI[オブジェクト](/ja/docs/concepts/overview/working-with-objects/kubernetes-objects/)です。ほとんどのKubernetesオブジェクトに`spec`セクションがあるのとは違い、ConfigMapには`data`および`binaryData`フィールドがあります。これらのフィールドは、キーとバリューのペアを値として受け入れます。`data`フィールドと`binaryData`フィールドはどちらもオプションです。`data`フィールドはUTF-8バイトシーケンスを含むように設計されていますが、`binaryData`フィールドはバイナリデータを含むように設計されています。
```

2021-04-23 05:50 UTC, inductor commented on content/ja/docs/concepts/configuration/configmap.md
> +`data`または` binaryData`フィールドの各キーは、英数字、`-`、`_`、または`.`で構成されている必要があります。`data`に格納されているキーは、`binaryData`フィールドのキーと重複することはできません。
```suggestion
`data`または`binaryData`フィールドの各キーは、英数字、`-`、`_`、または`.`で構成されている必要があります。`data`に格納されているキーは、`binaryData`フィールドのキーと重複することはできません。
```

2021-04-23 06:14 UTC, hase1128 commented
@inductor 

I accepted your suggestion, thank you.

2021-05-12 16:18 UTC, inductor commented
/approve
/lgtm

2021-05-12 16:19 UTC, merged