update ja/docs/concepts/policy/resource-quotas.md
kubernetes/website pull request #27662
Opened 2021-04-22 08:38 UTC by s-kawamura-w664

Updated ja/docs/concepts/policy/resource-quotas.md to follow v1.19 of the original (English) text.
Fixes #26878

2021-04-22 13:06 UTC, atoato88 commented
/lgtm

2021-04-27 09:41 UTC, s-kawamura-w664 commented
/assign @inductor
Could you please review?
If this is OK, please approve.

2021-04-27 10:23 UTC, inductor requested changes
一点だけ。

2021-04-27 10:23 UTC, inductor commented on content/ja/docs/concepts/policy/resource-quotas.md
> +同じクォータで`BestEffort`と`NotBestEffort`の両方のスコープを指定することもできないことに注意してください。
ここ改行けしてもらえると。Markdownで半角スペースが入っちゃうと思うんで

2021-04-28 07:06 UTC, s-kawamura-w664 commented
@inductor 
I updated according to your review comment.
Could you please check it?

2021-04-28 07:19 UTC, inductor commented
/close

2021-04-28 07:20 UTC, inductor commented
/reopen

2021-04-28 07:20 UTC, inductor commented
/lgtm
/approve

2021-04-28 07:20 UTC, merged