[zh] translate administer-cluster/controller-manager-leader-migration.md
kubernetes/website pull request #27719
Opened 2021-04-26 02:18 UTC by CaoDonghui123

translate content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md

2021-04-26 07:13 UTC, howieyuen requested changes

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +类似地，添加 `--feature-gates=ControllerManagerLeaderMigration=true`、 `--enable-leader-migration`
顿号后面的空格，多余

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +和 `--leader-migration-config=/etc/leadermigration.conf` 到 `cloud-controller-manager`。
到 `cloud-controller-manager` 的参数中。

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +并且 `kube-controller-manager` 的 `--cloud-provider` 标志没有设置。
并且没有设置 `kube-controller-manager` 的 `--cloud-provider` 标志。

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +使用更新的 `cloud-controller-manager` 清单创建一个新的 N + 1 版本的控制平面节点。
使用已更新的

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +请参阅 [云控制器管理器管理](/zh/docs/tasks/administer-cluster/running-cloud-controller/)
请参阅[云控制器管理器管理]

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +了解有关如何部署 `cloud-controller-manager` 的更多详细信息。
更多细节。

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +具体取决于哪个控制器管理器拥有迁移租约。任何控制器都不会在任何时候在两个控制器管理器下运行。
任何时候都不存在一个控制器在两个控制器管理器下运行。

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +如果需要从版本 N + 1 到 N 的回滚，则将启用了针对 `kube-controller-manager` 的领导者迁移的版本N的节点添加回控制平面，每次替换版本 N + 1 的一个，直到只有节点为止版本N。
如果需要从 N + 1 版本回滚到 N，则将启用了领导者迁移的 `kube-controller-manager` 且版本为 N 的节点添加回控制平面，每次替换 N + 1 版本的一个，直到只有 N 版本的节点为止。

2021-04-26 07:13 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +-阅读 [领导者迁移控制器管理器](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2436-controller-manager-leader-migration) 改进建议
阅读[领导者迁移控制器管理器](https://github.com/kubernetes/enhancements/tree/master/keps/sig-cloud-provider/2436-controller-manager-leader-migration)改进建议

2021-04-26 10:11 UTC, CaoDonghui123 commented
@howieyuen 十分感谢，已修改

2021-04-27 03:10 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +作为 [云提供商提取工作](https://kubernetes.io/blog/2019/04/17/the-future-of-cloud-providers-in-kubernetes/)的一部分，
这里的 provider 是"驱动“的意思。是将 cloud provider 从 kube controller manager 里面抽取出来，形成 cloud controller manager。翻译成将“云提供商”抽取出来就令人困惑了。请彻查。

2021-04-27 06:50 UTC, CaoDonghui123 commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +作为 [云提供商提取工作](https://kubernetes.io/blog/2019/04/17/the-future-of-cloud-providers-in-kubernetes/)的一部分，
已修改

2021-04-28 03:17 UTC, howieyuen commented
/lgtm
Thanks

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +领导者迁移提供了一种机制，其中 HA 集群可以通过两个组件之间的共享资源锁定，
```suggestion
领导者迁移提供了一种机制，使得 HA 集群可以通过两个组件之间的共享资源锁定，
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +在 `kube-controller-manager` 和 `cloud-controller-manager` 之间安全地迁移 “特定于云” 的控制器，同时升级复制的控制平面。
```suggestion
安全地将“特定于云” 的控制器从 `kube-controller-manager` 和迁移到`cloud-controller-manager`，
同时升级复制的控制平面。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +本指南将引导你手动将控制平面从内置的云驱动的 `kube-controller-manager` 升级到同时运行 `kube-controller-manager` 和 `cloud-controller-manager`。
```suggestion
本指南将引导你手动将控制平面从内置的云驱动的 `kube-controller-manager` 升级为
同时运行 `kube-controller-manager` 和 `cloud-controller-manager`。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +如果使用工具来管理群集，请参阅该工具和云驱动的文档以获取更多详细信息。
```suggestion
如果使用工具来管理群集，请参阅对应工具和云驱动的文档以获取更多详细信息。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +假定控制平面正在运行 Kubernetes N 版本，并且要升级到 N + 1 版本。
```suggestion
假定控制平面正在运行 Kubernetes N 版本，并且要升级到 N+1 版本。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +N 和 N + 1的确切版本取决于每个云驱动。例如，如果云驱动构建了一个可与 Kubernetes 1.22 配合使用的 `cloud-controller-manager`，则 N 可以为 1.21，N + 1 可以为 1.22。
```suggestion
N 和 N+1 的确切版本取决于各个云驱动。例如，如果云驱动构建了一个可与 Kubernetes 1.22
配合使用的 `cloud-controller-manager`，则 N 可以为 1.21，N+1 可以为 1.22。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +从版本 N 开始，In-Tree 云驱动必须设置 `--cloud-provider` 标志，而且 `cloud-controller-manager` 还尚未部署。
```suggestion
从版本 N 开始，树内云驱动必须设置 `--cloud-provider` 标志，而且 `cloud-controller-manager` 尚未部署。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +Out-Of-Tree 云驱动必须已经构建了一个实现领导者迁移的 `cloud-controller-manager`。
```suggestion
树外云驱动必须已经构建了一个实现领导者迁移的 `cloud-controller-manager`。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +如果云驱动导入了 v0.21.0 或更高版本的 `k8s.io/cloud-provider` 和 `k8s.io/controller-manager`，则可以进行领导者迁移。
```suggestion
如果云驱动导入了 v0.21.0 或更高版本的 `k8s.io/cloud-provider` 和 `k8s.io/controller-manager`，
则可以进行领导者迁移。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +本指南假定每个控制平面节点的 kubelet 以静态 pod 的形式启动 `kube-controller-manager` 和 `cloud-controller-manager`，静态 pod 的定义在清单文件中。
```suggestion
本指南假定每个控制平面节点的 kubelet 以静态 pod 的形式启动 `kube-controller-manager`
和 `cloud-controller-manager`，静态 pod 的定义在清单文件中。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +控制器管理器的默认权限仅允许访问其主租约。为了使迁移正常进行，需要访问其他租约。
```suggestion
控制器管理器的默认权限仅允许访问其主 Lease 对象。为了使迁移正常进行，需要访问其他 Lease 对象。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +你可以通过修改 `system::leader-locking-kube-controller-manager` 角色来授予 `kube-controller-manager` 完全访问租约 API 的权限。
```suggestion
你可以通过修改 `system::leader-locking-kube-controller-manager` 角色来授予
`kube-controller-manager` 对 Lease API 的完全访问权限。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +目前，对于 In-Tree 云驱动，`kube-controller-manager` 运行 `route`、`service` 和 `cloud-node-lifecycle`。
```suggestion
目前，对于树内云驱动，`kube-controller-manager` 运行 `route`、`service` 和 `cloud-node-lifecycle`。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +在每个节点上重新启动 `kube-controller-manager`。目前，`kube-controller-manager` 已启用领导者迁移，并准备进行迁移。
```suggestion
在每个节点上重新启动 `kube-controller-manager`。这时，`kube-controller-manager`
已启用领导者迁移，并准备进行迁移。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +在 N + 1 版本中，控制器到管理器分配的期望状态可以由新的配置文件表示，如下所示。
```suggestion
在 N+1 版本中，控制器到管理器分配的期望状态可以由新的配置文件表示，如下所示。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +当创建 N + 1 版本的控制平面节点时，应将内容部署到 `/etc/leadermigration.conf`。
```suggestion
当创建 N+1 版本的控制平面节点时，应将内容部署到 `/etc/leadermigration.conf`。
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +N + 1 版本的 `kube-controller-manager` 不能启用领导者迁移，
```suggestion
N+1 版本的 `kube-controller-manager` 不能启用领导者迁移，
```

2021-04-29 02:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +使用已更新的 `cloud-controller-manager` 清单创建一个新的 N + 1 版本的控制平面节点。
```suggestion
使用已更新的 `cloud-controller-manager` 清单创建一个新的 N+1 版本的控制平面节点。
```

2021-04-29 04:44 UTC, CaoDonghui123 commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +使用已更新的 `cloud-controller-manager` 清单创建一个新的 N + 1 版本的控制平面节点。
I fixed it

2021-04-29 04:58 UTC, tengqm commented
Thanks.
/approve

2021-04-29 06:29 UTC, howieyuen commented
Thanks
/lgtm

2021-04-29 06:30 UTC, merged