[zh] Resync concepts section (10)
kubernetes/website pull request #27780
Opened 2021-04-28 09:22 UTC by tengqm

related: #27672

2021-05-06 02:39 UTC, howieyuen requested changes

2021-05-06 02:39 UTC, howieyuen commented on content/zh/docs/concepts/architecture/nodes.md
> +is managed by the
line 36: 这些 ~Pods~  -> 节点

2021-05-06 02:39 UTC, howieyuen commented on content/zh/docs/concepts/overview/components.md
>  请参阅[构建高可用性集群](/zh/docs/setup/production-environment/tools/kubeadm/high-availability/)
使用 kubeadm 构建高可用性集群

2021-05-10 00:52 UTC, tengqm commented on content/zh/docs/concepts/overview/components.md
>  请参阅[构建高可用性集群](/zh/docs/setup/production-environment/tools/kubeadm/high-availability/)
Done.

2021-05-10 02:20 UTC, howieyuen commented
/lgtm

2021-05-18 01:25 UTC, tanjunchen reviewed
/approve

2021-05-18 01:27 UTC, merged