[es] Fix concepts/_index.md
kubernetes/website pull request #27871
Opened 2021-05-05 01:21 UTC by csantanapr

Closes #27865

The links on the spanish version of Concepts was pointing to the English pages instead of the Spanish pages.

There are two links I left pointing to the English versions ***Service** and *Volumes**

It look like these sections need to be translated to Spanish, I left a message in the issue https://github.com/kubernetes/website/issues/13948#issuecomment-832336496 that is tracking the pages missing translation and who is working on them here

2021-05-05 01:22 UTC, csantanapr commented
/language es

2021-05-05 02:51 UTC, electrocucaracha reviewed
/lgtm

2021-05-05 02:51 UTC, electrocucaracha commented on content/es/docs/concepts/_index.md
> +Si quieres empezar a contribuir a la documentación de Kubernetes accede la pagina [Empieza a contribuir](/es/docs/contribute/start/).
```suggestion
Si quieres empezar a contribuir a la documentación de Kubernetes accede a la página [Empieza a contribuir](/es/docs/contribute/start/).
```

2021-05-05 08:02 UTC, raelga commented
Buenas @csantanapr, puedes revisar los cambios solicitados por @electrocucaracha?

Gracias!

/hold

2021-05-05 14:56 UTC, csantanapr commented
Hola @raelga envie el cambio

2021-05-05 15:22 UTC, electrocucaracha commented
/lgtm
/unhold

2021-05-06 06:17 UTC, raelga requested changes

2021-05-06 06:17 UTC, raelga commented on content/es/docs/concepts/_index.md
> +Si quieres empezar a contribuir a la documentación de Kubernetes accede la página [Empieza a contribuir](/es/docs/contribute/start/).
```suggestion
Si quieres empezar a contribuir a la documentación de Kubernetes accede a la página [Empieza a contribuir](/es/docs/contribute/start/).
```

2021-05-06 06:17 UTC, raelga commented on content/es/docs/concepts/_index.md
> +Si quieres empezar a contribuir a la documentación de Kubernetes accede la página [Empieza a contribuir](/es/docs/contribute/start/).
Falta la preposición aún.

2021-05-06 19:02 UTC, csantanapr commented on content/es/docs/concepts/_index.md
> +Si quieres empezar a contribuir a la documentación de Kubernetes accede la página [Empieza a contribuir](/es/docs/contribute/start/).
ah lo tenia presente y lo quite, para mi mejor sonaba `accede la página ` que `accede a la página`
Hago el cambio ahora

2021-05-06 19:05 UTC, csantanapr commented
@raelga añadi la preposición

2021-05-06 20:33 UTC, raelga commented on content/es/docs/concepts/_index.md
> +Si quieres empezar a contribuir a la documentación de Kubernetes accede la página [Empieza a contribuir](/es/docs/contribute/start/).
Buenas Carlos, aunque pueda sonar mejor, la frase es incorrecta sin la preposición.

El verbo acceder se construye siempre con un complemento `a`, puedes consultar la información sobre la norma ortográfica en https://www.rae.es/dpd/acceder.

2021-05-06 20:35 UTC, raelga approved these changes
/lgtm
/approve

2021-05-06 20:36 UTC, merged

2021-05-06 20:37 UTC, raelga commented
> @raelga añadi la preposición

Gracias Carlos, publicado! 🎉 

Felicitaciones por tu primera contribución y bienvenido al equipo :)