[zh] Resync task files (5)
kubernetes/website pull request #27986
Opened 2021-05-14 08:09 UTC by tengqm

Related: #27674

2021-05-19 03:54 UTC, howieyuen requested changes

2021-05-19 03:54 UTC, howieyuen commented on content/zh/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +  所描述），则kubectl 补全脚本应该已经安装到目录 `/usr/local/etc/bash_completion.d/kubectl`
则 kubectl

2021-05-19 03:54 UTC, howieyuen commented on content/zh/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +  用 Hommbrew 安装的 bash-completion v2 会初始化 目录 `BASH_COMPLETION_COMPAT_DIR`
会初始化目录

2021-05-27 15:28 UTC, chenrui333 approved these changes
/lgtm
/approve

2021-05-27 15:29 UTC, chenrui333 commented on content/zh/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +  所描述），则kubectl 补全脚本应该已经安装到目录 `/usr/local/etc/bash_completion.d/kubectl`
I found the code style issues here and there, maybe we can do batch updates in a later time. Let's just focus on the cleanup work right now :)

2021-05-27 15:40 UTC, merged