Updated TTLAfterFinished feature reference
kubernetes/website pull request #28011
Opened 2021-05-17 18:45 UTC by ahg-g

In https://github.com/kubernetes/website/pull/26738 we missed to update the reference to indicate that TTLAfterFinished graduated to beta.

2021-05-17 19:11 UTC, ahg-g commented
/assign @sftim

2021-05-18 08:33 UTC, sftim requested changes
Hi. We should keep the history of when this feature was alpha.

2021-05-18 08:33 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> -| `TTLAfterFinished` | `false` | Alpha | 1.12 | |
Please retain this line

2021-05-18 08:33 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +| `TTLAfterFinished` | `true` | Beta | 1.21 | |
```suggestion
| `TTLAfterFinished` | `false` | Alpha | 1.12 | 1.20 |
| `TTLAfterFinished` | `true` | Beta | 1.21 | |
```

2021-05-18 11:22 UTC, ahg-g commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +| `TTLAfterFinished` | `true` | Beta | 1.21 | |
done.

2021-05-18 12:43 UTC, sftim reviewed
/lgtm
/approve

2021-05-18 12:45 UTC, merged