[uk] Add configuration java microservice
kubernetes/website pull request #28157
Opened 2021-05-28 22:00 UTC by Arhell

en PR https://github.com/kubernetes/website/pull/27278/files
/assign @MaxymVlasov

2021-05-28 22:18 UTC, MaxymVlasov requested changes
Please, translate all things

2021-05-28 22:18 UTC, MaxymVlasov commented on content/uk/docs/tutorials/_index.md
> +* [Приклад: Configuring a Java Microservice](/docs/tutorials/configuration/configure-java-microservice/)
```suggestion
* [Приклад: Конфігурування Java мікросервісу](/docs/tutorials/configuration/configure-java-microservice/)
```

2021-05-28 22:18 UTC, MaxymVlasov commented on content/uk/docs/tutorials/_index.md
>  * [Configuring Redis Using a ConfigMap](/docs/tutorials/configuration/configure-redis-using-configmap/)
```suggestion
 * [Конфігурування Redis використовуючи ConfigMap](/docs/tutorials/configuration/configure-redis-using-configmap/)
```

2021-05-30 08:53 UTC, Arhell commented on content/uk/docs/tutorials/_index.md
> +* [Приклад: Configuring a Java Microservice](/docs/tutorials/configuration/configure-java-microservice/)
Done

2021-05-30 08:54 UTC, Arhell commented on content/uk/docs/tutorials/_index.md
>  * [Configuring Redis Using a ConfigMap](/docs/tutorials/configuration/configure-redis-using-configmap/)
Done
сс @MaxymVlasov

2021-05-31 09:55 UTC, Arhell commented
/assign @anastyakulyk

2021-05-31 10:14 UTC, idvoretskyi approved these changes

2021-05-31 10:14 UTC, idvoretskyi commented on content/uk/docs/tutorials/_index.md
> +* [Приклад: Розгортання Cassandra за допомогою наборів Stateful](/docs/tutorials/stateful-application/cassandra/)
StatefulSets не мають бути перекладені.

2021-05-31 10:14 UTC, idvoretskyi commented on content/uk/docs/tutorials/_index.md
> +* [Запуск ZooKeeper, розподіленої системи CP](/docs/tutorials/stateful-application/zookeeper/)
Що таке CP (додати визначення)?

2021-05-31 10:14 UTC, idvoretskyi commented on content/uk/docs/tutorials/_index.md
> +* [Використання джерела IP](/docs/tutorials/services/source-ip/)
Source IP не має бути перекладеним.

2021-05-31 10:15 UTC, idvoretskyi requested changes
A few nits.

2021-05-31 10:15 UTC, idvoretskyi commented
/hold

2021-05-31 10:26 UTC, Arhell commented
@idvoretskyi  готово
Про "CP" нашел только тут https://kubernetes.io/docs/tutorials/stateful-application/zookeeper/#managing-the-zookeeper-process

**distributed system is a common pattern**

2021-06-01 11:03 UTC, MaxymVlasov requested changes

2021-06-01 11:03 UTC, MaxymVlasov commented on content/uk/docs/tutorials/_index.md
> +* [Запуск ZooKeeper, розподіленої системи CP(Common Pattern)](/docs/tutorials/stateful-application/zookeeper/)
```suggestion
* [Запуск ZooKeeper, координатора розподіленої системи](/docs/tutorials/stateful-application/zookeeper/)
```
Пропоную викинути зайву термінологію про CP-AP-CAP, хіба що є великий прошарок людей що знайомі з CAP, не знайомі з Zookeeper і хочуть в K8s.

“CP” (consistent but not available under network partitions),
https://martin.kleppmann.com/2015/05/11/please-stop-calling-databases-cp-or-ap.html

2021-06-01 21:15 UTC, Arhell commented
@MaxymVlasov  all done

2021-06-01 21:29 UTC, MaxymVlasov approved these changes
/lgtm
/approve

2021-06-02 12:15 UTC, idvoretskyi approved these changes
/approve

2021-06-02 12:15 UTC, idvoretskyi commented
/hold cancel

2021-06-02 12:16 UTC, merged