[zh] Resync server-side-apply page
kubernetes/website pull request #28346
Opened 2021-06-09 11:07 UTC by tengqm

Related: #27673

2021-06-16 07:17 UTC, howieyuen requested changes

2021-06-16 07:17 UTC, howieyuen commented on content/zh/docs/reference/using-api/server-side-apply.md
> +| `//+listType` | `x-kubernetes-list-type` | `atomic`/`set`/`map` | Applicable to lists. `set` applies to lists taht include only scalar elements. These elements must be unique. `map` applies to list
taht? that

2021-06-16 07:17 UTC, howieyuen commented on content/zh/docs/reference/using-api/server-side-apply.md
> +| `//+listMapKey` | `x-kubernetes-list-map-keys` | 字段名称的列表，例如，`["port", "protocol"]` | 仅当 `+listType=map` 时适用。取值为字段名称的列表，这些字段值的组合能够唯一标识列表中的条目。尽管可以存在多个键，`listMapKey` 是单数的，这是因为键名需要在 Go 类型中各自独立指定。 | 1.1
第三列的最后一句话缺失：“The key fields must be scalars”，键字段必须是标量。

2021-06-19 11:53 UTC, tengqm commented on content/zh/docs/reference/using-api/server-side-apply.md
> +| `//+listMapKey` | `x-kubernetes-list-map-keys` | 字段名称的列表，例如，`["port", "protocol"]` | 仅当 `+listType=map` 时适用。取值为字段名称的列表，这些字段值的组合能够唯一标识列表中的条目。尽管可以存在多个键，`listMapKey` 是单数的，这是因为键名需要在 Go 类型中各自独立指定。 | 1.1
done

2021-06-24 14:16 UTC, chenrui333 approved these changes
/lgtm
/approve

2021-06-24 14:19 UTC, merged