Fix a few grammar issues and typos
kubernetes/website pull request #28387
Opened 2021-06-12 17:07 UTC by mehabhalodiya

These frequent grammar errors might be making you look bad. I have fixed these common mistakes and avoid damaging your credibility.

2021-06-14 10:48 UTC, mehabhalodiya commented
@kbhawkey Can you please review?
Let me know if anything needs to be changed.

2021-06-19 04:03 UTC, mehabhalodiya commented
/assign @celestehorgan

2021-06-20 19:44 UTC, sftim requested changes
I'm afraid I disagree with more of these changes than I agree with. Are they machine-generated?

2021-06-20 19:44 UTC, sftim commented on content/en/docs/contribute/advanced.md
> +  impact on documentation. If the documentation for a given feature won't be ready
The original wording is also idiomatic. It's OK to add a definite article here.

2021-06-20 19:44 UTC, sftim commented on content/en/docs/contribute/advanced.md
> -on the [Kubernetes Slack instance](https://kubernetes.slack.com) or on the
I prefer the original wording here. “Ask on the mailing list” is using “on”, whereas “ask in the #sig-docs” channel is using “in”.

2021-06-20 19:44 UTC, sftim commented on content/en/docs/contribute/advanced.md
> +  [teams in k/org](https://github.com/kubernetes/org/blob/master/config/kubernetes/sig-docs/teams.yaml), the
If changing “process” we should also change “plugins”. I'd prefer to change neither though.

2021-06-20 19:44 UTC, sftim commented on content/en/docs/contribute/advanced.md
> +- Exemplify the [community code of conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) and hold SIG members accountable for it
(I assume that) the elided phrase is “comply with”, so “accountable to &hellip; it” is correct.

2021-06-20 19:44 UTC, sftim commented on content/en/docs/contribute/advanced.md
> +- Recruit for and advocate on behalf of SIG Docs with the {{< glossary_tooltip text= "CNCF" term_id= "cncf" >}} and its platinum partners, including Google, Oracle, Azure, IBM, and Huawei
We usually write shortcodes with no space after `=`.

2021-09-14 05:24 UTC, reylejano commented on content/en/docs/contribute/advanced.md
> +[Kubernetes-sig-docs mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-docs).
The original is the correct name for the mailing list
```suggestion
[kubernetes-sig-docs mailing list](https://groups.google.com/forum/#!forum/kubernetes-sig-docs).
```

2021-09-14 05:27 UTC, reylejano commented
Hi @mehabhalodiya , since comments have not been addressed and this PR has had no action for the past 2 months, I'm closing this PR.

Feel free to re-open this PR when you have addressed the comments.

/close

2021-09-14 05:30 UTC, mehabhalodiya commented
Hi @reylejano 
I will make changes soon as till now I haven't seen the reviewed comments.
Sorry for inconvenience! Requesting you to open this!

2021-11-29 05:26 UTC, mehabhalodiya commented
/reopen

2021-12-06 03:49 UTC, jimangel commented
Thanks for continuing work on this!
/label tide/merge-method-squash
/lgtm
/approve

2021-12-06 03:50 UTC, merged