Pod affinity namespaceSelector to beta
kubernetes/website pull request #28416
Opened 2021-06-15 03:13 UTC by ahg-g

ref: kubernetes/enhancements#2249

2021-06-15 03:14 UTC, ahg-g commented
/sig scheduling

2021-06-15 04:39 UTC, jimangel commented
/unassign
/assign @PI-Victor

2021-06-15 10:55 UTC, sftim requested changes
I've added a suggestion to show how to update the feature gate table.

2021-06-15 10:55 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +| `PodAffinityNamespaceSelector` | `true` | Beta | 1.21 | 1.22 |
```suggestion
| `PodAffinityNamespaceSelector` | `false` | Alpha | 1.21 | 1.21 |
| `PodAffinityNamespaceSelector` | `true` | Beta | 1.22 |  |
```

2021-06-15 13:04 UTC, ahg-g commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +| `PodAffinityNamespaceSelector` | `true` | Beta | 1.21 | 1.22 |
done.

2021-06-16 00:57 UTC, tengqm commented
/approve

2021-06-16 14:02 UTC, PI-Victor commented
/assign @carlisia

2021-06-28 02:46 UTC, carlisia commented
/approve

2021-06-28 02:46 UTC, carlisia commented
/lgtm

2021-06-28 02:47 UTC, merged