Add Dockershim Deprecation part
kubernetes/website pull request #28453
Opened 2021-06-17 05:04 UTC by yJunS

2021-06-17 05:06 UTC, yJunS commented
![image](https://user-images.githubusercontent.com/20575981/122334708-b715aa00-cf6c-11eb-9589-59054bff00a9.png)
![image](https://user-images.githubusercontent.com/20575981/122334754-c98fe380-cf6c-11eb-9ce6-93f711629566.png)

2021-06-17 06:52 UTC, Arhell reviewed
Pls sign the CLA in order for the PR to be reviewed.
more info
https://github.com/kubernetes/website/pull/28453#issuecomment-862927465

2021-06-17 14:10 UTC, yJunS commented
@k8s-ci-robot I already signed the CLA.

2021-06-18 08:25 UTC, yJunS commented
/assign @tengqm

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +## 主题 {#Major Themes}
```suggestion
## 主题 {#major-themes}
```

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +### Volume 快照操作变得稳定 {$Volume Snapshot Operations Goes Stable}
```suggestion
### Volume 快照操作变得稳定 {#volume-snapshot-operations-goes-stable}
```

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +### Kubectl Debug 功能升级到 Beta ${#Kubectl Debug Graduates to Beta}
```suggestion
### Kubectl Debug 功能升级到 Beta {#kubectl-debug-graduates-to-beta}
```

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +请注意，作为新的内置命令，`kubectl debug` 优先于任何名为 “debug” 的 kubectl 插件。您必须重命名受影响的插件。
```suggestion
请注意，作为新的内置命令，`kubectl debug` 优先于任何名为 “debug” 的 kubectl 插件。你必须重命名受影响的插件。
```

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +`kubectl alpha debug` 现在不推荐使用，并将在后续版本中删除。更新您的脚本以使用 `kubectl debug`. 有关更多信息 `kubectl debug`，请参阅[调试正在运行的 Pod]((https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/)。
在这类文章中，不要用“您”，下同。

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +### 测试版：API 优先级和公平性 ${#Beta: API Priority and Fairness)
这里及后面的anchor全都是错的。请修改。

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +进程 ID (pid) 是 Linux 主机上的基本资源。达到任务限制而不达到任何其他资源限制并导致主机不稳定是微不足道的。
```suggestion
进程 ID (pid) 是 Linux 主机上的基本资源。达到任务限制而不达到任何其他资源限制并导致主机不稳定是很可能发生的。
```

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +默认启用一年后，SIG 节点在 `SupportNodePidsLimit`（节点到 Pod PID 隔离）和 `SupportPodPidsLimit`（限制每个 Pod 的 PID 的能力）上都将 PID 限制升级为 GA 。
```suggestion
默认启用一年后，SIG Node 在 `SupportNodePidsLimit`（节点到 Pod PID 隔离）和 `SupportPodPidsLimit`（限制每个 Pod 的 PID 的能力）上都将 PID 限制升级为 GA 。
```

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +### Alpha：节点优雅的关闭 ${#Alpha: Graceful node shutdown}
Graceful -> 体面地

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +一个关于 exec 探测超时的长期错误可能会影响现有的 pod 定义，已得到修复。在此修复之前 `timeoutSeconds`，exec 探测器不考虑该字段。相反，探测将无限期运行，甚至超过其配置的截止日期，直到返回结果。通过此更改，`1 second` 如果未指定值，则将应用默认值，并且如果探测时间超过一秒，现有 pod 定义可能不再足够。`ExecProbeTimeout` 此修复程序添加
请适当折行！否则无法review.

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +* [运行时类](https://github.com/kubernetes/enhancements/issues/585)
首字母大写的这种资源类型名称不要翻译

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +* [将 AppProtocol 添加到服务和终端上](https://github.com/kubernetes/enhancements/issues/1507)
Endpoints、Service 不要翻译

2021-06-19 11:49 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +* [定时任务](https://github.com/kubernetes/enhancements/issues/19)
CronJob 不要翻译

2021-06-19 12:20 UTC, yJunS commented
@tengqm 已更正

2021-06-19 14:03 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +## 其他更新 ${#other-updates}
所有 anchor 之前没有 $ 符号！请彻查。

```suggestion
## 其他更新 {#other-updates}
```

2021-06-19 14:03 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +* [添加 Pod-Startup Liveness-Probe Holdoff](https://github.com/kubernetes/enhancements/issues/950)
```suggestion
* [添加了对 Pod 层面启动探针和活跃性探针的扼制](https://github.com/kubernetes/enhancements/issues/950)
```

2021-06-19 14:03 UTC, tengqm commented on content/zh/blog/_posts/2020-12-08-kubernetes-release-1.20.md
> +这个版本是由一群非常敬业的人促成的，他们在世界上发生的许多事情中作为一个团队走到了一起。非常感谢发布负责人 Jeremy Rickard 以及发布团队中的其他所有人，感谢他们相互支持，并努力为社区发布 1.20 版本。
```suggestion
这个版本是由一群非常敬业的人促成的，他们在世界上发生的许多事情的时段作为一个团队走到了一起。
非常感谢发布负责人 Jeremy Rickard 以及发布团队中的其他所有人，感谢他们相互支持，并努力为社区发布 1.20 版本。
```

2021-06-22 05:31 UTC, yJunS commented
@tengqm 已更新

2021-06-22 07:06 UTC, tengqm commented
/approve

2021-07-08 08:12 UTC, howieyuen requested changes

2021-07-12 02:26 UTC, howieyuen commented
Thanks 
/lgtm

2021-07-12 02:28 UTC, merged