[ko] Translate node-pressure-eviction.md
kubernetes/website pull request #29029
Opened 2021-07-20 07:47 UTC by jihoon-seo

Closes #28811

/language ko

2021-07-26 14:59 UTC, ClaudiaJKang commented
라인이 많아서 리뷰를 분할해서 진행해야 할 것 같습니다. 

처음~200까지는 제가 진행하도록 하겠습니다.

혹시 201~끝까지는 @seokho-son 님께서 리뷰가 가능하실까요? ^^

2021-07-27 05:13 UTC, seokho-son commented
@ClaudiaJKang 넵!!^^

2021-07-28 15:09 UTC, ClaudiaJKang reviewed
@jihoon-seo 긴 글 번역 컨트리뷰션 해주셔서 감사합니다! 
몇 가지 리뷰 남겼습니다.

2021-07-28 15:09 UTC, ClaudiaJKang commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +kubelet은 총 용량 대비 축출 신호의 백분율 값을
```suggestion
Kubelet은 총 용량 대비 축출 신호의 백분율 값을 
```

- [ ] 원문에 Kubelet으로 되어있어 수정이 필요합니다.

2021-07-28 15:09 UTC, ClaudiaJKang commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +cgroup 계층구조의 최종 사용자 파드 부분에서도 지역적으로 이루어지기 때문에 중요하다.
```suggestion
cgroup 계층 구조의 최종 사용자 파드 부분에서도 지역적으로 이루어지기 때문에 중요하다. 
```

- [ ] 계층 구조로 변경이 필요합니다.

2021-07-28 15:09 UTC, ClaudiaJKang commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +[이 스크립트](/examples/admin/resource/memory-available.sh)는
```suggestion
이 [스크립트](/examples/admin/resource/memory-available.sh)는 
```

- [ ] 원문과 동일하게 `스크립트`에만 링크가 걸리도록 수정이 필요합니다.

2021-07-29 15:24 UTC, ianychoi requested changes

2021-07-29 15:24 UTC, ianychoi commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +1. 종료된 파드와 컨테이너에 대해 가비지 수집을 수행한다
Please add a period - e.g., "수행한다" -> "수행한다".

2021-07-29 15:24 UTC, ianychoi commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +1. 사용중이지 않은 이미지를 삭제한다
Please add a period (similar as L206)

2021-07-29 15:24 UTC, ianychoi commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +노드에 전용 'imagefs' 파일 시스템이 있는지 여부에 따라 kubelet이 파드 축출 순서를
Original sentence uses back quotes, not single quotes
```
'imagefs' -> `imagefs`
```

2021-07-29 15:24 UTC, ianychoi commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +기본적으로 kubelet은 'cAdvisor'를 폴링하여
(Similar as L249)

2021-07-30 01:27 UTC, seokho-son reviewed
@jihoon-seo 기여 감사합니다.. ^^
리뷰 의견을 남겼습니다. 참고하셔서 PR 업데이트 부탁드립니다.

2021-07-30 01:27 UTC, seokho-son commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +또한, kubelet은 `system-node-critical` {{<glossary_tooltip text="Priority" term_id="pod-priority">}}를 갖는 파드의 컨테이너에
```suggestion
또한, kubelet은 `system-node-critical` {{<glossary_tooltip text="파드 우선 순위(Priority)" term_id="pod-priority">}}를 갖는 파드의 컨테이너에 
```
라고 해야 할까요?  L363에 병기되어 있습니다.

2021-07-30 01:27 UTC, seokho-son commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +극도의 활용도를 달성하려는 것이 아니라 오버커밋에 대한 합리적인 조치를 원하는 경우,
```suggestion
사용률(utilization)를 극단적으로 높이려는 것이 아니라 오버커밋(overcommit)에 대한 합리적인 조치만 원하는 경우, 
```
원문을 고려하여 자연스럽게 수정 및 한영병기해 보았습니다. 참고하시기 바랍니다.

원문
If you are not trying to achieve extreme utilization, but a sensible measure of
overcommit

2021-07-30 01:27 UTC, seokho-son commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +| Quality of Service | oom_score_adj                                                                     |
```suggestion
| 서비스 품질(Quality of Service) | oom_score_adj                                                                     |
```
L410에도 번역이 되어있어서 일관성 유지 차원에서 수정해보았습니다. 참고하시기 바랍니다.

2021-07-30 01:27 UTC, seokho-son commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +   컨테이너 쓰기 가능 레이어를 저장하는 데 사용하는 선택적 파일시스템이다.
```suggestion
   컨테이너 쓰기 가능 레이어를 저장하는 데 사용하는 선택적 파일 시스템이다.
```

2021-07-30 01:27 UTC, seokho-son commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +| `PIDPressure`     | `pid.available`                                                                       | (리눅스) 노드의 가용 프로세스 ID(PID)가 축출 임계값 이하로 내려왔다                                   |
```suggestion
| `MemoryPressure`  | `memory.available`                                                                    | 노드의 가용 메모리 양이 축출 임계값에 도달                                                             |
| `DiskPressure`    | `nodefs.available`, `nodefs.inodesFree`, `imagefs.available`, or `imagefs.inodesFree` | 노드의 루트 파일시스템 또는 이미지 파일시스템의 가용 디스크 공간 또는 inode의 수가 축출 임계값에 도달 |
| `PIDPressure`     | `pid.available`                                                                       | (리눅스) 노드의 가용 프로세스 ID(PID)가 축출 임계값 이하로 내려옴                                  |
```
은 어떨까요?

2021-07-30 07:17 UTC, seokho-son commented
/assign @seokho-son

2021-08-02 01:24 UTC, jihoon-seo commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +   컨테이너 쓰기 가능 레이어를 저장하는 데 사용하는 선택적 파일시스템이다.
- 구글에서 찾아 보니, 영문으로는 둘 다 사용되고 있습니다.
  - filesystem
  - file system

- 원문에는 `filesystem` 이라고 되어 있습니다.
  - 저는 '파일시스템' 으로 제안 드려 봅니다. 😊

- In `./content/ko`
  - '파일시스템': 101 results in 18 files
  - '파일 시스템': 19 results in 14 files
  - `./content/ko` 에서도 나뉘어 있네용..

- (제 PR에서 '파일 시스템' 과 '파일시스템' 이 혼재되어 있습니다. 한 쪽으로 통일하겠습니다.)

2021-08-02 01:59 UTC, jihoon-seo commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +| Quality of Service | oom_score_adj                                                                     |
구글에서 찾아 보니, 위키백과에는 이렇게 되어 있습니다.
https://ko.wikipedia.org/wiki/QoS

> QoS(Quality of Service)는 다른 응용 프로그램, 사용자, 데이터 흐름 등에 우선 순위를 정하여, 데이터 전송에 특정 수준의 성능을 보장하기 위한 능력을 말한다. 이를 굳이 한국말로 번역하여 말하자면, "통신 서비스 품질"이라고 할 수 있지만, **대한민국에서는 특별히 QoS를 한국말로 옮겨 사용하는 예는 드물고**, 용도가 확고하게 정해진 바도 현재로서는 없다.

저도 여기에 공감하여 L309에서는 번역을 하지 않고 영문 그대로 두었습니다.

[K8s 문서 한글화 용어집](https://kubernetes.io/ko/docs/contribute/localization_ko/#한글화-용어집-정보)을 찾아 보니
QoS 자체에 대한 항목은 아직 없고
`QoS Class`	→	`QoS 클래스` 로 되어 있습니다.

다만 L410에서는 제가 [해당 링크](https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/)에 들어가 보니
페이지 제목이 `파드에 대한 서비스 품질(QoS) 구성` 으로 되어 있어서
L410의 링크 텍스트도 `서비스 품질` 로 하였습니다.

제 PR의 L309와 L410에서 일관성이 떨어지는 것이 맞으며, 이는 한 쪽으로 통일을 하겠습니다. 😊

(https://kubernetes.io/ko/docs/tasks/configure-pod-container/quality-service-pod/ 등에 있는
'서비스 품질' 이라는 번역에 대하여:

'서비스 품질' 이라고 번역하면 서비스의 품질을 뜻하는 것으로 이해되지만,
실제 QoS가 어떻게 사용되는지를 보면
K8s에서는 사용자가 미리 파드의 QoS 클래스를 Guaranteed, Burstable, BestEffort 중 하나로 설정하면
이후 K8s 컨트롤 플레인이 파드 스케줄링과 축출을 결정하는 데 사용하는 레이블 비슷한 것으로 볼 수 있으며
네트워크에서는 패킷 송신 측에서 각 패킷에 0~7 중 하나의 우선순위를 기재하여 송신하면
수신 측에 도달하기까지 거치게 되는 중간 네트워크 엔티티들에서 패킷에 기록되어 있는 우선순위를 참고하여
어떤 패킷을 우선적으로 처리할지를 결정하는 레이블 비슷한 것으로 볼 수 있습니다.
따라서 QoS는 '서비스 품질' 이라고 번역하는 것 보다는 영문 그대로 쓰는 것이 더 좋겠다는 것이 저의 의견입니다.)

2021-08-02 02:41 UTC, seokho-son commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +   컨테이너 쓰기 가능 레이어를 저장하는 데 사용하는 선택적 파일시스템이다.
@jihoon-seo 넵. 일관성만 맞춰진다면, 기여자의 의견을 따르겠습니다..^^

2021-08-02 02:58 UTC, seokho-son commented on content/ko/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +| Quality of Service | oom_score_adj                                                                     |
@jihoon-seo 

기존의 다른 기술 및 sw에서도 많이 사용되고 있는 용어라 

"서비스 품질" (Quality of Service) 한글로도 사람들이 의미를 잘 파악할 수 있지 않을까 합니다. 
(QoS를 K8s에서만 특별히 다르게 다른 의미로 사용하는 것 같지는 않습니다.) 

아래 다른 여러가지 참조 문서들을 공유 드립니다.
- https://www.ksa.or.kr/ks-sqi/3358/subview.do
- https://terms.naver.com/entry.naver?docId=2271829&cid=51207&categoryId=51207
- 국내 논문 리스트(서비스품질 qos 로 검색): https://scholar.google.com/scholar?hl=ko&as_sdt=0%2C5&q=%EC%84%9C%EB%B9%84%EC%8A%A4%ED%92%88%EC%A7%88+qos&btnG=


"서비스 품질"이 기술 용어와 일반 용어 사이에
혼동의 여지를 조금 주긴합니다만 이것은 영문에서도 비슷한 상황이 아닐까요? 
(혼동의 여지가 있으니 영어에서도 약자를 많이 사용하기 하는 듯 합니다.) 

한영병기 정도면 충분하지 않을까요? 특별히 어려운 기술 용어가 아닌 것 같은데 모두 영문으로 처리하자니 다소 부담스럽네요..^^

2021-08-02 06:07 UTC, jihoon-seo commented
@ClaudiaJKang @ianychoi @seokho-son 리뷰 감사합니다!
리뷰 의견을 반영하여 새 커밋을 추가했습니다.
확인 부탁드립니다. 😊

2021-08-02 06:09 UTC, jihoon-seo commented
Netlify 빌드 에러:
> "docs/concepts/scheduling-eviction/node-pressure-eviction.md": "node-pressure-eviction" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list

곧 수정하겠습니다. 😊

2021-08-03 02:59 UTC, seokho-son commented
/lgtm

2021-08-03 03:06 UTC, seokho-son commented
@ianychoi 리뷰로 "change requested" 요청하신 항목 확인 및 처리 부탁드립니다..^^ (참고: "change requested" 로 남겨진 리뷰는 Github UI 상 처리가 되어야하므로 /lgtm 과 /approve 로 처리가 되지 않습니다.)

2021-08-04 09:03 UTC, ClaudiaJKang commented
/approve

2021-08-04 22:53 UTC, merged