Update Polish strings localization
kubernetes/website pull request #29037
Opened 2021-07-20 19:58 UTC by mfilocha

Update Polish localization strings up to 027eb249af1ec46106da53c1bb3cd4724908c627.

2021-07-21 07:43 UTC, kpucynski requested changes

2021-07-21 07:43 UTC, kpucynski commented on data/i18n/pl/pl.toml
> +other = """This section links to third party projects that provide functionality required by Kubernetes. The Kubernetes project authors aren't responsible for these projects. This page follows <a hre
```suggestion
other = """Ta sekcja przekierowuje do projektów osób trzecich, które udostępniają funkcjonalność wymaganą przez Kubernetesa. Autory projektu Kubernetes nie są odpowiedzialni za te projekty. Ta strona podąża za <a href="https://github.com/cncf/foundation/blob/master/website-guidelines.md" target="_blank">wytycznymi CNCF dla stron internetowych</a> aby pokazać projekty w kolejności alfabetycznej. Aby dodać projekt na tą listę przeczytaj <a href="/docs/contribute/style/content-guide/#third-party-content">wytyczne dla zawartości</a> przed wysyłaniem zmian."""
```

2021-07-21 07:43 UTC, kpucynski commented on data/i18n/pl/pl.toml
> +other = "Chcesz zacząć mieszać w kodzie Kubernetesa?"
```suggestion
other = "Chcesz zacząć zabawę z kodem Kubernetesa?"
```
może tak? mniej dosłownie trochę

2021-07-21 09:12 UTC, mfilocha commented on data/i18n/pl/pl.toml
> +other = """This section links to third party projects that provide functionality required by Kubernetes. The Kubernetes project authors aren't responsible for these projects. This page follows <a hre
"tą listę" czy "tę listę"? Zawsze mam z tym wątpliwość...

2021-07-21 11:37 UTC, sftim commented on data/i18n/pl/pl.toml
>  other = """The Kubernetes Authors | Documentation Distributed under <a href="https://git.k8s.io/website/LICENSE" class="light-text">CC BY 4.0</a>"""
BTW, this could use an update too if you wish.

2021-07-21 12:34 UTC, kpucynski commented on data/i18n/pl/pl.toml
>  other = """The Kubernetes Authors | Documentation Distributed under <a href="https://git.k8s.io/website/LICENSE" class="light-text">CC BY 4.0</a>"""
```suggestion
other = """Autorzy Kubernetesa | Dokumentacja jest udostępniona w ramach licencji <a href="https://git.k8s.io/website/LICENSE" class="light-text">CC BY 4.0</a>"""
```

2021-07-21 12:35 UTC, kpucynski commented on data/i18n/pl/pl.toml
> +other = """This section links to third party projects that provide functionality required by Kubernetes. The Kubernetes project authors aren't responsible for these projects. This page follows <a hre
https://sjp.pwn.pl/poradnia/haslo/te-czy-ta;2227.html oficjalnię "tę"

2021-07-22 13:19 UTC, kpucynski approved these changes
/lgtm

2021-07-22 13:24 UTC, mfilocha commented
/approve

2021-07-22 13:25 UTC, merged