Update Polish README file
kubernetes/website pull request #29110
Opened 2021-07-24 11:17 UTC by mfilocha

Update Polish translation of main README file.

Synced up to 9c7d7dcdf6a987bc40b18c5a23c981ff2737ecf5.

2021-07-26 12:27 UTC, kpucynski requested changes

2021-07-26 12:27 UTC, kpucynski commented on README-pl.md
> +Jeśli widzisz błędy, prawdopodobnie kontener z Hugo nie dysponuje wystarczającymi zasobami. Aby rozwiązać ten problem, zwiększ ilość dostępnych dla Docker-a zasobów CPU i pamięci na Twojej maszynie (
```suggestion
Jeśli widzisz błędy, prawdopodobnie kontener z Hugo nie dysponuje wystarczającymi zasobami. Aby rozwiązać ten problem, zwiększ ilość dostępnych zasobów CPU i pamięci dla Docker-a na Twojej maszynie ([MacOSX](https://docs.docker.com/docker-for-mac/#resources) i [Windows](https://docs.docker.com/docker-for-windows/#resources)).
```

2021-07-26 17:37 UTC, nvtkaszpir requested changes
chyba `Dockera` bez kreski

2021-07-26 19:57 UTC, kpucynski approved these changes
/lgtm

2021-07-26 19:59 UTC, kpucynski commented
> chyba `Dockera` bez kreski brzmi lepiej?

w sumie odmienia się jak "Kubernetesa" - to nazwa własna, a nie skrótowiec

2021-07-27 08:54 UTC, nvtkaszpir reviewed
/lgtm
/approve

2021-07-27 09:11 UTC, kpucynski commented
/assign @savitharaghunathan

2021-07-27 09:34 UTC, nvtkaszpir approved these changes

2021-07-29 16:44 UTC, celestehorgan commented
/label language-pl

2021-08-10 07:05 UTC, mfilocha commented
@sftim Could you approve, please?

2021-08-17 02:33 UTC, kbhawkey commented
/language pl

2021-08-17 02:34 UTC, kbhawkey commented
/approve

2021-08-17 02:36 UTC, merged