Update patch schedule and add 1.22 to the party
kubernetes/website pull request #29268
Opened 2021-08-06 10:38 UTC by cpanato

- update the cherry pick deadline to one day before for the upcoming months, it was set to a Saturday, moving to Friday
- Add 1.22 to the patch schedule

Need to define the `maintenance mode` and `End of life` for 1.22

/hold

/assign @saschagrunert @puerco @jeremyrickard @justaugustus 
cc @kubernetes/release-engineering

2021-08-06 11:25 UTC, justaugustus commented
Slack ref: https://kubernetes.slack.com/archives/CJH2GBF7Y/p1628246143151700?thread_ts=1628246143.151700&cid=CJH2GBF7Y

2021-08-08 11:58 UTC, cpanato commented
update the dates @justaugustus PTAL

2021-08-08 14:57 UTC, justaugustus requested changes
@cpanato -- Just one nit on the October dates.

2021-08-08 14:57 UTC, justaugustus commented on content/en/releases/patch-releases.md
> +| October 2021          | 2021-10-08           | 2021-10-13  |
KubeCon NA overlaps, so let's move October dates a week later.

```suggestion
| October 2021          | 2021-10-15           | 2021-10-20  |
```

2021-08-09 09:36 UTC, justaugustus commented
/lgtm
/approve
/hold in case another @kubernetes/release-managers wants to take a look
(Release the hold when ready)

2021-08-09 12:15 UTC, xmudrii approved these changes

2021-08-09 13:53 UTC, saschagrunert approved these changes

2021-08-09 13:53 UTC, cpanato commented
/hold cancel

2021-08-09 13:55 UTC, merged