Update Document Deployments
kubernetes/website pull request #29310
Opened 2021-08-10 02:06 UTC by jonathino2590

2021-08-10 02:07 UTC, electrocucaracha commented
@jonathino2590 https://github.com/kubernetes/website/pull/29308#issuecomment-895671395

2021-08-10 02:09 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/controllers/deployment.md
> +Si deseamos obtener mas información del deployment adicione el parámetro `-o wide`, ejecuta el comando `kubectl get deployments -o wide`. La salida debe ser parecida a la siguiente:
```suggestion
Si deseamos obtener mas información del Deployment adicione el parámetro `-o wide`, ejecuta el comando `kubectl get deployments -o wide`. La salida debe ser parecida a la siguiente:
```

2021-08-10 02:09 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/controllers/deployment.md
> +ejutando el comando anterior se muestran los siguientes campos acionales:
```suggestion
ejecutando el comando anterior se muestran los siguientes campos adicionales:
```

2021-08-10 02:09 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/controllers/deployment.md
> +* `SELECTOR` muestra el label selector que se declaro en matchLabels o matchExpressions.
```suggestion
* `SELECTOR` muestra el Label selector que se declaro en matchLabels o matchExpressions.
```

2021-08-10 02:12 UTC, jonathino2590 commented
Acabe de hacer esos cambios en la documentacion de deploys, pero no lo puede enviar y no puedo ingresar al slack @electrocucaracha

2021-08-10 02:14 UTC, electrocucaracha commented
> Acabe de hacer esos cambios en la documentacion de deploys, pero no lo puede enviar y no puedo ingresar al slack @electrocucaracha

Escribe tu correo personal para que te envie la invitacion y luego borramos el comentario del PR

2021-08-10 02:15 UTC, jonathino2590 commented
jonathino2590@gmail.com

2021-08-10 02:17 UTC, electrocucaracha commented
> [jonathino2590@gmail.com](mailto:jonathino2590@gmail.com)

Te envie a invitacion a ese correo, puedes borrar el comentario del PR

2021-08-10 02:31 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/controllers/deployment.md
> +* `CONTAINERS` muestra el/los nombre(s) del contenedor declarado en `.spec.template.spec.containers.[name]`.
```suggestion
* `CONTAINERS` muestra los nombres de los contenedores declarados en `.spec.template.spec.containers.[name]`.
```

2021-08-10 02:31 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/controllers/deployment.md
> +* `IMAGES` muestra el/los nombre(s) de las imagenes declarado en `.spec.template.spec.containers.[image]`.
```suggestion
* `IMAGES` muestra el/los nombre(s) de las imagenes declaradas en `.spec.template.spec.containers.[image]`.
```

2021-08-10 02:40 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/controllers/deployment.md
> +* `IMAGES` muestra el/los nombre(s) de las imagenes declaradas en `.spec.template.spec.containers.[image]`.
```suggestion
* `IMAGES` muestra los nombres de las imágenes declaradas en `.spec.template.spec.containers.[image]`.
```

2021-08-10 02:42 UTC, electrocucaracha commented
/lgtm

2021-08-11 13:28 UTC, electrocucaracha commented
@raelga podrias darle una ultima revisada a estos cambios

2021-08-16 10:00 UTC, raelga requested changes
@jonathino2590 gracias por la contribución, te propongo algunas correciones!

2021-08-16 11:16 UTC, jonathino2590 commented
@raelga gracias por la revisión las acabo de resolver

2021-08-16 13:47 UTC, raelga commented
> @raelga gracias por la revisión las acabo de resolver

Buenas @jonathino2590, a parte de resolver la conversación, deberías hacer el commit con los fixes si estás de acuerdo con ellos.

2021-08-16 13:53 UTC, jonathino2590 commented
ok cambios commit hechos @raelga

2021-08-16 14:16 UTC, raelga approved these changes
Muchas gracias @jonathino2590!

Por mi parte nada más que añadir.

/approve

@electrocucaracha Puedes darle un repaso final, que con los nuevos commits, se ha quitado tu `lgtm`.

2021-08-24 04:47 UTC, jonathino2590 commented
@electrocucaracha buenas, se tendría algo adicional por hacer para a se apruebe este PR?

2021-08-24 05:26 UTC, electrocucaracha commented
@jonathino2590 se me había pasado revisarlo nuevamente. Muchas gracias por las correcciones.

/lgtm

2021-08-24 05:27 UTC, merged