Introduced backward compatibility breaking change
kubernetes/website pull request #29397
Opened 2021-08-14 16:34 UTC by longwuyuan

There is an existing blog for the backward-compatibility breaking changes to the Ingress-Nginx-Controller. This PR tries to get explicit on some aspects of the breaking change in the blog.
Thanks,
; Long

2021-08-14 16:36 UTC, longwuyuan commented
@strongjz @rikatz @tao12345666333

2021-08-15 16:38 UTC, sftim requested changes
Hi @longwuyuan 

This is a substantial rewording to a published article. Our initial position on any change to a blog article that we already published is to say “No” and keep the article as-is. People who have already read the original wording would not expect to see it altered.

Could you explain why you are recommending this rewrite?

/hold
because of the project's preference not to substantially revise published blog articles

2021-08-15 16:38 UTC, sftim commented on content/en/blog/_posts/2021-07-26-update-with-ingress-nginx.md
> +title: 'Updating Ingress-Nginx-Controller, to use the stable Ingress API'
We wouldn't retrospectively retitle this article.

2021-08-15 17:39 UTC, longwuyuan commented
Hi @sftim,

Thanks you very much for the message.

I understand the rationale now. The goal was to ;

- Get precise & explicit on the backward compatibility breaking change 
to the ingress-nginx controller

- Get generic on the versions of the ingress-controller

We are also adding a faq, on migration to K8s v1.22, in the context of 
using the ingress-nginx-controller, and this blog is referenced there. 
So I thought that the blog can serve as one location of some precise 
info that I have not yet inserted into the faq.

I think I will get similar review/advise from @rikatz and @strongjz so 
you all can decide whatever is best. Its a easy way ahead as I can just 
as well add the precise info into the faq.

Much gratitude for all the wonderful experience.

Thanks,
; Long

On 15/08/21 10:08 pm, Tim Bannister wrote:
>
> ***@***.**** requested changes on this pull request.
>
> Hi @longwuyuan <https://github.com/longwuyuan>
>
> This is a substantial rewording to a published article. Our initial 
> position on any change to a blog article that we already published is 
> to say “No” and keep the article as-is. People who have already read 
> the original wording would not expect to see it altered.
>
> Could you explain why you are recommending this rewrite?
>
> /hold
> because of the project's preference not to substantially revise 
> published blog articles
>
> ------------------------------------------------------------------------
>
> In content/en/blog/_posts/2021-07-26-update-with-ingress-nginx.md 
> <https://github.com/kubernetes/website/pull/29397#discussion_r689113934>:
>
> > @@ -1,6 +1,6 @@
>   ---
>   layout: blog
> -title: 'Updating NGINX-Ingress to use the stable Ingress API'
> +title: 'Updating Ingress-Nginx-Controller, to use the stable Ingress API'
>
> We wouldn't retrospectively retitle this article.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/kubernetes/website/pull/29397#pullrequestreview-730203248>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABGZVWX2KZOND6ZKUM6HMA3T47URBANCNFSM5CFHYR2A>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> 
> or Android 
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.
>

2021-08-15 17:43 UTC, sftim commented
How about adding a one-line update that hyperlinks to the new FAQ page? Could that work?

Small updates are OK, major revisions need very strong justification (typically: the original article was factually incorrect to the point of misleading, or the original article violated the CNCF code of conduct)

2021-08-15 17:48 UTC, longwuyuan commented
I think the weight of changing a already published blog can be a reason 
to avoid this PR completely. And all users will visit the faq in any case.

Much gratitude. I will close the PR.

Thanks,
; Long

On 15/08/21 11:13 pm, Tim Bannister wrote:
>
> How about adding a one-line update that hyperlinks to the new FAQ 
> page? Could that work?
>
> Small updates are OK, major revisions need very strong justification 
> (typically: the original article was factually incorrect to the point 
> of misleading, or the original article violated the CNCF code of conduct)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/kubernetes/website/pull/29397#issuecomment-899086882>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABGZVWVIADEA7GWJYT75NKDT474C7ANCNFSM5CFHYR2A>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> 
> or Android 
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>.
>

2021-08-15 17:49 UTC, longwuyuan commented
/close

2021-08-15 17:49 UTC, closed without merging