Add content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
kubernetes/website pull request #29405
Opened 2021-08-15 08:04 UTC by rajatgupta24

Hey folks, this is a PR for hi localization of the file: 
`content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html `

PR is linked under this issue #29353

/language hi

2021-08-15 09:53 UTC, rajatgupta24 commented
/assign @mittalyashu

2021-08-20 08:27 UTC, anubha-v-ardhan commented
/retitle [hi] Add content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html

2021-08-20 10:03 UTC, verma-kunal commented on content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +title: इंटरएक्टिव ट्यूटोरियल - अपने ऐप को उजागर करना
```suggestion
title: इंटरएक्टिव ट्यूटोरियल - अपने ऐप को एक्सपोज़ करना
```

2021-08-20 10:04 UTC, verma-kunal commented on content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +title: इंटरएक्टिव ट्यूटोरियल - अपने ऐप को उजागर करना
Do check the sheet [here](https://docs.google.com/spreadsheets/d/1UmL4K0v4yaN34k4WzYDZBobLBp5OZQp4GCTi28AfwQM/edit#gid=0) for words like these!! 
Some of them may have already been discussed & we encourage to use the same every where

2021-08-20 10:05 UTC, verma-kunal commented on content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +<html lang="en">
```suggestion
<html lang="hi">
```

2021-08-20 10:06 UTC, verma-kunal commented on content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +<html lang="en">
as we are doing Hindi Localization!!
We always encourage to refer other localizations, as you would get a much better idea on what to change!!

2021-08-20 10:07 UTC, verma-kunal commented on content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +            	<a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/" role="button">होम <span class=""></span></a>
```suggestion
            	<a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/" role="button">होम<span class=""></span></a>
```

2021-09-15 03:34 UTC, anubha-v-ardhan commented
@rajatgupta24 Can you change the base branch to `dev-1.22-hi.1`. That should make this PR ready to merge.

2021-09-16 08:55 UTC, anubha-v-ardhan requested changes
@rajatgupta24 Final Review. Please incorporate the changes.
Please change the base branch to `dev-1.22-hi.1` for this PR to be merged.

2021-09-16 08:55 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +                <a class="btn btn-lg btn-success" href="/hi/docs/tutorials/kubernetes-basics/scale/scale-intro/" role="button">मॉड्यूल 5 जारी रखें &gt;<span class=""></span></a>
```suggestion
                <a class="btn btn-lg btn-success" href="/hi/docs/tutorials/kubernetes-basics/scale/scale-intro/" role="button">मॉड्यूल 5 पर जाएं &gt;<span class=""></span></a>
```

2021-09-17 04:39 UTC, anubha-v-ardhan commented
/assign
/label tide/merge-method-squash

2021-09-17 04:39 UTC, anubha-v-ardhan commented
/lgtm
/approve

2021-09-17 04:41 UTC, merged

2021-09-17 04:49 UTC, anubha-v-ardhan commented
Thank you @rajatgupta24