Add content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
kubernetes/website pull request #29401
Opened 2021-08-14 17:38 UTC by rajatgupta24

Hey folks, this is a PR for hi localization of the file: `content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html`
PR is linked under this issue #29353

/language hi

2021-08-15 09:54 UTC, rajatgupta24 commented
/assign @mittalyashu

2021-08-17 08:48 UTC, sftim commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +<html lang="en">
```suggestion
<html lang="hi">
```

2021-08-17 08:57 UTC, rajatgupta24 commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +<html lang="en">
Thanks, @sftim, I made the change.

2021-08-20 08:30 UTC, anubha-v-ardhan commented
/retitle [hi] Add content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html

2021-10-17 05:54 UTC, anubha-v-ardhan requested changes
:)

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                    <li>कुबेरनेट्स पर कुबेक्टल के साथ अपना पहला ऐप डिप्लॉय करें।</li>
```suggestion
                    <li>कुबेरनेट्स पर kubectl के साथ अपना पहला ऐप डिप्लॉय करें।</li>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                <p>एक बार जब आपके पास कुबेरनेट्स क्लस्टर चल रहा हो, तो आप इसके ऊपर अपने कंटेनरीकृत अनुप्रयोगों को तैनात कर सकते हैं। ऐसा करने के लिए, आप कुबेरनेट्स <b>डिप्लॉयमेंट</b> कॉन्फ़िगरेशन बना
```suggestion
                <p>एक बार जब आपके पास कुबेरनेट्स क्लस्टर चल रहा हो, तो आप इसके ऊपर अपने कंटेनरीकृत एप्लीकेशन को तैनात कर सकते हैं। ऐसा करने के लिए, आप कुबेरनेट्स <b>डिप्लॉयमेंट</b> कॉन्फ़िगरेशन बनाते हैं। डिप्लॉयमेंट कुबेरनेट्स को निर्देश देता है कि आपके आवेदन के उदाहरण कैसे बनाएं और अपडेट करें। एक बार जब आप एक डिप्लॉयमेंट बना लेते हैं, तो कुबेरनेट्स कंट्रोल प्लेन उस डिप्लॉयमेंट में शामिल एप्लिकेशन इंस्टेंस को क्लस्टर में अलग-अलग नोड्स पर चलाने के लिए शेड्यूल करता है।</p>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                <p>एक बार एप्लिकेशन इंस्टेंस बन जाने के बाद, कुबेरनेट्स डिप्लॉयमेंट कंट्रोलर लगातार उन इंस्टेंस की निगरानी करता है। यदि किसी इंस्टेंस को होस्ट करने वाला नोड नीचे चला जाता है या हटा दि
```suggestion
                <p>एक बार एप्लिकेशन इंस्टेंस बन जाने के बाद, कुबेरनेट्स डिप्लॉयमेंट कंट्रोलर लगातार उन इंस्टेंस की निगरानी करता है। यदि किसी इंस्टेंस को होस्ट करने वाला नोड बंद हो जाता है या हटा दिया जाता है, तो डिप्लॉयमेंट कंट्रोलर क्लस्टर में इंस्टेंस को किसी अन्य नोड के इंस्टेंस से बदल देता है। <b>यह मशीन की विफलता या रखरखाव को दूर करने के लिए एक स्व-उपचार तंत्र प्रदान करता है।</b></p>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                <p>पूर्व-ऑर्केस्ट्रेशन की दुनिया में, इंस्टॉलेशन स्क्रिप्ट का उपयोग अक्सर अनुप्रयोगों को शुरू करने के लिए किया जाता था, लेकिन वे मशीन की विफलता से पुनर्प्राप्ति की अनुमति नहीं देते थे
```suggestion
                <p>पूर्व-ऑर्केस्ट्रेशन की दुनिया में, इंस्टॉलेशन स्क्रिप्ट का उपयोग अक्सर एप्लीकेशन को शुरू करने के लिए किया जाता था, लेकिन वे मशीन की विफलता से पुनर्प्राप्ति की अनुमति नहीं देते हैं। कुबेरनेट्स डिप्लॉयमेंट आपके एप्लिकेशन इंस्टेंस को बनाकर और उन्हें नोड्स पर चालू रखते हुए, एप्लिकेशन प्रबंधन के लिए एक मौलिक रूप से अलग दृष्टिकोण प्रदान करता है। </p>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                        <li>कुबेक्टल</li>
```suggestion
                        <li>kubectl</li>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                <p>आप कुबेरनेट्स कमांड लाइन इंटरफेस, <b>कुबेक्टल</b> का उपयोग करके डिप्लॉयमेंट बना और प्रबंधित कर सकते हैं। कुबेक्टल क्लस्टर के साथ बातचीत करने के लिए कुबेरनेट्स एपीआई का उपयोग करता ह
```suggestion
                <p>आप कुबेरनेट्स कमांड लाइन इंटरफेस, <b>kubectl</b> का उपयोग करके डिप्लॉयमेंट बना और प्रबंधित कर सकते हैं। kubectl क्लस्टर के साथ बातचीत करने के लिए कुबेरनेट्स एपीआई का उपयोग करता है। इस मॉड्यूल में, आप कुबेरनेट्स क्लस्टर पर आपके एप्लिकेशन चलाने वाले डिप्लॉयमेंट बनाने के लिए आवश्यक सबसे सामान्य kubectl कमांड सीखेंगे।</p>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                <p>जब आप कोई डिप्लॉयमेंट बनाते हैं, तो आपको अपने एप्लिकेशन के लिए कंटेनर इमेज और चलाने के लिए इच्छित प्रतिकृतियों की संख्या निर्दिष्ट करने की आवश्यकता होगी। आप अपने कामकाज को अपडेट कर
```suggestion
                <p>जब आप कोई डिप्लॉयमेंट बनाते हैं, तो आपको अपने एप्लिकेशन के लिए कंटेनर इमेज और चलाने के लिए इच्छित प्रतिकृतियों की संख्या निर्दिष्ट करने की आवश्यकता होगी। आप अपने कामकाज को अपडेट करके बाद में उस जानकारी को बदल सकते हैं; बूटकैंप के मॉड्यूल <a href="/hi//docs/tutorials/kubernetes-basics/scale/scale-intro/">5</a> और <a href="/hi/docs/tutorials/kubernetes-basics/update/update-intro/" >6</a> चर्चा करते हैं कि आप अपने डिप्लॉयमेंट को कैसे स्केल और अपडेट कर सकते हैं।</p>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                    <p><i> कुबेरनेट्स पर डिप्लॉयड होने के लिए अनुप्रयोगों को समर्थित कंटेनर प्रारूपों में से एक में पैक करने की आवश्यकता है </i></p>
```suggestion
                    <p><i> कुबेरनेट्स पर डिप्लॉयड होने के लिए एप्लीकेशन को समर्थित कंटेनर प्रारूपों में से एक में पैक करने की आवश्यकता है </i></p>
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                    अपने पहले डिप्लिव के लिए, आप एक डॉकर कंटेनर में पैक किए गए हैलो-नोड एप्लिकेशन का उपयोग करेंगे जो सभी अनुरोधों को प्रतिध्वनित करने के लिए NGINX का उपयोग करता है। (यदि आपने पहले से
```suggestion
                    अपने पहले डिप्लॉयमेंट के लिए, आप एक डॉकर कंटेनर में पैक किए गए हैलो-नोड एप्लिकेशन का उपयोग करेंगे जो सभी अनुरोधों को प्रतिध्वनित करने के लिए NGINX का उपयोग करता है। (यदि आपने पहले से हैलो-नोड एप्लिकेशन बनाने और कंटेनर का उपयोग करके इसे तैनात करने का प्रयास नहीं किया है, तो आप पहले <a href="/hi/docs/tutorials/hello-minikube/">हेलो Minikube ट्यूटोरियल</a> के निर्देशों का पालन करके ऐसा कर सकते हैं)।
```

2021-10-17 05:54 UTC, anubha-v-ardhan commented
/assign

2021-10-20 13:01 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +title: डिप्लॉयमेंट बनाने के लिए कुबेक्टल का उपयोग करना
```suggestion
title: डिप्लॉयमेंट बनाने के लिए kubectl का उपयोग करना
```

2021-11-02 05:19 UTC, anubha-v-ardhan commented
@rajatgupta24 Can you look at the suggestions above. We could merge this PR then

2021-11-29 07:57 UTC, anubha-v-ardhan commented
@rajatgupta24 Are you active with this PR? Can you have a look at suggestions above

2021-12-13 12:53 UTC, sftim commented
/label tide/merge-method-squash

2021-12-16 11:26 UTC, anubha-v-ardhan commented
/lgtm
/approve
Thank you @rajatgupta24

2021-12-16 11:27 UTC, merged