Add content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
kubernetes/website pull request #29420
Opened 2021-08-16 06:26 UTC by verma-kunal

This PR is a part of ongoing hi localization effort here #29353

/language hi

2021-08-17 05:52 UTC, anubha-v-ardhan requested changes

2021-08-17 05:52 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +            <p>पिछले मॉड्यूल में हमने एक<a href="/docs/concepts/workloads/controllers/deployment/">डिप्लॉयमेंट</a>बनाया और फिर इसे<a href="/docs/concepts/services-networking/service/">सर्विस</a>के मा
```suggestion
            <p>पिछले मॉड्यूल में हमने एक <a href="/docs/concepts/workloads/controllers/deployment/">डिप्लॉयमेंट</a> बनाया और फिर इसे <a href="/docs/concepts/services-networking/service/">सर्विस</a> के माध्यम से सार्वजनिक रूप से प्रदर्शित किया| डिप्लॉयमेंट ने हमारे एप्लिकेशन को चलाने के लिए केवल एक पॉड बनाया। जब ट्रैफ़िक बढ़ता है, तो हमें उपयोगकर्ता की मांग को पूरा करने के लिए एप्लिकेशन को स्केल करना होता है|</p>
```

2021-08-17 05:52 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +            <p>डिप्लॉयमेंट में रेप्लिका की संख्या को बदलकर<b>स्केलिंग</b>पूरा किया जाता है</p>
```suggestion
            <p>डिप्लॉयमेंट में रेप्लिका की संख्या को बदलकर <b>स्केलिंग</b> पूरा किया जाता है</p>
```

2021-08-17 05:52 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                        <span class="sr-only ">पहले का</span>
```suggestion
                        <span class="sr-only ">पिछला</span>
```

2021-08-17 05:52 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                <p>एक डिप्लॉयमेंट को स्केल करना यह सुनिश्चित करेगा कि नए पॉड बनाए गए हैं और उपलब्ध संसाधनों के साथ नोड्स के लिए शेड्यूल किए गए हैं| स्केलिंग से पॉड्स की संख्या नई वांछित स्थिति में बढ
```suggestion
                <p>एक डिप्लॉयमेंट को स्केल करना यह सुनिश्चित करेगा कि नए पॉड बनाए गए हैं और उपलब्ध संसाधनों के साथ नोड्स के लिए शेड्यूल किए गए हैं| स्केलिंग से पॉड्स की संख्या नई वांछित स्थिति में बढ़ जाएगी| कुबेरनेट्स पॉड्स के <a href="/docs/user-guide/horizontal-pod-autoscaling/">ऑटोस्केलिंग</a> का भी समर्थन करता है, लेकिन यह इस ट्यूटोरियल के दायरे से बाहर है| शून्य पर स्केलिंग भी संभव है, और यह निर्दिष्ट डिप्लॉयमेंट के सभी पॉड्स को समाप्त कर देगा|</p>
```

2021-08-17 05:52 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                <p>किसी एप्लिकेशन के कई इंस्टेंस को चलाने के लिए उन सभी को ट्रैफ़िक वितरित करने के तरीके की आवश्यकता होगी| सेवाओं में एक एकीकृत लोड-बैलेंसर होता है जो एक उजागर डिप्लॉयमेंट के सभी पॉड्
```suggestion
                <p>किसी एप्लिकेशन के कई इंस्टेंस को चलाने के लिए उन सभी को ट्रैफ़िक वितरित करने के तरीके की आवश्यकता होगी| सेवाओं में एक एकीकृत लोड-बैलेंसर होता है जो एक एक्सपोज्ड डिप्लॉयमेंट के सभी पॉड्स को नेटवर्क ट्रैफ़िक वितरित करेगा| यह सुनिश्चित करने के लिए कि ट्रैफ़िक केवल उपलब्ध पॉड्स को ही भेजा जाए, सर्विसे एंडपॉइंट्स का उपयोग करते हुए रनिंग पॉड्स की लगातार निगरानी करेंगी|</p>
```

2021-08-18 15:58 UTC, verma-kunal commented
Thanks for suggesting the changes @anubha-v-ardhan

2021-08-19 01:50 UTC, mittalyashu commented
/assign verma-kunal

2021-09-13 15:44 UTC, anubha-v-ardhan requested changes
Final Review

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +          <h3>उद्देश्यों</h3>
```suggestion
          <h3>उद्देश्य</h3>
```

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                    <li>kubectl का उपयोग करके किसी ऐप को स्केल करें|</li>
```suggestion
                    <li>kubectl का उपयोग करके किसी ऐप को स्केल करें।</li>
```

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +            <p>पिछले मॉड्यूल में हमने एक <a href="/docs/concepts/workloads/controllers/deployment/">डिप्लॉयमेंट</a> बनाया और फिर इसे <a href="/docs/concepts/services-networking/service/">सर्विस</a> क
```suggestion
            <p>पिछले मॉड्यूल में हमने एक <a href="/docs/concepts/workloads/controllers/deployment/">डिप्लॉयमेंट</a> बनाया और इसे <a href="/docs/concepts/services-networking/service/">सर्विस</a> के माध्यम से सार्वजनिक रूप से प्रदर्शित किया। डिप्लॉयमेंट ने हमारे एप्लिकेशन को चलाने के लिए केवल एक पॉड बनाया। जब ट्रैफ़िक बढ़ता है, तो हमें उपयोगकर्ता की मांग को पूरा करने के लिए एप्लिकेशन को स्केल करना होता है।</p>
```

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                    <p><i>आप kubectl create deployment कमांड के लिए --replicas पैरामीटर का उपयोग करके कई इंस्टेंस के साथ एक डिप्लॉयमेंट शुरू से बना सकते हैं|</i></p>
```suggestion
                    <p><i>आप kubectl create deployment कमांड के लिए --replicas पैरामीटर का उपयोग करके कई इंस्टेंस के साथ एक डिप्लॉयमेंट शुरू से बना सकते हैं।</i></p>
```

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                <p>एक डिप्लॉयमेंट को स्केल करना यह सुनिश्चित करेगा कि नए पॉड बनाए गए हैं और उपलब्ध संसाधनों के साथ नोड्स के लिए शेड्यूल किए गए हैं| स्केलिंग से पॉड्स की संख्या नई वांछित स्थिति में बढ
```suggestion
                <p>एक डिप्लॉयमेंट को स्केल करना यह सुनिश्चित करेगा कि नए पॉड बनाए गए हैं और उपलब्ध संसाधनों के साथ नोड्स के लिए शेड्यूल किए गए हैं। स्केलिंग से पॉड्स की संख्या नई वांछित स्थिति में बढ़ जाएगी। कुबेरनेट्स पॉड्स के <a href="/docs/user-guide/horizontal-pod-autoscaling/">ऑटोस्केलिंग</a> का भी समर्थन करता है, लेकिन यह इस ट्यूटोरियल के दायरे से बाहर है। शून्य पर स्केलिंग भी संभव है, और यह निर्दिष्ट डिप्लॉयमेंट के सभी पॉड्स को समाप्त कर देगा।</p>
```

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                <p>किसी एप्लिकेशन के कई इंस्टेंस को चलाने के लिए उन सभी को ट्रैफ़िक वितरित करने के तरीके की आवश्यकता होगी| सेवाओं में एक एकीकृत लोड-बैलेंसर होता है जो एक एक्सपोज्ड डिप्लॉयमेंट के सभी
```suggestion
                <p>किसी एप्लिकेशन के कई इंस्टेंस को चलाने के लिए उन सभी को ट्रैफ़िक वितरित करने के तरीके की आवश्यकता होगी। सर्विसों में एक एकीकृत लोड-बैलेंसर होता है जो एक एक्सपोज्ड डिप्लॉयमेंट के सभी पॉड्स को नेटवर्क ट्रैफ़िक वितरित करेगा। सर्विसे एंडपॉइंट्स का उपयोग करते हुए रनिंग पॉड्स की लगातार निगरानी करेंगी यह सुनिश्चित करने के लिए कि ट्रैफ़िक केवल उपलब्ध पॉड्स को ही भेजा जाए।</p>
```

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                    <p><i>डिप्लॉयमेंट में रेप्लिका की संख्या को बदलकर स्केलिंग को पूरा किया जाता है|</i></p>
```suggestion
                    <p><i>डिप्लॉयमेंट में रेप्लिका की संख्या को बदलकर स्केलिंग को पूरा किया जाता है।</i></p>
```

2021-09-13 15:44 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-intro.html
> +                <p>एक बार जब आपके पास किसी एप्लिकेशन के चलने के कई इंस्टेंस हैं, तो आप डाउनटाइम के बिना रोलिंग अपडेट करने में सक्षम होंगे| हम इसे अगले मॉड्यूल में करेंगे। अब, ऑनलाइन टर्मिनल पर चलते ह
```suggestion
                <p>एक बार जब आपके पास किसी एप्लिकेशन के चलने के कई इंस्टेंस हैं, तो आप डाउनटाइम के बिना रोलिंग अपडेट करने में सक्षम होंगे। हम इसे अगले मॉड्यूल में करेंगे। अब, ऑनलाइन टर्मिनल पर चलते हैं और हमारे एप्लिकेशन को स्केल करते हैं।</p>
```

2021-09-14 07:22 UTC, verma-kunal commented
Hey @anubha-v-ardhan , is this PR good to go? should i squash the commits?

2021-09-14 07:56 UTC, anubha-v-ardhan commented
@verma-kunal You can squash the commits. 
LGTM

2021-09-16 08:36 UTC, anubha-v-ardhan commented
/assign
/lgtm
/approve

Thank you @verma-kunal :)

2021-09-16 08:37 UTC, merged