Add content/hi/docs/tasks/_index.md
kubernetes/website pull request #29434
Opened 2021-08-17 08:53 UTC by rajatgupta24

Hindi localization of the file: content/hi/docs/tasks/_index.md

PR is linked under this issue #29353

/language hi

2021-08-17 11:18 UTC, Atharva-Shinde commented
LGTM
@daminisatya @mittalyashu

2021-08-17 13:13 UTC, anubha-v-ardhan requested changes

2021-08-17 13:13 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/_index.md
> +कुबेरनेट्स प्रलेखन के इस खंड में ऐसे पृष्ठ हैं जो दिखाते हैं कि व्यक्तिगत कार्य कैसे करें। एक कार्य पृष्ठ दिखाता है कि किसी एक काम को कैसे करना है, आमतौर पर चरणों का एक छोटा क्रम देकर।
```suggestion
कुबेरनेट्स प्रलेखन के इस खंड के पृष्ठ एकल कार्य करने का तरीका दिखाते हैं। आमतौर पर, कार्य पृष्ठ दिखाता है कि किसी एक काम को कई छोटे चरणों में विभाजित करके कैसे करना है।
```

2021-08-17 13:13 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/_index.md
> +[दस्तावेज़ीकरण के लिए एक पीआर बनाएं ](/docs/contribute/new-content/open-a-pr/).
```suggestion
यदि आप एक कार्य पृष्ठ लिखना चाहते हैं, तो 
[प्रलेखन के लिए एक पुल अनुरोध बनाएं](/docs/contribute/new-content/open-a-pr/) देखें।
```

2021-08-19 01:49 UTC, mittalyashu commented
/assign rajatgupta24

2021-08-20 08:25 UTC, anubha-v-ardhan commented
/retitle [hi] Add content/hi/docs/tasks/_index.md

2021-09-26 22:03 UTC, anubha-v-ardhan commented
/assign
/lgtm
/approve

2021-09-26 22:04 UTC, merged

2021-09-26 22:12 UTC, anubha-v-ardhan commented
Thank you @rajatgupta24