Add content/hi/docs/tutorials/kubernetes-basics/update/update-interactive.html
kubernetes/website pull request #29432
Opened 2021-08-17 06:58 UTC by verma-kunal

This PR is a part of ongoing `hi` localization effort here #29353

/language hi

2021-08-19 01:50 UTC, mittalyashu commented
/assign verma-kunal

2021-09-13 14:38 UTC, anubha-v-ardhan requested changes
Final Review.
Do commit these changes if you agree and we should be all set to merge this PR.

2021-09-13 14:38 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/update/update-interactive.html
> +               <a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/" role="button">कुबेरनेट्स मूल बातें पर लौटें<span class=""></span></a>
```suggestion
               <a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/scale/scale-interactive/" role="button">&lt; मॉड्यूल 5 पर वापस जाएं<span class=""></span></a>
               <a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/" role="button">मुलभुत कुबेरनेट्स पर लौटें<span class=""></span></a>
```

2021-09-13 14:39 UTC, anubha-v-ardhan commented
/assign

2021-09-15 04:47 UTC, verma-kunal commented
any other changes to be made here?

2021-09-15 05:03 UTC, anubha-v-ardhan commented
/lgtm
/approve

Thank you @verma-kunal

2021-09-15 05:04 UTC, merged