Add content/hi/docs/tutorials/kubernetes-basics/update/update-intro.html
kubernetes/website pull request #29454
Opened 2021-08-18 08:56 UTC by verma-kunal

This PR is a part of ongoing `hi` localization effort here #29353

/language hi

2021-08-19 01:49 UTC, mittalyashu commented
/assign verma-kunal

2021-09-16 08:31 UTC, anubha-v-ardhan requested changes
Final Review

2021-09-16 08:31 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>एप्लिकेशन स्केलिंग के समान, यदि कोई डिप्लॉयमेंट सार्वजनिक रूप से एक्सपोज़ होता है, तो सर्विस केवल अपडेट के दौरान उपलब्ध पॉड्स पर ट्रैफ़िक को लोड-बैलेंस करेगी। एक उपलब्ध पॉड एक उदाह
```suggestion
                <p>एप्लिकेशन स्केलिंग के समान, यदि कोई डिप्लॉयमेंट सार्वजनिक रूप से एक्सपोज़ होता है, तो सर्विस केवल अपडेट के दौरान उपलब्ध पॉड्स पर ट्रैफ़िक को लोड-बैलेंस करेगी। उपलब्ध पॉड एक इंस्टेंस है जो एप्लिकेशन के उपयोगकर्ताओं के लिए उपलब्ध है।</p>
```

2021-09-16 08:31 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    <li>किसी एप्लिकेशन को एक परिवेश से दूसरे परिवेश में प्रचारित करें (कंटेनर इमेज अपडेट के माध्यम से)</li>
```suggestion
                    <li>किसी एप्लिकेशन को एक एनवायरनमेंट से दूसरे एनवायरनमेंट में प्रचारित करें (कंटेनर इमेज अपडेट के माध्यम से)</li>
```

2021-09-16 08:31 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    <p><i>यदि कोई डिप्लॉयमेंट सार्वजनिक रूप से प्रकट होता है, तो सर्विस अपडेट  के दौरान केवल उपलब्ध पॉड्स पर ट्रैफ़िक लोड-बैलेंस करेगी|</i></p>
```suggestion
                    <p><i>यदि कोई डिप्लॉयमेंट सार्वजनिक रूप से प्रकट होता है, तो सर्विस अपडेट के दौरान केवल उपलब्ध पॉड्स पर ट्रैफ़िक लोड-बैलेंस करेगी।</i></p>
```

2021-09-16 08:31 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                <p>निम्नलिखित इंटरैक्टिव ट्यूटोरियल में, हम अपने एप्लिकेशन को एक नए संस्करण में अपडेट करेंगे, और रोलबैक भी करेंगे|</p>
```suggestion
                <p>निम्नलिखित इंटरैक्टिव ट्यूटोरियल में हम अपने एप्लिकेशन को एक नए संस्करण में अपडेट और रोलबैक करेंगे। </p>
```

2021-09-16 08:33 UTC, anubha-v-ardhan commented on content/hi/docs/tutorials/kubernetes-basics/update/update-intro.html
> +                    <li>kubectl का उपयोग करके रोलिंग अपडेट करें|</li>
Note that `|` and `।` are different characters. While `|` is a vertical bar, `।` is what we call पूर्ण विराम in Hindi.

2021-09-17 05:43 UTC, anubha-v-ardhan commented
/assign

2021-09-18 15:18 UTC, verma-kunal commented
Hey @anubha-v-ardhan , are these commits good to go for squashing?

2021-09-19 16:23 UTC, anubha-v-ardhan commented
Just one suggestion is pending, try to commit it and its good for squashing.

2021-09-25 09:42 UTC, anubha-v-ardhan commented
/lgtm
/approve

Thank you @verma-kunal

2021-09-25 09:44 UTC, merged