Add content/hi/docs/tasks/tools/install-kubectl-windows.md
kubernetes/website pull request #29465
Opened 2021-08-18 18:49 UTC by vedant-kakde

Localizes

-  `content/hi/docs/tasks/tools/install-kubectl-windows.md`

2021-08-18 18:49 UTC, vedant-kakde commented
This PR is in continuation of hi localization effort: #29353

/language hi

2021-08-19 01:46 UTC, mittalyashu commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +title: Windows पर kubectl इंस्टॉल और सेट करें
```suggestion
title: Windows पर kubectl इंस्टॉल और सेटअप करें
```

2021-08-19 01:46 UTC, mittalyashu commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +## {{% heading "prerequisites" %}}
```suggestion
## {{% heading "आवश्यकताए" %}}
```

2021-08-19 01:46 UTC, mittalyashu commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +
```suggestion
```

2021-08-19 01:46 UTC, mittalyashu commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +
```suggestion
```

2021-08-19 01:46 UTC, mittalyashu commented
/assign vedant-kakde

2021-08-20 08:36 UTC, anubha-v-ardhan commented
/retitle [hi] Add content/hi/docs/tasks/tools/install-kubectl-windows.md

2021-10-02 05:42 UTC, anubha-v-ardhan commented
/assign

2021-10-02 05:48 UTC, anubha-v-ardhan requested changes
Can you replace all full stops `.` with purna viram '।` please

2021-10-02 05:48 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +## {{% heading "आवश्यकताए" %}}
```suggestion
## {{% heading "prerequisites" %}}
```

2021-10-02 05:48 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +## {{% heading "आगे क्या होगा" %}}
```suggestion
## {{% heading "whatsnext" %}}
```

2021-10-02 05:49 UTC, anubha-v-ardhan commented
This PR is similar to #29461 which is already reviewed and merged. It would be really helpful @vedant-kakde if you implement the same kind of changes here too.

2021-10-02 05:50 UTC, vedant-kakde commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +## {{% heading "आवश्यकताए" %}}
Yes, I'll do that.

2021-10-06 16:24 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +यदि आपने पहले Docker Desktop स्थापित किया है, तो आपको Docker Desktop इंस्टॉलर द्वारा जोड़े गए एक `PATH` से पहले अपनी `PATH` प्रविष्टि डालने की आवश्यकता हो सकती है या डॉकर डेस्कटॉप के `kubectl` को हटा
```suggestion
यदि आपने पहले Docker Desktop स्थापित किया है, तो आपको Docker Desktop इंस्टॉलर द्वारा जोड़े गए एक `PATH` से पहले अपनी `PATH` प्रविष्टि डालने की आवश्यकता हो सकती है या Docker Desktop के `kubectl` को हटा दें।
```

2021-10-06 16:26 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +1. यह सुनिश्चित करने के लिए परीक्षण करें कि `kubectl` का समान संस्करण डाउनलोड के समान है:
```suggestion
1. यह सुनिश्चित करने के लिए परीक्षण करें कि `kubectl` संस्करण डाउनलोड के समान है:
```

2021-10-06 16:30 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +1. अपनी होम डायरेक्टरी पर नेविगेट करें:
```suggestion
1. अपनी होम डायरेक्टरी पर जाएं:
```

2021-10-06 16:32 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +   # If you're using cmd.exe, run: cd %USERPROFILE%
```suggestion
   # यदि आप cmd.exe का प्रयोग कर रहे हैं, तो: cd %USERPROFILE%
```

2021-10-06 16:33 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +1. आपके द्वारा अभी बनाई गई `.kube` डायरेक्टरी में बदलें:
```suggestion
1. आपके द्वारा अभी बनाई गई `.kube` डायरेक्टरी में जाएं:
```

2021-10-06 16:36 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +1. बाइनरी को मान्य करें (ऐच्छिक)
```suggestion
1. बाइनरी को मान्य करें (वैकल्पिक)
```

2021-10-06 16:37 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +1. कमांड के साथ नवीनतम रिलीज डाउनलोड करें:
```suggestion
1. इस कमांड से नवीनतम रिलीज डाउनलोड करें:
```

2021-10-06 16:41 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +   - मैन्युअल रूप से कमांड प्रॉम्प्ट का उपयोग करके `CertUtil` के आउटपुट की तुलना डाउनलोडेड चेकसम फ़ाइल से करें:
```suggestion
   - मैन्युअल रूप से कमांड प्रॉम्प्ट का उपयोग करके `CertUtil` के आउटपुट की तुलना डाउनलोड किये गये चेकसम फ़ाइल से करें:
```

2021-10-06 16:42 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/install-kubectl-windows.md
> +   - `True` या `False` परिणाम प्राप्त करने के लिए `-eq` ऑपरेटर का उपयोग करके सत्यापन को ऑटोमेट करने के लिए powershell का उपयोग करें:
```suggestion
   - `True` या `False` परिणाम प्राप्त करने और `-eq` ऑपरेटर का उपयोग करके सत्यापन को ऑटोमेट करने के लिए Powershell का उपयोग करें:
```

2021-10-06 17:03 UTC, vedant-kakde commented
Thanks for reviewing @anubha-v-ardhan 😄

2021-10-06 17:09 UTC, anubha-v-ardhan commented
/label tide/merge-method-squash

2021-10-06 17:12 UTC, merged