Add docs/tasks/tools/included/_index.md
kubernetes/website pull request #29473
Opened 2021-08-19 09:02 UTC by kaiwalyakoparkar

Localizes
- `content/hi/docs/tasks/tools/included/_index.md`

2021-08-19 09:08 UTC, kaiwalyakoparkar commented
This PR is in continuation of hi localization effort: #29353

/language hi

2021-08-19 09:18 UTC, anubha-v-ardhan requested changes

2021-08-19 09:18 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/_index.md
> +title: "उपकरण शामिल"
```suggestion
title: "शामिल उपकरण"
```

2021-08-19 09:18 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/_index.md
> +description: "Snippets to be included in the main kubectl-installs-*.md pages."
```suggestion
```

2021-08-19 09:19 UTC, anubha-v-ardhan commented
@kaiwalyakoparkar Thanks for contributing : )
Please sign the CLA so your PR can reviewed 
https://github.com/kubernetes/community/blob/master/CLA.md

2021-08-19 09:33 UTC, kaiwalyakoparkar commented
@anubha-v-ardhan I have signed the cla. It still shows that not passed. What should I do? :thinking:

2021-08-19 09:34 UTC, anubha-v-ardhan commented
> @anubha-v-ardhan I have signed the cla. It still shows that not passed. What should I do?

: D It takes some time to update. Look its `yes` now. Hurry

2021-08-19 09:53 UTC, anubha-v-ardhan approved these changes
LGTM

2021-08-20 08:35 UTC, anubha-v-ardhan commented
/retitle [hi] Add docs/tasks/tools/included/_index.md

2021-09-12 16:21 UTC, anubha-v-ardhan commented
@kaiwalyakoparkar Can you squash all the commits into one commit and change the base to `dev-1.22-hi.1`.
That should make this PR ready to merge.

2021-09-13 04:52 UTC, kaiwalyakoparkar commented
@anubha-v-ardhan Changes done as you asked for
-[ ] PR is open now
-[ ] Squashed all commits to one
-[ ] Changed the base to `dev-i.22-hi.1`

2021-09-13 05:00 UTC, anubha-v-ardhan commented
@kaiwalyakoparkar Seems like something went wrong and a few other commits commits not related to this PR have crept in. Can you fix it.

2021-09-13 05:25 UTC, kaiwalyakoparkar commented
@anubha-v-ardhan Oh... I will fix it soon

2021-09-13 06:02 UTC, kaiwalyakoparkar commented
@anubha-v-ardhan could you please check it now?

2021-09-13 06:11 UTC, anubha-v-ardhan commented
/remove-approve

2021-09-13 06:16 UTC, anubha-v-ardhan commented
The extra file changes are gone but the commits are still there, you can use `git reset --hard HEAD~<no. of commits>` and the force push using `git push --force` to remove unwanted commits.

2021-09-13 07:26 UTC, kaiwalyakoparkar commented
> The extra file changes are gone but the commits are still there, you can use `git reset --hard HEAD~<no. of commits>` and then force push using `git push --force` to remove unwanted commits.

Strange, I squashed them again :thinking:

2021-09-13 07:28 UTC, anubha-v-ardhan commented
You need to rebase it too i guess

2021-09-13 09:15 UTC, kaiwalyakoparkar commented
> You need to rebase it too i guess

Umm.. I tried a couple of things but that doesn't seem to work. Do you have any suggestions on how I can do that?
At my end, the commit log looks like this
<img src="https://i.imgur.com/Mxm8LKn.png">

2021-09-13 09:34 UTC, verma-kunal commented
> > You need to rebase it too i guess
> 
> Umm.. I tried a couple of things but that doesn't seem to work. Do you have any suggestions on how I can do that?
> At my end, the commit log looks like this
> ![](https://camo.githubusercontent.com/b62f332742edf1d9d526166af8bf2165385bb8d751c6221cc30323464d00898f/68747470733a2f2f692e696d6775722e636f6d2f4d786d384c4b6e2e706e67)

Hey @kaiwalyakoparkar , this is the last commit in this branch, right?

2021-09-13 09:49 UTC, kaiwalyakoparkar commented
> > > You need to rebase it too i guess
> > 
> > 
> > Umm.. I tried a couple of things but that doesn't seem to work. Do you have any suggestions on how I can do that?
> > At my end, the commit log looks like this
> > ![](https://camo.githubusercontent.com/b62f332742edf1d9d526166af8bf2165385bb8d751c6221cc30323464d00898f/68747470733a2f2f692e696d6775722e636f6d2f4d786d384c4b6e2e706e67)
> 
> Hey @kaiwalyakoparkar , this is the last commit in this branch, right?

I hope it is

2021-09-13 09:52 UTC, verma-kunal commented
> > > > You need to rebase it too i guess
> > > 
> > > 
> > > Umm.. I tried a couple of things but that doesn't seem to work. Do you have any suggestions on how I can do that?
> > > At my end, the commit log looks like this
> > > ![](https://camo.githubusercontent.com/b62f332742edf1d9d526166af8bf2165385bb8d751c6221cc30323464d00898f/68747470733a2f2f692e696d6775722e636f6d2f4d786d384c4b6e2e706e67)
> > 
> > 
> > Hey @kaiwalyakoparkar , this is the last commit in this branch, right?
> 
> I hope it is

I followed this approach:
- [ ] git rebase -i <commit id of the last commit (you want all commits above this to be squashed)>
- [ ] replacing all the 'pick' with 's' option (except the 1st one, in which all the commit would be merged)
- [ ] esc + `:x`
- [ ] write a final commit message!!
- [ ] esc + `:x`
- [ ] git push --force-with-lease origin <your-branch-name>

did you this in this way?

2021-09-13 09:53 UTC, verma-kunal commented
i think so too!! this was your last commit
so, commit id below this one should be good iguess

![Screenshot 2021-09-13 at 3 22 58 PM](https://user-images.githubusercontent.com/72245772/133063518-702555ca-190d-4f39-a637-a49a023d6017.png)

2021-09-13 10:14 UTC, kaiwalyakoparkar commented
> * [ ]  git rebase -i <commit id of the last commit (you want all commits above this to be squashed)>
> * [ ]  replacing all the 'pick' with 's' option (except the 1st one, in which all the commit would be merged)
> * [ ]  esc + `:x`
> * [ ]  write a final commit message!!
> * [ ]  esc + `:x`
> * [ ]  git push --force-with-lease origin `your-branch-name`
> 
> did you this in this way?

I will try this

2021-09-13 11:59 UTC, kaiwalyakoparkar commented
@anubha-v-ardhan I tried a couple of techniques. Can you squash them while merging?

2021-09-13 12:17 UTC, verma-kunal commented
> @anubha-v-ardhan I tried a couple of techniques. Can you squash them while merging?

@anubha-v-ardhan , i think there might have been some error while squashing!! So maybe we cab use the `label`, which was suggested by @sftim 

What do you think?

2021-09-13 12:22 UTC, anubha-v-ardhan commented
the squash was successfull but few commits here are not related to this PR, @kaiwalyakoparkar Did you fetch and merged `kubernetes:main` to `kaiwalyakoparkar:docs/tasks/tools/included/_index.md`?

2021-09-13 12:32 UTC, sftim commented
> commit id of the last commit

You can use your shell and Git to work out the right place to rebase automatically:
```bash
git rebase -i "$( git merge-base HEAD dev-1.22-hi.1 )"
```

To _fix_ this PR, do that and also change `pick` to `drop` for all the unwanted commits.

2021-09-13 12:33 UTC, anubha-v-ardhan commented
The commits are not related to this PR and shouldn't be here.
@kaiwalyakoparkar Did you rebased against local `main` instead of `dev-1.22-hi.1`?

2021-09-13 12:47 UTC, kaiwalyakoparkar commented
> The commits are not related to this PR and shouldn't be here.
> @kaiwalyakoparkar Did you rebase against local `main` instead of `dev-1.22-hi.1`?

Unfortunately yes

2021-09-13 12:55 UTC, verma-kunal commented
> The commits are not related to this PR and shouldn't be here.
> @kaiwalyakoparkar Did you rebase against local `main` instead of `dev-1.22-hi.1`?

🤔 even i don't remember changing anything like this!!

2021-09-13 12:58 UTC, kaiwalyakoparkar commented
Closing this PR to open a new one due to rebasing issues
cc: @sftim @anubha-v-ardhan

2021-09-13 12:58 UTC, closed without merging

2021-09-13 13:19 UTC, anubha-v-ardhan commented
Thank you, Do tag the tracking issue in new PR.

2021-09-13 13:38 UTC, verma-kunal commented
here is the tracking issue: https://github.com/kubernetes/website/issues/29353