Add content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
kubernetes/website pull request #29474
Opened 2021-08-19 10:25 UTC by vedant-kakde

Localizes :

- `content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md`

2021-08-19 10:25 UTC, vedant-kakde commented
This PR is in continuation of hi localization effort: #29353

/language hi

2021-08-19 15:38 UTC, kaiwalyakoparkar requested changes
This sounds more appropriate. What do you think about this?

2021-08-19 15:38 UTC, kaiwalyakoparkar commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +अपने शेल को पुनः लोड करने के बाद, kubectl ऑटो-कम्पलीशन कार्य करना चाहिए.
```diff
- अपने शेल को पुनः लोड करने के बाद, kubectl ऑटो-कम्पलीशन कार्य करना चाहिए.
+ अपने शेल को पुनः शुरू  करने के बाद, kubectl ऑटो-कम्पलीशन कार्य करना चाहिए.
```

2021-08-20 08:34 UTC, anubha-v-ardhan commented
/retitle [hi] Add content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md

2021-09-13 10:18 UTC, anubha-v-ardhan requested changes

2021-09-13 10:18 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +description: "zsh ऑटो-कम्पलीशन के लिए कुछ वैकल्पिक कॉन्फ़िगरेशन|"
```suggestion
description: "zsh ऑटो-कम्पलीशन के लिए कुछ वैकल्पिक कॉन्फ़िगरेशन।"
```

2021-09-13 10:18 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +description: "zsh ऑटो-कम्पलीशन के लिए कुछ वैकल्पिक कॉन्फ़िगरेशन|"
Please note that `।` and `|` are not the same character and we should use `।` ideally.

2021-09-13 10:18 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +Zsh के लिए kubectl कम्पलीशन स्क्रिप्ट `kubectl completion zsh` कमांड के साथ उत्पन्न की जा सकती है। आपके शेल में कम्पलीशन स्क्रिप्ट को सोर्स करने से kubectl ऑटो-कम्पलीशन सक्षम हो जाती है|
```suggestion
Zsh के लिए kubectl कम्पलीशन स्क्रिप्ट `kubectl completion zsh` कमांड के साथ उत्पन्न की जा सकती है। आपके शेल में कम्पलीशन स्क्रिप्ट को सोर्स करने से kubectl ऑटो-कम्पलीशन सक्षम हो जाती है।
```

2021-09-13 10:18 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +अपने शेल को पुनः लोड करने के बाद, kubectl ऑटो-कम्पलीशन कार्य करना चाहिए.
```suggestion
अपने शेल को पुनः लोड करने के बाद, kubectl ऑटो-कम्पलीशन कार्य करना चाहिए।
```

2021-09-13 10:18 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +अगर आपको कोई त्रुटि मिलती है जैसे `complete:13: command not found: compdef`, फिर अपनी `~/.zshrc` फ़ाइल की शुरुआत में निम्नलिखित जोड़ें:
```suggestion
यदि आपको कोई त्रुटि मिलती है जैसे `complete:13: command not found: compdef`, तो अपनी `~/.zshrc` फ़ाइल की शुरुआत में निम्नलिखित जोड़ें:
```

2021-09-13 10:37 UTC, vedant-kakde commented
Done ✅

2021-09-13 10:37 UTC, anubha-v-ardhan commented
/lgtm
/approve

Thank you @vedant-kakde :)

2021-09-13 10:38 UTC, merged