Recommend using TTL field in job
kubernetes/website pull request #29478
Opened 2021-08-19 21:00 UTC by ravisantoshgudimetla

Recommend using ttlSecondsAfterFinished in the job spec so that the pod deletion can be guaranteed when jobs get deleted.

cc @liggit @soltysh

2021-08-20 13:21 UTC, sftim commented
/sig apps

2021-09-03 20:54 UTC, geoffcline requested changes
I think we should have a short warning alerting users to this behavior. 

> {{< warning >}}
> Unmanaged jobs (jobs not created via high level controllers like cronjobs) have
> a default deletion policy of `orphanDependents`. Under this policy, when a job
> is deleted, the associated pods are not deleted. 
> {{< /warning >}}
> 
> It is recommended to set `ttlSecondsAfterFinished` field to reduce orphaned pods. 
> 
> Even though [podgc](add link?) collector eventually deletes these lingering
> pods, lingering pods may reduce cluster performance. 
>

2021-09-25 00:09 UTC, sftim commented on content/en/docs/concepts/workloads/controllers/job.md
> +(jobs not created via high level controllers like cronjobs) have a default deletion
```suggestion
(Jobs that you created directly, and not indirectly through other workload APIs
such as CronJob) have a default deletion
```

2021-09-25 00:09 UTC, sftim commented on content/en/docs/concepts/workloads/controllers/job.md
> +policy of `orphanDependents` causing pods created by this job to be left around.
```suggestion
policy of `orphanDependents` causing Pods created by an unmanaged Job to be left around
after that Job is fully deleted.
```

2021-09-25 00:09 UTC, sftim commented on content/en/docs/concepts/workloads/controllers/job.md
> +Even though podgc collector eventually deletes these lingering pods, sometimes these
```suggestion
Even though the {{< glossary_tooltip text="control plane" term_id="control-plane" >}} eventually
[garbage collects](/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection)
the Pods from a deleted Job after they either fail or complete, sometimes those
```

2021-09-25 00:09 UTC, sftim commented on content/en/docs/concepts/workloads/controllers/job.md
> +cluster to go down.
```suggestion
cluster to go offline due to this degradation.

You can use [LimitRanges](/docs/concepts/policy/limit-range/) and
[ResourceQuotas](/docs/concepts/policy/resource-quotas/) to place a
cap on the amount of resources that a particular namespace can
consume.
```
?

2021-09-25 00:10 UTC, sftim commented
@kubernetes/sig-apps-misc how does this PR look to you?

2021-09-30 00:09 UTC, kbhawkey commented
Page preview:
https://deploy-preview-29478--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs

2021-09-30 00:19 UTC, kbhawkey commented
Hi @ravisantoshgudimetla .
Thanks for contributing. I think the note could use a couple of edits, otherwise the changes look good.
What do you think about the suggestions and comments?

2021-11-19 12:15 UTC, sftim reviewed
/approve

2021-11-19 12:16 UTC, merged