[hi] [Add/Update/Fix] [content/hi/docs/setup/production-environment/w…
kubernetes/website pull request #29493
Opened 2021-08-20 15:25 UTC by arsheelsheikh

Localizes

- `content/en/docs/setup/production-environment/windows/user-guide-windows-containers.md`

2021-08-20 15:28 UTC, arsheelsheikh commented
This PR is in continuation of hi localization effort: #29353

/language hi

2021-08-20 17:13 UTC, arsheelsheikh commented
@anubha-v-ardhan

2021-08-20 17:22 UTC, anubha-v-ardhan commented
/retitle [hi] Add content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md

2021-08-20 17:24 UTC, anubha-v-ardhan requested changes
Initial review

2021-08-20 17:24 UTC, anubha-v-ardhan commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +- perithompson
```suggestion
```

2021-08-20 17:24 UTC, anubha-v-ardhan commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +## उद्देश्यों
```suggestion
## उद्देश्य
```

2021-08-20 17:26 UTC, anubha-v-ardhan commented
Can you please sign the CLA so that your PR can be reviewed : )
https://github.com/kubernetes/community/blob/master/CLA.md

2021-08-20 17:46 UTC, vedant-kakde requested changes

2021-08-21 11:42 UTC, kaiwalyakoparkar commented
@arsheelsheikh Could you please convert this PR into draft PR please?

2021-08-21 15:45 UTC, arsheelsheikh commented
> @arsheelsheikh Could you please convert this PR into draft PR please?

Thanks, Done.

2021-08-22 10:03 UTC, Arhell reviewed
/check-cla

2021-08-23 08:58 UTC, arsheelsheikh commented
"I signed it"

2021-08-23 09:17 UTC, anubha-v-ardhan commented
/check-cla

2021-08-23 10:48 UTC, vedant-kakde requested changes

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +* एक कुबेरनेट्स क्लस्टर बनाएं जिसमें शामिल है a
```suggestion
* एक कुबेरनेट्स क्लस्टर बनाएं जिसमें
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +नियंत्रण विमान और [worker node running Windows Server](/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/)
```suggestion
नियंत्रण विमान और [worker node running Windows Server](/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/) शामिल है |
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +[Kubectl commands](/docs/reference/kubectl/overview/) क्लस्टर के साथ इंटरफेस करने के लिए समान हैं।
```suggestion
[kubectl commands](/docs/reference/kubectl/overview/) क्लस्टर के साथ इंटरफेस करने के लिए समान हैं।
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +विंडोज कंटेनर के साथ अपने अनुभव को जम्पस्टार्ट करने के लिए नीचे दिए गए अनुभाग में उदाहरण दिया गया है।
```suggestion
Windows कंटेनर के साथ अपने अनुभव को जम्पस्टार्ट करने के लिए नीचे दिए गए अनुभाग में उदाहरण दिया गया है।
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +    * विंडोज नोड पर प्रति पॉड दो कंटेनर, उपयोग करें `docker ps`
```suggestion
    * Windows नोड पर प्रति पॉड दो कंटेनर, उपयोग करें `docker ps` 
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +कार्यभार के परिचालन पहलू में और समस्याओं के निवारण के लिए एक प्रमुख घटक हैं।
```suggestion
वर्कलोड के परिचालन पहलू में और समस्याओं के निवारण के लिए एक प्रमुख घटक हैं।
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +उदाहरण के लिए विंडोज वर्कलोड आमतौर पर ETW (Event Tracing for Window) में लॉग इन करने के लिए कॉन्फ़िगर किया गया है।
```suggestion
उदाहरण के लिए Windows वर्कलोड आमतौर पर ETW (Event Tracing for Window) में लॉग इन करने के लिए कॉन्फ़िगर किया गया है।
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +विंडोज कंटेनर के अंदर कॉन्फ़िगर किए गए लॉग स्रोतों की निगरानी के लिए अनुशंसित तरीका है।
```suggestion
Windows कंटेनर के अंदर कॉन्फ़िगर किए गए लॉग स्रोतों की निगरानी के लिए अनुशंसित तरीका है।
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +कुबेरनेट्स v1.16 से शुरू होकर, विंडोज कंटेनरों को उनके प्रवेश बिंदुओं और प्रक्रियाओं को चलाने के लिए कॉन्फ़िगर किया जा सकता है
```suggestion
कुबेरनेट्स v1.16 से शुरू होकर, Windows कंटेनरों को उनके प्रवेश बिंदुओं और प्रक्रियाओं को चलाने के लिए कॉन्फ़िगर किया जा सकता है
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +इसके बारे में और जानें [यहां](/docs/tasks/configure-pod-container/configure-runasusername/).
```suggestion
इसके बारे में और [यहां](/docs/tasks/configure-pod-container/configure-runasusername/) जानें|
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +Windows कंटेनरों के लिए जीएमएसए को कॉन्फ़िगर करने और उपयोग करने के बारे में और जानें [यहां](/docs/tasks/configure-pod-container/configure-gmsa/).
```suggestion
Windows कंटेनरों के लिए जीएमएसए को कॉन्फ़िगर करने और उपयोग करने के बारे में और [यहां](/docs/tasks/configure-pod-container/configure-gmsa/) जानें|
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +विंडोज पॉड को विंडोज नोड पर शेड्यूल करने के लिए,
```suggestion
Windows पॉड को Windows नोड पर शेड्यूल करने के लिए,
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +प्रत्येक पॉड द्वारा उपयोग किया जाने वाला विंडोज सर्वर संस्करण नोड से मेल खाना चाहिए। यदि आप एकाधिक Windows का उपयोग करना चाहते हैं
```suggestion
प्रत्येक पॉड द्वारा उपयोग किया जाने वाला Windows सर्वर संस्करण नोड से मेल खाना चाहिए। यदि आप एकाधिक Windows का उपयोग करना चाहते हैं
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +यह लेबल विंडोज मेजर, माइनर और बिल्ड नंबर को दर्शाता है जिसे संगतता के लिए मिलान करने की आवश्यकता होती है।
```suggestion
यह लेबल Windows मेजर, माइनर और बिल्ड नंबर को दर्शाता है जिसे संगतता के लिए मिलान करने की आवश्यकता होती है।
```

2021-08-23 10:48 UTC, vedant-kakde commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +विंडोज ओएस, आर्किटेक्चर और वर्जन के लिए।
```suggestion
Windows OS, आर्किटेक्चर और वर्जन के लिए।
```

2021-08-25 04:41 UTC, rajatgupta24 requested changes

2021-08-25 04:41 UTC, rajatgupta24 commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +विंडोज ओएस, आर्किटेक्चर और वर्जन के लिए।
We are using `संस्करण` for `वर्जन`

2021-08-25 04:41 UTC, rajatgupta24 commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +Linux और विंडोज वर्कलोड को उनके संबंधित ओएस-विशिष्ट नोड्स पर रखें।
```suggestion
Linux और Windows वर्कलोड को उनके संबंधित ओएस-विशिष्ट नोड्स पर रखें।
```

2021-08-25 04:41 UTC, rajatgupta24 commented on content/hi/docs/setup/production-environment/windows/user-guide-windows-containers.md
> +इसका एक मुख्य लक्ष्य यह है कि यह दृष्टिकोण मौजूदा Linux वर्कलोड के लिए अनुकूलता को नहीं तोड़ना चाहिए।
```suggestion
इसका एक मुख्य लक्ष्य यह है कि यह दृष्टिकोण का मौजूदा Linux वर्कलोड की अनुकूलता को ना तोडे।
```

2021-09-02 03:13 UTC, RA489 commented
/check-cla

2021-09-02 08:19 UTC, RA489 commented
@arsheelsheikh your commits are linked to another user. Please fix that.

2021-09-02 08:20 UTC, RA489 commented
you may need to change your local Git configuration settings.

2021-09-07 10:14 UTC, keshavcodex commented
/check-cla

2021-09-07 10:17 UTC, keshavcodex commented
/check-cla

2021-09-07 10:41 UTC, keshavcodex commented
/check-cla

2021-09-13 07:52 UTC, closed without merging

2022-04-07 03:02 UTC, jihoon-seo commented
/remove-area blog release-eng
/remove-language en es id ja ko pt ru zh
/remove-sig release