Update README-hi.md
kubernetes/website pull request #29521
Opened 2021-08-24 14:36 UTC by AvineshTripathi

restructured a sentence 
fixed #29519

2021-08-24 14:37 UTC, anubha-v-ardhan commented
/language hi
/retitle [hi] Update README-hi.md

2021-08-24 14:40 UTC, anubha-v-ardhan requested changes

2021-08-24 14:40 UTC, anubha-v-ardhan commented on README-hi.md
> +आप अपने GitHub खाते में इस रिपॉजिटरी की एक copy बनाने के लिए स्क्रीन के ऊपरी-दाएँ क्षेत्र में **Fork** बटन पर क्लिक करें। इस copy को *Fork* कहा जाता है। अपने fork के परिवर्तन करने के बाद जब आप उनको ह
```suggestion
आप अपने GitHub खाते में इस रिपॉजिटरी की एक copy बनाने के लिए स्क्रीन के ऊपरी-दाएँ क्षेत्र में **Fork** बटन पर क्लिक करें। इस copy को *Fork* कहा जाता है। अपने fork में परिवर्तन करने के बाद जब आप उनको हमारे पास भेजने के लिए तैयार हों, तो अपने fork पर जाएं और हमें इसके बारे में बताने के लिए एक नया pull request बनाएं।
```

2021-08-24 14:43 UTC, anubha-v-ardhan commented on README-hi.md
> +आप अपने GitHub खाते में इस रिपॉजिटरी की एक copy बनाने के लिए स्क्रीन के ऊपरी-दाएँ क्षेत्र में **Fork** बटन पर क्लिक करें। इस copy को *Fork* कहा जाता है। अपने fork के परिवर्तन करने के बाद जब आप उनको ह
Grammatical mistakes and missing `।`

2021-08-24 14:45 UTC, anubha-v-ardhan approved these changes
LGTM

2021-09-08 13:59 UTC, AvineshTripathi commented
@divya-mohan0209 sure

2021-09-09 10:20 UTC, sftim commented
It looks like you'd want to omit the second commit here @AvineshTripathi

2021-09-09 10:46 UTC, AvineshTripathi commented
> It looks like you'd want to omit the second commit here @AvineshTripathi

yes if there is something still left to do please let me know @sftim

2021-09-12 16:50 UTC, sftim commented
The squash _here_ is wrong because the second commit reverts the first commit.

2021-09-13 17:25 UTC, AvineshTripathi commented
@sftim is it now fine ?

2021-09-15 04:47 UTC, divya-mohan0209 commented
@AvineshTripathi I can see 5 commits at this point on this PR. Please can you check the guide - https://kubernetes.io/docs/contribute/new-content/open-a-pr/ & squash + merge it correctly?

2021-09-15 04:53 UTC, AvineshTripathi commented
@divya-mohan0209 I want the lastest commit to be merged and I am not able to remove the other 4 commits can you help me for that

2021-09-15 05:02 UTC, divya-mohan0209 commented
> @divya-mohan0209 I want the lastest commit to be merged and I am not able to remove the other 4 commits can you help me for that also I my git log I have removed the other 4 but still it is showing

You need to add, rebase, & then force push the content. Please check your Slack DM.

2021-09-28 03:24 UTC, anubha-v-ardhan commented
@AvineshTripathi Are you still working on this PR. Can we have an update.

2021-09-28 03:39 UTC, AvineshTripathi commented
@anubha-v-ardhan thank you for asking me I have sent you a message in slack do see it

2021-09-28 04:15 UTC, closed without merging

2021-09-28 04:16 UTC, AvineshTripathi commented
there were branch conflicts therefore had to close this opening a new PR for the same