docs: Add "KubeOps" operator SDK to third-party list
kubernetes/website pull request #29529
Opened 2021-08-25 07:34 UTC by buehler

Adding dotnet operator SDK/framework to third-party list of operator SDKs.

2021-08-25 09:23 UTC, sftim requested changes
Thanks for suggesting this @buehler 

When we add items to _this_ list, we should keep the existing sorting (alphabetical order). Would you be willing to revise this to get the ordering right?

2021-08-25 09:24 UTC, buehler commented
Of course! I did not get the ordering, I thought it was by date added.

2021-08-25 09:25 UTC, buehler commented
@sftim done

2021-09-01 19:48 UTC, reylejano commented
Thanks for fixing the order
/lgtm

2021-09-02 16:24 UTC, celestehorgan commented on content/en/docs/concepts/extend-kubernetes/operator.md
> +* [KubeOps](https://buehler.github.io/dotnet-operator-sdk/) (dotnet operator SDK)
Small, non-blocking change: dotnet --> .NET

2021-09-02 16:25 UTC, celestehorgan commented
/approve

2021-09-02 16:26 UTC, merged

2021-09-08 00:01 UTC, reylejano commented
Follow-up PR https://github.com/kubernetes/website/pull/29637 to address [nit](https://github.com/kubernetes/website/pull/29529#discussion_r701241597) of dotnet --> .NET