fix kubelet Eviction thresholds
kubernetes/website pull request #29582
Opened 2021-08-29 15:00 UTC by zwwhdls

Fix usage of kubelet Eviction thresholds in KubeletConfiguration recording to 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/config/types.go#L291

2021-08-30 02:36 UTC, kbhawkey commented
👋 @zwwhdls . Thanks for the contribution.
Would you break up this pull request into multiple PRs? A pull request should only contain changes from one language or localization.

2021-08-30 02:51 UTC, zwwhdls commented
@kbhawkey done

2021-08-31 15:50 UTC, shannonxtreme requested changes
Some edits for clarity (and to remove curly braces). Also needs more information on the `--eviction-hard` flag's value

2021-08-31 15:50 UTC, shannonxtreme commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +Eviction thresholds is formed as `map[string]string`, where:
```suggestion
Eviction thresholds are key-value pairs with the form `[eviction-signal]: [quantity]` where:
```

2021-08-31 15:50 UTC, shannonxtreme commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +* value is the eviction threshold amount, such as `1Gi`. The value of `quantity`
```suggestion
* `eviction-signal` is the [eviction signal](#eviction-signals) to use.
* `quantity` is the eviction threshold amount, such as `1Gi`. The value of `quantity`
```

2021-08-31 15:50 UTC, shannonxtreme commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +either `{"memory.available": "10%"}` or `{"memory.available": "1Gi"}`. You cannot use both.
```suggestion
either `"memory.available": "10%"` or `"memory.available": "1Gi"`. You cannot use both.
```

2021-08-31 15:50 UTC, shannonxtreme commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +* `eviction-soft`: A set of eviction thresholds like `{"memory.available": "1.5Gi"}`
```suggestion
* `eviction-soft`: A set of eviction thresholds like `"memory.available": "1.5Gi"`
```

2021-08-31 15:50 UTC, shannonxtreme commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +thresholds like `{"memory.available": "1Gi"}`.
```suggestion
thresholds like `"memory.available": "1Gi"`.
```

2021-08-31 15:50 UTC, shannonxtreme commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +* `{"nodefs.inodesFree": "5%"}` (Linux nodes)
```suggestion
* `"memory.available": "100Mi"`
* `"nodefs.available": "10%"`
* `"imagefs.available": "15%"`
* `"nodefs.inodesFree": "5%"` (Linux nodes)
```

2021-08-31 15:50 UTC, shannonxtreme commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +--eviction-hard={"memory.available": "500Mi"}
I'm not sure this would work. Shouldn't the value for the flag in the command be something like `--eviction-hard=memory-available=500Mi`?

2021-09-01 08:29 UTC, zwwhdls commented
Hi @shannonxtreme , I studied kubelet code carefully and found that I had make a mistake.

According to the [flag definition](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L531), function `cliflag.NewLangleSeparatedMapStringString` will set map to string formed as "a<b".

I will close this PR, thanks all.

2021-09-01 08:29 UTC, closed without merging