[WIP] gRPC probes support (KEP 2727)
kubernetes/website pull request #29740
Opened 2021-09-17 20:38 UTC by SergeyKanzhelev

https://github.com/kubernetes/enhancements/issues/2727

/sig node
/hold

2021-09-17 21:52 UTC, jlbutler commented
/assign

2021-11-22 19:57 UTC, jlbutler commented
@SergeyKanzhelev Reminder that tomorrow Nov 23rd is the deadline for 1.23 Docs Ready for Review. Please push your docs content for this enhancement and remove the work-in-progress label when ready for review.

We have a tight turnaround to getting docs reviewed and approved for the release, and we’re hoping to have all docs in for review by EOB tomorrow. Thank you!

2021-11-28 19:11 UTC, sftim commented
Hi @SergeyKanzhelev 

Would you be willing to revise this to be ready for review?

2021-11-29 23:53 UTC, SergeyKanzhelev commented
> Hi @SergeyKanzhelev
> 
> Would you be willing to revise this to be ready for review?

I'm still working on validating yaml. some issues setting up 1.23 environment. But facts-wise, ready for review

2021-11-30 15:19 UTC, jlbutler requested changes
Thanks for getting this in! Suggested some wording/nits.

2021-11-30 15:19 UTC, jlbutler commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +Configuration problems - incorrect port and service, or not implemented health
suggestion:  "Configuration problems (e.g. incorrect port and service, unimplemented health checking protocol) are considered a probe failure, similar to HTTP and TCP probes."

2021-11-30 15:19 UTC, jlbutler commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +like described in the blog post [Health checking gRPC servers on Kubernetes](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/).
nit "as described"

2021-11-30 15:19 UTC, jlbutler commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +
nit, capitalize first letter in each of the bulleted items

2021-11-30 15:19 UTC, jlbutler commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +To try the gRPC liveness check, create a Pod:
maybe flip these two sentences for clarity? e.g. "To try the gRPC liveness check, create a Pod. In this example, the etcd pod is configured to use the liveness probe."

2021-11-30 15:19 UTC, jlbutler commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +After 15 seconds, view Pod events to verify that liveness probes run:
"...to verify that the liveness probes have run"

2021-11-30 19:29 UTC, SergeyKanzhelev commented on content/en/blog/_posts/2018-10-01-health-checking-grpc.md
> +_Since this article publication, in Kubernetes 1.23, built-in gRPC probes
Example: https://kubernetes.io/blog/2016/11/visualize-kubelet-performance-with-node-dashboard/

I think it is a big benefit for end users to add those notes and save some time for readers.

2021-11-30 19:31 UTC, SergeyKanzhelev commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ControllerManagerLeaderMigration`: Enables Leader Migration for
this is my auto-formatter for md files. lmk if this is critical and I will fix it back

2021-11-30 19:43 UTC, jlbutler commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +- `ControllerManagerLeaderMigration`: Enables Leader Migration for
No, fine by me.

2021-11-30 19:48 UTC, jlbutler commented
/lgtm

2021-11-30 22:37 UTC, mrunalp commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +- There is no error codes in built-in probes. All errors are considered a probe failures.
There are no error codes in built-in probes. All errors are considered as probe failures.

2021-11-30 22:38 UTC, mrunalp commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +To try the gRPC liveness check, create a Pod using command below.
using the command

2021-11-30 22:39 UTC, mrunalp commented
I left a couple of nits. Otherwise
/lgtm

2021-11-30 23:38 UTC, SergeyKanzhelev commented
addressed @mrunalp's comments. Also added a small note. This is ready for merge

2021-11-30 23:47 UTC, mrunalp commented
/lgtm

2021-12-01 00:00 UTC, jlbutler commented
/lgtm
/approve

2021-12-01 00:09 UTC, jlbutler commented
/remove-hold

2021-12-01 00:09 UTC, merged

2021-12-03 00:40 UTC, sftim commented on content/en/blog/_posts/2018-10-01-health-checking-grpc.md
> +_Built-in gRPC probes were introduced in Kubernetes 1.23. To learn more, see [Configure Liveness, Readiness and Startup Probes](/docs/tasks/configure-pod-container/configure-liveness-readiness-startu
Nice tweak.