[pt-br] Adding translation of ports and protocols page
kubernetes/website pull request #29790
Opened 2021-09-23 19:15 UTC by MarcosNBJ

# Changes
* Brazilian portuguese translation of the [Ports And Protocols](https://kubernetes.io/docs/reference/ports-and-protocols/) page.

## Required steps
- [x] Content translated 
- [x] Links to other pages with translations updated 
## Related Issue
#13939

2021-09-30 16:53 UTC, devlware commented
Sorry for the late reply @MarcosNBJ, I'll review later today!

2021-10-05 13:27 UTC, devlware requested changes
Left some comments Marcos.

2021-10-05 13:27 UTC, devlware commented on content/pt-br/docs/reference/ports-and-protocols.md
> +| Protocol | Direction | Port Range | Purpose                 | Used By                   |
@MarcosNBJ Maybe we should translate the description names of each column.

2021-10-05 13:27 UTC, devlware commented on content/pt-br/docs/reference/ports-and-protocols.md
> +Embora as portas do etcd estjam inclusas na secção da Camada de gerenciamento, você também
```suggestion
Embora as portas do etcd estejam inclusas na secção da Camada de gerenciamento, você também 

```

2021-10-05 13:27 UTC, devlware commented on content/pt-br/docs/reference/ports-and-protocols.md
> +| Protocol | Direction | Port Range  | Purpose               | Used By                 |
Same comment here on the column names.

2021-11-02 08:39 UTC, MarcosNBJ commented on content/pt-br/docs/reference/ports-and-protocols.md
> +Embora as portas do etcd estejam inclusas na secção da Camada de gerenciamento, você também
Woops. Nice catch. Fixed

2021-11-02 11:46 UTC, edsoncelio commented
/lgtm

2021-11-02 11:58 UTC, edsoncelio commented
@devlware this PR is done for merge (i think), could you take a look please?

2021-11-02 22:17 UTC, devlware commented
/lgtm

2021-11-02 22:18 UTC, devlware commented
/approve

2021-11-02 22:19 UTC, merged