Tweak scroll behavior for narrow viewports
kubernetes/website pull request #29910
Opened 2021-10-03 17:24 UTC by sftim

This change means that when the viewport is narrow, scrolling to (or navigating to) a fragment doesn't put the top of the actual target fragment behind the top nav.

/area web-development

Fixes #29909

2021-10-09 13:56 UTC, niteshseram reviewed
I think this approach is not solving the issue. It is still going under the header. And the header disappears when we scroll down and the menu button is gone from the header.

2021-10-10 02:38 UTC, niteshseram commented
> OK, let me try some more.
> 
> I'd be very happy to see someone else fix this. Ideally: with only CSS changes.
> 
> /retitle [WIP] Tweak scroll behavior for narrow viewports

I tried with jQuery and it worked. With CSS, I tried many ways to solved it but didn't work. Will have a look again with CSS only.

2021-10-10 12:38 UTC, niteshseram requested changes

2021-10-10 12:38 UTC, niteshseram commented on assets/scss/_custom.scss
> +
```suggestion
html {
  @media only screen and (max-width: 768px) {
    scroll-padding-top: 5rem;
  }
  @media only screen and (max-width: 1024px) {
    scroll-padding-top: 4rem;
  }
}
```

Somehow adding the padding to the body doesn't have any effect. With HTML, it works. This solution seems to works.

2021-10-10 12:49 UTC, niteshseram commented
> With those changes @niteshseram I can still replicate the symptoms (which is annoying, but that's how it is).

Did you try locally because Netlify hasn't deployed the latest changes yet. In my local, it is working fine.

2021-10-10 12:51 UTC, niteshseram commented
If all these don't work with CSS, we can give it a try with jQuery once.

2021-10-10 13:02 UTC, sftim commented
With those changes @niteshseram I can still replicate the symptoms (which is annoying, but that's how it is). The changes improve things from the status quo though.

I will take another look later / hope to so do.

2021-10-10 13:03 UTC, niteshseram commented
> With those changes @niteshseram I can still replicate the symptoms (which is annoying, but that's how it is). The changes improve things from the status quo though.
> 
> I will take another look later / hope to so do.

Sure

2021-12-05 22:45 UTC, jimangel commented
@sftim is this still WIP? If not, do we want to get it in as-is and open an issue?

2021-12-05 22:47 UTC, sftim commented
I don't think I found the right fix. I might just close this one, leaving the branch in place.

/close

2021-12-05 22:47 UTC, closed without merging