[hi] Add content\hi\docs\setup\best-practices\enforcing-pod-security-standards.md
kubernetes/website pull request #29967
Opened 2021-10-08 06:33 UTC by ShivamTyagi12345

In continuation to issue https://github.com/kubernetes/website/pull/29414

Localizes content\en\docs\setup\best-practices\enforcing-pod-security-standards.md to hindi
@mittalyashu @anubha-v-ardhan

2021-10-09 20:11 UTC, anubha-v-ardhan requested changes

2021-10-09 20:11 UTC, anubha-v-ardhan commented on content/hi/docs/setup/best-practices/enforcing-pod-security-standards.md
> +- liggitt
```suggestion
```

2021-10-30 13:36 UTC, ShivamTyagi12345 commented
hey @anubha-v-ardhan ,Must have missed your attention. Do I need to make any changes? I think its ready to be merged

2022-01-15 08:11 UTC, jayesh-srivastava requested changes
Line 38 and 39 : This sentence should be framed as : 
`पॉड सुरक्षा मानक प्रवेश नियंत्रक के `audit` और `warn` मोड, मौजूदा वर्कलोड को तोड़े बिना पॉड्स के बारे में महत्वपूर्ण सुरक्षा अंतर्दृष्टि एकत्र करना, आसान बनाते हैं।`

2022-04-15 10:28 UTC, anubha-v-ardhan commented
/remove-lifecycle stale

2022-07-04 05:00 UTC, divya-mohan0209 commented
@ShivamTyagi12345 : Please could you work on the changes suggested by Jayesh above?

2022-07-28 11:41 UTC, divya-mohan0209 commented
Hello @ShivamTyagi12345 , please reopen the PR when you're ready to work on the suggestions

2022-07-28 11:41 UTC, divya-mohan0209 commented
/close

2022-07-28 11:42 UTC, closed without merging