[zh] Concept files to sync for 1.22 - task13 - k8s Extension
kubernetes/website pull request #29984
Opened 2021-10-08 15:35 UTC by superleo

https://github.com/kubernetes/website/issues/29325

(13) k8s Extension
11 2 content/zh/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
2 2 content/zh/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
3 3 content/zh/docs/concepts/extend-kubernetes/operator.md

2021-10-09 03:03 UTC, howieyuen requested changes

2021-10-09 03:06 UTC, howieyuen requested changes

2021-10-09 03:06 UTC, howieyuen commented on content/zh/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
> +这里的附加 API 可以是现成的解决方案比如[指标服务器（metrics server）](https://github.com/kubernetes-sigs/metrics-server), 或者你自己开发的 API.
这里的附加 API 可以是现成的解决方案比如[度量服务器](https://github.com/kubernetes-sigs/metrics-server)，
或者你自己开发的 API。

1. 适当换行，方便review
2. 中英文标点符号转换
3. 特殊英文关键字可保留原文

2021-10-09 13:35 UTC, tengqm commented
Minor nits as spotted by @howieyuen, lgtm otherwise.
/approve

2021-10-12 00:34 UTC, tengqm commented on content/zh/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation.md
> +这里的附加 API 可以是现成的解决方案比如[度量服务器](https://github.com/kubernetes-sigs/metrics-server),
metrics server 是一个项目的名称，按惯例我们不翻译。

2021-10-21 00:13 UTC, tengqm commented
/lgtm

2021-10-21 00:16 UTC, merged