[es] Add content/es/docs/tasks/tools/wg.md
kubernetes/website pull request #29989
Opened 2021-10-08 23:02 UTC by DiegoServinHdn

- Add wg.md file's Spanish translation

2021-10-09 00:36 UTC, electrocucaracha requested changes

2021-10-09 00:36 UTC, electrocucaracha commented on content/es/docs/reference/glossary/wg.md
> + Facilita la discusión y/o la implementación de un proyecto que sea efímero, corto o desacoplado para un comité, {{< glossary_tooltip text="SIG" term_id="sig" >}}, o trabajo SIG cruzado.
```suggestion
 Facilita la discusión y/o la implementación de un proyecto que sea efímero, corto o desacoplado para un comité, {{< glossary_tooltip text="SIG" term_id="sig" >}}, o un esfuerzo entre varios SIGs.
```

2021-10-09 01:04 UTC, DiegoServinHdn commented
> Muchas gracias por tu contribución al proyecto de documentación de Kubernetes

Creo que me equivoque de carpeta en el mensaje del commit, muchas gracias por el update.

2021-10-09 02:54 UTC, electrocucaracha commented
> > Muchas gracias por tu contribución al proyecto de documentación de Kubernetes
> 
> Creo que me equivoque de carpeta en el mensaje del commit, muchas gracias por el update.

Mas bien me confundió el titulo del PR

2021-10-10 16:28 UTC, raelga approved these changes
Muchas gracias @DiegoServinHdn por tu contribución y bienvenido a Kubernetes!

/approve

2021-10-10 16:28 UTC, merged