[es] - Updated `kubectl` Installation Docs
kubernetes/website pull request #30209
Opened 2021-10-24 07:28 UTC by adithyaakrishna

Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

**Summary:**
This PR Updates the `kubectl `installation docs in Spanish

**Description:**
This PR Fixes #27078

2021-11-02 05:09 UTC, tengqm commented
/remove-language zh

2021-11-04 07:34 UTC, adithyaakrishna commented on content/es/docs/tasks/tools/included/install-kubectl-linux.md
> +Debes usar una versión de kubectl que esté dentro de una diferencia de versión menor de tu clúster. Por ejemplo, un v{{< skew latestVersion >}} La cliente puede comunicarse con v{{< skew prevMinorVer
Okay sure @electrocucaracha will fix this up ASAP 👍🏻

2021-11-04 07:40 UTC, adithyaakrishna commented
/remove-language ko

2021-11-13 01:23 UTC, electrocucaracha requested changes

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/kubectl-convert-overview.md
> +Un complemento para la herramienta de línea de comandos de Kubernetes `kubectl`, que le permite convertir manifiestos entre diferentes versiones de API. Esto puede ser particularmente útil para migra
```suggestion
Un plugin para la herramienta de línea de comandos de Kubernetes `kubectl`, que le permite convertir manifiestos entre diferentes versiones de la API. Esto puede ser particularmente útil para migrar manifiestos a una versión no obsoleta de la API con la versión más reciente de Kubernetes.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +El script de finalización de kubectl para Bash se puede generar con el comando `kubectl completion bash`. Obtener el script de finalización en su shell habilita el autocompletado de kubectl.
```suggestion
El script de completado de kubectl para Bash se puede generar con el comando `kubectl completion bash`. Obtener el script de completado en su shell habilita el autocompletado de kubectl.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +Sin embargo, el guión de finalización depende de [**bash-completion**](https://github.com/scop/bash-completion), lo que significa que primero debe instalar este software (puedes probar si tienes bash
```suggestion
Sin embargo, el script de completado depende de [**bash-completion**](https://github.com/scop/bash-completion), lo que significa que primero debe instalar este software (puedes probar si tienes bash-completion ya instalado ejecutando `type _init_completion`).
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +La finalización de bash es proporcionado por muchos administradores de paquetes (ver [aquí](https://github.com/scop/bash-completion#installation)). Puedes instalarlo con `apt-get install bash-complet
```suggestion
El completado de bash es proporcionado por muchos administradores de paquetes (ver [aquí](https://github.com/scop/bash-completion#installation)). Puedes instalarlo con `apt-get install bash-completion` o `yum install bash-completion`, etc.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +Los comandos anteriores crean `/usr/share/bash-completion/bash_completion`, que es el guión principal de bash-complete. Dependiendo de su administrador de paquetes, debe obtener manualmente este arch
```suggestion
Los comandos anteriores crean `/usr/share/bash-completion/bash_completion`, que es el script principal de bash-complete. Dependiendo de su administrador de paquetes, debe obtener manualmente este archivo de perfil en su `~/.bashrc`.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +Ahora debe asegurarse de que el script de finalización de kubectl se obtenga en todas sus sesiones de shell. Hay dos formas de hacer esto:
```suggestion
Ahora debe asegurarse de que el script de completado de kubectl se obtenga en todas sus sesiones de shell. Hay dos formas de hacer esto:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +- Obtenga el script de finalización en su `~/.bashrc` expediente:
```suggestion
- Obtenga el script de completado en su perfil `~/.bashrc`:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +- Agregue el guión de finalización al `/etc/bash_completion.d` directorio:
```suggestion
- Agregue el script de completado al directorio de `/etc/bash_completion.d`:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +Si tiene un alias para kubectl, puede extender la finalización del shell para trabajar con ese alias:
```suggestion
Si tiene un alias para kubectl, puede extender el completado del shell para trabajar con ese alias:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +fuentes de bash-complete todos los guiones `/etc/bash_completion.d`.
```suggestion
El código fuente de bash-complete todos los scripts se encuentra en `/etc/bash_completion.d`.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +El script de finalización de kubectl para Bash se puede generar con `kubectl completion bash`. Obtener este script en su shell permite la finalización de kubectl.
```suggestion
El script de completado de kubectl para Bash se puede generar con `kubectl completion bash`. Obtener este script en su shell permite el completado de kubectl.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Sin embargo, el script de finalización de kubectl depende de [**finalización de bash**](https://github.com/scop/bash-completion) que, por lo tanto, debe instalar previamente.
```suggestion
Sin embargo, el script de finalización de kubectl depende de [**bash-completion**](https://github.com/scop/bash-completion) que, por lo tanto, debe instalar previamente.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +que es el predeterminado en macOS), y v2 es para Bash 4.1+. El script de finalización de kubectl **no funciona** correctamente con bash-complete v1 y Bash 3.2. Requiere **bash-complete v2** y **Bash
```suggestion
que es el predeterminado en macOS), y v2 es para Bash 4.1+. El script de completado de kubectl **no funciona** correctamente con bash-complete v1 y Bash 3.2. Requiere **bash-complete v2** y **Bash 4.1+**. Por lo tanto, para poder usar correctamente la finalización de kubectl en macOS, debe instalar y usar Bash 4.1+ ([*instrucciones*](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba)). Las siguientes instrucciones asumen que usa Bash 4.1+ (es decir, cualquier versión de Bash de 4.1 o posterior).
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Las instrucciones aquí asumen que usa Bash 4.1+. Puede verificar la versión de su Bash ejecutando:
```suggestion
Las siguientes instrucciones asumen que usa Bash 4.1+. Puede verificar la versión de su Bash ejecutando:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Si es demasiado antiguo, puede instalarlo / actualizarlo usando Homebrew:
```suggestion
Si es demasiado antiguo, puede instalarlo o actualizarlo usando Homebrew:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Como se mencionó, estas instrucciones asumen que usa Bash 4.1+, lo que significa que instalará bash-completacion v2 (a diferencia de Bash 3.2 y bash-deployment v1, en cuyo caso la finalización de kub
```suggestion
Como se mencionó antes, estas instrucciones asumen que usa Bash 4.1+, lo que significa que instalará bash-completacion v2 (a diferencia de Bash 3.2 y bash-deployment v1, en cuyo caso el completado de kubectl no funcionará).
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Puede probar si ya tiene instalado bash-complete v2 con `type _init_completion`.Si no es así, puede instalarlo con Homebrew:
```suggestion
Puede probar si ya tiene instalado bash-complete v2 con `type _init_completion`. Si no es así, puede instalarlo con Homebrew:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Como se indica en el resultado de este comando, agregue lo siguiente a su archivo `~ / .bash_profile`:
```suggestion
Como se indica en el resultado de este comando, agregue lo siguiente a su archivo `~/.bash_profile`:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Vuelva a cargar su shell y verifique que bash-complete v2 esté instalado correctamente con`type _init_completion`.
```suggestion
Vuelva a cargar su shell y verifique que bash-complete v2 esté instalado correctamente con `type _init_completion`.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Ahora debe asegurarse de que el script de finalización de kubectl se obtenga en todas sus sesiones de shell. Hay varias formas de lograrlo:
```suggestion
Ahora debe asegurarse de que el script de completado de kubectl se obtenga en todas sus sesiones de shell. Hay varias formas de lograrlo:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +- Obtenga el script de finalización en su `~/.bash_profile` expediente:
```suggestion
- Obtenga el script de finalización en su perfil `~/.bash_profile`:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +- Agregue el guión de finalización al `/usr/local/etc/bash_completion.d` directorio:
```suggestion
- Agregue el script de completado al directorio `/usr/local/etc/bash_completion.d`:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +- Si tiene un alias para kubectl, puede extender la finalización del shell para trabajar con ese alias:
```suggestion
- Si tiene un alias para kubectl, puede extender el completado del shell para trabajar con ese alias:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +- Si instaló kubectl con Homebrew (como se explica [aquí](/docs/tasks/tools/install-kubectl-macos/#install-with-homebrew-on-macos)), entonces el script de finalización de kubectl ya debería estar en
```suggestion
- Si instaló kubectl con Homebrew (como se explica [aquí](/docs/tasks/tools/install-kubectl-macos/#install-with-homebrew-on-macos)), entonces el script de completado de kubectl ya debería estar en `/usr/local/etc/bash_completion.d/kubectl`. En ese caso, no necesita hacer nada.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +   La instalación de Homebrew de bash -mentation v2 genera todos los archivos en el `BASH_COMPLETION_COMPAT_DIR` directorio, es por eso que los dos últimos métodos funcionan.
```suggestion
   La instalación de Homebrew de bash-completion v2 genera todos los archivos en el directorio `BASH_COMPLETION_COMPAT_DIR`, es por eso que los dos últimos métodos funcionan.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +En cualquier caso, después de recargar su shell, la finalización de kubectl debería estar funcionando.
```suggestion
En cualquier caso, después de recargar su shell, el completado de kubectl debería estar funcionando.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +El script de finalización de kubectl para Zsh se puede generar con el comando `kubectl completion zsh`. Obtener el script de finalización en su shell habilita el autocompletado de kubectl.
```suggestion
El script de completado de kubectl para Zsh se puede generar con el comando `kubectl completion zsh`. Obtener el script de completado en su shell habilita el autocompletado de kubectl.
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +Para hacerlo en todas sus sesiones de shell, agregue lo siguiente a su`~/.zshrc` expediente:
```suggestion
Para hacerlo en todas sus sesiones de shell, agregue lo siguiente a su perfil `~/.zshrc`:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +Si tiene un alias para kubectl, puede extender la finalización del shell para trabajar con ese alias:
```suggestion
Si tiene un alias para kubectl, puede extender el completado del shell para trabajar con ese alias:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/optional-kubectl-configs-zsh.md
> +luego agregue lo siguiente al comienzo de su `~/.zshrc` expediente:
```suggestion
luego agregue lo siguiente al comienzo de su perfil `~/.zshrc`:
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/verify-kubectl.md
> +[archivo kubeconfig](/docs/concepts/configuration/organize-cluster-access-kubeconfig/),que se crea automáticamente cuando creas un clúster usando
```suggestion
[archivo kubeconfig](/docs/concepts/configuration/organize-cluster-access-kubeconfig/), que se crea automáticamente cuando creas un clúster usando
```

2021-11-13 01:23 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/verify-kubectl.md
> +La conexión al servidor <server-name:port> fue rechazada. ¿Especificó el host o puerto correcto?
```suggestion
The connection to the server <server-name:port> was refused - did you specify the right host or port?
```

2021-12-06 00:32 UTC, jimangel commented
@adithyaakrishna are you still working on this? If so, would you mind resolving the conflicting files and [squashing your commits](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits)?

If PR is open for greater than a month without action, the next PR wrangler may close it if appropriate (and you can return / reopen when ready to continue).

Thanks!

2021-12-15 18:08 UTC, raelga commented
@adithyaakrishna  can you check the latests comments?

2021-12-20 18:36 UTC, adithyaakrishna commented
@raelga @jimangel Thanks for reminding :)
Yes sure, Apologies for the delay. I have addressed most of the changes but some are pending still. Will finish it up ASAP

2022-01-11 11:03 UTC, raelga reviewed
@adithyaakrishna let me know if you need any help with the review process!

2022-01-11 11:03 UTC, raelga commented on content/es/docs/tasks/tools/included/install-kubectl-linux.md
> +kubectl proporciona soporte de autocompletado para Bash y Zsh, lo que puede ahorrarle mucho tiempo al escribir.
```suggestion
kubectl proporciona soporte de autocompletado para Bash y Zsh, lo que puede ahorrarle mucho tiempo al interactuar con la herramienta.
```

2022-01-16 13:12 UTC, adithyaakrishna commented
@electrocucaracha @raelga Apologies for the delay :/
I have made all the requested changes to the PR and Rebased the branch as well. Please do lmk if you have any changes/suggestions as well :)

2022-01-25 02:36 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/install-kubectl-linux.md
> +Debes usar una versión de kubectl que esté dentro de una diferencia de versión menor de tu clúster. Por ejemplo, un v{{< skew latestVersion >}} La cliente puede comunicarse con v{{< skew prevMinorVer
```suggestion
Debes usar una versión de kubectl que esté dentro de una diferencia de versión menor de tu clúster. Por ejemplo, un cliente v{{< skew latestVersion >}} puede comunicarse con v{{< skew prevMinorVersion >}}, v{{< skew latestVersion >}}, y v{{< skew nextMinorVersion >}} del plano de control.
```

2022-01-25 02:36 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/install-kubectl-linux.md
> +   # y luego agrega ~/.local/bin/kubectl para $PATH
```suggestion
   # y luego agregue ~/.local/bin/kubectl en el $PATH
```

2022-01-25 02:36 UTC, electrocucaracha commented on content/es/docs/tasks/tools/included/install-kubectl-macos.md
> +Debes usar una versión de kubectl que esté dentro de una diferencia de versión menor de tu clúster. Por ejemplo, un v{{< skew latestVersion >}} El cliente puede comunicarse con v{{< skew prevMinorVer
```suggestion
Debes usar una versión de kubectl que esté dentro de una diferencia de versión menor de tu clúster. Por ejemplo, un cliente v{{< skew latestVersion >}} puede comunicarse con v{{< skew prevMinorVersion >}}, v{{< skew latestVersion >}}, y v{{< skew nextMinorVersion >}} del plano de control.
```

2022-01-25 16:10 UTC, electrocucaracha reviewed
/lgtm

/cc @raelga

2022-02-08 15:42 UTC, raelga commented
/approve

2022-02-08 15:42 UTC, merged

2022-02-08 15:43 UTC, anyulled approved these changes