Suggested improvement for audit log set up
kubernetes/website pull request #30341
Opened 2021-11-03 08:46 UTC by pmmalinov01

Hello,

I want to suggest a small improvement, I was setting up the Kubernetes audit according to the documentation and faced an issue. It was related to the Kubernetes API not being able to rename the file

`Error in audit plugin 'log' affecting 1 audit events: can't rename log file: rename /var/log/audit.log /var/log/audit-2021-11-03T06-52-01.404.log: device or resource busy`

It turns to be caused by mounting the file only and not a directory. 
My suggestion is to add the options to enable rotation and to set up the volumeMounts and volumes properly to help future users not deal with it.
The other approach, we can take is to add a note saying that if the user wants to rotate a different set-up is needed, I am just not sure if it will be convoluted.

2021-11-12 18:40 UTC, geoffcline requested changes
noticed a small typo

2021-11-16 09:42 UTC, RinkiyaKeDad commented
I believe this is similar to #29026 🤔

2021-12-06 00:41 UTC, jimangel commented
duplicate, closing in favor of: https://github.com/kubernetes/website/pull/30712

2021-12-06 00:41 UTC, jimangel commented
/close

2021-12-06 00:41 UTC, closed without merging