Podsecurity beta updates
kubernetes/website pull request #30351
Opened 2021-11-03 21:44 UTC by liggitt

/sig auth
/cc @tallclair @enj 

xref https://github.com/kubernetes/enhancements/issues/2579

2021-11-05 13:23 UTC, jlbutler commented
/assign @chrisnegus

2021-11-08 03:35 UTC, enj commented
/assign

2021-11-10 15:27 UTC, chrisnegus commented on content/en/docs/concepts/security/pod-security-admission.md
> +is Beta and enabled by default.
```suggestion
is a Beta feature and is enabled by default.
```

2021-11-10 15:32 UTC, chrisnegus requested changes
I suggested a couple of small wording changes.

2021-11-10 15:32 UTC, chrisnegus commented on content/en/docs/concepts/security/pod-security-admission.md
> +is Alpha and must be enabled in `kube-apiserver` in order to use the built-in admission plugin.
```suggestion
is an Alpha feature and must be enabled in `kube-apiserver` in order to use the built-in admission plugin.
```

2021-11-10 15:35 UTC, liggitt commented
> I suggested a couple of small wording changes.

done

2021-11-10 15:38 UTC, chrisnegus commented
/lgtm

2021-11-11 07:37 UTC, tengqm commented
/approve

2021-11-11 07:37 UTC, merged

2021-11-11 20:45 UTC, chrisnegus commented
@liggitt Thanks for getting this done!