kubelet-in-userns.md: fix typoes; fix unexpected config paths; add back the link to example port forwarder implementation
kubernetes/website pull request #30410
Opened 2021-11-09 10:31 UTC by AkihiroSuda

# Commit 1: `kubelet-in-userns.md: fix typoes`

(EOM)
- - -

# Commit 2: `kubelet-in-userns.md: fix unexpected config paths`

Referring to `/etc/containerd/config.toml` makes sense only when the user has read/write permissions to `/etc/containerd/config.toml` in the current mount namespace, which is not always assumed in the context of this documentation.

The same applies to `/etc/crio/crio.conf`, too.

Partially revert PR #30020 

- - -

# Commit 3: `kubelet-in-userns.md: add back the link to example port forwarder implementation`

Add back the link to `k3s/pkg/rootlessports/controller.go` removed in PR #30020 .

As stated in `{{ <note> }}`, the corresponding section is written for developers of Kubernetes distros, not for end users.
So we should retain the implementation details here.

Partially revert PR #30020 .

2021-11-09 15:45 UTC, geoffcline commented
a small fix, we try to avoid "[here]" links in the docs. :)

2021-11-09 15:47 UTC, geoffcline requested changes
fix "here" link

2021-11-09 15:47 UTC, geoffcline commented
/assign

2021-11-10 05:24 UTC, AkihiroSuda commented
removed "here"

2021-11-11 10:56 UTC, tengqm commented
/lgtm

2021-11-12 01:52 UTC, kbhawkey commented
Page preview:
https://deploy-preview-30410--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/kubelet-in-userns/

2021-11-12 01:58 UTC, kbhawkey commented
/retitle Fix typos,config paths in kubelet-in-userns.md. Add link to port forwarder implementation

2021-11-12 01:58 UTC, kbhawkey commented
/label tide/merge-method-squash

2021-11-12 02:00 UTC, kbhawkey commented
/approve

2021-11-12 02:02 UTC, merged