Fix to reveal more info when '[+]' is clicked
kubernetes/website pull request #30458
Opened 2021-11-12 12:38 UTC by wiggitywhitney

(´ ▽｀).。ｏ♡ Hello friends!

Currently in the glossary, in the 'Pod Disruption' definition, when the '[+]' is clicked the definition simply repeats itself.  

 This should fix that to instead display more information when the '[+]' is clicked.

2021-11-12 13:10 UTC, divya-mohan0209 requested changes
Please leave a line after the sentence completion on line 24 . There's an additional whitespace showing up in the deploy preview: https://deploy-preview-30458--kubernetes-io-main-staging.netlify.app/docs/reference/glossary/?operation=true

2021-11-12 14:12 UTC, wiggitywhitney commented
@divya-mohan0209 I am happy to change it if you like but I believe that every entry that has been extended by clicking the '[+]' has that line of whitespace

2021-11-12 14:26 UTC, divya-mohan0209 commented
@wiggitywhitney The whitespace line distribution is non-standard. I'll defer to @sftim for his take on this.

2021-11-12 16:32 UTC, reylejano commented
Original page update (at the time of this comment):
https://kubernetes.io/docs/reference/glossary/?operation=true

Preview of update page:
https://deploy-preview-30458--kubernetes-io-main-staging.netlify.app/docs/reference/glossary/?operation=true

/lgtm

2021-11-13 03:18 UTC, reylejano commented
/approve

2021-11-13 03:20 UTC, merged