[hi] Add  content/hi/docs/tasks/tools/included/optional-kubectl-confi…
kubernetes/website pull request #30595
Opened 2021-11-22 17:06 UTC by ashish-jaiswar

### ### added one file 
localized optional-kubectl-configs-bash-linux.md to Hindi.
[issues](https://github.com/kubernetes/website/issues/30569)

2021-11-22 18:08 UTC, ashish-jaiswar commented
/I signed it

2021-11-22 18:16 UTC, ashish-jaiswar commented
/check-cla

2021-11-22 18:26 UTC, ashish-jaiswar commented
/easycla

2021-11-23 08:48 UTC, verma-kunal commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> + बैश के लिए kubectl  कम्प्लिशन स्क्रिप्ट `kubectl completion bash` कमांड के साथ उत्पन्न की जा सकती है।                         आपके शेल में  कम्प्लिशन  स्क्रिप्ट को सोर्स करने से kubectl ऑटोकम्प्लिशन
it is recommended to follow a uniform localising style throughout the doc. 
for example: if we are using `bash` as it is in a certain sentence, its recommended to use the same pattern throughout!

2021-11-23 09:03 UTC, anubha-v-ardhan requested changes
These are shortcode and should not be translated. This was also the reason netlify tests failed as netlify couldn't build the site.

As the log says
```
7:57:48 PM: ────────────────────────────────────────────────────────────────
7:57:48 PM:   1. build.command from netlify.toml                            
7:57:48 PM: ────────────────────────────────────────────────────────────────
7:57:48 PM: ​
7:57:48 PM: $ git submodule update --init --recursive --depth 1 && make deploy-preview
7:57:48 PM: hugo --enableGitInfo --buildFuture -b https://deploy-preview-30555--kubernetes-io-main-staging.netlify.app
7:57:48 PM: Start building sites …
7:57:48 PM: hugo v0.87.0-B0C541E4+extended linux/amd64 BuildDate=2021-08-03T10:57:28Z VendorInfo=gohugoio
7:57:51 PM: Error: Error building site: "/opt/build/repo/content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md:46:1": failed to extract shortcode: template for shortcode "ध" not found
7:57:51 PM: Total in 3161 ms
7:57:51 PM: Makefile:38: recipe for target 'deploy-preview' failed
7:57:51 PM: make: *** [deploy-preview] Error 255
```

2021-11-23 10:16 UTC, ashish-jaiswar commented
@verma-kunal , @anubha-v-ardhan I updated the file please merge this PR.

2021-11-23 12:26 UTC, divya-mohan0209 requested changes
lgtm to me.

However, please could you squash & merge the number of commits to 1?

2021-11-23 13:47 UTC, anubha-v-ardhan requested changes
Final Review.
Please commit the suggestions if you agree with them.

2021-11-23 13:47 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +- अपनी `~/.bashrc` फ़ाइल में  कम्प्लिशन स्क्रिप्ट सॉर्स करें :
```suggestion
- अपनी `~/.bashrc` फ़ाइल में कम्प्लिशन स्क्रिप्ट सॉर्स करें:
```

2021-11-23 13:47 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +बैश- कम्प्लिशन स्रोत सभी कम्प्लिशन स्क्रिप्ट `/etc/bash_completion.d` में ।
```suggestion
bash-completion सभी कम्प्लिशन स्क्रिप्ट को `/etc/bash_completion.d` में सोर्स करता है।
```

2021-11-23 18:09 UTC, ashish-jaiswar commented
hey, @anubha-v-ardhan I committed the suggestion, what is the next step?

2021-11-23 18:12 UTC, anubha-v-ardhan commented
@ashish-jaiswar Looks like you merged the main branch along with the suggestions too which has caused 1011 commits on this PR. Can you fix it?

2021-11-23 18:14 UTC, ashish-jaiswar commented
@anubha-v-ardhan How can I resolve this issue? can you suggest to me I am a new contributor?

2021-11-23 18:24 UTC, anubha-v-ardhan commented
@ashish-jaiswar afaik, you can do one of the following to fix this (whichever will be easier for you)

1. Do a rebase and drop the unwanted commits.
2. Start a new branch off `dev-1.22-hi.1`, copy the text from here and make a new PR.

Its totally fine to make a new PR, just close this PR mentioning the new one if you choose the 2nd option

2021-11-23 18:34 UTC, ashish-jaiswar commented
opening new PR

2021-11-23 18:34 UTC, closed without merging

2022-04-07 02:54 UTC, jihoon-seo commented
/remove-area blog release-eng
/remove-language de en es fr id it ja ko pl pt ru uk vi zh
/remove-sig release