[hi] Add content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
kubernetes/website pull request #30607
Opened 2021-11-23 10:47 UTC by kranurag7

Added the localisation of optional-kubectl-configs-bash-mac.md 

(https://github.com/kubernetes/website/issues/30570)

@anubha-v-ardhan

2021-11-28 17:59 UTC, anubha-v-ardhan requested changes
Thank you, here's my review. Please go through all the suggested changes and commit if you agree with them. Feel free to ask if you have any doubt

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +
```suggestion
---
title: "macOS पर bash ऑटो-कम्पलीशन"
description: "macOS पर bash ऑटो-कम्पलीशन के लिए कुछ वैकल्पिक कॉन्फ़िगरेशन।"
headless: true
---
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +`kubectl completion bash` से बैश के लिए kubectl कम्पलीशन स्क्रिप्ट किया जा सकता हैं | इस स्क्रिप्ट को अपने सेल में सोर्स करने से kubectl कम्पलीशन इनेबल होगा |
```suggestion
### परिचय

Bash के लिए kubectl समापन स्क्रिप्ट `kubectl completion bash` कमांड के साथ उत्पन्न की जा सकती है। आपके शेल में समापन स्क्रिप्ट को सोर्स करने से kubectl ऑटोकम्पलीशन सक्षम हो जाती है।```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +`kubectl completion bash` से बैश के लिए kubectl कम्पलीशन स्क्रिप्ट किया जा सकता हैं | इस स्क्रिप्ट को अपने सेल में सोर्स करने से kubectl कम्पलीशन इनेबल होगा |
```suggestion
### परिचय

Bash के लिए kubectl समापन स्क्रिप्ट `kubectl completion bash` कमांड के साथ उत्पन्न की जा सकती है। आपके शेल में समापन स्क्रिप्ट को सोर्स करने से kubectl ऑटोकम्पलीशन सक्षम हो जाती है।```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +हालाँकि, kubectl कम्पलीशन स्क्रिप्ट बैश कम्पलीशन पर निर्भर करती है जिसे आपको पहले इनस्टॉल करना होगा।
```suggestion
हालाँकि, समापन की स्क्रिप्ट [**bash-completion**](https://github.com/scop/bash-completion) पर निर्भर हैं जिसका अर्थ है कि आपको पहले इस सॉफ़्टवेयर को इंस्टॉल करना होगा।
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +{{चेतावनी>}}
```suggestion
{{< warning >}}
Bash-completion के लिये दो संस्करण हैं  v1 और v2। v1 bash 3.2 के लिये हैं (जो macOS के लिए डिफ़ॉल्ट है), और v2 bash 4.1+ के लिए है।kubectl कम्पलीशन स्क्रिप्ट Bash-completion v1 और Bash 3.2 के साथ ठीक से **काम नहीं करती है**। इसके लिए **Bash-completion v2** और बैश 4.1+ की आवश्यकता है। इसलिए macOS पर kubectl कम्पलीशन को सही तरीके से इस्तेमाल करने के लिए , आपको bash 4.1+ इनस्टॉल और उपयोग करना होगा ([*निर्देश*](https://itnext.io/upgrading-bash-on-macos-7138bd1066ba))। निम्नलिखित निर्देश मानते हैं कि आप बैश का उपयोग करते हैं (अर्थात 4.1  का कोई भी बैश संस्करण या इससे नया)।
{{< /warning >}}
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +निम्नलिखित  निर्देश मानते हैं कि आप बैश 4.1+ का उपयोग करते हैं | आप अपने बैश के संस्करण को   यह चलाकर देख सकते हैं:
```suggestion
निम्नलिखित निर्देश मानते हैं कि आप बैश 4.1+ का उपयोग करते हैं। आप अपने बैश के संस्करण को यह चलाकर देख सकते हैं:

```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +यदि यह बहुत पुराना है, तो आप Homebrew का उपयोग करके इसे इनस्टॉल/अपग्रेड कर सकते हैं :
```suggestion
यदि यह बहुत पुराना है, तो आप Homebrew का उपयोग करके इसे इनस्टॉल/अपग्रेड कर सकते हैं:

```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +अपना शेल को दुबारा  लोड करें और सत्यापित करें कि वांछित संस्करण का उपयोग किया जा रहा है:
```suggestion
अपने शेल को पुनः लोड करें और सत्यापित करें कि इच्छित संस्करण का उपयोग किया जा रहा है:

```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +### इनस्टॉल बैश कम्पलीशन
```suggestion
### इनस्टॉल bash-completion
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +
```suggestion

Homebrew आमतौर पर इसे `/usr/local/bin/bash` पर स्थापित करता है।
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +{{<ध्यान दे >}}
```suggestion
{{< note >}}
जैसा कि उल्लेख किया गया है, ये निर्देश मानते हैं कि आप Bash 4.1+ का उपयोग करते हैं, जिसका अर्थ है कि आप bash-completion v2 इनस्टॉल  करेंगे (Bash 3.2 और bash-completion v1 पर kubectl  पूर्णता काम नहीं करेगी)।
{{< /note >}}
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +आप `type_init_completion` से परीक्षण कर सकते हैं कि क्या आपके पास बैश कम्पलीशन v2 पहले से ही इनस्टॉल है | अगर नहीं, तो आप इसे Homebrew के साथ इनस्टॉल कर सकते हैं
```suggestion
आप `type_init_completion` से सत्यापित कर सकते हैं कि क्या आपके पास bash-completion v2 पहले से इनस्टॉल है। यदि नहीं, तो आप इसे Homebrew से इनस्टॉल कर सकते हैं
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +अपने शेल को दुबारा लोड करें और सत्यापित करें कि बैश कम्पलीशन v2 `type_init_completion` . के साथ सही ढंग से इनस्टॉल है
```suggestion
अपने शेल को पुनः लोड करें और `type_init_completion` से सत्यापित करें कि bash-completion  v2 सही ढंग से इनस्टॉल है।
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +### इनेबल kubectl ऑटोकम्पलीशन
```suggestion
### kubectl ऑटोकम्पलीशन सक्षम करें
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +अब आपको यह सुनिश्चित करना होगा कि आपके सभी शेल सत्रों में kubectl कम्पलीशन स्क्रिप्ट प्राप्त हो जाए। इसे हासिल करने के कई तरीके हैं:
```suggestion
अब आपको यह सुनिश्चित करने की आवश्यकता है कि kubectl समापन स्क्रिप्ट आपके सभी शेल सत्रों (sourced) में प्राप्त हो जाए। इसे हासिल करने के कई तरीके हैं:
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +```
```suggestion
- अपने कम्पलीशन स्क्रिप्ट को  `~/.bash_profile`  में सोर्स करें:

    ```bash
    echo 'source <(kubectl completion bash)' >>~/.bash_profile
    ```
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +```
```suggestion
- कम्पलीशन स्क्रिप्ट को `/usr/local/etc/bash_completion.d` डायरेक्टरी में जोड़ें:

    ```bash
    kubectl completion bash >/usr/local/etc/bash_completion.d/kubectl
    ```
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +```
```suggestion
- यदि आपके पास kubectl के लिए एक नाम (alias) है, तो आप उस उपनाम के साथ काम करने के लिए शेल कम्पलीशन को बढ़ा सकते हैं:

    ```bash
    echo 'alias k=kubectl' >>~/.bash_profile
    echo 'complete -F __start_kubectl k' >>~/.bash_profile
    ```
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +- यदि आपने होमब्रे के साथ kubectl इनस्टॉल किया है (जैसा कि यहां बताया गया है), तो kubectl पहले से ही कम्पलीशन स्क्रिप्ट `/usr/local/etc/bash_completion.d/kubectl` में होनी चाहिए। ऐसे में आपको कुछ भी
```suggestion
- यदि आपने Homebrew के साथ kubectl इनस्टॉल किया है (जैसा कि यहां बताया गया है), तो kubectl कम्पलीशन स्क्रिप्ट पहले से ही `/usr/local/etc/bash_completion.d/kubectl` में होनी चाहिए। ऐसे में आपको कुछ भी करने की जरूरत नहीं है।
```

2021-11-28 17:59 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +{{<ध्यान दे >}}
```suggestion
{{< note >}}
bash-completion Homebrew से इनस्टॉल होने पर, सारे फाइल्स को `BASH_COMPLETION_COMPAT_DIR` डायरेक्टरी में सोर्स कर देता है। इसलिए आखरी दो तरीके काम करते हैं।
{{< /note >}}
```

2021-11-29 12:53 UTC, anubha-v-ardhan requested changes

2021-11-29 12:53 UTC, anubha-v-ardhan commented on content/hi/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +Homebrew आमतौर पर इसे `/usr/local/bin/bash` पर स्थापित करता है।
```suggestion
Homebrew आमतौर पर इसे `/usr/local/bin/bash` पर इनस्टॉल करता है।

```

2021-11-29 14:52 UTC, anubha-v-ardhan commented
/label tide/merge-method-squash
/assign

2021-11-29 14:53 UTC, anubha-v-ardhan commented
/lgtm
/approve

2021-11-29 14:55 UTC, merged

2021-11-29 14:55 UTC, anubha-v-ardhan commented
Thank you @kranurag7 :)

2021-11-29 15:00 UTC, vedant-kakde commented
Thanks @kranurag7

2021-12-01 12:37 UTC, kranurag7 commented
Thanks @anubha-v-ardhan & @vedant-kakde, I look forward to contribute more to the community.