Added task-tutorial-prereqs
kubernetes/website pull request #30602
Opened 2021-11-23 03:48 UTC by Nawaz027

Added task-tutorial-prereqs on the path website/content/hi/includes.
Please have a look @anubha-v-ardhan

2021-11-23 08:50 UTC, anubha-v-ardhan commented
/retitle [hi] Add content/hi/includes/task-tutorial-prereqs.md

2021-11-28 15:25 UTC, anubha-v-ardhan commented
fixes #30590

2021-11-28 15:35 UTC, anubha-v-ardhan requested changes
Links should not be removed

2021-11-28 15:35 UTC, anubha-v-ardhan commented on content/hi/includes/task-tutorial-prereqs.md
> +आपको कुबरनेट्स क्लस्टर की ज़रूरत पड़ेगी और क्यूब सीटीएल कमांड लाइन साधन को समनुरूप करना होगा ताकि वो आपके क्लस्टर के साथ संवाद कर सके। ये अनुशंसित किया गया है की इस अनुशीक्षण को क्लस्टर में रन करने क
```suggestion
आपको कुबरनेट्स क्लस्टर की ज़रूरत पड़ेगी और क्यूब सीटीएल कमांड लाइन साधन को 
समनुरूप करना होगा ताकि वो आपके क्लस्टर के साथ संवाद कर सकें। हमारी सलाह है की इस टुटोरिअल को क्लस्टर में रन करने के लिए कम से कम दो नोड का इस्तेमाल करे जो कि कंट्रोल प्लेन 
होस्ट के तरह ना एक्ट करे। अगर आपके पास पहले से क्लस्टर नही है, आप 
[minikube](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/)
की मदद से वह बना सकते है या आप नीचे दिए हुए इन दो कुबरनेट्स प्लेग्राउंड का इस्तेमाल कर सकते हैं:

```

2021-11-28 15:35 UTC, anubha-v-ardhan commented on content/hi/includes/task-tutorial-prereqs.md
> +•	प्ले विद कुबरनेट्स
```suggestion
* [Katacoda](https://www.katacoda.com/courses/kubernetes/playground)
* [प्ले विथ कुबेरनेट्स](http://labs.play-with-k8s.com/)
```

2021-11-28 15:37 UTC, anubha-v-ardhan commented on content/hi/includes/task-tutorial-prereqs.md
> +आपको कुबरनेट्स क्लस्टर की ज़रूरत पड़ेगी और क्यूब सीटीएल कमांड लाइन साधन को समनुरूप करना होगा ताकि वो आपके क्लस्टर के साथ संवाद कर सके। ये अनुशंसित किया गया है की इस अनुशीक्षण को क्लस्टर में रन करने क
Feel free to use new line when needed, markdown doesn't mind and it makes it more easily readable

2021-11-28 16:21 UTC, Nawaz027 commented
please have a look @anubha-v-ardhan

2021-11-28 16:51 UTC, anubha-v-ardhan commented
/label tide/merge-method-squash
/assign

2021-11-28 16:51 UTC, anubha-v-ardhan commented
/lgtm
/approve

Thank you @Nawaz027

2021-11-28 16:53 UTC, merged