Updated deb sources location
kubernetes/website pull request #30651
Opened 2021-11-27 02:24 UTC by paulgreenbank

Changed deb source from "https://apt.kubernetes.io/" to "http://packages.cloud.google.com/apt/" as apt.kubernetes.io generates apt error regarding no Release file preventing install of kube* packages for install.

2021-11-27 10:51 UTC, divya-mohan0209 requested changes
Please make the necessary changes.

2021-11-27 10:51 UTC, divya-mohan0209 commented on content/en/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +   echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] http://packages.cloud.google.com/apt/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
Small alteration in the link, but otherwise lgtm 

https://packages.cloud.google.com/apt/ kubernetes-xenial main

2021-11-27 14:21 UTC, neolit123 commented
Please post the exact error, apt version, distro version. Before merging
this change it seem better to first report the problem in the
kubernetes/release repository.

2021-11-28 00:24 UTC, Arhell reviewed
Please sign CLA 
https://github.com/kubernetes/website/pull/30651#issuecomment-980488405

2021-11-28 06:08 UTC, mehabhalodiya commented
/check-cla

2021-11-28 06:10 UTC, mehabhalodiya commented
/check-cla

2021-11-29 07:05 UTC, RA489 commented
/check-cla

2021-11-29 13:17 UTC, sftim commented
I haven't reviewed the code (CLA not signed) but with https://github.com/kubernetes/website/pull/30651#issuecomment-980635392 in mind:
/hold

2021-12-05 19:18 UTC, jimangel commented
Hey there! @paulgreenbank, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

2022-01-05 20:14 UTC, annajung commented
closing the PR as the author has [not signed the CLA for two weeks](https://kubernetes.io/docs/contribute/participate/pr-wranglers/#when-to-close-pull-requests).
Please feel free to reopen after signing the CLA.

/close

2022-01-05 20:14 UTC, closed without merging