Kubectl command waits until init containers terminated
kubernetes/website pull request #30673
Opened 2021-11-29 13:01 UTC by gbarceloPIB

Kubectl command waits until init containers terminated, this behaviour is different than only 'started'

2021-11-30 00:56 UTC, Arhell reviewed
Please sign CLA
https://github.com/kubernetes/website/pull/30673#issuecomment-981612191

2021-11-30 07:43 UTC, gbarceloPIB commented
> Please sign CLA [#30673 (comment)](https://github.com/kubernetes/website/pull/30673#issuecomment-981612191)

Done, yesterday I got an error when signing CLA

2021-12-01 04:37 UTC, divya-mohan0209 commented
/check-cla

2021-12-01 04:50 UTC, divya-mohan0209 requested changes
Although, I understand the rationale behind the change I don't feel the phrasing captures what you're trying to put across. 

Maybe, we leave it as is OR phrase it as below?

> * `Initialized`: all [init containers](/docs/concepts/workloads/pods/init-containers/)
  have completed a successful run to completion.

2021-12-01 08:36 UTC, gbarceloPIB commented
> 

To my mind is better as is, is simple. Proposed "completed a successful run to completion" sounds redundant. The fact here is that I read the docs and they were mistaken slightly only. I took edited the phrase from doc init container wording: "Each init container must **complete successfully** before the next one starts" (_aka Initialized_) ([source](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/)). You can try by yourself:

apiVersion: v1
kind: Pod
metadata:
  name: init-test
  namespace: mynamespace
spec:
  restartPolicy: Never
  initContainers:
    - name: busybox-exit-1
      command: ["/bin/sh", "-c", "sleep 120 && exit 1"]
      image: busybox:latest
  containers:
    - name: busybox-exit-0
      command: ["/bin/sh", "-c", "sleep 120 && exit 0"]
      image: busybox:latest

kubectl -n mynamespace wait --for=condition=Initialized pod/init-test --timeout=130s

This will always throw err timeout, the condition that works here is that initContainers have to be in terminated AND **succesfully** state = completed successfully. When pod restarts, this condition will have to happen again if we want the mentioned command to be executed without errors again.

2021-12-01 08:53 UTC, divya-mohan0209 commented
Sorry, there was a nit on my part. 

> * `Initialized`: all [init containers](/docs/concepts/workloads/pods/init-containers/)
  have completed a successful run.

2021-12-01 09:48 UTC, gbarceloPIB commented
It is the same, as you feel

2021-12-01 14:14 UTC, divya-mohan0209 commented
Will await another sig docs reviewer to weigh in on this, however thank you for working on rephrasing this!

2021-12-02 17:26 UTC, mehabhalodiya commented
/check-cla

2021-12-02 17:27 UTC, mehabhalodiya commented
@divya-mohan0209 Still CLA isn't signed!
Otherwise, /lgtm from SIG Docs!

2021-12-05 19:18 UTC, jimangel commented
Hey there! @gbarceloPIB, looks like you haven't signed the CLA yet. Could I please have you do that? https://github.com/kubernetes/community/blob/master/CLA.md

2021-12-05 23:42 UTC, jimangel commented
@gbarceloPIB thanks for your first PR to k/website! 🎉 

I think there's a couple ways to phrase this section but for now it'll do! Thanks!

/lgtm
/approve

2021-12-05 23:44 UTC, merged