[ja] Translate reference/using-api into Japanese
kubernetes/website pull request #30703
Opened 2021-12-01 12:59 UTC by ptux

fix #30671

2021-12-03 00:22 UTC, Arhell reviewed
/assign @nasa9084

2021-12-03 09:44 UTC, ptux commented
@Arhell 

Thanks for the review assignment.

2021-12-03 17:27 UTC, nasa9084 requested changes

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +その結果、Kubernetesプラットフォーム内のすべてのものは、APIオブジェクトとして扱われ、[API](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)に対応するエントリがあります.
```suggestion
その結果、Kubernetesプラットフォーム内のすべてのものは、APIオブジェクトとして扱われ、[API](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)に対応するエントリーがあります.
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +[Kubernetes API参照](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)は、Kubernetesバージョン {{< param "version" >}}のAPI一覧を提供します。
```suggestion
[Kubernetes API参照](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)は、Kubernetesバージョン{{< param "version" >}}のAPI一覧を提供します。
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +## API バージョニング
```suggestion
## APIバージョニング
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +  - バグのリスクが高く、長期的なサポートが得られないため、短期間のテストクラスタのみでの使用を推奨します。
```suggestion
  - バグのリスクが高く、長期的なサポートが得られないため、短期間のテストクラスターのみでの使用を推奨します。
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +  - バージョン名には `beta` が含まれています（例：`v2beta3`）。
```suggestion
  - バージョン名には `beta` が含まれています(例：`v2beta3`)。
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +* *core*（*legacy*とも呼ばれる）グループは、RESTパス `/api/v1` にあります。
```suggestion
* *core*(*legacy*とも呼ばれる)グループは、RESTパス `/api/v1` にあります。
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +   `apiVersion: $GROUP_NAME/$VERSION`を使用します（例：`apiVersion: batch/v1`）。
```suggestion
   `apiVersion: $GROUP_NAME/$VERSION`を使用します(例：`apiVersion: batch/v1`)。
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +また`runtime-config`フラグには、APIサーバのランタイム構成を記述したコンマ区切りの`<key>[=<value>]`ペアを指定します。
```suggestion
また`runtime-config`フラグには、APIサーバーのランタイム構成を記述したコンマ区切りの`<key>[=<value>]`ペアを指定します。
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +APIサーバとコントローラマネージャを再起動して、`--runtime-config`の変更を反映させる必要があります。
```suggestion
APIサーバーとコントローラマネージャーを再起動して、`--runtime-config`の変更を反映させる必要があります。
```

2021-12-03 17:27 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +## 永久化
```suggestion
## 永続化
```

persistency -> 永続性
と訳すことが多いと思いますので、ここは「永続化」の方が良いかな、とおもいます

2021-12-05 08:02 UTC, ptux commented
@nasa9084 
レビューありがとうございます。

下記のガイドを再確認しました。
Kubernetesのドキュメントを翻訳する
https://kubernetes.io/ja/docs/contribute/localization/

2021-12-05 14:42 UTC, nasa9084 commented on content/ja/docs/reference/using-api/_index.md
> +[Kubernetes API参照](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)は、Kubernetesバージョン{{< param "version" >}}のAPI一覧を提供します。
```suggestion
[Kubernetes APIリファレンス](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)は、Kubernetesバージョン{{< param "version" >}}のAPI一覧を提供します。
```
ドキュメント、みたいな意味のreferenceだと思うので、参照と訳すよりはカタカナ表記の方が良いかと思います

2021-12-06 02:30 UTC, nasa9084 commented
/approve

2021-12-09 04:28 UTC, ptux commented
@nasa9084 

> tide — Not mergeable. Merging is blocked by issue 30779.
1.23のリリースが終わったようですが、
こちらのCIステップをどうのように通しますか？

それから、`kubernetes/website`のmembershipを獲得したいのですが、
sponsorになっていただけないでしょうか。

2021-12-09 04:36 UTC, ptux commented
コメントをしたら、

> tide Pending — Not mergeable. Needs lgtm label.

になった。

2022-01-28 00:11 UTC, ptux commented
/label tide/merge-method-squash

2022-01-29 09:45 UTC, riita10069 commented
/lgtm

2022-01-29 09:48 UTC, merged