Tweak flexVolume deprecation
kubernetes/website pull request #30704
Opened 2021-12-01 17:21 UTC by sftim

Redo `flexVolume` deprecation changes + related tweaks.

/sig storage
/milestone 1.23
/kind cleanup

Follow up to PR #30686

2021-12-01 18:17 UTC, jlbutler commented
/assign

2021-12-02 19:38 UTC, jlbutler requested changes
looks great, just found an errant typo

2021-12-02 19:38 UTC, jlbutler commented on content/en/docs/concepts/storage/volumes.md
> +{{< glossary_tooltip text="Container Storage Interface" term_id="csi" >}} (CSI)i, and also FlexVolume (which is deprecated). These plugins enable storage vendors to create custom storage plugins
typo, "(CSI)i"

2021-12-02 22:29 UTC, xing-yang commented
Looks good other than the typo.

2021-12-02 23:47 UTC, sftim commented
Typo fixed. Thanks for spotting it.

2021-12-03 00:08 UTC, jlbutler commented
/lgtm
/approve

2021-12-03 00:10 UTC, merged