[ja] Translate reference/kubectl/conventions into Japanese
kubernetes/website pull request #30785
Opened 2021-12-07 09:01 UTC by ptux

Address https://github.com/kubernetes/website/issues/30782

2021-12-08 05:45 UTC, YuikoTakada commented on content/ja/docs/reference/kubectl/conventions.md
> +#### Generators
How about translate to `ジェネレーター` ? FYI: https://kubernetes.io/ja/docs/tasks/configure-pod-container/configure-pod-configmap/#%E3%82%B8%E3%82%A7%E3%83%8D%E3%83%AC%E3%83%BC%E3%82%BF%E3%83%BC%E3%81%8B%E3%82%89configmap%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B

2021-12-08 05:45 UTC, YuikoTakada commented
Thank you for your PR. I posted one comment, so please check it.

2021-12-08 05:51 UTC, ptux commented on content/ja/docs/reference/kubectl/conventions.md
> +#### Generators
ありがとうございます。

2021-12-15 07:34 UTC, ptux commented
/assign @nasa9084

2021-12-29 10:42 UTC, nasa9084 commented on content/ja/docs/reference/kubectl/conventions.md
> +* コンテキストやプリファレンス、その他の暗黙的な状態に頼ってはいけません。
```suggestion
* コンテキストや設定、その他の暗黙的な状態に頼ってはいけません。
```

2021-12-29 10:42 UTC, nasa9084 commented on content/ja/docs/reference/kubectl/conventions.md
> +`kubectl run`がインフラのコード化を満たすのために:
```suggestion
`kubectl run`がインフラのコード化を満たすために:
```

2021-12-29 10:42 UTC, nasa9084 commented on content/ja/docs/reference/kubectl/conventions.md
> +* 画像にバージョン固有のタグを付けて、そのタグを新しいバージョンに移さない。例えば、`:latest`ではなく、`:v1234`、`v1.2.3`、`r03062016-1-4`を使用してください(詳細は、[Best Practices for Configuration](/docs/concepts/configuration/overview/#container-images)を参照し
```suggestion
* イメージにバージョン固有のタグを付けて、そのタグを新しいバージョンに移さない。例えば、`:latest`ではなく、`:v1234`、`v1.2.3`、`r03062016-1-4`を使用してください(詳細は、[Best Practices for Configuration](/docs/concepts/configuration/overview/#container-images)を参照してください)。
```

2021-12-29 10:42 UTC, nasa9084 commented on content/ja/docs/reference/kubectl/conventions.md
> +`dry-run=client` フラグを使用すると、実際に送信することなく、クラスタに送信されるオブジェクトをプレビューすることができます。
```suggestion
`dry-run=client` フラグを使用すると、実際に送信することなく、クラスターに送信されるオブジェクトを確認することができます。
```

2021-12-29 15:37 UTC, nasa9084 requested changes
(just change pr state)

2022-01-11 15:15 UTC, nasa9084 commented
/approve

2022-01-28 00:11 UTC, ptux commented
/label tide/merge-method-squash

2022-01-29 12:44 UTC, ptux commented
@inductor

cloud you give an LGTM label?

2022-01-30 13:46 UTC, inductor commented
/lgtm

2022-01-30 13:48 UTC, merged