Add v1.23 release to release list
kubernetes/website pull request #30800
Opened 2021-12-08 01:40 UTC by sftim

https://kubernetes.io/releases/patch-releases/ doesn't list Kubernetes v1.23 at all; I think it should, albeit to say that there aren't any patch releases yet. We can also say when v1.23 goes out of support.

/sig release
/milestone 1.23

2021-12-08 03:52 UTC, jlbutler commented
It looks like there are regular cadence updates here as part of another mechanism. I’m certainly not opposed to the updates, but I wonder if we’re missing where these are usually added.

2021-12-08 10:05 UTC, sftim commented
@jlbutler the `/release` path is fairly recent; I don't think it existed in its current form for the v1.22 release.

Usually folks from SIG Release keep it up to date, but I'm not sure that's covered for minor or major releases.

2021-12-08 10:06 UTC, sftim commented
/priority important-soon

2021-12-09 22:26 UTC, jlbutler commented
I think we should fold this into the release docs workflows, I'll put it on my list. Thanks much @sftim 

What's the source for the EOL info? If we can get that sorted and in place, lgtm.

2021-12-10 09:42 UTC, sftim commented
@jlbutler:
> What's the source for the EOL info? If we can get that sorted and in place, lgtm.

I usually look at this page. I don't know where that information stems from; there might be a SIG Docs person who does.
I did mention in SIG Release' Slack channel that it needs filling in. Ultimately I think we have to rely somewhat on SIG Release owning both this section of the website and the information that lives in it.

2021-12-13 19:56 UTC, jlbutler commented
removing this from the 1.23 milestone as i need to close it out to wrap 1.23 work. however, this should be handled and is important to resolve.

@cpanato you've done a few updates of this sort in the past. is this something the release team should be doing for each version, or is this typically ok to do later by some other mechanism?

2021-12-13 22:36 UTC, puerco requested changes
These should be the EOL and maintenance mode for Kubernetes 1.23 :point_down:

2021-12-13 22:36 UTC, puerco commented on content/en/releases/patch-releases.md
> +End of Life for **1.22** is **FIXME**.
```suggestion
**1.23** enters maintenance mode on **2022-12-28**.

End of Life for **1.23** is **2023-02-28**.
```

2021-12-13 22:36 UTC, puerco commented on data/releases/schedule.yaml
> +  endOfLifeDate: FIXME
```suggestion
  endOfLifeDate: 2023-02-28
```

2021-12-13 23:00 UTC, sftim commented
Not sure what Netlify is thinking though. No preview update yet.

2021-12-13 23:02 UTC, sftim commented
![Local preview](https://user-images.githubusercontent.com/22591623/145902824-abc44147-d27d-4237-b4c0-50a1eeced583.png)

2021-12-13 23:03 UTC, sftim commented
/test

2021-12-13 23:39 UTC, reylejano commented on content/en/releases/patch-releases.md
> +No patch releases.
```suggestion
Patch release schedule to be determined.
```
Is it better to state that the 1.23 patch schedule is to be determined to deter an impression of no patch releases for 1.23

2021-12-14 17:42 UTC, sftim commented
I also opened https://github.com/kubernetes/website/pull/30924 which makes the `{{< release-data >}}` shortcode render better.

2021-12-14 18:15 UTC, reylejano commented
/lgtm

2021-12-14 18:27 UTC, jimangel commented
/approve

2021-12-14 18:27 UTC, merged