[ja] Translate tasks/administer-cluster/securing-a-cluster into Japanese
kubernetes/website pull request #30812
Opened 2021-12-08 12:17 UTC by ptux

Adress issue https://github.com/kubernetes/website/issues/30810

2021-12-15 07:32 UTC, ptux commented
/assign @nasa9084

2021-12-29 03:09 UTC, nasa9084 requested changes

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +このドキュメントでは、偶発的または悪意のあるアクセスからクラスタを保護するためのトピックについて説明します。
```suggestion
このドキュメントでは、偶発的または悪意のあるアクセスからクラスターを保護するためのトピックについて説明します。
```

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +このドキュメントでは、偶発的または悪意のあるアクセスからクラスタを保護するためのトピックについて説明します。
以下同様に修正お願いします

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +### すべてのAPIトラフィックにTLS（Transport Layer Security）の使用
```suggestion
### すべてのAPIトラフィックにTLS(Transport Layer Security)の使用
```

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +It is recommended that you use the [Node](/docs/reference/access-authn-authz/node/) and [RBAC](/docs/reference/access-authn-authz/rbac/) authorizers together, in combination with the [NodeRestriction
消し忘れ

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +たとえば、ユーザーは直接ポッドを作成することはできませんが、ユーザーに代わってポッドを作成するデプロイメントの作成を許可することで、間接的にそれらのポッドを作成することができます。
```suggestion
たとえば、ユーザーは直接Podを作成することはできませんが、ユーザーに代わってPodを作成するDeploymentの作成を許可することで、間接的にそれらのPodを作成することができます。
```

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +たとえば、ユーザーは直接ポッドを作成することはできませんが、ユーザーに代わってポッドを作成するデプロイメントの作成を許可することで、間接的にそれらのポッドを作成することができます。
以下同様

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +ポッドの定義には、[security context](/docs/tasks/configure-pod-container/security-context/)が含まれており、ノード上の特定の Linux ユーザー(root など)として実行するためのアクセス、特権的に実行するためのアクセス、ホストネットワークにアクセスするためのアクセス、その他の制御を要求することができます。
```suggestion
ポッドの定義には、[security context](/docs/tasks/configure-pod-container/security-context/)が含まれており、ノード上の特定の Linux ユーザー(rootなど)として実行するためのアクセス、特権的に実行するためのアクセス、ホストネットワークにアクセスするためのアクセス、その他の制御を要求することができます。
```

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +クラウドプラットフォーム（AWS、Azure、GCEなど）では、しばしばメタデータサービスをインスタンスにローカルに公開しています。
```suggestion
クラウドプラットフォーム(AWS、Azure、GCEなど)では、しばしばメタデータサービスをインスタンスにローカルに公開しています。
```

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +API 用の etcd バックエンドへの書き込みアクセスは、クラスタ全体の root を取得するのと同等であり、読み取りアクセスはかなり迅速にエスカレートするために使用できます。
```suggestion
API用のetcdバックエンドへの書き込みアクセスは、クラスタ全体のrootを取得するのと同等であり、読み取りアクセスはかなり迅速にエスカレートするために使用できます。
```

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +API 用の etcd バックエンドへの書き込みアクセスは、クラスタ全体の root を取得するのと同等であり、読み取りアクセスはかなり迅速にエスカレートするために使用できます。
以下同様

2021-12-29 03:09 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +page for more on how to report vulnerabilities.
このブロック消し忘れですね

2022-01-11 15:24 UTC, nasa9084 requested changes
I have reviewed above L70

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +ノード、プロキシ、スケジューラ、ボリュームプラグインなど、インフラの一部であるものも含めて、すべてのAPIクライアントを認証する必要があります。
```suggestion
ノード、プロキシー、スケジューラー、ボリュームプラグインなど、インフラの一部であるものも含めて、すべてのAPIクライアントを認証する必要があります。
```

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +これらのクライアントは通常、[service accounts](/docs/reference/access-authn-authz/service-accounts-admin/)であるか、またはx509クライアント証明書を使用しており、クラスタ起動時に自動的に作成されるか、クラスタインストールの一部として設定されます。
```suggestion
これらのクライアントは通常、[service accounts](/docs/reference/access-authn-authz/service-accounts-admin/)であるか、またはx509クライアント証明書を使用しており、クラスター起動時に自動的に作成されるか、クラスターインストールの一部として設定されます。
```

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +クラスタのインストール時に、共通のアクセスパターンに合わせて、APIサーバーが使用する認証メカニズムを選択します。
```suggestion
クラスターのインストール時に、共通のアクセスパターンに合わせて、APIサーバーが使用する認証メカニズムを選択します。
```

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +Kubernetesは完全にAPI駆動であるため、誰がクラスタにアクセスできるか、どのようなアクションを実行できるかを制御・制限することが第一の防御策となります。
```suggestion
Kubernetesは完全にAPI駆動であるため、誰がクラスターにアクセスできるか、どのようなアクションを実行できるかを制御・制限することが第一の防御策となります。
```

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +Kubernetesは、クラスタ内のすべてのAPI通信がデフォルトでTLSにより暗号化されていることを期待しており、大半のインストール方法では、必要な証明書を作成してクラスタコンポーネントに配布することができます。
```suggestion
Kubernetesは、クラスター内のすべてのAPI通信がデフォルトでTLSにより暗号化されていることを期待しており、大半のインストール方法では、必要な証明書を作成してクラスターコンポーネントに配布することができます。
```

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +### すべてのAPIトラフィックにTLS(Transport Layer Security)の使用
```suggestion
### すべてのAPIトラフィックにTLS(Transport Layer Security)を使用する
```

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +詳細については、[authentication reference document](/docs/reference/access-authn-authz/authentication/)を参照してください。
The page has been translated, please update link text and url

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +Kubernetesには、統合された[Role-Based Access Control (RBAC)](/docs/reference/access-authn-authz/rbac/)コンポーネントが搭載されており、入力されたユーザーやグループを、ロールにまとめられたパーミッションのセットにマッチさせます。
The page has been translated, please update link text and url

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +Kubernetesには、統合された[Role-Based Access Control (RBAC)](/docs/reference/access-authn-authz/rbac/)コンポーネントが搭載されており、入力されたユーザーやグループを、ロールにまとめられたパーミッションのセットにマッチさせます。
please check below links too

2022-01-11 15:24 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +認証の場合と同様に、小規模なクラスタにはシンプルで幅広い役割が適切かもしれません。
```suggestion
認証の場合と同様に、小規模なクラスターにはシンプルで幅広い役割が適切かもしれません。
```

please fix below too

2022-01-27 13:42 UTC, nasa9084 requested changes

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +### クラスタのリソース使用量の制限
```suggestion
### クラスターのリソース使用量の制限
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +これは、ネームスペースが割り当てることのできるCPU、メモリ、永続的なディスクの量を制限するためによく使われますが、各ネームスペースに存在するPod、サービス、ボリュームの数を制御することもできます。
```suggestion
これは、ネームスペースが割り当てることのできるCPU、メモリー、永続的なディスクの量を制限するためによく使われますが、各ネームスペースに存在するPod、サービス、ボリュームの数を制御することもできます。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +[Limit ranges](/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/)は、上記のリソースの一部の最大または最小サイズを制限することで、ユーザーがメモリなどの一般的に予約されたリソースに対して不当に高いまたは低い値を要求するのを防いだり、何も指定されていない場合にデフォルトの制限を提供したり
```suggestion
[Limit ranges](/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/)は、上記のリソースの一部の最大または最小サイズを制限することで、ユーザーがメモリーなどの一般的に予約されたリソースに対して不当に高いまたは低い値を要求するのを防いだり、何も指定されていない場合にデフォルトの制限を提供したりします。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +ホスト情報にアクセスすることなく、ルートプロセス（uid 0）として正常に実行できます。
```suggestion
ホスト情報にアクセスすることなく、ルートプロセス(uid 0)として正常に実行できます。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +クラウドプラットフォーム(AWS、Azure、GCEなど)では、しばしばメタデータサービスをインスタンスにローカルに公開しています。
```suggestion
クラウドプラットフォーム(AWS、Azure、GCEなど)では、しばしばメタデータサービスをインスタンスローカルに公開しています。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +これらの認証情報は、クラスタ内でのエスカレーションや、同じアカウントの他のクラウドサービスへのエスカレーションに使用できます。
```suggestion
これらの認証情報は、クラスター内でのエスカレーションや、同じアカウントの他のクラウドサービスへのエスカレーションに使用できます。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +## クラスタのコンポーネントの保護
```suggestion
## クラスターのコンポーネントの保護
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +管理者は、TLSクライアント証明書による相互認証など、APIサーバーからetcdサーバーへの強力な認証情報を常に使用すべきであり、API サーバーのみがアクセスできるファイアウォールの後ろにetcdサーバーを隔離することがしばしば推奨される。
```suggestion
管理者は、TLSクライアント証明書による相互認証など、APIサーバーからetcdサーバーへの強力な認証情報を常に使用すべきであり、API サーバーのみがアクセスできるファイアウォールの後ろにetcdサーバーを隔離することがしばしば推奨されます。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +クラスタ内の他のコンポーネントが、完全なキースペースへの読み取りまたは書き込みアクセスを持つマスターetcdインスタンスへのアクセスを許可することは、クラスタ管理者のアクセスを許可することと同じです。
```suggestion
クラスター内の他のコンポーネントが、完全なキースペースへの読み取りまたは書き込みアクセスを持つマスターetcdインスタンスへのアクセスを許可することは、クラスター管理者のアクセスを許可することと同じです。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +発行されたトークンの利用可能期間を制御できる認証プロバイダを使用し、可能な限り短いライフタイムを使用します。
```suggestion
発行されたトークンの利用可能期間を制御できる認証プロバイダーを使用し、可能な限り短いライフタイムを使用します。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +Kubernetesへの多くのサードパーティの統合は、クラスタのセキュリティプロファイルを変更する可能性があります。
```suggestion
Kubernetesへの多くのサードパーティの統合は、クラスターのセキュリティプロファイルを変更する可能性があります。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +例えば、多くのセキュリティ統合は、事実上そのコンポーネントをクラスタ管理者にしているクラスタ上のすべての秘密を見るためのアクセスを要求するかもしれません。
```suggestion
例えば、多くのセキュリティ統合は、事実上そのコンポーネントをクラスター管理者にしているクラスター上のすべての秘密を見るためのアクセスを要求するかもしれません。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +一般的に、etcdデータベースにはKubernetes APIを介してアクセス可能なあらゆる情報が含まれており、攻撃者はクラスタの状態に大きな可視性を与える可能性があります。
```suggestion
一般的に、etcdデータベースにはKubernetes APIを介してアクセス可能なあらゆる情報が含まれており、クラスターの状態に対する大きな可視性を攻撃者へ与える可能性があります。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +Kubernetesは1.7で導入された機能である[encryption at rest](/docs/tasks/administer-cluster/encrypt-data/)をサポートしており、1.13からはベータ版となっています。
```suggestion
Kubernetesは1.7で導入された機能である[encryption at rest](/docs/tasks/administer-cluster/encrypt-data/)をサポートしており、これは1.13からはベータ版となっています。
```

2022-01-27 13:42 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/securing-a-cluster.md
> +ページに参照してください。
```suggestion
脆弱性の報告方法については、[security reporting](/docs/reference/issues-security/security/)ページを参照してください。
```

2022-01-28 00:04 UTC, ptux commented
/label tide/merge-method-squash

2022-02-21 15:56 UTC, nasa9084 reviewed
/approve

2022-03-08 03:45 UTC, ptux commented
@inductor 

Cloud you take a look at this PR?

2022-03-15 15:35 UTC, kakts commented
/lgtm

2022-03-15 15:38 UTC, merged