[ja] Translate tasks/debug-application-cluster/debug-application-introspection into Japanese
kubernetes/website pull request #30868
Opened 2021-12-12 09:07 UTC by ptux

Address #30867

2021-12-12 11:52 UTC, Arhell reviewed
/assign @nasa9084

2021-12-27 15:30 UTC, nasa9084 requested changes

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +以下のコマンドを実行して、Deploymentトを作成します:
```suggestion
以下のコマンドを実行して、Deploymentを作成します:
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +ここでは、コンテナ（複数可）とPodに関する構成情報（ラベル、リソース要件など）や、コンテナ（複数可）とPodに関するステータス情報（状態、準備状況、再起動回数、イベントなど）を確認できます。
```suggestion
ここでは、コンテナ(複数可)とPodに関する構成情報(ラベル、リソース要件など)や、コンテナ(複数可)とPodに関するステータス情報(状態、準備状況、再起動回数、イベントなど)を確認できます。
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +コンテナの状態は、Waiting（待機中）、Running（実行中）、Terminated（終了）のいずれかです。状態に応じて、追加の情報が提供されます。ここでは、Running状態のコンテナについて、コンテナがいつ開始されたかが表示されています。
```suggestion
コンテナの状態は、Waiting(待機中)、Running(実行中)、Terminated(終了)のいずれかです。状態に応じて、追加の情報が提供されます。ここでは、Running状態のコンテナについて、コンテナがいつ開始されたかが表示されています。
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +Readyは、コンテナが最後のレディネスプローブに合格したかどうかを示す。(この場合、コンテナにはレディネスプローブが設定されていません。レディネスプローブが設定されていない場合、コンテナはレディであるとみなされます)。
```suggestion
Readyは、コンテナが最後のReadiness Probeに合格したかどうかを示す。(この場合、コンテナにはReadiness Probeが設定されていません。Readiness Probeが設定されていない場合、コンテナは準備が完了した状態であるとみなされます)。
```
Readiness Probeはリソース名ではないですが、他の訳を見るとママ表記なので倣ってママ表記にするのが良さそうです。
最後のReadyの訳は少し悩むところですが、少し冗長でも丁寧に訳した方が読みやすいかと思います。

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +現在、Podに関連する条件は、バイナリのReady条件のみです。これは、Podがリクエストに対応可能であり、マッチングするすべてのサービスのロードバランシングプールに追加されるべきであることを示します。
```suggestion
現在、Podに関連する条件は、二値のReady条件のみです。これは、Podがリクエストに対応可能であり、マッチングするすべてのサービスのロードバランシングプールに追加されるべきであることを示します。
```
日本語で「バイナリ」というとアプリケーションバイナリのことを連想しそうなので、ここは「二値」とした方が良さそうです。

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +現在、Podに関連する条件は、バイナリのReady条件のみです。これは、Podがリクエストに対応可能であり、マッチングするすべてのサービスのロードバランシングプールに追加されるべきであることを示します。
この場合のserviceはServiceリソースにも思えますが・・・
@inductor @kakts @bells17 @makocchi-git どう思いますか？

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +最後に、Podに関連する最近のイベントのログが表示されます。このシステムでは、複数の同一イベントを圧縮して、最初に見られた時刻と最後に見られた時刻、そして見られた回数を示します。"From"はイベントを記録しているコンポーネントを示し、"SubobjectPath"はどのオブジェクト（例：ポッド内のコンテナ）が参照されているかを示し、"Reason"と "Message"は何が起こったかを示して
```suggestion
最後に、Podに関連する最近のイベントのログが表示されます。このシステムでは、複数の同一イベントを圧縮して、最初に見られた時刻と最後に見られた時刻、そして見られた回数を示します。"From"はイベントを記録しているコンポーネントを示し、"SubobjectPath"はどのオブジェクト(例：Pod内のコンテナ)が参照されているかを示し、"Reason"と "Message"は何が起こったかを示しています。
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +## 例：Pending Podsのデバッグ
```suggestion
## 例: Pending Podsのデバッグ
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +イベントを使って検出できる一般的なシナリオは、どのノードにも収まらないPodを作成した場合です。例えば、Podがどのノードでも空いている以上のリソースを要求したり、どのノードにもマッチしないラベルセレクタを指定したりする場合です。例えば、各(仮想)マシンが1つのCPUを持つ4ノードのクラスター上で、（2つではなく）5つのレプリカを持ち、500ではなく600のミリコアを要求する前のDeployme
```suggestion
イベントを使って検出できる一般的なシナリオは、どのノードにも収まらないPodを作成した場合です。例えば、Podがどのノードでも空いている以上のリソースを要求したり、どのノードにもマッチしないラベルセレクターを指定したりする場合です。例えば、各(仮想)マシンが1つのCPUを持つ4ノードのクラスター上で、(2つではなく)5つのレプリカを持ち、500ではなく600のミリコアを要求する前のDeploymentを作成したとします。この場合、Podの1つがスケジュールできなくなります。(なお、各ノードではfluentdやskydnsなどのクラスターアドオンPodが動作しているため、もし1000ミリコアを要求した場合、どのPodもスケジュールできなくなります)
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +ここでは、理由 `FailedScheduling` (およびその他の理由)でPodのスケジュールに失敗したという、スケジューラによって生成されたイベントを見ることができます。このメッセージは、どのノードでもPodに十分なリソースがなかったことを示しています。
```suggestion
ここでは、理由 `FailedScheduling` (およびその他の理由)でPodのスケジュールに失敗したという、スケジューラーによって生成されたイベントを見ることができます。このメッセージは、どのノードでもPodに十分なリソースがなかったことを示しています。
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +kubectl describe pod`の最後に出てきたようなイベントは、etcdに永続化され、クラスタで何が起こっているかについての高レベルの情報を提供します。
```suggestion
`kubectl describe pod`の最後に出てきたようなイベントは、etcdに永続化され、クラスターで何が起こっているかについての高レベルの情報を提供します。
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +しかし、イベントは名前空間であることを忘れてはいけません。つまり、名前空間で管理されているオブジェクトのイベントに興味がある場合(例：名前空間 `my-namespace`のPods で何が起こったか)コマンドに名前空間を明示的に指定する必要があります。
```suggestion
しかし、イベントは名前空間に所属することを忘れてはいけません。つまり、名前空間で管理されているオブジェクトのイベントに興味がある場合(例：名前空間 `my-namespace`のPods で何が起こったか)、コマンドに名前空間を明示的に指定する必要があります。
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +`kubectl describe pod`に加えて、(`kubectl get pod` で提供される以上の)Podに関する追加情報を得るためのもう一つの方法は、`-o yaml`出力形式フラグを `kubectl get pod`に渡すことです。これにより、`kubectl describe pod`よりもさらに多くの情報、つまりシステムが持っているPodに関するすべての情報をYAML形式で
```suggestion
`kubectl describe pod`に加えて、(`kubectl get pod` で提供される以上の)Podに関する追加情報を得るためのもう一つの方法は、`-o yaml`出力形式フラグを `kubectl get pod`に渡すことです。これにより、`kubectl describe pod`よりもさらに多くの情報、つまりシステムが持っているPodに関するすべての情報をYAML形式で得ることができます。ここでは、アノテーション(Kubernetesのシステムコンポーネントが内部的に使用している、ラベル制限のないキーバリューのメタデータ)、再起動ポリシー、ポート、ボリュームなどが表示されます。
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +## 例：ダウン／到達不可能なノードのデバッグ
```suggestion
## 例: ダウン/到達不可能なノードのデバッグ
```

2021-12-27 15:30 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +例えば、ノード上で動作しているPodのおかしな挙動に気付いたり、Podがノード上でスケジュールされない原因を探ったりと、デバッグ時にノードのステータスを見ることが有用な場合があります。Podと同様に、`kubectl describe node`や`kubectl get node -o yaml`を使ってノードの詳細情報を取得することができます。例えば、ノードがダウンした場合（ネットワークから
```suggestion
例えば、ノード上で動作しているPodのおかしな挙動に気付いたり、Podがノード上でスケジュールされない原因を探ったりと、デバッグ時にノードのステータスを見ることが有用な場合があります。Podと同様に、`kubectl describe node`や`kubectl get node -o yaml`を使ってノードの詳細情報を取得することができます。例えば、ノードがダウンした場合(ネットワークから切断された、またはkubeletが死んで再起動しないなど)に表示される内容は以下の通りです。ノードがNotReadyであることを示すイベントに注目してください。また、ポッドが実行されなくなっていることにも注目してください(NotReady状態が5分続くと、Podは退避されます)。
```

2021-12-28 03:47 UTC, nasa9084 requested changes

2021-12-28 03:47 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +例えば、ノード上で動作しているPodのおかしな挙動に気付いたり、Podがノード上でスケジュールされない原因を探ったりと、デバッグ時にノードのステータスを見ることが有用な場合があります。Podと同様に、`kubectl describe node`や`kubectl get node -o yaml`を使ってノードの詳細情報を取得することができます。例えば、ノードがダウンした場合(ネットワークから
```suggestion
例えば、ノード上で動作しているPodのおかしな挙動に気付いたり、Podがノード上でスケジュールされない原因を探ったりと、デバッグ時にノードのステータスを見ることが有用な場合があります。Podと同様に、`kubectl describe node`や`kubectl get node -o yaml`を使ってノードの詳細情報を取得することができます。例えば、ノードがダウンした場合(ネットワークから切断された、またはkubeletが死んで再起動しないなど)に表示される内容は以下の通りです。ノードがNotReadyであることを示すイベントに注目してください。また、Podが実行されなくなっていることにも注目してください(NotReady状態が5分続くと、Podは退避されます)。
```

2021-12-28 03:47 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +しかし、イベントは名前空間に所属することを忘れてはいけません。つまり、名前空間で管理されているオブジェクトのイベントに興味がある場合(例：名前空間 `my-namespace`のPods で何が起こったか)、コマンドに名前空間を明示的に指定する必要があります。
```suggestion
しかし、イベントは名前空間に所属することを忘れてはいけません。つまり、名前空間で管理されているオブジェクトのイベントに興味がある場合(例: 名前空間 `my-namespace`のPods で何が起こったか)、コマンドに名前空間を明示的に指定する必要があります。
```

2021-12-28 03:47 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +イベントを使って検出できる一般的なシナリオは、どのノードにも収まらないPodを作成した場合です。例えば、Podがどのノードでも空いている以上のリソースを要求したり、どのノードにもマッチしないラベルセレクターを指定したりする場合です。例えば、各(仮想)マシンが1つのCPUを持つ4ノードのクラスター上で、(2つではなく)5つのレプリカを持ち、500ではなく600のミリコアを要求する前のDeploym
```suggestion
イベントを使って検出できる一般的なシナリオは、どのノードにも収まらないPodを作成した場合です。例えば、Podがどのノードでも空いている以上のリソースを要求したり、どのノードにもマッチしないラベルセレクターを指定したりする場合です。例えば、各(仮想)マシンが1つのCPUを持つ4ノードのクラスター上で、(2つではなく)5つのレプリカを持ち、500ではなく600ミリコアを要求する前のDeploymentを作成したとします。この場合、Podの1つがスケジュールできなくなります。(なお、各ノードではfluentdやskydnsなどのクラスターアドオンPodが動作しているため、もし1000ミリコアを要求した場合、どのPodもスケジュールできなくなります)
```

2021-12-28 03:47 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +最後に、Podに関連する最近のイベントのログが表示されます。このシステムでは、複数の同一イベントを圧縮して、最初に見られた時刻と最後に見られた時刻、そして見られた回数を示します。"From"はイベントを記録しているコンポーネントを示し、"SubobjectPath"はどのオブジェクト(例：Pod内のコンテナ)が参照されているかを示し、"Reason"と "Message"は何が起こったかを示して
```suggestion
最後に、Podに関連する最近のイベントのログが表示されます。このシステムでは、複数の同一イベントを圧縮して、最初に見られた時刻と最後に見られた時刻、そして見られた回数を示します。"From"はイベントを記録しているコンポーネントを示し、"SubobjectPath"はどのオブジェクト(例: Pod内のコンテナ)が参照されているかを示し、"Reason"と "Message"は何が起こったかを示しています。
```

2021-12-29 13:35 UTC, nasa9084 commented
/approve

2022-01-28 00:11 UTC, ptux commented
/label tide/merge-method-squash

2022-01-29 12:42 UTC, ptux commented
/lgtm

2022-01-29 12:43 UTC, ptux commented
@inductor 

cloud you give an LGTM label?

<img width="796" alt="Screen Shot 0004-01-29 at 21 43 18" src="https://user-images.githubusercontent.com/1912974/151661478-fc5ef3b1-8062-4d7a-b4f3-61a792bf1878.png">

2022-01-30 13:46 UTC, inductor commented
/lgtm

2022-01-30 13:50 UTC, merged