[ja] Translate tasks/debug-application-cluster/crictl into Japanese
kubernetes/website pull request #30881
Opened 2021-12-12 12:39 UTC by ptux

Address #30869

2021-12-17 00:57 UTC, Arhell reviewed
/assign @nasa9084

2021-12-29 13:27 UTC, nasa9084 requested changes

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +- ptux
please remove reviewers block

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +これを使って、Kubernetes ノード上のコンテナランタイムやアプリケーションの検査やデバッグを行うことができます。
```suggestion
これを使って、Kubernetesノード上のコンテナランタイムやアプリケーションの検査やデバッグを行うことができます。
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +`crictl`とそのソースは[cri-tools](https://github.com/kubernetes-sigs/cri-tools)リポジトリにホストされています。
```suggestion
`crictl`とそのソースコードは[cri-tools](https://github.com/kubernetes-sigs/cri-tools)リポジトリにホストされています。
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +`crictl`にはCRIランタイムを搭載した Linux が必要です。
```suggestion
`crictl`にはCRIランタイムを搭載したLinuxが必要です。
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +cri-tools [release page](https://github.com/kubernetes-sigs/cri-tools/releases)から、いくつかの異なるアーキテクチャ用の圧縮アーカイブ`crictl`をダウンロードできます。
```suggestion
cri-toolsの[リリースページ](https://github.com/kubernetes-sigs/cri-tools/releases)から、いくつかの異なるアーキテクチャ用の圧縮アーカイブ`crictl`をダウンロードできます。
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +それを解凍してシステムパス上の`/usr/local/bin/`などの場所に移動します。
```suggestion
それを解凍して`/usr/local/bin/`などのシステムパス上の場所に移動します。
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +実行中のKubernetesクラスターに`crictl`を使ってポッドのサンドボックスやコンテナを作成しても、Kubeletは最終的にそれらを削除します。`crictl` は汎用のワークフローツールではなく、デバッグに便利なツールです。
```suggestion
実行中のKubernetesクラスターに`crictl`を使ってPodのサンドボックスやコンテナを作成しても、Kubeletは最終的にそれらを削除します。`crictl` は汎用のワークフローツールではなく、デバッグに便利なツールです。
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +すべてのポッドをリストアップ:
```suggestion
すべてのPodをリストアップ:
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +ランニングコンテナをリストアップします:
```suggestion
実行中のコンテナをリストアップします:
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +稼働中のKubernetesクラスタでは、サンドボックスは最終的にKubeletによって停止され、削除されます。
```suggestion
稼働中のKubernetesクラスターでは、サンドボックスは最終的にKubeletによって停止され、削除されます。
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +2. Podとコンテナのコンフィグを作成します:
```suggestion
2. Podとコンテナの設定を作成します:
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +4.  すべてのコンテナをリストアップし、新しく作成されたコンテナのステートが`Created`に設定されていることを確認します:
```suggestion
4.  すべてのコンテナをリストアップし、新しく作成されたコンテナの状態が`Created`に設定されていることを確認します:
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +`attach` | `attach` | ランニングコンテナにアタッチ | `--detach-keys`, `--sig-proxy`
```suggestion
`attach` | `attach` | 実行中のコンテナにアタッチ | `--detach-keys`, `--sig-proxy`
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +`exec` | `exec` | ランニングコンテナにコマンドの実行 | `--privileged`, `--user`, `--detach-keys`
```suggestion
`exec` | `exec` | 実行中のコンテナでコマンドの実行 | `--privileged`, `--user`, `--detach-keys`
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +`version` | `version` | ランタイム（Docker、ContainerD、その他）のバージョン情報を表示します |  
```suggestion
`version` | `version` | ランタイム(Docker、ContainerD、その他)のバージョン情報を表示します |  
```

2021-12-29 13:27 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +`pull` | `pull` | レジストリからイメージやリポジトリをプルします | `--all-tags`, `--disable-content-trust`
```suggestion
`pull` | `pull` | レジストリーからイメージやリポジトリをプルします | `--all-tags`, `--disable-content-trust`
```

2021-12-29 15:32 UTC, nasa9084 commented
/cc @riita10069

2022-01-02 10:41 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +実行中のKubernetesクラスターに`crictl`を使ってポッドのサンドボックスやコンテナを作成しても、Kubeletは最終的にそれらを削除します。`crictl` は汎用のワークフローツールではなく、デバッグに便利なツールです。
```suggestion
実行中のKubernetesクラスターに`crictl`を使ってPodのサンドボックスやコンテナを作成しても、Kubeletは最終的にそれらを削除します。`crictl`は汎用のワークフローツールではなく、デバッグに便利なツールです。
```

2022-01-02 15:29 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/crictl.md
> +4.  すべてのコンテナをリストアップし、新しく作成されたコンテナのステートが`Created`に設定されていることを確認します:
```suggestion
4. すべてのコンテナをリストアップし、新しく作成されたコンテナの状態が`Created`に設定されていることを確認します:
```

2022-01-03 14:15 UTC, riita10069 commented
/lgtm

2022-01-13 09:23 UTC, inductor commented
/approve

2022-01-13 09:28 UTC, merged