Remove docker from Node-pressure Eviction #30896
kubernetes/website pull request #30913
Opened 2021-12-14 06:28 UTC by killerkc12

On line 238, removed docker from the examples of system daemons.

2021-12-14 17:01 UTC, natalisucks commented
/check-cla

2021-12-14 20:23 UTC, chrisnegus commented
@killerkc12 Thanks for your contribution. Please [sign the CLA]( https://git.k8s.io/community/CLA.md#the-contributor-license-agreement) so we can accept this PR for review.

2021-12-14 20:25 UTC, chrisnegus commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +of another pod's resource consumption. If a system daemon (such as `kubelet`,
```suggestion
of another pod's resource consumption. If a system daemon (such as `kubelet` 
```

2021-12-14 21:33 UTC, bradtopol commented
/recheck

2021-12-14 21:33 UTC, bradtopol commented
/retest

2021-12-15 00:31 UTC, Arhell reviewed
/check-cla

2021-12-15 06:02 UTC, killerkc12 commented
I've signed the cla.
May I know the next step now

2021-12-15 06:45 UTC, divya-mohan0209 commented
/check-cla

2021-12-15 06:46 UTC, divya-mohan0209 requested changes
Please make the changes @chrisnegus has requested once the CLA has been signed.

2021-12-15 08:50 UTC, killerkc12 commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +of another pod's resource consumption. If a system daemon (such as `kubelet`,
Thank you so much

2021-12-15 08:51 UTC, killerkc12 commented
changes are done

2021-12-15 09:14 UTC, divya-mohan0209 commented
@killerkc12 : Please sign the CLA for us to review.

2021-12-15 09:29 UTC, sftim commented
We're migrating CLA signing bots. See https://github.com/kubernetes/website/pull/30913/files#issuecomment-993201599 for details on how to sign with the one that's authoritative.

2021-12-15 09:30 UTC, sftim reviewed
An optional tweak. Fine to merge this as-is.

2021-12-15 09:30 UTC, sftim commented on content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +and `journald`) is consuming more resources than were reserved via
```suggestion
of another pod's resource consumption. If a system daemon (such as `kubelet`
`journald`, or your container runtime) is consuming more resources than were reserved via
```

2021-12-15 09:42 UTC, divya-mohan0209 commented
Hello @killerkc12 , as @sftim said please refer to https://github.com/kubernetes/website/pull/30913#issuecomment-993201599 to sign the linux foundation CLA. Further steps on how to do so are provided in the details section.

2021-12-15 10:15 UTC, killerkc12 commented
> Hello @killerkc12 , as @sftim said please refer to [#30913 (comment)](https://github.com/kubernetes/website/pull/30913#issuecomment-993201599) to sign the linux foundation CLA. Further steps on how to do so are provided in the details section.

I signed it and I got mail as well

2021-12-15 10:27 UTC, divya-mohan0209 commented
Please could you squash & merge the commits to one? I'll sign off and approve after this.

2021-12-15 10:43 UTC, killerkc12 commented
> Please could you squash & merge the commits to one? I'll sign off and approve after this.

yes

2021-12-15 11:32 UTC, killerkc12 commented
@divya-mohan0209 I squash and merged the commits

2021-12-15 11:39 UTC, divya-mohan0209 commented
@killerkc12 - can still see three commits instead of one.  please could you follow the guidelines at - https://www.kubernetes.dev/docs/guide/github-workflow/#squash-commits

2021-12-15 11:48 UTC, killerkc12 commented
> @killerkc12 - can still see three commits instead of one. please could you follow the guidelines at - https://www.kubernetes.dev/docs/guide/github-workflow/#squash-commits

Done.
The first time, I'm contributing to cncf.
But thank you so much @divya-mohan0209  for helping me throughout.

2021-12-15 11:53 UTC, divya-mohan0209 commented
Taking the approval for merge as-is from [this comment](https://github.com/kubernetes/website/pull/30913#pullrequestreview-832543357) by @sftim and adding lgtm + approve.
/lgtm
/approve

2021-12-15 11:54 UTC, merged