[zh] Translate audit API reference
kubernetes/website pull request #30967
Opened 2021-12-15 07:27 UTC by tengqm

/language zh

2021-12-15 09:47 UTC, howieyuen requested changes

2021-12-15 09:47 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   为每个请求所生成的唯一性的审计 ID。
为每个请求所生成唯一审计 ID。

2021-12-15 09:47 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   关于所扮演（impersonated）的用户的信息。
译成“伪装”怎样？

2021-12-15 09:47 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
>  <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#userinfo-v1-authentication"><code>authentication/v1.UserInfo</code></a>
newest en doc use api version of 1.21

2021-12-15 09:47 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   此请求所指向的对象引用。对于 List 类型的请求或者非自愿请求，此字段可忽略。
typo：对于非资源请求

2021-12-15 09:47 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   合法的对象。对于非自愿请求，此字段被忽略。
typo：对于非资源请求

2021-12-16 11:05 UTC, tengqm commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   为每个请求所生成的唯一性的审计 ID。
OK

2021-12-16 11:06 UTC, tengqm commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   关于所扮演（impersonated）的用户的信息。
伪装似乎带点儿贬义味道，也行。

2021-12-16 11:07 UTC, tengqm commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
>  <a href="https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#userinfo-v1-authentication"><code>authentication/v1.UserInfo</code></a>
sure

2021-12-16 11:13 UTC, tengqm commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   为每个请求所生成的唯一性的审计 ID。
“唯一审计ID”比较难理解，有意啰嗦了一点。

2021-12-16 11:22 UTC, howieyuen commented
/lgtm

2021-12-16 11:23 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-audit.v1.md
> +   关于所扮演（impersonated）的用户的信息。
确实有点贬义的味道……

2021-12-20 02:41 UTC, howieyuen commented
/lgtm

2022-01-01 12:28 UTC, tanjunchen reviewed
/approve

2022-01-01 12:30 UTC, merged