[zh] Translation of the kube-proxy configuration struct
kubernetes/website pull request #30973
Opened 2021-12-15 09:06 UTC by tengqm

/language zh

2021-12-20 03:19 UTC, howieyuen requested changes

2021-12-20 03:19 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-proxy-config.v1alpha1.md
> +   contentType 是从此客户端向服务器发送数据时使用的内容类型（Content Type）。）
extra right bracket '）'

2021-12-20 03:19 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-proxy-config.v1alpha1.md
> +VModuleConfiguration 是一组文件名或文件名模式，及其对应的日志详尽程度阈值配置。
missing original en text

2021-12-20 03:21 UTC, howieyuen commented
I have to say, every time I review @tengqm PR, just like read the doc, not to correct but to study.
Good Job 👍

2021-12-29 09:33 UTC, howieyuen commented
/lgtm

2022-02-12 12:58 UTC, tanjunchen reviewed
/approve

2022-02-12 12:59 UTC, merged