[ja] Translate tasks/debug-application-cluster/local-debugging into Japanese
kubernetes/website pull request #30981
Opened 2021-12-15 14:21 UTC by ptux

Address #30877

2021-12-15 14:43 UTC, ptux commented
/assign @inductor

2021-12-29 10:54 UTC, nasa9084 requested changes
I'm verry sorry to be late to review, however the base page has big update 10 days ago...

/cc @kakts @bells17 @makocchi-git

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +- ptux
reviewersブロックは削除して下さい

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +Kubernetesアプリケーションは通常、複数の独立したサービスから構成され、それぞれが独自のコンテナで動作しています。これらのサービスをリモートのKubernetesクラスタ上で開発・デバッグするには、[get a shell on a running container](/docs/task/debug-application-cluster/get-shell-running-cont
```suggestion
Kubernetesアプリケーションは通常、複数の独立したサービスから構成され、それぞれが独自のコンテナで動作しています。これらのサービスをリモートのKubernetesクラスター上で開発・デバッグするには、[get a shell on a running container](/docs/task/debug-application-cluster/get-shell-running-container/)してリモートシェル内でツールを実行しなければならず面倒な場合があります。
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +`telepresence`は、リモートKubernetesクラスタにサービスをプロキシングしながら、ローカルでサービスを開発・デバッグするプロセスを容易にするためのツールです。
```suggestion
`telepresence`は、リモートKubernetesクラスターにサービスをプロキシングしながら、ローカルでサービスを開発・デバッグするプロセスを容易にするためのツールです。
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +`telepresence` を使用すると、デバッガや IDE などのカスタムツールをローカルサービスで使用でき、ConfigMap や secret、リモートクラスタ上で動作しているサービスへのフルアクセスをサービスに提供します。
```suggestion
`telepresence` を使用すると、デバッガーやIDEなどのカスタムツールをローカルサービスで使用でき、ConfigMapやsecret、リモートクラスター上で動作しているサービスへのフルアクセスをサービスに提供します。
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +* Kubernetesクラスタがインストールされていること
```suggestion
* Kubernetesクラスターがインストールされていること
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +* クラスタと通信するために `kubectl` が設定されていること
```suggestion
* クラスターと通信するために `kubectl` が設定されていること
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +* telepresence(https://www.telepresence.io/reference/install)がインストールされていること
```suggestion
* [telepresence](https://www.telepresence.io/reference/install)がインストールされていること
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +## リモートクラスタ上でシェルの取得
```suggestion
## リモートクラスター上でシェルの取得
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +例えば、ラップトップでシェルスクリプトを書いて、それをシェルから直接リアルタイムで実行することができます。これはリモートシェルでもできますが、好みのコードエディタが使えないかもしれませんし、コンテナが終了するとスクリプトは削除されます。
```suggestion
例えば、ラップトップでシェルスクリプトを書いて、それをシェルから直接リアルタイムで実行することができます。これはリモートシェルでもできますが、好みのコードエディターが使えないかもしれませんし、コンテナが終了するとスクリプトは削除されます。
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +Use the `--swap-deployment` option to swap an existing deployment with the Telepresence proxy. Swapping allows you to run a service locally and connect to the remote Kubernetes cluster. The services
これらのブロックは消し忘れだと思います

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +既存のデプロイメントとtelepresenceプロキシを交換するには、`--swap-deployment` オプションを使用します。
```suggestion
既存のデプロイメントとtelepresenceプロキシーを交換するには、`--swap-deployment` オプションを使用します。
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +スワップすることで、ローカルでサービスを実行し、リモートのKubernetesクラスタに接続することができます。
```suggestion
スワップすることで、ローカルでサービスを実行し、リモートのKubernetesクラスターに接続することができます。
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +リモートクラスタ内のサービスは、ローカルで実行されているインスタンスにアクセスできるようになりました。
```suggestion
リモートクラスター内のサービスは、ローカルで実行されているインスタンスにアクセスできるようになりました。
```

2021-12-29 10:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +また、デバッガやその他のローカルな開発ツールでサービスを実行することもできます。
```suggestion
また、デバッガーやその他のローカルな開発ツールでサービスを実行することもできます。
```

2021-12-29 15:32 UTC, nasa9084 commented
/cc @riita10069

2022-01-02 10:36 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +
```suggestion
```

2022-01-02 10:36 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +このドキュメントでは、リモートクラスタ上で動作しているサービスをローカルで開発・デバッグするために `telepresence` を使用する方法を説明します。
```suggestion
このドキュメントでは、リモートクラスタ上で動作しているサービスをローカルで開発・デバッグするために`telepresence`を使用する方法を説明します。
```

2022-01-02 10:36 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +もしハンズオンのチュートリアルに興味があるなら、Google Kubernetes Engine上でGuestbookアプリケーションをローカルに開発する手順を説明した[this tutorial](https://cloud.google.com/community/tutorials/developing-services-with-k8s)をチェックしてみてください。
```suggestion
もしハンズオンのチュートリアルに興味があるなら、Google Kubernetes Engine上でGuestbookアプリケーションをローカルに開発する手順を説明した[こちらのチュートリアル](https://cloud.google.com/community/tutorials/developing-services-with-k8s)をチェックしてみてください。
```

2022-01-12 16:13 UTC, nasa9084 commented
see folded comments too

2022-01-27 13:54 UTC, nasa9084 requested changes

2022-01-27 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +`telepresence`は、リモートKubernetesクラスターにサービスをプロキシングしながら、ローカルでサービスを開発・デバッグするプロセスを容易にするためのツールです。
```suggestion
`telepresence`は、リモートKubernetesクラスターにサービスをプロキシーしながら、ローカルでサービスを開発・デバッグするプロセスを容易にするためのツールです。
```

2022-01-28 00:01 UTC, ptux commented
/label tide/merge-method-squash

2022-02-21 15:52 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/local-debugging.md
> +ここで、$DEPLOYMENT_NAMEは既存のディプロイメントの名前です。
```suggestion
ここで、$DEPLOYMENT_NAMEは既存のDeploymentの名前です。
```

2022-02-23 16:00 UTC, kakts commented
Thank you for your contribution.

/lgtm

2022-03-04 06:12 UTC, nasa9084 commented
/approve

2022-03-04 06:14 UTC, merged