[ja] Translate tasks/debug-application-cluster/troubleshooting into Japanese
kubernetes/website pull request #30997
Opened 2021-12-16 13:44 UTC by ptux

resolve #30875

2021-12-16 14:07 UTC, ptux commented
/assign @inductor

2021-12-29 11:01 UTC, nasa9084 requested changes

2021-12-29 11:01 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/troubleshooting.md
> +[`#kubernetes-novice`](https://kubernetes.slack.com/messages/kubernetes-novice)
```suggestion
たとえば、Kubernetesの初心者は、[`#kubernetes-novice`](https://kubernetes.slack.com/messages/kubernetes-novice)に参加してみるのもよいでしょう。
```

2021-12-29 11:01 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/troubleshooting.md
> +また、多くの国別／現地語チャンネルがあります。これらのチャンネルに参加すれば、地域特有のサポートや情報を得ることができます。
```suggestion
また、多くの国別/言語別チャンネルがあります。これらのチャンネルに参加すれば、地域特有のサポートや情報を得ることができます。
```

「国別」に対比するかたちの方が読みやすそうです

2021-12-29 11:01 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/troubleshooting.md
> +GitHub課題追跡システム](https://github.com/kubernetes/kubernetes/issues)をご利用ください。
```suggestion
バグらしきものを発見した場合、または機能要望を出したい場合、[GitHub課題追跡システム](https://github.com/kubernetes/kubernetes/issues)をご利用ください。
```

2022-01-28 07:47 UTC, ptux commented
/label tide/merge-method-squash

2022-03-08 03:46 UTC, ptux commented
@nasa9084

Cloud you take a look at this PR?

2022-03-21 12:47 UTC, nasa9084 commented
see 2 comments I left before

2022-03-22 00:07 UTC, ptux commented
@nasa9084 

fixed.

2022-03-28 10:30 UTC, nasa9084 reviewed
/lgtm

2022-05-10 07:22 UTC, ptux commented
@inductor 

Cloud you take a look at this pr?

2022-05-11 13:41 UTC, nasa9084 commented
/lgtm cancel
/approve
/cc @kakts @makocchi-git @riita10069

2022-05-13 15:34 UTC, bells17 commented
/lgtm

2022-05-13 15:35 UTC, merged