[es] Add concepts/security/controlling-access.md
kubernetes/website pull request #31017
Opened 2021-12-18 02:27 UTC by gamba47

Se añade la documentación en español para:

[es] Add concepts/security/controlling-access.md

2021-12-18 02:35 UTC, gamba47 commented
/assign @electrocucaracha

Me tira el error de firma todavia, pero ya firme y recibí el documento en mi casilla.

2021-12-18 15:58 UTC, electrocucaracha commented
> /assign @electrocucaracha
> 
> Me tira el error de firma todavia, pero ya firme y recibí el documento en mi casilla.

Parece ser que solo era cuestión de esperar

2021-12-29 14:57 UTC, raelga requested changes
Gracias por la PR @gamba47, te dejo algunos comentarios que habría que revisar. 

:)

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Esta pagina proporciona información sobre el como controlar el acceso a la API de Kubernetes.
```suggestion
Esta página proporciona información sobre cómo controlar el acceso a la API de Kubernetes.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +client libraries, o haciendo peticiones REST.  Humanos y los
```suggestion
bibliotecas de cliente, o haciendo peticiones REST.  Usuarios y
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Cuando una peticion llega a la API, pasa por varias etapas, estan ilustradas en el
```suggestion
Cuando una petición llega a la API, pasa por varias etapas, están ilustradas en el
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +El server API presenta un certificado. Este certificado puede ser firmando usando
```suggestion
El {{< glossary_tooltip term_id="kube-apiserver" text="API Server" >}} presenta un certificado. Este certificado puede ser firmando usando
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +un certificado de autoridad privada (CA) o basado en una llave publica relacionada
```suggestion
un certificado de autoridad privada (CA) o basado en una llave pública relacionada
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +En un cluster típico de Kubernetes, la API sirve peticiones en el puerto 443, protegida por TLS.
```suggestion
En un {{< glossary_tooltip term_id="cluster" text="cluster" >}}  típico de Kubernetes, la API sirve peticiones en el puerto 443, protegida por TLS.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +CA configurado dentro de su `~/.kube/config` en el cliente, entonces usted podrá
```suggestion
CA configurado dentro de su `~/.kube/config` en el cliente, entonces se podrá
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +confiar en la conección y estar seguro que no será hackeada.
```suggestion
confiar en la conexión y estar seguro que no será comprometida.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Su cliente puede presentar un certificado TLS de cliente en esta etapa.
```suggestion
El cliente puede presentar un certificado TLS de cliente en esta etapa.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +## Transport security
```suggestion
## Seguridad en la capa de transporte
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Una vez que se estableció el TLS, las peticiones HTTP avanzan a la etapa de autenticación.
```suggestion
Una vez que se estableció la conexión TLS, las peticiones HTTP avanzan a la etapa de autenticación.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +El script de creación del cluster o el administrador del cluster configurada el servidor API para ejecutar
```suggestion
El script de creación del cluster o el administrador del cluster puede configurar el {{< glossary_tooltip term_id="kube-apiserver" text="API Server" >}} para ejecutar
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Los Autenticadores estan descriptos con más detalle en
```suggestion
Los Autenticadores están descritos con más detalle en
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +```
```suggestion
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +El ingreso al paso de autenticación es la petición HTTP completa, aun así, esta tipicamente
```suggestion
La entrada al paso de autenticación es la petición HTTP completa, aun así, esta tipicamente
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Multiples modulos de autenticación puede ser especificados, en este caso cada uno es probado secuencialmente,
```suggestion
Múltiples módulos de autenticación puede ser especificados, en este caso cada uno es probado secuencialmente,
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Si la petición no puede ser autenticada, la misma es rechazada con un codigo de estado HTTP  401.
```suggestion
Si la petición no puede ser autenticada, la misma es rechazada con un código HTTP 401.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +En otro caso, el usuario es validado con el `username` específico, y el nombre de usuario
```suggestion
Si la autenticación tiene éxito, el usuario es validado con el `username` específico, y el nombre de usuario
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +tambien proporcionan membresías de grupo al usuario, mientras que otros
```suggestion
también proporcionan membresías de grupo al usuario, mientras que otros
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Despues de autenticar la petición como proveniente de un usuario específico, la petición debe ser autorizada. Esto se muestra en el paso 2 del diagrama.
```suggestion
Después de autenticar la petición como proveniente de un usuario específico, la petición debe ser autorizada. Esto se muestra en el paso 2 del diagrama.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Una petición debe incluir el nombre de usuario solicitante, la acción solicitada y el objeto afectado por la acción. La petición es autorizada si hay una politica existente que declare que el usuario
```suggestion
Una petición debe incluir el nombre de usuario solicitante, la acción solicitada y el objeto afectado por la acción. La petición es autorizada si hay una política existente que declare que el usuario tiene permisos para la realizar la acción.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Por ejemplo, si Bob tiene la siguiente politica, entonces el puede leer pods solamente en el namespace `projectCaribou`:
```suggestion
Por ejemplo, si el usuario Bob tiene la siguiente política, entonces puede leer pods solamente en el namespace `projectCaribou`:
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +de ellos en su API.
```suggestion
Aunque Kubernetes utiliza los nombres de usuario para tomar decisiones durante el control de acceso y para registrar las peticiones de entrada, no tiene un objeto `User` ni tampoco almacena información sobre los usuarios en la API.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Si Bob hace la siguiente petición, será aturizada porque él tiene permitido leer los objetos en el namespace `projectCaribou` :
```suggestion
Si Bob hace la siguiente petición, será autorizada dado que tiene permitido leer los objetos en el namespace `projectCaribou` :
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Si Bob en su petición intenta escribir (`create` o `update`) en los objetos del namespace `projectCaribou`. Si Bob hace una petición para leer (`get`) objetocs en otro namespace como `projectFish`, e
```suggestion
En cambio, si Bob en su petición intenta escribir (`create` o `update`) en los objetos del namespace `projectCaribou`, la petición será denegada. Del mismo modo, si Bob hace una petición para leer (`get`) objetos en otro namespace como `projectFish`, la autorización también será denegada.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Kubernetes soporta multiples modulos de autorización, como el modo ABAC, el modo RBAC y el modo Webhook. Cuando un administrador crea un cluster, se realiza la configuración de los modulos de autoriz
```suggestion
Kubernetes soporta múltiples módulos de autorización, como el modo ABAC, el modo RBAC y el modo Webhook. Cuando un administrador crea un cluster, se realiza la configuración de los módulos de autorización que deben ser usados con la API del server. Si más de uno módulo de autorización es configurado, Kubernetes verificada cada uno y si alguno de ellos autoriza la petición entonces la misma se ejecuta. Si todos los modules deniegan la petición, entonces la misma es denegada (Con un error HTTP con código 403).
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Para leer más acerca de las autorizaciones en Kubernetes, incluyendo detalles acerca de crear politicas usando los modulos de autorización soportados, vea [Authorization](/docs/reference/access-authn
```suggestion
Para leer más acerca de las autorizaciones en Kubernetes, incluyendo detalles sobre cómo crear politicas usando los módulos de autorización soportados, vea [Authorization](/docs/reference/access-authn-authz/authorization/).
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +- como los pods pueden usar
```suggestion
- Como los pods pueden usar
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Lea mas documentación sobre autenticación, autorización y el contro de acceso a la API:
```suggestion
En los siguientes enlaces, encontrará mucha más documentación sobre autenticación, autorización y el control de acceso a la API:
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Tambien puede aprender sobre:
```suggestion
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Los modulos de Control de Admisión son modulos de software que solo pueen modificar o rechazar peticiones.
```suggestion
Los módulos de Control de Admisión son módulos de software que solo pueden modificar o rechazar peticiones.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Adicionalmente a los atributos disponibles en los modulos de Autorización, los modulos de
```suggestion
Adicionalmente a los atributos disponibles en los módulos de Autorización, los de
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Los Controles de Admisión actúan en las peticiones que crean, modifican, borran ó se conectan (proxy) a un objeto.
```suggestion
Los Controles de Admisión actúan en las peticiones que crean, modifican, borran o se conectan (proxy) a un objeto.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +cuando multiples modulos de control de admisión son configurados, son llamados en orden.
```suggestion
Cuando múltiples módulos de control de admisión son configurados, son llamados en orden.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +A diferencia de los modulos de Autorización y Autenticación, si uno de los modulos de control de admisión
```suggestion
A diferencia de los módulos de Autorización y Autenticación, si uno de los módulos de control de admisión
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Adicionalmente a rechazar objetos, los controles de admisión pueden tambien permite establecer
```suggestion
Adicionalmente a rechazar objetos, los controles de admisión también permiten establecer
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +Los modulos de Control de Admisión disponibles están descriptos en [Admission Controllers](/docs/reference/access-authn-authz/admission-controllers/).
```suggestion
Los módulos de Control de Admisión disponibles están descritos en [Admission Controllers](/docs/reference/access-authn-authz/admission-controllers/).
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - request **bypasses** authentication and authorization modules.
```suggestion
      - la petición no pasa por los mecanismos de autenticación ni autorización
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - protejidas por necesidad para tener acceso al host
```suggestion
      - protegidas por necesidad para tener acceso al host
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - usa TLS.  Se configura el certificado con el flag `--tls-cert-file` y la llave con `--tls-private-key-file`.
```suggestion
      - usa TLS. Se configura el certificado con el flag `--tls-cert-file` y la clave con `--tls-private-key-file`.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - el puerto predeterminado es 6443, se cambia con el flag `--secure-port`.
```suggestion
      - el puerto predeterminado es `6443`, se cambia con el flag `--secure-port`.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - el puerto predeterminado es el 8080
```suggestion
      - el puerto predeterminado es el `8080`
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - la IP por defecto es la primer interface que no es la localhost. se cambia con el flag `--bind-address`.
```suggestion
      - la IP por defecto es la de la primera interfaz de red que no es la localhost. Se cambia con el flag `--bind-address`.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - peticiones controladas por los modulos de autenticación y autorización.
```suggestion
      - peticiones controladas por los módulos de autenticación y autorización.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - peticiones controladas por los modulos de control de admisión.
```suggestion
      - peticiones controladas por los módulos de control de admisión.
```

2021-12-29 14:57 UTC, raelga commented on content/es/docs/concepts/security/controlling-access.md
> +      - authentication and authorization modules run.
```suggestion
```
Redundante.

2021-12-29 15:42 UTC, gamba47 commented on content/es/docs/concepts/security/controlling-access.md
> +Los Autenticadores estan descriptos con más detalle en
Estoy en argentina y acá usamos la P para esta palabra, pero me parece mejor seguir la idea internacional y a lo sumo usar la española que es la lengua madre de todas.

2021-12-29 15:53 UTC, gamba47 commented
> Gracias por la PR @gamba47, te dejo algunos comentarios que habría que revisar.
> 
> :)

Review aceptado, para la próxima voy a ser más prolijo, me faltaron muchos acentos, perdon por eso.

2021-12-29 18:31 UTC, gamba47 commented
Reopen this pr, was a mistake.

2021-12-29 21:01 UTC, raelga commented
Muchas gracias @gamba47, por mi parte lo veo perfecto! 

/lgtm

2021-12-29 21:02 UTC, raelga approved these changes

2021-12-29 21:05 UTC, merged