[zh] Translate scheduler config API v1beta3
kubernetes/website pull request #31018
Opened 2021-12-18 06:29 UTC by tengqm

/language zh

2021-12-18 18:29 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta3.md
> +   <code>addedAffinity</code> 会作为附加的亲和性属性添加到所有 Pods 的
这个原文是不是 也应该要加上 `<code>`?

2021-12-18 18:38 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta3.md
> +   服务器端可信任的根证书。
```suggestion
   服务器端被信任的根证书。
```

2022-02-21 06:55 UTC, tengqm commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta3.md
> +   <code>addedAffinity</code> 会作为附加的亲和性属性添加到所有 Pods 的
不好处理。

2022-02-21 06:56 UTC, tengqm commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta3.md
> +   <code>addedAffinity</code> 会作为附加的亲和性属性添加到所有 Pods 的
英文原文的拼写方式也是错的。

2022-02-22 07:02 UTC, howieyuen requested changes

2022-02-22 07:02 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta3.md
> +   <code>addedAffinity</code> 会作为附加的亲和性属性添加到所有 Pods 的
```suggestion
   <code>addedAffinity</code> 会作为附加的亲和性属性添加到所有 Pod 的
```

2022-02-22 07:02 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta3.md
> +   <code>queueSort</code> 是一个在对调度队列中 Pods 排序时要调用的插件列表。
```suggestion
   <code>queueSort</code> 是一个在对调度队列中 Pod 排序时要调用的插件列表。
```

2022-02-23 05:09 UTC, howieyuen commented
/lgtm

2022-03-03 02:35 UTC, howieyuen commented
/approve

2022-03-03 02:36 UTC, merged