[zh] Translate kube-scheduler config API v1beta2
kubernetes/website pull request #31021
Opened 2021-12-18 12:27 UTC by tengqm

2022-02-10 12:38 UTC, howieyuen requested changes

2022-02-10 12:38 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +   preempt 调用所使用的动词，如果不支持过滤操作则为空。
```suggestion
   preempt 调用所使用的动词，如果不支持抢占操作则为空。
```

2022-02-10 12:38 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +   prioritize 调用所使用的动词，如果不支持过滤操作则为空。
```suggestion
   prioritize 调用所使用的动词，如果不支持优先调用则为空。
```

2022-02-10 12:38 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +   bind 调用所使用的动词，如果不支持过滤操作则为空。
```suggestion
   bind 调用所使用的动词，如果不支持绑定操作则为空。
```

2022-02-10 12:38 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +prioritize 和 bind （如果扩展模块可以执行绑定操作）阶段被发送到该扩展模块。</li>
missing translation：
"If empty or unspecified, all pods will be sent to this extender."

2022-02-10 12:38 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +   <code>queueSort</code> 是一个在对调度队列中 Pods 排序时要调用的插件列表。
```suggestion
   <code>queueSort</code> 是一个在对调度队列中 Pod 排序时要调用的插件列表。
```

2022-02-11 04:28 UTC, tengqm commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +   <!--
looking into this...

2022-02-11 09:18 UTC, howieyuen commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +   <!--
> 注释掉的文字当中存在空白行时，hugo 处理器会继续解释其内容，当做 markdown 语法。

所以，像这种html标签式的md文档，段落注释不可包含空白行？

2022-02-11 09:34 UTC, tengqm commented on content/zh/docs/reference/config-api/kube-scheduler-config.v1beta2.md
> +   <!--
空白行，缩进等等都可能有影响，取决于 hugo 处理器对文字的解析。

2022-02-22 06:41 UTC, howieyuen commented
/lgtm

2022-03-03 02:35 UTC, howieyuen commented
/approve

2022-03-03 02:40 UTC, merged