[zh] Translate kubeadm config ref v1beta2
kubernetes/website pull request #31030
Opened 2021-12-20 01:30 UTC by tengqm

2021-12-20 01:58 UTC, tengqm commented
preview: https://deploy-preview-31030--kubernetes-io-main-staging.netlify.app/zh/docs/reference/config-api/kubeadm-config.v1beta2/

2021-12-20 07:33 UTC, howieyuen requested changes

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +<li><code>networking</code>：其中包含集群的网络拓扑配置。使用这一部分可以定制 Pod 的
这部分，是特地把大写格式改成代码块，分号变冒号是吗？
这个`<p></p>`标签省略有没有影响？（我从预览中是没看到有什么区别）

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +  <li>在一个包含不止一个控制面实例的集群中，该字段应该设置为放置在控制面
没有标点符号的换行，会渲染出一个空格，样式会不好看，建议合并成一行，或者在逗号处换行。
```suggestion
 <li>在一个包含不止一个控制面实例的集群中，
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +实例之前的外部负载均衡器的地址。</li>
```suggestion
 该字段应该设置为放置在控制面实例之前的外部负载均衡器的地址。</li>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +  <li>在带有强制性节点回收的环境中，<code>controlPlaneEndpoint</code> 可以用来
```suggestion
  <li>在带有强制性节点回收的环境中，
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +为控制面设置一个稳定的 DNS。</li>
```suggestion
<code>controlPlaneEndpoint</code> 可以用来为控制面设置一个稳定的 DNS。</li>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>caCertPath</code> 是指向 SSL 证书机构的路径，该证书包用来加密
```suggestion
   <p><code>caCertPath</code> 是指向 SSL 证书机构的路径，
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +节点与控制面之间的通信。默认值为 &quot;/etc/kubernetes/pki/ca.crt&quot;。</p>
```suggestion
该证书包用来加密节点与控制面之间的通信。
默认值为 &quot;/etc/kubernetes/pki/ca.crt&quot;。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <code>controlPlane</code> 定义要在正被加入到集群中的节点上部署的额外
```suggestion
   <code>controlPlane</code> 定义要在正被加入到集群中的节点上部署的额外控制面实例。
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +控制面实例。此字段为 null 时，不会再上面部署额外的控制面实例。
```suggestion
此字段为 null 时，不会再上面部署额外的控制面实例。
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <span class="text-muted">无描述.</span>
```suggestion
   <span class="text-muted">无描述</span>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>description</code> 设置一个对人友好的消息，说明为什么此令牌
```suggestion
   <p><code>description</code> 设置一个对人友好的消息，
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +会存在以及其目标用途，这样其他管理员能够知道其目的。</p>
```suggestion
说明为什么此令牌会存在以及其目标用途，这样其他管理员能够知道其目的。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>expires</code> 设置此令牌过期的时间戳。默认为在运行时基于
```suggestion
   <p><code>expires</code> 设置此令牌过期的时间戳。
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +<code>ttl</code> 来决定。
```suggestion
默认在运行时基于<code>ttl</code> 来决定。
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>usages</code> 描述此令牌的可能使用方式。默认情况下，令牌可用于
```suggestion
   <p><code>usages</code> 描述此令牌的可能使用方式。默认情况下，
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +建立双向的信任关系；不过这里可以改变默认用途。</p>
```suggestion
令牌可用于建立双向的信任关系；不过这里可以改变默认用途。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +<code>external</code> 是互斥的。
```suggestion
<code>local</code> 和 <code>external</code> 是互斥的。
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +<p>FileDiscovery 用来指定一个文件或者 URL 路径，指向一个 kubeconfig 文件；该配置文件
```suggestion
<p>FileDiscovery 用来指定一个文件或者 URL 路径，指向一个 kubeconfig 文件；
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +可用来加载集群信息。</p>
```suggestion
该配置文件可用来加载集群信息。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>ignorePreflightErrors</code> 提供一组在当前节点被注册时可以
```suggestion
   <p><code>ignorePreflightErrors</code> 提供一组在当前节点被注册时可以忽略掉的预检错误。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +忽略掉的预检错误。</p>
```suggestion

```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +这里的参数会通过 kubeadm 在运行时写入的、由 kubelet 来读取的环境文件来
```suggestion
这里的参数会通过 kubeadm 在运行时写入的、
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +传递给 kubelet 命令行。
```suggestion
由 kubelet 来读取的环境文件来传递给 kubelet 命令行。
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>peerCertSANs</code> 为 etcd 的对等端签名证书设置额外的
```suggestion
   <p><code>peerCertSANs</code> 为 etcd 的对等端签名证书设置额外的主体替代名（Subject Alternative Names，SAN）。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +主体替代名（Subject Alternative Names，SAN）。</p>
```suggestion

```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>serverCertSANs</code> 为 etcd 服务器的签名证书设置额外的
```suggestion
   <p><code>serverCertSANs</code> 为 etcd 服务器的签名证书设置额外的主体替代名（Subject Alternative Names，SAN）。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +主体替代名（Subject Alternative Names，SAN）。</p>
```suggestion

```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +   <p><code>localAPIEndpoint</code> 代表的是将在此节点上部署的 API 服务器实例
```suggestion
   <p><code>localAPIEndpoint</code> 代表的是将在此节点上部署的 API 服务器实例的端点。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +的端点。</p>
```suggestion

```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +<p>JoinControlPlane 包含在正在加入集群的节点上要部署的额外的控制面组件的
```suggestion
<p>JoinControlPlane 包含在正在加入集群的节点上要部署的额外的控制面组件的设置。</p>
```

2021-12-20 07:33 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +设置。</p>
```suggestion
```

2021-12-20 07:34 UTC, howieyuen commented
英语版本的 code 标签 只是渲染成了反引号，而不是MD的代码块特效，这个是什么问题？

2021-12-20 12:42 UTC, tengqm commented
> 英语版本的 code 标签 只是渲染成了反引号，而不是MD的代码块特效，这个是什么问题？

反引号出现在表格中，即`<table>`这种 HTML 标记内时，不再用 markdown 解析。

2021-12-20 12:48 UTC, tengqm commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +<li><code>networking</code>：其中包含集群的网络拓扑配置。使用这一部分可以定制 Pod 的
是的。原注释中使用的是面向开发人员的数据字段名（首字母大写才能被 Go 解释为暴露到包外的字段），
面向读者，这里应该用小写形式，是 YAML 文件中的字段名。
关于这个争论比较多，一直未能说服 sig-cluster-lifecyle

2021-12-20 12:49 UTC, tengqm commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +<li><code>networking</code>：其中包含集群的网络拓扑配置。使用这一部分可以定制 Pod 的
`<p>` 标签没有影响。原来没有这个标签的。
使用 goldmark 解析源代码注释，将其转换成 HTML 时，自动加上去的；一旦加上很难去除，就留下了。

2021-12-20 12:50 UTC, tengqm commented on content/zh/docs/reference/config-api/kubeadm-config.v1beta2.md
> +  <li>在一个包含不止一个控制面实例的集群中，该字段应该设置为放置在控制面
我全文再看一下。

2021-12-22 02:25 UTC, howieyuen commented
> > 英语版本的 code 标签 只是渲染成了反引号，而不是MD的代码块特效，这个是什么问题？
> 
> 反引号出现在表格中，即`<table>`这种 HTML 标记内时，不再用 markdown 解析。

所以这是符合预期的咯？

2021-12-22 02:25 UTC, howieyuen commented
/lgtm

2021-12-22 03:50 UTC, tengqm commented
> > > 英语版本的 code 标签 只是渲染成了反引号，而不是MD的代码块特效，这个是什么问题？
> > 
> > 
> > 反引号出现在表格中，即`<table>`这种 HTML 标记内时，不再用 markdown 解析。
> 
> 所以这是符合预期的咯？

No. 有一部分是 reference generator 的不足，正在改进（https://github.com/kubernetes-sigs/reference-docs/pull/269/files）。这里新提交的版本已经是改进后的输出。

2022-03-03 02:35 UTC, howieyuen commented
/approve

2022-03-03 02:42 UTC, merged