[ja] Translate tasks/debug-application-cluster/resource-usage-monitoring into Japanese
kubernetes/website pull request #31054
Opened 2021-12-21 12:44 UTC by ptux

Address #30872

2021-12-22 02:09 UTC, Arhell reviewed
/assign @nasa9084

2021-12-29 13:32 UTC, nasa9084 requested changes

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +- ptux
please remove reviewers block

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +コンテナ、[Pods](/docs/concepts/workloads/pods/)、[service](/docs/concepts/services-networking/service/)、クラスタ全体の特性を調べることにより、Kubernetesクラスタのアプリケーションパフォーマンスを調査することができます。
```suggestion
コンテナ、[Pod](/docs/concepts/workloads/pods/)、[Service](/docs/concepts/services-networking/service/)、クラスター全体の特性を調べることにより、Kubernetesクラスターのアプリケーションパフォーマンスを調査することができます。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +新しいクラスタでは、[resource metrics](#resource-metrics-pipeline) または [full metrics](#full-metrics-pipeline) パイプラインを使用してモニタリング統計を収集することができます。
```suggestion
新しいクラスターでは、[リソースメトリクス](#resource-metrics-pipeline)または[フルメトリクス](#full-metrics-pipeline)パイプラインを使用してモニタリング統計を収集することができます。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +新しいクラスタでは、[resource metrics](#resource-metrics-pipeline) または [full metrics](#full-metrics-pipeline) パイプラインを使用してモニタリング統計を収集することができます。
加えて、対象の見出しにIDを付けないと正しくアクセスできないですね

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +リソースメトリックパイプラインは、[Horizontal Pod Autoscaler](/docs/tasks/run-application/horizontal-pod-autoscale/)コントローラなどのクラスタコンポーネントや、`kubectl top`ユーティリティに関連する限定的なメトリックセットを提供します。
```suggestion
リソースメトリックパイプラインは、[Horizontal Pod Autoscaler](/docs/tasks/run-application/horizontal-pod-autoscale/)コントローラーなどのクラスターコンポーネントや、`kubectl top`ユーティリティに関連する限定的なメトリックセットを提供します。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +これらのメトリクスは軽量、短期、インメモリの[metrics-server](https://github.com/kubernetes-sigs/metrics-server)によって収集され、`metrics.k8s.io` APIを通じて公開されます。
```suggestion
これらのメトリクスは軽量、短期、インメモリーの[metrics-server](https://github.com/kubernetes-sigs/metrics-server)によって収集され、`metrics.k8s.io` APIを通じて公開されます。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +metrics-serverはクラスタ上のすべてのノードを検出し
```suggestion
metrics-serverはクラスター上のすべてのノードを検出し
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +各ノードの [kubelet](/docs/reference/command-line-tools-reference/kubelet/) にCPUとメモリの使用量を問い合わせます。
```suggestion
各ノードの[kubelet](/docs/reference/command-line-tools-reference/kubelet/)にCPUとメモリーの使用量を問い合わせます。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +kubeletは各ポッドを構成するコンテナに変換し、コンテナランタイムインターフェースを介してコンテナランタイムから個々のコンテナ使用統計情報を取得します。この情報は、レガシーDocker統合のための統合cAdvisorから取得されます。
```suggestion
kubeletは各Podを構成するコンテナに変換し、コンテナランタイムインターフェースを介してコンテナランタイムから個々のコンテナ使用統計情報を取得します。この情報は、レガシーDocker統合のための統合cAdvisorから取得されます。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +そして、集約されたポッドリソース使用統計情報を、metrics-server Resource Metrics APIを通じて公開します。
```suggestion
そして、集約されたPodリソース使用統計情報を、metrics-server Resource Metrics APIを通じて公開します。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +完全なメトリクス・パイプラインは、より豊富なメトリクスにアクセスすることができます。
```suggestion
フルメトリクスパイプラインは、より豊富なメトリクスにアクセスすることができます。
```

どちらでも良いんですが、見出しと合わせた方が良いと思います

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +Kubernetesは、Horizontal Pod Autoscalerなどのメカニズムを使用して、現在の状態に基づいてクラスタを自動的にスケーリングまたは適応させることによって、これらのメトリクスに対応することができます。
```suggestion
Kubernetesは、Horizontal Pod Autoscalerなどのメカニズムを使用して、現在の状態に基づいてクラスターを自動的にスケールまたは適応させることによって、これらのメトリクスに対応することができます。
```

2021-12-29 13:32 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/resource-usage-monitoring.md
> +モニタリングパイプラインは、kubeletからメトリクスをフェッチし、`custom.metrics.k8s.io` または `external.metrics.k8s.io` APIを実装してアダプタ経由でKubernetesにそれらを公開する。
```suggestion
モニタリングパイプラインは、kubeletからメトリクスを取得し、`custom.metrics.k8s.io` または `external.metrics.k8s.io` APIを実装してアダプタ経由でKubernetesにそれらを公開します。
```

2021-12-29 13:32 UTC, nasa9084 commented
/cc @bells17

2022-01-11 15:18 UTC, nasa9084 commented
please check hidden (folded) comments

2022-01-21 09:35 UTC, nasa9084 commented
/approve

2022-01-28 00:10 UTC, ptux commented
/label tide/merge-method-squash

2022-01-29 12:45 UTC, ptux commented
@inductor

cloud you give an LGTM label?

2022-01-30 13:46 UTC, inductor commented
/lgtm

2022-01-30 13:52 UTC, merged