[ja] Translate docs/concepts/architecture/garbage-collection into Japanese
kubernetes/website pull request #31063
Opened 2021-12-22 07:05 UTC by KobayashiD27

close #31061

2021-12-22 07:07 UTC, KobayashiD27 commented
/assign @inductor

2021-12-22 13:33 UTC, ptux commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +ガベージコレクションは、Kubernetesがクラスターリソースをクリーンアップするために使用するさまざまなメカニズムの総称です。これにより、次のようなリソースのクリーンアップが可能になります。:
末尾に余計な`。`入っています。

2021-12-22 13:33 UTC, ptux commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +また、Kubernetes {{<glossary_tooltip text="finalizer" term_id="finalizer">}}を使用して、ガベージコレクションがowner referenceを持つリソースを削除する方法とタイミングを制御することもできます
末尾に`。`抜けています。

2022-01-18 00:52 UTC, KobayashiD27 commented
@inductor  Could you check it out?
Thank you.

2022-02-21 16:19 UTC, nasa9084 requested changes

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * [失敗したPod](/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection)
```suggestion
  * [失敗したPod](/ja/docs/concepts/workloads/pods/pod-lifecycle/#pod-garbage-collection)
```
日本語訳があるので日本語訳リンクに修正お願いします

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * [完了したJob](/docs/concepts/workloads/controllers/ttlafterfinished/)
```suggestion
  * [完了したJob](/ja/docs/concepts/workloads/controllers/ttlafterfinished/)
```
ditto

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * [StorageClassの再利用ポリシーがDeleteである動的にプロビジョニングされたPersistentVolume](/docs/concepts/storage/persistent-volumes/#delete)
```suggestion
  * [StorageClassの再利用ポリシーがDeleteである動的にプロビジョニングされたPersistentVolume](/docs/concepts/storage/persistent-volumes/#delete)
```

同上で、リンク先のIDがない(訳されて日本語のIDになってしまっている)ので、リンク先のID指定もお願いします

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * [失効または期限切れのCertificateSigningRequests (CSRs)](/reference/access-authn-authz/certificate-signing-requests/#request-signing-process)
リンク先がnot foundですね

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +    * クラウド上でクラスターが[クラウドコントローラーマネージャー](/docs/concepts/architecture/cloud-controller/)を使用する場合
```suggestion
    * クラウド上でクラスターが[クラウドコントローラーマネージャー](/ja/docs/concepts/architecture/cloud-controller/)を使用する場合
```
ditto

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * [Node Leaseオブジェクト](/docs/concepts/architecture/nodes/#heartbeats)
```suggestion
  * [Node Leaseオブジェクト](/ja/docs/concepts/architecture/nodes/#heartbeats)
```
ditto

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +ラベルに加えて、サービスに代わって管理される各`EndpointSlice`には、owner referenceがあります。
```suggestion
ラベルに加えて、Serviceに代わって管理される各`EndpointSlice`には、owner referenceがあります。
```
このServiceはService resourceの話をしていると思います

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +namespaceのdependentは、クラスタースコープまたはnamespaceのオーナーを指定できます。
dependentは訳して欲しいというのと、`namespaced` を「namespaceの」と訳してしまうと、owner of namespaceと勘違いしそうなので、「namespace内の」とかの方が良いかもしれません

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +V1.20以降では、ガベージコレクタは無効な名前空間間の`ownerReference`、またはnamespaceのkindを参照する`ownerReference`をもつクラスター・スコープのdependentを検出した場合、無効なdependentの`OwnerRefInvalidNamespace`と`involvedObject`を理由とする警告イベントが報告されます。
ditto

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +`MaxPerPodContainer`と`MaxContainer`は、Podごとのコンテナーの最大数（`MaxPerPodContainer`）を保持すると、グローバルなデッドコンテナーの許容合計（`MaxContainers`）を超える状況で、互いに競合する可能性があります。
```suggestion
`MaxPerPodContainer`と`MaxContainer`は、Podごとのコンテナーの最大数(`MaxPerPodContainer`)を保持すると、グローバルなデッドコンテナの許容合計(`MaxContainers`)を超える状況で、互いに競合する可能性があります。
```

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * [完了したジョブのクリーンアップの設定](/docs/concepts/workloads/controllers/ttlafterfinished/)
```suggestion
  * [完了したジョブのクリーンアップの設定](/ja/docs/concepts/workloads/controllers/ttlafterfinished/)
```
ditto

2022-02-21 16:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +* 完了したジョブをクリーンアップする[TTL controller](/docs/concepts/workloads/controllers/ttlafterfinished/)(beta)について学びます。
```suggestion
* 完了したジョブをクリーンアップする[TTL controller](/ja/docs/concepts/workloads/controllers/ttlafterfinished/)(beta)について学びます。
```
ditto

2022-04-01 06:18 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * [StorageClassの再利用ポリシーがDeleteである動的にプロビジョニングされたPersistentVolume](/docs/concepts/storage/persistent-volumes/#delete)
```suggestion
  * [StorageClassの再利用ポリシーがDeleteである動的にプロビジョニングされたPersistentVolume](/ja/docs/concepts/storage/persistent-volumes/#delete)
```

2022-04-01 06:18 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +さらに、削除されたポッドが所有するコンテナは、`MinAge`より古くなると削除されます。
```suggestion
さらに、削除されたPodが所有するコンテナは、`MinAge`より古くなると削除されます。
```

2022-04-01 06:18 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> +  * `MaxPerPodContainer`: 各ポッドペアが持つことができるデッドコンテナの最大数。`0`未満に設定すると無効化されます。
```suggestion
  * `MaxPerPodContainer`: 各Podのペアが持つことができるデッドコンテナの最大数。`0`未満に設定すると無効化されます。
```

2022-04-01 06:19 UTC, nasa9084 commented on content/ja/docs/concepts/architecture/garbage-collection.md
> + kubeletがガベージコレクションするのは、自分が管理するコンテナーのみです。
```suggestion
 kubeletがガベージコレクションするのは、自分が管理するコンテナのみです。
```

2022-04-01 09:01 UTC, nasa9084 commented
/assign
/approve

2022-04-03 03:13 UTC, ptux commented
/lgtm

2022-04-03 03:14 UTC, merged