[ja] Translate tasks/debug-application-cluster/debug-application into Japanese
kubernetes/website pull request #31089
Opened 2021-12-24 05:19 UTC by ptux

Address #30873

2021-12-25 16:29 UTC, ptux commented
/assign @inductor

2021-12-29 14:04 UTC, nasa9084 requested changes

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +レプリケーションコントローラはかなり単純なものです。
```suggestion
レプリケーションコントローラーはかなり単純なものです。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +もしPodを作成できないのであれば、[instructions above](#debugging-pods)を参照して、Podをデバッグしてください。
```suggestion
もしPodを作成できないのであれば、[上記の説明](#debugging-pods)を参照して、Podをデバッグしてください。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +また、`kubectl describe rc ${CONTROLLER_NAME}`を使用すると、レプリケーションコントローラに関連するイベントをイントロスペクトすることができます。
```suggestion
また、`kubectl describe rc ${CONTROLLER_NAME}`を使用すると、レプリケーションコントローラーに関連するイベントを確認することができます。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +サービスは、ポッドのセット全体でロードバランシングを提供します。
```suggestion
Serviceは、Podの集合全体でロードバランシングを提供します。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +### サービスのデバッグ
```suggestion
### Serviceのデバッグ
```

Podに対してServiceですね

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +サービスが正しく動作しない原因には、いくつかの一般的な問題があります。
```suggestion
Serviceが正しく動作しない原因には、いくつかの一般的な問題があります。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +以下の手順は、サービスの問題をデバッグするのに役立つはずです。
```suggestion
以下の手順は、Serviceの問題をデバッグするのに役立つはずです。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +まず、サービスのエンドポイントが存在することを確認します。
```suggestion
まず、Serviceに対応するEndpointが存在することを確認します。
```
この場合Endpointリソースを指していると思います

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +全てのサービスオブジェクトに対して、apiserverは `endpoints` リソースを利用できるようにします。
```suggestion
全てのServiceオブジェクトに対して、apiserverは `endpoints` リソースを利用できるようにします。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +エンドポイントがサービスのメンバーとして想定されるPod数と一致していることを確認してください。
```suggestion
EndpointがServiceのメンバーとして想定されるPod数と一致していることを確認してください。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +例えば、3つのレプリカを持つnginxコンテナ用のサービスであれば、サービスのエンドポイントには3つの異なるIPアドレスが表示されるはずです。
```suggestion
例えば、3つのレプリカを持つnginxコンテナ用のServiceであれば、ServiceのEndpointには3つの異なるIPアドレスが表示されるはずです。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +#### サービスにエンドポイントがありません
```suggestion
#### Serviceに対応するEndpointがありません
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +エンドポイントが見つからない場合は、サービスが使用しているラベルを使用してポッドをリストアップしてみてください。
```suggestion
Endpointが見つからない場合は、Serviceが使用しているラベルを使用してPodをリストアップしてみてください。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +セレクタに一致するポッドを一覧表示するには、次のコマンドを使用します。
```suggestion
セレクタに一致するPodを一覧表示するには、次のコマンドを使用します。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +リストがサービスを提供する予定のPodと一致することを確認します。
```suggestion
リストがServiceを提供する予定のPodと一致することを確認します。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +Podの`containerPort`がサービスの`targetPort`と一致することを確認します。
```suggestion
Podの`containerPort`がServiceの`targetPort`と一致することを確認します。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +[Debugging Service document](/docs/tasks/debug-application-cluster/debug-service/)で、`Service` が実行されていること、`Endpoints`があること、`Pods`が実際にサービスを提供していること、DNS が機能していること、IPtables ルールがインストールされていること、kube-proxyが誤
```suggestion
[Debugging Service document](/docs/tasks/debug-application-cluster/debug-service/)で、`Service` が実行されていること、`Endpoints`があること、`Pods`が実際にサービスを提供していること、DNS が機能していること、IPtablesルールがインストールされていること、kube-proxyが誤作動を起こしていないようなことを確認してください。
```

2021-12-29 14:04 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +トラブルシューティングドキュメント](/docs/tasks/debug-application-cluster/troubleshooting/)に詳細が記載されています。
```suggestion
[トラブルシューティングドキュメント](/docs/tasks/debug-application-cluster/troubleshooting/)に詳細が記載されています。
```

2021-12-29 15:39 UTC, nasa9084 commented
/cc @riita10069

2022-01-02 10:20 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +Podが`Pending` で止まっている場合、それはノードにスケジュールできないことを意味します。
```suggestion
Podが`Pending`で止まっている場合、それはノードにスケジュールできないことを意味します。
```

2022-01-02 10:20 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +* **リソースが不足しています。** クラスタのCPUまたはメモリーを使い果たした可能性があります。Podを削除するか、リソース要求を調整するか、クラスタに新しいノードを追加する必要があります。詳しくは[Compute Resources document](/docs/concepts/configuration/manage-resources-containers/)を参照してください。
```suggestion
* **リソースが不足しています。** クラスターのCPUまたはメモリーを使い果たしている可能性があります。Podを削除するか、リソースの要求値を調整するか、クラスターに新しいノードを追加する必要があります。詳しくは[Compute Resources document](/ja/docs/concepts/configuration/manage-resources-containers/)を参照してください。
```

2022-01-02 10:20 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +Podが `Waiting` 状態で止まっている場合、ワーカーノードにスケジュールされていますが、そのマシン上で実行することはできません。この場合も、`kubectl describe ...` の情報が参考になるはずです。`Waiting`状態のポッドの最も一般的な原因は、イメージの取り出しに失敗することです。
```suggestion
Podが`Waiting`状態で止まっている場合、ワーカーノードにスケジュールされていますが、そのノード上で実行することができません。この場合も、`kubectl describe ...`の情報が参考になるはずです。`Waiting`状態のPodの最も一般的な原因は、コンテナイメージのプルに失敗することです。
```

2022-01-02 10:20 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +* イメージをリポジトリにプッシュしましたか？
Isn't this the registry?
However, the upstream documentation describes it as a repository.
"Repository" is a collection of container images or other artifacts in the registry that have the same name but different tags.

2022-01-02 10:20 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +詳しくは[debugging service](/docs/tasks/debug-application-cluster/debug-service/)を参照してください。
```suggestion
詳しくは[Serviceのデバッグ](/ja/docs/tasks/debug-application-cluster/debug-service/)を参照してください。
```

2022-01-02 10:20 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +[Debugging Service document](/docs/tasks/debug-application-cluster/debug-service/)で、`Service` が実行されていること、`Endpoints`があること、`Pods`が実際にサービスを提供していること、DNS が機能していること、IPtables ルールがインストールされていること、kube-proxyが誤
```suggestion
[Serviceのデバッグに関するドキュメント](/ja/docs/tasks/debug-application-cluster/debug-service/)で、`Service` が実行されていること、`Endpoints`があること、`Pods`が実際にサービスを提供していること、DNS が機能していること、IPtablesルールがインストールされていること、kube-proxyが誤作動を起こしていないようなことを確認してください。
```

2022-01-03 00:05 UTC, ptux commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +* イメージをリポジトリにプッシュしましたか？
I think you are right.
And I have created PR for the upstream.

> https://github.com/kubernetes/website/pull/31170

Let's wait until the PR merged.

2022-01-03 23:19 UTC, ptux commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +* イメージをリポジトリにプッシュしましたか？
Got #31170 PR merged.
And changed `リポジトリ` to `レジストリ`.

2022-01-12 16:20 UTC, nasa9084 requested changes

2022-01-12 16:20 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-application.md
> +Podなのか、レプリケーションコントローラなのか、それともサービスなのか？
```suggestion
Podなのか、レプリケーションコントローラーなのか、それともサービスなのか？
```

2022-01-12 16:20 UTC, nasa9084 commented
/assign

2022-01-27 13:52 UTC, nasa9084 commented
/approve

2022-01-27 14:11 UTC, inductor commented
/lgtm

2022-01-27 14:12 UTC, merged

2022-01-28 00:00 UTC, ptux commented
@nasa9084 @inductor 

You'd better merge the PR with squash.

`/label tide/merge-method-squash`