[ja] Translate tasks/debug-application-cluster/debug-cluster into Japanese #30874
kubernetes/website pull request #31087
Opened 2021-12-24 03:43 UTC by ptux

Address #30874

2021-12-25 16:29 UTC, ptux commented
/assign @inductor

2021-12-29 13:54 UTC, nasa9084 approved these changes

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +- ptux
please remove reviewers block

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +title: クラスタのトラブルシューティング
```suggestion
title: クラスターのトラブルシューティング
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +このドキュメントはクラスタのトラブルシューティングに関するもので、お客様が経験している問題の根本原因として、アプリケーションをすでに除外していることを前提としています。
```suggestion
このドキュメントはクラスターのトラブルシューティングに関するもので、あなたが経験している問題の根本原因として、アプリケーションをすでに除外していることを前提としています。
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +## クラスタのリストアップ
```suggestion
## クラスターのリストアップ
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +クラスタで最初にデバッグするのは、ノードがすべて正しく登録されているかどうかです。
```suggestion
クラスターで最初にデバッグするのは、ノードがすべて正しく登録されているかどうかです。
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +クラスタ全体の健全性に関する詳細な情報を得るには、以下を実行します。
```suggestion
クラスター全体の健全性に関する詳細な情報を得るには、以下を実行します。
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +今のところ、クラスタをより深く掘り下げるには、関連するマシンにログインする必要があります。
```suggestion
今のところ、クラスターをより深く掘り下げるには、関連するマシンにログインする必要があります。
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +(systemd ベースのシステムでは、代わりに `journalctl` を使う必要があるかもしれないことに注意してください)
```suggestion
(systemdベースのシステムでは、代わりに `journalctl` を使う必要があるかもしれないことに注意してください)
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +### Master ノード
```suggestion
### マスターノード
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +   * `/var/log/kube-controller-manager.log` - レプリケーションコントローラを管理するコントローラのログ
```suggestion
   * `/var/log/kube-controller-manager.log` - レプリケーションコントローラーを管理するコントローラーのログ
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +### Worker ノード
```suggestion
### ワーカーノード
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +## クラスタ障害モードの一般的な概要
```suggestion
## クラスター障害モードの一般的な概要
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +これは、問題が発生する可能性のある事柄と、問題を軽減するためにクラスタのセットアップを調整する方法の不完全なリストです。
```suggestion
これは、問題が発生する可能性のある事柄と、問題を軽減するためにクラスターのセットアップを調整する方法の不完全なリストです。
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - VM（s）のシャットダウン
```suggestion
  - VMのシャットダウン
```

日本語では複数形にあまり意味が無いので不要だと思います

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - クラスタ内、またはクラスタとユーザー間のネットワークパーティション
```suggestion
  - クラスター内、またはクラスターとユーザー間のネットワークパーティション
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - データの損失や永続的ストレージ（GCE PDやAWS EBSボリュームなど）の使用不能
```suggestion
  - データの損失や永続的ストレージ(GCE PDやAWS EBSボリュームなど)の使用不能
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - Apiserver VMのシャットダウンまたはApiserverのクラッシュ
```suggestion
  - apiserver VMのシャットダウンまたはapiserverのクラッシュ
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - Apiserverのバックアップストレージが失われた
```suggestion
  - apiserverのバックアップストレージが失われた
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - kubelets は到達できなくなりますが、同じ Pod を実行し、同じサービスのプロキシを提供し続けます
```suggestion
    - kubeletsは到達できなくなりますが、同じPodを実行し、同じサービスのプロキシを提供し続けます
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - サポートサービス（ノードコントローラ、レプリケーションコントローラマネージャ、スケジューラなど） VMのシャットダウンまたはクラッシュ
```suggestion
  - サポートサービス(ノードコントローラ、レプリケーションコントローラーマネージャー、スケジューラーなど)VMのシャットダウンまたはクラッシュ
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - 現在、これらはapiserverとコロケーションしており、使用できない場合はapiserverと同様の影響があります
`colocated` は何かいい訳を見つけたいですね
cc @inductor

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - 個別ノード（VMまたは物理マシン）のシャットダウン
```suggestion
  - 個別ノード(VMまたは物理マシン)のシャットダウン
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - そのノード上のポッドの実行を停止
```suggestion
    - そのノード上のPodの実行を停止
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - ネットワーク・パーティション
```suggestion
  - ネットワークパーティション
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - パーティションAはパーティションBのノードがダウンしていると考え、パーティションBはアピサーバーがダウンしていると考えています。(マスターVMがパーティションAで終了したと仮定)
```suggestion
    - パーティションAはパーティションBのノードがダウンしていると考え、パーティションBはapiserverがダウンしていると考えています。(マスターVMがパーティションAで終了したと仮定)
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - kubeletがポッドを削除するかどうか
```suggestion
    - kubeletがPodを削除するかどうか
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - レプリケーションコントローラが別の場所で新しいPodを起動する
```suggestion
    - レプリケーションコントローラーが別の場所で新しいPodを起動する
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - ポッドやサービスなどの損失
```suggestion
    - PodやServiceなどの損失
```

悩ましいですがこのserviceはリソース名としてのServiceっぽいような気がします

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - apiserverのバッキングストアの紛失
```suggestion
    - apiserverのバックエンドストレージの紛失
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +- 対処法: IaaSプロバイダの自動VM再起動機能をIaaS VMに使用する
```suggestion
- 対処法: IaaSプロバイダーの自動VM再起動機能をIaaS VMに使用する
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +- 対処法: IaaSプロバイダーの信頼できるストレージ（GCE PDやAWS EBSボリュームなど）をapiserver+etcdを使用するVMに使用する
```suggestion
- 対処法: IaaSプロバイダーの信頼できるストレージ(GCE PDやAWS EBSボリュームなど)をapiserver+etcdを使用するVMに使用する
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - 異常: Apiserverのバッキングストレージが失われる
```suggestion
  - 異常: Apiserverのバックエンドストレージが失われる
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +- 対処法: [high-availability](/docs/setup/production-environment/tools/kubeadm/high-availability/)構成を使用します
```suggestion
- 対処法: [高可用](/docs/setup/production-environment/tools/kubeadm/high-availability/)構成を使用します
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - 異常: 制御プレーンノードのシャットダウンまたは制御プレーンコンポーネント（スケジューラ、APIサーバ、コントローラマネージャ）のクラッシュ
```suggestion
  - 異常: コントロールプレーンノードのシャットダウンまたはコントロールプレーンコンポーネント(スケジューラー、APIサーバー、コントローラーマネージャー)のクラッシュ
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - 異常 APIサーバーのバックアップストレージ（etcdのデータディレクトリなど）が消失
```suggestion
  - 異常: APIサーバーのバックアップストレージ(etcdのデータディレクトリーなど)が消失
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +    - HA（高可用性）etcdの構成を想定しています
```suggestion
    - HA(高可用性) etcdの構成を想定しています
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - 異常。Apiserver のバッキングストレージが失われた
```suggestion
  - 異常: Apiserver のバックエンドストレージが失われる
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - 異常。操作ミスが発生する場合がある
```suggestion
  - 異常: 操作ミスが発生する場合がある
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +  - 異常。Kubernetesのソフトウェアに障害が発生する場合がある
```suggestion
  - 異常: Kubernetesのソフトウェアに障害が発生する場合がある
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +- 対処法：レプリケーションコントローラとサービスをポッドの前に使用する
```suggestion
- 対処法：レプリケーションコントローラーとServiceをPodの前に使用する
```

2021-12-29 13:54 UTC, nasa9084 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +- 対処法: 予期せぬ再起動に耐えられるように設計されたアプリケーション（コンテナ）
```suggestion
- 対処法: 予期せぬ再起動に耐えられるように設計されたアプリケーション(コンテナ)
```

2021-12-29 15:28 UTC, nasa9084 requested changes
oh I made mistake

2021-12-29 15:28 UTC, nasa9084 commented
/unapprove

2022-01-28 07:49 UTC, ptux commented
/label tide/merge-method-squash

2022-03-30 14:51 UTC, nasa9084 commented
See hidden comments too. Sorry for so many comments

2022-03-31 03:19 UTC, nasa9084 commented
/assign
/cc @kakts @bells17 @riita10069 
/assign

2022-03-31 03:19 UTC, nasa9084 commented
/approve

2022-04-11 06:18 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/debug-cluster.md
> +
```suggestion
```

If you find it too trivial, feel free to ignore it.

2022-04-22 18:39 UTC, bells17 commented
/lgtm

2022-04-22 18:41 UTC, merged