[ja] Translate tasks/debug-application-cluster/monitor-node-health into Japanese
kubernetes/website pull request #31108
Opened 2021-12-25 15:58 UTC by ptux

Address #30870

2021-12-25 15:59 UTC, ptux commented
/assign @inductor

2021-12-30 06:16 UTC, kakts commented
/lgtm

2022-01-05 07:58 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +`Node Problem Detector`は様々なデーモンからノードの問題に関する情報を収集し、これらの状態を[NodeCondition](/docs/concepts/architecture/nodes/#condition)および[Event](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/#even
```suggestion
`Node Problem Detector`は様々なデーモンからノードの問題に関する情報を収集し、これらの状態を[NodeCondition](/ja/docs/concepts/architecture/nodes/#condition)および[Event](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/#event-v1-core)としてAPIサーバにレポートします。
```

2022-01-05 07:58 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +  `journald` のようなログツールはサポートされていません。
```suggestion
  `journald`のようなログツールはサポートされていません。
```

2022-01-05 07:58 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +  カーネルログフォーマットを拡張する方法については、 [Add support for another log format] (#support-other-log-format) を参照してください。
```suggestion
  カーネルログフォーマットを拡張する方法については、[Add support for another log format](#support-other-log-format) を参照してください。
```

2022-01-05 07:58 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +クラウドプロバイダーによっては、`Node Problem Detector`を{{< glossary_tooltip text="Addon" term_id="addons" >}} として有効にしている場合があります。
```suggestion
クラウドプロバイダーによっては、`Node Problem Detector`を{{< glossary_tooltip text="Addon" term_id="addons" >}}として有効にしている場合があります。
```

2022-01-05 07:58 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +しかし、[`ConfigMap`](/docs/tasks/configure-pod-container/configure-pod-configmap/) を使用して設定を上書きできます。
```suggestion
[`ConfigMap`](/ja/docs/tasks/configure-pod-container/configure-pod-configmap/) を使用することで設定を上書きすることができます。
```

2022-01-05 07:58 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +ご使用のオペレーティングシステム（OS）ディストリビューションのカーネルログパスの場所をご確認ください。
```suggestion
ご使用のオペレーティングシステム(OS)ディストリビューションのカーネルログパスをご確認ください。
```

2022-01-28 07:48 UTC, ptux commented
/label tide/merge-method-squash

2022-01-31 16:41 UTC, riita10069 commented
/lgtm

2022-02-04 17:00 UTC, inductor requested changes

2022-02-06 02:56 UTC, ptux commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +title: ノードの健康状態を監視します
how about `健全性`?

2022-02-06 03:38 UTC, inductor commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +title: ノードの健康状態を監視します
That kinda sounds like compliance perspective

2022-02-22 15:52 UTC, riita10069 commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +title: ノードの健康状態を監視します
@inductor 
Sorry for the late reply.

I think we often say `正常性`, as `ノードが正常か、異常かを表す名詞`.

I have a few more ideas below.

- `ノードのヘルスモニタリング`
- `ノードの状態を監視する`

@ptux 

`健全性` is also used in the content, perhaps it should be replaced with `正常性`.

2022-03-04 22:40 UTC, ptux commented on content/ja/docs/tasks/debug-application-cluster/monitor-node-health.md
> +title: ノードの健康状態を監視します
@inductor @riita10069 
Here are some use cases about「健全」.

content/ja/docs/concepts/workloads/pods/_index.md
> そして、スケジューラーが代わりのPodを健全なノード上に配置します。

And please google search for [kubernetes 健全].
You will find out that [健全性] is better.

content/ja/docs/setup/production-environment/tools/kubeadm/high-availability.md
>すべての健全なコントロールプレーンノードにトラフィックを分配します

2022-03-15 16:04 UTC, kakts commented
/lgtm

2022-05-10 07:24 UTC, ptux commented
@inductor 

This is a friendly reminder.

2022-05-11 13:59 UTC, merged