Update overview.md
kubernetes/website pull request #31121
Opened 2021-12-28 04:00 UTC by luckyops

fix example url

2021-12-28 04:06 UTC, shuaijinchao commented
Please sign CLA
https://github.com/kubernetes/website/pull/31121#issuecomment-1001856269

2021-12-28 04:17 UTC, luckyops commented
CLA Ready

2021-12-28 06:59 UTC, mengjiao-liu commented
/hold
谢谢贡献。根据[指南](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87)约定，我们会拒绝对页面的部分修改。部分修改针对的是对应页面的英文上游还有其他改动需要同步的情况。
一旦我们合并了此 PR，将来就无法根据文件的最后更改时间来判断是否有其他上游变更尚未同步。请理解。
请在 main 分支上执行以下命令查看上游尚未同步的更改：
```
./scripts/lsync.sh content/zh/docs/concepts/configuration/overview.md
```

2021-12-28 11:49 UTC, championshuttler requested changes

2021-12-28 11:49 UTC, championshuttler commented on content/zh/docs/concepts/configuration/overview.md
> + 请参阅[guestbook-all-in-one.yaml](https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml) 文件作为此语法的示例。
```suggestion
 请参阅[guestbook-all-in-one.yaml](https://github.com/kubernetes/examples/tree/master/guestbook/all-in-one/guestbook-all-in-one.yaml) 文件作为此语法的示例。
```

2021-12-28 11:49 UTC, championshuttler commented on content/zh/docs/concepts/configuration/overview.md
> + 请参阅[guestbook-all-in-one.yaml](https://github.com/kubernetes/examples/blob/master/guestbook/all-in-one/guestbook-all-in-one.yaml) 文件作为此语法的示例。
This would do and its same in en/ docs too

2022-01-21 08:31 UTC, tengqm commented
/close

2022-01-21 08:31 UTC, closed without merging