[es] Add concepts/workloads/pods/disruptions
kubernetes/website pull request #31141
Opened 2021-12-29 18:26 UTC by gamba47

2021-12-29 20:57 UTC, raelga commented
/retitle WIP [es] Add concepts/workloads/pods/disruptions

2022-01-03 02:20 UTC, gamba47 commented
Work terminated! have a nice year!

/retitle [es] Add concepts/workloads/pods/disruptions

2022-01-03 22:14 UTC, electrocucaracha requested changes

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +different UID, could be created.  Otherwise, the example applies to a StatefulSet as well.)
```suggestion
(Nota: para un StatefulSet, `pod-a`, el cual debería ser llamado algo como `pod-0`, necesitaría ser terminado completamente antes de su remplazo, el cual también es llamado `pod-0` pero tiene un UID diferente, podría ser creado. De lo contrario, el ejemplo también aplica a un StatefulSet.)
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +En algún punto, los pods finalizan y el clúster se ve de esta forma:
```suggestion
En algún punto, los Pods finalizan y el clúster se ve de esta forma:
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +En este estado, si un administrador del clúster impaciente intenta desalojar el `nodo-2` ó al
```suggestion
En este estado, si un administrador del clúster impaciente intenta desalojar el `nodo-2` ó el 
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +`nodo-3`, el comando drain va a ser bloqueado, porque hay solamente 2 pods disponibles para
```suggestion
`nodo-3`, el comando drain va a ser bloqueado, porque hay solamente 2 Pods disponibles para
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +el deployment y el PDB requiere por lo menos 2. Después de pasado un tiempo el `pod-d` esta disponible.
```suggestion
el Deployment y el PDB requiere por lo menos 2. Después de pasado un tiempo el `pod-d` esta disponible.
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +El comando drain tratará de desalojar a los 2 pods con algún orden, digamos
```suggestion
El comando drain tratará de desalojar a los 2 Pods con algún orden, digamos
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +un pod disponible para el deployment.
```suggestion
Pero cuando intente desalojar al `pod-d`, va a ser rechazado porque esto va a dejar 
un Pod solamente disponible para el Deployment. 
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +El deployment crea un reemplazo para el `pod-b` llamando `pod-e`.
```suggestion
El Deployment crea un reemplazo para el `pod-b` llamado `pod-e`.
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +agregar un nodo de nuevo en el clúster para continuar con la actualización.
```suggestion
agregar un nuevo nodo en el clúster para continuar con la actualización.
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +Ustede puede ver como Kubernetes varia la tasa a la que las interrupciones
```suggestion
Usted puede ver como Kubernetes varia la tasa a la que las interrupciones
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +una interface entre los roles.
```suggestion
El presupuesto de interrupción de Pods soporta esta separación de roles, ofreciendo
una interfaz entre los roles.
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +los nodos en el clúster, como ser un upgrade de nodo o de software, estas son algunas de las opciones:
```suggestion
los nodos en el clúster, como ser una actualización de nodo o de software, estas son algunas de las opciones:
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +- Aceptar el tiempo sin funcionar mientras dura el upgrade.
```suggestion
- Aceptar el tiempo sin funcionar mientras dura la actualización.
```

2022-01-03 22:14 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +* Aprenda sobre [actualizar un deployment](/docs/concepts/workloads/controllers/deployment/#updating-a-deployment)
```suggestion
* Aprenda sobre [actualizar un Deployment](/docs/concepts/workloads/controllers/deployment/#updating-a-deployment)
```

2022-01-04 02:03 UTC, gamba47 commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +a creado el pod `pod-y` como un reemplazo del `pod-x` .
@electrocucaracha, en este caso lo deje así porque el texto en inglés hace referencia a que puede haber otra cosa que no es un Deployment o Replicaset que este queriendo mantener vivo a ese Pod, deja abierta la posibilidad que exista algo "mágico" que no quieren nombrar, si podes mira el texto en ingles, para ver si le podemos dar el mismo sentido.

2022-01-11 15:41 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +| nodo-1 *desalojando* |       nodo-2        |       nodo-3       |
```suggestion
| nodo-1 *draining* |       nodo-2        |       nodo-3       |
```

2022-01-11 15:41 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +| nodo-1 *desalojando* |       nodo-2        |       nodo-3       |
```suggestion
| nodo-1 *draining* |       nodo-2        |       nodo-3       |
```

2022-01-11 15:41 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +|  nodo-1 *desalojado* |       nodo-2        |       nodo-3       |
```suggestion
|  nodo-1 *drained* |       nodo-2        |       nodo-3       |
```

2022-01-11 15:41 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +|  nodo-1 *desalojado* |       nodo-2        |       nodo-3       |
```suggestion
|  nodo-1 *drained* |       nodo-2        |       nodo-3       |
```

2022-01-11 15:41 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +|    nodo-1 *drained*  |       nodo-2        |       nodo-3       | *sin nodo*          |
```suggestion
|    nodo-1 *drained*  |       nodo-2        |       nodo-3       | *no node*          |
```

2022-01-11 15:43 UTC, gamba47 reviewed
Fix some errors

2022-01-11 18:37 UTC, gamba47 reviewed
Cambiando algunas formas de llamar a las cosas, quedamos con drain y no desalojar para cuando es un estado.

2022-01-25 02:48 UTC, electrocucaracha reviewed
/lgtm

/cc @raelga

2022-03-08 15:38 UTC, merged