[zh] Translate memory manager page
kubernetes/website pull request #31172
Opened 2022-01-03 03:45 UTC by tengqm

/language zh

2022-02-07 11:44 UTC, howieyuen requested changes

2022-02-07 11:44 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/memory-manager.md
> +- pod 状态 - 可表明拓扑亲和性错误
```suggestion
- Pod 状态 - 可表明拓扑亲和性错误

```

2022-02-09 06:54 UTC, howieyuen commented
/lgtm

2022-02-26 10:06 UTC, tanjunchen reviewed
/approve

2022-02-26 10:07 UTC, merged