[zh] Translate migrate from PSP
kubernetes/website pull request #31177
Opened 2022-01-03 07:26 UTC by tengqm

/language zh

2022-01-10 08:19 UTC, howieyuen requested changes

2022-01-10 08:19 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +   - 检视使用了变更式 PSP 的 Pods，与拥有该代码的人一起将其迁移到合法的、非变更式的资源。
```suggestion
   - 检视使用了变更式 PSP 的 Pod，与拥有该代码的人一起将其迁移到合法的、非变更式的资源。
```

2022-01-10 10:25 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +   - 检视使用了变更式 PSP 的 Pods，与拥有该代码的人一起将其迁移到合法的、非变更式的资源。
OK

2022-01-10 11:27 UTC, howieyuen commented
/lgtm

2022-02-05 11:03 UTC, sftim commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +- 在 `--eanble-admission-plugins` 标志中去除 `PodSecurityPolicy`。
nit:
```suggestion
- 在 `--enable-admission-plugins` 标志中去除 `PodSecurityPolicy`。
```

2022-02-07 02:31 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +- 在 `--eanble-admission-plugins` 标志中去除 `PodSecurityPolicy`。
Thanks. Fixed.

2022-02-07 08:59 UTC, howieyuen commented
/lgtm

2022-02-12 12:59 UTC, tanjunchen reviewed
/approve

2022-02-12 13:01 UTC, merged