[zh] Translate enforce standards-namespace-labels page
kubernetes/website pull request #31238
Opened 2022-01-07 12:51 UTC by tengqm

/language zh

2022-01-10 08:14 UTC, howieyuen requested changes

2022-01-10 08:14 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
> +你可以通过为名字空间设置标签来强制实施 [Pod 安全标准](/zh/docs/concepts/security/pod-security-standards).
nit, `.` -> `。`

2022-01-10 08:16 UTC, howieyuen requested changes

2022-01-10 08:16 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
> +- 针对任何无法满足 `restricted` 策略要求的、已创建的 Pod 为用户生产警告信息，
```suggestion
- 针对任何无法满足 `restricted` 策略要求的、已创建的 Pod 为用户生成警告信息，
```

2022-01-10 11:27 UTC, howieyuen commented
/lgtm

2022-02-14 01:54 UTC, tanjunchen reviewed
/approve

2022-02-14 01:55 UTC, merged