[ja] Translate tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you into Japanese
kubernetes/website pull request #31285
Opened 2022-01-11 12:44 UTC by ptux

Address #31275

2022-01-11 15:29 UTC, nasa9084 requested changes

2022-01-11 15:29 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +このページでは、あなたのクラスタがどのようにDockerをコンテナランタイムとして使用しているか、使用中の`dockershim`が果たす役割について詳しく説明し、`dockershim`の廃止によって影響を受けるワークロードがあるかどうかをチェックするためのステップを示します。
```suggestion
このページでは、あなたのクラスターがどのようにDockerをコンテナランタイムとして使用しているか、使用中の`dockershim`が果たす役割について詳しく説明し、`dockershim`の廃止によって影響を受けるワークロードがあるかどうかをチェックするためのステップを示します。
```

please check below too

2022-01-11 15:29 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +アプリケーション・コンテナの構築にDockerを使用している場合でも、これらのコンテナを任意のコンテナランタイム上で実行することができます。このようなDockerの使用は、コンテナランタイムとしてのDockerへの依存とはみなされません。
```suggestion
アプリケーションコンテナの構築にDockerを使用している場合でも、これらのコンテナを任意のコンテナランタイム上で実行することができます。このようなDockerの使用は、コンテナランタイムとしてのDockerへの依存とはみなされません。
```

2022-01-11 15:29 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +1. Docker設定ファイル(`/etc/docker/daemon.json` など)にプライベートレジストリやイメージミラーの設定がないか確認します。これらは通常、別のコンテナランタイムのために再設定する必要があります。
```suggestion
1. Dockerの設定ファイル(`/etc/docker/daemon.json` など)にプライベートレジストリやイメージミラーの設定がないか確認します。これらは通常、別のコンテナランタイムのために再設定する必要があります。
```

2022-01-11 15:29 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +1. Kubernetesインフラストラクチャの外側のノードで実行されているスクリプトやアプリがDockerコマンドを実行しないことを確認します。それは、もしかしたら:
```suggestion
1. Kubernetesインフラストラクチャーの外側のノードで実行されているスクリプトやアプリがDockerコマンドを実行しないことを確認します。それは、もしかしたら:
```

2022-01-11 15:29 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +[コンテナランタイム](/docs/concepts/containers/#container-runtimes)とは、Kubernetes Podを構成するコンテナを実行できるソフトウェアです。
```suggestion
[コンテナランタイム](/ja/docs/concepts/containers/#container-runtimes)とは、Kubernetes Podを構成するコンテナを実行できるソフトウェアです。
```

2022-01-11 15:29 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +初期のリリースでは、Kubernetesは1つのコンテナランタイムと互換性を提供していました:Dockerです。
```suggestion
初期のリリースでは、Kubernetesは1つのコンテナランタイムと互換性を提供していました: Dockerです。
```

2022-01-11 15:29 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +しかし、DockerはCRI仕様が考案される前から存在していたため、Kubernetesプロジェクトはアダプタコンポーネント「dockershim」を作成しました
```suggestion
しかし、DockerはCRI仕様が考案される前から存在していたため、Kubernetesプロジェクトはアダプタコンポーネント「dockershim」を作成しました。
```

2022-01-21 09:40 UTC, nasa9084 commented
/approve

2022-01-28 00:09 UTC, ptux commented
/label tide/merge-method-squash

2022-02-01 09:36 UTC, ptux commented
@inductor

cloud you give an LGTM label?

2022-02-04 17:02 UTC, inductor requested changes

2022-02-06 03:37 UTC, inductor requested changes

2022-02-06 03:37 UTC, inductor commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/check-if-dockershim-deprecation-affects-you.md
> +   - ノードに直接インストールされた監視エージェントやセキュリティエージェント。
```suggestion
1. Kubernetesインフラストラクチャーの外側のノードで実行される以下のようなスクリプトやアプリがDockerコマンドを実行しないことを確認します。
   - トラブルシューティングのために人間がノードにSSH接続
   - ノードのスタートアップスクリプト
   - ノードに直接インストールされた監視エージェントやセキュリティエージェント
```

2022-04-22 18:38 UTC, bells17 commented
/lgtm

2022-04-22 18:39 UTC, merged