[ja] Translate tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents into Japanese
kubernetes/website pull request #31304
Opened 2022-01-12 12:57 UTC by ptux

Address #31303

2022-01-12 12:59 UTC, ptux commented
/assign @nasa9084

2022-01-27 13:49 UTC, nasa9084 requested changes

2022-01-27 13:49 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +### Dockerに依存するDaemonSetsの特定 {#identify-docker-dependency}
```suggestion
### Dockerに依存するDaemonSetの特定 {#identify-docker-dependency}
```

2022-01-27 13:49 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +- Dockerデーモンの特権ソケットがあるファイルシステムを{{< glossary_tooltip text="volume" term_id="volume" >}}のようになります。
```suggestion
- Dockerデーモンの特権ソケットがあるファイルシステムを{{< glossary_tooltip text="volume" term_id="volume" >}}のようにマウントする。
```

2022-01-27 13:49 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +例：COSイメージでは、DockerはそのUnixドメインソケットを`/var/run/docker.sock`に公開します。
```suggestion
例: COSイメージでは、DockerはそのUnixドメインソケットを`/var/run/docker.sock`に公開します。
```

2022-01-27 13:49 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +`grep '/var/run/docker.sock'`を削除して、他のマウントを確認することができます。
```suggestion
`grep '/var/run/docker.sock'`を削除して、他のマウントを確認することもできます。
```

2022-01-27 13:49 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +例えば、フルパスの代わりに親ディレクトリ`/var/run`をマウントすることができます(この例(https://gist.github.com/itaysk/7bc3e56d69c4d72a549286d98fd557dd) のように)。
```suggestion
例えば、フルパスの代わりに親ディレクトリ`/var/run`をマウントすることができます([この例](https://gist.github.com/itaysk/7bc3e56d69c4d72a549286d98fd557dd) のように)。
```

2022-01-27 13:49 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +を[Google doc](https://docs.google.com/document/d/1ZFi4uKit63ga5sxEiZblfb-c23lFhvy6RXVPikS8wf0/edit#)でご覧ください。
```suggestion
様々なテレメトリーおよびセキュリティエージェントベンダーのための移行指示の作業中バージョンを[Google doc](https://docs.google.com/document/d/1ZFi4uKit63ga5sxEiZblfb-c23lFhvy6RXVPikS8wf0/edit#)に保管しています。
```

2022-01-28 00:02 UTC, ptux commented
/label tide/merge-method-squash

2022-03-28 12:11 UTC, nasa9084 commented
/approve

2022-03-30 14:48 UTC, nasa9084 commented
/cc @riita10069 @kakts

2022-04-11 06:15 UTC, riita10069 approved these changes

2022-04-11 06:15 UTC, riita10069 commented
/lgtm

2022-04-11 06:16 UTC, merged