[pl] update date to mention KubeCon NA 2022
kubernetes/website pull request #31356
Opened 2022-01-15 22:26 UTC by Arhell

en PR https://github.com/kubernetes/website/pull/30722/files
/assign @mfilocha

2022-01-18 09:50 UTC, mfilocha requested changes

2022-01-18 09:50 UTC, mfilocha commented on content/pl/_index.html
> +        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna21" button id="desktopKCButton">Weź udział w wirt
```suggestion
        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna21" button id="desktopKCButton">Weź udział w KubeCon North America 24-28.10.2022</a>
```

2022-01-18 09:50 UTC, mfilocha commented on content/pl/_index.html
> +        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna21" button id="desktopKCButton">Weź udział w wirt
Hopefully no longer a virtual event...

2022-01-18 09:50 UTC, mfilocha commented on content/pl/_index.html
> +        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna21" button id="desktopKCButton">Weź udział w wirt
Thanks @Arhell!

2022-01-19 00:17 UTC, Arhell commented on content/pl/_index.html
> +        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/?utm_source=kubernetes.io&utm_medium=nav&utm_campaign=kccncna21" button id="desktopKCButton">Weź udział w wirt
Done, thanks!

2022-01-19 09:49 UTC, mfilocha commented
/lgtm
/approve

2022-01-19 09:50 UTC, mfilocha approved these changes

2022-01-19 09:52 UTC, merged