[ja]Translate concepts/storage/projected-volumes into Japanese
kubernetes/website pull request #31436
Opened 2022-01-21 05:52 UTC by KobayashiD27

close #31432

2022-01-21 05:54 UTC, KobayashiD27 commented
/assign @nasa9084

2022-01-21 06:47 UTC, jihoon-seo commented
[Netlify build fails](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/61ea4a704746f000080ce134#L77).

Copying `content/en/examples/pods/storage/projected-secret-downwardapi-configmap.yaml` to `content/ja/examples/pods/storage/projected-secret-downwardapi-configmap.yaml` might resolve the error! 😊

2022-01-21 07:43 UTC, KobayashiD27 commented
> [Netlify build fails](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/61ea4a704746f000080ce134#L77).
> 
> Copying `content/en/examples/pods/storage/projected-secret-downwardapi-configmap.yaml` to `content/ja/examples/pods/storage/projected-secret-downwardapi-configmap.yaml` might resolve the error! 😊

Thank you! I forget to stage these files...

2022-01-22 00:05 UTC, ptux commented on content/ja/docs/concepts/storage/projected-volumes.md
> +title: Projectedボリューム
Let's translate the term `Projected Volume`  into `投影ボリューム`.

https://eow.alc.co.jp/search?q=projected

2022-01-25 04:22 UTC, KobayashiD27 commented on content/ja/docs/concepts/storage/projected-volumes.md
> +title: Projectedボリューム
OK, I fix it.

2022-01-25 06:41 UTC, ptux requested changes

2022-01-25 06:41 UTC, ptux commented on content/ja/docs/concepts/storage/projected-volumes.md
> +すべてのソースは、Podと同じnamespaceにある必要があります。詳細は[all-in-one volume designドキュメント](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/node/all-in-one-volume.md)を参照してください。
```suggestion
すべてのソースは、Podと同じnamespaceにある必要があります。詳細は[all-in-one volume designドキュメント](https://github.com/kubernetes/design-proposals-archive/blob/main/node/all-in-one-volume.md)を参照してください。
```

2022-01-25 06:41 UTC, ptux commented on content/ja/docs/concepts/storage/projected-volumes.md
> +`TokenRequestProjection`機能が有効になっている場合、現在の[サービスアカウント](/docs/reference/access-authn-authz/authentication/#service-account-tokens)のトークンを指定されたパスのPodに挿入できます。例えば:
```suggestion
`TokenRequestProjection`機能が有効になっている場合、現在の[サービスアカウントトークン](/ja/docs/reference/access-authn-authz/authentication/#サービスアカウントトークン)を指定されたパスのPodに挿入できます。例えば:
```

2022-01-25 06:41 UTC, ptux commented on content/ja/docs/concepts/storage/projected-volumes.md
> +[サービスアカウントの投影ボリューム拡張でのファイル権限処理の提案]((https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2451-service-account-token-volumes#token-volume-projection))により、正しい所有者権限が設定された投影ファイルが導入されまし
```suggestion
[サービスアカウントの投影ボリューム拡張でのファイル権限処理の提案](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2451-service-account-token-volumes#proposal)により、正しい所有者権限が設定された投影ファイルが導入されました。
```

2022-01-25 12:22 UTC, ptux requested changes

2022-01-25 12:22 UTC, ptux commented on content/ja/docs/concepts/storage/projected-volumes.md
> +[サービスアカウントの投影ボリューム拡張でのファイル権限処理の提案](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2451-service-account-token-volumes#proposal)により、正しい所有者権限が設定された投影ファイルが導入されました。
I have made change on the upstream.
https://github.com/kubernetes/website/pull/31496/files

```suggestion
サービスアカウントの投影ボリューム拡張でのファイル権限処理の[提案](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2451-service-account-token-volumes#proposal)により、正しい所有者権限が設定された投影ファイルが導入されました。
```

2022-01-25 12:22 UTC, ptux commented on content/ja/docs/concepts/storage/projected-volumes.md
> +すべてのソースは、Podと同じnamespaceにある必要があります。詳細は[all-in-one volume designドキュメント](https://github.com/kubernetes/design-proposals-archive/blob/main/node/all-in-one-volume.md)を参照してください。
I have made change on the upstream.
https://github.com/kubernetes/website/pull/31496/files

```suggestion
すべてのソースは、Podと同じnamespaceにある必要があります。詳細は[all-in-one volume](https://github.com/kubernetes/design-proposals-archive/blob/main/node/all-in-one-volume.md) デザインドキュメントを参照してください。
```

2022-01-26 04:24 UTC, ptux commented
/lgtm

2022-01-28 13:04 UTC, nasa9084 commented on content/ja/docs/concepts/storage/projected-volumes.md
> +すべてのソースは、Podと同じnamespaceにある必要があります。詳細は[all-in-one volume](https://github.com/kubernetes/design-proposals-archive/blob/main/node/all-in-one-volume.md) デザインドキュメントを参照してください。
```suggestion
すべてのソースは、Podと同じnamespaceにある必要があります。詳細は[all-in-one volume](https://github.com/kubernetes/design-proposals-archive/blob/main/node/all-in-one-volume.md)デザインドキュメントを参照してください。
```

2022-01-28 13:04 UTC, nasa9084 commented on content/ja/docs/concepts/storage/projected-volumes.md
> +`TokenRequestProjection`機能が有効になっている場合、現在の[サービスアカウントトークン](/ja/docs/reference/access-authn-authz/authentication/#サービスアカウントトークン)を指定されたパスのPodに挿入できます。例えば:
日本語URLはエンコードされて見た目が良くない＆読みづらくなってしまうので、リンク先に英語でIDを付けて英語IDリンクに直してもらえますか？

2022-01-29 09:32 UTC, riita10069 commented on content/ja/docs/concepts/storage/projected-volumes.md
> +各投影ボリュームソースは、specの`sources`にリストされています。パラメータは、2つの例外を除いてほぼ同じです。
```suggestion
各投影ボリュームソースは、specの`sources`にリストされています。パラメーターは、2つの例外を除いてほぼ同じです。
```

2022-01-29 09:32 UTC, riita10069 commented on content/ja/docs/concepts/storage/projected-volumes.md
> +例のPodには、挿入されたサービスアカウントトークンを含む投影ボリュームがあります。このトークンはPodのコンテナがKubernetes APIサーバーにアクセスするために使用できます。この`audience`フィールドにはトークンのオーディエンスが含まれています。トークンの受信者は、トークンのオーディエンスで指定された識別子で自分自身を識別する必要があります。そうでない場合はトークンを拒否する
```suggestion
この例のPodには、挿入されたサービスアカウントトークンを含む投影ボリュームがあります。このトークンはPodのコンテナがKubernetes APIサーバーにアクセスするために使用できます。この`audience`フィールドにはトークンの受信対象者が含まれています。トークンの受信者は、トークンの`audience`フィールドで指定された識別子で自分自身であるかを識別します。そうでない場合はトークンを拒否します。このフィールドはオプションで、デフォルトではAPIサーバーの識別子が指定されます。
```

2022-02-01 02:49 UTC, KobayashiD27 commented on content/ja/docs/concepts/storage/projected-volumes.md
> +`TokenRequestProjection`機能が有効になっている場合、現在の[サービスアカウントトークン](/ja/docs/reference/access-authn-authz/authentication/#サービスアカウントトークン)を指定されたパスのPodに挿入できます。例えば:
ありがとうございます。リンクを修正しました。

2022-02-21 16:26 UTC, nasa9084 commented
/approve

2022-02-22 01:41 UTC, jihoon-seo commented
@KobayashiD27 If possible, please squash multiple commits into one single commit. 😊

2022-02-23 15:58 UTC, kakts commented
Thank you for your contribution.
/lgtm

2022-02-23 16:00 UTC, merged