[zh] Resync the configmap page
kubernetes/website pull request #31444
Opened 2022-01-21 08:29 UTC by tengqm

2022-01-21 17:20 UTC, sftim reviewed
Small nits

2022-01-21 17:20 UTC, sftim commented on content/zh/docs/concepts/configuration/configmap.md
> +卷挂载的容器无法收到 ConfiaMap 更新。
nit:
```suggestion
卷挂载的容器无法收到 ConfigMap 更新。
```

2022-01-21 17:20 UTC, sftim commented on content/zh/docs/concepts/configuration/configmap.md
>  * 阅读 [Twelve-Factor 应用](https://12factor.net/) 来了解将代码和配置分开的动机。
Could link to https://12factor.net/zh_cn/ if you want to.

2022-01-31 02:01 UTC, chenxuc requested changes
Thanks for the update. I have some minor comments.

2022-01-31 02:14 UTC, tengqm commented on content/zh/docs/concepts/configuration/configmap.md
> +* 阅读 [Twelve-Factor 应用](https://12factor.net/zh/)来了解将代码和配置分开的动机。
fixed.

2022-01-31 02:17 UTC, chenxuc commented
/lgtm

2022-03-24 06:58 UTC, chenxuc commented
/lgtm

2022-03-26 09:12 UTC, tanjunchen reviewed
/approve
/lgtm
thanks

2022-03-26 09:13 UTC, merged