[zh] Resync authentication page
kubernetes/website pull request #31443
Opened 2022-01-21 08:18 UTC by tengqm

This supersedes #31107 which is incomplete.

2022-01-21 09:56 UTC, howieyuen requested changes

2022-01-21 09:56 UTC, howieyuen commented on content/zh/docs/reference/access-authn-authz/authentication.md
> +* `Impersonate-Group`: A group name to act as. Can be provided multiple times to set multiple groups. Optional. Requires "Impersonate-User".
missing translation

2022-01-21 09:57 UTC, howieyuen commented
/lgtm

2022-02-15 11:00 UTC, tanjunchen reviewed
/approve

2022-02-15 11:04 UTC, merged