Documented annotation volume.kubernetes.io/storage-provisioner
kubernetes/website pull request #31532
Opened 2022-01-27 07:31 UTC by Kartik494

Fixes: #30807

2022-01-27 09:47 UTC, sftim commented
@kubernetes/sig-storage-pr-reviews does this look right? Anything more to add?

2022-01-27 14:05 UTC, jsafrane commented
lgtm from storage POV

2022-01-27 17:04 UTC, sftim requested changes
Thanks for this.

One thing to fix @Kartik494 - use the type name that you would see in a manifest.

2022-01-27 17:04 UTC, sftim commented on content/en/docs/reference/labels-annotations-taints.md
> +Used on: PVC
```suggestion
Used on: PersistentVolumeClaim
```

2022-01-28 04:27 UTC, Kartik494 commented on content/en/docs/reference/labels-annotations-taints.md
> +Used on: PVC
@sftim Done. PTAL!

2022-01-30 22:23 UTC, sftim approved these changes
Thanks

/lgtm
/approve

2022-01-30 22:24 UTC, merged

2022-01-30 22:56 UTC, sftim commented
/retitle Document annotation volume.kubernetes.io/storage-provisioner