[ja] Translate concepts/storage/volumes.md into Japanese
kubernetes/website pull request #31533
Opened 2022-01-27 07:50 UTC by KobayashiD27

close #31431

2022-01-27 07:53 UTC, KobayashiD27 commented
/assign @nasa9084

2022-01-28 13:58 UTC, nasa9084 requested changes

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +この機能を利用するには、クラスタに[Azure Disk CSI Driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver)をインストールし、`CSIMigration`および`CSIMigrationAzureDisk`機能を有効化する必要があります。
```suggestion
この機能を利用するには、クラスターに[Azure Disk CSI Driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver)をインストールし、`CSIMigration`および`CSIMigrationAzureDisk`機能を有効化する必要があります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +この機能を利用するには、クラスタに[Azure File CSI Driver](https://github.com/kubernetes-sigs/azurefile-csi-driver)をインストールし、`CSIMigration`および`CSIMigrationAzureFile`[フィーチャーゲート](/ja/docs/reference/command-line-tools-ref
```suggestion
この機能を利用するには、クラスターに[Azure File CSI Driver](https://github.com/kubernetes-sigs/azurefile-csi-driver)をインストールし、`CSIMigration`および`CSIMigrationAzureFile`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)を有効化する必要があります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`cephfs`ボリュームは複数のライターによって同時にマウントすることができます。
```suggestion
`cephfs`ボリュームは複数の書き込み元によって同時にマウントすることができます。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`log-config`ConfigMapはボリュームとしてマウントされ、その`log_level`エントリに格納されているすべてのコンテンツは、パス`/etc/config/log_level`のPodにマウントされます。
```suggestion
`log-config` ConfigMapはボリュームとしてマウントされ、その`log_level`エントリに格納されているすべてのコンテンツは、パス`/etc/config/log_level`のPodにマウントされます。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +コンテナがクラッシュしても、ノードからPodが削除されることは*ありません*。`emptyDir`ボリューム内のデータは、コンテナのクラッシュしても安全です。
```suggestion
コンテナがクラッシュしても、ノードからPodが削除されることは*ありません*。`emptyDir`ボリューム内のデータは、コンテナがクラッシュしても安全です。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +tmpfsは非常に高速ですが、ディスクと違ってノードのリブート時にクリアされ、書き込んだファイルはコンテナのメモリ制限にカウントされることに注意してください。
```suggestion
tmpfsは非常に高速ですが、ディスクと違ってノードのリブート時にクリアされ、書き込んだファイルはコンテナのメモリー制限にカウントされることに注意してください。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`SizeMemoryBackedVolumes`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)が有効な場合、メモリバックアップボリュームにサイズを指定することができます。
```suggestion
`SizeMemoryBackedVolumes`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)が有効な場合、メモリーバックアップボリュームにサイズを指定することができます。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +サイズが指定されていない場合、メモリでバックアップされたボリュームは、Linuxホストのメモリの50％のサイズになります。
```suggestion
サイズが指定されていない場合、メモリーでバックアップされたボリュームは、Linuxホストのメモリの50％のサイズになります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +残念ながらPDは読み取り/書き込みモードで1人のコンシューマーのみがマウントできます。同時書き込みは許可されていません。
```suggestion
残念ながらPDは読み取り/書き込みモードで1つのコンシューマーのみがマウントできます。同時書き込みは許可されていません。

```

人ではないので・・・

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> + この機能を使用するには、ボリュームをPersistentVolumeとしてプロビジョニングする必要があります。Podから直接ボリュームを参照することはサポートされていません。
```suggestion
[リージョン永続ディスク](https://cloud.google.com/compute/docs/disks/#repds)機能を使用すると、同じリージョン内の2つのゾーンで使用できる永続ディスクを作成できます。
この機能を使用するには、ボリュームをPersistentVolumeとしてプロビジョニングする必要があります。Podから直接ボリュームを参照することはサポートされていません。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +この機能を使用するには、クラスタに[GCE PD CSI Driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver)がインストールされ、`CSIMigration`と`CSIMigrationGCE`のbeta機能が有効になっている必要があります。
```suggestion
この機能を使用するには、クラスターに[GCE PD CSI Driver](https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver)がインストールされ、`CSIMigration`と`CSIMigrationGCE`のbeta機能が有効になっている必要があります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`gcePersistentDisk`ストレージプラグインがコントローラーマネージャーとkubeletによってロードされないようにするには、`InTreePluginGCEUnregister`フラグを`true`に設定します。
```suggestion
`gcePersistentDisk`ストレージプラグインがコントローラーマネージャーとkubeletによって読み込まれないようにするには、`InTreePluginGCEUnregister`フラグを`true`に設定します。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`gitRepo`ボリュームタイプは非推奨です。gitレポジトリを使用してコンテナをプロビジョニングするには、Gitを使用してレポジトリのクローンを作成するInitContainerに[EmptyDir](#emptydir)をマウントしてから、Podのコンテナに[EmptyDir](#emptydir)をマウントします。
```suggestion
`gitRepo`ボリュームタイプは非推奨です。gitレポジトリを使用してコンテナをプロビジョニングするには、Gitを使用してリポジトリのクローンを作成するInitContainerに[EmptyDir](#emptydir)をマウントしてから、Podのコンテナに[EmptyDir](#emptydir)をマウントします。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +* HostPath は、特権的なシステム認証情報(Kubeletなど)や特権的なAPI(コンテナランタイムソケットなど)を公開する可能性があり、コンテナのエスケープやクラスタの他の部分への攻撃に利用される可能性があります。
```suggestion
* HostPath は、特権的なシステム認証情報(Kubeletなど)や特権的なAPI(コンテナランタイムソケットなど)を公開する可能性があり、コンテナのエスケープやクラスターの他の部分への攻撃に利用される可能性があります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +ただし、`loval`ボリュームは、基盤となるノードの可用性に左右されるため、すべてのアプリケーションに適しているわけではありません。
```suggestion
ただし、`local`ボリュームは、基盤となるノードの可用性に左右されるため、すべてのアプリケーションに適しているわけではありません。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +ローカルボリュームを使用する場合は、PersistentVolume`nodeAffinity`を設定する必要があります。
```suggestion
ローカルボリュームを使用する場合は、PersistentVolume `nodeAffinity`を設定する必要があります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +KubernetesのスケジューラはPersistentVolume`nodeAffinity`を使用して、これらのPodを正しいノードにスケジューリングします。
```suggestion
KubernetesのスケジューラはPersistentVolume `nodeAffinity`を使用して、これらのPodを正しいノードにスケジューリングします。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +PersistentVolume`volumeMode`を(デフォルト値の「Filesystem」ではなく)「Block」に設定して、ローカルボリュームをrawブロックデバイスとして公開できます。
```suggestion
PersistentVolume `volumeMode`を(デフォルト値の「Filesystem」ではなく)「Block」に設定して、ローカルボリュームをrawブロックデバイスとして公開できます。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +ボリュームバインディングを遅延させると、PersistentVolumeClaimバインディングの決定が、ノードリソース要件、ノードセレクタ、Podアフィニティ、Podアンチアフィニティなど、Podが持つ可能性のある他のノード制約も含めて評価されるようになります。
```suggestion
ボリュームバインディングを遅延させると、PersistentVolumeClaimバインディングの決定が、ノードリソース要件、ノードセレクター、Podアフィニティ、Podアンチアフィニティなど、Podが持つ可能性のある他のノード制約も含めて評価されるようになります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +Portworxは、仮想マシンまたはベアメタルLinuxノードでゲスト内で動作します。
```suggestion
Portworxは、仮想マシンまたはベアメタルのLinuxノードでゲスト内動作します。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +この機能を使用するには、クラスタに[Ceph CSIドライバー](https://github.com/ceph/ceph-csi)をインストールし、`CSIMigration`および`csiMigrationRBD`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)を有効にしておく必要があります
```suggestion
この機能を使用するには、クラスターに[Ceph CSIドライバー](https://github.com/ceph/ceph-csi)をインストールし、`CSIMigration`および`csiMigrationRBD`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)を有効にしておく必要があります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +KubernetesvSphereクラウドプロバイダーを設定する必要があります。cloudproviderの設定については、[vSphere入門ガイド](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/)を参照してください。
```suggestion
KubernetesvSphereクラウドプロバイダーを設定する必要があります。クラウドプロバイダーの設定については、[vSphere入門ガイド](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/)を参照してください。

```

リソース名ではない・・・ですよね？多分

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +この機能を使用するには、クラスタに[vSphere CSIドライバー](https://github.com/kubernetes-sigs/vsphere-csi-driver)がインストールされ、`CSIMigration`および`CSIMigrationvSphere`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/f
```suggestion
この機能を使用するには、クラスターに[vSphere CSIドライバー](https://github.com/kubernetes-sigs/vsphere-csi-driver)がインストールされ、`CSIMigration`および`CSIMigrationvSphere`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)が有効になっていなければなりません。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +また、vSphere vCenter/ESXiのバージョンが7.0u1以上、HWのバージョンがVM version 15以上であることが条件となります。
```suggestion
また、vSphere vCenter/ESXiのバージョンが7.0u1以上、HWのバージョンがVM version 15以上であることが条件です。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`vsphereVolume`プラグインがコントローラーマネージャーとkubeletによってロードされないようにするには、`InTreePluginvSphereUnregister`機能フラグを`true`に設定する必要があります。すべてのワーカーノードに`csi.vsphere.vmware.com`{{< glossary_tooltip text="CSI" term_id="csi"
```suggestion
`vsphereVolume`プラグインがコントローラーマネージャーとkubeletによって読み込まれないようにするには、`InTreePluginvSphereUnregister`機能フラグを`true`に設定する必要があります。すべてのワーカーノードに`csi.vsphere.vmware.com`{{< glossary_tooltip text="CSI" term_id="csi" >}}ドライバーをインストールする必要があります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +FlexVolumeは、ストレージドライバーとのインターフェースにexecベースのモデルを使用するアウトオブツリープラグインインターフェースです。FlexVolumeドライバーのバイナリは、各ノード、場合によってはコントロールプレーンノードにも、あらかじめ定義されたボリュームプラグインパスにインストールする必要があります。
```suggestion
FlexVolumeは、ストレージドライバーとのインターフェースにexecベースのモデルを使用するツリー外プラグインインターフェースです。FlexVolumeドライバーのバイナリは、各ノード、場合によってはコントロールプレーンノードにも、あらかじめ定義されたボリュームプラグインパスにインストールする必要があります。

```

ツリー内、に対比して

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +Podは`flexVolume`インツリーボリュームプラグインを通してFlexVolumeドライバーと対話します。
```suggestion
Podは`flexVolume`ツリー内ボリュームプラグインを通してFlexVolumeドライバーと対話します。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`zureFile`の`CSIMigration`機能を有効にすると、既存のin-treeプラグインから`file.csi.azure.com`Container Storage Interface(CSI)Driverへすべてのプラグイン操作がリダイレクトされます。
```suggestion
`zureFile`の`CSIMigration`機能を有効にすると、既存のツリー内プラグインから`file.csi.azure.com`Container Storage Interface(CSI)Driverへすべてのプラグイン操作がリダイレクトされます。

```
後半でツリー内と訳しているので統一しましょう

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +既存のin-treeプラグインからのすべてのプラグイン操作を`cinder.csi.openstack.org`Container Storage Interface(CSI) Driverへリダイレクトします。
```suggestion
既存のツリー内プラグインからのすべてのプラグイン操作を`cinder.csi.openstack.org`Container Storage Interface(CSI) Driverへリダイレクトします。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`CSIMigrationOpenStack`機能を無効にすると、in-treeのCinderボリュームプラグインがCinderボリュームのストレージ管理のすべての側面に責任を持つようになります。
```suggestion
`CSIMigrationOpenStack`機能を無効にすると、ツリー内のCinderボリュームプラグインがCinderボリュームのストレージ管理のすべての側面に責任を持つようになります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +GCE PDの`CSIMigration`機能を有効にすると、すべてのプラグイン操作が既存のin-treeプラグインから`pd.csi.storage.gke.io`Container Storage Interface (CSI) Driverにリダイレクトされるようになります。
```suggestion
GCE PDの`CSIMigration`機能を有効にすると、すべてのプラグイン操作が既存のツリー内プラグインから`pd.csi.storage.gke.io`Container Storage Interface (CSI) Driverにリダイレクトされるようになります。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +* CSIドライバーの動作に必要なパラメーターとして`clusterID`フィールドがありますが、in-tree StorageClassには`monitors`フィールドがあるため、Kubernetesストレージ管理者はCSI config mapでモニターハッシュ(例：`#echo -n '<monitors_string>' | md5sum`)に基づいたclusterIDを作成し、モニタ
```suggestion
* CSIドライバーの動作に必要なパラメーターとして`clusterID`フィールドがありますが、ツリー内StorageClassには`monitors`フィールドがあるため、Kubernetesストレージ管理者はCSI config mapでモニターハッシュ(例：`#echo -n '<monitors_string>' | md5sum`)に基づいたclusterIDを作成し、モニターをこのclusterID設定の下に保持しなければなりません。

```

2022-01-28 13:58 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volumes.md
> +`RBD`の`CSIMigration`機能を有効にすると、既存のin-treeプラグインから`rbd.csi.ceph.com`{{< glossary_tooltip text="CSI" term_id="csi" >}}ドライバーにすべてのプラグイン操作がリダイレクトされます。
```suggestion
`RBD`の`CSIMigration`機能を有効にすると、既存のツリー内プラグインから`rbd.csi.ceph.com`{{< glossary_tooltip text="CSI" term_id="csi" >}}ドライバーにすべてのプラグイン操作がリダイレクトされます。

```

2022-02-03 02:38 UTC, KobayashiD27 commented on content/ja/docs/concepts/storage/volumes.md
> +`vsphereVolume`の`CSIMigration`機能を有効にすると、既存のインツリープラグインから`csi.vsphere.vmware.com`{{< glossary_tooltip text="CSI" term_id="csi" >}}ドライバーにすべてのプラグイン操作がリダイレクトされます。
レビューありがとうございます。指摘いただいた部分を一通り修正しました。

2022-03-04 06:08 UTC, nasa9084 commented
/approve

2022-03-04 06:08 UTC, nasa9084 commented
cc @bells17 @kakts @makocchi-git

2022-03-04 06:09 UTC, nasa9084 commented
/cc @bells17 @kakts @makocchi-git

2022-03-04 06:10 UTC, nasa9084 approved these changes

2022-03-05 05:34 UTC, bells17 commented
/lgtm

2022-03-05 05:34 UTC, merged