Update samples to use containerd
kubernetes/website pull request #31781
Opened 2022-02-17 23:06 UTC by shannonxtreme

Related issue https://github.com/kubernetes/website/issues/30976

The output samples in this page used docker as the runtime. I've switched to samples taken from a cluster running containerd.

/sig docs
/language en

2022-02-18 04:42 UTC, tengqm commented
/approve

2022-02-21 21:51 UTC, sftim requested changes
One thing to fix, otherwise LGTM.

2022-02-21 21:51 UTC, sftim commented on content/en/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +  - ip: 2001:4860:4860::3
Please use a [documentation IP address](https://www.rfc-editor.org/rfc/rfc3849.txt) here.

2022-02-21 21:51 UTC, sftim commented on content/en/docs/tasks/debug-application-cluster/debug-application-introspection.md
> +  IP:           2001:4860:4860::3
Please use a [documentation IP address](https://www.rfc-editor.org/rfc/rfc3849.txt) here.

2022-02-25 15:20 UTC, chrisnegus commented
It looks like the IPv6 IP address has been fixed. If that's it, can someone merge this?
/lgtm

2022-02-25 15:21 UTC, merged