[ko] Update outdated files in `dev-1.23-ko.2` (M60-M73)
kubernetes/website pull request #31880
Opened 2022-02-24 05:17 UTC by jihoon-seo

한 PR에 너무 많은 변경사항을 포함시키면 리뷰하기 어려울 수 있어서, 적절히 분할하여 올립니다. 😊

- Related issue: #31647 (**dev-1.23-ko.2**)

> ### 14 files to be modified
> * [ ]  M60.  `content/en/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace.md`  | 46(+M) 37(-)
> * [ ]  M61.  `content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md`  | 50(+M) 26(-)
> * [ ]  M62.  `content/en/docs/tasks/administer-cluster/manage-resources/quota-memory-cpu-namespace.md`  | 34(+M) 21(-)
> * [ ]  M63.  `content/en/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md`  | 19(+S) 10(-)
>   - 위의 4 파일은 #31793 의 M58, M59 와 유사한 면이 있습니다.
> * [ ]  M64.  `content/en/docs/tasks/configure-pod-container/assign-memory-resource.md`  | 1(+XS) 1(-)
> * [ ]  M65.  `content/en/docs/tasks/configure-pod-container/configure-gmsa.md`  | 28(+S) 60(-)
> * [ ]  M66.  `content/en/docs/tasks/configure-pod-container/pull-image-private-registry.md`  | 10(+S) 6(-)
> * [ ]  M67.  `content/en/docs/tasks/configure-pod-container/static-pod.md`  | 27(+S) 25(-)
> * [ ]  M68.  `content/en/docs/tasks/debug-application-cluster/resource-metrics-pipeline.md`  | 2(+XS) 2(-)
> * [ ]  M69.  `content/en/docs/tasks/inject-data-application/define-command-argument-container.md`  | 1(+XS) 43(-)
> * [ ]  M70.  `content/en/docs/tasks/manage-daemon/update-daemon-set.md`  | 2(+XS) 2(-)
> * [ ]  M71.  `content/en/docs/tasks/manage-kubernetes-objects/kustomization.md`  | 15(+S) 6(-)
> * [ ]  M72.  `content/en/docs/tasks/network/customize-hosts-file-for-pods.md`  | 9(+XS) 4(-)
> * [ ]  M73.  `content/en/docs/tasks/run-application/horizontal-pod-autoscale.md`  | 4(+XS) 3(-)

/language ko

2022-03-05 11:57 UTC, ianychoi requested changes

2022-03-05 11:57 UTC, ianychoi commented on content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +컨테이너는 메모리 요청량을 지정하지 않았으며, 메모리 상한도 지정하지 않았다.
Same as https://github.com/kubernetes/website/pull/31793#discussion_r820085964 thx

2022-03-05 11:57 UTC, ianychoi commented on content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +컨테이너는 메모리 상한은 지정했지만, 요청량은 지정하지 않았다.
Same as https://github.com/kubernetes/website/pull/31793#discussion_r820085964 thx

2022-03-05 11:57 UTC, ianychoi commented on content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +컨테이너는 메모리 요청량은 지정했지만, 상한은 지정하지 않았다.
Similar as https://github.com/kubernetes/website/pull/31793#discussion_r820085964 thx

2022-03-05 11:57 UTC, ianychoi commented on content/ko/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
> +{{< glossary_tooltip text="크론잡" term_id="cronjob" >}}의 청 수를 제한할 수 있다.
"청" -> "요청"?

2022-03-05 11:57 UTC, ianychoi commented on content/ko/docs/tasks/manage-kubernetes-objects/kustomization.md
> +# deployment.yaml 파일 생성(문서 구분 기호를 따옴표로 감쌈)
Open Q: How about '인용부호' instead of '따옴표'?

2022-03-05 11:57 UTC, ianychoi commented on content/ko/docs/tasks/network/customize-hosts-file-for-pods.md
> +
Any reason of adding blank lines on L2-4, although I see that the original markdown has 'reviewers:' part?

2022-03-05 11:57 UTC, ianychoi commented
/assign me

2022-03-05 11:57 UTC, ianychoi commented
/assign

2022-03-10 05:37 UTC, jihoon-seo reviewed
@ianychoi 리뷰 감사합니다. 😊
저의 의견을 달았습니다.
확인 부탁드립니다. 😊

2022-03-10 05:37 UTC, jihoon-seo commented on content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +컨테이너는 메모리 요청량을 지정하지 않았으며, 메모리 상한도 지정하지 않았다.
변경하겠습니다. 😊

2022-03-10 05:37 UTC, jihoon-seo commented on content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +컨테이너는 메모리 상한은 지정했지만, 요청량은 지정하지 않았다.
변경하겠습니다. 😊

2022-03-10 05:37 UTC, jihoon-seo commented on content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +컨테이너는 메모리 요청량은 지정했지만, 상한은 지정하지 않았다.
변경하겠습니다. 😊

2022-03-10 05:37 UTC, jihoon-seo commented on content/ko/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +쿠버네티스 클러스터는 여러 개의 네임스페이스로 파티션할 수 있다.
https://github.com/kubernetes/website/pull/31793#discussion_r820085489 에 따라
'쿠버네티스 클러스터를 여러 네임스페이스로 나눌 수 있다.' 로 변경하겠습니다.

2022-03-10 05:37 UTC, jihoon-seo commented on content/ko/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace.md
> +{{< glossary_tooltip text="크론잡" term_id="cronjob" >}}의 청 수를 제한할 수 있다.
[[원문](https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/quota-pod-namespace/#choice-of-resource)]
> For example, you might decide to limit how many [CronJobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) that can live in a single namespace.

"총" 을 의도했는데 오타가 났네요 😅

```suggestion
{{< glossary_tooltip text="크론잡" term_id="cronjob" >}}의 총 수를 제한할 수 있다.
```

(바로 위 문장 `하지만, 다른 종류의 오브젝트의 총 수를 제한할 수도 있다.` 와의 consistency를 고려했습니다)

<!--
또는, "총" 을 쓰지 않을 수도 있겠습니다.

```suggestion
{{< glossary_tooltip text="크론잡" term_id="cronjob" >}}의 수를 제한할 수 있다.
```
("예를 들어, 한 네임스페이스에 존재할 수 있는 크론잡의 수를 제한할 수 있다.")
-->

2022-03-10 05:37 UTC, jihoon-seo commented on content/ko/docs/tasks/manage-kubernetes-objects/kustomization.md
> +# deployment.yaml 파일 생성(문서 구분 기호를 따옴표로 감쌈)
훔.. '인용부호' 는 한자어이고, '따옴표' 는 우리말 이네요.. 😊
저는 두 쪽 모두 괜찮습니다. 😊

2022-03-10 05:37 UTC, jihoon-seo commented on content/ko/docs/tasks/network/customize-hosts-file-for-pods.md
> +
해당 리뷰어들은 en 파일에 대한 리뷰어로 보입니다.
이 자리에 en 리뷰어 라인을 그대로 보존해도
GitHub PR 리뷰 요청 시에 적용이 되는 것은 아니지만 (즉, 이 라인이 GitHub PR 리뷰어 선정에 영향을 미치지는 않지만)

(대신, k8s prow bot이 해당 PR의 변경 파일을 보고
예를 들어 `content/ko/` 아래의 파일들이 변경되었으면
`sig-docs-ko-reviewers` 중 2명을 리뷰어로 지정하는 것으로 보입니다. 😊)

그래도 한국어 파일을 리뷰하기에는 적합하지 않은 en 리뷰어들을 기재해 둘 이유가 적어서 삭제하였으며
영문 파일과의 line-by-line 비교를 수월하게 만들기 위해
대신 빈 줄을 넣었습니다. 😊

2022-03-18 12:40 UTC, ianychoi commented on content/ko/docs/tasks/manage-kubernetes-objects/kustomization.md
> +# deployment.yaml 파일 생성(문서 구분 기호를 따옴표로 감쌈)
Not sure this is my prejudice or not, but I generally feel that '따옴표' first imagines '쌍따옴표'. Anyway, I asked as an open question. I will respect author's preference

2022-03-18 12:41 UTC, ianychoi commented
Done on my comment

2022-03-21 09:18 UTC, jihoon-seo commented
@ianychoi 위의 사항들을 반영하였고, 변경 사항을 편하게 확인하실 수 있도록 squash는 하지 않았습니다.
추후 squash 하겠습니다. 😊

2022-03-31 23:12 UTC, gochist reviewed
/lgtm

2022-04-05 04:06 UTC, seokho-son commented
/lgtm

@ianychoi 님의 의견도 반영된 것으로 보여서, 브랜치 일정 관리 차원에서 해당 PR은 빠르게 처리하고자 합니다.
확인 가능하시면, 확인 후 change requested 해지를 부탁 드릴게요.
혹시 확인이 어려우시다면 dismiss review 처리하고 진행하도록 하려고 합니다. :)

@jihoon-seo 일단 스쿼시 부탁 드릴게요! :)

2022-04-05 04:21 UTC, jihoon-seo commented
@seokho-son 감사합니다. squash 하였습니다. 😊

2022-04-07 00:58 UTC, seokho-son commented
/approve

2022-04-07 00:59 UTC, merged