[zh] Translate enforcing PSS
kubernetes/website pull request #31926
Opened 2022-02-26 12:55 UTC by tengqm

This PR translates two files missing in zh localization and syncs two
related files for consistency.

2022-02-27 22:13 UTC, sftim commented on content/zh/docs/concepts/security/pod-security-admission.md
> +  对 Pod 安全性准入控制器的概述，Pod 安全性准入控制器可以实施 Pod 安全性标准
Should this end with “。”?

2022-03-01 07:36 UTC, howieyuen requested changes

2022-03-01 07:36 UTC, howieyuen commented on content/zh/docs/concepts/security/pod-security-admission.md
> +- **用户名：** 来自用户名已被豁免的、已认证的（或伪装的）的用户的请求会被忽略。
这里保留原文会更好一些，Usernames、RuntimeClassNames 和 Namespaces 应该都是 field name
ps：Namespaces 这行没翻译

2022-03-01 07:36 UTC, howieyuen commented on content/zh/docs/setup/best-practices/enforcing-pod-security-standards.md
> +能够在不影响现有负载的前提下，让该控制器更方便地收集关于 Pods 的重要的安全信息。
```suggestion
能够在不影响现有负载的前提下，让该控制器更方便地收集关于 Pod 的重要的安全信息。
```

2022-03-01 07:36 UTC, howieyuen commented on content/zh/docs/setup/best-practices/enforcing-pod-security-standards.md
> +### 采用多种模式的策略
```suggestion
### 采用多模式的策略
```

2022-03-01 07:36 UTC, howieyuen commented on content/zh/docs/setup/best-practices/enforcing-pod-security-standards.md
> +- 通过将 `warn` 设置为 `enforce` 相同的级别，客户可以在尝试创建无法通过合法检查的 Pods
```suggestion
- 通过将 `warn` 设置为 `enforce` 相同的级别，客户可以在尝试创建无法通过合法检查的 Pod
```

2022-03-01 08:26 UTC, tengqm commented on content/zh/docs/concepts/security/pod-security-admission.md
> +- **用户名：** 来自用户名已被豁免的、已认证的（或伪装的）的用户的请求会被忽略。
OK。

2022-03-01 08:29 UTC, tengqm commented on content/zh/docs/setup/best-practices/enforcing-pod-security-standards.md
> +### 采用多种模式的策略
英文原文的“multi-mode”很让人费解，因为这里的正文并没有讨论这样一种专门的“模式”。
本小节的正文实际上是在讨论多种模式的混合使用，因此翻译为“多种模式”会更贴切，读起来也不别扭。

2022-03-01 09:23 UTC, howieyuen commented on content/zh/docs/setup/best-practices/enforcing-pod-security-standards.md
> +### 采用多种模式的策略
ok

2022-03-01 09:23 UTC, howieyuen commented
/lgtm

2022-03-03 02:33 UTC, howieyuen commented
/approve

2022-03-03 02:34 UTC, merged