[zh] Translate the migrating from PSP page
kubernetes/website pull request #31939
Opened 2022-02-27 07:37 UTC by tengqm

2022-02-27 08:41 UTC, tengqm commented
Preview: https://deploy-preview-31939--kubernetes-io-main-staging.netlify.app/zh/docs/tasks/configure-pod-container/migrate-from-psp/

2022-02-28 12:47 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +同时将安全性的差距压缩到最小。
对 security gap 有别的翻译建议么？

2022-03-01 03:22 UTC, mengjiao-liu commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +同时将安全性的差距压缩到最小。
“安全漏洞” 或者 “安全隐患” ？

2022-03-01 05:20 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +同时将安全性的差距压缩到最小。
安全隐患或者安全风险应该都可以。原文的 security gap 我理解是跟业界最佳实践或理想状况之间的差距。

2022-03-01 06:53 UTC, mengjiao-liu commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +同时将安全性的差距压缩到最小。
理解成“业界最佳实践或理想状况之间的差距” 是可以的，但是 “安全性的差距” 给人的第一印象是不清楚在跟谁比较。

而且从英文原文来讲：
`with a goal of minimizing both therisks of a production outage and of a security gap.`
那 `production outage` 和 `security gap` 应该是同级的：

- 降低  `production outage`（生产不可用）风险
- 降低  `security gap`(xxx) 风险

我的理解是这样，让我们看看更多人的意见？/cc @howieyuen @chenrui333 @xichengliudui @tanjunchen

2022-03-01 08:20 UTC, howieyuen requested changes

2022-03-01 08:20 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +一旦你已经为名字空间选择了 Pod 安全性级别（或者你已经尝试了多个级别），
```suggestion
一旦你已经为名字空间选择了 Pod 安全性级别（或者你正在尝试多个级别），
```

2022-03-01 08:20 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +此命令会针对在所提议的级别下不再合法的所有 _现有_ Pod 返回警告信息。
```suggestion
此命令会针对在所提议的级别下所有不合法的 _现存_ Pod 返回警告信息。
```

2022-03-01 08:20 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +[配置准入控制器](/zhdocs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller)
```suggestion
[配置准入控制器](/zh/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller)
```

2022-03-01 08:20 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +同时将安全性的差距压缩到最小。
我理解，这里的gap指的是 PSP 和 PSA 之前的安全差距

2022-03-01 08:34 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +来控制的。这也就是说，任何能够更新（或通过 patch 部分更新或创建）
这里的 patch 实际上指的是 k8s API 中的 verb 之一，patch 用来实现部分更新，put 作整体替换。
现在这样处理可能更明确一些。

2022-03-01 08:35 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/migrate-from-psp.md
> +一旦你已经为名字空间选择了 Pod 安全性级别（或者你已经尝试了多个级别），
correct.

2022-03-01 09:23 UTC, howieyuen commented
/lgtm

2022-03-03 02:32 UTC, howieyuen commented
/approve

2022-03-03 02:50 UTC, merged