[zh] Translate projected volume page
kubernetes/website pull request #31945
Opened 2022-02-27 12:02 UTC by tengqm

2022-02-27 12:48 UTC, tengqm commented
Preview: https://deploy-preview-31945--kubernetes-io-main-staging.netlify.app/zh/docs/concepts/storage/projected-volumes/

2022-03-01 06:00 UTC, howieyuen requested changes

2022-03-01 06:00 UTC, howieyuen commented on content/zh/docs/concepts/storage/projected-volumes.md
> +在创建 Windows Pod 时，如何在其 `SecurityContext` 中设置了 `RunAsUser`，
```suggestion
在创建 Windows Pod 时，如果在其 `SecurityContext` 中设置了 `RunAsUser`，
```

2022-03-01 07:55 UTC, tengqm commented on content/zh/docs/concepts/storage/projected-volumes.md
> +reviewers:
These lines are in comments. Our convention is to keep them.

2022-03-01 08:23 UTC, howieyuen commented on content/zh/docs/concepts/storage/projected-volumes.md
> +reviewers:
last time, I was told to remove these, so I leave them not in comment? omg...

2022-03-01 08:39 UTC, tengqm commented on content/zh/docs/concepts/storage/projected-volumes.md
> +reviewers:
probably. We are supposed to leave them their only as comments.

2022-03-03 02:32 UTC, howieyuen commented
/approve

2022-03-03 03:00 UTC, merged