[zh] Translate API server config v1alpha1 reference
kubernetes/website pull request #31942
Opened 2022-02-27 09:59 UTC by tengqm

2022-02-27 10:19 UTC, tengqm commented
Preview: https://deploy-preview-31942--kubernetes-io-main-staging.netlify.app/zh/docs/reference/config-api/apiserver-config.v1alpha1/

2022-03-12 09:49 UTC, howieyuen requested changes

2022-03-12 09:49 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-config.v1alpha1.md
> +   <code>path</code> 为指向包含插件配置数据的配置文件的位置。
```suggestion
   <code>path</code> 为指向包含插件配置数据的配置文件的路径。
```

2022-03-12 09:49 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-config.v1alpha1.md
> +  &quot;master&quot; Egress 选择器以被弃用，推荐使用 &quot;controlplane&quot;。
```suggestion
  &quot;master&quot; Egress 选择器已被弃用，推荐使用 &quot;controlplane&quot;。
```

2022-03-12 09:49 UTC, howieyuen commented on content/zh/docs/reference/config-api/apiserver-config.v1alpha1.md
> +If absent while TCPTransport.URL is prefixed with https://, default to system trust roots.-->
here missing translation?

2022-03-13 03:54 UTC, howieyuen commented
/approve

2022-03-23 03:01 UTC, howieyuen commented
/lgtm

2022-03-23 03:03 UTC, merged