[zh] Translate docker to crictl map page
kubernetes/website pull request #31943
Opened 2022-02-27 10:18 UTC by tengqm

2022-02-27 11:25 UTC, tengqm commented
Preview: https://deploy-preview-31943--kubernetes-io-main-staging.netlify.app/zh/docs/reference/tools/map-crictl-dockercli/

2022-03-01 05:42 UTC, howieyuen requested changes

2022-03-01 05:42 UTC, howieyuen commented on content/zh/docs/reference/tools/map-crictl-dockercli.md
> +`crictl` 是 {{<glossary_tooltip term_id="cri" text="CRI">}}-兼容的容器运行时的一种命令行接口。
```suggestion
`crictl` 是一种兼容 {{<glossary_tooltip term_id="cri" text="CRI">} 的容器运行时的命令行接口。
```

2022-03-01 08:21 UTC, howieyuen commented
/lgtm

2022-03-03 02:32 UTC, howieyuen commented
/approve

2022-03-03 02:56 UTC, merged