[zh] Translate kubelet config v1alpha1 reference
kubernetes/website pull request #31951
Opened 2022-02-27 14:32 UTC by tengqm

2022-02-27 14:54 UTC, tengqm commented
Preview: https://deploy-preview-31951--kubernetes-io-main-staging.netlify.app/zh/docs/reference/config-api/kubelet-config.v1alpha1/

2022-03-05 10:12 UTC, howieyuen requested changes

2022-03-05 10:12 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1alpha1.md
> +如果字符串之一与 kubelet 所请求的镜像匹配，则此插件会被调用并给予提供凭证的机会。
```suggestion
如果列表之一与 kubelet 所请求的镜像匹配，则此插件会被调用并给予提供凭证的机会。
```

2022-03-05 10:12 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1alpha1.md
> +CredentialProviderConfig 包含关于每个 exec 凭据提供者的配置信息。
```suggestion
CredentialProviderConfig 包含有关每个 exec 凭据提供者的配置信息。
```

2022-03-06 02:31 UTC, tengqm commented on content/zh/docs/reference/config-api/kubelet-config.v1alpha1.md
> +如果字符串之一与 kubelet 所请求的镜像匹配，则此插件会被调用并给予提供凭证的机会。
我觉得还是表达成“字符串之一”更准确。

2022-03-06 13:49 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1alpha1.md
> +如果字符串之一与 kubelet 所请求的镜像匹配，则此插件会被调用并给予提供凭证的机会。
ok

2022-03-06 13:50 UTC, howieyuen commented
/approve

2022-03-23 03:01 UTC, howieyuen commented
/lgtm

2022-03-23 03:01 UTC, merged