Modify the expulsion link initiated by API
kubernetes/website pull request #31975
Opened 2022-03-01 02:22 UTC by pangqing123

Signed-off-by: pangqing <pangqing@uniontech.com>

2022-03-01 04:48 UTC, howieyuen requested changes

2022-03-01 04:48 UTC, howieyuen commented on ！
> +-->
missing translation

2022-03-01 04:48 UTC, howieyuen commented on ！
> +---
no_list: true

2022-03-01 04:48 UTC, howieyuen commented on ！
> +  在Kubernetes中，调度 (scheduling) 指的是确保 Pods 匹配到合适的节点，
pod/pods/Pods -> Pod，same as below

```suggestion
  在 Kubernetes 中，调度（scheduling）指的是确保 Pod 匹配到合适的节点，
```

2022-03-01 04:48 UTC, howieyuen commented on ！
> +  以便 kubelet 能够运行它们。抢占 (Preemption) 指的是终止低优先级的 Pods 以便高优先级的 Pods 可以
```suggestion
  以便 kubelet 能够运行它们。抢占（Preemption）指的是终止低优先级的 Pod 以便高优先级的 Pod 可以
```

2022-03-01 04:48 UTC, howieyuen commented on ！
> +  调度运行的过程。驱逐 (Eviction) 是在资源匮乏的节点上，主动让一个或多个 Pods 失效的过程。
```suggestion
  调度运行的过程。驱逐（Eviction）是在资源匮乏的节点上，主动让一个或多个 Pod 失效的过程。
```

2022-03-01 04:48 UTC, howieyuen commented on ！
> +* [Kubernetes 调度器](/zh/docs/concepts/scheduling-eviction/kube-scheduler/)
missing original text

2022-03-01 04:48 UTC, howieyuen commented on ！
> +* [Pod 优先级和抢占](/zh/docs/concepts/scheduling-eviction/pod-priority-preemption/)
missing original text

2022-03-01 13:34 UTC, sftim commented on content/zh/docs/concepts/scheduling-eviction/node-pressure-eviction.md
> +* Learn about [API-initiated Eviction](/docs/reference/generated/kubernetes-api/v1.23/)
Does this match the English original text? (It should be equivalent, but obviously in Chinese not English).

2022-03-05 10:15 UTC, howieyuen commented
/approve

2022-03-05 12:03 UTC, tanjunchen reviewed
/lgtm

2022-03-05 12:04 UTC, merged