[zh] Translate kubelet config v1beta1
kubernetes/website pull request #31976
Opened 2022-03-01 04:47 UTC by tengqm

2022-03-05 15:24 UTC, FOWind commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +如果动态更新了此字段，新的 ULR 上包含的静态 Pod 集合可能与 kubelet
“新的 ULR 上” -> "新的 URL 上"

2022-03-05 15:27 UTC, FOWind commented
“请考虑 xxxx 带来的问题” 改成 “请权衡 xxx 带来的问题” 会不会更好一点

2022-04-12 04:59 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +的默认值是&quot;5m&quot;。不过，如果<code>nodeStatusUpdateFrequency</code>
原文没有 quote 5m

2022-04-12 05:04 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>DynamicKubeletConfig</code> （已弃用）：
感觉原文在这个 DynamicKubeletConfig ref 上不是特别一致

2022-04-12 05:06 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +Pd。</li>
```suggestion
Pod。</li>
```

2022-04-12 05:08 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +存储后端的节点上更改默认值。详细信息可参见 #10959。</p>
这个 issue 是不翻译的对吧？

2022-04-12 05:09 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p>注意：由于 Issue #64530 的原因，系统中存在一个缺陷，即此处所设置的值会在软性逐出时覆盖
那上面应该要标注一下 issue as this one

2022-04-12 05:12 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +相关线程所预留的 CPU 列表。此字段提供的是一种“静态”的 CPU 列表，而不是像
```suggestion
相关线程所预留的 CPU 列表。此字段提供的是一种&quot;静态&quot;的 CPU 列表，而不是像
```

2022-04-12 05:12 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +<code>systemReserved</code>和<code>kubeReserved</code>所提供的“动态”列表。
```suggestion
<code>systemReserved</code>和<code>kubeReserved</code>所提供的&quot;动态&quot;列表。
```

2022-04-12 05:13 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +参阅<a href="https://git.k8s.io/community/contributors/design-proposals/node/node-allocatable.md">Node Allocatable</a>
这应该用 markdown instead of archor ref?

2022-04-12 05:21 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +Default: "1m"-->
这里这个原文好像 没有 escape

2022-04-12 05:21 UTC, chenrui333 reviewed
除了一些小的地方 大部分都 lgtm

2022-04-12 05:22 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>DynamicKubeletConfig</code> （已弃用）：
有些地方是 `deprecated` 有些地方是 `deprecated, default disabled`.

2022-04-12 11:11 UTC, tengqm commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>DynamicKubeletConfig</code> （已弃用）：
原文是人写的 ...

2022-04-12 11:13 UTC, tengqm commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +参阅<a href="https://git.k8s.io/community/contributors/design-proposals/node/node-allocatable.md">Node Allocatable</a>
markdown 嵌套在 HTML 里面的时候不被解析。

2022-04-13 09:58 UTC, howieyuen requested changes
暂且 review 到 500 行，主要就是格式问题：
- 代码用 <code> 标签，前后空格
- 默认值的引号，是否需要 `&quot;`

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +如果动态更新了此字段，要考虑可能导致无法从<code>staticPodURL</code>
```suggestion
如果动态更新了此字段，要考虑可能导致无法从 <code>staticPodURL</code>
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +和<code>tlsPrivateKeyFile</code>都没有设置，则系统会为节点的公开地址生成自签名的证书和私钥，
```suggestion
和 <code>tlsPrivateKeyFile</code> 都没有设置，则系统会为节点的公开地址生成自签名的证书和私钥，
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>tlsPrivateKeyFile</code>是一个包含与<code>tlsCertFile</code>
```suggestion
   <p><code>tlsPrivateKeyFile</code> 是一个包含与 <code>tlsCertFile</code>
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +  <p>默认值：""</p>
下文有将双引号改成 `&quot;`，这个在渲染时，需要注意吗？

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>tlsMinVersion</code>给出所支持的最小 TLS 版本。
```suggestion
   <p><code>tlsMinVersion</code> 给出所支持的最小 TLS 版本。
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +字段取值来自于<code>tls</code>包中的常数定义（https://golang.org/pkg/crypto/tls/#pkg-constants）。</p>
```suggestion
字段取值来自于 <code>tls</code> 包中的常数定义（https://golang.org/pkg/crypto/tls/#pkg-constants）。</p>
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>rotateCertificates</code>用来启用客户端证书轮换。kubelet 会调用
```suggestion
   <p><code>rotateCertificates</code> 用来启用客户端证书轮换。kubelet 会调用
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>serverTLSBootstrap</code>用来启用服务器证书引导。系统不再使用自签名的服务证书，
```suggestion
   <p><code>serverTLSBootstrap</code> 用来启用服务器证书引导。系统不再使用自签名的服务证书，
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +kubelet 会调用<code>certificates.k8s.io</code> API 来请求证书。
```suggestion
kubelet 会调用 <code>certificates.k8s.io</code> API 来请求证书。
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +设置此字段时，<code>RotateKubeletServerCertificate</code>特性必须被启用。</p>
```suggestion
设置此字段时，<code>RotateKubeletServerCertificate</code> 特性必须被启用。</p>
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>authorization</code>设置发送给 kubelet 服务器的请求是如何进行身份认证的。</p>
```suggestion
   <p><code>authorization</code> 设置发送给 kubelet 服务器的请求是如何进行身份认证的。</p>
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>authorization</code>设置发送给 kubelet 服务器的请求是如何进行鉴权的。</p>
```suggestion
   <p><code>authorization</code> 设置发送给 kubelet 服务器的请求是如何进行鉴权的。</p>
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>registryPullQPS</code>是每秒钟可以执行的镜像仓库拉取操作限值。
```suggestion
   <p><code>registryPullQPS</code> 是每秒钟可以执行的镜像仓库拉取操作限值。
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>registryBurst</code>是突发性镜像拉取的上限值，允许镜像拉取临时上升到所指定数量，
```suggestion
   <p><code>registryBurst</code> 是突发性镜像拉取的上限值，允许镜像拉取临时上升到所指定数量，
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +不过仍然不超过<code>registryPullQPS</code>所设置的约束。此值必须是非负值。
```suggestion
不过仍然不超过 <code>registryPullQPS</code> 所设置的约束。此值必须是非负值。
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +只有<code>registryPullQPS</code>参数值大于 0 时才会使用此设置。</p>
```suggestion
只有 <code>registryPullQPS</code> 参数值大于 0 时才会使用此设置。</p>
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>eventRecordQPS</code>设置每秒钟可创建的事件个数上限。如果此值为 0，
```suggestion
   <p><code>eventRecordQPS</code> 设置每秒钟可创建的事件个数上限。如果此值为 0，
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +   <p><code>eventBurst</code>是突发性事件创建的上限值，允许事件创建临时上升到所指定数量，
```suggestion
   <p><code>eventBurst</code> 是突发性事件创建的上限值，允许事件创建临时上升到所指定数量，
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +不过仍然不超过<code>eventRecordQPS</code>所设置的约束。此值必须是非负值，
```suggestion
不过仍然不超过 <code>eventRecordQPS</code> 所设置的约束。此值必须是非负值，
```

2022-04-13 09:58 UTC, howieyuen commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +且只有<code>eventRecordQPS</code>大于 0 时才会使用此设置。</p>
```suggestion
且只有 <code>eventRecordQPS</code> 大于 0 时才会使用此设置。</p>
```

2022-04-14 00:24 UTC, tengqm commented
> 暂且 review 到 500 行，主要就是格式问题：
> 
>     * 代码用 `<code>` 标签，前后空格
> 
>     * 默认值的引号，是否需要改成 `&quot;`

code 前后的空格是有意去掉的，因为 code 的样式表定义保证了中文和英文之间有一定的留白，再加一些留白也不是不可以，看渲染效果上有点多余。

双引号是直接输入还是用  `&quot;`，其实差别不大，效果是一样的。对于 reference 文档而言，因为统一经过一次程序化处理，很多地方直接转成 `&quot;` 了，包括将 `*` 转换成 `&lowast;` 也是这个原因。

2022-04-14 17:07 UTC, chenrui333 commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +如果动态更新了此字段，请考虑可能影响到 kubelet 与云驱动之间进行交互的能力。</p>
我也是第一次看到 云驱动 如果是云驱动的话 那原文是 cloud driver instead of cloud provider. 英文是 cloud provider, 那翻译成为云厂商，我个人是觉得没有问题的。你觉得呢？

2022-04-15 00:51 UTC, tengqm commented on content/zh/docs/reference/config-api/kubelet-config.v1beta1.md
> +如果动态更新了此字段，请考虑可能影响到 kubelet 与云驱动之间进行交互的能力。</p>
cloud provider 要根据上下文来判断。如果指的是云平台后面的厂商，翻译成云厂商更合适。如果是云平台提供的、特定于某个厂商的支持框架、插件、扩展程序，可以翻译为云驱动。

2022-04-15 02:12 UTC, howieyuen commented
> > 暂且 review 到 500 行，主要就是格式问题：
> > ```
> > * 代码用 `<code>` 标签，前后空格
> > 
> > * 默认值的引号，是否需要改成 `&quot;`
> > ```
> 
> code 前后的空格是有意去掉的，因为 code 的样式表定义保证了中文和英文之间有一定的留白，再加一些留白也不是不可以，看渲染效果上有点多余。
> 
> 双引号是直接输入还是用 `&quot;`，其实差别不大，效果是一样的。对于 reference 文档而言，因为统一经过一次程序化处理，很多地方直接转成 `&quot;` 了，包括将 `*` 转换成 `&lowast;` 也是这个原因。

ok, I got it

2022-04-17 05:07 UTC, howieyuen requested changes
这次看到 1500 行，发现一个小问题

2022-04-18 12:05 UTC, howieyuen approved these changes
omg...how much effort of this pr is totally beyond imagination.
Thanks.

2022-04-23 12:19 UTC, mengjiao-liu commented
/approve
/lgtm
Thanks!  Great job!

2022-04-23 12:19 UTC, merged