fix busybox image to version 1.28
kubernetes/website pull request #31989
Opened 2022-03-01 20:42 UTC by guettli

The current busybox image has issues with `nslookup`.

This confuses users again and again.

This PR fixes the image to `busybox:1.28`.

2022-03-01 22:02 UTC, sftim requested changes
@guettli please restrict this change to just English, as per https://kubernetes.io/docs/contribute/new-content/#languages-per-pr

Making these changes across lots of localizations is problematic because each localization team already has a workflow for adapting changes that are made to English.


Please _also_ update the PR description to make it clear **why** this change is required and appropriate. If you omit that justification, you're expecting reviewers to provide that context themselves.

2022-03-02 19:50 UTC, guettli commented
@sftim thank you for looking into my PR. I updated the PR to only change "en". I added two links to related issues which explain the issue in depth. Please let me know if there is anything which I need to do.

2022-03-03 01:10 UTC, kbhawkey commented
/remove-language de es fr id it

2022-03-03 01:11 UTC, kbhawkey commented
/remove-language ja ko pt ru vi zh

2022-03-25 05:51 UTC, tengqm commented
/approve

2022-03-25 22:44 UTC, reylejano commented
/lgtm

2022-03-25 22:45 UTC, merged