--all-namespaces shorthand
kubernetes/website pull request #32012
Opened 2022-03-02 17:21 UTC by bwolmarans

As a beginner to kubectl, I must have typed (and re-typed due to typos) --all-namespaces many hundreds of times before I stumbled across the -A shorthand notation for this.  I sincerely would be grateful on behalf of all kubectl beginners if this very useful cheat could be added to this cheatsheet.  I have proposed in this PR a location quite near the beginning of the cheatsheet for this so that it is very hard to miss.

2022-03-03 09:16 UTC, Arhell reviewed
Please sign CLA
https://github.com/kubernetes/website/pull/32012#issuecomment-1057182586

2022-03-03 11:20 UTC, sftim requested changes
How about adding an extra line after the first mention:
```diff
  kubectl get pods --all-namespaces             # List all pods in all namespaces
+ kubectl get pods -a                           # List all pods in all namespaces (less typing)
```

I'm not sure this needs its own heading; it's important to keep the cheat-sheet short.
For people who want to learn kubectl, we should provide other pages to explain how it works.

2022-03-03 11:20 UTC, sftim commented
Oops, reviewed before CLA was signed. Review will likely still apply after signing!

2022-03-03 16:12 UTC, bwolmarans commented
> Oops, reviewed before CLA was signed. Review will likely still apply after signing!

I just clicked on the CLA and it does not permit individuals only corps, but I am between jobs so I don't have anyone to sign it.  My new job starts in a few weeks so I could do it then?

2022-03-04 03:43 UTC, RA489 commented
/easycla

2022-03-23 23:36 UTC, reylejano commented
Hi @bwolmarans ,

Just a reminder to [lease sign the EasyCLA
https://github.com/kubernetes/community/blob/master/CLA.md

2022-03-24 17:13 UTC, bwolmarans commented
> 

done, ty

2022-03-24 17:19 UTC, sftim reviewed
@bwolmarans please consider the comments from https://github.com/kubernetes/website/pull/32012#pullrequestreview-898783520

Failing that, I have some formatting feedback.

2022-03-24 17:19 UTC, sftim commented on content/en/docs/reference/kubectl/cheatsheet.md
> +Appending --all-namespaces happens frequently enough where you should be aware of the  shorthand for --all-namespaces:
```suggestion
Appending `--all-namespaces` happens frequently enough where you should be aware of the  shorthand for `--all-namespaces`:
```

2022-03-24 17:29 UTC, bwolmarans commented on content/en/docs/reference/kubectl/cheatsheet.md
> +Appending --all-namespaces happens frequently enough where you should be aware of the  shorthand for --all-namespaces:
looks good thank you

2022-03-25 22:41 UTC, reylejano commented
Thank you for addressing the feedback
/lgtm
/approve

2022-03-25 22:41 UTC, merged