Translate docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md into Chinese
kubernetes/website pull request #32038
Opened 2022-03-04 07:51 UTC by shixiuguo

Fixes #32024

2022-03-05 09:46 UTC, howieyuen requested changes

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +<!--
leave the translation in comment block...

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +该文件是使用通用Go源码自动生成的组件 [生成器](https://github.com/kubernetes-sigs/reference-docs/)。
中英文混合时，英文前后需要添加空格，句末除外
```suggestion
该文件是使用通用 Go 源码自动生成的组件[生成器](https://github.com/kubernetes-sigs/reference-docs/)。
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +学习如何生成参考文档，请阅读 [贡献参考文档](/docs/contribute/generate-ref-docs/)。
except API reference page, other links should be localized 
```suggestion
学习如何生成参考文档，请阅读[贡献参考文档](/zh/docs/contribute/generate-ref-docs/)。
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +更新参考内容，请按照 [贡献上游](/docs/contribute/generate-ref-docs/contribute-upstream/)。
```suggestion
更新参考内容，请按照[贡献上游](/zh/docs/contribute/generate-ref-docs/contribute-upstream/)指南。
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +针对文档格式化，可以参考 [参考文档](https://github.com/kubernetes-sigs/reference-docs/)。
```suggestion
你可以针对[参考文档](https://github.com/kubernetes-sigs/reference-docs/)提交文档格式错误。
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +   节点选择器是一个需要包含键、值以及一个将键与值关联起来的运算符的选择器。
```suggestion
节点选择器要求包含键、值和关联键和值的运算符的选择器。
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +description: "节点选择器是一个需要包含键、值以及一个将键与值关联起来的运算符的选择器"
```suggestion
description: "节点选择器要求包含键、值和关联键和值的运算符的选择器"
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +- **key**（字符串），必选项
```suggestion
- **key**（string），必选
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +   key是一种被选择器使用的标签。
```suggestion
   选择器适用的标签键。
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +- **operator** (字符串), 必选项
```suggestion
- **operator** (string)，必选
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +  operator是表示键与一组值的关系的运算符。有效的运算符包括：In、NotIn、Exists、DoesNotExist、Gt和Lt。
```suggestion
  表示键与一组值的关系的运算符。有效的运算符包括：In、NotIn、Exists、DoesNotExist、Gt 和 Lt。
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +  可用的取值:
```suggestion
  可选值：
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +- **values** （字符串数组）
```suggestion
- **values** （[]string）
```

2022-03-05 09:46 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +   values是一个字符串数组。如果运算符为In或NotIn，则该数组必须为非空。如果运算符为Exists或DoesNotExist，则该数组必须为空。如果运算符为Gt或Lt，则数组必须有一个元素，该元素将被看作整数。该数组会在合入全局补丁时被替换。
proper line break, which makes CR easier and cleaner
```suggestion
  字符串数组。 如果运算符为 In 或 NotIn，则数组必须为非空。
  如果运算符是 Exists 或 DoesNotExist，则数组必须为空。
  如果运算符是 Gt 或 Lt，则数组必须有一个元素，该元素将被译为整数。
  该数组在合并计划补丁是时被替换。
```

2022-03-07 07:42 UTC, howieyuen requested changes

2022-03-07 07:42 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +<!--
译文被注释了，删除36行和41行的 html 注释标签

2022-03-07 07:44 UTC, shixiuguo commented on content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md
> +<!--
这一段上面的原文就是注释的

2022-03-08 07:07 UTC, shixiuguo commented
您好，这一段在英文文档里，原本就是注释的













在 2022-03-07 15:42:35，"Hao Yuan" ***@***.***> 写道：

@howieyuen requested changes on this pull request.

In content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md:

> +weight: 5

+auto_generated: true

+---

+-->

+

+<!--

+The file is auto-generated from the Go source code of the component using a generic

+[generator](https://github.com/kubernetes-sigs/reference-docs/). To learn how

+to generate the reference documentation, please read

+[Contributing to the reference documentation](/docs/contribute/generate-ref-docs/).

+To update the reference content, please follow the 

+[Contributing upstream](/docs/contribute/generate-ref-docs/contribute-upstream/)

+guide. You can file document formatting bugs against the

+[reference-docs](https://github.com/kubernetes-sigs/reference-docs/) project.

+-->

+<!--



译文被注释了，删除36行和41行的 html 注释标签

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-03-08 07:57 UTC, howieyuen commented
> 您好，这一段在英文文档里，原本就是注释的 在 2022-03-07 15:42:35，"Hao Yuan" ***@***.***> 写道： @howieyuen requested changes on this pull request. In content/zh/docs/reference/kubernetes-api/common-definitions/node-selector-requirement.md:
> +weight: 5
> +auto_generated: true +--- +--> + +<!-- +The file is auto-generated from the Go source code of the component using a generic +[generator](https://github.com/kubernetes-sigs/reference-docs/). To learn how +to generate the reference documentation, please read +[Contributing to the reference documentation](/docs/contribute/generate-ref-docs/). +To update the reference content, please follow the +[Contributing upstream](/docs/contribute/generate-ref-docs/contribute-upstream/) +guide. You can file document formatting bugs against the +[reference-docs](https://github.com/kubernetes-sigs/reference-docs/) project. +--> +<!-- 译文被注释了，删除36行和41行的 html 注释标签 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

抱歉，我看到译文，想当然地认为了。那就把这段原文和译文都删掉，顺便把这些个commit合并，谢谢

2022-03-24 00:44 UTC, tengqm commented
/lgtm
/label tide/merge-method-squash

2022-03-24 00:45 UTC, tengqm commented
/approve

2022-03-24 00:46 UTC, merged