[zh] Rework securing cluster page
kubernetes/website pull request #32161
Opened 2022-03-10 05:00 UTC by tengqm

This page was translated poorly. Many texts were not properly translated.

2022-03-10 09:36 UTC, mengjiao-liu commented on content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
> +你要始终使用经过良好审查的备份和加密方案来加密备份数据，
“良好审查” 改成“充分审查” 或者“仔细审查” 会不会好一点？

2022-03-10 10:38 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
> +你要始终使用经过良好审查的备份和加密方案来加密备份数据，
done

2022-03-10 10:58 UTC, mengjiao-liu commented
/lgtm

2022-03-23 03:16 UTC, howieyuen requested changes

2022-03-23 03:16 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
> +这些权限将动作（get、create、delete）和资源（pod、service、node）进行组合，并可在名字空间或者集群范围生效。
```suggestion
这些权限将动作（get、create、delete）和资源（Pod、Service、Node）进行组合，并可在名字空间或者集群范围生效。
```

2022-03-23 03:16 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
> +但也可以控制每个名字空间中存在多少个 Pod、服务或卷。
```suggestion
但也可以控制每个名字空间中存在多少个 Pod、Service 或 Volume。
```

2022-03-23 03:16 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
> +一般来说，大多数应用程序需要对主机资源的有限制的访问，这样它们可以在不访问主机信息的情况下
```suggestion
一般来说，大多数应用程序需要对主机资源的有限制的访问，
```

2022-03-23 03:16 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/securing-a-cluster.md
> +成功地以 root 账号（UID 0）运行。
```suggestion
这样它们可以在不访问主机信息的情况下，成功地以 root 账号（UID 0）运行。
```

2022-03-23 03:29 UTC, tengqm commented
@howieyuen All feedbacks taken. Please take another look.

2022-03-23 03:31 UTC, howieyuen commented
/approve

2022-03-25 06:57 UTC, howieyuen commented
/lgtm

2022-03-25 07:03 UTC, merged