[zh] Resync node local DNS page
kubernetes/website pull request #32188
Opened 2022-03-11 03:03 UTC by tengqm

2022-03-11 03:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +在当今的体系结构中，运行在 ClusterFirst DNS 模式的 Pod 可以连接到 kube-dns `serviceIP` 进行 DNS 查询。
```suggestion
在当今的体系结构中，运行在 ClusterFirst DNS 模式下的 Pod 可以连接到 kube-dns `serviceIP` 进行 DNS 查询。
```

2022-03-11 03:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +由于他们并不监视 Kubernetes 对象变化，集群规模或者 Service/Endpoints
```suggestion
由于它们并不监视 Kubernetes 对象变化，集群规模或者 Service/Endpoints
```

2022-03-11 03:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +的数量都不会直接影响内存用量。内存用量会收到 DNS 查询模式的影响。
```suggestion
的数量都不会直接影响内存用量。内存用量会受到 DNS 查询模式的影响。
```

2022-03-11 03:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +（因为系统资源总量的原因，或者所配置的[资源约束](/zh/docs/concepts/configuration/manage-resources-containers/)），
```suggestion
（由于系统资源总量，或者由于所配置的[资源约束](/zh/docs/concepts/configuration/manage-resources-containers/)），
```

2022-03-11 03:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +你也可以安装并使用一个运行在“Recommender Mode（建议者模式）”的
```suggestion
你也可以安装并使用一个运行在 “Recommender Mode（建议者模式）”的
```

2022-03-11 10:27 UTC, mengjiao-liu commented
/lgtm

2022-03-23 03:05 UTC, howieyuen requested changes
found a nit

2022-03-23 03:05 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +由于它们并不监视 Kubernetes 对象变化，集群规模或者 Service/Endpoints
```suggestion
由于它们并不监视 Kubernetes 对象变化，集群规模或者 Service/Endpoint
```

2022-03-23 03:24 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +由于它们并不监视 Kubernetes 对象变化，集群规模或者 Service/Endpoints
Endpoints 是一个资源类型的名称，Endpoint 不是。这是一个奇怪的决定，使用了复数。

2022-03-23 03:30 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/nodelocaldns.md
> +由于它们并不监视 Kubernetes 对象变化，集群规模或者 Service/Endpoints
omg...that's wired, 我查了API，果然是这样。。而且自从endpointslice出来后，endpoints就退居二线了

2022-03-23 03:30 UTC, howieyuen commented
/approve

2022-03-23 03:31 UTC, merged