[zh] Tweak translation of CCM development page
kubernetes/website pull request #32219
Opened 2022-03-12 06:02 UTC by tengqm

The glossary shortcode is annoying. Sometimes it generates weird
sentence structures for Chinese.

2022-03-12 06:42 UTC, howieyuen requested changes

2022-03-12 06:42 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
> +对于树内（In-Tree）驱动，你可以将树内云控制器管理器作为群集中的
```suggestion
对于树内（In-Tree）驱动，你可以将树内云控制器管理器作为集群中的
```

2022-03-12 08:24 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
> +对于树内（In-Tree）驱动，你可以将树内云控制器管理器作为群集中的
oops

2022-03-12 09:45 UTC, howieyuen commented
/approve

2022-03-16 12:19 UTC, ydFu commented
/assign

2022-03-17 06:27 UTC, ydFu reviewed
Remarks for proper nouns should be the same remarks in an article.

2022-03-17 06:27 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
> +对于树内（In-Tree）驱动，你可以将树内云控制器管理器作为集群中的
```suggestion
对于树内（In-Tree）驱动，你可以将树内（In-Tree）云控制器管理器作为集群中的
```

2022-03-17 06:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
> +对于树内（In-Tree）驱动，你可以将树内云控制器管理器作为集群中的
对于这类情况，第一次给出英文就好了，没有必要反复重复。

2022-03-17 06:44 UTC, ydFu commented on content/zh/docs/tasks/administer-cluster/developing-cloud-controller-manager.md
> +对于树内（In-Tree）驱动，你可以将树内云控制器管理器作为集群中的
I see. I'll keep an eye out for this next time I make a code review.

2022-03-17 06:48 UTC, ydFu commented
/lgtm
LGTM,thank you for guiding me on the code view details for localization.

2022-03-17 06:49 UTC, merged