[zh] Resync configure service account
kubernetes/website pull request #32233
Opened 2022-03-13 00:24 UTC by tengqm

2022-03-31 10:46 UTC, mengjiao-liu commented
/lgtm

/assign  @howieyuen

2022-03-31 10:47 UTC, mengjiao-liu commented
/assign  @howieyuen

2022-03-31 10:49 UTC, mengjiao-liu commented
/assign  @howieyuen

2022-03-31 12:31 UTC, howieyuen requested changes

2022-03-31 12:31 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-service-account.md
> +  集群版本必须是 v1.22 或更新，才能多次指定 `--service-account-issuer`。
“更高”会不会更好一点？“更新”乍一看像update

2022-03-31 12:33 UTC, tengqm commented on content/zh/docs/tasks/configure-pod-container/configure-service-account.md
> +  集群版本必须是 v1.22 或更新，才能多次指定 `--service-account-issuer`。
同意

2022-04-01 03:32 UTC, howieyuen commented
/approve

2022-04-01 03:45 UTC, mengjiao-liu commented
/lgtm

2022-04-01 03:46 UTC, merged