[zh] Resync configure probes
kubernetes/website pull request #32234
Opened 2022-03-13 02:50 UTC by tengqm

2022-03-13 06:17 UTC, jihoon-seo commented
[Netlify build fails](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/622d5be7bdc865000830bd58#L77).
> content/zh/examples/pods/probe/grpc-liveness.yaml: no such file or directory

@tengqm PTAL!

2022-03-31 10:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +15 秒钟之后，查看 Pod 时间确认活跃性检查并未失败：
```suggestion
15 秒钟之后，查看 Pod 事件以确认活跃性检查并未失败：
```

2022-03-31 10:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +来实现，如博客[Health checking gRPC servers on Kubernetes（对 Kubernetes 上的 gRPC 服务器执行健康检查）](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)所描述。
```suggestion
来实现，如博客 [Health checking gRPC servers on Kubernetes（对 Kubernetes 上的 gRPC 服务器执行健康检查）](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)所描述。
```

2022-03-31 10:37 UTC, mengjiao-liu commented on content/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +两者都用可以确保流量不会发给还未就绪的容器，当这些探测失败时容器会被重新启动。
```suggestion
两者都可以确保流量不会发给还未就绪的容器，当这些探测失败时容器会被重新启动。
```

2022-03-31 10:58 UTC, mengjiao-liu commented
/lgtm

2022-03-31 12:53 UTC, howieyuen requested changes

2022-03-31 12:53 UTC, howieyuen commented on content/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +如果要在执行活跃性探测器之前等待，应该使用 `initialDelaySeconds` 或 `startupProbe`。
```suggestion
如果要在执行活跃探测器之前等待，应该使用 `initialDelaySeconds` 或 `startupProbe`。
```

2022-04-09 07:03 UTC, howieyuen commented
/approve
/lgtm

2022-04-09 07:06 UTC, merged