Fix nits in the change runtime containerd page
kubernetes/website pull request #32259
Opened 2022-03-14 12:40 UTC by tengqm

There are two commits in the PR. The first one fixes a link. The second one applies some line wrapping changes and fixes some trivial nits.

2022-03-17 16:07 UTC, reylejano commented on content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
> +is applicable for cluster operators running Kubernetes 1.23 or earlier. Also  this covers an
nit: extra space
```suggestion
is applicable for cluster operators running Kubernetes 1.23 or earlier. Also this covers an
```

2022-03-17 16:08 UTC, reylejano commented
/lgtm

2022-03-23 14:08 UTC, divya-mohan0209 requested changes
I've reworded the initial paragraph so that the trail of though isn't lost midway. Open to suggestions if we can phrase it better though.

2022-03-23 14:08 UTC, divya-mohan0209 commented on content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
> +is applicable for cluster operators running Kubernetes 1.23 or earlier. Also  this covers an
```suggestion
is applicable for cluster operators running Kubernetes 1.23 or earlier. Also, an
```

2022-03-23 14:08 UTC, divya-mohan0209 commented on content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
> +example scenario for migrating from dockershim to containerd and alternative container runtimes
```suggestion
example scenario covering the migration from dockershim to containerd and alternative container runtimes
```

2022-03-23 14:08 UTC, divya-mohan0209 commented on content/en/docs/tasks/administer-cluster/migrating-from-dockershim/change-runtime-containerd.md
> +can be picked from this [page](/docs/setup/production-environment/container-runtimes/).
```suggestion
can be viewed [here](/docs/setup/production-environment/container-runtimes/).
```

2022-04-07 08:39 UTC, sftim commented
@divya-mohan0209 would you be happy to see these changes merge as-is? We could open a good-first-issue follow up that describes the extra tidying.

2022-04-07 08:52 UTC, divya-mohan0209 commented
@sftim : Absolutely! Not a problem at all :)

2022-04-07 09:02 UTC, sftim commented
/approve

2022-04-07 09:03 UTC, merged