csi: add nodeExpandSecret KEP details
kubernetes/website pull request #32298
Opened 2022-03-16 13:24 UTC by humblec

Signed-off-by: Humble Chirammal <hchiramm@redhat.com>

Ref # 

KEP: https://github.com/kubernetes/enhancements/pull/3173/
Implementation: https://github.com/kubernetes/kubernetes/pull/105963
Blog: https://github.com/kubernetes/website/pull/32450

2022-03-16 18:04 UTC, Arhell reviewed
/assign @sftim

2022-03-17 00:49 UTC, tengqm commented
/retitle [WIP] csi: add nodeExpandSecret KEP details

2022-03-19 13:42 UTC, mehabhalodiya commented
enhancement ref: https://github.com/kubernetes/enhancements/issues/3107

2022-03-19 13:43 UTC, mehabhalodiya commented
/assign @didicodes

2022-04-13 13:01 UTC, sftim reviewed
Ideally, the text that's introduced with:

> The following fields are available to storage administrators to configure a CSI persistent volume:

would move into the reference section. However, we can refactor that after the release. 

---

Here's some suggested wording.

2022-04-17 16:23 UTC, divya-mohan0209 requested changes

2022-04-17 16:23 UTC, divya-mohan0209 commented on content/en/docs/concepts/storage/volumes.md
> +  secret is required. If the secret object contains more than one secret, all
```suggestion
  secret is required. If the object contains more than one secret, all
```

2022-04-27 12:21 UTC, mehabhalodiya commented
The v1.24 milestone no longer tracks the KEP that this PR supports. Thanks for your effort on this documentation; I recommend saving this work for a future release.

/close

If you feel that this PR has been closed in error, please feel free to reopen it against another branch.
Thank you!

2022-04-27 12:21 UTC, closed without merging

2022-04-27 22:19 UTC, nate-double-u commented
/milestone clear