[es] Add content/es/docs/concepts/storage/storage-limits.md
kubernetes/website pull request #32383
Opened 2022-03-21 01:35 UTC by edithturn

[es] Add content/es/docs/concepts/storage/storage-limits.md in Spanish

2022-03-23 18:54 UTC, electrocucaracha requested changes

2022-03-23 18:54 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-limits.md
> +Los proveedores de la nube como Google, Amazon y Microsoft suelen tener un límite en la cantidad de Volúmenes que se pueden adjuntar a un Nodo. Es importante que Kubernetes respete esos límites. De l
```suggestion
Los proveedores de la nube como Google, Amazon y Microsoft suelen tener un límite en la cantidad de Volúmenes que se pueden adjuntar a un Nodo. Es importante que Kubernetes respete esos límites. De lo contrario, los Pods planificados en un Nodo podrían quedarse atascados esperando que los Volúmenes se conecten.
```

2022-03-23 18:54 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-limits.md
> +Consulte las especificaciones de [CSI specifications](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetinfo) para obtener más información.
```suggestion
Consulte las [especificaciones de CSI](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodegetinfo) para obtener más información.
```

2022-03-26 22:47 UTC, edithturn commented on content/es/docs/concepts/storage/storage-limits.md
> +- electrocucaracha
@electrocucaracha, estuve revisando otros PR, y no tienen esta parte a exception de una que yo misma envié: https://github.com/kubernetes/website/pull/29624/files

2022-03-26 22:48 UTC, edithturn commented
@electrocucaracha gracias por tu revision! 🐬 🚀

2022-03-26 23:59 UTC, electrocucaracha commented
/lgtm

/cc @raelga

2022-03-29 15:44 UTC, anyulled approved these changes

2022-03-29 16:52 UTC, electrocucaracha commented
/approve

2022-03-29 16:54 UTC, merged

2022-03-30 01:33 UTC, edithturn commented
@electrocucaracha @anyulled  thank you! 😃