[en] Modify short_description about namespace
kubernetes/website pull request #32416
Opened 2022-03-22 14:22 UTC by my-git9

I think short_description should be modified synchronously with the text.

2022-03-22 14:23 UTC, my-git9 commented
/retitle [en] Modify short_description about namespace

2022-03-22 15:30 UTC, sftim requested changes

2022-03-22 15:30 UTC, sftim commented on content/en/docs/reference/glossary/namespace.md
> +  An abstraction used by Kubernetes to support isolation of groups of resources within a single {{< glossary_tooltip text="cluster" term_id="cluster" >}}.
We don't use shortcodes inside glossary entry short descriptions. Can you rewrite this with just the plain word “cluster”?

2022-03-23 03:14 UTC, tengqm commented
yup. "virtual cluster" has become a thing these days, we'd better not use it.
/lgtm

2022-03-23 07:52 UTC, divya-mohan0209 approved these changes
/lgtm
/approve

2022-03-23 07:54 UTC, merged