adding pt-br translate for flow-control page
kubernetes/website pull request #32460
Opened 2022-03-24 01:54 UTC by ThiagoGMF

# Changes

- Brazilian portuguese translation for the [Flow Control](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/). page

2022-03-26 08:02 UTC, Arhell reviewed
/assign @edsoncelio

2022-03-27 12:49 UTC, edsoncelio requested changes
Hi, Thanks for your PR! I left a few suggestions below, feel free to ask on slack channel If you need any help :)

2022-03-27 12:49 UTC, edsoncelio commented on content/pt-br/docs/concepts/cluster-administration/flow-control.md
> +O recurso de prioridade e imparcialidade da API (APF) é uma alternativa que melhora
```suggestion
O recurso de prioridade e imparcialidade da API ( do inglês *API Priority and Fairness*, APF) é uma alternativa que melhora
```

2022-03-27 12:49 UTC, edsoncelio commented on content/pt-br/docs/concepts/cluster-administration/flow-control.md
> +Solicitações classificadas como "de longa duração" — principalmente relógios — não são
`principalmente relógios` I did get this sentence, what do we mean by `relógios?`

2022-03-27 12:49 UTC, edsoncelio commented on content/pt-br/docs/concepts/cluster-administration/flow-control.md
> +O recurso de prioridade e imparcialidade da API é controlado por um portão de recurso
In other cases we aren't translating `feature gate`

2022-03-27 12:49 UTC, edsoncelio commented on content/pt-br/docs/concepts/cluster-administration/flow-control.md
> +comportamento de guarda-corpo. Este é o comportamento que os servidores tinham antes
What do you mean by `guarda-corpo`?

2022-03-27 12:49 UTC, edsoncelio commented on content/pt-br/docs/concepts/cluster-administration/flow-control.md
> +A configuração sugerida não dá nenhum tratamento especial à saúde
This sentence can be improved, like `tratamento especial a checagem de saúde das requisições...`

2022-05-01 13:27 UTC, edsoncelio commented
@devlware PTAL :)
To me it's lgtm

2022-08-03 02:26 UTC, Sea-n commented
This PR has no problem, just lack of reviewers.
/remove-lifecycle stale

Could you help this PR move forward? Thanks.
/cc @devlware

2022-08-11 02:09 UTC, edsoncelio commented
> This PR has no problem, just lack of reviewers. /remove-lifecycle stale
> 
> Could you help this PR move forward? Thanks. /cc @devlware

Thanks @Sea-n, I reviewed this a few months ago, I'll check it again and ask for help to another reviewer :)

2022-08-26 13:10 UTC, devlware commented
/lgtm

2022-08-26 13:11 UTC, devlware commented
/approve

2022-08-26 13:12 UTC, merged