Improvement to the kubectl doc.
kubernetes/website pull request #32569
Opened 2022-03-28 03:46 UTC by Anilkumar56

Improvement to the kubectl doc.
fixes https://github.com/kubernetes/website/issues/32424

2022-03-29 04:19 UTC, RA489 commented
/easycla

2022-03-30 07:45 UTC, RA489 commented
/easycla

2022-03-30 07:48 UTC, RA489 commented
/easycla

2022-03-30 07:49 UTC, RA489 commented
/check-cla

2022-03-30 07:54 UTC, RA489 commented
/easycla

2022-03-30 07:55 UTC, RA489 commented
/check-cla

2022-03-31 05:35 UTC, Arhell reviewed
Please sign CLA
More info
https://github.com/kubernetes/community/blob/master/CLA.md

2022-04-01 03:38 UTC, RA489 commented
/check-cla
/easycla

2022-04-04 01:44 UTC, RA489 commented
/easycla

2022-04-04 03:55 UTC, RA489 commented
/easycla
/check-cla

2022-04-04 04:08 UTC, Anilkumar56 commented
I signed it

2022-04-04 04:15 UTC, Anilkumar56 commented
"I signed it"

2022-04-04 04:16 UTC, RA489 commented
/easycla
/check-cla

2022-04-04 04:23 UTC, RA489 commented
/easycla

2022-04-06 03:39 UTC, RA489 commented
/check-cla
/easycla

2022-04-06 06:09 UTC, divya-mohan0209 commented
@Anilkumar56 please sign the CLA appropriately for us to review the PR further.

2022-04-12 12:13 UTC, RA489 commented
/check-cla
/easycla

2022-04-12 14:43 UTC, RA489 commented
/easycla

2022-04-13 08:44 UTC, Anilkumar56 commented
/check-cla

2022-04-13 10:45 UTC, RA489 commented
/easycla

2022-04-13 10:54 UTC, Anilkumar56 commented
@mrbobbytables I have signed the EasyCLA as corporate employee but still its not passing on my PR. The github email with which i contributed matches the email i signed the CLA. Can you please take a look?

2022-04-13 11:07 UTC, divya-mohan0209 commented
Hey @Anilkumar56 , when you're pushing your PR have you set the username and user email as the ones that you have used to sign the CLA?

Please refer to [this](https://git-scm.com/docs/git-commit) link to configure them as variables for your environment before pushing the commit.

2022-04-13 11:26 UTC, Anilkumar56 commented
@divya-mohan0209  Yes, i have set the username and user email as the ones that i have used to sign the CLA.
still i am facing the EasyCLA  Failure.

2022-04-13 11:43 UTC, RA489 commented
/easycla

2022-04-13 11:52 UTC, mrbobbytables commented
/easycla

2022-04-15 02:28 UTC, gmannos commented
We are checking at our organization side if any step is missed during the CCLA signing. Please hold until then.

2022-04-21 05:01 UTC, RA489 commented
/easycla

2022-04-21 05:02 UTC, RA489 commented
/check-cla

2022-06-14 04:46 UTC, zacharysarah requested changes
@anilkumar56 With the CLA signed, it's possible to review the PR itself.

To other reviewers: I'm genuinely not sure whether we should approve this PR. If other reviewers think we should approve it, then I'm open to the idea, with some changes.

@anilkumar56 I'm willing to bet you opened this PR because this is an undocumented requirement that you encountered, and I want to honor that experience. I'm willing to bet that other people encounter the same difficulty. 

That said--and it's rare for me to say this--this information may be overly specific at the level of a Kubernetes installation. What do other docs reviewers think?

2022-06-14 04:46 UTC, zacharysarah commented on content/en/docs/tasks/tools/install-kubectl-linux.md
> +`curl` tool is a prerequisites for installing kubectl binary with curl on Linux method.
```suggestion
If your Linux distribution doesn't have `curl` installed, you'll need to install `curl` before you can install the kubectl binary. For example:
    ```sh
    apt update
    apt-get install curl
    ```
```

2022-06-14 08:27 UTC, sftim commented
I'm happy to list `curl` as an explicit prerequisite, but not tell the reader  specificallyhow to get `curl` installed. That way, they can use a search engine such as Google and search “How do I install curl on MyOperatingSystem” - and should find a clear answer.

The PR as is stands doesn't follow our website conventions for listing prerequisites. These should come before the text.

In the case of `curl`, we should make it clear that you need that tool only for a manual download, and that there are alternative tools that are equally valid. No need to _name_ any alternatives; again, Google searches for “alternative to curl tool” are likely to help if necessary.

2022-06-14 09:30 UTC, tengqm commented
I'm a little bit concerned at naming 'curl' a prerequisite. You use, for example, 'wget' instead.

2022-06-14 09:56 UTC, sftim commented
Some similar advice about prerequisites:
- https://kubernetes.io/docs/tasks/administer-cluster/verify-signed-images/#before-you-begin

The kubectl equivalent page states (semi-rendered):
>    Or if you have `curl` installed, use this command:
>   ```powershell
>    curl -LO "https://dl.k8s.io/release/{{< param "fullversion" >}}/bin/windows/amd64/kubectl.exe"
>   ```

We could either that kind of wording.

2022-06-14 16:34 UTC, shannonxtreme commented
> I'm a little bit concerned at naming 'curl' a prerequisite. You use, for example, 'wget' instead.

Maybe something like:

"Ensure that you have a network data transfer tool like `curl` installed"

2022-06-14 17:28 UTC, sftim commented
> Ensure that you have a network data transfer tool like `curl` installed

Sort of, but if someone has `wget` installed then we also need to explain, especially for more novice users, to remember to adapt the instructions accordingly. Especially if our aims here include cutting down on the number of docs issues filed by folks whose only contact with the Kubernetes docs so far has been to find the page about setting up `kubectl` - that audience may well not have the level of tech familiarity that other pages can usually assume.

2022-06-14 17:50 UTC, sftim commented
/retitle Mention that downloading kubectl may need curl

2022-06-23 23:12 UTC, reylejano commented
@anilkumar56 , what do you think of @zacharysarah [suggestion](https://github.com/kubernetes/website/pull/32569#discussion_r896364836)?

2022-07-04 05:57 UTC, divya-mohan0209 commented
@anilkumar56 : Please advise if you'd be able to continue with this PR?

2022-07-27 08:42 UTC, divya-mohan0209 commented
@anilkumar56 I'll be closing off this PR for now due to no response from your side since April. Please feel free to reopen this whenever you are ready to address the comments & work upon it.
/close

2022-07-27 08:42 UTC, closed without merging