[zh] Resync pages under overview
kubernetes/website pull request #32636
Opened 2022-03-30 06:27 UTC by tengqm

2022-04-03 02:28 UTC, tanjunchen commented on content/zh/docs/concepts/overview/kubernetes-api.md
> +请参与下表了解可接受的请求头部。
参与？

2022-04-05 11:30 UTC, howieyuen requested changes

2022-04-05 12:37 UTC, tengqm commented on content/zh/docs/concepts/overview/kubernetes-api.md
> +- 阅读 [API changes](https://git.k8s.io/community/contributors/devel/sig-architecture/api_changes.md#readme)
目标页面是一个英文页面，有意不翻译的。

2022-04-06 06:57 UTC, howieyuen commented
/approve

2022-04-07 05:59 UTC, tanjunchen reviewed
/lgtm

2022-04-07 05:59 UTC, merged