[zh] Resync flow-control page
kubernetes/website pull request #32639
Opened 2022-03-30 07:31 UTC by tengqm

2022-04-03 02:37 UTC, tanjunchen commented on content/zh/docs/concepts/cluster-administration/flow-control.md
> +这类控制器使用通知机构（Informers）获得信息并对 API 请求的失效作出反应，
通知机构？机制？

2022-04-03 08:11 UTC, tengqm commented on content/zh/docs/concepts/cluster-administration/flow-control.md
> +这类控制器使用通知机构（Informers）获得信息并对 API 请求的失效作出反应，
有意这样翻译的。如果觉得机制更容易接受，也可以。翻译成机构是为了突出其名词属性和实体属性。

2022-04-05 11:26 UTC, howieyuen requested changes

2022-04-05 11:26 UTC, howieyuen commented on content/zh/docs/concepts/cluster-administration/flow-control.md
> +  而应适当地创建自己的 `catch-all` FlowSchema 和 PriorityLevelConfigurations
```suggestion
  而应适当地创建自己的 `catch-all` FlowSchema 和 PriorityLevelConfiguration
```

2022-04-05 11:26 UTC, howieyuen commented on content/zh/docs/concepts/cluster-administration/flow-control.md
> +* `system` 优先级用于 `system:nodes` 组（即 kubelets）的与健康状态更新无关的请求；
建议使用 kubelet 单数形式，表示一类对象，下同

2022-04-05 11:26 UTC, howieyuen commented on content/zh/docs/concepts/cluster-administration/flow-control.md
> +* `workload-low` 优先级用于来自所有其他服务帐户的请求，通常包括来自 Pods
```suggestion
* `workload-low` 优先级用于来自所有其他服务帐户的请求，通常包括来自 Pod
```

2022-04-06 06:57 UTC, howieyuen commented
/approve

2022-04-07 05:59 UTC, tanjunchen reviewed
/lgtm

2022-04-07 06:01 UTC, merged