[zh] Fix cassandra tutorial translation
kubernetes/website pull request #32703
Opened 2022-04-01 13:15 UTC by tengqm

closes: #32702

2022-04-02 08:09 UTC, zaunist commented on content/zh/docs/tutorials/stateful-application/cassandra.md
> +使用"StatefulSets"可以更轻松地将有状态的应用程序部署到你的 Kubernetes 集群中。
```suggestion
使用 `StatefulSets` 可以更轻松地将有状态的应用程序部署到你的 Kubernetes 集群中。
```
如果要修改原本使用的斜体，我认为这样可能更好一点，您觉得呢？

2022-04-02 09:02 UTC, tengqm commented on content/zh/docs/tutorials/stateful-application/cassandra.md
> +使用"StatefulSets"可以更轻松地将有状态的应用程序部署到你的 Kubernetes 集群中。
关于英文里面要不要使用斜体，我发起过这个讨论。英文维护者的反馈是还是希望用斜体，但是本地化的时候可以自行决定要不要斜体。

斜体汉字太难看了！

2022-04-02 09:32 UTC, zaunist commented on content/zh/docs/tutorials/stateful-application/cassandra.md
> +使用"StatefulSets"可以更轻松地将有状态的应用程序部署到你的 Kubernetes 集群中。
了解

2022-04-05 11:49 UTC, howieyuen commented on content/zh/docs/tutorials/stateful-application/cassandra.md
> +使用"StatefulSets"可以更轻松地将有状态的应用程序部署到你的 Kubernetes 集群中。
> 关于英文里面要不要使用斜体，我发起过这个讨论。英文维护者的反馈是还是希望用斜体，但是本地化的时候可以自行决定要不要斜体。
> 
> 斜体汉字太难看了！

有关英文斜体格式，我发现了这个：[英语斜体在学术出版中的主要使用范围](http://www.xueshutang.com/yingyu/23620.html)，主要分四种：
- 作品
- 运载工具
- 外来语
- 强调

我认为， 作品一般是用书名号；强调是用粗体；’其他的属于引用类，一般用双引号表示。
这部分可否沉淀下来，补充到中文翻译样式指南里。

2022-04-05 11:52 UTC, howieyuen requested changes

2022-04-05 11:52 UTC, howieyuen commented on content/zh/docs/tutorials/stateful-application/cassandra.md
> +数据库 Cassandra 需要永久性存储提供数据持久性（应用"状态"）。
```suggestion
数据库 Cassandra 需要永久性存储提供数据持久性（应用“状态”）。
```

2022-04-05 11:52 UTC, howieyuen commented
/approve cancel

2022-04-05 12:35 UTC, tengqm commented on content/zh/docs/tutorials/stateful-application/cassandra.md
> +使用"StatefulSets"可以更轻松地将有状态的应用程序部署到你的 Kubernetes 集群中。
好的。英文里面引号、斜体、粗体使用非常不规范，我们可以在译文中改进。

2022-04-06 01:23 UTC, zaunist commented on content/zh/docs/tutorials/stateful-application/cassandra.md
> +使用"StatefulSets"可以更轻松地将有状态的应用程序部署到你的 Kubernetes 集群中。
> > 关于英文里面要不要使用斜体，我发起过这个讨论。英文维护者的反馈是还是希望用斜体，但是本地化的时候可以自行决定要不要斜体。
> > 斜体汉字太难看了！
> 
> 有关英文斜体格式，我发现了这个：[英语斜体在学术出版中的主要使用范围](http://www.xueshutang.com/yingyu/23620.html)，主要分四种：
> 
> * 作品
> * 运载工具
> * 外来语
> * 强调
> 
> 我认为， 作品一般是用书名号；强调是用粗体；其他的属于引用类，一般用双引号表示。 这部分可否沉淀下来，补充到中文翻译样式指南里。

Nice job.

2022-04-06 06:58 UTC, howieyuen commented
/approve

2022-04-09 04:54 UTC, tanjunchen reviewed
/lgtm

2022-04-09 04:56 UTC, merged