Update volumes.md
kubernetes/website pull request #32777
Opened 2022-04-06 16:36 UTC by lparis

Updating the link for the Kubernetes vSphere Cloud Provider and adding a more info link to the vSphere CSI documentation.

2022-04-07 04:03 UTC, divya-mohan0209 requested changes
Slight rephrasing

2022-04-07 04:03 UTC, divya-mohan0209 commented on content/en/docs/concepts/storage/volumes.md
> +The following documentation assumes that the [Kubernetes vSphere Cloud Provider](https://github.com/kubernetes/cloud-provider-vsphere) is configured. See also the [VMware vSphere Container Storage Pl
```suggestion
The following documentation assumes that the [Kubernetes vSphere Cloud Provider](https://github.com/kubernetes/cloud-provider-vsphere) is configured. You may also refer the [VMware vSphere Container Storage Plug-in Documentation](https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/index.html).
```

2022-04-22 05:06 UTC, divya-mohan0209 commented
@lparis : Would you please be able to make the requested changes?

2022-04-22 05:06 UTC, divya-mohan0209 commented
@lparis : Would you please be able to make the requested changes?

2022-04-28 06:46 UTC, Kartik494 commented
/sig storage

2022-05-30 12:05 UTC, Kartik494 commented
@lparis Could you please addressed the requested change and rebase occurring for continuing this.
Thanks

2022-06-14 05:04 UTC, zacharysarah commented
@lparis 👋🏻 Please feel free to `/reopen` when you're ready to rebase and respond to feedback.

/close

2022-06-14 05:04 UTC, closed without merging