[zh] Translate kubernetes-api/workload-resources/cron-job-v1 into Chinese
kubernetes/website pull request #32776
Opened 2022-04-06 09:55 UTC by twilight0620

Fixes: https://github.com/kubernetes/website/issues/32773

Do not have chinese docs: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/cron-job-v1/

so need to translate kubernetes-api/workload-resources/cron-job-v1.md into Chinese

2022-04-06 23:03 UTC, sftim requested changes

2022-04-06 23:03 UTC, sftim commented on content/zh/docs/reference/kubernetes-api/workload-resources/_index.md
> +auto_generated: true
Hi.
Localized docs should not be marked as automatically generated.

2022-04-06 23:03 UTC, sftim commented on content/zh/docs/reference/kubernetes-api/workload-resources/cron-job-v1.md
> +auto_generated: true
Localized docs should not be marked as automatically generated.

2022-04-07 02:19 UTC, twilight0620 commented
I need to change the refer link.
/close

2022-04-07 02:19 UTC, closed without merging