GracefulNodeShutdownBasedOnPodPriority is Beta in 1.24
kubernetes/website pull request #32831
Opened 2022-04-09 03:40 UTC by tengqm

Upstream: kubernetes/kubernetes#107986
KEP: https://github.com/kubernetes/enhancements/pull/3194

2022-04-10 22:02 UTC, sftim reviewed
This isn't _wrong_; however, I imagine that a change to https://kubernetes.io/docs/concepts/architecture/nodes/ is also appropriate?

2022-04-10 22:03 UTC, sftim commented
This is a fixup to https://github.com/kubernetes/website/pull/32771

2022-04-11 15:49 UTC, sftim requested changes
Thanks.

I spotted a factual error about which Kubernetes release introduced `GracefulNodeShutdownBasedOnPodPriority`; I also suggested new wording.

2022-04-11 15:49 UTC, sftim commented on content/en/docs/concepts/architecture/nodes.md
> +In v1.24, the feature has been promoted to Beta stage and enabled by default.
```suggestion
The ability to take Pod priority into account during graceful node shutdown was introduced
as an alpha feature in Kubernetes v1.23; in Kubernetes {{< skew currentVersion >}}
that feature is beta and is enabled by default.
```

2022-04-13 14:04 UTC, reylejano commented
A few non-blocking nits
/approve

2022-04-13 16:19 UTC, sftim approved these changes
/lgtm

![Ship it!](https://user-images.githubusercontent.com/22591623/163225521-6b822fbb-34f8-4afe-b226-b2a94526b0f4.png)

2022-04-13 16:19 UTC, sftim commented on content/en/docs/concepts/architecture/nodes.md
> +, and setting `ShutdownGracePeriodByPodPriority` in the
nit: the comma should follow the hyperlink with no preceding whitespace

2022-04-13 16:20 UTC, merged