[bn] Localize `content/bn/docs/tasks/tools/_index.md`
kubernetes/website pull request #32885
Opened 2022-04-12 18:47 UTC by Imtiaz1234

Signed-off-by: Saber Imtiaz  saberimtiazmitul@gmail.com
Localizes `content/bn/docs/tasks/tools/_index.md` to Bengali
This is an intial PR as may need some improvements!
Tracking issue: #31677

2022-04-12 19:45 UTC, mitul3737 requested changes
কুবারনেটিস

2022-04-12 19:45 UTC, mitul3737 commented on content/bn/docs/tasks/tools/_index.md
> +description: আপনার কম্পিউটারে Kubernetes টুল সেট আপ করুন।
Need to have কুবারনেটিস here

2022-04-12 19:47 UTC, mitul3737 approved these changes
LGTM

2022-04-13 01:38 UTC, jihoon-seo commented
/label tide/merge-method-squash

2022-05-08 00:04 UTC, mitul3737 commented
/lgtm

2022-05-08 00:05 UTC, merged

2023-02-25 17:40 UTC, noor-e-jannatnafia commented
Signed-off-by: Noor E Jannat Nafia noorejannatnafia.006@gmail.com
Localizes content/bn/docs/tasks/tools/included/verify-kubectl.md to Bengali
This is an initial PR as may need some improvements!
Tracking isse: 31677