Update address references for kube-scheduler Configuration
kubernetes/website pull request #32951
Opened 2022-04-15 09:00 UTC by HirazawaUi

Update address references for kube-scheduler Configuration, old address references are not accessible

2022-04-15 10:08 UTC, tengqm commented
/hold

谢谢贡献。根据[指南](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87)约定，我们会拒绝对页面的**部分**修改。部分修改针对的是对应页面的英文上游还有其他改动需要同步的情况。
一旦我们合并了此 PR，将来就无法根据文件的最后更改时间来判断是否有其他上游变更尚未同步。请理解。

请在 **main** 分支上执行以下命令查看上游尚未同步的更改：

```shell
./scripts/lsync.sh content/zh/docs/reference/scheduling/config.md
```

2022-04-16 07:58 UTC, HirazawaUi commented
> /hold
> 
> 谢谢贡献。根据[指南](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87)约定，我们会拒绝对页面的**部分**修改。部分修改针对的是对应页面的英文上游还有其他改动需要同步的情况。 一旦我们合并了此 PR，将来就无法根据文件的最后更改时间来判断是否有其他上游变更尚未同步。请理解。
> 
> 请在 **main** 分支上执行以下命令查看上游尚未同步的更改：
> 
> ```shell
> ./scripts/lsync.sh content/zh/docs/reference/scheduling/config.md
> ```

不好意思，我在提交之前没有看到中文本地化的指南，请问我需要关闭这个PR重新提交新的PR，或者是在此PR的基础上新增commit呢，如果是后者的话针对此次修改可能会有多个commit

2022-04-16 08:42 UTC, tengqm commented
> 不好意思，我在提交之前没有看到中文本地化的指南，请问我需要关闭这个PR重新提交新的PR，或者是在此PR的基础上新增commit呢，如果是后者的话针对此次修改可能会有多个commit

不需要重新提交新的 PR。直接在这个 PR 上改。每次提交之前，用 git commit --amend，之后 git push -f 就好。这样可以确保只有一个 commit.

2022-04-17 04:27 UTC, HirazawaUi commented
> > 不好意思，我在提交之前没有看到中文本地化的指南，请问我需要关闭这个PR重新提交新的PR，或者是在此PR的基础上新增commit呢，如果是后者的话针对此次修改可能会有多个commit
> 
> 不需要重新提交新的 PR。直接在这个 PR 上改。每次提交之前，用 git commit --amend，之后 git push -f 就好。这样可以确保只有一个 commit.

你好，我已经按照中文本地化样式指南同步了英文文档的内容，并且再次提交了文档的更新

2022-04-17 05:05 UTC, howieyuen requested changes
First, Welcome to join kubernetes doc team, we are so excited to see your coming!
I am one common committer in this community, and after reviewing your PR, I left several opinion below, 
and please allow me to make conclusion:
- 中英文、中文数字混合，原则上需要在英文和数字的前后各添加一个空格，除非在句首或句末
- 适当换行，中文本地化始终遵循中英文语义一致性，为了方便review，尽可能保持断句
- 专业名词、代码引用不翻译
Thanks

2022-04-17 05:28 UTC, howieyuen requested changes

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +7. reserve`：这是一个信息扩展点，当资源已经预留给 Pod 时，会通知插件。
```suggestion
7. `reserve`：这是一个信息扩展点，当资源已经预留给 Pod 时，会通知插件。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +11.  `postBind`：这是一个信息扩展点，在 Pod 绑定了节点之后调用。
```suggestion
11. `postBind`：这是一个信息扩展点，在 Pod 绑定了节点之后调用。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +  {{< glossary_tooltip text="StatefulSets" term_id="statefulset" >}} 的Pod
```suggestion
  {{< glossary_tooltip text="StatefulSets" term_id="statefulset" >}} 的 Pod 跨节点分布。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +- `SelectorSpread`：选择跨节点分布属于
```suggestion
- `SelectorSpread`：偏向把属于
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +-`CinderLimits`：检查是否可以满足节点的[OpenStack Cinder](https://docs.openstack.org/cinder/)卷限制
```suggestion
-`CinderLimits`：检查是否可以满足节点的 [OpenStack Cinder](https://docs.openstack.org/cinder/) 卷限制
   扩展点：`filter`。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +  实现的扩展点：`preScore`，`score`。
```suggestion
  扩展点：`preScore`，`score`。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +从 `kubescheduler.config.k8s.io/v1beta3` 开始，配置文件配置中有一个附加字段 `multiPoint`，它允许跨多个扩展点轻松启用或禁用插件。
适当换行，方便 review
```suggestion
从 `kubescheduler.config.k8s.io/v1beta3` 开始，配置文件配置中有一个附加字段 `multiPoint`，
它允许跨多个扩展点轻松启用或禁用插件。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +这相当于为所有扩展点手动启用`MyPlugin`，如下所示：
```suggestion
这相当于为所有扩展点手动启用 `MyPlugin`，如下所示：
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +例如，考虑两个Score插件 `DefaultScore1` 和 `DefaultScore2` ，每个插件的权重为 `1` 。
中英文混合，中文和数字混合，需要前后各添加一个空格，但遇到中文标点时，则不需要
```suggestion
例如，考虑两个 Score 插件 `DefaultScore1` 和 `DefaultScore2`，每个插件的权重为 `1` 。 
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +这些插件的一个有效示例配置是：
```suggestion
这些插件的一个合法示例配置如下：
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +* 在 v1beta2 配置版本中，您可以为 `NodeResourcesFit` 插件使用新的score扩展。
我们习惯翻译成“你”
```suggestion
* 在 v1beta2 配置版本中，你可以为 `NodeResourcesFit` 插件使用新的 score 扩展。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> + 新的扩展结合了 `NodeResourcesLeastAllocated`、`NodeResourcesMostAllocated` 和 `RequestedToCapacityRatio` 插件的功能。
适当换行
```suggestion
 新的扩展结合了 `NodeResourcesLeastAllocated`、`NodeResourcesMostAllocated`
 和 `RequestedToCapacityRatio` 插件的功能。 
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> + 例如，如果您之前使用了 `NodeResourcesMostAllocated` 插件，则可以改用 `NodeResourcesFit`（默认启用）并添加一个 `pluginConfig` 和 `scoreStrategy`，类似于：
- 您->你
- 适当换行
```suggestion
 例如，如果你之前使用了 `NodeResourcesMostAllocated` 插件，
 则可以改用 `NodeResourcesFit`（默认启用）并添加一个 `pluginConfig` 和 `scoreStrategy`，类似于：
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +* 调度器插件`NodeLabel`已弃用；相反，使用[`亲和性与反亲和性`](/zh/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) 插件（默认启用）来实现类似的行为。
这种代码符合引用的术语，我们一般不翻译
```suggestion
* 调度器插件 `NodeLabel` 已弃用；相反，
使用 [`NodeAffinity`](/zh/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
插件（默认启用）来实现类似的行为。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +* 调度程序插件`ServiceAffinity`已弃用相反，使用[`pod间亲和性与反亲和性`](/zh/doc/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity)插件（默认启用）来实现类似的行为。
```suggestion
* 调度程序插件 `ServiceAffinity` 已弃用相反，
使用 [`InterPodAffinity`](/zh/doc/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity)
插件（默认启用）来实现类似的行为。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +* 调度器插件 `NodePreferAvoidPods` 已弃用；相反，使用[节点污点](/zh/docs/concepts/scheduling-eviction/taint-and-toleration/)来实现类似的行为。
```suggestion
* 调度器插件 `NodePreferAvoidPods` 已弃用；
相反，使用[节点污点](/zh/docs/concepts/scheduling-eviction/taint-and-toleration/)来实现类似的行为。
```

2022-04-17 05:28 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +* 为 scheduler healthz 和指标绑定地址配置的 `host` 或 `port` 无效将导致验证失败。
```suggestion
* 调度器的健康检查和审计的绑定地址，所配置的 `host` 或 `port` 无效，将导致验证失败。
```

2022-04-17 08:11 UTC, HirazawaUi commented
@howieyuen 你好，我已经按照建议修改了相关内容，非常感谢指正

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +  实现的扩展点：`PreFilter`，`filter`，`preScore`，`score`。
```suggestion
  实现的扩展点：`preFilter`，`filter`，`preScore`，`score`。
```

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +  {{< glossary_tooltip text="StatefulSets" term_id="statefulset" >}} 的 Pod 跨节点分布
```suggestion
  {{< glossary_tooltip text="StatefulSets" term_id="statefulset" >}} 的 Pod 跨节点分布。
```

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +|Plugin|Extension Points|
```suggestion
| 插件 | 扩展点 |
```

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +* 重新排序 `DefaultPlugin2` 以在 `score` 中首先运行（甚至在自定义插件之前）
这种列表不用逐一翻译，三五个一起翻译就好。

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +* 在 v1beta2 配置版本中，你可以为 `NodeResourcesFit` 插件使用新的score扩展。
```suggestion
* 在 v1beta2 配置版本中，你可以为 `NodeResourcesFit` 插件使用新的 score 扩展。
```

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +  相反，使用 [`NodeAffinity`](/zh/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity) 插件（默认启用）来实现类似的行为。
```suggestion
  相反，要使用 [`NodeAffinity`](/zh/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  插件（默认启用）来实现类似的行为。
```

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +  相反，使用 [`InterPodAffinity`](/zh/doc/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity) 插件（默认启用）来实现类似的行为。
```suggestion
  相反，使用 [`InterPodAffinity`](/zh/doc/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity)
  插件（默认启用）来实现类似的行为。
```

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +  相反，使用 [node taints](/zh/docs/concepts/scheduling-eviction/taint-and-toleration/) 来实现类似的行为。
```suggestion
  相反，使用[节点污点](/zh/docs/concepts/scheduling-eviction/taint-and-toleration/)来实现类似的行为。
```

2022-04-18 01:34 UTC, tengqm commented on content/zh/docs/reference/scheduling/config.md
> +  * `TaintToleration` 从 1 到 3
以上段落一起翻译，不要逐行

2022-04-18 12:18 UTC, HirazawaUi commented
@tengqm 谢谢指正，已经按照建议全部修改完成了~

2022-04-18 12:31 UTC, howieyuen requested changes
found two nits, others lgtm

2022-04-18 12:31 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +使用 KubeSchedulerConfiguration ([v1beta2](/zh/docs/reference/config-api/kube-scheduler-config.v1beta2/)
中文符号，下同
```suggestion
使用 KubeSchedulerConfiguration（[v1beta2](/zh/docs/reference/config-api/kube-scheduler-config.v1beta2/)
```

2022-04-18 12:31 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +或者 [v1beta3](/zh/docs/reference/config-api/kube-scheduler-config.v1beta3/)) 结构体。
```suggestion
或者 [v1beta3](/zh/docs/reference/config-api/kube-scheduler-config.v1beta3/)）结构体。
```

2022-04-18 12:31 UTC, howieyuen commented on content/zh/docs/reference/scheduling/config.md
> +-`CinderLimits`：检查是否可以满足节点的 [OpenStack Cinder](https://docs.openstack.org/cinder/)卷限制
```suggestion
-`CinderLimits`：检查是否可以满足节点的 [OpenStack Cinder](https://docs.openstack.org/cinder/) 卷限制
```

2022-04-18 12:49 UTC, HirazawaUi commented
> found two nits, others lgtm

已改正~

2022-04-18 13:31 UTC, tengqm commented
/lgtm

2022-04-18 14:15 UTC, mengjiao-liu commented on content/zh/docs/reference/scheduling/config.md
> +
这个地方是不是少了这一行：
{{% /tab %}}

2022-04-18 15:03 UTC, mengjiao-liu commented on content/zh/docs/reference/scheduling/config.md
> +  * `TaintToleration` 从 1 到 3
```suggestion
<!--
* Three plugins' weight are increased by default:
  * `InterPodAffinity` from 1 to 2
  * `NodeAffinity` from 1 to 2
  * `TaintToleration` from 1 to 3
-->
* 默认增加三个插件的权重：
  * `InterPodAffinity` 从 1 到 2
  * `NodeAffinity` 从 1 到 2
  * `TaintToleration` 从 1 到 3
```
[预览页](https://deploy-preview-32951--kubernetes-io-main-staging.netlify.app/zh/docs/reference/scheduling/config/#%E8%B0%83%E5%BA%A6%E7%A8%8B%E5%BA%8F%E9%85%8D%E7%BD%AE%E8%BF%81%E7%A7%BB)显示如下：
列表递进关系不对。
<img width="489" alt="image" src="https://user-images.githubusercontent.com/44460091/163826235-8fca0397-c0f2-455b-bcf7-1f9e83978138.png">

英文版是这样：
<img width="465" alt="image" src="https://user-images.githubusercontent.com/44460091/163826632-9d448f6c-1b2d-4fc3-9ca5-a218819da9b7.png">


需要修改下 markdown 列表。
你可以把这几行直接放在一起翻译，不需要分开。

2022-04-18 15:20 UTC, HirazawaUi commented
@mengjiao-liu 已经更正了~

2022-04-19 02:27 UTC, mengjiao-liu commented
/lgtm

2022-04-19 02:33 UTC, howieyuen commented
Thanks for the big effort 👍 
/approve

2022-04-19 02:44 UTC, mengjiao-liu commented
/hold cancel
Thanks for your contribution!🎉

2022-04-19 02:45 UTC, merged