[zh] sync horizontal-pod-autoscale.md
kubernetes/website pull request #32964
Opened 2022-04-15 13:55 UTC by 0xff-dev

[zh] sync horizontal-pod-autoscale.md

2022-04-15 14:14 UTC, Sea-n requested changes
Great job, just a few nit pick for better format. :upside_down_face:

2022-04-15 14:14 UTC, Sea-n commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +## 可配置的缩放行为
All titles anchor should be specified.

Please refer to [中文本地化樣式指南#關於連結](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E5%85%B3%E4%BA%8E%E9%93%BE%E6%8E%A5).

2022-04-15 14:14 UTC, Sea-n commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +该指南涵盖了这个确切的用例。
Missed spaces between Chinese and English words.

Ref: [中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)

2022-04-15 14:22 UTC, 0xff-dev commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +## 可配置的缩放行为
okay, thanks.

2022-04-15 15:11 UTC, Sea-n approved these changes
Thanks for fixing quickly, lgtm.

2022-04-16 03:38 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +In Kubernetes, a _HorizontalPodAutoscaler_ automatically updates a workload resource (such as a
In Kubernetes, a _HorizontalPodAutoscaler_ automatically updates a workload resource (such as
a {{< glossary_tooltip text="Deployment" term_id="deployment" >}} or
{{< glossary_tooltip text="StatefulSet" term_id="statefulset" >}}), with the
aim of automatically scaling the workload to match demand.

2022-04-16 03:38 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +<!--with the aim of automatically scaling the workload to match demand. -->
删除此行

2022-04-16 03:38 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +目的是自动扩展工作负载以满足需求。
```suggestion
目的是自动扩缩工作负载以满足需求。
```

2022-04-16 03:38 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +-->
Horizontal scaling means that the response to increased load is to deploy more
{{< glossary_tooltip text="Pods" term_id="pod" >}}.
This is different from _vertical_ scaling, which for Kubernetes would mean
assigning more resources (for example: memory or CPU) to the Pods that are already
running for the workload.

2022-04-16 03:38 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +-->
请按段落翻译，不要按行切割。下同。
重新组织后再 review.

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +当前的稳定版本可以在 `autoscaling/v2` API 版本中找到，其中包括对内存扩展和自定义指标的支持。
```suggestion
当前的稳定版本可以在 `autoscaling/v2` API 版本中找到，其中包括对基于内存和自定义指标执行扩缩的支持。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +副本的数量可能会经常波动。这有时被称为 *抖动* 或 *波动*。它类似于控制论中的 *滞后* 概念。
```suggestion
副本的数量可能会经常波动。这有时被称为 **抖动（thrashing）** 或 *波动（flapping）*。
它类似于控制论中的 **滞后（hysteresis）** 概念。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +基于自定义指标（未内置于 Kubernetes 或任何 Kubernetes 组件）进行缩放。
在中英文边界处换行。
```suggestion
如果你使用 `autoscaling/v2` API 版本，则可以将 HorizontalPodAutoscaler
配置为基于自定义指标（未内置于 Kubernetes 或任何 Kubernetes 组件）进行扩缩。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +HorizontalPodAutoscaler 控制器然后从 Kubernetes API 查询这些自定义指标。
这里的 then 没有那么强的“然后”概念。

```suggestion
HorizontalPodAutoscaler 控制器能够从 Kubernetes API 查询这些自定义指标。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +有关要求，请参阅对[指标 API 的支持](#support-for-metrics-apis)。
Metrics API 可以视为专有名词。

```suggestion
有关要求，请参阅对 [Metrics API 的支持](#support-for-metrics-apis)。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +## 扩展多个指标 {#scaling-on-multiple-metrics}
```suggestion
## 基于多个指标来执行扩缩      {#scaling-on-multiple-metrics}
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +如果你使用 `autoscaling/v2` API 版本，你可以为 HorizontalPodAutoscaler 指定多个指标以进行扩展。
```suggestion
如果你使用 `autoscaling/v2` API 版本，你可以为 HorizontalPodAutoscaler 指定多个指标以进行扩缩。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +然后，HorizontalPodAutoscaler 控制器评估每个指标，并根据该指标提出一个新的比例。
```suggestion
HorizontalPodAutoscaler 控制器评估每个指标，并根据该指标提出一个新的比例。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +[the HPA V2](https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/hpa-v2.md),
```suggestion
[HPA V2](https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/hpa-v2.md),
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +## 可配置的缩放行为 {#configurable-scaling-behavior}
```suggestion
## 可配置的扩缩行为     {#configurable-scaling-behavior}
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +你可以指定一个 _稳定窗口_，以防止缩放目标的副本计数发生[波动](#flapping)。
```suggestion
你可以指定一个 “稳定窗口”，以防止缩放目标的副本计数发生[波动](#flapping)。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +可以在规范的行为部分中指定一个或多个扩展策略。当指定多个策略时，
```suggestion
可以在规约的 behavior 部分中指定一个或多个扩展策略。当指定多个策略时，
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +自动缩放算法使用此窗口来推断先前的期望状态并避免对工作负载规模进行不必要的更改。
```suggestion
自动扩缩算法使用此窗口来推断先前的期望状态并避免对工作负载规模进行不必要的更改。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +这近似于滚动最大值，并避免了缩放算法频繁删除 Pod 仅在稍后触发重新创建等效 Pod。
```suggestion
这近似于滚动最大值，并避免了扩缩算法频繁删除 Pod 而又触发重新创建等效 Pod。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +与每个 API 资源一样，HorizontalPodAutoscaler 都由 `kubectl` 以标准方式支持。
```suggestion
与每个 API 资源一样，HorizontalPodAutoscaler 都被 `kubectl` 以标准方式支持。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +你可以使用 `kubectl create` 命令创建一个新的自动缩放器。
缩放 -> 扩缩。

下同。

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +当启用 HPA 时，建议从它们的 {{< glossary_tooltip text="manifest(s)" term_id="manifest" >}}
```suggestion
当启用 HPA 时，建议从它们的{{< glossary_tooltip text="清单" term_id="manifest" >}}中
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +{{% tab name="Client Side Apply (this is the default)" %}}
```suggestion
{{% tab name="客户端 apply 操作（默认行为）" %}}
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +1. `kubectl apply edit-last-applied deployment/<deployment_name>`
```suggestion
1. `kubectl apply edit-last-applied deployment/<Deployment 名称>`
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +    在此步骤中不会更改 Pod 计数。
```suggestion
   在此步骤中不会更改 Pod 计数。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +    还应提交你的更改或采取任何其他步骤来修改源代码，以适应你如何跟踪更新。
```suggestion
   还应提交你的更改或采取任何其他步骤来修改源代码，以适应你如何跟踪更新。
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +{{% tab name="Server Side Apply" %}}
```suggestion
{{% tab name="服务器端 apply 操作" %}}
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +使用 [Server-Side Apply](/zh/docs/reference/using-api/server-side-apply/)，
```suggestion
使用[服务器端 Apply](/zh/docs/reference/using-api/server-side-apply/) 机制，
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +你可以遵循 [transferring ownership](/zh/docs/reference/using-api/server-side-apply/#transferring-ownership)，
```suggestion
你可以遵循[交出所有权](/zh/docs/reference/using-api/server-side-apply/#transferring-ownership)说明，
```

2022-04-16 09:11 UTC, tengqm commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +* 阅读 [API reference](/zh/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/)。
这个链接恐怕还要用英文，中文尚未翻译。
```suggestion
* 阅读 [API 参考](/zh/docs/reference/kubernetes-api/workload-resources/horizontal-pod-autoscaler-v2/)。
```

2022-04-16 10:16 UTC, 0xff-dev commented
/cc @tengqm 感谢review。

2022-04-16 13:39 UTC, tengqm commented
/approve

2022-04-16 16:37 UTC, ydFu commented
/assign @ydFu

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +## HorizontalPodAutoscaler是如何工作的？ {#how-does-a-horizontalpodautoscaler-work}
```suggestion
## HorizontalPodAutoscaler 是如何工作的？ {#how-does-a-horizontalpodautoscaler-work}
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +Pod 自动扩缩[演练示例](/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)。
```suggestion
使用水平 pod 自动扩缩[演练示例](/zh/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/)。
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +Pod 自动扩缩控制器会定期调整其目标（例如 Deployment）的所需规模，以匹配观察到的指标，
```suggestion
Pod 自动扩缩控制器会定期调整其目标（例如：Deployment）的所需规模，以匹配观察到的指标，
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +例如平均 CPU 利用率、平均内存利用率或你指定的任何其他自定义指标。
```suggestion
例如，平均 CPU 利用率、平均内存利用率或你指定的任何其他自定义指标。
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +（`metrics.k8s.io`、`custom.metrics.k8s.i`o 或 `external.metrics.k8s.io`）获取指标。
```suggestion
（`metrics.k8s.io`、`custom.metrics.k8s.io` 或 `external.metrics.k8s.io`）获取指标。
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +有关 Kubernetes API 中子资源的一般信息，
```suggestion
有关 Kubernetes API 子资源的一般信息，
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +HorizontalPodAutoscaler 控制器访问支持扩缩的相应工作负载资源（例如 Deployments 和 StatefulSet）。
```suggestion
HorizontalPodAutoscaler 控制器访问支持扩缩的相应工作负载资源（例如：Deployments 和 StatefulSet）。
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +因为 `200.0 / 100.0 == 2.0` 如果当前值为 `50`m，则副本数将减半，
```suggestion
因为 `200.0 / 100.0 == 2.0` 如果当前值为 `50m`，则副本数将减半，
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +有关要求，请参阅对[Metrics APIs 的支持](#support-for-metrics-apis)。
```suggestion
有关要求，请参阅对 [Metrics APIs 的支持](#support-for-metrics-apis)。
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +使用 [服务器端 Apply](/zh/docs/reference/using-api/server-side-apply/) 机制，
```suggestion
使用[服务器端 Apply](/zh/docs/reference/using-api/server-side-apply/) 机制，
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +这与 “垂直（Vertical）”扩缩不同，对于 Kubernetes，
```suggestion
这与 “垂直（Vertical）” 扩缩不同，对于 Kubernetes，
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +HorizontalPodAutoscaler 也支持容器指标源，这时 HPA 可以跟踪记录一组 Pods 中各个容器的
```suggestion
HorizontalPodAutoscaler API 也支持容器指标源，这时 HPA 可以跟踪记录一组 Pods 中各个容器的
```

2022-04-18 01:39 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +[HPA V2](https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/hpa-v2.md),
```suggestion
[HPA V2](https://github.com/kubernetes/design-proposals-archive/blob/main/autoscaling/hpa-v2.md) ，
```

2022-04-18 09:12 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +而不考虑尚未准备好的 pod 或缺少的指标，即使使用新的使用率也是如此。
```suggestion
而不考虑尚未准备好的 Pod 或缺少的指标，即使使用新的使用率也是如此。
```

2022-04-18 09:12 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +你可以指定一个 “稳定窗口”，以防止扩缩目标的副本计数发生[波动](#flapping)。
```suggestion
你可以指定一个“稳定窗口”，以防止扩缩目标的副本计数发生[波动](#flapping)。
```

2022-04-18 09:12 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +可以在规约的 behavior 部分中指定一个或多个扩缩策略。当指定多个策略时，
```suggestion
可以在规约的 `behavior` 部分中指定一个或多个扩缩策略。当指定多个策略时，
```

2022-04-18 09:12 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +2. 在编辑器中，删除 spec.replicas。当你保存并退出编辑器时，kubectl 会应用更新。
```suggestion
2. 在编辑器中，删除 `spec.replicas`。当你保存并退出编辑器时，`kubectl` 会应用更新。
```

2022-04-18 09:12 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +你可以遵循[交出所有权](/zh/docs/reference/using-api/server-side-apply/#transferring-ownership)说明，
```suggestion
你可以遵循[交出所有权](/zh/docs/reference/using-api/server-side-apply/#transferring-ownership) 说明，
```

2022-04-18 09:12 UTC, ydFu commented on content/zh/docs/tasks/run-application/horizontal-pod-autoscale.md
> +当使用 CPU 指标来扩缩时，任何还未就绪（例如还在初始化，或者可能是不健康的）状态的 Pod **或**
```suggestion
当使用 CPU 指标来扩缩时，任何还未就绪（还在初始化，或者可能是不健康的）状态的 Pod **或** 
```

2022-04-18 09:45 UTC, ydFu commented
LGTM,thank for your contributetion.
/lgtm

2022-04-18 09:46 UTC, merged