fix: Well-Known Annotations/Labels/Taints examples
kubernetes/website pull request #32991
Opened 2022-04-17 01:33 UTC by jai

Fixes https://github.com/kubernetes/website/issues/32989

2022-04-17 02:09 UTC, jai commented
Example page: https://deploy-preview-32991--kubernetes-io-main-staging.netlify.app/docs/reference/labels-annotations-taints/

2022-04-22 05:46 UTC, divya-mohan0209 requested changes
Small nit, otherwise lgtm.

2022-04-22 05:46 UTC, divya-mohan0209 commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +Example: `storageclass.kubernetes.io/is-default-class: true`
```suggestion
Example: `storageclass.kubernetes.io/is-default-class: "true"`
```

2022-06-17 05:56 UTC, zacharysarah commented
/lgtm
/approve

2022-06-17 05:58 UTC, merged