refactor: Descriptions on Well-Known Annotations/Labels/Taints
kubernetes/website pull request #32992
Opened 2022-04-17 01:46 UTC by jai

Fixes https://github.com/kubernetes/website/issues/32990

2022-06-16 04:32 UTC, zacharysarah requested changes
@jai Thanks for your patience, and thanks for adding clarity to the page.

I started doing individual suggestions, but gave up about two-thirds of the way through. The feedback is identical to my other suggestions on this PR: de-capitalize all instances of "Workload Resources" and use relative paths for all internal site links.

Otherwise LGTM

2022-06-16 04:32 UTC, zacharysarah commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +Used on: All Objects (typically used on [Workload Resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).
Remove [caps](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects), use [relative links](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects).

```suggestion
Used on: All Objects (typically used on [workload resources](/docs/reference/kubernetes-api/workload-resources/)).
```

2022-06-16 04:32 UTC, zacharysarah commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +Used on: All Objects (typically used on [Workload Resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).
Remove [caps](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects), use [relative links](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects).
```suggestion
Used on: All Objects (typically used on [workload resources](/docs/reference/kubernetes-api/workload-resources/)).
```

2022-06-16 04:32 UTC, zacharysarah commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +Used on: All Objects (typically used on [Workload Resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).
Remove [caps](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects), use [relative links](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects).
```suggestion
Used on: All Objects (typically used on [workload resources](/docs/reference/kubernetes-api/workload-resources/)).
```

2022-06-16 04:32 UTC, zacharysarah commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +A unique name identifying the instance of an application. If you want to declare what application this is part of but not in a unique way, use [app.kubernetes.io/name](##app-kubernetes-io-name).
Use [simple and direct language](https://kubernetes.io/docs/contribute/style/style-guide/#use-simple-and-direct-language), Markdown nit

```suggestion
A unique name identifying the instance of an application. To assign a non-unique name, use [app.kubernetes.io/name](#app-kubernetes-io-name).
```

2022-06-16 04:32 UTC, zacharysarah commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +Used on: All Objects (typically used on [Workload Resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/)).
Remove [caps](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects), use [relative links](https://kubernetes.io/docs/contribute/style/style-guide/#use-upper-camel-case-for-api-objects).
```suggestion
Used on: All Objects (typically used on [workload resources](/docs/reference/kubernetes-api/workload-resources/)).
```

2022-06-16 04:32 UTC, zacharysarah commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +The name of the application. Note that this label is typically used on [Workload Resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/).
Use simple and direct language, and use consistent text and formatting with other examples of this language.

```suggestion
The name of the application (typically used on [workload resources](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/).
```

2022-06-16 04:32 UTC, zacharysarah commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +The current version of the application. The values for this field are up to you.
Use simple and direct language.

```suggestion
The current version of the application.
```

2022-07-26 02:33 UTC, jai commented
@zacharysarah thanks for taking the time to comment, I'll get on this!

2022-08-19 05:31 UTC, reylejano commented
I'm closing this PR as this PR has not addressed comments/suggestions
Please feel free to reopen (with `/reopen`) when the author is ready to address the comments/suggestions
/close

2022-08-19 05:31 UTC, closed without merging