Add content/pt-br/docs/reference/glossary/sysctl.md
kubernetes/website pull request #33098
Opened 2022-04-21 17:30 UTC by MrErlison

Added translate content/pt-br/docs/reference/glossary/sysctl.md

2022-06-12 15:06 UTC, stormqueen1990 requested changes

2022-06-12 15:06 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/sysctl.md
> +Em sistemas do tipo Unix-like, `sysctl` é tanto o nome da ferramenta que os administradores usam para visualizar e modificar essas configurações, quanto a chamada do sistema que a ferramenta usa.
Suggestion: "sistemas do tipo Unix" reads more natural than "sistemas do tipo Unix-like" and delivers the same meaning.

2022-06-12 15:06 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/sysctl.md
> +Os {{< glossary_tooltip text="Contêiner" term_id="container" >}} em execução e os plugins de rede podem depender dos valores definidos do `sysctl`.
Typo: "contêiner" should have been "contêineres".

2022-06-17 14:46 UTC, rikatz commented
/approve
/lgtm
Thanks for the review @stormqueen1990 
Thanks for all the PRs in glossary you are doing @MrErlison  :)

2022-06-17 14:48 UTC, merged