Add pt-br/docs/reference/setup-tools/kubeadm/kubeadm-config.md
kubernetes/website pull request #33114
Opened 2022-04-22 11:19 UTC by MrErlison

Added translate pt-br/docs/reference/setup-tools/kubeadm/kubeadm-config.md

2022-06-02 13:11 UTC, Sea-n reviewed
Please refer to [Netlify build log](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/62628f42d1dd64000978a983#L4009-L4015), feel free to `/unhold` yourself once resolved the issue.

2022-06-02 13:11 UTC, Sea-n commented
/hold

2022-06-04 16:43 UTC, MrErlison commented on content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-config.md
> +{{< include "generated/kubeadm_config_print.md" >}}
Thank you. /unhold

2022-07-22 11:14 UTC, MrErlison commented
/assign @stormqueen1990

2022-08-03 02:02 UTC, Sea-n commented
The build error have been solved.
/unhold

CC @rikatz this PR is placed for a long time too.

2022-08-11 02:01 UTC, edsoncelio commented
Thanks!
/lgtm

2022-08-29 05:55 UTC, divya-mohan0209 commented
@stormqueen1990 : Hello there, please could you have a look at this PR? The build error seems to have been resolved & I believe this is one of the PRs required to merge another PR.

2022-08-29 13:04 UTC, stormqueen1990 commented
Hi there, @divya-mohan0209!

Sure thing, will take a look!

2022-08-29 13:25 UTC, stormqueen1990 requested changes
Hello there, @MrErlison! Thank you very much for your contribution! 🎉 

I found some issues with readability that need to be addressed. If you have any questions please don't hesitate to reach out!

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-config.md
> +Para obter mais informações sobre `init` e `join`, navegue até [Usando o init do kubeadm com um arquivo de configuração](/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file) ou [Usando o ku
Keep "kubeadm init" in this sentence instead of "init do kubeadm".

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-config.md
> +`kubeadm config images list` e `kubeadm config images pull` podem ser usadas para listar e puxar as imagens que o kubeadm precisa.
Suggestion: "baixar" instead of "puxar".

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print.md
> +Exibir configurações
Suggestion: "exibe" in lieu of "exibir".

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>O arquivo kubeconfig pode ser usado para se comunicar com o cluster. Se a flag não estiver definida, um conjunto de padrão local pode
This bit was better translated in your PR #33116. I think we can copy this bit from there.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_init-defaults.md
> +Este comando exibe os objetos como a configuração de inicialização padrão que é usada para 'kubeadm init'.
Maybe "exibe objetos, como por exemplo a configuração..."?

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_init-defaults.md
> +Observe que os valores confidenciais, como os campos do Token Bootstrap, são substituídos por valores de espaço reservado como "abcdef.0123456789abcdef", a fim de passar na validação, mas não executa
We usually don't say "espaço reservado" in Portuguese for placeholder. Maybe "valores de exemplo"?

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_init-defaults.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>Uma lista separada por vírgulas dos objetos da API de configuração exibirá os valores padrão. Valores disponíveis: [KubeProxyConfigur
This sentence can be rethought. It's a bit hard for me to parse through it and understand what meaning it was trying to deliver.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_init-defaults.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>O arquivo kubeconfig pode ser usado para se comunicar com o cluster. Se a flag não estiver definida, um conjunto de padrão local pode
Could be copied from #33116.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md
> +Observe que valores confidenciais, como os campos do Token Bootstrap, são substituídos por valores de espaço reservado como "abcdef.0123456789abcdef", a fim de passar na validação, mas não executar o
Same comment as in kubeadm config print init-defaults.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>Uma lista separada por vírgulas dos objetos da API de configuração exibirá os valores padrão. Valores disponíveis: [KubeProxyConfigur
Same comment as in kubeadm config print init-defaults.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_print_join-defaults.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>O arquivo kubeconfig pode ser usado para se comunicar com o cluster. Se a flag não estiver definida, um conjunto de padrão local pode
Same comment as in kubeadm config print init-defaults.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_migrate.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>O arquivo kubeconfig pode ser usado para se comunicar com o cluster. Se a flag não estiver definida, um conjunto de padrão local pode
Same comment as in kubeadm config print init-defaults.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>Formato de saída. Um dos: text|json|yaml|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-as-json|jsonpath-file.<
Instead of "um dos", maybe use "valores válidos".

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>Escolha um registro de contêineres para extrair imagens da camada de gerenciamento</p></td>
Maybe "baixar" in lieu of "extrair"?

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_list.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>O arquivo kubeconfig pode ser usado para se comunicar com o cluster. Se a flag não estiver definida, um conjunto de padrão local pode
Same comment as in kubeadm config print init-defaults.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
> +
Maybe "baixa" instead of "puxe"?

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>Caminho para se conectar ao socket CRI. Se um kubeadm vazio tentar detectar automaticamente esse valor; use essa opção somente se voc
For the second sentence, "Se vazio, o kubeadm tentará detectar automaticamente" delivers the meaning better.

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>Um conjunto de pares chave=valor que descrevem opções para vários recursos. As opções são:<br/>PublicKeysECDSA=true|false (ALPHA - pa
"descrevem _feature gates_" instead of "descrevem opções".

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>Escolha um registro de contêineres para extrair imagens da camada de gerenciamento</p></td>
Consider using "baixar" instead of "extrair".

2022-08-29 13:25 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/generated/kubeadm_config_images_pull.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>O arquivo kubeconfig pode ser usado para se comunicar com o cluster. Se a flag não estiver definida, um conjunto de padrão local pode
Same comment as in kubeadm config print init-defaults.

2022-10-23 16:08 UTC, stormqueen1990 commented
/lgtm
/assign @edsoncelio

2022-10-23 19:45 UTC, edsoncelio commented
Thanks @stormqueen1990 and @MrErlison 
/approve

2022-10-23 19:48 UTC, merged