Add content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-version.md
kubernetes/website pull request #33112
Opened 2022-04-22 10:54 UTC by MrErlison

Added translate content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-version.md

2022-05-30 11:20 UTC, devlware commented
/lgtm

2022-06-02 13:25 UTC, Sea-n reviewed
Please refer to [Netlify build log](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6263de226aa1c400097be32c#L4008), feel free to `/unhold` yourself when it's resolved.

/hold

2022-06-04 16:06 UTC, MrErlison commented on content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-version.md
> +{{< include "generated/kubeadm_version.md" >}}
Thanks @Sea-n . Now I understand what you say. /unhold

2022-07-22 11:14 UTC, MrErlison commented
/assign @stormqueen1990

2022-07-24 15:50 UTC, stormqueen1990 requested changes
Minor change in front matter. After updated will be a LGTM.

2022-07-24 15:50 UTC, stormqueen1990 commented on content/pt-br/docs/reference/setup-tools/kubeadm/kubeadm-version.md
> +content_type: conceito
Keep "concept" here.

2022-07-25 13:38 UTC, stormqueen1990 commented
/lgtm

2022-07-25 14:32 UTC, rikatz approved these changes
/lgtm
/approve
/unhold
Thanks

2022-07-25 14:34 UTC, merged