Add pt-br/docs/reference/glossary/ingress.md
kubernetes/website pull request #33153
Opened 2022-04-23 15:59 UTC by MrErlison

Add
- /pt-br/docs/reference/glossary/ingress.md

2022-06-11 14:10 UTC, rikatz commented on content/pt-br/docs/reference/glossary/ingress.md
> +O Ingress pode fornecer um balanceamento de carga, descriptografia SSL e hospedagem virtual baseada em nome.
This phrase is a bit strange. Maybe we don’t need the literal translation here and just say “Um ingress pode fornecer as capacidades de um proxy reverso para as aplicações”

2022-06-12 15:00 UTC, stormqueen1990 requested changes
Minor change for readability.

2022-06-12 15:00 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/ingress.md
> +  Um objeto API que gerencia o acesso externo aos serviços em um cluster, normalmente HTTP.
Minor: "objeto da API" instead of "objeto API".

2022-06-12 15:00 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/ingress.md
> + Um objeto API (do inglês "Application Programming Interface") que gerencia o acesso externo aos serviços em um cluster, normalmente HTTP.
Minor: "objeto da API" instead of "objeto API".

2022-06-17 13:31 UTC, stormqueen1990 commented
/lgtm

2022-06-17 14:12 UTC, rikatz commented
/approve
Thanks

2022-06-17 14:14 UTC, merged