Add pt-br/docs/reference/glossary/kubectl.md
kubernetes/website pull request #33154
Opened 2022-04-23 16:05 UTC by MrErlison

Add 
- pt-br/docs/reference/glossary/kubectl.md

2022-06-12 14:57 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/kubectl.md
> +Ferramenta de linha de comando para se comunicar com o {{< glossary_tooltip text="plano de controle" term_id="control-plane" >}} de um cluster Kubernetes usando a API do Kubernetes.
"camada de gerenciamento" would be our agreed upon term in Portuguese for control plane.

2022-06-12 14:58 UTC, stormqueen1990 requested changes
Minor change on the control plane translation.

2022-06-17 13:32 UTC, stormqueen1990 requested changes

2022-06-17 13:32 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/kubectl.md
> +Ferramenta de linha de comando para se comunicar com o {{< glossary_tooltip text="camada de gerenciamento" term_id="control-plane" >}} de um cluster Kubernetes usando a API do Kubernetes.
Very minor: "o camada de gerenciamento" should be "a camada de gerenciamento".

2022-06-17 22:39 UTC, Sea-n commented on content/pt-br/docs/reference/glossary/kubectl.md
> +full_link: /docs/user-guide/kubectl-overview/
```suggestion
full_link: /pt-br/docs/user-guide/kubectl-overview/
```

2022-06-17 22:47 UTC, Sea-n commented
Thanks for quick fixing! But I am not a Brazilian Portuguese speaker, format-wise looks good to me. 😅
/uncc

2022-06-26 14:27 UTC, edsoncelio commented
Thanks!
/lgtm 

@stormqueen1990 PTAL

2022-06-27 01:48 UTC, stormqueen1990 approved these changes

2022-07-29 17:53 UTC, rikatz commented
/approve
Thanks

2022-07-29 17:55 UTC, merged