Add pt-br/docs/reference/glossary/cluster-infrastructure.md
kubernetes/website pull request #33150
Opened 2022-04-23 15:29 UTC by MrErlison

Added translate pt-br/docs/reference/glossary/cluster-infrastructure.md

2022-06-12 15:03 UTC, stormqueen1990 requested changes
Minor capitalization.

2022-06-12 15:03 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/cluster-infrastructure.md
> +title: infraestrutura de Cluster
I think "infraestrutura" here should have the first letter capitalized.

2022-06-17 13:33 UTC, stormqueen1990 commented
/lgtm

2022-06-24 02:22 UTC, reylejano commented
/assign @femrtnz

2022-06-26 14:29 UTC, edsoncelio commented
Thanks!
/approve

2022-06-26 14:30 UTC, merged