[zh] Update kubeadm-join.md
kubernetes/website pull request #33210
Opened 2022-04-26 09:39 UTC by fenggw-fnst

Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

/assign @tengqm
PTAL, thanks.

2022-04-26 11:47 UTC, howieyuen requested changes

2022-04-26 11:47 UTC, howieyuen commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-join.md
> +有关配置的字段和用法的更多信息，你可以导航到我们的 API [参考页](/zh/docs/reference/config-api/kubeadm-config.v1beta3/)。
```suggestion
有关配置的字段和用法的更多信息，你可以导航到我们的
[API 参考](/zh/docs/reference/config-api/kubeadm-config.v1beta3/)。
```

2022-04-27 01:17 UTC, fenggw-fnst commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-join.md
> +有关配置的字段和用法的更多信息，你可以导航到我们的 API [参考页](/zh/docs/reference/config-api/kubeadm-config.v1beta3/)。
Thanks, done.

2022-04-27 02:00 UTC, tengqm commented
Thanks.
/lgtm
/approve

2022-04-27 02:02 UTC, merged