[zh]Update content/zh/blog/_posts/2018-10-01-health-checking-grpc.md
kubernetes/website pull request #33271
Opened 2022-04-27 17:56 UTC by kinzhi

2022-04-28 02:41 UTC, howieyuen requested changes
Thanks to the contribution, please refer to [中文本地化指南](https://kubernetes.io/zh/docs/contribute/localization_zh/) for more info.

2022-04-28 02:41 UTC, howieyuen commented on content/zh/blog/_posts/2018-10-01-health-checking-grpc.md
> +**更新（2021年12月）:** _Kubernetes 从 v1.23 开始具有内置 gRPC 运行状况探测。
斜体在中文格式是不存在的，印刷体可以使用楷书。因此在本项目中英文斜体在翻译时，使用引号代替。
```suggestion
**更新（2021 年 12 月）：** “Kubernetes 从 v1.23 开始具有内置 gRPC 健康探测。
```

2022-04-28 02:41 UTC, howieyuen commented on content/zh/blog/_posts/2018-10-01-health-checking-grpc.md
> +了解更多信息，请参阅 [配置 Liveness、Readiness 和 Startup Probes](/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe)。
```suggestion
了解更多信息，请参阅[配置存活探针、就绪探针和启动探针](/zh/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe)。
```

2022-04-28 02:41 UTC, howieyuen commented on content/zh/blog/_posts/2018-10-01-health-checking-grpc.md
> +本文最初是关于实现相同任务的外部工具。_
```suggestion
本文最初是为有关实现相同任务的外部工具所写。”
```

2022-04-28 03:23 UTC, tengqm commented
please squash your commits into one.

2022-04-29 03:53 UTC, kinzhi commented
Please help to review this PR

2022-04-29 06:14 UTC, howieyuen commented
/lgtm

2022-04-29 10:23 UTC, tengqm commented
/approve

2022-04-29 10:27 UTC, merged