[zh] sync api-concepts.md
kubernetes/website pull request #33283
Opened 2022-04-28 12:57 UTC by 0xff-dev

[zh] sync api-concepts.md

2022-04-28 12:59 UTC, 0xff-dev commented
/cc @tengqm  @mengjiao-liu

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +在 Kubernetes 术语中，你从 **list** 中获得的响应是​​一个 _集合（Collections）_。
```suggestion
在 Kubernetes 术语中，你从 **list** 中获得的响应是​​一个“集合（Collections）”。
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +集合有一种以资源种类命名的种类，并附加了`列表`。
```suggestion
集合的类别名是针对资源类别的，并附加了`List`。
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +例如，当你 **列出** 服务时，集合响应的 `kind` 设置为 [`ServiceList`](/zh/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceList)；
```suggestion
例如，当你 **list** Service 对象时，集合响应的 `kind` 设置为
[`ServiceList`](/zh/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceList)；
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +该集合中的每个项目都代表一个服务。例如：
Service 首字母大写时指资源类别名称，不要翻译。

```suggestion
该集合中的每个项目都代表一个 Service。例如：
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +一些工具，例如 `kubectl`，代表 Kubernetes 收集机制与 Kubernetes API 本身略有不同。
```suggestion
一些工具，例如 `kubectl`，对于 Kubernetes 集合的表现机制与 Kubernetes API 本身略有不同。
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +`kind：List` 是一个客户端内部实现细节，用于处理可能属于不同类型对象的集合。
```suggestion
`kind: List` 是一个客户端内部实现细节，用于处理可能属于不同类别的对象的集合。
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +[扩展核心 Kubernetes API](/zh/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/) 的 APIService 可能根本不提供表响应。
```suggestion
[扩展核心 Kubernetes API](/zh/docs/concepts/extend-kubernetes/api-extension/apiserver-aggregation/)
的 APIService 可能根本不提供 Table 响应。
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +如果你正在实现使用表信息并且必须针对所有资源类型（包括扩展）工作的客户端，
```suggestion
如果你正在实现使用 Table 信息并且必须针对所有资源类型（包括扩展）工作的客户端，
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +通过 `GET` 调用传递 `Accept` 请求头让请求服务器尝试以你的首选媒体类型返回响应，
```suggestion
带有 `Accept` 请求头部的 `GET` 调用会请求服务器尝试以你的首选媒体类型返回响应，
```

2022-04-29 10:45 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +同时将 Protobuf 中的对象发送到服务器以进行 `PUT` 或 `POST` 调用意味着你必须适当地设置 `Content-Type` 请求头。
```suggestion
而将 Protobuf 中的对象发送到服务器以进行 `PUT` 或 `POST` 调用意味着你必须适当地设置
`Content-Type` 请求头。
```

2022-04-29 13:55 UTC, 0xff-dev commented on content/zh/docs/reference/using-api/api-concepts.md
> +任何
你好，这个我看之前也是做了中文翻译，[resourceVersion 参数](https://kubernetes.io/zh/docs/reference/using-api/api-concepts/#the-resourceversion-parameter)，这里是不是对于`resourceVersionMatch`的两个可选参数`Exact`和`NotOlderThan` 不做翻译，而`Any`，`Most Recent`, `Continue Token, Exact`这个第三个是对`resourceVersion`未设置，0和非零值的情况的一个解释，这三个需要做翻译。

2022-04-29 17:19 UTC, mengjiao-liu requested changes

2022-04-29 17:19 UTC, mengjiao-liu commented on content/zh/docs/reference/using-api/api-concepts.md
> +  返回的继续令牌负责跟踪初始分页列表之后的所有分页列表调用的初始提供的资源版本。
```suggestion
返回的 _Continue 令牌_ 负责跟踪最初提供的资源版本，最初提供的资源版本用于在初始分页 **list** 之后的所有分页 **list** 中。
```

2022-04-29 17:19 UTC, mengjiao-liu commented on content/zh/docs/reference/using-api/api-concepts.md
> +  以这种方式初始化的手表可能会返回任意陈旧的数据。
```suggestion
  以这种方式初始化的监视可能会返回任意陈旧的数据。
```

2022-04-29 17:19 UTC, mengjiao-liu commented on content/zh/docs/reference/using-api/api-concepts.md
> +如果你 **list** 或 **get** API 服务器无法识别的资源版本，则 API 服务器可能会：
```suggestion
如果你请求了 **list** 或 **get** API 服务器无法识别的资源版本，则 API 服务器可能会：
```

2022-04-29 17:19 UTC, mengjiao-liu commented on content/zh/docs/reference/using-api/api-concepts.md
> +* 短暂等待资源版本可用，然后如果提供的资源版本在合理的时间内没有可用，
```suggestion
* 短暂等待资源版本可用，如果提供的资源版本在合理的时间内仍不可用，
```

2022-04-30 13:53 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +如果 **列表** 是完整的（因为它没有分块，或者因为这是最后一个块），没有更多的剩余项目，
本页面中，类似 `**list**` 这种表达，都是指 kubernetes API verb，不要翻译。请彻查。

```suggestion
如果 **list** 是完整的（因为它没有分块，或者因为这是最后一个块），没有更多的剩余项目，
```

2022-04-30 13:54 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +如果终结器列表是按顺序处理的，那么这可能会导致这样一种情况:在列表中负责第一个终结器的组件正在等待列表中稍后负责终结器的组件产生的某些信号（字段值、外部系统或其他），从而导致死锁。
```suggestion
如果终结器列表是按顺序处理的，那么这可能会导致这样一种情况：
在列表中负责第一个终结器的组件正在等待列表中稍后负责终结器的组件产生的某些信号
（字段值、外部系统或其他），从而导致死锁。
```

2022-04-30 13:56 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +的 `sideEffects` 字段为 `None`，依次声明它们没有副作用。
```suggestion
的 `sideEffects` 字段为 `None`，借此声明它们没有副作用。
```

2022-04-30 13:57 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
>  时的资源版本。
```suggestion
（即 **list** 操作的响应）的 `metadata.resourceVersion` 所标明的是 list
响应被构造时的资源版本。
```

2022-04-30 13:59 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +Not older than
这一行要与表格中的项对应起来，表格里面已将此翻译为“不老于指定版本”

2022-04-30 14:00 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +Exact
同样，这里要翻译为“精确匹配”，以便于表格中的值对应。

2022-04-30 14:00 UTC, tengqm commented on content/zh/docs/reference/using-api/api-concepts.md
> +Continue 令牌、精确匹配
同上。要与表格中翻译一致。

2022-05-02 10:47 UTC, mengjiao-liu commented
/lgtm

2022-05-03 12:49 UTC, 0xff-dev commented on content/zh/docs/reference/using-api/api-concepts.md
> +  则以 `504（网关超时）`超时；
好的。

2022-05-05 08:26 UTC, mengjiao-liu commented
/approve
/lgtm
Great job!

2022-05-05 08:28 UTC, merged

2022-05-20 03:01 UTC, nameYULI commented
related issue: https://github.com/kubernetes/website/issues/33478
reference-14