[bn] Localize content/bn/docs/concepts/overview/what-is-kubernetes.md
kubernetes/website pull request #33294
Opened 2022-04-28 21:04 UTC by ikramulkayes

Signed-off-by: Ikramul Kayes [ikramul.kayesgg@gmail.com](mailto:ikramul.kayesgg@gmail.com)
Localizes content/bn/docs/concepts/overview/what-is-kubernetes.md> to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/kubernetes/website/issues/31677

2022-04-28 21:09 UTC, mitul3737 commented
@ikramulkayes  Please do sign the [EasyCLA.](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/33294/#/?version=2)

2022-04-28 21:50 UTC, ikramulkayes commented
Updated my easycla

2022-04-28 22:08 UTC, mitul3737 requested changes

2022-04-28 22:08 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +আপনি কুবারনেটিস ব্যবহার করে আপনার স্থাপন করা কন্টেইনার জন্য পছন্দসই অবস্থা বর্ণনা করতে পারেন এবং এটি একটি নিয়ন্ত্রিত হারে প্রকৃত অবস্থাকে পছন্দসই অবস্থায় পরিবর্তন করতে পারে। উদাহরণস্বরূপ, আপনি আপনা
Kindly check this sentence `কুবারনেটসকে স্বয়ংক্রিয়ভাবে করতে পারেন।` . Specially the word `রিসোরস` & `কুবারনেটসকে`

2022-04-28 22:08 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +আপনি কুবারনেটিসকে নোডের একটি ক্লাস্টার প্রদান করেন যা এটি কন্টেইনারাইজড কাজ চালাতে ব্যবহার করতে পারে। আপনি কুবারনেটসকে বলুন প্রতিটি কন্টেইনারের কত CPU এবং মেমরি (RAM) প্রয়োজন। কুবারনেটিস আপনার সম্পদ
`কুবারনেটসকে` should not be here

2022-04-28 22:08 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +* মিডলওয়্যার (উদাহরণস্বরূপ, বার্তা বাস), ডেটা-প্রসেসিং ফ্রেমওয়ার্ক (উদাহরণস্বরূপ, স্পার্ক), ডাটাবেস (উদাহরণস্বরূপ, মাইএসকিউএল), ক্যাশে, বা ক্লাস্টার স্টোরেজ সিস্টেম (উদাহরণস্বরূপ, Ceph) এর মতো অ্যা
You can use `মাইএসকিউএল(MySql)` , `স্পার্ক(Spark)`

2022-04-28 22:08 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +## {{% heading "এরপর কি" %}}
You don't need to localize this one `{{% heading "whatsnext" %}}`

2022-04-28 22:08 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +*   কটাক্ষপাত করুন [Kubernetes Components](/docs/concepts/overview/components/)
Can you check this sentence? `কটাক্ষপাত করুন [Kubernetes Components]` . The sentence has not been properly localized

2022-04-28 22:08 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +*   প্রস্তুত [Get Started](/docs/setup/)?
Can you localize this one too properly `প্রস্তুত [Get Started]` ?

2022-04-29 05:30 UTC, ikramulkayes commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +বিষয়বস্তুর_প্রকার: ধারণা
from line 3 to 12 or from line 7 to 12, can you be more specific about which portion of the file should remain in English?

2022-04-29 17:09 UTC, mitul3737 requested changes

2022-04-29 17:09 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +বিষয়বস্তুর_প্রকার: ধারণা
@ikramulkayes from lines 6-12, you don't need to localize these lines.

2022-05-07 12:55 UTC, ikramulkayes commented
@mitul3737  check the updates.

2022-05-07 23:45 UTC, mitul3737 requested changes

2022-05-07 23:45 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +## কুবারনেটিস কি না
I think `কুবারনেটিস কি নয়` makes the title more suitable

2022-05-07 23:45 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +*   এটি দেখুন [কুবারনেটিস উপাদান](/docs/concepts/overview/components/)
I think `[কুবারনেটিস উপাদানটি] দেখুন` makes it a perfect sentence

2022-05-07 23:45 UTC, mitul3737 commented on content/bn/docs/concepts/overview/what-is-kubernetes.md
> +*   প্রস্তুত [এখানে থেকে শুরু করুন ](/docs/setup/)?
I think this `[শুরু করতে] প্রস্তুত আপনি?` makes more sense

2022-05-07 23:47 UTC, mitul3737 commented
@ikramulkayes look at the required changes to be made. Other than this, you have done a great job ☺️

2022-05-08 07:56 UTC, ikramulkayes commented
> @mitul3737 check the updates.

 check the updates.

2022-05-13 07:42 UTC, mitul3737 approved these changes
/lgtm

2022-05-13 07:43 UTC, merged