Create debug-statefulset.md
kubernetes/website pull request #33385
Opened 2022-05-01 17:40 UTC by ihuibin

Signed-off-by: bin.hui <bin.hui@daocloud.io>

2022-05-02 22:53 UTC, sftim requested changes
I don't think this page has been localized with enough care.

2022-05-02 22:53 UTC, sftim commented on content/zh/docs/tasks/debug/debug-application/debug-statefulset.md
> +title: Debug a StatefulSet
This title isn't localized, and the reviewer list looks wrong.

2022-05-02 22:53 UTC, sftim commented on content/zh/docs/tasks/debug/debug-application/debug-statefulset.md
> +如果你发现任何pod列表上的状态长时间处于“Unknown”或“Terminating”状态，参见[Deleting StatefulSet Pods](/docs/tasks/run-application/delete- StatefulSet /)查看如何处理它们的说明。
This link looks wrong.

2022-05-03 00:31 UTC, tengqm commented
@ihuibin Please refer to https://kubernetes.io/zh/docs/contribute/localization_zh/ for the style guide.

2022-05-23 16:33 UTC, Sea-n commented
It's duplicated with another PR, next time you can assign yourself to [umbrella issues](https://github.com/kubernetes/website/issues?q=is%3Aissue+zh+Umbrella) to avoid conflict.
- #33372

2022-05-28 08:19 UTC, tengqm commented
/close
closing as a dup.

2022-05-28 08:20 UTC, closed without merging