[ja] add Japanese translation for "Debugging DNS Resolution" page.
kubernetes/website pull request #33443
Opened 2022-05-04 10:18 UTC by skmkzyk

Let me add Japanese translation for "Debugging DNS Resolution" page.

2022-05-08 10:28 UTC, jihoon-seo commented
[Netlify build fails](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6272530d7e1bb70009fa3e20#L4050).
> content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md:21:1": failed to render shortcode "codenew": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/codenew.html:14:16": execute of template failed: template: shortcodes/codenew.html:14:16: executing "shortcodes/codenew.html" at <readFile $filename>: error calling readFile: stat /opt/build/repo/**content/ja/examples/admin/dns/dnsutils.yaml: no such file or directory**

Suggestion: copy `content/en/examples/admin/dns/dnsutils.yaml` to `content/ja/examples/admin/dns/dnsutils.yaml`,
and translate it into Japanese if needed.

@skmkzyk PTAL!

2022-05-11 13:39 UTC, nasa9084 requested changes

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +DNS エンドポイントが公開されていることを確認するには、`kubectl get endpoints`コマンドを使用します。
```suggestion
DNSエンドポイントが公開されていることを確認するには、`kubectl get endpoints`コマンドを使用します。
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +### DNSクエリは受信/処理されているか確認する {#are-dns-queries-being-received/processed?}
```suggestion
### DNSクエリーは受信/処理されているか確認する {#are-dns-queries-being-received/processed?}
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +クエリがCoreDNSによって受信されているかどうかを確認するには、CoreDNS構成(別名 Corefile)に`log`プラグインを追加します。
```suggestion
クエリーがCoreDNSによって受信されているかどうかを確認するには、CoreDNS構成(別名 Corefile)に`log`プラグインを追加します。
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +次に、いくつかのクエリを実行し、このドキュメントの上記のセクションごとにログを表示します。
```suggestion
次に、いくつかのクエリーを実行し、このドキュメントの上記のセクションごとにログを表示します。
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +CoreDNS Podがクエリを受信している場合は、ログにそれらが表示されます。
```suggestion
CoreDNS Podがクエリーを受信している場合は、ログにそれらが表示されます。
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +ログ内のクエリの例を次に示します:
```suggestion
ログ内のクエリーの例を次に示します:
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +名前空間を指定しないDNSクエリは、Podの名前空間に制限されます。
```suggestion
名前空間を指定しないDNSクエリーは、Podの名前空間に制限されます。
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +このクエリは、Podの名前空間に限定されます:
```suggestion
このクエリーは、Podの名前空間に限定されます:
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +このクエリは名前空間を指定します:
```suggestion
このクエリーは名前空間を指定します:
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +一部のLinuxディストリビューション(Ubuntuなど)は、既定でローカルDNSリゾルバ(`systemd-resolved`)を使用します。
```suggestion
一部のLinuxディストリビューション(Ubuntuなど)は、既定でローカルDNSリゾルバー(`systemd-resolved`)を使用します。
```

2022-05-11 13:39 UTC, nasa9084 commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +`systemd-resolved`は、`/etc/resolv.conf`をスタブファイルで移動して置き換え、アップストリームサーバで名前を解決するときに致命的な転送ループを引き起こす可能性があります。
```suggestion
`systemd-resolved`は、`/etc/resolv.conf`をスタブファイルで移動して置き換え、アップストリームサーバーで名前を解決するときに致命的な転送ループを引き起こす可能性があります。
```

2022-05-11 13:39 UTC, nasa9084 commented
/assign
/cc @bells17 @riita10069 

Can you file an issue for this PR?

2022-06-02 13:15 UTC, Sea-n reviewed
Please refer to [Netlify build log](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6272530d7e1bb70009fa3e20#L4050), feel free to `/unhold` yourself when the issue is solved.

/hold

2022-06-02 13:15 UTC, Sea-n commented on content/ja/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +{{< codenew file="admin/dns/dnsutils.yaml" >}}
Please copy `content/en/examples/admin/dns/dnsutils.yaml` to `content/ja/`, it caused build failure.

2022-06-15 14:08 UTC, Sea-n commented
Hey @skmkzyk,

Do you need help with fixing build error and addressing suggested changes? Please contact us on `#sig-docs` channel of [Kubernetes Slack](https://slack.k8s.io).

Feel free to `/reopen` this PR when you are ready to move forward.
/close

2022-06-15 14:08 UTC, closed without merging