[zh]Update content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
kubernetes/website pull request #33487
Opened 2022-05-05 10:53 UTC by nameYULI

2022-05-05 11:21 UTC, howieyuen requested changes

2022-05-05 11:21 UTC, howieyuen commented on content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
> +不要应用任何更改；只是输出将要执行的操作。
```suggestion
不会应用任何变更；只是输出将要执行的操作。
```

2022-05-05 11:21 UTC, howieyuen commented on content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
> +<td colspan="2">--apiserver-extra-args &lt;comma-separated 'key=value' pairs&gt;</td>
这里也翻译一下，下同
```suggestion
<td colspan="2">--apiserver-extra-args &lt;<!--comma-separated 'key=value' pairs-->逗号分割的 'key=value' 对&gt;</td>
```

2022-05-06 00:25 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_control-plane_all.md
> +不要应用任何更改；只是输出将要执行的操作。
Don't do something 在这个上下文中是祈使句，是对 kubeadm 的指示。所以，“不要应用任何变更” 更合适一些

2022-05-06 02:42 UTC, howieyuen commented
/approve

2022-05-06 03:41 UTC, tengqm commented
/lgtm

2022-05-06 03:43 UTC, merged