Update encrypt data
kubernetes/website pull request #33525
Opened 2022-05-06 10:09 UTC by fenggw-fnst

Work for #33477 task-7
/assign @tengqm
PTAL, thanks.

2022-05-06 10:10 UTC, sftim requested changes
Thank you. Please omit the changes to the English localization here, @fenggw-fnst 

It will be easiest to review this if the PR only touches **ONE** localization.

2022-05-07 01:14 UTC, fenggw-fnst commented
> Thank you. Please omit the changes to the English localization here, @fenggw-fnst
> 
> It will be easiest to review this if the PR only touches **ONE** localization.

Thanks for the review, done.

2022-05-07 01:42 UTC, fenggw-fnst commented
/retitle [zh] Update encrypt-data.md

2022-05-07 02:52 UTC, tengqm commented
/remove-language en

2022-05-07 03:00 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/encrypt-data.md
> +要禁用 rest 加密，请将 `identity` provider 作为配置中的第一个条目
```suggestion
要禁用静态加密，请将 `identity` provider 作为配置中的第一个条目
```

2022-05-07 03:04 UTC, tengqm commented
/label tide/merge-method-squash
/approve

2022-05-07 05:22 UTC, fenggw-fnst commented
Thanks for the review, I have updated the PR as suggested.

2022-05-07 13:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/encrypt-data.md
> +   以用新密钥加密所有现有的秘密
```suggestion
   以用新密钥加密所有现有的 Secret
```

2022-05-07 13:50 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/encrypt-data.md
> +并重新启动所有 `kube-apiserver` 进程。
```suggestion
要禁用静态加密，请将 `identity` provider
作为配置中的第一个条目并重新启动所有 `kube-apiserver` 进程。
```

2022-05-09 05:45 UTC, fenggw-fnst commented
Done, thanks.

2022-05-09 06:50 UTC, xichengliudui commented
/lgtm

2022-05-09 06:51 UTC, merged