[zh] Sync for tasks-10: change-pv-reclaim-policy.md and controller-manager-leader-migration.md
kubernetes/website pull request #33647
Opened 2022-05-13 08:50 UTC by fenggw-fnst

Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>

Work for https://github.com/kubernetes/website/issues/33477 tasks-10
/assign @tengqm
PTAL, thanks.

2022-05-13 09:31 UTC, howieyuen requested changes

2022-05-13 09:31 UTC, howieyuen commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +如果使用某种工具来部署和管理群集，请参阅对应工具和云驱动的文档以获取迁移的具体说明。
全文检索一下吧，“群集” -> “集群”，这应该是之前review遗漏的
```suggestion
如果使用某种工具来部署和管理集群，请参阅对应工具和云驱动的文档以获取迁移的具体说明。
```

2022-05-13 10:30 UTC, fenggw-fnst commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +如果使用某种工具来部署和管理群集，请参阅对应工具和云驱动的文档以获取迁移的具体说明。
谢谢，已进行了全文搜索，本PR所涉及的文件中只发现了这一处。

2022-05-13 10:30 UTC, fenggw-fnst commented on content/zh/docs/tasks/administer-cluster/controller-manager-leader-migration.md
> +如果使用某种工具来部署和管理群集，请参阅对应工具和云驱动的文档以获取迁移的具体说明。
已更新。

2022-05-13 13:53 UTC, howieyuen commented
/lgtm

2022-05-16 03:45 UTC, fenggw-fnst commented on content/zh/docs/tasks/administer-cluster/change-pv-reclaim-policy.md
> +    [字段](/zh/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1/#PersistentVolumeSpec)。
谢谢review，看起来 /content/zh/docs/reference/kubernetes-api/config-and-storage-resources 下只有一个 _index.md，英文的内容还未被中文本地化，因此这里先暂时改回链接向英文页面吧，等有了中文本地化页面后再更新。

2022-05-16 04:26 UTC, tengqm commented
/approve
/lgtm

2022-05-16 04:28 UTC, merged