[zh]translate kubernetes-api/workload-resources/priority-class-v1.md into chinese
kubernetes/website pull request #33753
Opened 2022-05-17 01:50 UTC by twilight0620

Fixes: https://github.com/kubernetes/website/issues/33646

Do not have chinese docs:  https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/priority-class-v1/

so need to translatekubernetes-api/workload-resources/priority-class-v1.md into Chinese

2022-05-17 03:32 UTC, howieyuen requested changes

2022-05-17 03:32 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +- **value** (int32)，必填
same as below
```suggestion
- **value** (int32)，必需
```

2022-05-17 03:32 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +  此优先级的值。这是 pod 在其 pod 规范中有此类名称时收到的实际优先级。
keep initials capitalized of k8s resource kind, same as below
```suggestion
  此优先级的值。这是 Pod 在其 Pod 规范中有此类名称时收到的实际优先级。
```

2022-05-17 03:32 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +<!-- - **apiVersion**: scheduling.k8s.io/v1 -->
译文与原文一致，可以删除原文对照，下同

2022-05-17 03:32 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +  Never、PreemptLowerPriority 之一。
```suggestion
  可选值：Never、PreemptLowerPriority。
```

2022-05-17 03:32 UTC, howieyuen commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +
remove extra empty lines, same as below

2022-05-17 03:47 UTC, tengqm commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +  此优先级的值。这是 pod 在其 pod 规范中有此类名称时收到的实际优先级。
spec 统一译为规约

2022-05-17 03:47 UTC, tengqm commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +<!-- ### `get` read the specified PriorityClass -->
这类 `<!--` 和 `-->` 都单独占一行，以便将来变更的时候逐行比较。下同。

2022-05-17 03:47 UTC, tengqm commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +200 (<a href="{{< ref "../workload-resources/priority-class-v1#PriorityClass" >}}">PriorityClass</a>): 成功
OK 不要翻译

2022-05-17 03:47 UTC, tengqm commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +401: 未授权
这种 HTTP 响应含义不要翻译。

```suggestion
401: Unauthorized
```

2022-05-17 03:47 UTC, tengqm commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +401: 未授权
同上，冒号后面的单词不要翻译

2022-05-17 06:44 UTC, twilight0620 commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +- **value** (int32)，必填
必填也行吧？我其他翻译的，comments让我写的必填。

2022-05-17 07:23 UTC, twilight0620 commented
I have modified the comments, thanks for reviewing.

2022-05-17 10:10 UTC, tengqm commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +- **value** (int32)，必填
还是统一为 “必需” 好些

2022-05-17 10:11 UTC, tengqm commented on content/zh/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +
类似这种空行，保留一个就好，剩下的删掉。下同。

2022-05-18 02:04 UTC, tengqm commented
Thanks.
/lgtm
/approve

2022-05-18 02:04 UTC, merged