[zh]Sync reference-10
kubernetes/website pull request #33797
Opened 2022-05-18 13:28 UTC by nameYULI

related issue: https://github.com/kubernetes/website/issues/33478
reference-10
```
145	76	content/en/docs/reference/command-line-tools-reference/feature-gates.md
```

2022-05-19 01:46 UTC, tengqm commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +  设置 `--runtime-config=storage.k8s.io/v1beta1/csistoragecapacities`。
```suggestion
  请设置 `--runtime-config=storage.k8s.io/v1beta1/csistoragecapacities`。
```

2022-05-19 03:51 UTC, tengqm commented
Good job.
/approve

2022-05-23 03:05 UTC, tengqm commented
/lgtm

2022-05-23 03:05 UTC, Sea-n requested changes

2022-05-23 03:05 UTC, Sea-n commented on content/zh/docs/reference/command-line-tools-reference/feature-gates.md
> +  更多详细信息，请参阅 [PersistentVolume 删除保护 finalizer](/zh/docs/concepts/storage/persistent-volumes/#persistentvolume-deletion-protection-finalizer)文档。
```suggestion
  更多详细信息，请参阅 [PersistentVolume 删除保护 finalizer](/zh/docs/concepts/storage/persistent-volumes/#persistentvolume-deletion-protection-finalizer) 文档。
```

2022-05-23 03:18 UTC, merged