[zh] Fix incorrect description for Service in endpoint-slices.md
kubernetes/website pull request #33826
Opened 2022-05-19 09:31 UTC by fenggw-fnst

Signed-off-by: Guangwen Feng <fenggw-fnst@fujitsu.com>

Inspired by [this comment](https://github.com/kubernetes/website/pull/33823#discussion_r876652479) and by the way modified the entire file.
/assign @tengqm
PTAL, thanks.

2022-05-19 09:45 UTC, howieyuen requested changes

2022-05-19 09:45 UTC, howieyuen commented on content/zh/docs/concepts/services-networking/endpoint-slices.md
> +由于任一 Service 的所有网络端点都保存在同一个 Endpoints 资源中，这类资源可能变得
这里可以考虑按照标点符合折行，这样渲染出来的结果不会有多余的空格

2022-05-19 12:58 UTC, tengqm commented
/approve

2022-05-20 03:59 UTC, fenggw-fnst commented on content/zh/docs/concepts/services-networking/endpoint-slices.md
> +由于任一 Service 的所有网络端点都保存在同一个 Endpoints 资源中，这类资源可能变得
谢谢 review，已经根据建议进行了全文修改以避免多余空格。

2022-05-20 12:58 UTC, tengqm commented
/lgtm

2022-05-20 12:59 UTC, merged