Fix a minor typo on expose-intro.html
kubernetes/website pull request #33880
Opened 2022-05-22 05:14 UTC by JohnTitor

Found a minor typo on expose-intro.html and fixed it.

2022-05-24 08:25 UTC, Arhell reviewed
/lgtm

2022-06-01 11:07 UTC, divya-mohan0209 requested changes
Slight nit, please address.

2022-06-01 11:07 UTC, divya-mohan0209 commented on content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>A Service routes traffic across a set of Pods. Services are the abstraction that allows pods to die and replicate in Kubernetes without impacting your application. Discovery and routing among
Slight nit.

```suggestion
				<p>A Service routes traffic across a set of Pods. Services are the abstraction that allows pods to die and replicate in Kubernetes without impacting your application. Discovery and routing among dependent Pods (such as the frontend and backend components in an application) are handled by Kubernetes Services.</p>
```

2022-06-01 21:58 UTC, JohnTitor commented on content/en/docs/tutorials/kubernetes-basics/expose/expose-intro.html
> +				<p>A Service routes traffic across a set of Pods. Services are the abstraction that allows pods to die and replicate in Kubernetes without impacting your application. Discovery and routing among
Addressed!

2022-06-02 04:09 UTC, divya-mohan0209 reviewed
Thank you @JohnTitor 
/lgtm
/approve

2022-06-02 04:11 UTC, merged