[zh] sync v1.24 kubeadm-24
kubernetes/website pull request #33897
Opened 2022-05-23 13:10 UTC by JarHMJ

related issues: #33479
```
92	18	content/en/docs/reference/setup-tools/kubeadm/kubeadm-init.md
6	11	content/en/docs/reference/setup-tools/kubeadm/implementation-details.md
18	11	content/en/docs/reference/setup-tools/kubeadm/kubeadm-config.md
```

2022-05-23 13:13 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-config.md
> +kubeadm 运行 `kubeadm init` and `kubeadm join` 时将使用此配置
```suggestion
kubeadm 运行 `kubeadm init` and `kubeadm join` 时将使用此配置。
```

2022-05-23 13:38 UTC, Sea-n commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +: 可用于创建集群时使用 ECDSA 证书而不是默认 RSA 算法。
nit: It's better to use `：` instead of `:`.

2022-05-23 13:38 UTC, Sea-n commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +当读取此 ConfigMap 时（在 `kubeadm join`、`kubeadm reset`、`kubeadm upgrade ...`期间），kubeadm 尝试首先使用未版本化的 ConfigMap 名称；
```suggestion
当 kubeadm 写入此 ConfigMap 时（在 `kubeadm init` 或 `kubeadm upgrade apply` 期间），kubeadm 遵守 `UnversionedKubeletConfigMap` 的值。
当读取此 ConfigMap 时（在 `kubeadm join`、`kubeadm reset`、`kubeadm upgrade ...` 期间），kubeadm 尝试首先使用未版本化的 ConfigMap 名称；
```

2022-05-23 13:38 UTC, Sea-n commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +设置 `UnversionedKubeletConfigMap` 为 `false` 是支持的，但**已废弃**的。
```suggestion
设置 `UnversionedKubeletConfigMap` 为 `false` 是支持的，但**已棄用**的。
```

2022-05-23 14:01 UTC, Sea-n requested changes

2022-05-23 14:01 UTC, Sea-n commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +如果将此标志设置为 `false`，则此 ConfigMap 的名称会包括 Kubernetes 的主要版本和次要版本（例如：`kubelet-config-{{< skew currentVersion >}`）。
This caused [Netlify build error](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/628b87d43402a900083f68a5#L77).

```suggestion
如果将此标志设置为 `false`，则此 ConfigMap 的名称会包括 Kubernetes 的主要版本和次要版本（例如：`kubelet-config-{{< skew currentVersion >>}`）。 
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +Kubeadm 确保 RBAC 规则适合你设置的值，用于读写 ConfigMap。
```suggestion
Kubeadm 会确保针对读写 ConfigMap 的 RBAC 规则适合于你设置的值。
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +Kubeadm 确保 RBAC 规则适合你设置的值，用于读写 ConfigMap。
```suggestion
Kubeadm 会确保用于读写 ConfigMap 的 RBAC 规则适合你设置的值。
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +当 kubeadm 写入此 ConfigMap时（在 `kubeadm init` 或 `kubeadm upgrade apply` 期间），kubeadm 遵守 `UnversionedKubeletConfigMap` 的值。
```suggestion
当 kubeadm 写入此 ConfigMap时（在 `kubeadm init` 或 `kubeadm upgrade apply` 期间），
kubeadm 根据 `UnversionedKubeletConfigMap` 的设置值来执行操作。
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +当读取此 ConfigMap 时（在 `kubeadm join`、`kubeadm reset`、`kubeadm upgrade ...`期间），kubeadm 尝试首先使用未版本化的 ConfigMap 名称；
```suggestion
当读取此 ConfigMap 时（在 `kubeadm join`、`kubeadm reset`、`kubeadm upgrade ...` 期间），
kubeadm 尝试首先使用无版本（后缀）的 ConfigMap 名称；
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +如果不成功，kubeadm 将回退到使用该 ConfigMap 的旧（版本化）名称。
```suggestion
如果不成功，kubeadm 将回退到使用该 ConfigMap 的旧（带版本号的）名称。
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +设置 `UnversionedKubeletConfigMap` 为 `false` 是支持的，但**已废弃**的。
```suggestion
设置 `UnversionedKubeletConfigMap` 为 `false` 是被支持的特性，但该特性**已被废弃**。
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +kubeadm 需要的所有默认 `k8s.gcr.io` 镜像都支持多种架构。
```suggestion
kubeadm 需要的所有默认 `k8s.gcr.io` 镜像都支持多种硬件体系结构。
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +例如，一个镜像可能在 `k8s.gcr.io/subpath/image` 有一个子路径，
```suggestion
例如，某镜像的子路径可能是 `k8s.gcr.io/subpath/image`，
```

2022-05-23 22:42 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +确保将镜像推送到 kubeadm 可以消费的自定义仓库的路径中，你必须：
```suggestion
确保将镜像推送到 kubeadm 可以使用的自定义仓库的路径中，你必须：
```

2022-05-23 22:45 UTC, tengqm commented on content/zh/docs/reference/setup-tools/kubeadm/kubeadm-init.md
> +: 可用于创建集群时使用 ECDSA 证书而不是默认 RSA 算法。
No. 这里的引号一定不能改为全角。参见： https://www.markdownguide.org/extended-syntax/#definition-lists

2022-05-24 02:16 UTC, tengqm commented
/lgtm
/approve

2022-05-24 02:17 UTC, merged