Create verify-signed-images.md
kubernetes/website pull request #33899
Opened 2022-05-23 15:28 UTC by ihuibin

Signed-off-by: bin.hui <bin.hui@daocloud.io>

2022-05-23 16:00 UTC, Sea-n requested changes
Tips: You can use machine translator to confirm what the original content means.

2022-05-24 01:37 UTC, ihuibin commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +. {{< /note >}}
OK，I translated it.

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +这些说明适用于 {{< skew currentVersion >}}。如果你想要检查不同版本完整的 Kubernetes 组件，请查看该 Kubernetes 版本的文档。
```suggestion
这些说明适用于 {{< skew currentVersion >}}。如果你想要检查其他版本的 Kubernetes 组件的完整性，
请查看对应 Kubernetes 版本的文档。
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +- `cosign` ([安装指导](https://docs.sigstore.dev/cosign/installation/))
```suggestion
- `cosign` ([安装指南](https://docs.sigstore.dev/cosign/installation/))
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +完整的镜像签名列表请参见链接 [Releases](/releases/download/).
```suggestion
完整的镜像签名列表请参见[发行版本](/releases/download/)。
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +`COSIGN_EXPERIMENTAL=1` 用于在 `KEYLESS` 模式对已签名的镜像进行验证。 想获取更多`KEYLESS`， 请参考
```suggestion
`COSIGN_EXPERIMENTAL=1` 用于对以 `KEYLESS` 模式签名的镜像进行验证。想要进一步了解 `KEYLESS`，请参考
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +. {{< /note >}}
```suggestion
[Keyless Signatures](https://github.com/sigstore/cosign/blob/main/KEYLESS.md#keyless-signatures)。
{{< /note >}}
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +验证所有控制平面组件镜像，请运行以下命令：
```suggestion
验证所有已签名的控制平面组件镜像，请运行以下命令：
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +验证所有控制平面组件镜像，请运行以下命令：
上面几行可以单独翻译，接下来的代码段直接复用英文的就好，不必注释一份再复制一份。

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +当你验证一个镜像，在你的 Pod 清单通过指定该镜像的杂凑值，像是此范例：`registry-url/image-name@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2`
```suggestion
当你完成某个镜像的验证时，可以在你的 Pod 清单通过摘要值来指定该镜像，例如：
`registry-url/image-name@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2`。
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +.
删除此行

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +## 使用准入控制器验证镜像
```suggestion
## 使用准入控制器验证镜像签名
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +），在部署时签名也可以使用
```suggestion
），也可以在部署时使用
```

2022-05-24 02:28 UTC, tengqm commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +控制器进行验证。如要使用 “cosigned”，下面是一些有帮助的资源：
```suggestion
控制器验证其签名。如要使用 “cosigned”，下面是一些有用的资源：
```

2022-05-24 02:55 UTC, tengqm commented
/label tide/merge-method-squash

2022-05-24 02:55 UTC, tengqm commented
/approve

2022-05-24 03:42 UTC, Sea-n commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +这些说明适用于 {{< skew currentVersion >}}。如果你想要检查其他版本的 Kubernetes 组件的完整性，
```suggestion
这些说明适用于 Kubernetes {{< skew currentVersion >}}。如果你想要检查其他版本的 Kubernetes 组件的完整性，
```

2022-05-24 03:42 UTC, Sea-n commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +控制器验证其签名。如要使用 “cosigned”，下面是一些有用的资源：
```suggestion
控制器验证其签名。如要使用 `cosigned`，下面是一些有用的资源：
```

2022-05-24 04:24 UTC, ihuibin commented
/assign 
Signed-off-by: bin.hui <bin.hui@daocloud.io>

2022-05-24 20:04 UTC, sftim commented
According to Prow, this PR has an invalid commit message.
/approve cancel

Once that's fixed, re-approval is fine.

2022-05-24 23:15 UTC, tengqm commented
Why we have so many commits in this PR? It could have been a very clean PR because it only touches a single, non-existent file.

2022-05-25 14:53 UTC, ihuibin commented on content/zh/docs/tasks/administer-cluster/verify-signed-images.md
> +.
好的

2022-05-26 06:11 UTC, tengqm commented
/label tide/merge-method-squash

2022-05-26 06:12 UTC, tengqm commented
/close
Please propose a new PR for this. This one is currently messy.

2022-05-26 06:13 UTC, closed without merging