Update scale-stateful-set.md
kubernetes/website pull request #33904
Opened 2022-05-23 17:02 UTC by ihuibin

Signed-off-by: bin.hui <bin.hui@daocloud.io>
 /assign  @tengqm

2022-05-23 17:12 UTC, Sea-n requested changes

2022-05-23 17:12 UTC, Sea-n commented on content/zh/docs/tasks/run-application/scale-stateful-set.md
> +### 扩缩容操作无法正常工作
It's "scaling down" instead of just "scaling", I don't see why `縮容` is inappropriate.

2022-05-24 01:39 UTC, ihuibin commented on content/zh/docs/tasks/run-application/scale-stateful-set.md
> +### 扩缩容操作无法正常工作
Sorry,I ignore  it (down).

2022-05-24 02:18 UTC, tengqm commented
/close

2022-05-24 02:19 UTC, closed without merging