Fixed the broken link with modification of lines
kubernetes/website pull request #33926
Opened 2022-05-24 21:07 UTC by NitishKumar06

Problem:
This is regarding this section on this page: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity

See the [design doc](https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md) for many more examples of pod affinity and anti-affinity.

The link to https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md is dead.

Solution:
This issue has been resolved by adding a simple link and enhancing the document line so that it can look beginner-friendly.

2022-05-24 21:09 UTC, NitishKumar06 commented
Hey @davidopp , @kevin-wangzefeng  Please go through this PR and feel free to suggest some changes if necessary.

2022-05-25 16:19 UTC, Shubham82 commented
Hi @NitishKumar06 
you  have to update the link to the below one:
https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/podaffinity.md

2022-05-26 09:32 UTC, NitishKumar06 commented
Hey @Shubham82 , Could you please tell me to which link this should be updated? This is already working fine.

2022-05-28 10:44 UTC, Shubham82 requested changes
@niteshseram Update this link https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md to https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/podaffinity.md

Actually, this https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md redirects to Design proposals that have been archived, and All design proposals are moved under the[ kubernetes/design-proposals-archive](https://github.com/kubernetes/design-proposals-archive/) repo.

2022-05-28 11:09 UTC, NitishKumar06 commented
Okay I'll do it .

On Sat, 28 May, 2022, 4:14 pm Shubham, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> @niteshseram <https://github.com/niteshseram> Update this link to
> https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/podaffinity.md
>
> Actually, this
> https://git.k8s.io/community/contributors/design-proposals/scheduling/podaffinity.md
> redirects to Design proposals that have been archived, and All design
> proposals are moved under the kubernetes/design-proposals-archive
> <https://github.com/kubernetes/design-proposals-archive/> repo.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/website/pull/33926#pullrequestreview-988480868>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUQQSLU7SH3KFF5JT56MXMLVMH2KFANCNFSM5W24LQEA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-05-29 07:17 UTC, tengqm commented
Is this a dup?

2022-05-31 02:53 UTC, reylejano commented
Duplicate of https://github.com/kubernetes/website/pull/34019
/close

2022-05-31 02:53 UTC, closed without merging

2022-10-11 06:57 UTC, NitishKumar06 commented
Update to which link? This link is working fine.

On Wed, 25 May, 2022, 9:50 pm Shubham, ***@***.***> wrote:

> Hi @NitishKumar06 <https://github.com/NitishKumar06>
> you have to update the link to the below one:
>
> https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/podaffinity.md
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/website/pull/33926#issuecomment-1137494927>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUQQSLTDA7HRGGQMZDJZHPLVLZHLFANCNFSM5W24LQEA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>