[zh] Remove reviewer for concepts and tutorials
kubernetes/website pull request #33967
Opened 2022-05-26 13:40 UTC by Sea-n

- Re-sync en content
- Remove reviewers from metadata
- Add link anchors
- Fix punctuation

2022-05-26 23:26 UTC, tengqm commented on content/zh/docs/concepts/cluster-administration/networking.md
> +3. Pod 和服务间通信：这由[服务](/zh/docs/concepts/services-networking/service/)涵盖。
```suggestion
3. Pod 和服务间通信：由[服务](/zh/docs/concepts/services-networking/service/)负责。
```

2022-05-26 23:26 UTC, tengqm commented on content/zh/docs/concepts/cluster-administration/networking.md
> +4. 外部和服务间通信：同样于[服务](/zh/docs/concepts/services-networking/service/)涵盖。
```suggestion
4. 外部和服务间通信：也由[服务](/zh/docs/concepts/services-networking/service/)负责。
```

2022-05-26 23:26 UTC, tengqm commented on content/zh/docs/concepts/cluster-administration/networking.md
> +如果你具有一个 “哑” 的 L2 网络，例如 “裸机” 环境中的简单交换机，则应该能够执行与上述 GCE 设置类似的操作。
个人认为引号前后不必加空格

```suggestion
如果你具有一个“哑”的 L2 网络，例如“裸机”环境中的简单交换机，则应该能够执行与上述 GCE 设置类似的操作。
```

2022-05-26 23:26 UTC, tengqm commented on content/zh/docs/concepts/cluster-administration/networking.md
> +网络和可与其他多网络插件，非常适合多集群网络中基于边缘的云原生工作负载。
```suggestion
网络且可与其他多网络插件组合，非常适合多集群网络中基于边缘的云原生工作负载。
```

2022-05-26 23:26 UTC, tengqm commented on content/zh/docs/concepts/cluster-administration/networking.md
> +该项目有一个特定的 Kubernetes 插件和文档 [ovn-kubernetes](https://github.com/openvswitch/ovn-kubernetes)。
```suggestion
该项目在 [ovn-kubernetes](https://github.com/openvswitch/ovn-kubernetes)
提供特定的 Kubernetes 插件和文档。
```

2022-05-26 23:26 UTC, tengqm commented on content/zh/docs/concepts/cluster-administration/networking.md
>  托管应用程序的弹性且易于使用的网络系统。
```suggestion
[Weave Net](https://www.weave.works/oss/net/) 为 Kubernetes
及其托管应用提供的、弹性且易用的网络系统。
```

2022-05-27 01:25 UTC, Sea-n commented on content/zh/docs/concepts/cluster-administration/networking.md
> +如果你具有一个 “哑” 的 L2 网络，例如 “裸机” 环境中的简单交换机，则应该能够执行与上述 GCE 设置类似的操作。
Got it.
How about this?
> 使用 “Kubernetes” 系統
> 使用“Kubernetes”系統

2022-05-27 02:14 UTC, tengqm commented
/lgtm

2022-05-27 07:52 UTC, howieyuen requested changes

2022-05-27 07:52 UTC, howieyuen commented on content/zh/docs/tutorials/configuration/configure-redis-using-configmap.md
> +这篇文档基于[使用 ConfigMap 来配置 Containers](/zh/docs/tasks/configure-pod-container/configure-pod-configmap/)
```suggestion
这篇文档基于[使用 ConfigMap 来配置容器](/zh/docs/tasks/configure-pod-container/configure-pod-configmap/)
```

2022-05-27 07:52 UTC, howieyuen commented on content/zh/docs/tutorials/configuration/configure-redis-using-configmap.md
> +* 此页面上显示的示例适用于 `kubectl` 1.14 和以上的版本。
```suggestion
* 此页面上显示的示例适用于 `kubectl` 1.14 及其以上的版本。
```

2022-05-27 07:52 UTC, howieyuen commented on content/zh/docs/tutorials/configuration/configure-redis-using-configmap.md
> +* 理解[使用 ConfigMap 来配置 Containers](/zh/docs/tasks/configure-pod-container/configure-pod-configmap/)。
```suggestion
* 理解[使用 ConfigMap 来配置容器](/zh/docs/tasks/configure-pod-container/configure-pod-configmap/)。
```

2022-05-27 09:38 UTC, tengqm commented on content/zh/docs/tutorials/configuration/configure-redis-using-configmap.md
> +* 此页面上显示的示例适用于 `kubectl` 1.14 和以上的版本。
这个倒不如原来的翻译更容易懂

2022-05-27 09:41 UTC, Sea-n commented on content/zh/docs/tutorials/configuration/configure-redis-using-configmap.md
> +* 此页面上显示的示例适用于 `kubectl` 1.14 和以上的版本。
@tengqm 我想知道這段是您會怎麼翻譯

我個人偏好「1.14 及以上的版本」

2022-05-27 10:06 UTC, howieyuen commented on content/zh/docs/tutorials/configuration/configure-redis-using-configmap.md
> +* 此页面上显示的示例适用于 `kubectl` 1.14 和以上的版本。
这是我的本意。。。多敲了个字

2022-05-27 10:26 UTC, Sea-n commented on content/zh/docs/tutorials/configuration/configure-redis-using-configmap.md
> +这篇文档基于[使用 ConfigMap 来配置容器](/zh/docs/tasks/configure-pod-container/configure-pod-configmap/)这个任务，
In English version: `Configure a Pod to Use a ConfigMap`
Our [localized page](https://kubernetes.io/zh/docs/tasks/configure-pod-container/configure-pod-configmap/): `配置 Pod 使用 ConfigMap`

I think original translator mis-understond the meaning.

2022-05-30 12:47 UTC, tengqm commented
/lgtm
/approve

2022-05-30 12:48 UTC, merged