Add controllinng access and authorization for pt-br
kubernetes/website pull request #34097
Opened 2022-06-01 13:21 UTC by jralmaraz

Submitting this PR to translate authorization and controlling-access pages to Brazilian Portuguese.

2022-06-02 06:36 UTC, Arhell reviewed
/assign @rikatz

2022-07-31 11:25 UTC, divya-mohan0209 commented
Hello @rikatz @stormqueen1990! It has been ~2 months since this PR was submitted. Would it be possible for y'all to provide an initial review? I know y'all are busy, however is there any way we can support you so that this PR is reviewed?

2022-07-31 13:46 UTC, stormqueen1990 commented
Hi @divya-mohan0209!

Sure thing, I'll take a look in the next few days.

/cc

2022-08-06 16:19 UTC, stormqueen1990 commented
Hi @jralmaraz, thank you very much for your contribution! 🎉 

I noticed that you created a single PR with two pages. Could you please split the page `content/pt-br/docs/reference/access-authn-authz/authorization.md` into a separate PR?
It is our guideline to create separate PRs for each page and its related resources.

I will start reviewing the `controlling-access.md` page soon.

Thanks in advance!

2022-08-10 13:11 UTC, jralmaraz commented
Hi @stormqueen1990 , thanks for picking this up and sorry for missing the guidelines, my bad.

I've split the files per PR as requested. Authorization translation PR was raised separately at:  https://github.com/kubernetes/website/pull/35854 

Let me know if there's any further action/fix, happy to address them.

Cheers.

2022-08-10 13:32 UTC, stormqueen1990 commented
> Hi @stormqueen1990 , thanks for picking this up and sorry for missing the guidelines, my bad.

No problem!

> I've split the files per PR as requested. Authorization translation PR was raised separately at: #35854

Thank you very much! I'll take a look at both PRs as soon as possible.

2022-08-11 00:32 UTC, stormqueen1990 requested changes
Hi @jralmaraz, thank you very much for your contribution! 🎉 

I found some places that need changes. Please let me know if you need any clarification.

2022-08-11 07:00 UTC, jralmaraz commented
> c818731

Hi @stormqueen1990 ! Thanks so much for the review and really sorry for the dummy mistakes, it seems like I left Brazil longer than I realize lol.

I have tried to address the gotchas with commit 
[c818731](https://github.com/kubernetes/website/pull/34097/commits/c818731ea677a1c069b37931e7967dfeb21c479e).

I'll wait for the preview deployment and go through the links and highlighted items later today or tomorrow.

Appreciate the help.

Cheers.

2022-08-11 10:13 UTC, jralmaraz commented
I'm also keeping the authorization links here to the pt-br page, if that's ok. Let me know.

2022-08-12 15:05 UTC, stormqueen1990 requested changes
Hi @jralmaraz!

Found some small things that still need to be changed. I also noticed some leftover occurrences of words missing accents ("voce", "publica", "apos").

2022-08-12 15:30 UTC, stormqueen1990 commented
/assign @edsoncelio

2022-08-16 10:00 UTC, jralmaraz commented
Thanks a lot @stormqueen1990 . I'll go through the findings and hopefully push the fixes this week!

2022-09-23 14:58 UTC, jralmaraz commented
I clicked by mistake on the re-request review item, my bad!!!

2022-10-08 21:15 UTC, stormqueen1990 commented
Hi @jralmaraz! It seems some items I had pointed out before have not been addressed, could you please take another look at those? I noticed there are still a few occurrences of words missing accents ("sao", "apos"). I think GitHub collapses the comments in the list, and that may be the reason they were left behind.

2022-10-10 07:02 UTC, jralmaraz commented on content/pt-br/docs/concepts/security/controlling-access.md
> +campos.
Thanks!

2022-10-10 07:04 UTC, jralmaraz commented
> Hi @jralmaraz! It seems some items I had pointed out before have not been addressed, could you please take another look at those?
> 
> I noticed there are still some occurrences of words missing accents ("sao", "apos", among others). I think GitHub collapses the comments in the list, and that may be the reason they were left behind.

Indeed @stormqueen1990 , thanks again! I've pushed some changes, let me know if they look ok now.

2022-10-25 07:52 UTC, jralmaraz commented on content/pt-br/docs/concepts/security/controlling-access.md
> +Quando uma requisição chega a API, ela passa por diversos estágios,
fixed on b0051ac2e1

2022-10-29 18:31 UTC, edsoncelio commented
Looks good to me, thank you @jralmaraz!
/lgtm

2022-11-04 00:45 UTC, stormqueen1990 commented
/approve

Thanks!

2022-11-04 00:46 UTC, merged