Spanish Glossary feature gate
kubernetes/website pull request #34214
Opened 2022-06-10 12:09 UTC by ManriqueGarcia

2022-06-10 16:30 UTC, NitishKumar06 commented
HI @ManriqueGarcia ! Please sign the CLA.

2022-06-10 16:42 UTC, electrocucaracha requested changes
As @NitishKumar06 mentioned before, you have to sign the CLA. Let me know if you have questions about that process.

2022-06-10 16:42 UTC, electrocucaracha commented on content/es/docs/reference/glossary/feature-gate.md
> +  Las feature gates, puertas de funciones en castellano, son un conjunto de pares clave=valor que  permiten habilitar o deshabilitar al usuario funciones experimentales en Kubernetes.
Me parece que está de más la traducción del término
```suggestion
  Las feature gates son un conjunto de pares clave-valor que permiten al usuario habilitar o deshabilitar funciones experimentales en Kubernetes.
```

2022-06-10 16:42 UTC, electrocucaracha commented on content/es/docs/reference/glossary/feature-gate.md
> +Las feature gates, puertas de funciones en castellano, son un conjunto de pares clave=valor que  permiten habilitar o deshabilitar     al usuario funciones experimentales en Kubernetes.
```suggestion
Las feature gates son un conjunto de pares clave-valor que permiten al usuario habilitar o deshabilitar funciones experimentales en Kubernetes.
```

2022-06-10 16:42 UTC, electrocucaracha commented on content/es/docs/reference/glossary/feature-gate.md
> +Las puertas de funciones están destinadas a cubrir el ciclo de vida de desarrollo de una función; no están destinadas a ser API a largo plazo. Como tal, se espera que queden en desuso y se eliminen d
```suggestion
Las feature gates están destinadas a cubrir el ciclo de vida de desarrollo de una función; no están destinadas a ser APIs a largo plazo. Como tal, se espera que queden en desuso y se eliminen después de que una característica se convierta en GA o se elimine.
```

2022-06-10 17:24 UTC, Sea-n commented
You need to add `re***ci@redhat.com` to [GitHub Setting > Email](https://github.com/settings/emails) and sign [the CLA agreement](https://github.com/kubernetes/website/pull/34214#issuecomment-1152291412).
Please let us know if there are any issue.

2022-06-10 18:03 UTC, Sea-n requested changes
Where did this translation come from?

I don't see `content/en/docs/reference/glossary/feature-gate.md` file in English.

And in your `full_link` metadata, the [cli-ref/feature-gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is totally different with this.

/hold
/retitle [es] Add Glossary feature gate

2022-06-10 20:07 UTC, electrocucaracha commented
> Where did this translation come from?
> 
> I don't see `content/en/docs/reference/glossary/feature-gate.md` file in English.
> 
> And in your `full_link` metadata, the [cli-ref/feature-gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is totally different with this.
> 
> /hold /retitle [es] Add Glossary feature gate

I saw the [_index.md file](https://github.com/kubernetes/website/blob/main/content/es/docs/reference/command-line-tools-reference/_index.md) has an extra `toc-hide: true` line which maybe is affecting the rendering. @ManriqueGarcia can you remove that extra line.

2022-06-11 10:26 UTC, ManriqueGarcia commented
> toc-hide: true

I only see one line with `toc-hide:true` in the file should the whole line be removed?

2022-06-11 13:08 UTC, sftim commented
/retitle [es] Add Glossary entry for feature gate

/hold
This is not localizing an existing English file, and for that reason we should not merge it.

2022-06-13 07:47 UTC, ManriqueGarcia commented
> /retitle [es] Add Glossary entry for feature gate
> 
> /hold This is not localizing an existing English file, and for that reason we should not merge it.

so, do I create the entry also in English?

2022-08-03 01:40 UTC, Sea-n commented
Hey @ManriqueGarcia,

Thanks for purposing this PR, but our policy doesn't want pages diverged in each language.

If you think this page is good (and so do I), please open a new PR to add this page in English first.

This intention is really good, but I'm afraid that I have to close this.
/close

2022-08-03 01:40 UTC, closed without merging