Update blog post to include change in paths for kernel version 4.14
kubernetes/website pull request #34236
Opened 2022-06-11 09:31 UTC by taniaduggal

Fix #32011

2022-06-11 09:45 UTC, Sea-n commented
Please don't take steal others' hard work to be your PR, it's very unethical.
- #32011

/hold

2022-06-11 13:06 UTC, sftim commented
PRs to fix issues are welcome.

This doesn't look to me like “stealing” - open source is a thing. However, @taniaduggal, you could have been more clear that you were building on existing work.

@taniaduggal it is best to see if there is already an open PR and, if so, to try to liaise with the person who already opened that one.

/hold cancel

2022-06-12 15:52 UTC, taniaduggal commented
Hey @sftim , that user is inactive from long time. That's why , i raised a PR since I believed the changes were crucial. 
Please  review at my pr.
/assign @sftim

2022-06-12 15:54 UTC, taniaduggal commented
Hey @sftim , that user is inactive from long time . That's why, i raised a PR 
since I believed changes were crucial .
Please review at my PR.

2022-06-12 15:55 UTC, taniaduggal commented
> Hey @sftim , that user is inactive from long time. That's why , i raised a PR since I believed the changes were crucial. Please review at my pr. /assign @sftim

2022-06-12 15:56 UTC, taniaduggal commented
> Hey @sftim , that user is inactive from long time. That's why , i raised a PR since I believed the changes were crucial. Please review at my pr.

2022-06-12 15:56 UTC, taniaduggal commented
> Hey @sftim , that user is inactive from long time. That's why , i raised a PR since I believed the changes were crucial. Please review at my pr.

2022-06-12 16:22 UTC, sftim requested changes
Thanks for opening this pull request @taniaduggal 

I'm afraid that as things stand we couldn't accept this change

- PRs that change blog articles more than 1 year old should include an explanation about why we should make the change (the default policy is not to amend articles over a year old)
- this PR as I see it has a bunch of unrelated changes, and I'm afraid we'd prefer not to accept those
- the author, Yonkun Gui, might have a view on this amendment. Please mention in your PR description whether you have / haven't tried to get in touch with the original author

2022-06-12 16:22 UTC, sftim commented on content/en/blog/_posts/2019-03-29-kube-proxy-subtleties-debugging-an-intermittent-connection-resets.md
> +You must update the command in the DaemonSet below to use the correct path.
This seems to be the only / key change. @taniaduggal are you using an editor that automatically reformats Markdown?

We'd prefer to only see the relevant changes. To do that, you could copy this section and redo your PR from the _main_ branch. When you come to commit your work, use `git add -p` or the equivalent IDE tool to let you select which changes to commit.

2022-06-13 09:22 UTC, taniaduggal commented
Hey @sftim .I made only these changes which you suggested . You once have to check the original file .
and also i am beginner to open source . Any suggesstions are welcome .

2022-06-17 04:38 UTC, zacharysarah commented
/close

2022-06-17 04:38 UTC, closed without merging