Removing the overlapping text (project) from CNCF Logo
kubernetes/website pull request #34335
Opened 2022-06-16 18:46 UTC by UtkarshMishra12

***I have removed the overlapping text from CNCF Logo, by changing the CSS of the element,***
![Correct](https://user-images.githubusercontent.com/67385503/174143077-40b7f1fb-8a4c-47f3-9c07-b566639e2f6e.png)
![Error](https://user-images.githubusercontent.com/67385503/174143082-6ba59573-013c-43f5-b26f-a94e184d7961.png)

2022-06-16 18:58 UTC, NitishKumar06 commented
/lgtm

2022-06-16 21:45 UTC, Sea-n commented
Hey @UtkarshMishra12,

If I remember correct, this bug have a issue number, could you add `Fixes #34567` in your PR description?

And it's hard to find where did you changed, please attach this two URLs in your PR description too.
- https://deploy-preview-34335--kubernetes-io-main-staging.netlify.app/#cncf
- https://kubernetes.io/#cncf

2022-06-16 22:56 UTC, sftim requested changes
@UtkarshMishra12 thank you for proposing a fix.

/area web-development

It's better to change the CSS (Sass-flavored) inside `/assets` than to hard-code it into the HTML. Doubly so if setting layout attributes such as `position: absolute;`.

As it stands, I'm afraid that we shouldn't make this change.
/lgtm cancel

I'd welcome a different change that puts the CSS separate from the HTML in `/layouts`, and especially with evidence that the fix adapts to different viewport sizes, device sizes, DPIs, etc.

2022-06-24 03:08 UTC, reylejano commented
Hi @UtkarshMishra12 , I'm the PR Wrangler for this week.
I'm closing this PR and agree with Tim's [comment](https://github.com/kubernetes/website/pull/34335#pullrequestreview-1009826934) that the change in this PR should not be made as it is.
Feel free to open a new PR to change the CSS as suggested in Tim's [comment](https://github.com/kubernetes/website/pull/34335#pullrequestreview-1009826934)
/close

2022-06-24 03:08 UTC, closed without merging