[zh] Update /releases/_index.md
kubernetes/website pull request #34406
Opened 2022-06-19 18:40 UTC by yanrongshi

2022-06-19 18:42 UTC, yanrongshi commented
@howieyuen

2022-06-19 23:37 UTC, Sea-n commented
You have opened four PR for very small (and un-noticeable for current version) sync. Could you merge them into one?
- #34406
- #34407
- #34408
- #34409

Futher more, it's better to fix format errors and make sentences more fluent.

2022-06-20 02:37 UTC, howieyuen commented
see the [deploy log](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/62af6da775616800098c0c5f#L76):
```
2:41:36 AM: Error: Error building site: "/opt/build/repo/content/zh-cn/releases/_index.md:16:122": failed to extract shortcode: template for shortcode "currentVersionAddMinor" not found
```

2022-06-20 03:30 UTC, howieyuen commented
please squash commits into one
/label tide/merge-method-squash

2022-06-20 03:32 UTC, howieyuen requested changes

2022-06-20 03:32 UTC, howieyuen commented on content/zh-cn/releases/_index.md
> +Kubernetes 项目维护最近三个次要版本（{{< skew currentVersion >}}、{{< currentVersionAddMinor -1 >}}、{{< currentVersionAddMinor -2 >}}）的发布分支。
```suggestion
Kubernetes 项目维护最近三个次要版本（{{< skew currentVersion >}}、{{< skew currentVersionAddMinor -1 >}}、{{< skew currentVersionAddMinor -2 >}}）的发布分支。
```

2022-06-20 13:43 UTC, tengqm commented
/lgtm
/approve

2022-06-20 13:50 UTC, merged