[zh-cn]Add 2022-05-13-grpc-probes-in-beta.md chinese version
kubernetes/website pull request #34461
Opened 2022-06-22 02:36 UTC by zhangxyjlu

fixed: #34437
Translate Chinese version for blog/2022/05/13/grpc-probes-in-beta.md

2022-06-22 10:01 UTC, Sea-n reviewed
Thanks! Here is some nitpicks, please take a look.

2022-06-23 02:02 UTC, zhangxyjlu commented
I've revised all your reviews, thanks@[Sea-n](https://github.com/Sea-n)

2022-06-23 03:35 UTC, howieyuen requested changes

2022-06-23 03:35 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +在博文[在 Kubernetes 上对 gRPC 服务器进行健康检查](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)中，
```suggestion
在博文[在 Kubernetes 上对 gRPC 服务器进行健康检查](/zh-cn/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)中，
```

2022-06-23 03:35 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +的 3,626 个 Dockerfile 文件和 6,621 个 yaml 文件（在撰写本文时）。
```suggestion
的 [3,626 个 Dockerfile 文件](https://github.com/search?l=Dockerfile&q=grpc_health_probe&type=code)和
[6,621 个 yaml 文件](https://github.com/search?l=YAML&q=grpc_health_probe&type=Code)（在撰写本文时）。
```

2022-06-23 03:35 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +有了原生 gRPC 支持，你不需要下载和携带 `10MB` 的额外可执行文件。Exec 探针通常比 gRPC 调用慢，
```suggestion
有了原生 gRPC 支持，你不需要在镜像中下载和携带 `10MB` 的额外可执行文件。
Exec 探针通常比 gRPC 调用慢，因为它们需要实例化一个新进程来运行可执行文件。
当 Pod 在最大资源下运行并且在实例化新进程时遇到困难时，它还使得对边界情况的检查变得不那么智能。
```

2022-06-23 03:35 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +不过有一些限制。因为为探针配置客户端证书很难，所以不支持需要客户端身份验证的服务。
```suggestion
不过有一些限制。由于为探针配置客户端证书很难，因此不支持依赖客户端身份验证的服务。
```

2022-06-23 03:35 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +你现在可以尝试这个功能。要尝试原生 gRPC 探针，你可以在启用 `GRPCContainerProbe` 特性门的情况下自己启动
```suggestion
你现在可以尝试这个功能。要尝试原生 gRPC 探针，你可以自己启动一个启用了
`GRPCContainerProbe` 特性门控的 Kubernetes 集群，这有许多[工具可用](/zh-cn/docs/tasks/tools/)。
```

2022-06-23 03:35 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +由于特性门 `GRPCContainerProbe` 在 1.24 版本中是默认启用的，因此许多供应商将提供开箱即用的此功能。
术语翻译推荐：https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD
```suggestion
由于特性门控 `GRPCContainerProbe` 在 1.24 版本中是默认启用的，因此许多供应商将提供开箱即用的此功能。
```

2022-06-23 04:29 UTC, zhangxyjlu commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +在博文[在 Kubernetes 上对 gRPC 服务器进行健康检查](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)中，
此处添加 `/zh` 或 `/zh-cn` 都不能链接到博客的正确位置。

2022-06-23 06:14 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +在博文[在 Kubernetes 上对 gRPC 服务器进行健康检查](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)中，
这是因为这18年的这篇博客，还没被翻译。。。

2022-06-23 06:20 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +在博文[在 Kubernetes 上对 gRPC 服务器进行健康检查](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)中，
我检查了一下，是18年的这篇博客的标题翻译后，链接成了中文：https://kubernetes.io/zh-cn/blog/2018/10/01/%E5%9C%A8-kubernetes-%E4%B8%8A%E5%AF%B9-grpc-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%BF%9B%E8%A1%8C%E5%81%A5%E5%BA%B7%E6%A3%80%E6%9F%A5/
需要在此博客的原文头部加个参数：
```
slug: health-checking-grpc-servers-on-kubernetes
```

2022-06-23 06:38 UTC, zhangxyjlu commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +在博文[在 Kubernetes 上对 gRPC 服务器进行健康检查](/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/)中，
确实是这个问题，我已修改了。多谢指导。

2022-06-24 01:38 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +Kubernetes 上这种新的内置 gRPC 健康探测，使得通过 gRPC 实现健康检查比依赖使用单独 `exec`
```suggestion
Kubernetes 上这种新的内置 gRPC 健康探测，使得通过 gRPC 实现健康检查比依赖使用额外的 `exec`
```

2022-06-24 01:38 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +探测的旧方法更容易。通过阅读官方
```suggestion
探测的旧方法更容易。请阅读官方
```

2022-06-24 02:14 UTC, zhangxyjlu commented
I've revised all your reviews, thanks@[tengqm](https://github.com/tengqm)

2022-06-24 02:41 UTC, howieyuen commented
/lgtm

2022-06-24 03:39 UTC, tengqm commented
/approve

2022-06-24 03:41 UTC, merged