[zh-cn] update /create-cluster-kubeadm.md
kubernetes/website pull request #34540
Opened 2022-06-23 18:12 UTC by yanrongshi

2022-06-23 22:33 UTC, jihoon-seo commented
/retitle [zh-cn] Update `setup/_index.md`

2022-06-24 00:12 UTC, jihoon-seo commented
The commit message is not mached with the change this PR suggests.

2022-06-24 00:25 UTC, yanrongshi commented
> 提交消息与此 PR 建议的更改不匹配。

what's you mean? Can you be more specific? I'm new here. Not really. Thank you！

2022-06-24 01:29 UTC, jihoon-seo commented
The commit message is `[zh-cn] update /create-cluster-kubeadm.md` (see [here](https://github.com/kubernetes/website/pull/34540/commits)),
but this PR suggests the change of `content/zh-cn/docs/setup/_index.md` file, not `create-cluster-kubeadm.md` file.

So it would be great to change the commit message to, for example,
```
[zh-cn] Update `setup/_index.md`
```

2022-06-24 02:50 UTC, howieyuen requested changes

2022-06-24 02:50 UTC, howieyuen commented on content/zh-cn/docs/setup/_index.md
> +<!-- Several [Kubernetes components](/docs/concepts/overview/components/) such as `kube-apiserver` or `kube-proxy` can also be
```suggestion
<!-- 
Several [Kubernetes components](/docs/concepts/overview/components/) such as `kube-apiserver` or `kube-proxy` can also be
```

2022-06-24 02:50 UTC, howieyuen commented on content/zh-cn/docs/setup/_index.md
> +deployed as [container images](/releases/download/#container-images) within the cluster. -->
```suggestion
deployed as [container images](/releases/download/#container-images) within the cluster. 
-->
```

2022-06-24 02:50 UTC, howieyuen commented on content/zh-cn/docs/setup/_index.md
> +<!-- It is **recommended** to run Kubernetes components as container images wherever
```suggestion
<!-- 
It is **recommended** to run Kubernetes components as container images wherever
```

2022-06-24 02:50 UTC, howieyuen commented on content/zh-cn/docs/setup/_index.md
> +Components that run containers - notably, the kubelet - can't be included in this category. -->
```suggestion
Components that run containers - notably, the kubelet - can't be included in this category. 
-->
```

2022-06-24 02:50 UTC, howieyuen commented on content/zh-cn/docs/setup/_index.md
> +但是运行容器的组件——尤其是 kubelet，不能包含在这个类别中。
```suggestion
但是运行容器的组件 —— 尤其是 kubelet，不能包含在这个类别中。
```

2022-06-24 02:52 UTC, jihoon-seo commented
/label tide/merge-method-squash

2022-06-24 03:01 UTC, tengqm commented
Please squash your PR into one commit.

2022-06-24 12:20 UTC, closed without merging