[zh] Migrating telemetry and security agents from dockershim
kubernetes/website pull request #34571
Opened 2022-06-24 18:22 UTC by X723166587

Apply PR #31607 corrections to Chinese content.

2022-06-25 03:05 UTC, tengqm reviewed
please squash your commits.

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +`docker-container-stats` 监视器不要使用 Docker Engine 之外的运行时。
```suggestion
不要为 `docker-container-stats` 监视器使用 Docker Engine 之外的运行时。
```

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行，留一个

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行，留一个

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行，留一个

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除空行310

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +
删除此空行

2022-06-25 03:05 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
删除此空行

2022-06-26 04:19 UTC, Sea-n reviewed
Looks good to me, just a few nitpick.

2022-06-26 04:19 UTC, Sea-n commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +Flame 不支持 Docker 以外的容器运行时，具体可见[https://github.com/yahoo/kubectl-flame/issues/51](https://github.com/yahoo/kubectl-flame/issues/51)
```suggestion
Flame 不支持 Docker 以外的容器运行时，具体可见 [https://github.com/yahoo/kubectl-flame/issues/51](https://github.com/yahoo/kubectl-flame/issues/51)
```

2022-06-26 04:19 UTC, Sea-n commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +`kubelet-stats` 监视器此前已被弃用，现支持 `kubelet-metrics` 。
```suggestion
`kubelet-stats` 监视器此前已被弃用，现支持 `kubelet-metrics`。
```

2022-06-26 08:23 UTC, tengqm commented
/approve
/hold
Good to go once commits are squashed.

2022-06-27 03:32 UTC, howieyuen requested changes

2022-06-27 03:32 UTC, howieyuen commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +`kubelet-stats` 监视器此前已被弃用，现支持 `kubelet-metrics`。
```suggestion
`kubelet-stats` 监视器此前已被供应商所弃用，现支持 `kubelet-metrics`。
```

2022-06-27 03:32 UTC, howieyuen commented on content/zh-cn/docs/tasks/administer-cluster/migrating-from-dockershim/migrating-telemetry-and-security-agents.md
> +收集的指标会发生变化。具体请查看你的告警规则和仪表板。
```suggestion
收集的指标会发生变化。具体请查看你的告警规则和仪表盘。
```

2022-07-02 08:09 UTC, Sea-n commented
Hey @X723166587,

Please squash your changes into one commit.
You need to download local git client to do it.

2022-07-05 02:32 UTC, howieyuen approved these changes
/lgtm

2022-07-05 02:43 UTC, howieyuen commented
/hold cancel

2022-07-05 02:44 UTC, merged

2022-09-25 07:30 UTC, Sea-n commented
/remove-language en