[zh-cn] Resync authentication page
kubernetes/website pull request #34613
Opened 2022-06-26 02:26 UTC by tengqm

2022-06-26 03:16 UTC, Sea-n commented on content/zh-cn/docs/reference/access-authn-authz/authentication.md
> +警告：*不要* 在不同的上下文中复用 CA 证书，除非你清楚这样做的风险是什么以及应如何保护
```suggestion
警告：**不要**在不同的上下文中复用 CA 证书，除非你清楚这样做的风险是什么以及应如何保护
```

2022-06-26 03:16 UTC, Sea-n commented on content/zh-cn/docs/reference/access-authn-authz/authentication.md
> +* API 服务器使用[Webhook 令牌身份认证组件](#webhook-token-authentication)向外部服务发出
```suggestion
* API 服务器使用 [Webhook 令牌身份认证组件](#webhook-token-authentication)向外部服务发出
```

2022-06-26 03:16 UTC, Sea-n commented on content/zh-cn/docs/reference/access-authn-authz/authentication.md
>  ##### 选项一 - OIDC 身份认证组件
```suggestion
##### 选项一 - OIDC 身份认证组件   {#option-1-oidc-authenticator}
```

2022-06-26 03:16 UTC, Sea-n commented on content/zh-cn/docs/reference/access-authn-authz/authentication.md
>  ##### 选项一 - OIDC 身份认证组件
And `##### 选项二 - 使用 `--token` 选项   {#option-2-use-the-token-option}` missing anchor too.

2022-06-26 03:39 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authentication.md
>  ##### 选项一 - OIDC 身份认证组件
These anchors are for the convenience for reference. If we are sure that no other page may reference a (sub)section, adding anchors can be optional.

2022-06-26 03:54 UTC, Sea-n commented
Thanks for the explanation!
/lgtm

2022-06-27 03:44 UTC, howieyuen requested changes

2022-06-27 03:44 UTC, howieyuen commented on content/zh-cn/docs/reference/access-authn-authz/authentication.md
>  ##### 选项一 - OIDC 身份认证组件
这里破折号和汉字“一”连在一起看着有点迷惑，改成冒号含义不变；选项二，也可以这样修改
```suggestion
##### 选项一：OIDC 身份认证组件
```

2022-06-27 03:48 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authentication.md
>  ##### 选项一 - OIDC 身份认证组件
OK. Good suggestion.

2022-06-27 06:28 UTC, howieyuen commented
/approve
/lgtm

2022-06-27 06:30 UTC, merged