[zh-cn] Translate the endpoints-v1 API reference
kubernetes/website pull request #34641
Opened 2022-06-27 08:54 UTC by shixiuguo

#34635

2022-06-27 09:46 UTC, windsonsea requested changes

2022-06-27 09:46 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +
一个空行够了，删除多余的一行

2022-06-27 09:46 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  标准对象的元数据。更多信息： https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
```suggestion
  标准的对象元数据。更多信息：
  https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
```

2022-06-27 09:46 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  地址根据它们共享的IP被放入子集。
```suggestion
  地址根据它们共享的 IP 被放入子集。
```
通常中英文之间留个空格，比较美观

2022-06-27 09:46 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  具有多个端口的单个地址，其中一些端口已就绪，而另一些端口未就绪（因为它们来自不同的容器），将导致地址显示在不同端口的不同子集中。同一子集中的地址和NotReadyAddress中都不会显示任何地址。
```suggestion
  具有多个端口的单个地址，其中一些端口已就绪，而另一些端口未就绪（因为它们来自不同的容器），
  这将导致地址显示在不同端口的不同子集中。同一子集中的地址和 NotReadyAddress 中都不会显示任何地址。
```
通常 2-3 段一节，重新 <!-- -->，现在这样校对很痛苦

2022-06-27 09:59 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +Endpoints 是实现实际服务的端点的集合。 举例:
@windsonsea 这个情况很特殊，Endpoints 只能是复数形式的。API 就是这么定义的。

2022-06-27 11:20 UTC, tengqm reviewed
请分段翻译。现在这个很难review.

2022-06-27 11:20 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  *EndpointSubset 是一组具有公共端口集的地址。扩展的端点集是地址x端口的笛卡尔乘积。例如，给定:
这一行和 113 行的星号删除吧。

2022-06-27 11:20 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    }
这段用三个反引号括起来，不然输出很难看

2022-06-27 11:20 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      b: [ 10.10.1.1:309, 10.10.2.2:309 ]*
这两行用三个反引号括起来

2022-06-27 12:05 UTC, shixiuguo commented
> 请分段翻译。现在这个很难review.

好的，我改一下

2022-07-17 12:51 UTC, tengqm commented
@shixiuguo Still working on this? 20 days passed.

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  `Name: "mysvc",
````suggestion
  ```
  Name: "mysvc",
````

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> + ]`
````suggestion
 ]
 ```
````

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  所有端点的集合是所有子集的并集。
```suggestion
  所有端点的集合是所有 subsets 的并集。
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  地址根据它们共享的IP被放入子集。
```suggestion
  地址根据它们共享的 IP 被放入子集。
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  具有多个端口的单个地址，其中一些端口已就绪，而另一些端口未就绪（因为它们来自不同的容器），将导致地址显示在不同端口的不同子集中。同一子集中的地址和NotReadyAddress中都不会显示任何地址。
```suggestion
  对于具有多个端口的单个地址，如果其中一些端口已就绪，而另一些端口未就绪（因为它们来自不同的容器），
  将导致地址显示在不同端口的不同子集中。同一子集中的 addresses 和 notReadyAddress 中都不会显示任何地址。
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    `{
````suggestion
    ```
    {
````

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      b: [ 10.10.1.1:309, 10.10.2.2:309 ]`
````suggestion
  最终的端点集可以看作：
  ```
      a: [ 10.10.1.1:8675, 10.10.2.2:8675 ],
      b: [ 10.10.1.1:309, 10.10.2.2:309 ]
  ```
````

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      这可用于确定节点的本地端点。
```suggestion
      此字段可用于确定节点的本地端点。
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +       对提供端点的对象的引用。
```suggestion
      对提供端点的对象的引用。
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    提供相关端口但由于尚未完成启动、最近未通过就绪性检查或最近未通过活动性检查而当前未标记为就绪的IP地址。
翻译不彻底

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      此外，某些 kubernetes 组件，如 kube proxy，还没有准备好支持 IPv6。
同前。

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    -->
```suggestion

      <!--
      The Hostname of this endpoint
      -->
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    -->
```suggestion

      <!--
      Optional: Node hosting this endpoint. This can be used to determine endpoints local to a node.
      -->
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    -->
```suggestion
      <!--
      Reference to object providing the endpoint.
      -->
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    <!--
199 前面加空行

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    *EndpointAddress 是描述单个 IP 地址的元组。*
不要用单星号，用双星号。

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    -->
```suggestion

      <!--
      The IP protocol for this port. Must be UDP, TCP, or SCTP. Default is TCP.
      -->
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      此端口的IP协议。必须是UDP、TCP或SCTP。默认值为TCP。
```suggestion
      此端口的 IP 协议。必须是 UDP、TCP 或 SCTP。默认值为 TCP。  
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    <!--
```suggestion
      <!--
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    -->
```suggestion
      -->
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      这必须与相应 ServicePort 中的 “name” 字段匹配。必须是 DNS_LABEL 。
```suggestion
      此字段必须与相应 servicePort 中的 “name” 字段匹配。必须是 DNS_LABEL。
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      非标准协议应使用前缀名称，如 mycompany.com/my-custom-protocol。
```suggestion
      非标准协议应使用带前缀名称，如 mycompany.com/my-custom-protocol。      
```

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +
额外的空行不必要

2022-07-22 09:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +- **name** (*in path*): string, 必需
```suggestion
- **name** (**路径参数**): string, 必需
```

2022-07-25 03:02 UTC, tengqm commented
@shixiuguo Ping.

2022-07-27 03:56 UTC, tengqm commented
@shixiuguo Ping.

2022-07-27 05:06 UTC, windsonsea commented
If still no response till this weekend, I will take it over. @shixiuguo

2022-07-27 07:25 UTC, mengjiao-liu commented
Please squash commits to one.
Follow the requirements below for `Squash`. See [Kubernetes contributors guide](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md#squash-commits) for more details.

2022-07-28 01:58 UTC, tengqm commented
/label tide/merge-method-squash

2022-07-28 01:59 UTC, tengqm commented
preview doesn't look right, some empty lines should be added.

https://deploy-preview-34641--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1/

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    - **subsets.addresses.ip** (string), 必需
二级、三级列表条目前面必须加空行，不然会被理解为代码段。下同。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      端点主机名称。
142 前面加空行，不然会被 markdown 理解为代码段！！！

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      可选：承载此端点的节点。
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      对提供端点的对象的引用。
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    提供相关端口但由于尚未完成启动、最近未通过就绪性检查或最近未通过活动性检查而当前未标记为就绪的 IP 地址。
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    *EndpointAddress 是描述单个 IP 地址的元组。*
改掉单星号

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    - **subsets.notReadyAddresses.ip** (string), 必需
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +       端点主机名称。
一定不要随意加缩进！！
187 行前面加空行。

```suggestion

      端点主机名称。
```

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      可选：承载此端点的节点。
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      对提供端点的对象的引用。
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    相关IP地址上可用的端口号。
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +    <a name="EndpointPort"></a>
同前。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      此端口的 IP 协议。必须是 UDP、TCP 或S CTP。默认值为 TCP。
```suggestion
      此端口的 IP 协议。必须是 UDP、TCP 或 SCTP。默认值为 TCP。  
```

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      端口的名称。
241 前面加空行。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      端口的应用程序协议。
250 前面加空行

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +      非标准协议应使用带前缀名称，如 mycompany.com/my-custom-protocol。
```suggestion
      非标准协议应使用带前缀名称，如 `mycompany.com/my-custom-protocol`。      
```

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +- **name** (*路径参数*): string, 必需
```suggestion
- **name** (**路径参数**)：string，必需
```

后面依次修改。

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +  端点名称
```suggestion
  Endpoints 的名称。
```

2022-07-28 08:52 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/endpoints-v1.md
> +#### 应答
```suggestion
#### 响应
```

2022-07-29 07:52 UTC, tengqm commented
/retitle [zh-cn] Translate the endpoints-v1 API reference

2022-08-01 11:55 UTC, tengqm commented
@shixiuguo If you are really too busy to push this forward, you can let someone else to take it over. It is fine for someone else to continue a stalled work. This is one of the oldest PRs we have in the queue.

2022-08-01 12:19 UTC, windsonsea commented
I'm coming to take it over and will submit before next morning @shixiuguo , so we can move it forward quickly.

2022-08-01 12:23 UTC, tengqm commented
@windsonsea Thanks for stepping out. You may want to do `git fetch origin pull/34641/head:zh-endpoints-v1` and then `git checkout zh-endpoints-v1` into that branch as if you have created the initial commit. You may want to mention @shixiuguo as a co-author of the PR you are working on.

2022-08-02 00:16 UTC, tengqm commented
/close
Superceded by #35601

2022-08-02 00:17 UTC, closed without merging