[zh-cn]Update /docs/reference/kubectl/_index.md
kubernetes/website pull request #34713
Opened 2022-06-30 00:40 UTC by yanrongshi

![image](https://user-images.githubusercontent.com/29862632/176568702-f5a40c97-1aa9-426f-a1f1-caeeae12b885.png)
![image](https://user-images.githubusercontent.com/29862632/176568738-64ff5843-00f3-452f-a8d7-62169bae864b.png)

2022-06-30 03:04 UTC, mengjiao-liu requested changes

2022-06-30 03:04 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/kubectl/_index.md
>  `针对配置信息，`kubectl` 在 `$HOME/.kube` 目录中查找一个名为 `config` 的配置文件。
```suggestion
针对配置信息，`kubectl` 在 `$HOME/.kube` 目录中查找一个名为 `config` 的配置文件。
```
多加的这个 "`" 符号应该才是链接渲染失败的原因。

2022-06-30 03:04 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/kubectl/_index.md
> +`[`--kubeconfig`](/zh-cn/docs/concepts/configuration/organize-cluster-access-kubeconfig/)`
page preview: https://deploy-preview-34713--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubectl/

![image](https://user-images.githubusercontent.com/44460091/176583592-39633a63-d8e1-4498-85e1-7442799a7a67.png)

```suggestion
[`--kubeconfig`](/zh-cn/docs/concepts/configuration/organize-cluster-access-kubeconfig/)
```

2022-06-30 03:51 UTC, yanrongshi commented
Accidentally merged someone else's request, I will reopen a pr

2022-07-01 03:14 UTC, tengqm commented
@yanrongshi You dont have to reopen a new PR again and again. Fix this PR at your local machine. Then `git commit --amend`, followed by `git push -f`. It is not hard, but you have to learn the right way to push PRs.

2022-07-01 03:52 UTC, yanrongshi commented
> @yanrongshi You dont have to reopen a new PR again and again. Fix this PR at your local machine. Then `git commit --amend`, followed by `git push -f`. It is not hard, but you have to learn the right way to push PRs.

谢谢大佬，在git上的能力确实存在不足，这几天总算学会了，接下来不会再出现这种问题了，感谢

2022-07-11 06:17 UTC, tengqm commented
Still working on this, @yanrongshi?

2022-07-12 02:17 UTC, yanrongshi commented
> 还在做这个，@yanrongshi?

yes，today I will update this fire！

2022-07-12 13:53 UTC, closed without merging