Criando arquivo index
kubernetes/website pull request #34881
Opened 2022-07-08 15:10 UTC by DonatoHorn

2022-07-13 23:46 UTC, stormqueen1990 commented
/cc

2022-07-14 00:07 UTC, stormqueen1990 requested changes
Thank you for your contribution, @DonatoHorn! 🎉 

I left some comments with things I found during review.

Another small thing I noticed: all occurrences of "Contêiner" have the capitalized C, but I think it should be rendered with a small c in the middle of sentences.

2022-07-14 00:07 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +nos Nós do seu cluster. Mantendo os requisitos de memória dos Pod's baixos,
Typo: "Pod's" should be "Pods".

2022-07-16 16:51 UTC, DonatoHorn commented
/assign  @devlware 

I made some fixes, as requested.

2022-07-16 16:52 UTC, DonatoHorn commented
I made some fixes, as requested.
/assign  @devlware

2022-07-16 19:23 UTC, stormqueen1990 requested changes
Hi there!

Found a few minor required changes. After those are fixed, it will be a LGTM.

2022-07-16 19:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/_index.md
> +reviewers:
I think these fields should not be added here.

2022-07-16 19:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +reviewers:
I think these fields should not be added here.

2022-07-16 19:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +ser reiniciado, o kubelet o reinicia, assim como outro tipo de falha de runtime.
Suggestion: use "tempo de execução" instead of runtime here.

2022-07-16 19:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +que provávelmente excede a capacidade de qualquer Nó em seu cluster.
Typo: extra diacritic in "provavelmente".

2022-07-16 19:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +A saída mostra que o status do Pod é `PENDING`. O que significa que, o Pod não está
Minor: extra comma after "significa que".

2022-07-22 03:15 UTC, Sea-n commented
Hey @DonatoHorn,

It's been some day since last update, would you like to address issues in the previous comments so that we can move forward?

2022-07-22 05:15 UTC, DonatoHorn commented
> Hey @DonatoHorn,
> 
> It's been some day since last update, would you like to address issues in the previous comments so that we can move forward?

Sorry for the delay, it's ready for me.

2022-07-24 15:57 UTC, stormqueen1990 requested changes
Minor textual changes.

2022-07-24 15:57 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +Isso é mair que os 100 MiB de requisito do Pod, mas está dentro dos 200 MiB de limite do Pod.
Typo: mair.

2022-07-24 15:57 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +em um Nó somente se, o Nó possuir memória disponível suficiente para satisfazer
Extra comma after `se`.

2022-07-24 15:57 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +* O Pod pode ter picos de atividade, quando ele faz uso da memória
Extra comma after atividade.

2022-07-24 15:57 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-memory-resource.md
> +* O montante de memória que um Pod pode usar durante um pico de atividade,
Extra comma after atividade.

2022-07-25 17:59 UTC, closed without merging

2022-07-28 12:36 UTC, stormqueen1990 commented
Hi @DonatoHorn! Did you open a separate PR for this content?

2022-07-28 21:25 UTC, DonatoHorn commented
Moved to pr 35520