Feature/zh cn resource quota v1
kubernetes/website pull request #34933
Opened 2022-07-11 11:31 UTC by donghui12

Tranlate ontent/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
https://github.com/kubernetes/website/issues/34733

2022-07-11 12:03 UTC, windsonsea requested changes
kick a beginning nits.

You can modify some layout alignment issues by preview: 
https://deploy-preview-34933--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1/

2022-07-11 12:15 UTC, tengqm commented
pls squash your commits to 'main'. This is a new file and there should be no commit related to other files.
Please also always keep your PR at single commit.

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  hard 是每个指定资源所需的硬限制集。
```suggestion
  hard 是每种指定资源所需的硬性限制集合。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  scopeSelector 也就是过滤器的集合，
```suggestion
  scopeSelector 也是一组过滤器的集合，和 scopes 类似，
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  例如必须匹配由配额跟踪但使用 ScopeSelectorOperator 结合可能值表示的每个对象的范围。
```suggestion
  必须匹配配额所跟踪的每个对象，但使用 ScopeSelectorOperator 结合可能的值来表示。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  对于要匹配的资源，必须匹配范围和范围选择器（如果在规范中指定）。
```suggestion
  对于要匹配的资源，必须同时匹配 scopes 和 scopeSelector（如果在 spec 中设置了的话）。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  scope selector 表示 scoped-resource selector 所代表的**与**选择器。
```suggestion
  scope 选择算符表示的是由限定范围的资源选择算符进行 **逻辑与** 计算得出的结果。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +    按资源范围划分的 scope-selector-requirement 列表。
```suggestion
    按资源范围划分的范围选择算符需求列表。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +    scoped-resource-selector-requirement 是包含值、范围名称和关联两者的选择器。
```suggestion
    限定范围的资源选择算符需求是一种选择算符，包含值、范围名称和将二者关联起来的运算符。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +      表示范围与值的关系。有效的运算符为 In、NotIn、Exists、DoesNotExist。
```suggestion
      表示范围与一组值之间的关系。有效的运算符为 In、NotIn、Exists、DoesNotExist。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +      选择器应用于作用域的名称。
```suggestion
      选择器所适用的范围的名称。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +      该数组将在战略合并补丁期间替换。
```suggestion
      该数组将在策略性合并补丁操作期间被替换。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  一个匹配每个被配额跟踪的对象的筛选器集合。
```suggestion
  一个匹配被配额跟踪的所有对象的过滤器集合。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +ResourceQuotaStatus 定义了 hard limit 和 observed use。
```suggestion
ResourceQuotaStatus 定义硬性限制和观测到的用量。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  hard 是每个命名资源的强制硬限制集。
```suggestion
  hard 是每种指定资源所强制实施的硬性限制集合。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +  used 是当前监控的命名空间中资源的总使用量。
```suggestion
  used 是当前命名空间中所观察到的资源总用量。
```

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +- **name** （*路径参数*）: string, 必需
```suggestion
- **name** （**路径参数**）: string, 必需
```

下同。

2022-07-11 12:28 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +- **pretty** （*查询参数*）: string
```suggestion
- **pretty** （**查询参数**）: string
```

2022-07-13 02:13 UTC, xichengliudui commented
/lgtm

2022-07-13 02:35 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +    按资源范围划分的范围选择算符需求列表。
99 前面加空行

2022-07-13 02:35 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +      表示范围与一组值之间的关系。有效的运算符为 In、NotIn、Exists、DoesNotExist。
112 前面加空行

2022-07-13 02:35 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +      选择器所适用的范围的名称。
119 前面加空行

2022-07-13 02:35 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/resource-quota-v1.md
> +      字符串值数组。
126 前面加空行

2022-07-21 18:41 UTC, Sea-n commented
Hey @donghui12,

It's been a while since last update, would you like to address issues in the previous comments so that we can move forward?

2022-07-22 01:21 UTC, donghui12 commented
I got label lgtm ，think this pr is comleted ，I will fix this pr again

2022-07-23 03:08 UTC, tengqm commented
/lgtm
/approve

2022-07-23 03:10 UTC, merged