Internacionalização para pt-br content/pt-br/docs/tasks/configure-pod…
kubernetes/website pull request #34972
Opened 2022-07-13 02:35 UTC by DonatoHorn

…-container/assign-cpu-resource.md

2022-07-13 23:42 UTC, stormqueen1990 commented
/cc
/retitle [pt-br] Add content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md

2022-07-16 19:07 UTC, stormqueen1990 requested changes
Hi there, @DonatoHorn!

Thanks for your contribution!

I left some comments on a few places that need changes.

2022-07-16 19:07 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +Requisitos e limites de CPU são associados aos Contêineres, mas é funcional pensar num Pod como tendo requisito e limite de CPU. O requisito de CPU para um Pod é a soma dos requisitos de CPU de todos
I think "útil" is a better word to translate "useful" as, in lieu of "funcional".

2022-07-16 19:07 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +agendado para executar em qualquer Nó, e permanecerá no estado Pendente indefinidamente.
These two sentences are lacking a bit of flow to me. It feels a word is missing before "Que significa" and there's an extra comma afterwards.

2022-07-16 19:07 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +* O Contêiner não possue limite superior de recursos de CPU que possa usar.
Typo: possue should be possui.

2022-07-16 19:07 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +de ser agendado. Ao pegar um limite de CPU que é maior que os requisitos de CPU,
Suggestion: "especificar" in lieu of "pegar".

2022-07-16 19:07 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +a uma quantidade razoável.
Suggestion: "explosões" in lieu of "estouros".

2022-07-16 19:12 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +reviewers:
I think these fields should not be added here.

2022-08-12 16:18 UTC, stormqueen1990 requested changes
Hi @DonatoHorn, thank you very much for your contribution! 🎉 

I found some points that could be improved. Please let me know if you need any clarification.

2022-08-12 16:18 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +O agendamento do Pod é baseado em requisições. Um Pod é agendado para executar em um Nó, somente se o Nó possuir suficiente recursos de CPU disponíveis para satisfazer os requisitos de CPU do Pod.
Minor: instead of "suficiente recursos", "recursos de CPU suficientes" would sound better.

2022-08-12 16:18 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +Neste exercício, você cria um Pod que tem um requisito de CPU tão grande, que excede a capacidade de qualquer Nó em seu cluster. Aqui está o arquivo de configuração para o Pod que tem um Contêiner. O
Minor: extra accent in "provavelmente".

2022-08-12 16:18 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +o kubernetes automáticamente atribui os requisitos de CPU que correspondem ao limite.
Extra accent in "automaticamente".

2022-08-12 16:18 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +você faz um uso eficiente dos recursos de CPU disponívies nos Nós do seu cluster.
Minor: typo in "disponívies".

2022-08-12 16:18 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +você estará realizando duas coisas:
Suggestion: "garantindo as seguintes condições"/"permitindo as seguintes situações" in lieu of "você estará realizando duas coisas".

2022-08-12 16:18 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +* o Pod pode ter picos de atividade quando estiver fazendo uso de recursos de CPU
Minor: add capital "O" here in the beginning of the sentence for consistency.

Original documentation says "where", but that was translated to "quando". Suggestion: "picos de atividade onde utilizará recursos de CPU que estão disponíveis" delivers that better.

2022-08-12 16:18 UTC, stormqueen1990 commented
/assign @edsoncelio

2022-08-12 20:39 UTC, stormqueen1990 commented
> [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.
> 
> **The list of commits with invalid commit messages**:
> 
> * [2687028](https://github.com/kubernetes/website/commits/2687028f97113b51e5d03bcd804873af427dff87) add content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md

Hi @DonatoHorn!

It seems you added a user reference to my username in your commit message. That makes the commit message invalid to be merged. You will need to fix that commit message using `git commit --amend`, as described here: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message#amending-older-or-multiple-commit-messages.

2022-08-26 13:23 UTC, devlware commented on content/pt-br/docs/tasks/configure-pod-container/assign-cpu-resource.md
> +Ao configurar os requisitos de CPU e limites dos Contêneres que executam no seu cluster,
There is a typo here in Conteneres, believe should be Contêineres.

2022-08-26 13:25 UTC, devlware requested changes
Hi @DonatoHorn, thanks for translating. I left one small note, could you fix that? :)

2022-08-30 13:08 UTC, devlware approved these changes

2022-08-30 13:08 UTC, devlware commented
/lgtm

2022-11-04 00:48 UTC, stormqueen1990 commented
Hi @DonatoHorn!

This contribution is currently approved, but the bot cannot merge it automatically due to an invalid commit message.

Would you like to open a new PR with the current state of the files and close this one perhaps?

2022-11-20 23:30 UTC, devlware commented
@DonatoHorn +1 for using the suggestion from stormqueen. Lemme know if you need help with the operation.

2022-12-15 09:50 UTC, closed without merging

2022-12-15 09:51 UTC, DonatoHorn commented
I'll create a new PR for this same files.

2022-12-17 22:14 UTC, devlware commented
@DonatoHorn the problem with a new PR is that it will require a whole new review.