update website/content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
kubernetes/website pull request #35036
Opened 2022-07-15 01:57 UTC by sarazqy

update website/content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md

2022-07-15 02:03 UTC, windsonsea requested changes
/assign

2022-07-15 02:03 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +- **name** （**路径参数**）: string，必须
```suggestion
- **name** （**路径参数**）: string，必需
```

2022-07-15 03:47 UTC, javadoors commented
/lgtm

2022-07-15 13:23 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/priority-class-v1.md
> +  PriorityClass 名称
这个句号可以保留

2022-07-21 16:20 UTC, Sea-n reviewed
/lgtm

2022-07-22 02:16 UTC, mengjiao-liu commented
/approve
Thanks for the catch!

2022-07-22 02:18 UTC, merged