[WIP] Added Hindi localisation for docs/concepts/overview/components
kubernetes/website pull request #35123
Opened 2022-07-18 08:48 UTC by AmanSarraf

### Added Hindi localization for ```docs/concepts/overview/component```

fixes #35063
@anubha-v-ardhan @garima-negi @rolfedh

2022-07-19 11:16 UTC, rolfedh commented on content/hi/docs/concepts/overview/components.md
> +- lavalamp
Remove or update.

2022-07-19 11:17 UTC, rolfedh commented on content/hi/docs/concepts/overview/components.md
> +{{< glossary_definition term_id="cluster" length="all" prepend="A Kubernetes cluster consists of">}}
Should you create a Hindi glossary definition?

2022-07-19 11:19 UTC, rolfedh commented on content/hi/docs/concepts/overview/components.md
> +{{< glossary_definition term_id="cluster" length="all" prepend="A Kubernetes cluster consists of">}}
https://kubernetes.io/docs/contribute/localization/#language-specific-style-guide-and-glossary

2022-07-19 20:19 UTC, AmanSarraf commented on content/hi/docs/concepts/overview/components.md
> +- lavalamp
fixed with https://github.com/kubernetes/website/pull/35123/commits/a030f25e118346b77f83a21eab84351158c0fda5

2022-07-24 14:07 UTC, rolfedh commented on content/hi/docs/concepts/overview/components.md
> +{{< figure src="/images/docs/components-of-kubernetes.svg" alt="Components of Kubernetes" caption="कुबेरनेट्स क्लस्टर के घटक।" class="diagram-large" >}}
Please localize the alt text, too.

2022-07-24 14:19 UTC, rolfedh commented on content/hi/docs/concepts/overview/components.md
> +`क्यूब-सिस्टम ` नेमस्पेस में शामिल ऐडऑन के लिए।
When using Kubernetes, do Hindi users see the namespace names in English or Hindi? The documentation should match what the user sees in the UI and CLI. Looking at the Korean translation of `website/content/ko/docs/concepts/overview/components.md`, I see `   * `kube-system` 쿠버네티스 시스템에서 생성한 오브젝트를 위한 네임스페이스`.

2022-07-24 14:19 UTC, rolfedh commented on content/hi/docs/reference/glossary/cluster.md
> +   कार्यकर्ता मशीनों का एक सेट होता है, जिसे नोड्स कहा जाता है, जो कंटेनरीकृत अनुप्रयोगों को चलाता है। प्रत्येक क्लस्टर में कम से कम एक कार्यकर्ता नोड होता है।
Please indent all these descriptions using one tab character instead of multiple space characters.

2022-07-24 14:19 UTC, rolfedh commented on content/hi/docs/concepts/overview/components.md
> +कण्ट्रोल प्लेन के घटक क्लस्टर (उदाहरण के लिए, शेड्यूलिंग) के बारे में वैश्विक निर्णय लेते हैं, साथ ही क्लस्टर घटनाओं का पता लगाने और उनका जवाब देते हैं (उदाहरण के लिए, जब किसी परिनियोजन की `प्रतिकृति
It's very good that you're adding or translating tooltip text values like this.

2022-07-24 14:21 UTC, rolfedh reviewed
I think you should `git rm`:
- `themes/docsy`
- The empty files
- `.hugo_build.lock`

2022-07-31 18:14 UTC, rolfedh commented on content/hi/docs/concepts/overview/components.md
> +{{< glossary_definition term_id="cluster" length="all" prepend="A Kubernetes cluster consists of">}}
@AmanSarraf  You can click the Resolved button for this comment (only you have the button). You've created the glossary.md file in this PR.

2022-08-07 18:20 UTC, rolfedh reviewed
Please `$ git rm .hugo_build.lock` as well.

2022-08-08 17:07 UTC, AmanSarraf commented
/assign @anubha-v-ardhan
Please review and approve for merge.

2022-08-10 02:51 UTC, anubha-v-ardhan commented
@AmanSarraf There are multiple files on this PR while the title talks about `content/hi/docs/concepts/overview/components.md` only. Is this a mistake?

We prefer having one file per PR as they make things easy to manage and speed up the review process.

2022-08-10 05:57 UTC, AmanSarraf commented
> @AmanSarraf There are multiple files on this PR while the title talks about `content/hi/docs/concepts/overview/components.md` only. Is this a mistake?
> 
> We prefer having one file per PR as they make things easy to manage and speed up the review process.

I did localized the page and related glossary items as well that were supposed to appear in between like POD,NODE...etc

2022-08-10 11:15 UTC, rolfedh commented
@anubha-v-ardhan I understand the reasoning for limiting the number of files, [as described in these contributor guidelines](https://www.kubernetes.dev/docs/guide/pull-requests/#why-is-my-pull-request-not-getting-reviewed), but I don't see a guideline asking that PRs be limited to a single file. In our PR merge history, one sees exceptions to this preference. 

In this case, Aman's inclusion of the glossary files ensures that users who read the topic have a completely translated topic, not a patchwork of Hindi and English content from glossaries.

2022-08-20 09:26 UTC, anubha-v-ardhan requested changes
Initial review, will review more soon

2022-08-20 09:26 UTC, anubha-v-ardhan commented on content/hi/docs/concepts/_index.md
> +अवधारणा अनुभाग आपको कुबेरनेट्स प्रणाली के कुछ हिस्सों के बारे में जानने में मदद करता है और कुबेरनेट्स आपके {{< glossary_tooltip text="क्लस्टर" term_id="cluster" length="all" >}} का प्रतिनिधित्व करने
```suggestion
अवधारणा अनुभाग आपको कुबेरनेट्स प्रणाली के कुछ हिस्से तथा कुबेरनेट्स द्वारा आपके {{< glossary_tooltip text="क्लस्टर" term_id="cluster" length="all" >}} का प्रतिनिधित्व के बारे में जानने में मदद करता है और कुबेरनेट्स कैसे काम करता है इसकी गहरी समझ प्राप्त करने में आपकी सहायता करता है।
```

2022-08-20 09:26 UTC, anubha-v-ardhan commented on content/hi/docs/concepts/overview/components.md
> +title: कुबेरनेट्स घटक
```suggestion
title: कुबेरनेट्स अवयव
```

2022-08-20 09:26 UTC, anubha-v-ardhan commented on content/hi/docs/concepts/overview/_index.md
> +description: कुबेरनेट्स और उसके घटकों का एक उच्च-स्तरीय अवलोकन प्रदान करता है।
```suggestion
description: कुबेरनेट्स और उसके अवयव का एक उच्च-स्तरीय अवलोकन प्रदान करता है।
```
[Nit] अवयव fits better here in my opinion

2022-08-20 09:26 UTC, anubha-v-ardhan commented on content/hi/docs/concepts/overview/components.md
> + कुबेरनेट्स क्लस्टर में ऐसे घटक होते हैं जो नियंत्रण विमान का प्रतिनिधित्व करते हैं और मशीनों का एक सेट जिसे नोड्स कहा जाता है।
```suggestion
 कुबेरनेट्स क्लस्टर में ऐसे अवयव होते हैं जो कण्ट्रोल प्लेन और मशीनों का एक सेट, नोड्स का प्रतिनिधित्व करते हैं।
```

2022-08-20 09:26 UTC, anubha-v-ardhan commented on content/hi/docs/concepts/overview/components.md
> +जब आप कुबेरनेट्स को तैनात करते हैं, तो आपको एक क्लस्टर मिलता है।
```suggestion
जब आप कुबेरनेट्स को डेप्लॉय करते हैं, तो आपको एक क्लस्टर मिलता है।
```

2022-08-20 09:34 UTC, anubha-v-ardhan commented
@rolfedh @AmanSarraf 
I understand the idea behind addition of glossary files. Also, there's no hard and fast rule to limit a PR to a number of files. However keeping the number of files eases the work for reviewers and helps the PR to move faster.

For example here, we could have 
- `content/hi/docs/concepts/_index.md`
- `content/hi/docs/concepts/overview/_index.md`
- `content/hi/docs/concepts/overview/components.md`
on separate PRs.

We'll slowly review this PR step by step but please try to keep PRs small whenever possible.

Also @AmanSarraf If the work is complete, you can remove the "[WIP]" from PR title and `do-not-merge/work-in-progress` label

2022-11-19 14:24 UTC, closed without merging