[pt-br] add content/pt-br/docs/tasks/configure-pod-container/attach-h…
kubernetes/website pull request #35143
Opened 2022-07-18 22:12 UTC by DonatoHorn

2022-10-20 23:51 UTC, stormqueen1990 commented
/remove-lifecycle stale

2023-02-12 17:14 UTC, stormqueen1990 commented
/retitle [pt-br] Add docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
/cc
/remove-lifecycle stale

2023-03-05 01:52 UTC, DonatoHorn commented
/remove-lifecycle stale

2023-04-16 17:40 UTC, stormqueen1990 commented
/label tide/merge-method-squash

2023-05-10 16:15 UTC, stormqueen1990 reviewed
Hello there, @DonatoHorn! 👋

Thank you very much for your work on this translation! 🎉 

The text overall looks really good. I left some suggestions mostly for style reasons. If you have any questions or concerns please don't hesitate to reach out on Slack. 😃

Thanks again!

---

Olá, @DonatoHorn! 👋

Muito obrigada pelo teu trabalho nesta tradução! 🎉

O texto no geral está muito bom. Deixei algumas sugestões mais por motivo de estilo. Se tiveres quaisquer dúvidas ou questões não hesita em contatar via Slack. 😃

Obrigada novamente!

2023-05-10 16:15 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +Isto é útil se o Contêiner é terminado devido a uma falha.
```suggestion
Neste exercício, você cria um Pod que tem um contêiner. 
O contêiner tem um manipulador para os eventos `postStart` e `preStop`.

Aqui está o arquivo de configuração para o Pod:

{{< codenew file="pods/lifecycle-events.yaml" >}}

No arquivo de configuração, você pode ver que o comando `postStart` escreve um arquivo 
`message` no diretório `/usr/share` do contêiner. 
O comando `preStop` encerra o nginx graciosamente. 
Isto é útil se o contêiner é terminado devido a uma falha. 
```

2023-05-10 16:15 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +    Hello from the postStart handler
nit: it might be better if you use fenced code blocks (i.e. `` ``` ``) instead of the indentation-style code blocks here.

2023-05-10 16:15 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +Obtendo um shell no Contêiner executando em seu Pod:
```suggestion
Verifique que o contêiner no Pod está executando:

    kubectl get pod lifecycle-demo

Inicie um shell no contêiner que está executando no seu Pod:
```

2023-05-10 16:15 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +não é trocado para `RUNNING` até que o manipulador `postStart` esteja completo.
```suggestion
O Kubernetes envia o evento `postStart` imediatamente após o contêiner ser criado. 
Não há garantia, entretanto, que o manipulador `postStart` será chamado antes 
da execução do `entrypoint` do contêiner. O manipulador `postStart` executa 
assincronamente em relação ao código do contêiner, mas o gerenciamento de contêiner
do Kubernetes bloqueia até que o manipulador `postStart` esteja completo.
O status do Contêiner não é trocado para `RUNNING` até que o manipulador `postStart`
seja finalizado.
```

2023-05-10 16:15 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +veja [Ciclo de vida do Pod](/docs/concepts/workloads/pods/pod-lifecycle/).
```suggestion
O Kubernetes envia o evento `preStop` imediatamente antes do contêiner ser terminado. 
O gerenciador do Kubernetes bloqueia até que o manipulador `preStop` esteja completo, 
a não ser que o período de graça do Pod expire. Para mais detalhes, 
veja [Ciclo de vida do Pod](/docs/concepts/workloads/pods/pod-lifecycle/).
```

2023-05-10 16:15 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +Esta limitação é rastreada na [issue #55087](https://github.com/kubernetes/kubernetes/issues/55807).
```suggestion
O Kubernetes somente envia o evento `preStop` quando o Pod está *terminado*.
Isto significa que o _hook_ `preStop` não é invocado quando o Pod está *completo*. 
Esta limitação é rastreada na [issue #55087](https://github.com/kubernetes/kubernetes/issues/55807).
```

This note's last sentence is slightly outdated and needs to be updated.

2023-05-10 16:15 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +* Aprenda mais sobre [Hooks de ciclo de vida do Container](/docs/concepts/containers/container-lifecycle-hooks/).
```suggestion
* Aprenda mais sobre [Hooks de ciclo de vida do contêiner](/pt-br/docs/concepts/containers/container-lifecycle-hooks/).
```

2023-05-11 16:28 UTC, stormqueen1990 reviewed
Hi there, @DonatoHorn! 👋

It seems one of the suggestions got mixed around. Could you please take another look?

---

Olá, @DonatoHorn! 👋 

Parece que uma das sugestões ficou incorreta. Podes olhar novamente?

2023-05-11 16:28 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +
```suggestion
* Aprenda mais sobre [Hooks de ciclo de vida do contêiner](/pt-br/docs/concepts/containers/container-lifecycle-hooks/).
* Aprenda mais sobre o [ciclo de vida do Pod](/docs/concepts/workloads/pods/pod-lifecycle/).

```

It looks like those two links got mixed around. The first one has a version in Portuguese, whereas the second one does not.

2023-05-11 18:34 UTC, stormqueen1990 commented
/lgtm
/cc @edsoncelio

2023-06-04 13:49 UTC, DonatoHorn commented
Hi, there.
This PR was with LGTM label, but is waiting probably for removing the reviewers section that I can't update, so this section is always the same as the original (untouched) English version.

2023-06-05 17:48 UTC, stormqueen1990 commented
> Hi, there. This PR was with LGTM label, but is waiting probably for removing the reviewers section that I can't update, so this section is always the same as the original (untouched) English version.

Hi there, @DonatoHorn! I am unsure what the issue is with the reviewers section. It's not used in the Portuguese localization, so the key can just be removed from the front matter. Could you please explain it further?

2023-06-05 19:46 UTC, jcjesus requested changes
Thanks for your job @DonatoHorn, please, change this request changes, only a typo issue.

Seeya

2023-06-05 19:46 UTC, jcjesus commented on content/pt-br/docs/tasks/configure-pod-container/attach-handler-lifecycle-event.md
> +O Kubernetes envia o evento `postStart` emediatamente após o Contêiner ser criado.
Hi @DonatoHorn, please, I thougth that´s a typo here about the word "_emediatamente_", change to "**imediatamente**".

Thanks

2023-06-12 13:14 UTC, jcjesus commented
/lgtm

2023-06-15 15:12 UTC, stormqueen1990 commented
This PR needs rebase or an empty commit pushed before it can be merged (since the build is not passing).

2023-06-21 14:56 UTC, jcjesus approved these changes
Thanks @DonatoHorn, great job!

2023-06-26 14:25 UTC, stormqueen1990 commented
Hi @DonatoHorn! It seems this rebase didn't work as planned. If you need any help to try again, please feel free to reach out on the `#kubernetes-docs-pt` channel in Slack.

2023-07-13 13:35 UTC, stormqueen1990 commented
Hi again, @DonatoHorn!

Please let us know if you need help repeating the rebase for this branch. This changeset cannot be merged until the rebase issue is resolved.

2023-07-27 01:38 UTC, ydFu commented
Due to the author's lack of response to comments or feedback for a period of 2 weeks or more, we consider this pull request (PR) as inactive. If necessary, please resubmit it for further consideration.

Refer to ['When to close Pull Requests'](https://kubernetes.io/docs/contribute/participate/pr-wranglers/#when-to-close-pull-requests).

/close

2023-07-27 01:38 UTC, closed without merging

2023-12-04 07:50 UTC, jihoon-seo commented
/remove-area blog release-eng
/remove-language de en es fr hi id it ja ko pl ru uk vi zh
/remove-sig release