[pt-br] add content/pt-br/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
kubernetes/website pull request #35148
Opened 2022-07-19 02:12 UTC by DonatoHorn

2022-10-20 23:51 UTC, stormqueen1990 commented
/remove-lifecycle stale

2023-03-05 00:20 UTC, DonatoHorn commented
/remove-lifecycle rotten

2023-04-16 17:39 UTC, stormqueen1990 commented
/cc
/label tide/merge-method-squash

2023-06-04 13:29 UTC, DonatoHorn commented
Hi, there.
After about 12 months of waiting for revision, this PR wasn't up to date with the latest version of de docs, so I updated the file to follow the latest version.

2023-07-28 17:03 UTC, edsoncelio requested changes

2023-07-28 17:03 UTC, edsoncelio commented on content/pt-br/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
> +A transformação padrão do `kompose` vai gerar [Implantações](/docs/concepts/workloads/controllers/deployment/) Kubernetes e [Serviços](/docs/concepts/services-networking/service/), em formato yaml. V
Implantações] -> Deployments 
[Serviços] -> Services

2023-07-28 17:03 UTC, edsoncelio commented on content/pt-br/docs/tasks/configure-pod-container/translate-compose-kubernetes.md
> +Além disso, você pode gerar alternativamente objetos [Controladores de Replicação](/docs/concepts/workloads/controllers/replicationcontroller/), [Daemon Sets](/docs/concepts/workloads/controllers/dae
[Daemon Sets] -> DaemonSets

2024-02-25 22:33 UTC, edsoncelio commented
Hey @DonatoHorn! 
Due to the lack of response, we will close this PR but feel free to reopen it If you want to make the requested changes.
/close

2024-02-25 22:33 UTC, closed without merging