[pt-br] add content/pt-br/docs/tasks/configure-pod-container/enforce-…
kubernetes/website pull request #35151
Opened 2022-07-19 03:03 UTC by DonatoHorn

…standards-namespace-labels.md

2022-10-20 23:50 UTC, stormqueen1990 commented
/remove-lifecycle stale

2022-11-26 14:45 UTC, MrErlison reviewed
Thanks for your contribution!

2022-11-26 14:46 UTC, MrErlison commented on content/pt-br/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
> +(/docs/concepts/security/pod-security-standards). As três políticas
This link "Padrões de segurança de pod" is broken. I think it is because the newline after brackspaces.

2022-11-26 14:47 UTC, MrErlison commented on content/pt-br/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
> +do pod ainda serão executadas em _dry run_ mode, dando-lhe informações sobre
"modo _dry run_" instead of "_dry run_ mode"

2022-11-26 14:49 UTC, MrErlison commented on content/pt-br/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
> +(/docs/reference/command-line-tools-reference/feature-gates/#feature-gates-for-alpha-or-beta-features)
This link "portal de funcionalidades" is broken. There is a space between backspace and parenthesis.

2022-11-26 14:51 UTC, MrErlison commented on content/pt-br/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
> +Quando uma política de label `enforce` (ou version) é adicionada our modificada,
Sounds better "um rótulo de política ... é adicionado" or "uma label de política ... é adicionada"

Typo: "our"

2023-03-05 08:23 UTC, DonatoHorn commented
/remove-lifecycle rotten

2023-05-19 15:23 UTC, stormqueen1990 commented
/cc @edsoncelio

2023-05-25 21:11 UTC, jcjesus requested changes

2023-05-25 21:11 UTC, jcjesus commented on content/pt-br/docs/tasks/configure-pod-container/enforce-standards-namespace-labels.md
> +está habilitada.
Hi @DonatoHorn, please, change "está" for "esteja" should be more clear.

Thanks

2023-05-26 12:05 UTC, jcjesus approved these changes
Thanks @DonatoHorn, great job!

2023-05-26 12:14 UTC, jcjesus commented
/unassign @edsoncelio

2023-05-26 12:16 UTC, jcjesus commented
/lgtm

2023-05-26 12:16 UTC, merged