[zh-cn]update workloads/ _index.md
kubernetes/website pull request #35246
Opened 2022-07-22 13:43 UTC by yanrongshi

preview: https://kubernetes.io/zh-cn/docs/concepts/workloads/

2022-07-22 14:33 UTC, windsonsea commented
😄 
The preview link is: 
https://deploy-preview-35246--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/workloads/

2022-07-22 14:38 UTC, windsonsea requested changes
Prefer to use a bold font in zh-cn rather than an italic font.

2022-07-22 14:38 UTC, windsonsea commented on content/zh-cn/docs/concepts/workloads/_index.md
> +而是使用 _负载资源_ 来替用户管理一组 Pods。
```suggestion
而是使用**负载资源**来替用户管理一组 Pod。
```

2022-07-22 14:38 UTC, windsonsea commented on content/zh-cn/docs/concepts/workloads/_index.md
> +* [_Time-to-Live_ 控制器](/zh-cn/docs/concepts/workloads/controllers/ttlafterfinished/)会在 Job
```suggestion
* [**Time-to-Live** 控制器](/zh-cn/docs/concepts/workloads/controllers/ttlafterfinished/)会在 Job
```

2022-07-22 14:38 UTC, windsonsea commented on content/zh-cn/docs/concepts/workloads/_index.md
> +你都可以在一组 [Pods](/zh-cn/docs/concepts/workloads/pods) 中运行它。
```suggestion
你都可以在一组 [Pod](/zh-cn/docs/concepts/workloads/pods) 中运行它。
```

2022-07-22 15:22 UTC, yanrongshi commented on content/zh-cn/docs/concepts/workloads/_index.md
> +你都可以在一组 [Pods](/zh-cn/docs/concepts/workloads/pods) 中运行它。
Thanks your review,brother

2022-07-22 17:35 UTC, yanrongshi commented
/retest

2022-07-22 17:38 UTC, yanrongshi commented
/ok-to-test

2022-07-23 01:27 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/_index.md
> +所有该节点上的 Pods 的状态都会变成失败。Kubernetes 将这类失败视为最终状态：
这个更改不必要。

2022-07-23 01:28 UTC, tengqm commented
/approve

2022-07-23 04:19 UTC, windsonsea commented
/lgtm

2022-07-23 04:20 UTC, merged