[zh-cn]Update dns-debugging-resolution.md
kubernetes/website pull request #35507
Opened 2022-07-28 14:54 UTC by yanrongshi

2022-07-29 02:29 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
>  [服务和 Pod 的 DNS](/zh-cn/docs/concepts/services-networking/dns-pod-service/#what-things-get-dns-names)。
```suggestion
服务的 DNS 名字解析取决于 pod 的名字空间。
详细信息请查阅[服务和 Pod 的 DNS](/zh-cn/docs/concepts/services-networking/dns-pod-service/#what-things-get-dns-names)。
```

2022-07-29 02:29 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +DNS 的端点是否公开了。
```suggestion
你可以使用 `kubectl get endpoints` 命令来验证 DNS 的端点是否公开了。
```

2022-07-29 02:29 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +Kubernetes 把这些更改应用到
```suggestion
保存这些更改后，你可能会需要等待一到两分钟让 Kubernetes 把这些更改应用到
```

2022-07-30 11:32 UTC, windsonsea requested changes
If you localize a word such as pod, service, secret, or configmap, it will look like Pod, Service, Secret, or ConfigMap in Chinese.

2022-07-30 11:32 UTC, windsonsea commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +此示例在 `default` 名字空间创建 pod。
```suggestion
此示例在 `default` 名字空间创建 Pod。
```

2022-07-30 11:32 UTC, windsonsea commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +服务的 DNS 名字解析取决于 pod 的名字空间。
```suggestion
服务的 DNS 名字解析取决于 Pod 的名字空间。
```

2022-07-30 11:32 UTC, windsonsea commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +详细信息请查阅[服务和 Pod 的 DNS](/zh-cn/docs/concepts/services-networking/dns-pod-service/#what-things-get-dns-names)。
```suggestion
详细信息请查阅 [Pod 与 Service 的 DNS](/zh-cn/docs/concepts/services-networking/dns-pod-service/#what-things-get-dns-names)。
```
Sometimes, if the link name is different from the linked title, people may be doubted  whether it opens a wrong page.
https://kubernetes.io/zh-cn/docs/concepts/services-networking/dns-pod-service/#what-things-get-dns-names

2022-07-30 11:32 UTC, windsonsea commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +未指定名字空间的 DNS 查询仅作用于 pod 所在的名字空间。
```suggestion
未指定名字空间的 DNS 查询仅作用于 Pod 所在的名字空间。
```

2022-07-30 11:32 UTC, windsonsea commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +如果 pod 和服务的名字空间不相同，则 DNS 查询必须指定服务所在的名字空间。
```suggestion
如果 Pod 和服务的名字空间不相同，则 DNS 查询必须指定服务所在的名字空间。
```

2022-07-31 10:48 UTC, windsonsea commented
/lgtm

2022-07-31 14:07 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +该查询仅限于 Pod 所在的名称空间：
名称空间->名字空间

2022-07-31 14:07 UTC, tengqm commented on content/zh-cn/docs/tasks/administer-cluster/dns-debugging-resolution.md
> +- 阅读[Pod 与 Service 的 DNS](/zh-cn/docs/concepts/services-networking/dns-pod-service/)
```suggestion
- 阅读 [Pod 与 Service 的 DNS](/zh-cn/docs/concepts/services-networking/dns-pod-service/)
```

2022-07-31 14:36 UTC, tengqm commented
/lgtm
/approve

2022-07-31 14:38 UTC, merged