[zh-cn]Update coarse-parallel-processing-work-queue.md
kubernetes/website pull request #35571
Opened 2022-07-30 08:41 UTC by yanrongshi

2022-07-30 11:11 UTC, windsonsea requested changes
It's recommended to give some newline symbols to a long para.

2022-07-30 11:11 UTC, windsonsea commented on content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md
> +# 请注意 rabbitmq-service 拥有一个有 Kubernetes 提供的 DNS 名称：
```suggestion
# 请注意 rabbitmq-service 拥有一个由 Kubernetes 提供的 DNS 名称：
```

2022-07-30 11:11 UTC, windsonsea commented on content/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue.md
> +本例中，如果有大量的数据需要被 Job 的所有 Pod 读取，典型的做法是把它们放在一个共享文件系统中，如 NFS（Network File System 网络文件系统），并以只读的方式挂载到所有 Pod，或者 Pod 中的程序从类似 HDFS（Hadoop Distributed File System 分布式文件系统）的集群文件系统中读取。
```suggestion
本例中，如果有大量的数据需要被 Job 的所有 Pod 读取，典型的做法是把它们放在一个共享文件系统中，
如 NFS（Network File System，网络文件系统），并以只读的方式挂载到所有 Pod，或者 Pod 中的程序从类似
HDFS（Hadoop Distributed File System，分布式文件系统）的集群文件系统中读取。
```

2022-07-31 01:40 UTC, Sea-n reviewed
Overall looks good to me, wait for fixing previous suggestion brought by windsonsea.

Wow, I see you help updated the English comment even if the translated text is updated. 😊

---

The GitHub preview for Markdown is not the "preview page", we use Netlify bot to generate a live website for each PR.

Please refer to [this comment](https://github.com/kubernetes/website/pull/35571#issuecomment-1200119765), using "😎 Deploy Preview" with the right path:
https://deploy-preview-35571--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue

2022-07-31 03:23 UTC, yanrongshi commented
> Overall looks good to me, wait for fixing previous suggestion brought by windsonsea.
> 
> Wow, I see you help updated the English comment even if the translated text is updated. 😊
> 
> The GitHub preview for Markdown is not the "preview page", we use Netlify bot to generate a live website for each PR.
> 
> Please refer to [this comment](https://github.com/kubernetes/website/pull/35571#issuecomment-1200119765), using "😎 Deploy Preview" with the right path: https://deploy-preview-35571--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/job/coarse-parallel-processing-work-queue

Thanks，my brother

2022-07-31 10:43 UTC, windsonsea commented
/lgtm

2022-07-31 13:56 UTC, tengqm commented
/approve

2022-07-31 13:58 UTC, merged