Updated link on Release Managers page
kubernetes/website pull request #35605
Opened 2022-08-01 16:25 UTC by kadtendulkar

Follow up on #35604

Updated the page [Release Managers](https://kubernetes.io/releases/release-managers/)

2022-08-02 02:44 UTC, Sea-n reviewed
Confirmed.
/lgtm

2022-08-02 16:08 UTC, kadtendulkar commented
Hello @Sea-n , please approve PR.

2022-08-03 00:20 UTC, Sea-n commented
Hi @kadtendulkar,

I am not a eligible approver for this PR (need to be `sig-docs-en-owners` usually).

My approval doesn't counts for @k8s-ci-robot, but I would be happy to try.
/approve

2022-08-03 03:31 UTC, reylejano commented
This PR looks good but would like SIG Release to review
/sig release
/approve
/hold

@kubernetes/sig-release , ptal and remove the hold if this PR looks good

2022-08-03 03:51 UTC, puerco requested changes
Thanks for fixing this @kadtendulkar !
Just a tiny nit, let's keep the link in line with the others using the k8s.io redirector service:

2022-08-03 03:51 UTC, puerco commented on content/en/releases/release-managers.md
> +[handbook-packaging]: https://github.com/kubernetes/release/blob/master/hack/rapture/README.md
```suggestion
[handbook-packaging]: https://git.k8s.io/release/hack/rapture/README.md
```

2022-08-03 04:00 UTC, reylejano commented on content/en/releases/release-managers.md
> +[handbook-packaging]: https://github.com/kubernetes/release/blob/master/hack/rapture/README.md
+1 to @puerco 's suggestion

2022-08-03 05:06 UTC, puerco commented
Thanks @kadtendulkar !
/lgtm
/approve
/hold cancel

2022-08-03 05:07 UTC, merged