[zh-cn] Fix translate and links
kubernetes/website pull request #35730
Opened 2022-08-05 09:30 UTC by fusida

[zh-cn] fix a link and a translation

2022-08-05 09:40 UTC, howieyuen commented
/hold

谢谢贡献。根据[指南](https://kubernetes.io/zh/docs/contribute/localization_zh/#%E6%9B%B4%E6%96%B0%E8%AF%91%E6%96%87)约定，我们会拒绝对页面的部分修改。部分修改针对的是对应页面的英文上游还有其他改动需要同步的情况。
一旦我们合并了此 PR，将来就无法根据文件的最后更改时间来判断是否有其他上游变更尚未同步。请理解。

```bash
./scripts/lsync.sh content/zh-cn/blog/_posts/2022-04-07-Kubernetes-1-24-removals-and-deprecations.md
```

2022-08-06 00:48 UTC, windsonsea requested changes
Issue about the `in-tree` term.

2022-08-06 00:48 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-04-07-Kubernetes-1-24-removals-and-deprecations.md
> +* 内置驱动（In-tree provisioner）向 CSI 卷迁移：这适用于许多内置插件，
This change is unnecessary. We often use `树内` for `in-tree`.

2022-08-06 00:48 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-04-07-Kubernetes-1-24-removals-and-deprecations.md
> +  参见[内置存储插件向 CSI 卷迁移的设计文档](https://github.com/kubernetes/design-proposals-archive/blob/main/storage/csi-migration.md#background-and-motivations)
```suggestion
  参见[树内存储插件向 CSI 卷迁移的设计文档](https://github.com/kubernetes/design-proposals-archive/blob/main/storage/csi-migration.md#background-and-motivations) 
```
Need not to change.

2022-08-08 05:58 UTC, closed without merging

2022-08-08 06:36 UTC, mengjiao-liu commented
I opened the new PR #35777 to fix this issue and you are a co-author of the PR.