[zh-cn] Add blog 2022-05-20-non-graceful-node-shutdown.md chinese ver…
kubernetes/website pull request #35779
Opened 2022-08-08 07:40 UTC by zhangxyjlu

fixed: #35774
Add  2022-05-20-non-graceful-node-shutdown.md chinese version

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +如果关闭的原节点再次出现，该原节点上的 kubelet 会报告，删除现有的 Pod，并且控制平面会在不同的运行节点上为该
```suggestion
如果已关闭的原节点再次出现，该节点上的 kubelet 会执行报到操作，删除现有的 Pod，
并且控制平面会在其他运行中的节点上为该
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +在节点关闭的情况下，你可以手动将该节点标记污点使之停止服务。在添加污点之前，你应该确保节点确实关闭了（不是在重启过程中）。
```suggestion
在节点关闭的情况下，你可以手动为该节点标记污点，标示其已停止服务。
在添加污点之前，你应该确保节点确实关闭了（不是在重启过程中）。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +你可以在 kubelet 没有提前检测和处理的情况下，在节点关闭之后添加污点；
```suggestion
你可以在发生了节点关闭事件，且该事件没有被 kubelet 提前检测和处理的情况下，在节点关闭之后添加污点；
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +如果你已经启用了前面提到的特性门控，在节点上设置停止服务的污点意味着节点上的 Pod 将被删除，除非 Pod 上有匹配的容忍度。
```suggestion
如果你已经启用了前面提到的特性门控，在节点上设置 out-of-service 污点意味着节点上的 Pod 将被删除，
除非 Pod 上设置有与之匹配的容忍度。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +连接到关闭节点的持久性卷（Persistent volume）将被分离，对于 StatefulSet，将在不同的运行节点上成功创建替换 Pod。
```suggestion
原来挂接到已关闭节点的持久卷（Persistent volume）将被解除挂接，对于 StatefulSet，
系统将在其他运行中的节点上成功创建替换 Pod。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +注意：在应用停止服务污点之前，你**必须**验证节点是否已经处于关闭或断电状态（不是在重新启动过程中），
```suggestion
注意：在应用 out-of-service 污点之前，你**必须**确认节点是否已经处于关闭或断电状态（不是在重新启动过程中），
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +这可能是因为用户有意将其关闭，也可能是因为节点由于硬件故障、操作系统问题等而关闭。
```suggestion
节点关闭的原因可能是因为用户有意将其关闭，也可能是因为节点由于硬件故障、操作系统问题等而关闭。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +一旦链接到停止服务节点的所有工作负载 Pod 都移动到新的运行节点，并且关闭节点已恢复，
```suggestion
一旦关联到无法提供服务的节点的所有工作负载 Pod 都被移动到新的运行中的节点，并且关闭了的节点也已恢复，
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +此功能需要用户手动向节点添加污点以触发工作负载故障转移并在节点恢复后移除污点。
```suggestion
此功能需要用户手动向节点添加污点以触发工作负载故障转移，并要求用户在节点恢复后移除污点。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +未来，我们计划寻找方法来自动检测和隔离关闭或失败的节点，并自动将工作负载故障转移到另一个节点。
```suggestion
未来，我们计划寻找方法来自动检测和隔离已关闭的或已失败的节点，并自动将工作负载故障转移到另一个节点。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +查看节点非体面关闭相关[文档](/zh-cn/docs/concepts/architecture/nodes/#non-graceful-node-shutdown)
```suggestion
查看节点非体面关闭相关[文档](/zh-cn/docs/concepts/architecture/nodes/#non-graceful-node-shutdown)。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +此功能由来已久。Yassine Tijani ([yastij](https://github.com/yastij)) 在两年多前开始了 KEP。
```suggestion
此功能特性由来已久。Yassine Tijani ([yastij](https://github.com/yastij)) 在两年多前启动了这个 KEP。
```

2022-08-08 09:16 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +我们要感谢以下人员的评论：Tim Hockin  ([thockin](https://github.com/thockin)) 对设计的指导；
```suggestion
我们要感谢以下人员的评审：Tim Hockin ([thockin](https://github.com/thockin)) 对设计的指导；
```

2022-08-08 11:13 UTC, windsonsea requested changes

2022-08-08 11:13 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +StatefulSet 无法创建替换 Pod，因为该 Pod 仍存在于群集中。
```suggestion
StatefulSet 无法创建替换 Pod，因为该 Pod 仍存在于集群中。
```

2022-08-08 11:13 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +`node.kubernetes.io/out-of-service=nodeshutdown:" NoSchedule"`。
```suggestion
`node.kubernetes.io/out-of-service=nodeshutdown: "NoSchedule"`。
```
The en is wrong too.

2022-08-08 13:47 UTC, Sea-n commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +Kubernetes v1.24 引入了对[节点非体面关闭](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown)
I think "non-graceful" should be translated as 強制 or 非優雅.

2022-08-08 13:47 UTC, Sea-n commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +## 这与节点体面关闭有何不同
I think 優雅 is more usual translation for gracefully shutdown.

2022-08-09 01:37 UTC, zhangxyjlu commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +Kubernetes v1.24 引入了对[节点非体面关闭](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/2268-non-graceful-shutdown)
翻译成体面和非体面是根据之前已经审视合入的[文档](https://deploy-preview-35779--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/nodes/#graceful-node-shutdown)以及[中文本地化样式指南](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD)中术语表进行翻译的。

2022-08-09 01:37 UTC, zhangxyjlu commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +## 这与节点体面关闭有何不同
翻译成体面和非体面是根据之前已经审视合入的[文档](https://deploy-preview-35779--kubernetes-io-main-staging.netlify.app/zh-cn/docs/concepts/architecture/nodes/#graceful-node-shutdown)以及[中文本地化样式指南](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%9C%AF%E8%AF%AD)中术语表进行翻译的。

2022-08-09 02:54 UTC, howieyuen requested changes

2022-08-09 02:54 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-05-20-non-graceful-node-shutdown.md
> +此功能特性由来已久。Yassine Tijani ([yastij](https://github.com/yastij)) 在两年多前启动了这个 KEP。
replace the brackets with Chinese one, same below at line 182 to 184 and line 193 to 200
```suggestion
此功能特性由来已久。Yassine Tijani（[yastij](https://github.com/yastij))）在两年多前启动了这个 KEP。
```

2022-08-09 03:49 UTC, howieyuen reviewed
/lgtm

2022-08-09 04:16 UTC, Sea-n commented
/approve

2022-08-09 04:29 UTC, Sea-n commented
Hey @zhangxyjlu,

The Netlify build failed for no particular reason.

You can try this to trigger Netlify rebuild without losing <kbd>lgtm</kbd> label.
```bash
git reset
git commit --amend --no-edit
git push -f
```

2022-08-09 07:47 UTC, zhangxyjlu commented
> Hey @zhangxyjlu,
> 
> The Netlify build failed for no particular reason.
> 
> You can try this to trigger Netlify rebuild without losing lgtm label.
> 
> ```shell
> git reset
> git commit --amend --no-edit
> git push -f
> ```

这个方法没有起作用，看报错应该是传入的参数为nil导致，但是没找到具体原因.
报错信息：

```
WARNING: calling IsSet with unsupported type "invalid" (<nil>) will always return false.
```

Hugo 对应代码：

```
// IsSet returns whether a given array, channel, slice, or map has a key
// defined.
func (ns *Namespace) IsSet(a interface{}, key interface{}) (bool, error) {
	av := reflect.ValueOf(a)
	kv := reflect.ValueOf(key)
	switch av.Kind() {
	case reflect.Array, reflect.Chan, reflect.Slice:
		if int64(av.Len()) > kv.Int() {
			return true, nil
		}
	case reflect.Map:
		if kv.Type() == av.Type().Key() {
			return av.MapIndex(kv).IsValid(), nil
		}
	default:
		ns.deps.Log.ERROR.Printf("calling IsSet with unsupported type %T will always return false", a)
	}
```

2022-08-10 02:16 UTC, Sea-n commented
The build check is passed.

Reapply LGTM from @howieyuen.
/lgtm

2022-08-10 02:18 UTC, merged