[hi]Localize content/en/docs/reference/glossary/annotation.md
kubernetes/website pull request #36062
Opened 2022-08-18 03:56 UTC by taniaduggal

Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>

Fixes #35600

2022-08-19 13:11 UTC, taniaduggal commented
@anubha-v-ardhan Please review

2022-08-20 06:21 UTC, anubha-v-ardhan requested changes

2022-08-20 06:21 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/annotation.md
> +एनोटेट किया गया मेटाडेटा छोटा या बड़ा, संरचित या असंरचित हो सकता है, और इसमें ऐसे वर्ण हो सकते हैं जिनकी {{< glossary_tooltip text="लेबल" term_id="label" >}} में अनुमति नहीं है। आप क्लाइंट जैसे टूल औ
```suggestion
एनोटेट किया गया मेटाडेटा छोटा या बड़ा, संरचित या असंरचित हो सकता है, और इसमें ऐसे वर्ण हो सकते हैं जिनकी {{< glossary_tooltip text="लेबल" term_id="label" >}} में अनुमति नहीं है। आप टूल और लाइब्रेरी जैसे क्लाइंट से मेटाडेटा पुनर्प्राप्त कर सकते हैं।
```
[Nit] Adds more clarity in my opinion.

2022-08-29 11:37 UTC, anubha-v-ardhan requested changes
@taniaduggal Thank you for committing the suggested changes, can you squash the commits please so we can get this pr ready for merge.

2022-11-19 14:24 UTC, closed without merging