[hi]Localize content/en/docs/reference/glossary/application-developer.md
kubernetes/website pull request #36101
Opened 2022-08-19 08:28 UTC by taniaduggal

Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>

Fixes #35600

2022-08-19 08:35 UTC, divya-mohan0209 requested changes
Slight grammatical nit.

2022-08-19 08:35 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/application-developer.md
> + एक व्यक्ति जो Kubernetes क्लस्टर में चलने वाला एप्लिकेशन लिखता है।
```suggestion
 एक व्यक्ति जो Kubernetes क्लस्टर में चलने वाले एप्लिकेशन लिखता है।
```

2022-08-19 08:35 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/application-developer.md
> + एक व्यक्ति जो Kubernetes क्लस्टर में चलने वाला एप्लिकेशन लिखता है।
```suggestion
 एक व्यक्ति जो Kubernetes क्लस्टर में चलने वाले एप्लिकेशन लिखता है।
```

2022-08-20 06:46 UTC, taniaduggal commented
@divya-mohan0209 I made suggested changes. I request you please fast review and merge it, as I am willing to participate in 1.26 release shadow program ,so at least some pr should be merge is a plus point in my application.
thanks:)

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-20 07:31 UTC, divya-mohan0209 reviewed
Looks good to me!

/lgtm

2022-08-20 07:41 UTC, taniaduggal commented
/assign @divya-mohan0209 

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-20 07:42 UTC, divya-mohan0209 commented
@taniaduggal I understand that you need this as a supplement to your application and I appreciate the check-in. However, please bear in mind that we're working through a backlog of docs reviews here and it's not just the Hindi localization that I'm talking about when I say that. As the docs co-chair, I'd request you to be empathetic and patient if your PR hasn't received a review in a few hours because there are other things that are a priority like the release artifacts/blogs that need to be published over the next week/two. We're all trying our best here to get to each PR submitted while fostering a healthy environment for all contributors. Would request that you wait for atleast a couple of days before pinging for a re-review either here or on Slack. Please do let me know if any questions.

2022-08-29 11:49 UTC, anubha-v-ardhan requested changes

2022-08-29 11:49 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/application-developer.md
> + एक व्यक्ति जो Kubernetes क्लस्टर में चलने वाले एप्लिकेशन लिखता है।
```suggestion
 एक व्यक्ति जो कुबेरनेट्स क्लस्टर में चलने वाले एप्लिकेशन लिखता है।
```

2022-08-29 11:49 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/application-developer.md
> + एक व्यक्ति जो Kubernetes क्लस्टर में चलने वाले एप्लिकेशन लिखता है।
```suggestion
 एक व्यक्ति जो कुबेरनेट्स क्लस्टर में चलने वाले एप्लिकेशन लिखता है।
```

2022-08-29 11:49 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/application-developer.md
> +एप्लिकेशन डेवलपर्स एप्लिकेशन के एक हिस्से पर ध्यान केंद्रित करते हैं। उनकी कार्य सीमा के आकार में एक उल्लेखनीय अंतर है।
```suggestion
एप्लिकेशन डेवलपर्स एप्लिकेशन के एक हिस्से पर ध्यान केंद्रित करते हैं। उनकी कार्य सीमा के आकार में एक उल्लेखनीय अंतर हो सकता है।
```

2022-08-29 11:50 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/application-developer.md
> + एक व्यक्ति जो Kubernetes क्लस्टर में चलने वाले एप्लिकेशन लिखता है।
We can localize Kubernetes.

2022-08-29 13:48 UTC, anubha-v-ardhan commented
> I have apply all changes @anubha-v-ardhan :)

Thank you, if you could squash the commits, we can get this pr ready for merge.

2022-11-22 02:26 UTC, divya-mohan0209 reviewed
/lgtm

2022-11-23 05:11 UTC, divya-mohan0209 commented
Hello @taniaduggal - please squash ALL the commits & let us know. We'll get another set of eyes to review & approve.

2022-12-20 05:17 UTC, divya-mohan0209 commented
Closing this PR since it is a duplicate of #38332 
/close

2022-12-20 05:17 UTC, closed without merging