[hi] Localize content/en/docs/reference/glossary/cni.md
kubernetes/website pull request #36104
Opened 2022-08-19 12:31 UTC by amolmote

Signed-off-by: amolmote <amolmote201@gmail.com> 
Fixes #35600

2022-08-20 03:06 UTC, amolmote commented
/easycla

2022-08-20 04:26 UTC, amolmote commented
/assign @divya-mohan0209

2022-08-20 04:46 UTC, divya-mohan0209 requested changes
Duplicate lines.

2022-08-20 04:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cni.md
> +* कुबेरनेट्स और CNI के बारे में जानकारी के लिए, देखें [यह](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni).
This is the same line as below.

2022-08-21 06:18 UTC, amolmote reviewed
please check changes again

2022-08-21 06:19 UTC, amolmote commented
/assign anubha-v-ardhan

2022-08-24 11:19 UTC, amolmote reviewed
please check changes again and merge it

2022-08-29 11:55 UTC, anubha-v-ardhan requested changes

2022-08-29 11:55 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cni.md
> +    कंटेनर नेटवर्क इंटरफेस (CNI) प्लगइन्स एक प्रकार का नेटवर्क प्लगइन है जो appc/CNI विनिर्देश का पालन करता है।
```suggestion
    कंटेनर नेटवर्क इंटरफेस (CNI) प्लगइन्स एक प्रकार का नेटवर्क प्लगइन हैं जो appc/CNI विनिर्देश का पालन करते हैं।
```

2022-08-29 11:55 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cni.md
> + कंटेनर नेटवर्क इंटरफ़ेस (CNI) प्लगइन एक प्रकार का नेटवर्क प्लगइन है जो appc/CNI विनिर्देश का पालन करता है।
```suggestion
 कंटेनर नेटवर्क इंटरफ़ेस (CNI) प्लगइन एक प्रकार का नेटवर्क प्लगइन हैं जो appc/CNI विनिर्देश का पालन करते हैं।
```

2022-08-29 11:55 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cni.md
> +* कुबेरनेट्स और CNI के बारे में जानकारी के लिए, देखें ["नेटवर्क प्लगइन्स"](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni)।
```suggestion
* कुबेरनेट्स और CNI के बारे में जानकारी के लिए, ["नेटवर्क प्लगइन्स"](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/#cni) देखें।
```

2022-08-29 12:27 UTC, amolmote commented
thank you @anubha-v-ardhan , I will  rebase all the commits.

2022-08-29 13:50 UTC, anubha-v-ardhan approved these changes
/lgtm
/assign
/approve

Thank you @amolmote :)

2022-08-29 13:52 UTC, merged