[hi] Localize config.md
kubernetes/website pull request #36109
Opened 2022-08-19 13:30 UTC by bishal7679

Signed-off-by: Bishal Das <bishalhnj127@gmail.com>

Localizes `content/en/docs/reference/scheduling/config.md` to Hindi `content/hi/docs/reference/scheduling/config.md`

Fixes :- #35250

2022-08-19 13:31 UTC, bishal7679 commented
/assign @divya-mohan0209

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

2022-08-29 11:57 UTC, anubha-v-ardhan reviewed
/retitle [hi] Localize content/en/docs/reference/scheduling/config.md

2022-11-22 02:46 UTC, divya-mohan0209 requested changes
I'd highly recommend that this file be updated in line with the latest version available in English & then submitted for review.

However, I've left an initial set of reviews to incorporate in the first few paragraphs.

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +title: सचेंडूलर कॉन्फ़िगरेशन
```suggestion
title: शेड्यूलर कॉन्फ़िगरेशन
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +आप `kube-scheduler` के व्यवहार को एक कॉन्फ़िगरेशन फ़ाइल लिखकर और उसके पथ को कमांड लाइन आर्गुमेंटक के रूप में पारित करके अनुकूलित कर सकते हैं।
```suggestion
आप `क्यूब-शेड्यूलर` के व्यवहार को एक कॉन्फ़िगरेशन फ़ाइल लिखकर और उसके पथ को कमांड लाइन आर्गुमेंट के रूप में पारित करके अनुकूलित कर सकते हैं।
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +{{< feature-state for_k8s_version="v1.19" state="beta" >}}
```suggestion
{{< feature-state for_k8s_version="v1.25" state="stable" >}}
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +{{< glossary_tooltip text="kube-scheduler" term_id="kube-scheduler" >}} में।
```suggestion
शेड्यूलिंग प्रोफ़ाइल आपको शेड्यूलिंग के विभिन्न चरणों को कॉन्फ़िगर करने की अनुमति देता है। 
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +शेड्यूलिंग प्रोफ़ाइल आपको शेड्यूलिंग के विभिन्न चरणों को कॉन्फ़िगर करने की अनुमति देता है
```suggestion
{{< glossary_tooltip text="kube-scheduler" term_id="kube-scheduler" >}} में
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +प्रत्येक चरण एक विस्तार बिंदु में उजागर होता है। प्लगइन्स शेड्यूलिंग व्यवहार प्रदान करते हैं
```suggestion
प्रत्येक चरण एक विस्तार बिंदु में उजागर होता है। इनमें से एक या अधिक विस्तार बिंदु को लागू करके
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +इनमें से एक या अधिक विस्तार बिंदु को लागू करके।
```suggestion
प्लगइन्स शेड्यूलिंग व्यवहार प्रदान करते हैं।
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +आप `kube-scheduler --config <filename>` चलाकर शेड्यूलिंग प्रोफाइल निर्दिष्ट कर सकते हैं,
```suggestion
KubeSchedulerConfiguration ([v1beta2](/docs/reference/config-api/kube-scheduler-config.v1beta2/)
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +का उपयोग
```suggestion
या [v1beta3](/docs/reference/config-api/kube-scheduler-config.v1beta3/)) संरचना
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +KubeSchedulerConfiguration ([v1beta2](/docs/reference/config-api/kube-scheduler-config.v1beta2/)
```suggestion
का उपयोग करके आप `kube-scheduler --config <filename>`
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +या [v1beta3](/docs/reference/config-api/kube-scheduler-config.v1beta3/))
```suggestion
चलाकर शेड्यूलिंग प्रोफाइल निर्दिष्ट कर सकते हैं। 
```

2022-11-22 02:46 UTC, divya-mohan0209 commented on content/hi/docs/reference/scheduling/config.md
> +संरचना।
```suggestion
```

2022-12-20 05:23 UTC, divya-mohan0209 commented
@bishal7679 : Has this file been updated to be in synch with the latest English file?

2023-03-26 06:05 UTC, divya-mohan0209 commented
Hello @bishal7679 , there has been no activity on the PR for ~3 months and I'll be closing this out due to inactivity. Please feel free to reopen when you have the bandwidth/cycles to address the feedback.
/close

2023-03-26 06:06 UTC, closed without merging