[hi] Localize content/en/docs/reference/glossary/cncf.md into Hindi
kubernetes/website pull request #36117
Opened 2022-08-20 04:18 UTC by amolmote

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #35600

2022-08-20 04:23 UTC, amolmote commented
/assign @mittalyashu

2022-08-20 05:36 UTC, amolmote commented
/unassign @mittalyashu

2022-08-20 06:35 UTC, anubha-v-ardhan requested changes
Thank you @amolmote

2022-08-20 06:35 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cncf.md
> + एक माइक्रोसर्विस आर्किटेक्चर के हिस्से के रूप में कंटेनरों को ओर्केस्ट्रेट करता है।
```suggestion
 क्लाउड नेटिव कंप्यूटिंग फाउंडेशन (CNCF) स्थायी पारिस्थितिकी तंत्र का निर्माण करता है और
 [परियोजना](https://www.cncf.io/projects/) के आसपास समुदाय को बढ़ावा देता है जो 
 एक माइक्रोसर्विस आर्किटेक्चर के हिस्से के रूप में कंटेनरों को ओर्केस्ट्रेट करता है।
```

2022-08-20 06:35 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cncf.md
> +कुबेरनेट्स एक CNCF प्रोजेक्ट है।
```suggestion
कुबेरनेट्स एक CNCF परियोजना है।
```

2022-08-20 06:35 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cncf.md
> +इसका मिशन क्लाउड नेटिव कंप्यूटिंग को सर्वव्यापी बनाना है।
```suggestion
CNCF [Linux फाउंडेशन](https://www.linuxfoundation.org/) का एक उप-संस्थान है।
इसका लक्ष्य क्लाउड नेटिव कंप्यूटिंग को सर्वव्यापी बनाना है।
```

2022-08-20 06:35 UTC, anubha-v-ardhan commented
/assign

2022-08-20 06:48 UTC, anubha-v-ardhan reviewed
Thanks for accepting the change suggestions. Can you squash the commits so we can get this PR ready for merge.

2022-08-21 06:52 UTC, closed without merging

2023-03-04 01:58 UTC, jihoon-seo commented
/remove-area blog release-eng
/remove-language de en es fr ja ko pt zh
/remove-sig release