[hi] Localize control-plane.md
kubernetes/website pull request #36123
Opened 2022-08-20 12:34 UTC by bishal7679

Signed-off-by: Bishal Das <bishalhnj127@gmail.com>

Localizes `content/en/docs/reference/glossary/control-plane.md` to Hindi `content/hi/docs/reference/glossary/control-plane.md`

Fixes :- #35600

2022-08-20 12:35 UTC, bishal7679 commented
/assign @anubha-v-ardhan

2022-08-22 16:30 UTC, Babapool commented on content/hi/docs/reference/glossary/control-plane.md
> +- {{< glossary_tooltip text="इटीसीडी" term_id="etcd" >}}
```suggestion
- {{< glossary_tooltip text="etcd" term_id="etcd" >}}
```

2022-08-22 16:34 UTC, Babapool commented on content/hi/docs/reference/glossary/control-plane.md
> +- {{< glossary_tooltip text="एपीआई सर्वर" term_id="kube-apiserver" >}}
```suggestion
- {{< glossary_tooltip text="API सर्वर" term_id="kube-apiserver" >}}
```

2022-08-22 16:58 UTC, Babapool commented on content/hi/docs/reference/glossary/control-plane.md
> +- {{< glossary_tooltip text="सचेंडूलर" term_id="kube-scheduler" >}}
`शेड्यूलर`  resembles the `scheduler` more phonetically.
```suggestion
- {{< glossary_tooltip text="शेड्यूलर" term_id="kube-scheduler" >}}
```

2022-08-22 17:14 UTC, Babapool commented on content/hi/docs/reference/glossary/control-plane.md
> +  कंटेनर ऑर्केस्ट्रेशन लेयर जो कंटेनरों के जीवनचक्र को परिभाषित, परिनियोजित और प्रबंधित करने के लिए एपीआई और इंटरफेस को उजागर करता है।
Just a small nit:
```suggestion
  कंटेनर ऑर्केस्ट्रेशन लेयर जो कंटेनरों के जीवनचक्र को परिभाषित, परिनियोजित और प्रबंधित करने के लिए API और इंटरफेस को उजागर करता है।
```

2022-08-22 18:16 UTC, bishal7679 commented
@Babapool Nice suggestions
But Can you tell me how to do that?
like how you added commit in my PR as a suggestion?

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :question: I have a question

2022-11-23 05:39 UTC, divya-mohan0209 requested changes

2022-11-23 05:39 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/control-plane.md
> +title: कण्ट्रोल प्लेन (Control Plane)
```suggestion
title: कंट्रोल प्लेन (Control Plane)
```

2022-11-23 05:39 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/control-plane.md
> +इन घटकों को पारंपरिक ऑपरेटिंग सिस्टम सेवाओं (डेमॉन) या कंटेनर के रूप में चलाया जा सकता है। इन घटकों को चलाने वाले मेजबानों को ऐतिहासिक रूप से {{< glossary_tooltip text="मास्टरस" term_id="master" >}}
```suggestion
इन घटकों को पारंपरिक ऑपरेटिंग सिस्टम सेवाओं (डैमन) या कंटेनर के रूप में चलाया जा सकता है। इन घटकों को चलाने वाले मेजबानों को ऐतिहासिक रूप से {{< glossary_tooltip text="मास्टर्स" term_id="master" >}} कहा जाता था।
```

2022-11-23 05:40 UTC, divya-mohan0209 submitted a review, later dismissed
Additional set of nits

2022-11-23 05:40 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/control-plane.md
> +- {{< glossary_tooltip text="API सर्वर" term_id="kube-apiserver" >}}
```suggestion
- {{< glossary_tooltip text="क्यूब-API सर्वर" term_id="kube-apiserver" >}}
```

2022-11-23 05:40 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/control-plane.md
> +- {{< glossary_tooltip text="शेड्यूलर" term_id="kube-scheduler" >}}
```suggestion
- {{< glossary_tooltip text="क्यूब-शेड्यूलर" term_id="kube-scheduler" >}}
```

2022-12-20 05:29 UTC, divya-mohan0209 commented
@bishal7679 : Please retain only one PR among #36121 & aggregate all the suggestions in one of them.

2022-12-20 05:30 UTC, divya-mohan0209 commented
@bishal7679 Any update on this?

2022-12-22 01:53 UTC, divya-mohan0209 reviewed
Small nit. Otherwise LGTM.

2022-12-22 01:53 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/control-plane.md
> +इन घटकों को पारंपरिक ऑपरेटिंग सिस्टम सेवाओं (डैमन) या कंटेनर के रूप में चलाया जा सकता है। इन घटकों को चलाने वाले मेजबानों को ऐतिहासिक रूप से {{< glossary_tooltip text="मास्टर्स" term_id="master" >}}
```suggestion
इन घटकों को पारंपरिक ऑपरेटिंग सिस्टम सेवाओं (डेमॉन) या कंटेनर के रूप में चलाया जा सकता है। इन घटकों को चलाने वाले मेजबानों को ऐतिहासिक रूप से {{< glossary_tooltip text="मास्टर्स" term_id="master" >}} कहा जाता था।
```

2022-12-22 04:16 UTC, Babapool commented
@bishal7679 can you please squash your commits to make the PR ready to merge. Thanks.

2023-03-25 16:53 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2023-03-25 16:55 UTC, divya-mohan0209 reviewed
@Babapool : Please can you LGTM it if everything looks okay? I've added the squash commits label since this has been pending for quite some time now.

/approve

2023-03-26 06:29 UTC, Babapool reviewed
Thanks!
/lgtm

2023-03-26 06:29 UTC, merged