[hi]Localize content/en/docs/reference/glossary/cgroup.md
kubernetes/website pull request #36185
Opened 2022-08-23 07:30 UTC by taniaduggal

Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>
fixes #35600

2022-08-26 05:08 UTC, taniaduggal commented
@anubha-v-ardhan Please review :)

2022-08-29 12:05 UTC, anubha-v-ardhan requested changes

2022-08-29 12:05 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cgroup.md
> +  Linux प्रक्रियाओं का एक समूह जो चुनिंदा रूप से संसाधनों को अलग, प्रबंधित और प्रतिबंधित करता है।
```suggestion
  Linux प्रक्रियाओं (processes) का एक समूह जो चुनिंदा रूप से संसाधनों को अलग, प्रबंधित और प्रतिबंधित करता है।
```
I think having processes written in brakets makes this easier to understand for some people?

2022-08-29 12:05 UTC, anubha-v-ardhan commented on content/hi/docs/reference/glossary/cgroup.md
> +Linux प्रक्रियाओं का एक समूह जो चुनिंदा रूप से संसाधनों को अलग, प्रबंधित और प्रतिबंधित करता है।
```suggestion
Linux प्रक्रियाओं (processes) का एक समूह जो चुनिंदा रूप से संसाधनों को अलग, प्रबंधित और प्रतिबंधित करता है।
```
same as above

2022-08-29 13:49 UTC, anubha-v-ardhan requested changes
Thank you @taniaduggal. Can you please squash the commits so we can get this PR ready for merge.

2022-11-28 02:17 UTC, divya-mohan0209 commented
@taniaduggal : Please sync your fork & squash commits so that we can proceed with merge.

2022-11-28 15:55 UTC, taniaduggal commented
@divya-mohan0209 i think i already squash the commits

2023-01-02 05:36 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cgroup.md
> +cgroup एक Linux कर्नेल सुविधा है जो प्रक्रियाओं के एक सेट के लिए संसाधन उपयोग (CPU, मेमोरी, डिस्क I/O, नेटवर्क) को अलग, प्रबंधित और सीमित करता है।
```suggestion
cgroup एक Linux कर्नल सुविधा है जो प्रक्रियाओं के एक समूह के लिए संसाधन उपयोग (CPU, मेमोरी, डिस्क I/O, नेटवर्क) को अलग, प्रबंधित, और सीमित करता है।
```

2023-01-17 05:18 UTC, divya-mohan0209 commented
Duplicate of #38954 
/close

2023-01-17 05:18 UTC, closed without merging