[hi] Localize cloud-provider.md
kubernetes/website pull request #36239
Opened 2022-08-24 15:29 UTC by bishal7679

Signed-off-by: Bishal Das <bishalhnj127@gmail.com>

Localizes `content/en/docs/reference/glossary/cloud-provider.md` to Hindi `content/hi/docs/reference/glossary/cloud-provider.md`

Fixes :- #35600

2022-08-31 13:43 UTC, Babapool reviewed
Hope you find these suggestions useful:

2022-08-31 13:43 UTC, Babapool commented on content/hi/docs/reference/glossary/cloud-provider.md
> +कई क्लाउड प्रदाता प्रबंधित अवसंरचना प्रदान करते हैं (जिन्हें Infrastructure as a Service या IaaS भी कहा जाता है)। प्रबंधित अवसंरचना के साथ क्लाउड प्रदाता सर्वर स्टोरेज और नेटवर्किंग प्रदान करने के लि
This makes the sentence a little better to read. Thoughts WDYT @bishal7679? 
```suggestion
कई क्लाउड प्रदाता प्रबंधित अवसंरचना प्रदान करते हैं (जिन्हें Infrastructure as a Service या IaaS भी कहा जाता है)। प्रबंधित अवसंरचना के साथ क्लाउड प्रदाता सर्वर, स्टोरेज और नेटवर्किंग प्रदान करने के लिए जिम्मेदार है जबकि आप उसके ऊपरी लेयर्स का प्रबंधन करते हैं जैसे कि  कुबेरनेट्स क्लस्टर चलाना।
```

2022-08-31 13:43 UTC, Babapool commented on content/hi/docs/reference/glossary/cloud-provider.md
> +आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कण्ट्रोल प्लेन के साथ
This makes the sentence a little better to read. Thoughts WDYT @bishal7679?
```suggestion
आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कण्ट्रोल प्लेन के साथ-साथ {{< glossary_tooltip term_id="नोड" text="nodes" >}} और जिस अवसंरचना पर वे भरोसा करते हैं: नेटवर्किंग, स्टोरेज, और संभवतः अन्य तत्व जैसे लोड बैलेंसर्स के लिए जिम्मेदार है।
```

2022-12-23 01:47 UTC, divya-mohan0209 requested changes
Please could you amend this? It is the reason why the build is failing.

2022-12-23 01:47 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cloud-provider.md
> +आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कण्ट्रोल प्लेन के साथ
```suggestion
आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कण्ट्रोल प्लेन के साथ-साथ {{< glossary_tooltip text="नोड" term_id="nodes" >}} और जिस अवसंरचना पर वे भरोसा करते हैं: नेटवर्किंग, स्टोरेज, और संभवतः अन्य तत्व जैसे लोड बैलेंसर्स के लिए जिम्मेदार है।
```

2022-12-23 02:48 UTC, divya-mohan0209 requested changes

2022-12-23 02:48 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cloud-provider.md
> +एक व्यवसाय या अन्य संगठन जो क्लाउड कंप्यूटिंग प्लेटफॉर्म प्रदान प्रदान करते हैं।
```suggestion
एक व्यवसाय या अन्य संगठन जो क्लाउड कंप्यूटिंग प्लेटफॉर्म प्रदान करता हैं।
```

2022-12-23 02:48 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cloud-provider.md
> +आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कण्ट्रोल प्लेन के साथ
```suggestion
आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कंट्रोल प्लेन के साथ-साथ {{< glossary_tooltip text="नोड" term_id="node" >}} और जिस अवसंरचना पर वे भरोसा करते हैं: नेटवर्किंग, स्टोरेज, और संभवतः अन्य तत्व जैसे लोड बैलेंसर्स के लिए जिम्मेदार है।
```

2023-01-02 05:43 UTC, divya-mohan0209 requested changes
Just one slight nit based on the files from other localization.

2023-01-02 05:43 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cloud-provider.md
> +  - Cloud Service Provider
```suggestion
  - क्लाउड सेवा प्रदाता (Cloud Service Provider)
```

2023-01-03 12:22 UTC, Babapool reviewed
Thanks!
/lgtm

2023-01-17 05:16 UTC, divya-mohan0209 requested changes
I'd be happy to approve & lgtm once the changes are made.

2023-01-17 05:16 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cloud-provider.md
> +आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कंट्रोल प्लेन के साथ-
Too many "साथ" in one sentence. Eliminated this to retain conciseness without taking away from the meaning.
```suggestion
आप कुबेरनेट्स को एक प्रबंधित सेवा के रूप में भी पा सकते हैं; कई बार इसे Platform as a Service, या PaaS भी कहा जाता है। प्रबंधित कुबेरनेट्स के साथ, आपका क्लाउड प्रदाता कुबेरनेट्स कंट्रोल प्लेन{{< glossary_tooltip text="नोड" term_id="node" >}} और जिस अवसंरचना पर वे भरोसा करते हैं: नेटवर्किंग, स्टोरेज, और संभवतः अन्य तत्व जैसे लोड बैलेंसर्स के लिए जिम्मेदार है।
```

2023-01-17 05:19 UTC, bishal7679 commented
/cc @divya-mohan0209

2023-01-17 05:22 UTC, divya-mohan0209 reviewed
/lgtm
/approve

2023-01-17 05:24 UTC, merged