[zh-cn]Sync  persistent-volume-v1.md
kubernetes/website pull request #36246
Opened 2022-08-24 16:29 UTC by yanrongshi

Sync upstrem
```yaml
content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
```

2022-08-25 03:10 UTC, howieyuen requested changes

2022-08-25 03:10 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> +    从而传递到 CSI 驱动以完成 CSI NodePublishVolume 和 NodeUnpublishVolume 调用。
how about this ? “以传递到” or “该对象将传递到”
```suggestion
    以传递到 CSI 驱动以完成 CSI NodePublishVolume 和 NodeUnpublishVolume 调用。
```

2022-08-25 03:10 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> +      name 在名字空间内是唯一的，以引用一个 Secret 资源。
ctrl+c/v? 🤣 
```suggestion
      namespace 定义了 Secret 名称必须唯一的空间。
```

2022-08-25 06:13 UTC, howieyuen commented
/approve

2022-08-25 06:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> +<!--
```suggestion
  <!--
```

2022-08-25 06:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> +-->
```suggestion
  -->
```

2022-08-25 06:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> +  - **csi.nodePublishSecretRef** (SecretReference)
720 行之前加空行

2022-08-25 06:47 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> +    <a name="SecretReference"></a>
727 行删除

2022-08-25 11:24 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-v1.md
> +    - **csi.nodePublishSecretRef** (SecretReference)
720 行要保持原来的缩进，并且前面要加一个空行（markdown 解析限制）。

2022-08-25 11:28 UTC, tengqm commented
Preview 不正确

<img width="750" alt="image" src="https://user-images.githubusercontent.com/5094756/186652618-fc7b7022-7a17-48fa-8b0b-0e7cfdd27690.png">

2022-08-25 13:14 UTC, yanrongshi commented
> Preview 不正确
> 
> <img alt="image" width="750" src="https://user-images.githubusercontent.com/5094756/186652618-fc7b7022-7a17-48fa-8b0b-0e7cfdd27690.png">

这种的我可以理解为正确的吧
<img width="903" alt="image" src="https://user-images.githubusercontent.com/29862632/186674481-deca9fea-958c-439b-80aa-2553528758f1.png">

2022-08-25 22:17 UTC, windsonsea commented
The old zh-cn text also has some alignment error:

![image](https://user-images.githubusercontent.com/79828097/186778536-3739f1a0-6fdf-4dfb-833d-165f1ecf7fe6.png)

2022-08-27 04:42 UTC, closed without merging

2022-08-27 04:44 UTC, yanrongshi commented
Due to some unknown issues, my local fix could not be submitted to the cloud, so I resubmitted a PR about: #36347