[zh] Reformat kubeadm-init-phase-kfa page
kubernetes/website pull request #36310
Opened 2022-08-26 03:50 UTC by tengqm

This PR converts the DOS style EOL to UNIX style.

2022-08-26 11:39 UTC, howieyuen requested changes

2022-08-26 11:39 UTC, howieyuen commented on content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_init_phase_kubelet-finalize_all.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>[实验] 到'真实'主机根文件系统的路径。</p></td>
```suggestion
<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>[实验]到“真实”主机根文件系统的路径。</p></td>
```

2022-08-28 23:01 UTC, Sea-n reviewed
/approve

2022-08-29 01:16 UTC, windsonsea commented
/lgtm

2022-08-29 01:30 UTC, merged