[zh] Convert format for kubeadm-upgrade-npp page
kubernetes/website pull request #36313
Opened 2022-08-26 03:59 UTC by tengqm

This PR converts the EOL style from DOS to UNIX.

2022-08-26 11:41 UTC, howieyuen requested changes

2022-08-26 11:41 UTC, howieyuen commented on content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_preflight.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>错误将显示为警告的检查清单。示例：'IsPrivilegedUser,Swap'。值为'all'表示忽略所有检查的错误。</p></td>
```suggestion
<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>错误将显示为警告的检查清单。示例：“IsPrivilegedUser,Swap”。值为 “all” 表示忽略所有检查的错误。</p></td>
```

2022-08-26 11:41 UTC, howieyuen commented on content/zh-cn/docs/reference/setup-tools/kubeadm/generated/kubeadm_upgrade_node_phase_preflight.md
> +<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>[实验] 到'真实'主机根文件系统的路径。</p></td>
```suggestion
<td></td><td style="line-height: 130%; word-wrap: break-word;"><p>[实验]到“真实”主机根文件系统的路径。</p></td>
```

2022-08-28 23:00 UTC, Sea-n reviewed
/approve

2022-08-29 01:16 UTC, windsonsea commented
/lgtm

2022-08-29 01:32 UTC, merged