Add a note on the pre-provisioned snapshot scenario
kubernetes/website pull request #36407
Opened 2022-08-30 04:56 UTC by johnlinp

I found it confusing when filling a non-existing
volumeSnapshotContentName when creating a VolumeSnapshot in the
pre-provisioned mode. I hope this note can clear up some
confusion.

Signed-off-by: John Lin <johnlinp@gmail.com>

2022-09-01 07:27 UTC, divya-mohan0209 requested changes
Omitting the please since I don't think we require otherwise lgtm!

2022-09-01 07:27 UTC, divya-mohan0209 commented on content/en/docs/concepts/storage/volume-snapshots.md
> +For pre-provisioned snapshots, you need to specify a `volumeSnapshotContentName` as the source for the snapshot as shown in the following example. The `volumeSnapshotContentName` source field is requ
```suggestion
For pre-provisioned snapshots, you need to specify a `volumeSnapshotContentName` as the source for the snapshot as shown in the following example. The `volumeSnapshotContentName` source field is required for pre-provisioned snapshots. Note that the corresponding `VolumeSnapshotContent` object doesn't have to exist at the timing of the creation of the `VolumeSnapshot` object.
```

2022-09-01 07:28 UTC, divya-mohan0209 commented
@kubernetes/sig-storage-pr-reviews : Please could you sign this off from a technical standpoint?

2022-09-01 08:05 UTC, johnlinp commented
I would like to confirm: in the "pre-provisioning" scenario, is it a common use case to create the `VolumeSnapshot` before the creation of `VolumeSnapshotContent`? Or is it the other way around? Thank you.

2022-09-01 17:16 UTC, johnlinp commented on content/en/docs/concepts/storage/volume-snapshots.md
> +For pre-provisioned snapshots, you need to specify a `volumeSnapshotContentName` as the source for the snapshot as shown in the following example. The `volumeSnapshotContentName` source field is requ
It's done. Thank you!

2022-09-01 23:36 UTC, xing-yang commented
> I would like to confirm: in the "pre-provisioning" scenario, is it a common use case to create the VolumeSnapshot before the creation of VolumeSnapshotContent? Or is it the other way around? Thank you.

Normally it is the other way around. So I think adding this note is more confusing.

2022-09-02 03:16 UTC, xing-yang commented
/lgtm

2022-09-02 03:54 UTC, johnlinp commented
/assign @natalisucks

2022-09-02 04:53 UTC, divya-mohan0209 requested changes
Grammatical nit.

2022-09-02 04:53 UTC, divya-mohan0209 commented on content/en/docs/concepts/storage/volume-snapshots.md
> +`volumeSnapshotRef` is the reference of the correspinding `VolumeSnapshot`. Note that when the `VolumeSnapshotContent` is being created as a pre-provisioned snapshot, the `VolumeSnapshot` referenced
nit: Grammar
```suggestion
`volumeSnapshotRef` is the reference of the corresponding `VolumeSnapshot`. Note that when the `VolumeSnapshotContent` is being created as a pre-provisioned snapshot, the `VolumeSnapshot` referenced in `volumeSnapshotRef` might not exist yet.
```

2022-09-02 05:58 UTC, johnlinp commented on content/en/docs/concepts/storage/volume-snapshots.md
> +`volumeSnapshotRef` is the reference of the correspinding `VolumeSnapshot`. Note that when the `VolumeSnapshotContent` is being created as a pre-provisioned snapshot, the `VolumeSnapshot` referenced
Thanks! It's fixed now.

2022-09-02 08:13 UTC, natalisucks commented
Thanks for contributing!
/lgtm

2022-09-02 14:31 UTC, sftim commented
Thanks

/approve

2022-09-02 14:32 UTC, merged