Updated Japanese translation for the /content/ja/docs/concepts/workloads/controllers/replicaset.md file
kubernetes/website pull request #36482
Opened 2022-09-01 05:03 UTC by ziyi-xie

There are several updates in [the original English text](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/controllers/replicaset.md) and therefore this page is outdated.
This PR updated Japanese translation for the [/content/ja/docs/concepts/workloads/controllers/replicaset.md](https://kubernetes.io/ja/docs/concepts/workloads/controllers/replicaset/) file.

Fixes https://github.com/kubernetes/website/issues/36268

2022-09-01 07:31 UTC, ziyi-xie commented
/cc @atoato88 @t-inu 
Hi! I've updated Japanese translation for the [/content/ja/docs/concepts/workloads/controllers/replicaset.md](https://kubernetes.io/ja/docs/concepts/workloads/controllers/replicaset/) file, would you mind checking if everything looks alright at your convenience time please? Here is [the original English text](https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/workloads/controllers/replicaset.md) and thank you so much!

2022-09-01 07:40 UTC, Arhell reviewed
/assign @nasa9084

2022-09-01 10:47 UTC, nasa9084 requested changes

2022-09-01 10:47 UTC, nasa9084 commented on content/ja/docs/concepts/workloads/controllers/replicaset.md
> +[`controller.kubernetes.io/pod-deletion-cost`](/docs/reference/labels-annotations-taints/#pod-deletion-cost)  アノテーションを使用すると、ReplicaSetをスケールダウンする際に、どのPodを最初に削除するかについて、ユーザーが優先順位を設定することができます。
```suggestion
[`controller.kubernetes.io/pod-deletion-cost`](/docs/reference/labels-annotations-taints/#pod-deletion-cost)アノテーションを使用すると、ReplicaSetをスケールダウンする際に、どのPodを最初に削除するかについて、ユーザーが優先順位を設定することができます。
```

2022-09-01 12:43 UTC, ziyi-xie commented on content/ja/docs/concepts/workloads/controllers/replicaset.md
> + 4. Podの作成時間が異なる場合、より新しく作成されたPodが古いPodより優先されます(`LogarithmicScaleDown` [フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)が有効の場合、作成時間は整数対数スケールでバケット化されます。)
```suggestion
 4. Podの作成時間が異なる場合、より新しく作成されたPodが古いPodより優先されます(`LogarithmicScaleDown`[フィーチャーゲート](/ja/docs/reference/command-line-tools-reference/feature-gates/)が有効の場合、作成時間は整数対数スケールでバケット化されます。)
```

2022-09-01 12:43 UTC, ziyi-xie commented on content/ja/docs/concepts/workloads/controllers/replicaset.md
> + 2. `controller.kubernetes.io/pod-deletion-cost` アノテーションが設定されている場合、値の小さいPodが優先されます。
```suggestion
 2. `controller.kubernetes.io/pod-deletion-cost`アノテーションが設定されている場合、値の小さいPodが優先されます。
```

2022-09-02 10:12 UTC, t-inu reviewed
I left some comments.

2022-09-02 10:12 UTC, t-inu commented on content/ja/docs/concepts/workloads/controllers/replicaset.md
> +* [Deployments](/ja/docs/concepts/workloads/controllers/deployment/)について学ぶ。
```suggestion
* [Deployment](/ja/docs/concepts/workloads/controllers/deployment/)について学ぶ。
```

2022-09-05 03:52 UTC, atoato88 reviewed
Please check mu comments.

2022-09-05 03:52 UTC, atoato88 commented on content/ja/docs/concepts/workloads/controllers/replicaset.md
> +ReplicaSetは、Node上のいくつかのKubeletのようなエージェントに対して、ローカルのコンテナ再起動を移譲します。
```suggestion
ReplicaSetは、KubeletのようなNode上のいくつかのエージェントに対して、ローカルのコンテナ再起動を移譲します。
```
Your translation is also OK, but my suggestion is good for avoiding some ambiguities, I think.

2022-09-05 22:28 UTC, atoato88 commented
/lgtm
Thank you for quick update.

2022-09-06 00:50 UTC, t-inu commented
/label tide/merge-method-squash
LGTM

2022-09-06 15:56 UTC, nasa9084 commented
/approve

2022-09-06 15:57 UTC, merged