[zh-cn] add blog/2022-09-02-cosi-kubernetes-object-storage-management.md
kubernetes/website pull request #36586
Opened 2022-09-04 10:48 UTC by my-git9

[zh-cn] add blog/2022-09-02-cosi-kubernetes-object-storage-management.md

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +title: "COSI 简介：使用 Kubernetes API 的对象存储管理"
```suggestion
title: "COSI 简介：使用 Kubernetes API 管理对象存储"
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +
```suggestion
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +本文介绍了容器对象存储接口 (COSI)，它是在 Kubernetes 中供给和使用对象存储的标准。
```suggestion
本文介绍了容器对象存储接口 (COSI)，这是在 Kubernetes 中制备和消耗对象存储的一个标准。
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +它是 Kubernetes v1.25 中的一个 alpha 功能。
```suggestion
它是 Kubernetes v1.25 中的一个 Alpha 特性。
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +对象存储范式促进了计算和存储的分解,，这是通过网络而不是本地提供数据来完成的。
```suggestion
对象存储范式促进了计算和存储的分解，这是通过网络而不是本地提供数据来完成的。
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +分解架构允许计算工作负载是无状态的，从而使它们更易于管理、扩展和自动化。
```suggestion
分解的架构允许计算工作负载是无状态的，从而使它们更易于管理、扩缩和自动化。
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +* Kubernetes 原生 - 使用 Kubernetes API 来配置、配置和管理 Bucket
```suggestion
* Kubernetes 原生 - 使用 Kubernetes API 来制备、配置和管理 Bucket
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +* 自助服务 - 管理和运营 (DevOps) 之间的明确划分，为 DevOps 人员启用自助服务能力
```suggestion
* 自助服务 - 明确划分管理和运营 (DevOps)，为 DevOps 人员赋予自助服务能力
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +* 可移植性——通过跨 Kubernetes 集群和跨对象存储供应商的可移植性实现供应商中立性
```suggestion
* 可移植性 - 通过跨 Kubernetes 集群和跨对象存储供应商的可移植性实现供应商中立性
```

2022-09-04 14:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +例如，可以从 AWS S3 移植到 Ceph，或从 AWS S3 移植到 MinIO 并返回，因为它们都使用 S3 API。
```suggestion
例如，可以从 AWS S3 移植到 Ceph，或从 AWS S3 移植到 MinIO 以及反向操作，因为它们都使用 S3 API。
```

2022-09-05 09:32 UTC, zhangxyjlu commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +而无需更改应用程序定义（PodTemplates、StatefulSets、部署等）。这只有在源和目标提供者使用相同的数据时才有可能。
Deployment 不需要翻译

2022-09-05 09:32 UTC, zhangxyjlu commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +令人惊叹的 sig-storage-cosi 社区一直在努力将 COSI 标准带入 alpha 状态。
```suggestion
令人惊叹的 sig-storage-cosi 社区一直在努力将 COSI 标准带入 Alpha 状态。
```

2022-09-05 11:21 UTC, howieyuen requested changes

2022-09-05 11:21 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +COSI 接口 以 Bucket 为中心，因为 Bucket 是对象存储的抽象单元。COSI 定义了三个旨在管理它们的 Kubernetes API
标题后需空行

2022-09-05 11:21 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +除了提供 kubernetes-API 驱动的 Bucket 管理之外，COSI 还旨在使 DevOps 人员能够自行配置和管理 Bucket，
标题后需空行

2022-09-05 11:21 UTC, howieyuen commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +而无需管理员干预。 这进一步使开发团队能够实现更快的周转时间和更快的上市时间。
```suggestion
而无需管理员干预。这进一步使开发团队能够实现周转时间更短，上市更快。
```

2022-09-05 12:34 UTC, my-git9 commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +分解架构允许计算工作负载是无状态的，从而使它们更易于管理、扩展和自动化。
存储一般是不可缩容的

2022-09-09 11:54 UTC, Sea-n reviewed
/approve

2022-09-09 11:54 UTC, Sea-n commented on content/zh-cn/blog/_posts/2022-09-02-cosi-kubernetes-object-storage-management.md
> +**作者:** Sidhartha Mani ([Minio, Inc](https://min.io))
```suggestion
**作者：**Sidhartha Mani ([Minio, Inc](https://min.io))
```

2022-09-14 13:22 UTC, windsonsea commented
/lgtm

2022-09-14 13:23 UTC, merged