Issue_#36386
kubernetes/website pull request #36592
Opened 2022-09-04 17:24 UTC by YashPimple

2022-09-04 21:07 UTC, sftim commented
/retitle Update namespaces page

Please also fill in the PR description to explain why you are making this change. Then, reviewers can look at the change you're making and see how well those changes match up with the need for a fix.

2022-09-04 23:43 UTC, tengqm commented on content/en/docs/concepts/workloads/pods/user-namespaces.md
> +show the user ID or user name.
Still, this text is confusing. If the `ps` command doesn't show the user ID or the user name, what does "The user `ps` shows ..." mean?

2022-09-05 04:42 UTC, divya-mohan0209 requested changes
I've phrased this a bit better. WDYT?

2022-09-05 04:42 UTC, divya-mohan0209 commented on content/en/docs/concepts/workloads/pods/user-namespaces.md
> +doesn't have privileges on the host. You can verify it from the host by checking the user's
```suggestion
doesn't have privileges on the host. You can verify this, for example, if you
```

2022-09-05 04:42 UTC, divya-mohan0209 commented on content/en/docs/concepts/workloads/pods/user-namespaces.md
> +container in which the process `ps` is running. The user `ps` shows is not the same as the user
```suggestion
check the user that the container process is running as by executing `ps` on the host. The user
```

2022-09-05 04:42 UTC, divya-mohan0209 commented on content/en/docs/concepts/workloads/pods/user-namespaces.md
> +you see if the command `id` is execute inside the container. The command `ps` command doesn't
```suggestion
in the output of the `ps` command is not the same if you execute the command `id` inside the
```

2022-09-05 04:42 UTC, divya-mohan0209 commented on content/en/docs/concepts/workloads/pods/user-namespaces.md
> +show the user ID or user name.
```suggestion
container.
```

2022-09-05 13:50 UTC, YashPimple commented
> I've phrased this a bit better. WDYT?

Sure I would implement it.

2022-09-08 07:11 UTC, dilyanpalauzov commented
The documentation of user-namespaces by CRI-O is described at https://github.com/cri-o/cri-o/blob/main/tutorials/userns.md . It says that the user `containers` must exist on the host, and it must be present in the `/etc/subuid` and `/etc/subgid` files.  The user namespace mode is utilized by pods with the `io.kubernetes.cri-o.userns-mode` annotation.  User-namespace pods can mount `Directory` volumes.

The description at https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/ does not say under which host user are the pods running (cf. CRI-O which uses the `containers` user) and it states that `Directory` voluimes cannot be used.

Please extend both https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/ and the upcoming blog entry 2022-10-03-add-userns-alpha with information about the host user, under which the containers will be running and state, if the user must be in the ` /etc/subuid` and `/etc/subgid` files.

Why can’t a `hostUsers: false` pod use a Directory volume, but a Pod with the annotation `io.kubernetes.cri-o.userns-mode` can?

2022-09-08 11:04 UTC, sftim commented
@dilyanpalauzov are you asking that @YashPimple update the upcoming blog entry? That seems a big ask. Maybe you'd be willing to file an issue that records the changes you'd like to see.

2022-09-08 11:09 UTC, dilyanpalauzov commented
I am saying what currently is unclear to me.  If my hint is not sufficient to initiate improvements on the documentation, I doubt that any more formal requests will achieve it.

The missing peaces are both relevant to https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/ and the upcoming blog entry.

2022-09-08 12:10 UTC, sftim commented
> I am saying what currently is unclear to me. If my hint is not sufficient to initiate improvements on the documentation, I doubt that any more formal requests will achieve it.

In this instance @dilyanpalauzov I'm confident you're wrong - for open source, filing an issue is a great way to flag work up to the volunteers who might pick it up. It sounds like you wouldn't be willing to in this case, and that's OK.

2022-09-08 12:17 UTC, dilyanpalauzov commented
> In this instance @dilyanpalauzov I'm confident you're wrong - for open source, filing an issue is a great way to flag work up to the volunteers who might pick it up. It sounds like you wouldn't be willing to in this case, and that's OK.

In case of Kubernetes, most of the issues I opened were automatically closed after three months of inactivity.

2022-09-10 15:15 UTC, YashPimple commented
/assign

2022-09-19 16:04 UTC, Sea-n commented
I've see you opened PR #36738 and #36867 for the same fix, close the old one as duplicated.
/close

2022-09-19 16:04 UTC, closed without merging