[hi] Localize content/en/docs/reference/glossary/daemonset.md
kubernetes/website pull request #36652
Opened 2022-09-07 09:41 UTC by taniaduggal

Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>

Fixes #35600

2022-11-22 09:31 UTC, Garima-Negi requested changes

2022-11-22 09:31 UTC, Garima-Negi commented on content/hi/docs/reference/glossary/daemonset.md
> +सुनिश्चित करें कि {{<glossary_tooltip text="पॉड" term_id="pod" >}} की प्रतिकृति {{<glossary_tooltip text="क्लस्टर " term_id="cluster" >}} में नोड्स के एक सेट पर चल रही है।
suggestion: `सुनिश्चित करता है ..`

2022-11-22 09:31 UTC, Garima-Negi commented on content/hi/docs/reference/glossary/daemonset.md
> +आमतौर पर सिस्टम डेमॉन जैसे लॉग कलेक्टर(log collectors) और मॉनिटरिंग एजेंट(monitoring agents) को तैनात करने के लिए उपयोग किया जाता है जो प्रत्येक{{< glossary_tooltip text="नोड" term_id="node">}} पर चल
daemon should be डेमन  instead of डेमॉन

2023-01-20 02:16 UTC, divya-mohan0209 commented
#38957 has been opened to fix the changes. Closing the PR.
/close

2023-01-20 02:16 UTC, closed without merging