[zh-cn]Add content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
kubernetes/website pull request #36662
Opened 2022-09-07 15:34 UTC by yanrongshi

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +title: “Kubernetes 1.25：对使用用户名字空间运行 Pod 的 Alpha 支持”
```suggestion
title: “Kubernetes 1.25：对使用用户名字空间运行 Pod 提供 Alpha 支持”
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +**作者:** Rodrigo Campos（Microsoft），Giuseppe Scrivano（Red Hat）
```suggestion
**作者：** Rodrigo Campos（Microsoft）、Giuseppe Scrivano（Red Hat）
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +因此添加了一个新的安全层来保护在同一系统上运行的其它 Pod。
```suggestion
因此添加了一个新的安全层来避免其他 Pod 运行在同一系统上。
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +此外，在新用户名字空间中授予的功能不适用于主机初始名字空间。
```suggestion
此外，在新用户名字空间中授予的权能不适用于主机初始名字空间。
```
Make the trans different if the source is different:
- Feature 特性
- Function 功能
- Capability 能力、权能

Check through please.

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +在用户名字空间中，我们可以将 Pod 内的 root 用户映射到容器外的非零 ID，容器将认为是 root 身份在运行，而从主机的角度来看，它们是常规的非特权 ID。
```suggestion
在用户名字空间中，我们可以将 Pod 内的 root 用户映射到容器外的非零 ID，
容器将认为是 root 身份在运行，而从主机的角度来看，它们是常规的非特权 ID。
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +目前，对用户名字空间的支持是可选的，因此你必须在 Pod 规范部分将 `hostUsers` 设置为 `false` 以启用用户名字空间：
```suggestion
目前，对用户名字空间的支持是可选的，因此你必须在 Pod 规约部分将 `hostUsers` 设置为 `false` 以启用用户名字空间：
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +  进一步了解，请参阅 Containerd issue[#7063][Containerd 用户问题]。
```suggestion
  进一步了解，请参阅 Containerd issue [#7063][containerd-userns-issue]。
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +[containerd-用户问题]: https://github.com/containerd/containerd/issues/7063
```suggestion
[containerd-userns-issue]: https://github.com/containerd/containerd/issues/7063
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +- [邮件类标](https://groups.google.com/forum/#!forum/kubernetes-sig-node)
```suggestion
- [邮件列表](https://groups.google.com/forum/#!forum/kubernetes-sig-node)
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +- [Open Community Issues/PRs](https://github.com/kubernetes/community/labels/sig%2Fnode)
```suggestion
- [开源社区的 Issue/PR](https://github.com/kubernetes/community/labels/sig%2Fnode)
```

2022-09-09 01:23 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +- [Open Community Issues/PRs](https://github.com/kubernetes/community/labels/sig%2Fnode)
```suggestion
- [开源社区 Issue/PR](https://github.com/kubernetes/community/labels/sig%2Fnode)
```

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +- 以更安全的方式（以 root 身份）运行工作负载。
```suggestion
- 以更安全的方式使用 root 身份运行工作负载。
```

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +该进程可以保留通常仅限于特权 Pod 的功能，并以安全的方式执行此操作，
```suggestion
该进程可以保留通常仅限于特权 Pod 的功能，并以安全的方式执行这类操作，
```

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +## 如何启用用户名字空间 {#how-do-i-enable-user-namespaces}
以上请重新划分段落翻译，段落过长无法 review；88-96 行是源码，不必翻译，因此也不要注释一份再拷贝一份。

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +该功能位于特性门控之后，因此在使用新特性之前，请确保启用了 `UserNamespacesStatelessPodsSupport` 特性。
"位于特性门控之后”是什么汉语表达？你的目的是多一个 PR 被合并还是通过翻译让其他读者更容易了解 k8s ？

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +该功能位于特性门控之后，因此在使用新特性之前，请确保启用了 `UserNamespacesStatelessPodsSupport` 特性。
在使用新特性之前，确保启用了... 特性  <-- 这句话读起来对么？

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +此外，运行时还必须支持用户名字空间：
这种翻译错误实际上是没有读懂原文的敷衍造成的

```suggestion
此外，运行时也必须支持用户名字空间：
```

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +对于 `cri-dockerd` 的支持[尚未计划][CRI-dockerd-issue]。
这句也是没有读懂谁支持谁造成的

```suggestion
`cri-dockerd` 对用户名字空间的支持[尚无计划][CRI-dockerd-issue]。
```

2022-09-10 08:08 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +你可以通过多种方式访问 SIG Node：
```suggestion
你可以通过多种方式联系 SIG Node：
```

2022-09-17 01:14 UTC, windsonsea requested changes

2022-09-17 01:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +该功能目前还处于 Alphy 阶段，默认是禁用的，因此在使用新特性之前，
```suggestion
该特性目前还处于 Alpha 阶段，默认是禁用的，因此在使用此新特性之前，
```

2022-09-17 01:14 UTC, windsonsea commented on content/zh-cn/blog/_posts/2022-10-03-add-userns-alpha/index.md
> +用户名字空间是 Linux 的一项功能，它允许将容器中的一组用户映射到主机中的不同用户，
```suggestion
用户名字空间是 Linux 的一项特性，它允许将容器中的一组用户映射到主机中的不同用户，
```

2022-09-25 08:10 UTC, Sea-n reviewed
/approve

2022-09-25 14:03 UTC, windsonsea commented
Thanks.

/lgtm

2022-09-25 14:04 UTC, merged