[hi] Localize content/en/docs/reference/glossary/image.md
kubernetes/website pull request #36752
Opened 2022-09-12 08:39 UTC by taniaduggal

Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>
fixes #35600

2022-11-22 08:55 UTC, Garima-Negi requested changes
minor tweaks in suggestions

2022-11-22 08:55 UTC, Garima-Negi commented on content/hi/docs/reference/glossary/image.md
> +एक {{< glossary_tooltip text="कंटेनर" term_id="container" >}}  का संग्रहित इंस्टेंस जिसमें किसी एप्लिकेशन को चलाने के लिए आवश्यक सॉफ़्टवेयर का एक सेट होता है।
both the short description and fundamental are same in the original rnglish content. 

I suggest we use the second option, without the word किसी and fixed spelling for संग्रहित = संग्रहीत

so :  एक {{< glossary_tooltip text="कंटेनर" term_id="container" >}} का संग्रहीत इंस्टेंस जिसमें एप्लिकेशन को चलाने के लिए आवश्यक सॉफ़्टवेयर का एक सेट होता है।

2022-11-22 08:55 UTC, Garima-Negi commented on content/hi/docs/reference/glossary/image.md
> +एक इमेज पैकेजिंग सॉफ़्टवेयर का एक तरीका है जिसे एक कंटेनर रजिस्ट्री में संग्रहीत किया जा सकता है, स्थानीय सिस्टम पर खींचा(pull) जा सकता है, और एक एप्लिकेशन के रूप में चलाया जा सकता है। इमेज में निहित
```suggestion
सॉफ़्टवेयर पैकेज करने का एक तरीका है जिसे एक कंटेनर रजिस्ट्री में संग्रहीत किया जा सकता है, स्थानीय सिस्टम पर खींचा(pull) जा सकता है और एक एप्लिकेशन के रूप में चलाया जा सकता है। इमेज में निहित मेटाडेटा दर्शाता है कि कौन सा निष्पादन योग्य चल रहा है, इसे किसने बनाया है, और अन्य जानकारी देता है।
```

2022-11-25 03:33 UTC, divya-mohan0209 reviewed
/lgtm

2022-12-20 05:15 UTC, divya-mohan0209 commented
cc: @Babapool @verma-kunal @anubha-v-ardhan @Garima-Negi : Please take a look.

2022-12-20 14:32 UTC, Babapool reviewed
Some nits from my side, _otherwise LGTM_. Thanks

2022-12-20 14:32 UTC, Babapool commented on content/hi/docs/reference/glossary/image.md
> +  यह एक कंटेनर का एक संग्रहीत उदाहरण है और इसमें एप्लिकेशन चलाने के लिए आवश्यक सॉफ़्टवेयर का एक सेट होता है।
```suggestion
  यह एक कंटेनर का एक संग्रहीत उदाहरण है और इसमें एप्लिकेशन चलाने के लिए आवश्यक सॉफ़्टवेयर का एक समूह होता है।
```

2022-12-20 14:32 UTC, Babapool commented on content/hi/docs/reference/glossary/image.md
> + एक {{< glossary_tooltip text="कंटेनर" term_id="container" >}} का संग्रहीत इंस्टेंस जिसमें एप्लिकेशन को चलाने के लिए आवश्यक सॉफ़्टवेयर का एक सेट होता है।
```suggestion
 एक {{< glossary_tooltip text="कंटेनर" term_id="container" >}} का संग्रहीत इंस्टेंस जिसमें एप्लिकेशन को चलाने के लिए आवश्यक सॉफ़्टवेयर का एक समूह होता है।
```

2023-01-16 17:34 UTC, bishal7679 commented
closing this PR since addressing duplicate PR #38956
/close

2023-01-16 17:34 UTC, closed without merging