[zh-cn]Sync PodDisruptionsCondition to PodDisruptionConditions
kubernetes/website pull request #36765
Opened 2022-09-12 23:06 UTC by yanrongshi

2022-09-13 00:56 UTC, windsonsea requested changes

2022-09-13 00:56 UTC, windsonsea commented on content/zh-cn/docs/concepts/workloads/pods/disruptions.md
>  * 进一步了解[排空节点](/zh-cn/docs/tasks/administer-cluster/safely-drain-node/)的信息。
```suggestion
* 进一步了解[清空节点](/zh-cn/docs/tasks/administer-cluster/safely-drain-node/)的信息。
```
Following the term after you click is a good idea.

2022-09-13 00:56 UTC, windsonsea commented on content/zh-cn/docs/tasks/job/pod-failure-policy.md
> +iit is problematic to find a balance between setting a low value for `.spec.backoffLimit`
?

2022-09-24 15:56 UTC, Sea-n commented
The `content/zh-cn/docs/tasks/job/pod-failure-policy.md` file have some additional changes, please resync it again. Thanks!

2022-09-25 12:43 UTC, yanrongshi commented
> The `content/zh-cn/docs/tasks/job/pod-failure-policy.md` file have some additional changes, please resync it again. Thanks!

/ok，thanks

2022-09-30 13:55 UTC, tengqm commented
Where are we now?

2022-09-30 14:00 UTC, windsonsea commented
Ping @yanrongshi to check `content/zh-cn/docs/tasks/job/pod-failure-policy.md` again.

2022-10-06 08:41 UTC, closed without merging