created page-content-type.md
kubernetes/website pull request #36866
Opened 2022-09-16 18:03 UTC by YashPimple

[hi] Localize en/docs/contribute/style/page-content-types.md

issue #36594

2022-09-30 13:34 UTC, tengqm commented
/retitle [hi] create page-content-type.md

2022-10-02 17:31 UTC, YashPimple commented
@tengqm I have retitled the commit name.

2022-10-03 01:12 UTC, Garima-Negi requested changes
Please go through comments and suggestions for 2 sections - references and tutorials. 
Please also read through remaining parts and rectify where needed. Will be reviewing them shortly

2022-10-03 01:12 UTC, Garima-Negi commented on content/hi/docs/contribute/style/page-content-types.md
> +`heading` शोर्ट के साथ।
shortcode instead of short.

also remove extra spaces between sentences for continuity

2022-10-03 01:12 UTC, Garima-Negi commented on content/hi/docs/contribute/style/page-content-types.md
> +  स्वयं को टेम्पलेट द्वारा स्वचालित रूप से शीर्षक दिया जाता है।
`अनुभागों को स्वयं टेम्पलेट द्वारा स्वचालित रूप से शीर्षक दिया जाता है।`

2022-10-03 01:12 UTC, Garima-Negi commented on content/hi/docs/contribute/style/page-content-types.md
> +  उचित।
`उचित रूप में उपयोग करें।` might sound better here

2022-10-03 01:12 UTC, Garima-Negi commented on content/hi/docs/contribute/style/page-content-types.md
> +  कार्य पूरा करने के बाद क्लस्टर की स्थिति।
- क्रमांकित सूचियों और कथा सामग्री के मिश्रण का उपयुक्त रूप में उपयोग करें।  might be better

2022-10-13 18:02 UTC, YashPimple commented
@Garima-Negi I have made the required changes  as asked so do I need to commit it directly on this branch or create a new branch ?

2022-10-14 18:07 UTC, YashPimple commented
@Garima-Negi I have made the required changes and pushed the commit. Please have a look.

2022-11-22 16:42 UTC, Babapool reviewed
Some suggestions from myside, hope you find them useful. Thanks:

2022-11-22 16:53 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +आप अपने पेज में `prerequisites`,`cleanup` और `whatsnext` अनुभाग जोड़ सकते हैं
I have used `खंड` here for section, but if you have used `अनुभाग ` throughout the page, I suggest that you stick with `अनुभाग ` for uniformity.

2022-12-23 04:05 UTC, Babapool reviewed
Some suggestions from my side hope you find them useful. Thanks

2022-12-23 04:05 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +'/content/en/docs/tutorials' निर्देशिका की उपनिर्देशिका में एक मार्कडाउन फ़ाइल बनाएं:
```suggestion
 एक Markdown फ़ाइल बनाएँ, निम्नलिखित विशेषताओं के साथ:
```

2022-12-23 17:37 UTC, YashPimple commented
@Babapool  made the suggested changes as per instructed and would like to know that i have made the changes to the same branch or do i need to create a new PR ?

2022-12-24 02:52 UTC, Babapool commented
@YashPimple you can make the changes to the same branch (i.e. `page-content-type`) and then push it here. There is no need to create a new PR. If I may have missed your questions please do let me know. Thanks

2022-12-24 06:24 UTC, YashPimple commented
> @Babapool made the suggested changes as per instructed and would like to know that i have made the changes to the same branch or do i need to create a new PR ?

Sure I have made the changes on the same branch as instructed.

2022-12-24 09:44 UTC, Babapool reviewed
Some suggestions from my side, hope you find them useful. Thanks:

2022-12-25 11:56 UTC, Babapool reviewed
Another set of suggestions from my side, hope you find them useful (hopefully this should be the last set). Thanks.

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +  name: योगदान देना
```suggestion
  name: contribute
```

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +- काम
```suggestion
- कार्य
```

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +## सामग्री अनुभाग
```suggestion
## सामग्री अनुभाग {#content-sections}
```

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +प्रत्येक पृष्ठ सामग्री प्रकार में द्वारा परिभाषित कई अनुभाग होते हैं
```suggestion
प्रत्येक पृष्ठ सामग्री प्रकार में Markdown टिप्पणियों और HTML शीर्षकों 
```

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +Markdown comments तथा HTML headings. आप इसमें सामग्री शीर्षक जोड़ सकते हैं
```suggestion
द्वारा परिभाषित कई खंड होते हैं। आप `heading` शॉर्टकोड का उपयोग करके अपने पृष्ठों
```

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +आपका पृष्ठ `heading` शोर्ट के साथ। टिप्पणियाँ और शीर्षक मदद करते हैं
```suggestion
में विषय शीर्षक जोड़ सकते हैं। टिप्पणियाँ और शीर्षक पृष्ठ सामग्री प्रकारों की संरचना 
```

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +पृष्ठ सामग्री प्रकारों की संरचना बनाए रखें।
```suggestion
को बनाए रखने में मदद करते हैं।
```

2022-12-25 11:56 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +पृष्ठ सामग्री अनुभागों को परिभाषित करने वाली मार्कडाउन टिप्पणियों के उदाहरण:
```suggestion
पृष्ठ सामग्री अनुभागों को परिभाषित करने वाली Markdown टिप्पणियों के उदाहरण:
```

2023-01-12 17:51 UTC, YashPimple commented
@Babapool made the instructed changes do have a look

2023-01-14 04:23 UTC, Babapool commented on content/hi/docs/contribute/style/page-content-types.md
> +अवधारणा पेज में `overview` और `body` अनुभाग टिप्पणियों के रूप में दिखाई देते हैं।
@YashPimple please update this change as well. Thanks

2023-01-14 04:25 UTC, Babapool commented
@YashPimple, the changes LGTM, but I am not sure of how the tables in the PR should be localized.
Requesting other reviewers to PTAL and share their opinion on this cc: @divya-mohan0209 @anubha-v-ardhan @bishal7679 @Garima-Negi @verma-kunal 
Thanks!

2023-03-26 06:40 UTC, divya-mohan0209 requested changes
Left some suggestions. PTAL

2023-03-26 06:40 UTC, divya-mohan0209 commented on content/hi/docs/contribute/style/page-content-types.md
> +| Page section  |
Entire table should be localized since we are explaining what each concept page comprises of.

2023-03-26 06:40 UTC, divya-mohan0209 commented on content/hi/docs/contribute/style/page-content-types.md
> +अवधारणा पेज तीन खंडों में विभाजित हैं:
```suggestion
अवधारणा पृष्ठ तीन खंडों में विभाजित हैं:
```

2023-03-26 06:40 UTC, divya-mohan0209 commented on content/hi/docs/contribute/style/page-content-types.md
> +| Page section  |
Would recommend localizing this table as well.

2023-03-26 06:40 UTC, divya-mohan0209 commented on content/hi/docs/contribute/style/page-content-types.md
> +| Page section  |
Would recommend localizing this as well.

2023-03-26 06:40 UTC, divya-mohan0209 commented on content/hi/docs/contribute/style/page-content-types.md
> +| Page section                 |
Would recommend localizing this, as well.

2023-06-23 18:52 UTC, Babapool commented
Hi @YashPimple, since there has been no update on this PR for a long time, a gentle ping from my side are you still actively working on this PR? Thanks

2023-06-24 12:14 UTC, YashPimple commented
Hello @Babapool I apologize for the delay in providing updates. Rest assured, I am actively working on this pull request and making progress on it.

2023-06-28 15:33 UTC, anubha-v-ardhan commented
/label tide/merge-method-squash

2023-08-07 05:13 UTC, divya-mohan0209 commented
Hello @YashPimple please advise if this is ready to be reviewed? There has been no update on this PR for a very long time barring the check-ins.

2023-11-14 02:19 UTC, divya-mohan0209 commented
@YashPimple : Since there has been response from your side, we'll be closing this PR. If and when you do have the bandwidth, please consider reopening the PR.
/close

2023-11-14 02:19 UTC, closed without merging