[zh-cn] sync tasks/administer-cluster/configure-upgrade-etcd.md
kubernetes/website pull request #36997
Opened 2022-09-24 12:03 UTC by my-git9

[zh-cn] sync tasks/administer-cluster/configure-upgrade-etcd.md

2022-09-24 13:22 UTC, windsonsea requested changes
It's not a good image for you if a small PR has too many issues there.

2022-09-24 13:22 UTC, windsonsea commented on content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
> +Yet another example would be to first export the environment variable
```suggestion
Yet another example would be to first export the environment variable
```
This line should be moved before its trans

2022-09-24 13:22 UTC, windsonsea commented on content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
> +另一个例子是先设置环境变量
```suggestion
另一个例子是先导出环境变量：
```

2022-09-25 08:19 UTC, Sea-n commented on content/zh-cn/docs/tasks/administer-cluster/configure-upgrade-etcd.md
> +另一个例子是先导出环境变量：
```suggestion
另一个例子是先設定环境变量：
```

2022-09-27 06:10 UTC, tengqm commented
/approve

2022-09-27 06:10 UTC, tengqm commented
/lgtm

2022-09-27 06:15 UTC, merged