[zh] sync extend-kubernetes/compute-storage-net/device-plugins.md
kubernetes/website pull request #36995
Opened 2022-09-24 11:10 UTC by my-git9

[zh] sync extend-kubernetes/compute-storage-net/device-plugins.md

2022-09-24 14:17 UTC, windsonsea requested changes

2022-09-24 14:17 UTC, windsonsea commented on content/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins.md
> +`TopologyInfo` 支持定义 `nodes` 字段，允许为 `nil` 或者是一个 NUMA 节点的列表。
```suggestion
`TopologyInfo` 支持将 `nodes` 字段设置为 `nil` 或一个 NUMA 节点的列表。
```

2022-09-25 08:17 UTC, Sea-n reviewed
/approve

2022-09-25 08:44 UTC, windsonsea commented
Thanks.
/lgtm

2022-09-25 08:46 UTC, merged