[hi] Localize content/en/docs/reference/glossary/helm-chart.md
kubernetes/website pull request #37078
Opened 2022-09-29 09:31 UTC by taniaduggal

fixes #35600

2022-11-21 19:05 UTC, Babapool reviewed
Hope suggestions from myside. Hope you find them useful. Thanks

2022-11-22 07:59 UTC, Garima-Negi requested changes

2022-11-22 07:59 UTC, Garima-Negi commented on content/hi/docs/reference/glossary/helm-chart.md
> +हेल्म चार्ट(Helm Chart) पूर्व-कॉन्फ़िगर(pre-configured) कुबेरनेट्स संसाधनों का एक पैकेज है जिसे हेल्म टूल का उपयोग करके प्रबंधित(manage) किया जा सकता है।
किए गए could work with पूर्व-कॉन्फ़िगर but since we will use पूर्व-कॉन्फ़िगरड़ , we may skip किए गए

2022-11-22 08:25 UTC, Babapool commented on content/hi/docs/reference/glossary/helm-chart.md
> +हेल्म चार्ट(Helm Chart) पूर्व-कॉन्फ़िगर(pre-configured) कुबेरनेट्स संसाधनों का एक पैकेज है जिसे हेल्म टूल का उपयोग करके प्रबंधित(manage) किया जा सकता है।
Yes, that sounds right. Thank you for the correction and I have update my suggestion to reflect the same. Thanks.

2022-11-22 08:50 UTC, Babapool reviewed
The changes LGTM (I am not an official `hi` localization reviewer/approver). Thanks.

Also if possible can you squash your commits in one to make your PR ready to merge. Thanks

2022-12-22 04:36 UTC, Babapool reviewed
/lgtm

2023-01-16 17:37 UTC, bishal7679 commented
/close
duplicate of #38955

2023-01-16 17:37 UTC, closed without merging