#37226 Pod article missing PodAffinity
kubernetes/website pull request #37243
Opened 2022-10-10 07:34 UTC by weiy730

Signed-off-by: weiy730 <weiy730@163.com>

(#37226 ) Pod article missing PodAffinity

2022-10-10 08:56 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +Pod 亲和性是一组 Pod 亲和性调度规则。
```suggestion
Pod 亲和性是一组 Pod 间亲和性调度规则。
```

2022-10-10 08:56 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  调度程序会更倾向于将 Pod 调度到满足该字段指定的亲和性表达式的节点，
```suggestion
  调度器更倾向于将 Pod 调度到满足该字段指定的亲和性表达式的节点，
```
This page has 10 调度器 and 2 调度程序. It is recommended to use the higher hits: 调度器.

2022-10-10 09:21 UTC, weiy730 commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  调度程序会更倾向于将 Pod 调度到满足该字段指定的亲和性表达式的节点，
OK.

2022-10-10 10:25 UTC, sftim commented
/retitle [zh] Add PodAffinity to API reference for Pod

2022-10-11 09:43 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  **所有匹配的 WeightedPodAffinityTerm 字段的权重都是按节点添加的，以找到最优选的节点。**
```suggestion
  **所有匹配的 WeightedPodAffinityTerm 字段的权重都是按节点累计的，以找到最优选的节点。**
```

2022-10-11 09:43 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +    必需的字段。一个 Pod 亲和性条件，与相应的权重相关联。
```suggestion
    必需的字段。一个 Pod 亲和性条件，对应一个与相应的权重值。
```

2022-10-11 09:43 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  系统可能会或可能不会尝试最终将 Pod 从其节点中逐出。
```suggestion
  系统可能会也可能不会尝试最终将 Pod 从其节点中逐出。
```

2022-10-11 09:43 UTC, tengqm commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  当有多个元素时，每个 `podAffinityTerm` 对应的节点列表是取其交集的，即必须满足所有条件。
```suggestion
  当此列表中有多个元素时，每个 `podAffinityTerm` 对应的节点列表是取其交集的，即必须满足所有条件。
```

2022-10-11 09:48 UTC, howieyuen requested changes

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  但它可能会选择违反一个或多个表达式的节点。最优选的节点是权重总和最大的节点，
```suggestion
  但它可能会选择违反一个或多个表达式的节点。最优选择是权重总和最大的节点，
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +    当前 Pod 应该与所选 Pod 集合位于同一位置（亲和性）或不位于同一位置（反亲和性），
```suggestion
    当前 Pod 应该与所选 Pod 集合位于同一位置（亲和性）或位于不同位置（反亲和性），
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +      或不位于同一位置（反亲和性），这里的 "在同一位置" 意味着运行在一个节点上，其键名为
```suggestion
      或位于不同位置（反亲和性），这里的 "在同一位置" 意味着运行在一个节点上，其键名为
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  匹配的 Pod，则将 "权重" 添加到总和中；
```suggestion
  匹配的 Pod，则将“权重”添加到总和中； 
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +    其中 "在同一位置" 意味着运行在一个节点上，其键 `topologyKey` 的标签值与运行所选 Pod
```suggestion
    其中“在同一位置”意味着运行在一个节点上，其键 `topologyKey` 的标签值与运行所选 Pod
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +      选择算符为 null 和 namespaces 列表为 null 值或空表示 "此 Pod 的名字空间"。
```suggestion
      选择算符为 null 和 namespaces 列表为 null 值或空表示“此 Pod 的名字空间”。
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +      namespaces 列表为 null 或空，以及 namespaceSelector 值为 null 均表示 "此 Pod 的名字空间"。
```suggestion
      namespaces 列表为 null 或空，以及 namespaceSelector 值为 null 均表示“此 Pod 的名字空间”。
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  这里的 "位于同一位置" 含义是运行在一个节点上。基于 `topologyKey` 字段所给的标签键名，
```suggestion
  这里的“位于同一位置”含义是运行在一个节点上。基于 `topologyKey` 字段所给的标签键名，
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +  检查所选 Pod 集合中各个 Pod 所在的节点上的标签值，标签值相同则认作 "位于同一位置"。
```suggestion
  检查所选 Pod 集合中各个 Pod 所在的节点上的标签值，标签值相同则认作“位于同一位置”。
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +    这里的 "位于同一位置" 含义是运行在一个节点上。基于 `topologyKey` 字段所给的标签键名，
```suggestion
    这里的“位于同一位置”含义是运行在一个节点上。基于 `topologyKey` 字段所给的标签键名，
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +    检查所选 Pod 集合中各个 Pod 所在的节点上的标签值，标签值相同则认作 "位于同一位置"。
```suggestion
    检查所选 Pod 集合中各个 Pod 所在的节点上的标签值，标签值相同则认作“位于同一位置”。
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +    选择算符为 null 和 namespaces 列表为 null 或空值表示 “此 Pod 的名字空间”。
```suggestion
    选择算符为 null 和 namespaces 列表为 null 或空值表示“此 Pod 的名字空间”。
```

2022-10-11 09:48 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/workload-resources/pod-v1.md
> +    namespaces 列表为 null 或空，以及 namespaceSelector 为 null 表示 “此 Pod 的名字空间”。
```suggestion
    namespaces 列表为 null 或空，以及 namespaceSelector 为 null 表示“此 Pod 的名字空间”。
```

2022-10-12 03:30 UTC, howieyuen commented
/label tide/merge-method-squash

2022-10-12 09:41 UTC, howieyuen commented
/lgtm

2022-10-15 05:05 UTC, Sea-n commented
There are some suggestions marked as resolved without being fixed. Could you leave comments for them to explain how do you think?

2022-10-15 05:10 UTC, howieyuen commented
/cancel lgtm

2022-10-15 05:11 UTC, howieyuen commented
/lgtm cancel

2022-10-15 05:14 UTC, howieyuen commented
> There are some suggestions marked as resolved without being fixed. Could you leave comments for them to explain how do you think?

I remember there was 20+ commits after @weiy730 modified first, so I leave the `tide/merge-method-squash` label.
I guest he wrongly used `git rebase` before `git push -f`.

2022-10-16 04:46 UTC, weiy730 commented
Sorry, and I fixed it.

2022-10-17 09:09 UTC, tengqm commented
目前看，剩余几个没修改的问题都是关于使用全角引号的。请修订。

2022-10-17 10:09 UTC, tengqm commented
/lgtm
/approve

2022-10-17 10:11 UTC, merged