[zh] Update container-lifecycle-hooks.md
kubernetes/website pull request #37277
Opened 2022-10-12 02:59 UTC by gaogao101

Signed-off-by: Gao Qian <gaoq.jy@fujitsu.com>

2022-10-13 03:56 UTC, windsonsea requested changes

2022-10-13 03:56 UTC, windsonsea commented on content/zh-cn/docs/concepts/containers/container-lifecycle-hooks.md
> +要自己生成失败的 `FailedPreStartHook` 事件，请修改
```suggestion
要自己生成失败的 `FailedPostStartHook` 事件，请修改
```
这都能贴错吗？

2022-10-13 05:11 UTC, gaogao101 commented
@windsonsea I'm really sorry. I won't make such a simple mistake again next time. Thank you for your correction.

2022-10-13 05:58 UTC, windsonsea commented
/lgtm

2022-10-15 05:08 UTC, Sea-n commented
/approve

2022-10-15 05:11 UTC, merged