[zh-cn]Update memory-default-namespace.md
kubernetes/website pull request #37275
Opened 2022-10-11 18:59 UTC by kinzhi

2022-10-26 23:49 UTC, Sea-n requested changes

2022-10-26 23:49 UTC, Sea-n commented on content/zh-cn/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +{{< note >}}
Please use this format instead.

```md
{{< note >}}
<!--
English content
-->
中文翻譯
{{< /note >}}
```

2022-10-26 23:49 UTC, Sea-n commented on content/zh-cn/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md
> +更多信息，请参阅[资源限制的 limit 和 request](/zh-cn/docs/concepts/policy/limit-range/#constraints-on-resource-limits-and-requests)。
Please break line into 60 - 120 characters.
```suggestion
`LimitRange` **不会**检查它应用的默认值的一致性。 这意味着 `LimitRange` 设置的 _limit_ 的默认值可能小于客户端提交给
API 服务器的声明中为容器指定的 _request_ 值。如果发生这种情况，最终会导致 Pod 无法调度。更多信息，
请参阅[资源限制的 limit 和 request](/zh-cn/docs/concepts/policy/limit-range/#constraints-on-resource-limits-and-requests)。
```

2022-11-06 07:06 UTC, Sea-n commented
Hey @kinzhi,

It's been a while since the last update, would you like to address issues in the previous comments so that we can move forward?

2022-11-06 17:09 UTC, kinzhi commented
> Hey @kinzhi,
> 
> It's been a while since the last update, would you like to address issues in the previous comments so that we can move forward?

Yes, I have revised it

2022-11-07 01:43 UTC, tengqm commented
@kinzhi Looks like the CI gate has some transient issues on this. Could you please recommit this PR to trigger another check?

2022-11-07 03:16 UTC, Sea-n commented
Please solve merge conflict and `/unhold` by yourself.
/hold

2022-11-07 04:21 UTC, kinzhi commented
/unhold

2022-11-07 04:44 UTC, tengqm commented
/lgtm
/approve

2022-11-07 04:46 UTC, merged