localize deployment.md file
kubernetes/website pull request #37321
Opened 2022-10-15 14:39 UTC by hamees-sayed

Fix Issue #35600

2022-10-18 05:13 UTC, Kartik494 commented
Hi @hamees-sayed could you please update PR description from `Fix Issue #Issuenumber` to `fixes #Issuenumber` so that it will automatically closes the issue  once this PR got merged.
Thanks!

2022-10-19 14:41 UTC, amolmote commented
/retitle [hi] Localize content/hi/docs/reference/glossary/deployment.md

2022-10-19 14:45 UTC, amolmote commented
> Hi @hamees-sayed could you please update PR description from `Fix Issue #Issuenumber` to `fixes #Issuenumber` so that it will automatically closes the issue once this PR got merged. Thanks!

hi @Kartik494. this is the command issue for whole glossary entries. @hamees-sayed  you can do like this `Fixes#Issue_number` `Localize content/en/docs/reference/glossary/deployment.md into content/hi/docs/reference/glossary/deployment.md`

2022-10-19 14:55 UTC, amolmote commented on content/hi/docs/reference/glossary/deployment.md
> +प्रत्येक प्रतिकृति को एक {{<glossary_tooltip term_id="pod" >}} द्वारा दर्शाया जाता है, और पॉड्स को बीच में वितरित किया जाता है {{< glossary_tooltip text="nodes" term_id="node" >}} एक क्लस्टर का।
```suggestion
प्रत्येक प्रतिकृति को एक {{<glossary_tooltip term_id="pod" >}} द्वारा दर्शाया जाता है, और पॉड्स को एक क्लस्टर के  {{< glossary_tooltip text="नोड्स" term_id="node" >}} के बीच वितरित किया जाता है।
```

2022-10-19 15:03 UTC, amolmote requested changes

2022-10-19 15:03 UTC, amolmote commented on content/hi/docs/reference/glossary/deployment.md
> +ऐसे कार्यभार के लिए जिन्हें स्थानीय स्थिति की आवश्यकता होती है, {{< glossary_tooltip term_id="StatefulSet" >}} का उपयोग करने पर विचार करें।
```suggestion
ऐसे वर्कलोड के लिए जिन्हें स्थानीय स्थिति की आवश्यकता होती है, {{< glossary_tooltip term_id="StatefulSet" >}} का उपयोग करने पर विचार करें।
```

2022-10-20 08:49 UTC, hamees-sayed commented on content/hi/docs/reference/glossary/deployment.md
> +ऐसे कार्यभार के लिए जिन्हें स्थानीय स्थिति की आवश्यकता होती है, {{< glossary_tooltip term_id="StatefulSet" >}} का उपयोग करने पर विचार करें।
understood!

2022-11-21 13:54 UTC, Babapool reviewed
Some nits from my side, hope you find them useful. Thanks (Apart from these nits the PR looks LGTM)

2022-11-21 13:54 UTC, Babapool commented on content/hi/docs/reference/glossary/deployment.md
> +ऐसे वर्कलोड के लिए जिन्हें स्थानीय स्थिति की आवश्यकता होती है, {{< glossary_tooltip term_id="StatefulSet" >}} का उपयोग करने पर विचार करें।
I think it is better to transliterate `local state` as readers might not be able to associate with `स्थानीय स्थिति` easily. Thoughts, WDYT @hamees-sayed?
```suggestion
ऐसे वर्कलोड्स के लिए जिन्हें लोकल स्टेट की आवश्यकता होती है, {{< glossary_tooltip text="स्टेटफुलसेट" term_id="StatefulSet" >}} का उपयोग करने पर विचार करें।
```

2023-03-25 16:56 UTC, divya-mohan0209 commented
@hamees-sayed Thank you for your contribution. Due to lack of any response from your end, we will be closing this PR right now. However, if you feel that you're able to address the feedback provided and actively work on the PR, please feel free to reopen it & we shall begin right where we left off :)

/close

2023-03-25 16:56 UTC, closed without merging