ClusterIP: added "you can expose he service to the public with an Ing…
kubernetes/website pull request #37330
Opened 2022-10-16 12:22 UTC by guettli

It took me some time to understand that.

Feel free to change my wording

2022-10-18 10:59 UTC, sftim commented
/retitle Reword explanation of ClusterIP for Services

2022-10-18 11:00 UTC, sftim commented on content/en/docs/concepts/services-networking/service.md
> +  the service to the public with an Ingress. This is the
Maybe we could also mention [Gateway](gateway-api.sigs.k8s.io/) here?

2022-10-18 18:02 UTC, guettli commented
@sftim I added "Gateway API". Is it ok like this?

2022-10-19 07:08 UTC, Arhell reviewed
Please sign CLA

2022-10-19 11:54 UTC, sftim commented
@guettli please check the commit email address that you're using, it might not match the one you signed the CLA with.

2022-10-19 14:17 UTC, guettli commented
I signed it

2022-10-20 06:19 UTC, guettli commented
I am happy, the EasyCLA now passed. There was some confusion with an outdated email address.

2022-10-31 05:18 UTC, Sea-n commented
/remove-language zh

2022-11-20 14:27 UTC, guettli commented
@Arhell @sftim could you please review this tiny PR?

2023-01-17 11:06 UTC, divya-mohan0209 requested changes
Hyperlinked the two terms for the sake of clarity. Rest LGTM from the docs perspective!

2023-01-17 11:06 UTC, divya-mohan0209 commented on content/en/docs/concepts/services-networking/service.md
> +  You can expose the service to the public with an Ingress or the
```suggestion
  You can expose the service to the public with an [Ingress](docs/reference/kubernetes-api/service-resources/ingress-v1/) or the
```

2023-01-17 11:06 UTC, divya-mohan0209 commented on content/en/docs/concepts/services-networking/service.md
> +  Gateway API.
```suggestion
  [Gateway API](https://gateway-api.sigs.k8s.io/).
```

2023-01-30 17:39 UTC, sftim reviewed
/lgtm
from https://github.com/kubernetes/website/pull/37330#pullrequestreview-1251348126

/approve

2023-01-30 17:40 UTC, sftim commented on content/en/docs/concepts/services-networking/service.md
> +  [Gateway API](https://gateway-api.sigs.k8s.io/).
IMO this is still not quite right, but it's still a helpful change to make.

2023-01-30 17:40 UTC, merged

2023-01-31 07:10 UTC, tengqm commented
The link target misses a leading `/`, this needs a fix.

2023-01-31 09:46 UTC, sftim commented
Oops. https://github.com/kubernetes/website/pull/39185 should fix that.