[ja] In-page links are not working etc in /ja/docs/tasks/debug/debug-application/debug-pods.md
kubernetes/website pull request #37437
Opened 2022-10-21 18:09 UTC by K0more

PR for issue #37351 
fixed the following things:
- In-page links
- bold notations
- the required ja to eng edits.

signed-off-by: k0more arch.phenon@gmail.com

2022-10-21 19:05 UTC, K0more commented
can you add the hacktoberfest label to this PR as well, it'd be really appreciated.

2022-10-24 07:15 UTC, t-inu requested changes
This file is described using Markdown format.
[Hugo](https://gohugo.io/) generates a HTML file from this md file.
So, need not changing to the HTML format in this PR.

And, how to set custom heading IDs, refer to the following.
https://gohugo.io/content-management/cross-references/#heading-ids

2022-10-25 12:48 UTC, K0more commented on content/ja/docs/tasks/debug/debug-application/debug-pods.md
> +## 次の項目
okay 👍

2022-10-28 18:12 UTC, K0more commented
@t-inu Hey, I have updated the md file, can you recheck it.

2022-10-30 13:34 UTC, nasa9084 commented
/assign
/approve

btw we don't have hactoberfest labels

2022-10-30 15:00 UTC, K0more commented
> /assign /approve
> 
> btw we don't have hactoberfest labels

Oh ok no problem, I was just curious

2022-10-30 22:27 UTC, t-inu commented
Thanks for the fix.
/label tide/merge-method-squash
/lgtm

2022-10-30 22:28 UTC, merged

2022-10-31 02:34 UTC, K0more commented
たつけて ありがとうございます @t-inu @nasa9084