Localize /content/hi/docs/reference/glossary/kubelet.md
kubernetes/website pull request #37532
Opened 2022-10-26 09:29 UTC by vaibhav2107

Fixes: #37515

2022-10-26 09:30 UTC, vaibhav2107 commented
Hi @anubha-v-ardhan @divya-mohan0209 ,
Could you please have a look

2022-11-13 15:24 UTC, vaibhav2107 commented
Hi @bishal7679,
Could you please have a look.

2022-11-17 10:07 UTC, Babapool reviewed
Hope you find these suggestions useful. Thanks.

2022-11-17 10:39 UTC, vaibhav2107 commented
Thanks @Babapool for reviewing and suggesting the changes

2022-11-17 10:41 UTC, vaibhav2107 commented
@Babapool I think the suggestions are good. I am ready to commit them if some official member could approve them

2022-12-27 08:20 UTC, Babapool commented
Hi @vaibhav2107, just a friendly reminder are you still working on this PR? Thanks

2023-01-21 15:43 UTC, bishal7679 commented
@vaibhav2107 Gentle reminder!

2023-02-05 22:30 UTC, vaibhav2107 commented
@Babapool PTAL
I have updated your given suggestions

2023-03-26 06:51 UTC, divya-mohan0209 requested changes

2023-03-26 06:51 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/kubelet.md
> +क्यूबलेट को विभिन्न तंत्रों के माध्यम से एक पॉडस्पेक्स (PodSpec) समूह प्राप्त होता है और यह सुनिश्चित करता हैं कि इन पॉडस्पेक्स में वर्णित कंटेनर चल रहे हैं और स्वस्थ हैं। क्यूबलेट उन कंटेनरों का प्र
Nit.
```suggestion
क्यूबलेट को विभिन्न तंत्रों के माध्यम से पॉडस्पेक्स (PodSpec) का एक समूह प्राप्त होता है और यह सुनिश्चित करता हैं कि इन पॉडस्पेक्स में वर्णित कंटेनर चल रहे हैं और स्वस्थ हैं। क्यूबलेट उन कंटेनरों का प्रबंधन नहीं करता है जो कुबेरनेट्स द्वारा नहीं बनाए गए थे।
```

2023-06-23 18:58 UTC, Babapool commented
Hi @vaibhav2107, just a gentle ping, since there has been no updates on this PR for a long time are you still working on this PR? Thanks

2023-06-26 04:09 UTC, bishal7679 commented
!!Gentle Reminder!!
Hey @vaibhav2107 Would you like to have a look on this PR since it's been 4 month along with no update!
Feel free to comment here without any hesitation
Hope you understand
Thank you!

2023-06-26 04:55 UTC, vaibhav2107 commented
Hi @Babapool @bishal7679 
I have updated the PR for the change. Could you please have a look now

2023-06-28 15:35 UTC, anubha-v-ardhan commented
/label tide/merge-method-squash

2023-06-28 15:58 UTC, merged