[hi] Localize /en/docs/reference/glossary/kubectl.md #37516
kubernetes/website pull request #37538
Opened 2022-10-26 16:07 UTC by sachinparihar

Fixes: #37516

2022-11-04 17:47 UTC, bishal7679 commented
Fixes: #35600

2022-11-04 18:05 UTC, bishal7679 requested changes
Suggested some changes! commit this suggestion if you found this useful

2022-11-04 18:05 UTC, bishal7679 commented on content/hi/docs/reference/glossary/kubectl.md
> +आप `kubectl` का उपयोग कुबेरनेट्स ऑब्जेक्ट बनाने, निरीक्षण करने, अपडेट करने और हटाने के लिए कर सकते हैं।
```suggestion
आप कुबेरनेट्स ऑब्जेक्ट बनाने, निरीक्षण करने, अपडेट करने और हटाने के लिए `kubectl` का उपयोग कर सकते हैं।
```

2023-03-26 06:54 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/kubectl.md
> +  कुबेरनेट्स क्लस्टर के साथ बातचीत करने के लिए एक कमांड लाइन टूल।
Tbh, संचार fits better in this case.

2023-03-26 06:56 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/kubectl.md
> +के साथ बातचीत करने के लिए कमांड लाइन टूल।
The original text worked better here too. We refer to Control Plane in the reference docs in the former format. Please refer: https://github.com/kubernetes/website/blob/main/content/hi/docs/reference/glossary/control-plane.md

2023-03-26 06:57 UTC, divya-mohan0209 commented
Hello @sachinparihar , please address the feedback provided & resolve the merge conflict so that we can ready this for merge.

2023-03-29 15:52 UTC, sachinparihar commented
@divya-mohan0209 please help me!

2023-03-30 02:57 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2023-03-30 03:00 UTC, divya-mohan0209 commented
@sachinparihar:

1. Sign the LF CLA before you submit a PR to the kubernetes/website repo. Make sure you have added the email ID & username that you've used for signing to your local/global variables.
2. If it is simpler, please consider closing this PR & reopening a new PR addressing the changes.

2023-04-01 09:48 UTC, closed without merging

2023-05-18 05:48 UTC, sachinparihar commented
new pr #40438