hi-statefulset.md
kubernetes/website pull request #37552
Opened 2022-10-27 05:00 UTC by surbhiahuja

2022-10-27 08:52 UTC, bishal7679 requested changes
Thank you @surbhiahuja
Please go through the suggested changes and commit them if you agree.
Feel free to start a discussion in case any doubt!

2022-10-27 08:52 UTC, bishal7679 commented on content/hi/docs/reference/glossary/statefulset.md
> +एक {{<glossary_tooltip term_id="तैनाती">}} की तरह, एक StatefulSet एक समान कंटेनर विनिर्देश पर आधारित पॉड्स का प्रबंधन करता है। परिनियोजन के विपरीत, स्टेटफुलसेट अपने प्रत्येक पॉड के लिए एक चिपचिपा पहच
```suggestion
एक {{<glossary_tooltip text="डिप्लॉयमेंट" term_id="deployment">}} की तरह, एक स्टेटफुलसेट एक सदृश कंटेनर विनिर्देश पर आधारित पॉड्स का प्रबंधन करता है। डिप्लॉयमेंट के विपरीत, स्टेटफुलसेट अपने प्रत्येक पॉड के लिए एक चिपचिपा पहचान बनाए रखता है। ये पॉड एक ही विनिर्देश से बनाए गए हैं, लेकिन विनिमय करने योग्य नहीं हैं&#58; प्रत्येक का एक स्थायी पहचानकर्ता होता है जिसे वह किसी भी पुनर्निर्धारण के दौरान बनाए रखता है।
```

2022-10-27 08:52 UTC, bishal7679 commented on content/hi/docs/reference/glossary/statefulset.md
> +यदि आप अपने कार्यभार के लिए दृढ़ता प्रदान करने के लिए स्टोरेज वॉल्यूम का उपयोग करना चाहते हैं, तो आप समाधान के हिस्से के रूप में स्टेटफुलसेट का उपयोग कर सकते हैं। हालांकि स्टेटफुलसेट में अलग-अलग पॉड
```suggestion
यदि आप अपने वर्कलोड को दृढ़ता प्रदान करने के लिए स्टोरेज वॉल्यूम का उपयोग करना चाहते हैं, तो आप समाधान के हिस्से के रूप में स्टेटफुलसेट का उपयोग कर सकते हैं। हालांकि स्टेटफुलसेट में अलग-अलग पॉड विफलता के लिए अतिसंवेदनशील होते हैं, दृढ़ पॉड पहचानकर्ता मौजूदा वॉल्यूम को नए पॉड्स से मिलाना आसान बनाते हैं जो असफल होने वाले किसी भी पॉड को प्रतिस्थापित करता है।
```

2022-10-27 08:55 UTC, bishal7679 commented
Fixes:- #35600
Closes:- #37533 
/retitle Localize /en/docs/reference/glossary/statefulset.md

2022-10-27 08:56 UTC, bishal7679 commented
Fixes:- https://github.com/kubernetes/website/issues/35600
Closes:- https://github.com/kubernetes/website/issues/37533
/retitle [hi] Localize /en/docs/reference/glossary/statefulset.md

2022-10-27 18:19 UTC, surbhiahuja commented
@bishal7679 , I have updated file as suggested - https://github.com/kubernetes/website/pull/37552/commits

2022-10-29 12:15 UTC, sftim commented on content/hi/docs/reference/glossary/statefulset.md
> +id: स्टेटफुलसेट(StatefulSet)
```suggestion
id: statefulset
```

2022-11-01 06:38 UTC, surbhiahuja commented
@sftim , Updated as suggested.

2022-11-21 02:33 UTC, divya-mohan0209 requested changes

2022-11-21 02:33 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/statefulset.md
> +title: StatefulSet
Please translate this.

2022-11-21 02:33 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/statefulset.md
> +एक {{<glossary_tooltip text="डिप्लॉयमेंट" term_id="deployment">}} की तरह, एक स्टेटफुलसेट एक सदृश कंटेनर विनिर्देश पर आधारित पॉड्स का प्रबंधन करता है। डिप्लॉयमेंट के विपरीत, स्टेटफुलसेट अपने प्रत्येक
```suggestion
एक {{<glossary_tooltip text="डिप्लॉयमेंट" term_id="deployment">}} की तरह, एक स्टेटफुलसेट एक सदृश कंटेनर विनिर्देश पर आधारित पॉड्स का प्रबंधन करता है। डिप्लॉयमेंट के विपरीत, स्टेटफुलसेट अपने प्रत्येक पॉड के लिए एक चिपचिपा पहचान बनाए रखता है। ये पॉड एक ही विनिर्देश से बनाए गए हैं, लेकिन विनिमय करने योग्य नहीं हैं; प्रत्येक का एक स्थायी पहचानकर्ता होता है जिसे वह किसी भी पुनर्निर्धारण के दौरान बनाए रखता है।
```

2022-11-21 02:33 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/statefulset.md
> +  प्रत्येक पॉड के लिए स्थायी संचयन और दृढ़ पहचानकर्ता के साथ, पॉड्स के एक सेट की डिप्लॉयमेंट और स्केलिंग का प्रबंधन करता है।
We've mentioned संचयन here and स्टोरेज below. We'll need to stick to one term.

2022-11-21 05:09 UTC, divya-mohan0209 reviewed
Small nit. Otherwise lgtm!

2022-11-21 05:09 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/statefulset.md
> +title: StatefulSet(स्टेटफुलसेट)
```suggestion
title: स्टेटफुलसेट (StatefulSet)
```

2022-11-21 05:39 UTC, bishal7679 commented
/lgtm

2022-11-21 06:17 UTC, divya-mohan0209 reviewed
ID is capitalized wrong.

2022-11-21 06:17 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/statefulset.md
> +id: StatefulSet
```suggestion
id: statefulset
```

2022-11-22 08:49 UTC, surbhiahuja commented
id is corrected @divya-mohan0209 . Thanks for inputs.

2022-11-22 09:05 UTC, bishal7679 approved these changes
Now changes LGTM!

2022-11-22 16:35 UTC, bishal7679 commented
/lgtm

2022-11-23 01:18 UTC, divya-mohan0209 reviewed
/approve

2022-11-23 01:20 UTC, merged