[zh-cn] Update flow-control.md
kubernetes/website pull request #37633
Opened 2022-11-01 03:24 UTC by gaogao101

Signed-off-by: Gao Qian <gaoq.jy@fujitsu.com>

2022-11-01 06:13 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  数量的高或低水位标记的直方图向量(除以相应的限制，得到0到1的范围内的比率)，
```suggestion
  数量的高或低水位标记的直方图向量(除以相应的限制，得到 0 到 1 的范围内的比率)，
```

2022-11-01 06:13 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  的并发限制)的比率，介于0和1之间。
```suggestion
  的并发限制)的比率，介于 0 和 1 之间。
```

2022-11-01 06:13 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +   数量的高或低水平标记的直方图向量(除以相应的限制，得到0到1的范围内的比率)，
```suggestion
   数量的高或低水平标记的直方图向量(除以相应的限制，得到 0 到 1 的范围内的比率)，
```

2022-11-01 06:13 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  记录给定写的相关活动WATCH的数量，
```suggestion
  记录给定写相关活动的 WATCH 请求的数量，
```

2022-11-01 07:58 UTC, my-git9 commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  一个事件数量的计数器，这些事件在原则上可能导致请求被分派，
```suggestion
* `apiserver_flowcontrol_request_dispatch_no_accommodation_total` 
  是一个事件数量的计数器，这些事件在原则上可能导致请求被分派，
```

2022-11-02 02:49 UTC, chengxiangdong commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  的并发限制)的比率，介于0和1之间。
`(` -> `（`
`)` -> `）`

2022-11-02 02:49 UTC, chengxiangdong commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +   数量的高或低水平标记的直方图向量(除以相应的限制，得到0到1的范围内的比率)，
`(` -> `（`
`)` -> `）`

2022-11-02 02:58 UTC, chengxiangdong commented
`水平标记` or `水位线` ?
By reading the document, it may be more appropriate to use `水位线`.

2022-11-02 03:13 UTC, gaogao101 commented
@mengjiao-liu @my-git9 @chengxiangdong Thank you for your help. The modification has been completed.

2022-11-02 03:53 UTC, my-git9 commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +   数量的高或低水平标记的直方图向量(除以相应的限制，得到 0 到 1 的范围内的比率)，
```suggestion
* `apiserver_flowcontrol_priority_level_request_count_watermarks`
   是请求数量的高或低水平标记的直方图向量(除以相应的限制，得到 0 到 1 的范围内的比率)，
```

2022-11-02 03:53 UTC, my-git9 commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  的并发限制)的比率，介于 0 和 1 之间。
```suggestion
  每个观察到的值都是请求数除以相应的请求数限制(等待的队列长度限制和执行的并发限制)的比率，
  介于 0 和 1 之间。
```

2022-11-02 03:53 UTC, my-git9 commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  数量的高或低水平标记的直方图向量(除以相应的限制，得到 0 到 1 的范围内的比率)，
```suggestion
* `apiserver_flowcontrol_read_vs_write_request_count_watermarks`
  是请求数量的高或低水平标记的直方图向量(除以相应的限制，得到 0 到 1 的范围内的比率)，
```

2022-11-02 05:11 UTC, gaogao101 commented
@my-git9 The modification has been completed.

2022-11-07 01:32 UTC, tengqm commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  是请求数量的高或低水平标记的直方图向量(除以相应的限制，得到 0 到 1 的范围内的比率)，
```suggestion
  是请求数量的高或低水平标记的直方图向量（除以相应的限制，得到 0 到 1 的范围内的比率），
```

2022-11-07 01:32 UTC, tengqm commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  每个观察到的值都是请求数除以相应的请求数限制(等待的队列长度限制和执行的并发限制)的比率，
```suggestion
  所观察到的每个值都是请求数除以相应的请求数限制（等待的队列长度限制和执行的并发限制）的比率，
```

2022-11-07 01:32 UTC, tengqm commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  记录给定写的相关活动 WATCH 的数量，
```suggestion
  记录给定写的相关活动 WATCH 请求数量，
```

2022-11-07 01:32 UTC, tengqm commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  记录与估计位置(最初阶段和最后阶段的最多人数)相关联的请求数量，
```suggestion
  记录与估计席位（最初阶段和最后阶段的最多人数）相关联的请求数量，
```

2022-11-07 01:32 UTC, tengqm commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  但由于缺乏可用的并发性，没有被分派，
```suggestion
  但由于并发度不足而没有被分派，
```

2022-11-07 02:19 UTC, gaogao101 commented
@tengqm The modification has been completed.

2022-11-07 02:21 UTC, tengqm commented
Thanks.
/approve

2022-11-07 03:57 UTC, Sea-n reviewed
Overall LGTM.

2022-11-07 03:57 UTC, Sea-n commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  是请求数量的高或低水平标记的直方图向量（除以相应的限制，得到 0 到 1 的范围内的比率），
I think it would better to prevent two `的` in a sentence.
```suggestion
  是请求数量的高或低水平标记的直方图向量（除以相应的限制，得到介於 0 至 1 的比率），
```

2022-11-07 03:57 UTC, Sea-n commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
>    （取值为 `mutating` 和 `readOnly`）拆分；标签 `mark` 取值为 `high` 和 `low`。
Change to another conjunction for different level.
```suggestion
  由标签 `phase`（取值为 `waiting` 及 `executing`）和 `request_kind`
  （取值为 `mutating` 及 `readOnly`）拆分；标签 `mark` 取值为 `high` 和 `low`。
```

2022-11-11 03:31 UTC, gaogao101 commented
@Sea-n The modification has been completed.

2022-11-11 06:33 UTC, mengjiao-liu requested changes

2022-11-11 06:33 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/cluster-administration/flow-control.md
> +  是请求数量的高或低水平标记的直方图向量（除以相应的限制，得到介於 0 至 1 的比率），
```suggestion
  是请求数量的高或低水平标记的直方图向量（除以相应的限制，得到介于 0 至 1 的比率），
```

“介於” 是繁体

2022-11-14 10:07 UTC, merged