Add pt-br/docs/reference/glossary/csi.md
kubernetes/website pull request #37725
Opened 2022-11-05 17:31 UTC by MrErlison

Added translation for portuguese of the glossary term csi.

2022-11-16 13:14 UTC, stormqueen1990 requested changes
Hello there, @MrErlison!

Thank you very much for your contribution! 🎉 

There's some small things to be addressed, please let me know if you have any questions! 😃

2022-11-16 13:14 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/csi.md
> + A Interface de Armazenamento de Contêiner (Container Storage Interface - CSI) define um padrão de interface para expor sistemas de armazenamento a contêineres.
Suggestion: stylize "Container Storage Interface" as italic and use ", ou" instead of a dash to separate it from the acronym.

2022-11-16 13:14 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/csi.md
> +O CSI permite que os fornecedores criem plugins personalizados de armazenamento para o Kubernetes sem adicioná-los ao repositório Kubernetes (plugins fora da árvore). Para usar um driver CSI de um pr
Perhaps "instalá-lo" instead of "implantá-lo" could be a better translation?

2022-11-28 12:44 UTC, stormqueen1990 commented
/lgtm

/cc @edsoncelio

2022-11-28 12:59 UTC, edsoncelio commented
Thank you all!
/approve

2022-11-28 13:02 UTC, merged