Add pt-br/docs/reference/glossary/statefulset.md
kubernetes/website pull request #37818
Opened 2022-11-09 22:25 UTC by rodrigodelmonte

This PR adds Portuguese translation to the glossary term statefulset.

Signed-off-by: Rodrigo V. Del Monte [rvdelmonte@gmail.com](mailto:rvdelmonte@gmail.com)

2022-11-16 13:24 UTC, stormqueen1990 requested changes
Hello there, @rodrigodelmonte!

Thank you very much for your contribution! 🎉 

I found a few minor issues that need to be addressed in this PR. Should you have any questions please don't hesitate to reach out! 😃

2022-11-16 13:24 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/statefulset.md
> +Se vovê quiser usar volumes de armazenamento para fornecer persistência para sua carga de trabalho, você pode usar um *StatefulSet* como parte da sua soluçãp. Embora os Pods individuais em um *Statef
No need to stylize "StatefulSet" as italic here, as it is a Kubernetes core object (rather than a foreign term).

2022-11-16 13:24 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/statefulset.md
> +Como o {{< glossary_tooltip term_id="deployment" >}}, um *StatefulSet* gerencia Pods que são baseados em uma especificação de container idêntica. Diderente do Deployment, um *StatefulSet* mantém uma
Typo in "diderente".

2022-11-16 13:24 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/statefulset.md
> +Como o {{< glossary_tooltip term_id="deployment" >}}, um *StatefulSet* gerencia Pods que são baseados em uma especificação de container idêntica. Diderente do Deployment, um *StatefulSet* mantém uma
In the last sentence ("cada tem uma identificação..."): perhaps use "cada um" instead of just "cada"?

2022-11-16 13:24 UTC, stormqueen1990 commented on content/pt-br/docs/reference/glossary/statefulset.md
> +Se vovê quiser usar volumes de armazenamento para fornecer persistência para sua carga de trabalho, você pode usar um *StatefulSet* como parte da sua soluçãp. Embora os Pods individuais em um *Statef
A few typos:
* "vovê"
* "soluçãp"
* "susetíveis"

2022-11-17 09:36 UTC, rodrigodelmonte commented
@stormqueen1990 thanks for the review!
The PR is updated.

2022-11-20 23:02 UTC, devlware commented
/lgtm

2022-11-21 13:21 UTC, stormqueen1990 commented
/approve

Thanks!

2022-11-21 13:22 UTC, merged