[ru] Localization of /concepts/scheduling-eviction/api-eviction.md
kubernetes/website pull request #38081
Opened 2022-11-25 17:57 UTC by kirkonru

Add RU localization for api-eviction.md and _index.md.

2023-01-29 14:34 UTC, kirkonru commented
@shurup hello! Please review and merge this PR.

2023-01-30 12:47 UTC, kirkonru commented
/lgtm

2023-02-10 08:00 UTC, shurup requested changes
Thank you for this PR! Here are a few minor corrections for me to move on with it.

2023-02-16 07:08 UTC, kirkonru commented on content/ru/docs/concepts/scheduling-eviction/_index.md
> +мог их запустить. Приоритизация (упреждение) — процесс завершения работы Pod'ов
Great suggestion, thanks!

2023-02-16 07:15 UTC, kirkonru commented on content/ru/docs/concepts/scheduling-eviction/api-eviction.md
> +Вытеснение с версией `policy/v1` доступно, начиная с v1.22. Для более ранних релизов используйте `policy/v1beta1`.
Thanks a lot! The Russian language is so confusing sometimes. :)

2023-02-16 12:18 UTC, kirkonru commented on content/ru/docs/concepts/scheduling-eviction/api-eviction.md
> +{{< glossary_definition term_id="api-eviction" length="short" >}} </br>
```suggestion
{{< glossary_definition term_id="api-eviction" length="short" >}} </br>
```

2023-02-16 14:01 UTC, kirkonru commented on content/ru/docs/reference/glossary/pod-disruption.md
> +кластера. Внеплановое завершение работы обычно связано с непредвиденными проблемами различной природы,
```suggestion
кластера. Внеплановое завершение работы обычно вызвано непредвиденными обстоятельствами различной природы, 
```

2023-02-16 14:02 UTC, kirkonru commented on content/ru/docs/reference/glossary/api-eviction.md
> +Инициированные API вытеснения учитывают заданные параметры [`PodDisruptionBudget`](/docs/tasks/run-application/configure-pdb/) (минимальное количество реплик, которые должны быть доступны для данного
```suggestion
Вытеснения, инициированные через API, учитывают заданные параметры [`PodDisruptionBudget`](/docs/tasks/run-application/configure-pdb/) (минимальное количество реплик, которые должны быть доступны для данного развертывания в любой момент времени) и [`terminationGracePeriodSeconds`](/docs/concepts/workloads/pods/pod-lifecycle#pod-termination) (период ожидания корректного завершения работы Pod'а).
```

2023-02-16 14:07 UTC, kirkonru commented
@shurup appreciate the review, all the corrections are committed. I had to add two more files to the Glossary to get rid of the following errors:

> ERROR 2023/02/16 12:13:24 [ru] "docs/concepts/scheduling-eviction/api-eviction.md": "api-eviction" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list
> 
> ERROR 2023/02/16 13:03:30 [ru] "docs/concepts/scheduling-eviction/_index.md": "pod-disruption" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list

Now the tests run smoothly, and the PR seems to be ready for merging (well, at least I hope so :smile:)

2023-02-17 03:49 UTC, shurup commented
Great, thanks! All looks fine to me.

/lgtm
/approve

2023-02-17 03:51 UTC, merged