Translate docs/concepts/storage/volume-snapshots/ into Japanese
kubernetes/website pull request #38141
Opened 2022-11-29 01:59 UTC by KobayashiD27

close #38116

2022-11-29 02:21 UTC, KobayashiD27 commented
/assign @nasa9084

2022-11-29 12:50 UTC, nasa9084 commented on content/ja/docs/concepts/storage/volume-snapshots.md
> +- `VolumeSnapshot`の展開プロセスの一環として、Kubernetesチームは、コントロールプレーンに展開されるスナップショットコントローラーと、CSIドライバーと共に展開されるcsi-snapshotterと呼ばれるサイドカーヘルパーコンテナーを提供します。`VolumeSnapshot`および`VolumeSnapshotContent`オブジェクトを管理し、`VolumeSn
```suggestion
- `VolumeSnapshot`の展開プロセスの一環として、Kubernetesチームは、コントロールプレーンに展開されるスナップショットコントローラーと、CSIドライバーと共に展開されるcsi-snapshotterと呼ばれるサイドカーヘルパーコンテナを提供します。`VolumeSnapshot`および`VolumeSnapshotContent`オブジェクトを管理し、`VolumeSnapshotContent`オブジェクトの作成と削除を担当します。サイドカーcsi-snapshotterは、`VolumeSnapshotContent`オブジェクトを監視し、CSIエンドポイントに対して`CreateSnapshot`および`DeleteSnapshot`操作をトリガーします。
```

2022-12-01 06:16 UTC, atoato88 commented
The pages on preview site are following:
- https://deploy-preview-38141--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/storage/volume-snapshots
- https://deploy-preview-38141--kubernetes-io-main-staging.netlify.app/ja/docs/concepts/storage/persistent-volumes

2022-12-01 08:20 UTC, atoato88 reviewed
Thank you for create this PR!
I left some comments.

2022-12-02 00:39 UTC, KobayashiD27 commented on content/ja/docs/concepts/storage/volume-snapshots.md
> +- `VolumeSnapshot`の展開プロセスの一環として、Kubernetesチームは、コントロールプレーンに展開されるスナップショットコントローラーと、CSIドライバーと共に展開されるcsi-snapshotterと呼ばれるサイドカーヘルパーコンテナを提供します。`VolumeSnapshot`および`VolumeSnapshotContent`オブジェクトを管理し、`VolumeSna
Thank you!

2022-12-07 10:00 UTC, atoato88 reviewed
I left just one comment.

2022-12-07 10:00 UTC, atoato88 commented on content/ja/docs/concepts/storage/volume-snapshots.md
> +事前プロビジョニングされたスナップショットの場合、クラスター管理者が`Spec.SourceVolumeMode`を入力する必要があります。
```suggestion
事前プロビジョニングされたスナップショットの場合、クラスター管理者が`spec.sourceVolumeMode`を入力する必要があります。
```
I created the PR(#38207) which update json path at here and merged now.
So please update here.

2022-12-07 10:03 UTC, atoato88 requested changes
here is the comment.

2022-12-12 14:03 UTC, nasa9084 commented
/approve

2022-12-12 19:49 UTC, atoato88 commented
/lgtm
Thank you for updating!

2022-12-13 09:27 UTC, t-inu commented
@nasa9084 Please enter `/approve` command again because it seems `approved` label has not added.

2022-12-13 14:19 UTC, nasa9084 commented
/approve

2022-12-13 14:19 UTC, merged