Reworded the Confusing sentence in Virtual IPs and Service Proxies
kubernetes/website pull request #38231
Opened 2022-12-02 12:57 UTC by satyamkale27

### Reworded the Confusing sentence in Virtual IPs and Service Proxies 
**fixes #38169**

2022-12-02 16:12 UTC, sftim commented on content/en/docs/reference/networking/virtual-ips.md
> +appropriate endpoint. Actually, the service's virtual IP address is used to populate the environment variables and DNS records (and port).
How about:
```suggestion
appropriate endpoint. Actually, the kubelet on each node populates environment variable
for containers based on the port number for the Service and on the virtual IP address
(_cluster IP_), if any, that has been assigned.
The cluster DNS component also looks up the port and the virtual IP address for each
Service and make that information available within the cluster, through DNS.
For `type: ExternalName` Services, the DNS server maps the Service to that external
name, without resolving anything to a virtual IP address.
```

2023-02-23 20:30 UTC, sftim commented
LGTM for docs

2023-02-23 20:51 UTC, aojea commented on content/en/docs/reference/networking/virtual-ips.md
> +For `type: ExternalName` Services, the DNS server maps the Service to that external
is ExternalName meaningful in this context?

2023-02-23 20:56 UTC, aojea commented on content/en/docs/reference/networking/virtual-ips.md
> +The cluster DNS component also looks up the port and the virtual IP address for each
DNS does not care about the ports, unless you are using SRV records, but that is not common.

You may want to reference https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#services ?

2023-03-20 19:58 UTC, natalisucks commented
Hi @satyamkale27 – you've had a technical review from SIG Network here, so am checking that you're looking to incorporate this feedback. Thanks!

2023-04-04 07:54 UTC, divya-mohan0209 requested changes
Grammatical nits.

2023-04-04 07:54 UTC, divya-mohan0209 commented on content/en/docs/reference/networking/virtual-ips.md
> +for containers based on the port number for the Service and on the virtual IP address
nit.
```suggestion
for containers based on the port number for the Service and the virtual IP address
```

2023-04-04 07:54 UTC, divya-mohan0209 commented on content/en/docs/reference/networking/virtual-ips.md
> +(_cluster IP_), if any, that has been assigned.
Grammatical nit. We are talking about the assignment of port number & virtual IP address = 2 things. The appropriate verb would be "have"
```suggestion
(_cluster IP_), if any, that have been assigned.
```

2023-04-04 07:54 UTC, divya-mohan0209 commented on content/en/docs/reference/networking/virtual-ips.md
> +Service and make that information available within the cluster, through DNS.
nit.
```suggestion
Service and makes that information available within the cluster, through DNS.
```

2023-07-13 05:24 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2023-07-13 05:26 UTC, divya-mohan0209 commented
Hello @satyamkale27 , thank you for your contributions! This has been inactive for quite some time without any response from your end & per our guidelines around inactive PRs, we shall be closing it off. In the event, you have the bandwidth, please feel free to resume work on getting the changes merged by issuing the /reopen command in the PR comments.

/close

2023-07-13 05:26 UTC, closed without merging