[zh-cn]sync scheduling-eviction/topology-spread-constraints.md
kubernetes/website pull request #38366
Opened 2022-12-10 03:06 UTC by my-git9

[zh-cn]sync scheduling-eviction/topology-spread-constraints.md

2022-12-20 04:54 UTC, mengjiao-liu requested changes

2022-12-20 04:54 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
> +  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来关闭此此特性。
```suggestion
  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来禁用此特性。
```

2022-12-20 04:54 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
>    [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来禁用该字段。
upstream main branch have updated the content. Please resync the file.
```
./scripts/lsync.sh content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.m
```

see https://github.com/kubernetes/website/pull/38566

2022-12-20 04:54 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
> +  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来关闭此特性。
```suggestion
  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来禁用此特性。
```

2022-12-20 10:16 UTC, mengjiao-liu requested changes

2022-12-20 10:16 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
> +  `minDomains` 字段是一个 Alpha 字段，在 1.25 中默认被禁用。
```suggestion
  `minDomains` 字段是一个 Beta 字段，在 1.25 中默认被禁用。
```

2022-12-20 10:16 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
> +  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来关禁用此特性。
```suggestion
  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来禁用此字段。
```

2022-12-20 10:16 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/scheduling-eviction/topology-spread-constraints.md
> +  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来禁用此特性。
```suggestion
  [特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)来禁用此字段。
```

2022-12-20 10:21 UTC, mengjiao-liu commented
/lgtm

2022-12-22 13:02 UTC, tengqm commented
Thanks.
/approve

2022-12-22 13:03 UTC, merged