[en] fix misplaced quotation mark in multi-tenancy page
kubernetes/website pull request #38391
Opened 2022-12-10 21:16 UTC by oscr

Fixes a misplaced and miss-formatted quotation mark in the multi-tenancy page. 

Reference: https://kubernetes.io/docs/concepts/security/multi-tenancy/#multiple-customers

2022-12-10 21:32 UTC, onlydole reviewed
Hello, @osc! Thank you for your contribution.

This proposed change is grammatically correct and doesn't needed to be updated some great examples of this can be found here: https://www.thesaurus.com/e/grammar/does-punctuation-go-inside-or-outside-quotation-marks/

2022-12-10 22:34 UTC, oscr commented
@onlydole Thank you for explaining this interesting English feature. TIL. Follow up question: is the type of quotation mark also correct (I changed `”` to `"`)?

2022-12-11 17:44 UTC, onlydole commented
Howdy, @oscr - happy to help! 

For the quote styling, my preference would be the `"` version and to have matching quote styles, so that would be worth changing.

2022-12-11 17:44 UTC, onlydole requested changes

2022-12-11 17:44 UTC, onlydole commented on content/en/docs/concepts/security/multi-tenancy.md
> +term might be "multi-customer tenancy", since SaaS vendors may also use other deployment models,
```suggestion
term might be "multi-customer tenancy," since SaaS vendors may also use other deployment models,
```

2022-12-12 15:54 UTC, onlydole commented
Thank you, @oscr! 

/lgtm

2022-12-12 15:54 UTC, onlydole approved these changes

2022-12-12 15:55 UTC, merged