[zh-cn] sync feature-gates-removed.md
kubernetes/website pull request #38487
Opened 2022-12-15 08:00 UTC by gaogao101

Signed-off-by: Gao Qian <gaoq.jy@fujitsu.com>

2022-12-17 10:15 UTC, my-git9 reviewed
/lgtm

2022-12-17 10:19 UTC, my-git9 requested changes

2022-12-17 10:19 UTC, my-git9 commented on content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed.md
> +  特性以考虑 Pod 开销。
```suggestion
  特性以计算 Pod 开销。
```

2022-12-17 10:21 UTC, my-git9 commented
/lgtm cancel

2022-12-17 14:10 UTC, tengqm commented on content/zh-cn/docs/reference/command-line-tools-reference/feature-gates-removed.md
> +- `CSRDuration`：允许客户端请求通过 Kubernetes CSR API 签署的证书的有效期限。
```suggestion
- `CSRDuration`：允许客户端为通过 Kubernetes CSR API 签署的证书申请有效期限。
```

2022-12-22 04:46 UTC, tengqm commented
/lgtm
/approve

2022-12-22 04:47 UTC, merged