[bn] Localized content/bn/includes/task-tutorial-prereqs.md
kubernetes/website pull request #38506
Opened 2022-12-16 06:33 UTC by Arindam200

Signed-off-by: Arindam Majumder [arindammajumder2020@gmail.com]
Localizes `content/bn/includes/task-tutorial-prereqs.md` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/kubernetes/website/issues/31677

2022-12-17 06:11 UTC, Arhell reviewed
Please sign CLA

2022-12-18 05:50 UTC, rajibmitra commented
@Arindam200 thank you for the PR. 
LGTM but you have to sign the CLA.

2022-12-18 07:59 UTC, Arindam200 commented
> @Arindam200 thank you for the PR. 
> LGTM but you have to sign the CLA. 
> 

Thanks for mentioning it! I have signed the CLA !

2022-12-18 08:01 UTC, Arindam200 commented
> @Arindam200 thank you for the PR. 
> LGTM but you have to sign the CLA. 
> 

@Arhell 

I have signed the CLA! 

What do I have to do now?

2022-12-23 04:17 UTC, mitul3737 commented
> > @Arindam200 thank you for the PR.
> > LGTM but you have to sign the CLA.
> 
> @Arhell
> 
> I have signed the CLA!
> 
> What do I have to do now?

I will review the code now.

2022-12-23 04:20 UTC, mitul3737 requested changes

2022-12-23 04:20 UTC, mitul3737 commented on content/bn/includes/task-tutorial-prereqs.md
> +আপনার একটি Kubernetes ক্লাস্টার থাকতে হবে এবং আপনার ক্লাস্টারের সাথে যোগাযোগের জন্য kubectl কমান্ড-লাইন টুলটি কনফিগার করা আবশ্যক । কমপক্ষে দুটি নোড সহ একটি ক্লাস্টারে (যা কন্ট্রোল প্লেন হোস্টট হিসাবে
```suggestion
আপনার একটি Kubernetes ক্লাস্টার থাকতে হবে এবং আপনার ক্লাস্টারের সাথে যোগাযোগের জন্য kubectl কমান্ড-লাইন টুলটি কনফিগার করা আবশ্যক । কমপক্ষে দুটি নোড সহ একটি ক্লাস্টারে (যা কন্ট্রোল প্লেন হোস্ট হিসাবে কাজ করছে না) এই টিউটোরিয়ালটি চালাতে হবে । আপনার যদি ইতিমধ্যে একটি ক্লাস্টার না থাকে তবে আপনি [minikube](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/) ব্যবহার করে একটি তৈরি করতে পারেনি বা এই  Kubernetes playground-গুলির মধ্যে একটি ব্যবহার করতে পারেন ।
```

2022-12-23 04:25 UTC, mitul3737 approved these changes
LGTM

2022-12-23 04:26 UTC, mitul3737 commented
/label tide/merge-method-squash

2022-12-23 04:26 UTC, mitul3737 commented
/lgtm

2022-12-23 04:27 UTC, merged

2022-12-27 05:21 UTC, RockingSNP approved these changes
Awesome Work 👍👍