Update common-labels.md
kubernetes/website pull request #38729
Opened 2023-01-03 00:32 UTC by xfc

To fix a typo.

2023-01-03 02:09 UTC, divya-mohan0209 requested changes
I think the sentence could do with rephrasing to a simpler format since it currently sounds ambiguous. Would you be up to it @xfc ?

2023-01-03 02:10 UTC, divya-mohan0209 commented
Also, please sign the CLA before any further commits are pushed @xfc

2023-01-03 02:55 UTC, xfc commented
> I think the sentence could do with rephrasing to a simpler format since it currently sounds ambiguous. Would you be up to it @xfc ?

Hi @divya-mohan0209 , thanks for the feedback. I just signed the CLA. 
The meaning of the sentence seems clear enough for me. A rephrasing could make it wordy.

2023-01-03 03:05 UTC, divya-mohan0209 requested changes
For better clarity.

2023-01-03 03:05 UTC, divya-mohan0209 commented on content/en/docs/concepts/overview/working-with-objects/common-labels.md
> +example, WordPress has an `app.kubernetes.io/name` of `wordpress` while it has
```suggestion
example, WordPress has an application name, represented as `app.kubernetes.io/name` with a value of `wordpress` while it has
```

2023-01-03 03:14 UTC, divya-mohan0209 commented
@xfc : I would try making it as idiomatic as possible at the expense of wordiness because merely stating the below could confuse a new user. I've suggested a rephrasing incorporating your suggestion.

> WordPress has an `app.kubernetes.io/name` of `wordpress`

2023-01-03 04:49 UTC, tengqm commented
does this fall into trivial edits category?

2023-01-03 04:51 UTC, divya-mohan0209 commented
Yep, it does @tengqm

2023-02-01 21:58 UTC, xfc commented
I'm not sure whether this falls to the trivial edits category, what I do know is this is an error.
I heard the story that Donald Kruth paid real money for every person who spotted any typo in his book. I like the Kubernetes's documention and would like it to be as perfect as possible, (or as perfect as Kruth's books).

2023-02-02 03:24 UTC, tengqm commented
@xfc Would you like revise the text as per suggested by Divya?

2023-02-23 00:54 UTC, kbhawkey commented on content/en/docs/concepts/overview/working-with-objects/common-labels.md
> +example, WordPress has an `app.kubernetes.io/name` of `wordpress` while it has
Hello @xfc .
You could accept the suggested changes, or clarify the text a bit more.

2023-03-20 19:46 UTC, natalisucks commented
Hi @xfc – if you could please review the changes as proposed by Divya and accept them, or add your own clarification that improves on your initial change, then I'd be happy to approve this PR. Thanks!

2023-07-11 01:51 UTC, kbhawkey commented
Hello @xfc .
I am closing this pull request. It is okay to reopen the PR and continue to work on the changes.
/close

2023-07-11 01:51 UTC, closed without merging