[es] Add content/es/docs/concepts/security/pod-security-policy.md
kubernetes/website pull request #38888
Opened 2023-01-11 20:37 UTC by krol3

Related the issue https://github.com/kubernetes/website/issues/13948
cc: @electrocucaracha

2023-01-13 11:38 UTC, raelga approved these changes

2023-01-19 17:00 UTC, electrocucaracha requested changes

2023-01-19 17:00 UTC, electrocucaracha commented on content/es/docs/concepts/security/pod-security-policy.md
> +{{% alert title="Función eliminada" color="warning" %}}
```suggestion
{{% alert title="Característica eliminada" color="warning" %}}
```

2023-01-19 17:00 UTC, electrocucaracha commented on content/es/docs/concepts/security/pod-security-policy.md
> +- Un plugin de admisión de terceros, que implementa y configura usted mismo
```suggestion
- Un plugin de admisión de terceros, que implemente y configure usted mismo
```

2023-01-19 17:00 UTC, electrocucaracha commented on content/es/docs/concepts/security/pod-security-policy.md
> +[Deprecación de PodSecurityPolicy: Pasado, Presente y Futuro](/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/).
```suggestion
[Obsolescencia de PodSecurityPolicy: Pasado, Presente y Futuro](/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/).
```

2023-01-20 12:48 UTC, krol3 commented on content/es/docs/concepts/security/pod-security-policy.md
> +PodSecurityPolicy está en [deprecación](/blog/2021/04/08/kubernetes-1-21-release-announcement/#podsecuritypolicy-deprecation)
@electrocucaracha  a palabra deprecación, me parece mas próxima de deprecation, porque obsoleto seria más recomendable?

2023-01-24 16:40 UTC, ramrodo commented on content/es/docs/concepts/security/pod-security-policy.md
> +PodSecurityPolicy está en [deprecación](/blog/2021/04/08/kubernetes-1-21-release-announcement/#podsecuritypolicy-deprecation)
Aquí según [un tweet de la RAE](https://twitter.com/RAEinforma/status/1228256475535093760?s=20&t=yTXtVZTiOuv56fpg5hrm_g) no se recomienda _deprecado_, se recomienda _obsoleto_ (según nuestro contexto)

2023-01-24 16:41 UTC, krol3 commented on content/es/docs/concepts/security/pod-security-policy.md
> +{{% alert title="Función eliminada" color="warning" %}}
Funcionalidad!

2023-02-14 17:05 UTC, electrocucaracha commented
/lgtm

2023-02-14 17:07 UTC, merged