Localize content/en/docs/reference/glossary/helm-chart.md in hindi
kubernetes/website pull request #38955
Opened 2023-01-16 16:12 UTC by taniaduggal

Signed-off-by: Tania Duggal <103496926+taniaduggal@users.noreply.github.com>
fixes #37078

2023-01-16 17:36 UTC, bishal7679 approved these changes
Taking ref from #37078
/lgtm

2023-01-17 04:15 UTC, divya-mohan0209 requested changes

2023-01-17 04:15 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/helm-chart.md
> +कुबेरनेट्स एप्लिकेशन बनाने और साझा करने के लिए चार्ट एक प्रतिलिपि प्रस्तुत करने योग्य तरीका प्रदान करते हैं।
```suggestion
चार्ट्स कुबेरनेट्स एप्लिकेशन बनाने और साझा करने के लिए एक पुनरुत्पादनीय तरीका प्रदान करते हैं।
```

2023-01-17 04:37 UTC, divya-mohan0209 requested changes

2023-01-17 04:37 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/helm-chart.md
> +हेल्म चार्ट(Helm Chart) पूर्व-कॉन्फ़िगरड़ (pre-configured) कुबेरनेट्स संसाधनों का एक पैकेज है जिसे हेल्म टूल के माध्यम से प्रबंधित किया जा सकता है।
```suggestion
हेल्म चार्ट(Helm Chart) पूर्व-कॉन्फ़िगर (pre-configured) किए गए कुबेरनेट्स संसाधनों का एक पैकेज है जिसे हेल्म टूल के माध्यम से प्रबंधित किया जा सकता है।
```

2023-01-17 04:52 UTC, divya-mohan0209 reviewed
/approve

2023-01-17 05:12 UTC, bishal7679 approved these changes
/lgtm

2023-01-17 05:14 UTC, merged