[ru] Localization of /concepts/scheduling-eviction/assign-pod-node.md
kubernetes/website pull request #39162
Opened 2023-01-30 12:42 UTC by kirkonru

Add RU localization for assign-pod-node.md.

2023-02-10 09:29 UTC, shurup requested changes
A great effort is made here. However, it's not fully translated yet. I reviewed the ready part of this document.

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +## Правила совместного/раздельного существования (affinity и anti-affinity)
```suggestion
## Правила совместного/раздельного существования (affinity и anti-affinity) {#affinity-and-anti-affinity}
```
We need to keep the original titles here to make the anchor links work.

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Значения этих лейблов зависят от облачного провайдера и не гарантируются.
```suggestion
Значения этих лейблов зависят от облачного провайдера, поэтому нельзя точно на них полагаться.
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +
```suggestion
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +`nodeSelector` — самый простой способ развернуть Pod'ы на узлах с определенными лейблами. Плавила совместного/раздельного существования расширяют типы ограничений, которые можно накладывать. Вот неко
```suggestion
`nodeSelector` — самый простой способ развернуть Pod'ы на узлах с определенными лейблами. Правила совместного/раздельного существования расширяют типы ограничений, которые можно накладывать. Вот некоторые из их преимуществ:
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Правила совместного существования для узлов концептуально похожи на `nodeSelector`. С помощью лейблов они позволяют ограничивать список узлов, на которые может быть запланирован Существует два типа т
```suggestion
Правила совместного существования для узлов концептуально похожи на `nodeSelector`. С помощью лейблов они позволяют ограничивать список узлов, на которые может быть запланирован Pod. Существует два типа таких правил:
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Можно использовать поле `operator` для указания логического оператора, который Kubernetes будет использовать при интерпретации правил. Доступны `In`, `NotIn`, `Exists`, `DoesNotExist`, `Gt` и `Lt`.
```suggestion
Можно использовать поле `operator` для указания логического оператора, который Kubernetes будет применять при интерпретации правил. Доступны `In`, `NotIn`, `Exists`, `DoesNotExist`, `Gt` и `Lt`.
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Когда указаны и `nodeSelector`, и `nodeAffinity`,  Pod будет запланирован на узел только в том случае, если *оба* этих параметра удовлетворены.
```suggestion
Когда указаны и `nodeSelector`, и `nodeAffinity`, Pod будет запланирован на узел только в том случае, если *оба* этих параметра удовлетворены.
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Если задать несколько выражений `matchExpressions` для одного условия `nodeSelectorTerms`, Pod будет запланирован на узел только если удовлетворены все выражения `matchExpressions`. {{}}
```suggestion
Если задать несколько выражений `matchExpressions` для одного условия `nodeSelectorTerms`, Pod будет запланирован на узел, только если удовлетворены все выражения `matchExpressions`. {{}}
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Итоговая сумма добавляется к оценке, полученной при анализе других параметров, влияющих на приоритета узл. Принимая решение о размещении Pod'а, планировщик отдает предпочтение узлам с наибольшей сумм
```suggestion
Итоговая сумма добавляется к оценке, полученной при анализе других параметров, влияющих на приоритет узла. Принимая решение о размещении Pod'а, планировщик отдает предпочтение узлам с наибольшей суммарной оценкой.
```

2023-02-10 09:29 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Правило addedAffinity применяется ко всем Pod'ам с полем `.spec.schedulerName`, имеющем значение `foo-scheduler`, в дополнение к NodeAffinity, заданному в PodSpec. Таким образом, подходящие для Pod'а
```suggestion
Правило `addedAffinity` применяется ко всем Pod'ам с полем `.spec.schedulerName`, имеющем значение `foo-scheduler`, в дополнение к NodeAffinity, заданному в PodSpec. Таким образом, подходящие для Pod'а узлы должны удовлетворять параметрам `addedAffinity` и правилам `.spec.NodeAffinity` Pod'а.
```

2023-04-27 18:08 UTC, kirkonru commented
/retest

2023-04-27 18:14 UTC, kirkonru commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Дополнительные сведения о принципах их работы читайте в разделе ["Ограничения на топологию распределения подов"](/docs/concepts/scheduling-eviction/topology-spread-constraints/).
```suggestion
Дополнительные сведения о принципах их работы читайте в разделе [Ограничения на топологию распределения подов](/docs/concepts/scheduling-eviction/topology-spread-constraints/).
```

2023-05-18 10:47 UTC, shurup requested changes
Thank you, @kirkonru! Here are a few tiny corrections for me.

More importantly, I think the `content/ru/docs/reference/issues-security/*` files were included in this PR by some mistake? They are not translated and don't seem to be relevant to the main article.

2023-05-18 10:47 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +В дополнение к `labelSelector` и `topologyKey` можно опционально указать список пространств имен, которые должен выбирать `labelSelector`, с помощью поля `namespaces` на том же уровне, что и `labelSe
```suggestion
В дополнение к `labelSelector` и `topologyKey` можно опционально указать список пространств имен, которые должен выбирать `labelSelector`, с помощью поля `namespaces` на том же уровне, что `labelSelector` и `topologyKey`. Если поле `namespaces` опущено или пусто, по умолчанию выбирается пространство имен пода, в котором задаются правила совместного/раздельного существования.
```

2023-05-18 10:47 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Правила совместного/раздельного существования для подов особенно удобны, когда используются совместно с абстракциями более высокого уровня, такими как ReplicaSet, StatefulSet, Deployment, и т.д. Эти
```suggestion
Правила совместного/раздельного существования для подов особенно удобны, когда используются совместно с абстракциями более высокого уровня, такими как ReplicaSet, StatefulSet, Deployment и т.д. Эти правила позволяют настроить размещение рабочих нагрузок с учетом имеющейся топологии; например, пара связанных подов будет размещена на одном узле.
```

2023-05-18 10:47 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +Развертывание ресурсов в соответствии с приведенными выше конфигурациями приведет к созданию кластера, в котором на каждом узле будет по одному веб-серверу и одное реплике Redis (всего три отдельных
```suggestion
Развертывание ресурсов в соответствии с приведенными выше конфигурациями приведет к созданию кластера, в котором на каждом узле будет по одному веб-серверу и одной реплике Redis (всего три отдельных узла):
```

2023-05-18 10:47 UTC, shurup commented on content/ru/docs/concepts/scheduling-eviction/assign-pod-node.md
> +## Ограничения на топологию распределения подов.
```suggestion
## Ограничения на топологию распределения подов
```

2023-08-17 02:50 UTC, divya-mohan0209 commented
Hello @kirkonru , please do not make changes to multiple localization files over the same PR since the process for each localization differs.

2023-10-07 12:12 UTC, tengqm commented
/close
A long time has passed.
Feel free to reopen this PR to move it forward.

2023-10-07 12:12 UTC, closed without merging