[hi] Localize content/hi/docs/contribute/new-content/new-features.md
kubernetes/website pull request #39197
Opened 2023-02-01 03:39 UTC by amolmote

Signed-off-by: Amol Mote <amolmote201@gmail.com>
Fixes subtopic issue https://github.com/kubernetes/website/issues/36468 [hi] Localize en/docs/contribute/new-content/new-features.md into hi/docs/contribute/new-content/new-features.md
which is the sub-issue of https://github.com/kubernetes/website/issues/36455

2023-02-01 18:52 UTC, Babapool reviewed
Some suggestions from myside, hope you find them useful. Thanks

2023-02-01 18:52 UTC, Babapool commented on content/hi/docs/contribute/new-content/new-features.md
> +यदि आपके PR को अभी तक रिलीज की समय सीमा तक `dev-{{< skew nextMinorVersion >}}` शाखा में विलय नहीं किया गया है, तो रिलीज को प्रबंधित करने वाले डॉक्स व्यक्ति के साथ काम करें ताकि इसे समय सीमा तक प्राप्
Wouldn't it be better if we transliterate `milestone` here, thoughts @amolmote?
```suggestion
यदि आपके PR को रिलीज़ की समय सीमा तक `dev-{{< skew nextMinorVersion >}}` शाखा में विलय नहीं किया गया है, तो प्रलेखन टीम के सदस्य के साथ काम करें जो रिलीज़ का प्रबंधित करें ताकि इसे समय सीमा तक प्राप्त किया जा सके। यदि आपकी सुविधा को प्रलेखीकरण की आवश्यकता है और प्रलेखन तैयार नहीं हैं, तो सुविधा को माइलस्टोन से हटाया जा सकता है।
```

2023-02-01 18:52 UTC, Babapool commented on content/hi/docs/contribute/new-content/new-features.md
> +सामान्य तौर पर, प्रलेखीकरण योगदानकर्ता किसी रिलीज़ के लिए शुरू से ही सामग्री नहीं लिखते हैं।
```suggestion
सामान्य तौर पर, प्रलेखीकरण योगदानकर्ता किसी रिलीज़ की सामग्री शुरू से ही नहीं लिखते हैं।
```

2023-02-05 14:17 UTC, amolmote commented on content/hi/docs/contribute/new-content/new-features.md
> +सामान्य तौर पर, प्रलेखीकरण योगदानकर्ता किसी रिलीज़ के लिए शुरू से ही सामग्री नहीं लिखते हैं।
i don't this require to change

2023-02-05 14:18 UTC, amolmote commented
@Babapool ,i have accepted your some suggestion which i found useful, can you pls review this again

2023-05-07 19:34 UTC, Babapool commented
/remove-lifecycle stale

2023-07-21 13:20 UTC, kundan2707 requested changes

2023-07-21 13:20 UTC, kundan2707 commented on content/hi/docs/contribute/new-content/new-features.md
> +आम तौर पर, सुविधा के लिए जिम्मेदार SIG सुविधा के ड्राफ्ट प्रलेखन को `kubernetes/website` रिपॉजिटरी की उपयुक्त विकास शाखा को पुल अनुरोध के रूप में प्रस्तुत करता हैं, और SIG डॉक्स टीम में कोई व्यक्ति स
और SIG डॉक्स टीम में कोई व्यक्ति संपादकीय प्रतिक्रिया प्रदान करता है

2023-09-07 06:57 UTC, aj11anuj commented on content/hi/docs/contribute/new-content/new-features.md
> +यदि आपके PR को रिलीज़ की समय सीमा तक `dev-{{< skew nextMinorVersion >}}` शाखा में विलय नहीं किया गया है, तो प्रलेखन टीम के सदस्य के साथ काम करें जो रिलीज़ का प्रबंधित करें ताकि इसे समय सीमा तक प्राप्
```suggestion
यदि आपके PR को रिलीज़ की समय सीमा तक `dev-{{< skew nextMinorVersion >}}` शाखा में विलय नहीं किया गया है, तो प्रलेखन टीम के सदस्य के साथ काम करें जो रिलीज़ का प्रबंधन करेंगे, ताकि इसे समय सीमा तक प्राप्त किया जा सके। यदि आपकी सुविधा को प्रलेखीकरण की आवश्यकता है और प्रलेखन तैयार नहीं हैं, तो सुविधा को माइलस्टोन से हटाया जा सकता है।
```

2023-09-07 06:57 UTC, aj11anuj commented on content/hi/docs/contribute/new-content/new-features.md
> +प्रत्येक प्रमुख कुबेरनेट्स रिलीज़ नई सुविधाएँ शामिल होती हैं जिनके लिए प्रलेखन की आवश्यकता होती है। नई रिलीज़ मौजूदा सुविधाओं और प्रलेखन में भी अपडेट लाती हैं (जैसे किसी सुविधा को अल्फा से बीटा में अ
```suggestion
प्रत्येक प्रमुख कुबेरनेट्स रिलीज़ में नई सुविधाएँ शामिल होती हैं, जिनके लिए प्रलेखन की आवश्यकता होती है। नई रिलीज़ मौजूदा सुविधाओं और प्रलेखन में भी अपडेट लाती हैं (जैसे किसी सुविधा को अल्फा से बीटा में अपग्रेड करना)।
```

2023-09-07 06:59 UTC, aj11anuj commented on content/hi/docs/contribute/new-content/new-features.md
> +  title:  Documenting a feature for a release
This one is also essential

2023-09-07 07:11 UTC, aj11anuj commented on content/hi/docs/contribute/new-content/new-features.md
> +प्रलेखन या सहायता के लिए एक सुविधा चुनने के बाद, इसके बारे में `#sig-docs` स्लैक चैनल में, साप्ताहिक SIG डॉक्स मीटिंग में, या सीधे सुविधा SIG द्वारा दायर PR पर पूछें। यदि आपको आगे बढ़ने की अनुमति दी
```suggestion
प्रलेखन या सहायता के लिए एक सुविधा चुनने के बाद, इसके बारे में `#sig-docs` स्लैक चैनल में, साप्ताहिक SIG डॉक्स मीटिंग में, या सीधे SIG सुविधा द्वारा PR पर पूछें। यदि आपको आगे बढ़ने की अनुमति दी गई हैं, तो आप वर्णित तकनीकों में से एक का उपयोग करके [किसी अन्य व्यक्ति के PR में कमिट](/docs/contribute/review/for-approvers/#commit-into-another-persons-pr) करके PR में संपादित कर सकते हैं।
```

2023-09-07 07:15 UTC, aj11anuj commented on content/hi/docs/contribute/new-content/new-features.md
> +प्रलेखन या सहायता के लिए एक सुविधा चुनने के बाद, इसके बारे में `#sig-docs` स्लैक चैनल में, साप्ताहिक SIG डॉक्स मीटिंग में, या सीधे सुविधा SIG द्वारा दायर PR पर पूछें। यदि आपको आगे बढ़ने की अनुमति दी
That link also needs to be updated, as this link is redirecting towards english page. But currently as that page in hindi doesn't exists. So, its fine for this PR to mention english docs link

2023-09-07 07:22 UTC, aj11anuj requested changes
Apart from english docs links that can't be changed as in hindi that page doesn't exists, these are some of suggested changes from me. There are some other suggestions too that i haven't pointed that can be easily changed by author by just reading every sentence line by line once.

2023-12-07 04:59 UTC, divya-mohan0209 commented
@amolmote Please advise if you are able to address the suggestions above?

2024-03-30 08:32 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2024-03-30 08:32 UTC, divya-mohan0209 commented
Hello @amolmote , please could you advise if this is something you have the bandwidth to continue working on?

2024-05-24 10:03 UTC, sftim commented
/area localization

2024-06-05 05:27 UTC, pranav-pandey0804 commented
hello @amolmote , are you working on this issue?
If you're still working on this then please check the suggestions and take appropriate action, it has been inactive for a long time >

2024-06-05 13:07 UTC, amolmote commented
having issue in my local setup, i have directly committed the suggested change. thanks for all the suggestion and sorry for delay in my response.

2024-06-05 13:10 UTC, amolmote commented
@divya-mohan0209 , checks are failing. any idea ? I forgot many things. is it possible to re trigger the build?

2024-07-11 12:23 UTC, divya-mohan0209 commented
@amolmote Please push an empty commit.

2024-10-09 09:40 UTC, tengqm commented
/close

2024-10-09 09:40 UTC, tengqm commented
/reopen

2024-10-09 09:42 UTC, tengqm commented
The build error:

> 9:06:46 PM: Error: Error building site: "/opt/build/repo/content/en/docs/reference/issues-security/official-cve-feed.md:31:1": failed to render shortcode "cve-feed": failed to process shortcode: "/opt/build/repo/layouts/shortcodes/cve-feed.html:13:20": execute of template failed: template: shortcodes/cve-feed.html:13:20: executing "shortcodes/cve-feed.html" at <.cve_url>: can't evaluate field cve_url in type interface {}

Please rebase this to the `main` `HEAD`.

2024-10-31 10:58 UTC, divya-mohan0209 commented
@amolmote Please could you follow the instructions provided by @tengqm in [this comment](https://github.com/kubernetes/website/pull/39197#issuecomment-2401841640)?

2025-03-30 12:08 UTC, closed without merging