[zh-cn]SYNC content/zh-cn/docs/concepts/workloads/pods/_index.md
kubernetes/website pull request #39329
Opened 2023-02-07 15:14 UTC by kinzhi

2023-02-08 02:42 UTC, mengjiao-liu requested changes

2023-02-08 02:42 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +that would otherwise be inaccessible. This is available for both Windows and Linux.
The translation paragraph is too long for the reviewer, please change back to the previous segmentation method.

see [the guide](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%AE%B5%E8%90%BD%E5%88%92%E5%88%86) for more details.

2023-02-08 02:43 UTC, mengjiao-liu requested changes

2023-02-08 02:43 UTC, mengjiao-liu commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +必须启用“WindowsHostProcessContainers”[特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)。
The translation paragraph is too long for the reviewer, please change back to the previous segmentation method.

see [the guide](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#%E6%AE%B5%E8%90%BD%E5%88%92%E5%88%86) for more details.

2023-02-08 09:28 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +你的 {{< glossary_tooltip text="容器运行时" term_id="container-runtime" >}}
Where is the English text for this note now?

2023-02-08 09:28 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +你的 {{< glossary_tooltip text="容器运行时" term_id="container-runtime" >}}
when the `text` of a glossary tooltip is pure Chinese, we don't need the extra space before or after the term.

2023-02-08 09:28 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +必须支持特权容器的概念才能使用这一配置。
```suggestion
必须支持特权容器才能使用这一配置。
```

2023-02-08 09:28 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +否则将无法访问。这适用于 Windows 和 Linux。
Please translate paragraph by paragraph.
Current status is very unfriendly to reviewers. We have to scroll up and down to compare the English and Chinese text.

2023-02-08 09:28 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +Pod 必须作为 Windows HostProcess 容器运行。 HostProcess Pod 直接在主机上运行，也可以像使用 Linux 特权容器一样执行管理任务。 为了使用此功能，
There are extra spaces between sentences, please remove them.

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
>  {{< /note >}}
The correct way to translate a "note":

```
{{< note >}}
<!--
Original english text ...
-->
Translated Chinese text ...

<!--
Other paragraphs, if any
-->
Other translations.
{{< /note >}}
```

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +Pod 中的任何容器都可以在特权模式下使用操作系统管理功能，
"Any" 這個詞，在漢語表達中不要總翻譯成“任何”，有時候翻譯成“全部”、“所有”、“任一”等等更通順。

“capability”在这里翻译成“能力”是不是更合适？

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +否则将无法访问。这适用于 Windows 和 Linux。
```suggestion
这些管理能力在其他情况下是无法访问的。这适用于 Windows 和 Linux。
```

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +### Linux 特权容器{#linux-priviledged-containers}
这里所留的额外空白是有意义的，不要随便删除。我们建议留白四个空格左右。

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +在 `container.spec` 的 [安全性上下文](/zh-cn/docs/tasks/configure-pod-container/security-context/)
原来的翻译虽然绕口，但是更准确。

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +这对于想要使用操作系统管理操作网络堆栈或访问硬件设备等功能的容器很有用。
同上。原来的翻译比较准确。

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +在 Windows 中，你可以创建一个 [Windows 主机进程 Pod](/zh-cn/docs/tasks/configure-pod-container/create-hostprocess-pod)
HostProcess 是 Windows 上的一个专有词，不要翻译，尤其是遇到首字母大写的场合，是否翻译是需要斟酌的。

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +通过在 Pod 规范的安全上下文中设置 `windowsOptions.hostProcess` 标志。这些容器中的所有容器
spec 统一翻译为“规约”。
原来的译文有何不妥？

2023-02-09 02:44 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +Pod 必须作为 Windows HostProcess 容器运行。HostProcess Pod 直接在主机上运行，也可以像使用 Linux 特权容器一样执行管理任务。为了使用此功能，
对于过长行，需要在标点符号或者中英文边界处适当换行。
请参阅中文风格指南。

2023-02-12 01:36 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +### Linux containers
？

2023-02-12 01:36 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +### Windows containers
？

2023-02-12 01:36 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +[安全性上下文](/zh-cn/docs/tasks/configure-pod-container/security-context/)中的`privileged`（Linux）参数启用特权模式。
這裡沒必要改？

2023-02-12 01:36 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +HostProcess Pod 直接在主机上运行，也可以像使用 Linux 特权容器一样执行管理任务。为了使用`WindowsHostProcessContainers`功能，
過長行還是要適當折行

```suggestion
HostProcess Pod 直接在主机上运行，也可以像使用 Linux 特权容器一样执行管理任务。
为了使用 `WindowsHostProcessContainers` 功能，
```

2023-02-12 23:56 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +必须支持特权容器才能使用这一配置。
这里拆开翻译的原因是什么？

另外，我们一般要求 `<!--` 和 `-->` 在单独的一行。

2023-02-12 23:57 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +这些管理能力在其他情况下是无法访问的。这适用于 Windows 和 Linux。
原来的翻译没什么问题？

2023-02-12 23:58 UTC, tengqm commented on content/zh-cn/docs/concepts/workloads/pods/_index.md
> +必须启用[特性门控](/zh-cn/docs/reference/command-line-tools-reference/feature-gates/)。
这个改法，尤其是最后一句，还不如原来的翻译好？

2023-02-13 02:51 UTC, kinzhi commented
/close

2023-02-13 02:52 UTC, closed without merging