[zh-cn]sync blog 2022-12-16-non-graceful-node-shutdown-to-beta.md
kubernetes/website pull request #39639
Opened 2023-02-23 14:58 UTC by my-git9

2023-02-26 06:52 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-12-16-non-graceful-node-shutdown-to-beta.md
> +在工作负载成功转移到另一个正在运行的节点并且关闭的节点已恢复后，集群操作员可以自动删除污点。
```suggestion
在工作负载成功转移到另一个正在运行的节点并且曾关闭的节点已恢复后，集群操作员可以自动删除污点。
```

2023-02-26 06:52 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-12-16-non-graceful-node-shutdown-to-beta.md
> +要了解更多信息，请阅读 Kubernetes 文档中的[非正常节点关闭](/zh-cn/docs/concepts/architecture/nodes/#non-graceful-node-shutdown)。
```suggestion
要了解更多信息，请阅读 Kubernetes 文档中的[非体面节点关闭](/zh-cn/docs/concepts/architecture/nodes/#non-graceful-node-shutdown)。
```

2023-02-26 06:52 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-12-16-non-graceful-node-shutdown-to-beta.md
> +一路上有很多人帮助审查了设计和实施。我们要感谢为这项工作做出贡献的所有人，包括在过去几年中审查
```suggestion
一路上有很多人帮助审阅了设计和实现。我们要感谢为这项工作做出贡献的所有人，包括在过去几年中审查
```

2023-02-26 06:52 UTC, tengqm commented on content/zh-cn/blog/_posts/2022-12-16-non-graceful-node-shutdown-to-beta.md
> +和实施的大约 30 人。
```suggestion
和实现的大约 30 人。
```

2023-02-28 03:45 UTC, tengqm commented
/approve

2023-02-28 03:54 UTC, mengjiao-liu requested changes

2023-02-28 03:54 UTC, mengjiao-liu commented on content/zh-cn/blog/_posts/2022-12-16-non-graceful-node-shutdown-to-beta.md
> +**注意：**在应用 out-of-service 污点之前，你必须验证节点是否已经处于关闭或断电状态（而不是在重新启动中），
The preview page： https://deploy-preview-39639--kubernetes-io-main-staging.netlify.app/zh-cn/blog/2022/12/16/kubernetes-1-26-non-graceful-node-shutdown-beta/#%E5%AE%83%E6%98%AF%E5%A6%82%E4%BD%95%E5%B7%A5%E4%BD%9C%E7%9A%84

<img width="726" alt="image" src="https://user-images.githubusercontent.com/44460091/221749436-fe1bd5b5-fda1-473f-ac9c-2c29bc8e8c12.png">


加粗未生效，请更新。

2023-02-28 03:57 UTC, mengjiao-liu commented on content/zh-cn/blog/_posts/2022-12-16-non-graceful-node-shutdown-to-beta.md
> +则集群操作员可以通过自动应用“服务中断”污点来自动执行此过程。
```suggestion
则集群操作员可以通过自动应用 `out-of-service` 污点来自动执行此过程。
```

2023-03-02 15:12 UTC, windsonsea commented
Thanks.
/lgtm

2023-03-02 15:14 UTC, merged