[en] Update outdated update-readme-doc
kubernetes/website pull request #39678
Opened 2023-02-26 14:19 UTC by madhumita-kundo

**Changes :**

Update Swagger specification to `Swagger specification(currently known as OpenAPI specification) ` in README.md file for more clarity.

2023-02-26 20:24 UTC, dipesh-rawat commented
Hi @madhumita-kundo, and thank you for your fix! Could you please sign the CLA before your PR can be reviewed.

For steps to sign the CLA please refer: https://github.com/kubernetes/community/blob/master/CLA.md

2023-02-27 07:07 UTC, Arhell reviewed
/easycla

2023-02-27 15:57 UTC, madhumita-kundo commented
> Hi @madhumita-kundo, and thank you for your fix! Could you please sign the CLA before your PR can be reviewed.
> 
> For steps to sign the CLA please refer: https://github.com/kubernetes/community/blob/master/CLA.md

It is done now...thank you @dipesh-rawat

2023-02-27 15:57 UTC, madhumita-kundo commented
> /easycla

It is done now...thank you @Arhell

2023-02-28 16:18 UTC, NitishKumar06 reviewed
PTAL!

2023-02-28 16:18 UTC, NitishKumar06 commented on README.md
> +The API reference pages located in `content/en/docs/reference/kubernetes-api` are built from the Swagger specification (currently known as OpenAPI specification), using <https://github.com/kubernetes
```suggestion
The API reference pages located in `content/en/docs/reference/kubernetes-api` are built from the Swagger specification, also known as OpenAPI specification that is using <https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-resourcesdocs>.
```

2023-03-02 09:45 UTC, madhumita-kundo commented
> Sorry for the failure it's because of my changes. If you want it to work:
> 
> 1. [Synchronize your fork with upstream](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork)
> 2. Get the new changes on main: `git fetch && git checkout main && git pull origin main`
> 3. Rebase your branch on main `git checkout update-readme-doc && git rebase -i main`

Thank you very much @mtardy ....it's working now...

2023-03-03 02:41 UTC, divya-mohan0209 requested changes
Added commas + amended wording.

2023-03-03 02:41 UTC, divya-mohan0209 commented on README.md
> +The API reference pages located in `content/en/docs/reference/kubernetes-api` are built from the Swagger specification, also known as OpenAPI specification that is using <https://github.com/kubernete
```suggestion
The API reference pages located in `content/en/docs/reference/kubernetes-api` are built from the Swagger specification, also known as OpenAPI specification, using <https://github.com/kubernetes-sigs/reference-docs/tree/master/gen-resourcesdocs>.
```

2023-03-03 14:10 UTC, madhumita-kundo commented
> Added commas + amended wording.

Hi @divya-mohan0209 ...I have updated the pr with suggested changes...thank you

2023-03-06 13:17 UTC, dipesh-rawat reviewed
All the suggested fixes have been applied. Looks good to me.

2023-03-06 13:19 UTC, madhumita-kundo commented
> All the suggested fixes have been applied. Looks good to me.

Thank you @dipesh-rawat ...what should be my next course of action?

2023-03-07 05:19 UTC, NitishKumar06 commented
/lgtm

2023-03-07 13:15 UTC, bradtopol commented
/assign

2023-03-07 13:16 UTC, bradtopol commented on README.md
> +The API reference pages located in `content/en/docs/reference/kubernetes-api` are built from the Swagger specification, also known as OpenAPI specification, using <https://github.com/kubernetes-sigs/
Great job!

2023-03-07 13:16 UTC, bradtopol commented
Great job!
/lgtm
/approve

2023-03-07 13:18 UTC, merged