Community page feature hi
kubernetes/website pull request #39672
Opened 2023-02-26 07:10 UTC by harish343

Fixes : 39663

New feature has been added communtiy page in hindi please review it and ping me if any changes had to be made on this repository.
Fixed localize of alt and Title

2023-02-26 07:19 UTC, harish343 commented
/assign @sftim

2023-02-26 07:19 UTC, harish343 commented
/unassign @sftim

2023-02-27 19:09 UTC, harish343 commented
Hey @sftim can you review this.

2023-02-27 19:09 UTC, sftim commented
> Hey @sftim can you review this.

It will take a while! I'd have to learn Hindi.

2023-03-04 00:24 UTC, jihoon-seo commented
/label tide/merge-method-squash

2023-04-30 07:58 UTC, Babapool reviewed
Some suggestions from my side, hope you find them useful. Thanks

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  <img src="/images/community/kubernetes-community-final-03.jpg" alt="कुबेरनेट्स कॉन्फ्रेंस गैलरी फोटो" class="community-gallery-desktop">
```suggestion
  <img src="/images/community/kubernetes-community-final-03.jpg" alt="कुबेरनेट्स सम्मेलन की गैलरी तस्वीरें" class="community-gallery-desktop">
```

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  <img src="/images/community/kubernetes-community-final-04.jpg" alt="कुबेरनेट्स कॉन्फ्रेंस गैलरी फोट" class="community-gallery-desktop">
```suggestion
  <img src="/images/community/kubernetes-community-final-04.jpg" alt="कुबेरनेट्स सम्मेलन की गैलरी तस्वीरें" class="community-gallery-desktop">
```

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  <img src="/images/community/kubernetes-community-final-05.jpg" alt="कुबेरनेट्स कॉन्फ्रेंस गैलरी फोट" class="community-gallery-desktop">
```suggestion
  <img src="/images/community/kubernetes-community-final-05.jpg" alt="कुबेरनेट्स सम्मेलन की गैलरी तस्वीरें" class="community-gallery-desktop">
```

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  <img src="/images/community/kubernetes-community-04-mobile.jpg" alt="कुबेरनेट्स कॉन्फ्रेंस गैलरी फोट" class="community-gallery-mobile">
```suggestion
  <img src="/images/community/kubernetes-community-04-mobile.jpg" alt="कुबेरनेट्स सम्मेलन की गैलरी तस्वीरें" class="community-gallery-mobile">
```

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  <p>कुबेरनेट्स समुदाय के मूल्य प्रोजेक्ट की निरंतर सफलता के लिए महत्वपूर्ण होते हैं।<br class="optional"/>
```suggestion
  <p>कुबेरनेट्स समुदाय जिन मूल्यों के लिए खड़ा है, वे परियोजना की निरंतर सफलता की कुंजी हैं।<br class="optional"/>
```

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  ये सिद्धांत कुबेरनेट्स प्रोजेक्ट के हर पहलू को निर्देशित करते हैं।</p>
```suggestion
  ये सिद्धांत कुबेरनेट्स पपरियोजना के हर पहलू का मार्गदर्शन करते हैं।</p>
```

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  <p>कुबेरनेट्स समुदाय मूल्यों में सम्मान और समावेश शामिल हैं, और सभी इंटरैक्शन में आचरण संहिता का पालन करते हुए होते हैं।</p>
```suggestion
  <p>कुबेरनेट्स समुदाय मूल्यों में सम्मान और समावेश को महत्व देता, और सभी इंटरैक्शन में आचरण संहिता को लागू करता हैं।</p>
```

2023-04-30 07:58 UTC, Babapool commented on content/hi/community/_index.html
> +  <p>यदि आप किसी इवेंट या मीटिंग, <a href="#slack">स्लैक</a> या किसी अन्य संचार माध्यम में आचरण संहिता का उल्लंघन करते हुए देखते हैं, तो <a href="mailto:conduct@kubernetes.io">conduct@kubernetes.io</
```suggestion
  <p>यदि आप किसी इवेंट या मीटिंग, <a href="#slack">स्लैक</a> या किसी अन्य संचार माध्यम में आचरण संहिता का उल्लंघन करते हुए देखते हैं, तो <a href="mailto:conduct@kubernetes.io">conduct@kubernetes.io</a> पर कुबेरनेट्स आचार संहिता समिति से संपर्क करें। सभी रिपोर्ट को गोपनीय रखा जाता है। आप GitHub पर कुबेरनेट्स समुदाय रिपॉजिटरी में <a href="https://github.com/kubernetes/community/tree/master/committee-code-of-conduct">समिति के बारे में</a> पढ़ सकते हैं।</p>
```

2023-06-24 17:21 UTC, Babapool commented
@YashPimple, a friendly reminder from my end. I just wanted to confirm that since there have been no updates on this PR are you still working on this PR? Thanks

2023-06-28 15:35 UTC, anubha-v-ardhan commented
/label tide/merge-method-squash

2023-08-28 06:50 UTC, harish343 commented
Hey @Babapool can you tell me how to proceed further

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +  <p>कुबेरनेट्स समुदाय - उपयोगकर्ता, योगदानकर्ता और हम सभी ने साथ मिलकर बनाई हुई संस्कृति - इस ओपन सोर्स प्रोजेक्ट के उच्चाकांक्षी उदय के सबसे बड़े कारणों में से एक है। हमारी संस्कृति और मूल्य तब तक
```suggestion
  <p>कुबेरनेट्स समुदाय - उपयोगकर्ता, योगदानकर्ता और हम सभी ने साथ मिलकर बनाई हुई संस्कृति - इस ओपन सोर्स प्रोजेक्ट के उच्चाकांक्षी उदय के सबसे बड़े कारणों में से एक है। हमारी संस्कृति और मूल्य बढ़ते और बदलते रहते हैं जैसे की परियोजना बढ़ती है और बदलती है। हम सभी परियोजना के निरंतर सुधार और उस पर काम करने के तरीकों की दिशा में मिलकर काम करते हैं।</p>
```

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +  <img src="/images/community/kubernetes-community-final-05.jpg" alt="कुबेरनेट्स कॉन्फ्रेंस गैलरी फोट" class="community-gallery-desktop">
```suggestion
<div class="community-section" id="gallery">
  <img src="/images/community/kubernetes-community-final-03.jpg" alt="कुबेरनेट्स सम्मेलन की तस्वीरें" class="community-gallery-desktop">
  <img src="/images/community/kubernetes-community-final-04.jpg" alt="कुबेरनेट्स सम्मेलन की तस्वीरें" class="community-gallery-desktop">
  <img src="/images/community/kubernetes-community-final-05.jpg" alt="कुबेरनेट्स कॉन्फ्रेंस की तस्वीरें" class="community-gallery-desktop">
```

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +  <img src="/images/community/kubernetes-community-04-mobile.jpg" alt="कुबेरनेट्स सम्मेलन की गैलरी तस्वीरें" class="community-gallery-mobile">
```suggestion
  <img src="/images/community/kubernetes-community-04-mobile.jpg" alt="कुबेरनेट्स सम्मेलन की तस्वीरें" class="community-gallery-mobile">
```

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +  <p>कुबेरनेट्स समुदाय जिन मूल्यों के लिए खड़ा है, वे परियोजना की निरंतर सफलता की कुंजी हैं।<br class="optional"/>
```suggestion
  <p>कुबेरनेट्स समुदाय जिन मूल्यों पे खड़ा है, वे प्रोजेक्ट की निरंतर सफलता की कुंजी हैं।<br class="optional"/>
```

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +  ये सिद्धांत कुबेरनेट्स पपरियोजना के हर पहलू का मार्गदर्शन करते हैं।</p>
```suggestion
  ये सिद्धांत कुबेरनेट्स प्रोजेक्ट के हर पहलू का मार्गदर्शन करते हैं।</p>
```

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +  <p>कुबेरनेट्स समुदाय मूल्यों में सम्मान और समावेश को महत्व देता, और सभी इंटरैक्शन में आचरण संहिता को लागू करता हैं।</p>
```suggestion
  <p>कुबेरनेट्स समुदाय मूल्यों में सम्मान और समावेश को महत्व देता है, और सभी इंटरैक्शन में आचरण संहिता को लागू करता हैं।</p>
```

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +  <p class="community-simple">कुबेरनेट्स यूट्यूब पर बहुत सारे वीडियो उपलब्ध हैं। विभिन्न विषयों के लिए सब्सक्राइब करें।</p>
```suggestion
  <p class="community-simple">कुबेरनेट्स के यूट्यूब चैनल पर बहुत सारे वीडियो उपलब्ध हैं। विभिन्न विषयों के लिए सब्सक्राइब करें।</p>
```

2023-09-07 14:56 UTC, aj11anuj commented on content/hi/community/_index.html
> +       <span class="videocta">मासिक ऑफिस घंटे देखें&nbsp;&#9654;</span>
```suggestion
       <span class="videocta">मासिक ऑफिस ऑवर्स देखें&nbsp;&#9654;</span>
```

2023-09-07 14:57 UTC, aj11anuj commented on content/hi/community/_index.html
> +      <p><em>#कुबेरनेटेसियो</em></p>
```suggestion
      <p><em>#कुबेरनेट्स</em></p>
```

2023-09-07 14:57 UTC, aj11anuj commented on content/hi/community/_index.html
> +      <p>सर्वर फॉल्ट पर Kubernetes से संबंधित चर्चा। सवाल पूछें या एक का जवाब दें।</p>
```suggestion
      <p>सर्वर फॉल्ट पर कुबेरनेट्स से संबंधित चर्चा। सवाल पूछें या एक का जवाब दें।</p>
```

2023-09-07 14:57 UTC, aj11anuj commented on content/hi/community/_index.html
> +   <h2>आगामी कार्यक्रम</h2>
```suggestion
   <h2>आगे आने वाले कार्यक्रम</h2>
```

2023-09-07 14:57 UTC, aj11anuj commented on content/hi/community/_index.html
> +    दुनिया भर में 150 से अधिक मीटअप हो चुके हैं और आगे बढ़ रहे हैं, जाएं और अपने स्थानीय क्यूब लोगों को खोजें। अगर आपके पास कोई नहीं है, तो स्वयं निर्माण करें।
```suggestion
    दुनिया भर में 150+ मीटअप हो चुके हैं और आगे बढ़ रहे हैं, जाएं और अपने स्थानीय कुबेरनेट्स कम्यूनिटी के लोगों को खोजें। अगर आपके पास कोई नहीं है, तो स्वयं निर्माण करें।
```

2023-09-07 14:57 UTC, aj11anuj commented on content/hi/community/_index.html
> +    <span class="community-cta">एक मुलाकात खोजें</span>
```suggestion
    <span class="community-cta">एक मीटअप खोजें</span>
```

2023-09-07 14:57 UTC, aj11anuj commented on content/hi/community/_index.html
> +    <a class="twitter-timeline" data-tweet-limit="1" href="https://twitter.com/kubernetesio?ref_src=twsrc%5Etfw">कुबेरनेटेसियो द्वारा ट्वीट्स</a>
```suggestion
    <a class="twitter-timeline" data-tweet-limit="1" href="https://twitter.com/kubernetesio?ref_src=twsrc%5Etfw">कुबेरनेट्स द्वारा ट्वीट्स</a>
```

2023-09-07 15:03 UTC, aj11anuj commented on content/hi/community/_index.html
> +  <p> हम वे लोग हैं जो मुद्दों और पुल अनुरोध फाइल करते हैं, एसआईजी बैठकों, कुबेरनेट्स मीटअप और क्यूबेकॉन में भाग लेते हैं, इसके अपनाने और नवाचार के लिए वकालत करते हैं,
```suggestion
  <p> हम वे लोग हैं जो मुद्दों और पुल अनुरोध फाइल करते हैं, SIG मीटअप, कुबेरनेट्स मीटअप और KubeCon में भाग लेते हैं, इसके अपनाने और नवाचार के लिए वकालत करते हैं।
```

2023-09-07 15:05 UTC, aj11anuj requested changes
Work on these changes

2023-11-22 07:05 UTC, niranjandarshann commented
@harish343  
Could you please squash your commits: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits

2024-01-19 00:34 UTC, sftim commented
/retitle [hi] Localize community page

2024-05-18 07:28 UTC, niranjandarshann commented
@harish343  Are you currently working on this issue? Please make the suggested changes and address the comments. I am seeing this PR is inactive from long ago.

2024-06-10 11:37 UTC, divya-mohan0209 commented
Hi @harish343 , conversations on this PR have been going on for > 1 year & despite reminders, there has been no progress. Therefore, I shall be closing it. If you have the bandwidth to resume work on it, please feel free to reopen the PR.
/close

2024-06-10 11:37 UTC, closed without merging