[ES] Add content/es/docs/concepts/overview/working-with-objects/finalizers
kubernetes/website pull request #39783
Opened 2023-03-04 14:11 UTC by marianogg9

Added:
- glossary entry `content/es/docs/reference/glossary/finalizer.md`.
- [ES] translation `content/es/docs/concepts/overview/working-with-objects/finalizers.md`.

2023-03-04 14:39 UTC, utkarsh-singh1 commented
Hi @marianogg9, Sign EasyCla first,

please follow these guides to sign easycla,

You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla

and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor

You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

2023-03-04 15:34 UTC, marianogg9 commented
> Hi @marianogg9, Sign EasyCla first,
> 
> please follow these guides to sign easycla,
> 
> You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla
> 
> and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor
> 
> You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

@utkarsh-singh1 done

2023-03-05 00:23 UTC, Arhell reviewed
/easycla

2023-03-07 17:12 UTC, krol3 requested changes

2023-03-07 17:12 UTC, krol3 commented on content/es/docs/concepts/overview/working-with-objects/finalizers.md
> +## Referencias de dueño, etiquetas y finalizadores (#dueños-etiquetas-finalizadores)
```suggestion
## Referencias de dueño, etiquetas y finalizadores {#owners-labels-finalizers}
```

2023-03-14 16:19 UTC, krol3 approved these changes
/lgtm

2023-03-14 16:20 UTC, merged