[bn] localization content/bn/docs/setup/learning-environment/_index.md added
kubernetes/website pull request #39839
Opened 2023-03-07 15:14 UTC by sajibAdhi

Signed-off-by: Sajib Adhikary <tosajibadhi@gmail.com>
Localizes ``content/bn/docs/setup/learning-environment/_index.md``  to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #31677

2023-03-07 18:17 UTC, mitul3737 commented
@sajibAdhi Kindly localize the file. You have just changed the title but nothing else.

2023-03-08 11:20 UTC, sajibAdhi commented
> @sajibAdhi Kindly localize the file. You have just changed the title but nothing else.

@mitul3737 Kindly check the update of the file.

2023-03-08 18:45 UTC, mitul3737 requested changes

2023-03-08 18:45 UTC, mitul3737 commented on content/bn/docs/setup/learning-environment/_index.md
> +`kind` এরমত [`minikube`](https://minikube.sigs.k8s.io/) একটি টুল যেটি আপনাকে স্থানীয়ভাবে কুবারনেট (Kubernetes) চালাতে দেয়। `minikube` আপনার ব্যক্তিগত কম্পিউটারে (Windows, macOS এবং Linux PC সহ) একটি
```suggestion
`kind` এরমত [`minikube`](https://minikube.sigs.k8s.io/) একটি টুল যেটি আপনাকে স্থানীয়ভাবে কুবারনেটিস (Kubernetes) চালাতে দেয়। `minikube` আপনার ব্যক্তিগত কম্পিউটারে (Windows, macOS এবং Linux PC সহ) একটি একক-নোড (single-node) কুবারনেটিস (Kubernetes) ক্লাস্টার (cluster) চালায় যাতে আপনি কুবারনেটিস (Kubernetes) দৈনন্দিন উন্নয়ন (development) কাজের জন্য ।
```

2023-03-09 04:09 UTC, mitul3737 commented
/label tide/merge-method-squash

2023-03-09 04:09 UTC, mitul3737 approved these changes
/lgtm

2023-03-09 04:10 UTC, merged