[WIP] Placeholder PR for messageExpression update to KEP-2876
kubernetes/website pull request #40019
Opened 2023-03-15 16:18 UTC by DangerOnTheRanger

This is the placeholder docs PR for the `messageExpression` [update](https://github.com/kubernetes/enhancements/pull/3747) to [KEP-2876](https://github.com/kubernetes/enhancements/issues/2876) that was implemented by https://github.com/kubernetes/kubernetes/pull/115969.

2023-03-16 17:53 UTC, cici37 commented
/sig api-machinery
/language en

2023-03-22 00:09 UTC, jpbetz requested changes

2023-03-22 00:09 UTC, jpbetz commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +to insert more descriptive information into the validation failure message. For example:
```suggestion
Similar to the `message` field, which defines the string reported for a validation rule failure, `messageExpression` allows
you to use a CEL expression to construct the message string. This allows you to insert more descriptive information into the validation failure message.

`messageExpression` must evaluate a string and may use the same variables that are available to the `rule` field.
```

2023-03-22 00:31 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +  messageExpression: '"x exceeded max limit of " + string(self.maxLimit)'
Makes sense, I'll add some info on casting.

2023-03-22 00:37 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +will be used. However, if `messageExpression` fails at runtime, the string defined in `message` will be
Gotcha - "fails while being evaluated" seems like it might be more relatable.

2023-03-22 00:41 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +or a string containing line breaks.
No, I think you're right - I'll add the suggested changes.

2023-03-22 01:22 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +will be used. However, if `messageExpression` fails at runtime, the string defined in `message` will be
Sounds good, I'll make sure usages of "fail" are replaced - I think I had used it once or twice elsewhere.

2023-03-22 01:24 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +will be used. However, if `messageExpression` fails at runtime, the string defined in `message` will be
(marking as resolved now that "evaluates to an error" is used)

2023-03-22 16:06 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +or a string containing line breaks.
(marking as resolved - feel free to unresolve/comment if you think the wording around line breaks should be changed though)

2023-03-22 16:22 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +`messageExpression` must evaluate to a string, and this is checked at write time. Note that it is possible
(marking as resolved now that "while the CRD is being written" is used instead)

2023-03-22 20:37 UTC, jpbetz commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +in the example first.
```suggestion
Keep in mind that CEL string concatenation (`+` operator) does not auto-cast to string. If
you have a non-string scalar, use the `string(<value>)` function to cast the scalar to a string
like shown in the above example.
```

?

2023-03-22 20:44 UTC, DangerOnTheRanger commented on content/en/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions.md
> +in the example first.
Sounds good to me - fixed

2023-03-31 03:39 UTC, tengqm commented
/label tide/merge-method-squash

2023-03-31 03:40 UTC, tengqm commented
/approve

2023-03-31 03:41 UTC, merged