[hi] Localize hi/docs/partners/_index.html
kubernetes/website pull request #40030
Opened 2023-03-15 18:08 UTC by YashPimple

closed #39872

- [X] Localize hi/docs/partners/_index.html added the Partners page directory to [hi] localization

2023-03-31 05:29 UTC, kundan2707 reviewed
LGTM

2023-04-22 17:45 UTC, anubha-v-ardhan requested changes

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +cid: पार्टनर्स
```suggestion
class: gridPage
cid: partners
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +    <h5>कुबेरनेट्स भागीदारों के साथ एक मजबूत, जीवंत कोडबेस बनाने के कार्य में इस्तेमाल किया जाता है जो पूरक प्लेटफार्मों के एक स्पेक्ट्रम का समर्थन करता है।</h5>
```suggestion
    <h5>कुबेरनेट्स भागीदारों के साथ एक मज़बूत, जीवंत कोडबेस बनाने के कार्य में इस्तेमाल किया जाता है जो पूरक प्लेटफार्मों के एक स्पेक्ट्रम का समर्थन करता है।</h5>
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +          <a href="https://www.cncf.io/certification/kcsp/">KCSP</a>?
```suggestion
          <button class="button landscape-trigger landscape-default" data-landscape-types="kubernetes-certified-service-provider" id="kcsp">KCSP पार्टनर्स देखें</button>
          <br><br>
          <a href="https://www.cncf.io/certification/kcsp/">KCSP</a>बनने को इच्छुक हैं?
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +          </h5>सॉफ्टवेयर अनुरूपता यह सुनिश्चित करती है कि कुबेरनेट्स के प्रत्येक विक्रेता का संस्करण आवश्यक एपीआई का समर्थन करता है|
```suggestion
          </h5>सॉफ्टवेयर कन्फॉर्मन्स यह सुनिश्चित करती है कि कुबेरनेट्स के प्रत्येक विक्रेता का संस्करण आवश्यक एपीआई का समर्थन करता है।
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +          <button class="button landscape-trigger" data-landscape-types="certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer" id="conformance">See Conformance
```suggestion
          <button class="button landscape-trigger" data-landscape-types="certified-kubernetes-distribution,certified-kubernetes-hosted,certified-kubernetes-installer" id="conformance">कन्फॉर्मन्स पार्टनर्स देखें</button>
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +          <a href="https://www.cncf.io/certification/software-conformance/">Kubernetes Certified</a>?
```suggestion
          <br><br>
          <a href="https://www.cncf.io/certification/software-conformance/">कुबेरनेट्स प्रमाणित</a>होने को इच्छुक हैं?
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +          <br>परीक्षण किए गए प्रशिक्षण प्रदाता जिनके पास क्लाउड नेटिव प्रौद्योगिकी प्रशिक्षण का गहरा अनुभव है|
```suggestion
          <br>परीक्षण किए गए प्रशिक्षण प्रदाता जिनके पास क्लाउड नेटिव प्रौद्योगिकी प्रशिक्षण का गहरा अनुभव है। 
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +          <button class="button landscape-trigger" data-landscape-types="kubernetes-training-partner" id="ktp">See KTP Partners</button>
```suggestion
          <button class="button landscape-trigger" data-landscape-types="kubernetes-training-partner" id="ktp">KTP पार्टनर्स देखें</button>
```

2023-04-22 17:45 UTC, anubha-v-ardhan commented on content/hi/partners/_index.html
> +          <a href="https://www.cncf.io/certification/training/">KTP</a>?
```suggestion
          <br><br>
          <a href="https://www.cncf.io/certification/training/">KTP</a>बनने को इच्छुक हैं?
```

2023-06-24 17:19 UTC, Babapool commented
@YashPimple, a friendly reminder from my end. I just wanted to confirm that since there have been no updates on this PR are you still working on this PR? Thanks

2023-08-17 05:40 UTC, divya-mohan0209 commented
@YashPimple Thank you for your efforts on this! However this PR has been inactive for more than 4 months without any updates from your end. Therefore, we shall be closing it. However, if you wish to resume work on the PR whenever you have the bandwidth, please consider reopening it by issuing a /reopen command in the comments.
/close

2023-08-17 05:40 UTC, closed without merging