Create cluster-intro.html
kubernetes/website pull request #40089
Opened 2023-03-17 12:19 UTC by MashiatK

Signed-off-by: Mashiat Jamal mashiatjamal91@gmail.com
Localizes content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #31677

2023-03-18 00:43 UTC, Arhell reviewed
please sign CLA

2023-03-18 15:33 UTC, utkarsh-singh1 commented
Hi @MashiatK, please follow these guides to sign easycla,

You can find about EasyCLA here - https://docs.linuxfoundation.org/lfx/easycla

and the steps to sign EasyCLA are here - https://docs.linuxfoundation.org/v2/easycla/contributors/individual-contributor

You can start your signing EasyCLA from here - https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/38056/#/?version=2

2023-04-09 04:41 UTC, mitul3737 requested changes

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +title: একটি ক্লাস্টার তৈরি করতে Minikube ব্যবহার করে
```suggestion
title: একটি ক্লাস্টার তৈরি করতে Minikube ব্যবহার করো
```

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                <b>কুবারনেটস কম্পিউটারের একটি অত্যন্ত উপলব্ধ ক্লাস্টার সমন্বয় করে যা একটি একক হিসাবে কাজ করার জন্য সংযুক্ত।</b> Kubernetes-এর বিমূর্ততা আপনাকে বিশেষভাবে পৃথক মেশিনে না বেঁধে একটি ক্ল
```suggestion
                <b>কুবারনেটিস কম্পিউটারের একটি অত্যন্ত উপলব্ধ ক্লাস্টার সমন্বয় করে যা একটি একক হিসাবে কাজ করার জন্য সংযুক্ত।</b> Kubernetes-এর বিমূর্ততা আপনাকে বিশেষভাবে পৃথক মেশিনে না বেঁধে একটি ক্লাস্টারে কন্টেইনারাইজড অ্যাপ্লিকেশন স্থাপন করতে দেয়। স্থাপনার এই নতুন মডেলটি ব্যবহার করার জন্য, অ্যাপ্লিকেশনগুলিকে এমনভাবে প্যাকেজ করা দরকার যাতে সেগুলিকে পৃথক হোস্ট থেকে আলাদা করা যায়: তাদের কন্টেইনারাইজ করা দরকার। কন্টেইনারাইজড অ্যাপ্লিকেশনগুলি অতীতের স্থাপনার মডেলগুলির তুলনায় আরও নমনীয় এবং উপলব্ধ, যেখানে অ্যাপ্লিকেশনগুলি সরাসরি হোস্টের সাথে গভীরভাবে একত্রিত প্যাকেজ হিসাবে নির্দিষ্ট মেশিনে ইনস্টল করা হয়েছিল। <b>Kubernetes একটি ক্লাস্টার জুড়ে অ্যাপ্লিকেশন কন্টেইনারগুলির বিতরণ এবং সময়সূচীকে আরও দক্ষ উপায়ে স্বয়ংক্রিয় করে।</b> Kubernetes একটি ওপেন সোর্স প্ল্যাটফর্ম এবং এটি উৎপাদনের জন্য প্রস্তুত।
```

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                <p>>A কুবারনেটস ক্লাস্টার দুটি ধরণের সংস্থান নিয়ে গঠিত:
```suggestion
                <p>>একটি কুবারনেটিস ক্লাস্টার দুটি ধরণের সংস্থান নিয়ে গঠিত:
```

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                        <li>The <b>Control Plane</b> coordinates the cluster</li>
Kindly translate these words `Control Plane`  , `coordinates the cluster`

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                        <li><b>Nodes</b> are the workers that run applications</li>
Kindly translate these words too. `Nodes`, `are the workers that run applications`

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                    <h3>Summary:</h3>
Kindly translate this word: `Summary:`

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                        <li>Kubernetes cluster</li>
Kindly translate this word `Kubernetes cluster` , `Minikube`

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                         কুবারনেটস হল একটি প্রোডাকশন-গ্রেড, ওপেন-সোর্স প্ল্যাটফর্ম যা কম্পিউটার ক্লাস্টারের মধ্যে এবং জুড়ে অ্যাপ্লিকেশন কন্টেইনারগুলির প্লেসমেন্ট (শিডিউলিং) এবং এক্সিকিউশনকে অর্কেস্ট
```suggestion
                         কুবারনেটিস হল একটি প্রোডাকশন-গ্রেড, ওপেন-সোর্স প্ল্যাটফর্ম যা কম্পিউটার ক্লাস্টারের মধ্যে এবং জুড়ে অ্যাপ্লিকেশন কন্টেইনারগুলির প্লেসমেন্ট (শিডিউলিং) এবং এক্সিকিউশনকে অর্কেস্ট্রেট করে।
```

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                <h2 style="color: #3771e3;">Cluster Diagram</h2>
Translate the `Cluster Diagram`

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                <p><b>একটি নোড হল একটি VM বা একটি শারীরিক কম্পিউটার যা একটি কুবারনেটস ক্লাস্টারে কর্মী মেশিন হিসাবে কাজ করে।</b> প্রতিটি নোডের একটি কুবেলেট থাকে, যা নোড পরিচালনা এবং কুবারনেটস কন্ট্রো
```suggestion
                <p><b>একটি নোড হল একটি VM বা একটি শারীরিক কম্পিউটার যা একটি কুবারনেটিস ক্লাস্টারে কর্মী মেশিন হিসাবে কাজ করে।</b> প্রতিটি নোডের একটি কুবেলেট থাকে, যা নোড পরিচালনা এবং কুবারনেটিস কন্ট্রোল প্লেনের সাথে যোগাযোগের জন্য একটি এজেন্ট। নোডের কনটেইনার ক্রিয়াকলাপ পরিচালনা করার জন্য সরঞ্জাম থাকা উচিত, যেমন কন্টেইনার বা ডকার। একটি Kubernetes ক্লাস্টার যা উৎপাদন ট্র্যাফিক পরিচালনা করে তার ন্যূনতম তিনটি নোড থাকা উচিত কারণ যদি একটি নোড নিচে চলে যায়, তাহলে একটি etcd সদস্য এবং একটি কন্ট্রোল প্লেন ইনস্ট্যান্স উভয়ই হারিয়ে যায় এবং রিডানডেন্সি আপস করা হয়। আপনি আরো কন্ট্রোল প্লেন নোড যোগ করে এই ঝুঁকি কমাতে পারেন।</p>
```

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                    <p><i>Control Planes manage the cluster and the nodes that are used to host the running applications.</i></p>
Kindly translate this sentence  "Control Planes manage the cluster and the nodes that are used to host the running applications."

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                <p>এখন যেহেতু আপনি জানেন কুবারনেটস কী, আসুন অনলাইন টিউটোরিয়ালটিতে যাই এবং আমাদের প্রথম ক্লাস্টার শুরু করি!</p>
```suggestion
                <p>এখন যেহেতু আপনি জানেন কুবারনেটিস কী, আসুন অনলাইন টিউটোরিয়ালটিতে যাই এবং আমাদের প্রথম ক্লাস্টার শুরু করি!</p>
```

2023-04-09 04:41 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                <a class="btn btn-lg btn-success" href="/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/" role="button">Start Interactive Tutorial <span class="btn__next">›</span
Translate this sentence "Start Interactive Tutorial"

2023-07-08 12:09 UTC, mitul3737 commented
/close

2023-07-08 12:09 UTC, closed without merging