[bn] Localizes `content/bn/docs/tutorials/kubernetes-basics/_index.html`
kubernetes/website pull request #40097
Opened 2023-03-17 16:34 UTC by Acesif

Signed-off-by: Asif Zubayer Palak asifpalak@gmail.com
Localizes `content/bn/docs/tutorials/kubernetes-basics/_index.html`  to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #31677

2023-03-18 08:44 UTC, mitul3737 commented
Kindly remove `content/bn/docs/tasks/tools/install-kubectl-linux.md` file from this branch

2023-03-18 08:49 UTC, Acesif commented
@mitul3737 Removed the file you mentioned

2023-03-18 09:46 UTC, mitul3737 requested changes

2023-03-18 09:46 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/_index.html
> +<html lang="en">
```suggestion
<html lang="bn">
```

2023-03-18 09:46 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/_index.html
> +  name: টিউটোরিয়াল
```suggestion
  name: tutorials
```

2023-03-18 09:46 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/_index.html
> +title: কুবারনেটিস বেসিক শিখুন
```suggestion
title: কুবারনেটিসের বেসিক শিখুন
```

2023-03-18 09:46 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/_index.html
> +linkTitle: কুবারনেটিস বেসিক শিখুন
```suggestion
linkTitle: কুবারনেটিসের বেসিক শিখুন
```

2023-03-18 09:46 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/_index.html
> +        <p>এই টিউটোরিয়ালটি কুবারনেটস ক্লাস্টার অর্কেস্ট্রেশন সিস্টেমের মূল বিষয়গুলির একটি ওয়াকথ্রু প্রদান করে। প্রতিটি মডিউলে কুবারনেটসের প্রধান বৈশিষ্ট্য এবং ধারণাগুলির কিছু পটভূমি তথ্য রয়েছে এব
```suggestion
        <p>এই টিউটোরিয়ালটি কুবারনেটিস ক্লাস্টার অর্কেস্ট্রেশন সিস্টেমের মূল বিষয়গুলির একটি ধারণা প্রদান করে। প্রতিটি মডিউলে কুবারনেটিসের প্রধান বৈশিষ্ট্য এবং ধারণাগুলির কিছু পটভূমি তথ্য রয়েছে এবং একটি ইন্টারেক্টিভ অনলাইন টিউটোরিয়াল অন্তর্ভুক্ত রয়েছে। এই ইন্টারেক্টিভ টিউটোরিয়ালগুলি আপনাকে নিজের জন্য একটি সাধারণ ক্লাস্টার এবং এর ধারকযুক্ত অ্যাপ্লিকেশনগুলি পরিচালনা করতে দেয় ৷</p>
```

2023-03-18 09:46 UTC, mitul3737 commented on content/bn/docs/tutorials/kubernetes-basics/_index.html
> +      <h2>কুবারনেটিস বেসিক মডিউল</h2>
```suggestion
      <h2>কুবারনেটিসের বেসিক মডিউল</h2> 
```

2023-03-22 03:48 UTC, mitul3737 commented
/label tide/merge-method-squash

2023-03-22 03:48 UTC, mitul3737 approved these changes
/lgtm

2023-03-22 03:50 UTC, merged