[bn] Localizes data/i18n/bn/bn.toml
kubernetes/website pull request #40102
Opened 2023-03-17 22:04 UTC by nerdynikhil

Localizes `data/i18n/bn/bn.toml` to Bengali
This is an initial PR as may need some improvements!
Tracking issue: https://github.com/kubernetes/website/issues/31677

2023-03-18 16:07 UTC, mitul3737 requested changes

2023-03-18 16:07 UTC, mitul3737 commented on data/i18n/bn/bn.toml
> +#other = """1.24 রিলিজ হিসাবে Dockershim কুবারনেটস প্রকল্প থেকে সরানো হয়েছে। বিস্তারি তথ্যের জন্য <a href="/dockershim">Dockershim Removal FAQ</a> পড়ুন। """
```suggestion
#other = """1.24 রিলিজ হিসাবে Dockershim কুবারনেটিস প্রকল্প থেকে সরানো হয়েছে। বিস্তারি তথ্যের জন্য <a href="/dockershim">Dockershim Removal FAQ</a> পড়ুন। """
```

2023-03-18 16:07 UTC, mitul3737 commented on data/i18n/bn/bn.toml
> +#other = """এই বিভাগটি তৃতীয় পক্ষের প্রকল্পগুলির সাথে লিঙ্ক করে যা Kubernetes দ্বারা প্রয়োজনীয় কার্যকারিতা প্রদান করে। Kubernetes প্রকল্প লেখক এই প্রকল্পগুলির জন্য দায়ী নয়, যা বর্ণানুক্রমিকভাবে
```suggestion
#other = """এই বিভাগটি তৃতীয় পক্ষের (third party) প্রকল্পগুলির সাথে লিঙ্ক করে যা Kubernetes দ্বারা প্রয়োজনীয় কার্যকারিতা প্রদান করে। Kubernetes প্রকল্প লেখক এই প্রকল্পগুলির জন্য দায়ী নয়, যা বর্ণানুক্রমিকভাবে তালিকাভুক্ত করা হয়েছে। এই তালিকায় একটি প্রকল্প যোগ করতে, একটি পরিবর্তন জমা দেওয়ার আগে <a href="/docs/contribute/style/content-guide/#third-party-content">content guide</a> পড়ুন। <a href="#third-party-content-disclaimer">অধিক তথ্য</a>"""
```

2023-03-18 16:08 UTC, mitul3737 commented
@sftim Can you have a look into this ? Let me know if it looks ok 😊

2023-03-18 17:37 UTC, nerdynikhil commented
thanks @mitul3737 for the help.

2023-03-24 08:54 UTC, seokho-son reviewed
Hi @nerdynikhil @mitul3737  :)

You need to remove `#` for the keys and values to enable them. 
Also there are some keys which doesn't have localized value. (line 4 ~ 8)

You can think https://github.com/kubernetes/website/blob/main/data/i18n/en/en.toml is the template and we need to modify the value part only for the data/i18n/bn/bn.toml.

Please check the comments. :)

2023-03-24 08:54 UTC, seokho-son commented on data/i18n/bn/bn.toml
> +#other = "সতর্কতা:"
```suggestion
other = "সতর্কতা:"
```

> [caution]
> other = "Caution:"

`#` should be removed :) 
Please update all sections.

2023-03-24 08:54 UTC, seokho-son commented on data/i18n/bn/bn.toml
>  #other = """<p>This page is automatically generated.</p><p>If you plan to report an issue with this page, mention that the page is auto-generated in your issue description. The fix may need to happen
4~8 lines are not localized.

2023-03-25 14:32 UTC, nerdynikhil commented on data/i18n/bn/bn.toml
>  #other = """<p>This page is automatically generated.</p><p>If you plan to report an issue with this page, mention that the page is auto-generated in your issue description. The fix may need to happen
thanks @seokho-son

2023-03-25 14:57 UTC, mitul3737 approved these changes

2023-03-25 14:58 UTC, mitul3737 commented
/label tide/merge-method-squash

2023-03-25 14:59 UTC, mitul3737 commented
/lgtm

2023-03-25 14:59 UTC, mitul3737 commented
Great work @nerdynikhil 😊

2023-03-25 14:59 UTC, merged