Reference files to sync task 3
kubernetes/website pull request #40157
Opened 2023-03-20 10:58 UTC by asa3311

Reference files to sync task 3

Related to task-3 of issue https://github.com/kubernetes/website/issues/39987.

2023-03-20 11:51 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
> +      *IPBlock describes a particular CIDR (Ex. "192.168.1.0/24","2001:db8::/64") that is allowed to the pods matched by a NetworkPolicySpec's podSelector. The except entry describes CIDRs that shoul
Please change the zh text accordingly

2023-03-20 11:51 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
> +        CIDR is a string representing the IP Block Valid examples are "192.168.1.0/24" or "2001:db8::/64"
Please change the zh text accordingly

2023-03-20 11:51 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
> +        Except is a slice of CIDRs that should not be included within an IP Block Valid examples are "192.168.1.0/24" or "2001:db8::/64" Except values will be rejected if they are outside the CIDR ra
Please change the zh text accordingly

2023-03-20 11:51 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
> +      *IPBlock describes a particular CIDR (Ex. "192.168.1.0/24","2001:db8::/64") that is allowed to the pods matched by a NetworkPolicySpec's podSelector. The except entry describes CIDRs that shoul
Please change the zh text accordingly

2023-03-20 11:51 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
> +        CIDR is a string representing the IP Block Valid examples are "192.168.1.0/24" or "2001:db8::/64"
Please change the zh text accordingly

2023-03-20 11:51 UTC, windsonsea commented on content/zh-cn/docs/reference/kubernetes-api/policy-resources/network-policy-v1.md
> +        Except is a slice of CIDRs that should not be included within an IP Block Valid examples are "192.168.1.0/24" or "2001:db8::/64" Except values will be rejected if they are outside the CIDR ra
Please change the zh text accordingly

2023-03-21 02:47 UTC, tengqm commented
/lgtm
/approve

2023-03-21 02:50 UTC, howieyuen requested changes

2023-03-21 02:50 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> +  如果设置为“Local”，代理将以一种假设外部负载均衡器将负责在节点之间服务流量负载均衡，因此每个节点将仅向服务的节点本地端点传递流量，而不会伪装客户端源 IP。
```suggestion
  如果设置为 “Local”，代理将以一种假设外部负载均衡器将负责在节点之间服务流量负载均衡，
  因此每个节点将仅向服务的节点本地端点传递流量，而不会伪装客户端源 IP。
```

2023-03-21 02:50 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> +  请注意，从集群内部发送到 External IP 或 LoadBalancer IP 的流量始终具有“Cluster”语义，但是从集群内部发送到 NodePort 的客户端需要在选择节点时考虑流量路由策略。
```suggestion
  请注意，从集群内部发送到 External IP 或 LoadBalancer IP 的流量始终具有 “Cluster” 语义，
  但是从集群内部发送到 NodePort 的客户端需要在选择节点时考虑流量路由策略。
```

2023-03-21 02:50 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> +  InternalTrafficPolicy描述节点如何分发它们在ClusterIP上接收到的服务流量。
```suggestion
  internalTrafficPolicy 描述节点如何分发它们在 ClusterIP 上接收到的服务流量。
```

2023-03-21 02:50 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> +  如果设置为"Local"，代理将假定pod只想与在同一节点上的服务端点通信，如果没有本地端点，它将丢弃流量。
```suggestion
  如果设置为 “Local”，代理将假定 Pod 只想与在同一节点上的服务端点通信，如果没有本地端点，它将丢弃流量。
```

2023-03-21 02:50 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> +  "Cluster"默认将流量路由到所有端点（可能会根据拓扑和其他特性进行修改）。
```suggestion
  “Cluster” 默认将流量路由到所有端点（可能会根据拓扑和其他特性进行修改）。
```

2023-03-21 02:50 UTC, howieyuen commented on content/zh-cn/docs/reference/kubernetes-api/service-resources/service-v1.md
> +  externalTrafficPolicy 描述了节点如何分发它们在 Service 的“外部访问”地址（NodePort、ExternalIP 和 LoadBalancer IP）接收到的服务流量。
```suggestion
  externalTrafficPolicy 描述了节点如何分发它们在 Service 的“外部访问”地址
  （NodePort、ExternalIP 和 LoadBalancer IP）接收到的服务流量。
```

2023-03-21 02:51 UTC, merged