[zh-cn]Reference files to sync task 8
kubernetes/website pull request #40172
Opened 2023-03-21 02:12 UTC by asa3311

Reference files to sync task 8

Related to task-1 of issue https://github.com/kubernetes/website/issues/39987.

2023-03-21 02:16 UTC, tengqm commented on content/zh-cn/docs/reference/instrumentation/node-metrics.md
> +则 kubelet [将使用 CRI 来获取 Pod 和容器级别的指标数据] (/docs/reference/instrumentation/cri-pod-container-metrics)，而不是 cAdvisor 来获取 。
```suggestion
则 kubelet [将使用 CRI 来获取 Pod 和容器级别的指标数据](/zh-cn/docs/reference/instrumentation/cri-pod-container-metrics)，
而不是 cAdvisor 来获取 。
```

2023-03-21 02:20 UTC, asa3311 commented
done

2023-03-21 02:51 UTC, tengqm commented
/lgtm
/approve

2023-03-21 02:52 UTC, howieyuen requested changes

2023-03-21 02:52 UTC, howieyuen commented on content/zh-cn/docs/reference/config-api/_index.md
> +weight: 130
update the en text by the way

2023-03-21 02:52 UTC, howieyuen commented on content/zh-cn/docs/reference/instrumentation/node-metrics.md
> +而不是 cAdvisor 来获取 。
```suggestion
而不是 cAdvisor 来获取。
```

2023-03-21 02:56 UTC, asa3311 commented on content/zh-cn/docs/reference/config-api/_index.md
> +weight: 130
there is no en text.

2023-03-21 02:58 UTC, windsonsea commented on content/zh-cn/docs/reference/config-api/_index.md
> +weight: 130
请参见[中文本地化指南](https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#commented-en-text)，需要将英文复制过来，然后注释掉。

方便 review，也是为了保持风格一致。

2023-03-22 01:45 UTC, asa3311 commented on content/zh-cn/docs/reference/config-api/_index.md
> +weight: 130
done

2023-03-22 01:57 UTC, tengqm commented
/lgtm

2023-03-22 01:58 UTC, merged