[zh-cn]sync labels-annotations-taints/index.md
kubernetes/website pull request #40351
Opened 2023-03-28 01:29 UTC by asa3311

sync labels-annotations-taints/index.md

2023-03-28 03:13 UTC, tengqm commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +该注解用于标记 Kubernetes 配置文件中的对象，表示这些对象是本地配置，不应提交到 Kubernetes API。
```suggestion
该注解用于清单中的对象，表示某对象是本地配置，不应提交到 Kubernetes API。
```

2023-03-28 03:13 UTC, tengqm commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +对于这个注解，当值为 "true"时，表示该对象仅被客户端工具使用，不应提交到 API 服务器。
```suggestion
对于这个注解，当值为 "true" 时，表示该对象仅被客户端工具使用，不应提交到 API 服务器。
```

2023-03-28 03:13 UTC, tengqm commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +### internal.config.kubernetes.io/* (reserved prefix) {#internal.config.kubernetes.io-reserved-wildcard}
```suggestion
### internal.config.kubernetes.io/* （保留的前缀） {#internal.config.kubernetes.io-reserved-wildcard}
```

2023-03-28 03:13 UTC, tengqm commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +该前缀被保留，供按照 Kubernetes 资源模型 (KRM) 函数规范的编排工具内部使用。
```suggestion
该前缀被保留，供遵从 Kubernetes 资源模型 (KRM) 函数规范的编排工具内部使用。
```

2023-03-28 03:13 UTC, tengqm commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +此注解记录了加载对象清单文件的（斜杠分隔、与操作系统无关）相对路径。
```suggestion
此注解记录了加载对象清单文件的（斜线分隔、与操作系统无关）相对路径。
```

2023-03-28 03:43 UTC, howieyuen requested changes

2023-03-28 03:43 UTC, howieyuen commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +### config.kubernetes.io/local-config {#config-local-config}
ref: https://kubernetes.io/docs/reference/labels-annotations-taints/#config-kubernetes-io-local-config
```suggestion
### config.kubernetes.io/local-config {#config-kubernetes-io-local-config}
```

2023-03-28 03:43 UTC, howieyuen commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +对于这个注解，当值为 "true"时，表示该对象仅被客户端工具使用，不应提交到 API 服务器。
```suggestion
对于这个注解，当值为 “true” 时，表示该对象仅被客户端工具使用，不应提交到 API 服务器。
```

2023-03-28 03:43 UTC, howieyuen commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +当值为 "false"，可以用来声明该对象应提交到 API 服务器，即使它是本地对象。
```suggestion
当值为 “false” 时，可用于声明该对象应提交到 API 服务器，即使它是本地对象。
```

2023-03-28 03:43 UTC, howieyuen commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +该前缀被保留，供按照 Kubernetes 资源模型 (KRM) 函数规范的编排工具内部使用。
```suggestion
该前缀为 Kubernetes 资源模型（KRM）函数规范所规定的编排工具内部使用所保留。
```

2023-03-28 03:43 UTC, howieyuen commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +### internal.config.kubernetes.io/path {#internal-config-path}
```suggestion
### internal.config.kubernetes.io/path {#internal-config-kubernetes-io-path}
```

2023-03-28 03:43 UTC, howieyuen commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +此注解记录了加载对象清单文件的（斜杠分隔、与操作系统无关）相对路径。
```suggestion
此注解记录了加载对象的清单文件的相对路径（斜杠分隔、与操作系统无关）。
```

2023-03-28 03:43 UTC, howieyuen commented on content/zh-cn/docs/reference/labels-annotations-taints/_index.md
> +### internal.config.kubernetes.io/index {#internal-config-index}
```suggestion
### internal.config.kubernetes.io/index {#internal-config-kubernetes-io-index}
```

2023-03-28 09:24 UTC, howieyuen reviewed
/lgtm

2023-03-28 10:18 UTC, ydFu approved these changes
/lgtm

2023-03-28 14:25 UTC, Zhuzhenghao commented
/lgtm

2023-03-29 01:15 UTC, windsonsea commented
/approve

2023-03-29 01:17 UTC, merged