Add more detail about container images and referencing them by digest #39870
kubernetes/website pull request #40402
Opened 2023-03-29 18:28 UTC by KhushPatibandha

Explained image digest by making a new topic and added links to help understand image digest better.

2023-03-30 10:46 UTC, sftim commented
/retitle Add more detail about container images and referencing them by digest

2023-03-30 10:47 UTC, sftim reviewed
One (important) comment

2023-03-30 10:47 UTC, sftim commented on content/en/docs/concepts/containers/images.md
> +For more information refer [Using container image digests](https://cloud.google.com/kubernetes-engine/docs/archive/using-container-images).
This isn't quite the right thing. I'd omit this line until we have our own page to link to.
```suggestion
```

2023-04-09 13:25 UTC, KhushPatibandha commented
Hey, @sftim hope you doing great. What's the update on this PR?

2023-11-14 12:12 UTC, divya-mohan0209 commented on content/en/docs/concepts/containers/images.md
> +Using digest can provide a more secure and reliable way of referencing
I think this particular reiterates the point made in the second sentence and could be made idiomatic. Please could you rephrase it to ensure that the points being made aren't redundant?

2023-11-14 12:13 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2023-11-24 06:05 UTC, Ritikaa96 requested changes

2023-11-24 06:05 UTC, Ritikaa96 commented on content/en/docs/concepts/containers/images.md
> +the exact version of the image is used every time the pad is created or updated.
```suggestion
the exact version of the image is used every time the pod is created or updated.
```

2023-11-24 06:05 UTC, Ritikaa96 commented on content/en/docs/concepts/containers/images.md
> +However, using an image digest can be more reliable that image tag since it ensures that
```suggestion
However, using an image digest can be more reliable than image tag since it ensures that 
```

2023-11-24 06:05 UTC, Ritikaa96 commented on content/en/docs/concepts/containers/images.md
> +However, using an image digest can be more reliable that image tag since it ensures that
small nits

2023-11-27 06:44 UTC, Ritikaa96 requested changes

2023-11-27 06:44 UTC, Ritikaa96 commented on content/en/docs/concepts/containers/images.md
> +it provides a way to ensure that the image has not been tampered or modified with.
```suggestion
it provides a way to ensure that the image has not been tampered with or modified.
```
'Modified with' doesn't sound right. what it is modified with? did you mean tampered with?

2023-11-27 06:44 UTC, Ritikaa96 commented on content/en/docs/concepts/containers/images.md
> +This is more secure and reliable way of referencing
```suggestion
This is a more secure and reliable way of referencing 
```

2023-11-27 06:45 UTC, Ritikaa96 commented
Few more nits @KhushPatibandha

2024-01-07 22:12 UTC, sftim commented
@KhushPatibandha the feedback in https://github.com/kubernetes/website/pull/40402#issuecomment-1827213360 looks worth fixing - I'd expect a bug report if we left it in. Could your revise again?

Ideally, also squash your commits.

2024-01-23 11:54 UTC, divya-mohan0209 commented
Hello @KhushPatibandha , despite reminders since there have been no commits/comments from your side, we are closing this PR. 

Please note that when you have the bandwidth, you may choose to resume work by issuing the /reopen command on this PR.

/close

2024-01-23 11:55 UTC, closed without merging