[zh-cn] localize blog: 2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
kubernetes/website pull request #40539
Opened 2023-04-06 12:10 UTC by asa3311

localize blog: 2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md

link #40533

2023-04-06 12:27 UTC, windsonsea reviewed
可以先修复几个共性的问题：

1. 删除冗余的空行
2. 参考其他中文页面，长句适当折行

2023-04-06 12:27 UTC, windsonsea commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +
This blank line (line 28) is not necessary.

You can delete this kind of blank lines from start to end.

2023-04-06 12:27 UTC, windsonsea commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +[Go 项目](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance) 每年发布两个新的次要版本，并为最近的两个版本提供安全修复，每个 Go 版本的维护期约为一年。
```suggestion
[Go 项目](https://github.com/golang/go/wiki/Go-Release-Cycle#release-maintenance)每年发布两个新的次要版本，
并为最近的两个版本提供安全修复，每个 Go 版本的维护期约为一年。
```
通常中文在 col 40，英文在 col 80 左右，在标题符号、中英、数字之间折行，方便 review 和阅读。

2023-04-06 14:49 UTC, my-git9 commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +[GopherCon演讲](https://www.youtube.com/watch?v=v24wrd3RwGo) 和 [设计](https://go.dev/design/56986-godebug)，
```suggestion
[GopherCon 演讲](https://www.youtube.com/watch?v=v24wrd3RwGo)和[设计](https://go.dev/design/56986-godebug)，
```

2023-04-06 14:49 UTC, my-git9 commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +这些更改使 Kubernetes 1.23+ 在2023年1月升级到 Go 1.19，并避免了任何面向用户的配置或行为更改。
```suggestion
这些更改使 Kubernetes 1.23+ 在 2023 年 1 月升级到 Go 1.19，并避免了任何面向用户的配置或行为更改。
```

2023-04-06 14:49 UTC, my-git9 commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +2. 新的 Go 版本在新的 Kubernetes 次要版本中至少已经使用了1个月。
```suggestion
2. 新的 Go 版本在新的 Kubernetes 次要版本中至少已经使用了 1 个月。
```

2023-04-06 14:49 UTC, my-git9 commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +1. 新的 Go 版本必须至少已经推出3个月。
```suggestion
1. 新的 Go 版本必须至少已经推出 3 个月。
```

2023-04-06 14:49 UTC, my-git9 commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +   用户不必更新 Go 版本（尽管这更容易在 Go 1.21计划中 [兼容性改进](https://go.dev/design/56986-godebug)鼓励他们使用受支持的 Go 版本构建）。
```suggestion
   用户不必更新 Go 版本（尽管这更容易在 Go 1.21 计划中[兼容性改进](https://go.dev/design/56986-godebug)鼓励他们使用受支持的 Go 版本构建）。
```

2023-04-07 01:06 UTC, tengqm commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +展望未来，Kubernetes 维护者仍致力于使 Kubernetes 补丁发布尽可能安全且不会造成干扰，
```suggestion
展望未来，Kubernetes 维护者仍致力于使 Kubernetes 补丁发布尽可能安全且不会造成破坏，
```

2023-04-07 01:06 UTC, tengqm commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +3. 与先前的 Go 版本相比，不能出现已知会影响 Kubernetes 的问题。
```suggestion
3. 与先前的 Go 版本相比，不能出现新的已知会影响 Kubernetes 的问题。
```

2023-04-07 01:06 UTC, tengqm commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +   用户不必更新 Go 版本（尽管这更容易在 Go 1.21计划中[兼容性改进](https://go.dev/design/56986-godebug)鼓励他们使用受支持的 Go 版本构建）。
```suggestion
   以便在获取库补丁时，用户不必更新 Go 版本（不过还是鼓励他们使用受支持的 Go 版本构建，
   因为 Go 1.21 计划中的[兼容性改进](https://go.dev/design/56986-godebug)会使得这一操作变简单）。
```

2023-04-07 14:59 UTC, Zhuzhenghao requested changes

2023-04-07 14:59 UTC, Zhuzhenghao commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +title: "使用更新后的 Go 版本保持 Kubernetes 安全"
“使用更新后的 Go 版本保持 Kubernetes 安全”

2023-04-07 14:59 UTC, Zhuzhenghao commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +但在这一 Kubernetes 次要版本被停止支持之前， 对应的 Go 版本就已经不被支持，
但在这一 Kubernetes 次要版本被停止支持之前，对应的 Go 版本就已经不被支持，

2023-04-07 14:59 UTC, Zhuzhenghao commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +并且由于Kubernetes 从 v1.19 开始延长了补丁支持期，这个差距被进一步扩大。
并且由于 Kubernetes 从 v1.19 开始延长了补丁支持期，这个差距被进一步扩大。

2023-04-07 14:59 UTC, Zhuzhenghao commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +使所有 Go 用户受益，而不仅仅是 Kubernetes。
Add a blank line at the end of the file.

2023-04-07 15:02 UTC, Zhuzhenghao requested changes

2023-04-07 15:02 UTC, Zhuzhenghao commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +title: "使用更新后的 Go 版本保持 Kubernetes 安全"
“使用更新后的 Go 版本保持 Kubernetes 安全”

2023-04-07 15:02 UTC, Zhuzhenghao commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +并且由于Kubernetes 从 v1.19 开始延长了补丁支持期，这个差距被进一步扩大。
并且由于 Kubernetes 从 v1.19 开始延长了补丁支持期，这个差距被进一步扩大。

2023-04-07 15:02 UTC, Zhuzhenghao commented on content/zh-cn/blog/_posts/2023-04-06-keeping-kubernetes-secure-with-updated-go-versions.md
> +但在这一 Kubernetes 次要版本被停止支持之前， 对应的 Go 版本就已经不被支持，
但在这一 Kubernetes 次要版本被停止支持之前，对应的 Go 版本就已经不被支持，

2023-04-10 08:46 UTC, tengqm commented
/lgtm
/approve

2023-04-10 08:47 UTC, merged