Adding additional security measures to images Documentation at : /doc…
kubernetes/website pull request #40566
Opened 2023-04-08 21:55 UTC by Biswajit-Mohapatra2

fixed:  #40530

Adding additional image security points to kubernetes documentation.

It helps to more knowing about image security.

changes at:  https://kubernetes.io/docs/concepts/security/security-checklist/#images
                    https://kubernetes.io/docs/concepts/containers/images/

2023-04-08 22:03 UTC, Biswajit-Mohapatra2 commented
/language en

2023-04-08 22:04 UTC, Biswajit-Mohapatra2 commented
/sig security

2023-04-08 23:41 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +Image security refers to the measures taken to ensure that the images used to create and deploy containerized applications are free from vulnerabilities, malware, or other security threats.
please wrap long lines like this, as we do for other paragraphs ...

2023-04-09 06:13 UTC, NitishKumar06 commented on content/en/docs/concepts/security/security-checklist.md
> +Image security refers to the measures taken to ensure that the images used to create and deploy containerized applications are free from vulnerabilities, malware, or other security threats.
```suggestion
Image security refers to the measures taken to ensure that the images used to run and deploy containerized applications are free from vulnerabilities, malware, or other security threats.
```

2023-04-09 06:19 UTC, NitishKumar06 requested changes
Suggestions marked

2023-04-09 06:19 UTC, NitishKumar06 commented on content/en/docs/concepts/security/security-checklist.md
> +- Restricting the use of container images to trusted sources and avoiding the use of untrusted images or repositories.
Couple of more can be added like: 
The smaller the image size, better it is._
_Secure container registeries_

2023-10-14 01:36 UTC, aj11anuj requested changes
I think there isn't any need of these points here, as they come under "best practices while working with images" and they doesn't directly affect security of an image.

2023-10-14 01:36 UTC, aj11anuj commented on content/en/docs/concepts/security/security-checklist.md
> +Overall, while reducing the size of an image may not directly improve image security, it can indirectly help improve security by reducing the risk of attacks or breaches during image transfer, proces
```suggestion
```

2023-10-14 11:32 UTC, aj11anuj approved these changes
LGTM, 👍

As netlify checks have failed, use `git push --force-with-lease origin branch_name` to trigger netlify checks to start again.

2023-10-14 11:52 UTC, tengqm reviewed
Please manually wrap the long lines as we do for other paragraphs.

2023-10-14 11:52 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +Image security refers to the measures taken to ensure that the images used to run and deploy containerized applications are free from vulnerabilities, malware, or other security threats.
```suggestion
Image security refers to the measures taken to ensure that the images used to deploy
and run containerized applications are free from vulnerabilities, malware,
or other security threats.
```

2023-10-14 11:52 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +Secure container registries are a type of cloud-based service that provides a secure and centralized location for storing and managing container images. Container are pre-packaged software components
```suggestion
Secure container registries are a type of cloud-based service that provides a secure
and centralized location for storing and managing container images.
Container are pre-packaged software components that can be used to quickly and
easily deploy applications in a containerized environment.
```

2023-10-14 11:52 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +- Improved security: Secure container registries provide a secure and centralized location for storing and managing container images, which can help improve security by reducing the risk of unauthori
```suggestion
- Improved security: Secure container registries provide a secure and centralized location
  for storing and managing container images, which can help improve security
  by reducing the risk of unauthorized access or tampering.
```

2023-10-14 11:52 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +- Simplified management: By providing a centralized location for storing and managing container images, secure container registries can help simplify management and reduce the risk of errors or incon
```suggestion
- Simplified management: By providing a centralized location for storing and managing container images,
  secure container registries can help simplify management and reduce the risk of
  errors or inconsistencies.
```

2023-10-14 11:52 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +- Faster deployment: By providing pre-packaged container images, secure container registries can help speed up the deployment process and reduce the time and effort required to deploy applications.
```suggestion
- Faster deployment: By providing pre-packaged container images, secure container registries
  can help speed up the deployment process and reduce the time and effort required
  to deploy applications.
```

2023-10-14 11:52 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +- Improved collaboration: Secure container registries can help improve collaboration by providing a centralized location for sharing and accessing container images, which can help reduce the risk of
```suggestion
- Improved collaboration: Secure container registries can help improve collaboration
  by providing a centralized location for sharing and accessing container images,
  which can help reduce the risk of miscommunication or errors.
```

2023-10-14 11:52 UTC, tengqm commented on content/en/docs/concepts/security/security-checklist.md
> +By implementing these measures and maintaining a robust security posture, organizations can help to minimize the risk of security incidents and data breaches that may result from using insecure image
```suggestion
By implementing these measures and maintaining a robust security posture,
organizations can help to minimize the risk of security incidents and data breaches
that may result from using insecure images.
```

2023-11-14 04:10 UTC, divya-mohan0209 commented
@Biswajit-Mohapatra2 : Please can you action on suggestions by @tengqm?

2024-01-07 22:16 UTC, sftim commented on content/en/docs/concepts/security/security-checklist.md
> +- Ensuring that all dependencies used by container images are also secure and up-to-date.
```suggestion
- Ensuring that all build dependencies of container images are also secure and up-to-date.
  If an image you're using depends on a vulnerable build-time dependency, you should look for
  an update image that has a fix.
```

2024-01-07 22:16 UTC, sftim commented on content/en/docs/concepts/security/security-checklist.md
> +Secure container registries are a type of cloud-based service that provides a secure
A container registry need not be a cloud service (you could have one on your own premises).

2024-01-07 22:16 UTC, sftim commented on content/en/docs/concepts/security/security-checklist.md
> +easily deploy applications in a containerized environment.
```suggestion
Container images are ready-to-run packages of software that can be used to quickly and
easily deploy applications. Each replica of a container based on some image runs the exact
same software as other containers using the same image.
```

2024-01-07 22:16 UTC, sftim commented on content/en/docs/concepts/security/security-checklist.md
> +that may result from using insecure images.
What is a “secure container registry”? By comparison, what would an “_insecure_ container registry” be like?

2024-02-25 17:40 UTC, sftim commented
/label tide/merge-method-squash

2024-02-25 17:42 UTC, sftim requested changes
This proposes a change to a checklist document, but the added content doesn't include any checkable items.

@Biswajit-Mohapatra2 you should find a better home for this advice. Perhaps a blog article (on https://blog.k8s.io/)?

2024-04-01 02:45 UTC, divya-mohan0209 commented
@Biswajit-Mohapatra2 : Hi there! As @sftim commented above, I concur that the added information doesn't provide any "checkable" items to the existing checklist. If you would like to contribute a blog with the same information, we'd happily review that. 
/close

2024-04-01 02:45 UTC, closed without merging