explained back-off delay
kubernetes/website pull request #40713
Opened 2023-04-16 10:51 UTC by KhushPatibandha

worked on #18903 
explained back-off delay with primary behaviors and reasons to use back-off delay.

2023-06-02 13:02 UTC, sftim reviewed
Thanks

We should frame this more as explaining what the kubelet does (ie: less emphasis on why you might want Kubernetes to have the back off before retrying).

2023-06-02 13:02 UTC, sftim commented on content/en/docs/concepts/workloads/pods/pod-lifecycle.md
> +The reasons to use back-off delay are:
Not sure this makes sense. The back off delay is imposed on you; there's no choice to a user of the Pod API about whether to use it.

2023-06-06 07:31 UTC, Ritikaa96 requested changes
Few more nits

2023-06-06 07:31 UTC, Ritikaa96 requested changes
Few more nits

2023-06-06 17:33 UTC, KhushPatibandha commented
> Thanks
> 
> We should frame this more as explaining what the kubelet does (ie: less emphasis on why you might want Kubernetes to have the back off before retrying).

hey @sftim, should I put more emphasis on explaining how the kubelet handles "back off delay" or how kubelet assists us in "CrashLoopBackoff" in general?

2023-07-01 19:02 UTC, narharim commented
Hey @sftim, I was looking for a detailed explanation for the back-delay off; if this PR gets merged, it will be helpful to me as well the community.
Also, I suggest adding a `CrashLoopBackOff` as Pod Phase. 
We have 5 phases currently in documentation `Pending`, `Running`, `Succeeded`,`Failed` and `Unknown.`
we can add `CrashLoopBackOff` after the `Failed` in documentation.

2023-07-01 23:13 UTC, tengqm commented
> Hey @sftim, I was looking for a detailed explanation for the back-delay off; if this PR
> gets merged, it will be helpful to me as well the community.

Please avoid aiming at "get something merged". If you really want to "contribute",
think how to "get something improved/fixed".

> Also, I suggest adding a note of CrashLoopBackOff as Pod Phase.

Before doing that, you have to understand the definition of "Phase".
Are you sure that `CrashLoopBackOff` is defined as a Pod phase?

2023-07-02 09:15 UTC, narharim commented
> Please avoid aiming at "get something merged". If you really want to "contribute", think how to "get something improved/fixed".
> 
I apologize if my previous comment sounded like I was solely focused on getting something merged. I understand that is not about getting something merged but about positive impact on the community. Thank you for your valuable feedback
> 
> Before doing that, you have to understand the definition of "Phase". Are you sure that `CrashLoopBackOff` is defined as a  Pod phase?

Thank you for highlight this as well.You are correct. I should have double-checked the difference between "Pod status" and "Pod phase" before making the suggestion.

2023-09-19 07:14 UTC, Ritikaa96 commented
Hi @KhushPatibandha are you willing to address the reviews suggested ? are you still working on this PR?

2023-10-02 05:28 UTC, tengqm commented
@KhushPatibandha Still working on this one? If you don't have cycles to push this forward, is it okay for someone else to take over this and get the problem fixed?

2023-11-24 06:12 UTC, Ritikaa96 commented
Hi @KhushPatibandha , Please address the changes if you are still working or you can hand this issue to someone else who has bandwidth to fix this.

2023-12-20 13:20 UTC, kbhawkey commented
👋 @KhushPatibandha .
I am closing this pull request as it has been open for some time without activity.
You can reopen your pull request and continue to work on the changes.
/close

2023-12-20 13:20 UTC, closed without merging