[bn] Localized `content/bn/docs/setup/production-environment/_index.md`
kubernetes/website pull request #40718
Opened 2023-04-16 20:07 UTC by Acesif

Signed-off-by: Asif Zubayer Palak asifpalak@gmail.com
Localizes `content/bn/docs/setup/production-environment/_index.md`  to Bengali
This is an initial PR as may need some improvements!
Tracking issue: #31677

2023-06-09 09:18 UTC, mitul3737 requested changes

2023-06-09 18:55 UTC, Acesif commented on content/bn/docs/setup/production-environment/_index.md
> +সাধারণত, একটি প্রোডাকশন কুবারনেটিস ক্লাস্টার পরিবেশে ব্যক্তিগত শিক্ষা, উন্নয়ন, বা পরীক্ষার পরিবেশ কুবারনেটিস এর চেয়ে বেশি প্রয়োজনীয়তা থাকে।
The original text contained "Typically, a production Kubernetes cluster environment has more requirements than a personal learning, development, or test environment Kubernetes".
I tried to restructure it to make it more sensible while maintaining its literary meaning

2023-06-29 04:10 UTC, mitul3737 approved these changes

2023-06-29 04:11 UTC, mitul3737 commented
tide/merge-method-squash

2023-06-29 04:12 UTC, mitul3737 commented
/label tide/merge-method-squash

2023-06-29 04:12 UTC, mitul3737 commented
/lgtm

2023-06-29 04:12 UTC, merged

2023-06-29 04:20 UTC, mitul3737 commented
/label tide/merge-method-squash

2023-06-29 04:20 UTC, mitul3737 commented
/approve

2023-06-29 04:20 UTC, mitul3737 commented
/lgtm