[ko] Update outdated files in dev-1.26.-ko.1 [M149-155]
kubernetes/website pull request #40938
Opened 2023-05-02 22:38 UTC by Virusuki

Related Issue: #[38458](https://github.com/kubernetes/website/issues/38458#issuecomment-1512426915)

Updated outdated files in content/en/docs/tasks/.

> ### 7 files to be modified
- [ ] M149. content/en/docs/tasks/administer-cluster/cluster-upgrade.md | 9(+XS) 0(-)
- [ ] M150. content/en/docs/tasks/administer-cluster/dns-custom-nameservers.md | 59(+M) 112(-)
- [ ] M151. content/en/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade.md | 4(+XS) 4(-)
- [ ] M152. content/en/docs/tasks/administer-cluster/manage-resources/memory-default-namespace.md | 8(+XS) 0(-)
- [ ] M153. content/en/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md | 26(+S) 30(-)
- [ ] M154. content/en/docs/tasks/administer-cluster/use-cascading-deletion.md | 1(+XS) 141(-)
- [ ] M155. content/en/docs/tasks/configmap-secret/managing-secret-using-config-file.md | 55(+M) 1(-)

2023-05-03 08:20 UTC, ysyukr commented
/assign

2023-05-08 10:43 UTC, jongwooo requested changes
안녕하세요! 몇 가지 코멘트를 추가해보았습니다. 살펴보시고, 적절히 적용해주시면 감사하겠습니다.

2023-05-13 12:39 UTC, Virusuki commented on content/ko/docs/tasks/administer-cluster/dns-custom-nameservers.md
> +CoreDNS는 스텁 도메인 및 네임서버(예: ns.foo.com)에 대한 FQDN를 지원하지 않는다.
리뷰 감사합니다. ㅎㅎ

2023-05-13 12:43 UTC, Virusuki commented on content/ko/docs/tasks/administer-cluster/network-policy-provider/cilium-network-policy.md
> +이후 다음과 같은 명령을 사용하여 다운받은 파일을 `/usr/local/bin` 디렉토리에 압축푼다.
리뷰 감사합니다. ㅎㅎ

2023-05-13 12:45 UTC, Virusuki commented on content/ko/docs/tasks/configmap-secret/managing-secret-using-config-file.md
> +및 `stringData` 필드를 수정하고 해당 파일을 클러스터에 적용합니다.
리뷰 감사합니다. ㅎㅎ

2023-05-13 12:52 UTC, Virusuki commented
@jongwooo 목적격 조사와 놓친 평어체 부분 수정했습니다. 
리뷰 감사합니다~ㅎㅎ

2023-05-22 01:10 UTC, ysyukr commented
@Virusuki, @jongwooo 확인이 늦었습니다.
/lgtm
/approve

2023-05-22 01:12 UTC, merged

2023-05-22 01:40 UTC, Virusuki commented
네 확인감사합니다. 👍