[es] Add content/es/docs/concepts/storage/storage-classes.md
kubernetes/website pull request #41118
Opened 2023-05-13 20:08 UTC by edithturn

Se añadió la documentación en español para 
content/es/docs/concepts/storage/storage-classes.md
Agradecería puedan revisarlo y darme feedback.
Gracias! :)

2023-05-17 22:44 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +Este documento describe el concepto de StorageClass en Kubernetes. Necesita estar familiarizado con
Se podría mencionar el término en Inglés porque es más común solo para referencia entre paréntesis la primera vez.

```suggestion
Este documento describe el concepto de Clases de Almacenamiento (StorageClass) en Kubernetes. Necesita estar familiarizado con
```

2023-05-17 22:44 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +[volumes](/docs/concepts/storage/volumes/) y
```suggestion
[volúmenes](/docs/concepts/storage/volumes/) y
```

2023-05-17 22:44 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +[persistent volumes](/docs/concepts/storage/persistent-volumes).
```suggestion
[volúmenes persistentes](/docs/concepts/storage/persistent-volumes).
```

2023-05-17 22:45 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +StorageClass proporciona una forma para que los administradores describan las "clases" de
```suggestion
Una Clase de Almacenamiento proporciona una forma para que los administradores describan las "clases" de
```

2023-05-17 22:48 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +title: Clases de Almacenamiento
Como en el resto del documento se ocupa _StorageClass_, podríamos poner la referencia igual en el título

```suggestion
title: StorageClass (Clases de Almacenamiento)
```

2023-05-17 22:50 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +solicite cualquier clase en particular a la que vincularse: vea el
```suggestion
solicite cualquier clase en particular a la que vincularse: vea la
```

2023-05-17 22:52 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +que son programas independientes que siguen un [especificación](https://git.k8s.io/design-proposals-archive/storage/volume-provisioning.md)
```suggestion
que son programas independientes que siguen una [especificación](https://git.k8s.io/design-proposals-archive/storage/volume-provisioning.md)
```

2023-05-17 22:52 UTC, ramrodo commented on content/es/docs/concepts/storage/storage-classes.md
> +definido por Kubernetes. Los autores de proveedores externos tienen total discreción
```suggestion
definida por Kubernetes. Los autores de proveedores externos tienen total discreción
```

2023-05-21 01:57 UTC, edithturn commented on content/es/docs/concepts/storage/storage-classes.md
> +title: Clases de Almacenamiento
Entiendo, tiene sentido :)
Gracias

2023-05-21 02:09 UTC, edithturn commented
@ramrodo I sent some updates to the documentation, thanks for your feedback! :)

2023-05-22 16:59 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +ejecutada, qué complemento de volumen usa (incluido Flex), etc. El repositorio
Me [parece](https://www.diccionariodedudas.com/donde-o-donde/) que no llevan acento
```suggestion
sobre donde vive su código, como se envía el aprovisionador, como debe ser
ejecutada, que complemento de volumen usa (incluido Flex), etc. El repositorio
```

2023-05-22 17:17 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +supported plugins.
Por traducir?

2023-05-22 17:33 UTC, electrocucaracha requested changes

2023-05-22 17:33 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +- `zone` (Obsoleto): AWS sona. Si no se especifica `zone` ni `zones`, los volúmenes generalmente se distribuyen por turnos en todas las zonas activas donde el clúster de Kubernetes tiene un nodo. Los
```suggestion
- `zone` (Obsoleto): AWS zona. Si no se especifica `zone` ni `zones`, los volúmenes generalmente se distribuyen por turnos en todas las zonas activas donde el clúster de Kubernetes tiene un nodo. Los parámetros `zone` y `zones` no deben usarse al mismo tiempo.
```

2023-05-22 17:33 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +Los proveedores In-tree son [deprecated](/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/#why-are-we-migrating-in-tree-plugins-to-csi). Para obtener más información sobre el aprovisionado
```suggestion
Los proveedores In-tree estan [obsoletos](/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/#why-are-we-migrating-in-tree-plugins-to-csi). Para obtener más información sobre el aprovisionador de CSI, consulte [Kubernetes vSphere CSI Driver](https://vsphere-csi-driver.sigs.k8s.io/) y [vSphereVolume CSI migration](/docs/concepts/storage/volumes/#vsphere-csi-migration).
```

2023-05-22 17:33 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +3. Gestión de políticas de almacenamiento dentro de kubernetes
nit
```suggestion
3. Gestión de políticas de almacenamiento dentro de Kubernetes
```

2023-05-22 17:33 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +     Puedes ver[Administración basada en políticas de almacenamiento para el aprovisionamiento dinámico de volúmenes](https://github.com/vmware-archive/vsphere-storage-for-kubernetes/blob/fa4c8b8ad46
```suggestion
     Puedes ver la [Administración basada en políticas de almacenamiento para el aprovisionamiento dinámico de volúmenes](https://github.com/vmware-archive/vsphere-storage-for-kubernetes/blob/fa4c8b8ad46a85b6555d715dd9d27ff69839df53/documentation/policy-based-mgmt.md)
```

2023-05-22 17:33 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +- `fsType`: fsType que es compatible con kubernetes. Por defecto: `"ext4"`.
```suggestion
- `fsType`: fsType que es compatible con Kubernetes. Por defecto: `"ext4"`.
```

2023-05-22 17:33 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +  Defaults to false which means a read/write mount. This setting will impact theuna bandera que indica si el almacenamiento se montará como de solo lectura. El valor predeterminado es falso, lo que s
Por traducir

2023-05-27 02:00 UTC, edithturn commented on content/es/docs/concepts/storage/storage-classes.md
> +ejecutada, qué complemento de volumen usa (incluido Flex), etc. El repositorio
Estuve con dudas, y encontré algo más claro aqui:
`Se escribe donde, sin tilde, cuando podemos equiparar la función que tiene la oración que encabeza con un complemento de lugar («Yoli trabaja cerca de donde vive Paco»); pero se escribe con tilde en las oraciones interrogativas en las que se pregunta por el lugar («¿Dónde trabaja Yoli?» o «No estoy segura de dónde trabaja Yoli») y en las exclamativas («¡Dónde hemos ido a parar!»).`

https://www.fundeu.es/recomendacion/dondedonde/#:~:text=Se%20escribe%20donde%2C%20sin%20tilde,No%20estoy%20segura%20de%20d%C3%B3nde
@electrocucaracha

2023-05-27 03:23 UTC, edithturn commented on content/es/docs/concepts/storage/storage-classes.md
> +supported plugins.
Ups, lo olvidé :)
Ya lo envié, @electrocucaracha 
Thank youu!

2023-05-27 03:38 UTC, edithturn commented on content/es/docs/concepts/storage/storage-classes.md
> +  Defaults to false which means a read/write mount. This setting will impact theuna bandera que indica si el almacenamiento se montará como de solo lectura. El valor predeterminado es falso, lo que s
Thank you, @electrocucaracha :)

2023-05-29 04:26 UTC, electrocucaracha commented on content/es/docs/concepts/storage/storage-classes.md
> +ejecutada, qué complemento de volumen usa (incluido Flex), etc. El repositorio
En ocaciones es algo confuso. Me parece que tienes razon, quiza en este caso sea necesario ser mas enfaticos.

2023-06-20 17:51 UTC, ramrodo approved these changes
/lgtm

2023-06-20 17:52 UTC, merged

2023-06-20 18:01 UTC, ramrodo commented
closes https://github.com/kubernetes/website/issues/40964

2023-06-20 18:38 UTC, ramrodo commented
closes https://github.com/kubernetes/website/issues/41016