[de] Translate instructions for kubectl on Windows
kubernetes/website pull request #41239
Opened 2023-05-20 14:10 UTC by termdew

This Pull Request adds a new translation for the installation instructions for kubectl on Windows.
Furthermore the general kubectl installation article is removed as it's outdated and contains a few errors.

2023-05-22 09:41 UTC, bene2k1 requested changes

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +   # Falls Sie cmd.exe verwenden, führen Sie folgendes aus: cd %USERPROFILE%
```suggestion
   # Falls du `cmd.exe` verwendest, führe folgendes aus: cd %USERPROFILE%
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +1. Konfigurieren Sie `kubectl`, um ein externes Kubernetes Cluster zu verwenden:
```suggestion
1. Konfiguriere `kubectl`, um einen externen Kubernetes Cluster zu verwenden:
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +Somit können Sie sich viel Schreibarbeit sparen.
```suggestion
Somit kannst du dir viel Schreibarbeit sparen.
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +Im Folgenden finden Sie eine Anleitung, um die Auto-Vervollständigung für PowerShell einzurichten.
```suggestion
Im Folgenden findest du eine Anleitung, um die Auto-Vervollständigung für PowerShell einzurichten.
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +1. Laden Sie die aktuellste Version mit folgendem Kommando herunter:
```suggestion
1. Lade die aktuellste Version mit folgendem Kommando herunter:
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +1. Überprüfen Sie die Binärdatei (optional):
```suggestion
1. Überprüfe die Binärdatei (optional):
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +   Laden Sie die Prüfsumme von `kubectl-convert` herunter:
```suggestion
   Lade die Prüfsumme von `kubectl-convert` herunter:
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +   Validieren Sie die `kubectl-convert`-Binärdatei mit der heruntergeladenen Prüfsumme:
```suggestion
   Validiere die `kubectl-convert`-Binärdatei mit der heruntergeladenen Prüfsumme:
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +   - Vergleichen Sie das Ergebnis von `CertUtil` manuell mit der heruntergeladenen Prüfsumme:
```suggestion
   - Vergleiche das Ergebnis von `CertUtil` manuell mit der heruntergeladenen Prüfsumme:
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +   - Verwenden Sie den `-eq`-Operator von PowerShell, um den Hash der Binärdatei mit der Prüfsumme zu vergleichen:
```suggestion
   - Verwende den `-eq`-Operator von PowerShell, um den Hash der Binärdatei mit der Prüfsumme zu vergleichen:
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +1. Fügen Sie den Ordner mit der `kubectl-convert` Binärdatei zu Ihrer `PATH`-Umgebungsvariable hinzu.
```suggestion
1. Füge den Ordner mit der `kubectl-convert` Binärdatei zu deiner `PATH`-Umgebungsvariable hinzu.
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +1. Stellen Sie sicher, dass das Plugin korrekt installiert wurde:
```suggestion
1. Stelle sicher, dass das Plugin korrekt installiert wurde:
```

2023-05-22 09:41 UTC, bene2k1 commented on content/de/docs/tasks/tools/install-kubectl-windows.md
> +1. Entfernen Sie die Installationsdateien nach der Installation des Plugins:
```suggestion
1. Entferne die Installationsdateien nach der Installation des Plugins:
```

2023-08-11 18:54 UTC, termdew commented
I'll open the PR again, I somehow messed it up on my end. Sorry for that.

2023-08-11 18:54 UTC, closed without merging