Reformat paragraphs in the namespaces task page
kubernetes/website pull request #41256
Opened 2023-05-22 02:21 UTC by tengqm

This page can use more tweaks in addition to the ones proposed in this PR. This PR focuses on line wrappings, empty lines, inappropriate lists, and inappropriate indentations.

2023-05-22 06:03 UTC, Shubham82 requested changes

2023-05-22 12:18 UTC, sftim reviewed
Thanks

/lgtm

2023-05-22 12:18 UTC, sftim commented on content/en/docs/tasks/administer-cluster/namespaces.md
> +(henceforth a 'user community').
```suggestion
(henceforth in this document a _user community_).
```

2023-05-22 12:18 UTC, sftim commented on content/en/docs/tasks/administer-cluster/namespaces.md
>  1. A scope for [Names](/docs/concepts/overview/working-with-objects/names/).
```suggestion
1. A scope for [names](/docs/concepts/overview/working-with-objects/names/).
```

2023-05-23 03:54 UTC, Shubham82 commented
/lgtm

2023-05-23 13:55 UTC, shannonxtreme commented
Is the `console` highlighter for output code blocks new? We don't seem to have a section in our style guide to advise new contributors about formatting code blocks...maybe worth an issue to track adding that. Otherwise, changes are good!

/lgtm

2023-05-23 15:32 UTC, sftim reviewed
/approve

2023-05-23 15:34 UTC, merged