NodeOutOfServiceVolumeDetach feature update to GA
kubernetes/website pull request #41302
Opened 2023-05-24 10:43 UTC by carlory

Upstream: https://github.com/kubernetes/kubernetes/pull/118228
KEP: https://github.com/kubernetes/enhancements/pull/3320

2023-05-24 10:49 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +| `NodeOutOfServiceVolumeDetach` | `true` | Beta | 1.26 | |
```suggestion
| `NodeOutOfServiceVolumeDetach` | `true` | Beta | 1.26 | 1.27 |
```

2023-05-24 10:54 UTC, Shubham82 requested changes

2023-05-24 10:54 UTC, Shubham82 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +| `NodeOutOfServiceVolumeDetach` | `true` | Beta | 1.26 | |
please mention `1.27` for Beta  stage under `until` section
```suggestion
| `NodeOutOfServiceVolumeDetach` | `true` | Beta | 1.26 | 1.27 |
```

2023-05-24 10:58 UTC, Shubham82 commented
thanks, @carlory
/lgtm

2023-05-24 10:59 UTC, Shubham82 commented
It can be merged after the [PR:#118228](https://github.com/kubernetes/kubernetes/pull/118228) 
/hold

Please remove the hold label once the above PR will merge.

2023-05-25 05:46 UTC, YuikoTakada commented
Thank you for your PR.
https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md seems need to be updated also.

2023-05-25 06:22 UTC, carlory commented
This doc should only contains removed feature-gates. But the `NodeOutOfServiceVolumeDetach `still exists  in 1.28.

2023-05-28 23:52 UTC, YuikoTakada commented
> This doc should only contain removed feature-gates. But the `NodeOutOfServiceVolumeDetach `still exists in 1.28.

Thank you for your reply. It was my misunderstanding, sorry. You don't need to update https://github.com/kubernetes/website/blob/main/content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md . Thanks.

2023-05-29 01:17 UTC, tengqm commented
/hold till the upstream code is merged.

2023-05-30 03:11 UTC, YuikoTakada commented
> Upstream: [kubernetes/kubernetes#118228](https://github.com/kubernetes/kubernetes/pull/118228) 
> KEP: [kubernetes/enhancements#3320](https://github.com/kubernetes/enhancements/pull/3320)

nit: correct KEP is https://github.com/kubernetes/enhancements/pull/4029/ ?

2023-05-30 06:05 UTC, carlory commented
Thanks! It's updated.

2023-07-10 16:46 UTC, xing-yang commented
/assign

2023-07-16 13:15 UTC, carlory commented
/hold cancel

2023-07-17 19:46 UTC, xing-yang commented
/lgtm

2023-07-18 02:04 UTC, carlory commented
/assign @onlydole

2023-07-24 01:54 UTC, sftim commented
/sig node

2023-07-24 01:55 UTC, sftim reviewed
/lgtm
for docs

2023-07-24 01:55 UTC, sftim commented on content/en/docs/concepts/architecture/nodes.md
>  ## Non Graceful node shutdown {#non-graceful-node-shutdown}
(nit)
```suggestion
## Non-graceful node shutdown handling {#non-graceful-node-shutdown}
```

2023-07-24 05:53 UTC, carlory commented
@sftim @xing-yang please review again

2023-07-25 03:10 UTC, xing-yang commented
/lgtm

2023-07-25 07:36 UTC, carlory commented
/assign @onlydole

2023-08-02 12:10 UTC, kbhawkey commented
/approve

2023-08-02 12:10 UTC, merged