[pt-br] Update cluster-intro tutorial
kubernetes/website pull request #41550
Opened 2023-06-08 14:51 UTC by stormqueen1990

### Umbrella issue: #41496

### Changes
* Update the cluster-intro tutorial to reflect the latest English version and remove Katacoda references.
* Update the create-cluster/_index.md page to reflect the latest English version.

2023-06-10 13:06 UTC, MrErlison commented
Hi @stormqueen1990!

Thanks again for you great job!

/lgmt

2023-06-10 13:16 UTC, MrErlison commented
/lgtm

2023-06-10 14:21 UTC, MrErlison commented
/cc @jcjesus 

Could you please provide a second review?

2023-06-10 19:17 UTC, jcjesus commented
> /cc @jcjesus
> 
> Could you please provide a second review?

Sure!

2023-06-12 13:12 UTC, jcjesus requested changes
Hi @MrErlison, good job, there is just only typo to fix.
Thanks

2023-06-12 14:47 UTC, stormqueen1990 commented on content/pt-br/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html
> +                    Os nós se comunicam com o camada de gerenciamento usando a
Hi there, @jcjesus! This PR was actually opened by me 😅
Just fixed this!

2023-06-12 14:47 UTC, stormqueen1990 commented
/cc @MrErlison @jcjesus

2023-06-13 13:53 UTC, merged