promote memory qos to beta
kubernetes/website pull request #41655
Opened 2023-06-16 03:17 UTC by pacoxu

- [ ] merge after https://github.com/kubernetes/kubernetes/pull/118699

- [KEP]: https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2570-memory-qos

2023-06-16 03:54 UTC, Shubham82 requested changes

2023-06-16 03:54 UTC, Shubham82 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  | `MemoryQoS` | `false` | Alpha | 1.22 | |
@pacoxu, mention the release up to which `MemoryQoS` was in alpha.

 ```suggestion
| `MemoryQoS` | `false` | Alpha | 1.22 | 1.27 |
```

2023-06-16 03:57 UTC, Shubham82 commented
put on hold until [k8s/k8s #118699](https://github.com/kubernetes/kubernetes/pull/118699) will merge.

/hold

Please remove the hold label once the above PR will merge.

2023-06-16 05:41 UTC, Shubham82 commented
Thanks, @pacoxu 
/lgtm

2023-06-16 13:32 UTC, windsonsea commented
Thanks.
/lgtm

2023-06-17 06:48 UTC, tengqm commented
/approve

2023-07-24 01:56 UTC, sftim commented
Is this change still needed for v1.28?

2023-07-24 01:57 UTC, sftim commented
Because https://github.com/kubernetes/kubernetes/pull/118699 is marked as postponed:
/approve cancel

Feel free to re-approve if context shows that's the right thing to do.

2023-07-24 01:58 UTC, pacoxu commented
> Is this change still needed for v1.28?

No, we decided to postpone the promotion due to a throttling problem that will make application stuck and no successful response later( which is worse than immediately oom kill).

2023-07-24 01:58 UTC, pacoxu commented
/close
I will open another one if we want to promote it later.

2023-07-24 01:58 UTC, closed without merging