[ko] Update outdated files in dev-1.27-ko.1 (M44-M50)
kubernetes/website pull request #41825
Opened 2023-07-01 12:48 UTC by YanyChoi

- Related Issue : https://github.com/kubernetes/website/issues/41631

### Files Checked & Modified

- [x] M44. content/en/docs/concepts/scheduling-eviction/assign-pod-node.md | 88(+M) 54(-)
- [x] M45. content/en/docs/concepts/scheduling-eviction/node-pressure-eviction.md | 70(+M) 70(-)
- [x] M46. content/en/docs/concepts/scheduling-eviction/pod-priority-preemption.md | 4(+XS) 3(-)
- [x] M47. content/en/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md | 28(+S) 17(-)
- [x] M48. content/en/docs/concepts/scheduling-eviction/resource-bin-packing.md | 17(+S) 18(-)
- [x] M49. content/en/docs/concepts/scheduling-eviction/taint-and-toleration.md | 5(+XS) 0(-)
- [x] M50. content/en/docs/concepts/scheduling-eviction/topology-spread-constraints.md | 22(+S) 10(-)

### Comments

M47 : 영문판의 경우 mermaid 다이어그램을 mermaid 자체 페이지의 유료판 기능을 사용해서 공유했는데, 다이어그램 자체 내용에 차이는 없고 커뮤니티 내에서의 합의사항도 찾을 수 없어 우선 현 상태로 유지하였습니다.

2023-07-21 01:12 UTC, jongwooo commented
/assign

2023-07-22 04:54 UTC, jongwooo requested changes
@YanyChoi 사소한 사항들 확인해봤습니다. 아래 리뷰 의견 참고하여 업데이트 부탁드립니다.
그리고, [f0c032d](https://github.com/kubernetes/website/pull/41825/commits/f0c032d791985e20ea131c63c4537bec75c491b0) 부터 [288e572](https://github.com/kubernetes/website/pull/41825/commits/288e572b80099011e471c4303ebc3d90f22621ff)까지의 4개의 커밋을 squash를 통해 하나의 커밋으로 합쳐주시면 감사하겠습니다:)

2023-07-22 04:54 UTC, jongwooo commented on content/ko/docs/concepts/scheduling-eviction/taint-and-toleration.md
> +API 서버와의 통신이 재개될때까지 kubelet에 전달되지 않는다. 그동안 삭제가 스케쥴링된 파드들이 분리된 노드에서
자연스럽게 다듬어 보았습니다.

```suggestion
API 서버와의 통신이 재개될 때까지 kubelet에 전달될 수 없다. 그동안 삭제가 스케쥴링된 파드들이 분리된 노드에서
```

2023-07-22 04:54 UTC, jongwooo commented on content/ko/docs/concepts/scheduling-eviction/taint-and-toleration.md
> +노드에 접근이 불가능한 경우, API 서버는 노드의 kubelet과의 통신에 실패한다. 파드를 삭제하기로 한 의사결정은
```suggestion
노드에 접근이 불가능한 경우, API 서버는 노드의 kubelet과의 통신에 실패한다. 파드 삭제 결정은
```

2023-07-22 04:54 UTC, jongwooo commented on content/ko/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
M47의 mermaid 다이어그램을 에디터 상에서 수정한 후, 링크를 공유하면 변경 사항이 저장이 되어 있네요. 하기 링크 확인해보시고 적용 부탁드립니다.

[mermaid 다이어그램](https://mermaid.live/edit#pako:eNp1Uk9v0zAc_SqWd0PpSpMs64wEl3HkxA3CwYvtxloSR7EzmKpKReQwuh6QgInDhnaINI4b2gEkPlHjfgecP22ExHzy7_2en9-zf1MYCEIhglJhRQ85nmQ4HpzYfuInwCw5QmC9XFafL4H-cKWLuw62e3hR6j9zXRbVzXuw-rnUV_frxa_q04-O6fyfqct59bvoaW5POy_XFx9bmDP0wAWr2zkwAvriHujvZ9XiiwGetYdeP3oDBoOnxvsmQ1NytvHelQ9JA319ubq73XrjrJUzmfXXojo_09_KfzsmY1WUm8At5m6CNaXxVD9pEGEpDykDx2MJGI8itOPYXkD3LKkycUzRDmOs2w_ecqJC5KbvrEBEImt6TzoNE8qStiUdS7oWb_T8BFowplmMOTEfOq3v96EKaUx9iMyWUIbzSPnQT2aGinMlXp4mAUQqy6kF85T0IwARw5Hcos8JVyLbgpHAhJpyCtVpWk_PhEtlJAORMD6p8TyLDBwqlUo0HNbt3QlXYX60G4h4KDkJcabCkwNv6NneGNsO9fYdvOc4JDgaHYyZ7Y4Y2X88sjGczSyY4uSVEL0r2vh50Y5uM8Gzv5FKGGo)

2023-07-22 04:54 UTC, jongwooo commented on content/ko/docs/concepts/scheduling-eviction/pod-scheduling-readiness.md
또한, #40000 의 변경 사항도 적용 부탁드립니다.

2023-07-29 13:37 UTC, YanyChoi commented
@jongwooo 수정사항 반영했습니다.
밑에 제대로 안봐서 mermaid 공유 칸이 있는줄도 몰랐네요 😅
svg 파일까지 추가했습니다~

2024-01-01 06:56 UTC, jongwooo commented
@YanyChoi 확인이 늦어 죄송합니다..! 리뷰 꼼꼼하게 반영해주셔서 감사합니다:)

/lgtm

2024-01-02 02:28 UTC, YanyChoi commented
@jongwooo approve label이 필요한 것 같습니다...!

2024-01-02 03:36 UTC, jongwooo commented
@YanyChoi approve label은 [승인자 권한](https://kubernetes.io/ko/docs/contribute/review/for-approvers/#리뷰를-위한-prow-명령)이어서 제가 드리긴 어려울 것 같습니다.. ㅎㅎ 추후에 승인자께서 검토하시고 추가해주실 듯 합니다!

2024-01-26 06:27 UTC, jihoon-seo commented
@YanyChoi @jongwooo 고생 많으셨습니다 감사합니다!
/approve

2024-01-26 06:33 UTC, merged