[ko] Update outdated files in dev-1.27-ko.1 (M222-M229)
kubernetes/website pull request #41951
Opened 2023-07-09 03:09 UTC by onestone9900

Related comment: https://github.com/kubernetes/website/issues/41631#issuecomment-1608836600

[x] M222. content/en/docs/tutorials/hello-minikube.md | 41(+M) 37(-)
[x] M223. content/en/docs/tutorials/kubernetes-basics/_index.html | 3(+XS) 1(-)
[x] M224. content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html | 17(+S) 19(-)
[x] M225. content/en/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro.html | 11(+S) 9(-)
[x] M226. content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html | 17(+S) 33(-)
[x] M227. content/en/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html | 67(+M) 14(-)
[x] M228. content/en/docs/tutorials/kubernetes-basics/explore/explore-interactive.html | 17(+S) 25(-)
[x] M229. content/en/docs/tutorials/kubernetes-basics/explore/explore-intro.html | 69(+M) 7(-)

2023-07-09 03:11 UTC, onestone9900 commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro.html
> +                    스케줄한다.
원문과 라인을 일치하기 위해 줄바꿈 합니다.

2023-09-07 11:18 UTC, jongwooo commented
/assign

2023-09-07 17:02 UTC, jongwooo requested changes
@onestone9900 사소한 사항들 확인해봤습니다. 아래 리뷰 의견 참고하여 업데이트 부탁드립니다.

2023-09-10 09:44 UTC, onestone9900 commented on content/ko/docs/tutorials/hello-minikube.md
> +쿠버네티스 대시보드를 열어보자. 두 가지 방법으로 할 수 있다:
안녕하세요~

리뷰 감사합니다.

찾아보니 다른 문서도 전부 : -> .으로 되어있네요!

수정하겠습니다. 감사합니다 ㅎㅎ!

2023-09-13 06:23 UTC, jihoon-seo reviewed
@onestone9900 고생 많으셨습니다.
간단하게 후속 코멘트를 달아 보았습니다.
확인을 부탁드립니다. ㅎㅎ

2023-09-13 06:23 UTC, jihoon-seo commented on content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
@onestone9900 님께서 반영을 하신 것 같은데, 이 코멘트가 해당 line에 달려 있는 것은 아니고 file에 달려 있어서 "Outdated" 표시가 붙지 않은 것 같습니다.
@onestone9900 님, 아마도 "Mark as resolved" 버튼을 눌러서 처리 완료로 표시하실 수 있습니다. ㅎㅎ

2023-09-13 06:23 UTC, jihoon-seo commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
@onestone9900 이 파일에서는 위의 리뷰가 아직 반영되지 않았네요.
확인 및 반영을 부탁드리겠습니다. ㅎㅎ

2023-09-13 06:23 UTC, jihoon-seo commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
> +              콘텐츠는 이용이 불가능하다
@onestone9900 님, 확인 및 반영을 부탁드리겠습니다. ㅎㅎ

2023-09-13 14:33 UTC, onestone9900 commented on content/ko/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
> +              콘텐츠는 이용이 불가능하다
앗,,, 반영했습니다!

2023-09-13 14:36 UTC, onestone9900 commented on content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
혹시 Resolve conversation을 말씀하시는걸까요~?

이것저것 찾아봐도 Mark as resolved는 어떻게 처리할지 모르겠습니다. @_@!!
검색해보니 Mark as resolved는 충돌 났을 때 코드 수정 시 나오는 것 같네요!

2023-09-13 23:43 UTC, jihoon-seo commented on content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
아 Resolve conversation 가 맞습니다.. ㅎㅎㅎ

2023-09-17 02:07 UTC, onestone9900 commented on content/ko/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
아하 감사합니다 ㅎㅎㅎㅎ!

2023-09-18 01:17 UTC, jihoon-seo commented
@onestone9900 @jongwooo 감사합니다! LGTM 입니다. ㅎㅎ
/lgtm

2023-09-21 02:12 UTC, jihoon-seo commented
제가 머지 하겠습니다~~
/approve

2023-09-21 02:13 UTC, merged