Add SIG CLI Spotlight article
kubernetes/website pull request #41973
Opened 2023-07-10 18:24 UTC by fsmunoz

SIG CLI Spotlight article.

Initial review is done in the contributor-site: https://github.com/kubernetes/contributor-site/pull/411

The final version there will be copied here, with any necessary adjustments, like the date.

2023-07-13 15:16 UTC, sftim requested changes
Thanks. With a couple of tweaks, this'll be good to go.

/hold
Let's merge this once the other PR has merged.
(we can unhold the contributor site PR once this has earned LGTM and approval)

2023-07-13 15:16 UTC, sftim commented on content/en/blog/_posts/2023-07-13-sig-cli-spotlight.md
Delete this file.

2023-07-13 15:22 UTC, fsmunoz commented on content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md
> +
Done in latest commit.

2023-07-13 16:38 UTC, sftim commented on content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md
> +author: "Arpit Agrawal"
```suggestion
```

2023-07-13 18:40 UTC, sftim commented
/retitle Add SIG CLI Spotlight article
/lgtm
/approve

2023-07-13 18:42 UTC, sftim reviewed
/hold cancel

2023-07-13 18:42 UTC, sftim commented on content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md
> +---
D'oh
(nice to get this in after merge)
```suggestion
canonicalUrl: https://www.kubernetes.dev/blog/2023/07/13/sig-cli-spotlight-2023/
---
```

```

2023-07-13 18:43 UTC, merged

2023-07-14 11:19 UTC, fsmunoz commented on content/en/blog/_posts/2023-07-20-sig-cli-spotlight.md
> +---
Added in a new PR!