improved the grammar in the hindi docs
kubernetes/website pull request #42036
Opened 2023-07-16 08:38 UTC by Vikash-8090-Yadav

Improved some grammatical mistakes.

2023-07-16 11:10 UTC, windsonsea commented
/language hi

2023-07-16 17:15 UTC, kundan2707 commented on README-hi.md
> +स्वागत हे! इस रिपॉजिटरी में [कुबरनेट्स वेबसाइट और दस्तावेज](https://kubernetes.io/) बनाने के लिए आवश्यक सभी संपत्तियाँ हैं। हम बहुत खुश हैं कि आप योगदान करने की इच्छा रखते हैं!
स्वागत है

2023-07-17 07:57 UTC, Vikash-8090-Yadav commented
Done with  the chnages. Thanks @kundan2707

2023-07-22 15:24 UTC, Vikash-8090-Yadav commented
Any updates on this pr?

2023-07-23 19:32 UTC, kundan2707 reviewed
Changes looks good now

2023-07-23 19:32 UTC, kundan2707 commented
/lgtm

2023-07-23 19:33 UTC, kundan2707 commented
@Vikash-8090-Yadav squash multiple commits

2023-08-07 13:06 UTC, divya-mohan0209 requested changes
Thank you for the PR. We should try to keep the sentences as idiomatic as possible rather than complicating it.

2023-08-07 13:06 UTC, divya-mohan0209 commented on README-hi.md
> +स्वागत है! इस रिपॉजिटरी में [कुबरनेट्स वेबसाइट और दस्तावेज](https://kubernetes.io/) बनाने के लिए आवश्यक सभी संपत्तियाँ हैं। हम बहुत खुश हैं कि आप योगदान करने की इच्छा रखते हैं!
More idiomatic in nature. I'd suggest not changing it.
```suggestion
स्वागत है! इस रिपॉजिटरी में [कुबरनेट्स वेबसाइट और दस्तावेज](https://kubernetes.io/) बनाने के लिए आवश्यक सभी संपत्तियाँ हैं। हम बहुत खुश हैं कि आप योगदान करना चाहते हैं!
```

2023-08-25 12:05 UTC, Vikash-8090-Yadav commented
Sorry, 4 the late response.!
 @divya-mohan0209 please check once I updated all the things as mentioned above. Thanks!

2023-09-06 11:28 UTC, aj11anuj approved these changes
All the requested changes are made properly, and everything seems fine here. Its ready to get merged.

2023-11-18 09:11 UTC, Babapool reviewed
Thanks!
/lgtm

2023-12-04 10:26 UTC, kundan2707 commented
/label tide/merge-method-squash

2023-12-07 04:51 UTC, merged