added and imporved the grammar
kubernetes/website pull request #42037
Opened 2023-07-16 09:38 UTC by Vikash-8090-Yadav

Improved the grammar

2023-07-16 17:25 UTC, kundan2707 commented on content/hi/includes/task-tutorial-prereqs.md
> +समनुरूप करना होगा ताकि वो आपके क्लस्टर के साथ संवाद कर सकें। हमारी सलाह है की इस टुटोरिअल को क्लस्टर में रन करने के लिए कम से कम दो नोड का इस्तेमाल करें जो कि कंट्रोल प्लेन
समनुरूप करना होगा ताकि वो आपके क्लस्टर के साथ संवाद कर सके। हमारी सलाह है कि

2023-07-17 07:53 UTC, Vikash-8090-Yadav commented
Done with the changes. Thanks @kundan2707

2023-07-17 08:31 UTC, dipesh-rawat commented on content/hi/includes/task-tutorial-prereqs.md
> +* [प्ले विथ कुबेरनेट्स](http://labs.play-with-k8s.com/)
We recently merged PR[#41665](https://github.com/kubernetes/website/pull/41665/files) for the main website (equivalent 'hi' PR[#41917](https://github.com/kubernetes/website/pull/41917/files) ) to change this link to use secure HTTPS. However, I'm wondering why the link in this particular PR has been altered to an insecure 'HTTP' again.

2023-07-17 08:38 UTC, kundan2707 commented
> Done with the changes. Thanks @kundan2707
Make sure to squash all commits to a single once after resolving all comments from all reviewers.

2023-07-19 10:11 UTC, sftim commented
/label tide/merge-method-squash
/retitle Tweak grammar for localized (hi) task / tutorial prerequisites

2023-07-19 10:11 UTC, sftim commented
/reopen
Sorry, misclick!

2023-09-06 11:03 UTC, aj11anuj commented on content/hi/includes/task-tutorial-prereqs.md
>  होस्ट के तरह ना एक्ट करे। अगर आपके पास पहले से क्लस्टर नही है, आप
This one is more appropriate

समनुरूप करना होगा ताकि वो आपके क्लस्टर के साथ संवाद कर सके। हमारी सलाह है कि इस ट्यूटोरियल को क्लस्टर में रन करने के लिए कम से कम दो नोड का इस्तेमाल करें जो कि कंट्रोल प्लेन
होस्ट की तरह कार्य ना करे । अगर आपके पास पहले से क्लस्टर नही है, तो आप

2023-09-06 11:09 UTC, aj11anuj commented on content/hi/includes/task-tutorial-prereqs.md
>  * [प्ले विथ कुबेरनेट्स](https://labs.play-with-k8s.com/)
I think either "Play with Kubernetes" needs to be written in English or "Katacoda", "minikube" needs be written in hindi

2023-09-06 11:10 UTC, aj11anuj requested changes
Here are my thoughts, and some suggestions

2023-11-22 05:08 UTC, niranjandarshann commented
@Vikash-8090-Yadav  Could you please squash your commits: https://kubernetes.io/docs/contribute/new-content/open-a-pr/#squashing-commits.

2024-04-20 06:48 UTC, closed without merging