api-concepts.md: fix TypeMeta definition
kubernetes/website pull request #42072
Opened 2023-07-18 16:56 UTC by loskutov

Fix TypeMeta definition to match one in generated protobufs

2023-07-19 09:49 UTC, sftim commented
/wg api-expression
/sig api-machinery

2023-07-19 11:15 UTC, loskutov commented
Eventually, the message is actually from https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/generated.proto, and it corresponds with the one in the documentation. It could be useful to have the link, though.

2023-09-20 07:28 UTC, Ritikaa96 requested changes

2023-09-20 07:28 UTC, Ritikaa96 commented on content/en/docs/reference/using-api/api-concepts.md
> +The messages described above can also be found at https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/generated.proto.
```suggestion
The messages described above can also be found at https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/generated.proto/.
```

2023-09-20 08:02 UTC, Ritikaa96 requested changes

2023-09-20 08:02 UTC, Ritikaa96 commented on content/en/docs/reference/using-api/api-concepts.md
> +The messages described above can also be found at https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/generated.proto.
Maybe we can add it as a hyperlink and not just paste the link inline.
Something along the lines of :
```
The message above can also be found in kubernetes [sourcecode](https://github.com/kubernetes/apimachinery/blob/master/pkg/runtime/generated.proto/).
```

2023-10-10 06:56 UTC, tengqm commented
@loskutov Mind revise the pointer to a Markdown link?

2023-10-10 06:56 UTC, tengqm commented
Also, `master` is a moving target. Maybe we should point to a tag instead?

2023-11-14 12:35 UTC, divya-mohan0209 commented
Hello @loskutov , gentle reminder about this PR. Would you be able to address the changes suggested by @tengqm and @Ritikaa96 ?

2023-11-15 10:22 UTC, Ritikaa96 commented
Sure @divya-mohan0209 . 

> Also, `master` is a moving target. Maybe we should point to a tag instead?

Am not able to understand what is requested here. a bit confused . should we change the `master` to branch name there?

2023-11-15 13:52 UTC, sftim commented
I'd use a tag; what I'd use is `release-{{< skew currentVersion >}}`.

Why? Because it's useful to link to the version of that file for the relevant release. There's a risk that the link breaks, but that breakage will be obvious to any reader, whereas a link to stale code might not be.

Link checkers should be able to pick up a putative broken link, too. Right now we don't run automated link checking that I know of, but it's a well known technique.

2023-12-20 13:47 UTC, kbhawkey commented
Hello @loskutov .
Can you address the suggestions or do you have questions?
If you are no longer actively working on your pull request, you can close it and reopen it at a later time.
Thanks

2024-01-24 11:41 UTC, divya-mohan0209 commented
Hello @loskutov , thank you for your contribution. However, since there has been no response from your side, we will be closing this PR. If you wish to continue work on this PR, please feel free to reopen it.
/close

2024-01-24 11:41 UTC, closed without merging