Fixing issue #38958
kubernetes/website pull request #42093
Opened 2023-07-19 22:46 UTC by abhigyadufare

Card structure for Features section on Homepage.

2023-07-20 07:41 UTC, utkarsh-singh1 commented
Hi @abhigyadufare, seems like Netlify Build time is over , you can regenerate the build process with - 

```bash
git reset
git commit --amend --no-edit
git push --force-with-lease
```

2023-07-20 08:08 UTC, abhigyadufare commented
Hi @utkarsh-singh1, i followed your instructions and force-pushed it.

2023-07-20 08:36 UTC, sftim commented
/retitle Amend card structure for Features section on Homepage

2023-07-20 08:36 UTC, sftim commented
This may relate to #38958

2023-07-20 08:37 UTC, sftim commented
@abhigyadufare please write a PR description that summarizes why we should make this change

2023-07-20 08:57 UTC, abhigyadufare commented
@sftim okay

2023-07-20 09:10 UTC, abhigyadufare commented
### As mentioned in the description of the issue #38958 

**This is a Feature Request** which has been approved

<img width="431" alt="212727755-884a255e-fa84-46e2-bb5c-a455f1712d08" src="https://github.com/kubernetes/website/assets/76903966/3d270835-6973-41fc-9c97-82517d04de0e">

The above image displays the card structure that needs to be implemented

**Why is this needed**
It provides a better structure and look to the section. It makes them stand out.

2023-07-20 10:34 UTC, sftim commented
/area web-development

2023-07-20 10:35 UTC, sftim requested changes
Looks good, _but_ I don't want to delete the JavaScript package lock.

2023-07-20 10:35 UTC, sftim commented on package-lock.json
Please don't delete this file.

2023-07-20 11:05 UTC, abhigyadufare commented on package-lock.json
i used 
-`npm audit fix`
but i can remove it if required and keep the previous package.json file.

2023-07-24 12:52 UTC, sftim commented
/label tide/merge-method-squash

2023-07-24 12:52 UTC, abhigyadufare commented
@sftim Is this what you wanted me to do?

2023-07-24 12:54 UTC, sftim commented
Thanks

/lgtm

2023-08-07 13:08 UTC, divya-mohan0209 reviewed
LGTM! Thank you so much for these changes :)
/approve

2023-08-07 13:10 UTC, merged

2023-08-07 16:34 UTC, abhigyadufare commented
> LGTM! Thank you so much for these changes :) /approve

@divya-mohan0209  Pleasure 😊 Please do me know if i should do this on other pages as well.

2023-08-07 16:36 UTC, sftim commented
Feel free to open new issues with suggested web design improvements @abhigyadufare