KEP-2681: Docs update for Alpha PodHostIPs
kubernetes/website pull request #42153
Opened 2023-07-24 01:57 UTC by wzshiming

ref: https://github.com/kubernetes/enhancements/issues/2681

2023-07-24 02:24 UTC, sftim requested changes
I assume that we'll also need an update to https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-fieldRef to mention the new field and the feature gate that controls it.

Please add that.

2023-07-24 02:24 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +- `PodHostIPs`: Enables the `status.hostIPs` field for pods and downward API to expose host IPs.
```suggestion
- `PodHostIPs`: Enable the `status.hostIPs` field for pods and the {{< glossary_tooltip term_id="downward-api" text="downward API" >}}. The field lets you expose host IP addresses to workloads.
```

2023-07-24 06:15 UTC, wzshiming commented
Done

2023-07-24 21:26 UTC, sftim commented
> Done

I still don't see an update to the downward API docs.

2023-07-25 02:01 UTC, wzshiming commented
Updated, sorry, I didn't notice it before.

2023-07-25 09:33 UTC, sftim commented on content/en/docs/concepts/workloads/pods/downward-api.md
> +: the IP addresses is a dual-stack version of `status.hostIP`, the first is always the same as `status.hostIP`
```suggestion
: the IP addresses is a dual-stack version of `status.hostIP`, the first is always the same as `status.hostIP`. The field is available if you enable the `PodHostIPs` [feature gate](/docs/reference/command-line-tools-reference/feature-gates/).
```

2023-07-25 09:34 UTC, sftim commented on content/en/docs/concepts/workloads/pods/downward-api.md
We might need to change
```diff
-For most Pod-level fields, you can provide them to a container either as
+For some Pod-level fields, you can provide them to a container either as
an environment variable or using a `downwardAPI` volume. The fields available
via either mechanism are:
```

2023-07-25 09:45 UTC, wzshiming commented
done

2023-07-25 10:05 UTC, sftim commented on content/en/docs/reference/kubernetes-api/workload-resources/pod-v1.md
Don't update this file. We'll automatically update it during the release process.

2023-07-25 10:05 UTC, sftim commented on content/en/docs/reference/kubernetes-api/cluster-resources/node-v1.md
Don't update this file. We'll automatically update it during the release process.

2023-07-25 10:06 UTC, sftim commented
I think this is ready for a tech review.

2023-08-03 02:37 UTC, tengqm commented on content/en/docs/concepts/workloads/pods/downward-api.md
> +: the IP addresses is a dual-stack version of `status.hostIP`, the first is always the same as `status.hostIP`. The field is available if you enable the `PodHostIPs` [feature gate](/docs/reference/co
please manually wrap the long line as we do for other paragraphs.

2023-08-03 02:37 UTC, tengqm commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +- `PodHostIPs`: Enable the `status.hostIPs` field for pods and the {{< glossary_tooltip term_id="downward-api" text="downward API" >}}. The field lets you expose host IP addresses to workloads.
Please wrap the long line.

2023-08-05 13:27 UTC, sftim reviewed
Thanks

/lgtm
/approve

2023-08-05 13:28 UTC, merged