localize hi/docs/reference/glossary/cluster.md
kubernetes/website pull request #42250
Opened 2023-07-27 13:21 UTC by kundan2707

localize hi/docs/reference/glossary/cluster.md

2023-07-27 13:21 UTC, kundan2707 commented
/kind documentation

2023-07-27 13:21 UTC, kundan2707 commented
/language hi

2023-07-31 18:25 UTC, kundan2707 commented
@anubha-v-ardhan @divya-mohan0209  PATL

2023-08-17 05:54 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cluster.md
> +{{< glossary_tooltip text="कंट्रोल प्लेन" term_id="control-plane" >}} क्लस्टर में वर्कर नोड्स और पॉड्स का प्रबंधन करता है। एक प्रोडक्शन  वातावरण में, कंट्रोल प्लेन आमतौर पर
```suggestion
{{< glossary_tooltip text="कंट्रोल प्लेन" term_id="control-plane" >}} क्लस्टर में वर्कर नोड्स और पॉड्स का प्रबंधन करता है। एक प्रोडक्शन वातावरण में, कंट्रोल प्लेन आमतौर पर
```

2023-08-17 05:54 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cluster.md
> +कई कंप्यूटरों पर चलता है और एक क्लस्टर आमतौर पर कई नोड्स चलाता है, जो दोष-सहिष्णुता और उच्च उपलब्धता प्रदान करता है।
I don't know if high availability & failover should be translated the way you have done it here.

2023-09-07 05:56 UTC, aj11anuj commented on content/hi/docs/reference/glossary/cluster.md
> +कई कंप्यूटरों पर चलता है और एक क्लस्टर आमतौर पर कई नोड्स चलाता है, जो दोष-सहिष्णुता और उच्च उपलब्धता प्रदान करता है।
```suggestion
कई कंप्यूटरों पर चलता है और एक क्लस्टर आमतौर पर कई नोड्स चलाता है, जो बिना किसी विफलता के उच्च उपलब्धता प्रदान करता है। 
```

2023-09-07 06:01 UTC, aj11anuj requested changes
Although it will change meaning of whole sentence a bit but will increase clarity a lot and i think that's fine here.

2023-11-29 13:21 UTC, kundan2707 commented
@divya-mohan0209 @aj11anuj  incorporated review comments 
PTAL.

2024-02-29 04:33 UTC, kundan2707 commented
/remove-lifecycle stale

2024-03-08 06:48 UTC, divya-mohan0209 requested changes
Since we're referring to the machines themselves and not just the group of machines, the associated pronouns also need to change in number.

2024-03-08 06:48 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cluster.md
> +  वर्कर मशीनों का एक समूह, जिसे नोड्स भी कहा जाता है, जो कंटेनरीकृत एप्लिकेशन्स चलाते हैं। हर क्लस्टर में कम से कम एक वर्कर नोड होता है।
```suggestion
  वर्कर मशीनों का एक समूह, जिन्हें नोड्स भी कहा जाता है, जो कंटेनरीकृत एप्लिकेशन्स चलाते हैं। हर क्लस्टर में कम से कम एक वर्कर नोड होता है।
```

2024-03-08 06:48 UTC, divya-mohan0209 commented on content/hi/docs/reference/glossary/cluster.md
> +वर्कर मशीनों का एक समूह, जिसे {{< glossary_tooltip text="नोड्स" term_id="node" >}} भी कहा जाता है,
```suggestion
वर्कर मशीनों का एक समूह, जिन्हें {{< glossary_tooltip text="नोड्स" term_id="node" >}} भी कहा जाता है,
```

2024-07-11 12:33 UTC, divya-mohan0209 commented
@kundan2707 : Please could you push an empty commit to retrigger the build?

2024-07-11 18:49 UTC, kundan2707 commented
> @kundan2707 : Please could you push an empty commit to retrigger the build?

Pushed empty commit.

2024-07-30 12:12 UTC, aj11anuj reviewed
/lgtm

2024-08-12 11:23 UTC, merged