Translate blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/ into Japanese
kubernetes/website pull request #42335
Opened 2023-08-01 12:56 UTC by mikutas

Closes #42334

2024-01-30 07:15 UTC, Okabe-Junya commented
Thank you for your contribution!!

I'm very sorry for the long delay in responding. I will review this PR. Please wait a little longer :)

/assign
/remove-lifecycle stale

2024-01-30 07:23 UTC, Okabe-Junya commented
The target page on the deploy preview site:

- https://deploy-preview-42335--kubernetes-io-main-staging.netlify.app/ja/blog/2023/01/06/unhealthy-pod-eviction-policy-for-pdbs/

2024-01-30 16:38 UTC, Okabe-Junya requested changes
@mikutas 

改めて、レビューが非常に遅くなってしまい大変申し訳ないです。

いくつかコメントさせて頂きました。修正していただいた上で、再度 @Okabe-Junya にメンション飛ばしてください。

k/website内全体で、英単語/日本語間の空白は削除するようになっています。少し大変ですが、こちらの修正もお願いします

2024-01-30 16:38 UTC, Okabe-Junya commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +- [PodDisruptionBudgets](/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets)、[draining of Nodes](/docs/tasks/administer-cluster/safely-drain-node/)および [evictions](/docs/concepts/schedu
```suggestion
- [PodDisruptionBudgets](/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets)、[draining of Nodes](/docs/tasks/administer-cluster/safely-drain-node/)および [evictions](/ja/docs/concepts/scheduling-eviction/api-eviction/)についてKubernetesドキュメントを確認してください
```

日本語訳がすでに存在するものは、`/ja` を記載してください

2024-01-30 16:38 UTC, Okabe-Junya commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +これはアルファ機能であり、kube-apiserver に対してコマンドライン引数 `--feature-gates=PDBUnhealthyPodEvictionPolicy=true` を指定して
IMHO:

> This is an alpha feature, which means you have to enable the ...

は、「これはアルファ機能であるため、〇〇を有効にしなければならない」のように訳しても良いと思いました
（which meansは「意味する」ではなくイディオム的に訳して良いかと思います）

ref. https://eow.alc.co.jp/search?q=which+means

2024-01-30 16:38 UTC, Okabe-Junya commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +Web サーバー Pod が正常でない場合でも、退避を許可することにしました。
```suggestion
Web サーバーのPodが不健全な場合でも、退避を許可することにしました。
```

ditto

> IMO: 他の場所では "unhealthy" は「不健全な」と訳されていたので、統一した方が良いように思いました

2024-01-31 10:04 UTC, mikutas commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +PDB の `spec.unhealthyPodEvictionPolicy` フィールドを `AlwaysAllow` に設定することにより、アプリケーションにとってベストエフォートの可用性を選択することになります。
https://github.com/kubernetes/website/issues/44965 を作成しました 🙋

2024-01-31 10:06 UTC, mikutas commented
@Okabe-Junya レビューありがとうございます。修正を行いました。

2024-01-31 11:44 UTC, Okabe-Junya reviewed
Thank you~~!!

almost LGTM, but I have some nits

2024-01-31 11:44 UTC, Okabe-Junya commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +- PodDisruptionBudgets についてのドキュメントを読んでください: [Unhealthy Pod Eviction Policy](/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy)
```suggestion
- PodDisruptionBudgetsについてのドキュメントを読んでください: [Unhealthy Pod Eviction Policy](/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy)
```

ditto

2024-01-31 11:44 UTC, Okabe-Junya commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +- PodDisruptionBudgets についてのドキュメントを読んでください: [Unhealthy Pod Eviction Policy](/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy)
```suggestion
- PodDisruptionBudgetsについてのドキュメントを読んでください: [Unhealthy Pod Eviction Policy](/docs/tasks/run-application/configure-pdb/#unhealthy-pod-eviction-policy)
```

英単語/日本語間の空白の削除をお願いします（多分このセクションだけ抜け漏れですかね。。）

2024-01-31 11:44 UTC, Okabe-Junya commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +- [PodDisruptionBudgets](/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets)、[draining of Nodes](/docs/tasks/administer-cluster/safely-drain-node/)および [evictions](/ja/docs/concepts/sch
```suggestion
- [PodDisruptionBudgets](/docs/concepts/workloads/pods/disruptions/#pod-disruption-budgets)、[draining of Nodes](/docs/tasks/administer-cluster/safely-drain-node/)および[evictions](/ja/docs/concepts/scheduling-eviction/api-eviction/)についてKubernetesドキュメントを確認してください
```

ditto

2024-01-31 11:44 UTC, Okabe-Junya commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +フィードバックがある場合は、Slackの[#sig-apps](https://kubernetes.slack.com/archives/C18NZM5K9) チャンネル (必要な場合は https://slack.k8s.io/ にアクセスして招待を受けてください)、またはSIG Appsメーリングリストにご連絡ください。 kubernetes-sig-apps@googlegroups.c
```suggestion
フィードバックがある場合は、Slackの[#sig-apps](https://kubernetes.slack.com/archives/C18NZM5K9) チャンネル(必要な場合は https://slack.k8s.io/ にアクセスして招待を受けてください)、またはSIG Appsメーリングリストにご連絡ください。kubernetes-sig-apps@googlegroups.com
```

ditto

2024-01-31 11:47 UTC, Okabe-Junya commented
/label tide-merge-method-squash
/assign @nasa9084

2024-01-31 11:48 UTC, Okabe-Junya commented
/label tide/merge-method-squash

2024-01-31 13:02 UTC, nasa9084 commented on content/ja/blog/_posts/2023-01-06-unhealthy-pod-eviction-policy-for-pdb.md
> +または単に準備ができていないPodがあるアプリケーションが誤動作している場合、このタスクはさらに困難になります。
```suggestion
(バグまたは構成ミスにより)Podが`CrashLoopBackOff`状態になっているアプリケーション、または単に準備ができていないPodがあるアプリケーションが誤動作している場合、このタスクはさらに困難になります。
```

We can just merge lines if it's a single sentence. Breaking lines will insert a space but it's not expected for Japanese

2024-02-01 07:45 UTC, Okabe-Junya commented
Thank you, LGTM!!

/lgtm

2024-02-13 05:55 UTC, nasa9084 commented
Thank you,
/approve

2024-02-13 06:02 UTC, merged