Tracking with finalizers is always enabled
kubernetes/website pull request #42388
Opened 2023-08-04 15:36 UTC by alculquicondor

In Kubernetes 1.27, we made tracking with finalizers always enabled, even for Jobs created before tracking with finalizers was enabled.
As part of this, we also removed the use of `bactch.kubernetes.io/job-tracking` as an annotation for the Job.

This was documented in the KEP https://github.com/kubernetes/enhancements/tree/master/keps/sig-apps/2307-job-tracking-without-lingering-pods#deprecation
and in https://kubernetes.io/docs/reference/labels-annotations-taints/#batch-kubernetes-io-job-tracking

2023-08-04 15:46 UTC, sftim commented
/retitle Mark Job tracking with finalizers as always enabled
/sig apps

2023-08-04 15:47 UTC, sftim requested changes
Please also update https://kubernetes.io/docs/reference/labels-annotations-taints/#batch-kubernetes-io-job-tracking (it implies that the v1.27 release is in the future)

2023-08-04 15:51 UTC, alculquicondor commented
Oh right, done :)

2023-08-04 16:03 UTC, sftim commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +are tracked with finalizers.
```suggestion
Adding or removing this annotation no longer has an effect (Kubernetes v1.27 and later).
All Jobs are tracked with finalizers.
```

2023-08-04 16:05 UTC, kannon92 reviewed
LGTM to me as someone that worked on removing these finalizers.

2023-08-04 17:41 UTC, alculquicondor commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +are tracked with finalizers.
Done

2023-08-08 17:57 UTC, sftim reviewed
/lgtm
/approve

Thanks

2023-08-08 17:58 UTC, merged