added docs for main.go and created new folder for autogenerate docs
kubernetes/website pull request #42483
Opened 2023-08-10 08:49 UTC by deepak4566

fixes some parts of #42453 
@sftim can check the docs ,can propose changes required for it 
in future many pr's are expected to come

2023-08-11 16:43 UTC, deepak4566 commented
/assign @logicalhan 
Your review is very much required here

2023-08-11 16:45 UTC, logicalhan commented on content/en/docs/contribute/generate-ref-docs/docs for autogeneration for metrics reference/docs for test/instrumentation/documentation/main.go.md
> +git clone https://github.com/yourusername/your-repo.git
this doesn't look accurate.

2023-08-11 16:50 UTC, deepak4566 commented on content/en/docs/contribute/generate-ref-docs/docs for autogeneration for metrics reference/docs for test/instrumentation/documentation/main.go.md
> +go run main.go
Hey thanks so much for ur review and will update the docs for sure 👍

2023-08-11 17:03 UTC, deepak4566 commented on content/en/docs/contribute/generate-ref-docs/docs for autogeneration for metrics reference/docs for test/instrumentation/documentation/main.go.md
> +git clone https://github.com/yourusername/your-repo.git
Done ! removed it

2023-08-13 15:46 UTC, sftim commented
> @sftim can check the docs ,can propose changes required for it

I'm one of our reviewers. Any other contributors are welcome to provide feedback as well.

2023-08-13 16:32 UTC, deepak4566 commented
> > @sftim can check the docs ,can propose changes required for it
> 
> I'm one of our reviewers. Any other contributors are welcome to provide feedback as well.

@sftim  fine with it , i have no problem regarding it ,as you are author of issue just wanted to see the changes and here every one are open for reviewing and contributing to community  , for me as a student it feels very good to me contributing to cncf or k8's docs

2023-08-20 22:43 UTC, sftim requested changes
This new page doesn't seem to render. You can [preview your changes locally](https://kubernetes.io/docs/contribute/new-content/open-a-pr/#preview-locally) to check that for yourself.

2023-09-15 01:10 UTC, tengqm commented
I'm not convinced that we need a deep analysis/explanation of the main.go program.
We can instead explain how the docs are generated and outline the main steps to follow
when the reference needs to be updated.
This PR is adding a markdown file to a weird path, and that path contains spaces.
Why are we doing this?
/hold

2023-09-18 12:00 UTC, sftim commented
A PR that covers the need from https://github.com/kubernetes/website/issues/42453 is welcome. I'm not sure this this PR covers that yet, though.

@deepak4566 please ensure that the PR description clearly explains what changes and **why**.

2023-10-10 02:33 UTC, tengqm commented
/close
No response from the author for a month.

2023-10-10 02:33 UTC, closed without merging