[ES] Corrección de ortografía y gramática en el archivo de documentación - Jonathan Lopez Torres
kubernetes/website pull request #42620
Opened 2023-08-18 03:09 UTC by jonathino2590

Corrección de ortografía y gramática en el archivo de documentación.

Realicé correcciones de ortografía y gramática en el archivo de documentación para mejorar su claridad y legibilidad. No se realizaron cambios en el contenido ni en la estructura del documento.

Cambios detallados:
- Corregí errores de ortografía y puntuación en todo el documento.
- Alineé los términos técnicos con la terminología estándar.
- Aseguré la coherencia en el uso de mayúsculas y minúsculas.

Estos cambios no afectan el contenido ni la intención original del documento. Por favor, revisa y aprueba los cambios. ¡Gracias!

2023-08-18 14:49 UTC, electrocucaracha reviewed
Un par de cosas a considerar:
* Al referirse a recursos de K8s (Pods, Services, Deployments), estos quedan como nombres propios y no se traducen.
* Que y como solo llevan acento en oraciones [interrogativas](https://www.rae.es/espanol-al-dia/tilde-en-que-cuales-quienes-como-cuan-cuantoaosas-cuando-donde-y-adonde).

2023-08-18 18:54 UTC, jonathino2590 commented
@electrocucaracha acabo de hacer un commit con los comentarios que me indicas

2023-08-18 19:18 UTC, electrocucaracha requested changes

2023-08-18 19:18 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +Usted puede ver cómo Kubernetes varía la tasa a la que ocurren las interrupciones,
```suggestion
Usted puede ver como Kubernetes varía la tasa a la que ocurren las interrupciones,
```

2023-08-18 19:34 UTC, electrocucaracha commented
/lgtm
/cc @krol3 @ramrodo @92nqb

2023-09-01 23:20 UTC, ramrodo commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +qué tipos de interrupciones pueden suceder en los pods.
```suggestion
qué tipos de interrupciones pueden suceder en los Pods.
```

2023-09-01 23:20 UTC, ramrodo commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +Los pods no desaparecen hasta que algo (una persona o un controlador) los destruye
```suggestion
Los Pods no desaparecen hasta que algo (una persona o un controlador) los destruye
```

2023-09-01 23:21 UTC, ramrodo commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +Si ninguna se encuentra habilitada, puede omitir la creación del presupuesto de Interrupción de pods.
```suggestion
Si ninguna se encuentra habilitada, puede omitir la creación del presupuesto de Interrupción de Pods.
```

2023-09-01 23:21 UTC, ramrodo commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +No todas las interrupciones voluntarias son consideradas por el presupuesto de interrupción de pods. Por ejemplo,
```suggestion
No todas las interrupciones voluntarias son consideradas por el presupuesto de interrupción de Pods. Por ejemplo,
```

2023-09-01 23:21 UTC, ramrodo commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +borrar un Deployment o pods que evitan el uso del presupuesto.
```suggestion
borrar un Deployment o Pods que evitan el uso del presupuesto.
```

2023-09-01 23:21 UTC, ramrodo commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +## Presupuesto de Interrupción de pods
```suggestion
## Presupuesto de Interrupción de Pods
```

2023-09-01 23:28 UTC, ramrodo requested changes
¡Gracias por corregir los errores @jonathino2590!

No sé si con el force push se eliminó la sugerencia de @electrocucaracha sobre dejar los nombres propios (Pods, Services, Deployments) porque aún siguen en minúsculas.

¿Podrías corregir esto por favor?
Mismo comentario

2023-09-02 01:54 UTC, jonathino2590 commented
@ramrodo listo ya apliqué los cambios sugeridos

2023-09-02 15:43 UTC, ramrodo commented
@jonathino2590 ¿podrías actualizar todas las referencias a **Pods** por favor?. Solo había marcado una sugerencias como ejemplo pero necesitamos que todo el documento tenga consistencia. Cualquier pregunta o duda estamos aquí atentos o [por Slack](https://kubernetes.slack.com/archives/CH7GB2E3B)

2023-09-05 15:49 UTC, electrocucaracha commented on content/es/docs/concepts/workloads/pods/disruptions.md
> +Un PDB limita el numero de pods de una aplicación replicada, que estan caídos de manera simultánea por
@jonathino2590 podrías actualizar `pods` como nombre propio
```suggestion
Un PDB limita el numero de Pods de una aplicación replicada, que estan caídos de manera simultánea por
```

2023-09-08 20:51 UTC, jonathino2590 commented
@electrocucaracha @ramrodo Listo ya hice el ultimo cambio que me solicitaron

2023-09-08 21:24 UTC, ramrodo approved these changes
Thanks!
/lgtm

2023-09-08 21:26 UTC, merged