[en] fix links for blog/_posts/2018-05-29-announcing-kustomize
kubernetes/website pull request #42635
Opened 2023-08-19 13:22 UTC by bugoverdose

from #42634

Fixed some oudated links in blog post: [Introducing kustomize; Template-free Configuration Customization for Kubernetes](https://kubernetes.io/blog/2018/05/29/introducing-kustomize-template-free-configuration-customization-for-kubernetes/)

Page updated: content/en/blog/_posts/2018-05-29-announcing-kustomize.md

2023-08-19 13:26 UTC, bugoverdose commented on content/en/blog/_posts/2018-05-29-announcing-kustomize.md
> -[kustomization]: https://github.com/kubernetes-sigs/kustomize/blob/master/docs/glossary.md#kustomization
I deleted [kustomization] because it's outdated link that leads to nowhere, and it's not used in the main content.

2023-08-19 13:26 UTC, bugoverdose commented on content/en/blog/_posts/2018-05-29-announcing-kustomize.md
> +[subproject]: https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/2377-Kustomize/README.md
This [commit](https://github.com/kubernetes/enhancements/commit/3e4e4171929e03de851d3fe3946f7d1e5d10bf33) shows that the page migrated from `~/0008-kustomize.md` to `~/2377-Kustomize/README.md`.

![image](https://github.com/kubernetes/website/assets/73531614/fe748775-f49d-4ffc-b6df-ffa5f3966891)

2023-08-19 13:26 UTC, bugoverdose commented on content/en/blog/_posts/2018-05-29-announcing-kustomize.md
> +[workflow]: https://github.com/kubernetes-sigs/kustomize/blob/1dd448e65c81aab9d09308b695691175ca6459cd/docs/workflows.md
I couldn't find where the page moved to, so I made it check the commit from 4 years ago.

2023-08-19 17:18 UTC, sftim requested changes
Please rebase against _main_; see https://lwkd.info/2023/20230606#developer-news for more context.

2023-08-20 02:15 UTC, bugoverdose commented
> Please rebase against _main_; see https://lwkd.info/2023/20230606#developer-news for more context.

I rebased it and Netlify build issue was fixed.

2023-08-20 02:18 UTC, tengqm commented
/lgtm
/approve

2023-08-20 02:19 UTC, merged