Gateway API 0.8.0... en español.
kubernetes/website pull request #42781
Opened 2023-08-29 18:19 UTC by kflynn

Versión en español del anuncio de la versión v0.8.0 de Gateway API (https://github.com/kubernetes/website/pull/42727). 

Spanish version of the Gateway API v0.8.0 announcement.

Signed-off-by: Flynn <flynn@buoyant.io>

2023-08-30 18:28 UTC, krol3 requested changes
Hi @kflynn thanks for your spanish translation :). This first review is about the term `Gateway API` mainly, in Spanish we use `API Gateway`.

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +cluster (north-south), estaba claro casi desde el principio que los mismos
```suggestion
cluster (norte-sur), estaba claro casi desde el principio que los mismos
```

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +service mesh (east-west). En 2022, el subproyecto Gateway API lanzó [la
```suggestion
service mesh (este-oeste). En 2022, el subproyecto Gateway API lanzó [la
```

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +de Gateway API tuvieran que aprender de nuevo todo lo aprendido.
```suggestion
de API Gateway tuvieran que aprender de nuevo todo lo aprendido.
```

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +de reflexión y debate, y proporcionan un camino viable, con cambios mínimos,
```suggestion
de reflexión y debate proporcionando un camino viable con cambios mínimos,
```

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +posibles soluciones para usar Gateway API para service mesh. El resultado
```suggestion
posibles soluciones para usar API Gateway para service mesh. El resultado
```

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +para permitir que Gateway API soporte service mesh.
```suggestion
para permitir que API Gateway soporte service mesh.
```

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +### ¿Cómo funcionará el enrutamiento de mesh con Gateway API?
```suggestion
### ¿Cómo funcionará la Malla de Servicios con API Gateway?
```
Check the sugggestion: https://glossary.cncf.io/es/service-mesh/

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +Todos los detalles se puede encontrar en [la documentación de la mesh de
```suggestion
Todos los detalles se puede encontrar en [la documentación del service mesh de
```

2023-08-30 18:28 UTC, krol3 commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +Gateway API][mesh-routing] y en [GEP-1426], pero en resumen: en Gateway API
```suggestion
API Gateway][mesh-routing] y en [GEP-1426], pero en resumen: en API Gateway
```

2023-08-31 14:40 UTC, electrocucaracha commented
/cc @electrocucaracha

2023-08-31 22:21 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +Además, nos alegra anunciar que Kuma 2.3+, Linkerd 2.14+, e Istio 1.16+
```suggestion
Además, nos alegra anunciar que Kuma 2.3+, Linkerd 2.14+ e Istio 1.16+
```

2023-08-31 22:24 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +Gateway. Anticipamos GEPs futuros en este área a medida que adquirimos más
```suggestion
Gateway. Anticipamos GEPs futuros en esta área a medida que adquirimos más
```

2023-08-31 23:00 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +ingress. Muchas service meshes no hacen así, y requerir que una mesh
```suggestion
ingress. Muchas service meshes no lo hacen así, y requieren que una mesh tipo Gamma
```

2023-08-31 23:01 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +implemente un controlador de ingress para cumplir con GAMMA no parece
```suggestion
implemente un controlador de ingress para cumplir con GAMMA lo cual no parece
```

2023-08-31 23:03 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +Versión v0.8.0 trata principalmente de preparar Gateway API para versión
```suggestion
Ésta versión trata principalmente de preparar Gateway API para versión
```

2023-08-31 23:03 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +v.1.0, en la que planeamos que HTTPRoute, Gateway, y GatewayClass se graduarán
```suggestion
v.1.0, en la que planeamos que HTTPRoute, Gateway y GatewayClass se graduarán
```

2023-08-31 23:06 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +GatewayClass, y HTTPRoute a la versión de API v1 desde v1beta1. Como
```suggestion
GatewayClass y HTTPRoute a la versión de API v1 desde v1beta1. Como
```

2023-08-31 23:06 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +[las notas de lanzamiento a la versión v0.8.0][v0.8.0 release notes].
```suggestion
[las notas de lanzamiento de la versión v0.8.0][v0.8.0 release notes].
```

2023-08-31 23:07 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +Gateway API representa el futuro de las APIs de load balancing, enrutamiento,
```suggestion
Gateway API representa el futuro de las APIs de load balancing, enrutamiento
```

2023-08-31 23:07 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +[Guides][guides] cubren la instalación y configuración de Gateway API, y
```suggestion
[Guías][guides] cubren la instalación y configuración de Gateway API, y
```

2023-08-31 23:08 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +tengas dudas en crear una nueva issue en nuestro repositorio de GitHub, o
```suggestion
tengas dudas en crear un nuevo issue en nuestro repositorio de GitHub o
```

2023-08-31 23:08 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +emocionados de ver cómo usas esta API en producción, y esperamos escuchar
```suggestion
emocionados de ver cómo usas esta API en producción y esperamos escuchar
```

2023-08-31 23:09 UTC, ramrodo commented on content/es/blog/_posts/2023-08-29-Gateway-API-v080.md
> +Aunque estos patrones están [Experimental][status], están disponibles en el
```suggestion
Aunque estos patrones están en [Experimental][status], están disponibles en el
```

2023-08-31 23:13 UTC, ramrodo requested changes
Thanks for your contribution @kflynn!

Some improvements related to grammar and orthography.

Also, the same comment as @krol3, we usually use `API Gateway` more than _"`Gateway API"_. So, please replace all these words :)

Additionally, instead of using `service mesh`, please use `malla de servicios`, as we do it at the [CNCF Glossary for service-mesh term in Spanish](https://glossary.cncf.io/es/service-mesh/).

2023-09-01 20:18 UTC, kflynn commented
@ramrodo, ¡gracias! Hoy aprendí que no se usa la coma Oxford en español. 🤦‍♂️ 

La nomenclatura acerca de "Gateway API" siempre es interesante – en inglés, el subproyecto ha decidido que debemos tratar "Gateway API" como un nombre propio, en vez de "*the* Gateway API* en la que "gateway" es un adjectivo que modifica "API". Todavía creo que sería mejor usar "API Gateway" en español? (Resultó que @krol3 y yo hablabamos en Slack sobre este tema ayer. 🙂)

Gracias!

2023-09-01 23:58 UTC, ramrodo commented
@kflynn De acuerdo con manejar "Gateway API". En el equipo de traducción al Español también conservamos los nombres propios originales del Inglés, por lo que si el subproyecto ha decidido manejarlo como nombre propio, nosotros en la traducción al Español, respetaremos esa decisión :)

/lgtm

/cc @electrocucaracha @krol3

2023-09-03 20:42 UTC, ramrodo approved these changes
Thanks! @kflynn 

/lgtm

2023-09-03 20:43 UTC, merged