[es] Add concepts/storage/projected-volumes.md
kubernetes/website pull request #43023
Opened 2023-09-12 21:05 UTC by edithturn

Se añadió la documentación en español para las sección:

content/es/docs/concepts/storage/projected-volumes.md
Agradecería puedan revisarlo y darme feedback.
Gracias! :)

2023-09-13 00:42 UTC, ramrodo commented
/cc @ramrodo @krol3

2023-09-13 22:27 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +  - raelga
Rael is not active in the revisions right now, but you can add @krol3
```suggestion
  - krol3
```

2023-09-13 22:33 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +Este documento describe los _volúmenes proyectados_ en Kubernetes. Necesita estar familiarizado con [volumes](/docs/concepts/storage/volumes/).
Creo que podemos colocar **volúmenes** ya que así está referido en [el artículo referenciado en español]() (igual podemos corregir el título de éste último porque está en Inglés pero en su contenido y definición refieren a _volúmenes_)

De igual forma, colocar la URL correspondiente al término ya existente de _/es/_:

```suggestion
Este documento describe los _volúmenes proyectados_ en Kubernetes. Necesita estar familiarizado con [volúmenes](/es/docs/concepts/storage/volumes/).
```

2023-09-13 22:34 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +- [`secret`](/docs/concepts/storage/volumes/#secret)
```suggestion
- [`secret`](/es/docs/concepts/storage/volumes/#secret)
```

2023-09-13 22:36 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +- [`configMap`](/docs/concepts/storage/volumes/#configmap)
```suggestion
- [`secret`](/es/docs/concepts/storage/volumes/#secret)
- [`downwardAPI`](/es/docs/concepts/storage/volumes/#downwardapi)
- [`configMap`](/es/docs/concepts/storage/volumes/#configmap)
```

2023-09-13 22:38 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +### Configuración de ejemplo con un secreto, una downwardAPI, y una configMap {#example-configuration-secret-downwardapi-configmap}
```suggestion
### Configuración de ejemplo con un secreto, una downwardAPI y una configMap {#example-configuration-secret-downwardapi-configmap}
```

2023-09-13 22:41 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +El Pod de ejemplo tiene un volumen proyectado que contiene el token de cuenta de servicio inyectado. Los contenedores en este Pod pueden usar ese token para acceder al servidor API de Kubernetes, aut
Seguir con el mismo formato de salto de línea por "frase" en vez de colocar todo el párrafo en una sola línea:

```suggestion
El Pod de ejemplo tiene un volumen proyectado que contiene el token de cuenta de servicio inyectado.
Los contenedores en este Pod pueden usar ese token para acceder al servidor API de Kubernetes,
autenticándose con la identidad [del pod de ServiceAccount](/docs/tasks/configure-pod-container/configure-service-account/).
```

2023-09-13 22:42 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +token. Un destinatario del token debe identificarse con un identificador especificado en la audiencia del token y, de lo contrario, debe rechazar el token. Este campo es opcional y de forma predeterm
Separar éste párrafo en varias líneas como en el documento original.

2023-09-13 22:43 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +The `expirationSeconds` es la duración esperada de validez del token de la cuenta de servicio. El valor predeterminado es 1 hora y debe durar al menos 10 minutos (600 segundos). Un administrador
Separar éste párrafo en varias líneas como en el documento original.

2023-09-13 22:44 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +En los pods de Windows que tienen un volumen proyectado y `RunAsUsername` configurado en el pod `SecurityContext`, la propiedad no se aplica debido a la forma en que se administran las cuentas de usu
Separar éste párrafo en varias líneas como en el documento original.

2023-09-13 22:47 UTC, ramrodo requested changes
Sugerencias recomendadas.

De igual forma, quisiera preguntarle a @electrocucaracha @krol3 si debemos manejar la referencia de "usted/tú" como en el caso de la L13: "Necesitas" en vez de "Necesita" (y otras referencias en el documento de este tipo). Ya que creo que habíamos comentado que íbamos a manejar la referencia de "tú"

2023-09-14 19:12 UTC, electrocucaracha commented
> Sugerencias recomendadas.
> 
> De igual forma, quisiera preguntarle a @electrocucaracha @krol3 si debemos manejar la referencia de "usted/tú" como en el caso de la L13: "Necesitas" en vez de "Necesita" (y otras referencias en el documento de este tipo). Ya que creo que habíamos comentado que íbamos a manejar la referencia de "tú"

Muy importante este tema, quizá deberíamos de volver revisar la documentación para determinar cuál opción tendría menor impacto y mantener consistencia, actualizando las diferencias.

2023-09-19 15:39 UTC, ramrodo commented
> > Sugerencias recomendadas.
> > De igual forma, quisiera preguntarle a @electrocucaracha @krol3 si debemos manejar la referencia de "usted/tú" como en el caso de la L13: "Necesitas" en vez de "Necesita" (y otras referencias en el documento de este tipo). Ya que creo que habíamos comentado que íbamos a manejar la referencia de "tú"
> 
> Muy importante este tema, quizá deberíamos de volver revisar la documentación para determinar cuál opción tendría menor impacto y mantener consistencia, actualizando las diferencias.

@krol3 y yo decidimos en la junta semanal que nos parece más adecuado manejar la referencia de los verbos en Tú de forma implícita, es decir, "Necesitas", "Quieres", etc.

2023-09-20 19:57 UTC, edithturn commented on content/es/docs/concepts/storage/projected-volumes.md
> +Este documento describe los _volúmenes proyectados_ en Kubernetes. Necesita estar familiarizado con [volumes](/docs/concepts/storage/volumes/).
Tiene mucho sentido! Gracias por el feedback!

2023-09-20 20:01 UTC, edithturn commented on content/es/docs/concepts/storage/projected-volumes.md
> +- [`configMap`](/docs/concepts/storage/volumes/#configmap)
@ramrodo estoy de acuerdo con esto. En el caso de sownwardAPI, esta documentación no esta visible en español aún https://kubernetes.io/docs/concepts/workloads/pods/downward-api/

2023-09-20 20:05 UTC, edithturn commented on content/es/docs/concepts/storage/projected-volumes.md
> +El Pod de ejemplo tiene un volumen proyectado que contiene el token de cuenta de servicio inyectado. Los contenedores en este Pod pueden usar ese token para acceder al servidor API de Kubernetes, aut
Entiendo que esto es una mejora de la documentación en Inglés, correcto?
Por que revisando la documentacion en Inglés todo se muestra en un solo párrafo: https://kubernetes.io/docs/concepts/storage/projected-volumes/

Sin embargo pienso que ponerlo con saltos de linea, se ven definitivamente mejor.

2023-09-20 20:09 UTC, edithturn commented on content/es/docs/concepts/storage/projected-volumes.md
> +token. Un destinatario del token debe identificarse con un identificador especificado en la audiencia del token y, de lo contrario, debe rechazar el token. Este campo es opcional y de forma predeterm
Ya veo, estoy revisando la documentación oficial https://kubernetes.io/docs/concepts/storage/projected-volumes/
No veo que esto este separado por saltos de línea, sino todo esta en un solo párrafo. Por favor indicame si me estoy olvidando o perdiendo de algo.
<img width="609" alt="Screenshot 2023-09-20 at 15 07 08" src="https://github.com/kubernetes/website/assets/58795858/b78224b5-27d2-46f7-86de-333b6dd283a7">

2023-09-20 20:12 UTC, edithturn commented on content/es/docs/concepts/storage/projected-volumes.md
> +En los pods de Windows que tienen un volumen proyectado y `RunAsUsername` configurado en el pod `SecurityContext`, la propiedad no se aplica debido a la forma en que se administran las cuentas de usu
Gracias por tu feedback @ramrodo. Viendo la documentación en Inglés. Veo que todo esta en un solo párrafo. Definitivamente me estoy perdiendo de algo. Estou revisando la documentación de la version V1.28 https://kubernetes.io/docs/concepts/storage/projected-volumes/

<img width="632" alt="Screenshot 2023-09-20 at 15 10 42" src="https://github.com/kubernetes/website/assets/58795858/e4dcbe84-9bb3-4985-81be-1cfce8fad06f">

2023-09-26 16:08 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +En los pods de Windows que tienen un volumen proyectado y `RunAsUsername` configurado en el pod `SecurityContext`, la propiedad no se aplica debido a la forma en que se administran las cuentas de usu
@edithturn Una disculpa, creo que no me dí a explicar bien. En el website, sí se ve visualizado en un solo párrafo, sin embargo, en el código markdown, se añaden los saltos de línea para que sea más fácil de actualizar/corregir/ver diferencias de Git en un futuro.

Como bien dices, es una práctica que se está realizando en la documentación en inglés y en otros proyectos de traducción de la CNCF (como el Glosario, véase [semántica de saltos de línea](https://github.com/ramrodo/glossary/blob/main/content/es/style-guide/_index.md?plain=1#L132)).

Sería separar las líneas lo más parecido al artículo en inglés como en el [comentario de arriba](https://github.com/kubernetes/website/pull/43023#discussion_r1325143790).

/cc @electrocucaracha @krol3

2023-10-06 15:55 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +El Pod de ejemplo tiene un volumen proyectado que contiene el token de cuenta de servicio inyectado. Los contenedores en este Pod pueden usar ese token para acceder al servidor API de Kubernetes, aut
No es una mejora de la documentación en inglés, más bien, seguir el mismo formato de saltos de línea en el código Markdown. Ver [éste otro comentario](https://github.com/kubernetes/website/pull/43023#discussion_r1337461675) para mayor referencia.

2023-10-06 15:56 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +token. Un destinatario del token debe identificarse con un identificador especificado en la audiencia del token y, de lo contrario, debe rechazar el token. Este campo es opcional y de forma predeterm
Más bien, es seguir el mismo formato de saltos de línea en el código Markdown. Ver [éste otro comentario](https://github.com/kubernetes/website/pull/43023#discussion_r1337461675) para mayor referencia.

2023-10-08 07:29 UTC, edithturn commented on content/es/docs/concepts/storage/projected-volumes.md
> +El Pod de ejemplo tiene un volumen proyectado que contiene el token de cuenta de servicio inyectado. Los contenedores en este Pod pueden usar ese token para acceder al servidor API de Kubernetes, aut
De acuerdo, entonces creo que lo más correcto aqui sería: 
- El Pod de ejemplo tiene un volumen proyectado que contiene el token de cuenta de servicio inyectado.
- Los contenedores en este Pod pueden usar ese token para acceder al servidor API de Kubernetes,
autenticándose con la identidad [del pod de ServiceAccount](/docs/tasks/configure-pod-container/configure-service-account/).

2023-10-08 07:48 UTC, edithturn commented on content/es/docs/concepts/storage/projected-volumes.md
> +En los pods de Windows que tienen un volumen proyectado y `RunAsUsername` configurado en el pod `SecurityContext`, la propiedad no se aplica debido a la forma en que se administran las cuentas de usu
Cuesta un poco visualizar los saltos de linea, pero seguiré la recomendación que me diste Rodolfo, gracias por tu apoyo.

<img width="775" alt="Screenshot 2023-10-08 at 08 43 11" src="https://github.com/kubernetes/website/assets/58795858/89184bd1-4d67-48f5-aaac-762ac47a14c6">

2023-10-11 20:03 UTC, ramrodo commented on content/es/docs/concepts/storage/projected-volumes.md
> +En los pods de Windows que tienen un volumen proyectado y `RunAsUsername` configurado en el pod `SecurityContext`, la propiedad no se aplica debido a la forma en que se administran las cuentas de usu
Estoy de acuerdo contigo, sí es un poco más de trabajo andar colocando y siguiendo los saltos de línea pero facilitará la revisión y cambios que se quieran aplicar posteriormente.

Muchas gracias por implementar las sugerencias :)

2023-10-11 20:05 UTC, ramrodo approved these changes
¡Gracias! @edithturn 
/lgtm

2023-10-11 20:06 UTC, ramrodo commented
/cc @electrocucaracha @krol3
Buscando el segundo `/lgtm` :)

2023-10-11 20:09 UTC, merged