update Hover effect on all buttons
kubernetes/website pull request #43063
Opened 2023-09-15 15:33 UTC by anurag4499

2023-09-16 09:01 UTC, anurag4499 commented
/approve

2023-09-16 10:53 UTC, windsonsea commented
Please keep patient to wait for reviewer come in. You cannot approve any PR opened by yourself.

2023-09-16 12:05 UTC, utkarsh-singh1 commented
Hi @anurag4499, Always write a description on the PR as what changes are from your side, will help reviewers understand the PR.

2023-09-16 12:28 UTC, Gauravpadam requested changes
Some Suggestions from my end

2023-09-16 12:28 UTC, Gauravpadam commented on static/css/community.css
> +
These LGTM

2023-09-16 12:28 UTC, Gauravpadam commented on static/css/training.css
> +
These LGTM too

2023-09-16 12:28 UTC, Gauravpadam commented on assets/scss/_base.scss
> +  }
I would then put this pseudo class inside the button class above
```suggestion
    :hover {
      color: white;
      background-color:#298af5;
  }
```

2023-09-17 04:39 UTC, windsonsea commented
/area web-development

2023-09-26 08:13 UTC, tengqm commented
Looks like the improvement is done and merged in another PR, shall we close this one?

2023-09-27 22:33 UTC, onlydole commented
Closing this due to this PR: https://github.com/kubernetes/website/pull/43175

/close

2023-09-27 22:33 UTC, closed without merging