[zh] sync /working-with-objects/_index.md annotations field-selectors
kubernetes/website pull request #43208
Opened 2023-09-26 13:41 UTC by asa3311

2023-09-27 06:02 UTC, howieyuen requested changes

2023-09-27 06:02 UTC, howieyuen commented on content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> +大多数情况下，你需要提供 manifest 文件为 `kubectl` 提供这些信息。
```suggestion
大多数情况下，你需要提供 _manifest_ 文件为 `kubectl` 提供这些信息。
```

2023-09-27 06:02 UTC, howieyuen commented on content/zh-cn/docs/concepts/overview/working-with-objects/field-selectors.md
> +（`in`、`notin`、`exists`）不支持字段选择器。
```suggestion
（`in`、`notin`、`exists`）不支持字段选择算符。
```

2023-09-27 07:22 UTC, tengqm commented on content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> +大多数情况下，你需要提供 _manifest_ 文件为 `kubectl` 提供这些信息。
```suggestion
大多数情况下，你会通过 **清单（Manifest)** 文件为 `kubectl` 提供这些信息。
```

2023-09-27 07:22 UTC, tengqm commented on content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> +按照惯例，manifest 是 YAML 格式的（你也可以使用 JSON 格式）。
```suggestion
按照惯例，清单是 YAML 格式的（你也可以使用 JSON 格式）。
```

2023-09-27 07:22 UTC, tengqm commented on content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> +会将 manifest 中的信息转换为 JSON 或其他受支持的序列化格式。
```suggestion
会将清单中的信息转换为 JSON 或其他受支持的序列化格式。
```

2023-09-27 07:22 UTC, tengqm commented on content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> +这里有一个 manifest 示例文件，展示了 Kubernetes Deployment 的必需字段和对象 `spec`：
```suggestion
这里有一个清单示例文件，展示了 Kubernetes Deployment 的必需字段和对象 `spec`：
```

2023-09-27 07:22 UTC, tengqm commented on content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> +相较于上面使用 manifest 文件来创建 Deployment，另一种类似的方式是使用 `kubectl` 命令行接口（CLI）中的
```suggestion
与上面使用清单文件来创建 Deployment 类似，另一种方式是使用 `kubectl` 命令行接口（CLI）的
```

2023-09-27 07:22 UTC, tengqm commented on content/zh-cn/docs/concepts/overview/working-with-objects/_index.md
> +在想要创建的 Kubernetes 对象所对应的 manifest（YAML 或 JSON 文件）中，需要配置的字段如下：
```suggestion
在想要创建的 Kubernetes 对象所对应的清单（YAML 或 JSON 文件）中，需要配置的字段如下：
```

2023-09-27 14:25 UTC, tengqm commented
/lgtm

2023-09-28 12:02 UTC, windsonsea commented
Thanks.
/approve

2023-09-28 12:04 UTC, merged