Local Preview of Website now works normally on windows
kubernetes/website pull request #43211
Opened 2023-09-26 18:08 UTC by Gauravpadam

This PR aims to close #36937 and any other related issues which are already closed due to inactivity

I've modified hugo.toml to include a path for the i18n dir. This enables hugo to build the website on windows without explicitly building the symbolic links for it

2023-09-27 08:24 UTC, sftim commented on README.md
> +```
On Linux and other Unix, Git just works. No need to run this.

2023-09-27 08:26 UTC, sftim requested changes
/hold

Please don't delete the existing symbolic links. Contributors whose Git tool supports symbolic links won't like this change, and it breaks the site.

2023-09-27 09:38 UTC, Gauravpadam commented
Agreed, We might have to change the approach a little bit. Perhaps limiting the changes to windows will make things work

2023-09-28 12:48 UTC, Gauravpadam commented
@sftim I'd like to know your views on adding i18n to gitignore, To keep it unaffected from local changes

2023-09-28 13:09 UTC, sftim commented
> I'd like to know your views on adding i18n to gitignore, To keep it unaffected from local changes

This sounds like a bad idea. How would we add a new localization?

2023-09-29 19:42 UTC, Gauravpadam commented
With recent pushes, We just need a .env file and The current changes to hugo.toml appropriately recognize the OS type and select the symbolic link directory respectively

2023-09-30 19:02 UTC, Gauravpadam commented
Good for review now, I've changed the approach

2023-10-09 13:23 UTC, tengqm commented
/lgtm
/approve
/hold cancel

2023-10-09 13:26 UTC, merged