Fix initialDelaySeconds docs
kubernetes/website pull request #43289
Opened 2023-10-02 10:49 UTC by Affan-7

Fixes #43259

if `periodSeconds` > `initialDelaySeconds` then the `initialDelaySeconds` would be ignored. Tested on kubernetes 1.27

2023-10-02 16:19 UTC, aj11anuj requested changes
I think this line will make more sense, if it gets changed to this one 👇

2023-10-02 16:19 UTC, aj11anuj commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +  ignored. Defaults to 0 seconds. Minimum value is 0.
```suggestion
  ignored and defaults to 0 seconds with minimum value 0.
```

2023-10-02 16:21 UTC, Affan-7 commented on content/en/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes.md
> +  ignored. Defaults to 0 seconds. Minimum value is 0.
I think it will cause confusion.

2023-10-03 15:49 UTC, sftim commented
/approve

2023-10-03 15:52 UTC, merged