Remove katacoda mention in kubernetes-tutorials in hindi document
kubernetes/website pull request #43480
Opened 2023-10-13 18:24 UTC by utkarsh-singh1

Description:
Removed katacoda instances in kubernetes-tutorials

Page to Update:
https://kubernetes.io/hi/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive/

2023-10-13 18:25 UTC, utkarsh-singh1 commented
fixes - #41496

2023-10-13 18:26 UTC, utkarsh-singh1 commented
/hold

2023-10-14 00:16 UTC, aj11anuj reviewed
LGTM, 👍

2023-10-14 05:25 UTC, Gauravpadam reviewed
Thanks,

One thing, I would redirect to the English blog article

2023-10-14 05:25 UTC, Gauravpadam commented on content/hi/docs/tutorials/kubernetes-basics/create-cluster/cluster-interactive.html
> +                अधिक जानकारी के लिए देखें <a href="https://kubernetes.io/pt-br/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/">
This should redirect to "https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/"

2023-10-16 18:45 UTC, Gauravpadam reviewed
Thanks for the wider set of changes,

A few things,

- Try to localize with context
- If not, The suggested changes are fine too!

2023-10-16 18:45 UTC, Gauravpadam commented on content/hi/docs/tutorials/kubernetes-basics/deploy-app/deploy-interactive.html
> +                क्लस्टर बनाने के तरीके पर इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
Better to localize these in correct contexts OR we could do this
```suggestion
इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```

2023-10-16 18:45 UTC, Gauravpadam commented on content/hi/docs/tutorials/kubernetes-basics/explore/explore-interactive.html
> +                क्लस्टर बनाने के तरीके पर इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```suggestion
इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```

2023-10-16 18:45 UTC, Gauravpadam commented on content/hi/docs/tutorials/kubernetes-basics/expose/expose-interactive.html
> +                क्लस्टर बनाने के तरीके पर इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```suggestion
इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```

2023-10-16 18:45 UTC, Gauravpadam commented on content/hi/docs/tutorials/kubernetes-basics/scale/scale-interactive.html
> +                क्लस्टर बनाने के तरीके पर इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```suggestion
इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```

2023-10-16 18:45 UTC, Gauravpadam commented on content/hi/docs/tutorials/kubernetes-basics/update/update-interactive.html
> +                क्लस्टर बनाने के तरीके पर इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```suggestion
इंटरैक्टिव ट्यूटोरियल उपलब्ध नहीं है।
```

2023-12-07 04:06 UTC, divya-mohan0209 requested changes

2023-12-07 04:06 UTC, divya-mohan0209 commented on content/hi/docs/tutorials/hello-minikube.md
> +यह ट्यूटोरियल आपको मिनिक्यूब और काटाकोडा का उपयोग करते हुए कुबेरनेट्स पर एक साधारण ऐप चलाने का तरीका दिखाता है। ट्यूटोरियल एक कंटेनर छवि प्रदान करता है जो सभी अनुरोधों को प्रतिध्वनित करने के लिए NGIN
Doesn't reflect the current version of the Hello Minikube document

https://kubernetes.io/docs/tutorials/hello-minikube/.

Kindly make appropriate changes.

2024-01-09 17:32 UTC, utkarsh-singh1 commented
/hold cancel

2024-01-19 00:37 UTC, sftim commented
/retitle [hi] Remove Katacoda mentions in tutorials

2024-02-02 01:40 UTC, dipesh-rawat commented
Hey @utkarsh-singh1, just dropping a friendly note to see if you have the capacity to tackle this. This pull request requires a rebase against the main branch to resolve conflicts.

2024-02-06 08:09 UTC, utkarsh-singh1 commented
Hi @dipesh-rawat, I have rebased the branch and updated the PR.

2024-02-06 08:11 UTC, utkarsh-singh1 commented
Hi @divya-mohan0209, I have make changes to the PR can can you review it.

2024-05-06 13:21 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2024-06-10 18:29 UTC, utkarsh-singh1 commented
Hi @dipesh-rawat @divya-mohan0209, Are there any more changes required in the PR?

2024-06-11 03:41 UTC, divya-mohan0209 reviewed
/lgtm

2024-06-23 23:23 UTC, dipesh-rawat reviewed
Thanks for these changes!

/approve

2024-06-23 23:24 UTC, dipesh-rawat commented
/remove-label tide/merge-method-squash

2024-06-23 23:24 UTC, merged

2024-06-24 04:45 UTC, utkarsh-singh1 commented
Thanks @dipesh-rawat @divya-mohan0209 for the review.