Remove grpc container probe feature gate
kubernetes/website pull request #43552
Opened 2023-10-18 09:11 UTC by pacoxu

Since https://github.com/kubernetes/kubernetes/pull/120248 was merged for v1.29.

https://github.com/kubernetes/website/blob/63b39839b87d4dea04624d8fbbadd1ac55f28ff2/content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md#L73-L76
- should we remove this part as well?

2023-10-18 09:58 UTC, Shubham82 requested changes

2023-10-18 09:58 UTC, Shubham82 commented on content/en/docs/reference/command-line-tools-reference/feature-gates-removed.md
> +| `GRPCContainerProbe` | `true` | GA | 1.27 | 1.29 |
```suggestion
| `GRPCContainerProbe` | `true` | GA | 1.27 | 1.28 |
```

2023-10-18 10:00 UTC, Shubham82 commented
/sig node

2023-10-18 10:33 UTC, tengqm commented
/lgtm
Not sure if we want to change the old blog.
I'm supportive to this change.

2023-10-18 10:38 UTC, pacoxu commented on content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +yourself, and there are many [tools available](/docs/tasks/tools/).
May need revert the change here.

2023-10-19 06:31 UTC, pacoxu commented on content/en/blog/_posts/2022-05-13-grpc-probes-in-beta.md
> +yourself, and there are many [tools available](/docs/tasks/tools/).
Reverted here.

2023-10-19 09:22 UTC, merged