Fix varies of style issues for community page
kubernetes/website pull request #43740
Opened 2023-10-30 09:25 UTC by nekomeowww

## Changes

1. Fixed overflowed line through of headings, use a better solution to achieve the same effect
2. Adjusted the font size of headings when in smaller screens, it was way too big for mobile devices and reduces readability
3. Added paddings for the Recent News section, it used to have no paddings and looks weird
4. Adjusted the navigation anchor links for sections, the button style was way too big and not harmony with the rest of the design pattern
5. Added comments for blocks
6. Make it more consistent for paddings, margins and other styles for each of the sections
7. Fixed the entangled styles with the size of view ports, make it more smoother when resizes
8. Remove hard-coded paddings and margins
9. Added max-width for Tweets section to prevent it from being too wide

## Previous

### Desktop

<img width="1331" alt="image" src="https://github.com/kubernetes/website/assets/11081491/b40a543b-3ffe-4ce3-85f2-e061a40a377f">
<img width="1449" alt="image" src="https://github.com/kubernetes/website/assets/11081491/db6bfff8-11aa-4bcc-bde3-8c3d25a8b9be">
<img width="1399" alt="image" src="https://github.com/kubernetes/website/assets/11081491/6d8e24a9-2e70-429e-ab1e-660283fc0209">

### Mobile

<img width="414" alt="image" src="https://github.com/kubernetes/website/assets/11081491/daf51883-495c-4ed1-8f48-3d42ab9e6ffa">
<img width="414" alt="image" src="https://github.com/kubernetes/website/assets/11081491/76e3230c-2c70-4da2-a1f5-f134bcefbcbb">
<img width="414" alt="image" src="https://github.com/kubernetes/website/assets/11081491/9f7627a5-fce5-4bc4-b257-8700c511ae52">

## After

### Desktop

<img width="1331" alt="image" src="https://github.com/kubernetes/website/assets/11081491/56abb418-2109-479f-bf75-c878c1f091d4">
<img width="1331" alt="image" src="https://github.com/kubernetes/website/assets/11081491/f0db66e6-d76b-4050-a05a-08f61999fcdd">

### Mobile

<img width="414" alt="image" src="https://github.com/kubernetes/website/assets/11081491/53e0b686-7c3f-49bd-b72a-66a328392167">
<img width="414" alt="image" src="https://github.com/kubernetes/website/assets/11081491/46248615-74a4-43d7-aaf9-3a5f50c50f69">

2023-10-30 10:58 UTC, dipesh-rawat commented
/area web-development

2023-10-30 11:02 UTC, dipesh-rawat reviewed
Based on the quick look of the [Preview Page](https://deploy-preview-43740--kubernetes-io-main-staging.netlify.app/community/), this looks like an improvement!
LGTM

[Preview Community Page](https://deploy-preview-43740--kubernetes-io-main-staging.netlify.app/community/)

2023-10-30 15:05 UTC, Gauravpadam reviewed
LGTM

A significant improvement! Thanks for this PR

2023-10-30 15:12 UTC, Gauravpadam commented
@nekomeowww while we're at it, I can see some more improvements we can make (only if you wish to make them)

- The navigation items can be centred (with or without media queries)
- There's some persistent horizontal scrolling, If you can possibly target that?

Rest all good, Thanks again

2023-10-30 15:35 UTC, nekomeowww commented
> @nekomeowww while we're at it, I can see some more improvements we can make (only if you wish to make them)
> 
> 
> 
> - The navigation items can be centred (with or without media queries)
> 
> - There's some persistent horizontal scrolling, If you can possibly target that?
> 
> 
> 
> Rest all good, Thanks again
> 
> 

Absolutely! Although, it's a bit late for tonight in my time zone, I will tweak it and get it squashed and updated tomorrow ASAP.

2023-10-31 03:40 UTC, nekomeowww commented
> There's some persistent horizontal scrolling, If you can possibly target that?

Can you provide me some screenshot or steps to reproduce? On what size of the device are you experiencing  such horizontal scroll issue?

2023-10-31 04:27 UTC, Gauravpadam commented
I'm on a viewport of ~1600px width

> Is this the navigation items you talked about?
Correct, In smaller viewports, Flex can act up and break the alignment as so
![image](https://github.com/kubernetes/website/assets/12787482/b51b0ed2-af1a-428f-bb87-7b69b56e1509)

Perhaps some justify-content will help?

> 
![image](https://github.com/kubernetes/website/assets/12787482/f04d2001-eebd-4583-9b40-b2ef41cecb1f)

2023-10-31 04:39 UTC, nekomeowww commented
@Gauravpadam 

> Perhaps some justify-content will help?

Yes. Adjusted.

> ![](https://user-images.githubusercontent.com/12787482/279258075-f04d2001-eebd-4583-9b40-b2ef41cecb1f.png)

Interesting. I've tested all sorts of the viewports all the way from 4K to 720P with or without refreshes, I never got the overflow scroll like you did.

Do you know how to use devtools to point the elements? May I ask you to help me to find the overflow element that causes the scroll?

2023-10-31 04:46 UTC, Gauravpadam commented
> Do you know how to use devtools to point the elements? May I ask you to help me to find the overflow element that causes the scroll?

Sure, I'll try some tinkering and get back to you

2023-10-31 07:15 UTC, Gauravpadam reviewed
Addressing these should solve our problems

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
>    width: 100vw;
Either this OR auto, As per your liking
```suggestion
  width: 100%;
```

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
>    width: 100vw;
```suggestion
  width: 100%;
```

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
>    width: 100vw;
```suggestion
  width: 100%;
```

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
>    width: 100vw;
```suggestion
  width: 100%;
```

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
>    width: 100vw;
(OR auto)
```suggestion
  width: 100%;
```

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
>    width: 100vw;
```suggestion
  width: 100%;
```

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
> +  max-width: 100vw;
Let's stick with this
```suggestion
  max-width: 100%;
```

2023-10-31 07:15 UTC, Gauravpadam commented on static/css/community.css
>    flex-wrap: wrap;
Can we add a `justify-content:center` after line 77?

2023-10-31 11:40 UTC, Gauravpadam reviewed
Now that fits!

LGTM, Thanks for the good work @nekomeowww
(You'll have to wait a bit more for an approver's approval though)

2023-10-31 11:54 UTC, sftim commented
On a wide viewport, these changes make the menu list harder to read (very big gaps between items).

## Before

![Screenshot](https://github.com/kubernetes/website/assets/22591623/e102463a-105a-45c2-bc18-6d3eb80a1ec1)

---

## After

![Screenshot](https://github.com/kubernetes/website/assets/22591623/b229a2e2-8ebe-4c61-9759-bf91389f7fde)



_however_, I don't object if the changes are overall a benefit. What do other reviewers think?

2023-10-31 11:57 UTC, sftim commented
**Aside / doesn't block a merge**
The X (aka Twitter) content is a lot to scroll through; if we can shrink that and still have it useful, even better.

2023-10-31 13:26 UTC, nekomeowww commented
> On a wide viewport, these changes make the menu list harder to read (very big gaps between items).

@sftim  I agree with you. I should keep the padding around navigation items to prevent it being to wide to read. I will adjust it as suggested and make it more closer to the previous design.

2023-10-31 14:30 UTC, nekomeowww commented
> The X (aka Twitter) content is a lot to scroll through; if we can shrink that and still have it useful, even better.

@sftim I used the official support of height settings X (Twitter) to limit the height of the widget by setting the [`data-height` attribute](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview#customization). However, such change requires updates of all the localizations of the community page, if limit the height by overriding `height` property with CSS property, then the border of the widget will be lost. Not sure if this solution is acceptable.

2023-10-31 15:12 UTC, sftim commented
> I used the official support of height settings X (Twitter) to limit the height of the widget by setting the [`data-height` attribute](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview#customization). However, such change requires updates of all the localizations of the community page, if limit the height by overriding `height` property with CSS property, then the border of the widget will be lost. Not sure if this solution is acceptable.

Let's do that, but in a [separate](https://github.com/kubernetes/website/pull/43740#issuecomment-1787336097) PR. If we have to change all localizations at once, make one PR that crosses localizations (add a note to the PR description to explain the exception)

2023-10-31 15:39 UTC, nekomeowww commented
> Let's do that, but in a separate PR.

@sftim  Removed the changes that related to X (Twitter).

2023-11-17 03:39 UTC, nekomeowww commented
<img width="746" alt="image" src="https://github.com/kubernetes/website/assets/11081491/744dcf41-f3a6-4b7b-b630-7c1634699690">

Please note this "Nothing to see here - yet" empty list for Twitter (X) widget wasn't broke by either the related #43766 Pull Request and this Pull Request.

It is something the developer platform of Twitter (X) team should address and get fixed.

About the "Nothing to see here - yet" issue of Twitter (X) widget, there are two forums that are actively being used by community to report the incidents, read more and follow here:

- [Embedded Tweets Not Working - Publisher Tools / Twitter for Websites - Twitter Developers](https://twittercommunity.com/t/embedded-tweets-not-working/199477/56)
- [[Again] List Widget says “Nothing to see here - yet” if logged out - Publisher Tools / Twitter for Websites - Twitter Developers](https://twittercommunity.com/t/again-list-widget-says-nothing-to-see-here-yet-if-logged-out/198782/346)

2023-11-20 02:37 UTC, nekomeowww commented
@sftim @Gauravpadam Could you please take a review on this?

2023-12-05 01:36 UTC, aj11anuj requested changes
Layout break problem is already fixed for main website of this page even for smaller viewports. But all the changes and enhancements of this PR seems betterment of whole page. Just one thing, if you can increase the size of headings a bit for smaller viewports, then it will look better.

![Screenshot_2023-12-05-06-57-44-869_com android chrome](https://github.com/kubernetes/website/assets/116108975/874fe409-6947-44b0-822e-4ca4ae7251f6)

2023-12-05 07:34 UTC, nekomeowww commented
> Layout break problem is already fixed for main website of this page even for smaller viewports. But all the changes and enhancements of this PR seems betterment of whole page. Just one thing, if you can increase the size of headings a bit for smaller viewports, then it will look better.

Sure. No problem.

But which one does everyone prefer?

### Use `24px`

<img width="414" alt="image" src="https://github.com/kubernetes/website/assets/11081491/fdb52328-01aa-4fe7-bd09-4566758091ca">

### Use `28px`

<img width="414" alt="image" src="https://github.com/kubernetes/website/assets/11081491/639641e1-1fa8-4ff5-b7ca-f821b23c4ace">

2024-01-07 22:06 UTC, sftim commented
/approve

2024-01-07 22:11 UTC, merged