Add a clarification for autoscaling on minikube
kubernetes/website pull request #43808
Opened 2023-11-03 16:34 UTC by morhook

Added a very small clarification on how to run this guide on `minikube`.

2023-11-06 10:24 UTC, Shubham82 requested changes

2023-11-06 10:24 UTC, Shubham82 commented on content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +For enabling on minikube you can enable it with
```suggestion
If you are running {{< glossary_tooltip term_id="minikube" >}}, run the following command to enable metrics-server:
```

2023-11-06 10:25 UTC, Shubham82 commented on content/en/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough.md
> +For enabling on minikube you can enable it with
@morhook , Maybe adding something like this would be better.

2023-11-06 10:26 UTC, Shubham82 commented
/sig autoscaling

2023-11-07 19:59 UTC, morhook commented
> Welcome @morhook! It looks like this is your first PR to [kubernetes/website](https://github.com/kubernetes/website) 🎉. Please refer to our [pull request process documentation](https://git.k8s.io/community/contributors/guide/pull-requests.md) to help your PR have a smooth ride to approval. You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). You can also check if kubernetes/website has [its own contribution guidelines](https://github.com/kubernetes/website/tree/master/CONTRIBUTING.md). You may want to refer to our [testing guide](https://git.k8s.io/community/contributors/devel/sig-testing/testing.md) if you run into trouble with your tests not passing. If you are having difficulty getting your pull request seen, please follow the [recommended escalation practices](https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#why-is-my-pull-request-not-getting-reviewed). Also, for tips and tricks in the contribution process you may want to read the [Kubernetes contributor cheat sheet](https://git.k8s.io/community/contributors/guide/contributor-cheatsheet/README.md). We want to make sure your contribution gets all the attention it needs! Thank you, and welcome to Kubernetes. 😃

thanks to you @k8s-ci-robot ! Love to read you from Argentina  (🇦🇷 championsof the world on soccer for 2 more years!). I've been working on k8s for some time now and would love to continue helping on this awesome community and technology.

2023-11-08 09:25 UTC, Shubham82 commented
Thanks @morhook
Preview looks good to me.
https://deploy-preview-43808--kubernetes-io-main-staging.netlify.app/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#before-you-begin

/lgtm

2023-11-09 05:31 UTC, Shubham82 commented
@morhook It is not the label problem, once the PR gets `lgtm` label, you need the `approve`  label to merge the PR, and the approver approves the PR.

See the above comment from the bot: https://github.com/kubernetes/website/pull/43808#issuecomment-1792772785

2023-12-21 21:01 UTC, morhook commented
who can approve this PR?

2024-01-05 05:32 UTC, Shubham82 commented
cc @sftim 
If it seems good to you, please approve this PR.

Thanks

2024-01-05 09:22 UTC, sftim reviewed
Nice.

Thank you.

/approve

2024-01-05 09:26 UTC, merged