Corrected-Grammar-consistency-about-verb
kubernetes/website pull request #43804
Opened 2023-11-03 11:31 UTC by Ayush9026

**Description** -  Grammar consistency about verb form in singular and plural, whether to add an "s", in feature-gates docs #43795

solved this issue added "s" where needed.

2023-11-03 13:04 UTC, PranitRout07 commented
I suggest to change defaulting to default here . It is at line number 504 in feature-gates.md file.
<img width="545" alt="Screenshot 2023-11-03 182047" src="https://github.com/kubernetes/website/assets/102309095/3e1638f2-c1e8-4c5b-8e86-0d8bd1754a02">

Change 'fine-tuing' to 'fine-tuning' at line number 614 and line number 615.
<img width="616" alt="Screenshot 2023-11-03 182846" src="https://github.com/kubernetes/website/assets/102309095/d1c93fa9-6599-4a77-b940-da5ff4863755">

2023-11-04 06:18 UTC, amolmote reviewed
lgtm.

seems the change is necessary to have.

2023-11-04 06:20 UTC, amolmote commented
fix the checks and review the whole file again, do the possible changes that you can think valid to have.

2023-11-04 06:33 UTC, windsonsea reviewed
Are the addition of 's' in these cases necessary as well?

2023-11-04 06:33 UTC, windsonsea commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `AdmissionWebhookMatchConditions`: Enable [match conditions](/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions)
```suggestion
- `AdmissionWebhookMatchConditions`: Enables [match conditions](/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions)
```

2023-11-04 06:33 UTC, windsonsea commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `APISelfSubjectReview`: Activate the `SelfSubjectReview` API which allows users
```suggestion
- `APISelfSubjectReview`: Activates the `SelfSubjectReview` API which allows users
```

2023-11-04 06:33 UTC, windsonsea commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `CronJobsScheduledAnnotation`: Set the scheduled job time as an
```suggestion
- `CronJobsScheduledAnnotation`: Sets the scheduled job time as an
```

2023-11-20 06:58 UTC, Ritikaa96 requested changes

2023-11-20 06:58 UTC, Ritikaa96 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `ConsistentHTTPGetHandlers`: Normalize HTTP get URL and Header passing for lifecycle
```suggestion
- `ConsistentHTTPGetHandlers`: Normalizes HTTP get URL and Header passing for lifecycle
```

2023-11-20 06:58 UTC, Ritikaa96 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `CRDValidationRatcheting`: Enable updates to custom resources to contain
```suggestion
- `CRDValidationRatcheting`: Enables updates to custom resources to contain 
```

2023-11-20 06:58 UTC, Ritikaa96 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +- `EventedPLEG`: Enablse support for the kubelet to receive container life cycle events from the
```suggestion
- `EventedPLEG`: Enables support for the kubelet to receive container life cycle events from the
```

2023-11-20 06:58 UTC, Ritikaa96 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `KubeProxyDrainingTerminatingNodes`: Implement connection draining for
```suggestion
- `KubeProxyDrainingTerminatingNodes`: Implements connection draining for
```

2023-11-20 06:58 UTC, Ritikaa96 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `KubeletPodResources`: Enable the kubelet's pod resources gRPC endpoint. See
```suggestion
- `KubeletPodResources`: Enables the kubelet's pod resources gRPC endpoint. See
```

2023-11-20 06:58 UTC, Ritikaa96 commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
>  - `UserNamespacesSupport`: Enable user namespace support for Pods.
```suggestion
- `UserNamespacesSupport`: Enables user namespace support for Pods.
```

2023-11-20 07:02 UTC, Ritikaa96 commented
Hi @Ayush9026 , there are more grammatical errors in this doc , can you again review and correct them:
For eg . 
`Feature gates are a set of **key=value** pairs that describe Kubernetes features`
should be
`Feature gates are a set of key-value pairs that describe Kubernetes features`

2023-11-20 07:07 UTC, Ritikaa96 commented
Hi @Ayush9026 Please resolve the conflicts.

2024-01-21 21:17 UTC, natalisucks commented
@Ayush9026 Hi there! With the inactivity on this PR when it comes to following up on feedback, I'll be closing it. However, please feel free to come back and open this PR when you have the capacity to work on it once again. Thank you!
/close

2024-01-21 21:17 UTC, closed without merging

2024-03-24 06:46 UTC, Ayush9026 commented
/ open