Fix KinD typos in en docs.
kubernetes/website pull request #43828
Opened 2023-11-06 08:19 UTC by yanggangtony

Fix ```KinD``` typos in en docs.
There are somes show Kind , and somes not Kind.
Review the website of kind [kind quick start](https://kind.sigs.k8s.io/docs/user/quick-start/). 

It is maybe Kind is rightness.

2023-11-06 08:33 UTC, Gauravpadam commented
For reference, PR #43250 was merged a while ago, Which accepted `kind` (all lowercase).

I leave it to the approvers to decide whether it should be `KinD`, `Kind` or `kind`.
My preference would incline with `KinD`

2023-11-06 09:15 UTC, sftim commented
I checked https://kind.sigs.k8s.io/, which writes kind as “kind”.

/priority awaiting-more-evidence

2023-11-06 09:16 UTC, sftim commented
/remove-priority awaiting-more-evidence

2023-11-06 09:16 UTC, sftim requested changes
Please write kind as “kind”, all-lowercase.

2023-11-06 09:16 UTC, sftim commented on content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
> +New to Windows 10 and WSL2, or new to Docker and Kubernetes? Welcome to this blog post where we will install from scratch Kubernetes in Docker [Kind](https://kind.sigs.k8s.io/) and [Minikube](https:/
`kind`, please.

2023-11-06 10:01 UTC, sftim commented
/retitle Fix KinD typos in en docs

2023-11-06 10:41 UTC, yanggangtony commented on content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
> +New to Windows 10 and WSL2, or new to Docker and Kubernetes? Welcome to this blog post where we will install from scratch Kubernetes in Docker [Kind](https://kind.sigs.k8s.io/) and [Minikube](https:/
Thanks for quick review.
Rebased.

2023-11-06 10:43 UTC, yanggangtony commented
wait review, still a litter chang to go.

2023-11-06 10:51 UTC, tengqm commented on content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
> +New to Windows 10 and WSL2, or new to Docker and Kubernetes? Welcome to this blog post where we will install from scratch Kubernetes in Docker [Kind](https://kind.sigs.k8s.io/) and [Minikube](https:/
Still not changed?

2023-11-06 10:51 UTC, tengqm commented
/lgtm

2023-11-06 10:59 UTC, yanggangtony commented on content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
> +New to Windows 10 and WSL2, or new to Docker and Kubernetes? Welcome to this blog post where we will install from scratch Kubernetes in Docker [Kind](https://kind.sigs.k8s.io/) and [Minikube](https:/
Rebased now.

2023-11-06 12:23 UTC, windsonsea commented
/lgtm

2023-11-06 20:37 UTC, nate-double-u commented on content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
+1

2023-11-06 21:58 UTC, yanggangtony commented
@sftim 
So your suggestion is like that .
>>For old blog articles, we should only change them if the authors agree (even for small fixups).
```
content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
content/en/blog/_posts/2021-06-21-writing-a-controller-for-pod-labels.md
content/en/blog/_posts/2021-12-09-pod-security-admission-beta.md
```
revert this changed.

Just changed the file 
```
content/en/blog/_posts/2020-08-26-kubernetes-release-1.19.md
content/en/docs/tutorials/security/ns-level-pss.md
```

2023-11-07 03:19 UTC, kumarankit999 commented on content/en/blog/_posts/2020-05-21-wsl2-dockerdesktop-k8s.md
+1

2023-11-08 22:15 UTC, yanggangtony commented
Thanks @sftim 
your suggest is right. Rebased. 
Now , we will not dirty the blogs without the agressment by its authors.

2023-11-09 09:41 UTC, merged