[es] Add concepts/storage/windows-storage.md
kubernetes/website pull request #43820
Opened 2023-11-04 20:53 UTC by edithturn

Se añadió la documentación en español para las sección: content/es/docs/concepts/storage/windows-storage.md
Agradecería puedan revisarlo y darme feedback. Wohoo!!!! 🕺🏼 

Gracias! :)

2023-11-06 15:59 UTC, ramrodo commented on content/es/docs/concepts/storage/windows-storage.md
> +Esta página proporciona una descripción general del almacenamiento específica para el sistema operativo Windows.
Creo que la referencia de _specific_ al traducirla al Español hace referencia más al término de _almacenamiento_:

```suggestion
Esta página proporciona una descripción general del almacenamiento específico para el sistema operativo Windows.
```

2023-11-06 16:00 UTC, ramrodo commented on content/es/docs/concepts/storage/windows-storage.md
> +## Persistent storage {#storage}
```suggestion
## Almacenamiento persistente {#storage}
```

2023-11-06 16:02 UTC, ramrodo commented on content/es/docs/concepts/storage/windows-storage.md
> +Kubernetes {{< glossary_tooltip text="volúmenes" term_id="volume" >}} habilita la implementación de aplicaciones complejas, con requisitos de persistencia de datos y uso compartido de volúmenes de Po
```suggestion
Los {{< glossary_tooltip text="volúmenes" term_id="volume" >}} de Kubernetes habilitan la implementación de aplicaciones complejas, con requisitos de persistencia de datos y uso compartido de volúmenes de Pod, en Kubernetes.
```

2023-11-06 16:06 UTC, ramrodo commented on content/es/docs/concepts/storage/windows-storage.md
> +La gestión de volúmenes persistentes asociados a un backend o protocolo de almacenamiento específico incluye acciones como la provisión/desprovisión/redimensión de volúmenes, la conexión/desconexión
```suggestion
La gestión de volúmenes persistentes asociados a un backend o protocolo de almacenamiento específico incluye acciones como la provisión/desprovisión/redimensión de volúmenes, la conexión/desconexión de un volumen de/para un nodo de Kubernetes, y el montaje/desmontaje de un volumen de/para contenedores individuales en un Pod que necesita persistir datos.
```

2023-11-06 16:14 UTC, ramrodo commented on content/es/docs/concepts/storage/windows-storage.md
> +Los componentes de gestión de volúmenes se envían como volumen de Kubernetes [plugin](/docs/concepts/storage/volumes/#volume-types).
Ésta traducción de _plugin_ se me complica colocarla para que tenga buen sentido, pero creo que podría ser:

```suggestion
Los componentes de gestión de volúmenes se envían como [plugin](/docs/concepts/storage/volumes/#volume-types) de volumen de Kubernetes.
```

Aquí está el [Volume plugin FAQ](https://github.com/kubernetes/community/blob/master/sig-storage/volume-plugin-faq.md) para más contexto y apoyo a la traducción.

Igual otra duda sería si manejar `plugin` o `complemento`...
\cc @electrocucaracha @krol3

2023-11-06 16:16 UTC, ramrodo commented on content/es/docs/concepts/storage/windows-storage.md
> +  - Tenga en cuenta que los FlexVolumes han sido descontinuados a partir de la versión 1.23.
```suggestion
  - Ten en cuenta que los FlexVolumes han sido descontinuados a partir de la versión 1.23.
```

2023-11-06 16:16 UTC, ramrodo requested changes
Thanks!
Some minor suggestions were given.

2023-11-06 16:17 UTC, ramrodo commented
/assign @electrocucaracha @krol3

2023-11-08 09:40 UTC, edithturn commented on content/es/docs/concepts/storage/windows-storage.md
> +Los componentes de gestión de volúmenes se envían como volumen de Kubernetes [plugin](/docs/concepts/storage/volumes/#volume-types).
Se lee definitivamente mejor, Rodolfo!
Estoy de acuerdo con esa traducción :)

2023-11-14 19:36 UTC, ramrodo commented
/retest

2023-11-15 16:39 UTC, ramrodo commented
/retest

2023-11-15 16:42 UTC, ramrodo commented on content/es/docs/concepts/storage/windows-storage.md
> +Los componentes de gestión de volúmenes se envían como volumen de Kubernetes [plugin](/docs/concepts/storage/volumes/#volume-types).
Hola @edithturn, creo que solo faltó ésta sugerencia :)

2023-11-15 16:42 UTC, ramrodo reviewed
Solo una sugerencia pendiente.

2023-11-17 09:26 UTC, edithturn commented
> Solo una sugerencia pendiente.

Se me fue, muchas gracias! :)

2023-11-17 23:17 UTC, electrocucaracha commented on content/es/docs/concepts/storage/windows-storage.md
> +Los siguientes complementos incorporados admiten almacenamiento persistente en nodos de Windows:
Me parece que `plugin` no debería ser traducido.

```suggestion
Los componentes de gestión de volúmenes se envían como [plugin](/docs/concepts/storage/volumes/#volume-types) de volumen de Kubernetes.
Las siguiente variedad de clases de plugins de volumen de Kubernetes son compatibles en Windows:

- [`FlexVolume plugins`](/docs/concepts/storage/volumes/#flexvolume)

  - Ten en cuenta que los FlexVolumes han sido descontinuados a partir de la versión 1.23.

- [`CSI Plugins`](/docs/concepts/storage/volumes/#csi)

##### Plugins de volumen incorporados

Los siguientes plugins incorporados admiten almacenamiento persistente en nodos de Windows:
```

2023-11-20 00:44 UTC, electrocucaracha commented
/lgtm

2023-11-20 23:48 UTC, ramrodo commented
Great! Thanks @edithturn 
/lgtm
/approve

2023-11-20 23:52 UTC, merged

2023-11-21 08:57 UTC, edithturn commented
> Great! Thanks @edithturn /lgtm /approve

Wohoo! Thank youuu!!!