Merged main dev 1.29
kubernetes/website pull request #43908
Opened 2023-11-13 15:56 UTC by katcosgrove

Merging main into dev-1.29 to maintain branch sync

2023-11-13 16:10 UTC, reylejano commented
clean sync
/approve

2023-11-14 09:42 UTC, sftim requested changes
Thanks

/hold

Please remove the merge conflicts (squashing them out), and force-push. Or make an equivalent change.

2023-11-14 09:42 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +  the pod template of [Job](/docs/concepts/workloads/controllers/job/).
Doesn't look right.

2023-11-14 09:42 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +>>>>>>> upstream/main
Doesn't look right.

2023-11-14 09:42 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +>>>>>>> upstream/main
Doesn't look right.

2023-11-14 09:42 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +>>>>>>> upstream/main
Doesn't look right.

2023-11-14 09:42 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates.md
> +>>>>>>> upstream/main
Doesn't look right.

2023-11-14 09:42 UTC, sftim commented
/approve cancel

with https://github.com/kubernetes/website/pull/43908#pullrequestreview-1729317170 in mind. OK to re-approve once this has an appropriate LGTM.

2023-11-14 18:44 UTC, sftim commented
/retitle Merge main branch into dev-1.29

2023-11-14 18:46 UTC, sftim commented
@katcosgrove could you squash the latest commit into its (merge commit) parent? Let us know if you've a concern around doing this.

Reason: the feature gates file is one we try to be extra nice about as merge conflicts there are a frustration (which you've kinda seen).

2023-11-14 21:05 UTC, katcosgrove commented
Closing this and re-doing due to git being haunted and that being faster than unraveling the problem

2023-11-14 21:05 UTC, closed without merging