adding page manifest.md
kubernetes/website pull request #43967
Opened 2023-11-16 16:37 UTC by julialamenza

2023-11-16 16:52 UTC, stormqueen1990 commented
/retitle [pt-br] Add docs/reference/glossary/manifest.md

2023-11-16 17:43 UTC, edsoncelio commented
/cc

2023-11-16 17:48 UTC, edsoncelio requested changes
Hey @julialamenza!
Thanks for the contribution! 
Just a few (small) changes :)

2023-11-16 17:48 UTC, edsoncelio commented on content/pt-br/docs/reference/glossary/manifest.md
> +  Uma especificação serializada de um ou mais objetos da API Kubernetes.
"API Kubernetes" can be "API do Kubernetes"

2023-11-16 17:48 UTC, edsoncelio commented on content/pt-br/docs/reference/glossary/manifest.md
> + Especificação de um objeto da API Kubernetes em formato JSON ou YAML.
"API Kubernetes" can be "API do Kubernetes"

2023-12-16 18:34 UTC, edsoncelio commented
Thanks @julialamenza!
/lgtm
PTAL @stormqueen1990

2023-12-18 02:06 UTC, stormqueen1990 reviewed
Thanks for your contribution, @julialamenza! 🎉

/approve

2023-12-18 02:07 UTC, stormqueen1990 commented
/label tide/merge-method-squash

2023-12-18 02:13 UTC, merged