Update trouble shooting to include the issue of etcd upgrade
kubernetes/website pull request #44058
Opened 2023-11-23 10:22 UTC by chendave

For the isse which is reported recently: https://github.com/kubernetes/kubeadm/issues/2957 We'd better to provide some tips to workaround this known issue.

related: https://github.com/kubernetes/kubeadm/issues/2957

2023-11-23 10:23 UTC, chendave commented
cc @sftim @neolit123

2023-11-23 10:44 UTC, neolit123 reviewed
/lgtm

2023-11-23 10:44 UTC, neolit123 commented
/sig cluster-lifecycle

2023-11-24 05:02 UTC, Ritikaa96 requested changes

2023-11-27 02:09 UTC, chendave commented
this was based on dev-1.29 branch (https://github.com/kubernetes/website/pull/43903), and was suggested by @sftim to base on the main branch.

> We're not using dev-1.28 any more as v1.28 is released. This PR should target main.

2023-11-27 06:45 UTC, neolit123 reviewed
/lgtm

2023-11-27 10:06 UTC, merged