Add 1.29 to release schedule for 1.29 release
kubernetes/website pull request #44135
Opened 2023-11-29 14:13 UTC by katcosgrove

This PR adds 1.29 to the releases schedule for the 1.29.0 release.

/milestone 1.29
/cc @jimangel @marosset @Priyankasaggu11929

2023-11-29 14:16 UTC, Priyankasaggu11929 commented
cc: @kubernetes/release-managers

2023-11-29 15:21 UTC, sftim commented
/approve

2023-11-30 12:22 UTC, sftim commented
> It's a bit odd that we then use past tense for a future date

This is a preview of what people will see post-release.
When we release Kubernetes 1.29, the release will be in the past.

When reviewing, imagine that the release has already happened.

2023-12-11 14:59 UTC, xmudrii requested changes

2023-12-11 14:59 UTC, xmudrii commented on data/releases/schedule.yaml
> +  endOfLifeDate: 2026-02-28
These dates are off for one year
```suggestion
  maintenanceModeStartDate: 2024-12-28
  endOfLifeDate: 2025-02-28
```

2023-12-11 15:06 UTC, xmudrii approved these changes
/lgtm
/approve

2023-12-11 15:11 UTC, merged