[zh-cn] sync releases/patch-releases
kubernetes/website pull request #44186
Opened 2023-12-02 14:06 UTC by my-git9

content/zh-cn/releases/patch-releases.md

2023-12-03 16:35 UTC, 1000Delta requested changes
LGTM

You can help to fix the month of release.

2023-12-03 16:35 UTC, 1000Delta commented on content/zh-cn/releases/patch-releases.md
> +| 2023 年 11 月 | 2023-12-15          | 2023-12-19  |
```suggestion
| 2023 年 12 月 | 2023-12-15          | 2023-12-19  |
```

2023-12-04 07:13 UTC, utkarsh-singh1 commented
Seems to be a Netlify issue that timeout before build is complete, A simple empty commit may fix this issue.

2023-12-05 00:20 UTC, tengqm commented
/lgtm

2023-12-05 02:28 UTC, 1000Delta commented
/lgtm

Thanks!

2023-12-05 04:35 UTC, windsonsea commented
/approve

2023-12-05 04:38 UTC, merged