[es] localize content/en/docs/tasks/run-application/delete-stateful-set.md to Spanish
kubernetes/website pull request #44249
Opened 2023-12-07 13:48 UTC by gamba47

This is a Feature Request related to #41878 

What would you like to be added
Localize content/en/docs/tasks/run-application/delete-stateful-set.md to Spanish

Why is this needed
There is no Spanish localization for this file.

2023-12-07 13:49 UTC, gamba47 commented
/assing @ramrodo

2023-12-14 01:24 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Esta página muestra como se debe eliminar un {{< glossary_tooltip term_id="StatefulSet" >}}.
Ver referencia en [ésta página de la RAE](https://www.rae.es/espanol-al-dia/tilde-en-que-cuales-quienes-como-cuan-cuantoaosas-cuando-donde-y-adonde).

```suggestion
Esta página muestra cómo se debe eliminar un {{< glossary_tooltip term_id="StatefulSet" >}}.
```

2023-12-14 01:24 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +- Se asume que se tiene una aplicación del tipo StatefulSet corriendo en su clúster.
```suggestion
- Se asume que se tiene una aplicación del tipo StatefulSet corriendo en tu clúster.
```

2023-12-14 01:24 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Use el comando `kubectl delete` y especifique el StatefulSet, usando su nombre o el archivo con el que fue creado.
```suggestion
Usa el comando `kubectl delete` y especifica el StatefulSet, usando tu nombre o el archivo con el que fue creado.
```

2023-12-14 01:25 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Puede suceder que necesite eliminar los servicios headless asociados después de eliminar el StatefulSet.
```suggestion
Puede suceder que necesites eliminar los servicios headless asociados después de eliminar el StatefulSet.
```

2023-12-14 01:25 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Todos los Pods que eran parte de esta carga de trabajo son eliminados. Si usted quiere eliminar
```suggestion
Todos los Pods que eran parte de esta carga de trabajo son eliminados. Si tú quieres eliminar
```

2023-12-14 01:25 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +solo el StatefulSet y no los Pods utilice `--cascade=orphan`. Por ejemplo:
```suggestion
solo el StatefulSet y no los Pods utiliza `--cascade=orphan`. Por ejemplo:
```

2023-12-14 01:28 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +after claim deletion.
Aquí se fue un TODO:

```suggestion
y la política de reclamo. #TODO Nunca debes asumir la capacidad de acceder a un volumen
después de la eliminación del claim.
```

2023-12-14 01:28 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Tenga cuidado al borrar un PVC ya que puede llevar una pérdida de datos.
```suggestion
Ten cuidado al borrar un PVC ya que puede llevar una pérdida de datos.
```

2023-12-14 01:30 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +sustituya la misma por su propia etiqueta.
```suggestion
sustituye la misma por tu propia etiqueta.
```

2023-12-14 01:30 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Si encuentra algún pod bloqueado en su StatefulSet en el estado 'Terminating'
```suggestion
Si encuentras algunos pods bloqueados en tu StatefulSet en el estado 'Terminating'
```

2023-12-14 01:31 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +o 'Unknow' por un largo período de tiempo, puede ser que necesite intervenir
```suggestion
o 'Unknown' por un largo período de tiempo, puede ser que necesites intervenir
```

2023-12-14 01:31 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +manualmente para forzar la eliminación del pod del apiserver.
```suggestion
manualmente para forzar la eliminación de los pods del apiserver.
```

2023-12-14 01:31 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Esta es una tarea potencialmente riesgosa. Visite [Forzar eliminación de Pods en StatefulSet](/docs/tasks/run-application/force-delete-stateful-set-pod/)
```suggestion
Ésta es una tarea potencialmente riesgosa. Visita [Forzar eliminación de Pods en StatefulSet](/docs/tasks/run-application/force-delete-stateful-set-pod/)
```

2023-12-14 01:31 UTC, ramrodo commented on content/es/docs/tasks/run-application/delete-stateful-set.md
> +Aprenda más sobre [Forzar eliminación de Pods en StatefulSet](/docs/tasks/run-application/force-delete-stateful-set-pod/).
```suggestion
Aprende más sobre [Forzar eliminación de Pods en StatefulSet](/docs/tasks/run-application/force-delete-stateful-set-pod/).
```

2023-12-14 01:32 UTC, ramrodo requested changes
¡Gracias!

Unos comentarios sugeridos.

2023-12-14 22:07 UTC, gamba47 commented
Comentarios aceptados, muchas gracias.

2023-12-15 17:09 UTC, ramrodo commented
¡Gracias!
/lgtm

2023-12-15 17:09 UTC, ramrodo commented
/retest

2023-12-15 17:11 UTC, ramrodo commented
/ok-to-test

2023-12-15 17:14 UTC, ramrodo commented
/retest

2023-12-15 17:17 UTC, ramrodo commented
/test all

2023-12-16 17:01 UTC, ramrodo commented
/retest

2023-12-19 18:44 UTC, ramrodo commented
/lgtm

2023-12-19 18:44 UTC, ramrodo commented
/cc @krol3 @electrocucaracha

2023-12-19 18:57 UTC, krol3 approved these changes
@gamba47 Nice work :) Thanks
/approved

2023-12-19 19:02 UTC, merged