RFC 1035 vs RFC 1123: clarify the difference
kubernetes/website pull request #44245
Opened 2023-12-07 03:42 UTC by skissane

Add a paragraph explaining what is the difference between RFC 1035
and RFC 1123 labels.

Before this change, the documentation just listed the requirements for
each type of label, which meant the reader had to use their brain to
work out for themselves what the difference actually is. This takes time
and mental load. It is better that the documentation explicitly state
what the actual difference is, so the reader doesn't have to do that.

It will also hopefully reduce the future incidence of people logging
issues due to being confused about the difference between them,
see for example: https://github.com/kubernetes/kubernetes/issues/116964

2023-12-11 07:27 UTC, Shubham82 requested changes

2023-12-11 07:27 UTC, Shubham82 commented on content/en/docs/concepts/overview/working-with-objects/names.md
> +The only difference between the RFC 1035 and RFC 1123
```suggestion
{{< note >}}
The only difference between the RFC 1035 and RFC 1123
```

2023-12-11 07:27 UTC, Shubham82 commented on content/en/docs/concepts/overview/working-with-objects/names.md
> +with a lowercase alphabetic character only.
```suggestion
with a lowercase alphabetic character only.
{{< /note >}}
```

2023-12-11 07:29 UTC, Shubham82 commented
@skissane, it will be good, if we can put this as a note so that it will be more highlighted.

2023-12-13 23:25 UTC, skissane commented
@Shubham82 I accept your suggestion, thank you

2023-12-14 08:20 UTC, reylejano commented
/lgtm

2023-12-14 08:26 UTC, merged