[hi] Added content/hi/docs/concepts/architecture/_index.md
kubernetes/website pull request #44257
Opened 2023-12-07 21:20 UTC by akash-kumar-saw

Issue Number #39548

Localized en/docs/concepts/architecture/_index.md in hindi language :)

2024-01-14 01:06 UTC, dipesh-rawat commented on content/hi/docs/concepts/architecture/_index.md
> +
It seems that the localization of this file may be incomplete. There is a diagram included in the `{{ <figure> }} ` shortcode in the English file _[(check it out on Line 8)](https://github.com/kubernetes/website/blob/17f080049278a691d417c44decddbdb297f744b5/content/en/docs/concepts/architecture/_index.md?plain=1)_ that should be incorporated into this Hindi file here.

2024-02-12 06:09 UTC, utkarsh-singh1 commented on content/hi/docs/concepts/architecture/_index.md
> +{{< figure src="/images/docs/kubernetes-cluster-architecture.svg" alt="Components of Kubernetes" caption="Kubernetes cluster architecture" class="diagram-large" >}}
Hi @akash-kumar-saw, can you localize caption into Hindi.

2024-02-12 06:10 UTC, utkarsh-singh1 commented on content/hi/docs/concepts/architecture/_index.md
> +{{< figure src="/images/docs/kubernetes-cluster-architecture.svg" alt="Components of Kubernetes" caption="Kubernetes cluster architecture" class="diagram-large" >}}
```suggestion
{{< figure src="/images/docs/kubernetes-cluster-architecture.svg" alt="Components of Kubernetes" caption="कुबेरनेट्स क्लस्टर आर्किटेक्चर" class="diagram-large" >}}
```

2024-03-30 14:55 UTC, divya-mohan0209 requested changes
Hello @akash-kumar-saw : Please advise if you have the bandwidth to localise the caption into Hindi?

2024-07-11 12:36 UTC, divya-mohan0209 commented
@akash-kumar-saw Since there has been no response/activity on this PR, we'll be closing it. If you have the bandwidth to continue work on this PR, please feel free to reopen the PR and let us know.
/close

2024-07-11 12:36 UTC, closed without merging