updated hindi readme file
kubernetes/website pull request #44366
Opened 2023-12-14 14:51 UTC by haripriya9647

#41989

2023-12-14 14:58 UTC, dipesh-rawat commented
/retitle [hi] Update Hindi readme file

2023-12-14 14:58 UTC, dipesh-rawat commented
/language hi

2023-12-20 14:42 UTC, haripriya9647 commented
@divya-mohan0209 requesting your suggestions

2024-01-03 14:11 UTC, aj11anuj commented on README-hi.md
> +अगर आप इस रिपॉजिटरी की एक अपनी copy बनाना चाहते हैं, तो स्क्रीन के ऊपरी-दाएँ क्षेत्र में **Fork** बटन पर क्लिक करें। इसको हम Fork कहते हैं, जो आपकी खुद की एक नई copy होती है। जब आप इस fork में कुछ बद
```suggestion
अगर आप इस रिपॉजिटरी की एक copy बनाना चाहते हैं, तो स्क्रीन के ऊपरी-दाएँ क्षेत्र में **Fork** बटन पर क्लिक करें। इसको हम Fork कहते हैं, जो आपकी खुद की एक नई copy होती है। जब आप इस fork में कुछ बदलाव करके हमें भेजने के लिए तैयार हो जाएं, तो अपने fork पर जाएं और एक नया pull request बनाएं, ताकि हमें आपके किए गए परिवर्तन के बारे में पता चल सके।
```

2024-01-03 14:16 UTC, aj11anuj commented on README-hi.md
> +एक बार जब आपका pull request तैयार हो जाता है, तो हमारे कुबरनेट्स समीक्षक आपके सुझाव और प्रतिक्रिया को ध्यान से देखेंगे। आपकी pull request की मालिकी के रूप में, **यह आपकी जिम्मेदारी है कि आप हमारे समी
```suggestion
एक बार जब आपका pull request तैयार हो जाता है, तो हमारे कुबरनेट्स समीक्षक आपके सुझाव और प्रतिक्रिया को ध्यान से देखेंगे। आपकी pull request की मालिकी के रूप में, **यह आपकी जिम्मेदारी है कि आप हमारे समीक्षकों द्वारा दी गई प्रतिक्रिया का उचित रूप से संबोधित करने के लिए अपनी पुल रिक्वेस्ट को संशोधित करेंगे। हम साथ में काम करेंगे ताकि हमारा कोड सही और बेहतर हो सके।**
```

2024-01-03 14:24 UTC, aj11anuj commented on README-hi.md
> +यह भी ध्यान दें कि एक से अधिक कुबरनेट्स समीक्षक आपको प्रतिक्रिया देने के लिए आ सकते हैं या फिर आप एक समीक्षक से प्रतिक्रिया प्राप्त कर सकते हैं, जो मूल रूप से आपके पुल रिक्वेस्ट की जांच कर रहे हैं। इ
```suggestion
यह भी ध्यान दें कि एक से अधिक कुबरनेट्स समीक्षक आपको प्रतिक्रिया देने के लिए आ सकते हैं, जो मूल रूप से आपकी पुल रिक्वेस्ट की जांच करेंगे। इसके अलावा, कुछ मामलों में, आपको आपके प्रोजेक्ट के लिए [कुबेरनेट्स टेक्निकल समीक्षक](https://github.com/kubernetes/website/wiki/Tech-reviewers) से तकनीकी समीक्षा प्राप्त करने की आवश्यकता हो सकती है। समीक्षक समय पर प्रतिक्रिया देने की पूरी कोशिश करेंगे, लेकिन हम समझते हैं कि सभी के पास व्यस्तता होती है और परिस्थितियों के आधार पर प्रतिक्रिया में विलंब हो सकता है।
```

2024-01-03 14:27 UTC, aj11anuj commented on README-hi.md
>  ## स्थानीय रूप से डॉकर का उपयोग करके साइट चलाना
```suggestion
## स्थानीय रूप से डॉकर का उपयोग करके साइट चलायें
```

2024-01-03 14:29 UTC, aj11anuj commented on README-hi.md
> +कुबरनेट्स आपकी भागीदारी की कड़ी से जुड़ा हुआ है, और हम हमेशा आपके सहयोग के लिए आभारी हैं।
```suggestion
कुबरनेट्स सामुदायिक भागीदारी से बढ़ता है, और हम सचमुच हमारी साइट और प्रलेखन में आपके योगदान की सराहना करते हैं!

कुबरनेट्स आपकी भागीदारी की कड़ी से जुड़ा हुआ है, और हम हमेशा आपके सहयोग के लिए आभारी रहेंगे।
```

2024-01-03 14:30 UTC, aj11anuj commented on README-hi.md
> +कुबरनेट्स वेबसाइट को स्थानीय रूप से चलाने के लिए, हम आपको एक विशेष [डॉकर](https://docker.com) image का इस्तेमाल करने की सिफारिश करते हैं, जिसमें [Hugo](https://gohugo.io) स्टेटिक साइट जनरेटर शामिल है
```suggestion
कुबरनेट्स वेबसाइट को स्थानीय रूप से चलाने के लिए, हम आप से एक विशेष [डॉकर](https://docker.com) image को इस्तेमाल करने की सिफारिश करते हैं, जिसमें [Hugo](https://gohugo.io) स्टेटिक साइट जनरेटर शामिल है।
```

2024-01-03 14:34 UTC, aj11anuj commented on README-hi.md
> +अगर आप [डॉकर](https://www.docker.com/get-started) का इस्तेमाल कर रहे हैं, तो स्थानीय रूप से `कुबेरनेट्स-ह्यूगो` Docker image बनाने की कदमों को देखें:
```suggestion
अगर आप [डॉकर](https://www.docker.com/get-started) का इस्तेमाल कर रहे हैं, तो स्थानीय रूप से `Kubernetes-Hugo` Docker image बनाने की प्रक्रिया को देखें:
```

2024-01-03 14:35 UTC, aj11anuj requested changes
Some minor suggestions from my side

2024-03-25 15:17 UTC, sftim commented
Also see https://github.com/kubernetes/website/pull/45657

2024-03-30 14:04 UTC, divya-mohan0209 commented
@haripriya9647 : Please could you advise if you have the bandwidth to address the reviews suggested by Anuj?

2024-04-01 05:03 UTC, haripriya9647 commented
yes @divya-mohan0209 I will add commits by tonight

2024-04-02 14:43 UTC, sftim commented
Awaiting update from Hindi team (@haripriya9647)

2024-07-09 09:16 UTC, niranjandarshann commented
@haripriya9647 The changes looks good to me but  there is lack of  some consistency of using the Word `pull request` instead of using `पुल रिक्वेस्ट` . SomeWhere you use as `पुल रिक्वेस्ट` many where you used  `pull request`.

So use  `pull request ` in entire page.

2024-07-11 12:52 UTC, divya-mohan0209 requested changes
@haripriya9647 - The contents of [this file](https://github.com/kubernetes/website/blob/main/README.md) and the translated version don't match. This seems to be outdated & you will need to update the Hindi README to match the English one.

2024-07-11 12:52 UTC, divya-mohan0209 commented on README-hi.md
> +अगर आप इस रिपॉजिटरी की एक copy बनाना चाहते हैं, तो स्क्रीन के ऊपरी-दाएँ क्षेत्र में **Fork** बटन पर क्लिक करें। इसको हम Fork कहते हैं, जो आपकी खुद की एक नई copy होती है। जब आप इस fork में कुछ बदलाव क
Either pull request or the transliterated version, please.
```suggestion
अगर आप इस रिपॉजिटरी की एक copy बनाना चाहते हैं, तो स्क्रीन के ऊपरी-दाएँ क्षेत्र में **Fork** बटन पर क्लिक करें। इसको हम Fork कहते हैं, जो आपकी खुद की एक नई copy होती है। जब आप इस fork में कुछ बदलाव करके हमें भेजने के लिए तैयार है, तो अपने fork पर जाएं और एक नया pull request बनाएं, ताकि हमें आपके किए गए परिवर्तन के बारे में पता चल सके।
```

2024-07-11 12:52 UTC, divya-mohan0209 commented on README-hi.md
> +यह भी ध्यान दें कि एक से अधिक कुबरनेट्स समीक्षक आपको प्रतिक्रिया देने के लिए आ सकते हैं, जो मूल रूप से आपकी पुल रिक्वेस्ट की जांच करेंगे। इसके अलावा, कुछ मामलों में, आपको आपके प्रोजेक्ट के लिए [कुबेर
```suggestion
यह भी ध्यान दें कि एक से अधिक कुबरनेट्स समीक्षक मूल रूप से आपकी पुल रिक्वेस्ट की जांच कर सकते हैं और आपको प्रतिक्रिया दे सकते हैं। इसके अलावा, कुछ मामलों में, आपको आपके प्रोजेक्ट के लिए [कुबेरनेट्स टेक्निकल समीक्षक](https://github.com/kubernetes/website/wiki/Tech-reviewers) से तकनीकी समीक्षा प्राप्त करने की आवश्यकता हो सकती है। समीक्षक समय पर प्रतिक्रिया देने की पूरी कोशिश करेंगे, लेकिन हम समझते हैं कि सभी के पास व्यस्तता होती है और परिस्थितियों के आधार पर प्रतिक्रिया में विलंब हो सकता है।
```

2024-07-19 10:57 UTC, sftim commented
/area localization

2024-09-17 12:22 UTC, closed without merging