[zh] should be container not sandbox for `tasks/debug/debug-cluster/crictl`
kubernetes/website pull request #44448
Opened 2023-12-20 09:09 UTC by testwill

用 crictl 创建容器对容器运行时排错很有帮助。 在运行的 Kubernetes 集群中，沙盒会随机地被 kubelet 停止和删除
应改成 
用 crictl 创建容器对容器运行时排错很有帮助。 在运行的 Kubernetes 集群中，容器会随机地被 kubelet 停止和删除

2023-12-20 23:35 UTC, chenrui333 commented
/retitle should be container not sandbox for `tasks/debug/debug-cluster/crictl`

2023-12-20 23:36 UTC, chenrui333 commented
/retitle [zh] should be container not sandbox for `tasks/debug/debug-cluster/crictl`

2023-12-20 23:37 UTC, chenrui333 requested changes
correct me if I am wrong

this is the original text

> On a running Kubernetes cluster, the sandbox will eventually be stopped and
deleted by the Kubelet.

2023-12-20 23:37 UTC, chenrui333 commented
/hold

2024-01-09 09:40 UTC, windsonsea commented
IMO, you need to update the english upstream before changing the zh-cn text:

```
content/en/docs/tasks/debug/debug-cluster/crictl.md
```

Literally, the zh-cn text is consistent with the current en version.

/hold

2024-01-09 09:45 UTC, closed without merging