[en] Update go lang link common-parameters.md
kubernetes/website pull request #44479
Opened 2023-12-22 22:43 UTC by Arhell

2023-12-23 14:29 UTC, PranitRout07 reviewed
These changes are good . What are your thoughts changing these text font style to bold or italic , these changes will increase readability  of the page . 
<img width="679" alt="Screenshot 2023-12-23 195045" src="https://github.com/kubernetes/website/assets/102309095/4ec90987-148c-41f0-9d55-6cb7847cffbe">

2023-12-23 14:31 UTC, Arhell commented
> These changes are good . What are your thoughts changing these text font style to bold or italic , these changes will increase readability of the page . <img alt="Screenshot 2023-12-23 195045" width="679" src="https://private-user-images.githubusercontent.com/102309095/292631023-4ec90987-148c-41f0-9d55-6cb7847cffbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDIxMTIsIm5iZiI6MTcwMzM0MTgxMiwicGF0aCI6Ii8xMDIzMDkwOTUvMjkyNjMxMDIzLTRlYzkwOTg3LTE0OGMtNDFmMC05ZDU1LTZjYjc4NDdjZmZiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDI2NDRlZTE0YzRhNDhmOGY3YWYwNTljMWUwMzEyM2U3ZTEzOTk5NzcyYTdjZjM0M2RmNWNkOWMxMzcwZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WuQVfwKJNvWD2qmrFubQ26GaKjkktlAEwmiET7KBDOk">

No, this PR is only for replacing the link, if you want, take up your proposal.

2023-12-23 14:48 UTC, PranitRout07 commented
> > These changes are good . What are your thoughts changing these text font style to bold or italic , these changes will increase readability of the page . <img alt="Screenshot 2023-12-23 195045" width="679" src="https://private-user-images.githubusercontent.com/102309095/292631023-4ec90987-148c-41f0-9d55-6cb7847cffbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNDIxMTIsIm5iZiI6MTcwMzM0MTgxMiwicGF0aCI6Ii8xMDIzMDkwOTUvMjkyNjMxMDIzLTRlYzkwOTg3LTE0OGMtNDFmMC05ZDU1LTZjYjc4NDdjZmZiZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyM1QxNDMwMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDI2NDRlZTE0YzRhNDhmOGY3YWYwNTljMWUwMzEyM2U3ZTEzOTk5NzcyYTdjZjM0M2RmNWNkOWMxMzcwZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WuQVfwKJNvWD2qmrFubQ26GaKjkktlAEwmiET7KBDOk">
> 
> No, this PR is only for replacing the link, if you want, take up your proposal.

ok @Arhell .

2024-01-10 16:56 UTC, Ritikaa96 requested changes

2024-01-10 16:56 UTC, Ritikaa96 commented on content/en/docs/reference/kubernetes-api/common-parameters/common-parameters.md
> +fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https
```suggestion
fieldManager is a name associated with the actor or entity making these changes.
The value must be less than or 128 characters long and only contain printable
characters, as defined by https://pkg.go.dev/unicode#IsPrint.
```

2024-01-10 16:56 UTC, Ritikaa96 commented on content/en/docs/reference/kubernetes-api/common-parameters/common-parameters.md
> +fieldManager is a name associated with the actor or entity that is making these changes. The value must be less than or 128 characters long, and only contain printable characters, as defined by https
small nit . please wrap the lines.

2024-02-01 15:24 UTC, Ritikaa96 commented
/lgtm

2024-02-10 16:32 UTC, Arhell reviewed
/assign @sftim

2024-02-12 18:23 UTC, sftim commented
/unassign
I'm happy for any approver to take the next step.

2024-03-08 06:49 UTC, divya-mohan0209 reviewed
/approve

2024-03-08 06:53 UTC, merged