Revise callouts in encryption-at-rest task page
kubernetes/website pull request #44622
Opened 2024-01-03 23:18 UTC by sftim

This is split out from PR https://github.com/kubernetes/website/pull/33285 in order to make it a review more likely. See that PR and its previews to show the changes in a wider context.

/sig security docs
/language en

2024-01-04 02:16 UTC, kbhawkey commented on content/en/docs/tasks/administer-cluster/encrypt-data.md
> +If there is a difference in the encryption provider configuration, this may well mean
nit: this paragraph could be shortened
Otherwise, the kube-apiserver can't decrypt ...

2024-03-01 11:50 UTC, sftim commented
What's the next step for this PR? Is it OK to merge?

2024-04-01 02:37 UTC, divya-mohan0209 requested changes
@sftim: I agree with @kbhawkey's analysis here. Is it possible to shorten the paragraph she marked? The kube-apiserver cannot decrypt the data if there is a difference in the encryption provider config.

2024-04-01 14:01 UTC, sftim commented
Sure. I'd left that out as the feedback was marked as a nit. If it's actually a blocked for a merge, I'll revise it.

2024-04-01 14:43 UTC, sftim commented
I've revised PR https://github.com/kubernetes/website/pull/33285 and have copied part of a commit from that PR into this one.

2024-04-09 20:49 UTC, reylejano commented
Preview: https://deploy-preview-44622--kubernetes-io-main-staging.netlify.app/docs/tasks/administer-cluster/encrypt-data

/approve

2024-05-03 15:32 UTC, dipesh-rawat reviewed
Thanks!

/lgtm

2024-05-03 15:36 UTC, merged