[es] Add concepts/storage/persistent-volumes.md
kubernetes/website pull request #44735
Opened 2024-01-14 17:39 UTC by edithturn

Hi team!
Sending a new translation page about persistent-volumes

2024-01-14 23:00 UTC, ramrodo commented
/cc @krol3 @electrocucaracha

2024-01-14 23:17 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +  title: Storage orchestration
```suggestion
  title: Orquestación de almacenamiento
```

2024-01-14 23:22 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +[volumes](/docs/concepts/storage/volumes/), [StorageClasses](/docs/concepts/storage/storage-classes/)
Add the current Spanish translations references:

```suggestion
[volumes](/es/docs/concepts/storage/volumes/), [StorageClasses](/es/docs/concepts/storage/storage-classes/)
```

2024-01-14 23:26 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +[Storage Classes](/docs/concepts/storage/storage-classes/). Es un recurso en
```suggestion
[Storage Classes](/es/docs/concepts/storage/storage-classes/). Es un recurso en
```

2024-01-14 23:29 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +NFS, iSCSI, o un sistema de almacenamiento específico de un proveedor de nube.
```suggestion
NFS, iSCSI o un sistema de almacenamiento específico de un proveedor de nube.
```

2024-01-14 23:33 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Hay dos formas en que los PVs pueden ser aprovisionados: estática o dinámicamente.
```suggestion
Hay dos formas en que los PVs pueden ser aprovisionados: estáticamente o dinámicamente.
```

2024-01-14 23:34 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +[clase de almacenamiento](/docs/concepts/storage/storage-classes/) y
```suggestion
[clase de almacenamiento](/es/docs/concepts/storage/storage-classes/) y
```

2024-01-14 23:44 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Consulta [Claims As Volumes](#claims-as-volumes) para más detalles sobre esto.
Para que funcione ésta referencia dentro del este mismo documento, se debe:
1. Entre corchetes: colocar el mismo formato y texto que el subtítulo de más abajo,
2. Entre paréntesis: colocar el mismo texto de referencia con '#'  pero:
    2.1 reemplazando los espacios por guiones medios
    2.2 reemplazando mayúsculas por minúsculas
    2.3 reemplazar vocales con acento por vocales sin acento

```suggestion
Consulta [Solicitudes como Volúmenes](#solicitudes-como-volumenes) para más detalles sobre esto.
```

2024-01-14 23:55 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +heredan la [política de reclamación de su StorageClass](#reclaim-policy), que
Mismo comentario que en https://github.com/kubernetes/website/pull/44735/files#r1451826950:

```suggestion
heredan la [política de reclamación de su StorageClass](#politica-de-reclamacion), que
```

2024-01-14 23:58 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +un borrado básico (`rm -rf /thevolume/*`) en el volumen y lo hace disponible nuevamente para una nueva solicitud.
[Más abajo](https://github.com/kubernetes/website/pull/44735/files#diff-fe32330dd666d023eddcd6170a28c61e5a4aa6934495ff62a4121f35266667cbR635), se traduce el _path_ de éste comando en español como `rm -rf /elvolumen/*`. Ambas opciones pudieran ser correctas, solamente creo que debemos manejar el mismo criterio en ambas referencias:

```suggestion
un borrado básico (`rm -rf /elvolumen/*`) en el volumen y lo hace disponible nuevamente para una nueva solicitud.
```

2024-01-15 00:01 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +El plano de control aún verifica que la [clase de almacenamiento](/docs/concepts/storage/storage-classes/),
```suggestion
El plano de control aún verifica que la [clase de almacenamiento](/es/docs/concepts/storage/storage-classes/),
```

2024-01-15 00:02 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
Creo que deberíamos traducir también el comentario aquí:

```suggestion
  storageClassName: "" # La cadena vacía debe establecerse explícitamente; de lo contrario, se establecerá la StorageClass predeterminada
```

2024-01-15 00:11 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{% tab name="By requesting expansion to smaller size" %}}
```suggestion
{{% tab name="Solicitando ampliación a un tamaño menor" %}}
```

2024-01-15 00:13 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +- [`csi`](/docs/concepts/storage/volumes/#csi) - Interfaz de Almacenamiento de Contenedores (CSI)
```suggestion
- [`csi`](/es/docs/concepts/storage/volumes/#csi) - Interfaz de Almacenamiento de Contenedores (CSI)
```

2024-01-15 00:14 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +- [`fc`](/docs/concepts/storage/volumes/#fc) - Almacenamiento de Canal de Fibra (FC)
```suggestion
- [`fc`](/es/docs/concepts/storage/volumes/#fc) - Almacenamiento de Canal de Fibra (FC)
```

2024-01-15 00:14 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +- [`hostPath`](/docs/concepts/storage/volumes/#hostpath) - Volumen HostPath
```suggestion
- [`hostPath`](/es/docs/concepts/storage/volumes/#hostpath) - Volumen HostPath
```

2024-01-15 00:16 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +- [`nfs`](/docs/concepts/storage/volumes/#nfs) - Almacenamiento del Sistema de Archivos de Red (NFS)
```suggestion
- [`csi`](/es/docs/concepts/storage/volumes/#csi) - Interfaz de Almacenamiento de Contenedores (CSI)
- [`fc`](/es/docs/concepts/storage/volumes/#fc) - Almacenamiento de Canal de Fibra (FC)
- [`hostPath`](/es/docs/concepts/storage/volumes/#hostpath) - Volumen HostPath
  (solo para pruebas en un único nodo; NO FUNCIONARÁ en un clúster multinodo;
  considera usar el volumen `local` en su lugar)
- [`iscsi`](/es/docs/concepts/storage/volumes/#iscsi) - iSCSI (SCSI sobre IP) almacenamiento
- [`local`](/es/docs/concepts/storage/volumes/#local) - dispositivos de almacenamiento locales
  montados en los nodos.
- [`nfs`](/es/docs/concepts/storage/volumes/#nfs) - Almacenamiento del Sistema de Archivos de Red (NFS)
```

2024-01-15 00:19 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +  (**obsoleto** en v1.28)
```suggestion
- [`azureFile`](/es/docs/concepts/storage/volumes/#azurefile) - Azure File
  (**obsoleto** en v1.21)
- [`flexVolume`](/es/docs/concepts/storage/volumes/#flexvolume) - FlexVolume
  (**obsoleto** en v1.23)
- [`portworxVolume`](/es/docs/concepts/storage/volumes/#portworxvolume) - Volumen Portworx
  (**obsoleto** en v1.25)
- [`vsphereVolume`](/es/docs/concepts/storage/volumes/#vspherevolume) - Volumen VMDK de vSphere
  (**obsoleto** en v1.19)
- [`cephfs`](/es/docs/concepts/storage/volumes/#cephfs) - Volumen CephFS
  (**obsoleto** en v1.28)
- [`rbd`](/es/docs/concepts/storage/volumes/#rbd) - Dispositivo de Bloque Rados (RBD)
  (**obsoleto** en v1.28)
```

2024-01-15 00:19 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +  (**no disponible** en v1.26)
```suggestion
- [`awsElasticBlockStore`](/es/docs/concepts/storage/volumes/#awselasticblockstore) - AWS Elastic Block Store (EBS)
  (**no disponible** en v1.27)
- [`azureDisk`](/es/docs/concepts/storage/volumes/#azuredisk) - Disco Azure
  (**no disponible** en v1.27)
- [`cinder`](/es/docs/concepts/storage/volumes/#cinder) - Cinder (almacenamiento en bloque de OpenStack)
  (**no disponible** en v1.26)
```

2024-01-15 00:22 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +El nombre de un objeto PersistentVolume debe ser un válido
```suggestion
El nombre de un objeto PersistentVolume debe ser uno válido
```

2024-01-15 00:28 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="stable" >}}
Me parece que el correcto del artículo original es `v1.18` (no `v1.29`):

```suggestion
{{< feature-state for_k8s_version="v1.18" state="stable" >}}
```

2024-01-15 00:30 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Puedes establecer el valor de `volumeMode` en `Block` para utilizar un volumen como un dispositivo de bloque sin formato. Este tipo de volumen se presenta en un Pod como un dispositivo de bloque, sin
Se debe utilizar el mismo texto del subtítulo de más abajo para que la referencia funcione:

```suggestion
Puedes establecer el valor de `volumeMode` en `Block` para utilizar un volumen como un dispositivo de bloque sin formato. Este tipo de volumen se presenta en un Pod como un dispositivo de bloque, sin ningún sistema de archivos en él. Este modo es útil para proporcionar al Pod la forma más rápida posible de acceder a un volumen, sin ninguna capa de sistema de archivos entre el Pod y el volumen. Por otro lado, la aplicación que se ejecuta en el Pod debe saber cómo manejar un dispositivo de bloque sin formato. Consulta [Soporte para Volúmenes en Bloque sin Procesar](#soporte-para-volumenes-en-bloque-sin-procesar) para ver un ejemplo de cómo usar un volumen con `volumeMode: Block` en un Pod.
```

2024-01-15 00:33 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Puedes establecer el valor de `volumeMode` en `Block` para utilizar un volumen como un dispositivo de bloque sin formato. Este tipo de volumen se presenta en un Pod como un dispositivo de bloque, sin
Una sugerencia más en éste párrafo: ¿podrías separarlo en diferentes líneas como en el artículo original por favor? Ya que aquí todo está en una misma línea y en el artículo original está separado en varias líneas. Esto ayuda a añadir "sugerencias de código" más sencillas.

2024-01-15 00:33 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Un PersistentVolume puede montarse en un host de cualquier manera compatible con el proveedor de recursos. Como se muestra en la tabla a continuación, los proveedores tendrán diferentes capacidades y
Mismo comentario que https://github.com/kubernetes/website/pull/44735/files#r1451836625
(separarlo en diferentes líneas añadiendo saltos de línea)

2024-01-15 13:33 UTC, sftim reviewed
Thank you for working on this.

I have a few small suggestions.

2024-01-15 13:33 UTC, sftim commented on content/es/docs/concepts/storage/persistent-volumes.md
> +| PV volumeMode | PVC volumeMode |  Result |
```suggestion
| PV volumeMode | PVC volumeMode |  Resultado |
```

2024-01-16 02:02 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +### Uso de una fuente de datos de volumen entre espacios de nombres
```suggestion
### Uso de una fuente de datos de volumen entre Namespaces
```

2024-01-16 02:02 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Crea un ReferenceGrant para permitir que el propietario del espacio de nombres acepte la referencia.
```suggestion
Crea un ReferenceGrant para permitir que el propietario del Namespace acepte la referencia.
```

2024-01-16 02:02 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Define un volumen poblado especificando una fuente de datos de volumen entre espacios de nombres utilizando el campo `dataSourceRef`. Debes tener un ReferenceGrant válido en el espacio de nombres de
```suggestion
Define un volumen poblado especificando una fuente de datos de volumen entre Namespaces utilizando el campo `dataSourceRef`. Debes tener un ReferenceGrant válido en el Namespace de origen previamente:
```

2024-01-16 11:51 UTC, sftim commented
> What I have seen is that some terms have become part of the Kubernetes argot in Spanish, so feature gates could be left as it is or eventually create a new consensus definition.

That's fine for people who already know Kubernetes, but: some readers might not yet be familiar.

2024-01-16 21:40 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +heredan la [política de reclamación de su StorageClass](#reclaim-policy), que
A que comentario te refieres, Rodolfo. No puedo visializar haciendo click en el link :)

2024-01-16 21:41 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +un borrado básico (`rm -rf /thevolume/*`) en el volumen y lo hace disponible nuevamente para una nueva solicitud.
Entiendo!

2024-01-16 21:42 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +heredan la [política de reclamación de su StorageClass](#reclaim-policy), que
Te refieres a este comentario tuyo?:

> Para que funcione ésta referencia dentro del este mismo documento, se debe:
> 
> Entre corchetes: colocar el mismo formato y texto que el subtítulo de más abajo,
> Entre paréntesis: colocar el mismo texto de referencia con '#' pero:
> 2.1 reemplazando los espacios por guiones medios
> 2.2 reemplazando mayúsculas por minúsculas
> 2.3 reemplazar vocales con acento por vocales sin acento

2024-01-16 21:45 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="stable" >}}
Ups, no traduje esto. Como nos aseguramos? :)

2024-01-17 17:48 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +heredan la [política de reclamación de su StorageClass](#reclaim-policy), que
Disculpa, sí, me refería justo ese mismo comentario para hacer que las referencias de "link" al mismo documento funcionen.

2024-01-17 17:51 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="stable" >}}
No me refería a traducir al Español como tal, si no más bien, es un typo, porque en el artículo original dice `v1.18`, aquí se puede ver:

https://github.com/kubernetes/website/blob/main/content/en/docs/concepts/storage/persistent-volumes.md?plain=1#L946

2024-01-17 18:50 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Un PV puede tener una clase, que se especifica configurando el atributo `storageClassName` con el nombre de una [StorageClass](/docs/concepts/storage/storage-classes/). Un PV de una clase particular
```suggestion
Un PV puede tener una clase, que se especifica configurando el atributo `storageClassName` con el nombre de una [StorageClass](/es/docs/concepts/storage/storage-classes/). Un PV de una clase particular solo puede vincularse a PVC que soliciten esa clase. Un PV sin `storageClassName` no tiene clase y solo puede vincularse a PVC que no soliciten una clase en particular.
```

2024-01-17 18:52 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Debes establecer esto explícitamente para los volúmenes [locales](/docs/concepts/storage/volumes/#local).
```suggestion
Debes establecer esto explícitamente para los volúmenes [locales](/es/docs/concepts/storage/volumes/#local).
```

2024-01-17 18:57 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Las solicitudes utilizan [las mismas convenciones que los volúmenes](#access-modes) al solicitar almacenamiento con modos de acceso específicos.
```suggestion
Las solicitudes utilizan [las mismas convenciones que los volúmenes](#modos-de-acceso) al solicitar almacenamiento con modos de acceso específicos.
```

2024-01-17 18:57 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Las solicitudes utilizan [la misma convención que los volúmenes](#volume-mode) para indicar el consumo del volumen como un sistema de archivos o un dispositivo de bloque.
```suggestion
Las solicitudes utilizan [la misma convención que los volúmenes](#modo-de-volumen) para indicar el consumo del volumen como un sistema de archivos o un dispositivo de bloque.
```

2024-01-17 18:59 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Las solicitudes pueden especificar un [selector de etiqueta](/docs/concepts/overview/working-with-objects/labels/#label-selectors) para filtrar aún más el conjunto de volúmenes. Solo los volúmenes cu
```suggestion
Las solicitudes pueden especificar un [selector de etiqueta](/es/docs/concepts/overview/working-with-objects/labels/#label-selectors) para filtrar aún más el conjunto de volúmenes. Solo los volúmenes cuyas etiquetas coincidan con el selector pueden vincularse a la solicitud. El selector puede constar de dos campos:
```

2024-01-18 02:13 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Una solicitud puede solicitar una clase en particular especificando el nombre de una [StorageClass](/docs/concepts/storage/storage-classes/) utilizando el atributo `storageClassName`. Solo los PV de
```suggestion
Una solicitud puede solicitar una clase en particular especificando el nombre de una [StorageClass](/es/docs/concepts/storage/storage-classes/) utilizando el atributo `storageClassName`. Solo los PV de la clase solicitada, es decir, aquellos con el mismo `storageClassName` que el PVC, pueden vincularse al PVC.
```

2024-01-18 02:26 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="stable" >}}
Typo

```suggestion
{{< feature-state for_k8s_version="v1.28" state="stable" >}}
```

2024-01-18 02:33 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Las instantáneas de volúmenes solo admiten los complementos de volumen CSI fuera del árbol. Para obtener más detalles, consulta [Instantáneas de Volúmenes](/docs/concepts/storage/volume-snapshots/).
```suggestion
Las instantáneas de volúmenes solo admiten los complementos de volumen CSI fuera del árbol. Para obtener más detalles, consulta [Instantáneas de Volúmenes](/es/docs/concepts/storage/volume-snapshots/). Los complementos de volumen dentro del árbol están obsoletos. Puedes obtener información sobre los complementos de volumen obsoletos en el [FAQ de Complementos de Volumen](https://github.com/kubernetes/community/blob/master/sig-storage/volume-plugin-faq.md).
```

2024-01-18 02:35 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +[Clonación de Volúmenes](/docs/concepts/storage/volume-pvc-datasource/)
```suggestion
[Clonación de Volúmenes](/es/docs/concepts/storage/volume-pvc-datasource/)
```

2024-01-18 02:35 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="stable" >}}
Typo

```suggestion
{{< feature-state for_k8s_version="v1.20" state="stable" >}}
```

2024-01-18 02:36 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="beta" >}}
Typo

```suggestion
{{< feature-state for_k8s_version="v1.24" state="beta" >}}
```

2024-01-18 02:43 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +- Cuando se especifica un espacio de nombres, `dataSource` y `dataSourceRef` no están sincronizados.
[Above](https://github.com/kubernetes/website/pull/44735/files#diff-fe32330dd666d023eddcd6170a28c61e5a4aa6934495ff62a4121f35266667cbR801) she detailed: `espacio de nombres (namespace)`, so using the term in Spanish can be considered correct.

However, let us discuss at the weekly meeting to decide which term we would like to use to be consistent in all the documentation.

2024-01-18 02:51 UTC, ramrodo requested changes
Thanks, Edith for your incredible effort in translating this huge document!

Some suggestions were made. Mostly on:
- Aiming to use the already concepts/links translated into Spanish
- Typos on specifying the Kubernetes versions supported on each feature
- Break an entire paragraph into several lines as the original document

2024-01-27 15:19 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="stable" >}}
Cierto Ciertooo!!
Lo debo haber copiado mal de otro párrafo!
Gracias por esto Rodolfo!

2024-01-27 15:38 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Puedes establecer el valor de `volumeMode` en `Block` para utilizar un volumen como un dispositivo de bloque sin formato. Este tipo de volumen se presenta en un Pod como un dispositivo de bloque, sin
Rodolfo, no entiendo esta parte. 
Tanto el contenido del titulo Modo de Volumen en Ingles y el que traduje tiene 04 párrafos en total. Te fieres a que debo añadir saltos de linea en el ultimo párrafo para hacerlo más consumible?

imagen: Derecha, texto traducido en Español. Izquierda: Texto original de la documentación.
<img width="1418" alt="Screenshot 2024-01-27 at 15 35 03" src="https://github.com/kubernetes/website/assets/58795858/5c94ea68-adc5-4eb7-8560-db8fbff8fcf8">

Gracias por tu soporte!

2024-01-27 15:56 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Un PersistentVolume puede montarse en un host de cualquier manera compatible con el proveedor de recursos. Como se muestra en la tabla a continuación, los proveedores tendrán diferentes capacidades y
Okey entiendo a que te refieres. Aunque el contenido original no esta asi, trataré de separarlo :)

2024-01-27 16:11 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +{{< feature-state for_k8s_version="v1.29" state="stable" >}}
Correcto!!

2024-01-27 16:38 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +[feature gates](/docs/reference/command-line-tools-reference/feature-gates/) para el kube-apiserver y kube-controller-manager.
Let me know if I leave it as is or if it will be changed.
Thanks! :)

2024-01-30 16:58 UTC, electrocucaracha commented
> > What I have seen is that some terms have become part of the Kubernetes argot in Spanish, so feature gates could be left as it is or eventually create a new consensus definition.
> 
> That's fine for people who already know Kubernetes, but: some readers might not yet be familiar.

Hey @sftim, we have discussed that case in our weekly meeting, using [the GKE documentation](https://cloud.google.com/kubernetes-engine/docs/concepts/feature-gates?hl=es-419) as reference. They use two different translations for the same concept, `Puertas de funciones` and `interruptores de funciones` so we decided to use `Interruptores de funcionalidades (feature gates)`. That translation maintains the idea of the original concept, avoiding any divergence.

2024-02-07 19:40 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +[feature gates](/docs/reference/command-line-tools-reference/feature-gates/) para el kube-apiserver y kube-controller-manager.
@edithturn from the internal discussion at the weekly meeting, we decided to use:

```suggestion
[Interruptores de funcionalidades (feature gates)](/docs/reference/command-line-tools-reference/feature-gates/) para el kube-apiserver y kube-controller-manager.
```

could you apply this final change, please?

2024-02-07 19:40 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +[feature gates](/docs/reference/command-line-tools-reference/feature-gates/) para el kube-apiserver y kube-controller-manager.
@edithturn from the internal discussion at the weekly meeting, we decided to use:

```suggestion
[Interruptores de funcionalidades (feature gates)](/docs/reference/command-line-tools-reference/feature-gates/) para el kube-apiserver y kube-controller-manager.
```

could you apply this final change, please?

2024-02-07 19:41 UTC, ramrodo requested changes
Just one more suggestion for `feature gates`

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Un administrador puede recuperar manualmente el volumen con los siguientes pasos.
```suggestion
Un administrador puede reclamar manualmente el volumen con los siguientes pasos.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Cuando la bandera de función `CSIMigration{provider}` está habilitada para un plugin de volumen integrado específico,
```suggestion
Cuando la bandera de funcionalidad `CSIMigration{provider}` está habilitada para un plugin de volumen integrado específico,
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +La recuperación de la expansión fallida de PVC por parte de los usuarios está disponible como una característica alfa desde Kubernetes 1.23. La funcionalidad `RecoverVolumeExpansionFailure` debe esta
```suggestion
La recuperación de la expansión fallida de PVC por parte de los usuarios está disponible como una característica alfa desde Kubernetes 1.23. La funcionalidad `RecoverVolumeExpansionFailure` debe estar habilitada para que esta característica funcione. Consulta la documentación de [interruptores de funcionalidades](/docs/reference/command-line-tools-reference/feature-gates/) para más información.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Si la feature gate de `RecoverVolumeExpansionFailure` están habilitadas en tu clúster, y la expansión ha fallado para un PVC, puedes intentar nuevamente la expansión con un tamaño menor al valor prev
```suggestion
Si el interruptor de funcionalidad de `RecoverVolumeExpansionFailure` está habilitado en tu clúster, y la expansión ha fallado para un PVC, puedes intentar nuevamente la expansión con un tamaño menor al valor previamente solicitado. Para solicitar un nuevo intento de expansión con un tamaño propuesto menor, edita `.spec.resources` para ese PVC y elige un valor que sea menor al valor que intentaste previamente.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +: el volumen puede montarse como lectura-escritura por un solo nodo. El modo de acceso ReadWriteOnce aún puede permitir que varios pods accedan al volumen cuando los pods se ejecutan en el mismo nodo
```suggestion
: el volumen puede montarse como lectura-escritura por un solo nodo. El modo de acceso ReadWriteOnce aún puede permitir que varios Pods accedan al volumen cuando los Pods se ejecutan en el mismo nodo. Para el acceso de un solo Pod, consulta ReadWriteOncePod.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +el volumen puede montarse como lectura-escritura por un solo Pod. Utiliza el modo de acceso ReadWriteOncePod si deseas garantizar que solo un pod en todo el clúster pueda leer ese PVC o escribir en é
```suggestion
el volumen puede montarse como lectura-escritura por un solo Pod. Utiliza el modo de acceso ReadWriteOncePod si deseas garantizar que solo un Pod en todo el clúster pueda leer ese PVC o escribir en él.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Debes habilitar la [feature gate](/docs/reference/command-line-tools-reference/feature-gates/) `PersistentVolumeLastPhaseTransitionTime` para poder usar o ver el campo `lastPhaseTransitionTime`.
```suggestion
Debes habilitar el [interruptor de funcionalidad](/docs/reference/command-line-tools-reference/feature-gates/) `PersistentVolumeLastPhaseTransitionTime` para poder usar o ver el campo `lastPhaseTransitionTime`.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Los Pods acceden al almacenamiento utilizando la solicitud como un volumen. Las solicitudes deben existir en el mismo espacio de nombres (namespace) que el Pod que utiliza la solicitud. El clúster en
```suggestion
Los Pods acceden al almacenamiento utilizando la solicitud como un volumen. Las solicitudes deben existir en el mismo Namespace que el Pod que utiliza la solicitud. El clúster encuentra la solicitud en el Namespace del Pod y la utiliza para obtener el PersistentVolume que respalda la solicitud. Luego, el volumen se monta en el host y dentro del Pod.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Las instantáneas de volúmenes solo admiten los complementos de volumen CSI fuera del árbol. Para obtener más detalles, consulta [Instantáneas de Volúmenes](/es/docs/concepts/storage/volume-snapshots/
```suggestion
Las instantáneas de volúmenes solo admiten los plugins de volumen CSI fuera del árbol. Para obtener más detalles, consulta [Instantáneas de Volúmenes](/es/docs/concepts/storage/volume-snapshots/). Los plugins de volumen dentro del árbol están obsoletos. Puedes obtener información sobre los plugins de volumen obsoletos en el [FAQ de Plugins de Volumen](https://github.com/kubernetes/community/blob/master/sig-storage/volume-plugin-faq.md).
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +solo está disponible para complementos de volumen CSI.
```suggestion
solo está disponible para plugins de volumen CSI.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Los pobladores de volúmenes aprovechan un campo de especificación de PVC llamado `dataSourceRef`. A diferencia del campo `dataSource`, que solo puede contener una referencia a otra PersistentVolumeCl
```suggestion
Los pobladores de volúmenes aprovechan un campo de especificación de PVC llamado `dataSourceRef`. A diferencia del campo `dataSource`, que solo puede contener una referencia a otra PersistentVolumeClaim o a un VolumeSnapshot, el campo `dataSourceRef` puede contener una referencia a cualquier objeto en el mismo Namespace, excepto los objetos principales que no sean PVC. Para los clústeres que tienen habilitada la característica, se prefiere el uso de `dataSourceRef` en lugar de `dataSource`.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Al habilitar la característica `CrossNamespaceVolumeDataSource`, puedes especificar un espacio de nombres en el campo dataSourceRef.
```suggestion
Al habilitar la característica `CrossNamespaceVolumeDataSource`, puedes especificar un Namespace en el campo dataSourceRef.
```

2024-02-08 22:41 UTC, electrocucaracha commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Cuando especificas un espacio de nombres para una fuente de datos de volumen, Kubernetes verifica la existencia de un ReferenceGrant en el otro espacio de nombres antes de aceptar la referencia. Refe
```suggestion
Cuando especificas un Namespace para una fuente de datos de volumen, Kubernetes verifica la existencia de un ReferenceGrant en el otro Namespace antes de aceptar la referencia. ReferenceGrant forma parte de las API de extensiones de `gateway.networking.k8s.io`. Consulta [ReferenceGrant](https://gateway-api.sigs.k8s.io/api-types/referencegrant/) en la documentación de la API de Gateway para obtener detalles. Esto significa que debes extender tu clúster de Kubernetes con al menos ReferenceGrant de la API de Gateway antes de poder utilizar este mecanismo.
```

2024-02-26 14:30 UTC, electrocucaracha commented
/retest

2024-02-26 20:10 UTC, ramrodo commented
/retest

2024-02-26 20:32 UTC, ramrodo commented
/lgtm

2024-02-26 20:33 UTC, ramrodo commented
/retest

2024-02-26 20:42 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Si la feature gate de `RecoverVolumeExpansionFailure` están habilitadas en tu clúster, y la expansión ha fallado para un PVC, puedes intentar nuevamente la expansión con un tamaño menor al valor prev
@edithturn un favor, ¿podrías aplicar éstas sugerencias de traducción de `feature gate` a `interruptor de funcionalidad`? Ésta traducción fue un aceptada en concenso en el grupo interno en la [junta del 30-Enero-24](https://docs.google.com/document/d/1jOTK1tqBRwlNQJUB88wfDnGxpdInxMJ7lIFDZy9cMGY/edit)

2024-02-26 20:42 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +La recuperación de la expansión fallida de PVC por parte de los usuarios está disponible como una característica alfa desde Kubernetes 1.23. La funcionalidad `RecoverVolumeExpansionFailure` debe esta
@edithturn un favor, ¿podrías aplicar éstas sugerencias de traducción de `feature gate` a `interruptor de funcionalidad`? Ésta traducción fue un aceptada en concenso en el grupo interno en la [junta del 30-Enero-24](https://docs.google.com/document/d/1jOTK1tqBRwlNQJUB88wfDnGxpdInxMJ7lIFDZy9cMGY/edit)

2024-02-26 20:43 UTC, ramrodo requested changes
Aplicar sugerencia de `feature gate` por `interruptor de funcionalidad`

2024-02-26 20:45 UTC, ramrodo commented on content/es/docs/concepts/storage/persistent-volumes.md
> +Debes habilitar la [feature gate](/docs/reference/command-line-tools-reference/feature-gates/) `PersistentVolumeLastPhaseTransitionTime` para poder usar o ver el campo `lastPhaseTransitionTime`.
@edithturn un favor, ¿podrías aplicar éstas sugerencias de traducción de `feature gate` a `interruptor de funcionalidad`? Ésta traducción fue un aceptada en concenso en el grupo interno en la [junta del 30-Enero-24](https://docs.google.com/document/d/1jOTK1tqBRwlNQJUB88wfDnGxpdInxMJ7lIFDZy9cMGY/edit)

2024-02-26 20:46 UTC, ramrodo commented
/remove-lgtm

2024-02-29 15:46 UTC, edithturn commented on content/es/docs/concepts/storage/persistent-volumes.md
> +La recuperación de la expansión fallida de PVC por parte de los usuarios está disponible como una característica alfa desde Kubernetes 1.23. La funcionalidad `RecoverVolumeExpansionFailure` debe esta
Wow, entre muchos comentarios, no pude encontrar esto, busque cada uno de los comentarios para saber cual estaba abierto aun. ¡Lo encontré! GRacia!

2024-02-29 15:59 UTC, edithturn commented
@ramrodo apliqué tu sugerencia, por favor revisalo Espero que lo podamos mergear pronto :) 
Woho!!!

2024-03-04 16:28 UTC, anyulled commented
/lgtm

2024-03-05 00:56 UTC, ramrodo commented
Thanks!
/lgtm

2024-03-05 01:00 UTC, electrocucaracha commented
/lgtm
/approve

2024-03-05 01:05 UTC, merged