[ru] Localization of concepts/workloads/controllers/cron-jobs.md
kubernetes/website pull request #44766
Opened 2024-01-16 15:58 UTC by yungserge

This contributes to issue #37044.
Localized the doc and updated the glossary.
Previewed the changes locally.

This one was tough to translate, I used my best judgement, and tried to refer to already translated documents to see what words are used there for the concepts. However, some terms are pretty abstract so I am looking forward to the feedback.

/language ru

2024-01-26 05:27 UTC, shurup requested changes
I think you've done a great job dealing with all those Jobs :-) Here are my suggestions to finalise this text.

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +Например, если установлено значение `200`, это позволяет создать задание на 200 секунд после фактического расписания.
```suggestion
Например, если установлено значение `200`, задание может быть создано в период до 200 секунд позже фактического расписания.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +В этой спецификации может быть указана только одна из следующих директив параллелизма:
```suggestion
В этой спецификации может быть указана только одна из следующих политик параллелизма:
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +### Правила параллелизма
```suggestion
### Политика параллелизма (concurrency policy)
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +### Остановка графика (Schedule suspension)
```suggestion
### Остановка выполнения заданий по расписанию
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +Можно приостановить выполнение CronJob заданий, присвоив необязательному полю `.spec.suspend` значение true.
```suggestion
Можно приостановить выполнение CronJob-заданий, присвоив необязательному полю `.spec.suspend` значение true.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +(они остаются запланированными, но CronJob контроллер не запускает задания для выполнения),
```suggestion
(они остаются запланированными, но CronJob-контроллер не запускает задания для выполнения),
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +[дэдлайна задержки начала задания](#starting-deadline), пропущенные задания планируются немедленно.
```suggestion
[дедлайна задержки начала задания](#starting-deadline), пропущенные задания планируются немедленно.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +Поля `.spec.successfulJobsHistoryLimit` и `.spec.failedJobsHistoryLimit` являются опциональными.
Just for the sake of consistency in this document.
```suggestion
Поля `.spec.successfulJobsHistoryLimit` и `.spec.failedJobsHistoryLimit` являются необязательными.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +По умолчанию они установлены на 3 и 1 соответственно.  Установка предела в `0` соответствует сохранению
```suggestion
По умолчанию они установлены на 3 и 1 соответственно. Установка предела в `0` будет означать,
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +ни одного из заданий соответствующего типа после их завершения.
```suggestion
что никакие задания соответствующего типа не сохранятся после их завершения.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +В этих полях указывается, сколько завершенных и неудачных заданий должно быть сохранено.
```suggestion
В этих полях указывается, сколько завершенных и неудачных заданий должно быть сохранено в истории.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +[часового пояса](https://ru.wikipedia.org/wiki/Список_часовых_поясов_по_странам)
TZ identifiers for the time zones are missing in Russian Wikipedia. Therefore, we'd better use the original link here.
```suggestion
[часового пояса](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones).
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +### Неподдерживаемая TimeZone спецификация
```suggestion
### Неподдерживаемая спецификация TimeZone
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +Обновления CronJobs, уже использующих `TZ` или `CRON_TZ`, будут продолжать выдавать
```suggestion
Обновления для CronJobs, уже использующих `TZ` или `CRON_TZ`, будут продолжать выдавать
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +задания, которые вы определяете, должны быть _эдемпотентными_.
```suggestion
задания, которые вы определяете, должны быть _идемпотентными_.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +Если поле `startingDeadlineSeconds` задано большим значением или не задано (по умолчанию),
```suggestion
Если в поле `startingDeadlineSeconds` задано большое значение или оно не определено (по умолчанию),
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +и,если `concurrencyPolicy` имеет значение `Allow`, задания всегда будут выполняться по крайней мере один раз.
```suggestion
а также при условии, что `concurrencyPolicy` имеет значение `Allow`, задания всегда будут выполняться по крайней мере один раз.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +Если `startingDeadlineSeconds` имеет значение меньше 10 секунд, задание CronJob возможно не будет запланировано. Это происходит потому, что CronJob выполняет проверку каждые 10 секунд.
```suggestion
Если `startingDeadlineSeconds` имеет значение меньше 10 секунд, задание CronJob, возможно, не будет запланировано. Это происходит потому, что CronJob выполняет проверку каждые 10 секунд.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +  [Заданиями](/docs/concepts/workloads/controllers/job/) - двух концепциях, на которые опирается CronJobs.
```suggestion
  [Заданиями](/docs/concepts/workloads/controllers/job/) — двумя концепциями, на которые опираются CronJobs.
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +  CronJob манифеста, см. раздел [Выполнение автоматизированных задач с помощью CronJob](/docs/tasks/job/automated-tasks-with-cron-jobs/).
```suggestion
  CronJob-манифеста см. раздел [Выполнение автоматизированных задач с помощью CronJob](/docs/tasks/job/automated-tasks-with-cron-jobs/).
```

2024-01-26 05:27 UTC, shurup commented on content/ru/docs/concepts/workloads/controllers/cron-jobs.md
> +* `CronJob` является частью REST API Kubernetes.
```suggestion
* `CronJob` является частью Kubernetes REST API.
```

2024-01-26 12:48 UTC, yungserge commented
@shurup Thanks for the feedback! Committed all the suggestions and squashed the commits.

2024-02-05 09:57 UTC, shurup commented
Thank you!
/lgtm
/approve

2024-02-05 09:57 UTC, shurup approved these changes

2024-02-05 10:03 UTC, merged