Update description for the NetworkUnavailable condition
kubernetes/website pull request #44783
Opened 2024-01-17 20:09 UTC by letmerecall

## Why this PR?
In #42917 we found that the description for the `NetworkUnavailable` condition, when it's `False`, is not clear enough to understand how it should be interpreted. Also, the condition (`NetworkUnavailable`) is not something that's a k8s standard (managed by third-party libraries and plugins ) and the nodes can be fully functional even if that condition does not exist.

It is a result of a deeper issue which is being discussed in [#120486](https://github.com/kubernetes/kubernetes/issues/120486)

For this PR, we aim to clear the `NetworkUnavailable`'s description a bit.

## What was changed in this PR?
Update the description of `NetworkUnavailable` condition to:
- clarify what a `False` value means for this condition.
- clarify that it is not a k8s standard and is dependent on plugins.

2024-01-17 20:13 UTC, letmerecall commented
/cc @jayunit100

2024-01-17 23:05 UTC, sftim requested changes
Thanks, but the change is misleadingly wrong as I see it right now.

/sig network

2024-01-17 23:05 UTC, sftim commented on content/en/docs/reference/node/node-status.md
> +| `NetworkUnavailable` | Reflects the network status as determined by the plugins; `True` if improperly configured, `False` for correct configuration and operational network. This value is plugin-dep
The name of this condition _is_ a standard part of Kubernetes' core; see https://github.com/kubernetes/kubernetes/blob/2624e93d55375a9642977d4d5795841ab7463b1d/pkg/apis/core/types.go#L4914

2024-01-18 07:07 UTC, kundan2707 reviewed
Without change in core logic and meaning it is not good idea to change documentation it will create conflict.

2024-06-13 11:59 UTC, divya-mohan0209 commented
> @sftim thanks for pointing this out. So it is established that it's a standard part of k core, but do we set/unset this in Kubernetes? Or it's something which is handled by the plugins/third-party? (maybe we can clarify this bit in docs)

There's an [issue discussion](https://github.com/kubernetes/kubernetes/issues/56794) that you might find helpful.

2024-06-13 12:00 UTC, closed without merging