Update docs around sidecar containers
kubernetes/website pull request #44800
Opened 2024-01-18 23:59 UTC by sftim

Update the documentation around sidecar containers.

This wording fits having at least one minor release after v1.29, so I've targeted the branch _dev-1.30_.

/sig node

2024-01-21 20:29 UTC, bart0sh commented
/cc @SergeyKanzhelev

2024-01-23 08:27 UTC, Ritikaa96 requested changes

2024-01-23 08:27 UTC, Ritikaa96 commented on content/en/docs/concepts/workloads/pods/sidecar-containers.md
> +If you define a Jobs that uses sidecar using Kubernetes-style init containers,
```suggestion
If you define a Job that uses sidecar using Kubernetes-style init containers,
```

2024-01-26 03:28 UTC, Ritikaa96 commented
thanks @sftim 
/lgtm

2024-02-01 17:20 UTC, reylejano commented
Thank you, the proposed changes improve the docs
/approve

2024-02-01 17:24 UTC, merged