Issue 41867
kubernetes/website pull request #44924
Opened 2024-01-28 12:47 UTC by EigoOda

2024-02-29 01:00 UTC, Okabe-Junya commented
/cc Okabe-Junya

@t-inu @atoato88 

このPRのレビューは自分が引き取りたいと思います :)

2024-02-29 01:02 UTC, Okabe-Junya commented
The target page on the deploy preview site:

- https://deploy-preview-44924--kubernetes-io-main-staging.netlify.app/ja/docs/setup/best-practices/enforcing-pod-security-standards/

2024-02-29 02:36 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます〜！！

何点かコメントしたので、ご確認よろしくお願いします

2024-02-29 02:36 UTC, Okabe-Junya commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +- `warn`を`enforce`と同じレベルに設定すると、バリデーションに合格しないPod(またはPodテンプレートを持つリソース)を作成しようとしたときに、クライアントが警告を受け取るようになります。これにより、対象のリソースを更新して準拠させることができます。
```suggestion
- `warn`を`enforce`と同じレベルに設定すると、バリデーションに通過しないPod(またはPodテンプレートを持つリソース)を作成しようとしたときに、クライアントが警告を受け取るようになります。これにより、対象のリソースを更新して準拠させることができます。
```

nits: 目的語が "validation" なので、pass の訳は「通過する」のほうが良いのかなと思いました

>  clients will receive warnings when attempting to create Pods (or resources that have Pod templates) that do not pass validation

2024-02-29 02:36 UTC, Okabe-Junya commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +- `enforce`を特定の非最新バージョンに固定するネームスペースでは、`audit`と`warn`モードを`enforce`と同じレベルに設定するが、最新バージョンに設定することで、以前のバージョンでは許可されていたが、現在のベストプラクティスでは許可されていない設定を可視化することができます。
```suggestion
- `enforce`を特定の最新ではないバージョンに固定するネームスペースでは、`audit`と`warn`モードを`enforce`と同じレベルに設定するが、最新バージョンに設定することで、以前のバージョンでは許可されていたが、現在のベストプラクティスでは許可されていない設定を可視化することができます。
```

nits: 「非最新」という表現はあまり一般的ではないように感じたので、 "non-latest" は「最新で（は）ない」と訳してしまって良いように思いました

2024-02-29 02:36 UTC, Okabe-Junya commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +- `enforce`を特定の非最新バージョンに固定するネームスペースでは、`audit`と`warn`モードを`enforce`と同じレベルに設定するが、最新バージョンに設定することで、以前のバージョンでは許可されていたが、現在のベストプラクティスでは許可されていない設定を可視化することができます。
```suggestion
- `enforce`を特定の非最新バージョンに固定するネームスペースでは、`audit`と`warn`モードを`enforce`と同じレベルに設定するが、最新バージョンに対して設定することで、以前のバージョンでは許可されていたが、現在のベストプラクティスでは許可されていない設定を可視化することができます。
```

nits: "to the" の旨を明記しても良いかと思いました。

（ここは原文が長く文構造も読み取りにくいので、翻訳が難しいですね。。2文に分割しても良いかなと思いましたが、それも難しそうですね。。）

2024-02-29 02:36 UTC, Okabe-Junya commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +ビルトインソリューション（PodSecurityアドミッションコントローラーなど）とサードパーティツールのどちらを選ぶかは、あなたの状況次第です。
```suggestion
ビルトインソリューション(PodSecurityアドミッションコントローラーなど)とサードパーティツールのどちらを選ぶかは、あなたの状況次第です。
```

k/websiteでは、半角の括弧を用います

ref. https://kubernetes.io/ja/docs/contribute/localization/#基本方針

> スペースと括弧 () 、コロン : は半角、それ以外の記号類は全角で表記

2024-02-29 04:19 UTC, Okabe-Junya approved these changes
ありがとうございます〜LGTMです

/lgtm

2024-02-29 04:20 UTC, Okabe-Junya commented
/assign nasa9084

2024-02-29 04:20 UTC, EigoOda commented
@Okabe-Junya 
レビューありがとうございました！🙏

2024-02-29 04:21 UTC, Okabe-Junya commented
（非本質的なコメントですが、手元でsquash & force-push しなくても、`/label tide/merge-method-squash` とコメントすることで、squash mergeできますので、もしよければご活用ください〜）

2024-02-29 04:43 UTC, EigoOda commented
@Okabe-Junya 
ありがとうございます！次回から活用させていただきます🙏

2024-03-27 11:12 UTC, nasa9084 commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +### すべてのネームスペースに設定する
この場合のnamespace(s)は、ラベルをつけるとかつけないとかという説明からnamespace resourceである気がするのですがどうでしょうか(namespace resourceであるなら「ネームスペース」ではなくPodなどと同様にママ表記としたい)

cc @kubernetes/sig-docs-ja-reviews

2024-03-27 11:45 UTC, Okabe-Junya commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +### すべてのネームスペースに設定する
+1です🙆‍♂️

2024-03-27 13:21 UTC, EigoOda commented
/label tide/merge-method-squash

2024-03-27 13:27 UTC, EigoOda commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +### すべてのネームスペースに設定する
@nasa9084 @Okabe-Junya 
レビューありがとうございます！全"ネームスペース"を"Namespace"に変更しました

2024-03-27 14:17 UTC, Okabe-Junya commented on content/ja/docs/setup/best-practices/enforcing-pod-security-standards.md
> +### すべてのネームスペースに設定する
修正ありがとうございます〜！LGTMは自分の方から売っておきますね

2024-03-27 14:17 UTC, Okabe-Junya approved these changes
/lgtm

2024-03-27 14:56 UTC, nasa9084 commented
/approve
ありがとうございます〜！

2024-03-27 14:58 UTC, merged