Add issue link info to PR template
kubernetes/website pull request #44978
Opened 2024-02-01 10:26 UTC by stmcginnis

While reviewing pull requests I noticed there are a lot of PRs that are addressing open issues, but the PRs are not properly linked. This results in a lot of issues being left open, even after the fix has been merged.

This updates the PR template to give a short instruction on adding the expected line in the PR description so that the issue and PR can be linked automatically and closed on merge.

2024-02-01 11:11 UTC, sftim commented on .github/PULL_REQUEST_TEMPLATE.md
> +description so it will automically close when the PR is merged. This is done
```suggestion
description so it will automatically close when the PR is merged. This is done
```

2024-02-02 05:54 UTC, Shubham82 commented
Thanks @stmcginnis 
/lgtm

2024-02-08 07:41 UTC, Gauravpadam reviewed
Thanks @stmcginnis,

Do you feel we should keep this somewhere near the beginning of the file?
Also, Should keep it short, In a single line perhaps?
"If this PR solves an open issue, please add a closing tag (Closes #[issue_number]) to the PR description."

2024-02-08 18:03 UTC, stmcginnis commented
That makes sense. I've pushed up another format that has worked really well for me on other projects. It makes it more clear what sections/information to fill out in the PR template.

It does not shorten things as you mention, but I wanted to throw it out there as another potential approach. If you prefer the original way but more concise, just let me know and I can switch things back to that.

2024-04-02 14:50 UTC, sftim requested changes
This PR doesn't look right.

2024-04-02 14:50 UTC, sftim commented on pmsecret.yaml
What's this?

2024-04-02 15:11 UTC, stmcginnis commented on pmsecret.yaml
Oops, accidental `git add .` there. Cleaned up now.

2024-04-23 03:48 UTC, aj11anuj commented
I liked the concise format Gaurav proposed -
> "If this PR solves an open issue, please add a closing tag (Closes #[issue_number]) to the PR description."

and if needed then a hyperlink for newcomers to learn more about it can be added at bottom of this whole description.

2024-07-22 07:44 UTC, Shubham82 commented
/remove-lifecycle stale

2024-07-22 07:57 UTC, Shubham82 commented
/lgtm

2024-07-26 11:45 UTC, Shubham82 commented
@tengqm, could you please take a look?

2024-07-27 04:49 UTC, tengqm commented
/approve

2024-07-27 04:53 UTC, merged