Translate home index to arabic
kubernetes/website pull request #45031
Opened 2024-02-05 21:45 UTC by mboukhalfa

This PR adds the minimal translation related to the file /home/_index.md and splitting the old [PR](https://github.com/kubernetes/website/pull/44902) to smaller

2024-02-06 04:41 UTC, seokho-son commented on content/ar/docs/home/_index.md
> +- mboukhalfa
```suggestion
# approvers:
# - chenopis
```

Please do not change the names of reviewers or approvers in individual documents.
Instead, please disable the section by toggling a line comment.

2024-02-06 04:43 UTC, seokho-son commented
/language ar

2024-02-06 04:46 UTC, seokho-son commented
/retitle [ar] Translate home index to arabic

Please provide language code as the prefix of the PR title. (this is one of the agreed conventions from SIG Docs localization subproject meeting.)

2024-02-06 04:48 UTC, seokho-son commented
For the Arabic localization (for the initial minimum-viable Arabic localization), please try to refer https://github.com/kubernetes/website/issues/44682
 - PTAL the comment: https://github.com/kubernetes/website/issues/44682#issuecomment-1918971618 (for collaboration)

2024-04-18 02:12 UTC, seifrajhi commented on content/ar/docs/home/_index.md
> +- name: setup
إعداد

2024-04-18 02:12 UTC, seifrajhi commented on content/ar/docs/home/_index.md
> +  title: "أنصب عنقود ك8ز"
إعداد عنقود ك8س

2024-04-20 08:46 UTC, mboukhalfa commented on content/ar/docs/home/_index.md
> +  title: "أنصب عنقود ك8ز"
أفضل أنصب لاننا نستخدم أعداد مع configuration

2024-04-20 09:03 UTC, mboukhalfa commented on content/ar/docs/home/_index.md
> +- name: setup
the names are kept in english : https://github.com/kubernetes/website/blob/main/content/ko/docs/home/_index.md?plain=1

2024-05-05 08:59 UTC, seifrajhi requested changes

2024-05-05 08:59 UTC, seifrajhi commented on content/ar/docs/home/_index.md
> +  title: "أنصب عنقود ك8ز"
ok makes sense, can we use `ك8س` ? instead of `ك8ز`

2024-05-05 09:10 UTC, mboukhalfa commented
@seifrajhi  تم

2024-05-05 13:26 UTC, seifrajhi commented
/lgtm

2024-05-05 13:26 UTC, seifrajhi commented
/approve

2024-05-05 13:29 UTC, merged