[ar] Add Arabic technique glossary
kubernetes/website pull request #45082
Opened 2024-02-10 12:11 UTC by mboukhalfa

Adding Arabic technique glossary to unify and avoid using different translation for the same English word

2024-02-10 16:27 UTC, Arhell reviewed
/language ar

2024-02-13 09:15 UTC, adowair requested changes
Thank you for taking the initiative. I've made some additions to text and some typing nits.

2024-02-13 09:15 UTC, adowair commented on content/ar/docs/contribute/localization.md
> +لايجب إستخدام أي مرادف بختلف عن المصطلح المدرج في المعجم في وثائق كوبيرنيتيس بل يجب تحديث المعجم أولا.
```suggestion
إذا وجد تعريب لمصطلح إنجليزي معين في المعجم، فيجب استخدام ذلك التعريب فقط، ولا يجوز استخدام أي تعريب أو ترجمة أخرى للمصطلح في وثائق كوبيرنيتيس. نرحب دائماً بطلبات تحديث المعجم ومناقشة التعريبات.
```

2024-02-15 18:26 UTC, mboukhalfa commented on content/ar/docs/contribute/localization.md
> +title: دليل لترجمة وثائق كوبيرنيتيس
done

2024-02-15 18:26 UTC, mboukhalfa commented on content/ar/docs/contribute/localization.md
> +دليل لترجمة وثائق كوبيرنيتيس إلى اللغة العربية
done

2024-02-15 18:26 UTC, mboukhalfa commented on content/ar/docs/contribute/localization.md
> +لايجب إستخدام أي مرادف بختلف عن المصطلح المدرج في المعجم في وثائق كوبيرنيتيس بل يجب تحديث المعجم أولا.
done

2024-02-15 18:32 UTC, adowair commented
LGTM for Arabic, thank you @mboukhalfa

2024-02-15 19:01 UTC, adowair approved these changes

2024-02-17 16:39 UTC, adowair commented
Thanks @mboukhalfa. It may be more convenient and better Git hygiene to move updates to the existing docs to a new PR.

2024-02-20 17:54 UTC, ContainerNerd commented
LGTM for Arabic!
Thank you fro the efforts @mboukhalfa

2024-02-20 17:54 UTC, ContainerNerd approved these changes

2024-02-20 17:59 UTC, seifrajhi commented
LGTM for Arabic!
Thank you fro the efforts @mboukhalfa

2024-02-23 10:32 UTC, adowair commented
> The idea is to unify the words once this PR gets merged so we do not have merged content conflicting with the technical glossary

@mboukhalfa I understand your sentiment to make sure the development branch is "clean" in this way, but I would like to respectfully rebut, for several reasons:
1. `dev-1.29-ar.1` is a development, unpublished branch. Since its content is not visible publicly, we can afford to have merged work in progress.
2. As more and more documents get added, it will become impractical to combine all updates to terminology localization in this one PR. What I fear is that way, this PR will not merge **until after** everything else is done, which I do not think is the intuitive order of operations.
3. Repeating the above, I fear that we regress into a "waterfall" model where all PRs are "pending" because we are waiting for "perfectly consistent" PRs. This will slow down progress and defeats the purpose of having a development branch and a Git history.
4. On that topic, as an aside, I believe that this project is set up with the ability to "squash" commits when PRs are merged, so I believe that we can indeed create incremental commits within PRs, saving the "history" of the work. As @seifrajhi pointed out in #45047, in reference to #40184, force-pushes break Netlify's rendering behavior.

The content of this PR (minus the last set of changes) looks great to me, and I really appreciate your effort. I am encouraging to merge it ASAP so that we can see real, even if incremental, progress.

2024-02-23 12:17 UTC, adowair commented
Also, for reference, this PR pours into the effort: #44682.

2024-04-17 17:48 UTC, adowair commented
/lgtm

2024-04-18 12:40 UTC, adowair commented
/assign @seifrajhi

Will you please take a look and lgtm?

2024-04-19 16:13 UTC, seifrajhi commented
/lgtm

2024-04-28 13:01 UTC, seifrajhi commented
/lgtm

2024-04-28 13:04 UTC, merged