[ja] Translate content/en/blog/_posts/2024-01-23-image-filesystem.md into Japanese
kubernetes/website pull request #45102
Opened 2024-02-12 15:07 UTC by b1gb4by

## Issue

https://github.com/kubernetes/website/issues/45098

## Change. List

Translate content/en/blog/_posts/2024-01-23-image-filesystem.md into Japanese

2024-02-12 15:27 UTC, Okabe-Junya commented
/cc @Okabe-Junya

2024-03-20 09:14 UTC, Okabe-Junya commented
The target page on the deploy preview site:

- https://deploy-preview-45102--kubernetes-io-main-staging.netlify.app/ja/blog/2024/01/23/kubernetes-separate-image-filesystem/

2024-03-20 09:53 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます。何点かコメントさせていただいたので、ご確認お願いします〜！

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +title: 'Image Filesystem: Configuring Kubernetes to store containers on a separate filesystem'
タイトルも翻訳をお願いします

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +Kubernetesクラスターの稼働/運用する上でよくある問題は、ディスク容量が不足することです。ノードがプロビジョニングされる際には、コンテナイメージと実行中のコンテナのために十分なストレージスペースを確保することが重要です。通常、[コンテナランタイム](/ja/docs/setup/production-environment/container-runtimes/)は`/var`に書き込み
```suggestion
Kubernetesクラスターの稼働、運用する上でよくある問題は、ディスク容量が不足することです。ノードがプロビジョニングされる際には、コンテナイメージと実行中のコンテナのために十分なストレージスペースを確保することが重要です。通常、[コンテナランタイム](/ja/docs/setup/production-environment/container-runtimes/)は`/var`に書き込みます。これは別のパーティションとして、ルートファイルシステム上に配置できます。CRI-Oはデフォルトで、コンテナとイメージを`/var/lib/containers`に書き込みますが、containerdはコンテナとイメージを`/var/lib/containerd`に書き込みます。
```

IMHO: 日本語だと "稼働/運用" のように、`/` で区切るのは少し読みにくくなってしまうので句点や「や」で区切るのはどうでしょうか（他の場所も同様です）

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +## Kubernetesディスク使用状況の理解
```suggestion
## Kubernetesディスク使用状況を理解する
```

nits

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +ルート/ノード・ファイルシステムは/ではなく、/var/lib/kubeletがあるディスクのため、ほとんどのPOSIXシステムとは異なります。
```suggestion
ルート/ノード・ファイルシステムは`/`ではなく、`/var/lib/kubelet`があるディスクのため、ほとんどのPOSIXシステムとは異なります。
```

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +ポッドやコンテナは、動作に一時的または短期的なローカルストレージを必要とする場合があります。エフェメラルストレージの寿命は個々のポッドの寿命を超えず、エフェメラルストレージはポッド間で共有することはできません。
```suggestion
Podやコンテナは、動作に一時的または短期的なローカルストレージを必要とする場合があります。エフェメラルストレージの寿命は個々のPodの寿命を超えず、エフェメラルストレージはPod間で共有することはできません。
```

（明文化されていなくて恐縮ですが）基本的に "Pod" 表記で統一する方針になっているので、他の場所と合わせて修正をお願いしたいです

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +各ノードの[ログローテーション](/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存せずにログの配信を設定することができます（サードパーティーのソリューションを使用）。
```suggestion
各ノードの[ログローテーション](/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存せずにログの配信を設定することができます(サードパーティーのソリューションを使用)。
```

カッコは半角でお願いします（他の場所も同様にお願いします）

ref. https://kubernetes.io/ja/docs/contribute/localization/#基本方針

> スペースと括弧 () 、コロン : は半角、それ以外の記号類は全角で表記

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +- 読み取り専用レイヤー：イメージは通常、コンテナが実行されている間に変更されないため、読み取り専用レイヤーとして表されます。読み取り専用レイヤーには、複数のレイヤーが組み合わされて単一の読み取り専用レイヤーになることがあります。コンテナがファイルシステムに書き込んでいる場合、コンテナの上にはエフェメラルストレージを提供する薄いレイヤーがあります。
```suggestion
- 読み取り専用レイヤー:イメージは通常、コンテナが実行されている間に変更されないため、読み取り専用レイヤーとして表されます。読み取り専用レイヤーには、複数のレイヤーが組み合わされて単一の読み取り専用レイヤーになることがあります。コンテナがファイルシステムに書き込んでいる場合、コンテナの上にはエフェメラルストレージを提供する薄いレイヤーがあります。
```

コロンは半角表記でお願いします（他の場所も同様にお願いします）

ref. https://kubernetes.io/ja/docs/contribute/localization/#基本方針

> スペースと括弧 () 、コロン : は半角、それ以外の記号類は全角で表記

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +  - SELinuxが有効になっている場合、これは `/var/lib/containers/storage` と一致させる必要があります
```suggestion
  - SELinuxが有効になっている場合、これは`/var/lib/containers/storage`と一致させる必要があります
```

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +  - デフォルトは、`/run/containerd` です
```suggestion
  - デフォルトは、`/run/containerd`です
```

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +  - デフォルトは `/var/lib/containerd` です
```suggestion
  - デフォルトは`/var/lib/containerd`です
```

空白を取り除いてください（他の場所も同様にお願いします）

ref. https://kubernetes.io/ja/docs/contribute/localization/#基本方針

> 英単語と日本語の間に半角スペースは不要

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +kubelet内の退避マネージャには、関連する閾値を制御するいくつかの構成設定があります。ファイルシステムの場合、関連する測定値は`nodefs.available`、`nodefs.inodesfree`、`imagefs.available`、および`imagefs.inodesfree`です。コンテナランタイム用に専用のディスクがない場合、imagefsは無視されます。
```suggestion
kubelet内の退避マネージャーには、関連する閾値を制御するいくつかの構成設定があります。ファイルシステムの場合、関連する測定値は`nodefs.available`、`nodefs.inodesfree`、`imagefs.available`、および`imagefs.inodesfree`です。コンテナランタイム用に専用のディスクがない場合、imagefsは無視されます。
```

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +  限界値を定義します。これらの限界値を超えると、Grace Periodが設定されたシグナルごとにポッドが追い出されます。
手元で検証していなくて恐縮ですが、先頭の `:` がなくても表記上問題なさそうですかね。。？？

https://github.com/kubernetes/website/blob/bf455d82974c68856688b36cad4092d5c96da3be/content/en/blog/_posts/2024-01-23-image-filesystem.md?plain=1#L139-L143

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
ファイル全体に対してですが、MDのリーダビリティを高めるために、一行（読点）ごとに改行していただけると助かります 🙏

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +各ノードの[ログローテーション](/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存せずにログの配信を設定することができます（サードパーティーのソリューションを使用）。
```suggestion
各ノードの[ログローテーション](/ja/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存せずにログの配信を設定することができます（サードパーティーのソリューションを使用）。
```

日本語訳があるため、そちらへリンクするようにお願いします

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +Kubernetesは、コンテナファイルシステムがノードファイルシステムと分離されているかどうかを自動的に検出します。ファイルシステムを分離する場合、Kubernetesはノードファイルシステムとコンテナランタイムファイルシステムの両方を監視する責任があります。Kubernetesドキュメントでは、ノードファイルシステムとコンテナランタイムファイルシステムをそれぞれnodefsとimagefsと
```suggestion
Kubernetesは、コンテナファイルシステムがノードファイルシステムと分離されているかどうかを自動的に検出します。ファイルシステムを分離する場合、Kubernetesはノードファイルシステムとコンテナランタイムファイルシステムの両方を監視する責任があります。Kubernetesドキュメントでは、ノードファイルシステムとコンテナランタイムファイルシステムをそれぞれnodefsとimagefsと呼んでいます。nodefsまたはimagefsのいずれかがディスク容量不足になると、ノード全体がディスク圧迫があると見なされます。Kubernetesは、まず未使用のコンテナやイメージを削除してスペースを回収し、その後にポッドを追い出すことでスペースを再利用します。nodefsとimagefsの両方を持つノードでは、kubeletはimagefs上の未使用のコンテナイメージを[ガベージコレクト](/ja/docs/concepts/architecture/garbage-collection/#containers-images)し、nodefsからは終了したポッドとそれらのコンテナを削除します。nodefsのみが存在する場合、Kubernetesのガベージコレクションには、終了したコンテナ、ポッド、そして未使用のイメージが含まれます。
```

2024-03-20 09:53 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +素晴らしいレビューや貴重な洞察を提供してくれたり、トピックのアイデアを提案してくれたすべての貢献者に特別な感謝を申し上げます。あなた方の貢献によって、コミュニティ全体のKubernetesがより良くなることを支えています。
"あなた方の貢献によって、コミュニティ全体のKubernetesがより良くなることを支えています。" に対応する原文が見つけられなかったのですが、こちらが把握できていなかったら申し訳ないです。。

Origin

> Special thanks to all the contributors who provided great reviews, shared valuable insights or suggested the topic idea.

2024-03-20 09:53 UTC, Okabe-Junya commented
/label tide/merge-method-squash

2024-03-20 09:56 UTC, Okabe-Junya commented
一点ファイル内容ではないコメントですが、PR descriptionを編集して、issueとリンクしていただけると助かります〜

FYI: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

2024-03-24 06:06 UTC, b1gb4by commented
@Okabe-Junya 
レビューありがとうございます！！
ご指摘を受けた内容を修正します 🙇‍♂️

2024-03-25 03:20 UTC, Okabe-Junya requested changes
修正ありがとうございます〜！もう何点かだけお願いします。こちら修正いただければLGTMです

2024-03-25 03:20 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +title: 'Image Filesystem: Configuring Kubernetes to store containers on a separate filesystem'
タイトルの翻訳をお願いします

2024-03-25 03:20 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +各ノードの[ログローテーション](/ja/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存せずにログの配信を設定することができます（サードパーティーのソリューションを使用）。
```suggestion
各ノードの[ログローテーション](/ja/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存せずにログの配信を設定することができます(サードパーティーのソリューションを使用)。
```

半角カッコに修正をお願いします

2024-03-25 03:20 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +- 書き込み可能レイヤー：コンテナランタイムによっては、ローカルの書き込みがレイヤー化された書き込みメカニズム（例えば、Linux上の`overlayfs`やWindows上のCimFS）として実装されることがあります。これは書き込み可能レイヤーと呼ばれます。ローカルの書き込みは、コンテナイメージの完全なクローンで初期化された書き込み可能なファイルシステムを使用する場合もあります。これは、ハイパ
```suggestion
- 書き込み可能レイヤー：コンテナランタイムによっては、ローカルの書き込みがレイヤー化された書き込みメカニズム(例えば、Linux上の`overlayfs`やWindows上のCimFS)として実装されることがあります。これは書き込み可能レイヤーと呼ばれます。ローカルの書き込みは、コンテナイメージの完全なクローンで初期化された書き込み可能なファイルシステムを使用する場合もあります。これは、ハイパーバイザ仮想化に基づく一部のランタイムで使用されます。
```

ditto

2024-03-25 03:20 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +一部のLinuxディストリビューションには、ストレージに関するマニュアルエントリ（`man 5 containers-storage.conf`）があります。ストレージの主な設定は、`/etc/containers/storage.conf`にあり、一時データの場所やルートディレクトリを制御することができます。
```suggestion
一部のLinuxディストリビューションには、ストレージに関するマニュアルエントリ(`man 5 containers-storage.conf`)があります。ストレージの主な設定は、`/etc/containers/storage.conf`にあり、一時データの場所やルートディレクトリを制御することができます。
```

ditto

2024-03-25 03:20 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +Kubernetesクラスターの稼働、運用する上でよくある問題は、ディスク容量が不足することです。ノードがプロビジョニングされる際には、コンテナイメージと実行中のコンテナのために十分なストレージスペースを確保することが重要です。通常、[コンテナランタイム](/ja/docs/setup/production-environment/container-runtimes/)は`/var`に書き込み
```suggestion
Kubernetesクラスターの稼働、運用する上でよくある問題は、ディスク容量が不足することです。
ノードがプロビジョニングされる際には、コンテナイメージと実行中のコンテナのために十分なストレージスペースを確保することが重要です。
通常、[コンテナランタイム](/ja/docs/setup/production-environment/container-runtimes/)は`/var`に書き込みます。
これは別のパーティションとして、ルートファイルシステム上に配置できます。
CRI-Oはデフォルトで、コンテナとイメージを`/var/lib/containers`に書き込みますが、containerdはコンテナとイメージを`/var/lib/containerd`に書き込みます。
```

文章（句点）ごとに改行を入れていただくようお願いします（他の箇所も同様にお願いします）

ref. https://github.com/kubernetes/website/pull/45102/files#r1531770725

2024-03-25 03:20 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +素晴らしいレビューや貴重な洞察を提供してくれたり、トピックのアイデアを提案してくれたすべての貢献者に特別な感謝を申し上げます。あなた方の貢献によって、コミュニティ全体のKubernetesがより良くなることを支えています。
こちらご確認いただきたいです

2024-03-25 03:21 UTC, Okabe-Junya commented
/assign nasa9084

2024-03-26 08:50 UTC, Okabe-Junya approved these changes
度々のご修正をありがとうございます。LGTMです〜！

/lgtm

2024-04-01 15:22 UTC, nasa9084 reviewed
kubernetes/websiteへのはつコントリビューションありがとうございます！
修正点が多くなってしまって申し訳ありませんが確認お願いします！

2024-04-01 15:22 UTC, nasa9084 commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +Kubernetesには永続データと一時データがあります。
```suggestion
Kubernetesには永続(persistent)データと一時(ephemeral)データがあります。
```

nit: PersistentVolumeや、(この記事の他の部分で使われるように)エフェメラルストレージ、という表現がKubernetesの文脈では頻出なので、括弧書きでもとの単語を入れておくと親切かと思いました

2024-04-01 15:22 UTC, nasa9084 commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +kubeletとローカルのKubernetes固有ストレージのベースパスは設定可能ですが、通常は`/var/lib/kubelet`と想定されています。
```suggestion
kubeletとKubernetes固有ローカルストレージのベースパスは設定可能ですが、通常は`/var/lib/kubelet`と想定されています。
```

nit: `Kubernetes固有ローカルストレージ` はちょっと長くて微妙な感じがしないでもないのですが、 `local` が `storage` にかかっていると思いますので、順番を少し入れ替えた方がわかりやすいような気がします

2024-04-01 15:22 UTC, nasa9084 commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +Kubernetesのドキュメントでは、これは時々ルートまたはノードファイルシステムと呼ばれます。
```suggestion
Kubernetesのドキュメントでは、これは時々ルートファイルシステムまたはノードファイルシステムと呼ばれます。
```

`root/node filesystem` は `root filesystem or node filesystem` という意味だと思いますので、少し冗長にはなりますが「ファイルシステム」を補った方がよいと思います

2024-04-01 15:22 UTC, nasa9084 commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +各ノードの[ログローテーション](/ja/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存せずにログの配信を設定することができます(サードパーティーのソリューションを使用)。
```suggestion
各ノードの[ログローテーション](/ja/docs/concepts/cluster-administration/logging/#log-rotation)設定をカスタマイズしてこれらのログのサイズを管理し、ノードローカルストレージに依存しないためにログの配信を設定することができます(サードパーティーのソリューションを使用)。
```

2024-04-01 15:22 UTC, nasa9084 commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +nodefsとimagefsの両方を持つノードでは、kubeletはimagefs上の未使用のコンテナイメージを[ガベージコレクト](/ja/docs/concepts/architecture/garbage-collection/#containers-images)し、nodefsからは終了したポッドとそれらのコンテナを削除します。
```suggestion
nodefsとimagefsの両方を持つノードでは、kubeletはimagefs上の未使用のコンテナイメージを[ガベージコレクト](/ja/docs/concepts/architecture/garbage-collection/#containers-images)し、nodefsからは終了したPodとそれらのコンテナを削除します。
```

2024-04-01 15:22 UTC, nasa9084 commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +nodefsのみが存在する場合、Kubernetesのガベージコレクションには、終了したコンテナ、ポッド、そして未使用のイメージが含まれます。
```suggestion
nodefsのみが存在する場合、Kubernetesのガベージコレクションには、終了したコンテナ、Pod、そして未使用のイメージが含まれます。
```

2024-04-01 17:10 UTC, b1gb4by commented
@nasa9084 
レビューありがとうございます！コメント頂いた箇所を確認し、修正します。

2024-04-01 17:23 UTC, b1gb4by commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +kubeletとローカルのKubernetes固有ストレージのベースパスは設定可能ですが、通常は`/var/lib/kubelet`と想定されています。
@nasa9084 
なるほど。個人的に改めて考えてみたのですが、以下の表現でもわかりやすいかな？と思ったのですがいかがでしょうか？

- Kubernetes固有のローカルストレージ
- ローカルのKubernetes固有のストレージ

2024-04-01 17:24 UTC, b1gb4by commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +したがって、構成ですべてのシグナルを設定することが重要です。
わかりました。「設定する」に置換します。

2024-04-01 17:28 UTC, b1gb4by commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +ポッド内のコンテナがファイルシステムをバックエンドとする`emptyDir`ボリュームに書き込んでいる場合、これはノードファイルシステムからスペースを使用します。
すいません、Podへ置換が漏れていました。

2024-04-01 17:29 UTC, b1gb4by commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +シグナルを見逃すと、Kubernetesはそのリソースを監視しません。
そうですね、「設定を忘れる」に置換します。

2024-04-04 20:24 UTC, Okabe-Junya commented
FYI: https://github.com/kubernetes/website/pull/45749#pullrequestreview-1981062903

> コントリビュートありがとうございます！
> 
> 非本質的なコメントですが、ブログでは、ローカライゼーションの貢献推進の一環として、以下のように "翻訳者" の項目を追加することができるそうです。（韓国語の例です）
> 
> https://github.com/kubernetes/website/blob/1d8cfb08dced46e5002697a23ed9f469d43a0eec/content/ko/blog/_posts/2022-05-13-grpc-probes-in-beta.md?plain=1#L10
> 
> > （機械翻訳）
> > **Translated by: Wonseok Song (Soka), Seokho Son (ETRI), Sanghong Kim (Kookmin University), Bo Bae Kim (11th Avenue)
> 
> もちろんこの項目の追加の有無は自由ですが、ご参考にしてください（追加していただける場合は、このPRのレビューを主に担当してくださったatoatoさんのお名前を追加していただくと良いかもしれないです; 韓国語ではそのようになっています FYI: #35280）

2024-04-08 11:27 UTC, b1gb4by commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +kubeletとローカルのKubernetes固有ストレージのベースパスは設定可能ですが、通常は`/var/lib/kubelet`と想定されています。
わかりました、では前者に書き直します！

2024-04-08 11:55 UTC, b1gb4by commented
> FYI: [#45749 (review)](https://github.com/kubernetes/website/pull/45749#pullrequestreview-1981062903)
> 
> > コントリビュートありがとうございます！
> > 非本質的なコメントですが、ブログでは、ローカライゼーションの貢献推進の一環として、以下のように "翻訳者" の項目を追加することができるそうです。（韓国語の例です）
> > https://github.com/kubernetes/website/blob/1d8cfb08dced46e5002697a23ed9f469d43a0eec/content/ko/blog/_posts/2022-05-13-grpc-probes-in-beta.md?plain=1#L10
> > 
> > > （機械翻訳）
> > > **Translated by: Wonseok Song (Soka), Seokho Son (ETRI), Sanghong Kim (Kookmin University), Bo Bae Kim (11th Avenue)
> > 
> > 
> > もちろんこの項目の追加の有無は自由ですが、ご参考にしてください（追加していただける場合は、このPRのレビューを主に担当してくださったatoatoさんのお名前を追加していただくと良いかもしれないです; 韓国語ではそのようになっています FYI: #35280）

ありがとうございます！
この場合って、以下のような書き方をすればよろしいのでしょうか？

```
翻訳者: 翻訳 太郎 (企業名)
```

それとも、ローマ字の方がよろしいのでしょうか？

2024-04-09 06:59 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +**Author:** Kevin Hannon (Red Hat)
```suggestion
**著者:** Kevin Hannon (Red Hat)
```

2024-04-09 07:00 UTC, Okabe-Junya commented
ありがとうございます、`翻訳者: 翻訳 太郎 (企業名)` のフォーマットで良いかと思います。合わせて、"Author"を"著者"の表記に変更をお願いします！

cc @kubernetes/sig-docs-ja-reviews どうでしょうか？？

2024-04-09 07:03 UTC, Okabe-Junya commented
すいません、もう一点補足で、

1. 氏名はGitHubのネームフィールド（e.g., Junya Okabe）。設定されていなければID （e.g., Okabe-Junya）
2. 所属は、GitHubのオーガナイゼーションフィールド（e.g., University of Tsukuba）。設定されていなければ無し

を記載するという形でどうでしょうか？？

2024-04-10 11:22 UTC, b1gb4by commented
> すいません、もう一点補足で、
> 
> 1. 氏名はGitHubのネームフィールド（e.g., Junya Okabe）。設定されていなければID （e.g., Okabe-Junya）
> 2. 所属は、GitHubのオーガナイゼーションフィールド（e.g., University of Tsukuba）。設定されていなければ無し
> 
> を記載するという形でどうでしょうか？？

@Okabe-Junya 
良いとおもいます！！
では、それに準拠した形で追記させていただきます。

2024-04-10 11:31 UTC, b1gb4by commented on content/ja/blog/_posts/2024-01-23-image-filesystem.md
> +**翻訳者:** Taisuke Okamoto (IDC Frontier Inc), Junya Okabe (University of Tsukuba), nasa9084 (LY Corporation)
GitHubのOrgフィールドから、企業名が分かる場合はその企業の英語表記にしています。

2024-04-12 13:58 UTC, Okabe-Junya approved these changes
/lgtm

2024-04-12 14:01 UTC, merged