[ja] Translate content/ja/docs/concepts/workloads/pods/disruptions.md into Japanese
kubernetes/website pull request #45162
Opened 2024-02-16 06:25 UTC by levi106

Fixes #45161

2024-02-17 04:28 UTC, Okabe-Junya commented
/cc @Okabe-Junya

2024-02-17 04:39 UTC, Okabe-Junya requested changes
コントリビュートありがとうございます :)

後ほど時間をとって確認させて頂きますが、取り急ぎ一点だけコメントさせて頂きますね。

2024-02-17 04:39 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +Podは誰か (人やコントローラー) が破壊するか、避けることができないハードウェアまたは
```suggestion
Podは誰か(人やコントローラー)が破壊するか、避けることができないハードウェアまたは
```

k/websiteでは、半角スペースを含まない決まりになっているので、修正をお願いします。他の箇所も同様にお願いします

ref. https://kubernetes.io/ja/docs/contribute/localization/#基本方針

> - スペースと括弧 `()` 、コロン `:` は半角、それ以外の記号類は全角で表記
> - 英単語と日本語の間に半角スペースは不要

2024-02-17 11:21 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +Podは誰か (人やコントローラー) が破壊するか、避けることができないハードウェアまたは
コメントありがとうございます。半角スペースを削除しました。
また、あらためて基本方針を確認し、「〜ので」と書かれたところがあったので「〜ため」に修正しました。

2024-02-23 14:45 UTC, Okabe-Junya requested changes
ありがとうございます。

長いページなので、レビューを前後半に分けて行わせてください。前半部分（`## Pod Disruption Budget` まで）を確認しました。後半部分は改めて確認します。

2024-02-24 01:29 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +アプリケーション所有者を対象としたものです。
@Okabe-Junya 
レビューありがとうございます。文単位で改行すると句点と次の間の文の間に空白が入ってしまうので、段落中は改行しない方がよいでしょうか。

<img width="731" alt="Screen Shot 2024-02-24 at 10 25 06" src="https://github.com/kubernetes/website/assets/16788901/1f55182f-c12a-44bd-84c0-0ccf0c833e4a">

2024-02-25 14:30 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +アプリケーション所有者を対象としたものです。
ありがとうございます :) 段落内でも文単位で改行していただいても良いでしょうか🙆‍♂️

もちろん半角スペースが挿入されない方が嬉しいのですが、それ以上にmdファイルの可読性が著しく悪くなってしまうためです。なので、

1. 読点 `。`では（必ず）改行する
2. 句点 `、`では改行しない

でお願いします

（余談: この辺りのルールがきちんと整備されていなかったので、#45037 で更新します。お手数おかけしました）

2024-02-25 17:16 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +アプリケーション所有者を対象としたものです。
ありがとうございます。
> 段落内でも文単位で改行していただいても良いでしょうか🙆‍♂️

こちら承知しました。

> （余談: この辺りのルールがきちんと整備されていなかったので、https://github.com/kubernetes/website/pull/45037 で更新します。お手数おかけしました）

"日本語文では、文章の途中で改行を行わない" に加えて

> 1.  読点 。では（必ず）改行する
> 2. 句点 、では改行しない

も明記いただい方がよいかなと思いました。

2024-02-26 13:42 UTC, Okabe-Junya commented
/label tide/merge-method-squash

2024-02-26 14:43 UTC, levi106 commented
@Okabe-Junya 
指摘いただいた点、修正しましたのでご確認お願いします。
- 改行は1文毎
- 日本語訳がある場合は日本語ドキュメントへリンク
- 英文にピリオドがないリストは句点を削除
- 先頭のコメントを削除

2024-03-01 14:08 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます〜〜

いくつかコメントさせて頂きました。"Disruption" の訳は非常に迷う部分なので、ご意見などあればコメントしてください :)

2024-03-01 14:08 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
cc @kubernetes/sig-docs-ja-reviews 

全体を通して、"Disruption" という言葉を訳すべきかどうかは難しいところですね。。個人的には訳さずママ表記で良いのではないかと思いました。サイト内のGlossary（標準化用語集）では以下のように定義されています。

ref. https://kubernetes.io/docs/reference/glossary/?fundamental=true#term-disruption

> Disruptions are events that lead to one or more [Pods](https://kubernetes.io/docs/concepts/workloads/pods/) going out of service. A disruption has consequences for workload resources, such as [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/), that rely on the affected Pods
> ...

抄訳: Disruptionは、1つ以上のPodのサービス停止につながるイベントのことです。Disruptionは、影響を受けたPodに依存しているDeploymentなどのワークロードリソースに影響を与えます。...

定義およびその抄訳から鑑みると、"Disruption" に何か直接的な訳語を与えるよりは、固有名詞として扱う方が良いように思いました。（逆説的ですが、一般名詞以上の意味を持たない用語はわざわざGlossaryに載せないのかなとも思いました）

2024-03-01 16:26 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +`node-1`から`node-3`まで3ノードあるクラスターを考えます。
ありがとうございます、修正します。

2024-03-01 16:28 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +`node-1`はcordonされたため、別のノードに展開されます。
ありがとうございます。
既存の翻訳されたページをみても基本的には cordon はそのまま記載されており、「封鎖」と翻訳されたページはありませんでした。なので cordon のままの方がよいかなと思いましたがいかがでしょうか。
https://kubernetes.io/ja/docs/tutorials/stateful-application/zookeeper/
https://kubernetes.io/ja/docs/concepts/architecture/nodes/
https://kubernetes.io/ja/docs/tasks/run-application/run-replicated-stateful-application/

2024-03-01 16:29 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +Pod Disruption Budgetはロール間のインターフェイスを提供することによって、この役割の分離をサポートします。
ありがとうございます、修正します。

2024-03-01 16:29 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +* ロールアウト中の可用性を維持するためのステップなど、[deploymentの更新](/ja/docs/concepts/workloads/controllers/deployment/#updating-a-deployment)について学んでください。
ありがとうございます、修正します。

2024-03-01 17:04 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +`node-1`はcordonされたため、別のノードに展開されます。
ありがとうございます :)

確かにおっしゃる通りですね。そのままの方が良さそうです 👍

2024-03-02 02:45 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +Conditionの`reason`フィールドにて、追加で以下のいずれかをPodの終了の理由として示します:
Condition が [PodCondition](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podcondition-v1-core) のことを指している場合は Condition にしてみました。
- `DisruptionTarget` というPodCondition のときの Condition
- PodCondition の`reason` フィールドのときの Condition
一方で Pod disruption condition の condition 自体は PodCondtion を指していないので条件と翻訳しました。

どちらかに統一するならば disruption を翻訳するのかそのままにするのかに依るかなと思いました。
disruption を翻訳する場合は Pod 中断 condition だと変な感じがするので condition を条件と翻訳する方向で統一
disruption を翻訳しない場合は、condition を翻訳してもしなくてもそれほど違和感はありませんが、Pod disruption 条件よりも Pod disruption condition の方がいいかもと思いました。

2024-03-02 04:37 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
ありがとうございます。Disruption を訳すかどうかは悩みましたが Glossary を確認していなかったので、一般名詞と判断して訳しました。
記載いただいた内容はなるほどなと思いましたので、一度 Disruption に変えてみて違和感が無いか確認してみます。
なお、訳さない場合はすべて大文字始まり (Disruption) でよいでしょうか？

2024-03-02 14:24 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
@levi106 

ありがとうございます！！

> 記載いただいた内容はなるほどなと思いましたので、一度 Disruption に変えてみて違和感が無いか確認してみます。

お手数をおかけしますが、その対応をしていただけると助かります。

> なお、訳さない場合はすべて大文字始まり (Disruption) でよいでしょうか？

こちらもおっしゃる通りで大丈夫です🙆‍♂️

2024-03-02 14:30 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +Conditionの`reason`フィールドにて、追加で以下のいずれかをPodの終了の理由として示します:
ありがとうございます ！

そうですね。別コメントで話している "Disruption" の表記にも依存しそうですが、

> Condition が PodCondition のことを指している場合は Condition にしてみました。

の判断指標で一貫性があるので、こちらで良さそうに感じました（ので、概ねそのままで良さそうです🙆‍♂️ ありがとうございます！！）。"Pod disruption condition" は "Pod（の）Disruptionの条件" のように、適宜助詞を補えば良さそうですかね。。？？

2024-03-03 07:37 UTC, levi106 commented
@Okabe-Junya 
指摘いただいた点、修正しました。
"condition" については Pod Disruption Condition の方が Pod Disruption Budge と合っているので訳さないことにしました。

2024-03-04 07:08 UTC, Okabe-Junya requested changes
修正ありがとうございます〜

almost LGTMですが、細かい表現の部分だけ修正していただけると嬉しいです :)

2024-03-04 07:08 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +## 自発的Disruptionと非自発的Disruption
```suggestion
## 自発的なDisruptionと非自発的なDisruption
```

他の箇所に合わせて「な」を入れた方が良いと思いました

2024-03-04 07:08 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +非自発的Disruptionを軽減する方法をいくつか紹介します:
```suggestion
非自発的なDisruptionを軽減する方法をいくつか紹介します:
```

ditto

2024-03-04 07:08 UTC, Okabe-Junya commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +[非自発的Disruption](#voluntary-and-involuntary-disruptions)はPDBによって防ぐことができません;
```suggestion
[非自発的なDisruption](#voluntary-and-involuntary-disruptions)はPDBによって防ぐことができません;
```

ditto

2024-03-04 07:08 UTC, Okabe-Junya commented
/assign nasa9084

2024-03-04 15:24 UTC, levi106 commented
@Okabe-Junya 
ありがとうございます。コメントいただいた点、修正しました。

2024-03-04 15:26 UTC, Okabe-Junya approved these changes
度々の修正ありがとうございます〜

LGTMです！！

2024-03-04 15:27 UTC, Okabe-Junya commented
/lgtm

2024-03-28 14:31 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +## PodDisruptionBudge の例 {#pdb-example}
ありがとうございます、これは修正漏れでした。

2024-03-28 14:36 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +例えば、クォーラムベースのアプリケーションでは、実行中のレプリカの数がクォーラムに必要な数を下回らないようにする必要があります。
ありがとうございます。
クォーラムと訳している他のドキュメントもあるので、「クォーラム」のままでどうでしょうか。
https://kubernetes.io/ja/docs/tutorials/stateful-application/zookeeper/#zookeeper

2024-03-28 14:56 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +PDBは、レプリケートされたアプリケーションのうち、自発的なDisruptionによって同時にダウンするPodの数を制限します。
他のドキュメントでは色々な書き方があるようでした。「複製された」は自然かなと思うのですが、「レプリカ」という言葉は普通に使うので、それと離れ過ぎているのが気になります。そうするとやはり「レプリカを持つ」がいいんでしょうか、、、

「レプリケートされた」
https://kubernetes.io/ja/docs/concepts/workloads/controllers/replicaset/#horizontalpodautoscaler-hpa-のターゲットとしてのreplicaset

「複製された」
https://kubernetes.io/ja/docs/tutorials/services/pods-and-endpoint-termination-flow/

「レプリカを持つ」
https://kubernetes.io/ja/docs/tasks/run-application/run-replicated-stateful-application/

2024-03-28 15:13 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +例えばクラスター管理者がカーネルのバグを修正するために、新しいカーネルバージョンにリブートしたいとします。
自分ではあまりこのような言い方をしないなと悩んだ文でした。
意訳であれば
「再起動して新しいカーネルバージョンにしたいとします。」
の方がしっくりくるのですが、こちらではどうでしょうか？

2024-03-30 16:18 UTC, levi106 commented
@Okabe-Junya , @nasa9084 
3 点修正しました
- レプリケートされた -> レプリカを持っている
- PodDisruptionBudge の例 -> PodDisruptionBudgeの例
- 新しいカーネルバージョンにリブートしたいとします。 -> 再起動して新しいカーネルバージョンにしたいとします。

2024-03-30 16:36 UTC, Okabe-Junya approved these changes
ありがとうございます〜！LGTMです

/lgtm

2024-04-01 15:43 UTC, nasa9084 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +例えばクラスター管理者がカーネルのバグを修正するために、新しいカーネルバージョンにリブートしたいとします。
それも良いと思います！

2024-04-01 15:44 UTC, nasa9084 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +## PodDisruptionBudgeの例 {#pdb-example}
```suggestion
## PodDisruptionBudgetの例 {#pdb-example}
```

修正を出しておいて全然気づかなかったんですがtypoに気づいてしまったので・・・すみません

2024-04-01 16:54 UTC, levi106 commented on content/ja/docs/concepts/workloads/pods/disruptions.md
> +## PodDisruptionBudgeの例 {#pdb-example}
すいません、私も修正する際に気づきませんでした、、、ありがとうございます。

2024-04-01 17:43 UTC, Okabe-Junya approved these changes
LGTMなので、改めて打ち直しますね ：）

/lgtm

2024-04-02 12:48 UTC, nasa9084 commented
対応ありがとうございます！！

/approve

2024-04-02 12:50 UTC, merged

2024-04-02 13:30 UTC, levi106 commented
何度もレビューありがとうございました！