Add information about validation.policy.admission.k8s.io/validation_f…
kubernetes/website pull request #45190
Opened 2024-02-18 05:19 UTC by prashant235913

…ailure annotation

tried solving according to the issue mentioned in https://github.com/kubernetes/website/issues/45187#issue-2140222281

2024-02-18 13:12 UTC, dipesh-rawat requested changes

2024-02-18 13:12 UTC, dipesh-rawat commented on content/en/docs/reference/labels-annotations-taints/_index.md
> +- [`validation.policy.admission.k8s.io/validation_failure`](docs/reference/labels-annotations-taints/audit-annotations/#validation-policy-admission-k8s-io-validation-failure)
Thank you for your contribution! However, the link to the newly added annotation isn't quite right, as it's leading to a 404 error ([see the build preview](https://deploy-preview-45190--kubernetes-io-main-staging.netlify.app/docs/reference/labels-annotations-taints/#annotations-used-for-audit)). Below I have provided suggestion for fixing it. Hope you find it helpful!

```suggestion
- [`validation.policy.admission.k8s.io/validation_failure`](/docs/reference/labels-annotations-taints/audit-annotations/#validation-policy-admission-k8s-io-validation-failure)
```

2024-02-18 13:15 UTC, dipesh-rawat commented
/retitle Register audit annotation for admission policy validation

2024-02-19 00:32 UTC, dipesh-rawat reviewed
Thank you for your contribution! The change looks good to me.
Congrats on your first PR 🎉

/lgtm

[Preview Page](https://deploy-preview-45190--kubernetes-io-main-staging.netlify.app/docs/reference/labels-annotations-taints/#annotations-used-for-audit)

2024-02-19 04:53 UTC, prashant235913 commented
> Thank you for your contribution! The change looks good to me. Congrats on your first PR 🎉
> 
> /lgtm
> 
> [Preview Page](https://deploy-preview-45190--kubernetes-io-main-staging.netlify.app/docs/reference/labels-annotations-taints/#annotations-used-for-audit)

Thanks @dipesh-rawat .......This contribution is helped by you so much...
Waiting for ur to get merged☺️.

2024-02-19 19:29 UTC, merged