[ja] translation `content/en/docs/reference/glossary/cluster-operations.md` into Japanese
kubernetes/website pull request #45227
Opened 2024-02-20 15:17 UTC by NaokiIkesaka

Fixes #45117

2024-02-21 04:56 UTC, Okabe-Junya commented
/cc @Okabe-Junya

2024-02-21 04:58 UTC, Okabe-Junya commented
The target page on the deploy preview site:

- https://deploy-preview-45227--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-cluster-operations

2024-02-21 05:07 UTC, Okabe-Junya requested changes
コントリビュートありがとうございます〜〜

Almost LGTMなのですが、一点だけ修正をお願いします

2024-02-21 05:07 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cluster-operations.md
> + Kubernetesクラスターの管理に関連する作業：日々の運用管理とアップグレードの調整。
```suggestion
 Kubernetesクラスターの管理に関連する作業: 日々の運用管理とアップグレードの調整。
```

k/websiteでは、コロン（`:`）は半角を用いることになっています

ref. https://kubernetes.io/ja/docs/contribute/localization/#基本方針

> スペースと括弧 () 、コロン : は半角、それ以外の記号類は全角で表記

2024-02-21 05:07 UTC, Okabe-Junya commented
/assign nasa9084

2024-02-21 05:08 UTC, Okabe-Junya commented
/retitle [ja] translation `content/en/docs/reference/glossary/cluster-operations.md` into Japanese

2024-02-21 10:37 UTC, NaokiIkesaka commented on content/ja/docs/reference/glossary/cluster-operations.md
> + Kubernetesクラスターの管理に関連する作業：日々の運用管理とアップグレードの調整。
申し訳ございません。確認不足でした。

2024-02-21 17:03 UTC, Okabe-Junya requested changes
修正ありがとうございます。

レビュー抜けで大変恐縮なのですが、もう一点だけ対応お願いしたいです。。

2024-02-21 17:03 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cluster-operations.md
> + クラスター管理作業の例は以下の通りです。クラスターをスケールするために新しいノードをデプロイすること、ソフトウェアのアップグレードを実行すること、セキュリティコントロールを実装すること、ストレージの追加または削除を行うこと、クラスターのネットワークを構成すること、クラスター全体のオブザーバビリティを管理すること、イベントに対応すること。
ですます体（敬体）の方が良さそうですね（標準化用語集のページは敬体と常体が混同しているんで、紛らわしいですね。。ルールに準拠する形で敬体にしましょうか）

ref. https://kubernetes.io/ja/docs/contribute/localization/#基本方針

> 本文を、敬体（ですます調）で統一

2024-02-22 07:30 UTC, Okabe-Junya commented
/label tide/merge-method-squash

2024-02-25 07:25 UTC, NaokiIkesaka commented on content/ja/docs/reference/glossary/cluster-operations.md
> + クラスター管理作業の例は以下の通りです。クラスターをスケールするために新しいノードをデプロイすること、ソフトウェアのアップグレードを実行すること、セキュリティコントロールを実装すること、ストレージの追加または削除を行うこと、クラスターのネットワークを構成すること、クラスター全体のオブザーバビリティを管理すること、イベントに対応すること。
その場合は、クラスター管理作業...対応することです。
と、最後にですを付けるくらいで問題ないでしょうか。

また、short_descriptionの部分も、
Kubernetesクラスターの管理に関連する作業
→Kubernetesクラスターの管理に関連する作業です。
と変更すべきということでしょうか。

その場合、
Kubernetesクラスターの管理に関連する作業:日々の運用管理とアップグレードの調整。
→Kubernetesクラスターの管理に関連する作業です。日々の運用管理とアップグレードの調整が含まれます。
とコロンを削除しても大丈夫でしょうか。元の英語にはコロンが含まれます。

2024-02-25 14:57 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cluster-operations.md
> + クラスター管理作業の例は以下の通りです。クラスターをスケールするために新しいノードをデプロイすること、ソフトウェアのアップグレードを実行すること、セキュリティコントロールを実装すること、ストレージの追加または削除を行うこと、クラスターのネットワークを構成すること、クラスター全体のオブザーバビリティを管理すること、イベントに対応すること。
> 最後にですを付けるくらいで問題ないでしょうか

問題ないです🙆‍♂️

> short_descriptionの部分も ... と変更すべきということでしょうか。

はい、お手数ですが変更をお願いします〜 🙏 

> とコロンを削除しても大丈夫でしょうか。元の英語にはコロンが含まれます。

こちらも全く問題ないです🙆‍♂️ お願いします

---

参考: 以下のページなどがある程度参考になると思います。

https://github.com/kubernetes/website/blob/main/content/ja/docs/reference/glossary/cluster.md?plain=1

2024-03-12 15:29 UTC, Okabe-Junya approved these changes
修正ありがとうございます〜！LGTMです〜

/lgtm

2024-03-27 11:43 UTC, nasa9084 reviewed
/approve

Thank you for your first contribution~!!! 🎉

2024-03-27 11:46 UTC, merged