[ar] Translate tutorials/kubernetes-basics/_index.html page to arabic
kubernetes/website pull request #45330
Opened 2024-02-25 10:26 UTC by seifrajhi

This PR adds the translation related to the tutorials basics  `/docs/tutorials/kubernetes-basics`.

Part of https://github.com/kubernetes/website/issues/44682

2024-02-25 11:52 UTC, seifrajhi commented
/EasyCLA

2024-02-26 03:31 UTC, adowair requested changes
Did a preliminary read and will leave my feedback+suggestios here soon. Thanks @seifrajhi for the efforts!

2024-02-26 13:14 UTC, dipesh-rawat commented
/language ar

2024-02-27 13:37 UTC, adowair requested changes
شكراً أخي سيف لجهودك، اقترحت عدة تغييرات في صياغة النص، و أجد أن قرائة النص الإنجليزي كاملاً قبل الترجمة يفيد في إنشاء جمل عربية أصيلة ذات تركيب مفهوم ومستساغ. أرجو إعادة النظر في بعض الصيغ حيث أنها تترك انطباع الترجمة الآلية. شاكراً جهودك مرة أخرى

Thanks @seifrajhi for the efforts! I've suggested some changes to the sentence structures—overallI think reading the English text fully before writing in Arabic will help in writing Arabic with more natural expressions.Let me know what you think. Thank you once more.

2024-02-27 13:37 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +            <p>مع خدمات الويب الحديثة، يتوقع المستخدمون توافر التطبيقات على مدار الساعة طوال الأسبوع، ويتوقع المطورون نشر نسخ جديدة من هذه التطبيقات عدة مرات في اليوم. تساعد تقنية التعبئة في تحقيق هذ
انظر بعض الآراء عن الفرق بين "تَوَفُر" و "تَوَافُر" [هنا](https://www.linkedin.com/pulse/%D9%85%D8%A7-%D8%A7%D9%84%D9%81%D8%B1%D9%82-%D8%A8%D9%8A%D9%86-%D8%AA%D9%88%D9%81%D8%B1-%D8%A7%D9%84%D8%AA%D9%88%D9%81%D8%B1-%D9%88%D8%AA%D9%88%D8%A7%D9%81%D8%B1-%D8%A7%D9%84%D8%AA%D9%88%D8%A7%D9%81%D8%B1-bashir-%D8%A3%D8%A8%D9%88%D8%A7%D9%84%D8%AD%D8%AC%D8%A7%D8%AC-%D8%A8%D8%B4%D9%8A%D8%B1/).

2024-02-27 13:37 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +            <p>مع خدمات الويب الحديثة، يتوقع المستخدمون توافر التطبيقات على مدار الساعة طوال الأسبوع، ويتوقع المطورون نشر نسخ جديدة من هذه التطبيقات عدة مرات في اليوم. تساعد تقنية التعبئة في تحقيق هذ
ارجو النظر في إعادة صياغة الجملة، ترتيب كلماتها الحالي يشبه الترجمة الآلية.

2024-02-27 13:37 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +                  <a href="/ar/docs/tutorials/kubernetes-basics/expose/expose-intro/"><h5>4. تعريض التطبيق للعموم</h5></a>
أرجو النظر في ترجمة expose هناك عدة خيارات.
```suggestion
                  <a href="/ar/docs/tutorials/kubernetes-basics/expose/expose-intro/"><h5>4. إبراز التطبيق خارج العنقود</h5></a>
```

2024-02-27 13:38 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +            <h2>ماذا يمكن لكوبيرنيتيس أن يفعل لك؟</h2>
أو ما شابه من جمل مستساغة...

2024-02-27 18:55 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +  title: المرور عبر الأساسيات.
أو ما شابه، هذا اقتراح لا أكثر، ولك القرار ☺️

2024-02-29 00:11 UTC, Arhell reviewed
/easycla

2024-03-30 13:43 UTC, adowair reviewed
شكراً أخي سيف، تركت بعض الملاحظات البسيطة، والنص الآن أرتب وأفضل بكثير

2024-03-30 13:43 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +            <p>نتناول في الدرس هذا أساسيات نظام كوبيرنيتيس لإدارة العناقيد. ينقسم الدرس إلى عدة وحدات،
```suggestion
            <p>نتناول في الدرس الآتي أساسيات كوبيرنيتيس، وهو نظام لإدارة العناقيد. ينقسم الدرس إلى عدة وحدات،
```

2024-03-30 13:43 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +            <p>من خلال البرامج التعليمية، يمكنك تعلم كيفية:</p>
```suggestion
            <p>يمكنك تعلم الآتي من خلال تلك البرامج:</p>
```

2024-03-30 13:43 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +            <p>مع خدمات الويب الحديثة، يتوقع المستخدمون توفر التطبيقات على مدار الساعة طوال أيام الأسبوع، ويتوقع المطورون نشر إصدارات جديدة من تلك التطبيقات عدة مرات في اليوم. تساعد تعبئة البرمجيات ف
```suggestion
            <p>مع خدمات الويب الحديثة، يتوقع المستخدمون توفر التطبيقات على مدار الساعة طوال أيام الأسبوع، ويتوقع المطورون نشر إصدارات جديدة من تلك التطبيقات عدة مرات في اليوم. تساعد تحوية البرامج  على تحقيق تلك الأهداف، ذلك لتمكين إصدار وتحديث التطبيقات دون توقف. يساعد كوبيرنيتيس في ضمان تشغيل تلك التطبيقات المحزمة حيثما وعندما ترغب، ويساعدها في العثور على الموارد والأدوات التي تحتاج إليها للعمل. كوبيرنيتيس هو منصة جاهزة للإنتاج، مفتوح المصدر، صُمِّمَ بخبرة جوجل المتراكمة في تنظيم الحاويات، بالإضافة إلى أفضل الأفكار من المجتمع.</p>
```

2024-04-10 05:52 UTC, adowair reviewed
Thank you @seifrajhi, I've given this paragraph some thought and think it could use these tweaks (last vote is yours). Otherwise this is perfect to merge.

2024-04-10 05:52 UTC, adowair commented on content/ar/docs/tutorials/kubernetes-basics/_index.html
> +            <p>مع خدمات الويب الحديثة، يتوقع المستخدمون توفر التطبيقات على مدار الساعة طوال أيام الأسبوع، ويتوقع المطورون نشر إصدارات جديدة من تلك التطبيقات عدة مرات في اليوم. تساعد تحوية البرامج  عل
```suggestion
            <p>في سياق تطبيقات الويب الحديثة، يتوقع المستخدمون توفر التطبيقات بشكل متواصل دون أعطال، وينشر المطورون إصدارات جديدة للتطبيقات بشكلٍ متاوصلً أيضاً. تساعد تحوية البرامج  على تحقيق تلك الأهداف، ذلك لتمكين إصدار وتحديث التطبيقات دون توقف. يساعد كوبيرنيتيس على ضمان عمل تلك التطبيقات المحزمة في المكان والوقت المرغوب، ويساعدها في العثور على الموارد والأدوات التي تحتاج إليها للعمل. كوبيرنيتيس هو مشروع جاهز للإنتاج، مفتوح المصدر، صُمِّمَ بخبرة جوجل المتراكمة في تنظيم الحاويات، بالإضافة إلى أفضل الأفكار من المجتمع.</p>
```

2024-04-10 20:49 UTC, adowair commented
/lgtm

/assign @mboukhalfa

2024-04-10 21:50 UTC, mboukhalfa commented
/approve

2024-04-10 21:55 UTC, merged