[es] localize content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md to Spanish
kubernetes/website pull request #45347
Opened 2024-02-26 15:10 UTC by jorge-oduber

/kind feature
/language es
/sig docs
/area localization
/assign @ramrodo @electrocucaracha

solves https://github.com/orgs/kubernetes/projects/97/views/1?pane=issue&itemId=54346875

2024-02-26 17:20 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +semántica de como máximo uno inherente a StatefulSet. Los StatefulSets pueden usarse para ejecutar aplicaciones distribuidas y
```suggestion
semántica de como máximo uno, inherente a StatefulSet. Los StatefulSets pueden usarse para ejecutar aplicaciones distribuidas y
```

2024-02-26 17:30 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +- El kubelet en el Nodo no responsivo comienza a responder, mata el Pod y elimina la entrada del apiserver.
```suggestion
- Kubelet, en el nodo no responsivo, comienza a responder, mata el Pod y elimina la entrada del apiserver.
```

2024-02-26 17:31 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +La mejor práctica recomendada es usar el primer o segundo enfoque. Si un Nodo está confirmado
```suggestion
La mejor práctica recomendada es usar el primer o segundo enfoque. Si un nodo está confirmado
```

2024-02-26 17:32 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +el objeto Node. Si el Nodo está sufriendo de una partición de red, entonces trata de resolver esto
```suggestion
el objeto Node. Si el nodo es afectado de una partición de red, entonces trata de resolver esto
```

2024-02-26 17:32 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +o espera a que se resuelva. Cuando la partición se cure, el kubelet completará la eliminación
```suggestion
o espera a que se resuelva. Cuando la partición se solucione, kubelet completará la eliminación
```

2024-02-26 17:33 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +el Nodo es eliminado por un administrador. Puedes anular esto forzando la eliminación del Pod.
```suggestion
Normalmente, el sistema completa la eliminación una vez que el Pod ya no se está ejecutando en un nodo, o
el nodo es eliminado por un administrador. Puedes anular esto forzando la eliminación del Pod.
```

2024-02-26 17:34 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +Las eliminaciones forzosas **no** esperan confirmación del kubelet de que el Pod ha sido terminado.
```suggestion
Las eliminaciones forzosas **no** esperan confirmación de kubelet de que el Pod ha sido terminado.
```

2024-02-26 17:35 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +Cuando eliminas forzosamente un pod de StatefulSet, estás afirmando que el Pod en cuestión nunca
```suggestion
Cuando eliminas forzosamente un Pod de StatefulSet, estás afirmando que el Pod en cuestión nunca
```

2024-02-26 17:35 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +eliminar el pod del clúster:
```suggestion
eliminar el Pod del clúster:
```

2024-02-26 20:20 UTC, ramrodo commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +El [controlador de StatefulSet](/docs/concepts/workloads/controllers/statefulset/) es responsable de
Ésta referencia al documento de `statefulset` [ya existe](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/workloads/controllers/statefulset.md), por lo que en este caso, debemos de colocar `es/` al inicio de la referencia para que redirija al término ya traducido al Español:

```suggestion
El [controlador de StatefulSet](/es/docs/concepts/workloads/controllers/statefulset/) es responsable de
```

2024-02-26 20:27 UTC, ramrodo commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +- El objeto Node es eliminado (ya sea por ti, o por el [Controlador de Nodo](/docs/concepts/architecture/nodes/#node-controller)).).
Ésta referencia al documento de `statefulset` [ya existe](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/architecture/nodes.md#controlador-de-nodos), por lo que en este caso, debemos de colocar `es/` al inicio de la referencia para que redirija al término ya traducido al Español:

```suggestion
- El objeto Node es eliminado (ya sea por ti, o por el [Controlador de Nodo](/es/docs/concepts/architecture/nodes/#controlador-de-nodos)).).
```

2024-02-26 20:30 UTC, ramrodo requested changes
¡Gracias por ésta contribución @jorge-oduber!

Algunas sugerencias solicitadas con respecto a referenciar documentos ya existentes y traducidos al Español.

2024-02-27 00:17 UTC, ramrodo commented
/lgtm

2024-02-27 16:54 UTC, krol3 commented on content/es/docs/tasks/run-application/force-delete-stateful-set-pod.md
> +## {{% heading "prerequisitos" %}}
```suggestion
## {{% heading "prerequisites" %}}
```
It's missing the header

2024-02-28 00:35 UTC, electrocucaracha commented
/lgtm

2024-02-28 16:53 UTC, ramrodo commented
/approve

2024-02-28 16:56 UTC, merged