[es] Added content/es/docs/tasks/manage-kubernetes-objects/kustomizat…
kubernetes/website pull request #45367
Opened 2024-02-27 15:42 UTC by parraletz

/kind feature
/language es
/sig docs
/area localization
/assign @ramrodo @electrocucaracha

resolves #[44740](https://github.com/kubernetes/website/issues/44740)

2024-02-28 19:15 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Desde la versión 1.14, Kubectl también admite la gestión de objetos de Kubernetes utilizando un archivo de kustomización. Para ver Recursos encontrados en un directorio que contiene un archivo de kus
Manejar los verbos en forma tú (en vez de usted):

```suggestion
Desde la versión 1.14, Kubectl también admite la gestión de objetos de Kubernetes utilizando un archivo de kustomización. Para ver Recursos encontrados en un directorio que contiene un archivo de kustomización, ejecuta el siguiente comando:
```

2024-02-28 19:15 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Para aplicar esos Recursos, ejecute `kubectl apply` con la bandera `--kustomize` o `-k` :
Manejar los verbos en forma tú (en vez de usted):

```suggestion
Para aplicar esos Recursos, ejecuta `kubectl apply` con la bandera `--kustomize` o `-k` :
```

2024-02-28 19:17 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +## Overview of Kustomize
```suggestion
## Descripción General de Kustomize
```

2024-02-28 19:25 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Remover línea en blanco extra

```suggestion
```

2024-02-28 19:27 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Para generar un ConfigMap desde un archivo env , añade una entrada en la lista de  `envs` en `configMapGenerator`. Aquí tienes un ejemplo de cómo generar un ConfigMap con un elemento de datos de un a
```suggestion
Para generar un ConfigMap desde un archivo env, añade una entrada en la lista de  `envs` en `configMapGenerator`. Aquí tienes un ejemplo de cómo generar un ConfigMap con un elemento de datos de un archivo `.env`:
```

2024-02-28 19:28 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Los ConfigMaps también pueden generarse a partir de pares clave-valor literales. Para generar un ConfigMap a partir de un par clave-valor literal, añade una entrada a la lista `literals` en configMap
```suggestion
Los ConfigMaps también pueden generarse a partir de pares clave-valor literales. Para generar un ConfigMap a partir de un par clave-valor literal, añade una entrada a la lista `literals` en configMapGenerator. Aquí hay un ejemplo de cómo generar un ConfigMap con un elemento de datos de un par clave-valor:
```

2024-02-28 19:31 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Para usar un ConfigMap generado en un Despliegue, refiérelo por el nombre del configMapGenerator. Kustomize reemplazará automáticamente este nombre con el nombre generado.
Manejar el nombre propio _Deployment_ del Inglés [referencia de la localización de _Deployment_ existente](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/workloads/controllers/deployment.md):

```suggestion
Para usar un ConfigMap generado en un Deployment, refiérelo por el nombre del configMapGenerator. Kustomize reemplazará automáticamente este nombre con el nombre generado.
```

2024-02-28 19:31 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Este es un ejemplo de un despliegue que utiliza un ConfigMap generado:
Manejar el nombre propio _Deployment_ del Inglés [referencia de la localización de _Deployment_ existente](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/workloads/controllers/deployment.md):

```suggestion
Este es un ejemplo de un deployment que utiliza un ConfigMap generado:
```

2024-02-28 19:32 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Al igual que los ConfigMaps, los Secrets generados pueden utilizarse en Despliegues refiriéndose al nombre del secretGenerator.
Manejar el nombre propio _Deployment_ del Inglés [referencia de la localización de _Deployment_ existente](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/workloads/controllers/deployment.md):

```suggestion
Al igual que los ConfigMaps, los Secrets generados pueden utilizarse en Deployments refiriéndose al nombre del secretGenerator.
```

2024-02-28 19:32 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Los Recursos de `kubectl kustomize ./` contienen tanto los objetos de Despliegue como los de Servicio.
Manejar el nombre propio _Deployment_ del Inglés [referencia de la localización de _Deployment_ existente](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/workloads/controllers/deployment.md):

```suggestion
Los Recursos de `kubectl kustomize ./` contienen tanto los objetos de Deployment como los de Servicio.
```

2024-02-28 19:32 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Los parches pueden usarse para aplicar diferentes personalizaciones a los Recursos. Kustomize admite diferentes mecanismos de parcheo a través de `patchesStrategicMerge` y `patchesJson6902`. `patches
Manejar el nombre propio _Deployment_ del Inglés [referencia de la localización de _Deployment_ existente](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/workloads/controllers/deployment.md):

```suggestion
Los parches pueden usarse para aplicar diferentes personalizaciones a los Recursos. Kustomize admite diferentes mecanismos de parcheo a través de `patchesStrategicMerge` y `patchesJson6902`. `patchesStrategicMerge` es una lista de rutas de archivo. Cada archivo debe resolverse en un [parche de fusión estratégica](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md). Los nombres dentro de los parches deben coincidir con los nombres de Recursos que ya están cargados. Se recomiendan pequeños parches que hagan una sola cosa. Por ejemplo, crear un parche para aumentar el número de réplicas del deployment y otro parche para establecer el límite de memoria.
```

2024-02-28 19:33 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Ejecuta el siguiente comando para aplicar el objeto de Despliegue `dev-my-nginx`:
Manejar el nombre propio _Deployment_ del Inglés [referencia de la localización de _Deployment_ existente](https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/workloads/controllers/deployment.md):

```suggestion
Ejecuta el siguiente comando para aplicar el objeto de Deployment `dev-my-nginx`:
```

2024-02-28 19:33 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +El Deployment generado hara referencia al  ConfigMap generado por nombre:
```suggestion
El Deployment generado hara referencia al ConfigMap generado por nombre:
```

2024-02-28 19:34 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:35 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +# Create a password.txt file
```suggestion
# Crea un archivo password.txt
```

2024-02-28 19:35 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:35 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:36 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:39 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:40 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +### Setting cross-cutting fields
```suggestion
### Establecer campos transversales
```

2024-02-28 19:41 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:42 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:43 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:43 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Kustomize ofrece la implementacion a travéz de  [JSON patch](https://tools.ietf.org/html/rfc6902) `patchesJson6902`.
```suggestion
Kustomize ofrece la implementacion a través de  [JSON patch](https://tools.ietf.org/html/rfc6902) `patchesJson6902`.
```

2024-02-28 19:43 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Ejecuta `kubectl kustomize ./` para ver que el campo  `replicas`  está actualizado:
```suggestion
Ejecuta `kubectl kustomize ./` para ver que el campo `replicas` está actualizado:
```

2024-02-28 19:45 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Dado que el nombre del Servicio puede cambiar a medida que se agrega `namePrefix` o `nameSuffix` en el archivo `kustomization.yaml`. No se recomienda codificar de manera fija el nombre del Service en
En las líneas posteriores se maneja _Service_ como nombre propio, entonces manejar aquí también la misma palabra para mantener consistencia:

```suggestion
Dado que el nombre del Service puede cambiar a medida que se agrega `namePrefix` o `nameSuffix` en el archivo `kustomization.yaml`. No se recomienda codificar de manera fija el nombre del Service en el argumento del comando. Para este uso, Kustomize puede inyectar el nombre del Service en los contenedores a través de vars.
```

2024-02-28 19:47 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Run `kubectl kustomize ./` to see that the Service name injected into containers is `dev-my-nginx-001`:
Remover ésta línea extra ya que se encuentra ya traducida justo abajo:

```suggestion
```

2024-02-28 19:48 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +## Bases and Overlays
```suggestion
## Bases y Superposiciones
```

2024-02-28 19:49 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:49 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco extra (en el artículo original no existe ninguna línea en blanco en ésta parte):

```suggestion
```

2024-02-28 19:50 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +
Eliminar una línea en blanco y solo dejar una de separación:

```suggestion
```

2024-02-28 19:51 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +Nota que `-k` debe apuntar a un directorio de kustomization, tal como
A pesar de que en el artículo original no vienen los ":" (dos puntos) me parece que podemos añadirlo aquí:

```suggestion
Nota que `-k` debe apuntar a un directorio de kustomization, tal como:
```

2024-02-28 19:58 UTC, ramrodo commented
@parraletz , could you update `solves #<issue-number>` to `fixes ...` or `closes ...`, please?. I made a mistake last time regarding which words should we use to link the PR with the issue. Here you can see the words accepted by GitHub:

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2024-02-29 19:02 UTC, ramrodo commented
/lgtm

2024-02-29 19:03 UTC, electrocucaracha requested changes
Muchas gracias @parraletz por tu contribución a la traducción de la documentación del sitio web, he dejado algunas observaciones al mismo, saludos

2024-02-29 19:03 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +## Kustomize Feature List
```suggestion
## Lista de funciones de Kustomize
```

2024-02-29 19:03 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +| namespace             | string                                                                                                       | Agregar namespace a todos los recursos
```suggestion
| namespace             | string                                                                                                       | Agrega Namespace a todos los recursos                                             |
```

2024-02-29 19:03 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/kustomization.md
> +| commonLabels          | map[string]string                                                                                            | Etiquetas para agregar a los  recursos y selectores.
```suggestion
| commonLabels          | map[string]string                                                                                            | Etiquetas para agregar a los recursos y selectores.                               |
```

2024-03-01 14:42 UTC, parraletz commented
> @parraletz , could you update `solves #<issue-number>` to `fixes ...` or `closes ...`, please?. I made a mistake last time regarding which words should we use to link the PR with the issue. Here you can see the words accepted by GitHub:
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

Ok, I've modified the PR message

2024-03-01 19:27 UTC, electrocucaracha commented
> > Muchas gracias @parraletz por tu contribución a la traducción de la documentación del sitio web, he dejado algunas observaciones al mismo, saludos
> 
> Gracias acepte las observaciones , saludos

@parraletz veo que existen algunas sugeriencias que aun no han sido aceptadas, puedes revisarlas por favor

2024-03-02 13:41 UTC, parraletz commented
> > > Muchas gracias @parraletz por tu contribución a la traducción de la documentación del sitio web, he dejado algunas observaciones al mismo, saludos
> > 
> > 
> > Gracias acepte las observaciones , saludos
> 
> @parraletz veo que existen algunas sugeriencias que aun no han sido aceptadas, puedes revisarlas por favor

Cierto, no había visto que estaban ocultas en la lista de sugerencias.

Gracias.

2024-03-05 16:52 UTC, electrocucaracha commented
/lgtm

2024-03-05 16:53 UTC, krol3 reviewed
Thanks @parraletz 
/approve

2024-03-05 16:57 UTC, krol3 commented
/approve

2024-03-05 17:01 UTC, merged