[ja] translate blog:kubernetes book cloub
kubernetes/website pull request #45364
Opened 2024-02-27 11:38 UTC by ystkfujii

2024-02-27 11:56 UTC, ystkfujii commented on content/ja/blog/_posts/2024-02-22-k8s-book-club/index.md
> +title: "Kubernetes読書会を覗く"
`Book Club`の訳に困り、一旦「読書会」と訳しています。  
他の選択肢としては、「輪読会」や「ブッククラブ」等があるかと思います。  
より良い訳語があれば、コメントいただけると助かります 🙇

2024-02-27 11:56 UTC, ystkfujii commented on content/ja/blog/_posts/2024-02-22-k8s-book-club/index.md
> +この成長と約束は、コミュニティにおける影響やKubernetes読書会の影響範囲に関して、私たちのCNCF加盟が肯定的な影響である明確な指標です。
`growth and engagement`を`成長と約束`と訳しています。  
ただ、「約束」で伝わるのか少し怪しい気がしており、より良い訳があればコメントいただけると助かります。

2024-02-27 11:59 UTC, ystkfujii commented
Edited page: https://deploy-preview-45364--kubernetes-io-main-staging.netlify.app/ja/blog/2024/02/22/k8s-book-club/

2024-02-29 02:48 UTC, Okabe-Junya commented
/cc Okabe-Junya

自分がレビュー引き取らせていただきますね :)

2024-02-29 02:49 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-02-22-k8s-book-club/index.md
> +title: "Kubernetes読書会を覗く"
cc @kubernetes/sig-docs-ja-reviews

2024-02-29 04:01 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます〜〜

何点かコメントさせていただきました。ご確認ください :)

2024-02-29 12:33 UTC, ystkfujii commented on content/ja/blog/_posts/2024-02-22-k8s-book-club/index.md
> +title: "Kubernetes読書会を覗く"
コメントありがとうございます 🙇 
ブッククラブで置換しました！

2024-02-29 12:33 UTC, ystkfujii commented on content/ja/blog/_posts/2024-02-22-k8s-book-club/index.md
> +この成長と約束は、コミュニティにおける影響やKubernetes読書会の影響範囲に関して、私たちのCNCF加盟が肯定的な影響である明確な指標です。
コメントありがとうございます 🙇
エンゲージメントで置換しました！

2024-02-29 12:35 UTC, ystkfujii commented
@Okabe-Junya 

コメントありがとうございます。対応したので再度ご確認をお願いします

2024-03-01 02:42 UTC, Okabe-Junya approved these changes
修正ありがとうございます。LGTMです〜

/lgtm

2024-03-01 02:44 UTC, Okabe-Junya commented
/remove-language zh
/label tide/merge-method-squash
/assign nasa9084 
/hold

@nasa9084 

PTAL https://github.com/kubernetes/website/pull/45364#discussion_r1504093487 :) After checking, fell free to remove hold

2024-03-10 14:46 UTC, Okabe-Junya commented
/retitle [ja] translate blog:kubernetes book club

2024-04-01 14:55 UTC, nasa9084 reviewed
/approve

2024-04-01 15:33 UTC, merged