[ja] Translate content/ja/docs/tasks/debug/debug-cluster/windows.md into Japanese
kubernetes/website pull request #45386
Opened 2024-02-29 03:09 UTC by levi106

Fixes #44988

2024-03-01 13:37 UTC, Okabe-Junya commented
/cc Okabe-Junya

（レビューまでちょっとお時間いただくかもしれません）

2024-03-10 19:04 UTC, Okabe-Junya requested changes
@levi106 

丁寧で継続的なコントリビューションをありがとうございます！

お時間いただきましたが、レビューさせていただいたのでご確認ください〜

2024-03-10 19:04 UTC, Okabe-Junya commented on content/ja/docs/tasks/debug/debug-cluster/windows.md
> +   (管理者シェルで)次のコマンドを実行しても結果が返されない場合、-kubeletが動作するために必要な前提条件である-仮想ネットワークの作成に失敗しています。
IMO: 原文では `— a necessary prerequisite for the kubelet to work — ` となっていますが、日本語表記では `—` は用いないで翻訳した方が良いと感じました

2024-03-10 19:04 UTC, Okabe-Junya commented
/assign nasa9084

2024-03-11 12:23 UTC, levi106 commented
@Okabe-Junya 
レビューありがとうございます。変更点が少なかったので amend して commit を一つにまとめました。
ご確認お願いします。

2024-03-11 12:28 UTC, levi106 commented on content/ja/docs/tasks/debug/debug-cluster/windows.md
> +   Podが[互換性](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/version-compatibility)のあるWindowsノードにスケジュールされていることを確認してください。
> リンク先に（多分機械翻訳ですが）日本語訳が存在するので、そちらに遷移するようにお願いします。

(関係ない話ではありますが) ページソースをみると `<meta name="ms.translationtype" content="HT" />` と書かれているので、おそらくこれは人による翻訳です (機械翻訳ならば通常は MT)。

2024-03-11 16:18 UTC, Okabe-Junya commented on content/ja/docs/tasks/debug/debug-cluster/windows.md
> +   Podが[互換性](https://docs.microsoft.com/virtualization/windowscontainers/deploy-containers/version-compatibility)のあるWindowsノードにスケジュールされていることを確認してください。
そうなんですね。。存じ上げませんでした、ありがとうございます〜（MS/GitHubなどのドキュメントは勝手に機械翻訳だと思っていました。。）

いずれにしても、修正いただきありがとうございました :)

2024-03-11 16:20 UTC, Okabe-Junya approved these changes
LGTMです〜！いつもありがとうございます〜

/lgtm

2024-03-11 16:22 UTC, Okabe-Junya commented
> 変更点が少なかったので amend して commit を一つにまとめました。

余談ですが、k/website（や他のkubernetes kubernetes-sigs配下のrepo）では、`/label tide/merge-method-squash` とコメントすることで commit merge を squash and merge に変更することができるので、もしよければご活用ください〜

多分手元でamend なり squashするより楽だと思います（あとレビューするときちょっと楽だったりします〜）

2024-03-11 16:53 UTC, levi106 commented
レビューありがとうございました。

> 余談ですが、k/website（や他のkubernetes kubernetes-sigs配下のrepo）では、/label tide/merge-method-squash とコメントすることで commit merge を squash and merge に変更することができるので、もしよければご活用ください〜

ありがとうございます。次回以降使ってみます。

2024-03-27 11:38 UTC, nasa9084 reviewed
ありがとうございます！！

/approve

2024-03-27 11:38 UTC, merged