[ja] Translate reference/glossary/cluster-architect.md
kubernetes/website pull request #45408
Opened 2024-03-01 16:15 UTC by rmiki

add: content/ja/docs/reference/glossary/cluster-architect.md

close #45115

2024-03-01 16:29 UTC, dipesh-rawat reviewed
@rmiki I see the bot has added `do-not-merge/invalid-commit-message` as the [commit message](https://github.com/kubernetes/website/pull/45408/commits/e08a0c8c628249eafedadfbf11f45daf8754022a) has "close https://github.com/kubernetes/website/issues/45115" ([Blocked Keywords Guide](https://www.kubernetes.dev/docs/guide/pull-requests/#do-not-use-github-keywords-or-mentions-within-your-commit-message)). Refer bot's message below:

> The list of commits with invalid commit messages:
[e08a0c8](https://github.com/kubernetes/website/commits/e08a0c8c628249eafedadfbf11f45daf8754022a) [ja] Translate reference/glossary/cluster-architect.md

Would you be able to edit the commit message to remove the [Blocked Keyword](https://www.kubernetes.dev/docs/guide/pull-requests/#do-not-use-github-keywords-or-mentions-within-your-commit-message) in order to move this PR forward?

2024-03-02 12:14 UTC, rmiki commented
@dipesh-rawat

Thank you for comment. I'll remove it.

2024-03-02 14:32 UTC, Okabe-Junya commented
/cc Okabe-Junya

2024-03-02 14:36 UTC, Okabe-Junya commented
/assign nasa9084

2024-03-02 14:40 UTC, Okabe-Junya requested changes
Thank you for your contribution!!

I have some nits, so please check it out :)

2024-03-02 14:40 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cluster-architect.md
> +  一つ以上のKubernetesクラスターで構成されるインフラストラクチャーを設計する人
```suggestion
  一つ以上のKubernetesクラスターで構成されるインフラストラクチャーを設計する人。
```

Please add "。"

2024-03-02 14:40 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cluster-architect.md
> + 一つ以上のKubernetesクラスターで構成されるインフラストラクチャーを設計する人
```suggestion
 一つ以上のKubernetesクラスターで構成されるインフラストラクチャーを設計する人。
```

ditto

2024-03-02 14:41 UTC, Okabe-Junya commented
/assign nasa9084

2024-03-02 15:04 UTC, Okabe-Junya approved these changes
Thank you for updating!!

/lgtm

2024-03-02 15:05 UTC, Okabe-Junya commented
/label tide/merge-method-squash

2024-03-27 11:18 UTC, nasa9084 reviewed
Thank you for your first contribution!! :tada:
Sorry for late review... 🙇 

/approve

2024-03-27 11:18 UTC, merged