Update cri-dockerd links to point to the official docs
kubernetes/website pull request #45480
Opened 2024-03-08 16:14 UTC by nwneisen

We get a lot of questions around the installation of cri-dockerd in the repo. We've found that many of the questions come from users being linked to the repo from the kubernetes docs and then they try to use the development installation method when they are not developers.

We now have an official documentation page that provides a straightforward installation using the different packages available. This PR is to update the links in the website so users get directed to the official docs rather than the repo.

2024-03-08 16:27 UTC, stmcginnis commented
Looks like a lot of unrelated changes. Some  are good, but it would be better to keep this focused on the primary change.

Also, policy is to only update one language at a time. Can you start with updating the English pages. Then follow up PRs can update the translations.

2024-03-08 16:54 UTC, sftim requested changes
We'll need to restrict this change to one language (English), following our usual contribution process.

/hold

OK to unhold once this only touches `en` content.

2024-03-08 16:54 UTC, sftim commented on content/en/blog/_posts/2022-03-31-ready-for-dockershim-removal.md
Hold on.
Please minimise changes made to this published page (avoid whitespace updates), and mark any changes made after publication.

2024-03-08 18:46 UTC, stmcginnis commented
/lgtm

Thanks!

2024-03-09 02:31 UTC, dipesh-rawat commented
/remove-language hi
/remove-language ja
/remove-language ko
/remove-language pt
/remove-language zh

2024-03-09 02:32 UTC, dipesh-rawat commented
/unhold
PR now targets only single language `en`.

2024-03-09 12:00 UTC, sftim approved these changes
These changes look OK to make

2024-03-09 12:05 UTC, merged