Translate define-command-argument-container.md into Japanese
kubernetes/website pull request #45545
Opened 2024-03-14 08:01 UTC by EigoOda

Closes: https://github.com/kubernetes/website/issues/45343

2024-04-11 00:33 UTC, EigoOda commented
/label tide/merge-method-squash

2024-04-16 10:07 UTC, Okabe-Junya commented
@atoato88

If you haven't started reviewing yet, I will check this pr. thank you

2024-04-16 10:09 UTC, Okabe-Junya commented
The target page on the deploy preview:

- https://deploy-preview-45545--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/inject-data-application/define-command-argument-container/

2024-04-23 04:51 UTC, Okabe-Junya commented
I will check this pr, thanks!!

/cc

2024-04-23 08:14 UTC, Okabe-Junya requested changes
継続的な貢献ありがとうございます！何点かコメントさせて頂きました。ご確認頂ければと思います！

2024-04-23 08:15 UTC, Okabe-Junya commented
/area localization
/assign nasa9084

2024-04-23 12:11 UTC, EigoOda commented on content/ja/docs/tasks/inject-data-application/define-command-argument-container.md
> +つまり、[ConfigMaps](/docs/tasks/configure-pod-container/configure-pod-configmap/)や[Secrets](/docs/concepts/configuration/secret/)など、環境変数を定義するために利用可能なテクニックのどれを使っても、Podの引数を定義できるということです。
'技術'と訳しました

2024-04-23 12:22 UTC, EigoOda commented
@Okabe-Junya 
レビュー、suggestion ありがとうございます！修正しました

2024-04-23 12:33 UTC, Okabe-Junya approved these changes
ご対応ありがとうございます！LGTMです！

/lgtm

2024-04-23 15:40 UTC, nasa9084 reviewed
/approve

2024-04-23 15:46 UTC, merged