translate setup/production-environment/tools/_index.md
kubernetes/website pull request #45574
Opened 2024-03-16 22:29 UTC by essamgouda97

Added translation for `setup/production-environment/tools/_index.md`

2024-03-16 22:32 UTC, essamgouda97 commented
/language ar

2024-03-17 00:15 UTC, dipesh-rawat commented
/retitle [ar] Localize setup/production-environment/tools/_index.md

2024-03-20 07:52 UTC, mboukhalfa commented
/approve

2024-04-10 06:25 UTC, adowair reviewed
Thank you @essamgouda97, I've suggested one major change to reword the last paragraph. Otherwise some minor nits and updating the spelling of "kubernetes" to match the [latest standard](https://github.com/kubernetes/website/issues/45078).

2024-04-10 06:25 UTC, adowair commented on content/ar/docs/setup/production-environment/tools/_index.md
> +- [kubespray](https://kubespray.io/): مجموعة من السكربتات الخاصة  [بانسيبل](https://docs.ansible.com/)، [الجرد](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md#inventory)، أد
```suggestion
مزيج من مكونات إدارة البنية التحتية للعناقيد، بما في ذلك مجموعة الأوامر، و[قوائم المحتوى](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md#inventory)، وأدوات التوفير، والمعرفة المجالية، الخاصة ب[أنسيبل](https://docs.ansible.com/). يمكنك التواصل مع مجتمع kubespray على .سلاك ([#kubespray](https://kubernetes.slack.com/messages/kubespray/))
```

2024-04-28 11:28 UTC, adowair requested changes
One minor nit, but otherwise looks good

2024-04-28 11:28 UTC, adowair commented on content/ar/docs/setup/production-environment/tools/_index.md
> +مزيج من مكونات إدارة البنية التحتية للعناقيد، بما في ذلك مجموعة الأوامر، و[قوائم المحتوى](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md#inventory)، وأدوات التوفير، والمعرفة
Looks like a list sign is missing
```suggestion
- مزيج من مكونات إدارة البنية التحتية للعناقيد، بما في ذلك مجموعة الأوامر، و[قوائم المحتوى](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/ansible.md#inventory)، وأدوات التوفير، والمعرفة المجالية، الخاصة ب[أنسيبل](https://docs.ansible.com/). يمكنك التواصل مع مجتمع kubespray على .سلاك ([#kubespray](https://kubernetes.slack.com/messages/kubespray/))
```

2024-05-02 15:43 UTC, adowair commented
/lgtm

2024-05-02 15:46 UTC, merged