[es] Added concepts/services-networking/endpoint-slices.md to Spanish
kubernetes/website pull request #45609
Opened 2024-03-19 20:11 UTC by eduardoSalazarCarrillo

/kind feature
/language es
/sig docs
/area localization

/assign @ramrodo @electrocucaracha

resolves https://github.com/kubernetes/website/issues/45441

2024-03-27 14:44 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +  La API EndpointSlice es el mecanismo que Kubernetes utiliza para permitir que tu Servicio
```suggestion
  La API de EndpointSlice es el mecanismo que Kubernetes utiliza para permitir que tu Servicio

```

2024-03-27 14:56 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +La API _EndpointSlice_ de Kubernetes proporciona una forma de rastrear los endpoints de red dentro de un clúster Kubernetes. EndpointSlices ofrece una alternativa más escalable y extensible a [Endpoi
```suggestion
La API de _EndpointSlice_ de Kubernetes proporciona una forma de rastrear los endpoints de red dentro de un clúster Kubernetes. EndpointSlices ofrece una alternativa más escalable y extensible a [Endpoints].(/docs/concepts/services-networking/service/#endpoints).

```

2024-03-27 14:58 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +## EndpointSlice API {#recurso endpointslice}
Añadir un guión medio (en vez de espacios) en las referencias tipo `{#abc-xyz}` para que puedan ser referenciadas correctamente.

```suggestion
## EndpointSlice API {#recurso-endpointslice}
```

2024-03-27 15:04 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +En Kubernetes, un EndpointSlice contiene referencias a un conjunto de puntos endpoints. El plano de control crea automáticamente EndpointSlices para cualquier Servicio Kubernetes que tenga especifica
```suggestion
En Kubernetes, un EndpointSlice contiene referencias a un conjunto de endpoints de red. El plano de control crea automáticamente EndpointSlices para cualquier Servicio de Kubernetes que tenga especificado un {{< glossary_tooltip text="selector" term_id="selector" >}}. Estos EndpointSlices incluyen referencias a todos los Pods que coinciden con el selector de Servicio. Los EndpointSlices agrupan los endpoints de la red mediante combinaciones únicas de protocolo, número de puerto y nombre de Servicio.
```

2024-03-27 18:26 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +A modo de ejemplo, a continuación se muestra un objeto EndpointSlice de ejemplo, propiedad del servicio  `example`
```suggestion
A modo de ejemplo, a continuación se muestra un objeto EndpointSlice de ejemplo, propiedad del servicio `example`
```

2024-03-27 18:27 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +Servicio Kubernetes.
La palabra _servicio_ está duplicado:

```suggestion
de Kubernetes.
```

2024-03-27 18:31 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +En la mayoría de los casos de uso, los EndpointSlices son propiedad del Servicio para el que el objeto EndpointSlices rastrea los endpoints. Esta propiedad se indica mediante una referencia de propie
```suggestion
En la mayoría de los casos de uso, los EndpointSlices son propiedad del Servicio para el que el objeto EndpointSlices rastree los endpoints. Esta propiedad se indica mediante una referencia de propietario en cada EndpointSlice, así como una etiqueta `kubernetes.io/service-name` que permite búsquedas sencillas de todos los EndpointSlices que pertenecen a un Servicio.

```

2024-03-27 18:36 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +The control plane mirrors Endpoints resources unless:
Eliminar ésta oración en inglés que está de más:

```suggestion
The control plane mirrors Endpoints resources unless:
```

2024-03-27 18:39 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +Puede encontrar una implementación de referencia sobre cómo realizar esta agregación y deduplicación de endpoints como parte del código `EndpointSliceCache` dentro de `kube-proxy`.
```suggestion
Puedes encontrar una implementación de referencia sobre cómo realizar esta agregación y deduplicación de endpoints como parte del código `EndpointSliceCache` dentro de `kube-proxy`.
```

2024-03-27 18:46 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +La API Endpoints original proporcionaba una forma simple y directa de rastrear los puntos finales de red en Kubernetes. A medida que los clústeres de Kubernetes y {{< glossary_tooltip text="Services"
```suggestion
La API Endpoints original proporcionaba una forma simple y directa de rastrear los puntos finales de red en Kubernetes. A medida que los clústeres de Kubernetes y los {{< glossary_tooltip text="Services" term_id="service" >}} crecían para manejar más tráfico y enviar más tráfico a más Pods backend, las limitaciones de la API original se hicieron más visibles.
```

2024-03-27 18:47 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +* Lea la [Referencia API](/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1/) for the EndpointSlice API
```suggestion
* Lea la [Referencia API](/docs/reference/kubernetes-api/service-resources/endpoint-slice-v1/) para la API EndpointSlice
```

2024-03-27 18:48 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +* Siga las instrucciones de [Conexión de aplicaciones con servicios](/docs/tutorials/services/connect-applications-service/) tutorial
```suggestion
* Sigue las instrucciones de [Conexión de aplicaciones con servicios](/docs/tutorials/services/connect-applications-service/) tutorial
```

2024-03-27 18:48 UTC, ramrodo commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +* Lea la [Referencia API](/docs/reference/kubernetes-api/service-resources/endpoints-v1/) for the Endpoints API
```suggestion
* Lee la [Referencia API](/docs/reference/kubernetes-api/service-resources/endpoints-v1/) para la API Endpoints
```

2024-03-27 18:49 UTC, ramrodo requested changes
Great! Thanks for this contribution.

I left some suggestions.

2024-03-28 00:29 UTC, ramrodo commented
/lgtm

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +  escale para manejar un gran número de backends, y permite que el cluster actualice tu lista de
```suggestion
  escale para manejar un gran número de backends, y permite que el clúster actualice tu lista de 

```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +y extensible a [Endpoints].(/docs/concepts/services-networking/service/#endpoints).
```suggestion
y extensible a [Endpoints](/docs/concepts/services-networking/service/#endpoints).

```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +* `zone` - La zona en la que se encuentra este punto final.
```suggestion
* `zone` - La zona en la que se encuentra este endpoint.

```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +* El recurso de servicio correspondiente no existe.
```suggestion
* El recurso Service correspondiente no exista.
```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +Con kube-proxy ejecutándose en cada Nodo y vigilando los EndpointSlices, cada cambio en un EndpointSlice se vuelve relativamente caro ya que será transmitido a cada Nodo del cluster. Este enfoque pre
```suggestion
Con kube-proxy ejecutándose en cada Nodo y vigilando los EndpointSlices, cada cambio en un EndpointSlice se vuelve relativamente caro ya que será transmitido a cada Nodo del clúster. Este enfoque pretende limitar el número de cambios que necesitan ser enviados a cada Nodo, incluso si puede resultar con múltiples EndpointSlices que no están llenos.

```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +En la práctica, esta distribución menos que ideal debería ser poco frecuente. La mayoría de los cambios procesados por el controlador EndpointSlice serán lo suficientemente pequeños como para caber e
```suggestion
En la práctica, esta distribución menos que ideal debería ser poco frecuente. La mayoría de los cambios procesados por el controlador EndpointSlice serán lo suficientemente pequeños como para caber en un EndpointSlice existente, y si no, es probable que pronto sea necesario un nuevo EndpointSlice de todos modos. Las actualizaciones continuas de los Deployments también proporcionan un reempaquetado natural de los EndpointSlices con todos los Pods y sus correspondientes endpoints siendo reemplazados.

```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +La API Endpoints original proporcionaba una forma simple y directa de rastrear los puntos finales de red en Kubernetes. A medida que los clústeres de Kubernetes y los {{< glossary_tooltip text="Servi
```suggestion
La API Endpoints original proporcionaba una forma simple y directa de rastrear los endpoints de red en Kubernetes. A medida que los clústeres de Kubernetes y los {{< glossary_tooltip text="Services" term_id="service" >}} crecían para manejar más tráfico y enviar más tráfico a más Pods backend, las limitaciones de la API original se hicieron más visibles.
```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +Dado que todos los puntos finales de red para un Servicio se almacenaban en un único objeto Endpoints, esos objetos Endpoints podían llegar a ser bastante grandes. Para los servicios que permanecían
```suggestion
Dado que todos los endpoints de red para un Servicio se almacenaban en un único objeto Endpoint, esos objetos Endpoints podían llegar a ser bastante grandes. Para los Services que permanecían estables (el mismo conjunto de puntos finales durante un largo período de tiempo), el impacto era menos notable; incluso entonces, algunos casos de uso de Kubernetes no estaban bien servidos.
```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +Cuando un servicio tenía muchos puntos finales de backend y la carga de trabajo se escalaba con frecuencia o se introducían nuevos cambios con frecuencia, cada actualización del objeto Endpoints para
```suggestion
Cuando un Service tenía muchos Endpoints de backend y la carga de trabajo se escalaba con frecuencia o se introducían nuevos cambios con frecuencia, cada actualización del objeto Endpoint para ese Service suponía mucho tráfico entre los componentes del clúster de Kubernetes (dentro del plano de control y también entre los nodos y el servidor de API). Este tráfico adicional también tenía un coste en términos de uso de la CPU.
```

2024-04-08 19:29 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +Aunque `serving` es casi idéntico a `ready`, se añadió para evitar romper el significado existente de `ready`. Podría ser inesperado para los clientes existentes si `ready` pudiera ser `true` para lo
```suggestion
Aunque `serving` es casi idéntico a `ready`, se añadió para evitar romper el significado existente de `ready`. Podría ser inesperado para los clientes existentes si `ready` pudiera ser `true` para los endpoints de terminación, ya que históricamente los endpoints de terminación nunca se incluyeron en la API Endpoints o EndpointSlice para empezar. Por esta razón, `ready` es _siempre_ `false` para los Endpoints que terminan, y se ha añadido una nueva condición `serving` en la v1.20 para que los clientes puedan realizar un seguimiento de la disponibilidad de los pods que terminan independientemente de la semántica existente para `ready`.
```

2024-04-08 20:03 UTC, electrocucaracha commented on content/es/docs/concepts/services-networking/endpoint-slices.md
> +Dado que todos los endpoints de red para un Servicio se almacenaban en un único objeto Endpoint, esos objetos Endpoints podían llegar a ser bastante grandes. Para los Services que permanecían estable
```suggestion
Dado que todos los endpoints de red para un Servicio se almacenaban en un único objeto Endpoint, esos objetos Endpoints podían llegar a ser bastante grandes. Para los Services que permanecían estables (el mismo conjunto de endpoints durante un largo período de tiempo), el impacto era menos notable; incluso entonces, algunos casos de uso de Kubernetes no estaban bien servidos.

```

2024-04-08 20:33 UTC, electrocucaracha commented
/lgtm

2024-04-08 22:02 UTC, ramrodo commented
Thanks!
/approve

2024-04-08 22:06 UTC, merged