Enhancing troubleshoot section with Windows Operational Readiness
kubernetes/website pull request #45612
Opened 2024-03-19 23:57 UTC by knabben

Adding  Windows operational Readiness instructions for troubleshooting and Windows cluster validation

2024-03-20 08:13 UTC, sftim commented
/sig windows

2024-03-20 08:16 UTC, sftim requested changes
Hi. The change being added _isn't_ a troubleshooting guide, and the section being added isn't a deployment tool.

Would you be willing to revise further @knabben?

2024-03-20 08:16 UTC, sftim commented on content/en/docs/concepts/windows/intro.md
> +which introduces a structured test suite. This suite is split into two sets of tests,
```suggestion
The Kubernetes project provides a _Windows Operational Readiness_ specification,
accompanied by structured test suite. This suite is split into two sets of tests,
```

2024-03-20 13:22 UTC, knabben commented
Moving it as a subsection of get help and troubleshooting.

2024-03-20 17:07 UTC, geetikabatra commented
LGTM

2024-03-21 06:38 UTC, sftim reviewed
LGTM for docs, with a quibble

Can we get a technical review from SIG Windows as well?

2024-03-21 06:39 UTC, sftim commented
@geetikabatra - was your LGTM on behalf of SIG Windows?

2024-03-21 06:49 UTC, geetikabatra commented
@sftim Yep

2024-03-21 06:59 UTC, sftim commented
/approve

2024-03-22 01:17 UTC, sftim commented
/lgtm

2024-03-22 01:21 UTC, merged