Added content: content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
kubernetes/website pull request #45629
Opened 2024-03-21 21:53 UTC by SerDigital

/kind feature
/language es
/sig docs
/area localization
/assign 
@ramrodo
 
@electrocucaracha

resolves #44739

2024-03-28 01:01 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +title: Administración imperativa de objetos de Kubernetes mediante archivos de configuración
Usar PascalCase como en el archivo original en Inglés:

```suggestion
title: Administración Imperativa de Objetos de Kubernetes Mediante Archivos de Configuración
```

2024-03-28 01:04 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Consulte [Administración de objetos de Kubernetes](/docs/concepts/overview/working-with-objects/object-management/)
```suggestion
Consulta [Administración de objetos de Kubernetes](/docs/concepts/overview/working-with-objects/object-management/)
```

2024-03-28 01:05 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Consulte la [referencia de la API de Kubernetes](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)
```suggestion
Consulta la [referencia de la API de Kubernetes](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)
```

2024-03-28 01:06 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +archivo. Los campos administrados de forma independiente deben copiarse en
```suggestion
campo `externalIPs` se administra independientemente del archivo de
configuración. Los campos administrados de forma independiente deben copiarse en 
```

2024-03-28 01:06 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Puede usar `kubectl replace -f` para actualizar un objeto en activo de acuerdo con un archivo de configuración.
```suggestion
Puedes usar `kubectl replace -f` para actualizar un objeto en activo de acuerdo con un archivo de configuración.
```

2024-03-28 01:07 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Puede usar `kubectl delete -f` para eliminar un objeto que se describe en un
```suggestion
Puedes usar `kubectl delete -f` para eliminar un objeto que se describe en un
```

2024-03-28 01:08 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Puede usar `kubectl get -f` para ver información sobre un objeto que está
```suggestion
Puedes usar `kubectl get -f` para ver información sobre un objeto que está
```

2024-03-28 01:08 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +La bandera `-o yaml` especifica que se imprime la configuración completa del objeto. Utilice `kubectl get -h` para ver una lista de opciones.
```suggestion
La bandera `-o yaml` especifica que se imprime la configuración completa del objeto. Utiliza `kubectl get -h` para ver una lista de opciones.
```

2024-03-28 01:08 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Los comandos `create`, `replace`, y `delete` funcionan bien cuando la configuración de cada objeto está completamente definida y registrada en su archivo de configuración. Sin embargo, cuando se actu
```suggestion
Los comandos `create`, `replace` y `delete` funcionan bien cuando la configuración de cada objeto está completamente definida y registrada en su archivo de configuración. Sin embargo, cuando se actualiza un objeto activo y las actualizaciones no se combinan en su archivo de configuración las actualizaciones se perderán la próxima vez que se ejecute un `replace`. Esto puede suceder si un controlador, como un HorizontalPodAutoscaler, realiza actualizaciones directamente a un objeto en activo. 
```

2024-03-28 01:11 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Los comandos `create`, `replace`, y `delete` funcionan bien cuando la configuración de cada objeto está completamente definida y registrada en su archivo de configuración. Sin embargo, cuando se actu
También separar éste párrafo con saltos de línea:

```suggestion
Los comandos `create`, `replace`, y `delete` funcionan bien cuando la configuración de cada objeto
está completamente definida y registrada en su archivo
de configuración. Sin embargo, cuando se actualiza un objeto activo y las actualizaciones no se combinan
en su archivo de configuración las actualizaciones se perderán la próxima vez que
se ejecute un `replace`. Esto puede suceder si un controlador, como un
HorizontalPodAutoscaler, realiza actualizaciones directamente a un objeto en activo. 
```

2024-03-28 01:11 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Si necesita admitir varios escritores en el mismo objeto, puede usar `kubectl apply` para administrar el objeto.
```suggestion
Si necesitas admitir varios escritores en el mismo objeto, puede usar `kubectl apply` para administrar el objeto.
```

2024-03-28 01:14 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Supongamos que tiene la URL de un archivo de configuración de objeto. Puedes usar
```suggestion
Supongamos que tienes la URL de un archivo de configuración de objeto. Puedes usar
```

2024-03-28 01:14 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +1. Exporte el objeto en vivo a un archivo de configuración de objeto local:.
```suggestion
1. Exporta el objeto en vivo a un archivo de configuración de objeto local:.
```

2024-03-28 01:14 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +1. Elimine manualmente el campo de estado del archivo de configuración del objeto.
```suggestion
1. Elimina manualmente el campo de estado del archivo de configuración del objeto.
```

2024-03-28 01:14 UTC, ramrodo commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +1. Para la gestión posterior de objetos, utilice `replace` exclusivamente.
```suggestion
1. Para la gestión posterior de objetos, utiliza `replace` exclusivamente.
```

2024-03-28 01:15 UTC, ramrodo requested changes
Thanks for your first contribution!
I left some suggestions.

2024-04-09 15:52 UTC, electrocucaracha commented
/assign @electrocucaracha

2024-04-09 19:31 UTC, electrocucaracha requested changes
@SerDigital muchas gracias por tu contribucion a la traduccion del sitio oficial de Kubernetes, he dejado algunas observaciones que quiza sean necesario corregir. Saludos

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +para detalles.
nit:
```suggestion
para mas detalles.
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +## Cómo crear objetos
```suggestion
## ¿Cómo crear objetos?
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +## Cómo actualizar objetos
```suggestion
## ¿Cómo actualizar objetos?
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +parcialmente por el clúster, como Servicios de tipo `LoadBalancer`, donde el
```suggestion
parcialmente por el clúster, como Services de tipo `LoadBalancer`, donde el 
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +## Cómo eliminar objetos
```suggestion
## ¿Cómo eliminar objetos?
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +## Cómo ver un objeto
```suggestion
## ¿Cómo ver un objeto?
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +Los comandos `create`, `replace` y `delete` funcionan bien cuando la configuración de cada objeto está completamente definida y registrada en su archivo de configuración. Sin embargo, cuando se actua
```suggestion
Los comandos `create`, `replace` y `delete` funcionan bien cuando la configuración de cada objeto está completamente definida y registrada en su archivo de configuración. Sin embargo, cuando se actualiza un objeto activo y las actualizaciones no se combinan en su archivo de configuración las actualizaciones se perderán la próxima vez que se ejecute un `replace`. Esto puede suceder si un controlador, como un HorizontalPodAutoscaler, realiza actualizaciones directamente a un objeto en activo. 
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +1. Exporta el objeto en vivo a un archivo de configuración de objeto local:.
```suggestion
1. Exporta el objeto en vivo a un archivo de configuración de objeto local.
```

2024-04-09 19:31 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +* [Kubernetes API Reference](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)
```suggestion
* [Referencia de la API de Kubernetes](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)
```

2024-04-23 07:24 UTC, SerDigital reviewed
I review the suggestions

2024-04-23 16:47 UTC, ramrodo commented
Thanks!
/lgtm

2024-04-23 16:49 UTC, ramrodo commented
/assign @electrocucaracha @krol3 @jossemarGT

2024-04-23 17:01 UTC, electrocucaracha requested changes

2024-04-23 17:01 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +1. Exporta el objeto en vivo a un archivo de configuración de objeto local:.
@SerDigital parece ser que esta sugerencia sigue siendo valida

2024-04-23 17:01 UTC, electrocucaracha commented on content/es/docs/tasks/manage-kubernetes-objects/imperative-config.md
> +* [Kubernetes API Reference](/docs/reference/generated/kubernetes-api/{{< param "version" >}}/)
@SerDigital podrias traducir este fragmento?

2024-05-21 07:26 UTC, SerDigital reviewed
Add some words, correct the bad translation. Add question marks

2024-05-21 15:59 UTC, electrocucaracha commented
/lgtm

2024-05-28 15:54 UTC, merged