[hi] Updated documentation of  _index.md (overview page)
kubernetes/website pull request #45730
Opened 2024-03-30 13:13 UTC by AnshRoshan

2024-03-30 13:30 UTC, AnshRoshan commented
@divya-mohan0209 thanks for the advice. I sync the fork and update. But discarding the commit closed the PR. So, I created this PR.

2024-03-31 16:32 UTC, kundan2707 commented on content/hi/docs/concepts/overview/_index.md
> +## समय में वापस जाना
```suggestion
## समय में पीछे जाना
```

2024-04-02 05:49 UTC, kundan2707 commented on content/hi/docs/concepts/overview/_index.md
> +आइए वक्त में पीछे जाकर एक नज़र डालते हैं कि कुबेरनेट्स इतना उपयोगी क्यों है।
follow same convention everywhere like either समय or वक्त similiarly either वापस or  पीछे

2024-04-02 06:00 UTC, kundan2707 commented on content/hi/docs/concepts/overview/_index.md
> +प्रारंभ में, संगठनों ने भौतिक (physical) सर्वरों पर एप्लिकेशन चलाए। भौतिक सर्वर में एप्लिकेशनों के लिए संसाधन सीमाओं को परिभाषित करने का कोई तरीका नहीं था, और इससे संसाधनों के आवंटन की समस्याएँ उत्पन
```suggestion
प्रारंभ में, संगठनों ने भौतिक (physical) सर्वरों पर एप्लिकेशन चलाए। भौतिक सर्वर में एप्लिकेशनों के लिए संसाधन सीमाओं को परिभाषित करने का कोई तरीका नहीं था, और इससे संसाधन आवंटन समस्याएं उत्पन्न हुईं। उदाहरण के लिए, यदि एक से अधिक एप्लिकेशन एक भौतिक सर्वर पर चलते हैं, तो ऐसे उदाहरण हो सकते हैं, जहाँ एक एप्लिकेशन अधिकांश संसाधनों को ले लेगा, और इसके परिणामस्वरूप, अन्य एप्लिकेशनों का प्रदर्शन खराब हो सकता है। इसका एक समाधान यह होगा कि प्रत्येक एप्लिकेशन को एक अलग भौतिक सर्वर पर चलाया जाए। लेकिन यह पैमाना नहीं था क्योंकि संसाधनों का कम उपयोग किया गया था, और संगठनों के लिए कई भौतिक सर्वरों को बनाए रखना महंगा था।
```

2024-04-02 06:28 UTC, kundan2707 commented on content/hi/docs/concepts/overview/_index.md
> +वर्चुअलाइजेशन एक भौतिक सर्वर में संसाधनों के बेहतर उपयोजन की अनुमति देता है और बेहतर मापक्रमणीयता की अनुमति देता है क्योंकि एक एप्लिकेशन को आसानी से जोड़ा या अपडेट किया जा सकता है, हार्डवेयर की लागत
Existing one seems more correct no need of change

2024-04-02 06:30 UTC, kundan2707 commented on content/hi/docs/concepts/overview/_index.md
> +कंटेनर लोकप्रिय हो गए हैं क्योंकि वे कई लाभ प्रदान करते हैं, जैसे:
No change required

2024-04-10 11:10 UTC, kundan2707 commented on content/hi/docs/concepts/overview/_index.md
> +* एप्लिकेशन-स्तरीय सेवाएं प्रदान नहीं करता है, जैसे कि मिडलवेयर (जैसे message buses), डेटा-प्रोसेसिंग फ्रेमवर्क (जैसे spark), डेटाबेस (जैसे MySQL), कैश मेमोरी, और न ही क्लस्टर स्टोरेज सिस्टम (जैसे की
No change required

2024-04-10 11:24 UTC, kundan2707 commented on content/hi/docs/concepts/overview/_index.md
> +कुबेरनेट्स आपको अपनी पसंदीदा स्टोरेज सिस्टम को स्वचालित रूप से माउंट करने की अनुमति देता है, जैसे कि स्थानीय स्टोरेज, पब्लिक क्लाउड प्रोवाइडर, और बहुत कुछ।
existing one is equally correct

2024-05-20 05:23 UTC, divya-mohan0209 requested changes
Initial set of reviews

2024-05-20 05:23 UTC, divya-mohan0209 commented on content/hi/docs/concepts/overview/_index.md
> +* Loosely coupled, Distributed, Elastic-free, Microservices: एप्लिकेशन को छोटे, स्वतंत्र टुकड़ों में तोड़ा जाता है और उन्हें सक्रिय रूप से तैनात और प्रबंधित किया जा सकता है - एक बड़ी एकल-उद्देश्य वाल
I would prefer the transliterated versions for the last line as well as the previous lines.

2024-05-20 05:23 UTC, divya-mohan0209 commented on content/hi/docs/concepts/overview/_index.md
> +आप कुबेरनेट्स को नोड्स के एक समूह के साथ प्रदान करते हैं जिसका उपयोग वह कंटेनरीकृत कार्यों को चलाने के लिए कर सकता है। आप कुबेरनेट्स को बताते हैं कि प्रत्येक कंटेनर को कितना सीपीयू और मेमोरी (रैम) चा
Why is this change required?

2024-05-20 05:23 UTC, divya-mohan0209 commented on content/hi/docs/concepts/overview/_index.md
> +कुबेरनेट्स DNS के नाम का उपयोग करके या अपने स्वयं के आईपी (IP) एड्रेस का उपयोग करके एक कंटेनर को प्रकट कर सकता है। यदि एक कंटेनर में ट्रैफ़िक अधिक है, तो कुबेरनेट्स लोड बैलेंस करने और नेटवर्क ट्रैफ़ि
I don't think address needs to be transliterated. Rest of the changes, I agree with.
```suggestion
कुबेरनेट्स DNS के नाम का उपयोग करके या अपने स्वयं के आईपी (IP) पते का उपयोग करके एक कंटेनर को प्रकट कर सकता है। यदि एक कंटेनर में ट्रैफ़िक अधिक है, तो कुबेरनेट्स लोड बैलेंस करने और नेटवर्क ट्रैफ़िक को वितरित करने में सक्षम है ताकि डिप्लॉयमेंट स्थिर हो।
```

2024-08-20 18:14 UTC, kundan2707 commented
/remove-lifecycle stale

2024-08-20 18:14 UTC, kundan2707 commented
@AnshRoshan gentle reminder

2024-10-04 18:30 UTC, closed without merging