[es] Added content/es/docs/concepts/architecture/control-plane-node-communication.md
kubernetes/website pull request #45836
Opened 2024-04-11 15:55 UTC by parraletz

/kind feature
/language es
/sig docs
/area localization
/assign @ramrodo

resolves #https://github.com/kubernetes/website/issues/45700

2024-04-22 18:54 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +title: Communication between Nodes and the Control Plane
Translate this title to Spanish

2024-04-22 18:55 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +- liggitt
Remove the reviewer's section as those users are not reviewing this localization itself.

```suggestion
```

2024-04-22 19:00 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Kubernetes tiene un patrón de API "hub-and-spoke" (centro y radios). Todo uso de la API desde los nodos (o los pods que ejecutan) termina en el servidor API. Ninguno de los otros componentes del plan
_"hub-and-spoke"_ is translated to _"centro y conexiones"_ according to [this Wikipedia article](https://es.wikipedia.org/wiki/Paradigma_de_distribuci%C3%B3n_Spoke-hub).

```suggestion
Kubernetes tiene un patrón de API "hub-and-spoke" (centro y conexiones). Todo uso de la API desde los nodos (o los pods que ejecutan) termina en el servidor API. Ninguno de los otros componentes del plano de control está diseñado para exponer servicios remotos. El servidor API está configurado para escuchar conexiones remotas en un puerto HTTPS seguro (típicamente el 443) con una o más formas de
```

2024-04-22 19:03 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Los nodos debe ser aprovisionados con el {{< glossary_tooltip text="certificado" term_id="certificate" >}} raíz público del cluster para que puedan conectar de manera segura al API server junto con c
```suggestion
Los nodos debe ser aprovisionados con el {{< glossary_tooltip text="certificado" term_id="certificate" >}} raíz público del clúster para que puedan conectar de manera segura al API server junto con credenciales de cliente válidas. Un buen enfoque es que las credenciales del cliente proporcionadas al kubelet estén en forma de un certificado de cliente. Consulta [kubelet TLS bootstrapping] (/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/) para la provisión automatizada de certificados de cliente del kubelet.
```

2024-04-22 19:04 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:05 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:05 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:06 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:06 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:06 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:06 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:06 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +
Remove the extra blank line.

```suggestion
```

2024-04-22 19:07 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +running.
Remove this paragraph in English since it is already translated above.

```suggestion
```

2024-04-22 19:10 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Si eso no es posible, usa [túneles SSH](#ssh-tunnels) entre el servidor API y el kubelet si es necesario para evitar conectarse a través de una red no confiable o pública.
We should use the same words used in the below translation to have this reference working in this article.

```suggestion
Si eso no es posible, usa [túneles SSH](#tuneles-ssh) entre el servidor API y el kubelet si es necesario para evitar conectarse a través de una red no confiable o pública.
```

2024-04-22 19:10 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Finalmente, se debe habilitar la [autenticación y/o autorización del Kubelet ](/docs/reference/access-authn-authz/kubelet-authn-authz/) para asegurar API del servicio kubelet
```suggestion
Finalmente, se debe habilitar la [autenticación y/o autorización del Kubelet](/docs/reference/access-authn-authz/kubelet-authn-authz/) para asegurar API del servicio kubelet  
```

2024-04-22 19:12 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +### Servdor API a nodes, pods, y services
```suggestion
### Servidor API a nodos, pods y servicios
```

2024-04-22 19:14 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Kubernetes soporta túneles SSH para proteger los caminos de comunicación del plano de control a los nodos. En esta configuración, el servidor API inicia un túnel SSH a cada nodo en el clúster (conect
Previously in the above paragraphs, we have used _"control plane"_ without translating. So, you may want to use the words in English to keep consistency. 

```suggestion
Kubernetes soporta túneles SSH para proteger los caminos de comunicación del control plane a los nodos. En esta configuración, el servidor API inicia un túnel SSH a cada nodo en el clúster (conectándose al servidor SSH que escucha en el puerto 22) y pasa todo el tráfico destinado a un kubelet, nodo, pod o servicio a través del túnel.
```

2024-04-22 19:15 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Los túneles SSH están actualmente en deprecados,por lo que no deberías optar por usarlos a menos que sepas lo que estás haciendo. El [servicio Konnectivity](#konnectivity-service) es un reemplazo par
We should use the same words used in the below translation to have this reference working in this article.

```suggestion
Los túneles SSH están actualmente deprecados, por lo que no deberías optar por usarlos a menos que sepas lo que estás haciendo. El [servicio Konnectivity](#servicio-konnectivity) es un reemplazo para este canal de comunicación.
```

2024-04-22 19:16 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Como reemplazo de los túneles SSH, el servicio de Konnectivity proporciona un proxy a nivel de TCP para la comunicación del plano de control con el clúster. El servicio de Konnectivity consta de dos
Previously in the above paragraphs, we have used "control plane" without translating. So, you may want to use the words in English to keep consistency.

```suggestion
Como reemplazo de los túneles SSH, el servicio de Konnectivity proporciona un proxy a nivel de TCP para la comunicación del control plane con el clúster. El servicio de Konnectivity consta de dos partes: el servidor de Konnectivity en la red del plano de control y los agentes de Konnectivity en la red de los nodos. Los agentes de Konnectivity inician conexiones al servidor de Konnectivity y mantienen las conexiones de red.
```

2024-04-22 19:16 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Después de habilitar el servicio de Konnectivity, todo el tráfico del plano de control a los nodos pasa a través de estas conexiones.
Previously in the above paragraphs, we have used "control plane" without translating. So, you may want to use the words in English to keep consistency.

```suggestion
Después de habilitar el servicio de Konnectivity, todo el tráfico del control plane a los nodos pasa a través de estas conexiones.
```

2024-04-22 19:17 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* Leer más sobre los [componentes del plano de control de Kubernetes ](/es/docs/concepts/overview/components/#componentes-del-plano-de-control)
```suggestion
* Lee más sobre los [componentes del control plane de Kubernetes](/es/docs/concepts/overview/components/#componentes-del-plano-de-control)
```

2024-04-22 19:17 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* Aprender más del [modelo Hubs and Spoke ](https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html#hubs-spokes-and-other-wheel-metaphors)
```suggestion
* Aprender más del [modelo Hubs and Spoke](https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html#hubs-spokes-and-other-wheel-metaphors)
```

2024-04-22 19:17 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* Apreder como [Asegurar un Cluster](/docs/tasks/administer-cluster/securing-a-cluster/)
```suggestion
* Apreder cómo [Asegurar un Clúster](/docs/tasks/administer-cluster/securing-a-cluster/) 
```

2024-04-22 19:23 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +## Nodo a Control Plane
We have used "plano de control" as the translation for "control plane" in other Spanish articles. For instance, the official concept meaning translation:

https://kubernetes.io/es/docs/concepts/overview/components/#componentes-del-plano-de-control

Please use "Plano de Control" to keep consistency.

```suggestion
## Nodo a Plano de Control
```

2024-04-22 19:23 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Los componentes del control plane se comunican con el servidor API a través del puerto seguro.
We have used "plano de control" as the translation for "control plane" in other Spanish articles. For instance, the official concept meaning translation:

https://kubernetes.io/es/docs/concepts/overview/components/#componentes-del-plano-de-control

Please use "Plano de Control" to keep consistency.

```suggestion
Los componentes del plano de control se comunican con el servidor API a través del puerto seguro.
```

2024-04-22 19:24 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +## Control plane al nodo
We have used "plano de control" as the translation for "control plane" in other Spanish articles. For instance, the official concept meaning translation:

https://kubernetes.io/es/docs/concepts/overview/components/#componentes-del-plano-de-control

Please use "Plano de Control" to keep consistency.

```suggestion
## Plano de control al nodo
```

2024-04-22 19:24 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Existen dos formas de comunicación primarias desde el control plane (el servidor API) hacia los nodos. El primero es desde el servidor API hasta el proceso {{< glossary_tooltip text="kubelet" term_id
We have used "plano de control" as the translation for "control plane" in other Spanish articles. For instance, the official concept meaning translation:

https://kubernetes.io/es/docs/concepts/overview/components/#componentes-del-plano-de-control

Please use "Plano de Control" to keep consistency.

```suggestion
Existen dos formas de comunicación primarias desde el plano de control (el servidor API) hacia los nodos. El primero es desde el servidor API hasta el proceso {{< glossary_tooltip text="kubelet" term_id="kubelet" >}} que se ejecuta en cada nodo del clúster. El segundo es desde el servidor API hacia cualquier nodo, pod o servicio a través de la funcionalidad de proxy del servidor API.
```

2024-04-22 19:25 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* Aprender más acerca de la [API de Kubernetes](/docs/concepts/overview/kubernetes-api/)
```suggestion
* Aprende más acerca de la [API de Kubernetes](/docs/concepts/overview/kubernetes-api/)
```

2024-04-22 19:25 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* [Configurar el servicio de Konnectivity](/docs/tasks/extend-kubernetes/setup-konnectivity/)
```suggestion
* [Configura el servicio de Konnectivity](/docs/tasks/extend-kubernetes/setup-konnectivity/)
```

2024-04-22 19:25 UTC, ramrodo commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* [Utilizar el reenvío de puertos para acceder a aplicaciones en un clúster](/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)
```suggestion
* [Utiliza el reenvío de puertos para acceder a aplicaciones en un clúster](/docs/tasks/access-application-cluster/port-forward-access-application-cluster/)
```

2024-04-22 19:28 UTC, ramrodo requested changes
Thanks for this PR!

I left some suggestions.

Also, try adding break lines at the end of the sentences between paragraphs as in the original article. This will help us to add suggestions to single lines instead of doing them to the whole paragraph. If you want a better explanation, please don't hesitate to ask us.

2024-05-14 18:28 UTC, parraletz commented
> Thanks for this PR!
> 
> I left some suggestions.
> 
> Also, try adding break lines at the end of the sentences between paragraphs as in the original article. This will help us to add suggestions to single lines instead of doing them to the whole paragraph. If you want a better explanation, please don't hesitate to ask us.

Thank you so much for the feedback, Iv'e applied the suggestions.

2024-05-14 21:46 UTC, ramrodo commented
Thanks!
/lgtm
/cc @electrocucaracha @krol3

2024-05-15 16:20 UTC, krol3 commented
@ramrodo @electrocucaracha  @parraletz , this file is update of the https://github.com/kubernetes/website/blob/main/content/es/docs/concepts/architecture/master-node-communication.md
, What will be the next steps remove the older file?

2024-05-15 17:10 UTC, krol3 requested changes

2024-05-15 17:13 UTC, krol3 commented
Este traduccion esta relacionado con este issue: https://github.com/kubernetes/website/issues/45689 y ya tiene un PR abierto tb https://github.com/kubernetes/website/pull/45693

2024-05-16 17:55 UTC, ramrodo commented
> Este traduccion esta relacionado con este issue: #45689 y ya tiene un PR abierto tb #45693

Es verdad, al parecer hubo una confusión. El error fue que este PR debió haber traducido (actualizado) el documento del issue https://github.com/kubernetes/website/issues/45700 `nodes-md` (y que también está en la descripción), pero los cambios se realizaron sobre el documento `control-plane-node-communication.md`.

2024-05-17 02:38 UTC, electrocucaracha requested changes

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Este documento cataloga  las diferentes vías de comunicación entre el {{< glossary_tooltip term_id="kube-apiserver" text="servidor API" >}} y el {{< glossary_tooltip text="clúster" term_id="cluster"
nit
```suggestion
Este documento cataloga las diferentes vías de comunicación entre el {{< glossary_tooltip term_id="kube-apiserver" text="servidor API" >}} y el {{< glossary_tooltip text="clúster" term_id="cluster" length="all" >}} de Kubernetes. El objetivo es permitir a los usuarios personalizar su instalación para proteger la configuración de la red de tal manera que el clúster pueda ejecutarse en una red insegura (o en un proveedor de servicios en la nube con direcciones IP públicas).
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Kubernetes tiene un patrón de API "hub-and-spoke" (centro y conexiones). Todo uso de la API desde los nodos (o los pods que ejecutan) termina en el servidor API. Ninguno de los otros componentes del
```suggestion
Kubernetes sigue el patrón de API "hub-and-spoke" (centro y conexiones). Todo uso de la API desde los nodos (o los pods que ejecutan) termina en el servidor API. Ninguno de los otros componentes del plano de control está diseñado para exponer servicios remotos. El servidor API está configurado para escuchar conexiones remotas en un puerto HTTPS seguro (típicamente el 443) con una o más formas de
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Los nodos debe ser aprovisionados con el {{< glossary_tooltip text="certificado" term_id="certificate" >}} raíz público del clúster para que puedan conectar de manera segura al API server junto con c
Me parece que no lleva acento, https://www.ejemplos.co/como-y-como/

```suggestion
Los nodos debe ser aprovisionados con el {{< glossary_tooltip text="certificado" term_id="certificate" >}} raíz público del clúster para que puedan conectar de manera segura al servidor API junto con credenciales de cliente válidas. Un buen enfoque es que las credenciales del cliente proporcionadas al kubelet estén en forma de un certificado de cliente. Consulta [kubelet TLS bootstrapping](/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/) para ver como aprovisionar certificados de cliente de forma automática.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +{{< glossary_tooltip text="Pods" term_id="pod" >}} que deseen conectarse al servidor API pueden hacerlo de forma segura a través de una cuenta de servicio, de esta forma Kubernetes inserta de forma a
nit
```suggestion
{{< glossary_tooltip text="Pods" term_id="pod" >}} que deseen conectarse al servidor API pueden hacerlo de forma segura a través de una cuenta de servicio, de esta forma Kubernetes inserta de forma automática el certificado raíz público y un bearer token válido en el Pod cuando este es instanciado. El servicio `kubernetes` (en el namespace `default`) está configurado con una dirección IP virtual que es redireccionada (via {{< glossary_tooltip text="kube-proxy" term_id="kube-proxy" >}}) al punto de acceso HTTPS en el apiserver.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Como resultado, el modo de operación predeterminado para las conexiones desde los nodos y el pod que se ejecutan en los nodos hacia el plano de control está asegurado por defecto y puede funcionar so
```suggestion
Como resultado, el modo de operación predeterminado para las conexiones desde los nodos y el Pod que se ejecutan en los nodos hacia el plano de control está asegurado por defecto y puede funcionar sobre redes no confiables y/o públicas.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Kubernetes tiene un patrón de API "hub-and-spoke" (centro y conexiones). Todo uso de la API desde los nodos (o los pods que ejecutan) termina en el servidor API. Ninguno de los otros componentes del
```suggestion
Kubernetes tiene un patrón de API "hub-and-spoke" (centro y conexiones). Todo uso de la API desde los nodos (o los Pods que ejecutan) termina en el servidor API. Ninguno de los otros componentes del plano de control está diseñado para exponer servicios remotos. El servidor API está configurado para escuchar conexiones remotas en un puerto HTTPS seguro (típicamente el 443) con una o más formas de
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Los nodos debe ser aprovisionados con el {{< glossary_tooltip text="certificado" term_id="certificate" >}} raíz público del clúster para que puedan conectar de manera segura al API server junto con c
```suggestion
Los nodos debe ser aprovisionados con el {{< glossary_tooltip text="certificado" term_id="certificate" >}} raíz público del clúster para que puedan conectar de manera segura al servidor API junto con credenciales de cliente válidas. Un buen enfoque es que las credenciales del cliente proporcionadas al kubelet estén en forma de un certificado de cliente. Consulta [kubelet TLS bootstrapping](/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/) para ver cómo aprovisionar certificados de cliente de forma automática.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Existen dos formas de comunicación primarias desde el plano de control (apiserver) hacia los nodos. El primero es desde el servidor API hasta el proceso {{< glossary_tooltip text="kubelet" term_id="k
```suggestion
Existen dos formas de comunicación primarias desde el plano de control (apiserver) hacia los nodos. El primero es desde el servidor API hasta el proceso {{< glossary_tooltip text="kubelet" term_id="kubelet" >}} que se ejecuta en cada nodo del clúster. El segundo es desde el servidor API hacia cualquier nodo, Pod o servicio a través de la funcionalidad de proxy del servidor API.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* Conectarse (generalmente a través de `kubectl`) a pods en ejecución.
```suggestion
* Conectarse (generalmente a través de `kubectl`) a Pods en ejecución.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Para verificar esta conexión, usa la bandera `--kubelet-certificate-authority` para proporcionar al servidor API un paquete de certificados raíz para usar en la verificación del certificado de servic
```suggestion
Para verificar esta conexión, use la bandera `--kubelet-certificate-authority` para proporcionar al servidor API un paquete de certificados raíz para usar en la verificación del certificado de servicio del kubelet.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Si eso no es posible, usa [túneles SSH](#tuneles-ssh) entre el servidor API y el kubelet si es necesario para evitar conectarse a través de una red no confiable o pública.
```suggestion
Si eso no es posible, use [túneles SSH](#tuneles-ssh) entre el servidor API y el kubelet si es necesario para evitar conectarse a través de una red no confiable o pública.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +### Servidor API a nodos, pods y servicios
```suggestion
### Servidor API a nodos, Pods y servicios
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Las conexiones desde el servidor API a un nodo, pod o servicio por defecto son conexiones HTTP simples y, por lo tanto, no están autenticadas ni cifradas. Pueden ejecutarse sobre una conexión HTTPS s
```suggestion
Las conexiones desde el servidor API a un nodo, Pod o servicio por defecto son conexiones HTTP simples y, por lo tanto, no están autenticadas ni cifradas. Pueden ejecutarse sobre una conexión HTTPS segura anteponiendo el prefijo `https:` al nodo, pod o servicio en la URL de la API, pero no validarán el certificado proporcionado por el endpoint HTTPS ni proporcionarán credenciales de cliente. Así que, aunque la conexión estará cifrada, no ofrecerá garantías de integridad. Estas conexiones **actualmente no son seguras** para ejecutarse sobre redes no confiables o públicas.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +### Tuneles SSH
```suggestion
### Túneles SSH
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Kubernetes soporta túneles SSH para proteger los caminos de comunicación del plano de control a los nodos. En esta configuración, el servidor API inicia un túnel SSH a cada nodo en el clúster (conect
```suggestion
Kubernetes soporta túneles SSH para proteger los caminos de comunicación del plano de control a los nodos. En esta configuración, el servidor API inicia un túnel SSH a cada nodo en el clúster (conectándose al servidor SSH que escucha en el puerto 22) y pasa todo el tráfico destinado a un kubelet, nodo, Pod o servicio a través del túnel.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +Los túneles SSH están actualmente deprecados, por lo que no deberías optar por usarlos a menos que sepas lo que estás haciendo. El [servicio Konnectivity](#servicio-konnectivity) es un reemplazo para
```suggestion
Los túneles SSH están actualmente obsoletos, por lo que deberías optar por no usarlos a menos que sepas lo que estás haciendo. El [servicio Konnectivity](#servicio-konnectivity) es un reemplazo para este canal de comunicación.
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* Aprende más del [modelo Hubs and Spoke](https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html#hubs-spokes-and-other-wheel-metaphors)
```suggestion
* Aprende más del [modelo centro y conexiones](https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html#hubs-spokes-and-other-wheel-metaphors)
```

2024-05-17 02:38 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/control-plane-node-communication.md
> +* Aprende cómo [Asegurar un Clúster](/docs/tasks/administer-cluster/securing-a-cluster/)
```suggestion
* Aprende cómo [proteger un Clúster](/docs/tasks/administer-cluster/securing-a-cluster/) 
```

2024-05-21 15:58 UTC, ramrodo commented
Duplicated. Closed in favor of https://github.com/kubernetes/website/pull/45693
/close

2024-05-21 15:58 UTC, closed without merging