Translate content/en/docs/reference/glossary/container-lifecycle-hook…
kubernetes/website pull request #45886
Opened 2024-04-15 14:23 UTC by EigoOda

…s.md into Japanese

Closes: https://github.com/kubernetes/website/issues/45473

2024-04-18 07:15 UTC, Okabe-Junya commented
/retitle [ja] Translate content/en/docs/reference/glossary/container-lifecycle-hooks.md into Japanese

2024-04-18 07:30 UTC, Okabe-Junya commented
Deploy preview:

- https://deploy-preview-45886--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-container-lifecycle-hooks

2024-04-18 07:39 UTC, Okabe-Junya requested changes
継続的なコントリビューションありがとうございます！

細かい点で恐縮ですが、ご確認いただければと思います

2024-04-18 07:39 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-lifecycle-hooks.md
全体を通してですが、他の用語がですます調で翻訳されているため、こちらも合わせていただけると嬉しいです！

2024-04-18 07:39 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-lifecycle-hooks.md
> +  ライフサイクルフックは、コンテナ管理のライフサイクルにおけるイベントを公開し、イベントが発生したときにユーザーがコードを実行できるようにする。
```suggestion
  ライフサイクルフックは、コンテナ管理のライフサイクルにおけるイベントを公開し、イベントが発生したときにユーザーがコードを実行できるようにします。
```

2024-04-18 07:39 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-lifecycle-hooks.md
> +  ライフサイクルフックは、{{< glossary_tooltip text="コンテナ" term_id="container" >}}管理のライフサイクルにおけるイベントを公開し、イベントが発生したときにユーザーがコードを実行できるようにする。
```suggestion
  ライフサイクルフックは、{{< glossary_tooltip text="コンテナ" term_id="container" >}}管理のライフサイクルにおけるイベントを公開し、イベントが発生したときにユーザーがコードを実行できるようにします。
```

2024-04-18 07:39 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-lifecycle-hooks.md
> +コンテナには2つのフックが公開されている。PostStartはコンテナが作成された直後に実行され、PreStopはコンテナが終了する直前に呼ばれるブロッキングである。
```suggestion
コンテナには2つのフックが公開されています。PostStartはコンテナが作成された直後に実行され、PreStopはコンテナが終了する直前に呼ばれるブロッキングです。
```

2024-04-18 07:39 UTC, Okabe-Junya commented
/assign nasa9084

2024-04-18 11:55 UTC, EigoOda commented on content/ja/docs/reference/glossary/container-lifecycle-hooks.md
@Okabe-Junya 
レビューありがとうございます！suggestion 取り込ませていただきました。

2024-04-18 11:55 UTC, EigoOda commented
/label tide/merge-method-squash

2024-04-18 13:11 UTC, Okabe-Junya approved these changes
ありがとうございます！LGTMです！

/lgtm

2024-04-23 15:37 UTC, nasa9084 reviewed
/approve

2024-04-23 15:52 UTC, merged