Translate content/ja/docs/reference/glossary/cni.md into Japanese
kubernetes/website pull request #45883
Opened 2024-04-15 13:27 UTC by EigoOda

Closes: https://github.com/kubernetes/website/issues/45474

2024-04-15 13:28 UTC, EigoOda commented on content/ja/docs/reference/glossary/cni.md
> +* KubernetsとCNIについては、[ネットワークプラグイン](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/)を参照してください。
ja のページが無かったため、en をリンクしました

2024-04-16 07:22 UTC, Okabe-Junya commented
/cc

2024-04-16 09:50 UTC, Okabe-Junya commented
Deploy previews:

- https://deploy-preview-45883--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-cni

2024-04-16 09:56 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます！何点かコメントさせて頂きました。ご確認お願いいたします

2024-04-16 09:56 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cni.md
> +title: コンテナネットワークインターフェース（CNI）
```suggestion
title: コンテナネットワークインターフェース(CNI)
```

nits: カッコは半角でお願いします

FYI: https://kubernetes.io/ja/docs/contribute/localization/#basic-policy

> 記号類は感嘆符「！」と疑問符「？」のみ全角、それ以外は半角で表記

2024-04-16 09:56 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cni.md
> + コンテナネットワークインターフェイス（CNI）プラグインは、appc/CNI仕様に準拠したネットワークプラグインの一種です。
```suggestion
 コンテナネットワークインターフェイス(CNI)プラグインは、appc/CNI仕様に準拠したネットワークプラグインの一種です。
```

ditto

2024-04-16 09:56 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cni.md
> +    コンテナネットワークインターフェース（CNI）プラグインは、appc/CNI仕様に準拠したネットワークプラグインの一種です。
```suggestion
    コンテナネットワークインターフェース(CNI)プラグインは、appc/CNI仕様に準拠したネットワークプラグインの一種です。
```

ditto

2024-04-16 09:56 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cni.md
> +* KubernetsとCNIについては、[ネットワークプラグイン](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/)を参照してください。
```suggestion
* KubernetesとCNIについては、[**ネットワークプラグイン**](/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/)を参照してください。
```

"Kubernetes" のtypoの修正と、翻訳元に準拠して `** **` の挿入だけお願いいたします

https://github.com/kubernetes/website/blob/13dd6a817432249795b84e6f68bd8c4a7151c01d/content/en/docs/reference/glossary/cni.md?plain=1#L18

2024-04-16 09:56 UTC, Okabe-Junya commented
/assign nasa9084

2024-04-16 09:59 UTC, Okabe-Junya commented
/retitle [ja] Translate content/en/docs/reference/glossary/cni.md into Japanese

2024-04-16 12:35 UTC, EigoOda commented
/label tide/merge-method-squash

2024-04-16 13:48 UTC, Okabe-Junya approved these changes
ありがとうございます！LGTMです

/lgtm

2024-04-20 19:57 UTC, sftim commented
/area localization

2024-04-23 15:39 UTC, nasa9084 reviewed
/approve

2024-04-23 15:49 UTC, merged