[ja] Translate content/en/docs/reference/glossary/container-env-variables.md into Japanese
kubernetes/website pull request #45997
Opened 2024-04-24 08:12 UTC by EigoOda

Closes: https://github.com/kubernetes/website/issues/45472

2024-04-24 08:19 UTC, EigoOda commented on content/ja/docs/reference/glossary/container-env-variables.md
> + コンテナ環境変数は、{{< glossary_tooltip text="pod" term_id="pod" >}}内で実行されているコンテナに関する有用な情報を提供する`name=value`のペアです。
`name=value`を`名前=値`にするか迷いましたが、ママ表記のほうがわかりやすいと思いそのままにしました。

2024-04-24 08:25 UTC, EigoOda commented on content/ja/docs/reference/glossary/container-env-variables.md
> +  コンテナ環境変数は、Pod内で実行されているコンテナに関する有用な情報を提供する`name=value`のペアです。
`name=value`を`名前=値`にするか迷いましたが、ママ表記のほうがわかりやすいと思いそのままにしました。

2024-04-24 08:25 UTC, EigoOda commented
/label tide/merge-method-squash

2024-04-24 13:52 UTC, Okabe-Junya commented
/cc

2024-04-24 13:54 UTC, Okabe-Junya commented
Deploy preview:

- https://deploy-preview-45997--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-container-env-variables

2024-04-24 14:07 UTC, Okabe-Junya commented
/assign nasa9084

2024-04-25 01:04 UTC, EigoOda commented
@Okabe-Junya 
レビューありがとうございます！suggestion 取り込ませていただきました

2024-04-25 05:31 UTC, Okabe-Junya approved these changes
ありがとうございます！LGTMです！

/lgtm

2024-04-30 05:18 UTC, inductor requested changes

2024-04-30 05:18 UTC, inductor commented on content/ja/docs/reference/glossary/container-env-variables.md
> +コンテナ環境変数は、{{< glossary_tooltip text="コンテナ" term_id="container" >}}にとって重要なリソースに関する情報とともに、実行中のコンテナ化されたアプリケーションが必要とする情報を提供します。たとえば、ファイルシステムの詳細、コンテナ自体の情報、サービスエンドポイントのような他のクラスターリソースなどです。
英語では「サービスエンドポイントのような他のクラスターリソース」ここが１かたまりのはずですが、この翻訳だとその情報が欠落しており、「など」の所在も不明で読みにくくなっていそうです。such asが含まれる部分には「あるいは、〜のような〜です」みたいにしたほうが翻訳としては適切だと思います。

2024-05-01 08:20 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-env-variables.md
> +コンテナ環境変数は、{{< glossary_tooltip text="コンテナ" term_id="container" >}}にとって重要なリソースに関する情報とともに、実行中のコンテナ化されたアプリケーションが必要とする情報を提供します。たとえば、ファイルシステムの詳細、コンテナ自体の情報、サービスエンドポイントのような他のクラスターリソースなどです。
@EigoOda 

非常に細かい点で恐縮ですが、https://github.com/kubernetes/website/commit/49207d9ac051b5bd35e1e06c530d0e8d03276687 の変更で一文の中に句点が4箇所になってしまったので、少し減らした方が良いかと思いました

FYI: https://github.com/textlint-ja/textlint-rule-preset-ja-technical-writing?tab=readme-ov-file#カンマは1文中に3つまで

2024-05-01 08:21 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-env-variables.md
> +コンテナ環境変数は、{{< glossary_tooltip text="コンテナ" term_id="container" >}}にとって重要なリソースに関する情報とともに、実行中のコンテナ化されたアプリケーションが必要とする情報を提供します。たとえば、ファイルシステムの詳細、コンテナ自体の情報、サービスエンドポイントのような他のクラスターリソースなどです。
翻訳自体は良いと思いました

2024-05-02 00:27 UTC, EigoOda commented on content/ja/docs/reference/glossary/container-env-variables.md
> +コンテナ環境変数は、{{< glossary_tooltip text="コンテナ" term_id="container" >}}にとって重要なリソースに関する情報とともに、実行中のコンテナ化されたアプリケーションが必要とする情報を提供します。たとえば、ファイルシステムの詳細、コンテナ自体の情報、サービスエンドポイントのような他のクラスターリソースなどです。
@Okabe-Junya 
レビューありがとうございます。
https://github.com/kubernetes/website/pull/45997/commits/c7c115d7ee2668bb47a57979e4adb899d180ae00 で句点が3つになるように減らしました🙏

2024-05-02 02:22 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-env-variables.md
> +コンテナ環境変数は、{{< glossary_tooltip text="コンテナ" term_id="container" >}}にとって重要なリソースに関する情報とともに、実行中のコンテナ化されたアプリケーションが必要とする情報を提供します。たとえば、ファイルシステムの詳細、コンテナ自体の情報、サービスエンドポイントのような他のクラスターリソースなどです。
ご対応ありがとうございます〜！

2024-05-02 02:22 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/container-env-variables.md
> +コンテナ環境変数は、{{< glossary_tooltip text="コンテナ" term_id="container" >}}にとって重要なリソースに関する情報とともに、実行中のコンテナ化されたアプリケーションが必要とする情報を提供します。たとえば、ファイルシステムの詳細、コンテナ自体の情報、サービスエンドポイントのような他のクラスターリソースなどです。
cc @inductor

2024-05-02 02:23 UTC, Okabe-Junya approved these changes
/lgtm

2024-05-02 22:06 UTC, inductor commented
/approve

2024-05-02 22:08 UTC, merged