[pt-br] Update docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
kubernetes/website pull request #46001
Opened 2024-04-24 12:59 UTC by ricardoamaro

Per https://github.com/kubernetes/website/issues/44765 grabbed the https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ and translated that to pt-br taking into account the already existing page.

2024-04-24 13:06 UTC, edsoncelio commented
/cc

2024-04-30 20:14 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +* `kubelet`: o componente que roda em todas as máquinas do seu cluster
roda -> executa

2024-04-30 20:15 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +* `kubectl`: o utilitário de linha de comando para conversar com seu cluster.
interagir com o cluster instead of conversar

2024-04-30 20:15 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +precisará garantir que eles correspondam à versão do plano de controle do Kubernetes
We use "camada de gerenciamento" instead of "plano de controle"

2024-04-30 20:16 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +5. (Opcional) Habilite o serviço kubelet antes de executar kubeadm:
"executar o kubeadm"

2024-04-30 20:30 UTC, edsoncelio commented
PTAL @stormqueen1990

2024-04-30 21:44 UTC, stormqueen1990 commented
/retitle [pt-br] Update docs/setup/production-environment/tools/kubeadm/install-kubeadm.md

2024-04-30 22:51 UTC, ricardoamaro commented
Obrigado pelo feedback @edsoncelio

2024-04-30 23:32 UTC, edsoncelio requested changes
Hi Ricardo,
Just a few more changes before approve :)

2024-04-30 23:32 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +O plugin de rede de pods que você usa também pode exigir que certas portas estejam
pods -> Pods

2024-04-30 23:32 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +abertas. Como isso varia com cada plugin de rede de pods, consulte a
pods -> Pods

2024-04-30 23:32 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +  e faz coisas como iniciar pods e containers.
Pods -> pods
containers -> contêiners

2024-04-30 23:32 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +O kubelet agora está reiniciando a cada poucos segundos, enquanto espera em um loop de falha por
This section is a bit confusing, you can use the old one:
"O kubelet agora ficará reiniciando de alguns em alguns segundos, enquanto espera por instruções vindas do kubeadm."

2024-04-30 23:32 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +3. Instale kubelet, kubeadm e kubectl:
Instale kubelet -> instale o kubelet

2024-04-30 23:32 UTC, edsoncelio commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +* [Política de versão e descompasso de versão](/docs/setup/release/version-skew-policy/) do Kubernetes
Política de versão e descompasso de versão -> Políticas de versão e compatibilidade entre versões

2024-05-06 03:12 UTC, stormqueen1990 reviewed
Olá, @ricardoamaro! 👋🏻

Muito obrigada pela tua contribuição! 🙏🏻

Encontrei alguns itens menores a serem ajustados, mas esta alteração está bem encaminhada!

2024-05-06 03:12 UTC, stormqueen1990 commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +{{% legacy-repos-deprecation %}}
Este shortcode também ainda não foi traduzido (e poderia ter sua tradução incluída em um pull request posterior).

2024-05-06 03:12 UTC, stormqueen1990 commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +1. Atualize o índice do pacote `apt` e instale os pacotes necessários para usar o repositório `apt` do Kubernetes:
"de pacotes" nesse contexto se refere a um índice de pacotes genérico, não necessariamente ao índice do pacote específico chamado "`apt`".

```suggestion
1. Atualize o índice de pacotes `apt` e instale os pacotes necessários para usar o repositório `apt` do Kubernetes:
```

2024-05-06 03:13 UTC, stormqueen1990 commented
/label tide/merge-method-squash

2024-05-06 13:50 UTC, ricardoamaro commented on content/pt-br/docs/setup/production-environment/tools/kubeadm/install-kubeadm.md
> +{{% legacy-repos-deprecation %}}
ok! se faltar algo mais neste pull request digam por favor.

2024-05-08 13:03 UTC, edsoncelio commented
Thanks
/lgtm

2024-05-12 20:53 UTC, ricardoamaro commented
@stormqueen1990 @edsoncelio when are you planning to merge this?

2024-05-12 20:58 UTC, edsoncelio commented
> @stormqueen1990 @edsoncelio when are you planning to merge this?

Hello Ricardo, 
We do not have a scheduled date for merging the PRs.
A few people are reviewing (and approving) so this depends on our free time.

Thanks.

2024-05-13 00:54 UTC, stormqueen1990 reviewed
Obrigada pela contribuição! 🙏🏻

/approve

2024-05-13 00:57 UTC, merged