[es] Added docs/concepts/architecture/leases to Spanish
kubernetes/website pull request #46005
Opened 2024-04-24 17:50 UTC by eduardoSalazarCarrillo

/kind feature
/language es
/sig docs
/area localization

resolves #45698

2024-04-24 23:47 UTC, dipesh-rawat commented on content/es/docs/concepts/architecture/leases.md
> +{{< glossary_tooltip term_id=«controller» text=«controlador» >}} en la que un miembro principal o líder
The PR build failed [(logs here)](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6629467a76432200089f88b7) encountering an error in this line as mentioned below. 

[Build Logs](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/6629467a76432200089f88b7)

> 6:53:07 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
6:53:07 PM: ERROR [es] "docs/concepts/architecture/leases.md": "«controller»" is not a valid glossary term_id, see ./docs/reference/glossary/* for a full list


Please take a look at the suggestion provided. I hope this helps.
```suggestion
{{< glossary_tooltip term_id=controller text=controlador >}} en la que un miembro principal o líder
```

2024-04-27 17:07 UTC, electrocucaracha commented
/assign @krol3 @ramrodo

2024-04-27 17:35 UTC, electrocucaracha requested changes
@eduardoSalazarCarrillo gracias por traducir este concepto al Español, quizá sería bueno traer a la reunión semanal el traducir o no el término de `lease`

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +que se utilizan para capacidades críticas del sistema, como los latidos del nodo y la elección del líder a nivel de componente.
Quizá sea mejor no traducir este término
```suggestion
que se utilizan para capacidades críticas del sistema, como los heartbeats del nodo y la elección del líder a nivel de componente.

```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +## Latidos del nodo {#node-heart-beats}
```suggestion
## Heartbeats del nodo {#node-heart-beats}
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +Kubernetes utiliza la API Lease para comunicar los latidos de los nodos kubelet al servidor API de Kubernetes.
```suggestion
Kubernetes utiliza la API Lease para comunicar los heartbeats de los nodos kubelet al servidor API de Kubernetes.
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +Para cada `Nodo` , existe un objeto `Lease` con un nombre coincidente en el espacio de nombres `kube-node-lease`.
```suggestion
Para cada `Nodo` , existe un objeto `Lease` con un nombre que coincide en el espacio de nombres `kube-node-lease`.
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +Bajo el capó, cada latido kubelet es una solicitud **update** a este objeto `Lease`, actualizando
```suggestion
Analizando a detalle, cada heartbeat es una solicitud **update** a este objeto `Lease`, actualizando
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +## Elección del líder
```suggestion
## Elección del líder

```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +descubrir cuántas instancias de `kube-apiserver` están operando el plano de control de Kubernetes.
```suggestion
puedan descubrir cuántas instancias de `kube-apiserver` están operando el plano de control de Kubernetes.
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +Puede desactivar el lease de identidades del servidor API desactivando la opción `APIServerIdentity` de la [puerta de función](/docs/reference/command-line-tools-reference/feature-gates/).
```suggestion
Puede desactivar el lease de identidades del servidor API desactivando la opción `APIServerIdentity`
de los [interruptores de funcionalidades](/docs/reference/command-line-tools-reference/feature-gates/).
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +El hash SHA256 utilizado en el nombre del lease se basa en el nombre de host del sistema operativo visto por ese servidor API. Cada kube-apiserver debe ser
```suggestion

El hash SHA256 utilizado en el nombre del lease se basa en el nombre de host del sistema operativo visto por ese servidor API. Cada kube-apiserver debe ser
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +title: Arrendamientos
```suggestion
title: Leases
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +Los sistemas distribuidos suelen necesitar _arrendamientos_, que proporcionan un mecanismo para bloquear recursos compartidos
```suggestion
Los sistemas distribuidos suelen necesitar _leases_, que proporcionan un mecanismo para bloquear recursos compartidos
```

2024-04-27 17:35 UTC, electrocucaracha commented on content/es/docs/concepts/architecture/leases.md
> +En Kubernetes, el concepto de arrendamiento está representado por objetos [Lease](/docs/reference/kubernetes-api/cluster-resources/lease-v1/)
```suggestion
En Kubernetes, el concepto de lease (arrendamiento) está representado por objetos [Lease](/docs/reference/kubernetes-api/cluster-resources/lease-v1/)
```

2024-04-28 05:32 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +Véase [Objetos Lease de nodos](/docs/concepts/architecture/nodes/#heartbeats) para más detalles.
Usar la forma "tú" en vez de "usted"

```suggestion
Ve [Objetos Lease de nodos](/docs/concepts/architecture/nodes/#heartbeats) para más detalles.
```

2024-04-28 05:32 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +Puede inspeccionar los leases de cada kube-apiserver buscando objetos leases en el espacio de nombres `kube-system`
Usar la forma "tú" en vez de "usted"

```suggestion
Puedes inspeccionar los leases de cada kube-apiserver buscando objetos leases en el espacio de nombres `kube-system`
```

2024-04-28 05:36 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +con el nombre `kube-apiserver-<sha256-hash>`. También puede utilizar el selector de etiquetas `apiserver.kubernetes.io/identity=kube-apiserver`:
Usar la forma "tú" en vez de "usted".

```suggestion
con el nombre `kube-apiserver-<sha256-hash>`. También puedes utilizar el selector de etiquetas `apiserver.kubernetes.io/identity=kube-apiserver`:
```

2024-04-28 05:37 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +asumirán los leases existentes utilizando una nueva identidad de titular, en lugar de instanciar nuevos objetos leases. Puede comprobar el
Usar la forma "tú" en vez de "usted".

```suggestion
asumirán los leases existentes utilizando una nueva identidad de titular, en lugar de instanciar nuevos objetos leases. Puedes comprobar el
```

2024-04-28 05:37 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +Puede desactivar el lease de identidades del servidor API desactivando la opción `APIServerIdentity` de la [puerta de función](/docs/reference/command-line-tools-reference/feature-gates/).
Usar la forma "tú" en vez de "usted".

```suggestion
Puedes desactivar el lease de identidades del servidor API desactivando la opción `APIServerIdentity` de la [puerta de función](/docs/reference/command-line-tools-reference/feature-gates/).
```

2024-04-28 05:38 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +Su propia carga de trabajo puede definir su propio uso de los leases. Por ejemplo, puede ejecutar un
```suggestion
Tu propia carga de trabajo puede definir su propio uso de los leases. Por ejemplo, puedes ejecutar un
```

2024-04-28 05:39 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +realiza operaciones que sus compañeros no realizan. Usted define un Lease para que las réplicas del controlador puedan seleccionar
```suggestion
realiza operaciones que sus compañeros no realizan. Tú defines un Lease para que las réplicas del controlador puedan seleccionar
```

2024-04-28 05:39 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +Si utiliza un lease, es una buena práctica definir un nombre para el lease que esté obviamente vinculado a
```suggestion
Si utilizas un lease, es una buena práctica definir un nombre para el lease que esté obviamente vinculado a
```

2024-04-28 05:39 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +el producto o componente. Por ejemplo, si tiene un componente denominado Ejemplo Foo, utilice un lease denominado
```suggestion
el producto o componente. Por ejemplo, si tienes un componente denominado Ejemplo Foo, utiliza un lease denominado
```

2024-04-28 05:40 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +Si un operador de clúster u otro usuario final puede desplegar varias instancias de un componente, seleccione un nombre
```suggestion
Si un operador de clúster u otro usuario final puede desplegar varias instancias de un componente, selecciona un nombre
```

2024-04-28 05:40 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +prefijo y elija un mecanismo (como el hash del nombre del despliegue) para evitar colisiones de nombres
```suggestion
prefijo y elije un mecanismo (como el hash del nombre del despliegue) para evitar colisiones de nombres
```

2024-04-28 05:40 UTC, ramrodo commented on content/es/docs/concepts/architecture/leases.md
> +Puede utilizar otro enfoque siempre que consiga el mismo resultado: los distintos productos de software no entran en conflicto entre sí.
```suggestion
Puedes utilizar otro enfoque siempre que consigas el mismo resultado: los distintos productos de software no entran en conflicto entre sí.
```

2024-04-28 05:42 UTC, ramrodo requested changes
¡Gracias por ésta contribución Eduardo!

También podríamos discutir si traducimos la palabra _"namespace"_ o la dejamos en Inglés.

De igual forma, en las reuniones semanales hemos optado por manejar la forma "tú" en vez de "usted" para hacer más amable y cercana la documentación hacia la persona lectora.

2024-06-04 16:00 UTC, ramrodo commented
Great! LGTM
/approve

2024-06-04 16:04 UTC, merged