[ja] Translate content/en/docs/tasks/tools/install-kubectl-linux.md
kubernetes/website pull request #46029
Opened 2024-04-26 14:57 UTC by levi106

Fixes #45344 

This pull request is for the translation of `content/en/docs/tasks/tools/install-kubectl-linux.md` and its dependencies.

This translation is based on the contents of the [content/ja/docs/tasks/tools/install-kubectl.md](https://github.com/kubernetes/website/blob/de98cc74a50fca202fb6febcf482c99e0ca6efb4/content/ja/docs/tasks/tools/install-kubectl.md) (This file has already been deleted).

Preview: https://deploy-preview-46029--kubernetes-io-main-staging.netlify.app/ja/docs/tasks/tools/install-kubectl-linux/

2024-04-29 14:17 UTC, bells17 commented
/lgtm

2024-04-30 05:19 UTC, inductor requested changes

2024-04-30 05:19 UTC, inductor commented on content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +すべてのシェルセッションにてkubectlの補完スクリプトをsourceできるようにしなければなりません。
「sourceできるようにしなければなりません」は英語がわかる人なら意味がわかるけど、日本語を読もうとしてる人にとってはちょっと読み詰まる箇所かもしれません

2024-04-30 10:21 UTC, levi106 commented on content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +すべてのシェルセッションにてkubectlの補完スクリプトをsourceできるようにしなければなりません。
レビューありがとうございます。
元々翻訳されたドキュメント
https://github.com/kubernetes/website/blob/de98cc74a50fca202fb6febcf482c99e0ca6efb4/content/ja/docs/tasks/tools/install-kubectl.md#はじめに
があり、これはこのドキュメントが OS 毎に分割されたものとなります。
なるべく元の翻訳を変えないようにしたのですが、別の表現の方がよいでしょうか？

2024-04-30 14:32 UTC, inductor commented on content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +すべてのシェルセッションにてkubectlの補完スクリプトをsourceできるようにしなければなりません。
結構前の翻訳ですし、見直してもいい頃でしょう。

2024-04-30 16:01 UTC, levi106 commented on content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +すべてのシェルセッションにてkubectlの補完スクリプトをsourceできるようにしなければなりません。
「すべてのシェルセッションにて、kubectlの補完スクリプトが読み込まれるようにしなければなりません。」
ではどうでしょうか。

2024-05-02 22:09 UTC, inductor commented on content/ja/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md
> +すべてのシェルセッションにてkubectlの補完スクリプトをsourceできるようにしなければなりません。
```suggestion
次に、kubectl補完スクリプトがすべてのシェルセッションで読み込まれるように設定する必要があります。
```

とかですかね。"now"のニュアンスも欠落してるので

2024-05-04 23:48 UTC, inductor approved these changes
/lgtm
/approve

2024-05-04 23:51 UTC, merged