Create super-linter.yml
kubernetes/website pull request #46037
Opened 2024-04-28 06:33 UTC by Hawthorne001

2024-04-28 13:31 UTC, stmcginnis commented on .github/workflows/super-linter.yml
> +        uses: github/super-linter@v4
Looks like we probably would be fine with using the `slim` variant? https://github.com/super-linter/super-linter?tab=readme-ov-file#super-linter-variants

2024-06-11 02:40 UTC, habibrosyad commented on content/de/examples/minikube/Dockerfile
> +FROM node:20.13.1
is updating the Dockerfile for each localizations relevant in this case (adding linter)?

2024-06-23 15:12 UTC, Okabe-Junya requested changes
FYI: https://github.com/kubernetes/website/issues/43335#issuecomment-1749499930

> Make sure to use Prow for the checks (not GitHub Actions, which as a project we avoid).

I think it would be better to use Prow instead of GHA

2024-06-23 15:29 UTC, Okabe-Junya commented
Other concerns -  Why are you using super-linter instead of linters for each language? I think it is better to properly set up linters for each language.

Please note that the super-linter has a large container image and takes time to execute.

2024-12-09 20:03 UTC, closed without merging