[ja] Translate content/ja/docs/tasks/tools/_index.md
kubernetes/website pull request #46030
Opened 2024-04-26 15:46 UTC by levi106

Fixes #45855 

This pull request is for the translation of the latest `content/en/docs/tasks/tools/_index.md`.

2024-04-28 07:15 UTC, Okabe-Junya commented
/cc

2024-04-28 07:24 UTC, Okabe-Junya approved these changes
継続的なコントリビューションありがとうございます！

LGTMです！

2024-04-28 07:24 UTC, Okabe-Junya commented
/lgtm
/assign nasa9084

2024-04-30 05:21 UTC, inductor requested changes

2024-04-30 05:21 UTC, inductor commented on content/ja/docs/tasks/tools/_index.md
> +下記の中からお好みのオペレーティングシステムを見つけてください。
「お好みのオペレーティングシステムを見つけてください。」
なんかこう直訳感がすごいので、もうちょっと自然な日本語っぽい感じにしたいですね

2024-04-30 09:48 UTC, levi106 commented on content/ja/docs/tasks/tools/_index.md
> +下記の中からお好みのオペレーティングシステムを見つけてください。
ありがとうございます。だいぶ意訳な感じですが、以下ではどうでしょうか？
「下記の中から使用しているオペレーティングシステムを選んでください。」

2024-04-30 10:00 UTC, Okabe-Junya commented on content/ja/docs/tasks/tools/_index.md
> +下記の中からお好みのオペレーティングシステムを見つけてください。
> Find your preferred operating system below.

個人的には either is fine だと思っています。leviさんのオリジナルを尊重 & 極力直訳に寄せるということであれば、

- 下記の中から好きなオペレーティングシステムを選んでください

くらいでどうでしょうか

2024-05-03 14:06 UTC, Okabe-Junya approved these changes
/lgtm

2024-05-03 14:07 UTC, Okabe-Junya commented on content/ja/docs/tasks/tools/_index.md
> +下記の中からお好みのオペレーティングシステムを見つけてください。
ご対応ありがとうございます！LGTM打ち直しておきますね

2024-05-03 14:08 UTC, Okabe-Junya commented
/label tide/merge-method-squash

2024-05-04 23:47 UTC, inductor approved these changes
/approve

2024-05-04 23:53 UTC, merged