[bn] Localize controller.md
kubernetes/website pull request #46070
Opened 2024-04-29 11:04 UTC by aytullahdev

Localize controller.md
Resolves: #45729

2024-04-29 11:29 UTC, sajibAdhi requested changes

2024-04-29 11:29 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/controller.md
> +id: কন্ট্রোলার
we don't need to change the value of `id`.
you can keep it as before. `id: controller`

2024-04-29 11:29 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/controller.md
> +full_link: /docs/concepts/architecture/controller/
Use `full_link: /bn/docs/concepts/architecture/controller/` as we are localizing in the `bn` directory.

2024-04-29 11:29 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/controller.md
> +কুবারনেটস-এ, কন্ট্রোলার হল কন্ট্রোল লুপ যা আপনার
use `কুবারনেটিস`.

2024-04-29 11:29 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/controller.md
> +কুবারনেটস এর অপারেশন মূল. যেমন: ডিপ্লয়মেন্ট কন্ট্রোলার,
use `কুবারনেটিস` instead of `কুবারনেটস`.

2024-05-01 13:28 UTC, sftim commented on content/bn/docs/reference/glossary/controller.md
> +full_link: /bn/docs/concepts/architecture/controller/
Does this link actually exist in [kubernetes:dev-1.24-bn.1](https://github.com/kubernetes/website/tree/dev-1.24-bn.1)? If not, we should hold this PR until that link works.

2024-05-02 03:35 UTC, asem-hamid commented on content/bn/docs/reference/glossary/controller.md
> +date: ২০১৮-০৪-১২
date: 2018-04-12

2024-05-02 03:39 UTC, asem-hamid commented on content/bn/docs/reference/glossary/controller.md
> +  একটি কন্ট্রোল লুপ যা এপিসার্ভারের মাধ্যমে ক্লাস্টারের ভাগ করা অবস্থা পর্যবেক্ষণ করে এবং বর্তমান অবস্থাকে পছন্দসই অবস্থায় নিয়ে যাওয়ার চেষ্টা করে।
একটি কন্ট্রোল লুপ যা API সার্ভারের মাধ্যমে ক্লাস্টারের শেয়ার করা অবস্থা দেখে এবং বর্তমান অবস্থাকে কাঙ্ক্ষিত অবস্থায় নিয়ে যাওয়ার চেষ্টা করে পরিবর্তন করে।

2024-05-02 03:41 UTC, asem-hamid commented on content/bn/docs/reference/glossary/controller.md
> +প্রতিটি কন্ট্রোলার বর্তমান ক্লাস্টার অবস্থাকে পছন্দসই অবস্থার কাছাকাছি নিয়ে যাওয়ার চেষ্টা করে।
কুবারনেটিসে, কন্ট্রোলার হলো কন্ট্রোল লুপ যা আপনার
{{< glossary_tooltip term_id="cluster" text="ক্লাস্টার">}} এর অবস্থা দেখে, 
তারপর প্রয়োজনে পরিবর্তন করে বা করতে অনুরোধ করে।
প্রতিটি কন্ট্রোলার বর্তমান ক্লাস্টার অবস্থাকে কাঙ্ক্ষিত অবস্থার কাছাকাছি 
নিয়ে যাওয়ার চেষ্টা করে।

2024-05-02 03:45 UTC, asem-hamid commented on content/bn/docs/reference/glossary/controller.md
> +{{< glossary_tooltip term_id="control-plane" >}})।
কন্ট্রোলাররা {{< glossary_tooltip text="API সার্ভার" term_id="kube-apiserver" >}}
({{< glossary_tooltip term_id="control-plane" >}} এর অংশ)
এর মাধ্যমে আপনার ক্লাস্টারের শেয়ার করা অবস্থা দেখে।

2024-05-02 03:48 UTC, asem-hamid commented on content/bn/docs/reference/glossary/controller.md
> +{{< glossary_tooltip term_id="kube-controller-manager" >}}।
কিছু কন্ট্রোলার কন্ট্রোল প্লেনের অভ্যন্তরেও চলে, কন্ট্রোল লুপ প্রদান করে 
যা কুবারনেটিসের অপারেশনের মূল। যেমন: ডিপ্লয়মেন্ট কন্ট্রোলার, 
ডেমনসেট কন্ট্রোলার, নেমস্পেস কন্ট্রোলার এবং পারসিসটেন্ট ভলিউম 
কন্ট্রোলার (এবং অন্যান্য) সবই 
{{< glossary_tooltip term_id="kube-controller-manager" >}} -এর মধ্যে চলে।

2024-05-07 14:44 UTC, asem-hamid commented
@aytullahdev Please fix them

2024-05-14 09:58 UTC, asem-hamid commented
to fix netlify build  errors follow this steps :

![image](https://github.com/kubernetes/website/assets/155321064/d0ce2ec3-493d-4714-92ac-06af445acb97)


 1 ) go to your fork repo .
 2) go to dev-1.24-bn.1 branch 
 3 ) sync fork  
     
![image](https://github.com/kubernetes/website/assets/155321064/de0d0cf4-df14-4648-acfa-1443fc9a9470)

4) go to PR section and create new PR 

![image](https://github.com/kubernetes/website/assets/155321064/cdac5ab0-10b1-48ea-81e9-679501fdb58a)


5) take your own forked repo as a base repository 

![image](https://github.com/kubernetes/website/assets/155321064/5a0acf04-0753-4275-90ff-96dde7bb21c9)


6) take your PR branch as base 

![image](https://github.com/kubernetes/website/assets/155321064/cb892f4d-37c5-4157-b1d5-709a63b7db3c)


7) take dev-1.24-bn.1 as compare and create PR  

![image](https://github.com/kubernetes/website/assets/155321064/5affb194-d03a-4d80-aca0-6cd38c66b867)


8)  
![image](https://github.com/kubernetes/website/assets/155321064/fbf7bfed-2920-41d0-86f4-439e16d03426)

9) merge this PR 

![image](https://github.com/kubernetes/website/assets/155321064/a8a53089-f504-43c6-bb10-ca623b77f70c)

10 ) and done

2024-09-16 06:06 UTC, asem-hamid commented
@aytullahdev, are you still working on this task? Please let me know; otherwise, I will close this PR and unassign you.

Since we now have our new working branch `dev-1.31-bn.1`, you'll need to create a fresh PR with the following details:

- **Source repo**: `kubernetes/website`
- **Source branch**: `dev-1.31-bn.1`
- **Target branch**: `dev-1.31-bn.1`

2024-10-03 13:07 UTC, asem-hamid commented
for inactivity /close

2024-10-03 13:07 UTC, asem-hamid commented
/close

2024-10-03 13:07 UTC, closed without merging