docs: updates automatics reloading behaviour.
kubernetes/website pull request #46113
Opened 2024-05-01 21:22 UTC by nilekhc

Fixes https://github.com/kubernetes/kubernetes/issues/122563

/cc @enj @aramase

2024-05-01 22:29 UTC, aramase requested changes
```bash
--encryption-provider-config-automatic-reload boolean argument determines if the file set by --encryption-provider-config should be automatically reloaded if the disk contents change. This enables key rotation without API server restarts.
```
in https://kubernetes.io/docs/tasks/administer-cluster/kms-provider/#encrypting-your-data-with-the-kms-provider needs to be updated as well.

Also, can you add a note about the metric `apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds ` that can be used to detect reload status?

2024-05-04 01:07 UTC, tengqm commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +1. `--encryption-provider-config-automatic-reload` boolean argument determines if the file set by `--encryption-provider-config` should be automatically reloaded if the disk contents change. The Encr
Add a 'The' and wrap the long lines properly.
```suggestion
1. `--encryption-provider-config-automatic-reload` boolean argument determines
   if the file set by `--encryption-provider-config` should be automatically reloaded
   if the disk contents change. The Encryption configuration file is polled every minute
   to check if the disk content has changed. This enables key rotation without API
   server restarts.
   The `apiserver_encryption_config_controller_automatic_reload_last_timestamp_seconds`
   metric correctly identifies when the new config becomes effective.
```

2024-05-06 22:52 UTC, tengqm commented
/lgtm

2024-05-07 20:47 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +1. `--encryption-provider-config-automatic-reload` boolean argument determines
I think the other page should have this detailed doc, and this KMS page should just link to that section.

2024-05-07 20:47 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +   metric correctly identifies when the new config becomes effective.
```suggestion
   metric identifies when the new config becomes effective.
```

2024-05-08 16:03 UTC, enj requested changes

2024-05-08 16:03 UTC, enj commented on content/en/docs/tasks/administer-cluster/kms-provider.md
> +   rotation without API server restarts.
```suggestion
   [automatically reloaded](/docs/tasks/administer-cluster/encrypt-data/#configure-automatic-reloading) if the disk contents change.
```

2024-05-08 16:03 UTC, enj commented on content/en/docs/tasks/administer-cluster/encrypt-data.md
> +metric identifies when the new config becomes effective.
```suggestion
metric identifies when the new config becomes effective. This allows
encryption keys to be rotated without restarting the API server.
```

2024-05-14 17:17 UTC, salaxander commented
/approve

2024-05-14 17:19 UTC, merged