[bn] Localize gateway.md
kubernetes/website pull request #46124
Opened 2024-05-02 09:39 UTC by sadique21hs

Localize gateway.md
fixes issue: #45729

2024-05-13 05:31 UTC, sajibAdhi requested changes
Kindly update those changes.

2024-05-13 05:31 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/gateway.md
> +title: প্রবেশপথ এ পি আই (API)
title: গেটওয়ে API

2024-05-13 05:31 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/gateway.md
> +date: ২০২৩/১০/১৯
date: 2023-10-19

2024-05-13 05:31 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/gateway.md
> +  Kubernetes-এ মডেলিং পরিষেবা নেটওয়ার্কিংয়ের জন্য একটি এ পি আই (API)।
কুবারনেটিস-এ মডেলিং সার্ভিস নেটওয়ার্কিংয়ের জন্য একটি API।

2024-05-13 05:31 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/gateway.md
> +Kubernetes-এ মডেলিং পরিষেবা নেটওয়ার্কিংয়ের জন্য এ পি আই (API) ধরণের একটি পরিবার।
কুবারনেটিস-এ মডেলিং সার্ভিস নেটওয়ার্কিংয়ের জন্য API ধরণের একটি ফ্যামিলি।

2024-05-13 05:31 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/gateway.md
> +Kubernetes-এ মডেলিং পরিষেবা নেটওয়ার্কিংয়ের জন্য API এক প্রকার।
```
গেটওয়ে API কুবারনেটিস-এ মডেলিং সার্ভিস নেটওয়ার্কিংয়ের জন্য এক্সটেনসিবল, রোল-ভিত্তিক, প্রোটোকল-সচেতন
API ধরণের একটি পরিবার সরবরাহ করে।
```

2024-05-14 06:44 UTC, sajibAdhi reviewed
/lgtm

2024-05-14 07:35 UTC, asem-hamid commented
o fix netlify build  errors follow this steps :

![image](https://github.com/kubernetes/website/assets/155321064/d0ce2ec3-493d-4714-92ac-06af445acb97)


 1 ) go to your fork repo .
 2) go to dev-1.24-bn.1 branch 
 3 ) sync fork  
     
![image](https://github.com/kubernetes/website/assets/155321064/de0d0cf4-df14-4648-acfa-1443fc9a9470)

4) go to PR section and create new PR 

![image](https://github.com/kubernetes/website/assets/155321064/cdac5ab0-10b1-48ea-81e9-679501fdb58a)


5) take your own forked repo as a base repository 

![image](https://github.com/kubernetes/website/assets/155321064/5a0acf04-0753-4275-90ff-96dde7bb21c9)


6) take your PR branch as base 

![image](https://github.com/kubernetes/website/assets/155321064/cb892f4d-37c5-4157-b1d5-709a63b7db3c)


7) take dev-1.24-bn.1 as compare and create PR  

![image](https://github.com/kubernetes/website/assets/155321064/5affb194-d03a-4d80-aca0-6cd38c66b867)


8)  
![image](https://github.com/kubernetes/website/assets/155321064/fbf7bfed-2920-41d0-86f4-439e16d03426)

9) merge this PR 

![image](https://github.com/kubernetes/website/assets/155321064/a8a53089-f504-43c6-bb10-ca623b77f70c)

10 ) and done

2024-05-14 07:37 UTC, asem-hamid commented
@sadique21hs  let me know ([here](https://kubernetes.slack.com/team/U06DG1EBR9S)) if you stuck anywhere

2024-05-14 08:36 UTC, asem-hamid commented
Good job @sadique21hs   , one little fix , please change targeted branch dev-1.24-bn.1 to main 

![image](https://github.com/kubernetes/website/assets/155321064/3ec70832-0c79-45f9-b5ab-810a6e739516)

2024-05-14 09:52 UTC, sajibAdhi reviewed
/lgtm

2024-05-14 09:55 UTC, asem-hamid commented
@sadique21hs thank you

2024-05-14 09:55 UTC, asem-hamid approved these changes

2024-05-14 09:57 UTC, merged