[bn] Localization of service-account.md
kubernetes/website pull request #46136
Opened 2024-05-02 14:34 UTC by Ashfinn

Resolves : #45729

2024-05-02 15:10 UTC, sajibAdhi requested changes

2024-05-02 15:23 UTC, Ashfinn commented on content/bn/docs/reference/glossary/service-account.md
> +  পডগুলিতে চলমান কার্যক্রমের জন্য একটি পরিচিতি সরবরাহ করে।
fixed it

2024-05-02 15:24 UTC, Ashfinn commented on content/bn/docs/reference/glossary/service-account.md
> +যখন পডগুলির ভেতরের প্রক্রিয়াগুলি ক্লাস্টার অ্যাক্সেস করে, তাদেরকে প্রাসঙ্গিক সার্ভিস অ্যাকাউন্ট হিসেবে API সার্ভার দ্বারা অথেনটিকেট(authenticate) করা হয়, উদাহরণস্বরূপ, `default`। যদি আপনি সার্ভিস অ
fixed it too

2024-05-07 14:58 UTC, asem-hamid commented
/lgtm

2024-05-08 04:15 UTC, mitul3737 approved these changes

2024-05-08 04:23 UTC, sajibAdhi approved these changes
/lgtm

2024-05-08 04:40 UTC, Imtiaz1234 approved these changes

2024-05-08 04:43 UTC, merged