Move App Deployment from SIG CLI guides to the kubectl reference
kubernetes/website pull request #46158
Opened 2024-05-03 11:32 UTC by T-Lakshmi

Fixes #45662

2024-05-03 12:04 UTC, T-Lakshmi commented
[Preview page](https://deploy-preview-46158--kubernetes-io-main-staging.netlify.app/docs/reference/kubectl/app_deployment/)

2024-07-29 06:05 UTC, T-Lakshmi commented
Hello @reylejano, @kbhawkey,
Requesting for PR Review, can you please take a look once.

2024-07-31 07:38 UTC, T-Lakshmi commented
Hello @kbhawkey, @reylejano,
Requesting for your review feedback on this PR.
PTAL!

2024-10-31 11:24 UTC, divya-mohan0209 commented
/remove-lifecycle stale

2024-10-31 11:30 UTC, divya-mohan0209 requested changes
The preview doesn't show all the pages moved. Please check and amend appropriately.

2025-02-22 23:59 UTC, nate-double-u commented
Hi @T-Lakshmi, thanks for this.

I'm closing this PR as stale since some change requests were made but not responded to in over 2 weeks. Please feel free to reopen it if you would like to continue the work.

/close

2025-02-22 23:59 UTC, closed without merging