[bn] Localization of  Content/bn/releases/release.md
kubernetes/website pull request #46249
Opened 2024-05-07 13:34 UTC by radiumSodium

[bn] Localization of  Content/bn/releases/release.md

Fixes : #44993
Resolves : #44993

2024-05-07 13:47 UTC, asem-hamid commented on content/bn/releases/release.md
> +এই কনটেন্ট স্বয়ংক্রিয়ভাবে তৈরি এবং লিঙ্কগুলি কাজ নাও করতে পারে৷ উকুমেন্টটির সোর্স অবস্থিত [এখানে](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/release.md).
ডকুমেন্টটির

2024-05-07 14:00 UTC, asem-hamid commented on content/bn/releases/release.md
> +পুল রিকুয়েস্টের পথে পরিচালিত হয়।
গিটহাব

2024-05-07 14:03 UTC, asem-hamid commented on content/bn/releases/release.md
> +- *[প্রুনিং](https://git.k8s.io/sig-release/releases/release_phases.md#pruning)*:
Pruning

2024-05-07 14:05 UTC, asem-hamid commented on content/bn/releases/release.md
> +  প্রায় 12 মাসের জন্য `vX.Y.Z` প্যাচ রিলিজ সহ মুক্তি।
`vX.Y-rc.0` রিলিজের সময় তৈরি করা হয়েছে এবং রিলিজের পর 
প্রায় ১২ মাস ধরে `vX.Y.Z` প্যাচ রিলিজের সাথে রক্ষণাবেক্ষণ করা হয়েছে।

2024-05-07 14:06 UTC, asem-hamid commented on content/bn/releases/release.md
> +  রিলিজ 1.18 এবং তার আগে 9 মাসের প্যাচ রিলিজ সমর্থন পেয়েছে।
সাপোর্ট

2024-05-07 14:16 UTC, asem-hamid commented on content/bn/releases/release.md
> +কিন্তু বাস্তবে, এটি একটি ওপেন সোর্স এবং চটপটে প্রকল্প, ফিচার পরিকল্পনা
কিন্তু বাস্তবে, এটি একটি ওপেন সোর্স এবং অ্যাজাইল(agile) প্রকল্প, ফিচার পরিকল্পনা

2024-05-07 14:41 UTC, asem-hamid commented
@radiumSodium  Please fix them

2024-05-07 17:15 UTC, asem-hamid requested changes

2024-05-08 04:23 UTC, mitul3737 approved these changes

2024-05-08 04:39 UTC, Imtiaz1234 approved these changes

2024-05-08 04:40 UTC, Imtiaz1234 approved these changes

2024-05-08 04:42 UTC, Imtiaz1234 commented
/lgtm

2024-05-08 05:03 UTC, asem-hamid commented
/approve

2024-05-08 06:40 UTC, asem-hamid commented
To fix netlify build  errors follow this steps :

![image](https://github.com/kubernetes/website/assets/155321064/d0ce2ec3-493d-4714-92ac-06af445acb97)


 1 ) go to your fork repo .
 2) go to dev-1.24-bn.1 branch 
 3 ) sync fork  
     
![image](https://github.com/kubernetes/website/assets/155321064/de0d0cf4-df14-4648-acfa-1443fc9a9470)

4) go to PR section and create new PR 

![image](https://github.com/kubernetes/website/assets/155321064/cdac5ab0-10b1-48ea-81e9-679501fdb58a)


5) take your own forked repo as a base repository 

![image](https://github.com/kubernetes/website/assets/155321064/5a0acf04-0753-4275-90ff-96dde7bb21c9)


6) take your PR branch as base 

![image](https://github.com/kubernetes/website/assets/155321064/cb892f4d-37c5-4157-b1d5-709a63b7db3c)


7) take dev-1.24-bn.1 as compare and create PR  

![image](https://github.com/kubernetes/website/assets/155321064/5affb194-d03a-4d80-aca0-6cd38c66b867)


8)  
![image](https://github.com/kubernetes/website/assets/155321064/fbf7bfed-2920-41d0-86f4-439e16d03426)

9) merge this PR 

![image](https://github.com/kubernetes/website/assets/155321064/a8a53089-f504-43c6-bb10-ca623b77f70c)

10 ) and done

2024-05-08 06:40 UTC, asem-hamid commented
@radiumSodium  Kubernetes is one of the largest open-source repositories in the world, and as such, we encounter many obstacles along the way. It's our responsibility to address and overcome them  as a contributor .

2024-05-08 08:20 UTC, asem-hamid commented
/lgtm 

great work

2024-05-08 08:23 UTC, merged