[zh-cn] sync ingress-minikube.md
kubernetes/website pull request #46250
Opened 2024-05-07 14:06 UTC by my-git9

content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md

2024-05-08 00:12 UTC, tengqm commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +如果你在具有不同 CPU 架构的计算机上使用 minikube，可以尝试使用带有可以模拟 AMD64 的驱动程序的 minikube。
```suggestion
如果你在其他 CPU 架构的计算机上使用 minikube，可以尝试使用带有可以模拟 AMD64 的驱动程序的 minikube。
```

2024-05-08 00:12 UTC, tengqm commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +   要让 ingress 正常工作，你需要打开一个新终端并运行 `minikube tunnel`。
```suggestion
   要让 Ingress 正常工作，你需要打开一个新终端并运行 `minikube tunnel`。
```

2024-05-08 00:12 UTC, tengqm commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +   它需要 `sudo` 权限，因此请在出现提示时提供密码。
```suggestion
   此操作需要 `sudo` 权限，因此请在出现提示时提供密码。
```

2024-05-08 02:50 UTC, mengjiao-liu requested changes
Please check it again from [the preview page](https://deploy-preview-46250--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/access-application-cluster/ingress-minikube/).

2024-05-08 02:50 UTC, mengjiao-liu commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +    ```
![image](https://github.com/kubernetes/website/assets/44460091/bf78a9c7-86d4-4a90-8a18-0f4d926d9cc0)

格式渲染不对。
Preview page: https://deploy-preview-46250--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/access-application-cluster/ingress-minikube/

2024-05-08 02:50 UTC, mengjiao-liu commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +    ```
![image](https://github.com/kubernetes/website/assets/44460091/ddeea216-70ff-4974-b925-68bc3d7312eb)

same above。

2024-05-08 02:50 UTC, mengjiao-liu commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +   ```
same above

2024-05-08 02:50 UTC, mengjiao-liu commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +    ```
same above.

2024-05-08 05:37 UTC, my-git9 commented on content/zh-cn/docs/tasks/access-application-cluster/ingress-minikube.md
> +    ```
Fixed, thx

2024-05-08 08:56 UTC, windsonsea commented
The [preview](https://deploy-preview-46250--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/access-application-cluster/ingress-minikube/#create-second-deployment) still has some issue, like this note:

```
更改 IP 地址以匹配 `minikube ip` 的输出。
```

2024-05-08 13:45 UTC, my-git9 commented
> The [preview](https://deploy-preview-46250--kubernetes-io-main-staging.netlify.app/zh-cn/docs/tasks/access-application-cluster/ingress-minikube/#create-second-deployment) still has some issue, like this note:
> 
> ```
> 更改 IP 地址以匹配 `minikube ip` 的输出。
> ```

Fixed, thx

2024-05-09 01:11 UTC, windsonsea reviewed
/approve

2024-05-09 02:53 UTC, tengqm commented
/lgtm

2024-05-09 02:58 UTC, merged