[ja] Localization of content/ja/docs/reference/glossary/cidr.md
kubernetes/website pull request #46267
Opened 2024-05-08 08:12 UTC by hihumikan

close https://github.com/kubernetes/website/issues/45112

# Change List
- Translate [content/en/docs/reference/glossary/cidr.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/cidr.md) into Japanese

2024-05-08 08:13 UTC, hihumikan commented
/assign Okabe-Junya

2024-05-08 08:16 UTC, Okabe-Junya commented
ありがとうございます！後ほどレビューさせて頂きますね

2024-05-08 16:51 UTC, Okabe-Junya commented
Deploy preview: https://deploy-preview-46267--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-cidr

2024-05-08 16:55 UTC, Okabe-Junya requested changes
コントリビューションありがとうございます！2点ほどコメントさせていただいたのでご確認をお願いいたします

2024-05-08 16:55 UTC, Okabe-Junya commented
/assign nasa9084

2024-05-08 21:51 UTC, hihumikan commented
@Okabe-Junya 
レビュー頂きありがとうございます！！
先ほど修正コミットしましたのでご確認お願いします！🙏

2024-05-09 00:09 UTC, Okabe-Junya approved these changes
ありがとうございます！LGTMです！

/lgtm

2024-05-15 03:25 UTC, bells17 commented
/lgtm too

2024-05-15 09:07 UTC, inductor commented on content/ja/docs/reference/glossary/cidr.md
> +CIDR (Classless Inter-Domain Routing)はIPアドレスの範囲を記述するための表記法であり、さまざまなネットワークを構成するために使用されています。
```suggestion
CIDR(Classless Inter-Domain Routing)はIPアドレスの範囲を記述するための表記法であり、さまざまなネットワークを構成するために使用されています。
```

ここのスペースって入れるんだっけ？ @Okabe-Junya

2024-05-15 09:25 UTC, inductor commented
/assign @seokho-son

2024-05-15 09:26 UTC, inductor commented
/unassign @seokho-son sorry that was a mistake

2024-05-15 09:27 UTC, inductor commented
/unassign @seokho-son

2024-05-15 09:27 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cidr.md
> +CIDR (Classless Inter-Domain Routing)はIPアドレスの範囲を記述するための表記法であり、さまざまなネットワークを構成するために使用されています。
半角同士なので入れた方が良いですー

2024-05-15 11:27 UTC, inductor commented on content/ja/docs/reference/glossary/cidr.md
> +CIDR (Classless Inter-Domain Routing)はIPアドレスの範囲を記述するための表記法であり、さまざまなネットワークを構成するために使用されています。
![image](https://github.com/kubernetes/website/assets/20236173/c9e5a918-c7da-45ac-b539-48ee02b15834)
そんなことなさそう

2024-05-15 11:38 UTC, inductor commented on content/ja/docs/reference/glossary/cidr.md
> +CIDR (Classless Inter-Domain Routing)はIPアドレスの範囲を記述するための表記法であり、さまざまなネットワークを構成するために使用されています。
議論の結果入れないことになった。

2024-05-15 11:38 UTC, inductor commented
/lgtm
/approve

2024-05-15 11:44 UTC, merged