Drop param shortcode
kubernetes/website pull request #46324
Opened 2024-05-11 19:59 UTC by sftim

We don't use the `param` shortcode (we switched to a new approach in PR https://github.com/kubernetes/website/pull/40692)

Drop that shortcode. As part of this, switch Bengali to the new approach.

/area web-development

2024-05-11 19:59 UTC, sftim commented on content/bn/docs/tasks/tools/install-kubectl-windows.md
> +1. [kubectl {{% skew currentPatchVersion %}}](https://dl.k8s.io/release/v{{% skew currentPatchVersion %}}/bin/windows/amd64/kubectl.exe) এর সর্বশেষ প্রকাশ ডাউনলোড করুন
This is a machine-aided translation; I don't speak Bengali

2024-05-12 00:08 UTC, dipesh-rawat reviewed
Overall, the change looks good! 
_Just added an observation on the removal of shortcode._

LGTM

2024-05-12 00:08 UTC, dipesh-rawat commented on layouts/shortcodes/param.html
I'm surprised that removing the shortcode HTML file hasn't caused build errors, considering there are still instances in the repo where the `<param>` shortcode is used ([example 1](https://github.com/kubernetes/website/blob/ea4444a8498bab841af7ea1dd56ffb35a9247d32/content/en/docs/concepts/workloads/pods/_index.md?plain=1#L224), [example 2](https://github.com/kubernetes/website/blob/d8e55f2ec1d66d115860d80c4011de5965c90881/content/en/releases/download.md?plain=1#L56)). I assume now the site is using the shortcode source retrieved from Docsy or its dependencies during the build process.

2024-05-12 01:04 UTC, sftim commented
/retitle Drop param shortcodes, warn on new use

2024-05-12 01:07 UTC, sftim commented
Do we want to merge this with lots of pages showing warnings, or split out the Bengali fixes, or something else?

2024-05-12 01:35 UTC, sftim commented
/retitle Fix legacy param shortcodes; warn on new use

2024-05-12 06:59 UTC, asem-hamid requested changes

2024-05-12 06:59 UTC, asem-hamid commented on content/bn/docs/tasks/tools/install-kubectl-windows.md
> +1. [kubectl {{% skew currentPatchVersion %}}](https://dl.k8s.io/release/v{{% skew currentPatchVersion %}}/bin/windows/amd64/kubectl.exe) এর সর্বশেষ প্রকাশ ডাউনলোড করুন।
```suggestion
1. সর্বশেষ {{< skew currentVersion >}} প্যাচ রিলিজ ডাউনলোড করুন: [kubectl {{% skew currentPatchVersion %}}](https://dl.k8s.io/release/v{{% skew currentPatchVersion %}}/bin/windows/amd64/kubectl.exe)।
```

2024-05-12 07:06 UTC, asem-hamid requested changes

2024-05-12 07:06 UTC, asem-hamid commented on content/bn/docs/tasks/tools/install-kubectl-windows.md
> +1. [kubectl {{% skew currentPatchVersion %}}](https://dl.k8s.io/release/v{{% skew currentPatchVersion %}}/bin/windows/amd64/kubectl.exe) এর সর্বশেষ প্রকাশ ডাউনলোড করুন।
```suggestion
1. সর্বশেষ {{< skew currentVersion >}} প্যাচ রিলিজ ডাউনলোড করুন: [kubectl {{% skew currentPatchVersion %}}](https://dl.k8s.io/release/v{{% skew currentPatchVersion %}}/bin/windows/amd64/kubectl.exe)।
```

2024-05-12 23:49 UTC, dipesh-rawat commented
> Do we want to merge this with lots of pages showing warnings, or split out the Bengali fixes, or something else?

Focusing this PR specifically on Bengali fixes makes a lot of sense. For the other changes related to shortcode and its usage in English doc pages and blogs, let's include those in a separate PR. This will help in review and also adhere more closely to the practice of making changes to a single language per PR.

2024-05-13 09:45 UTC, ydFu commented
> Do we want to merge this with lots of pages showing warnings, or split out the Bengali fixes, or something else?

It is recommended to ask reviewers from different languages ​​to review the changed localization content before merging it.

2024-05-13 12:29 UTC, ricardoamaro commented
I have reviewed this pull request. 
It is well-structured and moves towards a more maintainable and standardized way of handling version references and other parameters within the site's content.
I agree that reviewers from different languages should look at the changed localization content before merging it.

2024-05-13 12:36 UTC, sftim commented
/hold

Let's rebase this on _main_ once language-specific fixes have merged in.

2024-05-13 12:47 UTC, asem-hamid commented
bn fixes has been merged in this [PR](https://github.com/kubernetes/website/pull/46346)

2024-05-15 20:35 UTC, sftim commented
/retitle Warn on new use of param shortcode

2024-05-15 20:36 UTC, sftim commented
/remove-area blog release

2024-05-15 20:37 UTC, sftim commented on layouts/shortcodes/param.html
> +{{- else }}{{ errorf "Missing param key: %s" $.Position }}{{ end -}}
This is Hugo's default `param` shortcode.

2024-05-15 20:37 UTC, sftim commented on layouts/shortcodes/param.html
> +{{- end -}}
This is our warning mechanism.

2024-05-15 20:39 UTC, sftim commented
Updated. This PR won't add warnings, but future pages that use `param` might make a new warning show up.

2024-05-15 20:40 UTC, sftim commented
/hold cancel

The fixes to Bengali have merged.

2024-05-15 23:20 UTC, dipesh-rawat commented
/remove-language bn
/remove-area release-eng 
/remove-sig release

2024-05-15 23:21 UTC, dipesh-rawat reviewed
The changes look good!

/lgtm

2024-05-16 03:29 UTC, ydFu commented
/lgtm
This change can solve specific problems and will not involve files with cross-language permissions.

2024-05-16 15:54 UTC, salaxander commented
/approve

2024-05-16 15:59 UTC, merged