[hi] Resolved Stale Homepage of site
kubernetes/website pull request #46406
Opened 2024-05-16 16:59 UTC by niranjandarshann

[hi] Resolved Stale Homepage of site

2024-05-16 17:04 UTC, niranjandarshann commented
Deployment Preview
https://deploy-preview-46406--kubernetes-io-main-staging.netlify.app/hi/

2024-05-16 17:32 UTC, sftim requested changes
I'm afraid you won't like the feedback, but we can't accept English content for Hindi. You need to localize the pages for Hindi.

/hold
OK to unhold if [all] the content in this PR is localized for Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/ancestry/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/adform/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/adidas/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/amadeus/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/ant-financial/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/babylon/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/blablacar/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/blackrock/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/booking-com/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/bose/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/box/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/buffer/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/capital-one/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/chinaunicom/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/city-of-montreal/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/daocloud/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/ing/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/tasks/run-application/horizontal-pod-autoscale.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/workloads/controllers/replicaset.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/workloads/controllers/job.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/workloads/controllers/deployment.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/storage/persistent-volumes.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/extend-kubernetes/operator.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/extend-kubernetes/_index.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/configuration/secret.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/docs/concepts/configuration/manage-resources-containers.md
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/zalando/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/ygrene/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/workiva/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/woorank/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/wikimedia/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/vsco/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/thredup/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/squarespace/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/spotify/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/sos/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/slingtv/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/slamtec/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/ricardo-ch/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/prowise/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/pinterest/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/peardeck/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/openAI/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/ocado/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/northwestern-mutual/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/nordstrom/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/nokia/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/newyorktimes/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/jd-com/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/ibm/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/haufegroup/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/denso/index.html
This doesn't look like Hindi.

2024-05-16 17:32 UTC, sftim commented on content/hi/case-studies/crowdfire/index.html
This doesn't look like Hindi.

2024-05-17 03:33 UTC, niranjandarshann commented
@sftim  Thank you for your feedback, What i think is, The Case studies are the point of view /experience by different industries in respect of k8s like Why they are using and how k8s is useful in their project. How they are utilizing k8s for their Project. Due to which i dont think it will be good to translate all the elements of the case- studies in hindi. As You can see the Same think for the Zn-ch localization  aswell they put the case studies element as it is in english only.

2024-05-17 03:40 UTC, niranjandarshann commented
@sftim  For Feature and Glossary, yes We can translate the detailed explaination in hindi which will look good but it will take some time or The PR may go large enough to review.
So What i think is we can raise other PR after it get merge So that Working in Chunk will give the best feedback and proper work instead of bulk. Thats Why I had changed raised it as this PR will have lots of Work to do. But in bulk it will be time comsuming. 
Same For glossary 
I amOk with it if this PR wait for bulk  with more than 40 file translation.

2024-05-17 03:48 UTC, niranjandarshann commented on content/hi/case-studies/ancestry/index.html
@sftim  What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so.  But what we can translate we had did .

2024-05-17 03:48 UTC, niranjandarshann commented on content/hi/case-studies/adform/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:48 UTC, niranjandarshann commented on content/hi/case-studies/adidas/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:49 UTC, niranjandarshann commented on content/hi/case-studies/amadeus/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:49 UTC, niranjandarshann commented on content/hi/case-studies/ant-financial/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:49 UTC, niranjandarshann commented on content/hi/case-studies/babylon/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:49 UTC, niranjandarshann commented on content/hi/case-studies/blablacar/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:50 UTC, niranjandarshann commented on content/hi/case-studies/blackrock/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:50 UTC, niranjandarshann commented on content/hi/case-studies/booking-com/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:50 UTC, niranjandarshann commented on content/hi/case-studies/bose/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:50 UTC, niranjandarshann commented on content/hi/case-studies/box/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:50 UTC, niranjandarshann commented on content/hi/case-studies/buffer/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:50 UTC, niranjandarshann commented on content/hi/case-studies/capital-one/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:51 UTC, niranjandarshann commented on content/hi/case-studies/chinaunicom/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:51 UTC, niranjandarshann commented on content/hi/case-studies/city-of-montreal/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:51 UTC, niranjandarshann commented on content/hi/case-studies/daocloud/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:51 UTC, niranjandarshann commented on content/hi/case-studies/ing/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:52 UTC, niranjandarshann commented on content/hi/case-studies/haufegroup/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:52 UTC, niranjandarshann commented on content/hi/case-studies/golfnow/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:52 UTC, niranjandarshann commented on content/hi/case-studies/denso/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:52 UTC, niranjandarshann commented on content/hi/case-studies/crowdfire/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:52 UTC, niranjandarshann commented on content/hi/case-studies/cern/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:53 UTC, niranjandarshann commented on content/hi/case-studies/zalando/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:53 UTC, niranjandarshann commented on content/hi/case-studies/ygrene/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:53 UTC, niranjandarshann commented on content/hi/case-studies/workiva/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:53 UTC, niranjandarshann commented on content/hi/case-studies/woorank/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:53 UTC, niranjandarshann commented on content/hi/case-studies/wikimedia/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:54 UTC, niranjandarshann commented on content/hi/case-studies/vsco/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:54 UTC, niranjandarshann commented on content/hi/case-studies/squarespace/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:54 UTC, niranjandarshann commented on content/hi/case-studies/spotify/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:54 UTC, niranjandarshann commented on content/hi/case-studies/sos/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:55 UTC, niranjandarshann commented on content/hi/case-studies/slingtv/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:55 UTC, niranjandarshann commented on content/hi/case-studies/slamtec/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:55 UTC, niranjandarshann commented on content/hi/case-studies/ricardo-ch/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:55 UTC, niranjandarshann commented on content/hi/case-studies/prowise/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:55 UTC, niranjandarshann commented on content/hi/case-studies/pinterest/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:56 UTC, niranjandarshann commented on content/hi/case-studies/peardeck/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:56 UTC, niranjandarshann commented on content/hi/case-studies/openAI/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:56 UTC, niranjandarshann commented on content/hi/case-studies/ocado/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:56 UTC, niranjandarshann commented on content/hi/case-studies/northwestern-mutual/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:57 UTC, niranjandarshann commented on content/hi/case-studies/nordstrom/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:57 UTC, niranjandarshann commented on content/hi/case-studies/nokia/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:57 UTC, niranjandarshann commented on content/hi/case-studies/newyorktimes/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:57 UTC, niranjandarshann commented on content/hi/case-studies/netease/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:58 UTC, niranjandarshann commented on content/hi/case-studies/nerdalize/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:58 UTC, niranjandarshann commented on content/hi/case-studies/nav/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:58 UTC, niranjandarshann commented on content/hi/case-studies/naic/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:58 UTC, niranjandarshann commented on content/hi/case-studies/jd-com/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 03:59 UTC, niranjandarshann commented on content/hi/case-studies/ibm/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 04:00 UTC, niranjandarshann commented on content/hi/case-studies/huawei/index.html
@sftim What i think is these are the case studies element Which is the experience by different company on the use of k8s in their project which will not good to translate it. As i Seen it with other locaization like zn-ch as well they are using the same approach thats why i and they hadnt did so. But what we can translate we had did .

2024-05-17 05:53 UTC, niranjandarshann commented
@sftim  We can make a issue  Where other contributor can also raise a PRs partially to resolve and translate  the bulk of files.

2024-05-20 04:39 UTC, divya-mohan0209 commented
My observations:
- The homepage for case studies is stale for Hindi. This needs to be updated to include the box testimonial. 
- Different localisations have different approaches. The [Chinese localisation](https://kubernetes.io/zh-cn/case-studies/) has some of the case studies localised. For example, [Zalando](https://kubernetes.io/zh-cn/case-studies/zalando), and [Netease](https://kubernetes.io/zh-cn/case-studies/netease/). They have included the files in their case-studies folder because of this. The [Korean localisation](https://kubernetes.io/ko/case-studies/) has none of the case studies localised and points to their English versions.

What I suggest:
- Instead of submitting a massive PR, these should be tackled via two different issues IMO - one issue opened to track the update on the homepage and another issue to discuss how we can approach updating the case study translations.
- Since the latter is a massive amount of work to be undertaken by a single contributor, I would consider splitting up the work among multiple contributors to grow the localisation efforts rather than taking it all on yourself.

@niranjandarshann WDYT?

2024-05-20 05:17 UTC, niranjandarshann commented
@divya-mohan0209  Yes I agree that if we distribute the related task of localization then it will be easy,  with it as i had seen one of the PR is raised for [glossary update](https://github.com/kubernetes/website/pull/45557). Which is relevant for this work. 
For case study as well we need to  raise PR for localization.
One more is if we click on the link of the Feature it will send us to the English language instead of Hindi So this also need to be localized.

What i think is first we focus on this Homepage only  after it get merged we can open further  more issue and PR.

2024-05-20 05:24 UTC, divya-mohan0209 commented
Please only use this PR to update the homepage, if need be. We can track the others via an umbrella PR and invite contributions.

2024-09-11 04:28 UTC, niranjandarshann commented
@sftim @divya-mohan0209 @dipesh-rawat  Here to localize the every components of case studies as mentioned in PR comment by @sftim It will be very large PR. Because every component is the directory having explanation page and image.

This PR is like an umbrella issue. umbrella PR . So to resolve this do i need to raise new PR by making the task list or i need to add task list in https://github.com/kubernetes/website/issues/46085  issue only.

2024-10-11 05:47 UTC, niranjandarshann commented
/area web-development

2025-01-31 03:48 UTC, niranjandarshann commented
/close

2025-01-31 03:48 UTC, closed without merging