Update KubeCon 2024 events
kubernetes/website pull request #46413
Opened 2024-05-17 03:50 UTC by shurup

Removing the past European event and adding two upcoming KubeCon 2024 events (in Hong Kong and India).

Please, note I'm intentionally removing the 2024 year from all those links' text to fit them for small screens — to prevent the situation pictured here:

![image](https://github.com/kubernetes/website/assets/1560718/fbe014af-6b87-42f8-9e45-b2663b7f3d1c)

For the same reason, I'm using the "KubeCon + CloudNativeCon China" title instead of the full long name ("KubeCon + CloudNativeCon + Open Source Summit + AI_dev China").

Fixes #46386

2024-05-17 05:23 UTC, afzal442 requested changes

2024-05-17 05:23 UTC, afzal442 commented on content/en/_index.html
> +        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2024/" button id="desktopKCButton">Attend KubeCon + CloudNativeCon North America on November 12-15</a>
Looks good. Just my viewon what you can do rather. e.g.
```suggestion
        <a href="https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america-2024/" button id="desktopKCButton">Attend KubeCon + CloudNativeCon North America on Nov 12-15, 2024</a>
```

2024-06-01 20:28 UTC, sftim commented
We could make the page [data-driven](https://gohugo.io/templates/data-templates/). Until we do, this looks good.

/lgtm

2024-06-01 23:40 UTC, dipesh-rawat reviewed
Thanks!
/approve

_Potential for improvement as part of separate work as suggested in https://github.com/kubernetes/website/pull/46413#issuecomment-2143576733_

2024-06-01 23:44 UTC, merged