[ja] Translate content/en/docs/reference/glossary/cloud-provider.md
kubernetes/website pull request #46417
Opened 2024-05-17 08:32 UTC by arisaokasaka

Closes: #45114 

This pull request is for the translation of [content/en/docs/reference/glossary/cloud-provider.md](https://github.com/kubernetes/website/blob/main/content/en/docs/reference/glossary/cloud-provider.md) .

2024-05-17 08:37 UTC, Okabe-Junya commented
/check-cla

2024-05-17 08:40 UTC, Okabe-Junya commented
@arisaokasaka 

コントリビューションありがとうございます！以下の記事などを参考にして、CLAのご対応をお願いします

- 公式ドキュメント（英語）: https://github.com/kubernetes/community/blob/master/CLA.md
- 有志の方による日本語の記事: https://qiita.com/jlandowner/items/d14d9bc8797a62b65e67

2024-05-17 08:45 UTC, arisaokasaka commented
@Okabe-Junya 
CLAの対応させていただきました！
よろしくお願いします

2024-05-17 09:11 UTC, Okabe-Junya requested changes
改めてコントリビューションありがとうございます！

何点かコメントさせていただいたので、お手隙の際にご確認お願いします！

2024-05-17 09:11 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cloud-provider.md
> +Cloud Providerは、Cloud Service Provider（CSP）と呼ばれることもあり、クラウドコンピューティングプラットフォームやサービスを提供しています。
```suggestion
Cloud Providerは、Cloud Service Provider(CSP)と呼ばれることもあり、クラウドコンピューティングプラットフォームやサービスを提供しています。
```

nits: カッコは半角を用いていただくようお願いします

ref. https://kubernetes.io/ja/docs/contribute/localization/#basic-policy

> 記号類は感嘆符「！」と疑問符「？」のみ全角、それ以外は半角で表記

2024-05-17 09:11 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cloud-provider.md
> +多くのCloud Providerは、マネージドインフラストラクチャー（Infrastructure as a ServiceやIaaSとも呼ばれる）を提供しています。
```suggestion
多くのCloud Providerは、マネージドインフラストラクチャ(Infrastructure as a ServiceやIaaSとも呼ばれる)を提供しています。
```

"re" で終わる単語（infrastructure）には長音を付与しないようにお願いします

ref. https://kubernetes.io/ja/docs/contribute/localization/#long-vowel

> -ear、-eer、-re、-ty、-dy、-ryで終わる単語は長音を付与しない
>    - 例: 「クリア」「エンジニア」「アーキテクチャ」「セキュリティ」「スタディ」「ディレクトリ」

2024-05-17 09:11 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cloud-provider.md
> +マネージドインフラストラクチャーでは、Cloud Providerがサーバー、ストレージ、ネットワーキングの責任を負い、ユーザーはKubernetesクラスタの実行など、その上のレイヤーを管理します。
```suggestion
マネージドインフラストラクチャでは、Cloud Providerがサーバー、ストレージ、ネットワーキングの責任を負い、ユーザーはKubernetesクラスターの実行など、その上のレイヤーを管理します。
```

"er" で終わる単語（cluster）には、長音を付与するようにお願いします

> - -er、-or、-ar、-cy、-gyで終わる単語は長音を付与する
>     - 例: 「クラスター」「セレクター」「サイドカー」「ポリシー」「トポロジー」

2024-05-17 09:11 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cloud-provider.md
> +Kubernetesはマネージドサービスとしても提供されています。これは、Platform as a Service（PaaS）と呼ばれることもあります。マネージドKubernetesでは、Cloud Providerは、Kubernetesのコントロールプレーンだけでなく、{{< glossary_tooltip term_id="node" text="ノード" >}}と、それらが依存するイ
```suggestion
Kubernetesはマネージドサービスとしても提供されています。これは、Platform as a Service(PaaS)と呼ばれることもあります。マネージドなKubernetesでは、Cloud Providerは、Kubernetesのコントロールプレーンだけでなく、{{< glossary_tooltip term_id="node" text="Node" >}}と、それらが依存するインフラストラクチャ(ネットワーク、ストレージ、場合によってはロードバランサーなどの他要素)にも責任を負います。
```

2024-05-17 09:11 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cloud-provider.md
全体を通してですが、"Cloud Provider" "Cloud Service Provider" という用語は固有名詞ではないので、カタカナ表記（クラウドプロバイダー / クラウドサービスプロバイダー）にした方が良いかなと思いました。

---

参考:

- Google Cloud: https://cloud.google.com/learn/what-is-a-cloud-service-provider?hl=ja
- Microsoft: https://azure.microsoft.com/ja-jp/resources/cloud-computing-dictionary/what-is-a-cloud-provider
- Red Hat: https://www.redhat.com/ja/topics/cloud-computing/what-are-cloud-providers

2024-05-17 09:12 UTC, Okabe-Junya commented
/assign nasa9084

2024-05-18 14:32 UTC, arisaokasaka commented
@Okabe-Junya 
ご確認ありがとうございます！
修正しましたので、お手隙の際にご確認お願いします

2024-05-18 15:33 UTC, Okabe-Junya approved these changes
ご対応ありがとうございます！LGTMです！

/lgtm

2024-05-20 10:44 UTC, inductor requested changes
全体的にスリムにできそうなところをまとめました

2024-05-20 10:44 UTC, inductor commented on content/ja/docs/reference/glossary/cloud-provider.md
> +  クラウドコンピューティングプラットフォームを提供する組織。
下部と揃ってない
```suggestion
クラウドコンピューティングプラットフォームを提供する企業やその他の組織。
```

2024-05-20 10:44 UTC, inductor commented on content/ja/docs/reference/glossary/cloud-provider.md
> +クラウドプロバイダーは、クラウドサービスプロバイダー(CSP)と呼ばれることもあり、クラウドコンピューティングプラットフォームやサービスを提供しています。
```suggestion
クラウドプロバイダーは、クラウドサービスプロバイダー(CSP)とも呼ばれ、クラウドコンピューティングプラットフォームやサービスを提供します。
```

2024-05-20 10:44 UTC, inductor commented on content/ja/docs/reference/glossary/cloud-provider.md
> +マネージドインフラストラクチャでは、クラウドプロバイダーがサーバー、ストレージ、ネットワーキングの責任を負い、ユーザーはKubernetesクラスターの実行など、その上のレイヤーを管理します。
```suggestion
マネージドインフラストラクチャでは、クラウドプロバイダーがサーバー、ストレージ、ネットワーキングの責任を負い、ユーザーはその上のレイヤー、例えばKubernetesクラスターの運用を管理します。
```

2024-05-20 10:44 UTC, inductor commented on content/ja/docs/reference/glossary/cloud-provider.md
> +Kubernetesはマネージドサービスとしても提供されています。これは、Platform as a Service(PaaS)と呼ばれることもあります。マネージドなKubernetesでは、クラウドプロバイダーは、Kubernetesのコントロールプレーンだけでなく、{{< glossary_tooltip term_id="node" text="Node" >}}と、それらが依存するインフ
```suggestion
また、Kubernetesをマネージドサービスとして提供する場合もあります。これはPlatform as a Service(PaaS)とも呼ばれます。マネージドKubernetesでは、クラウドプロバイダーがKubernetesのコントロールプレーンや{{< glossary_tooltip term_id="node" text="Node" >}}、ネットワーキング、ストレージ、ロードバランサーなどのインフラストラクチャを管理します。
```

2024-05-20 10:48 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/cloud-provider.md
> +  クラウドコンピューティングプラットフォームを提供する組織。
これは翻訳元の文章も異なっているからですね

2024-05-25 01:22 UTC, inductor commented
@arisaokasaka いかがでしょ？

2024-05-27 09:22 UTC, inductor approved these changes
/approve

2024-05-27 09:25 UTC, Okabe-Junya approved these changes
/lgtm

2024-05-27 09:25 UTC, Okabe-Junya commented
/hold

2024-05-27 09:25 UTC, Okabe-Junya commented
/label tide/merge-method-squash
/hold cancel

2024-05-27 09:29 UTC, merged

2024-05-28 01:54 UTC, inductor commented
@arisaokasaka Thank you for your contribution!