feat: Add image content section to images page
kubernetes/website pull request #46440
Opened 2024-05-18 12:03 UTC by sergeyshevch

Hello! This PR is aiming to solve the remaining items in #4502 especially addressing https://github.com/kubernetes/website/issues/4502#issuecomment-570288311

2024-05-20 05:27 UTC, thisisharrsh reviewed
How about we make a tooltip for `OCI artefact` so that readers can get more information about OCI?

2024-05-20 05:37 UTC, thisisharrsh commented
Deployment preview : https://deploy-preview-46440--kubernetes-io-main-staging.netlify.app/docs/concepts/containers/images/

2024-06-01 20:57 UTC, sftim requested changes
Thanks. With tweaks this could merge; without them, I need to request changes.

2024-06-01 20:57 UTC, sftim commented on content/en/docs/concepts/containers/images.md
> +A container image is an OCI artifact that that encapsulates an application and all its
This does need either a glossary tooltip or a plain hyperlink. Without it, we're making the page more confusing, not less.

2024-06-01 20:57 UTC, sftim commented on content/en/docs/concepts/containers/images.md
> +OCI images are composed of layers. Each layer is a set of files that are added to the image.
```suggestion
Container images are composed of _layers_. Each layer is a set of files that are added to the image.
```

Docker-format images have layers too. It'd be wrong to imply that only OCI images have layers.

2024-06-01 20:57 UTC, sftim commented on content/en/docs/concepts/containers/images.md
> +{{< /note >}}
Why is this important to mention? I wouldn't use a note callout here.

Try this:

```suggestion
### Artifacts that are _not_ images {#other-oci-artifacts}

Container images are only one kind of OCI artifact. You can read more about them in the [OCI Manifest Spec](https://github.com/opencontainers/image-spec/blob/main/manifest.md). Types of artifacts that are OCI compliant but not container images cannot be used by Kubernetes as container images.
```

2024-06-01 20:57 UTC, sftim commented on content/en/docs/concepts/containers/images.md
> +OCI Container images can be created using various tools and techniques.
```suggestion
Container images can be created using various tools and techniques.
```

2024-06-01 20:57 UTC, sftim commented on content/en/docs/concepts/containers/images.md
> +Some examples are: Docker, Buildah, Kaniko, and Buildpacks.
- Alphabetical order please
- And use a shortcode marker - see https://kubernetes.io/docs/contribute/style/hugo-shortcodes/#third-party-content-item

2024-07-30 12:34 UTC, sftim commented
@sergeyshevch: do you have the time to address the feedback so far?

2024-12-27 13:12 UTC, closed without merging