Revise pod lifecycle concept page
kubernetes/website pull request #46525
Opened 2024-05-24 10:27 UTC by sftim

Revise the existing docs about Pod termination.
- Fix a formatting issue
- Overall, have fewer notes
- Make sidecar containers more prominent; they are on by default in Kubernetes v1.30

Fixes #46524

/sig node

2024-05-24 20:58 UTC, sftim commented
/retitle Revise termination section in pod lifecycle concept

2024-05-26 15:36 UTC, bart0sh commented
/cc @SergeyKanzhelev

2024-06-04 18:33 UTC, T-Lakshmi requested changes

2024-06-04 18:33 UTC, T-Lakshmi commented on content/en/docs/concepts/workloads/pods/pod-lifecycle.md
> +   1. When the grace period expires, if if there is still any container running in the Pod, the
nit
```suggestion
   1. When the grace period expires, if there is still any container running in the Pod, the
```

2024-06-04 18:37 UTC, T-Lakshmi commented
/label tide/merge-method-squash

2024-06-06 05:33 UTC, sftim commented
/remove-label tide/merge-method-squash

Each commit in this PR represents a separate unit of work

2024-06-20 01:17 UTC, windsonsea reviewed
The [preview](https://deploy-preview-46525--kubernetes-io-main-staging.netlify.app/docs/concepts/workloads/pods/pod-lifecycle/#pod-termination) looks good.
/lgtm

2024-06-21 23:41 UTC, dipesh-rawat reviewed
Thanks!

/approve

2024-06-21 23:42 UTC, merged