[zh-cn] sync authorization.md
kubernetes/website pull request #46537
Opened 2024-05-25 07:33 UTC by my-git9

content/zh-cn/docs/reference/access-authn-authz/authorization.md

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +通常，发出请求的客户端必须经过身份验证（登录）才能允许其请求；
```suggestion
通常，发出请求的客户端必须经过身份认证（登录），其请求才可以被允许；
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +有关鉴权如何融入 API 访问控制的更多的上下文信息，
```suggestion
有关鉴权在 API 访问控制中的位置这类进一步的语境信息，
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +依赖于特定对象种类的特定字段的{{< glossary_tooltip text="访问控制" term_id="admission-controller" >}}和策略由准入控制器处理。
```suggestion
依赖于特定对象种类的特定字段的访问控制和策略由{{< glossary_tooltip text="准入控制器" term_id="admission-controller" >}}处理。
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +Kubernetes 准入控制发生在鉴权完成后（因此，仅当鉴权决策是允许请求时）。
```suggestion
Kubernetes 准入控制发生在鉴权完成之后（因此，仅当鉴权决策是允许请求时）。
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +#### 非资源请求
```suggestion
#### 非资源请求   {#request-verb-non-resource}
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +#### 资源请求
```suggestion
#### 资源请求    {#resource-requests}
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +`GET`, `HEAD` | **get**（for individual resources）, **list**（针对集合，包括完整的对象内容）, **watch**（用于查看单个资源或资源集合）
```suggestion
`GET`, `HEAD` | **get**（针对单个资源）、**list**（针对集合，包括完整的对象内容）、**watch**（用于查看单个资源或资源集合）
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +`DELETE`      | **delete**（针对单个资源）, **deletecollection**（针对集合）
```suggestion
`DELETE`      | **delete**（针对单个资源）、**deletecollection**（针对集合）
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +## 鉴权上下文
```suggestion
## 鉴权上下文    {#authorization-context}
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
>  ## 鉴权模块  {#authorization-modules}
```suggestion
## 鉴权模式  {#authorization-modules}
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +: 此模式允许所有请求，但存 [安全风险](#warning-always-allow)，
```suggestion
: 此模式允许所有请求，但存在[安全风险](#warning-always-allow)，
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +: 此模式阻止所有请求。仅将此鉴权模式用于测试。
```suggestion
: 此模式阻止所有请求。此鉴权模式仅适用于测试。
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +: Kubernetes RBAC 是一种根据企业内各个用户的角色来管理对计算机或网络资源的访问权限的方法。
```suggestion
: Kubernetes RBAC 是一种根据企业内各个用户的角色来管理其对计算机或网络资源的访问权限的方法。
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +  阻止请求直到远程 HTTP 服务响应查询。你可以编写自己的软件来处理调出，也可以使用生态系统中的解决方案。
```suggestion
  阻塞请求直到远程 HTTP 服务响应查询。你可以编写自己的软件来处理这种向外调用，也可以使用生态系统中的解决方案。
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +激活 `AlwaysAllow` 意味着如果所有其他鉴权者都返回 “no opinion”，则允许该请求。
```suggestion
激活 `AlwaysAllow` 意味着如果所有其他鉴权者都返回“无意见”，则允许该请求。
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +特性使用[配置文件](#using-configuration-file-for-authorization)来配置 Kubernetes API 服务器的鉴权链。
```suggestion
你可以仅使用[命令行参数](#using-flags-for-your-authorization-module)，
或使用[配置文件](#using-configuration-file-for-authorization)来配置 Kubernetes API
服务器的鉴权链，后者目前是 Beta 特性。
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +* `--authorization-mode=Node`（节点鉴权者）
```suggestion
* `--authorization-mode=Node`（节点鉴权组件）
```

2024-05-25 09:30 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +该链中的鉴权项可以具有明确定义的参数，这些参数可以按特定顺序验证请求，
```suggestion
该链中的鉴权项可以具有明确定义的参数，这些参数可以按特定顺序检查请求，
```

2024-05-27 02:33 UTC, mengjiao-liu requested changes
Please check the format from the [preview page](https://deploy-preview-46537--kubernetes-io-main-staging.netlify.app/zh-cn/docs/reference/access-authn-authz/authorization/).

2024-05-27 02:33 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +<!--
<img width="489" alt="image" src="https://github.com/kubernetes/website/assets/44460091/3ec084e6-fa0e-480a-81a0-1d5b8bd52c20">

2024-05-27 02:33 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +-->
<img width="426" alt="image" src="https://github.com/kubernetes/website/assets/44460091/fb4dcef2-1d0e-44d7-bc6f-19b55babc9db">

2024-05-27 10:09 UTC, mengjiao-liu requested changes

2024-05-27 10:09 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +激活 `AlwaysAllow` 意味着如果所有其他鉴权者都返回“无意见”，则允许该请求。
```suggestion
激活 `AlwaysAllow` 意味着如果所有其他鉴权器都返回“无意见”，则允许该请求。
```
“ authorizer” -> "鉴权器"
根据中文属于对照：https://kubernetes.io/zh-cn/docs/contribute/localization_zh/#glossary

下同。

2024-05-27 10:09 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +      # 缓存来自 Webhook 鉴权者的“鉴权”响应的持续时间
```suggestion
      # 缓存来自 Webhook 鉴权器的“鉴权”响应的持续时间
```

2024-05-27 10:09 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +      # 缓存来自 Webhook 鉴权者的“未授权”响应的持续时间。
```suggestion
      # 缓存来自 Webhook 鉴权器的“未授权”响应的持续时间。
```

2024-05-27 10:09 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +      #   - NoOpinion：继续联系后续鉴权者，看其中是否有人允许该请求
```suggestion
      #   - NoOpinion：继续联系后续鉴权器，看其中是否有人允许该请求
```

2024-05-27 10:09 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +      #   - Deny：拒绝请求而不咨询后续鉴权者
```suggestion
      #   - Deny：拒绝请求而不咨询后续鉴权器
```

2024-05-27 10:09 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +重新加载**不能**添加或删除节点或 RBAC 鉴权者（可以重新排序，但不能添加或删除）。
```suggestion
重新加载**不能**添加或删除节点或 RBAC 鉴权器（可以重新排序，但不能添加或删除）。
```

2024-05-27 13:08 UTC, tengqm commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +激活 `AlwaysAllow` 意味着如果所有其他鉴权者都返回“无意见”，则允许该请求。
“鉴权器”的翻译有点儿生硬，是不是意译为“鉴权组件”更合适？

2024-05-28 01:55 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +激活 `AlwaysAllow` 意味着如果所有其他鉴权者都返回“无意见”，则允许该请求。
也可以。

2024-05-28 01:57 UTC, mengjiao-liu commented on content/zh-cn/docs/reference/access-authn-authz/authorization.md
> +你必须确保重新加载时文件中所有非 Webhook 鉴权器类型保持不变。
```suggestion
你必须确保重新加载时文件中所有非 Webhook 鉴权组件类型保持不变。
```
全文保持一致。

2024-05-28 08:29 UTC, mengjiao-liu reviewed
/approve

2024-05-28 09:19 UTC, windsonsea commented
/lgtm

2024-05-28 09:23 UTC, merged