Data plane definition in JA
kubernetes/website pull request #46555
Opened 2024-05-27 06:55 UTC by tamilselvan1102

Fixes #46446

2024-05-27 06:56 UTC, tamilselvan1102 commented
cc @Okabe-Junya

2024-05-27 07:13 UTC, tamilselvan1102 commented
preview page: https://deploy-preview-46555--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?fundamental=true#term-data-plane

2024-05-27 08:02 UTC, Okabe-Junya requested changes
Thank you for your contribution!!

I made a few comments, PTAL :)

2024-05-27 08:02 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/data-plane.md
> + コンテナが実行してネットワークに接続できるように、CPU、メモリー、ネットワーク、ストレージなどの容量を提供するレイヤーです。
```suggestion
  コンテナを実行し、ネットワークに接続できるように、CPU、メモリ、ネットワーク、ストレージなどの容量を提供するレイヤーです。
```

ditto

2024-05-27 08:03 UTC, Okabe-Junya commented
/retitle [ja] Translate data plane definition

2024-05-27 11:33 UTC, Okabe-Junya approved these changes
LGTM!! Thank you!

/lgtm
/assign inductor

2024-05-28 05:09 UTC, Okabe-Junya requested changes
@tamilselvan1102 

Sorry for the inconvenience, but I have further reviewed this translation and would like to request a few simple fixes. 

(Note that this is a part of the glossary, so a very high-quality translation is required.)

/lgtm cancel

2024-05-28 05:09 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/data-plane.md
> +  コンテナを実行し、ネットワークに接続できるように、CPU、メモリ、ネットワーク、ストレージなどの容量を提供するレイヤーです。
```suggestion
  コンテナを実行し、ネットワークに接続できるように、CPU、メモリ、ネットワーク、ストレージなどのキャパシティを提供するレイヤーです。
```

2024-05-28 05:09 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/data-plane.md
> +  コンテナを実行し、ネットワークに接続できるように、CPU、メモリ、ネットワーク、ストレージなどの容量を提供するレイヤーです。
```suggestion
  コンテナを実行し、ネットワークに接続できるように、CPU、メモリ、ネットワーク、ストレージなどのキャパシティを提供するレイヤーです。
```

2024-05-28 05:16 UTC, Okabe-Junya approved these changes
Thank you!!

/lgtm

2024-05-28 05:18 UTC, Okabe-Junya commented
/label tide/merge-method-squash

2024-05-28 05:33 UTC, inductor approved these changes

2024-05-28 05:33 UTC, inductor commented
/approve

2024-05-28 05:38 UTC, merged