[hi] Localized docs/reference/tools/_index.md
kubernetes/website pull request #46558
Opened 2024-05-27 16:55 UTC by aj11anuj

2024-05-28 05:40 UTC, niranjandarshann commented on content/hi/docs/reference/tools/_index.md
> +  [वितरित एप्लिकेशनो के बंडलों](https://docs.docker.com/compose/bundles/) के माध्यम से अपने एप्लिकेशन
instead of `वितरित एप्लिकेशनो के बंडलों` i think `डिस्ट्रीब्यूटेड एप्लिकेशन बंडलों `will look good.

2024-05-28 05:45 UTC, niranjandarshann commented on content/hi/docs/reference/tools/_index.md
> +Kui उन टेबल्स के साथ एक GUI प्रदान करता है, जिन्हें आप सॉर्ट कर सकते हैं।
सॉर्ट -> क्रमबद्ध

Will be more understandable.

2024-05-28 05:53 UTC, niranjandarshann commented on content/hi/docs/reference/tools/_index.md
> +* `Kubectl` कमांड टाइप करें और उन्हें चलते हुए देखें, यहां तक कि कभी-कभी `Kubectl` से भी तेज।
`Kubectl` कमांड टाइप करें और उन्हें चलते हुए देखें, यहां तक कि कभी-कभी `Kubectl` से भी तेज  हो सकता है।

This whole sentence will be more suitable.

2024-05-28 05:55 UTC, niranjandarshann commented on content/hi/docs/reference/tools/_index.md
> +* एक {{< glossary_tooltip text="जॉब" term_id="job">}} क्वेरी करें और इसके निष्पादन को
किसी {{< glossary_tooltip text="जॉब" term_id="job">}} को क्वेरी करें और इसके निष्पादन को

2024-05-28 05:58 UTC, niranjandarshann commented on content/hi/docs/reference/tools/_index.md
> +* एक टैब्ड UI का उपयोग करके अपने क्लस्टर में संसाधनों पर क्लिक करें।
* टैब्ड UI का उपयोग करके अपने क्लस्टर में संसाधनों पर क्लिक करें।

2024-05-28 06:00 UTC, niranjandarshann commented
@aj11anuj  I have added some of the suggestion for the improvement of the doc.

2024-07-11 12:21 UTC, divya-mohan0209 requested changes
First batch of reviews.

2024-07-11 12:21 UTC, divya-mohan0209 commented on content/hi/docs/reference/tools/_index.md
> +{{<glossary_tooltip term_id="cri" text="CRI">}}-compatible कंटेनर रनटाइम के
Translate the word compatible.
```suggestion
{{<glossary_tooltip term_id="cri" text="CRI">}}-संगत कंटेनर रनटाइम के 
```

2024-07-11 12:21 UTC, divya-mohan0209 commented on content/hi/docs/reference/tools/_index.md
> +[`डैशबोर्ड`](/docs/tasks/access-application-cluster/web-ui-dashboard/), कुबेरनेट्स का
This whole line doesn't read right, please rephrase.

2024-07-11 12:21 UTC, divya-mohan0209 commented on content/hi/docs/reference/tools/_index.md
> +* अपने स्वयं के एप्लिकेशन को कुबेरनेट्स चार्ट के रूप में साझा करें।
```suggestion
* अपने ख़ुद के एप्लिकेशन को कुबेरनेट्स चार्ट के रूप में साझा करें।
```

2024-07-11 12:21 UTC, divya-mohan0209 commented on content/hi/docs/reference/tools/_index.md
> +* अपने कुबेरनेट्स एप्लीकेशन के लिए प्रस्तुत करने योग्य बिल्ड बनाएं।
This line doesn't make sense. Please check and rephrase.

2024-07-11 12:21 UTC, divya-mohan0209 commented on content/hi/docs/reference/tools/_index.md
> +* बुद्धिमानी से अपने कुबेरनेट्स मैनिफ़ेस्ट फ़ाइलों को प्रबंधित करें।
```suggestion
* बुद्धिमत्ता से अपने कुबेरनेट्स मैनिफ़ेस्ट फ़ाइलों को प्रबंधित करें।
```

2024-07-29 17:19 UTC, aj11anuj reviewed
.

2024-07-29 17:19 UTC, aj11anuj commented on content/hi/docs/reference/tools/_index.md
> +[`डैशबोर्ड`](/docs/tasks/access-application-cluster/web-ui-dashboard/), कुबेरनेट्स का
```suggestion
कुबेरनेट्स का 
```

2024-07-29 17:19 UTC, aj11anuj commented on content/hi/docs/reference/tools/_index.md
> +वेब पे आधारित उपयोगकर्ता इंटरफ़ेस, आपको कुबेरनेट्स क्लस्टर में कंटेनरीकृत अनुप्रयोगों को तैनात करने,
```suggestion
वेब [`डैशबोर्ड`](/docs/tasks/access-application-cluster/web-ui-dashboard/) आपको क्लस्टर में कंटेनरीकृत अनुप्रयोगों को तैनात करने, 
```

2024-07-29 17:19 UTC, aj11anuj commented on content/hi/docs/reference/tools/_index.md
> +उनकी समस्या का निवारण करने और क्लस्टर और उसके संसाधनों को प्रबंधित करने की अनुमति देता है।
```suggestion
उनकी समस्या का निवारण करने और क्लस्टर के संसाधनों को प्रबंधित करने की अनुमति देता है।
```

2024-07-29 17:19 UTC, aj11anuj commented on content/hi/docs/reference/tools/_index.md
> +* अपने कुबेरनेट्स एप्लीकेशन के लिए प्रस्तुत करने योग्य बिल्ड बनाएं।
```suggestion

2024-07-29 17:19 UTC, aj11anuj commented on content/hi/docs/reference/tools/_index.md
> +* `Kubectl` कमांड टाइप करें और उन्हें चलते हुए देखें, यहां तक कि कभी-कभी `Kubectl` से भी तेज।
```suggestion
* `Kubectl` कमांड टाइप करें और उन्हें निष्पादन होते हुए देखें, यहां तक कि कभी-कभी `Kubectl` से भी तेज।
```

2024-07-29 17:19 UTC, aj11anuj commented on content/hi/docs/reference/tools/_index.md
> +  [वितरित एप्लिकेशनो के बंडलों](https://docs.docker.com/compose/bundles/) के माध्यम से अपने एप्लिकेशन
```suggestion
  [डिस्ट्रीब्यूटेड एप्लिकेशनो के बंडलों ](https://docs.docker.com/compose/bundles/) के माध्यम से अपने एप्लिकेशन
```

2024-07-29 17:20 UTC, aj11anuj commented
Please take a look

2024-09-12 08:32 UTC, niranjandarshann commented
changes looks good to me 
/lgtm

2024-09-12 10:49 UTC, divya-mohan0209 reviewed
Nit, but can be addressed in a followed up PR.

/approve

2024-09-12 10:49 UTC, divya-mohan0209 commented on content/hi/docs/reference/tools/_index.md
> +{{<glossary_tooltip term_id="cri" text="CRI">}}-संगत कंटेनर रनटाइम के
The text should be localized.

2024-09-12 10:51 UTC, merged