[ja] Translate code contributor definition
kubernetes/website pull request #46564
Opened 2024-05-28 10:19 UTC by tamilselvan1102

Fixes #46444

2024-05-28 10:36 UTC, tamilselvan1102 commented
preview page: https://deploy-preview-46564--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-code-contributor

2024-05-28 10:47 UTC, Okabe-Junya requested changes
Thanks, PTAL my comments

/label tide/merge-method-squash

2024-05-28 10:47 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> +title: コードの貢献者（Code Contributor）
```suggestion
title: コードコントリビューター
```

2024-05-28 10:47 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> +They are also an active {{< glossary_tooltip text="community member" term_id="member" >}} who participates in one or more {{< glossary_tooltip text="Special Interest Groups (SIGs)" term_id="sig" >}}.
```suggestion
```

plz delete original content

2024-05-28 10:47 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> +  コードを開発し、Kubernetesオープンソースコードベースに貢献する人々。
```suggestion
  Kubernetesのオープンソースのコードベースを開発し、貢献する人。
```

2024-05-28 10:47 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> + コードを開発し、Kubernetesオープンソースコードベースに貢献する人々。
```suggestion
 Kubernetesのオープンソースのコードベースを開発し、貢献する人。
```

2024-05-28 10:47 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> +彼らは、一つ以上の{{< glossary_tooltip text="特別利益団体（SIGs）" term_id="sig" >}}のアクティブな{{< glossary_tooltip text="コミュニティメンバー" term_id="member" >}}でもあります。
```suggestion
彼らは、一つ以上の{{< glossary_tooltip text="SIG" term_id="sig" >}}のアクティブな{{< glossary_tooltip text="コミュニティメンバー" term_id="member" >}}でもあります。
```

2024-05-28 13:23 UTC, Okabe-Junya approved these changes
Thanks, LGTM!!

/lgtm
/assign nasa9084

2024-05-28 13:23 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> +彼らは、一つ以上の{{< glossary_tooltip text="SIG" term_id="sig" >}}のアクティブな{{< glossary_tooltip text="コミュニティメンバー" term_id="member" >}}でもあります。
nit: "彼らは" の部分、何かもっといい訳ないですかね。。（差し当たり問題ではないですが）

2024-05-30 21:24 UTC, inductor commented on content/ja/docs/reference/glossary/code-contributor.md
> +彼らは、一つ以上の{{< glossary_tooltip text="SIG" term_id="sig" >}}のアクティブな{{< glossary_tooltip text="コミュニティメンバー" term_id="member" >}}でもあります。
このロールを持つ人は、とか？

2024-05-31 06:42 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> +彼らは、一つ以上の{{< glossary_tooltip text="SIG" term_id="sig" >}}のアクティブな{{< glossary_tooltip text="コミュニティメンバー" term_id="member" >}}でもあります。
コントリビューターだからと言ってロールを持っているとは限らないと思いました

（自分の印象では、"ロール" というとreviewer, approver, leadみたいなものを連想します。定義的にはコントリビューターもロールなのかもしれないですが。。）

2024-05-31 09:52 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/code-contributor.md
> +彼らは、一つ以上の{{< glossary_tooltip text="SIG" term_id="sig" >}}のアクティブな{{< glossary_tooltip text="コミュニティメンバー" term_id="member" >}}でもあります。
```suggestion
コントリビューターは、一つ以上の{{< glossary_tooltip text="SIG" term_id="sig" >}}のアクティブな{{< glossary_tooltip text="コミュニティメンバー" term_id="member" >}}でもあります。
```

2024-05-31 15:30 UTC, Okabe-Junya approved these changes
Thank you!!

/lgtm

2024-06-02 09:54 UTC, inductor reviewed
/approve

2024-06-02 09:57 UTC, merged