Modify registry.k8s.io/nginx-slim version from 0.8 to 0.24
kubernetes/website pull request #46639
Opened 2024-06-03 17:36 UTC by shayaniox

This pull request aims to fix the error raised by pulling the image `registry.k8s.io/nginx-slim:0.8` that says:
```
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of registry.k8s.io/nginx-slim:0.8 to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/
```

2024-06-03 22:07 UTC, sftim requested changes
Thanks, but: we need to use two different image tags so that people can see the change happen.

2024-06-03 22:07 UTC, sftim commented on content/en/docs/tutorials/stateful-application/basic-stateful-set.md
> +kubectl patch statefulset web --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/image", "value":"registry.k8s.io/nginx-slim:0.24"}]'
I'm not sure this works. We need two **different** image tags; they can be any two tags, but they can't be the same as each other.

2024-06-03 22:07 UTC, sftim commented on content/en/docs/tutorials/stateful-application/basic-stateful-set.md
> +registry.k8s.io/nginx-slim:0.24
I'm not sure this works. We need two **different** image tags; they can be any two tags, but they can't be the same as each other.

2024-06-03 22:07 UTC, sftim commented on content/en/docs/tutorials/stateful-application/basic-stateful-set.md
> +registry.k8s.io/nginx-slim:0.24
I'm not sure this works. We need two **different** image tags; they can be any two tags, but they can't be the same as each other.

2024-06-03 22:07 UTC, sftim commented on content/en/examples/application/web/web.yaml
> +        image: registry.k8s.io/nginx-slim:0.24
I'm not sure this works. We need two **different** image tags; they can be any two tags, but they can't be the same as each other.

2024-06-03 22:08 UTC, sftim commented
@shayaniox, how can someone reproduce the warning that you want to suppress? Any special steps required (eg: use Docker)?

2024-06-04 07:42 UTC, shayaniox commented
@sftim Thanks for the review. The error is reproducible by pulling the image using the following Docker version:

```
Client: Docker Engine - Community
 Version:           26.1.2
 API version:       1.45
 Go version:        go1.21.10
 Git commit:        211e74b
 Built:             Wed May  8 13:59:58 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.2
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.10
  Git commit:       ef1912d
  Built:            Wed May  8 13:59:58 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.31
  GitCommit:        e377cd56a71523140ca6ae87e30244719194a521
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

2024-06-05 06:58 UTC, shayaniox commented
@sftim Could you determine state of the pull request?

2024-06-06 10:11 UTC, mengjiao-liu commented
> @shayaniox, how can someone reproduce the warning that you want to suppress? Any special steps required (eg: use Docker)?

I can reproduce the warning as follows:

<img width="1435" alt="image" src="https://github.com/kubernetes/website/assets/44460091/fbec0b18-d9b0-4813-8166-d7dc8d7bbb85">

```
docker version
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:26 2024
 OS/Arch:           darwin/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:25 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

2024-06-06 10:11 UTC, mengjiao-liu commented
/lgtm

2024-06-07 10:37 UTC, shayaniox commented
@mengjiao-liu Is the PR approvable? Or does it need further actions to take?

2024-06-07 10:42 UTC, mengjiao-liu commented
I don't have permission to approve this PR, you need to wait for approval from the sig-docs approver

2024-06-07 13:06 UTC, tengqm commented
/approve

2024-06-07 13:11 UTC, merged