[ja] Translate content/en/docs/reference/glossary/cla.md into Japanese
kubernetes/website pull request #46636
Opened 2024-06-03 11:21 UTC by ntkm61027

Fixes #45113

2024-06-03 11:46 UTC, bells17 commented
/assign @nasa9084 @inductor 

For approval.

2024-06-03 16:34 UTC, inductor commented on content/ja/docs/reference/glossary/cla.md
> +CLAは、提供された素材や知的財産(IP)に関する法的紛争の解決に役立ちます。
"素材" をどう捉えるかかなぁ

2024-06-05 04:31 UTC, ntkm61027 commented on content/ja/docs/reference/glossary/cla.md
> +CLAは、提供された素材や知的財産(IP)に関する法的紛争の解決に役立ちます。
ご確認ありがとうございます。

 そこはたしかに抽象的でどうするか迷いました。。
他の言い回しだと、資材、コード、コンテンツ、貢献内容、など思いつきましがいかがでしょうか？

2024-06-07 03:13 UTC, bells17 commented on content/ja/docs/reference/glossary/cla.md
> +CLAは、提供された素材や知的財産(IP)に関する法的紛争の解決に役立ちます。
@inductor こちらどうですか？

2024-06-08 13:44 UTC, inductor requested changes

2024-06-08 13:44 UTC, inductor commented on content/ja/docs/reference/glossary/cla.md
> +CLAは、提供された素材や知的財産(IP)に関する法的紛争の解決に役立ちます。
```suggestion
CLAは、提供された成果物や知的財産(IP)に関する法的紛争の解決に役立ちます。
```

とするのが丸いかな

2024-06-10 09:11 UTC, inductor commented on content/ja/docs/reference/glossary/cla.md
> +CLAは、提供された素材や知的財産(IP)に関する法的紛争の解決に役立ちます。
@ntkm61027

2024-06-10 21:48 UTC, inductor commented
/lgtm
/approve

2024-06-10 21:51 UTC, merged