[ja] Translate "DIY: Create Your Own Cloud with Kubernetes (Part 2)" into Japanese
kubernetes/website pull request #46787
Opened 2024-06-12 02:48 UTC by b1gb4by

## Issue

Fix https://github.com/kubernetes/website/issues/46677

## Change. List

Translate content/en/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md

## Comment

This PR should be merged at the same time as the PR for the following issue.

- https://github.com/kubernetes/website/issues/45901
  - https://github.com/kubernetes/website/pull/46686
- https://github.com/kubernetes/website/issues/45902
  -

2024-06-12 02:54 UTC, b1gb4by commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +**翻訳者:** Taisuke Okamoto (IDC Frontier Inc),
最後にレビューしていただいた方を追記予定です。

2024-06-27 02:23 UTC, b1gb4by commented
@Okabe-Junya 
お手漉きの際にレビューお願いします！

2024-06-27 02:26 UTC, Okabe-Junya commented
k8s-ci-robot でreviewerが割り当てられているので、基本的にそちらの方からのレビューをお願いしています（当面の間レビューがされないようでしたらまた連絡をお願いします 🙇 ）

cc @atoato88 @kakts

2024-06-27 05:50 UTC, b1gb4by commented
> k8s-ci-robot でreviewerが割り当てられているので、基本的にそちらの方からのレビューをお願いしています（当面の間レビューがされないようでしたらまた連絡をお願いします 🙇 ）
> 
> cc @atoato88 @kakts

なるほど、そういうことでしたか。失礼しました 🙇

2024-07-01 14:09 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +このようなストレージは、多くの場合、運用を担当する外部ベンダーによって提供されるためです。
```suggestion
このようなストレージは、多くの場合運用を担当する外部ベンダーによって提供されるためです。
```

2024-07-01 14:09 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +多くの場合、外部ストレージを使用すると、データが計算ノードから分離して保存されるため、システム全体の安定性が向上します。
```suggestion
多くの場合、外部ストレージを使用するとデータが計算ノードから分離して保存されるため、システム全体の安定性が向上します。
```

2024-07-01 14:09 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[Cloud-Hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor)を使用した軽量な仮想化を実装し、当初はCluster APIを使用した仮想Kubernetesクラスターの実行に重点を置いている代替プロジェクト[Virtink](https://github.com/smartxworks/virtink)もあります。
ここの"当初は"という部分ってどういう意味合いなんでしょう？

2024-07-01 14:14 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[前回の記事](/blog/2024/04/05/diy-create-your-own-cloud-with-kubernetes-part-1/)で説明したように、Talos Linuxを使用している場合は、必要なカーネルモジュールを事前に有効にし、[指示](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/h
この場合「手順」の方がしっくり来る感じがしました

```suggestion
[前回の記事](/blog/2024/04/05/diy-create-your-own-cloud-with-kubernetes-part-1/)で説明したように、Talos Linuxを使用している場合は、必要なカーネルモジュールを事前に有効にし、[手順](https://github.com/piraeusdatastore/piraeus-operator/blob/v2/docs/how-to/talos.md)に従ってPiraeusを設定する必要があります。
```

2024-07-01 14:17 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +Kubernetesのネットワークアーキテクチャは、同様のインターフェースであるCNIを持っているにもかかわらず、実際にはより複雑で、通常、互いに直接接続されていない多くの独立したコンポーネントで構成されています。
```suggestion
Kubernetesのネットワークアーキテクチャは同じようなインターフェースであるCNIを持っているにもかかわらず、実際にはより複雑で、通常、互いに直接接続されていない多くの独立したコンポーネントで構成されています。
```

2024-07-01 14:19 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +ノード間の物理ネットワーク相互作用の設定は、ほとんどの状況でKubernetesが既存のネットワークインフラストラクチャを利用するため、この記事の範囲を超えています。
```suggestion
ノード間の物理ネットワークの相互作用の設定は、ほとんどの状況でKubernetesが既存のネットワークインフラストラクチャを利用するため、この記事の範囲を超えています。
```

2024-07-01 14:22 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +Kube-OVNでは、ネームスペース全体に個別のサブネットを割り当てたり、Multusを使用して追加のネットワークインターフェースとして接続したりできます。
```suggestion
Kube-OVNでは、名前空間全体に個別のサブネットを割り当てたり、Multusを使用して追加のネットワークインターフェースとして接続したりできます。
```

2024-07-01 14:23 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +Ciliumは、eBPFテクノロジーに基づいており、Linuxネットワークスタックを効率的にオフロードできるため、iptablesベースの従来の方法と比較してパフォーマンスとセキュリティが向上します。
```suggestion
CiliumはeBPFテクノロジーに基づいており、Linuxネットワークスタックを効率的にオフロードできるため、iptablesベースの従来の方法と比較してパフォーマンスとセキュリティが向上します。
```

2024-07-01 14:23 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +最も高度な実装は、[Cilium](https://cilium.io/)プロジェクトによって提供されており、kube-proxyの代替モードで実行できます。
```suggestion
最も高度な実装は[Cilium](https://cilium.io/)プロジェクトによって提供されており、kube-proxyの代替モードで実行できます。
```

2024-07-01 14:24 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +実際には、CiliumとKube-OVNを[統合](https://kube-ovn.readthedocs.io/zh-cn/stable/en/advance/with-cilium/)して、仮想マシンに対してシームレスなマルチテナントネットワーキングを提供し、高度なネットワークポリシーとサービスネットワーク機能を組み合わせた統一ソリューションを提供することが容易にできます。
```suggestion
実際には、CiliumとKube-OVNを[統合](https://kube-ovn.readthedocs.io/zh-cn/stable/en/advance/with-cilium/)して仮想マシンに対してシームレスなマルチテナントネットワーキングを提供し、高度なネットワークポリシーとサービスネットワーク機能を組み合わせた統一ソリューションを提供することが容易にできます。
```

2024-07-01 14:38 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +もう1つの利点は、L2モードでは、MetalLBスピーカーがメンバーリストプロトコルを使用してライブネスチェックを実行することにより、ネイバーの状態を継続的にチェックすることです。
memberlist protocolというのはこれのこと..?
https://ieeexplore.ieee.org/document/1028914

2024-07-01 14:40 UTC, bells17 commented
@b1gb4by 何点かコメントしました。ご確認をお願いします。

2024-07-02 12:58 UTC, kaitoii11 requested changes

2024-07-02 12:58 UTC, kaitoii11 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +私たちのプラットフォームでは、別の方法を選択し、[Kube-OVN](https://www.kube-ovn.io/)に完全に依存することにしました。
```suggestion
私たちのプラットフォームでは、別の方法を選択し、[Kube-OVN](https://www.kube-ovn.io/)に完全に頼ることにしました。
```

2024-07-02 12:58 UTC, kaitoii11 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +IPとMACアドレスを管理するためのカスタムリソースを備え、ノード間でIPアドレスを保持したままライブマイグレーションをサポートし、テナント間の物理ネットワーク分離用のVPCの作成を可能にします。
4つの列挙が分かれちゃってるので、「このCNIプラグインは、もともとOpenStack用に開発されたOVN(Open Virtual Network)をベースにしており、」で1文を切ってもいいかもしれないです。

2024-07-02 12:58 UTC, kaitoii11 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +最も高度な実装は、[Cilium](https://cilium.io/)プロジェクトによって提供されており、kube-proxyの代替モードで実行できます。
```suggestion
最も先進的な実装は、[Cilium](https://cilium.io/)プロジェクトによって提供されており、kube-proxyの代替モードで実行できます。
```

2024-07-02 12:58 UTC, kaitoii11 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +もう1つの利点は、L2モードでは、MetalLBスピーカーがメンバーリストプロトコルを使用してライブネスチェックを実行することにより、ネイバーの状態を継続的にチェックすることです。
metallbのドキュメントで紹介されているこちらかと思います。
https://github.com/hashicorp/memberlist

MetalLBのドキュメントはこちら。
https://metallb.universe.tf/concepts/layer2/#comparison-to-keepalived

2024-07-02 15:57 UTC, atoato88 reviewed
主に内容というよりは体裁についてコメントしました。
ご確認ください。

2024-07-02 15:57 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[Cloud-Hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor)を使用した軽量な仮想化を実装し、当初はCluster APIを使用した仮想Kubernetesクラスターの実行に重点を置いている代替プロジェクト[Virtink](https://github.com/smartxworks/virtink)もあります。
原文は "Initially" なので、文脈から判断すると "初期から" という言うような意味合いなのかなと私は解釈しました。
 
@b1gb4by どのような意味解釈をされていましたか？

2024-07-02 15:57 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +仮想マシンの永続ボリュームを自動的にプロビジョニングする場合や、テナントKubernetesクラスターからの永続ボリューム要求を処理するために使用されるKubeVirt CSIドライバーに必要な場合は、CDIが必要です。
```suggestion
CDIは、仮想マシンの永続ボリュームを自動的にプロビジョニングする場合や、テナントKubernetesクラスターからの永続ボリューム要求を処理するために使用されるKubeVirt CSIドライバーにも必要となります。
```
「・・・に必要な場合は、CDIが必要です。」という表現に少し違和感ありました。このような文章はどうでしょうか？

2024-07-02 15:57 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +従来の仮想マシンとは異なり、Kubernetesはもともとランダムなアドレスでポッドを実行するように設計されています。
```suggestion
従来の仮想マシンとは異なり、KubernetesはもともとランダムなアドレスでPodを実行するように設計されています。
```

2024-07-02 15:57 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +そして、サービスネットワークは、トラフィックを常に正しいポッドに誘導する便利な抽象化(安定したIPアドレスとDNS名)を提供します。
```suggestion
そして、サービスネットワークは、トラフィックを常に正しいPodに誘導する便利な抽象化(安定したIPアドレスとDNS名)を提供します。
```

2024-07-02 15:57 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +サービスネットワークプラグインは、通常どおりそれをポッドと仮想マシンに誘導します。
```suggestion
サービスネットワークプラグインは、通常どおりそれをPodと仮想マシンに誘導します。
```

2024-07-02 15:57 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +もう1つの利点は、L2モードでは、MetalLBスピーカーがメンバーリストプロトコルを使用してライブネスチェックを実行することにより、ネイバーの状態を継続的にチェックすることです。
お二人の話を確認し、私も結論としてmemberlist protocolとは、https://ieeexplore.ieee.org/document/1028914 のことだと思いました。

2024-07-02 16:02 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[前回の記事](/blog/2024/04/05/diy-create-your-own-cloud-with-kubernetes-part-1/)では、Talos LinuxとFlux CDをベースにした基本的なKubernetes ディストリビューションの準備方法を説明しました。
```suggestion
[前回の記事](/ja/blog/2024/04/05/diy-create-your-own-cloud-with-kubernetes-part-1/)では、Talos LinuxとFlux CDをベースにした基本的なKubernetes ディストリビューションの準備方法を説明しました。
```
今回、他のPR #46686 でPart1も翻訳していますよね。
このような場所は、できれば日本語記事へのリンクに変更したほうが読者には優しいと思いました。
いかがでしょうか？ 他の方の意見を聞きたいです。

ちなみに、この変更を加える場合はこのPRで他に複数の変更箇所がありそうです。
また、他PR #46686, #46788 にも同様に変更箇所があるか確認が必要ですね。

2024-07-02 16:48 UTC, Okabe-Junya commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[前回の記事](/blog/2024/04/05/diy-create-your-own-cloud-with-kubernetes-part-1/)では、Talos LinuxとFlux CDをベースにした基本的なKubernetes ディストリビューションの準備方法を説明しました。
> このような場所は、できれば日本語記事へのリンクに変更したほうが読者には優しいと思いました。

そうですね、全部jaへのリンクにしてholdかけておく方針で良いと思います（なのでpart1でholdしています）

2024-07-08 15:57 UTC, b1gb4by commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +このようなストレージは、多くの場合、運用を担当する外部ベンダーによって提供されるためです。
@bells17 
もう少し考えてみたのですが、以下だと句読点が多くても読みやすいのかなと思ったのですがいかがでしょうか？

```
「このようなストレージは、多くの場合、運用を担当する外部ベンダーによって提供されます。」
```

2024-07-08 16:01 UTC, b1gb4by commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +一方、ハイパーコンバージドシステムは、多くの場合、ローカルストレージ(レプリケーションが不要な場合)と、[Rook/Ceph](https://rook.io/)、[OpenEBS](https://openebs.io/)、[Longhorn](https://longhorn.io/)、[LINSTOR](https://linbit.com/linstor/)などのソフトウェア定義ストレー
@bells17 
なるほど、そうなんですね 👀 
では、カタカナに修正します。

2024-07-08 16:06 UTC, b1gb4by commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[Cloud-Hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor)を使用した軽量な仮想化を実装し、当初はCluster APIを使用した仮想Kubernetesクラスターの実行に重点を置いている代替プロジェクト[Virtink](https://github.com/smartxworks/virtink)もあります。
@bells17 @atoato88 

> 原文は "Initially" なので、文脈から判断すると "初期から" という言うような意味合いなのかなと私は解釈しました。

おっしゃるとおりです。

ただ、自分でも「当初から」と「初期から」のどちらが自然かなと思っていて悩ましくは感じています。

「初期から」の方が文章的にも自然でしょうか？

2024-07-08 16:25 UTC, b1gb4by commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +私たちのプラットフォームでは、別の方法を選択し、[Kube-OVN](https://www.kube-ovn.io/)に完全に依存することにしました。
@kaitoii11 
確かにこちらの書き方の方が、表現に棘がない気がしました。
こちらを採用させていただきます 🙇

2024-07-08 17:12 UTC, b1gb4by commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +仮想マシンの永続ボリュームを自動的にプロビジョニングする場合や、テナントKubernetesクラスターからの永続ボリューム要求を処理するために使用されるKubeVirt CSIドライバーに必要な場合は、CDIが必要です。
@atoato88 
たしかにこちらのほうが文章としても自然で読みやすいと思いました！
採用させていただきます。

2024-07-10 06:42 UTC, b1gb4by commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +IPとMACアドレスを管理するためのカスタムリソースを備え、ノード間でIPアドレスを保持したままライブマイグレーションをサポートし、テナント間の物理ネットワーク分離用のVPCの作成を可能にします。
以下のように文章を区切りました。

```
このCNIプラグインは、もともとOpenStack用に開発されたOVN(Open Virtual Network)をベースにしています。
Kube-OVNはKubernetes内の仮想マシン用の完全なネットワークソリューションを提供します。
IPとMACアドレスを管理するためのカスタムリソースを備え、ノード間でIPアドレスを保持したままライブマイグレーションをサポートし、テナント間の物理ネットワーク分離用のVPCの作成を可能にします。
```

2024-07-10 07:53 UTC, atoato88 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[Cloud-Hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor)を使用した軽量な仮想化を実装し、当初はCluster APIを使用した仮想Kubernetesクラスターの実行に重点を置いている代替プロジェクト[Virtink](https://github.com/smartxworks/virtink)もあります。
私としては「初期から」が自然かなと思うのですが、主観が入ってることを否定できないんですよね。
なのでそこまでこだわりはありません。
とりあえず @bells17 さんの反応をもらえるといいかなと。

2024-07-10 08:39 UTC, bells17 commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[Cloud-Hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor)を使用した軽量な仮想化を実装し、当初はCluster APIを使用した仮想Kubernetesクラスターの実行に重点を置いている代替プロジェクト[Virtink](https://github.com/smartxworks/virtink)もあります。
ありがとうございます。
「当初から」でいくなら文の締めは「代替プロジェクトVirtinkもありました。」と過去形のほうが流れが良さそうですね。

2024-07-10 11:33 UTC, tokamoto-idcf commented on content/ja/blog/_posts/2024-04-05-diy-create-your-own-cloud-with-kubernetes-part-2/index.md
> +[Cloud-Hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor)を使用した軽量な仮想化を実装し、当初はCluster APIを使用した仮想Kubernetesクラスターの実行に重点を置いている代替プロジェクト[Virtink](https://github.com/smartxworks/virtink)もあります。
@bells17@atoato88
お二人の意見、ありがとうございます。
僕の方でも考えた結果、前後の文脈から判断して「初期から」にすることにします。

2024-07-10 11:43 UTC, bells17 commented
/lgtm

2024-07-10 15:06 UTC, Okabe-Junya commented
@bells17 こちらもapprove頂きたいです

/hold
/label tide/merge-method-squash

2024-07-10 20:03 UTC, atoato88 commented
LGTMです。

2024-07-11 07:18 UTC, bells17 commented
/approve

2024-07-11 08:51 UTC, Okabe-Junya commented
/unhold

2024-07-11 08:54 UTC, merged