Update cloud-native-security.md
kubernetes/website pull request #46811
Opened 2024-06-13 15:11 UTC by Sagar2366

2024-06-14 05:28 UTC, divya-mohan0209 requested changes

2024-06-14 05:28 UTC, divya-mohan0209 commented on content/en/docs/concepts/security/cloud-native-security.md
> +to provide effective cluster security.
Original statement works fine.

2024-06-14 05:28 UTC, divya-mohan0209 commented on content/en/docs/concepts/security/cloud-native-security.md
> +applications runtime environment: a Kubernetes cluster (or
Original statement is grammatically correct.

2024-06-14 05:28 UTC, divya-mohan0209 commented on content/en/docs/concepts/security/cloud-native-security.md
> +encryption keys. If you use Kubernetes own API for
The original statement is grammatically correct.

2024-06-17 08:42 UTC, sftim commented
/sig security

Please write a description for this pull request. Part of the role of a reviewer is to check that the effect of merging the PR matches the description.

2024-06-27 18:16 UTC, Ritikaa96 commented
Hey @Sagar2366 are you able to address comments from @sftim and @divya-mohan0209 ? Please add description to the PR as asked by sftim.

2024-06-28 05:00 UTC, closed without merging