updated confusing virtual IP and service proxy
kubernetes/website pull request #46873
Opened 2024-06-18 19:13 UTC by kundan2707

Fixes: #38169

2024-06-18 19:13 UTC, kundan2707 commented
/kind documentation
/language en

2024-06-18 19:14 UTC, kundan2707 commented
/sig network

2024-06-19 17:02 UTC, kundan2707 commented
/easycla

2024-06-25 10:43 UTC, kundan2707 commented
@kbhawkey @Princesso  can you please take a look?

2024-06-28 07:44 UTC, katcosgrove requested changes
Adjustments for grammar and style guide.

2024-06-28 07:44 UTC, katcosgrove commented on content/en/docs/reference/networking/virtual-ips.md
> +appropriate endpoint. The kubelet running on that node set up environment variable
```suggestion
appropriate endpoint. The `kubelet` running on that node sets up environment variables 
```

2024-06-28 07:44 UTC, katcosgrove commented on content/en/docs/reference/networking/virtual-ips.md
> +for each active service based on Service's virtual IP address and port. Similarly,
```suggestion
for each active Service based on the Service's virtual IP address and port. Similarly,
```

2024-06-28 07:44 UTC, katcosgrove commented on content/en/docs/reference/networking/virtual-ips.md
> +DNS creates set of DNS records for each service by watching kubernetes API.
```suggestion
DNS creates set of DNS records for each Service by watching the Kubernetes API.
```

2024-06-28 08:03 UTC, kundan2707 commented on content/en/docs/reference/networking/virtual-ips.md
> +appropriate endpoint. The kubelet running on that node set up environment variable
accepted and updated as per comments

2024-06-28 08:04 UTC, kundan2707 commented on content/en/docs/reference/networking/virtual-ips.md
> +for each active service based on Service's virtual IP address and port. Similarly,
accepted and updated as per comments

2024-06-28 08:04 UTC, kundan2707 commented on content/en/docs/reference/networking/virtual-ips.md
> +DNS creates set of DNS records for each service by watching kubernetes API.
accepted and updated as per comments

2024-07-29 10:29 UTC, kundan2707 commented
[change preview ](https://deploy-preview-46873--kubernetes-io-main-staging.netlify.app/docs/reference/networking/virtual-ips/)

2024-07-29 10:30 UTC, kundan2707 commented
cc [@kubernetes/sig-network-misc](https://github.com/orgs/kubernetes/teams/sig-network-misc)

2024-08-10 06:44 UTC, network-charles commented on content/en/docs/reference/networking/virtual-ips.md
> +Either of two ways can be responsible for discovery of service.
SIG Docs here, the initial statement about the environmental variable is correct. (See [Services](https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services)).

The second statement about DNS is also correct.

2024-08-10 06:59 UTC, network-charles commented on content/en/docs/reference/networking/virtual-ips.md
> +Either of two ways can be responsible for discovery of service.
To try it out:
**service.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
```
```
kubectl apply -f service.yaml
```
**deployment.yaml**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
```
```
kubectl apply -f deployment
```
**View Service**
```
kubectl get svc

NAME            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
kubernetes      ClusterIP   10.96.0.1        <none>        443/TCP   7d23h
myapp-service   ClusterIP   10.101.104.130   <none>        80/TCP    15m
```

**Exec into the pod and do an nslookup of the service dns name**
```
root@myapp-7799f86b6-4dcck:/# nslookup myapp-service.default.svc.cluster.local

;; Got recursion not available from 10.96.0.10
;; Got recursion not available from 10.96.0.10
;; Got recursion not available from 10.96.0.10
;; Got recursion not available from 10.96.0.10
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   myapp-service.default.svc.cluster.local
Address: 10.101.104.130
;; Got recursion not available from 10.96.0.10
```

**View the created environmental variable via an exec into the pod**
```
root@myapp-7799f86b6-4dcck:/# | grep -i MYAPP

HOSTNAME=myapp-7799f86b6-4dcck
MYAPP_SERVICE_PORT_80_TCP=tcp://10.101.104.130:80
MYAPP_SERVICE_PORT_80_TCP_PROTO=tcp
MYAPP_SERVICE_PORT_80_TCP_PORT=80
MYAPP_SERVICE_PORT=tcp://10.101.104.130:80
MYAPP_SERVICE_SERVICE_HOST=10.101.104.130
MYAPP_SERVICE_SERVICE_PORT=80
MYAPP_SERVICE_PORT_80_TCP_ADDR=10.101.104.130
```
@kundan2707, next time, it'd be great to support your claim by either showing a sample we can try, referencing an existing URL in the documentation, or a merged PR.

2025-01-07 08:27 UTC, closed without merging