Hello minikube french
kubernetes/website pull request #47339
Opened 2024-08-01 15:34 UTC by cesar-lizurey

### Description

Getting rid of katacoda mentions in `hello minikube` for French language.

### Issue

Closes https://github.com/kubernetes/website/issues/47214 and contributes to https://github.com/kubernetes/website/issues/41496

2024-08-01 15:42 UTC, perriea requested changes

2024-08-01 15:42 UTC, perriea commented on content/fr/docs/tutorials/hello-minikube.md
> +title: Bienvenue sur minikube
```suggestion
title: Bienvenue sur Minikube
```

2024-08-01 15:42 UTC, perriea commented on content/fr/docs/tutorials/hello-minikube.md
> +Un [*Pod*](/docs/concepts/workloads/pods/) Kubernetes est un groupe de un ou plusieurs Containers, liés ensemble pour les besoins de l'administration et du réseau. Le Pod de ce tutoriel n'a qu'un seu
```suggestion
Un [*Pod*](/docs/concepts/workloads/pods/) Kubernetes est un groupe de un ou plusieurs conteneurs, liés ensemble pour les besoins de l'administration et du réseau. Le Pod de ce tutoriel n'a qu'un seul conteneur. Un [*Deployment*](/docs/concepts/workloads/controllers/deployment/) Kubernetes vérifie l'état de santé de votre Pod et redémarre le conteneur du Pod s'il se termine. Les Deployments sont la méthode recommandée pour gérer la création et la mise à l'échelle des Pods.
```

2024-08-01 15:42 UTC, perriea commented on content/fr/docs/tutorials/hello-minikube.md
> +1. Utilisez la commande `kubectl` create pour créer un Deployment qui gère un Pod. Le Pod exécute un Container basé sur l'image Docker fournie.
```suggestion
1. Utilisez la commande `kubectl` create pour créer un Deployment qui gère un Pod. Le Pod exécute un conteneur basé sur l'image Docker fournie.
```

2024-08-01 15:42 UTC, perriea commented on content/fr/docs/tutorials/hello-minikube.md
> +L'outil minikube inclut un ensemble intégré d'{{< glossary_tooltip text="addons" term_id="addons" >}} qui peuvent être activés, désactivés et ouverts dans l'environnement local Kubernetes.
```suggestion
La commande `minikube` inclut un ensemble intégré d'{{< glossary_tooltip text="addons" term_id="addons" >}} qui peuvent être activés, désactivés et ouverts dans l'environnement local Kubernetes.
```

2024-08-01 15:42 UTC, perriea commented on content/fr/docs/tutorials/hello-minikube.md
> +    The output is similar to:
```suggestion
    La sortie devrait être simulaire à :
```

2024-08-01 15:45 UTC, perriea commented
@cesar-lizurey Thank you for your corrections, I will let you sign the CLA and consult my suggestions :)

2024-08-01 16:01 UTC, cesar-lizurey commented
> @cesar-lizurey Thank you for your corrections, I will let you sign the CLA and consult my suggestions :)

I signed it, I don't know why it doesn't take my signature into account... :(

2024-08-01 17:57 UTC, dipesh-rawat commented
> I signed it, I don't know why it doesn't take my signature into account... :(

The EasyCLA bot's [message (here)](https://github.com/kubernetes/website/pull/47339#issuecomment-2263371090) indicates there are two commits from user `djcaesar9114` (See the message below)

> ❌ login: @djcaesar9114 / The commit (https://github.com/kubernetes/website/commit/3177ce51c5efbb4d9e72201546d4ae29ca46f4d0, https://github.com/kubernetes/website/commit/bbe01fcf65c0772440c0ddd7aec90695889027ab). This user is authorized, but they must confirm their affiliation with their company. Start the authorization process [by clicking here](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/18706487/51478266/47339/#/?version=2), click "Corporate", select the appropriate company from the list, then confirm your affiliation on the page that appears. For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

For the CLA, all contributors in the PR need to sign it. Although you've signed with @cesar-lizurey account, the check is failing because the other user (`djcaesar9114`) might not have signed the CLA yet.

2024-08-02 07:04 UTC, Arhell reviewed
/easycla

2024-08-02 07:58 UTC, cesar-lizurey commented
I submitted a ticket to EasyCLA. To be continued...

2024-08-05 07:04 UTC, T-Lakshmi commented
Re triggering EasyCLA to check if updated.

/easycla

2024-08-07 17:39 UTC, perriea approved these changes

2024-08-07 17:39 UTC, perriea commented
/lgtm

2024-08-07 17:40 UTC, merged

2024-08-07 17:41 UTC, perriea commented
Congratulation to your first contribution @cesar-lizurey ! 🎉

2024-08-07 20:32 UTC, cesar-lizurey commented
> Congratulation for your first contribution @cesar-lizurey ! 🎉

Thanks a lot!