feat: update structure and create new index.md ES translation
kubernetes/website pull request #47447
Opened 2024-08-12 01:11 UTC by krol3

### Description
 - New translation : content/es/docs/tasks/debug/_index.md
 - the other files are only moving to keep the new structure 
 

### Issue
Related to https://github.com/kubernetes/website/issues/47444

Closes: #

2024-08-13 21:17 UTC, sftim reviewed
I recommend some tweaks.

2024-08-13 21:17 UTC, sftim commented on content/es/docs/tasks/debug/_index.md
> +  title: Getting help
nit: localize this text

2024-08-13 21:17 UTC, sftim commented on content/es/docs/tasks/debug/_index.md
> +### Stack Exchange, Stack Overflow o Falla del Servidor {#stack-exchange}
```suggestion
### Stack Exchange, Stack Overflow o Server Fault {#stack-exchange}
```

2024-08-13 21:17 UTC, sftim commented on content/es/docs/tasks/debug/_index.md
> +[Falla del Servidor](https://serverfault.com/help/on-topic), o el Stack Exchange
```suggestion
[Server Fault](https://serverfault.com/help/on-topic), o el Stack Exchange
```

2024-08-13 21:17 UTC, sftim commented on content/es/docs/tasks/debug/_index.md
> +{{< table caption="Country / language specific Slack channels" >}}
nit: localize this caption

2024-08-13 21:17 UTC, sftim commented on content/es/docs/tasks/debug/_index.md
> +Región | Channels
```suggestion
Región | Canal(es)
```

2024-08-13 21:17 UTC, sftim commented on content/es/docs/tasks/debug/_index.md
> +por favor utilice el [Sistema de seguimiento de asuntos en el GitHub](https://github.com/kubernetes/kubernetes/issues).
(nit)
```suggestion
por favor utilice el [sistema de seguimiento de asuntos en el GitHub](https://github.com/kubernetes/kubernetes/issues).
```

2024-08-13 21:17 UTC, sftim commented on content/es/docs/tasks/debug/_index.md
> +-
```suggestion
```

2024-08-14 19:29 UTC, electrocucaracha requested changes

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +para administradores de clústeres y personas cuyo clúster de Kubernetes no está satisfecho.
```suggestion
para administradores de clústeres y personas cuyo clúster de Kubernetes no funciona correctamente.
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +puedes preguntarles a los de [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes).
```suggestion
puedes preguntar en [Stack Overflow](https://stackoverflow.com/questions/tagged/kubernetes).
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +Si tiene preguntas sobre Kubernetes relacionadas con *administración de clusters* or *configuración*,
```suggestion
Si tiene preguntas sobre Kubernetes relacionadas con *administración de clústeres* or *configuración*,
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +puedes preguntarles a los de
```suggestion
puedes preguntarles en
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +or [InfoSec](https://security.stackexchange.com/questions/tagged/kubernetes).
```suggestion
o [InfoSec](https://security.stackexchange.com/questions/tagged/kubernetes).
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +y el registro está abierto a todos. No dudes en participar y hacer todas y cada una de las preguntas.
```suggestion
el registro está abierto a todos. No dudes en participar y hacer todas y cada una de las preguntas.
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +Una vez registrado, acceder a la [Organización de Kubernetes en Slack](https://kubernetes.slack.com)
```suggestion
Una vez registrado, accede a la [Organización de Kubernetes en Slack](https://kubernetes.slack.com)
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +a través de su navegador web o mediante la aplicación dedicada de Slack..
```suggestion
a través de tu navegador web o mediante la aplicación dedicada de Slack..
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +También hay muchos canales en idiomas locales o específicos de cada país. Siéntete libre de unirte
```suggestion
También hay muchos canales en idiomas locales o específicos de cada país. Siéntete libre de unirte a
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +{{< table caption="Country / language specific Slack channels" >}}
```suggestion
{{< table caption="País / idioma especifico del canal de Slack" >}}
```

2024-08-14 19:29 UTC, electrocucaracha commented on content/es/docs/tasks/debug/_index.md
> +Turkey | [`#tr-users`](https://kubernetes.slack.com/messages/tr-users), [`#tr-events`](https://kubernetes.slack.com/messages/tr-events)
```suggestion
Finlandia | [`#fi-users`](https://kubernetes.slack.com/messages/fi-users)
Francia | [`#fr-users`](https://kubernetes.slack.com/messages/fr-users), [`#fr-events`](https://kubernetes.slack.com/messages/fr-events)
Alemania | [`#de-users`](https://kubernetes.slack.com/messages/de-users), [`#de-events`](https://kubernetes.slack.com/messages/de-events)
India | [`#in-users`](https://kubernetes.slack.com/messages/in-users), [`#in-events`](https://kubernetes.slack.com/messages/in-events)
Italia | [`#it-users`](https://kubernetes.slack.com/messages/it-users), [`#it-events`](https://kubernetes.slack.com/messages/it-events)
Japon | [`#jp-users`](https://kubernetes.slack.com/messages/jp-users), [`#jp-events`](https://kubernetes.slack.com/messages/jp-events)
Corea | [`#kr-users`](https://kubernetes.slack.com/messages/kr-users)
Holanda | [`#nl-users`](https://kubernetes.slack.com/messages/nl-users)
Noruega | [`#norw-users`](https://kubernetes.slack.com/messages/norw-users)
Polonia | [`#pl-users`](https://kubernetes.slack.com/messages/pl-users)
Rusia | [`#ru-users`](https://kubernetes.slack.com/messages/ru-users)
Países Hispanos | [`#es-users`](https://kubernetes.slack.com/messages/es-users)
Suecia | [`#se-users`](https://kubernetes.slack.com/messages/se-users)
Turquia | [`#tr-users`](https://kubernetes.slack.com/messages/tr-users), [`#tr-events`](https://kubernetes.slack.com/messages/tr-events)
```

2024-08-17 16:44 UTC, krol3 commented
Thanks for the review @sftim and @electrocucaracha. I considered all your comments.

2024-08-17 17:39 UTC, electrocucaracha commented
/lgtm

2024-08-20 15:23 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +Si ninguna de las guías anteriores resuelve su problema, existen varias formas de obtener ayuda de la comunidad de Kubernetes..
```suggestion
Si ninguna de las guías anteriores resuelve su problema, existen varias formas de obtener ayuda de la comunidad de Kubernetes.
```

2024-08-20 15:23 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +* [Depuración de su aplicación](/docs/tasks/debug/debug-application/) - Útil
```suggestion
* [Depuración de tu aplicación](/docs/tasks/debug/debug-application/) - Útil
```

2024-08-20 15:23 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +* [Depuración de su clúster](/docs/tasks/debug/debug-cluster/) - Útil
```suggestion
* [Depuración de tu clúster](/docs/tasks/debug/debug-cluster/) - Útil
```

2024-08-20 15:25 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +La documentación de este sitio ha sido estructurada para brindar respuestas a una amplia gama de preguntas. [Conceptos](/docs/concepts/) explican la arquitectura de Kubernetes
```suggestion
La documentación de este sitio ha sido estructurada para brindar respuestas a una amplia gama de preguntas. [Conceptos](/es/docs/concepts/) explican la arquitectura de Kubernetes
```

2024-08-20 15:26 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +y cómo funciona cada componente, mientras [Configuración](/docs/setup/) proporciona
```suggestion
y cómo funciona cada componente, mientras [Configuración](/es/docs/setup/) proporciona
```

2024-08-20 15:27 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +realizar tareas de uso común, y [Tutoriales](/docs/tutorials/) son recorridos más completos de escenarios de desarrollo reales, específicos de la industria o de extremo a extremo. La sección de [Refe
```suggestion
realizar tareas de uso común, y [Tutoriales](/es/docs/tutorials/) son recorridos más completos de escenarios de desarrollo reales, específicos de la industria o de extremo a extremo. La sección de [Referencia](/es/docs/reference/) proporciona
```

2024-08-20 15:27 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +y las interfaces de línea de comandos (CLIs), tal como [`kubectl`](/docs/reference/kubectl/).
```suggestion
y las interfaces de línea de comandos (CLIs), tal como [`kubectl`](/es/docs/reference/kubectl/).
```

2024-08-20 15:28 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +Si tienes preguntas relacionadas con *desarrollo de software* para su aplicación en contenedores,
```suggestion
Si tienes preguntas relacionadas con *desarrollo de software* para tu aplicación en contenedores,
```

2024-08-20 15:28 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +Si tiene preguntas sobre Kubernetes relacionadas con *administración de clústeres* o *configuración*,
```suggestion
Si tienes preguntas sobre Kubernetes relacionadas con *administración de clústeres* o *configuración*,
```

2024-08-20 15:28 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +correcto en el que estás preguntando**, y lea las instrucciones sobre
```suggestion
correcto en el que estás preguntando**, y lee las instrucciones sobre 
```

2024-08-20 15:28 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +Antes de preguntar una nueva!
```suggestion
antes de preguntar una nueva!
```

2024-08-20 15:32 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +Una vez registrado, ingrese a la [Organización de Kubernetes en Slack](https://kubernetes.slack.com)
```suggestion
Una vez registrado, ingresa a la [Organización de Kubernetes en Slack](https://kubernetes.slack.com)
```

2024-08-20 15:33 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +Si tiene lo que parece ser un error (bug) o desea realizar una solicitud de funcionalidades,
```suggestion
Si tienes lo que parece ser un error (bug) o desea realizar una solicitud de funcionalidades,
```

2024-08-20 15:33 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +por favor utilice el [sistema de seguimiento de asuntos en el GitHub](https://github.com/kubernetes/kubernetes/issues).
```suggestion
por favor utiliza el [sistema de seguimiento de asuntos en el GitHub](https://github.com/kubernetes/kubernetes/issues).
```

2024-08-20 15:33 UTC, ramrodo commented on content/es/docs/tasks/debug/_index.md
> +Antes de presentar un problema, busque problemas existentes para ver si su problema ya está cubierto.
```suggestion
Antes de presentar un problema, busca problemas existentes para ver si tu problema ya está cubierto.
```

2024-08-20 15:34 UTC, ramrodo requested changes
Some minor suggestions and typos.

2024-09-03 00:48 UTC, ramrodo commented
Great!
/lgtm

2024-09-03 02:14 UTC, electrocucaracha commented
/lgtm
/approve

2024-09-03 02:15 UTC, merged