Gateway API Translation
kubernetes/website pull request #47728
Opened 2024-08-30 07:23 UTC by tamilselvan1102

fixes : #47680

2024-08-30 07:38 UTC, tamilselvan1102 commented
page preview : https://deploy-preview-47728--kubernetes-io-main-staging.netlify.app/ja/docs/reference/glossary/?all=true#term-gateway-api

2024-08-30 08:08 UTC, Okabe-Junya commented
/retitle [ja] Translate Gateway API into Japanese

2024-08-30 08:14 UTC, Okabe-Junya requested changes
Thanks, I have some comments

2024-08-30 08:14 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/gateway.md
> +title: ゲートウェイ API（Gateway API）
```suggestion
title: Gateway API
```

2024-08-30 08:14 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/gateway.md
> +Kubernetesでサービスネットワークをモデル化するために使用されるAPIクラスのセット。
```suggestion
Kubernetesでサービスネットワーキングをモデル化するために使用されるAPIクラス群。
```

2024-08-30 08:14 UTC, Okabe-Junya commented on content/ja/docs/reference/glossary/gateway.md
> +Gateway APIはKubernetesでサービスネットワークをモデル化するための拡張可能、ロール指向、プロトコル認識APIクラスのセットを提供します。
```suggestion
Gateway APIは、Kubernetesにおけるサービスネットワーキングをモデル化するための、拡張性が高く、ロール指向で、プロトコル対応のAPIクラス群を提供します。
```

2024-08-30 08:15 UTC, Okabe-Junya commented
/assign nasa9084 
for approval
/label tide/merge-method-squash

2024-08-30 08:33 UTC, Okabe-Junya reviewed
/lgtm

2024-09-03 08:24 UTC, bells17 commented
/approve

2024-09-03 08:27 UTC, merged