update fr docs concepts overview
kubernetes/website pull request #47764
Opened 2024-09-02 19:31 UTC by rekcah78

2024-09-09 13:15 UTC, perriea requested changes
Sounds good except two file not translated yet :)

2024-09-09 13:15 UTC, perriea commented on content/fr/docs/concepts/overview/working-with-objects/_index.md
This part isn't translated yet

2024-09-11 09:39 UTC, rekcah78 commented on content/fr/docs/concepts/overview/working-with-objects/object-management.md
done

2024-09-11 09:40 UTC, rekcah78 commented on content/fr/docs/concepts/overview/working-with-objects/_index.md
done

2024-09-11 11:29 UTC, perriea commented
Nothing more to add? @rekcah78

2024-09-11 11:43 UTC, rekcah78 commented
> Nothing more to add? @rekcah78

no more for this PR

2024-09-11 11:46 UTC, perriea commented
/lgtm

2024-09-11 11:47 UTC, merged