Update kubernetes-api.md: correct tenses and add punctuation
kubernetes/website pull request #47826
Opened 2024-09-07 14:20 UTC by olu-folarin

## What Change is Proposed?
The tenses of the changed words and a punctuation mark **a comma**

## Why the Change?
To improve readability and tense structure.

2024-09-09 14:56 UTC, olu-folarin commented
@mickeyboxell @salaxander are there any modifications/alterations needed in this PR, please?

2024-09-09 20:03 UTC, salaxander requested changes

2024-09-09 20:03 UTC, salaxander commented on content/en/docs/concepts/overview/kubernetes-api.md
> -  The data is a complete specification and is significantly larger than that from the
I think this line can stay as is because I believe it's referring to data returned from the discovery API

2024-09-10 00:26 UTC, tengqm commented
/lgtm

2024-09-10 06:27 UTC, olu-folarin commented
@tengqm @salaxander @mickeyboxell I have reverted the changes that were made in the OpenAPI section.

2024-09-10 06:33 UTC, tengqm commented
/lgtm
/approve

2024-09-10 06:35 UTC, merged

2024-09-10 06:38 UTC, olu-folarin commented
Thanks @tengqm