[bn] Localization of cluster-architect.md
kubernetes/website pull request #47833
Opened 2024-09-08 15:59 UTC by Noblesse013

localized cluster-architect.md in bangla

fixes #45729

2024-09-10 11:54 UTC, sajibAdhi requested changes

2024-09-10 11:54 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/cluster-architect.md
> +  একজন ব্যক্তি যিনি এক বা একাধিক কুবের্নেটিস ক্লাস্টারের সাথে সম্পর্কিত পরিকাঠামো ডিজাইন করেন।
@Noblesse013 

Please use `ইনফ্রাস্ট্রাকচার` instead of `পরিকাঠামো` as this term is used very often.

2024-09-10 11:54 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/cluster-architect.md
> +একজন ব্যক্তি যিনি এক বা একাধিক কুবের্নেটিস ক্লাস্টারের সাথে সম্পর্কিত পরিকাঠামো ডিজাইন করেন।
Please use `ইনফ্রাস্ট্রাকচার` instead of `পরিকাঠামো` as this term is used very often.

2024-09-10 11:54 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/cluster-architect.md
> +ক্লাস্টার আর্কিটেক্টরা বিতরণ করা সিস্টেমের সেরা অনুশীলনগুলি নিয়ে চিন্তিত থাকেন, যেমন&#58; উচ্চ প্রাপ্যতা এবং সুরক্ষা।
```
ক্লাস্টার আর্কিটেক্টরা ডিস্ট্রিবিউটেড সিস্টেমের সেরা প্রাক্টিসগুলি নিয়ে চিন্তিত থাকেন, যেমন&#58; উচ্চ এভেইল্যাবিলিটি এবং সুরক্ষা।
```

2024-09-11 08:47 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/cluster-architect.md
> +ক্লাস্টার আর্কিটেক্টরা বিতরণ করা সিস্টেমের সেরা অনুশীলনগুলি নিয়ে চিন্তিত থাকেন, যেমন&#58; উচ্চ প্রাপ্যতা এবং সুরক্ষা।
> I have fixed the issue. Please check the updated version.

Thank you.

2024-09-11 08:48 UTC, sajibAdhi approved these changes
/lgtm

2024-09-11 08:51 UTC, sajibAdhi commented
/assign @asem-hamid 

Can you proceed with this?

2024-09-11 15:35 UTC, asem-hamid commented
/label tide/merge-method-squash

2024-09-14 13:28 UTC, Noblesse013 commented on content/bn/docs/reference/glossary/cluster-architect.md
> +একজন ব্যক্তি যিনি এক বা একাধিক কুবের্নেটিস ক্লাস্টারের সাথে সম্পর্কিত ইনফ্রাস্ট্রাকচার ডিজাইন করেন।
fixed the spelling.

2024-09-15 04:51 UTC, sajibAdhi reviewed
/lgtm

2024-09-15 05:24 UTC, asem-hamid approved these changes

2024-09-15 05:25 UTC, merged