[bn] Localization of uid.md
kubernetes/website pull request #47944
Opened 2024-09-15 20:05 UTC by Noblesse013

localised it in bengali #45729

2024-09-23 03:54 UTC, sajibAdhi requested changes

2024-09-23 03:54 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/uid.md
> +  কুবেরনেটিস সিস্টেম দ্বারা তৈরি একটি স্ট্রিং যা অবজেক্টকে অনন্যভাবে চিহ্নিত করে।
Kindly use `কুবারনেটিস` instead of `কুবেরনেটিস` and `ইউনিকভাবে` instead of `অনন্যভাবে`.

2024-09-23 03:54 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/uid.md
> +কুবেরনেটিস সিস্টেম দ্বারা তৈরি একটি স্ট্রিং যা অবজেক্টকে অনন্যভাবে চিহ্নিত করে।
Kindly use `কুবারনেটিস` instead of `কুবেরনেটিস` and `ইউনিকভাবে` instead of `অনন্যভাবে`.

2024-09-23 03:54 UTC, sajibAdhi commented on content/bn/docs/reference/glossary/uid.md
> +কুবেরনেটিস ক্লাস্টারের সারাজীবন জুড়ে তৈরি করা প্রতিটি অবজেক্ট একটি স্বতন্ত্র UID থাকে। এটি সদৃশ সত্তার ঐতিহাসিক ঘটনার মধ্যে পার্থক্য করার জন্য উদ্দেশ্যপ্রণোদিত।
Kindly use it.
```
কুবারনেটিস ক্লাস্টারের পুরো লাইফটাইম জুড়ে তৈরি করা প্রতিটি অবজেক্টের একটি স্বতন্ত্র UID থাকে। এটি অনুরূপ সত্তা ঐতিহাসিক ঘটনার মধ্যে পার্থক্য করার উদ্দেশ্যে করা হয়েছে।
```

2024-10-03 12:46 UTC, asem-hamid commented
@Noblesse013 Please fix them

2024-10-05 05:56 UTC, Noblesse013 commented
> @Noblesse013 Please fix them

i did . please check if more changes is required or not!

2024-10-21 16:23 UTC, asem-hamid commented
/lgtm

2024-10-21 16:33 UTC, asem-hamid commented
/label tide/merge-method-squash

2024-10-22 06:34 UTC, merged