Updated Kubernetes architecture image in tutorials
kubernetes/website pull request #48193
Opened 2024-10-04 10:46 UTC by utkarsh-singh1

### Description
Updated the kubernetes architecture image in tutorial/kubernetes-basics/create-cluster.

Closes: #45619

2024-10-04 10:47 UTC, utkarsh-singh1 commented
page link -> https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

2024-10-04 10:47 UTC, utkarsh-singh1 commented
/sig docs

2024-10-04 10:49 UTC, utkarsh-singh1 commented
@dipak-pawar, @tengqm Updated the image in tutorial PTAL.

2024-10-15 11:52 UTC, sftim commented
/lgtm

2024-10-15 11:53 UTC, sftim commented on content/en/docs/tutorials/kubernetes-basics/public/images/k8s-structure.svg
nit: kube-apiserver (no `-` between api and server)

2024-10-16 03:10 UTC, utkarsh-singh1 commented on content/en/docs/tutorials/kubernetes-basics/public/images/k8s-structure.svg
Updated @sftim

2025-01-14 17:37 UTC, sftim commented
@utkarsh-singh1 what's your intention with this PR? It's been draft a while.

2025-01-26 16:19 UTC, utkarsh-singh1 commented
@sftim, was not available for the changes.

2025-08-17 03:32 UTC, divya-mohan0209 requested changes
@utkarsh-singh1 : Please address the merge conflict to proceed with further review.

2025-09-16 03:54 UTC, closed without merging