Add list-all-running-container-images em PT-BR
kubernetes/website pull request #48288
Opened 2024-10-11 15:11 UTC by luisfroliveira

Adicionado a seguinte pagina em pt-br

/content/pt-br/docs/tasks/access-application-cluster.md

issue #48282

2024-10-11 15:19 UTC, stormqueen1990 commented
/retitle [pt-br] Add
tasks/access-application-cluster/list-all-running-container-images.md

2024-10-11 15:20 UTC, stormqueen1990 commented
/retitle [pt-br]
Add tasks/access-application-cluster/list-all-running-container-images.md

2024-10-11 15:25 UTC, stormqueen1990 commented
/retitle [pt-br] Add tasks/access-application-cluster/list-all-running-container-images.md

2024-10-11 15:31 UTC, edsoncelio commented
/cc edsoncelio

2024-10-13 13:15 UTC, edsoncelio requested changes
Thanks for your contribution!
I've made a few suggestions - after that will be LGTM from my side.

2024-10-13 13:15 UTC, edsoncelio commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +em execução no cluster e formatar a saida com uma lista dos conteiners
```suggestion
em execução no cluster e formatar a saída com uma lista dos contêineres 
```

2024-10-13 13:15 UTC, edsoncelio commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +O formato de saida pode ser controlado ainda mais usando a operação `range` para
```suggestion
O formato de saída pode ser controlado ainda mais usando a operação `range` para
```

2024-11-02 13:44 UTC, edsoncelio commented
PTAL @stormqueen1990

2024-12-18 22:39 UTC, stormqueen1990 reviewed
Olá @luisfroliveira!

Muito obrigada pela tua contribuição. Encontrei alguns itens que necessitam ajustes bem pontuais. Assim que estes forem feitos volto para deixar meu LGTM.

Obrigada novamente!

2024-12-18 22:39 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +  - Consulte [jsonpath reference](/docs/reference/kubectl/jsonpath/)
Ajuste pequeno para legibilidade em português

```suggestion
  - Consulte a [referência de jsonpath](/docs/reference/kubectl/jsonpath/)
```

2024-12-18 22:39 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +- Formate a saida incluindo apenas a lista de nomes das imagens de contêiner
Faltou um acento aqui!

```suggestion
- Formate a saída incluindo apenas a lista de nomes das imagens de contêiner
```

2024-12-18 22:39 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +- `['initContainers', 'containers'][*]`: especificação do tipo de Pod
O texto original aqui diz "para cada contêiner". Acho que seria legal manter.

```suggestion
- `['initContainers', 'containers'][*]`: para cada contêiner
```

2024-12-18 22:39 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +a parte `.items[*]` do caminho deve ser omitida porque um unico Pod é retornado
Faltou um acento aqui!

```suggestion
a parte `.items[*]` do caminho deve ser omitida porque um único Pod é retornado
```

2024-12-18 22:39 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +O formato de saida pode ser controlado ainda mais usando a operação `range` para
Outro acento!

```suggestion
O formato de saída pode ser controlado ainda mais usando a operação `range` para
```

2024-12-18 22:39 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/access-application-cluster/list-all-running-container-images.md
> +* [Go template](https://pkg.go.dev/text/template) guia de referência
Ajuste pequeno para legibilidade em português, já que costumamos falar "guia de referência de <tecnologia>" ao invés de "<tecnologia> guia de referência".

```suggestion
* Guia de referência de [Jsonpath](/docs/reference/kubectl/jsonpath/)
* Guia de referência de [Go template](https://pkg.go.dev/text/template)
```

2024-12-18 22:39 UTC, stormqueen1990 commented
/label tide/merge-method-squash

2025-01-15 20:59 UTC, stormqueen1990 reviewed
Muito obrigada pela contribuição!

/lgtm

PTAL @edsoncelio

2025-01-16 02:09 UTC, edsoncelio commented
Thanks!
/approve

2025-01-16 02:10 UTC, merged