[hi] Localize concepts/service-networking page
kubernetes/website pull request #48390
Opened 2024-10-16 21:08 UTC by aryasoni98

### Description
This pull request adds a Hindi translation of the "Services, Load Balancing, and Networking" documentation page. The translated _index.md file provides concepts and resources behind networking in Kubernetes for Hindi-speaking users.

### Issue

Closes: #48322

2024-10-17 06:21 UTC, niranjandarshann reviewed
Some suggestion for changes.

2024-10-17 06:21 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +* _पॉड नेटवर्क_ (जिसे क्लस्टर नेटवर्क भी कहा जाता है) पॉड्स के बीच संचार को संभालता है। यह सुनिश्चित करता है कि (जानबूझकर नेटवर्क विभाजन को छोड़कर):
```suggestion
* _पॉड नेटवर्क_ (जिसे क्लस्टर नेटवर्क भी कहा जाता है) पॉड्स के बीच संचार को संभालता है। यह सुनिश्चित करता है कि (जब तक जानबूझकर नेटवर्क विभाजन नहीं किया गया हो):
```

2024-10-17 06:21 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +* [सर्विस](/docs/concepts/services-networking/service/) API आपको एक स्थिर (लंबी अवधि) IP पता या होस्टनाम प्रदान करने की अनुमति देता है एक सेवा के लिए जो एक या अधिक बैकएंड पॉड्स द्वारा लागू की गई है,
```suggestion
* [सर्विस](/docs/concepts/services-networking/service/) API आपको एक स्थिर (लंबी अवधि) IP एड्रेस या होस्टनेम प्रदान करने की अनुमति देता है एक सर्विस के लिए जो एक या अधिक बैकएंड पॉड्स द्वारा लागू की गई है, जहाँ सर्विस बनाने वाले व्यक्तिगत पॉड्स समय के साथ बदल सकते हैं।
```

2024-10-17 06:21 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +  * Kubernetes स्वचालित रूप से [EndpointSlice](/docs/concepts/services-networking/endpoint-slices/) ऑब्जेक्ट्स को प्रबंधित करता है ताकि सेवा का समर्थन करने वाले वर्तमान पॉड्स के बारे में जानकारी प्रद
```suggestion
  * Kubernetes स्वचालित रूप से [EndpointSlice](/docs/concepts/services-networking/endpoint-slices/) ऑब्जेक्ट्स को प्रबंधित करता है ताकि सर्विस का समर्थन करने वाले वर्तमान पॉड्स के बारे में जानकारी प्रदान की जा सके।
```

2024-10-17 06:21 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +  * एक सेवा प्रॉक्सी कार्यान्वयन सेवा और EndpointSlice ऑब्जेक्ट्स के सेट की निगरानी करता है, और ऑपरेटिंग सिस्टम या क्लाउड प्रदाता API का उपयोग करके पैकेट्स को इंटरसेप्ट या पुनर्लेखन करके डेटा प्लेन क
```suggestion
  * एक सर्विस प्रॉक्सी कार्यान्वयन सेवा और EndpointSlice ऑब्जेक्ट्स के सेट की निगरानी करता है, और ऑपरेटिंग सिस्टम या क्लाउड प्रदाता API का उपयोग करके पैकेट्स को इंटरसेप्ट या पुनर्लेखन करके डेटा प्लेन को सर्विस ट्रैफ़िक को उसके बैकएंड्स तक रूट करने के लिए प्रोग्राम करता है।
```

2024-10-17 06:29 UTC, niranjandarshann commented
@aryasoni98  it will be the good practice not to translate the predefined technical terms of k8s in hindi like **सर्विस, होस्टनेम, IP एड्रेस ** I have suggested some Please have a look into the entire page and change the required in entire docs. Try to use simple hindi language so that it can be easy to understand by the readers.

2024-10-17 18:03 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +शीर्षक: "सेवाएँ, लोड बैलेंसिंग, और नेटवर्किंग"
Fix the issue

2024-10-17 18:05 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +* क्लस्टर में प्रत्येक [पॉड](/docs/concepts/workloads/pods/) को अपना विशिष्ट क्लस्टर-वाइड IP पता मिलता है।
Fix the issue

2024-10-17 18:05 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +  * एक पॉड का अपना निजी नेटवर्क नेमस्पेस होता है जिसे उस पॉड के सभी कंटेनर साझा करते हैं। एक ही पॉड में अलग-अलग कंटेनरों में चलने वाली प्रक्रियाएँ `localhost` के माध्यम से एक-दूसरे से संचार कर सकती ह
Fix the issue

2024-10-17 18:06 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +* [सर्विस](/docs/concepts/services-networking/service/) API आपको एक स्थिर (लंबी अवधि) IP पता या होस्टनाम प्रदान करने की अनुमति देता है एक सेवा के लिए जो एक या अधिक बैकएंड पॉड्स द्वारा लागू की गई है,
Fix the issue

2024-10-17 18:07 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +  * Kubernetes स्वचालित रूप से [EndpointSlice](/docs/concepts/services-networking/endpoint-slices/) ऑब्जेक्ट्स को प्रबंधित करता है ताकि सेवा का समर्थन करने वाले वर्तमान पॉड्स के बारे में जानकारी प्रद
Fix the issue

2024-10-17 18:08 UTC, aryasoni98 commented
> @aryasoni98 it will be the good practice not to translate the predefined technical terms of k8s in hindi like **सर्विस, होस्टनेम, IP एड्रेस ** I have suggested some Please have a look into the entire page and change the required in entire docs. Try to use simple hindi language so that it can be easy to understand by the readers.

Thank you for your feedback, @aryasoni98. I agree that we should retain predefined technical terms like Service, Hostname, and IP Address in English. I'll review the entire document and update it accordingly to ensure these terms remain untranslated. I'll also make sure to use simple Hindi language throughout to make it easier for readers to understand. I appreciate your suggestions and will make the necessary changes.

2024-10-18 05:57 UTC, niranjandarshann reviewed
Some suggestion for changes from my side.

2024-10-18 05:57 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +शीर्षक: "सर्विसेज , लोड बैलेंसिंग, और नेटवर्किंग"
```suggestion
शीर्षक: "सर्विसेज, लोड बैलेंसिंग और नेटवर्किंग"
```

2024-10-18 05:57 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +पुराने कंटेनर सिस्टम में, विभिन्न होस्ट्स पर कंटेनरों के बीच स्वचालित कनेक्टिविटी नहीं होती थी, इसलिए कंटेनरों के बीच स्पष्ट लिंक बनाना या अन्य होस्ट्स पर कंटेनरों द्वारा उन्हें सुलभ बनाने के लिए कंट
```suggestion
पुराने कंटेनर सिस्टम में, विभिन्न होस्ट्स पर कंटेनरों के बीच स्वचालित कनेक्टिविटी नहीं होती थी, इसलिए कंटेनरों के बीच स्पष्ट लिंक बनाना या अन्य होस्ट्स पर कंटेनरों द्वारा उन्हें सुलभ बनाने के लिए कंटेनर पोर्ट्स को होस्ट पोर्ट्स पर मैप करना अक्सर आवश्यक होता था। Kubernetes में यह आवश्यक नहीं है; Kubernetes का मॉडल है कि पॉड्स को VMs या भौतिक होस्ट्स की तरह माना जा सकता है, पोर्ट आवंटन, नामकरण, सर्विस डिस्कवरी, लोड बैलेंसिंग, एप्लिकेशन कॉन्फ़िगरेशन और माइग्रेशन के दृष्टिकोण से।
```

2024-10-18 05:57 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +* Kubernetes सेवा प्रॉक्सींग का एक डिफ़ॉल्ट कार्यान्वयन प्रदान करता है, जिसे {{< glossary_tooltip term_id="kube-proxy">}} कहा जाता है, लेकिन कुछ पॉड नेटवर्क कार्यान्वयन इसके बजाय अपने स्वयं के सेवा प
```suggestion
* Kubernetes सर्विस प्रॉक्सींग का एक डिफ़ॉल्ट कार्यान्वयन प्रदान करता है, जिसे {{< glossary_tooltip term_id="kube-proxy">}} कहा जाता है, लेकिन कुछ पॉड नेटवर्क कार्यान्वयन इसके बजाय अपने स्वयं के सर्विस प्रॉक्सी का उपयोग करते हैं जो शेष कार्यान्वयन के साथ अधिक दृढ़ता से एकीकृत होता है।
```

2024-10-18 05:57 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +* [गेटवे API के कई कार्यान्वयन](https://gateway-api.sigs.k8s.io/implementations/) हैं, जिनमें से कुछ विशेष क्लाउड वातावरणों के लिए विशिष्ट हैं, कुछ अधिक "बेयर मेटल" वातावरणों पर केंद्रित हैं, और अन्य
```suggestion
* [गेटवे API के कई कार्यान्वयन](https://gateway-api.sigs.k8s.io/implementations/) हैं, जिनमें से कुछ विशेष क्लाउड एनवायरनमेंट  के लिए विशिष्ट हैं, कुछ अधिक "बेयर मेटल" एनवायरनमेंट  पर केंद्रित हैं, और अन्य अधिक सामान्य हैं।
```

2024-10-18 05:57 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +[सेवाओं के साथ अनुप्रयोगों को कनेक्ट करना](/docs/tutorials/services/connect-applications-service/) ट्यूटोरियल आपको एक व्यावहारिक उदाहरण के साथ सेवाओं और Kubernetes नेटवर्किंग के बारे में सीखने में मद
```suggestion
[सर्विसेज के साथ अनुप्रयोगों को कनेक्ट करना](/docs/tutorials/services/connect-applications-service/) ट्यूटोरियल आपको एक व्यावहारिक उदाहरण के साथ सर्विसेज और Kubernetes नेटवर्किंग के बारे में सीखने में मदद करता है।
```

2024-10-18 05:57 UTC, niranjandarshann commented on content/hi/docs/concepts/services-networking/_index.md
> +[क्लस्टर नेटवर्किंग](/docs/concepts/cluster-administration/networking/) बताता है कि अपने क्लस्टर के लिए नेटवर्किंग कैसे सेट अप करें, और शामिल प्रौद्योगिकियों का एक सिंहावलोकन भी प्रदान करता है।
```suggestion
[क्लस्टर नेटवर्किंग](/docs/concepts/cluster-administration/networking/) बताता है कि अपने क्लस्टर के लिए नेटवर्किंग कैसे सेटअप करें, और शामिल प्रौद्योगिकियों का एक समीक्षा भी प्रदान करता है।
```

2024-10-21 14:28 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +शीर्षक: "सर्विसेज , लोड बैलेंसिंग, और नेटवर्किंग"
Fix the issue

2024-10-21 14:28 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +पुराने कंटेनर सिस्टम में, विभिन्न होस्ट्स पर कंटेनरों के बीच स्वचालित कनेक्टिविटी नहीं होती थी, इसलिए कंटेनरों के बीच स्पष्ट लिंक बनाना या अन्य होस्ट्स पर कंटेनरों द्वारा उन्हें सुलभ बनाने के लिए कंट
Fix the issue

2024-10-21 14:28 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +* Kubernetes सेवा प्रॉक्सींग का एक डिफ़ॉल्ट कार्यान्वयन प्रदान करता है, जिसे {{< glossary_tooltip term_id="kube-proxy">}} कहा जाता है, लेकिन कुछ पॉड नेटवर्क कार्यान्वयन इसके बजाय अपने स्वयं के सेवा प
Fix the issue

2024-10-21 14:29 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +[सेवाओं के साथ अनुप्रयोगों को कनेक्ट करना](/docs/tutorials/services/connect-applications-service/) ट्यूटोरियल आपको एक व्यावहारिक उदाहरण के साथ सेवाओं और Kubernetes नेटवर्किंग के बारे में सीखने में मद
Fix the issue

2024-10-21 14:30 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +* [गेटवे API के कई कार्यान्वयन](https://gateway-api.sigs.k8s.io/implementations/) हैं, जिनमें से कुछ विशेष क्लाउड वातावरणों के लिए विशिष्ट हैं, कुछ अधिक "बेयर मेटल" वातावरणों पर केंद्रित हैं, और अन्य
Fix the issue

2024-10-21 14:30 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +[क्लस्टर नेटवर्किंग](/docs/concepts/cluster-administration/networking/) बताता है कि अपने क्लस्टर के लिए नेटवर्किंग कैसे सेट अप करें, और शामिल प्रौद्योगिकियों का एक सिंहावलोकन भी प्रदान करता है।
Fix the issue

2024-10-29 11:27 UTC, aryasoni98 commented
@niranjandarshann @drnic @gnufied Just wanted to follow up on the PR—everything is looking good on your end, and no further changes are needed. Could you please review it when you have a moment? If all looks good to you, feel free to go ahead and merge.

2024-11-23 09:52 UTC, aryasoni98 commented
This is a quick reminder about this PR. If everything looks good, could you please go ahead and merge it? Let me know if there’s anything else you need from me.

2024-12-10 17:52 UTC, aryasoni98 commented
> This is a quick reminder about this PR. If everything looks good, could you please go ahead and merge it? Let me know if there’s anything else you need from me.

@niranjandarshann could you please go ahead and merge it?

2025-01-02 04:32 UTC, aj11anuj requested changes
Make required changes

2025-01-02 04:32 UTC, aj11anuj commented on content/hi/docs/concepts/services-networking/_index.md
> +वर्णन: >
```suggestion
title: "सर्विसेज, लोड बैलेंसिंग और नेटवर्किंग"
weight: 60
description: >
```
The structure of yaml/md file should not be localized in any language

2025-01-02 04:32 UTC, aj11anuj commented on content/hi/docs/concepts/services-networking/_index.md
> +* [गेटवे](/docs/concepts/services-networking/gateway/) API (या इसका पूर्ववर्ती, [इंग्रेस](/docs/concepts/services-networking/ingress/)) आपको क्लस्टर के बाहर के क्लाइंट्स के लिए सेवाओं को सुलभ बनाने क
- Don't use pure Hindi words that are not easy to understand and break the flow of reading like - पूर्ववर्ती, प्रौद्योगिकियों, समीक्षा, कार्यान्वयन, व्यवस्थापक, पोर्ट आवंटन etc. Use synonyms that make the sentences easy to read. (Try to use words commonly spoken in Hindi if they align with the context of the sentence.)
- Don't just use the AI or translation tools to do a literal translation of each word. Proofread once and make changes wherever you have used such words.
- Update the links used in the page with the Hindi docs page link wherever a Hindi doc page exists for that link.
- Replace 'Kubernetes' with कुबेरनेट्स wherever you have used it.
- If writing a Hinglish word like - एपीआई, क्यूबलेट in Hindi doesn't sound odd in places where you used English words like API, kubelet then write Hinglish there.

2025-01-02 19:52 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +वर्णन: >
Fix the issue

2025-01-02 19:53 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +वर्णन: >
Okay sure , fix the issue

2025-01-02 19:58 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +* [गेटवे](/docs/concepts/services-networking/gateway/) API (या इसका पूर्ववर्ती, [इंग्रेस](/docs/concepts/services-networking/ingress/)) आपको क्लस्टर के बाहर के क्लाइंट्स के लिए सेवाओं को सुलभ बनाने क
Sure, Fix the issue

2025-01-06 06:00 UTC, niranjandarshann reviewed
Few suggestion for changes.

2025-01-17 16:18 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +* क्लस्टर में प्रत्येक [पॉड](/docs/concepts/workloads/pods/) को एक वलग क्लस्टर-व्यापी IP एड्रेस मिलता है।
Fix the issue

2025-01-17 16:18 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +* क्लस्टर में प्रत्येक [पॉड](/docs/concepts/workloads/pods/) को एक वलग क्लस्टर-व्यापी IP एड्रेस मिलता है।
Fix the issue

2025-01-17 16:28 UTC, aryasoni98 commented on content/hi/docs/concepts/services-networking/_index.md
> +  * एक सर्विस प्रॉक्सी सर्विस और एंडपॉइंटस्लाइस ऑब्जेक्ट्स को मॉनिटर करता है, और ऑपरेटिंग सिस्टम या क्लाउड प्रोवाइडर API का उपयोग करके डेटा को सर्विस के बैकएंड्स तक पहुंचाता है।
Fxi the issue

2025-01-17 16:53 UTC, niranjandarshann commented
Thanks  LGTM

/lgtm

2025-01-25 01:03 UTC, dipesh-rawat reviewed
/approve

2025-01-25 01:05 UTC, merged