[WIP] Document the new feature `SplitStdoutAndStderr`
kubernetes/website pull request #48405
Opened 2024-10-17 15:27 UTC by knight42

### Description

This is a placeholder PR for the new feature https://github.com/kubernetes/enhancements/issues/3288. I will update the document after the implemention PR get merged.

KEP issue: https://github.com/kubernetes/enhancements/issues/3288
Code (k/k) update PR(s):
* https://github.com/kubernetes/kubernetes/pull/127360

### Issue

2024-10-17 15:28 UTC, knight42 commented
/cc @spurin

2024-10-17 17:40 UTC, sftim reviewed
Ideally, also update https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#examine-pod-logs

2024-10-17 17:40 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates/split-stdout-stderr.md
> +Allow retrieving either stdout or stderr log stream of the given container.
Try this:
```suggestion
Enable fetching specific log streams (either stdout or stderr) from a container's log streams, using the Pod API.
```

2024-10-17 17:41 UTC, sftim commented
/sig node

2024-11-01 12:33 UTC, spurin commented
Hello @knight42 :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday November 19th 2024 18:00 PST. Thank you!

2024-11-08 00:44 UTC, tengqm commented
Looks like the upstream code change has landed.
/lgtm

2024-11-11 16:39 UTC, spurin commented
Hello @knight42 :wave:, 1.32 Docs Shadow here,

A quick reminder to get your PR ready for review before the deadline, Tuesday November 19th at 18:00 PDT. For additional information, refer to: [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review).

Thank you!

2024-11-18 16:03 UTC, haircommander commented
@knight42 is this still a draft or is this ready?

2024-11-19 11:38 UTC, knight42 commented
> Ideally, also update [kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod#examine-pod-logs](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#examine-pod-logs)

Unfortunately the kubectl PR https://github.com/kubernetes/kubernetes/pull/128159 has not been merged yet, I think we'd better update this document later?

2024-11-19 12:38 UTC, tengqm commented
> > Ideally, also update [kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod#examine-pod-logs](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#examine-pod-logs)
> 
> Unfortunately the kubectl PR [kubernetes/kubernetes#128159](https://github.com/kubernetes/kubernetes/pull/128159) has not been merged yet, I think we'd better update this document later?

Yup. We'd better leave this a WIP and see if the upstream PR can be merged.

2024-11-28 22:56 UTC, sftim commented
/retitle Update docs for split stdout / stderr Pod logging

2024-11-28 23:06 UTC, sftim requested changes
Why does this PR add _two_ feature gates?

2024-11-28 23:06 UTC, sftim commented on content/en/docs/concepts/cluster-administration/logging.md
> +`PodLogsQuerySplitStreams` [feature gate](/docs/reference/command-line-tools-reference/feature-gates/) to be enabled.
```suggestion

### Container log streams

{{< feature-state feature_gate_name="PodLogsQuerySplitStreams" >}}

As an alpha feature, the kubelet can split out the logs from the two standard streams produced
by a container: [standard output](https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout))
and [standard error](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)).
To use this behavior, you must enable the `PodLogsQuerySplitStreams`
[feature gate](/docs/reference/command-line-tools-reference/feature-gates/).
```

2024-11-28 23:06 UTC, sftim commented on content/en/docs/concepts/cluster-administration/logging.md
> +In the meantime, you can still use this feature by directly accessing the API.
We prefer to write documentation that is more [timeless](https://developers.google.com/style/timeless-documentation). Try this:
```suggestion
With that feature gate enabled, Kubernetes {{< skew currentVersion >}} allows access to these
log streams directly via the Pod API. You can fetch a specific stream by specifying the stream name (either `Stdout` or `Stderr`),
using the `stream` query string. You must have access to read the `log` subresource of that Pod.
```

2024-11-28 23:06 UTC, sftim commented on content/en/docs/concepts/cluster-administration/logging.md
> +```
We [avoid statements about the future](https://kubernetes.io/docs/contribute/style/style-guide/#avoid-statements-about-the-future) in docs, so:
```suggestion
```

2024-11-28 23:06 UTC, sftim commented on content/en/docs/tasks/debug/debug-application/debug-running-pod.md
> +```
Until there's more support, this advice isn't much use to a reader who wants to troubleshoot a Pod.
```suggestion
```

2024-11-28 23:06 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates/split-stdout-stderr.md
Is this right?

2024-11-28 23:06 UTC, sftim commented
Given the question at https://github.com/kubernetes/website/pull/48405#pullrequestreview-2468866590

/lgtm cancel

/hold

OK to unhold once that question is addressed.

2024-11-29 16:08 UTC, knight42 commented on content/en/docs/reference/command-line-tools-reference/feature-gates/split-stdout-stderr.md
oops... let me remove this file

2024-11-29 16:11 UTC, sftim commented
/hold cancel
/label tide/merge-method-squash

2024-11-29 16:12 UTC, sftim reviewed
LGTM

2024-11-29 16:13 UTC, knight42 commented
> Why does this PR add two feature gates?

Ah, I think one was submitted by mistake, I’ve deleted the incorrect one.

2024-11-29 16:14 UTC, sftim commented
/lgtm
/approve

/hold
You can either:
- squash this to 1 commit (keep the same parent commit, 35e7e1d00c0f15c3124b27f309ddc4ea5764b71c, though)
  and then unhold
- unhold as-is

First option is slightly tidier though.

2024-11-29 16:23 UTC, sftim commented
/lgtm
/hold cancel

2024-11-29 16:24 UTC, sftim commented
/remove-label tide/merge-method-squash

2024-11-29 16:24 UTC, merged