[pt-br] Create docs/concepts/windows
kubernetes/website pull request #48423
Opened 2024-10-18 17:46 UTC by rafaelmaferreira

### Description

### Issue

Closes: #

2024-10-18 18:04 UTC, knabben commented on content/pt-br/docs/concepts/windows/_index.md
> +O Kubernetes oferece suporte a {{< glossary_tooltip text="nodes" term_id="node" >}} de trabalho que executam Linux ou Microsoft Windows.
subsitui `text="nodes"` por `text="nós"`

2024-10-18 18:04 UTC, knabben commented on content/pt-br/docs/concepts/windows/_index.md
> +  O Kubernetes oferece suporte a nodes que executam Microsoft Windows.
nós?

2024-10-18 18:06 UTC, rafaelmaferreira commented on content/pt-br/docs/concepts/windows/_index.md
> +  O Kubernetes oferece suporte a nodes que executam Microsoft Windows.
done

2024-10-18 18:08 UTC, knabben commented on content/pt-br/docs/concepts/windows/_index.md
> +A CNCF e sua empresa-mãe, a Linux Foundation, adotam uma abordagem neutra a fornecedores em relação à compatibilidade. É possível adicionar seu [servidor Windows](https://www.microsoft.com/pt-br/wind
`A CNCF e sua controladora, a Linux Foundation` pode encaixar melhor

2024-10-18 18:10 UTC, knabben commented on content/pt-br/docs/concepts/windows/_index.md
> +* [Rede no Windows](/docs/concepts/services-networking/windows-networking/)
Verificar se já existe uma tradução para a página, 1) colocar o link correto, 2) Verificar se o título é o mesmo traduzido

2024-10-18 18:10 UTC, knabben commented on content/pt-br/docs/concepts/windows/_index.md
> +Ou, para uma visão geral, leia:
Existem dois links abaixo que precisam ser traduzidos também

2024-10-18 19:25 UTC, edsoncelio requested changes

2024-10-18 19:25 UTC, edsoncelio commented on content/pt-br/docs/concepts/windows/_index.md
> +O Kubernetes oferece suporte a {{< glossary_tooltip text="nós" term_id="nós" >}} de trabalho que executam Linux ou Microsoft Windows.
`term_id` é um identificador que se refere a um item do glossário (e esse id se mantém o original mesmo com termo localizado), pode manter o original.

2024-10-18 19:25 UTC, edsoncelio commented on content/pt-br/docs/concepts/windows/_index.md
> +Se você estiver usando nodes Windows, pode ler:
node -> nós
Tem algumas outras referências a `node` pelo texto ainda.

2024-10-18 19:25 UTC, edsoncelio commented on content/pt-br/docs/concepts/windows/_index.md
> +A CNCF e sua controladora, a Linux Foundation, adotam uma abordagem neutra a fornecedores em relação à compatibilidade. É possível adicionar seu [servidor Windows](https://www.microsoft.com/pt-br/win
Não acho que o termo `controladora` ficou muito bom, talvez algo como `entidade mantenedora`? 

O que acha @knabben ?

2024-10-18 20:00 UTC, knabben commented on content/pt-br/docs/concepts/windows/_index.md
> +A CNCF e sua controladora, a Linux Foundation, adotam uma abordagem neutra a fornecedores em relação à compatibilidade. É possível adicionar seu [servidor Windows](https://www.microsoft.com/pt-br/win
realmente não sei qual o termo legal, já que é um projeto da Linux Foundation.

Algo como "parent organization" = organização-mãe?

2024-10-21 13:27 UTC, edsoncelio commented on content/pt-br/docs/concepts/windows/_index.md
> +Ou, para uma visão geral, leia:
@rafaelmaferreira poderia adicionar os links faltantes?

2024-10-23 22:38 UTC, edsoncelio commented
/lgtm
PTAL @knabben

2024-10-23 22:38 UTC, edsoncelio commented on content/pt-br/docs/concepts/windows/_index.md
> +Ou, para uma visão geral, leia:
@knabben no arquivo .md não existem esses links (olhei até no original e realmente não tem).

2024-10-23 23:59 UTC, knabben commented
/lgtm
/label tide/merge-method-squash

2024-10-23 23:59 UTC, knabben commented
/label tide/merge-method-squash

2024-10-24 00:44 UTC, edsoncelio commented
/approve

2024-10-24 00:46 UTC, merged