KEP-3257 (Cluster Trust Bundles) docs placeholder
kubernetes/website pull request #48492
Opened 2024-10-22 09:10 UTC by stlaz

### Description

This is a placeholder for KEP-3257 Cluster Trust Bundles

### Issue

Related to: https://github.com/kubernetes/enhancements/issues/3257

2024-11-01 12:20 UTC, spurin commented
Hello @stlaz :wave: please take a look at [Documenting for a release - PR Ready for Review](https://kubernetes.io/docs/contribute/new-content/new-features/#pr-ready-for-review) to get your PR ready for review before Tuesday November 19th 2024 18:00 PST. Thank you!

2024-11-15 11:24 UTC, sftim commented
/retitle Document kubernetes.io/kube-apiserver-serving ClusterTrustBundle signer

2024-11-15 11:27 UTC, sftim reviewed
Some feedback

2024-11-15 11:29 UTC, sftim commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +       below.
- Can you clarify who or what organization deprecated the _Subject_ field?
- Either expand SAN, or add a glossary entry for subject alternative name and use a tooltip. Some people might think it's about storage.

2024-11-25 09:41 UTC, stlaz commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +    1. CA bit allowed/disallowed - not recommended.
I think so. I tried to stay consistent with the concise style used with the other signers.

2024-11-25 09:42 UTC, stlaz commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +    1. Permitted x509 extensions - honors subjectAltName and key usage extensions. At
Should I change this in all the other signers, too? I can do that in a separate commit.

2024-11-25 09:46 UTC, stlaz commented on content/en/docs/reference/command-line-tools-reference/feature-gates/cluster-trust-bundle.md
> +signer.
That would be true for any other API object, correct? Should I add a link to docs explaining how to enable alpha APIs?

2024-11-25 10:55 UTC, stlaz commented
Thank you @sftim for the review. I addressed your comments, I had additional questions with some of them.

2024-11-25 11:21 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates/cluster-trust-bundle.md
> +signer.
We don't have a doc to link to, so you'll need to explain it here (briefly).

2024-11-25 11:21 UTC, sftim commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +    1. Permitted x509 extensions - honors subjectAltName and key usage extensions. At
Ah, if they're all like this, let's skip it. We can fix it for beta graduation.

2024-11-27 12:31 UTC, sftim commented on content/en/docs/reference/glossary/san.md
> +  identities to be bound to the subject of the certificate.
```suggestion
  Modern way to identify what hostname or IP address an X.509 certificate applies to.
```

2024-11-27 12:32 UTC, sftim commented on content/en/docs/reference/glossary/san.md
> +The standard defines identities represented as an email address, a DNS name, an
```suggestion
The [standard](https://datatracker.ietf.org/doc/html/rfc4985) defines identities represented as
either an email address, a DNS name, an
```

2024-11-27 12:32 UTC, sftim commented on content/en/docs/reference/glossary/san.md
> +IP address or a Unified Resource Identifier (URI).
```suggestion
IP address or a Uniform Resource Identifier (URI).
```

2024-11-27 12:35 UTC, sftim commented on content/en/docs/reference/command-line-tools-reference/feature-gates/cluster-trust-bundle.md
> +[the kube-apiserver --runtime-config flag](/docs/tasks/administer-cluster/enable-disable-api/).
Even better:
```suggestion

In order to use the ClusterTrustBundle API in your cluster, you need to enable this feature gate
and also [enable](/docs/tasks/administer-cluster/enable-disable-api/) the associated alpha API group,
using the `--runtime-config` command line argument to kube-apiserver.
```

2024-11-27 12:36 UTC, sftim commented
LGTM for docs (even with pending feedback)
We should try to get a technical review on this change as well.

2024-11-27 12:48 UTC, stlaz commented
Thank you for the review, I applied your suggestions, modifying some slightly.

@enj @ahmedtd would you please do the technical review?

2025-01-14 21:11 UTC, enj reviewed
Minor comments, LGTM.

2025-01-15 16:07 UTC, benjaminapetersen commented
/assign @enj

2025-01-20 13:50 UTC, stlaz commented on content/en/docs/reference/command-line-tools-reference/feature-gates/cluster-trust-bundle.md
> +Enable ClusterTrustBundle support, including kubelet integration. Also makes the Kubernetes
Also, I just realized the mention of kubelet is likely all wrong here, I'll remove that. The ClusterTrustBundleProjection FG controls the availability of the pod fields AFAIK.

2025-01-31 00:33 UTC, sftim commented
@stlaz is this targeting the right branch? Kubernetes v1.32 is released, so I imagine you want to target _main_.

2025-01-31 14:29 UTC, stlaz commented
Indeed, this was created for 1.32 originally but that's now main. Switched to the correct one, I'll fix the merge conflicts to make the PR mergeable again.

2025-06-24 15:51 UTC, stlaz commented
/hold cancel

2025-06-24 15:52 UTC, enj commented
/milestone 1.33

2025-06-24 19:42 UTC, enj requested changes
Another pass.

2025-06-24 19:42 UTC, enj commented on content/en/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundle.md
> +Used from the kube-apiserver, it enables ClusterTrustBundle support.
Need the feature gate on the kubelet to use the volume right?

2025-06-24 19:42 UTC, enj commented on content/en/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundle.md
>      fromVersion: "1.27"
Need to add beta details?

2025-06-25 11:09 UTC, stlaz commented on content/en/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundle.md
> +Used from the kube-apiserver, it enables ClusterTrustBundle support.
Yes, that's documented elsewhere. This FG only controls the API and the signer.

2025-06-25 11:09 UTC, stlaz commented on content/en/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundle.md
>      fromVersion: "1.27"
Rebased to get this from the current main.

2025-07-23 07:40 UTC, stlaz commented
@lmktfy would you be the right person from sig-docs for a final review?

2025-07-23 21:44 UTC, ahmedtd commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +    1. Permitted subjects - "Subject" itself is deprecated for TLS server authentication by RFC2818. However,
I'm confused --- there's no automated signing at all for this signer, right?  Shouldn't we only document the trust anchor distribution?

2025-07-24 07:19 UTC, stlaz commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +    1. Permitted subjects - "Subject" itself is deprecated for TLS server authentication by RFC2818. However,
There is no automated signing but we should still document it as any other in-tree signer, including the expectations we've got for the certificates it signs.

2025-08-20 08:28 UTC, stlaz commented
/close
Looks like this PR just was not in people's review loops, let's merge it as a part of https://github.com/kubernetes/website/pull/51487

2026-04-27 13:18 UTC, stlaz commented
/reopen
https://github.com/kubernetes/website/pull/51487 was abandoned, reopening.

2026-04-27 13:20 UTC, stlaz commented
@enj @lmktfy please take a look if you'd be so good. I think the PR was almost good for merging before I closed it.

2026-04-27 20:57 UTC, lmktfy reviewed
/lgtm

Nits, but merging this as-is will make the docs better.

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/command-line-tools-reference/feature-gates/ClusterTrustBundle.md
> +for the `kubernetes.io/kube-apiserver-serving` signer.
We keep these descriptions short; most are one paragraph.

```suggestion
Enable use of [ClusterTrustBundles](/docs/reference/access-authn-authz/certificate-signing-requests/#cluster-trust-bundles).

If this feature gate is enabled for the kube-controller-manager, the control plane automatically publishes a ClusterTrustBundle
for the `kubernetes.io/kube-apiserver-serving` signer.

In order to use the ClusterTrustBundle API in your cluster, you need to enable this feature gate
and also [enable](/docs/tasks/administer-cluster/enable-disable-api/) the associated alpha API group.
```

We might one day render details of what components support a feature gate, but:
- if we do, that'll be autogenerated
- outside of a configuration rollout, the Kubernetes project recommends setting a given feature gate enabled or disabled across your entire cluster

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/glossary/san.md
> +extension that allows identities to be bound to the subject of the certificate.
Better:
```suggestion
An {{< glossary_tooltip text="X.509 certificate" term_id="certificate" >}}
extension that allows identities to be bound to the subject of the certificate.
```

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/glossary/san.md
> +extension that allows identities to be bound to the subject of the certificate.
This is better because we have a shortcode that allows you to turn this into (eg):
- A _subject alternative name_ is **an X.509 certificate extension that allows identities to be bound to the subject of the certificate.**

Our shortcode allows prefixing, but it doesn't support chopping bits off.

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +       from the "Permitted x509 extensions" section below.
Is this right?
```suggestion
       from the _permitted X.509 extensions_ section that follows this one.
```

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +       least one DNS or IP subjectAltName must be present. The SAN DNS/IP of the certificates
```suggestion
    1. Permitted X.509 extensions - honors `subjectAltName` and key usage extensions. At
       least one DNS or IP `subjectAltName` must be present. The SAN DNS name or IP address
       of the certificate(s)
```

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +       must resolve/point to kube-apiserver's hostname/IP.
```suggestion
       **must** resolve/point to an hostname or IP address of a kube-apiserver.
```
?

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +    1. CA bit allowed/disallowed - not recommended by the Kubernetes project.
```suggestion
    1. CA bit allowed/disallowed - setting the CA bit is possible, but the Kubernetes project recommends you do **not** set it.
```

2026-04-27 20:57 UTC, lmktfy commented on content/en/docs/reference/access-authn-authz/certificate-signing-requests.md
> +    1. Permitted subjects - "Subject" itself is deprecated for TLS server authentication by RFC2818. However,
```suggestion
    1. Permitted subjects - _Subject_ itself is deprecated for TLS server authentication by RFC2818. However,
```

2026-05-06 17:18 UTC, dipesh-rawat reviewed
/approve

@stlaz Thanks for the update. Please feel free to open a follow up PR to address the remaining review comments whenever convenient.

2026-05-06 17:20 UTC, merged