Created pt-br translated file
kubernetes/website pull request #48508
Opened 2024-10-23 01:33 UTC by yannkistenmacker

### Description
Create document file for install kubectl on macOS

### Issue
https://github.com/kubernetes/website/issues/48278

2024-10-24 01:06 UTC, edsoncelio commented
/retitle [pt-br] Add content/pt-br/docs/tasks/tools/included/install-kubectl-macos.md

2024-10-31 18:04 UTC, stormqueen1990 reviewed
Olá, @yannkistenmacker! Obrigada pela sua contribuição!

O motivo da falha do build é o local onde o arquivo foi criado. Poderias corrigir isso para que tenhamos o preview correto?

Volto para dar outra olhada assim que isso for corrigido!

Obrigada!

2024-10-31 18:04 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/included/install-kubectl-macos.md
Este arquivo foi criado no caminho incorreto, por isso a falha no processo de build. O caminho correto seria na pasta `content/pt-br/docs/tasks/tools`. Poderia efetuar a correção?

2024-10-31 18:04 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/included/install-kubectl-macos.md
> +- mikedanese
Estas duas linhas podem ser removidas.

2024-11-02 12:45 UTC, yannkistenmacker commented on content/pt-br/docs/tasks/tools/included/install-kubectl-macos.md
Olá, corrigi o caminho do arquivo.

2024-11-02 12:45 UTC, yannkistenmacker commented on content/pt-br/docs/tasks/tools/included/install-kubectl-macos.md
> +- mikedanese
Linhas removidas com sucesso.

2024-11-03 00:24 UTC, edsoncelio requested changes
Obrigado pela contribuição!
Deixei alguns comentários, se ficar alguma dúvida, só falar!

2024-11-03 00:24 UTC, edsoncelio commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +  - [Instalar com Homebew no macOS](#instalar-com-homebrew-no-macos)
```suggestion
  - [Instalar com Homebrew no macOS](#instalar-com-homebrew-no-macos)

```

2024-11-03 00:24 UTC, edsoncelio commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +  - [Instalar `kubectl convert` plugin](#instalar-kubectl-convert-plugin)
```suggestion
  - [Instalar o plugin `kubectl convert`](#instalar-kubectl-convert-plugin)

```

2024-11-03 00:24 UTC, edsoncelio commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +   Se a houver falha na validação, `shasum` ele retornará uma saída diferente de zero semelhante a:
```suggestion
   Se a houver falha na validação, o `shasum` vai retornar uma saída diferente de zero semelhante a:

```

2024-11-03 00:24 UTC, edsoncelio commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +1. Movendo o binário do kubectl para um diretório do seu sistema `PATH`.
```suggestion
1. Movendo o binário do kubectl para um diretório que esteja no `PATH` do seu sistema.

```

2024-11-03 00:24 UTC, edsoncelio commented on content/pt-br/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +### Upgrade Bash
Pode dar uma olhada daqui em diante? Parece que o conteúdo não foi traduzido.

2024-11-03 00:24 UTC, edsoncelio commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +### Desinstalar kubectl no macOS
```suggestion
### Desinstalar o kubectl no macOS

```

2024-11-03 01:26 UTC, yannkistenmacker commented on content/pt-br/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
> +### Upgrade Bash
Esse arquivo acabou subindo errado, eu peguei pra traduzir recentemente. Ele complementa uma das instruções referente a configuração do Bash.

2024-11-03 20:20 UTC, yannkistenmacker commented
Vou subir junto esse arquivo que fica no path /pt-br/docs/tasks/tools/included pois aparentemente o build está quebrando por ele não estar conseguindo encontra-lo e essa doc carrega ele na página.

2024-11-05 20:49 UTC, stormqueen1990 commented
/retitle [pt-br] Add docs/tasks/tools/install-kubectl-macos

2024-11-05 21:23 UTC, stormqueen1990 reviewed
Olá @yannkistenmacker! Muito obrigada pela tua contribuição! 🙏🏻

Encontrei alguns pontos que precisam ser ajustados. Se tiveres dúvidas ou discordares de algum ponto da revisão, não hesita em me contatar no canal `#kubernetes-docs-pt` do Slack do Kubernetes.

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +  - [Instalar o plugin `kubectl convert`](#instalar-kubectl-convert-plugin)
Estas âncoras estão quebradas no momento. Existem duas formas de corrigir:
1. O valor da âncora precisa ser exatamente igual ao título (exemplo: `#instalar-o-binário-do-kubectl-com-o-curl-no-macos`). Tu podes pegar esse texto do preview da página, ou rodar o Hugo local e copiar as âncoras do documento através do link gerado no título.
2. Adicionar o valor que tu utilizaste no link como uma âncora manual, via markdown, ao lado do título. Exemplo: https://github.com/kubernetes/website/blob/ae197690de7fee20f4e5a506da76a4605e105e83/content/pt-br/docs/concepts/architecture/controller.md#L91

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +
```suggestion
   Para baixar uma versão específica, substitua a parte `$(curl -L -s https://dl.k8s.io/release/stable.txt)`
   do comando com a versão específica da versão.


```

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +1. Validando o binário (opcional).
O texto original usa o modo imperativo. É preferível manter o imperativo aqui também.

```suggestion
1. Valide o binário (opcional).

```

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +   Validando o binário do kubectl com o arquivo de checksum:
```suggestion
   Valide o binário do kubectl com o arquivo de checksum:

```

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +1. Tornando o binário do kubectl executável.
```suggestion
1. Torne o binário do kubectl executável.

```

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +1. Movendo o binário do kubectl para um diretório que esteja no `PATH` do seu sistema.
```suggestion
1. Mova o binário do kubectl para um diretório que esteja no `PATH` do seu sistema.

```

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +   Tenha certeza que `/usr/local/bin` está configurado na sua variável de ambiente PATH.
Embora aqui o texto original use "make sure", tenha certeza não me soa tão natural. O que tu achas de usar "confira" ou "confirme" no lugar?

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +## Verificar ajustes do kubectl
Uso do imperativo aqui também. Não entendi porquê usar "ajustes" aqui no lugar de configuração. Algum motivo específico?

```suggestion
## Verifique a configuração do kubectl

```

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +## Plugins e ajustes opcionais do kubectl
Esta seção já tem um precedente de localização na página https://github.com/kubernetes/website/blob/8a89acca5b55d514fbc2c52bc65cdf267f4ab9fd/content/pt-br/docs/tasks/tools/install-kubectl-linux.md. Seria legal manter mais ou menos a mesma redação para fins de consistência. Notei que o nome da ferramenta "bash-completion" foi traduzido, mas não deveria.

2024-11-05 21:23 UTC, stormqueen1990 commented on content/pt-br/docs/tasks/tools/included/optional-kubectl-configs-bash-mac.md
Temos um precedente de localização deste texto em https://github.com/kubernetes/website/blob/defe7331b93238e024cdba590d57f2773ea9253d/content/pt-br/docs/tasks/tools/included/optional-kubectl-configs-bash-linux.md. Seria legal manter a consistência de redação onde possível entre essas duas páginas.

2024-11-06 15:51 UTC, yannkistenmacker commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +   Tenha certeza que `/usr/local/bin` está configurado na sua variável de ambiente PATH.
Ótima sugestão, irei alterar aqui.

2024-11-06 15:54 UTC, yannkistenmacker commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +## Verificar ajustes do kubectl
Alterei por ajustes pois a palavra "configuração" não estava permitindo a ancora localizar o tópico.

2024-11-06 15:57 UTC, yannkistenmacker commented on content/pt-br/docs/tasks/tools/install-kubectl-macos.md
> +## Verificar ajustes do kubectl
Alterei para configuração ^^

2024-11-13 11:39 UTC, edsoncelio commented
Thanks!
/lgtm

2024-11-16 19:44 UTC, yannkistenmacker commented
@stormqueen1990 @jcjesus

2024-11-18 21:43 UTC, stormqueen1990 reviewed
/approve

2024-11-18 21:44 UTC, merged