[es] Added content content/es/docs/tasks/run-application/access-api-from-pod #45316
kubernetes/website pull request #48549
Opened 2024-10-26 02:21 UTC by h3ct0rjs

/kind feature
/language es
/sig docs
/area localization

/assign @ramrodo 
resolves #45316

2024-11-05 04:49 UTC, electrocucaracha requested changes
Buen trabajo @h3ct0rjs, he hecho algunas observaciones que considero necesarias para que ayuden a mejorar la lectura.

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +Esta guía demuestra cómo acceder a la API de Kubernetes desde dentro de un pod.
```suggestion
Esta guía muestra como acceder a la API de Kubernetes desde de un Pod.
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +## Accediendo a la API desde dentro de un Pod
```suggestion
## Accediendo a la API desde de un Pod
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +en el servidor de la API es ligeramente diferente al caso de un cliente externo.
```suggestion
El acceder a la API desde de un Pod, la ubicacion y autentication
del servidor de la API es ligeramente diferente que en el caso de un cliente externo.
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +La forma más fácil de usar la API de Kubernetes desde un Pod es utilizar
```suggestion
La forma más fácil de usar la API de Kubernetes desde un Pod es utilizando
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +bibliotecas pueden descubrir automáticamente el servidor de la API y autenticarse.
```suggestion
bibliotecas pueden automáticamente descubrir el servidor de la API y autenticarse.
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +Desde dentro de un POD, las formas recomendadas de conectarse a la API de Kubernetes son:
```suggestion
Desde un Pod, las formas recomendadas de conectarse a la API de Kubernetes son:
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +- Para un cliente de Go, utiliza la
```suggestion
- Para un cliente de Go, utilice la
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +  y la autenticación. Ver [un ejemplo aqui](https://git.k8s.io/client-go/examples/in-cluster-client-configuration/main.go).
```suggestion
  y la autenticación. Vea [un ejemplo aqui](https://git.k8s.io/client-go/examples/in-cluster-client-configuration/main.go).
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +- Para un cliente de Python, utiliza la
```suggestion
- Para un cliente de Python, utilice la
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +  [biblioteca oficial de cliente Python](https://github.com/kubernetes-client/python/).
```suggestion
  [biblioteca oficial del cliente de Python](https://github.com/kubernetes-client/python/).
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +  [biblioteca oficial de cliente Go](https://github.com/kubernetes/client-go/).
```suggestion
  [biblioteca oficial del cliente de Go](https://github.com/kubernetes/client-go/).
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +  del host de la API y la autenticación. Ver [un ejemplo aqui](https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py).
```suggestion
  del host de la API y la autenticación. Vea [un ejemplo aqui](https://github.com/kubernetes-client/python/blob/master/examples/in_cluster_config.py).
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +- Existen varias bibliotecas disponibles, por favor consulta la pagina de
```suggestion
- Existen varias bibliotecas disponibles, por favor consulte la página de
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +  [Bibliotecas de Cliente](/docs/reference/using-api/client-libraries/).
```suggestion
  [Bibliotecas de Clientes](/docs/reference/using-api/client-libraries/).
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +Al ejecutarse en un Pod, tu contenedor puede crear una URL HTTPS para el servidor
```suggestion
Al ejecutarse en un Pod, su contenedor puede crear una URL HTTPS para el servidor
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +`default`, de modo que los pods pueden hacer referencia a `kubernetes.default.svc`como
```suggestion
`default`, de modo que los pods pueden hacer referencia a `kubernetes.default.svc` como
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +Por defecto, un poc esta asociado con una cuenta de servicio,
```suggestion
Por defecto, un Pod esta asociado con una cuenta de servicio,
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +Finalmente, el espacio de nombres predeterminado para ser utilizado en las operaciones de API
```suggestion
Finalmente, el Namespace default puede ser utilizado en las operaciones de API
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +con ámbito de espacio de nombres se coloca en un archivo en la ruta `/var/run/secrets/kubernetes.io/serviceaccount/namespace`
```suggestion
con ámbito de espacio de nombres que se colocan en un archivo con la ruta `/var/run/secrets/kubernetes.io/serviceaccount/namespace`
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +### Using kubectl proxy
```suggestion
### Usando kubectl proxy
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +# Point to the internal API server hostname
```suggestion
# Apunta al nombre del host del servidor de la API interno
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +# Path to ServiceAccount token
```suggestion
# Ruta del token de ServiceAccoun
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +# Read this Pod's namespace
```suggestion
# Lectura del Namespace del Pod
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +# Read the ServiceAccount bearer token
```suggestion
# Lectura del bearer token del ServiceAccount
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +# Reference the internal certificate authority (CA)
```suggestion
# Referencia a la autoridad de certificación interna (CA)
```

2024-11-05 04:49 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +# Explore the API with TOKEN
```suggestion
# Explora la API con TOKEN
```

2024-11-06 19:36 UTC, h3ct0rjs commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +## Accediendo a la API desde dentro de un Pod
@electrocucaracha esto si se lee en espanol, se leee un poco raro , podria ser mejor 

`Accediendo a la API desde un Pod` 
opiniones ?

2024-11-06 19:37 UTC, h3ct0rjs commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +# Path to ServiceAccount token
organizare este localmente.

2024-11-06 19:45 UTC, Fojlayrabbiy approved these changes

2024-11-06 19:56 UTC, h3ct0rjs commented
@electrocucaracha deberia squashear todos los commits, o se realiza al momento de hacer esto a la rama por defecto ?

2024-11-06 20:32 UTC, electrocucaracha commented
> @electrocucaracha deberia squashear todos los commits, o se realiza al momento de hacer esto a la rama por defecto ?

Hay una [opción](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request) para agregar las sugerencias en una lista (batch)

2024-11-06 20:46 UTC, electrocucaracha reviewed
Solo un par de cambios más para que coincidan con los párrafos en inglés

2024-11-06 20:46 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +el nombre DNS para el servidor de la API local.
```suggestion
Al ejecutarse en un Pod, su contenedor puede crear una URL HTTPS para el servidor de la API de Kubernetes
obteniendo las variables de entorno `KUBERNETES_SERVICE_HOST`y `KUBERNETES_SERVICE_PORT_HTTPS`.
La dirección del servidor de la API dentro del clúster también se publica
en un Servicio llamado `kubernetes` en el namespace `default`, de modo que los pods pueden hacer referencia a
`kubernetes.default.svc` como el nombre DNS para el servidor de la API local.
```

2024-11-06 20:46 UTC, electrocucaracha commented on content/es/docs/tasks/run-application/access-api-from-pod.md
> +de cada contenedor
```suggestion
Finalmente, el Namespace default puede ser utilizado en las operaciones de API con ámbito de espacio de nombres que se colocan en un archivo
con la ruta `/var/run/secrets/kubernetes.io/serviceaccount/namespace` de cada contenedor
```

2024-11-06 21:08 UTC, h3ct0rjs commented
Creo que con los ultimos cambios estamos bien. Hay algun otro issue en el que puede trabajar que creas que tenga una prioridad en la docu de espanol ?

2024-11-06 21:28 UTC, electrocucaracha commented
> Creo que con los ultimos cambios estamos bien. Hay algun otro issue en el que puede trabajar que creas que tenga una prioridad en la docu de espanol @electrocucaracha ?

Sería cuestión de checar el dashboard que se tiene. 

/lgtm
/cc @ramrodo @krol3

2024-11-07 21:55 UTC, ramrodo commented
/approve

2024-11-07 21:56 UTC, merged

2024-11-07 21:56 UTC, ramrodo commented
> Creo que con los ultimos cambios estamos bien. Hay algun otro issue en el que puede trabajar que creas que tenga una prioridad en la docu de espanol @electrocucaracha ?

Hola @h3ct0rjs , claro, en este documento colocamos los diferentes issues que están disponibles para traducir. Revisa las notas de la reunión del 5-Nov-24 para que puedas elegir un issue de esa lista:

https://docs.google.com/document/d/1jOTK1tqBRwlNQJUB88wfDnGxpdInxMJ7lIFDZy9cMGY/edit?tab=t.0