Bump Docsy to 0.6.x
kubernetes/website pull request #48724
Opened 2024-11-14 20:35 UTC by sftim

This PR upgrades to a newer version of Docsy: 0.6.0

In the testing I've done, I haven't found any different look or behavior that still needs fixing.

/area web-development

This PR incorporates the commits from PRs:
- #48721
- #48722
- #48723

2024-11-16 08:50 UTC, Arhell reviewed
/lgtm

2025-01-07 10:19 UTC, lhajouji approved these changes
i'm relatively new to the community, but i've checked every aspect ( even DeadLinks ) of the new version and LGTM.

2025-01-08 16:53 UTC, salaxander commented
/approve

2025-01-09 11:42 UTC, chalin requested changes
Visit the following preview doc page https://deploy-preview-48724--kubernetes-io-main-staging.netlify.app/docs/contribute/style/diagram-guide/#example-2-ingress and you'll see that the "Code block" is rendered as a mermaid diagram rather than raw code, as it is [rendered currently](https://kubernetes.io/docs/contribute/style/diagram-guide/#example-2-ingress):

> <img width="715" alt="image" src="https://github.com/user-attachments/assets/fbd9ebde-84e5-4222-b9ff-d8374abf6363" />

This is because the code-block language is set to `mermaid` and as of Docsy 0.6.0 such code blocks are rendered as Mermaid diagrams (without the need to use `{{<mermaid}}`). We need to set the code-block language to `text`.

The same is true of `content/zh-cn/docs/contribute/style/diagram-guide.md`.

2025-01-09 11:43 UTC, chalin commented
@sftim @nate-double-u - does `make container-image` work for you?

2025-01-09 12:19 UTC, chalin requested changes

2025-01-09 12:20 UTC, chalin commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
Probably best to run the following after accepting the change suggested above:

```console
$ rm -rf node_modules package-lock.json
$ npm install
```

2025-01-09 12:38 UTC, sftim commented
Hmm. Not sure that https://deploy-preview-48724--kubernetes-io-main-staging.netlify.app/docs/contribute/style/diagram-guide/#example-2-ingress is rendering right after my changes.

2025-01-09 12:40 UTC, sftim commented
Before adding LGTM, see https://github.com/kubernetes/website/pull/48724#issuecomment-2580056205

2025-01-09 15:46 UTC, chalin commented
> Hmm. Not sure that https://deploy-preview-48724--kubernetes-io-main-staging.netlify.app/docs/contribute/style/diagram-guide/#example-2-ingress is rendering right after my changes.

It appears to be rendering properly now:

> <img width="555" alt="image" src="https://github.com/user-attachments/assets/286cc15f-a3be-483a-978c-27e091686e1c" />

What appears off to you?

2025-01-09 15:53 UTC, chalin reviewed
@sftim - can you also fix `content/zh-cn/docs/contribute/style/diagram-guide.md` by changing <code>\`\`\`mermaid</code> to <code>\`\`\`text</code>, since it requires the same fix as the English page: https://deploy-preview-48724--kubernetes-io-main-staging.netlify.app/zh-cn/docs/contribute/style/diagram-guide/#%E7%A4%BA%E4%BE%8B-2-ingress

2025-01-09 16:24 UTC, chalin commented
Btw, my previous LGTM of this PR is for the _minimal changes_ it introduced in support of bumping up the version of Docsy to 0.6.x -- this is done is in the "minimalist" spirit of #44002. In particular, the Docsy 0.6.x Mermaid enhancements are _not_ being integrated here. I'm assuming that this will be done later in scope of #41171.

2025-01-09 16:33 UTC, sftim commented
We're all for minimal useful changes and small reviewable PRs.

2025-01-09 16:44 UTC, sftim commented
After this merges, let's try to tidy up our use of Mermaid and align it to what upstream Docsy recommends.

2025-01-10 19:43 UTC, nate-double-u commented
> @sftim @nate-double-u - does `make container-image` work for you?

Yes, it does (going through the same submodule management process I had to go through [for your PR]https://github.com/kubernetes/website/pull/48812))

```
make module-init # this will throw an error

pushd api-ref-generator && git fetch --unshallow && popd

make module-init # this will work now we've done the full clone

make container-image

make container-serve
```

2025-01-13 09:26 UTC, SayakMukhopadhyay commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
I am wondering what is causing the issue in the website. In the contribex site, I use `"docsy": "github:google/docsy#semver:0.5.1",` (see https://github.com/kubernetes/contributor-site/blob/ec62acc3e77e708c7e85486be34c07a2bf9a4c4e/package.json#L7) which works well. The above uses the commit https://github.com/google/docsy/commit/f27daed90073fb74ca3afdc0250910abcfaa6bea from Docsy (which doesn't include the `+1` patch you added in 0.5.1.

I am asking so that I can incorporate this change in the contribex site too.

2025-01-13 09:42 UTC, SayakMukhopadhyay commented
A few points and nits

1. Do we need to set text blocks as \`\`\`text ? Just keeping \`\`\` should be enough. But I can understand if its for verbosity.
> Hmm. Not sure that https://deploy-preview-48724--kubernetes-io-main-staging.netlify.app/docs/contribute/style/diagram-guide/#example-2-ingress is rendering right after my changes.
2. @sftim The mermaid blocks were not rendering for me, either in container or in a local build. I got the following error
![image](https://github.com/user-attachments/assets/41496951-ccbf-45b5-b280-20281f102c64)
> Failed to find a valid digest in the 'integrity' attribute for resource 'http://localhost:1313/js/mermaid-10.6.1.min.js' with computed SHA-384 integrity 'toDgDinNQVuBBJdT9Q9AnvM4szGg0g7BSEy/yLPRkkQylpeePcz8Mx/JLOFf33o+'. The resource has been blocked.

It seems like the issue lies in https://github.com/kubernetes/website/blob/646396c7751b7cd87813a625c96c8c84be89da60/layouts/partials/hooks/head-end.html#L31 which uses a wrong integrity hash. Changing the hash to the one expected by the browser gets the mermaid diagrams to render properly. The tricky questions are:
  1. How was this working until now?
  2. Why does the netlify deployment still work whereas locally the issue crops up.
  3. Is it only happening on my system or is this reproducible?
  
Apart from this I have this related question (https://github.com/kubernetes/website/pull/48724#discussion_r1912888732) but otherwise the PR is fine.

2025-01-13 09:49 UTC, sftim commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
`0.6.x` seems like a more sensible specification to use. Previously I think I had a stale `package-lock.json`

2025-01-13 10:11 UTC, SayakMukhopadhyay commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
The thing is that `#v0.6.x` pulls `0.6.0+1`whereas `#semver:^0.6.0` doesn't. Still, I am wondering why 0.6.0 works in the contribex-site but doesn't in the website and it has to be `0.6.0+1`. I can see that it has to be something related to hugo being a dev dependency but I have not yet figured out what.

2025-01-13 11:00 UTC, sftim commented
I think the Mermaid part might need more work. That's a shame. C'est la vie.

2025-01-13 11:02 UTC, SayakMukhopadhyay commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
Alright, did some testing and found that the `container-image` target was not working cause docsy had a dev dependency on hugo which itself needs `gcompat` to be installed. The contribex-project had this dependency for a while now (see https://github.com/kubernetes/contributor-site/blob/ec62acc3e77e708c7e85486be34c07a2bf9a4c4e/Dockerfile#L13) which is why it worked.

My suggestion would be to use docsy 0.6.0 (and not 0.6.0+1) and instead add `gcompat` via apk.

@chalin wrt Docsy, my suggestion would be to put Hugo under `peerDependencies` as peer dependencies do not get installed automatically but can be installed if required using the `--save-peer` flag. This is the how npm recommends.

2025-01-13 11:04 UTC, SayakMukhopadhyay commented
> I think the Mermaid part might need more work. That's a shame. C'est la vie.

You can get the mermaid to work by changing the integrity hash in the mermaid library that is getting imported. At least until we remove the shortcode and convert all mermaid diagrams to use code fencing.

2025-01-13 11:05 UTC, sftim commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
@SayakMukhopadhyay would you be willing to file an issue against upstream [Docsy](https://github.com/google/docsy) about the Hugo peer dependency?

2025-01-13 11:07 UTC, sftim commented
@SayakMukhopadhyay if you'd like to, you're very welcome to take over this PR - feel free to make your own local branch and cherry pick any useful commit.

I've more K8s WIP than I've capacity to look after; I've been leading on the Docsy upgrade partly because _at the time_ nobody else was working on it. I get the sense you could easily get this one over the line; also, if you send in a PR and it looks good, I can LGTM it.

2025-01-13 11:11 UTC, SayakMukhopadhyay commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
Yeah, of course. I have pinged chalin here but I will also raise it in their repo.

2025-01-13 11:13 UTC, SayakMukhopadhyay commented
> @SayakMukhopadhyay if you'd like to, you're very welcome to take over this PR - feel free to make your own local branch and cherry pick any useful commit from this one.
> 
> I've more K8s WIP than I've capacity to look after; I've been leading on the Docsy upgrade partly because _at the time_ nobody else was working on it. I get the sense you could easily get this one over the line; also, if you send in a PR and it looks good, I can LGTM it.

Yeah, I can give it a go but I hope I am not stepping on any toes.

2025-01-13 11:46 UTC, SayakMukhopadhyay commented on package.json
> +    "docsy": "github:google/docsy#v0.6.0",
Created https://github.com/google/docsy/issues/2171

2025-01-13 19:39 UTC, sftim commented
Closing in favor of https://github.com/kubernetes/website/pull/49416

/close

2025-01-13 19:39 UTC, closed without merging

2025-01-13 22:39 UTC, chalin commented
@sftim et all: why was this PR closed? It was a valid and fully functional update to Docsy 0.6.x, with Mermaid diagrams correctly rendering, ready to be merged.

It was also understood that any further Mermaid compatibility issues would be handled in a followup PR, as Tim wrote:

> After this merges, let's try to tidy up our use of Mermaid and align it to what upstream Docsy recommends.

2025-01-13 22:51 UTC, sftim commented
When I checked this, I wasn't seeing the Mermaid diagrams rendering correctly across all browsers; some pages did look OK in some browsers, but that wasn't enough for me to think it was good to merge. Also, I'm very happy for @SayakMukhopadhyay - or anyone else - to pick up the baton.

We need to at least not break Mermaid vs. the existing experience.