[ja]docs/concepts/security/security-checklist.md #47547
kubernetes/website pull request #48744
Opened 2024-11-17 15:01 UTC by luna029

### Description
Translated content/en/docs/concepts/security/security-checklist.md into Japanese.
The following Open Issues have been addressed https://github.com/kubernetes/website/issues/47547

### Issue
https://github.com/kubernetes/website/issues/47547

Closes: #

2024-11-17 15:45 UTC, dipesh-rawat commented on content/ja/docs/concepts/security/security-checklist.md
> +{{< /caution >}}
The tag here needs to be the opening tag of the `caution` shortcode instead of the closing tag. This is the reason for the build failure ([refer build logs](https://app.netlify.com/sites/kubernetes-io-main-staging/deploys/673a0553cceb520008bbdf7e)). Changing the tag should resolve the build error!

```suggestion
{{< caution >}}
```

2024-11-17 17:34 UTC, Okabe-Junya requested changes
First of all, thank you for your contribution to k/website

In Japanese, spaces are not included between words.
Additionally, our project has a style guide, so please ensure that your translation adheres to it, particularly regarding the use of half-width and full-width characters, as well as long vowel marks.

FYI: https://kubernetes.io/ja/docs/contribute/localization/#style-guide

Since Kubernetes documentation is read by many Japanese speakers, l10n is a complex task.
Please make sure to work in the language you are most proficient in. 
(If you choose to move forward with this PR, refer to the style guide. If it is too difficult, feel free to close it.)

/hold

2024-11-17 17:58 UTC, luna029 commented
@Okabe-Junya 
Thank you for your confirmation.
This is our first submission. We apologize for any inaccuracies.
We have made several updates following the guidance below, including the points you mentioned.
We have referred you to other documents committed to the master branch for any unclear points.
We hope you will check them when you have a chance. Thank you in advance.

> 参考: https://kubernetes.io/ja/docs/contribute/localization/#style-guide

2024-11-19 04:06 UTC, Okabe-Junya commented
@t-inu 

こちらレビューいただくことはできますか？
自分の方でも確認してlgtm, approveできたらと思います

2024-11-21 07:05 UTC, t-inu commented
@luna029
I've reviewed until the "認証と認可" section.
Thereafter, please modify the followings first. Then I'll resume the review.
- pod -> Pod
- Remove spaces between words (except between English words)

2024-11-22 02:06 UTC, luna029 commented
@t-inu 
Thank you for pointing out some things.
My understanding has improved. Please let me correct it again. I plan to address it over the weekend.
I would also like to add the following translation guidelines along with example sentences to the points I have been pointed out.
https://kubernetes.io/ja/docs/contribute/localization/#style-guide
I appreciate your help.

2024-12-05 08:20 UTC, t-inu commented
@luna029
> Please let me correct it again. I plan to address it over the weekend.

Are you still working on the corrections for the “ネットワークセキュリティ” section and after?
Please let us know the status.

2024-12-10 13:18 UTC, luna029 commented
@t-inu 
I apologize for the delay.
I have updated it so I hope you will proceed with your review.

2024-12-12 13:49 UTC, t-inu reviewed
Reviewed the “ネットワークセキュリティ” section.

2025-01-04 17:18 UTC, Okabe-Junya commented
ping @luna029

Please take a look our review, thanks

2025-01-08 15:49 UTC, t-inu reviewed
Reviewed from the "Podセキュリティ" to the "Podの配置".

2025-01-08 15:49 UTC, t-inu commented on content/ja/docs/concepts/security/security-checklist.md
> +Podが誤って同じNodeにデプロイされるのを防ぐために、この分離を実施する必要があります。
```suggestion
アプリケーションPodとKubernetes APIサーバーなど、機密性の異なる層にあるPodは、別々のノードにデプロイする必要があります。
ノード分離の目的は、アプリケーションコンテナのブレイクアウトを防ぎ、より機密性の高いアプリケーションへのアクセスを直接提供して、クラスター内で簡単にピボットできるようにすることです。
Podが誤って同じノードにデプロイされるのを防ぐために、この分離を実施する必要があります。
```

2025-01-08 15:49 UTC, t-inu commented on content/ja/docs/concepts/security/security-checklist.md
> +: Pod仕様の一部として、デプロイするNodeを指定するキーと値のペア。
```suggestion
[ノードセレクター](/ja/docs/concepts/scheduling-eviction/assign-Pod-node/)
: Pod仕様の一部として、デプロイするノードを指定するキーと値のペア。
```

2025-01-08 15:49 UTC, t-inu commented on content/ja/docs/concepts/security/security-checklist.md
> +Namespace内のPodは、デフォルトおよび許可された一連のtolerationsを提供するNamespaceオブジェクトアノテーションキーで指定されたtolerationsのみを使用できます。
```suggestion
: 管理者がNamespace内で許可された[toleration](/ja/docs/concepts/scheduling-eviction/taint-and-toleration/)を制限できるようにするアドミッションコントローラー。
Namespace内のPodは、デフォルトおよび許可された一連のtolerationを提供するNamespaceオブジェクトアノテーションキーで指定されたtolerationのみを使用できます。
```

2025-01-08 15:49 UTC, t-inu commented on content/ja/docs/concepts/security/security-checklist.md
> +コンテナのランタイム構成は、Podのコンテナを実行するために使用され、パフォーマンスオーバーヘッドを犠牲にして、ホストからの分離を提供できます。
```suggestion
コンテナのランタイム構成は、Podのコンテナを実行するために使用され、パフォーマンスのオーバーヘッドを犠牲にして、多少なりともホストからの分離を提供できます。
```
> The container runtime configuration is used to run a Pod's containers and can provide more or less isolation from the host at the cost of performance overhead.

2025-01-14 04:07 UTC, t-inu reviewed
Reviewed it to the end.
I made many comments, most of them trivial.
I think it's translated well.

2025-02-07 13:38 UTC, Okabe-Junya commented
@luna029 

Please take a look ouer review, thanks!

2025-02-10 01:41 UTC, Okabe-Junya commented
/cc t-inu
/label tide/merge-method-squash
/unhold
/assign

2025-02-10 08:40 UTC, t-inu commented on content/ja/docs/concepts/security/security-checklist.md
> +- [ ] イングレスおよびエグレスネットワークポリシーは、クラスター内のすべてのワークロードに適用しています。
@luna029 Could you please apply this suggestion?

2025-02-12 12:21 UTC, t-inu reviewed
Thanks for your great contribution!
/lgtm

2025-02-13 06:17 UTC, Okabe-Junya reviewed
Thank you for your contribution!!

/approve

2025-02-13 06:20 UTC, merged